### ISSUE TITLE
HP:0010709 is ambiguous about whether cutaneous or osseus syndactyly

### ISSUE THREAD

**Issue by MickeySegal** [obophenotype/human-phenotype-ontology#10007]
**HPO term**
HP:0010709

**Suggested revision of textual definition**
It is ambiguous about whether it is referring to cutaneous or osseus syndactyly.  This should be clarified and if necessary, split.  Also, Apert syndrome has fingers 2-4 osseous syndactyly and isn't listed.

**Comment by pnrobinson** [comment]
@azankl
Looking at the syndactly terms, I am wondering if we should put all of them underneath cutaneous and osseous? Is it useful to have general terms like simply "2-4 finger syndactyly" or should be have everything be either one or the other?

**Comment by azankl** [comment]
@pnrobinson agree, everything should be either a form of cutaneous syndactyly or osseous syndactyly.

**Comment by pnrobinson** [comment]
For some of the terms, we will need to check the annotations.
**2-3 finger syndactyly**

- [ ] [OMIM:269500](https://hpo.jax.org/browse/disease/OMIM:269500)
Sclerosteosis 1
- [ ] [OMIM:149730](https://hpo.jax.org/browse/disease/OMIM:149730)
Lacrimoauriculodentodigital syndrome-1
- [ ] [OMIM:186550](https://hpo.jax.org/browse/disease/OMIM:186550)
Synostosis, carpal, with dysplastic elbow joints and brachydactyly
- [ ] [OMIM:225280](https://hpo.jax.org/browse/disease/OMIM:225280)
Ectodermal dysplasia, ectrodactyly, and macular dystrophy syndrome
- [ ] [OMIM:601707](https://hpo.jax.org/browse/disease/OMIM:601707)
Curry-Jones syndrome
- [ ] [OMIM:312870](https://hpo.jax.org/browse/disease/OMIM:312870)
Simpson-Golabi-Behmel syndrome, type 1
- [ ] [OMIM:603467](https://hpo.jax.org/browse/disease/OMIM:603467)
Fanconi anemia, complementation group F
- [ ] [OMIM:217085](https://hpo.jax.org/browse/disease/OMIM:217085)
Congenital heart defects, hamartomas of tongue, and polysyndactyly

**Comment by pnrobinson** [comment]
2-4 finger syndactyly
- [ ] [OMIM:617063](https://hpo.jax.org/browse/disease/OMIM:617063)
Meier-Gorlin syndrome 7
- [ ] [OMIM:225280](https://hpo.jax.org/browse/disease/OMIM:225280)
Ectodermal dysplasia, ectrodactyly, and macular dystrophy syndrome
- [ ] [OMIM:613573](https://hpo.jax.org/browse/disease/OMIM:613573)
Ectodermal dysplasia-syndactyly syndrome 1
- [ ] [OMIM:225060](https://hpo.jax.org/browse/disease/OMIM:225060)
Cleft lip/palate-ectodermal dysplasia syndrome
- [ ] [OMIM:107480](https://hpo.jax.org/browse/disease/OMIM:107480)
Townes-Brocks syndrome 1
- [ ] [OMIM:617746](https://hpo.jax.org/browse/disease/OMIM:617746)
Sweeney-Cox syndrome

**Comment by pnrobinson** [comment]
2-5 finger syndactyly HP:0010692
- [ ] 308050. -cutaneous

**Comment by pnrobinson** [comment]
4-5 finger syndactyly

- [ ] [OMIM:617201](https://hpo.jax.org/browse/disease/OMIM:617201)
Periventricular nodular heterotopia 7
- [ ] [OMIM:186100](https://hpo.jax.org/browse/disease/OMIM:186100)
Syndactyly, type III
- [ ] [OMIM:164200](https://hpo.jax.org/browse/disease/OMIM:164200)
Oculodentodigital dysplasia
- [ ] [OMIM:257850](https://hpo.jax.org/browse/disease/OMIM:257850)
Oculodentodigital dysplasia, autosomal recessive

**Comment by pnrobinson** [comment]
done
