### ISSUE TITLE
'abnormality of the digestive system' is classified as a neoplasm

### ISSUE THREAD

**Issue by sabrinatoro** [obophenotype/human-phenotype-ontology#10018]
The whole "abnormality of the digestive system" branch is incorrectly in the "neoplasm" branch of the ontology. 
![Screenshot 2023-08-29 at 10 30 11 AM](https://github.com/obophenotype/human-phenotype-ontology/assets/12737987/0b347da9-7fa8-46c2-89c2-6af67ea4512c)

**Comment by pnrobinson** [comment]
fixed by PR
