### ISSUE TITLE
Revise Offers Information (HP:5200113)

### ISSUE THREAD

**Issue by bcoleman96** [obophenotype/human-phenotype-ontology#10026]
**HPO term**
HP:5200113

**Suggested revision of textual definition**
New Label: Failure to offer information to initiate social interaction
Definition: The absence of the tendency to offer information as a means to initiate social interactions or direct another's attention.
Comment: This term refers specifically to offering information in order to initiate social interactions and should not be applied to a person who is reluctant to offer information when prompted.

**Comment by pnrobinson** [comment]
revised as suggested
