### ISSUE TITLE
Change Malabsorption from morphology to physiology

### ISSUE THREAD

**Issue by allenbaron** [obophenotype/human-phenotype-ontology#10028]
**HPO term**
Malabsorption ([HP:0002024](http://purl.obolibrary.org/obo/HP_0002024)

**Suggested revision and reasons**
1. Change superclass from 'Abnormal intestine morphology' ([HP:0002242](http://purl.obolibrary.org/obo/HP_0002242) to 'Abnormality of digestive system physiology' ([HP:0025032](http://purl.obolibrary.org/obo/HP_0025032)) because it is a physiological abnormality. _I chose 'Abnormality of digestive system physiology' as the new parent because I did not find 'Abnormality of intestine physiology'.

2. Consider revising textual definition & exact synonyms of 'Abnormal intestine morphology' since they are broader than it's logical definition and label
    - Definition: 'An abnormality of the intestine. The closely related term enteropathy is used to refer to any disease of the intestine.'
    - Synonyms:
        - 'abnormality of the intestine'
        - 'enteropathy'

**Related comment:**
This may not be the only physiological abnormality classified under morphology. I just noticed 'Abnormal stool composition' ([HP:0031685](http://purl.obolibrary.org/obo/HP_0031685)) is a child of 'Abnormality of digestive system morphology' ([HP:0025033](http://purl.obolibrary.org/obo/HP_0025033)).

**Comment by pnrobinson** [comment]
Thanks!
Sorry for the late response.
Moved malabsorption
as suggested.
Changed definition to 
A structural abnormality of the intestine.

At the end of the day, every abnormality has both morphological and physiological aspects. The distinction in the HPO is basically about how they are measured (one point in time vs over time). Therefore, the Stool composition terms should remain under morphology.
