### ISSUE TITLE
Consider renaming morphological abnormalities for consistency

### ISSUE THREAD

**Issue by allenbaron** [obophenotype/human-phenotype-ontology#10027]
_This is just a suggestion. Feel free to do with it what you will._

There are 15 morphological abnormalities in HP with labels that follow the pattern `Morphological abnormality of the <anatomy>` and 36 with the pattern `Abnormality of <anatomy> morphology>`. If there's not a specific reason for these differences it would be nice if they were renamed for consistency.

<details>

<summary>List of terms by pattern</summary>

**Begin with 'Morphological'**
- HP:0002011 'Morphological central nervous system abnormality'
- HP:0002062 'Morphological abnormality of the pyramidal tract'
- HP:0002492 'Morphological abnormality of the corticospinal tract'
- HP:0008609 'Morphological abnormality of the middle ear'
- HP:0011376 'Morphological abnormality of the vestibule of the inner ear'
- HP:0011380 'Morphological abnormality of the semicircular canal'
- HP:0011390 'Morphological abnormality of the inner ear'
- HP:0011391 'Morphological abnormality of the nerves of the inner ear'
- HP:0012718 'Morphological abnormality of the gastrointestinal tract'
- HP:0025445 'Morphological abnormality of the papillary muscles'
- HP:0040106 'Morphological abnormality of the lateral semicircular canal'
- HP:0040107 'Morphological abnormality of the posterior semicircular canal'
- HP:0040108 'Morphological abnormality of the anterior semicircular canal'
- HP:0040109 'Morphological abnormality of the utricle'
- HP:0040110 'Morphological abnormality of the saccule'

**End with 'morphology'**
- HP:0000525 'Abnormality iris morphology'
- HP:0002648 'obsolete Abnormality of calvarial morphology'
- HP:0002813 'Abnormality of limb bone morphology'
- HP:0002823 'Abnormality of femur morphology'
- HP:0002991 'Abnormality of fibula morphology'
- HP:0002992 'Abnormality of tibia morphology'
- HP:0003839 'Abnormality of upper limb epiphysis morphology'
- HP:0004362 'Abnormality of enteric ganglion morphology'
- HP:0005561 'Abnormality of bone marrow cell morphology'
- HP:0006344 'Abnormality of primary molar morphology'
- HP:0006482 'Abnormality of dental morphology'
- HP:0006500 'Abnormality of lower limb epiphysis morphology'
- HP:0010663 'Abnormality of thalamus morphology'
- HP:0011071 'Abnormality of permanent molar morphology'
- HP:0011121 'Abnormality of skin morphology'
- HP:0011138 'Abnormality of skin adnexa morphology'
- HP:0011472 'Abnormality of small intestinal villus morphology'
- HP:0011732 'Abnormality of adrenal morphology'
- HP:0011766 'Abnormality of the parathyroid morphology'
- HP:0011992 'Abnormality of neutrophil morphology'
- HP:0012443 'Abnormality of brain morphology'
- HP:0025028 'Abnormality of enteric nervous system morphology'
- HP:0025029 'Abnormality of enteric neuron morphology'
- HP:0025033 'Abnormality of digestive system morphology'
- HP:0025057 'Abnormality of olfactory lobe morphology'
- HP:0025163 'Abnormality of optic chiasm morphology'
- HP:0025361 'Abnormality of medullary pyramid morphology'
- HP:0025487 'Abnormality of bladder morphology'
- HP:0030495 'Abnormality morphology of the macular vasculature'
- HP:0030680 'Abnormality of cardiovascular system morphology'
- HP:0030935 'Abnormality of intestinal smooth muscle morphology'
- HP:0100016 'Abnormality of mesentery morphology'
- HP:0100734 'Abnormality of vertebral epiphysis morphology'
- HP:0410007 'obsolete Abnormality of cartilage morphology'
- HP:0410310 'Abnormality of neutrophil morphology in CSF'
- HP:3000034 'Abnormality nasal septum cartilage morphology'

</details>

**Comment by pnrobinson** [comment]
Thanks for this suggestion. 
The shortest label pattern would be **_Abnormal X morphology_** -- what do you think?

@matentzn can we script this?

**Comment by matentzn** [comment]
Great push, thanks a ton @allenbaron for the prod.

@pnrobinson check, but don't just merge, some labels lack a bit of elegance after the renaming: https://github.com/obophenotype/human-phenotype-ontology/pull/10029
