### ISSUE TITLE
rename HP:0034983

### ISSUE THREAD

**Issue by matentzn** [obophenotype/human-phenotype-ontology#10023]
From Pablo via email:

```
HP:0034983 Phenylephrine does not induce blanching of eye redness: the label "Phenylephrine does not induce blanching of eye redness" seems to be more an explanation than a term label. Is this label correct?
```

**Comment by pnrobinson** [comment]
@MickeySegal
I think this was intended to be a modifier. Can we provide more context?

**Comment by pnrobinson** [comment]
This is from https://omim.org/entry/619433, but I agree there is a mistake somewhere. I will follow up

**Comment by MickeySegal** [comment]
Normally, phenylephrine produces blanching of eye redness.  However, in some situations such as when the blood vessels are deep or the blood has escaped the vasculature, phenylephrine does not produce blanching.  

Often one would use a positive term such as "Phenylephrine induces blanching of eye redness" but this is the typical effect of phenylephrine and is present in a large fraction of people, e.g., those will allergies or upper respiratory illnesses.  This term was crafted in a negative form to represent the diagnostically important situation in which the commonly used phenylephrine test shows a result that is unusual.

I don't see the connection to the OMIM URL.

**Comment by pnrobinson** [comment]
@MickeySegal 
I renamed to 
Failure of phenylephrine to induce blanching of eye redness

the link to the OMIM was my mistake.
