### ISSUE TITLE
Reorganization of duplication of internal organs

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#10035]
**HPO term**
HP:0005217 duplication of internal organs. Needs a definition and children
Textual definition proposal: The duplication or partial duplication of one or more internal organs.
Logical definition proposal
'has part' some 
    (duplicated
     and (towards some 'abdominal segment of trunk)
     and ('has modifier' some abnormal))

Children:
HP:0012572 ureter duplex
HP_0000081 Duplicated collecting system
HP_0005223 Duplicated colon (no textual def)
HP_0030993 Duplicated pancreatic duct
HP_0005580 Duplicated renal pelvis (textual def is identical to label)
HP_0000075 Renal duplication
HP:0025489 Bladder duplication
HP:0011139 Gastric duplication
HP:0000073 Ureteral duplication
HP:0100681 Esophageal duplication
HP:0100668 Intestinal duplication
HP:0008738 Partially duplicated kidney
HP:0031922 Renal artery duplication
HP:0012885 Fallopian tube duplication
HP:0008706 Distal urethral duplication
HP:0033323 Glomerular capillary wall duplication with cellular interposition

**Suggested revision and reasons**
incomplete

**Comment by pnrobinson** [comment]
The logical definition seems fine. The English language definition should do more than restate the label. How about this: A congenital malformation characterized by the development of an additional organ or organ-like structure, i.e., an extra copy of the organ.

**Comment by pnrobinson** [comment]
@pnrobinson The annotations to this term are not all accurate.
 - [ ] Cornelia de Lange syndrome 1 -- not mentioned in OMIM, no PMID
 - [ ] Disorganization, mouse, homolog of -- possibly a legacy entry
 - [ ] Branchiooculofacial syndrome - -- not mentioned in OMIM, no PMID

**Comment by pnrobinson** [comment]
The only annotation that was valid was to DISORGANIZATION, MOUSE, HOMOLOG OF. THis is a borderline entry with no known etiology, but many papers, we will keep it for now. I updated the annotations.

**Comment by LCCarmody** [comment]
Sorry, I should have made it more clear, but the reason for this ticket is the label HP:0005217 Duplication of internal organs has no children. I am proposing asserting those children AND adding a logical definition to catch the terms that should be children under the this term.

**Comment by pnrobinson** [comment]
My problem is that probably what the authors meant was duplication of abdominal organ rather than internal organ. It is not very clear though and I am not certain this annotation is very valuable.

**Comment by pnrobinson** [comment]
Revised the label to

Abdominal organ duplication
def: A congenital malformation characterized by the development of an additional organ or organ-like structure, i.e., an extra copy of the organ normally located in the abdomen.

I removed the annotations from Cornelia de Lange syndrome 1 and Branchiooculofacial syndrome, because they were wrong. The other disease is probably legacy, but there are a few publications so let's leave it for now.
