### ISSUE TITLE
Peripheral neuropathy moved to morphology branch

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#10037]
**HPO term**
HP:0009830 Peripheral neuropathy is currently a child of Abnormal nervous system physiology 
Text Def: Peripheral neuropathy is a general term for any disorder of the peripheral nervous system. The main clinical features used to classify peripheral neuropathy are distribution, type (mainly demyelinating versus mainly axonal), duration, and course.

Comment: "Terms from this subhierarchy should be used to describe morphological abnormalities seen in peripheral neuropathy. Functional deficits should be coded separately."

Logical def: 'has part' some 
    (damaged
     and ('characteristic of part of' some 'peripheral nervous system')
     and ('has modifier' some abnormal))

**Suggested revision and reasons**
Text definition mostly describes morphology and EQ uses 'damaged' which is in the morphology portion of PATO.

Think it should be moved as a child to 'Abnormal peripheral nerve morphology'. If kept in physiology, it should also be child of 'Abnormal peripheral nerve physiology' (or that branch be rearranged)

Also, should remove that comment or use another annotation field as that shows up in OLS.
@sbello

**Comment by pnrobinson** [comment]
Clinically, peripheral neuropathy is most often diagnosed based on physiological tests rather than by judging the morphology. This is a borderline call but I think physiology makes most sense. I agree of course to move the term to Abn. peripheral nerve physiology. Not sure what the way forward is with PATO.

**Comment by pnrobinson** [comment]
@LCCarmody 
This term is under physiology. The definition of PATO "damaged" should probably be replaced by "malfunctioning"

**Comment by LCCarmody** [comment]
Hi @pnrobinson I don't think there is a term in Pato called 'malfunctioning'. Possibly we could request a new one, but the best fit under process that I can find is PATO:0015003 Decreased efficacy. It is defined as "A decrease in the ability of a process to produce its output."

**Comment by pnrobinson** [comment]
that is probably a reasonable term!

**Comment by pnrobinson** [comment]
I cannot find this term in the import. I will delete the definition for now. At some point we should do a workshop surrounding this.
