### ISSUE TITLE
Layperson synonyms not displayed in HPO browser

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#1007]
The HPO browser that is linked to the HPO website does not display the layperson synonyms:
http://compbio.charite.de/hpoweb/showterm?id=HP:0000118

For example, if I search for webbed toes, nothing comes up (but I see it in the owl file and in Bioportal)

Thanks!

**Comment by pnrobinson** [comment]
@nicolevasilevsky  @drseb @mellybelly Any progress on this? We should fix it priot to submitting the layperson paper -- it does not seem to be workingnow.

**Comment by drseb** [comment]
This would require to update the data used by HPO-Browser. This is related to the annotation-data problem (licensing).

**Comment by pnrobinson** [comment]
I think this has been addressed and I am closing this item.
