### ISSUE TITLE
Beta globulins

### ISSUE THREAD

**Issue by asmunduhreinn** [obophenotype/human-phenotype-ontology#1008]
Is it possible to add a terms for the different beta globulins

```
beta-2 microglobulin
plasminogen
angiostatins
properdin
sex hormone-binding globulin
transferrin
```

example 
Abnormal levels of beta-2-microglobulin in blood

**Comment by pnrobinson** [comment]
See #1017 for beta-2 microglobulin

**Comment by pnrobinson** [comment]
Plasminogen is under coagulation.

**Comment by pnrobinson** [comment]
I have added this grouping term. Plasminogen, beta-2 microglobulin, and transferrin are now there. I am going to create separate terms for  
angiostatins
properdin
sex hormone-binding globulin
