### ISSUE TITLE
Glycated hemoglobin

### ISSUE THREAD

**Issue by asmunduhreinn** [obophenotype/human-phenotype-ontology#1009]
I would like to request a term for glycated hemoglobin

**Comment by drseb** [comment]
any hints @mbrush ?

**Comment by pnrobinson** [comment]
This is the current term Increased HbA1c levels
see:
https://en.wikipedia.org/wiki/Glycated_hemoglobin
This term needs a definition and synonsms, and perhaps a better primary term name.
