### ISSUE TITLE
Label Complex Phenotypic Features/Diseases

### ISSUE THREAD

**Issue by bcoleman96** [obophenotype/human-phenotype-ontology#10096]
**Problem**
In theory, HPO terms should be clearly circumscribed only referring to a single phenotypic feature (even if it is broad). In practice, there are many terms that include multiple features that are disconnected except in that they often correlate. Autism (HP:0000717) is an example of a term created early in the development of HPO to fill a large gap in the absence of more granular terms, however, many of these terms still serve a practical purpose in that clinicians and researchers can use them to describe a common set of findings with multiple parts, e.g. Diabetes mellitus (HP:0000819) or Tetralogy of Fallot (HP:0001636). While there is a practical application of having these terms, their discontinuity with simpler and more typical HPO terms is a point of confusion for users and developers of the HPO who are instructed to treat the HPO as if such terms do not and cannot exist. I propose one of the following two solutions to allow us to keep these terms for practical use while maintaining the integrity of the HPO by indicating that these terms are an exception to the criteria that most HPO terms are intended to follow.

**Solutions**
1. Create a new boolean attribute/annotation for HPO terms called is_complex_feature that we can set to True for complex features. This will allow these complex terms to easily be filtered out when they are not desired for an analysis.
2. As an alternative, we could use the existing comment attribute to say that a feature is complex. This would need to be done the same way for all complex terms so that they can be filtered.

**Further considerations**
 Additionally, it may be beneficial to consider creating a set of rules that govern how complex features exist in the hierarchy. For example, we might consider saying that a complex feature should not have any children that are not also complex features. Theoretically, this is a given considering the true-path rule, but the use of complex terms seems to create confusion on how to apply this rule as I have seen several occurrences where a part of a complex feature is listed as a child term to the complex feature.

Another rule might be to say that a complex feature's parents should include all terms that it always includes as parts and no terms that it only sometimes includes as parts. Again, this is an extension of the true-path rule but still may serve to clarify its application.

**Comment by pnrobinson** [comment]
The suggestion of an annotation sounds good. However, we have to think hard about this because there are a range of individual cases to be considered. The word "complex" is overloaded in genetics and should be avoided in any case. This would be a good topic for an upcoming Monarch curation meeting. @moni

**Comment by pnrobinson** [comment]
This issue is too much for an issue, I am going to close it now. We may be able to begin to address this in a few years when Mondo has progressed more.
