### ISSUE TITLE
New synonym for HP_0003270 Abdominal distention

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#1010]
Ceri Van Slyke suggested we add 'bloating' as a layperson synonym for abdominal distention. I can add this if there are no objections.

**Comment by pnrobinson** [comment]
That sounds pretty good. Maybe we should say "Abdominal bloating"  (or both-- I think most people understand that bloating is about the abdomen).

**Comment by pnrobinson** [comment]
Synonyms added
