### ISSUE TITLE
Crocodile tears

### ISSUE THREAD

**Issue by carolina-f** [obophenotype/human-phenotype-ontology#10102]
**HPO term**
Gustatory lacrimation HP:0100274

**Synonym to be added**
crocodile tears

**broad/exact/narrow/plural/abbreviation ?**
PMID: 32491381 The word derives from ancient Greek, epifora: "epi" means "on," "upon," or "in addition" and "phérein," meaning "bring" or "carry." The literal meaning of the word epiphora is "to bring upon." This symptom is known to have been described in Egypt (1500 BC) and by Hippocrates (460 BC to 370 BC). Epiphora applies to excessive tearing caused by excessive tear production or secondary to poor drainage. Epiphora is sometimes subdivided into:
 -Gustatory epiphora ("**crocodile tears**" caused by aberrant nerve regeneration)
- Reflex epiphora (reactive tear production caused by any ocular surface trauma or stimulation)
- Obstructive epiphora (punctal, canalicular, lacrimal sac or lacrimal duct occlusion)
- Hypersecretory epiphora is the production of excessive tears. This is very rare.

PMID: 30247828 
The term "**crocodile tears**" is derived from the ancient belief that crocodiles weep after killing their victims. "crocodile tears syndrome," also known as Bogorad syndrome, is the shedding of tears while eating or drinking in patients recovering from Bell palsy. It is also referred to as gustatory lacrimation. This activity reviews the cause, pathophysiology, and presentation of crocodile tear syndrome and highlights the role of the interprofessional team in its management.

**Comment by pnrobinson** [comment]
Thanks!
Added synonym and PMID reference.
