### ISSUE TITLE
HP:0006397 on the blink

### ISSUE THREAD

**Issue by MickeySegal** [obophenotype/human-phenotype-ontology#10104]
**HPO term**
HP:0006397 Lateral displacement of patellae

**Bug description**
If you search HPO for "Lateral displacement of patellae" the search box shows HP:0006397, but selecting it leads to a page that loads only partially.  

The same happens from the link at https://www.ncbi.nlm.nih.gov/medgen/C1860156

**Comment by pnrobinson** [comment]
@MickeySegal 
Not sure what happened, but it seems to be working now:
https://hpo.jax.org/app/browse/term/HP:0006397

We have just upgraded the HPO webpage to have ten translations, and maybe this was a temporary network issue. Please let us know if this happens again and we will investigate!

**Comment by MickeySegal** [comment]
I haven't seen the problem on other occasions after the language feature was added, but I can confirm that the problem is gone in the instance that I flagged.
