### ISSUE TITLE
Pallhypesthesia as synonym of Impaired vibratory sensation

### ISSUE THREAD

**Issue by carolina-f** [obophenotype/human-phenotype-ontology#10129]
**HPO term**
Impaired vibratory sensation HP:0002495

**Synonym to be added**
A diminished sense of vibration is known as **pallhypesthesia.**
 Source: Campbell, W. W., & DeJong, R. N. (2013). DeJong's the neurologic examination. [electronic resource] William W. Campbell. Philadelphia, PA : Lippincott Williams & Wilkins, c2013.

To determine whether a patient has diminished or absent pallesthesia, testing can be conducted using a tuning fork at 128 Hz by placing it on the skin overlying a bone. This works because bones are good resonators of vibrations.
Source: Zankel, Harry (1969). "Pallesthesia Studies in Stroke Patients". Southern Medical Journal. 63 (1): 8–11. [doi]:[10.1097/00007611-196901000-00002](https://doi.org/10.1097%2F00007611-196901000-00002). [PMID][5766441](https://pubmed.ncbi.nlm.nih.gov/5766441)

PMID: 34994254: All patients with clinically defined polyneuropathy complained of sensory neuropathic symptoms (e.g. tingling, numbness, loss of balance/sensory ataxia). Ankle jerks were absent or decreased and **pallhypesthesia** (i.e. diminished sense of vibration) was noted in all patients with polyneuropathy

**broad/exact/narrow/plural/abbreviation ?**

**Comment by pnrobinson** [comment]
added synonym thanks!
