### ISSUE TITLE
Abnormal testis morphology (HP:0000035)

### ISSUE THREAD

**Issue by sbello** [obophenotype/human-phenotype-ontology#10139]
**HPO term**
Abnormal testis morphology (HP:0000035)

**Suggested revision and reasons**
This is currently a child of Non-obstructive azoospermia (HP:0011961) which is on the physiology branch. 

Based on the label I would have expected this term to be on the morphology branch. Although the definition 'An anomaly of the testicle (the male gonad).' could cover both morphology and physiology.

I would suggest revising the term to limit it to structural anomalies and changing the parent to Abnormal male internal genitalia morphology (HP:0000022).

**Comment by pnrobinson** [comment]
@sbello this was a mistake, thanks for picking it up. I have revised this section. Also, we have been trying to be more consistent in separating morphology and physiology, and I have revised some labels in the nearby hierarchy.
