### ISSUE TITLE
Retinal dystrophies

### ISSUE THREAD

**Issue by psergouniotis** [obophenotype/human-phenotype-ontology#1013]
Please consider adding "Achromatopsia [HP:0011516]" as a subclass of "Cone dysfunction syndrome [HP:0030637]". 

Also, some minor issues:
* Add "Rod cone dystrophy" as a synonym of "Rod-cone dystrophy [HP:0008036]"
* Add "Cone rod dystrophy" as a synonym of "Cone/cone-rod dystrophy [HP:0000548]"

Many thanks

Panos

**Comment by pnrobinson** [comment]
I have moved ther term "Cone dysfunction" to abn. of eye physiology. I have added the definition Cone dysfunction can be characterised by color vision abnormalities, central scotomata, and electrophysiological or psychophysical evidence of abnormal cone function. I have added subclasses and the synonyms.
