### ISSUE TITLE
Classical Ehlers Danlos Syndrome

### ISSUE THREAD

**Issue by andrewdevereau** [obophenotype/human-phenotype-ontology#1014]
Two terms have been requested for our phenotype model for Classical Ehlers Danlos Syndrome which i can't find in HPO. These are shown in the attached document. For the term 'susceptibility to blood vessel rupture', this can apply to any part of the body.

Andrew Devereau
Genomics England
andrew.devereau@genomicsengland.co.uk

[New term request for HPO - Ehlers Danlos Syndrome.docx](https://github.com/obophenotype/human-phenotype-ontology/files/415138/New.term.request.for.HPO.-.Ehlers.Danlos.Syndrome.docx)

**Comment by pnrobinson** [comment]
Added term for  subcutaneous spheroids (HP_0025014), definition:
Small, hard cyst-like nodules, freely moveable in the subcutis over the bony prominences of the legs and arms, which have an outer calcified layer with a translucent core on x-ray.

**Comment by pnrobinson** [comment]
I am going to add a term for capillary fragility and arterial rupture, I think these are the two items that go along with Ehlers Danlos syndrome in the way you intend.

**Comment by pnrobinson** [comment]
I have added an additional term Arterial rupture.
