### ISSUE TITLE
Non-syndromic familial congenital anorectal malformations

### ISSUE THREAD

**Issue by andrewdevereau** [obophenotype/human-phenotype-ontology#1015]
Here are some more requests for this disorder. One of them may be already described by an existing term.

Andrew
[New term request for HPO - Non-syndromic familial congenital anorectal malformations.docx](https://github.com/obophenotype/human-phenotype-ontology/files/415666/New.term.request.for.HPO.-.Non-syndromic.familial.congenital.anorectal.malformations.docx)

**Comment by andrewdevereau** [comment]
Further to the above, the term 'Vestibular fistula' should be 'rectovestibular fistula' which is distinct from rectovaginal and rectoperineal fistulas. References are http://www.ncbi.nlm.nih.gov/pubmed/16307276 and http://www.ncbi.nlm.nih.gov/pubmed/9694082

**Comment by pnrobinson** [comment]
Added Rectal atresia as HP_0025023

**Comment by pnrobinson** [comment]
Added megarectum as HP:0025024. Def: An abnormal dilation of the rectum. There is a large filled rectum as a result of underlying nerve supply abnormalities or muscle dysfunction, which remains after disimpaction  of  the  rectum.

**Comment by pnrobinson** [comment]
Added rectovestibular fistula as HP_0025025.
