### ISSUE TITLE
New term stats by branch

### ISSUE THREAD

**Issue by matentzn** [obophenotype/human-phenotype-ontology#10176]
@pnrobinson this table shows how many new terms have been generated per branch. Note that the numbers do not all add up due to multiple inheritance, but I used the HPO version we used for the paper.

| branch     | branch_label                                   | ct_new_terms |
|------------|------------------------------------------------|--------------|
| HP:0032443 | Past medical history                           | 58           |
| HP:0001574 | Abnormality of the integument                  | 105          |
| HP:0000152 | Abnormality of head or neck                    | 82           |
| HP:0012823 | Clinical modifier                              | 85           |
| HP:0001939 | Abnormality of metabolism/homeostasis          | 354          |
| HP:0000005 | Mode of inheritance                            | 13           |
| HP:0001871 | Abnormality of blood and blood-forming tissues | 62           |
| HP:0001507 | Growth abnormality                             | 2            |
| HP:0002664 | Neoplasm                                       | 60           |
| HP:0001197 | Abnormality of prenatal development or birth   | 99           |
| HP:0000478 | Abnormality of the eye                         | 28           |
| HP:0001626 | Abnormality of the cardiovascular system       | 154          |
| HP:0000118 | Phenotypic abnormality                         | 2069         |
| HP:0033127 | Abnormality of the musculoskeletal system      | 133          |
| HP:0002715 | Abnormality of the immune system               | 307          |
| HP:0025142 | Constitutional symptom                         | 18           |
| HP:0002086 | Abnormality of the respiratory system          | 154          |
| HP:0040064 | Abnormality of limbs                           | 43           |
| HP:0000119 | Abnormality of the genitourinary system        | 408          |
| HP:0000707 | Abnormality of the nervous system              | 339          |
| HP:0025354 | Abnormal cellular phenotype                    | 13           |
| HP:0000818 | Abnormality of the endocrine system            | 39           |
| HP:0045027 | Abnormality of the thoracic cavity             | 2            |
| HP:0000598 | Abnormality of the ear                         | 4            |
| HP:0025031 | Abnormality of the digestive system            | 98           |

**Comment by pnrobinson** [comment]
Thanks, closing!
