### ISSUE TITLE
Short attention span HP:0000736

### ISSUE THREAD

**Issue by kscott66** [obophenotype/human-phenotype-ontology#10179]
**HPO term**
Short attention span HP:0000736

**Synonym to be added**
Distractibility

**broad/exact/narrow/plural/abbreviation ?**
Unsure which this would be. 

GBC mania group came up with this suggestion because of the following item: 
11. Did you have more trouble than usual concentrating because your attention kept jumping from one thing to another?
Since the "Diminished ability to concentrate" term (HP:0031987) definition seemed to be referring to a single object/activity that required focus or concentration. The short attention span term includes distractibility in its definition, but the search function of HPO doesn't seem to include that information.

**Comment by pnrobinson** [comment]
@bcoleman96 
I added he two synonyms "High distractibility" and "Easy distractibility"
