### ISSUE TITLE
Disinhibition term - unintuitive hierarchy 

### ISSUE THREAD

**Issue by kscott66** [obophenotype/human-phenotype-ontology#10177]
**HPO term**
Disinhibition HP:0000734

**Suggested revision and reasons**
During the GBC/HPO workshop, the mania group identified an issue with the hierarchical structure leading to the "disinhibition" term. The item being mapped was: 

12. Did you do anything that could have gotten you into trouble like buying things, make business investments, have sexual indiscretions, drive recklessly?

This could be a single event experience by an individual, but disinhibition is a child term of "Recurrent maladaptive behaviour", which is may not always be true. Some sort of restructuring should be done to fix this. One suggestion may be moving disinhibition, perhaps up one level to have atypical behaviour as a parent term, since other terms under the recurrent maladaptive behaviour parent term (HP:5200241) seem to be correctly placed. 

In addition, under atypical behaviour, there is "Reduced impulse control" (HP:5200045) that seems to have a similar definition to disinhibition, and may be redundant in combination with the impulsivity term (HP:0100710).

**Comment by pnrobinson** [comment]
@bcoleman96 I guess that we need to say if [Disinhibition](https://hpo.jax.org/app/browse/term/HP:0000734) refers to one episode or to a tendency. The current definition implies a tendency -- Reduced ability to control, or a failure to resist a temptation, urge, or impulse. Examples include disregard for social conventions, general impulsivity, and poor risk assessment. 
So this seems reasonably OK, and I would suggest let's close this issue and we can revisit this at a future workshop -- once the rest of the hierarchy is fleshed out it may be more obvious if we need an additional term for a single episode.
