### ISSUE TITLE
Clarifying Anxiety Term/Creating New Term

### ISSUE THREAD

**Issue by bcoleman96** [obophenotype/human-phenotype-ontology#10172]
The term anxiety is currently placed and defined such that it involves an abnormal judgment of the environment. There needs to be a new term that only describes the emotion but does not include the emotion on it's own. There should be an abnormal fear term listed under abnormal emotion.

**Comment by pnrobinson** [comment]
@bcoleman96 
I am wondering if we should collect a list of items like this that seem to require group discussion. I do not think we can effectively work on difficult concepts like this via GitHub?

**Comment by bcoleman96** [comment]
I agree that this requires a specific discussion. The lists would be the terms under Abnormal emotion vs. those under Abnormal affect.

**Comment by pnrobinson** [comment]
I think the current placement is reasonable and this issue is too complicated to be resolved using GitHub issues. We will revisit this at one of the upcoming workshops.
