### ISSUE TITLE
Psychomotor slowing

### ISSUE THREAD

**Issue by bcoleman96** [obophenotype/human-phenotype-ontology#10173]
The term for decreased motivation is not really a good synonym for psychomotor slowing. Patients with psychomotor slowing may have normal motivation but are unable to perform the tasks that they are motivated to do because they are moving so slowly. Furthermore, it is not clear whether psychomotor slowing can be modulated by the will.

**Comment by bcoleman96** [comment]
Asthenia (HP:0025406) might be a good alternative

**Comment by pnrobinson** [comment]
Asthenia is general weakness, and although it probably overlaps in many cases, I do not think it is a synonym

**Comment by pnrobinson** [comment]
I am removing the psychomotor slowing synonyms and think the term is OK now. We can revisit later on if necessary.
