### ISSUE TITLE
abnormality of beta-2-microglobulin

### ISSUE THREAD

**Issue by slaulederkind** [obophenotype/human-phenotype-ontology#1017]
I would like to see "Abnormality of circulating beta-2-microglobulin level" added to the HP ontology under the parent term "Abnormality of circulating protein level" (HP:0010876). The definition could be "Abnormal concentration of beta-2-microglobulin in the blood". An example can be found in PMID:16166103. Synonyms would be "Abnormality of circulating B2M level", "Abnormality of circulating beta2m level",  "Abnormality of circulating beta2-m level", and  "Abnormality of circulating beta2 microglobulin level". 
I would also like to see "Increased circulating beta-2-microglobulin level" and "Decreased circulating beta-2-microglobulin level"  added to the HP ontology under the parent term "Abnormality of circulating beta-2-microglobulin level" (new term request).  The definitions could be "Decreased concentration of beta-2-microglobulin in the blood" and "Elevated concentration of beta-2-microglobulin in the blood".  Synonyms would be the "decreased" and "elevated" versions of the synonyms for "Abnormality of circulating beta-2-microglobulin level".

**Comment by pnrobinson** [comment]
Sorry for the delay, adding these terms.
