### ISSUE TITLE
Feature suggestion: Link ISBN-13 links in HPO Browser (hpo.jax.org) to information about the book

### ISSUE THREAD

**Issue by azankl** [obophenotype/human-phenotype-ontology#10184]
There are some HPO annotations that have a book identified through an ISBN-13 number as the source (e.g. metaphyseal widening in [Pseudoachondroplasia](https://hpo.jax.org/app/browse/disease/OMIM:177170). In the HPO browser at hpo.jax.org, these entries have 'ISBN-13' listed as the source and 'ISBN-13' is hyperlinked, but the link just does back to hpo.jax.org. Would be nice if it would link to some more information about the referenced book, for example using the Google API as described here:
https://gist.github.com/AO8/faa3f52d3d5eac63820cfa7ec2b24aa7

**Comment by pnrobinson** [comment]
@azankl nice idea
@iimpulse is this feasible
On the other hand, it would be even nicer to replace the ISBN with PubMed links because it is hard for most people to get a book just to look something up

**Comment by azankl** [comment]
Agree ideally all sources should be from Pubmed, but I think association taken from books can be very valuable, if it's a good book. That's why I would like to see what the ISBN number actually links to, to make sure it's a book I would trust.

**Comment by pnrobinson** [comment]
@iimpulse ping

**Comment by pnrobinson** [comment]
Looking at this again, less than 1% of entries have ISBN. I think we should instead get rid of the ISBNs and instead use PMIDs. There are several reasons we should do this, include FAIR ness (books are too expensive for many and difficult to consult if you need to have them right away) and precision -- books do not have frequency data, and almost all of the ISBN annotations are from the very first years of HPO. Let's not do this, and let's try to update ISBNs to PMIDs wherever possible!
