### ISSUE TITLE
decreased erythrocyte sedimentation rate

### ISSUE THREAD

**Issue by slaulederkind** [obophenotype/human-phenotype-ontology#1018]
I would like to see "Abnormality of erythrocyte sedimentation rate" added to the HP ontology under the parent term "Abnormality of metabolism/homeostasis" (HP:0001939). An example can be found in PMID:16166103. "Elevated erythrocyte sedimentation rate" (HP:0003565) would be moved to be a child term of the newly requested term.
I would also like to see "Decreased erythrocyte sedimentation rate" added to the HP ontology under the newly requested term "Abnormality of erythrocyte sedimentation rate".  A synonym would be "low erythrocyte sedimentation rate" and "low ESR".

**Comment by cmungall** [comment]
I'm just placing the term "bio assay ontology" into this ticket so it 
can be found later. Ideally we would link these terms directly to 
assays, eg.
https://en.wikipedia.org/wiki/Erythrocyte_sedimentation_rate
