### ISSUE TITLE
Phenopackets for DIGS

### ISSUE THREAD

**Issue by bcoleman96** [obophenotype/human-phenotype-ontology#10187]
This issue is to open a discussion about how to create phenopackets for DIGS. Below is an initial proposal. I will move this issue once a project page is created for this software.

# Temporal Structure
Certain sections of the DIGS refer to episodes. There are sets of questions that repeat for multiple episodes. One phenopacket should be created for each patient for each episode. This would be relatively easy to code and be advantageous in that we could easily compare patients based on a single episode category. The major disadvantage is that we would not have temporal resolution beyond the length of the episode. One way to partially solve this is to use clinical modifiers such as Mood congruent (#10171) to describe certain important temporal relationships.

# Clinical Modifiers
Clinical modifiers supply a level of flexibility which is helpful for specific contexts but can reduce interoperability when used excessively or inconsistently for larger projects. For this reason, we should clearly define the clinical modifiers that we plan to use for this project. Below is a list of some categories to include.

- **Triggered by:** The challenge here is that these relations may be wrong, but the DIGS asks about these relationships. It seems better to record them and decide later whether to use them rather than to not map them at all.
- **Mood congruence:** (#10171)
- **Severity:** This should be included if it can be recorded reliably.
- **Context:** It is unclear to me exactly how to do this, but it seems relevant to want to record certain environmental contexts such as the death of a family member.

# Logical Question Structuring
Certain questions are related and modify each other. Some patterns will need to be considered when mapping the DIGS.

### Screening Questions
There are several screening questions that are only intended to determine whether the following questions are relevant. For example, one question may ask whether a patient has had trouble falling asleep while the next asks if it has consistently taken the patient at least an hour to fall asleep. In this example, the initial screening question should be ignored and the phenotype should only be recorded if the second is true.

### Repeating Question Sets
Certain question sets will be repeated for different "episodes". It is important to ensure that these question sets are recorded in the same way. Each set should be included in a different phenopacket.

**Comment by pnrobinson** [comment]
Moving this here https://github.com/TheJacksonLaboratory/q2HPO/issues/9
