### ISSUE TITLE
Abnormal glial cell morphology 

### ISSUE THREAD

**Issue by sbello** [obophenotype/human-phenotype-ontology#10198]
**HPO term**
Abnormal glial cell morphology  (HP:0100705) 

**Suggested revision and reasons**
HPO has this placed under CNS but the definition is more general. The MP has terms for both CNS and PNS glial cells as well as a generic parent. Is the HPO term meant to be CNS specific or is it meant to be more general?

I think based on the child terms of the HPO term (specifically Abnormal Schwann cell morphology HP:0033035) this should be moved out to be a child on Abnormal nervous system morphology (HP:0012639) as Schwann cell in the CL is part of the peripheral nervous system.

**Comment by LCCarmody** [comment]
suggestion to change Abnormal glial cell morphology from 'Morphological central nervous system abnormality to 'Abnormal nervous system morphology' as parent. 

Astrocytes and  oligodendroglia are CNS specific, so we could make additional terms. @pnrobinson Preference?

**Comment by pnrobinson** [comment]
For now I have moved to Abnormal nervous system morphology. At some point we will have a workshop and can go over the entire hierarchy.
