### ISSUE TITLE
Two tooth fusion findings that seem disconnected in HPO

### ISSUE THREAD

**Issue by MickeySegal** [obophenotype/human-phenotype-ontology#10191]
**HPO term**
https://hpo.jax.org/app/browse/term/HP:0006315
https://hpo.jax.org/app/browse/term/HP:0011090
**Suggested revision and reasons**
https://hpo.jax.org/app/browse/term/HP:0006315 seems like a subset of https://hpo.jax.org/app/browse/term/HP:0011090, so it might make sense to include https://hpo.jax.org/app/browse/term/HP:0006315 also under https://hpo.jax.org/app/browse/term/HP:0011089
It may make sense to comment on whether the tooth fusion is with another tooth of the same type or a different type.

**Comment by pnrobinson** [comment]
[Solitary median maxillary central incisor HP:0006315](https://hpo.jax.org/app/browse/term/HP:0006315) -- I think that the etiology involves fusion of the precursors, this is not actually observed and I think the phenotypic appearance is different. The HPO tries not to encode etiology and instead just appearance, so I would suggest we keep these terms separate for now. The comment of the term explains this. The dental section of the HPO could probably use with a revision/workshop.
