### ISSUE TITLE
Abnormal sperm motility and child term organization

### ISSUE THREAD

**Issue by sbello** [obophenotype/human-phenotype-ontology#10197]
**HPO term**
Abnormal sperm motility (HP:0012206)

**Suggested revision and reasons**
This term is currently defined as 'An anomaly of the mobility of ejaculated sperm.' but has as synonyms Asthenospermia  and Asthenozoospermia. In the MP asthenozoospermia (MP:0002675) is defined as 'loss or reduction of the mobility of the spermatozoa, frequently associated with infertility'. In attempting to align these terms and their child terms I have several questions.

Should Asthenospermia  and Asthenozoospermia be synonyms of Reduced sperm motility (HP:0012207) rather than the parent term? Note that in the MP we have a term for abnormal sperm motility (MP:0002674) that seems like it would be an exact match the the HPO term Abnormal sperm motility but the MP term has both increased and decreased motility child terms.

The difference in text definitions for asthenozoospermia also means that the MP has immotile sperm as a child of this term while the HPO has Reduced sperm motility and Immotile sperm as siblings. So, even if the synonym Asthenozoospermia was moved down to reduced sperm motility these sets of terms would not align. The definition for asthenozoospermia in the MP comes from Stedman's 

Looking https://www.sciencedirect.com/topics/medicine-and-dentistry/asthenospermia I find various definitions:
"Asthenospermia is defined as <40% [sperm motility](https://www.sciencedirect.com/topics/medicine-and-dentistry/sperm-motility) or less than 32% with progressive motility"
"Asthenozoospermia is a condition characterized by reduced [sperm motility](https://www.sciencedirect.com/topics/medicine-and-dentistry/sperm-motility) (Coutton et al., 2015; Ray et al., 2017). Complete asthenozoospermia that shows 100% immotile [spermatozoa](https://www.sciencedirect.com/topics/medicine-and-dentistry/spermatozoon) is found at a frequency of 1 in 5000 men."

I think from this that immotile sperm should be a severe form of asthenozoospermia and fall under this term.

Suggested revision:
Move the synonyms Asthenospermia  and Asthenozoospermia to Reduced sperm motility
Make Immotile sperm a child of Reduced sperm motility

**Comment by pnrobinson** [comment]
@MagoWyr thoughts on the above?

**Comment by MagoWyr** [comment]
Hi, I think that both ways are possible. So overall I do not have any objections to this suggestion. Though I still recommend getting rid of the word "Asthenospermia" as this is just a wrong writing of "Asthenozoospermia".

**Comment by pnrobinson** [comment]
@MagoWyr  -- We keep the old terminology (Asthenospermia) because if we get rid of it, text mining will not work.
@sbello I have moved the synonyms as suggested, and moved immotile.
