### ISSUE TITLE
Finalize HPO Layperson synonyms paper

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#1019]
The draft of the paper is here: https://docs.google.com/document/d/1-pBqqZzmW_x02zwKmRtmR1Bbo3PSr-5r_ZqYHsQhUzs/edit 

Action items:
- [ ] @pnrobinson @drseb @cmungall @nicolevasilevsky we should first decide where we are sending it
- [ ] me, @mellybelly: revise the current draft
- [ ] @drseb need final figures (table with # of layperson terms added, etc. and information content)
- [ ] @cmungall automating checking of the synonyms
- [ ] all authors review the final draft

The final ICBO paper is attached,
[HPOSynonyms_ICBO_2016_Revisions_Final.pdf](https://github.com/obophenotype/human-phenotype-ontology/files/423446/HPOSynonyms_ICBO_2016_Revisions_Final.pdf)

**Comment by nicolevasilevsky** [comment]
@cmungall have you been able to do the automated checking of synonyms? Can I help?

**Comment by cmungall** [comment]
Not yet. It would not be hard to extend the DOSDP framework to do this, 
but not sure when I will have a chance

**Comment by nicolevasilevsky** [comment]
@cmungall what is the DOSDP framework? Is this the same thing as the google metrics thing you were doing?

Here are the comments that are on the manuscript draft:
![image](https://cloud.githubusercontent.com/assets/6722114/19284080/462bb6fc-8fa9-11e6-8160-339a24c7982a.png)

**Comment by cmungall** [comment]
On 11 Oct 2016, at 14:53, nicolevasilevsky wrote:

> @cmungall what is the DOSDP framework?

https://github.com/dosumis/dead_simple_owl_design_patterns

https://github.com/obophenotype/human-phenotype-ontology/pull/1028

> Is this the same thing as the google metrics thing you were doing?

Unrelated

**Comment by nicolevasilevsky** [comment]
Oh! I was meaning to ask about the google metrics thing, are you still doing that? I think @mellybelly wanted to get that done before finalizing the paper.

**Comment by cmungall** [comment]
Not yet run on all synonyms, but we have a subset

**Comment by nicolevasilevsky** [comment]
Cool. @mellybelly, do you think we need to run them all?
@cmungall can I help run them?

**Comment by cmungall** [comment]
You can only do 100/day unless you pay google. May be worth it.

https://github.com/monarch-initiative/layperson-synonyms/tree/master/synonym-frequency-analysis

**Comment by nicolevasilevsky** [comment]
Looks like you have results for about 8k (out of 12k) terms, is that right?

@mellybelly do you think it is worth it to pay google to expedite the remaining analysis? There are about 4k terms left, so it would take about another 40 days/1.5 months to complete. Maybe that is okay though, I'm not sure if we'll get this paper done much sooner than that anyway.

**Comment by cmungall** [comment]
Maybe let's see how meaningful the results we have are

**Comment by nicolevasilevsky** [comment]
Ok, what do we need to do to do that?

**Comment by nicolevasilevsky** [comment]
I reviewed the results from the google metrics. 

Of the 7,921 terms that were run through the google metrics, it looks like 6,301 had hits in google.
2,466 were layperson terms
3,835 were non-layperson terms

785 terms were layperson synonyms for non-layperson terms
Of this subset, only 125 (16%) of the layperson terms had more hits in google compared to the non-layperson term. (Assuming I did this analysis correctly), it looks like the layperson terms are less commonly used in google compared to the non-layperson term.

I shared my spreadsheet here: https://github.com/monarch-initiative/layperson-synonyms/blob/master/synonym-frequency-analysis/target/google-results_NV.xlsx

**Comment by nicolevasilevsky** [comment]
See related ticket: https://github.com/obophenotype/human-phenotype-ontology/issues/1007

**Comment by pnrobinson** [comment]
@nicolevasilevsky @drseb @mellybelly @jmcmurry @cmungall @markengelstad 
Hi everybody,
we really need to get this paper out asap, since we will not be able to start a snowball effect with this if we do not have adequate publicity. The manuscript seems to not be very active. What is the current status? What are the roadblocks? Is there any way of accelerating the progress?

**Comment by nicolevasilevsky** [comment]
Per our discussion on the phenotype editors call, @pnrobinson will create a google doc and draft an email to ask Nature Genetics if they would be interested in publishing a commentary or brief communication (see publication types here: http://www.nature.com/ng/authors/article_types/index.html)

**Comment by drseb** [comment]
Submitted
