### ISSUE TITLE
To add 'Abnormal Urinary color' as keyword to suggest Alkaptonuria

### ISSUE THREAD

**Issue by PierreGoyot** [obophenotype/human-phenotype-ontology#10204]
OMIM:203500 Alkaptonuria ORPHA:56 Alkaptonuria

 MONDO:0008753 Alkaptonuria

Alkaptonuria (AKU) is an autosomal recessive genetic disease with mutations causing the defect of the enzyme Homogentisate Dioxygenase (HGD) in the tyrosine degradation pathway which result in the toxic accumulation of Homogentisic Acid (HGA). This toxic accumulation from birth to life long results in clinical symptoms mostly in adult age 30-40 years old and is causing invalidated diseases mainly osteoarticular, often requiring joints replacements, but also cardiovascular, which are considered generally irreversible. 
Many affected individuals are asymptomatic and unaware of their condition until adulthood, however, HGA eliminated in high quantities in urines may be recognized early in infancy by dark-stained diapers, dark urine or urine that turns dark on standing, which is due to HGA being oxidized and alkaptonuria should be suspected in individuals with these clinical findings. (reference-1) 
Nevertheless when accessing the HPO Search by clinical signs and symptoms web page with Human Phenotype Ontology keywords: Dark urine (HP:0040319: Dark urine) or Abnormal urinary color (HP:0012086: Abnormal urinary color), alkaptonuria did not appear as a suggestion for rare disease. This may be an issue as these symptoms appear in children and may lead to the early diagnosis of AKU i.e.: before adulthood when symptoms reveal complicated/late stage of AKU, e.g.: In the group of 13 Caucasian children, all (100%) had dark urine from birth, and in most of them, it was a symptom that led to the diagnosis of AKU (Reference-2).
Also when accessing the HPO description of symptoms for Alkaptonuria, with the term name 'HP:0003593 Infantile onset', the corresponding PubMed reference (Reference-3) indicated that thirty-two patients out of 58 (55 percent) received the diagnosis of alkaptonuria because of dark urine,

Would you like to consider these symptoms to be added to HPO suggesting clinicians to identify alkaptonuria among possible rare diseases? 

Best regards

References:
1-Introne WJ, Perry M, Chen M. Alkaptonuria. 2003 May 9 [updated 2021 Jun 10]. In: Adam MP, Mirzaa GM, Pagon RA, Wallace SE, Bean LJH, Gripp KW, Amemiya A, editors. GeneReviews® [Internet]. Seattle (WA): University of Washington, Seattle; 1993–2023. PMID: 20301627.)
2-Kujawa MJ, Świętoń D, Wierzba J, Grzywińska M, Budziło O, Limanówka M, Pierzynowska K, Gaffke L, Grabowski Ł, Cyske Z, Rintz E, Rąbalski Ł, Kosiński M, Węgrzyn G, Mański A, Anikiej-Wiczenbach P, Ranganath L, Piskunowicz M. Clinical presentation of 13 children with alkaptonuria. J Inherit Metab Dis. 2023 Sep;46(5):916-930. doi: 10.1002/jimd.12647. Epub 2023 Jul 10. PMID: 37395296.
3-Phornphutkul C, Introne WJ, Perry MB, Bernardini I, Murphey MD, Fitzpatrick DL, Anderson PD, Huizing M, Anikster Y, Gerber LH, Gahl WA. Natural history of alkaptonuria. N Engl J Med. 2002 Dec 26;347(26):2111-21. doi: 10.1056/NEJMoa021736. PMID: 12501223.

**Comment by pnrobinson** [comment]
Thanks, I added the finding to the HPOA files for Alkaptonuria. This will be visible at the next release of the HPO in January.

**Comment by PierreGoyot** [comment]
Hi Peter, Thank you so much it is really appreciated. Best regards. Pierre
