### ISSUE TITLE
Microspherophakia (HP:0030961) 

### ISSUE THREAD

**Issue by sbello** [obophenotype/human-phenotype-ontology#10200]
**HPO term**
Microspherophakia (HP:0030961)  and Spherophakia (HP:0034375) and Microphakia (HP:0012376)

**Suggested revision of textual definition**
Several questions here.

I'm confused as to the distinction between Microspherophakia (HP:0030961)  and Spherophakia (HP:0034375). Spherophakia is defined as "..weak zonules around a smaller and more spherical crystalline lens..". The child term Microspherophakia is defined as "Lens of the eye is smaller than normal and spherically shaped." I don't see what is the distinctive characteristic of Microspherophakia that separates it from Spherophakia.

In terms of organization if Microspherophakia is a child of Spherophakia why isn't it also a child of Microphakia?

The definition of Microphakia is "Abnormal smallness of the lens." Given that the definition of Spherophakia includes that the lens is smaller shouldn't this also be a child of Microphakia?

The organization in the MP has small lens (MP:0001306) with the synonym microphakia and the child term spherophakia. If there is a reason why spherophakia should not be a child of small lens then I can revise the MP organization.

**Comment by pnrobinson** [comment]
Whereas the logical meanings of the terms are different, I am not sure they are truly different phenomena. @psergouniotis @sukram thoughts?

**Comment by pnrobinson** [comment]
Suggested revised definition of Microspherophakia:
Microspherophakia is a rare congenital anomaly characterized by the abnormal spherical shape of the crystalline lens. It is characterized by an increased anteroposterior thickness of the lens associated with reduced equatorial diameter. The primary pathology lies in the development of zonules. The condition is often bilateral and is characterized by small, thick, and spherical lenses.
PMID:[35015420](https://pubmed.ncbi.nlm.nih.gov/35015420)

**Comment by pnrobinson** [comment]
@sbello 
I removed the "smaller" from the definition of spherophakia. This "often" accompanies it but is not necessary for the definition. I also added the above improved definition of Microspherophakia
