### ISSUE TITLE
Typo in Comment

### ISSUE THREAD

**Issue by MickeySegal** [obophenotype/human-phenotype-ontology#10203]
**HPO term**
https://hpo.jax.org/app/browse/term/HP:0001978

**Bug description**
**SOme** pathological conditions...

Additionally, it would be good to say something about how this finding is assessed.  My understanding is that it is by some combination of imaging and biopsy, but I suppose seeing some of the immature cells in the blood could also be possible.

**Comment by pnrobinson** [comment]
Fixed! I added a little information to the comment about how this feature presents. I think that the diagnostic procedure depends on the location of the finding and on the clinical situation and it is difficult to summarize it in a short comment, but I added two PMIDs.
