### ISSUE TITLE
Inconsistent patterns for representing increased amount of moelcule X in anatomy Y

### ISSUE THREAD

**Issue by mbrush** [obophenotype/human-phenotype-ontology#1021]
@cmungall @drseb @nicolevasilevsky  
I am looking into how the molecular glyco-phenotype module we are developing will ultimately integrate with HPO, and noted an inconsistency in HPO related to describing abnormal amounts of some molecular entity in some anatomical entity.

For example: 
HP_0003074 ! hyperglycemia = 

```
 'has part' some 
    ('increased amount'
     and ('inheres in' some blood)
     and (towards some glucose)
     and ('has modifier' some abnormal)
     and ('has modifier' some pathological))
```

While HP_0010471 ! oligosacchariduria = 

```
'has part' some 
    ('increased amount'
     and ('inheres in' some 
        (oligosaccharide
         and ('part of' some urine)))
     and ('has modifier' some abnormal))
```

My recollection is that we are moving away from the former pattern, so I am guessing we would want to refactor hyperglycemia to use the latter pattern (inheres in some (glucose and part of some blood)).  Same for hypoglycemia - and any similar phenotypes that still use the 'towards' pattern. This would make things more consistent with the patterns we are using for the MGPO as well.

**Comment by nicolevasilevsky** [comment]
@mbrush Yeah I think the second pattern is the correct pattern. We do need to make things consistent, I am not sure what the plan is for that.

**Comment by drseb** [comment]
yap. @mbrush is right

**Comment by pnrobinson** [comment]
OK, I will add this to the wiki as our normative pattern for metabolic abnormalities!

**Comment by pnrobinson** [comment]
I am closing this item as I think we are in agreement and the description has been aded to the official documentation. @nicolevasilevsky please re-open if we do not have this decision documented anywhere.
