### ISSUE TITLE
abnormality of mucus secretion

### ISSUE THREAD

**Issue by slaulederkind** [obophenotype/human-phenotype-ontology#1022]
I would like to see "Abnormality of  mucus secretion from the nose” (new term) added to the HP ontology under the parent term “Abnormality of the nasal mucosa” (HP:0000433).  As a child term of the suggested new term, I would like to see “Increased mucus secretion from the nose” added to the HP ontology.  An example can be found in PMID:27475650.  A synonym would be "rhinorrhea”.

Also, I think “Increased circulating renin level” (HP:0000848) should be moved from being a child term of “Abnormality of renin-angiotensin system” (HP:0000847) to being a child term of “Abnormal circulating renin” (HP:0040084).  Thanks.

**Comment by slaulederkind** [comment]
This issue seems to have fallen through the cracks.

**Comment by pnrobinson** [comment]
Sorry for the long delay, there has been a large backlog since my relocation, slowly getting less.

**Comment by pnrobinson** [comment]
I have corrected the position of “Increased circulating renin level” (HP:0000848)

**Comment by pnrobinson** [comment]
Adding HP_0031416, Abnormal nasal mucus secretion
Def:Any deviation from the normal quantity of secretion of nasal mucus, a thick viscous liquid produced by the mucous membranes of the nose.
and child term
Rhinorrhea (I think this is probably the better label)...
I have placed the terms under the functional part of the respiratory subontology.
