### ISSUE TITLE
Reduced lactate dehydrogenase level

### ISSUE THREAD

**Issue by carolina-f** [obophenotype/human-phenotype-ontology#10239]
**HPO term**
Reduced lactate dehydrogenase B level HP:0045041

**Suggested revision of textual definition**

Searching for the term Reduced lactate dehydrogenase level, I found that the term in HPO is Reduced lactate dehydrogenase B level HP:0045041.
I wonder if it is correct to call it "B", since what I understand is that low levels of lactate dehydrogenase can be a consequence of a deficiency of one of the 2 enzymes.
Therefore, perhaps it would be more correct to make a term for the low level of LDH in serum, and create the terms LDH-A (M-subunit protein) deficiency and another for LDH-B (H-subunit protein) deficiency.

PMID: 32491468 The deficiency of the enzyme LDH is very rare, and not much data is available for its prevalence. This deficiency can result from either the mutations in the **LDHA gene** or the **LDHB gene** leading to a deficiency in LDH-A (M- subunit protein) and LDH-B (H-subunit protein) proteins, respectively.[[37]](https://www.ncbi.nlm.nih.gov/books/NBK557536/#) LDHA gene mutations result in the formation of an abnormal M subunit protein. This protein subunit cannot bind to other subunits to form the LDH enzyme.

LDHA gene mutation mostly affects skeletal muscles, because skeletal LDH has all M-subunits. However, a lack of a functional subunit reduces the amount of enzyme formed in all other tissues as well. This chemistry results in an ineffective breakdown of glycogen. Hence, LDHA gene deficiency is also called glycogen storage disease XI. The unavailability of sufficient energy, especially to the muscle cells, causes muscle weakness and breakdown of muscle tissue (rhabdomyolysis).[[38]](https://www.ncbi.nlm.nih.gov/books/NBK557536/#) The effect is more pronounced during strenuous activities, and muscle tissue destruction releases protein myoglobin. This protein is processed in the kidneys and released in the urine, causing myoglobinuria. The high accumulation of myoglobin protein can damage the kidneys, which can also lead to kidney failure. In some patients, LDHA deficiency causes skin rashes of varying severity.
On the other hand, **LDHB gene** mutations affect the heart muscle primarily because the heart LDH is made of all four H-subunits. In cardiac muscle, the involuntary muscle movement is fueled by the conversion of lactate to pyruvate through the LDH enzyme. Such conditions lead to a reduced LDH activity in cardiac muscle of patients with LDHB deficiency. Interestingly, no visible phenotype, signs, or symptoms are observed in such patients. Both LDHA and LDHB gene mutations have shown relevance in tumorigenesis.

Clinical Significance

(....)Abnormally low levels of LDH are very rare and usually not considered harmful.

And also I add this paragraph from the following link: https://my.clevelandclinic.org/health/diagnostics/22736-lactate-dehydrogenase-ldh-test

What does it mean if my LDH levels are low?

Having a lower-than-normal LDH test result is uncommon.

Lower-than-normal LDH levels may indicate a very rare genetic condition called lactate dehydrogenase A deficiency (glycogen storage disease XI) or lactate dehydrogenase B deficiency.

High vitamin C consumption can cause falsely low LDH test results.

**Comment by pnrobinson** [comment]
Thanks for pointing this out. I think the intention of the term was not to restrict to "B" -- the definition was: A decreased or reduced level of the enzyme lactate dehydrogenase in serum.

I am removing the B from the label, I think this was just a mistake.

We are also trying to make the term labels more uniform, so I am changing the label to 

Reduced circulating lactate dehydrogenase concentration

**Comment by carolina-f** [comment]
Thank you, I also think "Reduced circulating lactate dehydrogenase concentration" it's a more accurate term
