### ISSUE TITLE
LDH as synonim of lactate dehydrogenase

### ISSUE THREAD

**Issue by carolina-f** [obophenotype/human-phenotype-ontology#10238]
**HPO term**
Abnormal lactate dehydrogenase level HP:0045040
Increased circulating lactate dehydrogenase concentration HP:0025435

**Synonym to be added**
Abnormal LDH concetration HP:0045040

Increased circulating LDH concentration HP:0025435
Elevated serum LDH  HP:0025435

**broad/exact/narrow/plural/abbreviation ?**
LDH as synonim of lactate dehydrogenase

**Comment by pnrobinson** [comment]
added, thanks!
