### ISSUE TITLE
sneeze

### ISSUE THREAD

**Issue by slaulederkind** [obophenotype/human-phenotype-ontology#1023]
I would like to see "Sneeze” (new term) added to the HP ontology under the parent term “Functional respiratory abnormality” (HP:0002795).  The definition could be “A sudden violent, spasmodic, audible expiration of breath through the nose and mouth, especially as a reflex act” (Merriam-Webster).  An example can be found in PMID:15580493.

**Comment by drseb** [comment]
Sneezing is not abnormal, IMHO

**Comment by slaulederkind** [comment]
I guess "Cough" (HP:0012735) is abnormal.

**Comment by pnrobinson** [comment]
Well, a sneeze is abnormal in the sense that it is not the usual way we use our respiratory system. But there are instances when repeated sneezing is an important medical symptom, for instance:
http://www.ncbi.nlm.nih.gov/pubmed/17388999
Let us think a little bit if we need a small hierarchy of terms for sneeze, cough etc.
Ontologically, consider this: A heartbeat is not abnormal, but if their frequency is increased, you have tachycardia. The situation is (very roughly) analogous with sneezing.

**Comment by pnrobinson** [comment]
btw slaulederkind, could you send me your email address (peter.robinson@jax.org), I wanted to ask you something offline?
