### ISSUE TITLE
`Additional_Info_from_G_D_source` field missing from `genes_to_phenotype.txt`

### ISSUE THREAD

**Issue by asmvernon** [obophenotype/human-phenotype-ontology#10234]
Hi,
Up to release `v2023-01-27` we were retrieving `genes_to_phenotype.txt` and filtering out entries that had `Additional_Info_from_G_D_source=="question"`. However, this field was removed in all subsecuet releases and I haven't been able to find any info in the release notes. 

Can these values be found somewhere else, or if it has been dropped entirely, why is the case?

**Comment by pnrobinson** [comment]
@iimpulse  can you have a look?

**Comment by pnrobinson** [comment]
@iimpulse ping

**Comment by pnrobinson** [comment]
@asmvernon I am not really sure we can reproduce this. Could you provide a more concrete example of what is not working on your end?

**Comment by pnrobinson** [comment]
@asmvernon there have been a few changes to make the entire pipeline more efficient and we have added new documentation
http://obophenotype.github.io/human-phenotype-ontology/annotations/introduction/
Please open a new issue if you find an error. Sorry for the inconvenience, but the problem you saw may have occurred while we were transitioning scripts.
