### ISSUE TITLE
Add `HPOExplorer` to HPO tools documentation

### ISSUE THREAD

**Issue by bschilder** [obophenotype/human-phenotype-ontology#10231]
We'd like to request that our R package [`HPOExplorer`](https://github.com/neurogenomics/HPOExplorer) be added to [list of HPO tools on the dedicated docs site](https://obophenotype.github.io/human-phenotype-ontology/tools/).

You can see an overview of all its functionality here:
https://neurogenomics.github.io/HPOExplorer/reference/index.html

As well as an introductory tutorial:
https://neurogenomics.github.io/HPOExplorer/articles/HPOExplorer.html

Importantly, we've recently made changes so that it pulls HPO resources (e.g. the ontology OBO file, gene annotations) directly from the [obophenotype/human-phenotype-ontology Releases](https://github.com/obophenotype/human-phenotype-ontology/releases), ensuring tightly coordinated version control.

Finally, if you have a chance to try it out and have any suggestions for how to improve it further, please feel free to add an [Issue](https://github.com/neurogenomics/HPOExplorer/issues) or contribute directly via a [Pull Request](https://github.com/neurogenomics/HPOExplorer/pulls). 

Many thanks in advance!

The `HPOExplorer` team: @bschilder @NathanSkene @KittyMurphy

**Comment by pnrobinson** [comment]
That's awesome! We have been looking for R resources for the HPO. I added it to he docs page above, and we will be linking this page to the main HPO page to give it more visibility as soon as we have finalized the version 1. If you would like me to send around a paragraph about this package to the HPO mailing list, which has a few hundred subscribers, please send me a paragraph by email. @mellybelly

**Comment by bschilder** [comment]
@pnrobinson that would be amazing if you could advertise it! Here's a paragraph you could use:

> `HPOExplorer` is an R package with extensive functions for easily importing, annotating, filtering, and visualising the Human Phenotype Ontology at the disease, phenotype, and gene levels. By pulling fresh data directly from official resources like HPO, Monarch and GenCC, it ensures tightly controlled version coordination with the most up-to-date data available at any given time (with the option to use caching to boost speed). Furthermore, it can efficiently reorganise gene annotations into sparse matrices for usage within downstream statistical and machine learning analysis. The package is still actively evolving and growing. We are currently working on integrating additional Monarch resources like cross-ontology phenotype/disease ID mapping, as well as integrating uPheno for cross-species comparisons. Any suggestions are welcome and can be submitted as an Issue or Pull Request in the dedicated GitHub repo: https://github.com/neurogenomics/HPOExplorer 


As a side note @pnrobinson here is my ongoing work integrating uPheno resources to analyse cross-species ontologies.
- https://github.com/neurogenomics/RareDiseasePrioritisation/issues/33

Looping in @NathanSkene as well.

**Comment by bschilder** [comment]
> Sure -- just sent to this list https://groups.io/g/human-phenotype-ontology

Amazing, thanks so much!
I've also just updated the README on the landing page of `HPOExplorer` to provide better background on HPO.
