### ISSUE TITLE
Phenotypic abnormality is not an exclusive ancestor of the phenotypic features anymore

### ISSUE THREAD

**Issue by ielis** [obophenotype/human-phenotype-ontology#10242]
[*Maternal fever in pregnancy*](https://hpo.jax.org/app/browse/term/HP:0030244) is a subclass of both *Fever* and *Pregnancy history*.
However, *Pregnancy history* is not a descendant of *Phenotypic abnormality*. 

Some algorithms rely on all phenotypic features having *Phenotypic abnormality* as an exclusive common ancestor. However, with terms like:
- Maternal fever in pregnancy[HP:0030244]
- Maternal first trimester fever[HP:0030246]
- Maternal diabetes[HP:0009800]
- Intrapartum fever[HP:0030245]
- Maternal hyperphenylalaninemia[HP:0100610]
- Maternal seizure[HP:0100622] 

this is no longer the case.

I would like to ask if *Maternal fever in pregnancy* and the others are intentionally subclasses of *Pregnancy history* (having `is_a` relationship) or if this is a bug.

This was observed in `v2023-10-09`

Thank you!

**Comment by pnrobinson** [comment]
The maternal history basically means that we are focussing on a fetus or newborn and so observations in the mother are not phenotypic features of the index patient (the fetus or newborn)!

**Comment by ielis** [comment]
So this is how the hierarch will be from now on?

**Comment by pnrobinson** [comment]
As discussed these terms are for the past medical history!
