### ISSUE TITLE
Longevity

### ISSUE THREAD

**Issue by asmunduhreinn** [obophenotype/human-phenotype-ontology#1024]
I would like to request a phenotype for Longevity under the term "Age of death" (HP:0011420)

**Comment by pnrobinson** [comment]
So you basically mean an age of death that is very high or do you mean somebody who is very old but is still living? The HPO has a subclass structure, so we could not directly say that "longevity" is a subclass of "Age of death", but it would be possible to say that "death at age 120 years" is an "age of death", if you see what I mean. Could you describe your use case?

**Comment by pnrobinson** [comment]
I am closing this for now, reopen as needed
