### ISSUE TITLE
Localized osteoporosis - sub phenotypes

### ISSUE THREAD

**Issue by asmunduhreinn** [obophenotype/human-phenotype-ontology#1025]
I would like to request further sub phenotypes for "Localized osteoporosis" (HP:0040161)
For example Knee, fingers, hip, ankle, elbow etc.

**Comment by pnrobinson** [comment]
Sorry for this very late response. The difficult with making terms like this is that in principle we would have to make one term for each bone in the body, and perhaps even for each part of each bone. Ontologies are models (simplifications) of a domain. The rule has been to date that terms are added if they enable us to distinguish between diseases. Could I suggest that if you want to model localized osteoporosis, that you use the anatomic terms of uberon (see https://www.ebi.ac.uk/ols/ontologies/uberon) to record to location of the bones? If there are particular localized osteoporosis terms required for differential diagnosis, could I ask you to open specific term requests, please include a pubmed id or a reference! Thank you, and sorry again for this late response -- my relocation to the US last year has meant a large backlog.
