### ISSUE TITLE
Neurodermatitis and others as a synonym for atopic dermatitis

### ISSUE THREAD

**Issue by D0ctorNo** [obophenotype/human-phenotype-ontology#10254]
**HPO term**
HP:0001047 Atopic dermatitis

**Synonym to be added**
Neurodermatitis, Atopic eczema, Infantile eczema, Prurigo Besnier, Allergic eczema

**broad/exact/narrow/plural/abbreviation ?**
https://en.wikipedia.org/wiki/Atopic_dermatitis
https://www.mayoclinic.org/diseases-conditions/atopic-dermatitis-eczema/symptoms-causes/syc-20353273

**Comment by pnrobinson** [comment]
thanks @D0ctorNo I added these synonyms.
