### ISSUE TITLE
Review synonym types for some terms

### ISSUE THREAD

**Issue by sbello** [obophenotype/human-phenotype-ontology#10259]
MGI is trying to use synonym matches to expand the set of mapped MP to HP terms for use in the HMDC. In reviewing the potential matches I have questions about synonym types to some of the terms.

Google spreadsheet of terms and synonyms where I have questions or suggestions:
https://docs.google.com/spreadsheets/d/1bHlql8bSmVv7yr1fqTizGnyBGK8DZ2NPo9IGak-xGic/edit?usp=sharing

**Comment by pnrobinson** [comment]
Thanks for this. I have made most of the changes as suggested. In some cases, the synonyms reflect clinical usage, and I did not make the change. I added a column to the spread sheet with comments. Please open a new issue if anything requires additional discussion.
