### ISSUE TITLE
HP:5200420 Definition typo?

### ISSUE THREAD

**Issue by mirandajarnot** [obophenotype/human-phenotype-ontology#10261]
Found after insertion of HPO into the UMLS:

Delusion of love [HPO2023_10_09/PT/[HP:5200420]

HPO2023_10_09/PT|**A delusion is when** someone believes they are
    loved by another person, even though there is no evidence of
    this, and the person in question denies it.

I believe the "is" should be removed, because that broadens the meaning to any delusion rather than defining the specific delusion of love.

**Comment by pnrobinson** [comment]
Thanks! I updated the definition to

A delusion (a fixed false belief held despite evidence to the contrary) of being loved by another person, even though there is no evidence of this, and the person in question denies it.

@bcoleman96  -- please reopen if necessary
