### ISSUE TITLE
Spondyloepiphyseal dysplasia tarda is NOT a synonym for Spondyloepiphyseal dysplasia HP:0002655

### ISSUE THREAD

**Issue by azankl** [obophenotype/human-phenotype-ontology#10271]
**HPO term**
Spondyloepiphyseal dysplasia HP:0002655

**Bug description**
Spondyloepiphyseal dysplasia tarda is listed as a synonym. This is not correct. Spondyloepiphyseal dysplasia tarda is sometimes used to refer to a specific disease (X-linked Spondyloepiphyseal dysplasia tarda OMIM:313400), but the name is also used for a number of other diseases (OMIM:184100, OMIM:609223) and should therefore be avoided altogether. It is definitely NOT a phenotype.

My Orcid-ID: 0000-0001-8612-1062

**Comment by pnrobinson** [comment]
@azankl 
thanks for pointing out this error. I have fixed it.
At some point it would be great to revisit terms like this that can easily be confused with disease names. If you are going to be at ESHG or ASHG this year maybe we can have a short workshop?
