### ISSUE TITLE
Synonyms for Scissor gait

### ISSUE THREAD

**Issue by D0ctorNo** [obophenotype/human-phenotype-ontology#10275]
**HPO term**
HP:0012407 Scissor gait

**Synonym to be added**
Scissoring gait, Scissoring of the lower limbs, Scissoring of the lower extremities

**broad/exact/narrow/plural/abbreviation ?**
In addition to the synonyms to be added, the term HP:0001437 Abnormality of the musculature of the lower limbs could be added as a second superordinate term.

**Comment by pnrobinson** [comment]
added synonyms. The other term is meant to be morphology (structural) not functional. We will need to return to this topic  -- workshops with child neurologists will be carried out this year.
