### ISSUE TITLE
Fix spelling for and add definition for "Preferes being alone" (HP:5200110)

### ISSUE THREAD

**Issue by bcoleman96** [obophenotype/human-phenotype-ontology#10291]
**HPO term**
"Preferes being alone" (HP:5200110)

**Suggested revision of textual definition**
Change label to "Prefers being alone"

Add definition: A persistent desire for one to prefer to be alone rather than socializing with others.

Comment: This term should not be used to describe people who are socially isolated unless it is because of an expressed preference.

**Comment by pnrobinson** [comment]
@bcoleman96 
"Prefers to be alone" is not an unambiguous label 
What about "Marked preference for solitude" with the above definition and comment?

**Comment by pnrobinson** [comment]
@bcoleman96 
I changed the label and added the definition
A persistent desire for one to prefer to be alone rather than socializing with others. This feature may or may not be accompanied by a feeling of loneliness, which is a feeling of sadness because of lack of friends and company.
