### ISSUE TITLE
HP:0007443 Partial albinism vs HP:0007544 Piebaldism

### ISSUE THREAD

**Issue by kanems** [obophenotype/human-phenotype-ontology#10297]
**HPO term**
HP:0007443 Partial albinism vs HP:0007544 Piebaldism

**Reason for deprecation**
I am not sure if these are the same or not? (One issue from the lot on https://github.com/obophenotype/human-phenotype-ontology/issues/9626, splitting out so it can be managed separately)
Based on the definitions and synonyms in HPO, these non-pigmented patches have the same anatomical distribution possibility, same age of onset and are both stable. I do not see any other criteria that would differentiate them from one another. Perhaps the piebaldism concept should be treated as a synonym and merged into the other?

Suggested replacement or term to consider
It would seem one or the other should be used in HPO, unless they are different (in which case I will ask UMLS to split them out into separate CUIs)

**Comment by pnrobinson** [comment]
I do not think they are synonyms. Piebaldism is a bundled phenotype ( a characteristic pattern of white forelock and multiple symmetrical, irregularly shaped, white or depigmented macules). I think it is better to rename the term as below. I am also updating the definition.

id: HP:0007544
label: Piebald skin depigmentation
def: Congenital large depigmented (white) macule of irergular rhomboid shape. Piebald skin depigmentation generally presents with multiple such macules in the affected individual. There may be smaller (5-15mm), discrete, skin-colored and hyperpigmented macules interspersed within the depigmented macules.
Comment: Piebaldism (OMIM:172800) generally is characterized by both Piebald skin depigmentation and White forelock, which should be coded separately.

**Comment by kanems** [comment]
Thank you, I will bring this to UMLS so they can review their concept mapping.
