### ISSUE TITLE
HP:0006767 Pituitary prolactin cell adenoma vs HP:0040278 Prolactinoma

### ISSUE THREAD

**Issue by kanems** [obophenotype/human-phenotype-ontology#10296]
**HPO term**
HP:0006767 Pituitary prolactin cell adenoma vs HP:0040278 Prolactinoma

**Reason for deprecation**
I am not sure if these are the same or not? (One issue from the lot on https://github.com/obophenotype/human-phenotype-ontology/issues/9626, splitting out so it can be managed separately)

Based on the definitions in HPO, I cannot tell a difference in these two terms.

Suggested replacement or term to consider
It would seem one or the other should be used in HPO, unless they are different (in which case I will ask UMLS to split them out into separate CUIs)

**Comment by pnrobinson** [comment]
@kanems 
you are correct, theswe are synonyms.
We have kepüt the primary term

Pituitary prolactin cell adenoma
HP:0006767

the other term was merged into the above term and the synonym Prolactinoma was added.
