### ISSUE TITLE
HP:0000964 Eczema vs HP:0000976 Eczematoid dermatitis

### ISSUE THREAD

**Issue by kanems** [obophenotype/human-phenotype-ontology#10295]
**HPO term**
HP:0000964 Eczema vs HP:0000976 Eczematoid dermatitis

**Reason for deprecation**
I am not sure if these are the same or not? (One issue from the lot on https://github.com/obophenotype/human-phenotype-ontology/issues/9626, splitting out so it can be managed separately)

No definition is provided for eczematoid 
dermatitis, is it a dermatitis that looks like eczema but isn't? Seems unlikely given the structure in the ontology (it has 1 and only 1 parent). 

**Suggested replacement or term to consider**
It would seem one or the other should be used in HPO, unless they are different (in which case I will ask UMLS to split them out into separate CUIs)

**Comment by pnrobinson** [comment]
Thanks for pointing this out, I agree they are synonyms. I merged the terms.

HP:0000964 is now the primary term id with the primary label Eczematoid dermatitis, and synonyms including Eczema.
HP:0000976 is now an alternate id.
