### ISSUE TITLE
Abnormal morphology of erythroid precursors

### ISSUE THREAD

**Issue by slaulederkind** [obophenotype/human-phenotype-ontology#1029]
I would like to see "Abnormal morphology of erythroid precursors” (new term) added to the HP ontology either under the parent term “Abnormality of erythrocytes” (HP:0001877) or “Dysplastic erythropoiesis” (HP:0012134).  A synonym could be “Abnormal morphology of proerythroblasts”.  An example can be found in PMID:16098079.

**Comment by pnrobinson** [comment]
In terms of modelling I think it would be better to make this term a sibling.
In Cell Ontology, we see
** erythroid progenitor  cell (CL_0000038) Definition: A progenitor cell  committed to the erythroid lineage. 
and
**erythrocyte,
both of which are listed as children of erythroid lineage cell.
In the HPOwe have abnormality of cells of the erythroid lineage, so I will pop this new term into there.

**Comment by pnrobinson** [comment]
Also in Cell Ontology, proerythroblast is defined as " An immature, nucleated
  erythrocyte occupying the stage of erythropoeisis that follows
  formation of erythroid progenitor cells. This cell is
  CD71-positive, has both a nucleus and a nucleolus, and lacks
  hematopoeitic lineage markers."
This is distinct from erythroid progenitor cell. I will make two separate terms and define them accordingly.

**Comment by slaulederkind** [comment]
Hi Peter, Considering where you are putting the new term, you might want to look at the position of "Abnormal number of erythroid precursors" (HP:0012131).  Thanks.
