### ISSUE TITLE
HP:0011497 Iris neovascularization vs. HP:0025319 Rubeosis iridis

### ISSUE THREAD

**Issue by kanems** [obophenotype/human-phenotype-ontology#10298]
**HPO term**
HP:0011497 Iris neovascularization vs. HP:0025319 Rubeosis iridis

**Reason for deprecation**

I am not sure if these are the same or not? (One issue from the lot on https://github.com/obophenotype/human-phenotype-ontology/issues/9626, splitting out so it can be managed separately)

Several sources cited in UMLS treat these as synonyms, including SNOMED CT (51995000).  As does this relatively recent article in PubMedCentral: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5989268 
This less recent article also suggests that 'abnormal' iris neovascularization is disordered, supporting the merge of these concepts: https://pubmed.ncbi.nlm.nih.gov/17240254/ 

Suggested replacement or term to consider
It would seem one or the other should be used in HPO, unless they are different (in which case I will ask UMLS to split them out into separate CUIs)

**Comment by pnrobinson** [comment]
@kanems 
thanks for pointing this, they are indeed synonyms.
We are keepting this term

id: HP:0011497
label: Rubeosis iridis
synyonyms include Iris neovascularization

Note I kept the oldest term (smallest id) but switched the label.
