### ISSUE TITLE
HP:0009380 Aplasia of the fingers vs HP:0001180 Hand oligodactyly

### ISSUE THREAD

**Issue by kanems** [obophenotype/human-phenotype-ontology#10301]
**HPO term**
HP:0009380 Aplasia of the fingers vs HP:0001180 Hand oligodactyly

**Reason for deprecation**
(One issue from the lot on https://github.com/obophenotype/human-phenotype-ontology/issues/9626, splitting out so it can be managed separately)
I cannot, conceptually, see a difference in these terms. 
Children concepts to Hand oligodactyly seem to make sense as children  by aplasia of fingers if these two were merged and treated as synonyms.

Alternatively- if hand oligodactyly is redefined to include non-developmental causes for too-few digits, then it would not make sense to merge (but does HPO want to have concepts for acquired hand/foot oligodactyly?)

**Suggested replacement or term to consider**

**Comment by pnrobinson** [comment]
@kanems thanks for pointing this out. I agree they are synonyms.

I have merged the terms
The primary term is now
HP:0009380 
Note I updated the label of the term from "Aplasia of the fingers" to "Finger aplasia" because the latter seems more correct.
