### ISSUE TITLE
HP:0001302 Pachygyria vs. HP:0007227 Macrogyria

### ISSUE THREAD

**Issue by kanems** [obophenotype/human-phenotype-ontology#10300]
**HPO term**
HP:0001302 Pachygyria vs. HP:0007227 Macrogyria

**Reason for deprecation**
(One issue from the lot on https://github.com/obophenotype/human-phenotype-ontology/issues/9626, splitting out so it can be managed separately)
Based on the textual definitions and synonyms in HPO, these appear to be the same concept .

**Suggested replacement or term to consider**
It seems only one is needed of the above pair, other could be treated as a synonym?

**Comment by pnrobinson** [comment]
@DLewisSmith  is there a distinction between these two terms?

**Comment by pnrobinson** [comment]
Thanks @DLewisSmith 
I merged the terms keeping Pachygyria as the preferred term.
