### ISSUE TITLE
HP:0033919 Medial/intimal arcuate venulitis vs. HP:0033917 Arcuate intimal/medial venulitis

### ISSUE THREAD

**Issue by kanems** [obophenotype/human-phenotype-ontology#10303]
**HPO term**
HP:0033919 Medial/intimal arcuate venulitis vs. HP:0033917 Arcuate intimal/medial venulitis

**Reason for deprecation**
(One issue from the lot on https://github.com/obophenotype/human-phenotype-ontology/issues/9626, splitting out so it can be managed separately)
I am pretty sure these are the same concept. HP:0033917 textual definition specifies 'kidney' but  wikipedia says "The arcuate vein is a vessel of the renal circulation." so I don't see why these would need to be maintained as separate entries in HPO, it is only a variation in word order for the preferred name.

**Suggested replacement or term to consider**

**Comment by pnrobinson** [comment]
@kanems 
thanks for pointing this out, it was indeed an error.
We are keeping this term
Arcuate intimal/medial venulitis HP:0033917
the other term was merged.
