### ISSUE TITLE
HP:0008572 External ear malformation vs HP:0000356 Abnormality of the outer ear

### ISSUE THREAD

**Issue by kanems** [obophenotype/human-phenotype-ontology#10302]
**HPO term**
HP:0008572 External ear malformation vs HP:0000356 Abnormality of the outer ear

**Reason for deprecation**
(One issue from the lot on https://github.com/obophenotype/human-phenotype-ontology/issues/9626, splitting out so it can be managed separately)

Abnormality of the outer ear uses 'External ear malformations' as a synonym, suggests these two should be merged and treated as same concept.
(Again, unless the intent is have a space in HPO for acquired vs. congenital/developmental abnormalities, as  on #10301 , but if so that should be clarified in the textual definitions and relationships between terms)

**Suggested replacement or term to consider**
One or the other of the terms above would be fine, but I don't think both are needed.

**Comment by pnrobinson** [comment]
@kanems  Looking at the context and the annotations, External ear malformation HP:0008572 is actually a synonym of [Abnormal pinna morphology HP:0000377](https://hpo.jax.org/app/browse/term/HP:0000377) -- The definition was -  A malformation of the auricle of the ear. (auricle is a synonym for pinna). 


 I am thus merging HP:0008572 to HP:0000377,  The external ear includes more than the pinna, so I am moving the synonym to Abnormality of the outer ear HP:0000356

Note that we are trying to better separate morphology and physiology, so I am re-labeling HP:0000356 to Abnormal outer ear morphology
