### ISSUE TITLE
revise naming of febrile seizures?

### ISSUE THREAD

**Issue by azankl** [obophenotype/human-phenotype-ontology#10314]
The tree for febrile seizures currently looks like this:
<img width="486" alt="Screenshot 2024-02-15 at 12 38 13 pm" src="https://github.com/obophenotype/human-phenotype-ontology/assets/4812335/5ddce111-ed41-48fa-8adc-34a0f33aa885">

The names `Febrile seizure (within the age range of 3 months to 6 years)` and `Febrile seizure outside the age of 3 months to 6 years` struck we as odd, they are long and unwieldy. How about `typical febrile seizure` and `atypical febrile seizure` and explain in the definition what constitutes a typical vs atypical febrile seizure (which includes the age range, but also other things).

I would also rename the parent term`Seizure precipitated by febrile infection` to `febrile seizures`.

What do you think?

Andreas
Orcid 0000-0001-8612-1062

**Comment by pnrobinson** [comment]
@azankl  this nomenclature was discussed at length by this group
https://pubmed.ncbi.nlm.nih.gov/33949685/
While it is not concise, there is a lot of possibilities to confuse things in this field and so we decided to make the term labels be as unambiguous as possible!
thanks!
