### ISSUE TITLE
remove typo in HP_0020215 (Thinking-Induced Seizure)

### ISSUE THREAD

**Issue by azankl** [obophenotype/human-phenotype-ontology#10313]
**HPO term**
 HP_0020215 (Thinking-Induced Seizure)

**Bug description**
Current definition (IAO_0000115) reads:

`Seizures induced by thinking and decision-making. comment:`

The `comment:` bit at the end of the sentence should be removed.

ORCID-ID
0000-0001-8612-1062

**Comment by pnrobinson** [comment]
fixed! thanks
