### ISSUE TITLE
Aortic aneurysm HP:0004942

### ISSUE THREAD

**Issue by carolina-f** [obophenotype/human-phenotype-ontology#10315]
**HPO term**
Aortic aneurysm HP:0004942

**Suggested revision and reasons**
I found the article the definition is based on, and it says [doi: 10.1016/j.ijcha.2015.01.009 (2015)]:
"Definition of aortic aneurysm:
Published data on arteries diameter in healthy population are often scant or variable because of different imaging modalities used for measurement. Nevertheless, by common convention, **aortic dilatation** refers to a dimension that is greater than the 95th percentile for the normal person age, sex and body size. In contrast, an **aneurysm** is defined as a localized dilation of the aorta that is more than 50% of predicted (ratio of observed to expected diameter ≥1.5). Aneurysm should be distinguished from **ectasia**, which represents a diffuse dilation of the aorta less than 50% of normal aorta diameter.
(...)
**Dilatation of the ascending aorta** is a very indolent process as it takes many years to develop and it is asymptomatic initially. In patients who develop an ascending aortic aneurysm secondarily to a systemic disorder, signs of the primary disease are the ones who lead the clinician to look for the dilatation such as in Marfan syndrome. Otherwise, this pathology remains quiet until its catastrophic complications occur or when it is incidentally seen on cardiovascular imaging related to other causes. We can prevent these complications by screening asymptomatic patients. Feared events include aortic dissection or rupture, pericardial hemorrhage, cardiac tamponade and occlusion of aortic branches. In addition, some patients, in a lesser proportion, can also develop intramural hematomas or penetrating aortic ulcer".

As numerous publications show, the diameter of the aorta varies depending on sex, weight, height and especially age.

PMID: 34295712 "The accepted definition for an **aneurysm** is a permanent focal dilatation of an artery with a ≥50% increase in diameter compared to the expected normal diameter (2,15). **Ectasia** is defined as arterial dilatation <150% of the normal arterial diameter, while **arteriomegaly** is diffuse arterial dilatation involving several arterial segments, with an increase in diameter >50% compared to expected. **Aortic dilatation is a broader term which encompasses ectasia and aneurysm**. True thoracic aortic aneurysms involve all three layers of the aortic wall; 60% affect the aortic root and/or ascending aorta, 40% the descending aorta, 10% the arch, and 10% the thoracoabdominal aorta. Aneurysms may be fusiform or saccular in morphology"

PMID: 20233780 2010 ACCF/AHA/AATS/ACR/ASA/SCA/SCAI/SIR/STS/SVM Guidelines for the Diagnosis and Management of Patients With Thoracic Aortic Disease
**Aneurysm** (or true aneurysm): a permanent localized dilatation of an artery, having at least a 50% increase in diameter compared with the expected normal diameter of the artery in question. Although all 3 layers (intima, media, and adventitia) may be present, the intima and media in large aneurysms may be so attenuated that in some sections of the wall they are undetectable.
**Ectasia**: arterial dilatation less than 150% of normal arterial diameter. 
**Arteriomegaly**: diffuse arterial dilatation involving several arterial segments with an increase in diameter greater than 50% by comparison to the expected normal arterial diameter.

So, according to the publications, we can add the term **aortic ectasia**, and the classification would look like this:
Main term: Vascular dilatation HP:0002617
                          Child term: Aortic dilatation: refers to aortic diameter that is greater than the 95th percentile for the normal person age, sex and body size.
         Aortic dilatation child terms: Aortic Ectasia: arterial dilatation less than 150% of normal arterial diameter.
                                        Aortic aneurysm HP:0004942: a permanent localized dilatation of an artery, having at least a 50% increase in diameter compared with the expected normal diameter of the aorta and affecting all 3 layers.
                      Aortic aneurysm Child terms: Thoracic aortic aneurysm HP:0012727
                                              Abdominal aortic aneurysm HP:0005112

**Comment by pnrobinson** [comment]
@carolina-f the terms aneurysm, dilatation, ectasia are used inconsistently in the literature, and although there are articles that claim they are different, there are other articles that claim they are the same (aneurysm, dilatation). For this reason, at present, the HPO does not distinguish. It would be great to have a cardiovascular workshop to clarify these issues, but I do not think it is a good idea to do so without more input. Thoughts?

**Comment by pnrobinson** [comment]
I will close this for now, it is a difficult area and we would need to have a workshop with cardiologists to make progress.

**Comment by carolina-f** [comment]
I see, this is a difficult subject.
Do you have a date planned for the workshop?
