### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#1032]
ZuoFeng commented on the string "Multicystic dysplasia of the kidney is characterized by multiple cysts of varying size in the kidney and the absence of a normal pelvocaliceal system. The condition is associated with ureteral or ureteropelvic atresia, and the affected kidney is nonfunctional" from file hpo_notes.xliff in Chinese Simplified.
Comment: "pelvocaliceal should be pelvicaliceal"

**Comment by pnrobinson** [comment]
Good bug call!
