### ISSUE TITLE
Review if correct CHEBI terms are used and if these are the subclass relationship for 

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#10324]
**HPO term**
Parent: HP:0010918 Abnormal circulating cysteine concentration USES CYSTEINE
             child: HP:0500151 Hypercystinemia USES CYSTINE
             child: HP:0500152 Hypocystinemia USES CYSTINE

**Suggested revision and reasons**
I am not sure if these 2 terms are in the wrong place OR if the wrong compound is used for text def/logical def. In CHEBI, Cysteine and cystine are siblings and not a parent child relationship.

It looks as though I made the children terms (!!!) though I don't recall. Do we have any idea which term(s) are needed?

**Comment by pnrobinson** [comment]
Cystine is the [disulfide](https://en.wikipedia.org/wiki/Disulfide) derived from the amino acid [cysteine](https://en.wikipedia.org/wiki/Cysteine); I think there is an equilibrium between the two and measurements wind up measuring both at the same time.

**Comment by LCCarmody** [comment]
So do you want to change anything? Add to textual def and/or logical?

**Comment by pnrobinson** [comment]
I think it is correct as is.
