### ISSUE TITLE
Duplicate terms: Merge HP:0034933 to HP:0025550 Elevated circulating ribitol concentration

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#10322]
**HPO term**
Merge HP:0034933 Increased circulating ribitol concentration
 to HP:0025550 Elevated circulating ribitol concentration

**Reason for deprecation**
They are the same term.

**Suggested replacement or term to consider**
If @pnrobinson or @matentzn Or someone else knows how to replace terms in HP (it is different in MAXO) let me know. 

Is this up to date: https://github.com/obophenotype/human-phenotype-ontology/wiki/Obsoletion

**Comment by pnrobinson** [comment]
@LCCarmody 
Merged, keeping HP:0025550 as the surviving term
