### ISSUE TITLE
Duplicate terms? Merge HP:0034026 to HP:0034994

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#10323]
**HPO term**
HP:0034026 Elevated circulating sacchroropine concentration
HP:0034994 Elevated circulating saccharopine concentration

**Reason for deprecation**
These appear to be the same thing, but the first has a typo in the label. I still would merge to that term because it is (1) older (2) has a textual definition, but either way is fine. 
Also, fix typo.

**Suggested replacement or term to consider**

Let me know how want to handle it and I will make changes.

**Comment by pnrobinson** [comment]
thanks for finding this. Merged!
