### ISSUE TITLE
Add synonym to hyperextensibility wrists

### ISSUE THREAD

**Issue by lisannesw** [obophenotype/human-phenotype-ontology#10339]
**HPO term**
Hyperextensibility at wrists HP:0005072

**Synonym to be added**
Wrist hypermobility

**broad/exact/narrow/plural/abbreviation ?**

Andreas Zankl: 0000-0001-8612-1062, @azankl
Lisanne Wit: 0009-0007-1020-5412

**Comment by pnrobinson** [comment]
added thanks (I think this is a better primary label, so I changed it)
