### ISSUE TITLE
Add synonym wide cranial sutures

### ISSUE THREAD

**Issue by lisannesw** [obophenotype/human-phenotype-ontology#10342]
**HPO term**
Wide cranial sutures HP:0010537

**Synonym to be added**
Sutural diastasis, diastasis of cranial sutures

**broad/exact/narrow/plural/abbreviation ?**
exact

Andreas Zankl: 0000-0001-8612-1062, @azankl
Lisanne Wit: 0009-0007-1020-5412

**Comment by pnrobinson** [comment]
added, thanks!
