### ISSUE TITLE
Add synonym cleft earlobe

### ISSUE THREAD

**Issue by lisannesw** [obophenotype/human-phenotype-ontology#10343]
**HPO term**
Cleft earlobe HP:0011265

**Synonym to be added**
Bifid earlobe, notched earlobe (see https://onlinelibrary.wiley.com/doi/10.1002/ajmg.a.32599)

**broad/exact/narrow/plural/abbreviation ?**
exact

Andreas Zankl: 0000-0001-8612-1062, @azankl
Lisanne Wit: 0009-0007-1020-5412

**Comment by pnrobinson** [comment]
added, thanks!
