### ISSUE TITLE
add synonym camptodactyly fifth finger

### ISSUE THREAD

**Issue by lisannesw** [obophenotype/human-phenotype-ontology#10341]
**HPO term**
Contracture of the proximal interphalangeal joint of the 5th finger HP:0009185

**Synonym to be added**
Camptodactyly of 5th finger, camptodactyly of the fifth finger

**broad/exact/narrow/plural/abbreviation ?**

Andreas Zankl: 0000-0001-8612-1062, @azankl
Lisanne Wit: 0009-0007-1020-5412

**Comment by pnrobinson** [comment]
added, thanks!
