### ISSUE TITLE
Add synonym short humerus

### ISSUE THREAD

**Issue by lisannesw** [obophenotype/human-phenotype-ontology#10348]
**HPO term**
Short humerus HP:0005792

**Synonym to be added**
Rhizomelic arm shortening HP:0004991

**broad/exact/narrow/plural/abbreviation ?**
Exact

*Structural changes to the HPO hierarchy might be appropriate

@azankl

**Comment by pnrobinson** [comment]
@lisannesw @azankl

Usually the HPO tries to avoid bundled terms (i.e., terms that include more than one observation).
Rhizomelic arm means the humerus is short but the forearm is relatively normal.
Short humerus just means that the humerus is short and can be combined with terms such as Short radius.
Two questions:

- Is there something we can write in the comments of these terms to disambiguate?
- Is "Short humerus" the best term label? Maybe we should name the term Humerus hypoplasia as the main label?

**Comment by azankl** [comment]
Ok, in that sense, `Rhizomelic arm shortening` is a `narrow` synonym for `short humerus`, as its a bit more specific (implies that the rest of the arm is normal length). If there is a comment we can add to the  `is_narrow_synonym` statement, it could be "Rhizomelic arm shortening implies that the rest of the arm is normal length, while short humerus does not make that assumption".
I prefer `short humerus` to `humerus hypoplasia` as it emphasises the shortening, but dont really mind either way.

**Comment by pnrobinson** [comment]
OK!
