### ISSUE TITLE
Add synonym short femur

### ISSUE THREAD

**Issue by lisannesw** [obophenotype/human-phenotype-ontology#10347]
**HPO term**
Short femur HP:0003097

**Synonym to be added**
Rhizomelic leg shortening HP:0012106

**broad/exact/narrow/plural/abbreviation ?**
Exact

*Structural changes to the HPO hierarchy might be appropriate

@azankl

**Comment by pnrobinson** [comment]
This is not the same thing because rhizomelic implies that the lower leg is not short. I think they need to stay the same as is.

**Comment by azankl** [comment]
This is similar to [Add synonym short humerus #10348](https://github.com/obophenotype/human-phenotype-ontology/issues/10348). Could we make `rhizomelic leg shortening` a `narrow` synonym as its more specific (implies normal length of lower legs)?
