### ISSUE TITLE
Duplicate terms HP:0033444, HP"0033153

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#10356]
**HPO term**
HP:0033444, HP"0033153 Elevated circulating dodecanoylcarnitine concentration

**Reason for deprecation**

Duplicates
**Suggested replacement or term to consider**

**Comment by pnrobinson** [comment]
These are C12:0 and C12:1 -- not synonyms. I have added a new term, Elevated circulating C12 acylcarnitine concentration, and made both children, to make this easier. There is a very slight spelling difference.
