### ISSUE TITLE
Revise textual definition of Panniculitis ?

### ISSUE THREAD

**Issue by anna-anagnostop** [obophenotype/human-phenotype-ontology#10359]
Panniculitis [HP:0012490](https://www.informatics.jax.org/vocab/hp_ontology/HP:0012490)  is broadly defined as "Inflammation of adipose tissue", whereas panniculitis [MP:0011164 ](https://www.informatics.jax.org/vocab/mp_ontology/MP:0011164) specifically denotes "inflammation of the **_subcutaneous_** adipose tissue" and has recently been made a child of adipose tissue inflammation MP:0020386.

Moreover, panniculus adiposus is defined as "the fatty layer of the subcutaneous tissues", see [UBERON:0013488](http://www.ebi.ac.uk/ols4/ontologies/uberon/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_0013488). The DO and MONDO definitions are in agreement with the MP, see [DOID:1526](https://www.informatics.jax.org/vocab/mmxvii_disease_ontology/DOID:1526) and [MONDO:0006591](http://www.ebi.ac.uk/ols4/ontologies/mondo/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FMONDO_0006591).

Other sources I have checked specifically denote "inflammation of the **_subcutaneous_** adipose tissue , see:

[DermNet](https://dermnetnz.org/topics/panniculitis), [DynaMed](https://www.dynamed.com/condition/panniculitis#GUID-CE14D996-9F2C-470B-A76B-0804A66CAF7B), [PMID: 20666823](https://pubmed.ncbi.nlm.nih.gov/20666823/), [PMID: 27321570](https://pubmed.ncbi.nlm.nih.gov/27321570/), [PMID: 28844095](https://pubmed.ncbi.nlm.nih.gov/28844095/).

Should the HP definition be revised? see also old HPO ticket [#210](https://github.com/obophenotype/human-phenotype-ontology/issues/210).

Many thanks, 

Anna

**Comment by pnrobinson** [comment]
@anna-anagnostop thanks! You are correct, the word "subcutaneous" was missing. I have updated the definition and added citations.

**Comment by anna-anagnostop** [comment]
@pnrobinson Thank you! Best regards.
