### ISSUE TITLE
revise Pace of Progression (HP:0003679) subclasses

### ISSUE THREAD

**Issue by azankl** [obophenotype/human-phenotype-ontology#10354]
The current tree looks like this:
<img width="281" alt="Screenshot 2024-02-29 at 3 59 24 pm" src="https://github.com/obophenotype/human-phenotype-ontology/assets/4812335/1da403e3-b623-4950-b058-3f3ba53a31e0">
`Rapidly progressive`, `slowly progressive` and `variable progression rate` should all the subclasses of `Progressive`

Andreas Zankl
Orcid ID 0000-0001-8612-1062
@lisannesw

**Comment by pnrobinson** [comment]
thanks, fixed!
