### ISSUE TITLE
Hypoferremia as synonym of Decreased serum iron HP:0040303

### ISSUE THREAD

**Issue by carolina-f** [obophenotype/human-phenotype-ontology#10361]
**HPO term**
Decreased serum iron HP:0040303

**Synonym to be added**
Hypoferremia

**broad/exact/narrow/plural/abbreviation ?**
PMID: 36197985 Low plasma iron (**hypoferremia**) induced by hepcidin is a conserved inflammatory response that protects against infections but inhibits erythropoiesis

PMID: 36816471 In an inflammatory state, systemic iron homeostasis is dysregulated, commonly resulting in **hypoferremia**, or low serum iron.

**Comment by pnrobinson** [comment]
Thanks!
I also updated the label of this term to Decreased circulating iron concentration
