### ISSUE TITLE
Add synonym inverted triangular face

### ISSUE THREAD

**Issue by lisannesw** [obophenotype/human-phenotype-ontology#10368]
**HPO term**
Triangular face HP:0000325

**Synonym to be added**
Inverted triangular face

Explanation: triangular could be seen as a triangle with the point as top (Δ). This implicates that inverted triangle means the point is facing downwards (∇). This is consistend with the definition of triangular face. 

**broad/exact/narrow/plural/abbreviation ?**
exact

Andreas Zankl: 0000-0001-8612-1062, @azankl
Lisanne Wit: 0009-0007-1020-5412

**Comment by pnrobinson** [comment]
@lisannesw @azankl while this is logical, does anybody use this terminology? Otherwise it is just confusing. Could you provide a PMID?

**Comment by lisannesw** [comment]
@pnrobinson Sorry for not adding the PMID. PMID21166787 and PMID30515601 for example.

**Comment by pnrobinson** [comment]
OK, added!
