### ISSUE TITLE
Nasal speech subclass of "Abnormality of the soft palate"?

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#1036]
Nasal speech is defined as "A type of speech characterized by the presence of an abnormally increased nasal airflow during speech, **associated with incomplete or weak closure of the velum**". 

We do have  "Abnormality of the soft palate" (HP:0100736)

Question: should we assert that nasal speech is a subclass of "Abnormality of the soft palate"?

**Comment by pnrobinson** [comment]
In hindsight, I would say that the association with the velum is not 100%, and thus it is one of the possible causes of nasal speech. It might be better to move that part of the definition to the comment and say

Nasal speech may be associated with incomplete or weak closure of the velum.

**Comment by drseb** [comment]
ok. good that I asked. thanks
