### ISSUE TITLE
Add and change synonym short tubular bones of the hand

### ISSUE THREAD

**Issue by lisannesw** [obophenotype/human-phenotype-ontology#10371]
**HPO term**
Short tubular bones of the hand HP:0001248

**Synonym to be added**
Based on: Short long bone HP:0003026
Short long bones of the hand - Long bone shortening of the hand - Shortened long tubular bones of the hand

Comment: Long bones are also known as tubular bones. 

Current synonym (Shortened short tubular bones of the hand) seems to have a duplication of 'short' in, please adjust to 'shortened tubular bones of the hand' as 'short tubular bones of the hand' is the HPO term.

**broad/exact/narrow/plural/abbreviation ?**
Exact

Andreas Zankl: 0000-0001-8612-1062, @azankl
Lisanne Wit: 0009-0007-1020-5412

**Comment by pnrobinson** [comment]
added, thanks!
