### ISSUE TITLE
HPO Statistics for RPPR

### ISSUE THREAD

**Issue by matentzn** [obophenotype/human-phenotype-ontology#10381]
## GitHub statistics

From 2023-07-01 to 2024-06-30

| Event | Total | Internal | Internal (%) | External | External (%) |
| -------- | -------- | -------- | -------- | -------- | -------- |
| Contributors | 68 | 4 |  5.88 | 64 |  94.12 |
| Issues opened | 457 | 53 |  11.60 | 404 |  88.40 |
| Issues closed | 1239 | 1235 |  99.68 | 4 |  0.32 |
| Pull requests opened | 47 | 42 |  89.36 | 5 |  10.64 |
| Pull requests closed | 47 | 47 |  100.00 | 0 |  0.00 |
| Pull requests merged | 39 | 39 |  100.00 | 0 |  0.00 |
| Comments | 2460 | 1881 |  76.46 | 579 |  23.54 |
| Commits | 357 | 349 |  97.76 | 8 |  2.24 |
| Releases | 7 | 7 |  100.00 | 0 |  0.00 |

## Term statistics

- New classes: 1043
- Added text definition: 80
- Changed text definitions: 351
- Changed classifications: 267
- New synonyms: 450
- Renamed classes: 265
- Obsoletions: 31

**Comment by pnrobinson** [comment]
Thanks!
