### ISSUE TITLE
Suggestion: obsolete synonym 'spinal fusion'

### ISSUE THREAD

**Issue by peupeubangbang** [obophenotype/human-phenotype-ontology#10386]
**HPO term**
HP:0002948 Spinal fusion (SYNONYM)

**Reason for deprecation**
Spinal fusion is a well known surgical procedure term. I think having this in HPO may potentially confuse some people and software. 

It has created occasional issues when using annotation tools on clinical letters whereby the annotation software mines "spinal fusion" in text as a "HP:0002948 Vertebral Fusion" when in fact it's in reference to spinal fusion surgery for scoliosis in a Marfan's syndrome patient as an example.

**Suggested replacement or term to consider**
N/A

**Comment by pnrobinson** [comment]
I agree that is potentially confusing. 
I have updated the synonym name to
Congenital spinal fusion
thanks!
