### ISSUE TITLE
Should we add "en" language tags to all labels in HPO?

### ISSUE THREAD

**Issue by matentzn** [obophenotype/human-phenotype-ontology#10387]
Right now, we have about 1000 terms with an `@en` language tag.

EG

```
AnnotationAssertion(rdfs:label <http://purl.obolibrary.org/obo/HP_0025007> "Ectopic fovea"@en)
```

Either we 

1. Remove it everywhere
2. Add it everywhere

@pnrobinson what do you propose?

**Comment by pnrobinson** [comment]
I think the en tag is superfluous and would drop it.

**Comment by matentzn** [comment]
Ok! Sounds good. Finished with QC and all in https://github.com/obophenotype/human-phenotype-ontology/pull/10390
