### ISSUE TITLE
HP:0430110 Positive bloodstream Cysticercosis antigen test and HP:0430109 Positive bloodstream infectious agent antigen test

### ISSUE THREAD

**Issue by grahamponting** [obophenotype/human-phenotype-ontology#10395]
**HPO term**
HP:0430110 Positive bloodstream Cysticercosis antigen test and HP:0430109 Positive bloodstream infectious agent antigen test.
These two terms have been placed under HP:0500015 Abnormal cardiac test, which I think must be a mistake. The infection primarily affects other organs, such as the brain, not usually the heart.
The two terms should be moved to a more suitable parent such as HP:0031863 Bloodstream infectious agent.
Many thanks
Graham Ponting

**Comment by pnrobinson** [comment]
@pnrobinson 
I am not seeing this error on my side:
[Positive bloodstream infectious agent antigen test HP:0430109](https://hpo.jax.org/app/browse/term/HP:0430109)
Not sure what the problem could have been. If you continue to see this, please let us know what browser/version you are using.
thanks!

**Comment by grahamponting** [comment]
Hi Peter

Apologies, the error seems to relate to me using Protégé with an OWL  file link, which has been working well for me, but seems to have rendered the hierarchy incorrectly, and I presume there are other errors.
I will cross check more carefully in future.

Many thanks and apologies again.
Graham Ponting
