### ISSUE TITLE
Aldosterone levels on the loose

### ISSUE THREAD

**Issue by domibln** [obophenotype/human-phenotype-ontology#10392]
**HP:0040085: Abnormal circulating aldosterone** does not have any sub classes but should contain

- HP:0000859: Hyperaldosteronism 
(sub class of _Adrenal overactivity_)
- HP:0004319: Decreased circulating aldosterone level
(sub class of _Primary adrenal insufficiency_)

1. I think HP:0040085 should be added as a super class for both (the existing parents are absolutely valid).
2. Another term "increased circulating aldosterone level" might also be helpful to discriminate between classical hyperaldosteronism (adrenal glands release too much aldosterone) and increased levels (for whatever reason). This new term should **not** be a sub class of _Adrenal overactivity_.

**Comment by pnrobinson** [comment]
Thanks for pointing this out. I have implemented as suggested.
At a much earlier stage of HPO we decided to name the term for increased aldosterone concentration "Hyperaldosteronism" but this was suboptimal becase the latter is a bundled description. I have therefore changed the primary label to Increased circulating aldosterone concentration and added Hyperaldosteronism as a related synonym. The HPO does not model etiology and so it does not matter where the aldosterone is coming from.
