### ISSUE TITLE
HP:0430118 Positive skin fungus test,  and HP:0430117 Positive skin infectious agent test, wrong parent

### ISSUE THREAD

**Issue by grahamponting** [obophenotype/human-phenotype-ontology#10401]
HP:0430118 Positive skin fungus test,  and HP:0430117 Positive skin infectious agent test, wrong parent
These two terms are currently placed under  HP:0000818 Abnormality of the endocrine system, which I believe must be a mistake.
I suspect that was meant to be under **HP:0430030 Any kind of test for an infectious agent in a specimen positive**.

Graham Ponting

**Comment by pnrobinson** [comment]
Not sure, it looks as if the terms are placed correctly, either this was some error in an interim version or some other gremlin, biut it appears to be OK now. Thanks for reporting and for all of the other issues you have made!
