### ISSUE TITLE
Hand clenching synonims

### ISSUE THREAD

**Issue by carolina-f** [obophenotype/human-phenotype-ontology#10402]
**HPO term**
Hand clenching HP:0001188

**Synonym to be added**
Fisted hand
Fisting
Thumb clasp
Adducted thumb 

**broad/exact/narrow/plural/abbreviation ?**
PMID: 20301416 Infantile-onset Krabbe disease typically has four stages: Stage I. The infant, apparently normal for the first few months after birth, begins to cry frequently without apparent cause. Many keep their **hands tightly fisted**

 PMID: 27638597 Initial symptoms include crying/irritability, feeding difficulties, poor head control, ****fisted hand**s**, and loss of smiling.

PMID: 24384330 Subtle neurologic findings like shoulder girdle hypotonia and intermittent **thumb clasp** may be found (...) Overall, the most common presenting symptoms described by families of early-infantile Krabbe disease are crying and irritability (90%), stiffness (27%), poor feeding (27%), poor head control (25%), seizures (23%), **fisting** (18%), and loss of smiling (15%)

**Comment by pnrobinson** [comment]
@carolina-f 
I do not think  Adducted thumb is an exact synonym since it can occur without the fisting.
added the others.
