### ISSUE TITLE
Add definition radioulnar joint dislocation

### ISSUE THREAD

**Issue by lisannesw** [obophenotype/human-phenotype-ontology#10411]
**HPO term**
Radioulnar dislocation HP:0006439

**Suggested revision of textual definition**
The radioulnar joints are two locations, proximal and distal, in which the radius and ulna articulate in the forearm. Both can dislocate. 

**Comment** 
This term refers to when both radioulnar joints are dislocated or if it is unknown whether the distal or proximal joint was dislocated.

Andreas Zankl: 0000-0001-8612-1062, @azankl
Lisanne Wit: 0009-0007-1020-5412

**Comment by pnrobinson** [comment]
@lisannesw @azankl
thanks!
Updated to:
A dislocation is a separation of the radius and ulna bones where they normally meet. The radioulnar joints are two locations, proximal and distal, in which the radius and ulna articulate in the forearm. Both can dislocate.
Comment: This term refers to any kind of radioulnar joint dislocation (proximal, distal, both, or unknown).
