### ISSUE TITLE
Add parental term femur fracture

### ISSUE THREAD

**Issue by lisannesw** [obophenotype/human-phenotype-ontology#10418]
**HPO term**
Femur fracture HP:0031846

**Suggested revision and reasons**
Add 'Fractures of the long bones HP:0003084' as parent term, as it is a type of long bone fracture. 

Andreas Zankl: 0000-0001-8612-1062, @azankl
Lisanne Wit: 0009-0007-1020-5412

**Comment by pnrobinson** [comment]
The term Fractures of the long bones HP:0003084 is supposed to mean Recurrent long-bone fractures. The current hierarchy is a mistake, and there needs to be a term for a simple long-bone fracture.

**Comment by pnrobinson** [comment]
fixed!
