### ISSUE TITLE
HP:0000483 Astigmatism--revise textual definition AND remove logical definition

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#10429]
**HPO term**
HP:0000483 Astigmatism

**Suggested revision of textual definition**
Current: "A type of astigmatism associated with abnormal curvatures on the anterior and/or posterior surface of the cornea."

Proposed "A type of REFRACTION ERROR associated with abnormal curvatures on the anterior and/or posterior surface of the cornea AND LENS."

Reasons: First part seems to be a typo, but need to add Lens b/c otherwise this is the same definition as 'corneal astigmatism' and 'lenticular astigmatism' Is a child of astigmatism'.

ALSO: NEED TO REMOVE (or revise) the logical definition. As is, this would be the logical definition for defining it as morphology, which we will keep in the physiology branch.

**Comment by pnrobinson** [comment]
@LCCarmody Thanks for picking up the error, I revised the definition.
The logical definition is correct as far as i goes, just that this particular abnormal morphology is 100% tied to the abnormal physiology. I think it is probably OK to keep as is, and it wouldbe OK if anabnormal morphology of the cornea is also inferred.

```
'has part' some 
    ('asymmetrically curved'
     and ('characteristic of' some cornea)
     and ('has modifier' some abnormal))
```

**Comment by LCCarmody** [comment]
The problem is that it could be CORNEA or LENS. So it is incorrect and your description is 100% morphology...which causes a physiology change. We are also trying to be consistent with MP.

**Comment by pnrobinson** [comment]
I see what you mean, you are correct. Maybe we should just delete the defintion?

**Comment by LCCarmody** [comment]
Deleting would work. Thanks.

**Comment by pnrobinson** [comment]
deleted
