### ISSUE TITLE
Merge HP:0001900 Increased hemoglobin with HP:0020063 Increased hemoglobin concentration

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#10422]
**HPO term**
Merge HP:0001900 Increased hemoglobin with HP:0020063 Increased hemoglobin concentration

**Reason for deprecation**

These appear to be duplicate terms
**Suggested replacement or term to consider**

Found while working on patterns https://github.com/obophenotype/human-phenotype-ontology/issues/10391

**Comment by pnrobinson** [comment]
Merged
Main term is now

HP:0001900
Increased circulating hemoglobin concentration. (revised label)
