### ISSUE TITLE
Add synonym sacral appendage

### ISSUE THREAD

**Issue by lisannesw** [obophenotype/human-phenotype-ontology#10424]
**HPO term**
Caudal appendage HP:0002825

**Synonym to be added**
Sacral appendage
For example in: PMID: 18629881, PMID: 23904413, PMID18266249

**broad/exact/narrow/plural/abbreviation ?**
Exact

Andreas Zankl: 0000-0001-8612-1062, @azankl
Lisanne Wit: 0009-0007-1020-5412

**Comment by pnrobinson** [comment]
added thanks!
