### ISSUE TITLE
HP_0030680 Abnromality of cardiovascular morphology text definition

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#10426]
**HPO term**
HP_0030680 Abnromality of cardiovascular morphology text definition
Any structural anomaly of the heart and great vessels.

**Suggested revision of textual definition**

In this hierarchy, there are terms that include capillaries and 'not great vessels'. Could the text def be "Any structural anomaly of the heart and vessels."?

**Comment by pnrobinson** [comment]
yes, heart and blood vessels would be correct!

**Comment by pnrobinson** [comment]
fixed
