### ISSUE TITLE
Change parent term short proximal phalanx thumb

### ISSUE THREAD

**Issue by lisannesw** [obophenotype/human-phenotype-ontology#10423]
**HPO term**
Short proximal phalanx of thumb HP:0009638

**Suggested revision and reasons**
Short middle phalanx of finger HP:0005819 is parent term of Short proximal phalanx of thumb HP:0009638. However, the thumb does not have a middle phalanx and the HPO term states proximal phalanx. The correct parent term should be Short proximal phalanx of finger HP:0010241

Source: Moore, K. L., Dalley, A. F., & Agur, A. (2017). Clinically oriented anatomy (8th ed.). Lippincott Williams and Wilkins.

Andreas Zankl: 0000-0001-8612-1062, @azankl
Lisanne Wit: 0009-0007-1020-5412

**Comment by pnrobinson** [comment]
@azankl
@lisannesw 
I thought the proximal thumb phalanx was like the middle finger phalanges (embryological)? Is there an official classification for this?
