### ISSUE TITLE
Add synonym 

### ISSUE THREAD

**Issue by lisannesw** [obophenotype/human-phenotype-ontology#10420]
**HPO term**
Limb hypertonia HP:0002509

**Synonym to be added**
Appendicular hypertonia

**broad/exact/narrow/plural/abbreviation ?**
exact

Andreas Zankl: 0000-0001-8612-1062, @azankl
Lisanne Wit: 0009-0007-1020-5412

**Comment by pnrobinson** [comment]
@lisannesw added, thanks!
