### ISSUE TITLE
loss of appetite 

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1044]
Please consider new term for loss of appetite .

**Comment by pnrobinson** [comment]
I think you are referening to the current HPO term anorexia. If you think that this term requires more resolution, please submit a new term request. Anorexia is  HP_0002039

**Comment by LOURGHI** [comment]
I think  the clinician needs to have both terms loss of appetite and anorexia 
anorexia would be a loss of appetite that lasts over time and gives a weight loss
