### ISSUE TITLE
Rename pulmonary insufficiency

### ISSUE THREAD

**Issue by lisannesw** [obophenotype/human-phenotype-ontology#10444]
**HPO term**
Pulmonary insufficiency HP:0010444

**Suggested revision of textual definition**
The HPO-term might give the suggestion it is about the pulmonary system/lungs. However this is about the pulmonary valve. Could lead to confusion. Suggestion is to change the term to 'pulmonary valve insufficiency'. Pulmonary insufficiency could be added as synonym, or be removed. 

Secondly, there is a typo in the current synonym 'pulmonary valve insufficiency'

Andreas Zankl: 0000-0001-8612-1062, @azankl
Lisanne Wit: 0009-0007-1020-5412

**Comment by pnrobinson** [comment]
@azankl
thanks for the suggestion -- I relabeled the term as Pulmonic regurgitation and added Pulmonary valve insufficiency as a synonym.
