### ISSUE TITLE
Remove/change synonym fractured ankle

### ISSUE THREAD

**Issue by lisannesw** [obophenotype/human-phenotype-ontology#10443]
**HPO term**
Fractured ankle HP:0041153

**Bug description**
Synonym is 'bone ankle joint'. This does not sound like a synonym as there is no reference to fracturing only anatomical site. Please adjust to 'fractured bone ankle joint' or remove the synonym.

Andreas Zankl: 0000-0001-8612-1062, @azankl
Lisanne Wit: 0009-0007-1020-5412

**Comment by pnrobinson** [comment]
done!
