### ISSUE TITLE
Add synonym periosteal elevation

### ISSUE THREAD

**Issue by lisannesw** [obophenotype/human-phenotype-ontology#10449]
**HPO term**
Subperiosteal bone formation HP:0031485

**Synonym to be added**
Periosteal elevation

**broad/exact/narrow/plural/abbreviation ?**
Exact

Andreas Zankl: 0000-0001-8612-1062, @azankl
Lisanne Wit: 0009-0007-1020-5412

**Comment by pnrobinson** [comment]
added, thanks!
