### ISSUE TITLE
Revise definition bent long bone

### ISSUE THREAD

**Issue by lisannesw** [obophenotype/human-phenotype-ontology#10468]
**HPO term**
Bent long bone HP:0034530

**Suggested revision of textual definition**
The current definition: A developmental defect of a long bone, such as the femur or the humerus, characterized by a sharply curve deviation located in the metaphysis (shaft) of the bone.

Please revise 'metaphysis' to 'diaphysis', as this is the shaft of the bone and makes more sense to be bent/angulated. 

Andreas Zankl: 0000-0001-8612-1062, @azankl
Lisanne Wit: 0009-0007-1020-5412

**Comment by pnrobinson** [comment]
fixed, thanks!
