### ISSUE TITLE
pigmented spots on the tongue

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1046]
Please consider new term for pigmented spots on the tongue .

**Comment by pnrobinson** [comment]
It would be good to use more exact terminology. For instance,  lingual melanotic macule (http://www.ncbi.nlm.nih.gov/pubmed/12810508). We will consider some terms here, but describe what you want to annotate if you like!

**Comment by pnrobinson** [comment]
I would suggested using the current HPO term Intra-oral hyperpigmentation (HP_0010284). Please reopen the term if needed.
