### ISSUE TITLE
Add synonym cauliflower ear

### ISSUE THREAD

**Issue by lisannesw** [obophenotype/human-phenotype-ontology#10466]
**HPO term**
Crumpled ear HP:0009901

**Synonym to be added**
Cauliflower ear

Cauliflower deformity of the pinnae is a feature in 50-75% of the cases with diastrophic dysplasia.  The ear thickened, hardend and with irregular morphology.

Smithson S. (2019). Jürgen W. Spranger, Paula W. Brill, Christine Hall, Gen Nishimura, Andrea Superti-Furga, and Sheila Unger: Bone dysplasias: an atlas of genetic disorders of skeletal development: Fourth Edition, ISBN: 9780190626655. Human Genetics, 138(7), 787. https://doi.org/10.1007/s00439-019-02038-0

**broad/exact/narrow/plural/abbreviation ?**
Broad

Andreas Zankl: 0000-0001-8612-1062, @azankl
Lisanne Wit: 0009-0007-1020-5412

**Comment by pnrobinson** [comment]
added, thanks!
