### ISSUE TITLE
increased total iron binding capacity

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1047]
Please consider new term for increased total iron binding capacity.

**Comment by pnrobinson** [comment]
Definition: An elevation in the total-iron binding capacity, which measures how much serum iron is bound if an excess of radioactive iron is added. A high TIBC corresponds to a high transferrin concentration. The latent (or free) iron binding capacity is the difference between the TIBC and the measured serum iron, corresponding to the transferrin not bound to iron, i.e., free iron binding capacity.

Comment: Iron is transported to body tissues by a protein, transferrin, in plasma. This protein has two high-affinity binding sites for iron. Determination of total iron-binding capacity (TIBC) of the plasma therefore gives a measure of transferrin, although it can also be directly determined. Virtually all plasma iron (P1) normally is bound to transferrin, and measurement of P1 is assumed to reflect the amount of transferrin iron. The expression transferrin saturation, expressed as percent [(P1/TIBC) x 100], indicates the availability of iron to tissues. As transferrin saturation increases, there is an increase in the amount of diferric transferrin, which has a greater capacity to deliver iron than does monoferric transferrin. Measurements of P1, TIBC, and transferrin saturation have served several purposes in clinical medicine. The P1 concentration and (particularly) transferrmn saturation relect the adequacy of
iron supply. A saturation of less than 16% indicates a deficient iron supply, whereas a saturation of over 60% as measured on more than one occasion represents excessive iron loading owing to increased iron absorption or liver disease. An increased transferrmn concentration as
reflected in the TIBC indicates iron depletion if the effects of estrogen and
pregnancyare excluded. Other characteristic changes inboth P1 and  TIBC are useful in the
differential diagnosis of various diseases, for example, the decrease in transferrin saturations associated with a decreased transferrin concentration in inflammatory states.  
(from http://www.ncbi.nlm.nih.gov/pubmed/3542299)
