### ISSUE TITLE
HPO website - Profile search function - simple metrics?

### ISSUE THREAD

**Issue by peupeubangbang** [obophenotype/human-phenotype-ontology#10470]
This is very low priority, but is it possible to get some simple metrics on the number of diseases that have phenotype matches on the profile search page, or even be able to export the disease candidates into a csv?
https://hpo.jax.org/app/browse/profile-search

![MicrosoftTeams-image (29)](https://github.com/obophenotype/human-phenotype-ontology/assets/86904969/1de0c2c3-de3b-4718-8e00-32335dc0b524)

**Comment by pnrobinson** [comment]
@peupeubangbang  Moving this to the HPO Web tracker - https://github.com/TheJacksonLaboratory/hpo-web/issues/280
