### ISSUE TITLE
I suggest the term "Asymmetric blood pressure between limbs" as parent term of Blood pressure substantially higher in legs than arms HP:0020141, Blood pressure substantially higher in arms than legs HP:0020142, and Asymmetric blood pressure between arms (new term Issue )

### ISSUE THREAD

**Issue by carolina-f** [obophenotype/human-phenotype-ontology#10472]
**HPO term**
Blood pressure substantially higher in legs than arms HP:0020141
Blood pressure substantially higher in arms than legs HP:0020142

**Suggested revision and reasons**

Since in takayasu disease there can be a difference in blood pressure not only between arms and legs but also between both arms, I suggest the term "Asymmetric blood pressure between arms", and that the three terms as children of the term "Asymmetric blood pressure between limbs". "
Do you agree with this?

PMID: 34907753 Patients with TAK also show the following symptoms depending on the location of vascular changes – arthralgia, carotidinia, limb claudication, arterial bruit, headache, neurological symptoms, differences in arterial pressure between bilateral upper or lower limbs.

PMID: 30338248 Prevalence of dissection in childhood TA has been estimated at 11% (74). Discrepancy of any of four limbs blood pressure >10 mm Hg (which constitutes a classification criteria item) as well as bruits over aorta and its major branches are present in over 50% of patients.

**Comment by pnrobinson** [comment]
@carolina-f 
added as
HP:0025749
Asymmetric blood pressure between limbs

**Comment by pnrobinson** [comment]
@carolina-f 
also
HP:0025750
Asymmetric blood pressure between legs
