### ISSUE TITLE
HPO-Orphanet associations with conflicting excluded/included symptoms

### ISSUE THREAD

**Issue by schonbej** [obophenotype/human-phenotype-ontology#10478]
**HPO term**

<details><summary>Multiple (click to expand table)</summary>

orpha number | orpha title | hpo_parent_exclusion | hpo_children_inclusion
-- | -- | -- | --
64745 | Pruritic urticarial papules and plaques of pregnancy | Abnormality of the immune system | [Eczematoid dermatitis]
2848 | Camptodactyly-arthropathy-coxa-vara-pericarditis syndrome | Increased inflammatory response | [Pericarditis]
2177 | Hydranencephaly | Abnormality of vision | [Blindness]
254875 | Mitochondrial DNA depletion syndrome, myopathic form | Cognitive impairment | [Motor deterioration]
90349 | Autosomal recessive cutis laxa type 1 | Morphological central nervous system abnormality | [Microcephaly]
79319 | MPI-CDG | Abnormality of the nervous system | [Intellectual disability]
66529 | Tako-Tsubo cardiomyopathy | Abnormal coronary artery morphology | [Coronary artery stenosis, Coronary artery atherosclerosis]
398147 | Persistent idiopathic facial pain | Abnormality of the nervous system | [Acute episodes of neuropathic symptoms, Paresthesia, Somatic  sensory dysfunction, Anxiety, Impaired pain sensation, Depression,  Abnormal autonomic nervous system physiology]
79255 | GM1 gangliosidosis type 1 | Abnormality of extrapyramidal motor function | [Exaggerated startle response]
567544 | Idiopathic non-lupus full-house nephropathy | Autoimmunity | [Anti-dsDNA antibody positivity]
424 | Familial hyperthyroidism due to mutations in TSH receptor | Abnormal eye morphology | [Proptosis]
137605 | Legius syndrome | Neoplasm of the central nervous system | [Optic nerve glioma]
210272 | Mal de débarquement | Vestibular dysfunction | [Vertigo]
2752 | Orofaciodigital syndrome type 3 | Abnormality of the cardiovascular system | [Cherry red spot of the macula]
2752 | Orofaciodigital syndrome type 3 | Abnormal skeletal morphology | [Thoracic kyphosis, Short sternum, Postaxial hand polydactyly,  Pectus excavatum, Dandy-Walker malformation, Postaxial foot  polydactyly]
1991 | Cleft lip with or without cleft palate | Median cleft lip | [Median cleft lip and palate]
240094 | Progressive supranuclear palsy-pure akinesia with gait freezing syndrome | Abnormal saccadic eye movements | [Hypometric saccades]
79135 | Episodic ataxia type 3 | Headache | [Migraine]
79445 | Pseudopseudohypoparathyroidism | Abnormality of the endocrine system | [Elevated circulating parathyroid hormone level]
158676 | Localized dystrophic epidermolysis bullosa, nails only | Abnormality of skin morphology | [Fragile skin, Abnormal blistering of the skin]
324737 | SRD5A3-CDG | Abnormal hair morphology | [Hypertrichosis]
60039 | Pudendal neuralgia | Somatic sensory dysfunction | [Paresthesia]
60039 | Pudendal neuralgia | Neoplasm of the genitourinary tract | [Genital neoplasm]
2399 | Nasopalpebral lipoma-coloboma syndrome | Morphological central nervous system abnormality | [Microcephaly]
79409 | Recessive dystrophic epidermolysis bullosa inversa | Abnormality of the eye | [Corneal erosion]
3198 | Stiff person spectrum disorder | Abnormality of the nervous system | [Agoraphobia, Falls, Difficulty walking, Exaggerated startle response, Anxiety, Emotional lability]
206599 | Isolated asymptomatic elevation of creatine phosphokinase | Phenotypic abnormality | [Elevated creatine kinase after exercise, Elevated circulating creatine kinase concentration, Myopathy]
2688 | Adult idiopathic neutropenia | Abnormal neutrophil count | [Neutropenia]
2269 | Ichthyosis-alopecia-eclabion-ectropion-intellectual disability syndrome | Abnormality of the nervous system | [Spasticity, Intellectual disability, Absent speech,  Paraplegia, Delayed gross motor development, Unsteady gait,  Tetraplegia/tetraparesis, Seizure, Global developmental delay]

</details>

**Bug description**

Some associations of HPO terms with Orphanet diseases are contradictory given their hierarchy in the ontology. 
In the table above there are examples of HPO terms, which are exclusion criteria for a disease, but are parents of terms positively associated with the disease.

For example _Blindness_ is a very frequent clinical sign for [Hydranencephaly](https://www.orpha.net/en/disease/sign/2177), but _Abnormality of vision_ is an exclusion criterion.

**Comment by pnrobinson** [comment]
Since this is an issue specifically with ORPHA annotations, then please contact ORPHANET directly. We import their annotations but cannot ourselves modify the Orphanet data.
