### ISSUE TITLE
Add parent term to amelia involving upper limb

### ISSUE THREAD

**Issue by lisannesw** [obophenotype/human-phenotype-ontology#10481]
**HPO term**
Amelia involving the upper limbs HP:0009812

**Suggested revision and reasons**
Add transverse terminal upper limb defect (#10328) as parent term to amelia involving the upper limb.
Based on the classification of Frantz and O'Rahilly amelia is a form of transverse terminal limb defect.  (Frantz, C. H., and Ronan O'Rahilly, Congenital skeletal limb deficiencies, J. Bone & Joint Surg., Boston, 43A:1202-1224, December 1961.)

Andreas Zankl: 0000-0001-8612-1062, @azankl
Lisanne Wit: 0009-0007-1020-5412

**Comment by pnrobinson** [comment]
done
