### ISSUE TITLE
Add parent term to absent hand

### ISSUE THREAD

**Issue by lisannesw** [obophenotype/human-phenotype-ontology#10483]
**HPO term**
Absent hand HP:0004050

Suggested revision and reasons
Add transverse terminal upper limb defect (https://github.com/obophenotype/human-phenotype-ontology/issues/10328) as parent term to absent hand.
Based on the classification of Frantz and O'Rahilly acheiria is a form of transverse terminal limb defect. (Frantz, C. H., and Ronan O'Rahilly, Congenital skeletal limb deficiencies, J. Bone & Joint Surg., Boston, 43A:1202-1224, December 1961.)

Andreas Zankl: 0000-0001-8612-1062, @azankl
Lisanne Wit: 0009-0007-1020-5412

**Comment by pnrobinson** [comment]
done
