### ISSUE TITLE
Change Label of Abnormal affect to Abnormal demeanor (HP:5200261)

### ISSUE THREAD

**Issue by bcoleman96** [obophenotype/human-phenotype-ontology#10491]
**HPO term**
Abnormal Affect (HP:5200261)

**Suggested revision of textual definition**
As discussed at the Budapest workshop, this term was mislabeled. We should correct it and create a new term for Abnormal affect. I wanted to highlight this now to avoid confusion when we revise the affect hierarchy.

**Comment by pnrobinson** [comment]
Just to be clear, we mean
1. Relabl the current Abnormal affect term to abnormal demeanor 
2. Create a new Abnormal affect term?

**Comment by bcoleman96** [comment]
Yes, but we should the first immediately and wait on the second until we consult Melvin/do it with the bulk revision.

**Comment by pnrobinson** [comment]
done
