### ISSUE TITLE
To add synonym for 'Specific learning disability' (HP:0001328)

### ISSUE THREAD

**Issue by jagcsun** [obophenotype/human-phenotype-ontology#10490]
**HPO term**
Specific learning disability (HP:0001328)

**Synonym to be added**
Dyspraxia,
Specific learning difficulty, 
Developmental coordination disorder (DCD)

**broad/exact/narrow/plural/abbreviation ?**
DCD

**To comment**
Additional comments: Dyspraxia vary with age and development, and may have difficulties in academic, social, emotional, organizational and coordination skills (PMID: 29159933 and 33559779)

**Comment by jagcsun** [comment]
Abbreviations: SpLD/SpLDs

**Comment by pnrobinson** [comment]
Dyspraxia can be considered a specific type of Specific learning difficulty but it is not a synonym.
The differences between Apraxia and Dyspraxia are not well delineated in the literature. 
We are planning a workshop on this, I will close for now since this needs a bigger context!
