### ISSUE TITLE
Add parent terms to adactyly

### ISSUE THREAD

**Issue by lisannesw** [obophenotype/human-phenotype-ontology#10492]
**HPO term**
Adactyly HP:0009776

**Suggested revision and reasons**
Add transverse terminal lower limb defect (#10480) and transverse terminal upper limb defect (#10328) as parent term to adactyly.
Based on the classification of Frantz and O'Rahilly adactyly is a form of transverse terminal limb defect. (Frantz, C. H., and Ronan O'Rahilly, Congenital skeletal limb deficiencies, J. Bone & Joint Surg., Boston, 43A:1202-1224, December 1961.)

Andreas Zankl: 0000-0001-8612-1062, @azankl
Lisanne Wit: 0009-0007-1020-5412

**Comment by pnrobinson** [comment]
done
