### ISSUE TITLE
Merging dislocation of the femoral head and hip dislocation

### ISSUE THREAD

**Issue by lisannesw** [obophenotype/human-phenotype-ontology#10508]
**HPO term**
Dislocation of the femoral head HP:0008826

**Reason for deprecation**
Hip dislocation HP:0002827 is in the HPO as well, and is by defenition the same as dislocation of the femoral head (femoral head dislocation from the acetabular socket (PMID30275789)).

**Suggested replacement or term to consider**
The suggestion will be to keep Hip dislocation as HPO term as this is the most commonly used term, and to add dislocation of the femoral head as a synonym.

Andreas Zankl: 0000-0001-8612-1062, @azankl
Lisanne Wit: 0009-0007-1020-5412

**Comment by pnrobinson** [comment]
thanks for pointing this out - agree and have merged the terms as suggested.
