### ISSUE TITLE
Abscess needs a definition

### ISSUE THREAD

**Issue by ddooley** [obophenotype/human-phenotype-ontology#10519]
**HPO term**
HP_0025615 Abscess

**Suggested revision of textual definition**
A newly formed tissue cavity containing pus which is the result of a bacterial, fungal, or parasitic infection or the presence of a foreign body.

This is slightly adjusted from MONDO definition, but conveying that it is a material entity rather than a process or disease disposition.

**Comment by pnrobinson** [comment]
This is a better definition:
An abscess is a localized collection of purulent material surrounded by inflammation and granulation
The limitations are not quite correct.
added!
