### ISSUE TITLE
Iappropriately low concentration of beta-hydroxybutyrate (HP:6000236)

### ISSUE THREAD

**Issue by slaulederkind** [obophenotype/human-phenotype-ontology#10523]
**HPO term**

Iappropriately low concentration of beta-hydroxybutyrate (HP:6000236)

**Bug description**

It looks like this term is missing an "n" after the initial "I".

**Comment by pnrobinson** [comment]
@slaulederkind 
Not just missing but i(n)appropriately so.
I have corrected the label to 

Inappropriately low concentration of beta-hydroxybutyrate

thanks!
-Peter
