### ISSUE TITLE
Error in textual definition and parentage of Joint contracture

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#10522]
**HPO term**
HP_0034392 Joint contracture

**Suggested revision of textual definition**
Current def: A limitation in the passive range of motion of the **elbow** resulting from loss of elasticity in the periarticular tissues owing to structural changes of non-bony tissues, such as muscles, tendons, ligaments, joint capsules or skin. A contracture prevents movement of the associated body part.

Change to: A limitation in the passive range of motion of a joint resulting from loss of elasticity in the periarticular tissues owing to structural changes of non-bony tissues, such as muscles, tendons, ligaments, joint capsules or skin. A contracture prevents movement of the associated body part.

ALSO: need to to REMOVE 'Abnormal skeletal muscle morphology', 'Abnormal tendon morphology', and 'Abnormality of connective tissue' as parents BECAUSE it breaks the ALWAYS TRUE rule as sometimes one of those 3 things are not involved. Also, of note, 'Joint hypermobility' (HP_0001382) only has 'Abnormality of joint mobility' as a parent and not the other 3.  Tagging @katiemullen

**Comment by pnrobinson** [comment]
Changed the definition. I do think that the "always" is justified, since a contracture by definition changes all of the named parts to some degree or other? Do you have a counterexample?

**Comment by LCCarmody** [comment]
I think that we agree that contractures can lead to problems in all, but some burns that lead to contractures and muscle contractures start out as a deficit in one area and then lead to issues in tendons, muscles, etc. So the definition (and hierarchy) as stated is not always true if seen early.

**Comment by pnrobinson** [comment]
@LCCarmody 
I am not really sure what the best revision is. Clinically, I do not think people would diagnosis "Contracture" at a very early state and by the time we get to a clinical contracture, surely all three organs are affected. I do not think this is a large mistake but it is something we should revisit whenever we do a workshop. We can also ask the contracture group.
