### ISSUE TITLE
Add synonym pyridoxal 5′-phosphate

### ISSUE THREAD

**Issue by lisannesw** [obophenotype/human-phenotype-ontology#10533]
**HPO term**
Abnormal circulating vitamin B6 concentration HP:0032476

**Synonym to be added**
Abnormal circulating pyridoxal 5′-phosphate

Comment: pyridoxal 5′-phosphate is the active form of vitamine B6

**broad/exact/narrow/plural/abbreviation ?**
narrow

Andreas Zankl: 0000-0001-8612-1062, @azankl
Lisanne Wit: 0009-0007-1020-5412

**Comment by pnrobinson** [comment]
added!
