### ISSUE TITLE
add synonym double ring sign

### ISSUE THREAD

**Issue by lisannesw** [obophenotype/human-phenotype-ontology#10556]
**HPO term**
Optic nerve hypoplasia HP:0000609

**Synonym to be added**
Double ring sign 
"Double ring sign of optic nerve head is a characteristic fundus finding in cases with optic nerve head hypoplasia"PMID:31238457

**broad/exact/narrow/plural/abbreviation ?**
Broad

Andreas Zankl: 0000-0001-8612-1062, @azankl
Lisanne Wit: 0009-0007-1020-5412

**Comment by pnrobinson** [comment]
thanks! Added
