### ISSUE TITLE
Add lang="en" tag to international version pref labels

### ISSUE THREAD

**Issue by janelomax** [obophenotype/human-phenotype-ontology#10559]
In http://purl.obolibrary.org/obo/hp/hp-international.owl the class labels all have explicit lang tags except for the English one e.g.

```
<rdfs:label xml:lang="fr">Anomalie phénotypique</rdfs:label>
        <rdfs:label xml:lang="es">Anomalía fenotípica</rdfs:label>
        <rdfs:label xml:lang="tr">Fenotipik anormallik</rdfs:label>
        <rdfs:label xml:lang="nl">Fenotypische abnormaliteit</rdfs:label>
        <rdfs:label xml:lang="cs">Fenotypová abnormalita</rdfs:label>
        <rdfs:label>Phenotypic abnormality</rdfs:label>
```

would it be possible to also have `lang="en" tag` added to the English labels please?

**Comment by pnrobinson** [comment]
@janelomax 
well, English is the original language and the others are labeled as translations, so it does not seem we would gain anything by adding more complexity to the file. But does this cause a problem on your end?
@matentzn

**Comment by matentzn** [comment]
FYI - we _could_ do this just for the hp-international edition - technically this is easy. There are some good arguments to do this just for that specific version, and now harm for us doing it.

But note that we are, on OBO level, striding towards a solution that allows for a single "default" language, without the need for language tags. I think that tools should probably support this no matter what. https://github.com/information-artifact-ontology/ontology-metadata/issues/128. We have previously decided to drop language tags for english in HPO here: https://github.com/obophenotype/human-phenotype-ontology/issues/10387.

@pnrobinson let me know if you think its reasonable to add language tags _just_ for the international edition of HPO, or if you think it causes more churn than value. I am fine either way, 5 min job.

**Comment by pnrobinson** [comment]
It seems relatively straightforward to adapt code to assume that English is the default language if no code is supplied. 
Every change to the format of the file causes small problems at our end with software that is reading these files and I think for now it would be easiest if we just try to keep our current formats. @janelomax could you please use whatever workaround? I am assuming this is not enormously onerous.
