### ISSUE TITLE
Add parental term to pseudoepiphysis of metacarpal

### ISSUE THREAD

**Issue by lisannesw** [obophenotype/human-phenotype-ontology#10562]
**HPO term**
Pseudoepiphysis of the 3rd metacarpal HP:0010223
Pseudoepiphysis of the 4th metacarpal HP:0010225
Pseudoepiphysis of the 5th metacarpal HP:0010227

**Suggested revision and reasons**
Add Pseudoepiphyses of the metacarpals HP:0009193 as parental term for the above terms. The first and second metacarpal already have it as parental term.

**Comment by pnrobinson** [comment]
Done.
Also changed label to "Metacarpal pseudoepiphysis"
