### ISSUE TITLE
search function has changed since last update

### ISSUE THREAD

**Issue by CentogeneRHS** [obophenotype/human-phenotype-ontology#10565]
Since the last update search for synonyme or only enter partially HPOs is not anymore working as before, it costs now much more time to find approbiate HPOs as before. see two examples attached.
![example search function](https://github.com/obophenotype/human-phenotype-ontology/assets/170631574/93c3929b-c06d-48e5-a75a-90056507f1ce)
![example search function_synonyme](https://github.com/obophenotype/human-phenotype-ontology/assets/170631574/10e201e3-229e-4454-9e4c-a33fde9c6a14)

**Comment by pnrobinson** [comment]
Thanks, we have noticed this and are working on an update.  @iimpulse 
This would be the tracker for HPO Website related issues: https://github.com/TheJacksonLaboratory/hpo-web
