### ISSUE TITLE
Aseptic meningitis as synonym of Non-infectious meningitis HP:0033430 

### ISSUE THREAD

**Issue by carolina-f** [obophenotype/human-phenotype-ontology#10576]
**HPO term**
Non-infectious meningitis HP:0033430 

**Synonym to be added**
Aseptic meningitis

**broad/exact/narrow/plural/abbreviation ?**
PMID: 33622338 Cognitive disorders, a pseudo-bulbar syndrome,  or cerebellar disorders, which half the time are associated  with various neuropsychiatric disorders (confused states, depressive syndrome, psychotic manifestations), have  also been observed. Patterns of acute transverse myelitis  have been described. Meningeal damage is frequent; this  includes **aseptic meningitis**. It remains latent in more than  one out of two patients, being expressed by isolated headaches. A pattern of “benign” HTIC is present in 20% of cases. 

PMID: 19028363 Neurological manifestations, such as ischemic stroke, **aseptic meningitis** or encephalitis. Such symptoms might reveal hepatic failure or coagulation dysfunction, as in DICS, haemophagocytosis or Moschcowitz syndrome.

**Comment by pnrobinson** [comment]
Thanks! Added
