### ISSUE TITLE
phenotype.hpoa - What does aspect "H" stand for?

### ISSUE THREAD

**Issue by yarong-lifemap** [obophenotype/human-phenotype-ontology#10586]
We've noticed a new "H" aspect in the phenotypes.hpoa file. Can someone please explain what H stands for?

**Comment by pnrobinson** [comment]
Thanks for asking. I have added some documentation about this to the bottom of this page:

https://obophenotype.github.io/human-phenotype-ontology/annotations/phenotype_hpoa/
