### ISSUE TITLE
HP:0007035 Anterior encephalocele / Frontal encephalocele HP:0007330

### ISSUE THREAD

**Issue by kanems** [obophenotype/human-phenotype-ontology#10597]
**HPO term**
HP:0007035 Anterior encephalocele / Frontal encephalocele HP:0007330

**Suggested revision of textual definition**
Neither term has a definition, so I cannot tell if these are conceptually the same (as UMLS has lumped them in their latest release; possibly based on Orphanet using these two terms interchangeably on their record 1931 https://www.orpha.net/en/disease/detail/1931?name=1931&mode=orpha ) .
If these are truly different concepts, I will follow up with UMLS to request the split. Thanks!

**Comment by pnrobinson** [comment]
@kanems 
An anterior encephalocele occurs on the anterior part of the skull. Frontal encephalocele is a specific type of anterior that involves the frontal bone (i.e. the forehead).
The terminology seems to be used in a slightly inconsistent way in the literature.
I am rearranging this part of the HPO and adding definitions, could you please check after the next release?

**Comment by pnrobinson** [comment]
I am looking at the annotations for "Frontal" and think that "frontoethmoidal encephalocele" is what is meant -- see https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4293844/. I will change the label accordingly.
