### ISSUE TITLE
HP:0010464 "Streak ovary" recursion

### ISSUE THREAD

**Issue by austinant** [obophenotype/human-phenotype-ontology#10592]
**HPO term**
HP:0010464

**Bug description**
in the hp.obo file for v2024-06-25, HP:0010464 "Streak ovary" has the attribute

```is_a: HP:0010464 ! Streak ovary```

This introduces a cycle (in particular, a self loop) to the graph. I looked for others like this and, as far as I can tell, this is an isolated occurrence, but it does flummox pyhpo.

**Comment by pnrobinson** [comment]
This was fixed and will be online shortly, thanks for pointing it out!
