### ISSUE TITLE
Fetal alcohol exposure synonyms

### ISSUE THREAD

**Issue by peupeubangbang** [obophenotype/human-phenotype-ontology#10603]
**HPO term**
Fetal alcohol exposure HP:0034984

**Synonym to be added**
Prenatal alcohol exposure
Prenatal ETOH exposure
Prenatal exposure to alcohol
Prenatal exposure to ETOH
Antenatal alcohol exposure
Antenatal ETOH exposure
Alcohol in pregnancy
Alcohol during pregnancy
Alcohol use in pregnancy
Alcohol use during pregnancy
Alcohol drinking in pregnancy
Alcohol drinking during pregnancy
Alcohol exposure before birth
Before birth alcohol exposure
Alcohol exposure in pregnancy
Alcohol exposure during pregnancy
Alcohol exposure during gestation
Alcohol exposure in the womb
Alcohol exposure to pregnancy
Alcohol consumption during pregnancy
Alcohol consumption in pregnancy
ETOH in pregnancy
ETOH in utero
ETOH during pregnancy
ETOH use in pregnancy
ETOH use in utero
ETOH use during pregnancy
Exposure to alcohol during pregnancy
Exposure to alcohol during gestation
Exposure to alcohol in pregnancy
Exposure to alcohol in utero
Exposure to alcohol in the womb
Exposure to alcohol while in the womb
Exposure of alcohol to the fetus
Exposure of the developing fetus to alcohol
In utero alcohol exposure
Alcohol exposure in utero
Periconceptional alcohol exposure
Prenatally exposed to alcohol

PAE

**broad/exact/narrow/plural/abbreviation ?**
Exact

Abbreviation (prenatal alcohol exposure)

**Comment by pnrobinson** [comment]
added thanks!
