### ISSUE TITLE
Lymphoid organ involvement

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1060]
Please consider new term for Lymphoid organ involvement

**Comment by drseb** [comment]
involved in what?

**Comment by LOURGHI** [comment]
involved in asceptic abscess but it would be more useful to have the term in its general meaning without precision .

**Comment by pnrobinson** [comment]
Hi, I still do not really understand what the term is meant to describe. Can you provide a use case? Please note that the phrase "lymphoid organ involvement" could imply involvement in many different processes (cancer, infection, atrophy), and so we will need to be more precise somehow.

**Comment by LOURGHI** [comment]
Hi,I have sent you a screenshot of the article on aseptic abscesses on your mailbox.

**Comment by pnrobinson** [comment]
Sorry, I did not receive the screenshot. Can you just paste the title of the reference into this request?

**Comment by LOURGHI** [comment]
Aseptic abscesses: a study of 30 patients with or without inflammatory bowel disease and review of the literature.PMID 17505254.

**Comment by pnrobinson** [comment]
An HPO term needs to be complete, i.e., the term definition or label cannot rely on the context of a paper (lymphoid organ involvement). I think that the best term for this abnormality is "Abdominal aseptic abscess" (HP_0025181). Please add new term requests if this is not sufficient.
