### ISSUE TITLE
HP:0020079 versus HP:6000276

### ISSUE THREAD

**Issue by anna-anagnostop** [obophenotype/human-phenotype-ontology#10609]
Please consider reviewing the textual definitions of Beta-alaninuria [HP:0020079](http://www.ebi.ac.uk/ols4/ontologies/hp/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHP_0020079) (no EQ) and Elevated urinary beta-alanine level [HP:6000276](http://www.ebi.ac.uk/ols4/ontologies/hp/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHP_6000276) (no EQ).

These terms appear to be identical based on their current definitions. Should one of them be obsoleted? Is HP:6000276 meant to denote an excessive mount? Please clarify the definitions and revise the relationship between the 2 terms, if needed.

Many thanks, 

Anna V. Anagnostopoulos

**Comment by pnrobinson** [comment]
@anna-anagnostop 
Indeed this was an error - thanks for pointing this out.
I have merged the terms.
The surviving id is Beta-alaninuria [HP:0020079]

**Comment by anna-anagnostop** [comment]
Thank you, Peter.
Best regards,
Anna
