### ISSUE TITLE
Aplasia/Hypoplastia of the eccrine sweat glands HP:0007592 - revise label typo

### ISSUE THREAD

**Issue by peupeubangbang** [obophenotype/human-phenotype-ontology#10612]
**HPO term**
Aplasia/Hypoplastia of the eccrine sweat glands HP:0007592

**Bug description**
Current string: Aplasia/Hypoplastia of the eccrine sweat glands
Revised: Aplasia/**Hypoplasia** of the eccrine sweat glands

**Comment by pnrobinson** [comment]
thanks, fixed!
