### ISSUE TITLE
Remove parent: Lipomyelomeningocele

### ISSUE THREAD

**Issue by peupeubangbang** [obophenotype/human-phenotype-ontology#10628]
**HPO term**
Lipomyelomeningocele HP:0025480

**Suggested revision and reasons**
REMOVE PARENT
Myelomeningocele HP:0002475

Lipomyelomeningocele is a closed NTD and should have Myelomeningocele removed as a parent because that is an open NTD.

**Comment by pnrobinson** [comment]
thanks, done!
