### ISSUE TITLE
HPO web interface sync with releases?

### ISSUE THREAD

**Issue by kanems** [obophenotype/human-phenotype-ontology#10630]
**HPO term**
Progressive alveolar ridge hypertrop(h)y HP:0009092

**Bug description**
I see in the 2024-06-25 release notes that this term was corrected to 'hypertrophy' instead of 'hypertropy' but the wrong spelling is still showing on the web viewer for HPO data: https://hpo.jax.org/browse/term/HP:0009092 

When will the website sync with released data?

**Comment by iimpulse** [comment]
fixed with https://github.com/TheJacksonLaboratory/ontology-service/releases/tag/v0.5.14 PURL Redirects were not being followed with curl
