### ISSUE TITLE
Do we need both HP:6000259 and HP:4000100?

### ISSUE THREAD

**Issue by MickeySegal** [obophenotype/human-phenotype-ontology#10632]
**HPO term**
HP:6000259 and HP:4000100?

**Reason for deprecation**
They overlap so much and consolidating may make sense.

**Suggested replacement or term to consider**

**Comment by pnrobinson** [comment]
[Positive hydrogen breath test HP:6000259](https://hpo.jax.org/browse/term/HP:6000259)
[Positive lactose hydrogen breath test HP:4000100](https://hpo.jax.org/browse/term/HP:4000100)

**Comment by MickeySegal** [comment]
Aren't these the same?

**Comment by pnrobinson** [comment]
I believe there are hydrogen (glucose/lactose/lactulose) breath tests. I am not sure if they have different indications or if they are all essentially the same -- I need to check this, but do you have knowledge/experience in this area?

**Comment by MickeySegal** [comment]
I have no special knowledge, but the HPO descriptions and synonyms for the two seem indistinguishable:

HP:6000259
Abnormally elevated quantiy of hydrogen measured by a hydrogen breath test (HBT). HBTs administer substrates such as glucose, lactulose, lactose and fructose and subsequently measure hydrogen exhaled in the breath using a gas chromatograph.

Synonyms:    Positive glucose hydrogen breath test - Positive glucose or lactulose hydrogen breath test - Positive lactulose hydrogen breath test

HP:4000100
Elevated hydrogen gas level in exhaled breath following oral administration of lactose. In individuals with lactose intolerance, undigested lactose in the colon will be metabolized by colonic bacteria, releasing hydrogen gas.

Synonyms:    No synonyms found for this term.

**Comment by pnrobinson** [comment]
The tests apparently can be used indistinguishably for bacterial overgrowth but do have differences --  see
https://my.clevelandclinic.org/health/diagnostics/12360-hydrogen-breath-test
Lactose, fructose, sucrose and sorbitol tests check for intolerance to those particular sugars. These are all sugars that, for different reasons, can be hard for some people to digest. You’ll only be tested for one at a time.

I have made the "lactose" version be a child of the other term. If there is ever a need we could add the other special tests.
