### ISSUE TITLE
*Maternal seizure* is a descendant of both *Seizure* and *Pregnancy history*

### ISSUE THREAD

**Issue by ielis** [obophenotype/human-phenotype-ontology#10640]
**HPO term**
[Maternal seizure](https://hpo.jax.org/browse/term/HP:0100622)

**Bug description**
*Maternal seizure* is a descendant of both *Seizure* and *Pregnancy history*. However, it should not be a descendant of *Seizure*.

**Comment by pnrobinson** [comment]
done
