### ISSUE TITLE
Delete HP0002570 Steatorrhea EQ and remove HP_0002630 fat malabsorption as child of Intestine morph

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#10641]
**HPO term**

Delete HP0002570 Steatorrhea EQ and remove HP_0002630 fat malabsorption as child of Intestine morph
**Suggested revision of logical definition**
HP0002570 Steatorrhea uses 'adipose tissue' which is incorrect. There are issues with inferences while using lipid for EQ and it is missing the malabsorption component of the term, so I propose we remove the EQ for now.

Secondly, HP_0002630 fat malabsorption has parents 'Malabsorption' and 'Abnormal small intestine morphology', but there are a number of non morphology reasons for fat malabsorption, so propose to remove 'Abnormal small intestine morphology'  as a parent. @sbello 
'

**Comment by pnrobinson** [comment]
I revised the logical definition to
```
'has part' some 
    ('increased amount'
     and ('characteristic of' some 
        (lipid
         and ('part of' some feces)))
     and ('has modifier' some abnormal))
```
and I removed the parentage as suggested.
