### ISSUE TITLE
Revise parent HP:0012033 

### ISSUE THREAD

**Issue by peupeubangbang** [obophenotype/human-phenotype-ontology#10652]
**HPO term**
HP:0012033 Sacral lipoma

**Suggested revision and reasons**
REVISE PARENT - suggest to go underneath
HP:6000590 Spinal lipoma

I think having both sacral lipoma and spinal lipoma at the same level of the tree are potentially confusing and that a sacral lipoma provides more granularity on top of spinal lipoma

**Comment by pnrobinson** [comment]
agree, thanks!
