### ISSUE TITLE
CKD for Chronic kidney disease

### ISSUE THREAD

**Issue by domibln** [obophenotype/human-phenotype-ontology#10660]
**HPO term**

hp:0012622

**Synonym to be added**

CKD

**broad/exact/narrow/plural/abbreviation ?**

abbreviation

(requested by virtually every nephrologist)

We might also consider AKI for Acute kidney injury (HP:0001919), but the abbreviation is not as widely used as CKD.

**Comment by pnrobinson** [comment]
added both acronyms, thanks!
