### ISSUE TITLE
HP:0034322 revise label and add parent?

### ISSUE THREAD

**Issue by peupeubangbang** [obophenotype/human-phenotype-ontology#10663]
**HPO term**
HP:0034322 Reduced tissue galactocerebrosidase activity

This label and structure is for 'tissue' however in Krabbe disease reduced galactocerebrosidase activity is typically diagnosed measuring leukocytes on NBS at least for early onset/infantile forms.

The definition for this term currently includes both tissue and leukocytes measurement.

**Suggested revision and reasons**
Revise label and add parent
REVISED LABEL: Reduced ~~tissue~~ galactocerebrosidase activity
ADD PARENT: HP:0034858 Abnormal leukocyte enzyme concentration or activity 

Or would the more preferable option be to create another term specific to leukocyte measurement? E.g. **Reduced galactocerebrosidase activity in leukocyte** 
I am wondering if that is the case then is adding another parent term best to group the galactocerebrosidase  enzyme phenotypes, with both the tissue and (new) leukocyte terms to come underneath this...

**Comment by pnrobinson** [comment]
@peupeubangbang 
the reason for the "tissue" is that this enzyme actiivty can be measured in multiple tissues -- according to OMIM "Galactocerebroside beta-galactosidase deficiency in serum, leukocytes, and fibroblasts"
To my knowledge the clinical implication is the same and thus it seems more useful not to have separate terms for each. We can add narrow synonyms for each of the individual tissues.
Thoughts?

**Comment by peupeubangbang** [comment]
@pnrobinson agree! youre right there are no further clinical implications it is all the same thing synonyms is a great idea. i am happy to make synonym suggestions. i can close and will reference this
