### ISSUE TITLE
Knuckle pad

### ISSUE THREAD

**Issue by MickeySegal** [obophenotype/human-phenotype-ontology#10661]
**HPO term**
HP:0032541

**Synonym to be added**
Dorsal dupuytren nodules (DDN)

One of our orthopedics curators said this is the preferred term instead of knuckle pad, but agreed that knuckle pad may be more familiar to non-orthopedists and that Dorsal dupuytren nodules should be added as a synonym.

**broad/exact/narrow/plural/abbreviation ?**
DDN

**Comment by pnrobinson** [comment]
added, thanks!
