### ISSUE TITLE
Krabbe disease & reduced GALC activity

### ISSUE THREAD

**Issue by peupeubangbang** [obophenotype/human-phenotype-ontology#10662]
**Disease ID and Name**
OMIM:245200 Krabbe disease (MONDO:0009499)

**HPO ID and Name**
HP:0034322 Reduced tissue galactocerebrosidase activity 

**Further information (Frequency, Onset, Pubmed-references, Comments)**
Very frequent
Ranges seen from 0-22% of normal GALC activity levels in Krabbe disease patient cohorts
PMID:20301416

**Comment by pnrobinson** [comment]
we made this annotation a few weeks ago and it will appear in the public release shortly, probably next week.
