### ISSUE TITLE
Elevated gamma-glutamyltransferase level HP:0030948

### ISSUE THREAD

**Issue by MickeySegal** [obophenotype/human-phenotype-ontology#10674]
**HPO term**
Elevated gamma-glutamyltransferase level HP:0030948

**Synonym to be added**
https://www.ncbi.nlm.nih.gov/books/NBK584020/
"Gamma-glutamyl transpeptidase (GGTP; also referred to as gamma-glutamyl transferase [GGT]) "

Also worth doing (in the other direction) for https://hpo.jax.org/browse/term/HP:6000578

**broad/exact/narrow/plural/abbreviation ?**

**Comment by pnrobinson** [comment]
added synonym, thanks!
