### ISSUE TITLE
HP:0001674 Complete atrioventricular canal defect: Remove synonym

### ISSUE THREAD

**Issue by peupeubangbang** [obophenotype/human-phenotype-ontology#10678]
**HPO term**
Complete atrioventricular canal defect HP:0001674

**Bug description**
_Atrioventricular canal_ is a broader synonym than term HP:0001674 and would be better placed as a synonym for HP:0006695 Atrioventricular canal defect per #10676

**Comment by pnrobinson** [comment]
Thanks @peupeubangbang I am changing the synonym to Complete atrioventricular canal (https://pmc.ncbi.nlm.nih.gov/articles/PMC1459121/).
