### ISSUE TITLE
HP:0011577 Partial atrioventricular canal defect: add synonyms

### ISSUE THREAD

**Issue by peupeubangbang** [obophenotype/human-phenotype-ontology#10681]
**HPO term**
Partial atrioventricular canal defect HP:0011577

**Synonym to be added**
PAVSD, PAVC

partial atrioventricular septal defect, incomplete atrioventricular septal defect, partial AVSD, AVSD partial, AVSD incomplete, incomplete AVSD, partial AVC, AVC partial, incomplete AVC, AVC incomplete, incomplete AVC defect, AVC defect incomplete, partial AVC defect, AVC defect partial, incomplete atrioventricular canal defect, atrioventricular canal defect incomplete, atrioventricular canal defect partial 

**broad/exact/narrow/plural/abbreviation ?**
Abbreviation

Exact

**Comment by pnrobinson** [comment]
added thanks! Note that I am not adding permutation of word order because text mining tools should do this automatically (our HPO mining tools do!)
