### ISSUE TITLE
rem to REM, also include "rapid eye movement" 

### ISSUE THREAD

**Issue by kanems** [obophenotype/human-phenotype-ontology#10691]
**HPO term**
Prolonged rem sleep HP:5200361
Short rem sleep HP:5200360

**Bug description**
Similar to the older ticket about abbreviation expansion (#897) , suggest that rem be spelled out in at least one synonym. Also rem should be REM (in all caps) to indicate its an acronym.

**Comment by kanems** [comment]
Also update capitalization on the preferred name for Rem parasomnia HP:5200299

**Comment by pnrobinson** [comment]
@kanems thanks for the suggestion -- done!
