### ISSUE TITLE
Hypoplasia of the nasal bone and Hypoplastic nasal bone

### ISSUE THREAD

**Issue by sbello** [obophenotype/human-phenotype-ontology#10759]
**HPO term**
Hypoplasia of the nasal bone (HP:0004646) and Hypoplastic nasal bone (HP:0025707)

**Reason for deprecation**
The labels of these terms make it appear they are the same phenotype. The definitions are:

HP:0025707: Length of the nasal bone below a predetermined cut-off as seen on antenatal ultrasound using standard imaging techniques

HP:0004646: Underdevelopment of the nasal bone. 

The first I would have considered 'short nasal bone' or 'reduced nasal bone length'. The second sounds like impaired nasal bone development.  Assuming these are meant to be the same phenotype I would suggest merging these.

**Comment by pnrobinson** [comment]
@sbello The intention of this term was to refer to a specifically fetal finding. I have changed the name of the term to Hypoplastic fetal nasal bone. Thanks for picking up this error.
