### ISSUE TITLE
Elevated circulating hepatic transaminase concentration synonyms

### ISSUE THREAD

**Issue by sbello** [obophenotype/human-phenotype-ontology#10760]
**HPO term**
Elevated circulating hepatic transaminase concentration (HP:0002910)

**Bug description**
Elevated circulating hepatic transaminase concentration has as an exact synonym 'abnormal liver function' this seems more like a broad synonym rather than exact.

**Comment by pnrobinson** [comment]
I am removing this synonym, which I think very occasionally is used in clinical parlance, but even there it is bad.
