### ISSUE TITLE
Abnormal vestibular saccule morphology and Abnormal saccule morphology

### ISSUE THREAD

**Issue by sbello** [obophenotype/human-phenotype-ontology#10768]
**HPO term**
HPO has the terms Abnormal vestibular saccule morphology (HP:0030999) and Abnormal saccule morphology (HP:0040110) both descendants of Abnormal morphology of the vestibule of the inner ear (HP:0011376). It is unclear to me that there is any difference between these two terms. I suggest merging these into a single term. I suggest retaining Abnormal vestibular saccule morphology (HP:0030999) as this has a more detailed definition and a child term.

**Comment by pnrobinson** [comment]
@sbello  thanks!
Merged as recommended.
