### ISSUE TITLE
Hyperkinetic movements synonym

### ISSUE THREAD

**Issue by sbello** [obophenotype/human-phenotype-ontology#10761]
**HPO term**
Hyperkinetic movements HP:0002487

**Bug description**
Hyperkinetic movements has the exact synonym 'muscle spasms' but there is a separate term for 'muscle spasm' (HP:0003394). I think muscle spasms would be better as an exact synonym to HP:0003394. If retained as a synonym of HP:0002487 I do not think it should be an exact synonym.

**Comment by pnrobinson** [comment]
@sbello thanks for pointing this out. That was a layperson synonym, which I have changed to "Hyperactive movements". I will add the plural form  to Muscle spasm
