### ISSUE TITLE
peritoneal effusion

### ISSUE THREAD

**Issue by sbello** [obophenotype/human-phenotype-ontology#10765]
**HPO term**
Peritoneal effusion (HP:0030995)

**Reason for deprecation**
I can not find a source that makes a distinction between Peritoneal effusion and Ascites (HP:0001541). I find multiple sources that use these terms as exact synonyms (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3936968/ https://mesothelioma.net/peritoneal-effusion-ascites/ ) HPO currently has terms for both of Peritoneal effusion and Ascites. I would suggest merging these into a single term.

**Comment by pnrobinson** [comment]
@sbello 
thanks!!
Fixed as recommended.
