### ISSUE TITLE
Muscle hemorrhage 

### ISSUE THREAD

**Issue by sbello** [obophenotype/human-phenotype-ontology#10776]
**HPO term**
Muscle hemorrhage (HP:0040242) and Intramuscular hematoma (HP:0012233)

**Synonym to be added**
move the synonyms 'Intramuscular haemorrhage' and 'Intramuscular hemorrhage' from Intramuscular hematoma to Muscle hemorrhage

**broad/exact/narrow/plural/abbreviation ?**
exact based on the definition of Muscle hemorrhage 'Bleeding occurring within a muscle'

**Comment by pnrobinson** [comment]
@sbello Thanks again! Fixed!
