### ISSUE TITLE
Agenesis of permanent teeth

### ISSUE THREAD

**Issue by sbello** [obophenotype/human-phenotype-ontology#10774]
**HPO term**
Agenesis of permanent teeth (HP:0006349)

**Bug description**
Agenesis of permanent teeth has the exact synonym 'Missing teeth' but there is the parent term Tooth agenesis (HP:0009804) that has synonyms like Missing some teeth and Reduced number of teeth.It seems to me that 'Missing teeth' should be an exact synonym for Tooth agenesis and the exact synonym for Agenesis of permanent teeth should be 'Missing permanent teeth'

**Comment by pnrobinson** [comment]
Thanks, agreed! Fixed!
