### ISSUE TITLE
Submucous cleft palate

### ISSUE THREAD

**Issue by sbello** [obophenotype/human-phenotype-ontology#10770]
**HPO term**
Submucous cleft palate (HP:5201016)

**Synonym to be added**
Submucosal cleft palate

**broad/exact/narrow/plural/abbreviation ?**
exact

Submucosal cleft palate is currently an exact synonym to Submucous cleft hard palate (HP:0000176). It seems like this would be more appropriately an exact synonym of the parent term Submucous cleft palate

**Comment by sbello** [comment]
Please consider also moving the synonym Submucous clefting to Submucous cleft palate (HP:5201016) from Submucous cleft hard palate (HP:0000176) as well

**Comment by pnrobinson** [comment]
@sbello thanks for pointing these errors out -- I have fixed them as recommended!
