### ISSUE TITLE
Cutaneous cyst

### ISSUE THREAD

**Issue by sbello** [obophenotype/human-phenotype-ontology#10778]
**HPO term**
Cutaneous cyst (HP:0025245) and Epidermoid cyst (HP:0200040)

**Synonym to be added**
Move the exact (lay person) synonym 'skin cyst' from Epidermoid cyst to Cutaneous cyst.

Given that cutaneous cyst is defined as '..hollow mass located in the skin..' it seems like the synonym 'skin cyst' would be a better exact synonym for cutaneous cyst rather than epidermoid cyst.

**broad/exact/narrow/plural/abbreviation ?**
exact

**Comment by pnrobinson** [comment]
@sbello Thanks! fixed!
