### ISSUE TITLE
New Term Request: Reduced brain lactate level by MRS

### ISSUE THREAD

**Issue by pbuczkowicz** [obophenotype/human-phenotype-ontology#1077]
Please consider adding: Reduced brain lactate level by MRS

**Comment by pnrobinson** [comment]
Hi Pawel,
the HPO does not usually include the assay name in the term, except for phenotypes such as EEG, where there is no other way of measurement. We can put in a comment stating that the phenotype can be measured by MR spectroscopy, what do you think?

**Comment by pbuczkowicz** [comment]
Hi Peter,
I agree and believe it would be less restrictive if "by MRS" were omitted from the term, but I was going by previous terms such as Elevated brain lactate level by MRS found here, http://compbio.charite.de/hpoweb/showterm?id=HP:0012707. In which case, I believe "by MRS" could be removed from some of the other terms as well and only have the comment as you suggested.

**Comment by drseb** [comment]
Thanks. I will make an extra ticket for fixing the other classes.

**Comment by pnrobinson** [comment]
Note that after review of the terms, I think this is a technology-specific phenotype so that it is justified to leave MRS in the term labels.
