### ISSUE TITLE
Word 'pain' absent for 'forearm pain' for HP:6000299

### ISSUE THREAD

**Issue by DanielBHier** [obophenotype/human-phenotype-ontology#10775]
**HPO term**
**Forearm HP:6000299**

**Bug description**
I believe that the intention was for this term to **'forearm pain**' but the '**pain**' part does not appear.
The definition in the HPO is "
An unpleasant sensation characterized by physical discomfort (such as pricking, throbbing, or aching) localized to the forearm.
"
Note that the label and pref label is incorrect: 
label | Forearm |  
-- | -- | --
notation | **HP:6000299** |  
prefLabel | Forearm

Note that the CUI is incorrect. It is not: [Forearm (C0016536)](https://uts.nlm.nih.gov/uts/umls/concept/C0016536)
Definition: Part of the upper extremity in humans and primates extending from the ELBOW to the WRIST.
Semantic Types: Body Part, Organ, or Organ Component

It should map to CUI
Pain in forearm
**UMLS CUI: C0239667**
Semantic Types
:
[Sign or Symptom](https://uts.nlm.nih.gov/uts/umls/semantic-network/T184)

**Comment by pnrobinson** [comment]
@DanielBHier Thanks! I have fixed this, it was indeed Forearm pain!
