### ISSUE TITLE
Peg-shaped maxillary lateral incisors

### ISSUE THREAD

**Issue by sbello** [obophenotype/human-phenotype-ontology#10773]
**HPO term**
Peg-shaped maxillary lateral incisors (HP:0006342)

**Bug description**
Peg-shaped maxillary lateral incisors has the exact synonym 'Peg-shaped tooth'. This does not seem like an exact synonym for this term. I think it would either be a broad synonym or removed from this term and made an exact synonym to Conical tooth (HP:0000698). Conical tooth already has the synonym 'Peg shaped tooth' without the '-'.

**Comment by pnrobinson** [comment]
@sbello thanks, fixed!
