### ISSUE TITLE
Ectopia lentis

### ISSUE THREAD

**Issue by sbello** [obophenotype/human-phenotype-ontology#10780]
**HPO term**
Ectopia lentis (HP:0001083)

**Synonym to be added**
Ectopia lentis has the synonym 'Lens dislocation' but the synonyms 'Dislocated lenses' and 'Dislocated lens' are exact synonyms to Lens luxation (HP:0012019). Based on the definitions it seems like 'Dislocated lenses' and 'Dislocated lens' should be narrow and exact synonyms, respectively, to Ectopia lentis while the synonym for Lens luxation should be 'Complete lens dislocation'

**Comment by pnrobinson** [comment]
Thanks for pointing this out. I have added the word "Completely" to the synonyms for Lens luxation.
