### ISSUE TITLE
Forearm 

### ISSUE THREAD

**Issue by MickeySegal** [obophenotype/human-phenotype-ontology#10784]
**HPO term**
https://hpo.jax.org/browse/term/HP:6000299

**Bug description**
The definition is "An unpleasant sensation characterized by physical discomfort (such as pricking, throbbing, or aching) localized to the forearm" so it seems this should be something like "Forearm pain".

**Comment by pnrobinson** [comment]
@MickeySegal 
thanks for pointing this out, it is indeed "Forearm pain"
