### ISSUE TITLE
New terms request (EKG abnormalities)

### ISSUE THREAD

**Issue by BrunOrpha** [obophenotype/human-phenotype-ontology#1079]
Concerning the field of HP:0003115, please consider adding:
- U wave (present in hypokalemia)
- Increased QRS voltage (present in ventricular hypertrophy, hyperthyroïdism)

**Comment by pnrobinson** [comment]
A U Wave iteself can benormal, but increased amplitude of U wave, U wave inversion, and exercsie induced U wave inversion seem to be good term candidates.
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3279650/
