### ISSUE TITLE
Additional build artefacts

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#1080]
Requested via email:

> ... would like to know if there is a downloadable list in a simple format (i.e. HPO code plus symptom on each line) or if there is any API key which I could use to have the form retrieving the terms and the codes straight from your website.

**Comment by pnrobinson** [comment]
Several people have requested basically an Excel file with

HP ID / Name / Definition / List of synonyms / List of parent terms

It might be nice to have this simply as a function that the homepage provides.
Peter

**Comment by drseb** [comment]
sure. once it's in the build-artefacts, I will link it from the download section

**Comment by pnrobinson** [comment]
Moving this to the wiki  https://github.com/obophenotype/human-phenotype-ontology/wiki/Downloadable%20files
