### ISSUE TITLE
increased internal nuclei

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1082]
Please consider new term for increased internal nuclei.

**Comment by pnrobinson** [comment]
Note I think this is different fromthe current term "centrally located nuclei". See also here
http://www.ncbi.nlm.nih.gov/books/NBK1432/

The clinical and histopathologic features of MTM1-associated myopathies are broad, requiring that a distinction be made between central and internal nuclei [Romero 2010]. The former occur at (or very near) the exact center of a myofiber and are typical of (although not specific for) XLCNM, whereas the latter are eccentrically situated within the myofiber.

**Comment by pnrobinson** [comment]
Myocytes are 
syncitial  and  the  nuclei  are  seen  subsarcolemma
ly.  However,  3-4%  of  internal  nuclei  are  
normal. 

In  a  normal  muscle,  nuclei  are  subsarcolemmal.
  They  are  small,  oval
  and  dark  staining.  
However, about 3% of fibers in transverse se
ction may show internal nuclei. Large number  of  internal  nuclei  suggests  a  myopathy  and  tran
sverse  section  is  best  to  assess  the  same.  
Dystrophies show about 10-30% internal nuclei
 and myotonic dystrophy is characterized by 
profuse number of internal nuclei of about 60%.

**Comment by pnrobinson** [comment]
Centrali nuclei instead are this: Myotubular/centronuclear   myopathy   shows   mo
re   than   30%   of   fibers   showing   single   
centrally  placed  nulei.  (Figure  5)  Chronic  neuropathies  like  Charcot-Marie-Tooth  disease  
also  shows  large  number  of  central  nuclei. 
TODO -- add term and check both definitions.

**Comment by LOURGHI** [comment]
excess internal nuclei and endomysial connective tissue,rimmed vacuoles, accumulation of myofibrillar material, were observed in a a patient with Zebra body myopathy .

**Comment by pnrobinson** [comment]
This should go under abnormal cell phenotype and abn. muscle

**Comment by pnrobinson** [comment]
We had a term for Centrally nucleated skeletal muscle fibers HP_0003687

**Comment by pnrobinson** [comment]
Adding term, HP_0031237, internally nucleated skeletal muscle fibers
