### ISSUE TITLE
Distinguishing Peripheral cyanosis versus Raynaud phenomenon

### ISSUE THREAD

**Issue by MickeySegal** [obophenotype/human-phenotype-ontology#10831]
**HPO term**
https://hpo.jax.org/browse/term/HP:0034033
https://hpo.jax.org/browse/term/HP:0030880

**Suggested revision of textual definition**
We've added the qualifier "in the absence of cold temperature or stress" to our peripheral cyanosis term.  You have the reverse qualifier in the Raynaud term but no mention in the peripheral cyanosis term.

**Comment by pnrobinson** [comment]
@MickeySegal 
thanks for the suggestion, I agree. I updated the definition to:

Bluish discoloration of the distal extremities in the absence of cold temperature or stress. Peripheral cyanosis can involve hands, fingertips, or toes, and sometimes circumoral and periorbital areas. Mucous membranes are generally not involved.
