### ISSUE TITLE
Abnormal thorax morphology

### ISSUE THREAD

**Issue by sbello** [obophenotype/human-phenotype-ontology#10846]
**HPO term**
 Abnormal thorax morphology http://purl.obolibrary.org/obo/HP_0000765 

**Suggested revision of logical definition**
Current eq uses quality but as the term is morphology this should use morphology

Current
[has part](https://www.ebi.ac.uk/ols4/ontologies/hp/properties/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FBFO_0000051?lang=en)[bfo](https://www.ebi.ac.uk/ols4/ontologies/bfo/properties/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FBFO_0000051)some([quality](https://www.ebi.ac.uk/ols4/ontologies/hp/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FPATO_0000001?lang=en)[pato](https://www.ebi.ac.uk/ols4/ontologies/pato/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FPATO_0000001)and[characteristic of part of](https://www.ebi.ac.uk/ols4/ontologies/hp/properties/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FRO_0002314?lang=en)[ro](https://www.ebi.ac.uk/ols4/ontologies/ro/properties/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FRO_0002314)some[chest](https://www.ebi.ac.uk/ols4/ontologies/hp/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_0001443?lang=en)[uberon](https://www.ebi.ac.uk/ols4/ontologies/uberon/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_0001443)and[has modifier](https://www.ebi.ac.uk/ols4/ontologies/hp/properties/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FRO_0002573?lang=en)[ro](https://www.ebi.ac.uk/ols4/ontologies/ro/properties/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FRO_0002573)some[abnormal](https://www.ebi.ac.uk/ols4/ontologies/hp/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FPATO_0000460?lang=en)[pato](https://www.ebi.ac.uk/ols4/ontologies/pato/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FPATO_0000460))

change some (quality... to some (morphology...

Also this term sits under 'abnormal axial skeletal morphology' but includes the child terms 'Thoracoabdominal wall defect' and 'Intercostal muscle weakness' which are not a skeletal phenotypes. It seems like the term should be moved out from under skeletal but I'm not quite sure where to put it. Is the intention that this would include just the skeletal and muscle elements of the chest or would it (as the Uberon term does) also include the skin? If it is the former then the term could sit under Abnormality of the musculoskeletal system. If it is the latter then I'm not sure where it fits.

**Comment by pnrobinson** [comment]
@sbello 
thanks for this. 
I fixed "morphology"
As a part of this, I moved "Intercostal muscle weakness" to "Muscle weakness".

Thoracoabdominal wall defect includes bony defects of the thorax (and other things), so it is admittedly a bunded term. 
We are going to be having a heart defect workshop and want to work on a lot of terms in this area, so I would suggest we leave it for now, it is more likely people will find it here. Abn. or the ms system is also not 100% covering everything (skin defect), so there is no really obvious other place to put it. Please reopen if this seems very wrong!
