### ISSUE TITLE
Hypolacrimia

### ISSUE THREAD

**Issue by carolina-f** [obophenotype/human-phenotype-ontology#10853]
**HPO term**
Decreased lacrimation HP:0000633

**Synonym to be added**
Hypolacrimia

**broad/exact/narrow/plural/abbreviation ?**
PMID: 35925585 
As part of the lacrimal apparatus, the lacrimal gland participates in the maintenance
of a healthy eye surface by producing the aqueous part of the tear film. Alacrimia and
**hypolacrimia**, which are relatively rare during childhood or young adulthood, have their
origin in a number of mechanisms which include agenesia, aplasia, hypoplasia, or incor-
rect maturation of the gland. Moreover, impaired innervation of the gland and/or the
cornea and alterations of protein secretion pathways can lead to a defective tear film. In
most conditions leading to alacrimia or **hypolacrimia**, however, the altered tear film is
only one of numerous defects that arise and therefore is commonly disregarded.

**Comment by pnrobinson** [comment]
added, thank you!
