### ISSUE TITLE
change synonym types for Microcephaly

### ISSUE THREAD

**Issue by sbello** [obophenotype/human-phenotype-ontology#10851]
**HPO term**
Microcephaly (HP:0000252)

**Synonym to be modified**
Please review the synonym types of the synonyms for Microcephaly
The MP has separate terms for small cranium and small calverium in addition to the term microcephaly but HPO has these as exact synonyms. As a small calverium is limited to just the bones of the skull enclosing the brain this seems like it should be a narrow synonym or possibly related as for both of these it could be small but not small enough to qualify as microcephaly

**broad/exact/narrow/plural/abbreviation ?**

**Comment by pnrobinson** [comment]
I am not sure this occurs a lot clinically, but I agree and have added small calvarium as a narrow synonym. Thanks!
