### ISSUE TITLE
myelin-like whorls in vacuolated fibres

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1085]
Please consider new term for myelin-like whorls in vacuolated fibres.

**Comment by pnrobinson** [comment]
Good reference: http://www.ncbi.nlm.nih.gov/pmc/articles/PMC2635944/

**Comment by pnrobinson** [comment]
Definition: Muscle fibers contain one or more vacuoles (membrane-bound cavity) associated with collections of membranes arranged in a whorl-like (spiral or circular) manner PMID:18974994
