### ISSUE TITLE
'Dysmenorrhea' (pain) isn't a type of 'Irregular menstruation' (variation in time between periods) 

### ISSUE THREAD

**Issue by paola-scibite** [obophenotype/human-phenotype-ontology#10865]
**HPO term**
Dysmenorrhea HP:0100607
Irregular menstruation HP:0000858

**Suggested revision and reasons**

Hi,

HP:0100607 'Dysmenorrhea' is defined as "_Pain_ during menstruation that interferes with daily activities." and has synonym "Painful menstruation". 
It is currently a subclass of
HP:0000858 'Irregular menstruation', defined as "Abnormally high _variation in the amount of time_ between periods." (synonyms: Irregular menses - Irregular periods - Menstrual irregularities - Menstrual irregularity).
The subclass relationships seems incorrect, and AFAIK, there isn't a correlation between the two phenotypes.
Should 'Dysmenorrhea' be a child of HP:0012531 'Pain' and HP:0000140 'Abnormality of the menstrual cycle' instead?

Thank you,

Paola (Roncaglia)

**Comment by pnrobinson** [comment]
@paola-scibite Thank you, I have adopted your suggestion.
