### ISSUE TITLE
rod-like structures on electron microscopy

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1087]
Please consider new term for rod-like structures on electron microscopy.

**Comment by pnrobinson** [comment]
I think you are refering to Nemaline bodies/rods (HP_0003798). I am not familiar with the phrase "rod-like bodies", but please add a definition to this term request if it is not the same. I have added a synonym, Rod bodies.

Rod  bodies  characteristically  stain  red  with
  MGT. The  rods  are  delicate  and  
accumulate  subsarcolemmaly.  They  stain  negative  with  ATPase,  NADH  and  SDH  as  they  
lack myosin and mitochondria. Rods are charac
teristic of nemaline myopathy but also seen 
in  central  core  disease  and  various  other  diseases  which  include  neurogenic  disorders  
(amyotrophic    lateral    sclerosis,    spinal    muscular    atrophy,    undefined),    inflammatory    
myopathies   (dermatomyositis,   polymyositis,   periarteritis   nodosa),   metabolic   myopathy  (mitochondrial myopathy), muscular dystrophy (LGMD) and some undefined myopathies. 

Shoei-Show  Liou,  Shun-Sheng  Chen,  Itsuro  Higuchi,  Hidetoshi  Fukunaga,  Mitsuhiro  
Osame.  Diagnostic  role  of  nemaline  rod  in  neuromuscular  disease.  Acta  Neurol  
Sinica 1992;1: 218-23

**Comment by pnrobinson** [comment]
Note: Latin nema thread, nemaline      having the form of threads :  fibrous

**Comment by LOURGHI** [comment]
you are right it's just  the description of nemaline rods.PMID:25747004.
