### ISSUE TITLE
Forearm HP:6000299 should be Forearm pain

### ISSUE THREAD

**Issue by paola-scibite** [obophenotype/human-phenotype-ontology#10873]
**HPO term**
Forearm HP:6000299, subclass of Pain,
"An unpleasant sensation characterized by physical discomfort (such as pricking, throbbing, or aching) localized to the forearm."

**Bug description**
Should be renamed Forearm pain

**Comment by pnrobinson** [comment]
Thanks! This was fixed recently and will be correct in the next HPO release (on Dec 1).
