### ISSUE TITLE
accumulation of actin-like thin filaments

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1088]
Please consider new term for accumulation of actin-like thin filaments.

**Comment by pnrobinson** [comment]
I guess you mean in skeletal muscle as in
https://ghr.nlm.nih.gov/condition/actin-accumulation-myopathy?

**Comment by pnrobinson** [comment]
By the way, could you put the name of the requested term (rather than "new term request") into the tracker item in the future?

**Comment by LOURGHI** [comment]
actin-like thin filaments were also observed in patient with Zebra body myopathy.

**Comment by LOURGHI** [comment]
It's OK for the name of the requested term.

**Comment by pnrobinson** [comment]
I think the label of Muscle fiber actin filament accumulation is better, & have added this term.
