### ISSUE TITLE
To add synonyms to Neurofibrillary tangles HP:0002185

### ISSUE THREAD

**Issue by jagcsun** [obophenotype/human-phenotype-ontology#10895]
**HPO term**
Neurofibrillary tangles

**Synonym to be added**
tau-positive neurofibrillary tangles (PMID: 38812098); tau-positive tangles (PMID:19652142); NFTs(PMID: 38812098).

**Your nano-attribution (ORCID)**
000-0002-6670-9157

**broad/exact/narrow/plural/abbreviation ?**

@pnrobinson

**Comment by pnrobinson** [comment]
added thanks
