### ISSUE TITLE
Need logical definition for HP_0001827 Genital tract atresia

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#1089]
Does this seem like the correct uberon class to use in the logical def? It is used in the parent class HP_0012243 Abnormal genital system morphology

'has part' some 
    (atretic
     and ('inheres in' some 'reproductive system')
     and ('has modifier' some abnormal))

cc @cmungall @drseb @pnrobinson

**Comment by pnrobinson** [comment]
There is an issue that this is a grouping class, and the atresia affects just a certain part of the reproductive system, never all at once. Probably the following is better

'has part' some 
(atretic
and ('inheres in part of' some 'reproductive system')
and ('has modifier' some abnormal))

**Comment by nicolevasilevsky** [comment]
Ok, sounds good, I'll add that logical def. I'll do the same for #1090
