### ISSUE TITLE
Increased U wave amplitude

### ISSUE THREAD

**Issue by BrunOrpha** [obophenotype/human-phenotype-ontology#1091]
Increased amplitude of U wave is present typically during hypokalemia
https://www.ncbi.nlm.nih.gov/pubmed/23839104

**Comment by pnrobinson** [comment]
There is currenlty a term "Prominent U wave" (HP_0025072) that seems to be synonymous. Do you agree and should I add this as a synonym? What would be the preferred term name for a cardiologist?

**Comment by BrunOrpha** [comment]
I currently cannot visualize this HP term, but i totally agree (a clinician would know this one term): "Prominent U wave"
