### ISSUE TITLE
Typos in label of Decreased cirrculating antimullerian hormone circulation HP:0031103

### ISSUE THREAD

**Issue by paola-scibite** [obophenotype/human-phenotype-ontology#10916]
**HPO term**
Decreased cirrculating antimullerian hormone circulation HP:0031103

**Bug description**
Typo in `cirrculating`, and `circulation` was probably entered instead of concentration? See parent Abnormal circulating antimullerian hormone concentration. Thanks.

**Comment by pnrobinson** [comment]
Thanks, this was fixed and will be updated in the next release this week.
