### ISSUE TITLE
New terms for epilepsy/seizures

### ISSUE THREAD

**Issue by andrewdevereau** [obophenotype/human-phenotype-ontology#1094]
The attached gives some suggested additional terms within the Seizures classes. In particular we would like to add Generalized Genetic Seizures as a subtype of Seizure. Prof Sanjay M Sisodiya  from UCL Institute of Neurology has made the suggestions as part of the 100000 Genomes Project. He has provided the following pubmed references, plus the attached pdf.:
PMID: 20196795, 2508707

The International League Against Epilepsy is currently conducting a consultation on classification which can be seen here:
http://www.ilae.org/Visitors/Centre/Class-Roadmap.cfm, http://www.ilae.org/Visitors/Centre/Organization.cfm

[OrganizationEpilepsy.pdf](https://github.com/obophenotype/human-phenotype-ontology/files/503131/OrganizationEpilepsy.pdf)
[New term request for HPO - epilepsy.docx](https://github.com/obophenotype/human-phenotype-ontology/files/503132/New.term.request.for.HPO.-.epilepsy.docx)

Andrew Devereau
Genomics England

**Comment by pnrobinson** [comment]
One of the above requests:
Genetic generalised epilepsy
This refers to epilepsy in which the etiology has a known or presumed genetic defect in which seizures are the core symptom of the disorder.It is therefore a disease entity rather than a phenotypic feature, and thus it is not a good HPO term
