### ISSUE TITLE
New term request: chills or rigors

### ISSUE THREAD

**Issue by Public-Health-Bioinformatics** [obophenotype/human-phenotype-ontology#1096]
In converting some SYMP ontology entries we had over to HP phenotype entries, SYMP chills came up blank.  Synonyms are rigors and shivering.  They could be associated with temperature instability (HP_0005968) , but perhaps not exclusively?

https://en.wikipedia.org/wiki/Chills

**Comment by pnrobinson** [comment]
The HPO currently does not have a subhierarchy for what is known as constitutional symptom
(Constitutional symptoms - also known as general symptoms, these affect the entire body. They include fever, weight loss, fatigue or altered appetite. )
Chills are  not an abnormality of termperature regulation, but  can be a normal reaction to an abnormal event (e.g., infection)

**Comment by Public-Health-Bioinformatics** [comment]
So it sounds like, to keep HPO within its vocabulary mandate, that constitutional symptoms won't be let into it.  That's ok, I can keep references to some SYMP terms.
Thanks for the info.

**Comment by pnrobinson** [comment]
Infact, we have been discussing this for a year and trying to figure out the best of of modeling this. Our preliminary conclusion is that we need a new top level term called "Constitutional symptom" and then this term can go under that. I am going to add this to the tracker to see if there are any comments, but will add it in a few days if there are none. Sorry for the delay with this term request.

**Comment by Public-Health-Bioinformatics** [comment]
Ah, nice!  I am trying to consolidate down the number of ontologies our GenEpiO ontology references.  Right now 25+ is a bit much.  This will help!

**Comment by pnrobinson** [comment]
I think that chills and rigors are not synonymous and am creating two distinct terms.
