### ISSUE TITLE
vanishing posterior fossa

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1099]
please consider new term for vanishing posterior fossa

**Comment by pnrobinson** [comment]
I do not know what this is. Do you mean 'vanishing cerebellum in Chiari II malformation'? Please provide a definition or more context.

**Comment by pnrobinson** [comment]
from Ravine syndrome pmid 22411793

**Comment by pnrobinson** [comment]
This is referring to vanishing of the cerebellar white matter  in Ravine syndrome, not to an abnormality of the bony posterior fossa.

**Comment by pnrobinson** [comment]
Looking at the article and the images, I think that it should be annotated with Cerebellar atrophy. It does not seem to be a clearly separated subtype of cerebellar atrophy that spares grey matter at the expense of white matter. See term HP_0001272
