### ISSUE TITLE
large choroidal vessels

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1106]
Please consider new term for large choroidal vessels

**Comment by psergouniotis** [comment]
I think this proposed term is a bit inaccurate and ill-defined. Does it refer to enlargement choroidal vessels of the Sattler's layer, Haller's layer or both? Is it an abnormality? It would be helpful to highlight which condition you have found to be associated with this.

**Comment by pnrobinson** [comment]
@LOURGHI Could you let us know what disease is being referred to?

**Comment by pnrobinson** [comment]
Enlarged choroidal vessels does seem to exist as a phenotype, 
see,
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4023115/
and 
thus I will interpret this issue as such.

**Comment by pnrobinson** [comment]
Here, the diagnosis is of  dilated choroidal vessels
http://www.sciencedirect.com/science/article/pii/S1350946215000336

I am adding the term with label
Dilatation of large choroidal vessels
HP_0030979
