### ISSUE TITLE
Placoid macular lesion

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1108]
Please consider new term for Placoid macular lesion

**Comment by pnrobinson** [comment]
Are you referring to this
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1809922/
Well-delineated whitish plaque-like lesions involving the macula and sparing the peripapillary area. Fluorescein angiography shows well-defined early hypofluorescent areas, which partially filled-in in the late phase. Indocyanine green angiography showed the hypofluorescence to be persistent.

**Comment by LOURGHI** [comment]
That's exactly it .

**Comment by psergouniotis** [comment]
"Placoid macular lesion" could be a subclass of HP:0030500 "Yellow/white lesions of the macula".

I think a definition could be:
" Yellow/white, sharply delineated lesion, typically of inflammatory nature, involving the macula". 

I do not think that it should be restricted to the condition described in PMC1809922.

**Comment by pnrobinson** [comment]
Thanks, adding term with suggested definition as HP_0025110.
