### ISSUE TITLE
rhythmic myoclonia in the perioral muscles

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1109]
Please consider new term for rhythmic myoclonia in the perioral muscles.

**Comment by LOURGHI** [comment]
this symptom has been defined as a rhythmic contractions of perioral muscles causing protrusion of the lips, twitchingof the corners of the mouth, or jaw jerking. in a Case Report
Ictal video-polygraphic features of perioral myoclonia with absences PMID:21570919

**Comment by pnrobinson** [comment]
I believe that eyelid myoclonia is the disease while eyelid myoclonus is the phenotypic feature, although the literature does not seem to be consistent on this. One finds that Eyelid myoclonia (Jeavons syndrome) is asyndrome where childrenmay have ... abscence seizures and bilateral eyelid myoclonus (also referred to as blepharoclonus).
