### ISSUE TITLE
irregularities in the number of spikes in the  spike-wave complex , spike amplitude and in occurrence of fragmentation 

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1110]
Please consider new term for irregularities in the number of spikes in the  spike-wave complex , spike amplitude and in occurrence of fragmentation 

this symptom differentiates POMA from CAE and EMA.

**Comment by pnrobinson** [comment]
Can you provide more context? What is the source of the assertion?

**Comment by pnrobinson** [comment]
@LOURGHI  I am not able to identify definitions for this description. I am going to close this issue. If it is possible to provide definitions then please open a new issue. This seems to be composed of three separate items.

**Comment by LOURGHI** [comment]
Please take a look at PMID:21570919.Ictal video-polygraphic features of perioral myoclonia with absences.
