### ISSUE TITLE
Retinal  Vasculitis

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1111]
Please consider new a term for Please consider new term for.

**Comment by drseb** [comment]
Is this rather a disease? This question is motivated by having a look at http://eyewiki.aao.org/Retinal_Vasculitis#Symptoms

**Comment by LOURGHI** [comment]
Retinal vasculitis may be the only expression of an eye disease or be a location from
others of a  systemic disease.

**Comment by drseb** [comment]
@pnrobinson please advise.

**Comment by psergouniotis** [comment]
Although it is often used to describe a disorder, I think it is mainly a phenotypic feature. It is therefore reasonable to include it as a subclass of HP:0008046 ("Abnormality of the retinal vasculature").

I note that the the Standardization of Uveitis Nomenclature (SUN) Project is aiming to address issues with terminology relating to intra-ocular inflammation such as this one.
