### ISSUE TITLE
neuro-retinitis

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1112]
Please consider a new term for neuro-retinitis.

**Comment by pnrobinson** [comment]
I think that this is a disease entity and not a phenotypic feature. See http://eyewiki.org/Neuroretinitis. If you need specific features, please make new requests. I think this is currenlty well covered.

**Comment by LOURGHI** [comment]
In fact, neuroretinitis is part of the IRVAN syndrome components which are : Idiopathic retinal vasculitis-aneurysms-neuroretinitis .PMID:9121757.
