### ISSUE TITLE
numerous aneurysmal dilatations of the retinal and optic nerve head arterioles.

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1113]
Please consider a new term for numerous aneurysmal dilatations of the retinal and optic nerve head arterioles.

**Comment by pnrobinson** [comment]
Are you considering IRVAN? (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3306109).
Should we include the epithet "tied-knot" in the term name?

**Comment by psergouniotis** [comment]
I do not think that "numerous aneurysmal dilatations of the retinal and optic nerve head arterioles" is a good HPO term. 

I believe though that if you want to describe retinal findings in IRVAN, you could select HP:0025188 (retinal vasculitis) or even better HP:0008030 (retinal arteritis). I note that these two are synonyms at present which is not accurate. HP:0008030 (retinal arteritis) should be a subclass of HP:0025188 (retinal vasculitis).

Also, two terms could be added:
* neuroretinitis (subclass of Abnormality of the fundus [HP:0001098]); this is not an ideal term as it is compound (combination of inflammation of the retina AND inflammation of the optic nerve head).
* Retinal arterial macroaneurysms (for definition see here http://eyewiki.aao.org/Macroaneurysm; subclass of Abnormality of retinal arteries [HP:0000630]).

I would not include the epithet "tied-knot" and I would not include reference to optic nerve head arterioles.

**Comment by pnrobinson** [comment]
Adding Retinal arterial macroaneurysms, and correcting the location of Reintal arteritis in the hierarchy.
Perhaps neuroretinitis should be better conceptualized as a disease entity.
