### ISSUE TITLE
lipid accumulation in macula.

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1114]
Please consider a new term for lipid accumulation in macula.

**Comment by pnrobinson** [comment]
I think that this is synonymous with macular drusen
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4816825/
A cardinal clinical feature of the disease is extracellular deposition of lipid-rich deposits underneath the retinal pigmented epithelium (RPE) called drusen, which contain high amounts of esterified and unesterified cholesterol 

I have added lipid accumulation in macula as a RELATED_SYNONYM. If there is a well defined form of macular lipid accumulation that is distinct from drusen, please reopen this term.
