### ISSUE TITLE
subacute sclerosing panencephalitis

### ISSUE THREAD

**Issue by janinelewis3** [obophenotype/human-phenotype-ontology#1116]
This condition is marked as autosomal recessive in the database.   Is this accurate?  It may be based on an OMIM entry from 1982, but in general this condition is not considered genetic.

**Comment by drseb** [comment]
according to OMIM it is: http://www.omim.org/clinicalSynopsis/260470

do you have a reference for it not being genetic?

**Comment by janinelewis3** [comment]
Subacute sclerosing panencephalitis (SSPE) is a progressive neurological disorder of children and young adults that affects the central nervous system (CNS). It is a  viral infection caused by defective measles virus. http://www.ninds.nih.gov/disorders/subacute_panencephalitis/subacute_panencephalitis.htm

It is a late complication of the measles infection.  There may be susceptibility genes but in general, not considered a mendelian condition
https://www.ncbi.nlm.nih.gov/pubmed/24875585

**Comment by pnrobinson** [comment]
Hi Janine,
you are almost certainly correct about this. There are a number of legacy entries in OMIM, and as I understand it, these entries are usually not actively retired. I think that the purpose of this is to have something out there in case there is actually a second case. The HPO project is hoping to extend more into the realm of common disease in the future, and then we will have the resources to deal better with diseases such as this, but for now I think the semantics is that there was one case back in 1982 that showed an apparently AR inheritance pattern.
