### ISSUE TITLE
flattened and locally umbilicated nodules

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1117]
Please consider a new term for flattened and ocally umbilicated nodules.

**Comment by pnrobinson** [comment]
I think you are referring to this kind of lesion:
http://escholarship.org/uc/item/4993r122
I think the better term name will be simply umbilicated nodule. As a rule, ontology terms should not have too many adjectives, as we get into a combinatorial problem. If there are clinical situations that make it important to distinguish between flattened and non-flattened umbilical nodules, then we need to create these terms and define them.
