### ISSUE TITLE
acanthotic epidermis

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1118]
Please consider a new term for acanthotic epidermis.

**Comment by drseb** [comment]
Would you consider this equivalent to Acanthosis? If not, why?

**Comment by LOURGHI** [comment]
I think these two terms are equivalent.

**Comment by pnrobinson** [comment]
acantho- (ă-kan'thō),
A spinous process; spiny, thorny.
The current HPO term Acanthocytosis (note misspelling above!) refers to red blood cells (cyto) that have thorn-like projections (acantho). 
Therefore, the terms are different. To my knowledge, if you just say Acanthocytosis you think of RBCs, so we will need to consider a term for acanthotic epidermis -- let's look and try to find the best preferred name.

**Comment by drseb** [comment]
oh right. I thought we have Acanthosis already
