### ISSUE TITLE
multinodular lesion

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1122]
Please consider a new term for multinodular lesion.

**Comment by LOURGHI** [comment]
This lesion is Pink to salmon-colored,well-circumscribed,elliptical, hairless and bosselated and it is very speciphique of Congenital panfollicular nevus
so pleaes ca you consider a new terme for  Pink to salmon-colored,well-circumscribed,elliptical, hairless and bosselated multinodular lesion .

**Comment by pnrobinson** [comment]
Please use the term Congenital panfollicular nevus for this (HP_0025471). The above description is particular to one patient but it is difficult to extend this to something general that would be a good HPO term.

**Comment by LOURGHI** [comment]
I can not find this term on HPO.
