### ISSUE TITLE
hamartomatous proliferation containing malformed hair follicles in various stages of development 

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1123]
Please  consider a new term for hamartomatous proliferation containing malformed hair follicles in various stages of development .

**Comment by pnrobinson** [comment]
I think this is referring to “panfollicular nevus", which should be the prefer label of this term.

**Comment by pnrobinson** [comment]
Congenital  panfollicular  nevus  (CPN),  first
described in 2005, is a hamartomatous proliferation
containing malformed hair follicles in various stages
of development
CPN is a recently described member of the larger
family of benign adnexal disorders of the skin. The
histologic differential diagnosis of this benign follic-
ular lesion includes follicular tumors such as panfol-
liculoma   and   trichoepithelioma   and   other
hamartomas. Panfolliculomas are well-circumscribed
lesions demonstrating all stages of follicular differen-
tiation, like CPN; unlike CPN, it is acquired as an
adult. Trichoepithelioma is a benign follicular tumor
that does not show all stages of follicular differenti-
ation. Nevus sebaceous of Jadassohn and folliculose-
baceous cystic hamartoma show sebaceous lobules
(which are small in congenital cases but still present),
which were absent in this case (5) [from PMID:    26822169]

**Comment by pnrobinson** [comment]
Pink to salmon-colored, 
well-circumscribed, 
elliptical, hairless, 
bosselated, multinodular
No bleeding or ulceration
Not painful or pruritic
Negative Darier’s sign

**Comment by pnrobinson** [comment]
Congenital
non-melanocytic
nevi
(hamartomas)
include epidermal nevi, connective tissue nevi, seba-
ceous  nevi,  hair  follicle  nevi  (trichofolliculoma),  and
various   proliferations   of   other   dermal   and   sub-
cutaneous  structures  including  smooth  muscle  and
lipomatous hamartomas. Such growths often involve
the skin of the head and neck region and are some-
times  associated  with  well-established  syndromes  of
genodermatoses.
Neoplasms with follicular differentiation include a
large variety of lesions that recapitulate different parts
of  the  hair  follicle  and  exhibit  a  broad  spectrum  of
behaviors.  Numerous  classifications  of  hair  follicle
proliferations  proposed  by  various  experts  demon-
strate  limited  consensus. Despite  the  abundance
of potentially applicable terms, we report an unusual
hamartomatous  lesion  with  pilar  features  that  does
not   entirely   fulfill   the   criteria   of   any   previously
described hair follicle neoplasms [PMID:    15660657]

**Comment by pnrobinson** [comment]
Parent term "Nevus"

**Comment by LOURGHI** [comment]
I had annotated with Hamartoma as parent.

**Comment by LOURGHI** [comment]
to annotate congenital panfollicular nevus .
