### ISSUE TITLE
hyperpigmentation of the basal epidermis

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1125]
Please consider a new term for hyperpigmentation of the basal epidermis.

**Comment by pnrobinson** [comment]
To my knowledge, many etiologies of hyperpigmentation involve melanocytes in the basal epidermis. The layer of hyperpigmentation is probably unknown or not recorded in the majority of cases. I would suggest annotating simply with "Hyperpigmentation of the skin" (HP_0000953). If there is a need for more specificity, please reopen this request but provide more details on the phenotype and its differentiating features from general hyperpigmentation.
