### ISSUE TITLE
 skin calcification

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1135]
Please consider a new term for  skin calcification.

**Comment by pnrobinson** [comment]
There is a term, "Subcutaneous calcification" def Deposition of calcium salts in subcutaneous tissue (i.e., the the lowermost layer of the integument). I think this is what you mean.

**Comment by drseb** [comment]
add as lay syn?

**Comment by LOURGHI** [comment]
In elastosis there is a calcification of elastic tissu which is present in in the dermal and epidermal layer.
PMID:19088
calcification is absent in elastoderma.

**Comment by pnrobinson** [comment]
Hi everybody -- we may need to revist this -- we are planning on rallying on the dermatology terms with several collaborators. But for now I added skin calcification as a synonym as Seb suggested.
