### ISSUE TITLE
The presence of fibroblasts with prominent rough endoplasmic reticulum

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1136]
Please consider a new term for The presence of fibroblasts with prominent rough endoplasmic reticulum.
This feature was found in patient with elastoderma.

**Comment by pnrobinson** [comment]
The term should probably be prominent rough endoplasmic reticulum, perhaps with subterms for cell types?

**Comment by pnrobinson** [comment]
This is a correlate of the increased production of elastin in this disease. The HPO is going to be working on abnormalities of cellular phenotypes inthe future @mellybelly , but I think it is better to go about that in a systematic fashion. For now, perhaps we can stick with the annotation of increased number of elastic fibers?
