### ISSUE TITLE
electronic dense extensions

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1138]
Please consider a new term for electronic dense extensions.
This feature was found in patient with elastoderma.

**Comment by pnrobinson** [comment]
Not entirely sure what you are referring to
Accordingto https://www.ncbi.nlm.nih.gov/pubmed/25072684 elastoderma is characterized by:
Histologically, this entity is
characterized by increased and fragmented pleomorphic
elastic fibers in the papillary and superficial dermis. 5 There
is no evidence of calcification. 4 Transmission electron
microscopy shows fibroblast-like cells with prominent rough
endoplasmic reticulum and irregular deposits of elastic
material at the periphery of elastic tissue fibers, with
grape-like globular structures. 3
==>> Therefore, are you referring to the "grape-like globular structures"? This disease is so rare that there does not seem to be any standard diagnostic criteria.

Is that the same as Fig 1D here
http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.831.7328&rep=rep1&type=pdf

**Comment by LOURGHI** [comment]
It's exactly the description reported on Fig 1D on this article.
he goal is to describe in the most complete way a rare disease that clinical sign is a diagnostic criterion or just a sign observed in this disease.

**Comment by pnrobinson** [comment]
OK, thanks. We need to try and create terms and a structure that will be understanddable in themselves, i.e., without somebody reading original articles. The phrase "electronic dense extensions" only really makes sense when somebody is looking at that Figure, but in the ontology, there is only text. Usually what we try to do is to look for a preferred phrase that is used to describe multiple diseases in multiple publications -- this way, it is more likely to be a community standard. Buit I agree that this phenotype is distinctive and should get an HPO term, I am just not sure about the prefered label (name).

**Comment by LOURGHI** [comment]
OK I understand more and more the logic HPO,I leave it to you to choose the appropriate terms to the missing concepts on HPO.

**Comment by pnrobinson** [comment]
At the moment,I do not think this is a good HPO term. Elastic fibers can be normally irregular on electron microscopy (https://www.researchgate.net/publication/34974698_Latent_TGF-beta_binding_protein_LTBP-2_assembly_to_the_extracellular_matrix_and_effects_on_cell_adhesion/figures?lo=1), and it is a little difficult to know exactly what the authors of this paper are describing. I think that we would need an expert in the electron microscopy of the dermis to assist us if we want to have terms at this level of detail. I am closing this item for now, but in another request I created several terms that can be used for elastoderma, I hope that is sufficient.
