### ISSUE TITLE
 thickened, hyperemic serosal, ulceration of the mucosa.

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1142]
Please consider a new term for  thickened, hyperemic serosal, ulceration of the mucosa.
PMID:23416507

**Comment by pnrobinson** [comment]
This article is referring to colonic mucosa (Inflammatory cap polyposis ). The term is "bundled", i.e., it combines lots of different attributes.

**Comment by LOURGHI** [comment]
It is the histological definition of the Cap polyposis and  I often find complete pathological definitions like these.

**Comment by pnrobinson** [comment]
Perhaps cap polyposis would be the better HPO term if this is an accepted pathological entity?

**Comment by pnrobinson** [comment]
This is the new term"Inflammatory cap polyp" (HP_0025198) from a related request.
