### ISSUE TITLE
bloody mucoid diarrhea

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1143]
Please consider a new term for bloody mucoid diarrhea.

**Comment by pnrobinson** [comment]
Note the following:
Diarrhea that contains bright red or maroon-colored blood may be referred to as hematochezia, while melena is used to describe black, tarry, and smelly diarrhea.
=> Therefore, the lay person synonym "bloody diarrhea" for hematochezia is not quite correct. This is leading to an error. I will correct it.
