### ISSUE TITLE
add additional layperson synonyms

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#1146]
I'd like to add the following layperson synonyms to the terms below. @pnrobinson or @drseb I can add these if you give me the thumbs up.

HP_0001251 Ataxia
Broad synonym: Unsteady gait

HP_0001260 Dysarthria
Exact synonym: Difficulty articulating speech

HP_0001290 Generalized hypotonia
Exact synonym: Decreased muscle tone 
Exact synonym: Low muscle tone 

HP_0100785 Insomnia
Broad synonym: Fragmented sleep

**Comment by pnrobinson** [comment]
I would say that fragmented sleep is a particular type (narrow syn) of insomnia, the other ones seem good to go!

Peter


Peter Robinson

Professor of Computational Biology

The Jackson Laboratory for Genomic Medicine

10 Discovery Drive

Farmington, CT 06032

860.837.2095 t | 860.990.3130 m

peter.robinson@jax.org<mailto:peter.robinson@jax.org>

www.jax.org



The Jackson Laboratory: Leading the search for tomorrow's cures


________________________________
