### ISSUE TITLE
onychomadesis

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1148]
Please consider a new term for onychomadesis.

**Comment by pnrobinson** [comment]
Onychomadesis is defined as proximal nail plate separation from the nail matrix and nail bed caused by a temporary arrest in nail matrix activity, and may present as a Beau's line. (PMID:    25473242)

onychomadesis, the complete shedding of the nail from the proximal matrix. PMID:24882996

**Comment by pnrobinson** [comment]
This is distinct from Onycholysis of distal fingernails
But seems like it should be a child of oncolysis
