### ISSUE TITLE
erythemato-squamous psoriasiform lesions 

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1151]
Please consider a new term for erythemato-squamous psoriasiform lesions .

**Comment by pnrobinson** [comment]
Not sure what this is -- could you send a reference to the disease you are describing?

**Comment by LOURGHI** [comment]
I's a feature observed in Bazex syndrome PMID:24346922.

**Comment by pnrobinson** [comment]
I think this is detailed description of this patient but too detailed to be a good HPO term, see 
https://github.com/obophenotype/human-phenotype-ontology/wiki/What-makes-up-a-good-HPO-term%3F
Please annotate instead with terms such as Scaling skin or Psoriasis
