### ISSUE TITLE
Move to GH releases

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#1155]
make move soon.

@cmungall how to handle old releases? separate folder for each release?

**Comment by cmungall** [comment]
I don't like doing this with folders. I prefer to use github tags. I'm not 100% sure how best to do this retrospectively. But I need to figure out how to do this for GO before we move from svn in March: https://github.com/geneontology/go-site/issues/189

**Comment by drseb** [comment]
Please let me know if you have good ideas how best to do this retrospectively. This on our todo-list since a long time.

**Comment by drseb** [comment]
I gave up retrospective release and just put a archive to repository https://github.com/Human-Phenotype-Ontology/HPO-archive

This issue is related to https://github.com/obophenotype/upheno/issues/194 , which I will close now.

**Comment by drseb** [comment]
Done! Hooray
