### ISSUE TITLE
entrapment of adnexal structures

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1158]
Pleaes consider a new term for entrapment of adnexal structures.
(Infantile digital fibromatosis PMID: 27684985)

**Comment by drseb** [comment]
You have to mention where the adnexal structure are entrapped!

According to what I read it is about the overlying epidermis of the tumor. Please be as specific as possible.

**Comment by pnrobinson** [comment]
Similar to a comment on a related term, this appears to be a characteristic of the tumor itself, and should be included in the description of the HPO term for Infantile digital fibromatosis. I have added a detailed description to the term created for this. I would not create a separate HPO term for it at this time.
