### ISSUE TITLE
a proliferation of bland intradermal spindle cells arranged in whorls, fascicles, or a storiform pattern in a collagenous background of varying degrees

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1160]
Please consider a new term for a proliferation of bland intradermal spindle cells arranged in whorls, fascicles, or a storiform pattern in a collagenous background of varying degrees.
(Infantile digital fibromatosis PMID: 27684985)

**Comment by pnrobinson** [comment]
This is a bundled description, and it is not certain to me that it is a good HPO term. Please see my comments about bundling in a previous comment (also in the HPO github wiki).
