### ISSUE TITLE
ulceration

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1162]
Please consider a new term for ulceration.
(Infantile digital fibromatosis PMID: 27684985)

**Comment by pnrobinson** [comment]
Again, please provide more context -- ulceration of what?

**Comment by LOURGHI** [comment]
sorry,it is an ulceration that affects the epidermis.

**Comment by pnrobinson** [comment]
Please see the HPO term "Skin ulcer" and the children term emanating from it -- I think that is what you want here.
