### ISSUE TITLE
abnormality of extensor tendon 

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1165]
Please consider a new term for abnormality of extensor tendon .
(Infantile digital fibromatosis PMID: 27684985).

**Comment by pnrobinson** [comment]
Can you specify which abnormality is meant and which finger(s) are affected?

**Comment by LOURGHI** [comment]
The extensor tendon was incorporated into the lesion in two cases without precision (PMID 21276743).

**Comment by pnrobinson** [comment]
Again, this is not necessairy a feature of the disease. Especially if there is not a precise description or larger case series, it does not seem appropriate to annotate to this feature.
