### ISSUE TITLE
axial deformity of the distal interphalangeal joint

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1166]
Please consider a new term for axial deformity of the distal interphalangeal joint.
(Infantile digital fibromatosis PMID: 27684985)

**Comment by pnrobinson** [comment]
After reading about this disease, I do not think it is necessarily characterized by this feature. Instead, it depends on the location and the extent of the tumor. I would advise not annotating the disease with a term like this. Depending on the exact abnormality,however,  it could be "Contracture of the distal interphalangeal joint of the fingers".
