### ISSUE TITLE
dermal inﬁltration of uniform spindle cells 

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1167]
Please consider a new term for dermal inﬁltration of uniform spindle cells .
(Infantile digital fibromatosis PMID: 27684985)

**Comment by pnrobinson** [comment]
This phrase is describing the appearance of the tumor itself:  The lesion itself is made up of a proliferation of bland intradermal spindle cells arranged in whorls, fascicles, or a storiform pattern in a collagenous background of varying degrees. 
The tumor is classified by NCIT as Inclusion Body Fibromatosis (Code C3456).
I think it is better to add a term for this.
