### ISSUE TITLE
tumoural cells stained positive for smooth muscle actin, desmin, and calponin

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1168]
Please consider a new term for tumoural cells stained positive for smooth muscle actin, desmin, and calponin.
(Infantile digital fibromatosis PMID: 27684985)

**Comment by pnrobinson** [comment]
This is not a good HPO term since the tumor cells may be expected to stain positive for these markers. The actual abnormality is the tumor itself. I do not think this needs to be annotated.
