### ISSUE TITLE
lactase deﬁciency

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1173]
Please consider a new term for lactase deﬁciency.
(Cono-spondylar dysplasia PMID: 24975242)

**Comment by pnrobinson** [comment]
This enzyme is produced in the small intestine in humans, and thus the term
Decreased intestinal mucosa lactase activity 
seems appropriate.
There are some diseases that need annotation with this term including 
http://omim.org/clinicalSynopsis/223000
