### ISSUE TITLE
bilateral epicanthic folds

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1174]
Pleases consider a new term for bilateral epicanthic folds.
(Cono-spondylar dysplasia PMID: 24975242)

**Comment by psergouniotis** [comment]
Epicanthic folds is a synonym of epicanthus (HP:0000286). For bilateral, best to use modifiers.

**Comment by pnrobinson** [comment]
I agree. Epicanthic folds is already listed as a synonym of Epicanthus, and the modifer bilateral (HP_0012832) can be used.
