### ISSUE TITLE
P1, B1 on the Tanner scale

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1175]
Please consider a new term for P1, B1 on the Tanner scale.
(Cono-spondylar dysplasia PMID: 24975242).

**Comment by pnrobinson** [comment]
Being at these Tanner stages is not in itself abnormal. The abnormality is the delay in the development of pubertal characteristics. Consider the term "delayed puberty" (HP:0000823)
