### ISSUE TITLE
white streaks

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1176]
Please consider a new term for white streaks.
(Lichen planus pemphigoides,PMID : 23331194)

**Comment by pnrobinson** [comment]
Can you please provide more context or send me the article this is based on?

**Comment by pnrobinson** [comment]
I think that it would be good to have a subhierarchy for white lesions of the oral mucosa. This seems to be a good reference
https://s3-ap-southeast-1.amazonaws.com/erbuc/files/5760_451dc457-e4ff-488b-bce8-68088317407d.pdf

**Comment by pnrobinson** [comment]
I have added a term for white lesion of the oral mucosa. I think that in this paper, "white streak" was a description that is not something that is in general use. Please see thenew term HP_0025125.
