### ISSUE TITLE
bandlike infiltration of lymphocytes in the upper dermis

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1181]
Please consider a new term for bandlike infiltration of lymphocytes in the upper dermis
(Lichen planus pemphigoides,PMID : 23331194)

**Comment by pnrobinson** [comment]
I think that moving forward it will be important to develop a coordinated set of terms for inflammatory skin manifestations. I am not sure that this description is something characteristic that should get its own term. HPO terms are useful if they can be applied to multiple patients and multiple diseases, and are not one-time descriptions of individual patients. We are engaging with dermatology groups and will be extending the HPO in this area next year. I would close this request for now, but please reopen if this term is something that is characteristic (e.g., is mentioned in diagnostic criteria etc -- I could not find this).
