### ISSUE TITLE
lichen planus 

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1183]
Please consider a new term for lichen planus 
(Lichen planus pemphigoides,PMID : 23331194)

**Comment by pnrobinson** [comment]
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4037946/
and
https://www.aad.org/public/diseases/rashes/lichen-planus#symptoms
and
http://www.aafp.org/afp/2011/0701/p53.html
-> Lichen planus is a disease, but the skin lesions are a characteristic phenotypic feature that are also called lichen planus (lesion).

**Comment by pnrobinson** [comment]
Please use the new terms for lichenoid skin lesion or oral lichenoid lesion.
