### ISSUE TITLE
bullous dermatoses

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1184]
Please consider a new term for bullous dermatoses
(Lichen planus pemphigoides,PMID : 23331194)

**Comment by pnrobinson** [comment]
A bullous dermatosis is a disease entity. There is an HPO term, "Abnormal blistering of the skin",that might be appropriate,especially since you are I think annotating another disease, lichen planus pemphigoides? I am closing for now, please reopenif I have misinterpreted this!
