### ISSUE TITLE
left hemispheric ischemic event 

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1185]
Please consider a new term for left hemispheric ischemic event 
(Lichen planus pemphigoides,PMID : 23331194)

**Comment by LOURGHI** [comment]
ecxuse me it's a feature of (Autoimmune hemolytic anemia-autoimmune thrombocytopenia-primary immunodeficiency syndrome PMID: 25414442)

**Comment by pnrobinson** [comment]
Ischemic event sounds like clinical slang. Is this supposed to be a synonym for stroke? The HPO has a term for ischemic stroke, and we could add some more specific subterms. I would use the left/right modifers rather than have a separate term for each side of the brain though.

**Comment by LOURGHI** [comment]
I think the author meant ischemic stroke,

**Comment by pnrobinson** [comment]
http://stroke.ahajournals.org/content/46/5/e114

**Comment by pnrobinson** [comment]
Coming back to this, I think it is better not to create HPO terms for all of the subtypes of stroke (which are diseases not phenotypes). I would say that the lichen pmnaus can be annotated for now to the HPO term ischemic stroke. In the future, we will be creating diseases models for various stroke syndromes.
