### ISSUE TITLE
 autoimmune hepatitis

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1186]
Please consider a new term for  autoimmune hepatitis
(Autoimmune hemolytic anemia-autoimmune thrombocytopenia-primary immunodeficiency syndrome PMID: 25414442)

**Comment by pnrobinson** [comment]
Autoimmune hepatitis should be annotatied using "Hepatitis" (HP:0012115) and the phenotyptic feature that led to the diagnosis of "autoimmune", e.g., antinuclear antibodies (ANA) and anti-smooth muscle antibodies (ASMA) in type 1 disease and, in type 2 autoimmune hepatitis, anti-liver-kidney microsome-1 antibodies (ALKM-1) and anti-liver cytosol antibody-1 (ALC-1
