### ISSUE TITLE
cardiopathy

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1187]
Please consider a new term for cardiopathy
(20q11.2 microdeletion syndrome PMID: 25572454)

**Comment by pnrobinson** [comment]
I do not have access to this article right now, but cardiopathy is not a specific phenotypic feature -- You could code with Abnormality of the heart. Did the authors mean cardiomyopathy? Then there are HPO terms. Please reopen if there is a specific term that is not yet in the HPO!
