### ISSUE TITLE
temper tantrums

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1191]
Please consider a new term for temper tantrums
(11q22.2q22.3 microdeletion syndrome,PMID : 25735893)

**Comment by pnrobinson** [comment]
I do not have access to this article -- could you send it to me offline.
Temper tantrums are a normal part of growing up in a 2-3 year old, so if we make a term like this we will have to make it reflect an increased severity or a late age. I think we should consult the pschiatry manual and see if there are criteria for this?

**Comment by pnrobinson** [comment]
I have added 3 terms: Abnormal, freqeunt, and severe temper tantrums.
