### ISSUE TITLE
mild tremors

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1194]
Please consider a new term for mild tremors
(11q22.2q22.3 microdeletion syndrome,PMID : 25735893)

**Comment by pnrobinson** [comment]
For this use the HPO term "Tremor" combined with the modifier "Mild". The HPO does not make terms for mild,moderate,severe etc unless there are numeric criteria accepted in the community e.g., for Intellectual disability.
