### ISSUE TITLE
epsis-like condition

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1196]
Please consider a new term for epsis-like condition
(Isolated sedoheptulokinase deficiency,PMID : 25647543)

**Comment by pnrobinson** [comment]
The article says this:
a sepsis-like condition with intestinal pseudoobstruction, transient hypoglycemia, cholestatic hepatitis, and transient renal failure (maximum plasma creatinine 132 μmol/L and urea 11 mmol/L at day 5 of life, which normalized on day 10).

In this case, there is a disease entity (the authors do not make a real diagnosis, and say sepsis-like condition), but actually the phenotypic features are 
1. intestinal pseudoobstruction
2. transient hypoglycemia
3. cholestatic hepatitis
4. transient renal failure

We are just making a guide to HPO term requests that I have put up onthe wiki -- I will use this as an example, it is a nice example of the vague way that publications describe clinical phenotypes.

https://github.com/obophenotype/human-phenotype-ontology/wiki/How_to_make_a_good_term_request
