### ISSUE TITLE
Improper Gene-disease associations

### ISSUE THREAD

**Issue by oleraj** [obophenotype/human-phenotype-ontology#1199]
Hi,

I'm doing some work with some of the HPO files from http://compbio.charite.de/jenkins/job/hpo.annotations.monthly/lastStableBuild/ to associate genes to phenotypes.  I noticed that sometimes one gene is associated with multiple diseases (and their corresponding phenotypes), even though there is no evidence for the association in OMIM.  For example, in the file ALL_SOURCES_TYPICAL_FEATURES_diseases_to_genes_to_phenotypes.txt, I see these diseases:

```
grep IL17RC ALL_SOURCES_TYPICAL_FEATURES_diseases_to_genes_to_phenotypes.txt  | cut -f 1-2 | uniq
ORPHANET:1334	IL17RC
OMIM:613108	IL17RC
OMIM:212050	IL17RC
OMIM:615527	IL17RC
OMIM:614162	IL17RC
OMIM:607644	IL17RC
OMIM:247650	IL17RC
OMIM:616445	IL17RC
OMIM:252250	IL17RC
OMIM:613953	IL17RC
OMIM:613956	IL17RC
OMIM:114580	IL17RC
```

However, in OMIM, there is only one disease associated with [IL17RC](http://www.omim.org/entry/610925?search=il17rc&highlight=il17rc), 616445.  In fact, for some of these other diseases not associated with IL17RC, if you look at the entry in OMIM, it sometimes even specifically mentions that there is *no* association with that gene.  An example is [613956](http://www.omim.org/entry/613956?search=il17rc&highlight=il17rc), associated with IL17F, where the only mention of IL17RC is in the sentence, "No mutations were identified in the IL22 (605330), IL22RA (605457), IL10RB (123889), IL17RA (605461), IL17RC (610925), or IL17A (603149) genes."  Can you explain what constitutes a gene-disease association for HPO? Is mention of a gene in the OMIM description of a gene sufficient?

The result is that some phenotypes are associated with the gene that would not be otherwise associated.  For example, one of the phenotypes associated with 613956 is "Chronic mucocutaneous candidiasis".  If I search for all of the diseases associated with IL17RC and "Chronic mucocutaneous candidiasis", 616445 doesn't come up, while a half dozen others do:

```
grep IL17RC ALL_SOURCES_TYPICAL_FEATURES_diseases_to_genes_to_phenotypes.txt  | grep "Chronic mucocutaneous candidiasis"
OMIM:614162	IL17RC	84818	HP:0002728	Chronic mucocutaneous candidiasis
OMIM:247650	IL17RC	84818	HP:0002728	Chronic mucocutaneous candidiasis
OMIM:252250	IL17RC	84818	HP:0002728	Chronic mucocutaneous candidiasis
OMIM:613953	IL17RC	84818	HP:0002728	Chronic mucocutaneous candidiasis
OMIM:613956	IL17RC	84818	HP:0002728	Chronic mucocutaneous candidiasis
OMIM:114580	IL17RC	84818	HP:0002728	Chronic mucocutaneous candidiasis

grep IL17RC ALL_SOURCES_TYPICAL_FEATURES_genes_to_phenotype.txt | grep "Chronic muco"
84818	IL17RC	Chronic mucocutaneous candidiasis	HP:0002728
```

While this may be an interesting phenotype, being related to the same pathway in some way, and being part of the same cluster of diseases, if someone is interested in phenotypes based only on reported cases where a gene has been associated with particular diseases, I can't see a way to do that currently with the HPO files. 

In contrast, when I search ["Chronic mucocutaneous candidiasis" in this HPO browser](http://compbio.charite.de/hpoweb/showterm?id=HP:0002728), I *don't* see IL17RC as an associated gene (and likewise if I search [IL17RC](http://compbio.charite.de/hpoweb/showterm?gene=84818)), which makes me think there must be some version of a mapping file that follows a stricter gene-disease association than these files.  I can't find this more strict mapping file.  Would you be able to point me in the right direction to find this if it does exist, or otherwise provide suggestions on how to filter for more strict associations?

Thanks,

Andrew

**Comment by drseb** [comment]
In the files there was a merge step between OMIM- and Orphanet-entries as described in the paper. The gene-disease associations are taken from Orphanet and a genemap-file from OMIM that is now not freely available anymore. 
This is not done (or if done, then in a less inclusive way) in the HPO Browser. 

I agree that this might be slightly confusing, but in general I recommend just taking our disease-HPO association (this is what we control) and then do the gene-associations on your own.

**Comment by drseb** [comment]
I think this can be closed then. Re-open if you have further questions

**Comment by oleraj** [comment]
Thanks for the response.  I'll do as you recommended.
