### ISSUE TITLE
Planovalgus of the ankles.

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1202]
Please consider a new term for Planovalgus of the ankles.
(Severe intellectual disability-hypotonia-strabismus-coarse face-planovalgus syndrome,PMID:25078763)

**Comment by pnrobinson** [comment]
I thinkit is better to annotate to two HPO terms
1) pes planus
2) pes valgus
Note that the primary name of the latter term was "valgus foot deformity", but Ihavejust changed the primary name to pes valguys for consistency.
This is an example of bundling (i.e., pes valgoplanus refers to two phenotypic features). It is usually good not to create a separate HPO term for every possible combination of features.
