### ISSUE TITLE
Abnormal cellular phenotype

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#1204]
We have several requests for items such as Zebra bodies, which are abnormal phenotypes of multiple cells. This is not easily representable using the current organ based structure. MP has an upper level term called cellular phenotype. I think we need to have something similar.

**Comment by mellybelly** [comment]
Peter if you assign to me I can work on the CL aspects.

**Comment by pnrobinson** [comment]
Added the grouping term.
