### ISSUE TITLE
HP:0007409 - 'Absence of fat below the skin over entire body except buttocks, hips, and thighs.’

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#1209]
This term should be revised, and the disease should be annotated using atomic terms

**Comment by drseb** [comment]
relates to https://github.com/obophenotype/human-phenotype-ontology/issues/1153

**Comment by pnrobinson** [comment]
This term is currently used only for one disease
OMIM	606721	#606721 PARTIAL LIPODYSTROPHY, CONGENITAL CATARACTS, AND NEURODEGENERATIONSYNDROME; LCCNS;;LIPODYSTROPHY, PARTIAL, WITH CONGENITAL CATARACTS AND NEURODEGENERATION		

The description is Absence of facial, neck, and extremity fat was noted. Neurologic manifestations appeared to be minimal.
I will add these three annotations to the disease and merge/obsolete the term.
