### ISSUE TITLE
Difficulty of fine hand movements

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1210]
Please consider a new term for difficulty of fine hand movements.
Autosomal dominant Charcot-Marie-Tooth disease type 2 due to VCP mutation(PMID:25125609).

The patient was having difficulty using her hand for fine mouvement such as manipulating buttons or fastening jewellery,I think this can be a synonym related to Writer's cramp??

**Comment by pnrobinson** [comment]
In CMT,  weakness and muscle atrophy may occur in the hands, resulting in difficulty with fine motor skills (see for instance, http://www.ninds.nih.gov/disorders/charcot_marie_tooth/charcot_marie_tooth.htm). Therefore, this phenotype is not related to writer's cramp.

**Comment by pnrobinson** [comment]
HPO currently has delayed fine motor development and poor fine motor coordination -- neither of which are correct, so I agree the HPO needs a new term for this feature. Fine motor impairment, fine motor disability, hand function disability, fine motor skill dysfunction, impaired fine fotor skills are descriptions to be considered. Todo, consider whether we need a hierarchy, one of whose terms refers to hand.

**Comment by pnrobinson** [comment]
I think that this is the existing HPO term "Poor fine motor coordination" (HP_0007010). I am adding the other synonyms.
