### ISSUE TITLE
Retinal Pigmented Bone Spicules.

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1216]
Please consider a new term for Retinal Pigmented Bone Spicules.
(Stargardt disease,PMID:27739528).
Fundus photographs have showed this featureb in the periphery of the retinal periphery.
Superclasse: Abnormality of the retina??

**Comment by pnrobinson** [comment]
We will add this as a synonym to Bone spicule pigmentation of the retina (HP:0007737).
