### ISSUE TITLE
bilateral subacute visual failure.

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1220]
Please consider a new term for bilateral subacute visual failure as related synonym to Slow decrease in visual acuity.
Leber Hereditary Optic Neuropathy,PMID:20301353.

**Comment by psergouniotis** [comment]
I do not think that this should be a separate HPO term. 
You can use [Reduced visual acuity HP:0007663] or [Blurred vision HP:0000622] and then use modifiers [subacute] and [bilateral].

**Comment by pnrobinson** [comment]
I agree -- if there is a more specific term needed, please reopen a new request.
