### ISSUE TITLE
ovarian cystoma

### ISSUE THREAD

**Issue by GiselaFobo** [obophenotype/human-phenotype-ontology#1223]
I"m not sure if  "Ovarian serous cystadenoma" is a synonym to "Ovarian cystoma".

**Comment by pnrobinson** [comment]
According toNCI (Ovarian Cystadenoma (Code C4060)),  "Ovarian serous cystadenoma"  is a subtype of Ovarian cystoma. Note in the future we intend to collaborate with NCI on these phenotypes.

**Comment by GiselaFobo** [comment]
Could "ovarian cystadenoma" be added to the phenotype list?
