### ISSUE TITLE
Transient hypocortisolism

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1226]
Please consider a new term for Transient hypocortisolism.
PMID:25647543,Isolated sedoheptulokinase deficiency.
The patient suffered from short-fasting hypoglycemic episodes (with normal lactate and ketones) and postprandial hyperglycemia aggravated by the end of the first year of life persist in spite of frequent meals. Transient hypocortisolism was identified, but hypoglycemia did not respond to specific treatment.
Superclass:hypocortisolism.??

**Comment by pnrobinson** [comment]
Please use "Hypocortisolemia" (HP:0008220) with the modifier Transient -- note that I have just create the HPO term for Transient as HP_0025153
