### ISSUE TITLE
collateral circulation

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1227]
Please consider a new term for collateral circulation.
PMID:25647543,Isolated sedoheptulokinase deficiency.
The patien n°1 suffered from cholestasis and collatral circulation confirms Confirms portal hypertension.
Superclass:Portal hypertension???

**Comment by pnrobinson** [comment]
The preferred label should be "Collateral biliary circulation", which can be a manifestation of portal hypertension.

**Comment by LOURGHI** [comment]
The collateral venous circulation is seen on the skin of the patient and it is a sign that orientates portal hypertension whatever its cause, I suupose that the most adequate term would be collateral venous circulation CVC ???And this is a very common sign in  hepatology practice.

**Comment by pnrobinson** [comment]
I see -- then you mean this: https://en.wikipedia.org/wiki/Caput_medusae ?
