### ISSUE TITLE
hypomyelinization

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1228]
Please consider a new term for hypomyelinization.
PMID:25647543,Isolated sedoheptulokinase deficiency.
Brain magnetic resonance imaging (MRI) was normal in the neonatal period of this patient . At the age of 3 years, MRI showed ventricular enlargement, cerebral subcortical atrophy, hyperintense periventricular lesions, hypomyelinization, and a Chiari malformation type 1 .
Superclass:Abnormal CNS myelination???

**Comment by pnrobinson** [comment]
Pleas use the term HP_0003429, CNS hypomyelinization.
We do not have a term that is called just "hypomyelinization" because it is impossible to know without context whether CNS or PNS is meant.

**Comment by LOURGHI** [comment]
The term that exists on HPO is CNS hypomyelination, CNS hypomyelinization with Z doesn't exist,but I did not deepen the research, I will annotate with HP_0003429 CNS hypomyelination,
