### ISSUE TITLE
asymmetrical eyes.

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1229]
Please consider a new term for asymmetrical eyes .
PMID:25647543,Isolated sedoheptulokinase deficiency.
The patient had right eye larger.
Superclass:Abnormality of globe location??

**Comment by psergouniotis** [comment]
This is a very vague term and I do not think it is appropriate. What does larger mean? Is it [Increased axial globe length HP:0007800] which is a subclass of [Abnormality of globe size HP:0100887]? Is it that there is [Microphthalmia HP:0000568] in one eye?
For the purpose of this paper I would go for [Abnormality of globe size HP:0100887] but I do not think that a new HPO term should be introduced.

**Comment by pnrobinson** [comment]
I agree. There is a current HPO term "large eyes" which is also not a great term, but I think there is a case to be made for "Macrophthalmia" as a term (which could become the prefered label of "Large eyes" (I will need to check the annotated diseases), and then one can say that either one of the eyes was large or one of the eyes was small (microphthalmia), and one can use the modifier "unilateral"
