### ISSUE TITLE
Fix layperson annotation

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#1236]
Layperson annotation not transferred to obo format

**Comment by sbello** [comment]
The layperson synonyms are showing up in the OBO file appended to the term name. For example:
"Retinal detachment {has_synonym_type=..."
"Visual impairment {has_synonym_type=..."
These are then showing up in MGI's HMDC display (see below).  There are 1154 terms in the OBO file with {has_synonym_type=“layperson”} appended to the term name.  Please look into the formatting to see if this can be prevented. 
![pax6human](https://cloud.githubusercontent.com/assets/10979793/23080816/4870f7ec-f520-11e6-992b-668609545990.PNG)

**Comment by drseb** [comment]
afaik this is correct obo syntax. Thus you would have to fix your parsers.

correct @cmungall ?

**Comment by cmungall** [comment]
It is **valid** obo syntax, but it's not what is **intended**. We should use the subset of OWL that corresponds to OBO-Basic. I think someone is annotating synonym types in a non-standard way.

Background documentation:

 * [OBO Basic](http://owlcollab.github.io/oboformat/doc/obo-syntax.html#6.2)
 * [Mapping of synonym types](http://owlcollab.github.io/oboformat/doc/obo-syntax.html#5.7)

**Comment by drseb** [comment]
I did this. This is not about the synonyms, but about the label that we mark as lay.

**Comment by cmungall** [comment]
Ah my mistake.

Sorry, I thought we discussed this. I don't think it's a good idea to stray outside obo-basic. I thought we we agreed to do this as synonyms.

I suspect every single obo format consumer is going to get burned here, not just MGI.

Really everyone should abandon obo format and consume the json instead

**Comment by cmungall** [comment]
https://www.google.com/webhp?q=%22%7Bhas_synonym_type%3D%22layperson%22%7D%22

**Comment by cmungall** [comment]
Nice! We broke public medgen, public GARD, an earlier version of phenotips, ...

This is a cool way of finding out how who is using obo format without reading the specs! Like van halen and the M&Ms on the rider.

I'm joking of course, this is really bad. We need to patch this ASAP. Just a quick perl script to scrape these from the name fields prior to release first of all?

**Comment by drseb** [comment]
So there is no way of specifying a primary label as being lay?

**Comment by cmungall** [comment]
Not directly in obo basic. Of course, there is nothing to stop you adding in some other indicator that the primary label is lay. But the `name` field itself is required not to have axiom annotations in basic (basic basically exists to retroactively map to what people *think* obo format is, and the assumptions they make in their parsers)

**Comment by drseb** [comment]
Ok. But I really do not want to loose information in the OBO <-> OWL conversion. Let's discuss either soon on skype or next week at the meeting.

Sorry @sbello . No hotfix in the next days. I still recommend fixing the parser. I did the same for the ontologizer-library.

Sorry @all . I didn't mean to disturb your systems.

**Comment by mellybelly** [comment]
I agree we should fix this asap, but perhaps this issue is a good indication that its time to senesce OBO simple? It would be quite fussy to have a separate annotation prop to classify the primary label field.

**Comment by drseb** [comment]
@sbello hp.obo should now be more OBO-basic than before. I hope this helps. Please keep in mind that your parsers should be aware of layperson-tags for the synonyms.
