### ISSUE TITLE
Which term should I use for poor exercise tolerance?

### ISSUE THREAD

**Issue by petkraw** [obophenotype/human-phenotype-ontology#1246]

**Comment by drseb** [comment]
How is the tolerance measured? Multiple parameters?

**Comment by pnrobinson** [comment]
There is a term, HP_0003546, "Exercise intolerance". I will add "Poor exercise intolerance" as a synonym. I agree with Seb it would be good to have a better and more precise definition, but this is a common descriptor used often, so there needs to be a term for it.
