### ISSUE TITLE
Crumpled ear helice

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1247]
Please consider a new term for Crumpled ear helice as a synonym of Overfolded helix???
PMID:25195018.

**Comment by pnrobinson** [comment]
This looks simply like overfolded helix. I do not think that "crumpled" ear helix is a good description of this, as crumpled is more than just overfolded (see the picture here): http://onlinelibrary.wiley.com/doi/10.1002/ajmg.a.32599/full
I think that this paper can be annotated with overfolded helix simply.
