### ISSUE TITLE
red eyes

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#1259]

**Comment by psergouniotis** [comment]
This not an easy one. Should "red eyes" exist only as a lay term? 
"Conjunctival hyperemia" (syn conjunctival injection, conjunctival vascular congestion) could be used instead (subclass of HP:0000502). This is typically (but not exclusively) associated with conjuctivitis.

"Superficial episcleral vessel hyperemia" & "deep episcleral vessel hyperemia" are two other useful terms. These can be associated with episcleritis and scleritis (http://eyewiki.aao.org/Episcleritis, http://eyewiki.aao.org/Scleritis), two other causes of red eye.

"Circumlimbal hyperemia" (syn ciliary flush) is another term. This 'red eye subtype' is often associated with anterior uveitis.

**Comment by pnrobinson** [comment]
Remember that the HPO is meant to capture clinical observations and not pathophysiology; 'red eye' is a very common sign and often a physician will not examine further or not know if it is conjunctivitis or episclertitis etc. Do you think that ther canbe a kind of subhierarchy around red eye?

**Comment by psergouniotis** [comment]
OK. Agree that "red eye" should be a term (perhaps subclass of HP:0008047). Some subclasses of "red eye" could include:
* conjuctival hyperemia (syn conjunctival injection, conjunctival vascular congestion); a subclass of this could be "circumlimbal hyperemia" (syn ciliary flush)
* superficial episcleral vessel hyperemia
* deep episcleral vessel hyperemia.
