### ISSUE TITLE
New Term Request: Fibromyalgia

### ISSUE THREAD

**Issue by pbuczkowicz** [obophenotype/human-phenotype-ontology#1286]
Please consider adding the term Fibromyalgia

**Comment by pnrobinson** [comment]
Hi!
Fibromyalgia is not a phenotypic feature, it is a disease, and thus it should be coded with Disease Ontology or some related disease resource. There are five major phenotypic feature associated with fibromyalgia, and for each of them HPO terms already exist to varying levels of detail: (1) widespread musculoskeletal pain accompanied by (2)fatigue, (3) sleep, (4)memory and (5)mood issues.

**Comment by pbuczkowicz** [comment]
Hi Peter,
I agree it is a disease, however there are other other similar scenarios in the HPO. For example, Medulloblastoma is be a phenotypic feature of Gorlin Syndrome, but itself be a diagnosed disease with its own set of symptoms; ataxia, headache, nausea, visual impairment. Another example of this in the HPO is diabetes, which can be both an HPO term, and a diagnosis with its own associated phenotypes.

**Comment by drseb** [comment]
OMIM has two entries with Fibromyalgia as clinical feature: http://www.omim.org/search/?index=entry&search=Fibromyalgia&filter=cs_exists%3Atrue&sort=score+desc&start=1&limit=10&retrieve=clinicalSynopsis
