### ISSUE TITLE
Merge Osteopenia?

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#1292]
HP:0000938 osteopenia
vs.
HP:0004349 reduced bone mineral density

**Comment by pnrobinson** [comment]
If you look at the definition, the reason why the classes are not equivalent is stated clearly. We could add some differentia to the definition. The easiest might be to add "mild", although there are numerical criteria.

**Comment by drseb** [comment]
Ok. Thanks for checking. We have to be careful with synonyms though.
I didn't have the time to look at defs, this was just the result of script.
