### ISSUE TITLE
Merge Hypodontia?

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#1293]
HP:0009804 reduced number of teeth
vs.
HP:0000668 hypodontia

did we discuss this before?

**Comment by nicolevasilevsky** [comment]
I feel like maybe we did discuss this before.

In this case, the definition of 'Reduced number of teeth' is 
The presence of a reduced number of teeth as in Hypodontia or as in Anodontia.

So it seems slightly different from hypodontia.

**Comment by pnrobinson** [comment]
We need to revisit this and to describe the differentiating criteria as a comment to the term. I think that Hypodontia and Adontia have specific creiteria, but reduced number of teeth can start at 32-1, which does not yet fulfil the criteria for hypodontia.

**Comment by pnrobinson** [comment]
Actually, reduced number of teeth is the parent term for several terms that have more specific definitions (including hypodontia). I think the hierarchy is OK, but we might want to make the logical definitions for hypodontia more specific-- it's from 1 to 6 teeth; not sure how we would do this within the confines of our current data structures.
