### ISSUE TITLE
Elevated Gamma-glutamyl transpeptidase

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1294]
Please consider a new term for Elevated Gamma-glutamyl transpeptidase .
Primary biliary cirrhosis, PMID:26261733.
Super classe:Abnormal enzyme/coenzyme activity???

**Comment by pnrobinson** [comment]
Gamma-glutamyl transferase (GGT) is elevated with most liver diseases and with bile duct damage, however there are extrahepatic causes of GGT elevation including pancreatitis, prostate carcinoma, breat carcinoma, lung carcinoma, systemic lupus erythematosus, and congestive heart failure.
