### ISSUE TITLE
interlobular biliary ducts lesion

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1295]
Please consider a new term for interlobular biliary ducts lesion.
Primary biliary cirrhosis,PMID:26261733.
in the meantime,I have annotated the desease with Abnormality of the intrahepatic bile duct HP:0011040.

**Comment by pnrobinson** [comment]
I think this term should be "Interlobular bile duct destruction" for Primary biliary cirrhosis. See also https://www.ncbi.nlm.nih.gov/pubmed/16177252
