### ISSUE TITLE
autoimmune hepatitis

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1296]
Please consider a new term for autoimmune hepatitis. 
Primary biliary cirrhosis,PMID:26261733.
ten percent to  twenty  percent  of  patients,  are  presented  with fluctuating or persistent biochemical and histological evidence of auto-immune hepatitis.
Super classe:Hepatitis or Autoimmunity??

**Comment by pnrobinson** [comment]
I think this is best modelled as a disease entity and not a phenotypic feature. The clue is that it contains something that can be ragarded as a phenotypic feature (inflammation of the liver) but also the etiology: autoimmune.
