### ISSUE TITLE
vanishing bile duct syndrome

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1297]
Please consider a new term for vanishing bile duct syndrome .
In Primary biliary cirrhosis,a small minority of patients, develop a very rapid onset of vanishing bile duct syndrome with serious cholestatic jaundice and quick progress to cirrhosis in less than 5 years.
PMID:26261733.
Super classe:Abnormal biliary tract morphology HP:0012440.

**Comment by pnrobinson** [comment]
This is a disease ("syndrome") and not a specific phenotypic feature.
