### ISSUE TITLE
excessive daytime somnolence

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1298]
Please consider a new term for excessive daytime somnolence.
In Primary biliary cirrhosis,symptoms of autonomic dysfunction like orthostatic hypotension, excessive daytime somnolence and  sleep  disturbance  have  been  reported.
I find this term interesting to add as  a synonym of Somnolence HP:0001262.
PMID:26261733.

**Comment by pnrobinson** [comment]
Thanks for this suggestion. I think that the word "somnolence" means simply  a state of strong desire for sleep. Sleepiness is a synonym. Somnolence itself can be normal (e.g., around midnight right before one goes to sleep). The HPO term is meant to indicate excessive daytime somnolence. Therefore, I will change the primary label and add "excessive daytime sleepiness" as a synonym.

**Comment by LOURGHI** [comment]
Synonyme =Daytime sleepiness (Among the symptoms of respiratory insufficiency,PMID:27514291)
