### ISSUE TITLE
remove HP:0003421 Platyspondyly (childhood)

### ISSUE THREAD

**Issue by azankl** [obophenotype/human-phenotype-ontology#1309]
I find terms with age of onset as part of the term problematic. This particular term is only annotated to a single disease (OMIM:215150 OTOSPONDYLOMEGAEPIPHYSEAL DYSPLASIA), so should be easy to remove this subclass and use platyspondyly (HP:0000926) instead.

**Comment by drseb** [comment]
I see this is already obsoleted. Should be visible in new release. We need to update some annotations for common disease @pnrobinson 


```
DO-DOID_0007938.tab
DO-DOID_0012804.tab
DO-DOID_0013481.tab
DO-DOID_0014286.tab
MESH-D004392.tab
MESH-D015838.tab
```

**Comment by pnrobinson** [comment]
As soon as Webphenote is up and running, we need to start revisiting the common disease stuff. We also need to decide whether to use MeSH, DO or MONDO.

**Comment by drseb** [comment]
We have now DO and MeSH. I think, one can apply MONDO downstream and we don't have to decide to use only one of these resource.

**Comment by cmungall** [comment]
Yes, MonDO's primary role is to bridge. I think it will make sense to use DO as the primary identifiers for common diseases.
