### ISSUE TITLE
Retinal vascular leakage

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1310]
Please consider a new term for Retinal vascular leakage.
This is one of the characteristic signs of Birdshot chorioretinopathy.
It is cited thus in the following article,
PMID:27847627.
Superclass:Abnormality of the retinal vasculature??

**Comment by psergouniotis** [comment]
"Leakage of retinal vessels" is very difficult to see on fundus examination (one sees "retinal exudates" or "retinal oedema" instead). To diagnosis "Leakage of retinal vessels" one should perform fundus fluorescein angiography. This is a commonly performed test in ophthalmology and leakage, staining and pooling of dye are frequent findings. I think we will need some terms around "abnormal fundus fluorescein angiography" - I could have a look at this at some point.

For birdshot, retinal vascular leakage reflects retinal vasculitis. The characteristic finding is HP:0025188

**Comment by pnrobinson** [comment]
There are a few fluorescein angiography terms.
There is a term "Leakage of dye on fundus fluorescein angiography" that can be used for this (HP_0025320).

**Comment by LOURGHI** [comment]
I don't find this term HP_0025320 online...

**Comment by drseb** [comment]
I also don't see any term like this
