### ISSUE TITLE
extrafoveal choroidal neovascularization

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1312]
Please consider a new term for extrafoveal choroidal neovascularization.
A patient with Birdshot chorioretinopathy deveolped extrafoveal choroidal neovascularization Three years after the onset of the disease.
PMID:27847627.
Superclass:Choroidal neovascularization of the macula??

**Comment by pnrobinson** [comment]
Looking at the annotations, the current term Choroidal neovascularization of the macula actually is not restricted by macular location, which is not reflected inthe current classification as noted above. I will remove the 'of the macula'
