### ISSUE TITLE
keratic precipitates

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1314]
Please consider a new term for keratic precipitates.
It is described as a criterion of exclusion of the Birdshot chorioretinopathy.
PMID:26530345.
Superclass:Abnormality of the cornea??

**Comment by psergouniotis** [comment]
I agree that the term "corneal keratic precipitates" could be added (perhaps as a subclass of "Abnormality of corneal endothelium").
