### ISSUE TITLE
abnormal convexity of the lower limb metaphyseal borders.

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1316]
Please consider a new term for abnormal convexity of the lower metaphyseal borders.
A clinical  sign observed in Eiken syndrome,PMID:6734674,There are radiological images that illustrate the anomaly.
Superclass:Lower-limb metaphyseal irregularity??

**Comment by pnrobinson** [comment]
I think it would be best to annotate simply to lower limb metaphyseal abnormality, as this description seems specific to this publication and not some general recognizable feature.
