### ISSUE TITLE
Knee pain

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1317]
Please consider a new term for Knee pain.
Superclass:Abnormality of the knees??
Eiken syndrome,PMID:6734674.

**Comment by LOURGHI** [comment]
Superclass:Arthralgia??

**Comment by pnrobinson** [comment]
There already is a term called knee plain, please see HP:0030839

**Comment by drseb** [comment]
Note, that this term isn't shown in the HPO browser because the browser is showing an older HPO version

**Comment by LOURGHI** [comment]
now I understand lol.
