### ISSUE TITLE
Limitation of hip flexion

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1319]
Please consider a new term for Limitation of hip flexion.
Eiken syndrome,PMID:6734674.
Superclass:Abnormality of the hip joint??

**Comment by pnrobinson** [comment]
There are some terms under HP_0008800, limited hip movement, including hip contracture, which I think might be appropriate. The article does not have that much detail. There are abduction and extension hip contractures and we should come back to this with orthopedic input in the future. I think probably Hip contracture is the best term for now.
