### ISSUE TITLE
pointed fingertips 

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1320]
Please consider a new term for pointed fingertips .
Eiken syndrome,PMID:6734674.
Superclass:Abnormality of the fingertips??

**Comment by pnrobinson** [comment]
Is this synonymous with tapered finger?
Tapered finger  HP_0001182
I cannot access that article, could you send it to me via email?

**Comment by LOURGHI** [comment]
_**I think the fingers can be tapered without being pointed and pointed without being tapered**_

**Comment by pnrobinson** [comment]
@LOURGHI I am unable to access this article about Eiken syndrome, and this feature is not mentioned in the more recent articles. It is hard to tell if the authors really were king a distinction to taper fingers without seeing photographs of the affected patients. Can you provide more detail? We do not want to make an HPO term unless this is a recognizable and distinct clinical entity, and one mention in the paper from 1984 is not convincing with photographs. I will close this issue for now, but please reopen with more information if available.
