### ISSUE TITLE
acetabular roofs poorly developed. 

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1322]
Please consider a new term for acetabular roofs poorly developed.
Patient had narrow iliac wings and acetabular roofs poorly developed.
Eiken syndrome,PMID:6734674.
Superclass:Abnormality of the acetabulum??

**Comment by pnrobinson** [comment]
This description is vague -- I think that "Abnormality of the acetabulum" would be one possible annotation, but we should try to define the precise abnormality of the acetabular roof. As mentioned in another comment, I do not have access to this article, could you send it?

**Comment by pnrobinson** [comment]
There are a number of terms such as "Flat acetabular roof" that describe specific abnormalities. I would annotate to one of them or simply to abnormality oif the acetabulum. Please reopen withmore detail if necessary.
