### ISSUE TITLE
Thick growth plates

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1324]
Please consider a new term for Thick growth plates.
Short stature, Brussels type,PMID:8867654.
Very rare desease bu I think that the sign is interesting.
Superclass:Abnormality of limbs??

**Comment by pnrobinson** [comment]
There is a term called Enlarged epiphyses, but this is not an optimal term label, because we do not know if the enlargement is side-to-side (widened) or increased height (thickened). I will ask Andreas Z about this.

**Comment by drseb** [comment]
he is on GH. Let's see if he see this: ping @azankl

**Comment by pnrobinson** [comment]
This was my error we need a new subhierarchy for growth plates -- azankl advised me already by email. In the works!

**Comment by drseb** [comment]
Ok
