### ISSUE TITLE
venous occlusion

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1327]
Please consider a new term for venous occlusion.
Neovascular glaucoma,PMID:1697175.
Superclass:Venous abnormality?

**Comment by pnrobinson** [comment]
I think you are referring to retinal vein occlusion? There is a term for this, HP_0012636. I will add a synonym of retinal venous occlusion.

**Comment by LOURGHI** [comment]
I updated the annotation with retinal vein occlusion HP_0012636
But it would not be useful to add venous occlusion and arterial occlusion us a subclasses of vascular abnormalities???

**Comment by pnrobinson** [comment]
Good suggestion,thanks
