### ISSUE TITLE
posterior segment ischemia

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1328]
Please consider a new term posterior segment ischemia.
 Neovascular glaucoma treatment was focused on reducing the posterior segment ischemic process that caused the formation of new vessels,through panretinal photocoagulation. 

Neovascular glaucoma,PMID:27895936.
Superclass:Abnormality of the posterior segment of the globe??
I hope that it is a good term despite that it contains a physiopathological definition!!

**Comment by psergouniotis** [comment]
Although 'posterior segment ischaemia' is used in ophthalmic practice, I would be inclined to use "retinal ischaemia" instead. Perhaps this could be added as a subclass of Abnormality of the retinal vasculature (HP:0008046). 

Ischaemic changes in the retina are, in general, seen in fundus fluorescein angiogram so perhaps a term that would reflect how the observer decided ischaemia is present should be considered.

**Comment by pnrobinson** [comment]
I think that this is better conceptualized as a disease, see
https://en.wikipedia.org/wiki/Posterior_ischemic_optic_neuropathy
It would be better to either annotate to the disease or to annotate the actual phenotypic features that were observed.
