### ISSUE TITLE
histological features in HPO

### ISSUE THREAD

**Issue by azankl** [obophenotype/human-phenotype-ontology#1329]
Are histological features meant to be part of HPO? I found the term Multinucleated giant chondrocytes in epiphyseal cartilage (HP:0030330), which is an histological term, but that is the only bone histology related term I could find. If histological features are part of HPO, I could suggest some more bone histological terms. If histology is not part of HPO, HP:0030330 should be removed.

**Comment by pnrobinson** [comment]
Hi Andreas -- histology is definitely within scope for HPO -- so please suggest additional abnormal histology terms. I will close this request for now, but please make a new request for each term or send an excel file if that is inconvenient.
