### ISSUE TITLE
Question regarding annotations file(s)

### ISSUE THREAD

**Issue by lawrlee** [obophenotype/human-phenotype-ontology#1331]
Apologies if this is the incorrect place to ask this, but I have not been able to establish email contact. I am using the phenotype annotations provided by the Jenkins job here

http://compbio.charite.de/hudson/job/hpo.annotations/lastStableBuild/

I realize that the OMIM licensing now precludes you doing these builds. I have an OMIM license and have been trying to reverse engineer the methods for creating these files by using OMIM, Orphanet, and Disgenet directly:

http://compbio.charite.de/jenkins/job/hpo.annotations/lastSuccessfulBuild/artifact/misc/phenotype_annotation.tab
http://compbio.charite.de/jenkins/job/hpo.annotations.monthly/lastSuccessfulBuild/artifact/annotation/ALL_SOURCES_ALL_FREQUENCIES_diseases_to_genes_to_phenotypes.txt

But have found some inconsistencies with the HPO->OMIM associations and also the gene counts that are on the viewer (http://compbio.charite.de/hpoweb/showterm). 

Can anybody point me to a resource or process for those Jenkins jobs? Thanks!

**Comment by drseb** [comment]
We have worked on the annotation data (i.e. OMIM->HPO) over the last 8 years, so there is no single method to re-create these. It is a mixture of text-mining, expert knowledge, annotation workshops etc...

**Comment by pnrobinson** [comment]
If you would like to point out any inconsistencies, we will check them. We have added to the OMIM annotations in many cases, going into more detail. Of course, there may be some errors on our part. We are currently revising our entire pipeline because of the licensing issues. We will be adding more of our own annotations shortly. The annotation pipeline should be updated very shortly.

**Comment by lawrlee** [comment]
Thanks for the responses. Below are a few examples where I could not confirm the information in the HPO viewer vs. the annotation files. I could well be looking at the wrong file(s) for the target information or processing the information incorrectly and would greatly appreciate pointing me in the right direction.

1. HP:0006088
    - The HPO browser lists OMIM:186200 and gene LMBR1 as associated with the HPO term http://compbio.charite.de/hpoweb/showterm?id=HP:0006088
    - The annotations provided in the `ALL_SOURCES_ALL_FREQUENCIES_diseases_to_genes_to_phenotypes.txt` show two genes, LMBR1 and SHH, as associated.
```
+-------------+--------+--------+-------------+------------------------------------------+
| DiseaseText | Symbol | GeneID | PhenotypeID | PhenotypeName                            |
+-------------+--------+--------+-------------+------------------------------------------+
| OMIM:186200 | LMBR1  |  64327 | HP:0006088  | 1-5 finger complete cutaneous syndactyly |
| OMIM:186200 | SHH    |   6469 | HP:0006088  | 1-5 finger complete cutaneous syndactyly |
+-------------+--------+--------+-------------+------------------------------------------+
```
2. HP:0000878
    - The browser lists 14 OMIM annotations and 10 gene annotations. http://compbio.charite.de/hpoweb/showterm?id=HP:0000878
    - The `ALL_SOURCES_ALL_FREQUENCIES_diseases_to_genes_to_phenotypes.txt` has
        - 11 annotated OMIM terms, missing 258040, 264480, 309610.
        - 35 annotated gene terms; additional ATRIP, CENPE, CENPJ, CEP152, GABRD, GATA1, GPX4, HDAC6, KCNAB2, PCNT, PLK4, PRDM16, RBBP8, RPL11, RPL15, RPL26, RPL35A, RPL5, RPS10, RPS17, RPS24, RPS26, RPS28, RPS29, RPS7, SKI, TSR2; missing PRS.
    - The `phenotype_annotation.tab` file only contains OMIM:309610 and PMID:18245432 in the DB:References column
3. HP:0011458
    - The browser lists 667 OMIM annotations, 7 Decipher annotations, 192 Orphanet annotations, and 557 gene annotations http://compbio.charite.de/hpoweb/showterm?id=HP:0011458
    - The HPO term is absent in `ALL_SOURCES_ALL_FREQUENCIES_diseases_to_genes_to_phenotypes.txt`, but present in `ALL_SOURCES_ALL_FREQUENCIES_phenotype_to_genes.txt`.
    - The `ALL_SOURCES_ALL_FREQUENCIES_phenotype_to_genes.txt` file contains 933 gene annotations
    - The Orphanet `en_product4_HPO.xml` file contains one Orphanet annotation, 99879, which is not present in the browser set.

**Comment by lawrlee** [comment]
@pnrobinson, just checking in to see if any of the above inconsistencies have been examined or not.

**Comment by drseb** [comment]
@lawrlee I have updated the downloadable files. The HPO Browser now uses these files as well. See http://human-phenotype-ontology.github.io/2017/01/23/release_jan.html
