### ISSUE TITLE
papillae

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1335]
_**Please consider a new term for papillae.
Papillae and blepharitis were present in 65% of patients with  atopic keratoconjunctivitis.PMID:26278858.
Superclass:conjunctivitis??**_

**Comment by pnrobinson** [comment]
Will create term
Conjunctival papillae
Def: Raised tissue masses located on the palpebral conjunctiva with a central vessel. Papillae are created by a focal infiltration of inflammatory cells.
Comment: Papillae may be observed with papillary conjunctivitis. The inflammatory cells in the papillae may differ according to the cause. For instance, eosinophils predominate in allergic conditions and neutrophils in bacterial disease.
