### ISSUE TITLE
term request for trichoepithelioma

### ISSUE THREAD

**Issue by petkraw** [obophenotype/human-phenotype-ontology#1341]
Hi there, 
trichoepithelioma are the pathognomonic features in OMIM 601606, 605041, ect, Could you add this feature, or is there already something we should use?
Thanks! 
Peter

**Comment by pnrobinson** [comment]
The NCI says that Trichoblastoma is now the preferred label.
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI_Thesaurus&ns=NCI_Thesaurus&code=C27132
Would this work for you?
We are in the planning to coordinate closely with NCI on cancer concepts but I will add the term for now.

**Comment by petkraw** [comment]
I think it would be great to have trichoepithelioma at least as synonym for trichoblastoma. geneticists will probably stick to trichoepithelioma for while, probably as long as it is in use at OMIM.

**Comment by pnrobinson** [comment]
However, according to this page they are not synonymous
http://www.dermnetnz.org/topics/trichoblastoma/. I will add Trichoepithelioma now, need to coordinate.
