### ISSUE TITLE
uveal ectropion

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1346]
_**Please consider a new term for uveal ectropion.
Anterior  biomicroscopy can reveal:uveal ectropion in neovascular glaucoma.
PMID:27895936.
Superclass:Abnormality of the uvea??**_

**Comment by psergouniotis** [comment]
uveal ectropion (syn ectropion uveae) could be added as a subclass of "Abnormality of the iris"(HP:0000525). 

definition: Uveal ectropion is defined by the presence of iris pigment epithelium on the anterior surface of the iris (https://www.aao.org/eyenet/article/ectropion-uveae-secondary-glaucoma?november-2013)
