### ISSUE TITLE
fluorescein leakage 

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1347]
_**Please consider a new term for fluorescein leakage .
In neovascular glaucoma,iris  angiography  can  also  be  useful  in  some  borderline  cases  because  it  shows  fluorescein  leakage,  which  is  not  normally  seen.
PMID:27895936
Superclass:Abnormal fundus fluorescein angiography?? **_

**Comment by pnrobinson** [comment]
Adding term with label Leakage of dye on fundus fluorescein angiography and fluorescein leakage as exact synonym
