### ISSUE TITLE
ovary cancer

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1349]
_**Please consider a new term for ovary cancer.
If we consider that ovarian neoplasia can be benign or malignant.
PMID:22967383.
Superclass:Ovarian neoplasm??**_

**Comment by pnrobinson** [comment]
Ovarian cancer is not an exact description, and it is even used as a synonym of Ovarian neoplasm in this MeSH entry https://www.nlm.nih.gov/cgi/mesh/2017/MB_cgi?field=uid&term=D010051. There are well known difficulties with the distinction between malignant and benign, and this is why we are non-committal (Neoplasm) higher up in the hierarchy. Looking at the article, it is hard to tell what kind of ovarian cancer was meant. The most common type is Ovarian carcinoma. But annotating to Ovarian neoplasm would also be correct I think. There is no term rightnow for Ovarian carcinoma, and I am adding one with xrfe to NCI
