### ISSUE TITLE
disease severity

### ISSUE THREAD

**Issue by shaytzur** [obophenotype/human-phenotype-ontology#1354]
consider using the following paper as a basis for the logical definitions of the classes.

Systematic Classification of Disease Severity for Evaluation of Expanded Carrier Screening Panels
Gabriel A. Lazarin Felicia Hawthorne Nicholas S. Collins Elizabeth A. Platt Eric A. Evans Imran S. Haque
http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0114391

**Comment by pnrobinson** [comment]
The HPO terms are not referring to overall disease severity, which in this paper is defined in terms of overall impact on quality of live. The HPO terms are defining the severity of individual phenotypic features, and "severe" can be applied to any of the phenotype items in the HPO, e.g., "severe myopia". Obviously there is an overlap in terms of  the effects on quality of life for many HPO terms, but I do not think that the definitions used in the paper cited are appropriate for the HPO terms, which do have their own definitions.
If you do not agree, or if you would like to make suggestions or corrections for the terms in "Clinical modifier" please reopen this issue or make a new one.
Thanks! Peter
