### ISSUE TITLE
Swelling of the limbus

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1355]
_**Please consider a new term for Swelling of the limbus.
A clinical sign observed in 40%  of cases in Atopic keratoconjunctivitis 
PMID:26278858.
Superclass:Abnormality of the cornea??**_

**Comment by pnrobinson** [comment]
Should this be called "Limbal edema" and be a subclass of cornal stromal edema? I will check

**Comment by psergouniotis** [comment]
I agree that "limbal edema" could be added. 
It is not exactly the corneal stroma that is edematous. I would perhaps add the term "Abnormality of the corneal limbus" as a subclass of "Abnormality of the cornea". Then "Limbal edema" could be added as a subclass of "Abnormality of the corneal limbus"
