### ISSUE TITLE
Limbal neovascularization

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1356]
_**Please consider a new term for Limbal neovascularization.
observed in 48% of cases in Atopic keratoconjunctivitis.
PMID: 26278858.
Superclass:Abnormality of the cornea??**_

**Comment by pnrobinson** [comment]
This is a synonym of corneal neovascularization (the new blood vessels grow into the cornea from the limbus (edge)). I am adding the synonym.
