### ISSUE TITLE
Double fold upper lids

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1358]
_**Please consider a new term for Double fold upper lids.
Atopic keratoconjunctivitis,PMID:26278858.
Abnormality of the eyelid??**_

**Comment by pnrobinson** [comment]
This is similar to Infra-orbital fold/crease -- two current HPO terms. WIll look into the differentia. According to wikipedia, this is called "Dennie–Morgan fold" which is synonymous with infraorbital fold.

**Comment by psergouniotis** [comment]
I think "infraorbital fold" (HP:0011232) and "infraorbital crease" (HP:0100876) can be merged. Either of those can be used to describe the findings described in PMID:26278858.

**Comment by pnrobinson** [comment]
My understanding is that "crease" goes inward and "fold" goes outward, so I would propose making Dennie-Morgan fold a related synonym to infra-orbital fold (I think Dennie Morgan is used in the case of allergic conjunctivitis but not in general).

**Comment by pnrobinson** [comment]
I have looked at this further and I think that the phrase "double fold" is incorrect. There is one fold that is on the lower eyelid with Dennie Morgan. There are two halves of the eyelids that are separated by the fold. Except for the article, I have never seen the phrase double fold used in this context, and I do not think it is correct. I am going to add the "Dennie Morgan" as a related synonym.
