### ISSUE TITLE
Facial cutaneousfissures 

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1360]
_**Please consider a new term for Facial cutaneousfissures .
Observed in 65% of cases in Atopic keratoconjunctivitis.
Superclass:Abnormality of the skin??**_

**Comment by pnrobinson** [comment]
See
http://www.sciencedirect.com/science/article/pii/S0161642015007034

**Comment by pnrobinson** [comment]
I have looked at one literature and I think that this disease is characterized by excema-like changes on the face. I have not seen other sources that use the phrase facial cutaneous fissure, and therefore I do not think that this description generalizes well as an HPO term. Please use the existing term for excema for annotation.

**Comment by LOURGHI** [comment]
skin fissure HP:0031057???
I think ,it's more precise ,this term didn't exisit before, if I'm not mistaken.
