### ISSUE TITLE
delayed ability to stand

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1362]
_**Please consider a new term for : delayed ability to stand.
Observed in CAMOS syndrome PMID:20531441.
Superclass:Delayed gross motor development?? **_

**Comment by pnrobinson** [comment]
There are a number of milestones for motor development (like this) that might be useful HPO terms. Here is an article with some background information
https://www.ncbi.nlm.nih.gov/pubmed/23321410?dopt=Abstract
