### ISSUE TITLE
terms for flow cytometric data

### ISSUE THREAD

**Issue by petkraw** [obophenotype/human-phenotype-ontology#1364]
Hi there,
We have flow cytometric measurements of patients with GPI-anchor deficiencies with several GPI-linked markers. We would like to add these results in to an already pretty comprehensive list of HPO annotations of these patients. Would it be possible to add terms like:
reduced cell surface levels of CD55, CD59, CD16, ... on granulocytes/fibroblasts?
Thanks a lot!
peter

**Comment by drseb** [comment]
I think so. Can you give us a complete list so that we can estimate the number terms to be added.

**Comment by pnrobinson** [comment]
Sure -- it weould be helpful to have some definitions and pubmed ids. Also, it would be good to have a consistent strategy about cell types -- do we need a term for each cell type (probably yes), and how many cell types overall are needed?

**Comment by pnrobinson** [comment]
Adding terms for CD55, CD59, CD16. I will add further terms related to GPI defects as per curation.
