### ISSUE TITLE
hypoceruloplasminemia

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1365]
_**Please consider a new term for hypoceruloplasminemia.
severe perturbations of copper metabolism with hypocupremia, hypoceruloplasminemia and liver copper accumulation were observed in IRIDA syndrome.PMID:23423674
Superclass:Abnormality of copper homeostasis???**_

**Comment by pnrobinson** [comment]
This is synonymous with HP_0010837, Decreased serum ceruloplasmin. I am adding this as a synonym.
