### ISSUE TITLE
Protrusio Bulbi

### ISSUE THREAD

**Issue by petkraw** [obophenotype/human-phenotype-ontology#1368]
There doesn't seem to be a term/synonyme for protrusio bulbi :(
(we saw some people using proptosis instead, but we think protrusio bulbi is something else)

**Comment by pnrobinson** [comment]
Can you provide references & definitions that these are different? Proptosis is a protrusion of the globe (according to wikipedia, Most sources define exophthalmos/proptosis as a protrusion of the globe greater than 18 mm).

**Comment by petkraw** [comment]
D.H. says: "We didn't measure whether it's less than 18 mm, but if it's mild we call it protrusio bulbi, and if it's very prominent then proptosis" 
Maybe ask a ophtalmologist?

**Comment by pnrobinson** [comment]
I will ask Panos. I am not certain that this usage is universal, and it could be better to just use modifiers (mild, severe) etc. rather than have terms that are overlapping synonymous.

**Comment by petkraw** [comment]
agreed.

**Comment by psergouniotis** [comment]
I would add "Protrusio bulbi" as a synonym of "Proptosis" / "Exophthalmos" [HP:0000520]. In my mind they are the same thing and can be used interchangeably. If someone wants to comment on the extent, a severity modifier can be added (mild, severe etc).

Ideally, to diagnose proptosis /protrusio one would want to perform exophthalmometry. However, this is not absolutely necessary and there is no consensus on above what value proptosis can be diagnosed (differs depending on gender, ethnic origin etc).
