### ISSUE TITLE
fractured bones

### ISSUE THREAD

**Issue by petkraw** [obophenotype/human-phenotype-ontology#1369]
What is the rationale with fractured bones? There is e.g. a term for "fractured ulna" not for "fractured femur". In this case the closest that we could find was "fractured long bones". 

A more systematic approach to fractured bones would be great! Maybe offer "fractured" as quality to any bone?

**Comment by pnrobinson** [comment]
The fractured terms have been added as needed. There is a tension in ontologies between pre- and post-composition, and it is probably not a great issue to add more fractured terms-- the downside of postcomposition is that the software needed to be able to deal with it, which is not usually the case with software designed for the HPO afaik.
Please add new requests if you need some additional fractured terms.
