### ISSUE TITLE
sparse medial eyebrows

### ISSUE THREAD

**Issue by petkraw** [obophenotype/human-phenotype-ontology#1370]
There is a term for sparse lateral eyebrows (HP:0005338). But guess what we have now, a patient with sparse medial eyebrows. What should we do?

**Comment by pnrobinson** [comment]
Is it like this?
http://www.humpath.com/spip.php?article5190

**Comment by petkraw** [comment]
We saw it in a patient with molecularly confirmed "MRD29" (http://omim.org/entry/616078?search=mrd29&highlight=mrd29)
(Mutation in SETBP1)

Although the patient really has sparse emdial eyebrows, this is not necessarily a characterstic feature for this gene,...
