### ISSUE TITLE
'Short tubular bones of the hand'  should be a child of 'short long bone'

### ISSUE THREAD

**Issue by azankl** [obophenotype/human-phenotype-ontology#1373]
Since HPO seems to treat long bones and tubular bones as equivalent, short tubular bones of the hand (HP:0001248) should be a child of short long bones (HP:0003026).

**Comment by pnrobinson** [comment]
See #1374 long bones and short tubular bones of the hand are treated as the same category, this is common usage (see also https://en.wikipedia.org/wiki/Long_bone). Will add this subclass relation.
