### ISSUE TITLE
long tubular bones vs short tubular bones

### ISSUE THREAD

**Issue by azankl** [obophenotype/human-phenotype-ontology#1374]
Tubular bones can be further subdivided into short tubular bones (e.g. phalanges) and long tubular bones (e.g. femurs). HP:0003026 (short long bones) has the synonyms short tubular bones and shortened long tubular bones. Shortened long tubular bones suggests that only the long tubular bones (e.g. femurs) are shortened, while short tubular bones and short long bones implies both the long tubular bones and the short tubular bones are shortened. Since HPO generally does not seem to differentiate between short tubular bones and long tubular bones, I would suggest removing the synonym 'shortened long tubular bones' to remove this inconsistency. Alternatively, we could consider introducing terms for shortened short tubular bones and shortened long tubular bones, but I feel that is overkill and not really needed.

**Comment by cmungall** [comment]
AFAICT phalanges and femurs are traditionally classified as long bones. 
This is what many classic sources say, as well as ontologies like the 
FMA.

I'm not sure what the benefit would be in further subdividing these, 
seems non-standard?

So I agree 'shortened long tubular bones' is not really consistent, but 
perhaps it's OK to retain as a synonym and mark as non-standard?

**Comment by azankl** [comment]
agree further subdividing the long bones is not useful, thats why I thought the synonym 'shortened long tubular bones' was confusing, as it suggests we are distinguishing between short and long tubular bones and only the long tubular bones are included here. We could add 'shortened short tubular bones' as a synonym to make clear that both short and long tubular bones that are shortened are lumped under this term.
