### ISSUE TITLE
absence of the philtral complex

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1377]
_**Please consider a new term for absence of the philtral complex.
Observed in Familial median cleft of the upper and lower lips.
PMID:23860042.
Patients had  incomplete   median   cleft   of   the   upper   lip   that   led   to disruption  of  the  integrity  of  the  orbicularis  oris  muscle  in  the Cupid’s bow  region and absence of the philtral complex.
Superclass:Abnormality of the philtrum?? **_

**Comment by cmungall** [comment]
my understanding

`P-complex = P-column + P-proper`

(thus abnormalities of the P-proper would be subclasses of the P-complex)

Does it make sense to distinguish the complex from the philtrum proper in HPO? Can you have absence of the philtrum without having absence of the philtral complex?

**Comment by pnrobinson** [comment]
It seems to me that the authors are just stating that the patient has a median cleft of the upper lip. As far as I can see no additional information is conveyed by also saying absence of the philtral complex. At this point I would not recommend adding a term like this. Instead, just annotate to midline cleft of upper lip.
