### ISSUE TITLE
incomplete median lower lip cleft 

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1378]
_**Please consider a new term for incomplete median lower lip cleft .
Observed in Familial median cleft of the upper and lower lips.
PMID:23860042.
Superclass:Cleft lower lip??**_

**Comment by pnrobinson** [comment]
Please use the term for Median lower lip cleft. We do not want to start making indivudal HPO terms for each level of severity. If the "incomplete" is characteristic for a disease and acts as a differential diagnostic sign, then we can reconsider, please reopen this issue with more information.

**Comment by LOURGHI** [comment]
So I'll annotate with Median cleft lip and Cleft lower lip.
