### ISSUE TITLE
downgaze difficulty

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1381]
_**Please consider a new term for downgaze difficulty.
Observed in progressive supranuclear palsy.PMID:6847139
Superclass:Abnormality of eye movement??**_

**Comment by pnrobinson** [comment]
This is a child of vertical supranuclear gaze palsy. Added terms for upgaze and downgaze palsy.

**Comment by LOURGHI** [comment]
Thanks for the correction I will update the annotatio with the parent:vertical supranuclear gaze palsy
