### ISSUE TITLE
emotionally triggered spasms

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1382]
_**Please consider a new term for emotionally triggered spasms.
Observed in Stiff person syndrome .PMID: 27756410.
Superclass:Hyperkinesis??**_

**Comment by pnrobinson** [comment]
This is a much better article that describes stiff person syndrome.
The spasms are classified as myoclonus
The myoclonus can be triggered by various things or can be spontaneous. 
There are clinical modifiers in the HPO for "triggered by" that can be combined with "Myoclonus" to annotate this disease.
