### ISSUE TITLE
Increase in pressure of cerebrospinal fluid

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1384]
_**Please consider a new term for Increase in pressure of cerebrospinal fluid.
Observed in neuromyelitis optica.PMID:27852384.
Superclass:Abnormality of the cerebrospinal fluid??**_

**Comment by pnrobinson** [comment]
In clinical parlance this is referred to as Increased intracranial pressure (HP_0002516).
