### ISSUE TITLE
Increase in kidney size at IVU

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1388]
_**Please consider a new term for Increase in kidney size at IVU.
Observed in  congenital megacalycosis.PMID:16293636.
Superclass:Abnormal renal morphology??**_

**Comment by pnrobinson** [comment]
Please use the existing HPO term "Enlarged kidney(s)", I have altered the label of that term to Enlarged kidney, and added the sentence to the comment: There are several ways of diagnosing enlarged kidney including intravenous urography.
