### ISSUE TITLE
dendritic lesion

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1393]
_**Please consider a new term for dendritic lesion .
Observed in Stromal Keratitis.Patient had an overlying dendritic lesion that staine with fluorescein PMID:26989540.
Superclass:Abnormality of the cornea??**_

**Comment by psergouniotis** [comment]
To describe this phenotype please use "Herpetiform corneal ulceration" (HP:0007812; please see definition). Perhaps "dendritic corneal epithelial ulcer" could be added as a synonym so that people who search for "dendritic" will be directed to HP:0007812

**Comment by LOURGHI** [comment]
I updated the annotation with "Herpetiform corneal ulceration"HP:0007812.
