### ISSUE TITLE
limb myoclonus

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1394]
_**Please consider a new term for limb myoclonus.
Limb myoclonus was noted in Early myoclonic encephalopathy.PMID:27789573.
Superclass:Myoclonus??**_

**Comment by drseb** [comment]
I added this with superclass _Myoclonus_ and _Abn. of the musculature of the limbs_.

**Not sure about the second superclass**, as none of the other _Myoclonus of X_ class have multiple parents. Let me know if should remove this.

**Comment by pnrobinson** [comment]
I would say the superclass Myoclonus is sufficient -- Abs of the musculature of the limbs needs to evolve to be morphology and myoclonus is function.

**Comment by drseb** [comment]
But _Abnormality of X_ usually includes both **morphological** and **functional** abnormalities in HPO. For the sake of consistence, I remove the second superclass.

**Comment by pnrobinson** [comment]
Yes but myoclonus is not a morphological abnormality. I am syaing that we need to revisit the structure of this part of the HPO!

**Comment by LOURGHI** [comment]
Just to be sure that I understand ,we describe using HPO ,what we see??and myoclonus can be seen during consultation???
