### ISSUE TITLE
Cone dysfunction syndrome [HP:0030637]

### ISSUE THREAD

**Issue by psergouniotis** [obophenotype/human-phenotype-ontology#1399]
Recommended change for HP:0030637: Please make "Cone dysfunction syndrome" the primary term (and "Cone dysfunction" the synonym). 

Recommended definition: Retinal phenotype characterised by cone photoreceptor dysfunction and preserved rod system. The abnormality is typically stationary or very slowly progressive and findings may include reduced central vision, colour vision abnormalities, nystagmus and photophobia.

**Comment by pnrobinson** [comment]
I have updated the definition. Since the HPO is an ontology of phenotypic features, it generally doesn't l-ike to use the word syndrome in its title -- there is a large gray zone because people use items like this to annotate phenotypes of other diseases. Cone dysfunction syndrome is currently a synonym -- do you think we can leave it this way?

**Comment by psergouniotis** [comment]
I agree that using the term 'syndrome' is not appropriate for HPO. However, in this case, "cone dysfunction syndrome" is a widely used term that, in ophthalmic practice, reflects a specific phenotype. 

Due to the fact that the current primary term ("cone dysfunction") is vague and not intuitively recognised by ophthalmologists, I believe it would be helpful to make "cone dysfunction syndrome" the primary term. 

Indeed the medical literature is full of misnomers and "cone dysfunction syndrome" is one of them. However, it is a very useful one and, to my knowledge, no suitable, broadly-used alternative exists at present. I would therefore be grateful if you would consider making the above change.

**Comment by pnrobinson** [comment]
OK!
