### ISSUE TITLE
chemical pneumonitis

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1403]
_**Please consider a new term for chemical pneumonitis.
Observed in Mercury Poisoning.
Superclass:Interstitial pneumonitis?? **_

**Comment by LOURGHI** [comment]
Sorry,PMID:26678598.

**Comment by pnrobinson** [comment]
I think that chemical pneumonitis is not the phenotype that we observe, it is a description of the cause. I think that the disease "Mercury poisoning" should be annotated to Interstitial pneumonitis, which is the observed phenotypic feature.
