### ISSUE TITLE
Elevated Propionylcarnitine (C3) Levels - term

### ISSUE THREAD

**Issue by shaytzur** [obophenotype/human-phenotype-ontology#1405]
Hello,

We have a case with elevated propionylcarnitine (C3) levels, but we cant find a required term in HPO under Complement deficiency    http://compbio.charite.de/hpoweb/showterm?id=HP:0004431
(all the available terms are "**decreased** C3").

Is it possible to add the needed term (unless such term already exists)?

Thanks and Regards,
Shay

**Comment by pnrobinson** [comment]
I am sorry for the late response to this.
I believe that complement C3 (https://www.ncbi.nlm.nih.gov/gene/718) 
is not the same thing as propionylcarnitine. I had never seen the abbreviation C3 for propionylcarnitine before, but as far as I can see it is referring to the three carbons (see here: https://en.wikipedia.org/wiki/Propionic_acid).

**Comment by pnrobinson** [comment]
Could you please provide more information?

**Comment by pnrobinson** [comment]
I am adding the term
Elevated propionylcarnitine level  HP_0031544
An elevated level of propionylcarnitine in the circulation. Propionylcarnitine is present in high abundance in the urine of patients with Methylmalonyl-CoA mutase (MUT) deficiency.
