### ISSUE TITLE
Cerebrotendinous xanthomatosis

### ISSUE THREAD

**Issue by BrunOrpha** [obophenotype/human-phenotype-ontology#1406]
Please consider new term for **Cerebrotendinous xanthomatosis**
Rarely seen in Homozygous familial hypercholesterolemia (ORPHA391665/OMIM#143890)
Child of: Xanthomatosis (HP:0000991)
PMID 23759795

**Comment by pnrobinson** [comment]
Cerebrotendinous xanthomatosis is a disease with lots of manifestations.
I think you simply mean tendon xanthomas?

**Comment by BrunOrpha** [comment]
No, i didn't ment tendon xanthomas. I ment cerebral localisation of those xanthomas, which indeed leads to lots of manifestations.

**Comment by pnrobinson** [comment]
According to this review, the cebreal lipid deposition in this disease is not called "xanthoma"--
https://ojrd.biomedcentral.com/articles/10.1186/s13023-014-0179-4
and looking in PubMed for "cerebral xanthoma" doesnt yield articles. Can you provide a reference for this? Perhaps we should be using different terminology to describe this phenotype? Do you think the cited article is a good place to start?

**Comment by BrunOrpha** [comment]
Thank you for the message. I found this for homozygous familial hypercholesterolemia:
https://www.ncbi.nlm.nih.gov/pubmed/?term=hypercholesterolemia+AND+cerebral+xanthoma
I just asked Pr Eric Bruckert (from the last consensus):
https://academic.oup.com/eurheartj/article/35/32/2146/2481389/Homozygous-familial-hypercholesterolaemia-new
whether the name, pathophysiology and aspect is similar to the cerebrotendinous xanthomatosis:
http://www.neurology.org/content/67/11/E20.full.pdf+html
and i will get back to you.

**Comment by BrunOrpha** [comment]
So, indeed; we should be using different terminology to describe this phenotype

1/So apparently, although old papers like those:
https://www.ncbi.nlm.nih.gov/pubmed/6743074
https://www.ncbi.nlm.nih.gov/pubmed/6428514
do underline the existence of cerebral xanthomas in hypercholesterolemia, it is not clinically part of the homozygous familial hypercholesterolemia phenotype (as stated in the OJRD reviews) and seems to be very exceptionnal. The lesions are more part of the cerebral xanthomatosis phenotype, and the pathophysiology (quite mysterious) is distinct from the homozygous hypercholesterolemia (other CYP mutations).
2/Those lesions:
https://www.ncbi.nlm.nih.gov/pubmed/17159091
https://www.ncbi.nlm.nih.gov/pubmed/15061585
http://ojrd.biomedcentral.com/articles/10.1186/s13023-014-0179-4
do exist as part of the cerebral xanthomatosis. They are usually named "cerebral xanthoma" in French usual medical langage to sum up all the cerebral abnormalities. So, we should be using different terminology to describe this phenotype
