### ISSUE TITLE
NTRs/Layperson Synonyms: kidney disease 

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#1408]
Need to come back to these, creating a ticket so I can come back and review these: (anyone - feel free to comment)

- [x] needle pain (like pins and needles?)
- [x] tingling (maybe syn or child of Paresthesia?)
- [x] dull burning sensation with urination (maybe child of dysuria?)
- [x] pressure in my bladder (maybe child of functional abnormality of bladder?)
- [x] lightheaded
- [x] foam in urine/foamy urine/frothy urine  

[WebMD message board](https://messageboards.webmd.com/health-conditions/f/kidney-disorders/)

**Comment by pnrobinson** [comment]
@nicolevasilevsky Paresthesia is perhaps best translated with Pins and needles feeling. It is not necessarily pain.
Tingling can also be used as a LP synonym
"dull burning sensation with urination" seems too specific. I would LP-translate Dysuria with "Painful urination" and also "Difficult urination"
"Pressure in the bladder" is normal when you need to go, so this does not seem like a good term/translation to me, it would need more context I think.
"Lightheaded" also seems too general to understand out of context. What was it referring to?
"Foamy urine" would be a good term, this is often a sign of proteinuria
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3539097/
I need to run right now, but let's check that Foamy urine is not already a term and then add it. This can be the primary label and also the LP translation.

**Comment by pnrobinson** [comment]
Added foamy urine as HP_0031504

**Comment by pnrobinson** [comment]
dull burning sensation with urination => Adding as a related synonym (LP)

**Comment by pnrobinson** [comment]
pressure in my bladder => This is so context dependent that I would not add it as a synonym.
