### ISSUE TITLE
NTR: kidney pain

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#1409]
child of pain
Layperson term

**Comment by pnrobinson** [comment]
There is a term for flank pain, which might be better as the primary label - http://share.upmc.com/2015/04/why-do-my-kidneys-hurt/
Where did you get this TR from?

**Comment by drseb** [comment]
I think this is from patient descriptions

**Comment by nicolevasilevsky** [comment]
yes, this is from the WebMD message board. I can add kidney pain as a broad synonym of flank pain.

**Comment by pnrobinson** [comment]
I agree I think it is a broad synonym the way the layperson jargon uses it.

**Comment by pnrobinson** [comment]
I added this as a broad synonym with layperson type.
