### ISSUE TITLE
NTR/Layperson synonyms: ADD/ADHD

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#1410]
Should we add the following terms or synonyms?

- [ ] inability to focus/difficulty focusing/trouble focusing/difficulty concentrating/hard to concentrate (this came up in the neurological disorder message board too, see #1413)
- [ ] disorganization/disorganized thoughts/trouble staying organized
- [ ] racing thoughts / thoughts constantly running through your head
- [x] unhappy demeanor (opposite of HP_0040082 Happy demeanor)
- [ ] hopelessness (could be child of Abnormal emotion/affect behavior)
- [ ] wake up several times a night (could this be a synonym or child of Sleep-wake cycle disturbance?)
- [x] difficultly falling asleep (child of sleep disturbance?)
- [ ] lack of follow through 
- [ ] substance abuse (NTR, child of addictive behavior)
- [x]  suicidal thoughts
- [ ] explosive (child of HP_0006919 Abnormal aggressive, impulsive or violent behavior)
- [ ] fidgety
- [ ] talkative/talk a lot
- [ ] argumentative

WebMD message board related to ADHD: https://messageboards.webmd.com/health-conditions/f/add-adhd

**Comment by pnrobinson** [comment]
These are valuable terms -- we need more coverage of phenotypes like this. Let's consider how to structure the hierarchy for the new terms.

**Comment by pnrobinson** [comment]
@nicolevasilevsky Should we skype to tackle this list?

**Comment by nicolevasilevsky** [comment]
Sure, that would be great! I'll ask Shanez to schedule a call

**Comment by pnrobinson** [comment]
Is inability to focus the same as the current term "Short attention span"? I would think so. @nicolevasilevsky can weadd these as LP synonyms?

**Comment by pnrobinson** [comment]
Added unhappy demeanor HP_0031588

**Comment by pnrobinson** [comment]
Adding term Suicidal ideation (LP syn Suicidal thoughts),  HP_0031589

**Comment by pnrobinson** [comment]
I would add hopeless as a related synonym to depressivity

**Comment by pnrobinson** [comment]
Other than that I would suggest we close this issue, the other items are not reqlly great HPO terms, but we will need to systematically revisit the behavior branch of HPO. @nicolevasilevsky

**Comment by nicolevasilevsky** [comment]
Closing this issue, per Peter's suggestion above.
