### ISSUE TITLE
NTR/Layperson synonyms related to Brain & Nervous System Disorders

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#1413]
I'm reviewing the [WebMD message board](https://messageboards.webmd.com/health-conditions/f/brain-nervous-system-disorder)

Should we add the following terms or synonyms:
- [ ] eye strain/asthenopia
- [ ] NTs: slow speech, muffled speech (children of 'neurological speech impairment'?)
- [ ] "legs felt heavy and weak" - is there a term for the sensation of heavy legs?
- [ ] "Electric shock down left arm" - not sure what they are referring to here, could we create (or do we have) a term for this?
- [ ] "She has trouble getting her feet to move. Its almost like her feet are stuck to the floor." - is there a term or syn we could add for this?
- [ ] NT: full body paralysis
- [ ] pressure between eyes
- [ ] bulging eyes/eye bulge
- [ ] facial numbness/numb face (also- general numbness)
- [ ] blink at different rate
- [ ] "Inability to sneeze resulting in Hulk-like anger" - NT: hypoactivity of the sneezing reflex?
- [ ] NT: Brain fog (?) - commonly used phrase that sums up feelings of confusion, forgetfulness, and lack of focus and mental clarity. Or could be a synonym for confusion
- [ ] Syn or NT: difficulty concentrating. Maybe child of 'Abnormality of higher mental function'
- [ ] difficulty concentrating/poor concentration
- [ ] difficulty waking from slumber
- [ ] Twitching in pointer finger and thumb - NT: digit fasciculations?
- [ ] temporary blindness

**Comment by pnrobinson** [comment]
Asthenopia: def: Eye strain, i.e., a feeling of fatigue or discomfort of the eyes related to 'overuse' of the eyes in activities such as reading or working at the computer and often accompanied by lacrimation or headache.

**Comment by nicolevasilevsky** [comment]
@pnrobinson I can add the new term Asthenopia if that works for you.

**Comment by pnrobinson** [comment]
I added Asthenopia. I do not think the other items are specific enough to make good HPO terms actually (but see #1410 for difficulty concentrating).
