### ISSUE TITLE
need def for HP_0002381 aphasia

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#1414]
Recommended def:
A neurological speech impediment where a person has an inability to comprehend and formulate language because of damage to specific brain regions.
xref: https://en.wikipedia.org/wiki/Aphasia

**Comment by pnrobinson** [comment]
I think it is better to provide some additional context from an article such as this
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5306063/
I will do this.

**Comment by pnrobinson** [comment]
The LP synoym "saying wrong words" is incorrect and should be removed.
In general we need to add some more subclasses. This page (https://www.aphasia.org/aphasia-definitions/) is good but is describing diseases -- we need to get terms describing the atomic phenotypes in this list. Need to do some literature research.
