### ISSUE TITLE
NTR/Layperson synonyms related to cancer

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#1415]
reading the [WebMD message board for cancer](https://messageboards.webmd.com/health-conditions/f/cancer#pi157388622=2), should we consider adding the following new terms or synonyms:

- [ ] dry nipple, itchy nipple
- [x] bloody bowel movement/bloody stool

(maybe these are symptoms, not phenotypes - feel free to close if these terms are not appropriate)

**Comment by pnrobinson** [comment]
Bloody stool is currently synonym of HP_0025085. I will as bloody bowel movement.

**Comment by pnrobinson** [comment]
I have added dry nipple as HP_0031509
