### ISSUE TITLE
Term requests Tudor

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#1417]
Batch request:

https://docs.google.com/spreadsheets/d/1qHuj2UXmT5GzB6K0kiH1HvwO7mvRmBsjhmDjwlDV6E4/edit#gid=0

**Comment by pnrobinson** [comment]
As far as I can see all of the valid terms in the sheet have been added since this issue was opened. I am closing this issue, please open new issue with any remaingin term request!
