### ISSUE TITLE
Stroke like episodes

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#1423]
From tudors list:

> Stroke-like episodes - Vascular pattern
> Stroke-like episodes - Non-vascular pattern
> Stroke-like episode with resolution

**Comment by pnrobinson** [comment]
These items sound more like diseases than phenotypic features -- they seem to relate to etiology and have a time course. Does Tudor have a more detailed description of the clinical data by some chance?

**Comment by drseb** [comment]
All I have is this from Tudor: https://github.com/obophenotype/human-phenotype-ontology/issues/1417

**Comment by pnrobinson** [comment]
I am going to close this issue since it is hard to define a precise phenotypic abnormality from the available information.
