### ISSUE TITLE
Ventilatory support

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#1424]
From Tudor:

> Ventilatory support
> Ventilatory support - Improved over time
> Ventilatory support - Normalised
> Ventilatory support - Ongoing ventilartory support

From https://github.com/obophenotype/human-phenotype-ontology/issues/1417

**Comment by drseb** [comment]
Also in this context: 

Assisted breathing

**Comment by pnrobinson** [comment]
These are not phenotypes, they are treatment courses. Indirectly, we can conclude something about the phenotype (there must be something seriously wrong about the respiratory system if you need ventilatory support). I realize there are a few terms like this in the HPO but it is inconsistent and I suggest it be coded differently. Tudor, if you have more details, we can try to help with the annotations. (will send same message by email)
