### ISSUE TITLE
Non-convulsive status epilepticus

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#1426]
More details e.g. http://doosesyndrome.org/mae-explained/ncse

From tudors list https://github.com/obophenotype/human-phenotype-ontology/issues/1417

**Comment by pnrobinson** [comment]
There is a term Obtundation status (HP:0011151) currently, but this appears to be just one type of NCSE. See here https://www.ncbi.nlm.nih.gov/pubmed/17805245
I will expand this section accordingly.
