### ISSUE TITLE
Interictal terms

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#1427]
Unifocal interictal epileptiform activity
Multifocal interictal epileptiform activity
Generalised interictal epileptiform activity
Focal and generalised interictal epileptiform activity
Interictal background: Burst suppression
Interictal background: Hypsarrhythmia

from tudor
https://github.com/obophenotype/human-phenotype-ontology/issues/1417

**Comment by LCCarmody** [comment]
Unifocal interictal epileptiform activity-Multiple seizures that arise from the same scalp region.

Multifocal interictal epileptiform activity-Multiple seizures that develop from different scalp regions

(Citation for both definitions) 
The Treatment of Epilepsy: Principles & Practice
edited by Elaine Wyllie, Ajay Gupta, Deepak K. Lachhwani
https://books.google.com/books?id=ngmo0th_2X0C&pg=PR4&lpg=PR4&dq=The+Treatment+of+Epilepsy:+Principles+%26+Practice+edited+by+Elaine+Wyllie,+Ajay+Gupta,+Deepak+K.+Lachhwani&source=bl&ots=gSvJhFoHG-&sig=CMW96do8ht0yqKbUOZWeYboUD7M&hl=en&sa=X&ved=0ahUKEwjV3NHfiujSAhWIQyYKHTF5DnUQ6AEIXjAB#v=onepage&q=The%20Treatment%20of%20Epilepsy%3A%20Principles%20%26%20Practice%20edited%20by%20Elaine%20Wyllie%2C%20Ajay%20Gupta%2C%20Deepak%20K.%20Lachhwani&f=false

Interictal Background: Burst Suppression: An electroencepholagram (EEG) pattern in which high-voltage activity alternates with isoelectric quiescence. 
PMCID: PMC3286963

Interictal Background: Hypsarrhythmia: very high-voltage, disorganized pattern of EEG abnormality during the interictal state
PMCID: PMC1464162



Less Confidence in the following—it is an extrapolation from this book.  There is not a definition.

Focal Interictal epileptiform activity: An electroencepholagram pattern from the interictal period measuring highly localized high-voltage spikes.  

Epileptiform Activity, Seizures and Epilepsy Syndromes by LM Selwa, MD (Greenfield, Geyer and Carney Reading EEGs: A Practical Approach) https://books.google.com/books?id=DuzmRe5p7cYC&pg=PA93&lpg=PA93&dq=Epileptiform+Activity,+Seizures+and+Epilepsy+Syndromes+Linda+M.+Selwa,+MD+(Greenfield,+Geyer+and+Carney+Reading+EEGs:+A+Practical+Approach)&source=bl&ots=vnjse0Ulfs&sig=68EeI87H3u-mFvuzwdZmVtAvgFs&hl=en&sa=X&ved=0ahUKEwi5zp6aj-jSAhUPziYKHcwbBJkQ6AEIITAB#v=onepage&q=Epileptiform%20Activity%2C%20Seizures%20and%20Epilepsy%20Syndromes%20Linda%20M.%20Selwa%2C%20MD%20(Greenfield%2C%20Geyer%20and%20Carney%20Reading%20EEGs%3A%20A%20Practical%20Approach)&f=false

**Comment by pnrobinson** [comment]
These terms should go under HP_0025373, Interictal EEG abnormality

**Comment by pnrobinson** [comment]
(From Ingo Helbig)
"Interictal epileptiform activity" -- better primary label for "Epileptiform EEG discharges" (this is an existing term)

Definition should be:

Epileptiform activity refers to distinctive EEG waves or complexes distinguished from background activity found in in a proportion of human subjects with epilepsy, but which can also be found in subjects without seizures. Interictal epileptiform activity refers to such activity that occurs in the absence of a clinical or subclinical seizure.

**Comment by pnrobinson** [comment]
Burst suppression was HP_0010851

**Comment by pnrobinson** [comment]
I changed the label of Epileptiform EEG discharges as per Ingo's suggestion.

**Comment by pnrobinson** [comment]
Hypsarrhytmia is also present.
I think it would better to add additional terms at the neuro work shop later this year, and I will close this item.
