### ISSUE TITLE
NTR/Layperson synonyms related to Digestive health

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#1428]
reading the [WebMD message board for digestive health](https://messageboards.webmd.com/health-conditions/f/digestive-health#pi157388622=3), should we consider adding the following new terms or synonyms:

- [ ] balance issues - should this be added as a syn? maybe for gait imbalance?
- [x]  tingling - this term is coming up again.
- [ ] problem of trying to "catch my breath" - not sure if this should be added?
- [ ] nasty taste in mouth (or abnormal taste in mouth or something like that)
- [x] skin itching

**Comment by pnrobinson** [comment]
@nicolevasilevsky  
tingling is a LP syn for paresthesia
skin itching is pruritus (we have this already)
catching my breath seems to be too unspecific
balance issues also seems to be too unspecific, but probably gait imbalance is meant. Need more context
nasty taste in mouth -- I think that perhaps metallic taste in mouth is meant? https://health.clevelandclinic.org/2015/04/8-possible-causes-for-that-metallic-taste-in-your-mouth/
Do you have more context?

**Comment by nicolevasilevsky** [comment]
These are all from the [WebMD message board for digestive health](https://messageboards.webmd.com/health-conditions/f/digestive-health#pi157388622=3), this is where the nasty taste in mouth came from:

"My 10 year old son started having issues a couple days before his birthday in september. He said it felt like he was punched in the stomach, followed by a nasty taste in his mouth, then felt like vomiting, he'd throw up but it was all liquid. First..."

We don't have to add it though if it is too non-specific.

**Comment by pnrobinson** [comment]
I would be for not adding this but instead adding Metallic taste in mouth as a NTR.
