### ISSUE TITLE
Invalid character in phenotype_annotation.tab for entry OMIM:605714

### ISSUE THREAD

**Issue by sdumitriu** [obophenotype/human-phenotype-ontology#1429]
The sixth column has an invalid 0xFFFD character in place of the `0`: `OMIM:6�5714`

**Comment by pnrobinson** [comment]
Just fixed this error, thanks for pointing it out. It is also possible to use the tracker for annotations here: https://github.com/monarch-initiative/hpo-annotation-data

**Comment by drseb** [comment]
No this repo is private for OMIM-reasons
