### ISSUE TITLE
Check required: imported classes (esp. NCIT) should not be used in SubClassOf axioms

### ISSUE THREAD

**Issue by cmungall** [obophenotype/human-phenotype-ontology#1430]
hp-edit.owl brings in external ontologies like CL, GO, Uberon, NCIT to use in logical definitions.

The pattern is always something like

    HP = has-part some Q and inheres-in some X ...

never

    HP SubClassOf X

or

    X SubClassOf HP

unfortunately we have a case of an import class leaking into the HPO hierarchy:

hp-edit.owl
```
169562:SubClassOf(<http://purl.obolibrary.org/obo/NCIT_C4089> <http://purl.obolibrary.org/obo/HP_0005266>)
```

It's easy to do this accidentally in Protege. The neoplasm classes from NCIT are labeled the same way as HP classes.

**Comment by pnrobinson** [comment]
The latter is an error -- Seb, could we get Travis to check for this? I thought we had removed all of these errors a while back.

**Comment by cmungall** [comment]
This would be a really useful general purpose check to have across all ontologies and also datasources in dipper etc.

E.g.

 * ID spaces A and B should never be in a SubClassOf relationship
 * Ontology O should never state axioms about ID space A
 * ...

cc @balhoff

**Comment by drseb** [comment]
My checks were looking for HP subclass_of NCIT not NCIT subclass_of HP. Will add this check.

**Comment by drseb** [comment]
Extended checker. There is now a whitelist-file at https://github.com/obophenotype/human-phenotype-ontology/blob/master/src/format/subclass_whitelist.txt

Currently the checker fails with:


```
java -jar CheckSubclassAxioms.jar ../ontology/hp-edit.owl
found problematic inter-ontology subclass axioms
 - SubClassOf(<http://purl.obolibrary.org/obo/NCIT_C4089> <http://purl.obolibrary.org/obo/HP_0005266>)
 - SubClassOf(<http://purl.obolibrary.org/obo/HP_0002197> ObjectIntersectionOf(<http://purl.obolibrary.org/obo/HP_0001250> ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/RO_0002573> <http://purl.obolibrary.org/obo/PATO_0002403>)))
 - SubClassOf(<http://purl.obolibrary.org/obo/hp.owl#HP_0030915> <http://purl.obolibrary.org/obo/HP_0001317>)
make: *** [check-subclass-axioms] Error 1
```

**Comment by drseb** [comment]
> ID spaces A and B should never be in a SubClassOf relationship

not true for HP/UPHENO. This is why: https://github.com/obophenotype/human-phenotype-ontology/blob/master/src/format/subclass_whitelist.txt

**Comment by cmungall** [comment]
I meant that A and B could be filled in with any two ID spaces for a 
particular blacklist rule. Yr whitelist looks like a perfectly good 
approach too!

**Comment by kshefchek** [comment]
@drseb could you release a new version of HPO with these fixes?

**Comment by drseb** [comment]
The next release is scheduled for April 1st. Other options? How urgent?

**Comment by kshefchek** [comment]
Because our pipeline merges disease and phenotype ontologies, we now have 52 classes categorized as both diseases and phenotypes (see https://github.com/monarch-initiative/monarch-disease-ontology/issues/197). We could wait until April 1st or consider some other options.
