### ISSUE TITLE
representing spectrums as subclasses

### ISSUE THREAD

**Issue by mellybelly** [obophenotype/human-phenotype-ontology#1433]
This ticket is largely to be parked for discussion later.

In a number of places in HPO there are cases where the subclass hierarchy is essentially trying to describe a spectrum. This is needed to adhere to the true path rule, the most severe is the child term, and the more atomic phenotype the parent term. This is logically consistent but biologically unintuitive. 

This ticket is to discuss this later if there should be some other relationship between the terms. This is not dissimilar to something being somewhat hypoplastic, very hypoplastic, and aplastic, too. Need to think about how the current implementation or any changes would affect the semantic similarity or annotations.

See below for example:

<img width="294" alt="screen shot 2017-03-14 at 10 19 19 pm" src="https://cloud.githubusercontent.com/assets/796636/23934742/955eeae4-0904-11e7-9373-dc8b764bf7bc.png">

**Comment by pnrobinson** [comment]
@mellybelly Is this something we should discuss soon? Otherwise I would put this on the wiki for discussion.

**Comment by pnrobinson** [comment]
I am putting this on the wiki, see here
https://github.com/obophenotype/human-phenotype-ontology/wiki/Spectrums-and-subclasses
