### ISSUE TITLE
Should 'Nodular calcific aortic valve disease' be in MONDO?

### ISSUE THREAD

**Issue by mellybelly** [obophenotype/human-phenotype-ontology#1435]
http://circ.ahajournals.org/content/124/16/1783

**Comment by pnrobinson** [comment]
This HPO term is used to annotate only one disease in our corpus,
https://omim.org/entry/114065
CALCIFIC AORTIC DISEASE WITH IMMUNOLOGIC ABNORMALITIES, FAMILIAL 
Thisis the phenotype that was being denoted:
The surgeon described a peculiar severe nodular calcification that was 'scooped out' from the aortic ring;

**Comment by pnrobinson** [comment]
I have reviewd the publications and think that there is not really enough evidence to support that specifically nodularity is a characteristic feature. I am going to merge this term with Aortic valve calcification
