### ISSUE TITLE
Clean up top level in OWL edition

### ISSUE THREAD

**Issue by cmungall** [obophenotype/human-phenotype-ontology#1437]
browsers like OLS mirror what is seen in Protege, including ugly floater classes etc

**Comment by drseb** [comment]
strategy suggestions?

**Comment by cmungall** [comment]
For releases, we can be aggressive in doing a cascading delete of axioms that don't point to subclasses of some expected root classes.

We should also try and be watchful in the edit file, and proactively fix:

 * if we reference an obsoleted classes, we should rewire
 * there is a subtle issue whereby module extraction may end up missing a subclass axiom if the axiom has a complex equivalence axioms. E.g. glabella is equivalent to bone area and connects exactly 2 supra-orbital ridges. This goes away as upstreams move to standard robot release pipelines which always ensures the subclass graph has one direct named class parent
 * we may want to explore importing or making a small upper ontology to group things

Partially related: one day it would be great if we could kill All

**Comment by pnrobinson** [comment]
@cmungall @drseb Is there a concrete open issue that remains?

**Comment by cmungall** [comment]
Yes, I'll try and get to this soon

**Comment by pnrobinson** [comment]
@cmungall @drseb Can we set up a time to discuss this? I am going to move this to the editors guide of the wiki for now:
https://github.com/obophenotype/human-phenotype-ontology/wiki/OWLTopLevel

**Comment by drseb** [comment]
I don't understand why you would move this issue to a wiki-entry!? Anyway, let me know if there is a time where you both could chat.

**Comment by pnrobinson** [comment]
For me, an issue should be a relatively small item of work, and important issues like this regularly get forgotten on our tracker. Not sure the wiki is better. Suggestions? @cmungall we are both going to be at the Translator--there may not be much time, but let's see if we can skype Seb while we are both in one place?

**Comment by drseb** [comment]
Lets discuss on skype. But wiki is IMHO the the worse alternative.
