### ISSUE TITLE
typo in amyloid cardiomyopathy  

### ISSUE THREAD

**Issue by mellybelly** [obophenotype/human-phenotype-ontology#1439]
term label

**Comment by pnrobinson** [comment]
I fixed the typo but notice there are two related terms
1. amyloid cardiomyopathy
2. cardiac amyloidosis
These are not 100% synonymous, but do we think we need to retain both terms?

**Comment by pnrobinson** [comment]
After reviewing the literature, I think that these two items are synonymous, and I will merge them.
