### ISSUE TITLE
obscure term needs def: Oncocytic cardiomyopathy

### ISSUE THREAD

**Issue by mellybelly** [obophenotype/human-phenotype-ontology#1440]
there is logical but not text def
in OMIM, rare.

**Comment by pnrobinson** [comment]
histiocytoid cardiomyopathy is a synonym
http://www.humpath.com/spip.php?article10236

According to this nice article there is now a disease-gene candidate (not yet mentioned in OMIM):
http://molecularcasestudies.cshlp.org/content/3/1/a001271.full?sid=229218f0-825c-4531-8afc-20c778b3dcaf#ref-13
