### ISSUE TITLE
NTR: peripheral artery calcification

### ISSUE THREAD

**Issue by cmungall** [obophenotype/human-phenotype-ontology#1441]
See https://docs.google.com/document/d/10VcYh_qDSf9iPt40gBaOvrwUQTIUoMzxxR1fEtuqSuU/edit

**Comment by pnrobinson** [comment]
Adding as HP_0031301

**Comment by pnrobinson** [comment]
Also lower extremities
femoral , tibial, illiac, cerebral, carotid, intracerebral , 
Aortic arch, abdominal aorta

Consider removing Large artery calcification - no-one uses this term and only has one child which is also child of medial artery calcification

Coronary artery calcification should have two parents, primary artery calcification and atherosclerosis
Developmental origin based classification

**Comment by pnrobinson** [comment]
[x] Coronary artery calcification should have two parents, primary artery calcification and atherosclerosis => I do not think that this is a parent relationship, this is anetiology (disease annotation) in our system.

**Comment by pnrobinson** [comment]
I have obsoleted Large artery calcification. @drseb This term is used only to annotate this disease http://compbio.charite.de/hpoweb/showterm?disease=ORPHA:391487 (but I think this is an error). Can HIPBI reannotate or correct this annotation please?
