### ISSUE TITLE
NTR/synonyms for Ears, Nose and Throat phenotypes

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#1442]
I'm reviewing the [WebMD message board](https://messageboards.webmd.com/health-conditions/f/ear-nose-throat) for ENT symptoms

I am going to add everything to the tracker because Melissa and Chris currently have the lock on HP.

Questions/NTR:
- [x] NTR 'Fluid behind the ear drum'
- [x] NTR: otitis externa/swimmer's ear (maybe this is a disease and not a phenotype?)
- [x] NTR: Recurrent ear infections/frequent ear infections
- [x] unbalance (I saw a similar term come up in another forum too)

I will add:
- [x] add layperson tag to 'pain in the ear' (syn of ear pain)
- [x]  'ringing in ears' syn for Tinnitus
- [x] add syn 'acid reflux' to Gastroesophageal reflux
- [x] add syn 'lost smell' to anosmia
- [x] add syn 'lost taste' to Decreased taste sensation

**Comment by drseb** [comment]
I checked the ones that I think are good to go. Was this the intention of the checkboxes?

**Comment by nicolevasilevsky** [comment]
@drseb that works! I love those checkboxes. :)

**Comment by pnrobinson** [comment]
@nicolevasilevsky  Unbalance--maybe vertigo, doyou have more context?
Fluid behind eardrum: Probably otitis media with effusion (OME). Let's make a NTR

**Comment by nicolevasilevsky** [comment]
Yes - the unbalance is related to vertigo, this is the message that was posted:

"Had a form of Vertigo.
I went to the hospital with severe dizziness, nausea and unbalance. Got out and went to an ENT who diagnosed me with "Vestibular Neuronitis". Took a Prednisone 21 tablet steroid pack. It's been 15 days and my head is still a little fuzzy..."

**Comment by nicolevasilevsky** [comment]
Should I add 'unbalance' as a broad synonym for vertigo?

**Comment by pnrobinson** [comment]
I think the correct word is imbalance and unbalance is a verb: to unbalance somebody (?)  But imbalance is a BROAD synonym and might apply equally well to ataxia. Can we make the same item a BROAD synonym for multiple terms?

**Comment by nicolevasilevsky** [comment]
I don't think so, but I'm not totally sure. @drseb, do you know?

**Comment by drseb** [comment]
At the moment the QC-pipeline would not allow this. 
We need to decide if we want to allow this, then I can change the QC. I am not sure about all the consequences of such a step, but my gut feeling is: we should allow multiple equivalent broad synonyms.

**Comment by pnrobinson** [comment]
I am a little worried about allowing really broad synonyms, because this will vastly increase the noise of text mining (unless people read the directions and figure out that BROAD means NOISY). In this particular case I think that imbalance really is way too broad because it can be used to describe loosing your balance if somebody pushes you etc etc, a feeling of lack of focus, vertigo, fainting, ataxia etc.
It wouldbe hard to go back once we add lots of BORAD synonyms in this way, and if we really want to do it, we should somehow test the consequences?

**Comment by pnrobinson** [comment]
I think that we are done with these and I would not add unbalance at this time for reasons stated above.
