### ISSUE TITLE
coronary artery disease

### ISSUE THREAD

**Issue by mellybelly** [obophenotype/human-phenotype-ontology#1443]
should not be in the HPO as is?

and child disease terms

**Comment by mellybelly** [comment]
is it atomic and if so, can it be labeled differently as primary term label? can keep synonym
from text def seems atomic but causes confusion...

**Comment by pnrobinson** [comment]
I agree and I think that we can use the term Coronary artery atherosclerosis as the primary label. I will work on a way of defining this so that it is clear we are talking about a phenotypic feature rather than the disease entity.

**Comment by pnrobinson** [comment]
I think it is best to call this Coronary artery atherosclerosis . I have also moved "Angina pectoris" to the functional branch (because angina can be caused by other pathologies too).

**Comment by pnrobinson** [comment]
I have completed refactoring these terms.
