### ISSUE TITLE
NTR/synonyms for Eye Health

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#1444]
I am reviewing the [WebMD message board](https://messageboards.webmd.com/health-conditions/f/eye-health) on eye health

I am adding all the NTR/syns in this ticket, I noted which I will add myself (as Melissa and Chris have the lock on HP right now)

**Questions:**
- [ ] NTR: Unequal pupil dilation (this seems related to Bilateral congenital mydriasis

**I will add:**
- [x] add nearsightedness as a syn for myopia
- [x] add tearing as a syn for increased lacrimation
- [ ] add syn extreme sensitivity to light to photophobia
- [x] add syn 'high eye pressure' to Increased intraocular pressure
- [x] add syn 'abnormal eye pressure' to Abnormal intraocular pressure

**Comment by drseb** [comment]
_extreme sensitivity to light_ is not very specific. Could also refer to the skin. @pnrobinson to advise

**Comment by pnrobinson** [comment]
Unequal pupil dilation is a synonym for Anisocoria, but probably it is better to say Unequal pupil dilatation. I will add this as a synonym.

**Comment by pnrobinson** [comment]
It seems impossible to disambiguate extreme sensitivity to light (skin vs eye) without saying extreme sensitivity of the eyes to light. I will add the latter as a LP synonym.
