### ISSUE TITLE
Combined hyperlipidemia - remove term

### ISSUE THREAD

**Issue by RLovering** [obophenotype/human-phenotype-ontology#1445]
Hi

in wikipedia this is described as: 
is a commonly occurring form of hypercholesterolemia (elevated cholesterol levels) characterised by increased LDL and triglyceride concentrations, often accompanied by decreased HDL

rather than have this term use the specific levels of each eg use terms:
increased LDL levels
decreased HDL levels

(will put ticket in for these)

Ruth

**Comment by pnrobinson** [comment]
I agree that this is a bundled term. There is currently one annotated disease (HYPERLIPIDEMIA, FAMILIAL COMBINED). There are a number of Orphanet entries that will need to be revised @drseb  could this be put on the HIPBI to do list?
