### ISSUE TITLE
rename hyperlipidemia terms and add terms

### ISSUE THREAD

**Issue by RLovering** [obophenotype/human-phenotype-ontology#1446]
Hi 

need to change the format of these terms, not sure what phrase you would want but ideally

Hyperalphalipoproteinemia change to:
Increased circulating high-density lipoprotein levels
or Increased plasma HDL levels

Increased circulating very-low-density lipoprotein cholesterol change to:
Increased circulating very-low-density lipoprotein levels
or Increased plasma VLDL levels

Hyperbetalipoproteinemia change to:
Increased circulating low-density lipoprotein levels
or Increased plasma LDL levels

Hyperchylomicronemia change to:
Increased circulating chylomicron levels
or Increased plasma chylomicron levels

and repeat for the Hypolipidemia terms, and create equivalent terms for chylomicron and VLDL.

Plus add Tg as synonym in Hypertriglyceridemia and Hypotriglyceridemia terms

Ruth

**Comment by RLovering** [comment]
PS for tg add synonyms as appropriate:

Increased circulating Tg levels, Increased plasma Tg levels
decreased circulating Tg levels, decreased plasma Tg levels

**Comment by pnrobinson** [comment]
Thanks for these suggestions, which I have completely implemented, and sorry for the delay!
