### ISSUE TITLE
TPV: Abdominal situs inversus should not be under Dextrocardia

### ISSUE THREAD

**Issue by cmungall** [obophenotype/human-phenotype-ontology#1449]
is_a HP:0004307 ! Abnormal anatomic location of the heart
       is_a HP:0001651 ! Dextrocardia
        is_a HP:0001696 ! Situs inversus totalis
         is_a HP:0003363 ! Abdominal situs inversus ***

**Comment by pnrobinson** [comment]
I have removed the subclass assertion for Abdominal situs inversus is_a Situs inversus totalis, which was incorrect.
@cmungall @drseb Is there a PATO term for "left-right reversed" that we could use to define Heterotaxy and Situs inversus totalis etc? Situs inversus totalis would need to be defined with an Uberon term referring to all thoracic and abdominal viscera, is that correct?

**Comment by cmungall** [comment]
We can make subclasses of the direction-neutral

PATO:0000625 ! inverted

**Comment by pnrobinson** [comment]
Inverted (in English) has two relevant meanings
1. to reverse in position, order, or relationship :  to subject to inversion
2. to turn inside out or upside down

left-right reversed only could be a subclass of meaning 1, which I think is the one chosen by PATO (An oriented quality inhering in a bearer by virtue of the bearer's being reversed in position, order, or condition. )
So I agree, and the label of the new term could be left-right inverted (while we are at it, there is also  top/bottom inverted and back-front inverted -- which are not necessarily medically relevant though).

**Comment by pnrobinson** [comment]
The hierarchy is now correct. I have made a NTR at PATO for "heterotaxic" that would allow us to make definitions for many terms. I will make another NTR for these definitions once we have the new PATO term.
