### ISSUE TITLE
NTR: ventricular septal aneurism 

### ISSUE THREAD

**Issue by cmungall** [obophenotype/human-phenotype-ontology#1450]
We have HP:0011995 ! Atrial septal aneurysm -- but not the ventricular counterpart

@drseb and @nicolevasilevsky - how should we do logical defs for these? MPATH:90 ! aneurysm

**Comment by drseb** [comment]
I like the MP-way here:

```
'has part' some 
    ('increased amount'
     and ('inheres in' some 
        (aneurysm
         and ('part of' some X)))
     and ('has modifier' some abnormal))
```

Sounds reasonable?

**Comment by nicolevasilevsky** [comment]
that looks good to me

**Comment by pnrobinson** [comment]
This does not seem correct to me or at least not elegant, because the normal situation is not to have any aneurysm at all. We are otherwise using this pattern for thing like hypernatremia, where people normally have say 135 mg/dl, and we call it increased if people have more than 145mg/dl (I forget the exact range). 
I did not like "balooning" from PATO, but what about making a PATO term called 'aneurysmal"

**Comment by drseb** [comment]
But using 'increased amount' (and IMHO going from 0 to 1 is an increase) gives us interoperability to MP and others...

What I always pray here is: let's at **first** be consistent and then **fix** the stuff consistently.

**Comment by pnrobinson** [comment]
I agree that consistency is the highest goal. We need to document this stuff though. If we are going to sue this pattern, then it needs to be documented so nobody creates a new definition with another pattern. Could we put this as an example onto the new wiki?

**Comment by drseb** [comment]
@nicolevasilevsky could make a yaml-pattern. Not sure this is enough documentation!? Probably not...

**Comment by pnrobinson** [comment]
I would plead for having sufficient documentation for the broader team. The current documentation is simply not that helpful and it is not that much work to document the thought processes behind this decision. It will save us all a lot of work in the long run if we have something like a wiki page for each of these patterns and will make it a lot easier to train new team members etc.

**Comment by cmungall** [comment]
@nicolevasilevsky - can you add a yaml for this?

**Comment by cmungall** [comment]
Also related to the definition of aneurysm (vs related concepts like dilation): #1453

**Comment by nicolevasilevsky** [comment]
I created this [yaml file](https://github.com/obophenotype/upheno/blob/master/src/patterns/abnormalPathology)

@cmungall, can  you check it to make sure it is correct? this is the first time I created a yaml file for a logical def with two variables. I tried to model it after this [example](https://github.com/dosumis/dead_simple_owl_design_patterns/blob/master/patterns/import_across_membrane.yaml) from David's

**Comment by cmungall** [comment]
This looks great, but I was thinking of a less generic pattern, one called anuerysm or dilatation. This was we can do things like immediately refactor all anuerysm OWL defs if needed.

However, let's keep the abnormal pathology one around

**Comment by nicolevasilevsky** [comment]
Here is an [aneurysm yaml file](https://github.com/obophenotype/upheno/blob/master/src/patterns/Aneurysm)
