### ISSUE TITLE
Does not follow aneurysm pattern

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#1451]
Aneurysm of an abdominal artery

```
'has part' some 
    (ballooning
     and ('inheres in' some 'abdominal aorta artery')
     and ('has modifier' some abnormal))
```

See https://github.com/obophenotype/human-phenotype-ontology/issues/1450 for better pattern

**Comment by pnrobinson** [comment]
@drseb @nicolevasilevsky Can we make this change? Where is the aneurysm yaml file mentioned in #1450 ?

**Comment by nicolevasilevsky** [comment]
@pnrobinson all the yaml files are in the upheno repo. The aneurysm yaml file is here: https://github.com/obophenotype/upheno/blob/master/src/patterns/aneurysm.yaml

(note, it was linked in the other ticket, but the links were broken, so I fixed them)

**Comment by pnrobinson** [comment]
@cmungall 
What about the following definition for Asymmetric abdominal aortic aneurysm
```
'has part' some 
    ('increased amount'
     and ('inheres in' some 
        (aneurysm
         and ('part of' some 'abdominal aorta')))
    and asymmetrical
     and ('has modifier' some abnormal))
```

Note that aneurysm and dilatation are not the same, and thus I will not change all patterns.

**Comment by pnrobinson** [comment]
@drseb 
could we please mireat the PATO term for fusiform
https://www.ebi.ac.uk/ols/ontologies/pato/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0002400

I have tried the above pattern for aneurysm (for the abdominal section) but still need fusiform.
@LCCarmody could we complete this for the thoracic aneurysm once we have "fusiform"? 
thanks

**Comment by pnrobinson** [comment]
@drseb Could you please mireot the term for fusiform? :-0

**Comment by drseb** [comment]
There is no PATO-import. I would have guessed that PATO is loaded completely!? No?

**Comment by drseb** [comment]
Ok. There is a PATO-import, sorry. Mireoting this class does not work at the moment. We'll see

**Comment by pnrobinson** [comment]
I cannot seem to use fusiform (https://www.ebi.ac.uk/ols/ontologies/pato/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0002400) for the definition of these terms...

**Comment by drseb** [comment]
It should work now.

**Comment by pnrobinson** [comment]
Thanks -- it does work. Can you please comment on whether this is correct?
```
'has part' some 
    ('increased amount'
     and asymmetrical
     and ('inheres in' some 
        (aneurysm
         and ('part of' some 'abdominal aorta')))
     and ('has modifier' some abnormal))
```
if so we can finish up all of these terms now!

**Comment by pnrobinson** [comment]
Sorry @drseb @cmungall could you please comment on whether the above is correct and we will finalize this issue? thanks!

**Comment by cmungall** [comment]
@LCCarmody 

I'm curious as to how you got Protege to accept:

`'fusiform' some abnormal`

fusiform is a class, you should only be able to use relations before the "some"

I think the fusiform quality inheres in the physical structure. If we are using aneurysm as the physical structure here, then it should be `...(aneurysm and bearer_of some fusiform)...`. 

I'm also not sure about the intersection between asymmetrical and increased amount

**Comment by LCCarmody** [comment]
Honestly, I am not sure.  It does not work.

**Comment by pnrobinson** [comment]
I have updated and unified the patterns according to this pattern:
```
'has part' some 
    ('increased amount'
     and fusiform
     and ('inheres in' some 
        (aneurysm
         and ('part of' some 'ascending aorta')))
     and ('has modifier' some abnormal))
```
