### ISSUE TITLE
NTR: Abnormality of the great vessels

### ISSUE THREAD

**Issue by cmungall** [obophenotype/human-phenotype-ontology#1452]
bit.ly/cardio-notes

Abnormality of the great vessels

```
        is_a UBERON:0013768 ! great vessel of heart *** 
         is_a UBERON:0000947 ! aorta
         is_a UBERON:0002012 ! pulmonary artery
         is_a UBERON:0002016 ! pulmonary vein
         is_a UBERON:0004087 ! vena cava
```

**Comment by cmungall** [comment]
Note also the discussion on whether to make a new grouping, see also: https://github.com/obophenotype/uberon/issues/1311

**Comment by pnrobinson** [comment]
This is a useful article for aortic abnormalities
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3036416/

**Comment by pnrobinson** [comment]
Arranging the hierarchy like this for morphology.
