### ISSUE TITLE
Consider merging HP:0001724 ! Aortic dilatation with HP:0004942 ! Aortic aneurysm

### ISSUE THREAD

**Issue by cmungall** [obophenotype/human-phenotype-ontology#1453]
from http://bit.ly/cardio-notes, Josh says:
"HP:0001724 ! Aortic dilatation basically same thing as HP:0004942 ! Aortic aneurysm"

**Comment by cmungall** [comment]
notes from mtg:
"use dilation as primary label, add aneurysm as synonym"

**Comment by cmungall** [comment]
should we have a new synonym type for modifiers, e.g 

synonym: "X anuerysm" NARROW SEVERE []

**Comment by pnrobinson** [comment]
In my opinion there is not sufficient uniformity in usage to commit to this type of synonym category. I think that we should use EXACT SYNOMYM for these because none of the cardiologists involved in the discussion could come up with any specific differentia for aneurysm as opposed to dilatation. My experience has been that different communities tend to use different labels but there is no accepted criteria for differentiation. This is probably true for the vast majority of other analogous cases in the HPO.

**Comment by cmungall** [comment]
OK, fair enough about the synonym proposal.

But you closed the ticket though the main request was to merge: HP:0001724 ! Aortic dilatation with HP:0004942 ! Aortic aneurysm (the synonym category note was a sidebar). It sounds like you agree with the proposed merger, so I'm reopening the ticket. Please close again if I've misunderstood.

**Comment by pnrobinson** [comment]
After some research, I would suggest we use aneurysm as the primary label. Much literature seems to use dilatation and aneurysm synonymously. But we also see this
 An aneurysm is a permanent localized (i.e., focal) dilation of an artery having at least a 50% increase in diameter compared to the expected normal diameter of the artery in question (https://www.ncbi.nlm.nih.gov/pubmed/1999868). 
and
Nevertheless, by common convention, aortic dilatation refers to a dimension that is greater than the 95th percentile for the normal person age, sex and body size. In contrast, an aneurysm is defined as a localized dilation of the aorta that is more than 50% of predicted (ratio of observed to expected diameter ≥ 1.5). Aneurysm should be distinguished from ectasia, which represents a diffuse dilation of the aorta less than 50% of normal aorta diameter (http://www.sciencedirect.com/science/article/pii/S235290671500010X).
and in Harrison's
An aneurysm is defined as a pathological dilation (sic) of a segment of a blood vessel...

**Comment by pnrobinson** [comment]
I have merged these terms
Def: Aortic dilatation refers to a dimension that is greater than the 95th percentile for the normal person age, sex and body size. In contrast, an aneurysm is defined as a localized dilation of the aorta that is more than 150 percent of predicted (ratio of observed to expected diameter 1.5 or more). Aneurysm should be distinguished from ectasia, which represents a diffuse dilation of the aorta less than 50 percent of normal aorta diameter.
Comment: Aneurysm is considered a severe (pathological) form of dilatation of a segment of a blood vessel. In clinical practice, dilatation and aneurysm are occasionally used interchangably. In this subhierarchy, we therefore use aneurysm as the primary label and list dilatation as a broad synonym.
