### ISSUE TITLE
Incorrect phenotype for OMIM:114030 -> HP:0009737

### ISSUE THREAD

**Issue by sdumitriu** [obophenotype/human-phenotype-ontology#1454]
OMIM's 114030 CAL spots disease is annotated with HP:0009737 Lisch nodules, but the [actual text](http://www.omim.org/entry/114030) indicates that's a missing symptom:

> The **absence** of neurofibromas and **Lisch nodules** of the iris suggests that these families are expressing a trait genetically distinct from NF1

So this phenotype should be moved to `negative_phenotype_annotation` instead.

**Comment by drseb** [comment]
Thanks @sdumitriu !

**Comment by pnrobinson** [comment]
Further revised the file in table editor
