### ISSUE TITLE
Add phenotypes for the different type of glycogen storage disease subclasses

### ISSUE THREAD

**Issue by mellybelly** [obophenotype/human-phenotype-ontology#1455]
e.g.
                                     [subClassOf] Glycogen Storage Disease Due To Aldolase A Deficiency
                                     [subClassOf] Glycogen Storage Disease Due To Glycogen Synthase Deficiency
                                     [subClassOf] Glycogen Storage Disease Due To Lactate Dehydrogenase Deficiency
                                     [subClassOf] Glycogen Storage Disease Due To Muscle Beta-Enolase Deficiency
                                     [subClassOf] Glycogen Storage Disease Due To Phosphoglycerate Kinase 1 Deficiency
                                     [subClassOf] Glycogen Storage Disease Due To Phosphoglycerate Mutase Deficiency
                                     [subClassOf] Glycogen Storage Disease Due To Phosphorylase Kinase Deficiency

**Comment by pnrobinson** [comment]
Are you thinking of any specific references for these diseases?

**Comment by pnrobinson** [comment]
I am closing this as these are diseases not phenotypes-add to MONDO tracker if appropriate.
