### ISSUE TITLE
New term request: Missed heartbeat/Skipped heartbeat

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#1457]
New term: skipped heartbeat
parent: arrhythmia (?) or palpitations?
Syn (layperson): Missed heartbeat, skipped heartbeat
Suggested def: Abnormal heart rhythm where there is a missed or skipped heartbeat.

**Comment by pnrobinson** [comment]
Actually, it is thought that this is not a "skipped" beat but rather an extra beat that we just perceive as a skipped beat (see wikipedia: https://en.wikipedia.org/wiki/Premature_ventricular_contraction). I am adding this as a RELATED synonym.
