### ISSUE TITLE
new term:Micropupil?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1459]

**Comment by psergouniotis** [comment]
It would be great if you could suggest a definition and/or point to a source when recommending a new term. This will make it easier for people to comment. I am not sure what micropupil is - I have personally not heard of it (I note that I am an ophthalmologist). 

Perhaps a more appropriate term could be "microcoria" - possible definition: small pupil (typically diameter < 2 mm) that dilates poorly or not at all in response to topically administered mydriatic drugs (PMID: 25772937).  Micorocoria could be a subclass of "Abnormality of the iris" HP:0000615.

**Comment by pnrobinson** [comment]
I am adding a term Microcoria as suggested.
