### ISSUE TITLE
new term:Misrouting of the optic nerves?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1461]

**Comment by psergouniotis** [comment]
"Optic pathway misrouting" (syn "Visual pathway misrouting", "Optic nerve misrouting", "Misrouting of the optic nerves") would perhaps be a good term to add as a subclass of Abnormality of the optic nerve [HP:0000587]. 

Possible definition could be: abnormal decussation of the visual pathways, typically identified using visual evoked potentials (VEP) (asymmetrical distribution of the VEP over the posterior scalp).

**Comment by LOURGHI** [comment]
It was observed in Hermansky-Pudlak syndrome.
