### ISSUE TITLE
new term:Facial poikiloderma ?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1471]

**Comment by pnrobinson** [comment]
I would suggest using the term Poikiloderma. We do not need to annotate every particularity. Unless there is a disease where the location of poikiloderma is specific to the face, in which case please reopen this issue.

**Comment by LOURGHI** [comment]
It was very frenquently observed in Rothmund-Thomson syndrome type 1.ORPHA:221008.
