### ISSUE TITLE
new term:faciotroncular lipohypertrophy?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1477]
Add synonym:increased fat in the face and around the neck  and trunk.

**Comment by pnrobinson** [comment]
@LOURGHI  This is a bundled (combined) term. We would use terms for facial lipohypertrophy and truncal lipohypotrophy. Do you happen to have more detail about the diagnosis involved?

**Comment by pnrobinson** [comment]
I think this is a mistake because partial acquired lipodystrophy has loss of fat tissue. The only lipohypertrophy I can find is the sign that follows insulin injections in diabetes. I will close this ticket, but please reopen if I am wrong but provide more details.
