### ISSUE TITLE
new term:Lipohypertrophy ?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1479]

**Comment by pnrobinson** [comment]
Are you refering to insulin-induced lipohypertrophy (e.g., http://www.nejm.org/doi/full/10.1056/NEJMicm1101527#t=article) ?

**Comment by LOURGHI** [comment]
I have no Physiopathological element but this sign was observed in Partial acquired lipodystrophy,Primary lipodystrophy and Lipedema.

**Comment by pnrobinson** [comment]
I think this is a mistake because partial acquired lipodystrophy has loss of fat tissue. The only lipohypertrophy I can find is the sign that follows insulin injections in diabetes. I will close this ticket, but please reopen if I am wrong but provide more details.

**Comment by LOURGHI** [comment]
My colleague who annotated this disease had noted lipodystrophy in the upper limbs and a lipohypertrophy of the thighs.PMID:24788242.
