### ISSUE TITLE
new term:Lipohypertrophy  of the thighs. ?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1480]

**Comment by pnrobinson** [comment]
@LOURGHI  Can we just use the term Increased adipose tissue? Is it specific that the lowerlimbs are affected? Do you have more context?
Is this really different from the term request with "lower limbs"?

**Comment by LOURGHI** [comment]
It was observed in Partial acquired lipodystrophy(24788242[PMID])
It's noted :lipoatrophy of the upper part of the body with  lipohypertrophy  of the thighs.

**Comment by pnrobinson** [comment]
Adding term as Lower extremity subcutanous fat hypertrophy HP_0031451
