### ISSUE TITLE
new term:Lipohypertrophy  of lower limbs  ?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1481]

**Comment by pnrobinson** [comment]
@LOURGHI  Can we just use the term Increased adipose tissue? Is it specific that the lowerlimbs are affected? Do you have more context?

**Comment by LOURGHI** [comment]
Sorry I have no contexte.

**Comment by pnrobinson** [comment]
I do not think this is good for an HPO term without more information, so I am closing the issue.
