### ISSUE TITLE
new term:Red-brown papulonodules ?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1490]

**Comment by pnrobinson** [comment]
This is a bundled term (two colors with papules and nodules). While this might be a valid description of a single patient, it is not a good HPO term. Instead, we would try to annotate say Red papules and Brown nodules (two terms, if that is correct). If needed, please provide a more detailed description of the patient being annotated and we will try to find the correct HPO terms -- please open new issues.
