### ISSUE TITLE
new term:Yellow-orange nodules?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1495]

**Comment by pnrobinson** [comment]
@LOURGHI  we do not want to create an HPO term for detailed descriptions like this but rather for recognizable clinical entities that can be found in multiple papers or diseases. I am thinking that possibly yellow nodule might be a good term (e.g., https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3250011/)
for lesions with high lipid content. I am not sure whether adding orange really adds much to the term. Can you provide more information?

**Comment by pnrobinson** [comment]
I have added a term, yellow nodule. Please use that term for annotation of reopen this issue if there is a true distilledinction to yellow orange nodule.
