### ISSUE TITLE
new term:Atrophic patches?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1510]

**Comment by pnrobinson** [comment]
@LOURGHI  I think this is the same as Atrophic scars HP_0001075  -- could you let us know more about the patient being described here?

**Comment by LOURGHI** [comment]
This sign was observed in Porokeratosis, ISBN:9781405161695.

**Comment by pnrobinson** [comment]
Actually, this is an incorrect description as far as I can see. In dermatology, a Patch is described as 
A circumscribed area of discoloration, greater than 1 cm, which is neither elevated or depressed relative to the surrounding skin. (see http://missinglink.ucsf.edu/lm/dermatologyglossary/primarylesions1a.html).
However, in Porokeratosis the lesions are raised:slightly raised peripheral border 
also, the lesions are not simply atrophic patches
Verrucous annular plaques with central atrophy (see https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4375752/).
I think in the future we will need to extend and improve the way HPO is used to describe dermatological diseases,but at present there is no way of getting this level of detail, and I think annotatingwith Plaque is probably the best way for now.

**Comment by LOURGHI** [comment]
The desease was annotated with skin atrophy as a parent of the missing term,I tend to leave this term and add skin plaque?????
