### ISSUE TITLE
new term:serpiginous cutaneous lesions?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1515]

**Comment by pnrobinson** [comment]
I think it is better to use the primary label Serpiginous eruption
see e.g. http://www.jaad.org/article/S0190-9622(09)00934-7/abstract

**Comment by pnrobinson** [comment]
After more reading, I agree that serpiginous lesion should be the prefered label, I have added eruption as a synonym.
