### ISSUE TITLE
new term:Gyrate lesions ?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1516]

**Comment by pnrobinson** [comment]
@LOURGHI Gyrate lesions of what? Are these skin lesions? We need more detail to make an HPO term, because there are lots of things that can appear gyrate.

**Comment by LOURGHI** [comment]
Sorry I have no context.

**Comment by pnrobinson** [comment]
Then it is impossible to make an HPO term for it, I will close the issue.
