### ISSUE TITLE
new term:Polycyclic lesions?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1517]

**Comment by pnrobinson** [comment]
@LOURGHI  I am assuming you mean polycyclic skin lesion like this
http://www.pcds.org.uk/quick-guide/annular-ring-shaped-polycyclic-two-or-more-connected-rings-arciform-arc-lik
?

**Comment by pnrobinson** [comment]
As far as I can see the polycyclinc nature of lesions is not characterisitc for Linear IgA dermatosis.
See for instance, https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3702236/
I have added a clinical modifier term for polycyclic:
HP_0031450
Definition: A distribution of skin lesions resembling multiple merged circles. For instance, this can be seen with multiple urticarial wheals as the individual, circular wheals resolve and merge.
This can be used to modify any skin lesion HPO term as appropriate.
