### ISSUE TITLE
new term:Exfoliative dermatitis?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1523]

**Comment by pnrobinson** [comment]
Exfoliative dermatitis is a disease characterized by generalized erythema with scaling or desquamation affecting at least 90% of the body surface area. 
I think the phenotype term is Desquamation.
There is currently a term Desquamation of skin soon after birth
This is used to annotate four diseases -- we should remove the "soon after birth" from the label and re-annotate with the clinical onset modifier congenital
ORPHA:39041
OMENN SYNDROME
	
ORPHA:88621
ICHTHYOSIS PREMATURITY SYNDROME
	

OMIM:242300
ICHTHYOSIS, CONGENITAL, AUTOSOMAL RECESSIVE 1

OMIM:608013
GAUCHER DISEASE, PERINATAL LETHAL

**Comment by pnrobinson** [comment]
Actually, probably the 'soon after birth' is characteristic and on second thought,it seems appropriate so I willleave the term.
