### ISSUE TITLE
new term:Albopapuloid lesions ?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1527]

**Comment by pnrobinson** [comment]
Albopapuloid means resembling a white papule. The terminology seems to be specific to this disease
https://www.omim.org/entry/131750
Probably it is better to have a term with the label "White papule"? This would be general.

**Comment by pnrobinson** [comment]
@LOURGHI  could you provide feedback on this, should we go with "White papule"?

**Comment by LOURGHI** [comment]
They are described as an ivory white papule in this book,
https://books.google.fr/books?id=omtyBgAAQBAJ&pg=PT213&lpg=PT213&dq=Albopapuloid+lesions&source=bl&ots=WEDXizqiqu&sig=bJzomBz4bLAeUbkwUeAadagBS08&hl=fr&sa=X&ved=0ahUKEwjA7s_Ep7vVAhUEORoKHWu_DdYQ6AEIVDAH#v=onepage&q=Albopapuloid%20lesions&f=false.
I think white papule should be a good term.

**Comment by pnrobinson** [comment]
Adding "White papule" HP_0031289
