### ISSUE TITLE
new term: punctate keratoderma?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1529]

**Comment by pnrobinson** [comment]
@LOURGHI  Do you mean this? https://www.dermnetnz.org/topics/punctate-type-palmoplantar-keratoderma/  (i.e., palmoplantar)?

**Comment by LOURGHI** [comment]
Sorry I have no contexte.

**Comment by pnrobinson** [comment]
I would leave this for now because I am uncertain exactly what is meant. Annotate perhaps to keratoderma.
