### ISSUE TITLE
new term:Pilosebaceous cyst?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1537]

**Comment by pnrobinson** [comment]
@LOURGHI  Can you provide more detail. Is there an intended distinction to sebaceous cyst?

**Comment by pnrobinson** [comment]
As far as I can see this terminology is now regarded as outdated. 
See
http://www.bad.org.uk/shared/get-file.ashx?id=198&itemtype=document
I think that this is probably Epidermoid cyst HP_0200040. Please open a new issue with more context if needed.
