### ISSUE TITLE
new term:Erythema multiforme-like lesions ?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1543]

**Comment by pnrobinson** [comment]
Erythema multiforme is a disease with a complicated clinical course as well as numerous different skin lesions. Therefore, it is unclear what "Erythema multiforme-like lesion" means and I think it is not good as an HPO term. Please open a new issue with more specific description if available.

**Comment by LOURGHI** [comment]
Please get a look on (Pemphigoid gestationis PMID:25178359).
