### ISSUE TITLE
new term:Pelvic hemangioma ?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1550]

**Comment by pnrobinson** [comment]
@LOURGHI  Is this referring to the skin around the pelvis or to an internal organ? "Pelvic hemangioma" is ambiguous.

**Comment by LOURGHI** [comment]
It was observed in PELVIS syndrome(PMID: 16847205),and it concerns the skin.

**Comment by pnrobinson** [comment]
In that paper, they are described as perineal hemangiomas.I will add this term.
