### ISSUE TITLE
new term:Capillary ectasias?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1551]

**Comment by pnrobinson** [comment]
@LOURGHI  Is this a skin finding? Is this the same as teleangiectasia? Please provide a definition and more context.

**Comment by LOURGHI** [comment]
Sorry I have no context.

**Comment by pnrobinson** [comment]
It is difficult to make a term without more information so I am closing this issue. Please open a new issue if there is more information.
