### ISSUE TITLE
new term:Flushing?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1553]

**Comment by pnrobinson** [comment]
Adding as HP_0031284

**Comment by pnrobinson** [comment]
@nicolevasilevsky  Note that Fluishing is not a synonym for erythema (it was entered as a LP synonym). Flushing comes and goes, but this is not the semantics of erythema. I am removing that LP synonym!

**Comment by nicolevasilevsky** [comment]
thanks for fixing that!
