### ISSUE TITLE
new term:Digital ulcer ?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1555]

**Comment by pnrobinson** [comment]
I think this should be combined with the acral ulceration terms, which need refactoring (todo).

**Comment by pnrobinson** [comment]
Term created as HP_0031917.
Refactoring the acral ulceration terms
(Note: acral ulceration is a subclass of digital ulceration).

**Comment by pnrobinson** [comment]
I have renamed HP:0006121 as acral ulceration, and reannotated with the existing term autoamputation. Finished refactoring the acral ulceration terms.
