### ISSUE TITLE
new term:Photodistributed skin lesions?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1563]

**Comment by pnrobinson** [comment]
@LOURGHI  I think that Cutaneous photosensitivity is possibly the proper term? Is there a need for the lesions term as well?

**Comment by LOURGHI** [comment]
It's noted Photodistributed lesions / Skin photosensitivity as frequent sign in Disseminated superficial actinic porokeratosis.

**Comment by pnrobinson** [comment]
It sounds to me like  Cutaneous photosensitivity (HP_0000992) is the best term for this.
There are some additional signs of  Disseminated superficial actinic porokeratosis, and these could be annotated using the "triggered" by sun exposure term.
