### ISSUE TITLE
new term:Red-bronze skin?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1566]

**Comment by pnrobinson** [comment]
@LOURGHI  I think you mean this term
Generalized bronze hyperpigmentation
?
HP_0007574
or is there a difference?

**Comment by LOURGHI** [comment]
It was observed in Oculocutaneous albinism type 3 Described as follows:Albinism +  skin hypopigmentation +   red-bronze skin /Abnormal pigmentary skin changes/skin pigmentation anomalies.
we can find this sign in many articles .
see:http://onlinelibrary.wiley.com/doi/10.1111/j.1600-0749.2006.00298.x/full

**Comment by pnrobinson** [comment]
The phenotype in that disease is described as Absence of facial, neck, and extremity fat was noted. I have added the three corresponding annotations and will merge/obsolete the term.

**Comment by pnrobinson** [comment]
I am not able to find a really good definition that would allow us to distinguish this.
https://onlinelibrary.wiley.com/doi/full/10.1111/j.1600-0749.2006.00298.x actually says "yellow" skin and not red-bronze. Also, other reports of this condition do not mention red-bronze skin as a characteristic feature. I think this is just an attempt to describe something that is probably represented by this HPO term https://hpo.jax.org/app/browse/term/HP:0007574
