### ISSUE TITLE
new term:Arc dermatoglyphics ?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1568]

**Comment by pnrobinson** [comment]
@LOURGHI  is this a medically abnormal phenotype? Can you provide more details and a reference?

**Comment by LOURGHI** [comment]
It's noted that it was observed very frequently in Intellectual deficit, X-linked, Stevenson type,this is all I have as context.

**Comment by pnrobinson** [comment]
As far as I know this is a normal finding,and thus I am closing this issue.
