### ISSUE TITLE
new term:xanthomata palmare striatum?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1578]
Add synonym:Palmar crease xanthoma. Is pathognomonic for type III dysbetalipoproteinemia

**Comment by pnrobinson** [comment]
I will use the primary label Xanthomas of the palmar creases,and add XPS as a exact syn

**Comment by pnrobinson** [comment]
Note that the usual order is Xanthoma striatum palmare.
