### ISSUE TITLE
new term:Fibromatosis?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1580]

**Comment by pnrobinson** [comment]
@LOURGHI I think that if a patient has fibromas,then terms such as Fibroma (HP:0010614) should be used. There are alsoterms for features of neurofibromatosis. 
I do not think that the term Fibromatosis as used in Wikipedia is that useful (https://en.wikipedia.org/wiki/Fibromatosis), and instead we should try to be as specific as possible.
