### ISSUE TITLE
new term:Penis freckling ?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1582]

**Comment by pnrobinson** [comment]
@LOURGHI  I would suggest using the HPO term HP_0030052, Inguinal freckling. Please reopen if the freckling is specifically penile in ths disease in question.

**Comment by LOURGHI** [comment]
please get a look on :24136893[PMID]_ 20301661 [PMID].
This sign was observed in PTEN hamartoma tumor syndrome.

**Comment by pnrobinson** [comment]
OK; I agree we should add this term, see
https://www.ncbi.nlm.nih.gov/books/NBK1488/
