### ISSUE TITLE
new term:Dermoid sinus?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1583]

**Comment by pnrobinson** [comment]
As far as I can see in English, dermoid sinus is used to describe in dogs what pilonidal sinus is in humans. I do not think dermoid sinus is used in this way in human medicine. I would recommend checking this but probably you should annotate with "Pilonidal sinus"

**Comment by LOURGHI** [comment]
Dermoid sinus/dimple/pit (excluding sacral) was observed very frenquently  in Hypophosphatasia,Gorlin syndrome,Neurogenic arthrogryposis multiplex congenita,occasionnally in Campomelic dysplasia,X-linked distal arthrogryposis multiplex congenita,frequently in Campomelia, Cumming type,Kyphomelic dysplasia,very frequently in Focal facial dermal dysplasia type III,Cleft palate - large ears - small head,occasionnally in Fronto-facio-nasal dysostosis,,frequently in Grant syndrome,
