### ISSUE TITLE
new term:Androgenetic alopecia?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1587]
Add synonym:Male pattern hair loss

**Comment by pnrobinson** [comment]
Androgenetic alopecia is a common form of hair loss in both men and women. In men, this condition is also known as male-pattern baldness.
I think this is better conceived of as a disease entity. If necessary, please reopen an issue with the precise phenotypic features (I think the HPO already has features for this disease --note that the word alopecia seems to be used both for disease and for phenotype in different contexts).
