### ISSUE TITLE
new term:Hair  shaft pits?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1588]

**Comment by pnrobinson** [comment]
@LOURGHI  I do not understand this. The follicles out of which hair grows can also be called pits, but this is normal. Can you provide some additional context or information please?

**Comment by LOURGHI** [comment]
This sign was observed in Trichodysplasia - amelogenesis imperfecta(PMID:8419879).

**Comment by pnrobinson** [comment]
I have searched for other reports of this feature and found literally nothing in pubmed or in google. The article is from 1993 and as far as I can tell the finding was never replicated. I think that this is probably not sufficient to make an HPO term for. It is also not really certain what the disease is that is being referred to in the article.
