### ISSUE TITLE
new term:spiky hair?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1589]

**Comment by pnrobinson** [comment]
I am uncertain what spiky hair is as a medical phenotype. (The phrase seems to be used as a description of a stylish hairdo that I wouldn't be caught dead with). I do not think that this is a good label or synonym for an HPO term, and wonder if you mean Brittle hair. Reopen if needed with a definition and reference.

**Comment by LOURGHI** [comment]
It was observed in Bamforth-Lazarus syndrome,this is all I have as information.
