### ISSUE TITLE
new term:Scarring alopecia except scalp ?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1590]

**Comment by pnrobinson** [comment]
@LOURGHI The HPO does not have terms that are like "Feature X except in organ Y" because this would lead to a combinatorial explosion. Can you provide additional context of where the alopecia was and whether is was associated with a specific disease?

**Comment by LOURGHI** [comment]
Sorry I have no context.

**Comment by pnrobinson** [comment]
In this case I think we should not make an HPO term at this time.
