### ISSUE TITLE
new term:dark toenails?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1597]

**Comment by pnrobinson** [comment]
@LOURGHI Are you talking about this kind of feature (which I think is usually called black toenail):https://www.runnersworld.com/black-toenails/5-causes-of-black-toenails-and-how-to-id-the-harmless-from-the-harmful

**Comment by LOURGHI** [comment]
Sorry I have no context.

**Comment by pnrobinson** [comment]
I think it is best not to create terms for dark nails at this time, but if we get more information we should reopen these issues.
