### ISSUE TITLE
new term:Intrapulpal calcification ?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1601]

**Comment by pnrobinson** [comment]
@LOURGHI  Can you provide more context? There are two current terms that describe pulpal calcification (see pulp stones for instance). Is this phenotype different?

**Comment by LOURGHI** [comment]
This sign was observed in Amelogenesis imperfecta and gingival hyperplasia syndrome,(I haven't PMID)

But as I see, pulpe stone are defined as a  calcified masses so it's logically the same.(gallstones or biliary calcifications I think it describes the same phenotype)???

**Comment by pnrobinson** [comment]
In that case then I think probably HP_0003771 is the best term to use. I do not think that the phrase Intrapulpal calcification is a good synonym and I have not seen it in PubMed enough to make a further assessment. We can reopen a new issue if more information becomes available.
