### ISSUE TITLE
new term:Limb overgrowth?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1609]

**Comment by pnrobinson** [comment]
@LOURGHI  can you provide more context? Is this a synonym for Hypertrophy of the lower limb and other existing terms? Or does it affect all limbs at once? What is the disease?

**Comment by LOURGHI** [comment]
Sorry I have no context.

**Comment by pnrobinson** [comment]
I think that probably Hypertrophy of the lower limb is the best annotation then.We can open a new issue if more information becomes available.
