### ISSUE TITLE
new term:Irregular length of fingers?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1611]

**Comment by pnrobinson** [comment]
@LOURGHI  The fingers have unequal lengths normally. I think that if there is more discrepancy, then it is best to annotate this with terms that reflect the precise observation, e.g., brachydactly terms. There are lots of terms for this. I would not like to introduce a new term that is less precise than the ones we already have. If there is a recognizable and characteristic feature,then please provide a detailed description and references.
