### ISSUE TITLE
new term:Mutilating acropathy?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1612]

**Comment by pnrobinson** [comment]
I think this is a general term for a group of diseases such as https://www.esciencecentral.org/journals/sporadic-ulcerative-mutilating-pseudosyringomyelic-acropathy-2327-5146.1000141.php?aid=27490. It therefore might be good to create ORDO terms accordingly. I think the phenotypic features can be described with current ulceration terms etc.
