### ISSUE TITLE
new term:Medially deviated thumb?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1621]

**Comment by pnrobinson** [comment]
I think you mean, Adducted thumb.
If you mean the insertion of the thumb is medial, please reopen this request or provide more context.

**Comment by LOURGHI** [comment]
It was observed in Pfeiffer syndrome type 1,Pfeiffer syndrome type 2 and Pfeiffer syndrome type 3.
