### ISSUE TITLE
new term:Mucosal erosions ?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1633]

**Comment by pnrobinson** [comment]
@LOURGHI This term is too broad because it does not define what mucosa is meant, e.g., oral, intestinal, bladder. Could you provide more details and context?

**Comment by LOURGHI** [comment]
This sign was observed in Epidermolysis bullosa simplex with pyloric atresia(PMID: 20301336).

**Comment by pnrobinson** [comment]
I think that this is oral and laryngeal mucous membranes, see https://www.ncbi.nlm.nih.gov/pubmed/10652001

**Comment by LOURGHI** [comment]
I think so.

**Comment by pnrobinson** [comment]
Add Erosion of oral mucosa as HP_0031446
