### ISSUE TITLE
new term:Mucosal nodule ?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1634]

**Comment by pnrobinson** [comment]
@LOURGHI  can you provide more information? What mucosa is affected? This is too broad unless we specify the location.

**Comment by LOURGHI** [comment]
this sign was observed in Multicentric reticulohistiocytosis,this is all I have as context.

**Comment by pnrobinson** [comment]
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3481828/
According to this there are buccal, tongue or nasal mucosa nodules.

**Comment by pnrobinson** [comment]
Here is another case report (no mucosal involvement though)
http://jamanetwork.com/journals/jamadermatology/fullarticle/1105215

**Comment by pnrobinson** [comment]
Adding Oral mucosa nodule as HP_0031445
