### ISSUE TITLE
new term:Myoclonic astastic epilepsy?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1649]
Add synonym:Doose syndrome.

**Comment by pnrobinson** [comment]
This is not a phenotype, it is a disease,and it should receive an ORPHA id. The clinical manifestations as summarized here http://www.epilepsy.com/information/professionals/about-epilepsy-seizures/idiopathic-generalized-epilepsies/epilepsy-0
should all have HPO terms.
