### ISSUE TITLE
new term:sleep seizure?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1650]

**Comment by pnrobinson** [comment]
@LOURGHI  This is something that we should probably use a clinical modifier for, since seizures during sleep can occur with any type of epilepsy, although some kinds show a prediliction. Can you give us more context?

**Comment by LOURGHI** [comment]
Sorry,I have no context.

**Comment by pnrobinson** [comment]
I would close this issue then. Perhaps it is appropriate to use the modifier "nocturnal"
