### ISSUE TITLE
new term:Cold hands ?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1666]

**Comment by pnrobinson** [comment]
This is not really an abnormal phenotype, since it is commonly observed with cold weather. Do you perhaps mean Raynaud phenomenon (which is an HPO term)? I am closing this issue, but please reopen with more context and detail if needed.

**Comment by LOURGHI** [comment]
It was observed with cold paresis in Monomelic amyotrophy,PMID:22032508.On paper it is rather cold extremities.
