### ISSUE TITLE
new term:cochleosaccular degeneration ?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1682]

**Comment by pnrobinson** [comment]
This is a bundled term. Possibly you are referring to this disease
http://www.omim.org/entry/120040
There may not be information on this family, but the phenotype is Inner ear pathologic changes limited to the cochlea and saccule, i.e., two items. 
Please use Cochlear degeneration HP_0005102 and I will create a new term,
Vestibular saccular degeneration (note there is an analogous MP term).
