### ISSUE TITLE
new term:Mega cisterna magna?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1684]

**Comment by pnrobinson** [comment]
This is HP:0002280, Enlarged cisterna magna

The term mega cisterna magna has been loosely applied to an enlarged cisterna magna, also known as the cerebellomedullary cistern. 

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3395281/

I will add mega cisterna magna aas a related synonym
