### ISSUE TITLE
new term:Low self esteem?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1688]

**Comment by pnrobinson** [comment]
@cmungall @jmcmurry @mellybelly @drseb 
I am thinking that we can add a subhierarchy to behavior that would reflect the DSM V thinking to some extent. 
Table 1 in this paper https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3848950/
provides a high level overview.  I would propose a term called
Impairment in personality functioning
--subterm 1
--subterm 2

with the appropriate phenotypic features that make up the DSM criteria for diagnosis being represented here. We need to add more terms for behavioral features.  Please let me know any comments or concerns before I start this!

**Comment by pnrobinson** [comment]
I had added several terms in this category.
