### ISSUE TITLE
new term:Gender dysphoria?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1689]

**Comment by pnrobinson** [comment]
This is a difficult area to model ontologically. But if we look at the DSM,then it is apparent that there are at least 6 phenotype features that are used to make the diagnosis of gender dysphoria -- suggesting that it is best not to model gender dysphoria as a single phenotypic feature. 

See here:

https://www.psychiatry.org/patients-families/gender-dysphoria/what-is-gender-dysphoria

The HPO project is planning to extend coverage of behavioral features,but this is something that we will structure as a series of workshops and a concerted action,it is not something that is really easy to do with individual issues.
