### ISSUE TITLE
new term:tachypsychia?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1692]

**Comment by pnrobinson** [comment]
This does not appear to be a medical phenotype -- not a single mention in pubmed. Instead, it seems to be referring to the feeling one can get while exercising that time slows down. I would say that this is too much of a "fuzzy" description that I would prefer not to make it an HPO term unless we can find evidence that it truly is an abnormal phenotype that is associated with diseases. Please reopenthis item  with additional information if needed. 

see
https://en.wikipedia.org/wiki/Tachypsychia
