### ISSUE TITLE
new term:Capillary ectasia?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1699]
Add synonym:capillary dilatation

**Comment by pnrobinson** [comment]
@LOURGHI  Can you provide more context? Which capillaries are being referred to?  We will need to add the anatomic structure to avoid ambiguity.

**Comment by LOURGHI** [comment]
Sorry I have no context.

**Comment by pnrobinson** [comment]
I do not think there is any way of knowing what the phenotypic abnormality was here. I am closing this item. But please open a new item if more information/context becomes available in the future.
