### ISSUE TITLE
new term:Superior vena cava syndrome ?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1705]

**Comment by pnrobinson** [comment]
Superior Vena Cava Syndrome is a disease entity comprising many manifestations of obstruction of blood through the Superior Vena Cava. I think that the HPO term should be
Obstruction of the SVC

**Comment by LOURGHI** [comment]
But this syndrome could be caused by obstruction or compression of the superior vena cava .
In fact this sign was observed in the Thymic carcinoma therefore it is rather a compression??
