### ISSUE TITLE
new term:Acute ischemia of the lower limbs?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1712]

**Comment by pnrobinson** [comment]
@LOURGHI I think that this is very probably the HPO term Intermittent claudication (HP:0004417). 
If this is not the case, please open a new issue with more context and details.

**Comment by LOURGHI** [comment]
This sign has been found as such in the following diseases:
Polyarteritis   nodosa
Ehlers-Danlos  syndrome, vascular type
Hypoalphalipoproteinemia
Buerger disease
Familial thrombocytosis
Cogan syndrome

I think this term is more general than intermittent claudication.
