### ISSUE TITLE
new term:Recurrent carotid artery dissection?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1717]

**Comment by pnrobinson** [comment]
We now have the term "Spontaneous carotid artery dissection". I think most dissections are, and I would propose we remove the word spontaneous (which is like an NOS "specifier") from the term and then that term can be used to annotate this together with the clinical modifier "Recurrent". I will makethis change next week if no counterarguments are made.

**Comment by pnrobinson** [comment]
I see that we already had a term for carotid artery dissection (HP:0012158). This can be used with the 'Recurrent' modifier for annotations.
