### ISSUE TITLE
new term:Aortic dissection in pregnancy?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1718]

**Comment by pnrobinson** [comment]
This is difficult. We have the modifier Triggered_by_pregnancy, but in an individual we do not know if a sign was triggered by pregnancy or simply occured during pregnancy.
@drseb @cmungall @mellybelly Should we have an additional onset term Onset during pregnancy?

**Comment by drseb** [comment]
Is this for the mother or for the child?

**Comment by drseb** [comment]
Probably you are referring to the mother. I feel like "triggered by pregnancy" is more appropriate. Where would you put "Onset in pregnancy" in the hierarchy then?

**Comment by pnrobinson** [comment]
Yes, but how do we know the dissection really was triggered by pregnancy in any individual case? This is not always correct.

**Comment by drseb** [comment]
Hmm... I see. But the term label should make clear that this is referring to the lifestage where the individual is itself being pregnant. Something like "Onset while being pregnant". Maybe it is just me, that finds "Onset in pregnancy" irritating...

**Comment by pnrobinson** [comment]
In any case, this is referring to an individual patient who suffered aortic dissection during pregnancy, and not to a disease. To my knowledge, pregnancy is a risk factor for dissection in any woman with a dilated aorta. However, the HPO does not currently try to record risk factors, and I think this needs to go outside of the current annotation scheme. We may be able to do this in a year or two with the common disease data structures.
