### ISSUE TITLE
new term:smooth muscle cell media hyperplasia?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1720]

**Comment by pnrobinson** [comment]
@LOURGHI  This should be specified as to which blood vessel is involved, e.g., pulmonary (https://www.ncbi.nlm.nih.gov/pubmed/23737174). Please provide more context

**Comment by LOURGHI** [comment]
Sorry I have no contex.

**Comment by pnrobinson** [comment]
I am not convinced this is a clinical phenotype, i.e., something that is observed during the medical encounter. Instead this is part of the pathogenesis of many diseases that has been defined by animal studies etc. I would suggest we hold off on this term and consider adding the clinical observations that are related in a focussed way.
