### ISSUE TITLE
new term:Lung cysts?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1733]

**Comment by pnrobinson** [comment]
There are several terms in the HPO such as bronchogenic cyst that probably are what you mean. Can you please reopen an issue with more detail if this in not sufficient.

**Comment by LOURGHI** [comment]
It's noted :Multicystic kidney/renal dysplasia + lung cysts in Cystic hamartoma of lung and kidney.
