### ISSUE TITLE
new term:Polypoid bladder?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1743]

**Comment by pnrobinson** [comment]
@LOURGHI  please provide more context.
There are many polypoid masses of the bladder (e.g., http://www.oapublishinglondon.com/article/1163)
The term polypoid cystitis has a special meaning:
Polypoid cystitis is a reversible, exophytic, inflammatory lesion of the bladder mucosa that is histologically characterized by normal or mildly hyperplastic urothelium, overlying a congested, chronically inflamed and markedly edematous stroma, but with metaplasia being rarely found
,from https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3522325/
However I am not familiar with "Polypoid bladder"

**Comment by LOURGHI** [comment]
Polypoid bladder was observed in Junctional epidermolysis bullosa - pyloric atresia with Hemorragic cystitis .
This is all I have as context.

**Comment by pnrobinson** [comment]
As far as I can see, this refers to a polyploid chromosomal finding -- this is a somatic alteration 
(perhaps similar to https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5006783/)
THe HPO does not provide terms describing the genotype of patients -- this needs to be kept separate.
Also note that the correct spelling is polyploid.

**Comment by drseb** [comment]
@pnrobinson note: polypoid vs. polyp**l**oid (no L in the first version)

**Comment by pnrobinson** [comment]
I think that the best term for this is simply Bladder polyp,since that is the phenotypic observation. A description such as Polypoid bladder sounds more like a disease. I will add it as a related synonym,.
