### ISSUE TITLE
new term:Pyeloureteral duplication  ?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1754]

**Comment by pnrobinson** [comment]
THis is almost always seen with duplicated collecting system (HP_0000081), but can also be coded as the combination duplicated ureter (several terms depending on anatomy) and duplicated renal pelvis (HP_0010946).

**Comment by LOURGHI** [comment]
I think it's better to annotate with Duplication of renal pelvis HP:0005580 and Ureteral duplicationHP:0000073.(HP_0010946=Dilatation of the renal pelvis).
