### ISSUE TITLE
new term:Urinary tract atony?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1763]

**Comment by pnrobinson** [comment]
@LOURGHI  Is this referring to atonic bladder?
I think it is better to have atony terms for each of the components of the urinary tract.
Do you have more context?

**Comment by LOURGHI** [comment]
Sorry I have no context.

**Comment by pnrobinson** [comment]
I am going to add a term for atonic bladder (see #2499), and probably this can be used to annotate this case if needed. I will close this issue and follow up via #2499.
