### ISSUE TITLE
new term:urethrorectal fistula?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1764]

**Comment by pnrobinson** [comment]
This is HP_0025407, Rectourethral fistula.
I am adding this as a synonym.

**Comment by LOURGHI** [comment]
I have doubts about the synonymy,
urethrorectal fistula implies that the pathological process begins at the urethra and ends in the rectum,while 
Rectourethral fistula implies the opposite ??????

**Comment by pnrobinson** [comment]
Fistulas are not directional in the sense of having peristalsis and so the gradient of flow is determined by the pressure difference in the two cavities that are connected. The order of the words does not imply pathophysiology. I am pretty sure that these two words are equivalent.

**Comment by LOURGHI** [comment]
It was just a doubt,thank's.
