### ISSUE TITLE
new term:Abnormal Wolff ducts?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1770]

**Comment by pnrobinson** [comment]
@LOURGHI  The Wolffian duct is an embryonic structure, the embryonic duct of the mesonephros, which in the male becomes the vas deferens and in both sexes gives rise to the ureter.
Therefore, is this term really referring to the Wolffian duct? Or is it referring to something that emerges from the Wolffian duct in the course of development. In the latter case, we would use a term for the adult structure, e.g., abnormality of vas deferens. 
Please provide more context!

**Comment by LOURGHI** [comment]
Sorry I have no context.

**Comment by pnrobinson** [comment]
In that case I would suggest we not make an HPO term at this time, I do not think this is measured clinically.
