### ISSUE TITLE
new term:Intestinal perforation ?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1775]

**Comment by pnrobinson** [comment]
@LOURGHI  I think we should make terms for the specific part of the intestine. Do you have information about where the perforation was located or other information about the disease? Was it Ehlers Danlos vascular type?

**Comment by LOURGHI** [comment]
This sign has been found as such in the following diseases:
Polyarteritis nodosa
Ehlers-Danlos syndrome, vascular type(I havn't found PMID on our data base but this desease is annotated on orphamizer)
Lyell syndrome
Malignant atrophic papulosis.

**Comment by pnrobinson** [comment]
Adding as HP_0031368 (together with subclasses)
