### ISSUE TITLE
new term:Short bowel?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1776]

**Comment by drseb** [comment]
is this referring to the disease "Short bowel syndrome"?

Otherwise probably a synonym or subclass of "Hypoplasia of the small intestine"

**Comment by LOURGHI** [comment]
Exactly, this sign describes as others(Hypospadias,Short stature,intellectual deficit..)the Congenital short bowel syndrome.My colleague had annotated it with HP:0005245 Intestinal hypoplasia.

**Comment by drseb** [comment]
@pnrobinson synonym or subclass? thx

**Comment by LOURGHI** [comment]
as a related synonym??
