### ISSUE TITLE
new term:Orange-yellow appearance  of the liver?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1780]

**Comment by pnrobinson** [comment]
I think that we will need a more detailed description. I did not find any term in PubMed or Google that indicates that this kind of description is in general use, and it is not a good idea to make a term for an imprecise description that is only used in one publication. Please reopen if necessary but provide a more detailed description.

**Comment by LOURGHI** [comment]
Sorry I have no context.
