### ISSUE TITLE
new term:Head retroflexion ?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1786]

**Comment by pnrobinson** [comment]
@LOURGHI  do you mean "fixed" retroflexion of the head as in https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4173238/

**Comment by LOURGHI** [comment]
It was observed in Iniencephaly,absence of the neck + Head retroflexion PMID:26167231.
