### ISSUE TITLE
new term:Bone tumefaction?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1790]

**Comment by pnrobinson** [comment]
Tumefaction is a really old word that is not used at all anymore.
 an action or process of swelling or becoming tumorous
See here (1899)
https://books.google.com/books?id=QBkUAAAAYAAJ&pg=PA251&lpg=PA251&dq=Bone+tumefaction&source=bl&ots=j0GTu96Duf&sig=BS4vQRDvPQJX_fu2fZeDVOwp4AM&hl=de&sa=X&ved=0ahUKEwif_eeU3-_TAhWB0iYKHY49D-kQ6AEIKjAA#v=onepage&q=Bone%20tumefaction&f=false
THere are terms for bone neoplasm.
Please reopen with more details if necessary.

**Comment by LOURGHI** [comment]
It was observed in Gnathodiaphyseal dysplasia,Majeed syndrome,Adult chronic recurrent multifocal osteomyelitis,Aggressive systemic mastocytosis,Eosinophilic granuloma,Maffucci syndrome,Caffey disease,Langer-Giedion syndrome,Sturge-Weber syndrome,Cranio-osteoarthropathy,Enchondromatosis........

**Comment by pnrobinson** [comment]
OK,I will have a look, but I think we need to figure out how to describe what this is using a more modern term!

**Comment by pnrobinson** [comment]
I am sorry, but I still do not understand the intended meaning of "bone tumescence".  Does it mean bone tumor? For instance Langer-Giedion syndrome can be characterized by cervical spinal exostoses? I think it would be better to use the specific annotations, unless I am not understanding something.

**Comment by LOURGHI** [comment]
It's true that it's a broad term that can include tumor and swelling,and on all the diseases I have mentioned, it was marked bone tumefaction/swelling .

**Comment by pnrobinson** [comment]
The HPO attempts to have specific terms. I do not thhink that in 2017 any one would use this term; if there was a swelling then it would be termed "swelling" or "mass" perhaps at the first examination but would then be investigated by X ray or whatever. I would suggest that we do not include this term but instead attempt to annotate the individual diseases with the individual type of tumor or mass that they have such as exostosis.
