### ISSUE TITLE
new term:Angel-shaped middle phalanges ?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1791]

**Comment by pnrobinson** [comment]
I think you are referring to the epiphysis of the phalanges?
THis term is probably what you are looking for. Please reopen the issue if this is not the case.

**Comment by LOURGHI** [comment]
It was observed in Angel-shaped phalango-epiphyseal dysplasia,because of its resemblance to the little angels used for the decoration of Christmas trees.

**Comment by pnrobinson** [comment]
But co

**Comment by pnrobinson** [comment]
My initial comment was wrong. I am adding a term.
