### ISSUE TITLE
new term:Absent vertebrae cervical and thoracic?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1794]

**Comment by pnrobinson** [comment]
@LOURGHI  DO you mean the complete absence of one cervical and one thoracic vertebra or the complete absence of that part of the spine?  Please provide the disease and more details. THis seems to be a rare phenotype.

**Comment by LOURGHI** [comment]
it's mentioned Spina bifida + Absent vertebrae(absent vertebrae cervical and thoracic) in Iniencephaly.

**Comment by pnrobinson** [comment]
Adding two terms -- Absent cervical vertebra and Absent thoracic vertebra
