### ISSUE TITLE
new term:Femur egg-shaped neck?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1798]

**Comment by pnrobinson** [comment]
I think this is probably best annotated with "Broad femoral neck". If the "egg shape" is really something characteristic and recognizable,then please reopen this issue with more information and a pubmed reference or radiograph!

**Comment by LOURGHI** [comment]
It was observed in Acrocapitofemoral dysplasia,PMID:12624140.
