### ISSUE TITLE
new term: V-shaped notching of ribs?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1799]

**Comment by pnrobinson** [comment]
@LOURGHI  I cannot find any information on this. Can you provide details?

**Comment by LOURGHI** [comment]
It was observed in Spondylometaphyseal dysplasia, Sedaghatian type,PMID:16892303.

**Comment by pnrobinson** [comment]
As far as I can see Figure 1 of PMID:16892303 does not show notching of the ribs. I also did not find a reference to V-shaped notching elsewhere. I am going to close this issue because given that there is not that much information it does not seem like it is a characteristic phenotypic abnormality.
