### ISSUE TITLE
new term:dorsal rib defects ?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1800]

**Comment by pnrobinson** [comment]
@LOURGHI  COuld you please describe what defects were seen? Was it a bony defect or is the word defect being used to describe a general abnormality?

**Comment by LOURGHI** [comment]
Posterior rib gaps, dorsal rib defects, flail chest were observed in Cerebro-costo-mandibular syndrome,
 This is all I have as information.

**Comment by pnrobinson** [comment]
I see. This is HP_0030282, Posterior rib gap. I am adding "Dorsal rib defect" as a synonym.
