### ISSUE TITLE
new term:notched tibia?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1805]

**Comment by pnrobinson** [comment]
@LOURGHI  Please provide additional explanations and context. The tibia normally has a notch: https://en.wikipedia.org/wiki/Fibular_notch
Is this phenotypic feature something different than that?

**Comment by LOURGHI** [comment]
Sorry I have no context.

**Comment by pnrobinson** [comment]
Without more information I do not think it is possible to create a term for this,and I am closing this issue.
