### ISSUE TITLE
new term:tibia vara?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1807]

**Comment by pnrobinson** [comment]
@LOURGHI  I have never heard tibia vara being used.
According to wikipedia, this term is used for genu varum. https://en.wikipedia.org/wiki/Tibia_vara
Can you provide us with more detail please?

**Comment by LOURGHI** [comment]
I have no context but please get a look on PMID: 27741108 .

**Comment by pnrobinson** [comment]
As far as I cansee the term"tibia vara" is used as a synonym forthe disease Blount's disease (https://en.wikipedia.org/wiki/Blount%27s_disease)
The phenotypic feature is bowed legs,and that is HP_0002979
