### ISSUE TITLE
new term:Prominent joints?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1808]

**Comment by pnrobinson** [comment]
@LOURGHI  I would say this is probably the same thing as HP:0003037, Enlarged joints, but could you add more details/context?

**Comment by LOURGHI** [comment]
This sign was observed in Spondylometaphyseal dysplasia, Kozlowski type,PMID:20577006

**Comment by pnrobinson** [comment]
I think this is a synonym and I will add it as a related synonym
