### ISSUE TITLE
new term: fusion of the iliac wings?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1810]

**Comment by pnrobinson** [comment]
@LOURGHI  Fusion with what?

**Comment by pnrobinson** [comment]
I think that this is a normal part of bone development, https://radiopaedia.org/articles/risser-classification
Please reopen this issue if necessary, but provide more detail on the observed phenotype!

**Comment by LOURGHI** [comment]
It was observed in Caudal regression sequence with abnormality of pelvic girdle bone morphology,this is all I have as context.
