### ISSUE TITLE
new term:Periarticular swelling?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1819]

**Comment by pnrobinson** [comment]
There is a term for "Joint swelling". Periarticular means "surrounding the joint", but in reality it is probably hard to distinguish. @LOURGHI  Is there evidence that these are different features in the disease you are curating, or can we make Periarticular swelling a related synonym of joint swelling?

**Comment by LOURGHI** [comment]
I have no precision on that but it was observed in Hyaluronidase deficiency.8793927[PMID].

**Comment by pnrobinson** [comment]
According to here, it is not periarticular swelling but it is periarticular masses:
http://www.nejm.org/doi/full/10.1056/NEJM199610033351405#t=article

**Comment by pnrobinson** [comment]
I am closing this issue, but please reopen it if there is a difference between periarticular swelling and joint swelling -- please provide references and details.
