### ISSUE TITLE
new term:Sterile arthritis ?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1822]

**Comment by drseb** [comment]
I see... should I delete the added term?

**Comment by drseb** [comment]
Sorry. Was not careful enough here

**Comment by pnrobinson** [comment]
Sterile arthritis is a disease entity in that it has an etiology (arthritis not caused by infectious agents that can be cultured). However, like some other HPO terms, it can also be a feature of other diseases. So I would not remove it for now, but let's add a definition to the term.

**Comment by drseb** [comment]
ok

**Comment by drseb** [comment]
https://github.com/obophenotype/human-phenotype-ontology/issues/2157
