### ISSUE TITLE
new term:extraarticular calcifications?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1825]

**Comment by pnrobinson** [comment]
@LOURGHI  Any calcification that is outside of a joint is an extraarticular calcification. Therefore, it would be better to define exactly where the calcification is that is being referred to. Please provide additional detail!

**Comment by pnrobinson** [comment]
I am adding a term for Periarticular calcification, and I think these two items are synonymous.

**Comment by LOURGHI** [comment]
We find this term in Pseudoxanthoma elasticum,Reynolds syndrome,Antisynthetase syndrome,Fibromyalgia,
Tumoral calcinosis.
