### ISSUE TITLE
new term:Alveolar bone deterioration?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1828]

**Comment by pnrobinson** [comment]
@LOURGHI  I think that you mean "Atrophy of alveolar ridges" (HP_0006308). The use of "deterioration" is not idiomatic in English, I think. Could you get back to me if you are referring to the same thing?

**Comment by pnrobinson** [comment]
I think a better label is Alveolar bone loss, synonym, Alveolar atrophy

**Comment by pnrobinson** [comment]
I think this is synoynmous with "Atrophy of alveolar ridges"  -- I will add alveolar bone loss as a related synonym.
