### ISSUE TITLE
new term:Radial ray defects?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1829]

**Comment by pnrobinson** [comment]
@LOURGHI  This is a spectrum of defects
https://radiopaedia.org/articles/radial-ray-anomaly
I think the term is used to group several items together that do not belong to the same hierarchy in HPO (radius and thumb), and this is difficult to add as a grouping term for that reason. Please add the individual phenotypic abnormalities observed, which are probably those that were mentioned in the link above.
