### ISSUE TITLE
new term:tendinitis?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1832]

**Comment by pnrobinson** [comment]
This is HP_0025230 (note misspelling --  it should be tendOnitis).

**Comment by kanems** [comment]
Question about the synonym on Tendonitis HP:0025230: "Teninitis," is this a typo? 
(SNOMED uses both Tendinitis and Tendonitis, but HPO appears to be the only source in UMLS that uses the spelling "teninitis")

**Comment by pnrobinson** [comment]
That's a typo, thanks for pointing out the mistake!
