### ISSUE TITLE
new term:Striated metaphysis?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1834]

**Comment by pnrobinson** [comment]
@LOURGHI  PLease let us know if this is a localized or generalized feature and provide somemore context. The HPO alrady has Osteopathia striata, but there are other forms or metaphyseal striation.

**Comment by LOURGHI** [comment]
SPONASTRIME dysplasia (SD) is an autosomal recessive skeletal dysplasia of the spondyloepimetaphyseal dysplasia(SEMD) type. The name was derived from ‘‘spondylar and nasal alterations with striated metaphyses
 [Fanconi et al.1983]
Patient 5 had metaphyseal striations of the knees.PMID:18203204

**Comment by pnrobinson** [comment]
Adding as HP_0031367
