### ISSUE TITLE
new term:Musculo-tendinous retractions?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1835]

**Comment by pnrobinson** [comment]
@LOURGHI  Do you mean this?
https://www.ncbi.nlm.nih.gov/pubmed/22174340
Do you mean a retraction of one specific joint or a generalized phenomenon? Please provide more context.

**Comment by LOURGHI** [comment]
this sign was observed in Systemic sclerosis,Ledderhose disease,Farber lipogranulomatosis and Scleroderma.
