### ISSUE TITLE
new term:Bone ankylosis?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1836]

**Comment by pnrobinson** [comment]
Ankylosis or anchylosis is a stiffness of a joint due to abnormal adhesion and rigidity of the bones of the joint
@LOURGHI  The HPO already has several ankylosis terms as well as Joint stiffness. Do anothem apply to the phenotype you want to describe? Please provide more detail.

**Comment by pnrobinson** [comment]
Note that bony ankylosis is a synonym for synostosis
http://gradestack.com/Dr-Bhatia-Medical/Bony-ankylosis-occurs-in-/95-3042-3176-23201-sf
I am adding this as a synonym. I think that today synostosis is used more often than ankylosis.
