### ISSUE TITLE
new term:Hips flexed and abducted in a "frog-leg" position?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1837]

**Comment by pnrobinson** [comment]
@LOURGHI  I guess you are referring to something like this?
https://www.ncbi.nlm.nih.gov/pubmed/1264518
I will look for a better way of saying this than frog-leg, which could be interpreted as derogatory.

**Comment by LOURGHI** [comment]
It was observed in Osteogenesis imperfecta,this is  all I have as context.

**Comment by nicolevasilevsky** [comment]
On an episode of Grey's Anatomy, a baby had Osteogenesis imperfecta and they were describing the baby as sitting like a little buddha. Maybe that could be a layperson synonym for whatever term you decide to add?

**Comment by pnrobinson** [comment]
I think this is referring to an infant with severe muscular hypotonia and who cannot sit up and when lying supine cannot control the position of the legs, that take on a "frog-leg" position.

**Comment by pnrobinson** [comment]
Adding term, Frog-leg posture
Def: A type of rest posture in an infant that indicated a generalized reduction in muscle tone. The hips are flexed and the legs are abducted to an extent that causes the lateral thigh to rest upon the supporting surface. This posture is said to resemble the legs of a frog.
