### ISSUE TITLE
new term:Acrania ?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1840]

**Comment by pnrobinson** [comment]
@LOURGHI  This seems synonymous with Calvarial skull defect or do you see a distinction?

**Comment by LOURGHI** [comment]
Anencephaly/acrania were observed in VACTERL/VATER association,Cerebrotendinous xanthomatosis,Cockayne syndrome,Tuberous sclerosis and Distal monosomy 13q.

**Comment by pnrobinson** [comment]
This is HP_0030716.
