### ISSUE TITLE
new term:Shoulder hypertrophic arthropathy?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1841]

**Comment by pnrobinson** [comment]
@LOURGHI  Do you mean "hypertrophic osteoarthropathy" of the shoulder? Please provide more details!

**Comment by LOURGHI** [comment]
It seems to me that it is the same, 
Sorry I have no context.

**Comment by pnrobinson** [comment]
I think that Hypertrophic osteoarthropathy is probably best conceptualized as a disease.
For instance here is a description.
Hypertrophic osteoarthropathy (HOA) is a syndrome of clubbing of the digits, periostitis of the long (tubular) bones, and arthritis.
The HPO has terms for these three phenotypes.
