### ISSUE TITLE
new term:Radially deviated forearms?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1842]

**Comment by pnrobinson** [comment]
@LOURGHI  Given the fact that the forearm can pronate and supinate, I am not sure I understand what is meant here. Is it a reduced extension of the forearm? Could this be Elbow flexion contracture (HP_0002987). Please provide more context and a detailed description!

**Comment by LOURGHI** [comment]
I think it is synonym of Cubitus valgus but I have no context.

**Comment by pnrobinson** [comment]
I do not think this is a great synonym because it is unclear what is meant -- maybe it is best to annotate with Cubitus valgus, and if there is another request for this term, we can ask what is meant.
