### ISSUE TITLE
new term: eosinophils inclusions bodies?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1847]

**Comment by pnrobinson** [comment]
@LOURGHI 
This is ambiguous -- one would usually say eosinophilic inclusion bodies, but here eosinophilic is not referring to the cell type eosinophil but to a type of stain (that eosinophils also display). Could you give us more context and a definition please?

**Comment by LOURGHI** [comment]
Sorry,I have no context.

**Comment by pnrobinson** [comment]
It is difficult to create the correct term for this then. Please open a new issue if more context becomes available.
