### ISSUE TITLE
new term:bronchoalveolar cancer?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1878]

**Comment by pnrobinson** [comment]
@LOURGHI  This is not a term for a cancer that is used in the NCIT hierarchy -- we are aiming to integrate with this system in the future. The diagnostic categories for some cancers are changing with time and the HPO would like to use up to date terminology, therefore, I would suggest we not make this a new term. 
Please reopen a new issue with more context and data if you think this is mistaken. Also, please consult the NCIT site https://ncit.nci.nih.gov/ncitbrowser/pages/message.jsf
