### ISSUE TITLE
new term: Skin pseudolymphom?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1880]

**Comment by pnrobinson** [comment]
The label should be cutaneous lymphoma
https://www.ncbi.nlm.nih.gov/pubmed/20797521

**Comment by LOURGHI** [comment]
On the file of my colleague it is noted: lymphocytoma CUTIS, Skin pseudolymphoma
Observed in Lyme disease ISBN: 9781405161695

**Comment by pnrobinson** [comment]
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4248499/
