### ISSUE TITLE
new term:Malignant parathyroid adenoma?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1902]

**Comment by pnrobinson** [comment]
@LOURGHI are you sure about malignant -- afaik the vast majority of parathyroid adenomas are benign, and this term is not in NCIT. I will close this issue for now. Please use either the existing term parathyroid adenoma (HP:0002897) or open a new issue with a definition and a pubmed refernece to support the "malignant" parathyroid adenoma.
