### ISSUE TITLE
new term:Ovarian cancer ?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1903]

**Comment by pnrobinson** [comment]
Please see HP_0100615.

**Comment by nicolevasilevsky** [comment]
@pnrobinson we can give this a logical def, right?

'has part' some 
    ('increased amount'
     and ('inheres in' some 
        (Neoplasm
         and ('part of' some 'female gonad')))
     and ('has modifier' some abnormal))

**Comment by pnrobinson** [comment]
I do not think the definition is specific enough, because I think it would also apply to a metastasis that is localized in the ovary. @cmungall  ?

**Comment by nicolevasilevsky** [comment]
Oh right, and I just noticed that these logical definition is used for HP_0100615 Ovarian neoplasm. This is probably an example of a term that is too complicated for a logical definition.

**Comment by pnrobinson** [comment]
I am going to close this since I think we will revisit the topic in a systematic way as part of the planned interactions with NCI.
