### ISSUE TITLE
new term:ovarian juvenile granulosa cell neoplasm?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1905]

**Comment by pnrobinson** [comment]
see https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4253180/
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI_Thesaurus&version=18.03d&ns=ncit&code=C7289&key=n2104787201&b=1&n=null

**Comment by pnrobinson** [comment]
Adding as HP:0031019
Juvenile type ovarian granulosa cell tumor
