### ISSUE TITLE
new term:Trophoblastic tumor ?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1907]

**Comment by pnrobinson** [comment]
@LOURGHI Are you referring to gestational trophoblastic tumor?
see https://en.wikipedia.org/wiki/Gestational_trophoblastic_disease

**Comment by LOURGHI** [comment]
This sign was found in Placental site trophoblastic tumor and Gestational trophoblastic neoplasm.

**Comment by pnrobinson** [comment]
Adding term Trophoblastic tumor HP_0031502
