### ISSUE TITLE
new term:presacral ganglioma?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1910]

**Comment by pnrobinson** [comment]
@LOURGHI  
Do you mean Presacral ganglioneuroma?
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4319138/

**Comment by LOURGHI** [comment]
Sorry I have no context.

**Comment by pnrobinson** [comment]
I am adding Presacral ganglioneuroma then.
