### ISSUE TITLE
new term:eyelid neoplasm?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1915]

**Comment by pnrobinson** [comment]
@LOURGHI Probably it is best to use one of the terms for skin neoplasm -- unless there is some reason to believe that there is something unique about the location on the eyelid. If the latter is the case, then please reopen this issue with more clinical details.

**Comment by LOURGHI** [comment]
It's noted Conjunctival neoplasms, Corneal neoplasms, Eyelid neoplasms in De Sanctis-Cacchione syndrome.
