### ISSUE TITLE
new term:Parotid oncocytoma?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1922]

**Comment by pnrobinson** [comment]
@LOURGHI Do you mean Salivary gland oncocytoma (https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI_Thesaurus&version=17.07e&ns=NCI_Thesaurus&code=C5932&key=1330410907&b=1&n=null)

**Comment by LOURGHI** [comment]
It seems to me that it's the same .(https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2827107/)

**Comment by pnrobinson** [comment]
It is only most cases that occur in the Parotid gland. I think that Salivary gland oncocytoma is the better primary label.
