### ISSUE TITLE
new term:virilization at puberty?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1929]

**Comment by pnrobinson** [comment]
@LOURGHI  This seems to be a normal phenotype (for boys). Please reopen this term if there is a specific abnormality, and provide more context and detail.

**Comment by LOURGHI** [comment]
It was observed in 46,XY disorder of sex development due to 5-alpha-reductase 2 deficiency,I think the most 
appropriate term is lack of virilization at puberty??
