### ISSUE TITLE
new term:Longer gestational age?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1936]

**Comment by pnrobinson** [comment]
@LOURGHI  I am sorry, I do not know what this intends to mean?

**Comment by LOURGHI** [comment]
Sorry, I have no context.

**Comment by pnrobinson** [comment]
I am going to add a term for Postterm pregnancy
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3991404/
This is the only thing I can think of that might be meant.

**Comment by pnrobinson** [comment]
Added as HP_0031169
