### ISSUE TITLE
new term:Increased LH response after LHRH stimulation test?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1939]

**Comment by pnrobinson** [comment]
To the best of my knowledge,there is a Gonadotropin releasing hormone that works for LH and FSH, se https://www.ncbi.nlm.nih.gov/gene/2796 and https://en.wikipedia.org/wiki/Gonadotropin-releasing_hormone. I am going to call this term Increased LH response after GnRH stimulation test
