### ISSUE TITLE
new term:High iodine uptake ?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1942]

**Comment by pnrobinson** [comment]
@LOURGHI  are we talking about a thyroid  test?

**Comment by LOURGHI** [comment]
I don't have a context, but I think that should be Positive Radioactive Iodine Uptake Test.

**Comment by pnrobinson** [comment]
Adding terms for abn, increased and decreased Radioactive Iodine Uptake Test.
