### ISSUE TITLE
new term:Puerile voice?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1951]

**Comment by drseb** [comment]
synonym of "High pitched voice"?

**Comment by BrunOrpha** [comment]
This may be a recurrent problem for pubertal diseases and would either be a clinical modifier ? 
Pre-pubertal can be applied to: voice, internal/external genitals for instance.
I do not know if HPO choose the phenome at the moment of the clinical examination, but the hint would be that this phenome may be totally reversible after hormonal treatment's start, as opposed to others malformations syndromes with lifelong uterus hypoplasia or lifelong high pitched voice (like in Werner's syndrome).

https://www.ncbi.nlm.nih.gov/pubmed/23565415

**Comment by pnrobinson** [comment]
I am not sure if this is a translation issue, but for me the word puerile has the connotation of "silly/childish", and I do not think that is what is intended. @LOURGHI  Please reopen this if you provide more detail? If not, then I would suggest that high-pitched voice would be the best term for annotation.

**Comment by LOURGHI** [comment]
I think high pitched voice does not describe having a child's voice at an adult age as the term implies.
If we take the opposite of high pitched voice it is  weak voice.on the other side the opposite of pueril voice is adult voice.Which is not at all the same...

**Comment by BrunOrpha** [comment]
ok, "puerile" voice seems inapproriate: how about"pre-pubertal voice" instead ? (implying evolutivity), otherwise how can the HPO coding be for the following examples ?
https://www-ncbi-nlm-nih-gov.gate2.inist.fr/pubmed/15475787
https://www-ncbi-nlm-nih-gov.gate2.inist.fr/pubmed/17459124
