### ISSUE TITLE
new term:reversible Hypogonadism?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1953]

**Comment by pnrobinson** [comment]
Do we need to add the qualifier "reversible"? We would only do so if it is characteristic of a disease entity. I have seen this only as a complication of doping in sports: Reversible hypogonadism and azoospermia as a result of anabolic-androgenic steroid use
I think that perhaps it is better to use the HPO term Hypogonadism unless the reversibility is a defining characteristic of a disease. Please reopen with more information if needed.
