### ISSUE TITLE
new term:Neuroglycopenia?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1956]

**Comment by pnrobinson** [comment]
This term refers to a shortage of glucose in the brain. However,this is an inference and it is not a phenotype that is directly observed (ie., we are not taking out a piece of the brain and measuring the sugar level, instead, we are looking at some clinical picture and making the inference that the brain is not getting enough glucose.
The HPO tries to have terms for items that we can observe (more or less) directly, and not for inferences about pathphysiology. Therefore, Neuroglycopenia is not in scope of the HPO.
