### ISSUE TITLE
new term:Increased excretion of 2-ketoglutarate?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1978]

**Comment by pnrobinson** [comment]
This compound has several synonyms
https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:16810
@drseb  please mireot this term and add logical def!
The term should be Elevated urinary 2-oxoglutarate

**Comment by pnrobinson** [comment]
I see we already have this term
Increased urine alpha-ketoglutarate concentration
I am adding Elevated urinary 2-oxoglutarate as a synonym

**Comment by pnrobinson** [comment]
@drseb disregard above request, we already have a logical definition!
