### ISSUE TITLE
new term:Elevated muscular enzymes   ?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1987]

**Comment by pnrobinson** [comment]
@LOURGHI  There are many enzymes in muscle and it is preferable to be precise which are being measured. I do not think that this is a good HPO term. To annotate a disease that is described like this in the literature, consider the HPO term Elevated serum creatine phosphokinase

**Comment by LOURGHI** [comment]
What about Increased liver enzymes???

**Comment by pnrobinson** [comment]
Try elevated hepatic transaminases maybe?
