### ISSUE TITLE
new term:grey platelet syndrome?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1990]

**Comment by pnrobinson** [comment]
This is related to reduced alpha granules, which is already an HPO term. I will ask Kathleen Freson about this.

**Comment by pnrobinson** [comment]
Kathleen's answer:
We have coded our grey platelet patients with the term absence or abnormal number of alpha granules. 

I understand why the term grey platelets was asked for as this is typically what pathologists describe in the giemsa stains of platelets from patients but is reflect the absence of alpha granules. Is it an option to add this to the definition of the term  ‘abnormal alpha granules’ ? 
Textual definition
A deviation from the normal count of alpha granules per thrombocyte. This typically results in the grey appearance of platelets  in giemsa stained blood smears. 

=> I will add 'Grey platelets' as a synonym.
