### ISSUE TITLE
new term:Increased circulating Androstenedione level?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2002]

**Comment by pnrobinson** [comment]
@LOURGHI  There are several types of Androstenedione, see
https://en.wikipedia.org/wiki/Androstenedione
Can you provide more information?

**Comment by LOURGHI** [comment]
Sorry, I have no context.

**Comment by pnrobinson** [comment]
Then please use HP_0025380 to annotate (Increased serum androstenedione)
