### ISSUE TITLE
new term:Abnormal serum DHEA?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2007]

**Comment by pnrobinson** [comment]
Label: Abnormal serum dehydroepiandrosterone level
Syn: Abnormal serum DHEA 
Syn: Abnormal serum androstenolone level
Def: A deviation from the normal concentration of dehydroepiandrosterone in the circulation.
Cmment: Dehydroepiandrosterone (DHEA), which is produced in the adrenal glands and the gonads, represents the most abundant circulating steroid hormone. It is a metabolic intermediate in the biosynthesis of the androgen and estrogen sex steroids.

**Comment by pnrobinson** [comment]
Parent term: Abnormal circulating androgen level

**Comment by LCCarmody** [comment]
Reminder to myself: PMID: 27979632

**Comment by LCCarmody** [comment]
Trying to do a logical definition but need to MIREOT DHEA. http://purl.obolibrary.org/obo/CHEBI_28689
@drseb Could you please help?

**Comment by drseb** [comment]
http://purl.obolibrary.org/obo/CHEBI_28689 should be available in Protege now.
