### ISSUE TITLE
new term:Increased cholesterol esters ?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2014]

**Comment by pnrobinson** [comment]
Definition: An elevated concentration of circulating cholesterol esters, which are fatty acid esters of cholesterol and make up about two-thirds of total plasma cholesterol. 
Comment: The accumulation of cholesterol esters in the arterial intima is a characteristic feature of atherosclerosis. 
Parent:Abnormality of cholesterol metabolism

**Comment by LCCarmody** [comment]
It appears that 'cholesteryl esters' is a synonym and is more commonly used, but most NCBI entries use 'cholesterol esters'.  https://meshb.nlm.nih.gov/record/ui?name=Cholesterol%20Esters

And most citations (ex. https://www.ncbi.nlm.nih.gov/pubmed/26884207) use 'cholesteryl esters', but use the MeSH term 'cholesterol esters'.

Which should be used as the entry? And which should be the synonym?

**Comment by cmungall** [comment]
In GO and HP we try and leverage CHEBI as much as possible. This mostly applies to the classification, but also to synonyms. Unfortunately CHEBI synonyms take a bit of pre-processing since we don't want to make HPO synonyms with SMILES strings! You can see the ECTO repo for how we do this.

This is what CHEBI has:

```
[Term]
id: CHEBI:17002
name: cholesterol ester
namespace: chebi_ontology
alt_id: CHEBI:13983
alt_id: CHEBI:23205
alt_id: CHEBI:3660
def: "Cholesterol esterified at the 3-hydroxy group." []
synonym: "C28H45O2R" RELATED FORMULA [ChEBI]
synonym: "Cholesterol ester" EXACT [KEGG_COMPOUND]
synonym: "[H][C@@]1(CC[C@@]2([H])[C@]3([H])CC=C4C[C@H](CC[C@]4(C)[C@@]3([H])CC[C@]12C)OC([*])=O)[C@H](C)CCCC(C)C" RELATED SMILES [ChEBI]
synonym: "a cholesterol ester" RELATED [UniProt]
synonym: "cholesterol esters" RELATED [ChEBI]
xref: KEGG_COMPOUND:C02530
is_a: CHEBI:35915  ! sterol ester
relationship: has_functional_parent CHEBI:16113 ! cholesterol
relationship: has_role CHEBI:75771 ! mouse metabolite
relationship: has_role CHEBI:77746 ! human metabolite
```

I filed a ticket for them to ask for a synonym or possibly primary label change (see link above this ticket)

**Comment by LCCarmody** [comment]
Note we need to 'MIREOT' cholesterol esters from ChEBI for the logical definition.  Could we go over this at the next Ontology meeting? @pnrobinson @drseb

**Comment by pnrobinson** [comment]
Think I need a C(O)C before working on synonyms.

**Comment by nicolevasilevsky** [comment]
What do you mean by C(O)C?

**Comment by pnrobinson** [comment]
Hint: I said it with a SMILE

**Comment by LCCarmody** [comment]
Peter, we added the logical definition.

**Comment by pnrobinson** [comment]
Added term with synonym Elevated cholesteryl ester level.
