### ISSUE TITLE
new term:Abnormal leucocyte acid lipase level?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2015]

**Comment by pnrobinson** [comment]
@LOURGHI  Can you specify? I am familiar with lysosomal acid lipase (e.g., https://www.ncbi.nlm.nih.gov/books/NBK305870/ and http://www.mayomedicallaboratories.com/test-catalog/Clinical+and+Interpretive/62954), but not leucocyte acid lipase.

**Comment by LOURGHI** [comment]
Sorry,I have no context.

**Comment by pnrobinson** [comment]
I think that this is Wolman disease
https://omim.org/entry/278000
This is the gene
https://www.ncbi.nlm.nih.gov/gene/3988
I have seen some publications refer to it as leukocyte lipase, but I think that this term is incorrect and that we really mean  lysosomal acid lipase, and I will make a corresponding term, ok?

**Comment by LOURGHI** [comment]
it's ok for me.

**Comment by pnrobinson** [comment]
I am adding a term, Reduced lysosomal acid lipase activity. HP_0031205
As far as I can see, one measures the activity of LAL and not the amount. Also, I have not seen any disease associated with increased activity, and thus I do not think we need an "Abnormal" and "Increased" term right now.
