### ISSUE TITLE
new term:paraproteinemia?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2020]

**Comment by pnrobinson** [comment]
Todo: Waldenstrom macroglobulinemia is related to this, but I think we need to re-examine the hierarchy of terms for monoclonal gammopathy/paraproteinemia.

**Comment by pnrobinson** [comment]
Def: An abnormal immunoglobulin or part of an Ig (light chain) in the circulation. Paraproteins are typically produced by a clonal population of B-cell derived plasma cells.
Comment: The frequency of paraprotein-associated heavy chains is IgG>IgA>IgM> IgD, and light chains may be kappa or lambda. Paraproteins are associated with both malignant and nonmalignant conditions and may lead to complications including neuropathy and nephropathy.

**Comment by pnrobinson** [comment]
DD: MGUS
Solitary Plasmacytoma
Multiple Myeloma
Waldenstrom  Macroglobulinemia
Amyloidosis
POEMS Syndrome
Lymphoplasmacytic  lymphoma

**Comment by pnrobinson** [comment]
Maybe we want subclasses such as  IgG, IgA, IgD Paraprotein
Bence-Jones  protein = free antibody light  chains.

**Comment by pnrobinson** [comment]
monoclonal gammopathy is a synonym of paraproteinemia

**Comment by pnrobinson** [comment]
Hierarchy
Paraproteinemia
--Light-chain paraproteinemia (the Bence Jones protein)
--Heavy-chain paraproteinemia (synonym heavy chain disease)
--Whole-immunoglobulin paraproteinemia
   M-proteins (monoclonal) are present in the blood
   related to cryoglobulinemia

**Comment by pnrobinson** [comment]
macroglobulinemia -- whole immunoglobulins can bind with one another

**Comment by pnrobinson** [comment]
Note I am revising the term Waldenstrom Macroglobulinemia to be Monoclonal IgM paraproteinemia (which is the feature;Waldenstrom Macroglobulinemia is a disease).

**Comment by callahantiff** [comment]
Would you consider adding an additional term for and/or incorporating an existing term to include biclonal gammopathies [PMC5780647](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5780647/)?
