### ISSUE TITLE
new term:Abnormality of pre-albumin?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2023]

**Comment by pnrobinson** [comment]
@LOURGHI 
-- Could you specifiy what abnormality? Is it a reduced or increased level or something else?

**Comment by LOURGHI** [comment]
Sorry I have no context.

**Comment by pnrobinson** [comment]
I think that Reduced prealbumin level is correct
http://clinchem.aaccjnls.org/content/52/12/2177.long
