### ISSUE TITLE
new term:Chromosomal reciprocal translocations?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2030]

**Comment by pnrobinson** [comment]
This is a genotype and not a phenotype. Thus, it is not a valid HPO term.

**Comment by LOURGHI** [comment]
Is it possible to create an entry for  chromosomal abnormality ??which could include all these new terms:
Abnormal Y chromosome.
Chromosomal translocation.
chromosomal deletion.

**Comment by LOURGHI** [comment]
Sorry,those terms that were important to me.I just read the comments .it's ok
