### ISSUE TITLE
new term:Abnormal insulinemia after glucagon test?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2036]

**Comment by pnrobinson** [comment]
I do not think this is a valid term -- if one gives glucagon, in general the blood sugar should tend to rise and insulin may also rise as a result. But the glucagon test is not normally used to measure insulin response. I am closing this issue, please provide more details if I am misunderstanding something.

**Comment by pnrobinson** [comment]
I am adding a term "Excessive insulin response to glucagon test"
