### ISSUE TITLE
new term:Fasting elevated C-Peptide?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2038]

**Comment by pnrobinson** [comment]
I think that in general C-peptide is collected after overnight fasting. See for instance
http://emedicine.medscape.com/article/2087824-overview#a3
Therefore, I will add this as a comment to the current C-peptide term, but I think that the current C-peptide term "HP_0030796, Increased C-peptide level" should be used to annotate this feature.
