### ISSUE TITLE
new term:Decreased plasma INHIBIN B?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2039]

**Comment by pnrobinson** [comment]
This is HP_0031100

**Comment by LOURGHI** [comment]
I don't find this term HP_0031100 on HPO.

**Comment by pnrobinson** [comment]
@LOURGHI  where are you looking?

**Comment by LOURGHI** [comment]
On line version or is it a term being created???

**Comment by pnrobinson** [comment]
The term should be available in the new version online as HP_0031100. We will try to update the hp.obo file very shortly
