### ISSUE TITLE
new term:Absent response of GH after glucagon-propranolol stimulation test ?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2054]
Add synonym:negative glucagon-propranolol testing

**Comment by pnrobinson** [comment]
There were a number of variations of the glucagon stimulation test. I do not think that propranol is used in modern practice, and I think it is sufficient to have a term called Impaired response to glucagon stimulation test. 
See e.g., http://www.eje-online.org/content/162/3/477.full.pdf
