### ISSUE TITLE
new term:Increased plasma alpha subunit of anterior pituitary hormones?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2055]

**Comment by pnrobinson** [comment]
The four human glycoprotein hormones chorionic gonadotropin (CG), luteinizing hormone (LH), follicle stimulating hormone (FSH), and thyroid stimulating hormone (TSH) are dimers consisting of alpha and beta subunits that are associated noncovalently. The alpha subunits of these hormones are identical, however, their beta chains are unique and confer biological specificity. (https://www.ncbi.nlm.nih.gov/gene/1081)

**Comment by pnrobinson** [comment]
The anterior pituitary gland secretes six hormones: growth hormone (GH), prolactin (PRL), follicle-stimulating hormone (FSH), luteinizing hormone (LH), adrenocorticotropic hormone (ACTH), and thyroid-stimulating hormone (TSH).

**Comment by pnrobinson** [comment]
Adding term with definition:An increased concentration of circulating alpha polypeptide of glycoprotein hormones (Entrez Gene 1081). This alpha subunit is common to luteinizing hormone (LH) , follicle stimulating hormone (FSH) , thyroid stimulating hormone (TSH) and human chorionic gonadotropin (hCG), which are glycoprotein hormones composed of an identical alpha subunit together with a beta subunit that confers biological specificity. The alpha subunit is used as a marker for tumors that produce these hormones. (HP_0031208)
