### ISSUE TITLE
new term:Abnormal HOMA test?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2057]

**Comment by pnrobinson** [comment]
Are you refering to this
https://en.wikipedia.org/wiki/Homeostatic_model_assessment
?

**Comment by drseb** [comment]
ping @LOURGHI

**Comment by LOURGHI** [comment]
Sorry,no contex for this term .
I invite my colleague bruno to intervene if this term tells him something.

**Comment by pnrobinson** [comment]
I think this must be what is meant. I do not think that the HOMA method is currently in wide use. I think that we should stick with the current HPO terms about insulin metabolism that describe the abnormalities that are measured by this test -- there is no need for a separate term.
See https://www.ncbi.nlm.nih.gov/pubmed/3899825
