### ISSUE TITLE
new term:Absence of GnRH pulsatility?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2063]

**Comment by pnrobinson** [comment]
@LCCarmody 
Label: Lack of gonadotropin-releasing hormone pulsatility
Definition: Secretion of gonadotropin-releasing hormone that does not occur in a pulsatile fashion.

Comment: The decapeptide gonadotropin-releasing hormone (GnRH) is the master hormone regulating reproduction. GnRH is released from some 1000 neurons within the hypothalamus in a pulsatile manner. Hypothalamic GnRH gene expression occurs intermittently (in a pulsatile fashion). The primary target of hypothalamic GnRH is the anterior pituitary gonadotrope, which responds to stimulation by increasing the synthesis and secretion of the gonadotropins luteinzing hormone (LH) and follicle stimulating hormone (FSH), which in turn regulate gonadal development and function.
Syn: Absence of GnRH pulsatility

We need to add a term called 
Abnormality of gonadotropin-releasing hormone level
and place this new term and also HP_0003164 underneath it.

**Comment by LCCarmody** [comment]
We are trying to add logical definition and had a question about the ChEBI definition of GnRH.  All I can find is GnRH II https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:80298.  Is this the same thing?  And then I would need help adding the term.  Thanks.

**Comment by nicolevasilevsky** [comment]
I think maybe this is the ChEBI term we want to use:
https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:5520

**Comment by pnrobinson** [comment]
I think that the ChEBI term is correct, but where do we get absence of pulsatility from? Can we define this term using our current resources? Normally, GnRH is secreted in an up and down fashion, and this term means that this pulsatility is not present.

**Comment by nicolevasilevsky** [comment]
Agreed- the def of Lack of gonadotropin-releasing hormone pulsatility is too complex to give it a logical definition, but Leigh and I were thinking we could add a logical def to the parent HP_0500012
'Abnormality of gonadotropin-releasing hormone level' (and probably the sibling too: HP_0003164 Hypothalamic gonadotropin-releasing hormone deficiency)

@drseb could you please MIREOT this term (thank you!):
https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:5520

**Comment by drseb** [comment]
should be in imports

**Comment by nicolevasilevsky** [comment]
thanks @drseb!
