### ISSUE TITLE
new term:Abnormal plasma INSL3 from Leydig cells?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2064]

**Comment by pnrobinson** [comment]
@LOURGHI  Note that although INSL3 is produced by Leydig cells, this is not what we measure. I will assume that you mean Reduced plasma INSL3 level
See https://www.ncbi.nlm.nih.gov/pubmed/24640568

**Comment by LOURGHI** [comment]
sorry I have no context.
