### ISSUE TITLE
new term:Decreased plasma acid-labile subunit?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2067]

**Comment by pnrobinson** [comment]
@LOURGHI  Are you referring to the acid-labile subunit (ALS) of the 150 kDa IGF-binding protein complex
??

**Comment by pnrobinson** [comment]
I am going to assume you mean this
https://www.ncbi.nlm.nih.gov/gene/3483
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2820127/

**Comment by pnrobinson** [comment]
I am adding this term as Reduced insulin like growth factor binding protein acid labile subunit level

**Comment by LOURGHI** [comment]
Sorry,I have no context.
