### ISSUE TITLE
new term:Vimentin staining positive?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2077]

**Comment by pnrobinson** [comment]
I know that vimentin staining is used in the diagnostics of some tumors. But could you be more precise -- what is being stained, and what is the finding?

**Comment by pnrobinson** [comment]
@LOURGHI  I am closing this request for now, as it appears to refer to a tumor that should be coded separately. Please reopen with more details if necessary.
