### ISSUE TITLE
new term:femoral torsion ?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2079]

**Comment by pnrobinson** [comment]
Femoral anteversion refers to the orientation of the femoral neck in relation to the femoral condyles at the level of the knee. In most cases, the femoral neck is oriented anteriorly as compared to the femoral condyles. In the case of posterior orientation, the term femoral retroversion is also applied.

**Comment by pnrobinson** [comment]
I think that the abnormal phenotype needs to be called Increased femoral anteversion. Will add as HP_0031068
