### ISSUE TITLE
new term:Abnormal fÅtal genitalia?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2084]

**Comment by pnrobinson** [comment]
I do not understand what you mean my "fÅtal "?

**Comment by drseb** [comment]
I guess it should read _fœtal_

**Comment by pnrobinson** [comment]
Of course. In this case, we should add an onset term to the specific abnormality, there is no case for a special term for this, because we would then need to add "fetal" to most of the other terms as well.

**Comment by LOURGHI** [comment]
I think it's one of the bad surprises of massive injections :)
the term is abnormal foetal genitalia.Ithink we can annotate with Abnormal genital system morphology +fetal onset.

**Comment by drseb** [comment]
ok great!
