### ISSUE TITLE
new term:Lean body mass?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2094]

**Comment by pnrobinson** [comment]
According to wikipedia: 

Lean body mass is a component of body composition, calculated by subtracting body fat weight from total body weight: total body weight is lean plus fat. 

This is a trait, and not an abnormality, thus is is not a valid HPO term. I am not familiar with anything like this, but if you want to annotate something like 'Reduced lean body mass' please open a new issue and provide a definition and some context.
