### ISSUE TITLE
new term:Sapho syndrome?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2096]
A syndrome encountered in Subcorneal pustular dermatosis

**Comment by pnrobinson** [comment]
Sapho syndrome is a disease entity and not a phenotype.
See https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4340847/
Please open new items if you need terms to describe the phenotypic abnormalities of Sapho syndrome.
