### ISSUE TITLE
new term:Pyoderma gangrenosum ?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2097]
A syndrome encountered in Subcorneal pustular dermatosis and PAPA syndrome,

**Comment by pnrobinson** [comment]
There may be some question as to whether Pyoderma gangrenosum is best conceptualized as a disease or as a phenotypic feature. BEcuase of the following, I think that is is appropriate to treat it as a phenotypeand add an HPO Term:

About half of the cases are associated with underlying systemic conditions, such as inflammatory bowel disease, arthritis, and haematological malignancies.

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1513476/
