### ISSUE TITLE
new term:Ichthyosis follicularis?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2098]
observed in IFAP syndrome

**Comment by pnrobinson** [comment]
@LOURGHI  Ichthyosis follicularis is the name of a disease. AFAIK there is not a specific phenotypic variant of the finding ichthyosis (dry, scaly skin). I think the features should be covered by existing HPO terms. Note that the word ichtyosis can be  used to describe the phenotypic feature or the disease.
