### ISSUE TITLE
new term:Lhermitte-Duclos disease (PTEN hamartoma tumor syndrome)?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2100]
Add synonym:  Dysplastic gangliocytoma of the cerebellum;observed in PTEN hamartoma tumor syndrome

**Comment by pnrobinson** [comment]
I think that 'Dysplastic gangliocytoma of the cerebellum' is a valid term, but Lhermitte-Duclos disease is obviously a disease and not a phenotypic feature.

**Comment by nicolevasilevsky** [comment]
@pnrobinson Do you mind if I work with @LCCarmody to add 'Dysplastic gangliocytoma of the cerebellum'?

**Comment by pnrobinson** [comment]
sounds great!

**Comment by LCCarmody** [comment]
@pnrobinson Should ' Lhermitte-Duclos disease'be listed as a synonym?  While I realize this is a disease, I have seen a few resources that list it as an exact synonym.  http://www.springer.com/us/book/9783642028731

**Comment by pnrobinson** [comment]
I would think that it is a good RELATED SYNONYM
