### ISSUE TITLE
new term:McCune-Albright syndrome?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2101]
observed in ACTH-independent macronodular adrenal hyperplasia

**Comment by pnrobinson** [comment]
This is incorrect. McCune Albright syndrome is a disease that rarely causes ACTH-independent macronodular adrenal hyperplasia (see Figure 5 of https://ojrd.biomedcentral.com/articles/10.1186/1750-1172-3-12).
