### ISSUE TITLE
new term:Calcinosis cutis ?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2102]
observed in Mandibuloacral dysplasia with type B lipodystrophy

**Comment by pnrobinson** [comment]
ToDo: Check whether this is synonymous with the current HPO term Subcutaneous calcification (HP:0007618)

**Comment by pnrobinson** [comment]
According to this article, the disease is characterized by "calcified skin nodules" 
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2965306/
