### ISSUE TITLE
new term:Aplasia cutis congenita  temporal ?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2104]
observed in Focal facial dermal dysplasia type I

**Comment by pnrobinson** [comment]
@LOURGHI I think this is a synonym for Aplasia cutis congenita over parietal area (HP_0004476) -- ?

**Comment by LOURGHI** [comment]
I think so,sorry,I have no context.

**Comment by pnrobinson** [comment]
Then I would say it is most likely a synonym. The phrase "Aplasia cutis congenita temporal" is not idiomatic English, so am not adding it to the term.
