### ISSUE TITLE
new term:carpal tunnel syndrome?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2106]

**Comment by nicolevasilevsky** [comment]
I don't think this is considered a phenotype. We do have HP_0012185 Constrictive median neuropathy, which is the major clinical feature of carpal tunnel syndrome.

**Comment by pnrobinson** [comment]
We might want to add Carpal tunnel syndrome as a related syn?

**Comment by pnrobinson** [comment]
@LCCarmody @nicolevasilevsky  Could we add this as a related syn, as suggested by Nicole
