### ISSUE TITLE
new term:Nelson's syndrome?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2108]
observed in   Hand and foot deformity-flat facies syndrome

**Comment by pnrobinson** [comment]
This is not an indiviudal phenotype -- it is a syndrome with a combination of phenotypes 
Nelson syndrome refers to a spectrum of symptoms and signs arising from an adrenocorticotropin (ACTH)–secreting pituitary macroadenoma after a therapeutic bilateral adrenalectomy. 
This is not in scope for the HPO.
