### ISSUE TITLE
new term:Cold exposition ?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2109]
Term that could be classified in a group called triggering factors in clinical modifiers?

**Comment by pnrobinson** [comment]
This is HP_0025206, triggered by cold.

**Comment by drseb** [comment]
Why not add as synonym?

**Comment by pnrobinson** [comment]
The phrase "cold exposure" (not exposition) doesnt mean the same as "triggered by" cold and would not be unambiguous in the setting of an ontology.
