### ISSUE TITLE
new term:Traumatism?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2110]
Term that could be classified in a group called triggering factors in clinical modifiers?

**Comment by pnrobinson** [comment]
Traumatism is defined as any abnormal condition produced by a trauma, thus it is a disease rather than a phenotypic feature. @LOURGHI  Please reopen this term with more details and a reference or two if needed.

**Comment by LOURGHI** [comment]
It's noted :Triggering factor : traumatism, in Acquired epidermolysis bullosa.this is all I have as information.

**Comment by pnrobinson** [comment]
I see. I think that a modifer term "Triggered by trauma" would be good?

**Comment by LOURGHI** [comment]
I think so.

**Comment by pnrobinson** [comment]
Thought it best to use the label 'Triggered by physical trauma' to avoid ambiguity.
