### ISSUE TITLE
new term:Warm weather?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2111]
Term that could be classified in a group called triggering factors in clinical modifiers?

**Comment by pnrobinson** [comment]
This is triggered by heat HP_0025214

**Comment by drseb** [comment]
Why not add as synonym (e.g. Triggered by warm weather)?

**Comment by pnrobinson** [comment]
I think probably hot weather is meant, and it is not precise -- sitting under an umbrella in warm/hot weather might not be a trigger, but jogging in hot weather might. I think we should wait until we see references to how terms like this are typically used.

**Comment by LOURGHI** [comment]
It's noted:Palmoplantar blistering exacerbated by warm weather in Localized epidermolysis bullosa simplex.
