### ISSUE TITLE
new term:Potassium-aggravated ?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2113]
Term that could be classified in a group called triggering factors in clinical modifiers?

**Comment by pnrobinson** [comment]
@LOURGHI 
Are you thinking of this:
https://ghr.nlm.nih.gov/condition/potassium-aggravated-myotonia
If so, what about "triggered by potassium-rich food ingestion" as a term label?

**Comment by LOURGHI** [comment]
see potassium-aggravated myotonia,PMID:    19472919.
