### ISSUE TITLE
new term:Intake of estrogens?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2118]
Term that could be classified in a group called triggering factors in clinical modifiers?

**Comment by pnrobinson** [comment]
@LOURGHI  I know that estorgen intake can cause side effects but I was not aware that there are disease specific triggering factors. Can you please provide more details?

**Comment by LOURGHI** [comment]
Sorry I have no context.

**Comment by pnrobinson** [comment]
I do not think this is a good term without further details -- as I say, triggered by means that a phenotype of some disease is triggered by intake of estrogens. I do not think we are describing medication side effects.
