### ISSUE TITLE
new term:Temperatures between 37-40Â°C?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2119]

**Comment by pnrobinson** [comment]
It would be better to take the term 'Fever'. It is not a good idea to start making terms for various ranges of numerical traits, since there can be an infinite number of ranges.

**Comment by LOURGHI** [comment]
It is an old annotation on which it is marked :Autoimmune Hemolytic anemia as very frequent sign observed in Autoimmune hemolytic anemia, warm type(Trigger : active at temperatures between 37-40°C).
