### ISSUE TITLE
new term:Fights ?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2121]

**Comment by pnrobinson** [comment]
This is not a phenotypic feature. Perhaps you can use the current HPO term aggressive behavior. If there is some specific fights-related phenotype, please send some more context and details and a reference (reopen this issue).

**Comment by LOURGHI** [comment]
It's noted :Triggers :unexpected falls, fights, sexual activit, eating and yawning ,in Paroxysmal extreme pain disorder.
