### ISSUE TITLE
new term:Eating  ?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2123]
Term that could be classified in a group called triggering factors in clinical modifiers?

**Comment by pnrobinson** [comment]
There are terms for abnormalities triggered by eating certain substances, e.g., Triggered by carbohydrate ingestion.
Are there symptoms that are triggered by eating in general? Or is this a specific trigger?

**Comment by pnrobinson** [comment]
@LOURGHI 
I am going to close this term right now because I am not aware of any complication that is triggered by eating in general, and think that to create a term like this would be confusing without more context.

**Comment by LOURGHI** [comment]
It's noted, Triggers :unexpected falls, fights, sexual activit, eating and yawning, observed in Paroxysmal extreme pain disorder.PMID:17145499.
