### ISSUE TITLE
new term:Yawning?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2124]
Term that could be classified in a group called triggering factors in clinical modifiers?

**Comment by pnrobinson** [comment]
@LOURGHI do you mean that there is a phenotypic feature that is triggered by yawning? COuld you please provide some additional information and a reference?

**Comment by pnrobinson** [comment]
I have not been able to find any references to yawing as a trigger for a disease. Please reopen this term with more information as necessary.

**Comment by LOURGHI** [comment]
mandibular crisis in Paroxysmal extreme pain disorder  is often triggered by eating and yawning.
(Among the diagnostic criteria of the disease) PMID:17145499.
