### ISSUE TITLE
new term:Antenatal exposure?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2125]
Term that could be classified in a group called triggering factors in clinical modifiers?

**Comment by pnrobinson** [comment]
A triggering factor has a direct and clear relationship to a phenotype. Antenatal exposures may or may not cause disease, and in any one child (with a few exceptions), it is impossible to say whether some maternal exposure led to a certain disease. We are currently exploring ways of captuing exposures in medical records, but this sort of term should not in general be directly coded with HPO.
