### ISSUE TITLE
new term: Asthenia ?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2134]

**Comment by nicolevasilevsky** [comment]
looks like we have myastenia but not asthenia. @pnrobinson is it okay if @LCCarmody and I add this?

**Comment by pnrobinson** [comment]
I would say that Asthenia is a constitutional symptom meaning general weakness. The wikipedia article on this is good https://en.wikipedia.org/wiki/Weakness
