### ISSUE TITLE
new term:Epigastric pain?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2136]

**Comment by LCCarmody** [comment]
@pnrobinson Should this be a subclass of abdominal pain?

**Comment by pnrobinson** [comment]
The general rule is that if we make a subclass assertion,, then it *always*  has to be true. Epigastric pain usually reflects some problem in the abdomen, but it can also be a symptom of a heart attack, and in the latter case, "epigastric pain" is_a "abdominal pain" would be false. I think we should make it a subclass of pain.

**Comment by nicolevasilevsky** [comment]
Sounds good. @pnrobinson Do you mind if I add this term next time I meet with Leigh, to show her how to edit the ontology?

**Comment by pnrobinson** [comment]
please go ahead!
