### ISSUE TITLE
new term:Abdominal pelvic mass ?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2137]

**Comment by pnrobinson** [comment]
@LOURGHI usually one speaks of either abdominal mass or pelvic mass.

e.g., A pelvic mass is a general term for any growth or tumor on the ovary or in the pelvis. 

Could you please clarify what is meant here?

**Comment by LOURGHI** [comment]
Sorry I have no context.

**Comment by pnrobinson** [comment]
I do not think the term makes sense, but what about adding "Pelvic mass" and "Abdominal mass"?

**Comment by LOURGHI** [comment]
These two terms are widely used in common practice and frequently appear in articles, I think they would be useful.

**Comment by pnrobinson** [comment]
Adding Abdominal mass as HP_0025556, and Pelvic mass as HP_0025557

**Comment by pnrobinson** [comment]
Adding them now as HP_0031500 and HP_0031501
