### ISSUE TITLE
new term:Rectal pain ?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2139]

**Comment by LCCarmody** [comment]
@pnrobinson It does not appear to be specifically a pain of the rectum.  Should it be added?

**Comment by pnrobinson** [comment]
I think that it is hard to distinguish specifically rectal pain from anal pain, which is the more commonly used term afaik. 
http://www.nhs.uk/conditions/anal-pain/Pages/Introduction.aspx
https://en.wikipedia.org/wiki/Rectal_pain
@LCCarmody  Let's ad a term Anal pain as a child of Pain with rectal pain as an exact synonym. The definition can be analogous to the other pain terms.
