### ISSUE TITLE
new term:Cushingoid morphotype?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2141]

**Comment by nicolevasilevsky** [comment]
Looks like there is a cushingoid phenotype:
Clinical Diagnosis [ edit | Change the code ]
The diagnosis of Cushing's syndrome is relatively difficult to install, so it may be delayed for several years 1 . Indeed, the symptoms suggestive of this disorder are not specific.

It can be manifested by 2 , 3 , 4 , a silhouette called "cushingoid"

The face is called "lunar", swollen and red.
Unsightly lipid formations become encysted in the neck, neck - referred to as buffalo hump term (in English  :  buffalo neck ). One will speak of obesity or lipodystrophy facioconconcular. Contrasting with this localized obesity, there is a muscular meltdown in the legs and arms.

**Comment by LCCarmody** [comment]
@pnrobinson This seems to be a collection of phenotypes.  Is this something we want to add?

**Comment by pnrobinson** [comment]
This is a "bundled" phenotype, as @nicolevasilevsky and @LCCarmody  point out. It would be better to annotate the patient to the specific phenotypes. @LOURGHI if you would care to supply more detail we can advise on how to best annotate the patient or publication in question. I do not think that "Cushingoid morphotype" is a good term.

**Comment by LOURGHI** [comment]
My colleague had annotated cushing disease with this sign and I can not find a PMID,but I think that the term cushingoid appearance is much more used than Cushingoid morphotype.

**Comment by pnrobinson** [comment]
HPO terms do not in general include bundled subjective assessments like that. You could essentially take about 2000 diseases that have some combination of abnormalities and for each disease X create a term called X-oid appearance -- but this would not be helpful for deep phenotyping or computational analysis. Instead, please annotate the individual abnormalities that make up a "Cushingoid appearance" -- this is available at wikipedia or many articles.
