### ISSUE TITLE
new term:Android morphotype?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2142]

**Comment by LCCarmody** [comment]
@LOURGHI @pnrobinson 
Is this a synonym for HP_0001956 (Truncal Obesity)?

**Comment by pnrobinson** [comment]
I do not know exactly what this means and am only finding references to Android morphotype on non-medical Webpages.  @LOURGHI could you please provide more detail/context?

**Comment by LOURGHI** [comment]
I don't find a bibliographic reference for this term for our diseases.
But this term has been observed in Primary amenorrhea in four adolescents revealed 5α-reductase deficiency confirmed by molecular analysis,PMID: 20850730.

**Comment by nicolevasilevsky** [comment]
I think this term is referring to this: https://en.wikipedia.org/wiki/Android_fat_distribution. We could add Android fat distribution as a subclass of HP_0007552 Abnormal subcutaneous fat tissue distribution?

and android morphotype could be a synonym.

**Comment by nicolevasilevsky** [comment]
If we add android morphotype, seems like we should also add gynoid morphotype (a layperson term for that would be pear shaped body type)

**Comment by pnrobinson** [comment]
Still I am sceptical about this term since slightly under 50% of the population has an android fat distribution, some of us more than others. The abnormality is that these are girls with this distribution. And presumably it might be considered abnormal to have an extremely android fat distribution, whatever that is. So I do not think the term label is clear enough to be used in an ontology without the context of a medical article. It might be better to describe the anatomical location of increased/decreased fat distribution?

**Comment by nicolevasilevsky** [comment]
Looks like we already have terms that describe anatomical location of increased/decreased fat distribution, like HP_0008993 Increased intraabdominal fat. @LOURGHI could this term work?

**Comment by LOURGHI** [comment]
I think what has been described is a somewhat excessive android morphotype which is not necessarily abnormal but this is the case for oval face roud face terms for exemple.

**Comment by pnrobinson** [comment]
I think that the main problem is that android morphotype is a combination of many items and thus if people are trying to annotate a new disease they will use different HPO terms to refer to the same thing. One important rule for ontologies is that the child terms of some term need to be disjoint and completely divide up the same of the parent term. Also, different people are likely to have different opinions about what "android" really means. Please let's use object and specific terms for each of the items that might be considered "android". I really would not be sure myself what this term intends to mean, other than perhaps beer belly, but this could be HP_0012743, Abdominal obesity.
