### ISSUE TITLE
new term:Stocky  habitus ?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2143]

**Comment by LCCarmody** [comment]
@pnrobinson Do you think this would be a  subclass of abnormality of body weight? Or abnormality of skeletal morphology?

**Comment by pnrobinson** [comment]
Stocky means "compact, sturdy, and relatively thick in build". Another definition is " A stocky person, especially a man is fairly short and has a body that is wide across the the shoulders and chest."
There are thus two reasons this should not be an HPO term
(1) This is not an abnormal phenotype, it is simple one end of a normal spectrum
(2) It is bundled (i.e., "short stature" and "broad shoulders").
While stocky habitus may have some diagnostic utility without being abnormal, I think it is not good as an ontology term without context of a medical article etc. Instead, the disease in question should be annotated with the individual abnormalities (for instance "short stature" if that is the case).
I am closing this issue for now, re-open with more details about the disease context if you disagree please.
