### ISSUE TITLE
new term:Puffy  facies?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2149]
Add synonym:myxedematous facies

**Comment by LCCarmody** [comment]
Do you mean a synonym for full cheeks?  HP_0000293  @LOURGHI

**Comment by LOURGHI** [comment]
At first glance,Full cheeks is observed in Williams syndrome,puffy facies is observed in Cushing's Syndrome ,I don't think that it's the same sign.

**Comment by pnrobinson** [comment]
@LOURGHI I think that the current HPO terms puffy cheeks and full cheeks are probably the same thing as the versions with ".." facies. Do you agree? We could add the puffy face and full face as related synonyms maybe?

**Comment by pnrobinson** [comment]
@LCCarmody 
I agree with Halima
Let's add a term called
Moon facies
Def: A rounded, puffy face with fat deposits in the temporal fossa and cheeks,  a double chin.
Comment: Moon facies can occur in persons treated with high-dose corticosteroids or with Cushing disease.
Syn: Moon face
Parent: Abnormal facial shape
