### ISSUE TITLE
new term: helical dimples?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2153]

**Comment by LCCarmody** [comment]
Could you clarify what you are referring to? Is this in the ear?  Could you suggest a definition?  @LOURGHI

**Comment by pnrobinson** [comment]
@LOURGHI  I am not able to find any reference to helical dimples. Please provide more background!

**Comment by LOURGHI** [comment]
This sign was observed  in Simpson-Golabi-Behmel syndrome .This is all I have as context

**Comment by LCCarmody** [comment]
I found one reference to 'helical dimples' in this disease in this paper. https://www.ncbi.nlm.nih.gov/books/NBK1219/

However, it is not referring to cheek dimples (as I previously thought), but dimples in the ear: "Ears. Minor ear abnormalities are frequent, most often preauricular tags, fistulas, ear lobule creases, and helical dimples. Conductive hearing loss has been described [Golabi & Rosen 1984]."

Trying to look if something is already in HPO.

**Comment by LCCarmody** [comment]
Possibly Preauricular pit  (HP:0004467)?

**Comment by drseb** [comment]
I would also say these are synonyms

**Comment by pnrobinson** [comment]
Remember that "helix" is a part of the ear, and thus helical dimple does not necessarily mean a dimple with a helical shape. Preauricular pit means a pit in front of the ear (preauricular). Thus this is not a synonym.
Simpson-Golabi-Behmel can have pits of the posterior helix. I do not think that this feature should be called dimple. I see that the phrase is used here: https://www.ncbi.nlm.nih.gov/books/NBK1219/, and thus I am going to send an email to the author asking exactly what is meant by it. Let us hold off until I get an answer.

**Comment by pnrobinson** [comment]
I never received an answer. I think you should probably annotate to HP:0008523, Posterior helix pit. Without further information, I do not think that helicle dimple is a good synonym or term.
