### ISSUE TITLE
Add  definition for HP_0040310 "Sterile arthritis"

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#2157]

**Comment by pnrobinson** [comment]
I think this may be related to Pyogenic Arthritis, Pyoderma Gangrenosum (see https://www.omim.org/entry/604416). Septic arthritis refers to joint inflammation due to an infectious agent (usually bacteria). The term sterile means that efforts to culture bacteria or other agents from a pus-filled (pyogenic) form of arthritis failed. Can we get more context?

**Comment by drseb** [comment]
context requested: @LOURGHI

**Comment by LOURGHI** [comment]
It's marked that it's a very frequent sign observed in Pyogenic arthritis - pyoderma gangrenosum - acne .
PMID:21532836.

**Comment by pnrobinson** [comment]
@drseb  @LOURGHI  Why was this term added in the first place? It does not appear to be used to annotate any of our diseases. In the disease  Pyogenic arthritis - pyoderma gangrenosum there is an arthritis that appears to be bacterial (pus in the joint, i.e., pyogenic), but bacteria cannot be cultured, and to emphasize this fact, the articles on that disease write "sterile" arthritis. However, there are many other causes of arthritis that are not infectious. Almost all references I can find to the term are for this disease. There is also "reactive arthritis" which is similar but has other causes. 
Probably we can keep the term but then I would say it should be "sterile pyogenic arthritis". But if anybody has more context or background please help!

**Comment by drseb** [comment]
request by @LOURGHI : https://github.com/obophenotype/human-phenotype-ontology/issues/1822

**Comment by LOURGHI** [comment]
It was observed very frequently in Pyogenic arthritis - pyoderma gangrenosum - acne .
