### ISSUE TITLE
Definition of borderline intellectual disability

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#2158]
We currently have the def:

> Borderline intellectual disability is defined as an intelligence quotient (IQ) in the range of 70-79

However David Koolen noted during translating that term, that

> Borderline ID is defined by an IQ of 70-85 in the Netherlands; not 70-79.

@pnrobinson to advise please.

**Comment by pnrobinson** [comment]
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4967780/
In the DSM-IV-TR, it is defined by IQ in the 71–84 range. In DSM-5, IQ boundaries are no longer part of the classification, leaving the concept without a clear definition. 
I think the current definition resulted from the Cambridge workshop. I will research this.

**Comment by pnrobinson** [comment]
I have updated the definition accordingly and added this comment:
We choose to define the concept of borderline intellectual disability onthe basis of the commonly used range of 70-85 (IQ), but note that in DSM-5, IQ boundaries are no longer part of the classification.
