### ISSUE TITLE
Pulmonary veno-occlusive disease

### ISSUE THREAD

**Issue by andrewdevereau** [obophenotype/human-phenotype-ontology#2159]
Please can we add a term for Pulmonary veno-occlusive disease (PVOD) to complement Pulmonary arterial hypertension. Relevant references are Guidelines for the diagnosis and treatment
of pulmonary hypertension, European Heart Journal (2009) 30, 2493–2537 doi:10.1093/eurheartj/ehp297 and Eyries et al. Nat Genet. 2014 Jan;46(1):65-9

**Comment by pnrobinson** [comment]
Hi Andrew,
the HPO term "Pulmonary arterial hypertension" is meant to describe the finding of increased blood pressure in the pulmonary arterial system, and not the disease entity (which has numerous other symptoms). Pulmonary veno-occlusive disease is indeed also a disease entity with numerous phenotypic features, as summarized in the article you refer to: https://academic.oup.com/eurheartj/article-lookup/doi/10.1093/eurheartj/ehp297
I think it would be better to refer to the PVOD as a disease using disease ontology or some other resource and to record the phenotypes that led to this diagnosis using HPO. I see that some of the features do not currently have HPO terms (e.g., centrilobular ground-glass opacities), but we can add them as needed (I will open an issue for centrilobular ground-glass opacities  right now).
Let me know if this works!

**Comment by andrewdevereau** [comment]
Hi Peter,
OK - I suspected this would be the case. We can add any new phenotypes for this disease to the model

**Comment by pnrobinson** [comment]
OK, I will close this issue!
