### ISSUE TITLE
Abnormal response to polysaccharide vaccine

### ISSUE THREAD

**Issue by julievonz** [obophenotype/human-phenotype-ontology#2164]
I need to record the reactions to vaccines for patients with Primary Immune Disorders

**Comment by pnrobinson** [comment]
Please provide us with more details as to the individual phenotypic features you are referring to?

**Comment by julievonz** [comment]
I have found literature to suggest I use the term selective antibody deficiency with normal or high immunoglobulins (SADNI) instead for recording an abnormal response to the vaccine.
