### ISSUE TITLE
Abnormal response to protein vaccine

### ISSUE THREAD

**Issue by julievonz** [obophenotype/human-phenotype-ontology#2165]
I need to record the reactions to vaccines for patients with Primary Immune Disorders

**Comment by pnrobinson** [comment]
Hi Julie -- could you provide us with a list of the phenotypic features or a few references to the primary literature that describes these reactions?

**Comment by julievonz** [comment]
Hi Peter. I will close this issue as I have got literature to suggest that I use the term of selective antibody deficiency with normal or high immunoglobulins (SADNI) instead to record the abnormal response to vaccines.
