### ISSUE TITLE
OMIM_ALL_FREQUENCIES_diseases_to_genes_to_phenotypes.txt contains non-omim records

### ISSUE THREAD

**Issue by davmlaw** [obophenotype/human-phenotype-ontology#2166]
http://compbio.charite.de/jenkins/job/hpo.annotations.monthly/lastStableBuild/

Files:
OMIM_ALL_FREQUENCIES_diseases_to_genes_to_phenotypes.txt 
ALL_SOURCES_ALL_FREQUENCIES_diseases_to_genes_to_phenotypes.txt

are identical, ie the OMIM text file contains non-OMIM entries.

**Comment by drseb** [comment]
Sorry. This was a bug introduced in recent weeks. Should be fixed with the latest release I made today.
