### ISSUE TITLE
square-wave jerks(SWJ)

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2169]
_**Please consider a new term for square-wave jerks.
Observed in Friedreich ataxia.
PMID:8149209.
Superclass:Abnormality of eye movement?? **_

**Comment by pnrobinson** [comment]
Square wave jerks (SWJ) are saccadic eye movements which, when recorded with open eyes are considered to be a pathological sign, caused by fixation instability, and pointing to a central neurological lesion.
