### ISSUE TITLE
increasing difficulty in activities of daily living

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2170]
_**I would like to know if it would be possible to have signs of disability in HPO**_

**Comment by pnrobinson** [comment]
This is a good idea. I believe that the items under "dependence" here (http://www.alz.org/careplanning/downloads/katz-adl-lawton-iadl.pdf) would tranlsate into valid HPO terms.

**Comment by cmungall** [comment]
Is the idea to have "difficulties in performing X", for about 6 different kinds of activities? Or to bundle into one term? @mateolan is developing an ontology of physical activities, if this helps

**Comment by pnrobinson** [comment]
I think we need one term for each of the activities in the index. I would like to read up a little on this, since I believe there are some competing ways of assessing the ADLs, and our ontology should be as interoperable as possible.

**Comment by annieolry** [comment]
Hi, we are annotating RDs with a disability thesaurus derived from the ICF-CY of the WHO. It is adaptated to annotate diseases rather individuals. You can look at the thesaurus here: http://www.orpha.net/orphacom/cahiers/docs/GB/Orphanet_Functioning_Thesaurus_EN.pdf and see an example of annotated RDs here (our prefered one:)):http://www.orpha.net/consor/cgi-bin/Disease_Disability.php?lng=EN&data_id=20628&Disease_Disease_Disability_diseaseGroup=Marfan-syndrome-type-1&Disease_Disease_Disability_diseaseType=Pat&Disease(s)/group%20of%20diseases=Marfan-syndrome-type-1&title=Marfan-syndrome-type-1&search=Disease_Disability_Simple.
I will be happy to discuss on that deeply if needed.

**Comment by pnrobinson** [comment]
@annieolry  This is an excellent list, but probably it is better to have these annotations on the Orphanet website be made using this list? Or do you think we should try to capture this in HPO as a separate subhierarchy? For now I am making a short list using the Katz scale.
