### ISSUE TITLE
pill-rolling tremor

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2171]
_**Please consider a new term for pill-rolling tremor.
Observed in Atypical juvenile parkinsonism.
PMID:22563501.
Superclass:Resting tremor??**_

**Comment by pnrobinson** [comment]
Here is a description of resting tremor and pill-rolling tremor from
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3367535/
todo: add term pill-rolling tremor and check the definition of rest tremor. Add synonym rest tremor to resting tremor.

Rest tremor (sometimes also called parkinsonian tremor) is a rhythmic oscillatory involuntary movement that comes about when the affected body part is relaxed and supported by a surface, thus removing the action of gravitational forces (Deuschl et al. 1998; Bain 2007; Edwards et al. 2008b). It vanishes with active movement, and typically can reappear after a few seconds when the arms are held outstretched (reemergent tremor). In PD, rest tremor frequency is usually in the low to mid-range (3–6 Hz), whereas the amplitude is quite variable, from less than 1 cm to >10 cm wide (see Movies 1, 3, 5, and 6). The most distinguishing tremor in this disorder is the so-called “pill-rolling” type, a visual portrayal resulting from the simultaneous rubbing movements of thumb and index fingers against each other (see Movie 1). Other forms of tremor movements can be seen, such as finger flexion-extension or abduction-adduction. Tremor can also be present in the lower limbs, jaw (see Movie 5), and tongue. Head tremor is not typical of PD; in fact, it should prompt careful diagnostic reconsideration. An additional form of tremor, postural (e.g., occurs immediately on stretching out the arms), faster (6–8 Hz), can be occasionally seen in PD, but this is noncontributory to the diagnosis. In clinical practice, tremor is best observed while the patient is focused on a particular mental task (e.g., countdown from 100 with eyes closed), which facilitates limb muscle relaxation.
