### ISSUE TITLE
slowness of movements

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2172]
_**Please consider a new term for slowness of movement.
Observed in  Atypical juvenile parkinsonism.
PMID:23804577.
Superclass:Diminished movement??**_

**Comment by pnrobinson** [comment]
I think you are referring simply to Bradykinesia, which is Greek for slow-motion.
I think that we can add slownewss of movements as a lay person synonym. 
This is a nice article about the clinical features of Parkinson
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3367535/
see the following text from that article:

Bradykinesia refers to slowness of movements with a progressive loss of amplitude or speed during attempted rapid alternating movements of body segments (Marsden 1982; Edwards et al. 2008a; Jankovic 2008; Rodríguez-Oroz et al. 2009). It is crucial to distinguish true bradykinesia from simple slowness, which is frequently seen in patients with decreased muscle power (paresis), spasticity, or reduced motivation (e.g., depression).
