### ISSUE TITLE
Stooped posture

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2173]
_**Please consider a new term for Stooped posture.
Observed in Atypical juvenile parkinsonism.
PMID:23804577.
Superclasse:??
Posture abnormality wich could include also enlarged support polygon for exp.**_

**Comment by pnrobinson** [comment]
Definition:  A habitual positioning of the body with the head and upper back bent forward.

There is a category of abnormalities called abnormal posturing which is clearly a neurophysiology defect. Abnormal posture (no "ing") is probably best modelled as a constitutional symptom.

**Comment by pnrobinson** [comment]
On reconsideration, I have added this term as child of Abnormality of movement
