### ISSUE TITLE
Obsolete/Invalid OMIM IDs in the annotation file

### ISSUE THREAD

**Issue by sbello** [obophenotype/human-phenotype-ontology#2174]
Hi Peter,
We're updating our HPO load and I wanted to pass along the results of one of our QC reports to you. The excel spreadsheet has entries in the HPO annotation file where the OMIM ID is invalid or obsolete. An ID is considered invalid/obsolete in the QC report if it is:

- On the MGI OMIM exclude list of non-disease OMIM terms (see https://docs.google.com/spreadsheets/d/1djz8rxfiJqccaJhqYQ7eSx7OWuRMP6ZSUkKrWlmNLK8/edit?usp=sharing for the list)
- Obsolete in OMIM (has the prefix ^)
- A gene only record in OMIM (has the prefix *)

OMIM has been actively converting gene+phenotype records into gene only (*) records and when they do this, they reuse the OMIM ID from the + record for the gene only record.

[omim_hpo_qc_invalid_OMIMIDs.xlsx](https://github.com/obophenotype/human-phenotype-ontology/files/920695/omim_hpo_qc_invalid_OMIMIDs.xlsx)

Hopefully this is useful to you,
Sue

**Comment by pnrobinson** [comment]
?Thanks, a lot, Sue, this is very useful! We will attend to these records.

-best Peter


Peter Robinson

Professor of Computational Biology

The Jackson Laboratory for Genomic Medicine

10 Discovery Drive

Farmington, CT 06032

860.837.2095 t | 860.990.3130 m

peter.robinson@jax.org<mailto:peter.robinson@jax.org>

www.jax.org

Robinson lab: https://robinsongroup.github.io/

The Jackson Laboratory: Leading the search for tomorrow's cures

________________________________

**Comment by pnrobinson** [comment]
@LCCarmody @drseb 
I have put all of these lines in a google doc
https://docs.google.com/spreadsheets/d/10QVm8tndi_Taio4ag-sUTu06c0rPhpzBzK70pNx8Vt8/edit#gid=0
Let's take a look at this and see if it would be good to automate this (ca. 250 items), or whether manual checking is necessary.

**Comment by pnrobinson** [comment]
Hi!
I have put this as an issue here since it is a little easier to check the items in GitHib:
https://github.com/monarch-initiative/hpo-annotation-data/issues/140
@LCCarmody Let's take a look at this list and see how to address this.
