### ISSUE TITLE
staring gaze

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2175]
_**Please consider a new term for staring gaze.
Observed in atypical juvenile parkinsonism.
PMID:23804577.
Superclass:Abnormality of eye movement??**_

**Comment by pnrobinson** [comment]
Note that this is probably a good term, not necessarily related to Parkinson

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3367535/
Progressive supranuclear palsy: The classical phenotype (Richardson syndrome, RS) will be hardly confused with PD, as patients present with a largely symmetric akinetic-rigid syndrome, with predominant axial involvement, including impairment of gait and balance, with falls occurring as early as the first year of symptoms. Tremor is infrequently seen in these patients. Other typical signs of RS are vertical gaze supranuclear palsy (only slowing of vertical saccades is apparent in early stages), pseudobulbar symptoms, retrocollis, and continuous activity of the frontalis muscle, with eyes permanently wide open (e.g., “staring eyes”). Frontal-subcortical cognitive deficits are usually evident. Levodopa is usually of no benefit (Warren and Burn 2007; Williams and Lees 2009). However, other patients present with a parkinsonian syndrome resembling PD: symptoms are asymmetric, at times with rest tremor, with few axial involvement, delayed onset, or no eye movement disorder, and displaying levodopa responsiveness, even if partial. This syndrome has been called PSP-P (“PSP-parkinsonism”) and survival is longer than in RS (Williams et al. 2005).
