### ISSUE TITLE
weight loss

### ISSUE THREAD

**Issue by andrewdevereau** [obophenotype/human-phenotype-ontology#2176]
We would like to add terms to HPO to reflect the specific characteristic in Lipoedema Disease that dieting to try to control weight gain is ineffective, in particular below the waist. It is quite a difficult to state a suitable term as the symptom is usually described in the literature, e.g. 'successful weight loss from dieting has no effect on lower limb size' without a specific term being used. We are suggesting the following, but recognize that these may need to change to align with other HPO terms:

'Weight loss below the waist unresponsive to diet or exercise', or 
'No effect of diet on weight reduction below the waist'

It may also be sensible to include a superclass which omits the 'below the waist' qualifier, as this can sometimes be the case in lipoedema, and in other similar diseases.

A possible alternative term is 'diet-resistant subcutaneous adipose tissue' which can be qualified with 'below the waist' or 'of the legs'.

Two references are below, and the website here http://lipedemaproject.org/about-lipedema/

Rare adipose disorders (RADs) masquerading as obesity
Karen L Herbst
Acta Pharmacol Sin. 2012 Feb; 33(2): 155–172. Published online 2012 Feb 3. doi: 10.1038/aps.2011.153
PMCID: PMC4010336

Child AH, Gordon KD, Sharpe P, Brice G,
Ostergaard P, Jeffery S, Mortimer PS. 2010.
Lipedema: An inherited condition.
Am J Med Genet Part A 152A:970–976.

**Comment by pnrobinson** [comment]
Hi Andrew, would this be appropriate
--Ineffective weight loss on diet
---Ineffective weight loss below waist on diet

I am trying to find a prefered label for this term that is somewhat comprehensible in isolation (i.e., sitting in the middle of an ontology rather than being mentioned with a lot of context in a medical article). Let me know if you can think of anything better, otherwise I will add these terms as suggested by Monday.

**Comment by andrewdevereau** [comment]
Hi Peter,

Yes these sound good…it’s a difficult thing to define concisely.

Many thanks

Andrew

**Comment by pnrobinson** [comment]
Thanks.
I am adding the term as HP_0025384 (analogous for the child term which will be HP_0025385)
Diet-resistant subcutanoues adipose tissue
def: Areas of subcutanous fat tissue that are resitant to (do not respond as expected to) diet, life-style alteration, or bariatric surgery.
comment:In certain diseases such as multiple symmetric lipomatosis, lipedema and Dercum's disease, accumulation of subcutaneous adipose tissue may result from growth of an abnormal brown stem cell population or from vascular or lymphatic dysfunction, with the result that the subcutaneous adipose tissue is difficult or impossible to reduce by caloric limitation and increased energy expenditure.
