### ISSUE TITLE
Nemaline myopathy

### ISSUE THREAD

**Issue by sambaxter** [obophenotype/human-phenotype-ontology#2177]
Please consider including Nemaline Myopathy as a term.  

There is nemaline bodies and myopathy but not Nemaline Myopathy.
Relevant sources: https://www.ncbi.nlm.nih.gov/books/NBK1288/

**Comment by pnrobinson** [comment]
Our approach in the HPO is to provide terms for the phenotypic features of diseases but not for the diseases themselves (instead, we provide "annotations" for the diseases -- this is a major collaboration with ORPHANET and we also refer to OMIM, DECIPHER, and some other diseases).
Therefore, "nemaline bodies" is a feature of the disease "Nemaline myopathy", see http://www.orpha.net/consor/cgi-bin/OC_Exp.php?Lng=GB&Expert=607
