### ISSUE TITLE
3-hydroxy-acyl-CoA dehydrogenase deficiency

### ISSUE THREAD

**Issue by sambaxter** [obophenotype/human-phenotype-ontology#2178]
Should also include Short Chain 3-HYDROXYACYL-CoA DEHYDROGENASE DEFICIENCY (SCHAD) and Medium Chain 3-HYDROXYACYL-CoA DEHYDROGENASE DEFICIENCY (MCHAD) as aliases. 

Relevant reference: https://www.omim.org/entry/231530

**Comment by pnrobinson** [comment]
On hindsight, I think that the best term name is Decreased activity of 3-hydroxyacyl-CoA dehydrogenase
The other labels refer to diseases. I will add the all as related synonyms.
