### ISSUE TITLE
bitemporal hollowing

### ISSUE THREAD

**Issue by sambaxter** [obophenotype/human-phenotype-ontology#2179]
Feature of miller-dieker syndrome

Relevant reference: https://www.nature.com/jp/journal/v28/n4/full/7211920a.html

**Comment by pnrobinson** [comment]
Note this is not synonymous with bitemporal narrowing (HP:000034; prefered label is "Narrow forehead").
Suggested definition: Depression of profile in both temporal regions.
There is no perfect parent term, but we could use Abnormality of the periorbital region
