### ISSUE TITLE
Surfactant dysfunction disease

### ISSUE THREAD

**Issue by sambaxter** [obophenotype/human-phenotype-ontology#2180]
Please consider adding Surfactant dysfunction disease as a term.
Relevant Reference: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2987676/

**Comment by pnrobinson** [comment]
The HPO doesn't have terms for disease, but rather for the phenotypic manifestations of diseases. Take a look here at the annotations for a surfactant disease:
http://compbio.charite.de/hpoweb/showterm?disease=OMIM:265120
The disease is annotated as OMIM:265120, and the HPO terms are attached ("annotated") to the disease. This is the structure that makes applications like Phenomizer or Exomiser work. If there is a disease that is not currently annotated, then we can add it in this way to the database. 
I am closing this item now but please open a new item of specific HPO terms are missing.
