### ISSUE TITLE
Possible phenotype error for Waardenburg syndrome type 2

### ISSUE THREAD

**Issue by GARDInfoCenter** [obophenotype/human-phenotype-ontology#2181]
Hi,

GARD received a question about the HPO data on our page for Waardenburg syndrome type 2. A patient called wondering why microcephaly is listed as very frequent because she had never heard of this in anyone she knows with the condition. 
https://rarediseases.info.nih.gov/diseases/5520/waardenburg-syndrome-type-2

In researching this question for her, we were unable to find microcephaly listed as a feature on the following sites:

Orphanet: http://www.orpha.net/consor/cgi-bin/OC_Exp.php?Expert=895 
NORD: https://rarediseases.org/rare-diseases/waardenburg-syndrome/
OMIM type 2A: https://www.omim.org/clinicalSynopsis/193510 
OMIM type 2B: https://www.omim.org/clinicalSynopsis/600193 
OMIM type 2C: https://www.omim.org/entry/606662 
OMIM type 2D: https://www.omim.org/clinicalSynopsis/608890 
OMIM type 2E: https://www.omim.org/clinicalSynopsis/611584

It seems type 3 does occasionally have microcephaly and MR as features, so it is possible that microcephaly was included for type 2 by mistake. Could you please review and let us know if microcephaly should be listed as a phenotype of WS2? We are going to remove it from out HPO table for now because it does not appear to be a very frequent feature.

Thanks,

Michelle Snyder
GARD Operations Manager
michelle.snyder@icf.com

**Comment by drseb** [comment]
This is coming from Orphanet data (en_product4_HPO.xml , line 39005 et al.), where 
_Waardenburg syndrome type 2_ (ORPHA:895) is annotated with _Microcephaly_ (You can use [Orphamizer](http://compbio.charite.de/phenomizer_orphanet/) to see). Also _Waardenburg syndrome type 3_ (ORPHA:896) has the same annotation.

ping @LOURGHI

**Comment by pnrobinson** [comment]
@LOURGHI @GARDInfoCenter I agree with Sebastian that it is type III Wardenburg syndrome in which some patients have been described to have microcephaly. This article has a good synopsis of the differences of the WS types: https://www.jscimedcentral.com/Otolaryngology/otolaryngology-3-1113.pdf
I have not been able to find any reference to microcephaly and WS type II. We should remove this annotation from our database unless the Orphanet team have a reference for it.

**Comment by LOURGHI** [comment]
I just checked the file of my ex collegue I think there was an injection error since it is the first line that separates type 2 from type 3 and that on its file it is marked microcephaly in Type 3.
I will correct on the database.

**Comment by drseb** [comment]
Awesome @LOURGHI . It is always better to fix at source than to deal with this downstream.

Thanks!

I'll close this. Please re-open if you don't agree this should be closed @GARDInfoCenter
