### ISSUE TITLE
cornea verticillata

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2183]
...removed...

**Comment by pnrobinson** [comment]
def: Golden brown or gray deposits with a clockwise, whorl-like distribution in the inferior interpalpebal portion of the cornea.
syn: Vortex keratopathy
comment: Cornea verticillata can be a feature of Fabry disease and can occur as an adverse effect of mediciations including amiodarone.

**Comment by drseb** [comment]
Shouldn't this go into another ticket:

> The HPO documentation currently has this:
> http://human-phenotype-ontology.github.io/documentation.html#annot
> 
> Aspect: one of O (Phenotypic abnormality), I (inheritance), C (onset and clinical course) or M (Mortality/Aging). This field is mandatory; cardinality 1.
> 
> I am not sure we need this field in the annotation file. Is there a need for it by anyone?

**Comment by pnrobinson** [comment]
Not sure how that happened, but it does not belong here!
