### ISSUE TITLE
HPO is currently not suitable to map most entities of the IC3D classification

### ISSUE THREAD

**Issue by daboe01** [obophenotype/human-phenotype-ontology#2185]
I.e. the various phenotypes of Bowman's layer are missing.
Reference:
https://www.ncbi.nlm.nih.gov/pubmed/25564336

**Comment by pnrobinson** [comment]
Thanks for this. Table 1 in this paper is a list of disease entities -- as a general rule, the HPO does not include terms for diseases. However, the article is very useful for discussions of the features of disease. Please note that there can be ambiguity -- "corneal dystrophy" can refer to a disease entity with an etiology, a time course, and a set of features (e.g., corneal opacity, visual impairment etc), or can be used in to describe the finding of the corneal abnormality as a part of a larger disease entity. The medical literature does not always differentiate well. The HPO is currently not 100% consistent on this, but we are working on it, and in essence if you want to annotate to a specific corneal disease, you could use the corresponding ORDO term (Orphanet Rare Disease Ontology) or the OMIM id. To annotate say how severely a patient with that disease is affected, you could use the corresponding HPO terms.

I am leaving this issue open until I have reviewed the article in detail.

**Comment by daboe01** [comment]
thank you!
i understand that HPO does not include terms for diseases.
however, the HPO ist currently missing many phenotypes of the corneal dystophies, e.g. "Partial destruction and absence of Bowman's layer" such as in Franceschetti corneal dystrophy

**Comment by pnrobinson** [comment]
I agree 100% and the article you sent is a good place to reference such phenotypes. We will be working on this.

**Comment by daboe01** [comment]
this will surely be fixed in the context of ERN-EYE

**Comment by pnrobinson** [comment]
I am going to leave this open, because it will be good to prepare for the ERN-EYE meeting. We have a certain backlog of terms right now that we are working to resolve, but hopefully we can study this prior to the ERN meeting.

**Comment by pnrobinson** [comment]
The majority of terms from the ERN-EYE have now been incorporated into the HPO. I hope this is a good start, please open specific issues for terms that may be missing!
