### ISSUE TITLE
obsolete vs deprecated

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2187]
I would like to introduce a synonym type for synonyms that the community has agreed not to use anymore because they are regarded as derogatory, but that we need to retain because they are used in the (legacy) literature. Of several suggestions, I would think that
1. obsolete
2. deprecated
are the best options. I will add this next week unless there are other suggestions.

**Comment by cmungall** [comment]
You could of course simply annotate the axioms with owl:deprecated=true, but if we want to retain compatibility with obo format and have the synonyms appear as:

```
synonymtypedef: DEPRECATED "A historic synonym, no longer encouraged"
...
synonym: "FLK" RELATED DEPRECATED []
```

then it's necessary to follow the obo to owl mapping spec.

Of course, it may be preferable to treat these as an entirely separate annotation property so they don't clutter 'real' synonyms, but then this may have implications for search etc.

**Comment by pnrobinson** [comment]
Realistically, we cannot completely deprecate these synonyms, since many of them are still in common use. I think "obsolete" probably captures this the best?

**Comment by drseb** [comment]
ok. go with obsolete

**Comment by pnrobinson** [comment]
I added obsolete as a synonym type. There are many synonyms and even some primary labels that might be considered to be denigrating, and we should start to label them. I added this synonym type to mesomelic dwarfism as a test.
