### ISSUE TITLE
Question re: logical def for HP_0005623 Absent ossification of calvaria

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#2190]
the logical def for HP_0005623 Absent ossification of calvaria is
'has part' some 
('lacking processual parts' and ('occurs in' some neurocranium) and (towards some ossification) and ('has modifier' some abnormal))

but the parent class uses 'vault of skull' instead of 'neurocranium' (and some of the siblings use 'skull' instead of 'vault of skull'. Should this be consistent throughout?

**Comment by pnrobinson** [comment]
I think that uberon clearly states that 'vault of skull' is equivalent to Calvaria in HPO. There are issues. The definition of neurocraniinum in uberon does not match what we want, so I am changing it.
