### ISSUE TITLE
Add synonym to HP_0011323 Cleft of chin

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#2191]
Add synonym 'cleft chin' (and add layperson tag)

also add:
chin cleft, dimple chin, chin dimple (all layperson)

Ref: https://en.wikipedia.org/wiki/Chin

**Comment by pnrobinson** [comment]
Dimple chin is not the same thing as cleft chin
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2778021/
Also, we should update the preferred label. @LCCarmody  let's look at this together, there is a rather complicated terminology here.

**Comment by LCCarmody** [comment]
Is there anyway to put 'cleft chin' as an erroneous synonym to dimple chin?  There are many, many sites (including wikipedia) that list them as synonyms.  It seems the HPO already has Verticle crease, H-crease, cleft jaw, etc.

**Comment by pnrobinson** [comment]
Verticle crease and cleft chin should be synonyms. We can write in the comments that some consider them to be synonyms. This is a difficult topic.

**Comment by nicolevasilevsky** [comment]
We merge vertical crease and cleft chin then? Could we do this together?
@LCCarmody @pnrobinson

**Comment by pnrobinson** [comment]
Are cleft mandible and cleft of chin synonymous? The definition of cleft of chin is NOT synonymous with Vertical crease of chin/cleft chin, and thus the label of the former term seems potentially confusing. Let's check this!

**Comment by nicolevasilevsky** [comment]
@markengelstad could you weigh in on this?

**Comment by markengelstad** [comment]
I agree with putting 'cleft chin' as an erroneous synonym to dimple chin. And I agreed that a cleft chin is a synonym of vertical crease. And that it is decidedly different than cleft mandible. Previous definitions seem to be erroneous . And you should probably not be constrained by them.

Dimple chin and vertical crease and cleft chin are in a similar class. Left a mandible is a distinct class.

**Comment by LCCarmody** [comment]
Added 'cleft chin' as a synonym to 'chin with vertical crease'.  Is there anything else we should do?

**Comment by pnrobinson** [comment]
Seems good to me, I am closing.
