### ISSUE TITLE
Nocturnal seizures

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#2193]
Nocturnal Seizures--I am adding this issue because a collaborator mentioned the term was missing in a meeting.

Defn: "Any form of epilepsy may occur during sleep, but some types of epilepsy are more likely to be restricted exclusively to sleep. These are sometimes called Nocturnal Seizures.

Some people have seizures occur only during sleep whilst others have both daytime and nocturnal seizures. Studies have shown that 10 - 45% of people with epilepsy have seizures that occur predominantly or exclusively during sleep or occur with sleep deprivation."  https://www.epilepsy.org.au/about-epilepsy/understanding-epilepsy/nocturnal-seizures-during-sleep

Suggested parent term: Question: should this be a subclass of Generalized and Partial?

"A person who suffers from epilepsy regardless of whether it is nocturnal or not, can be categorized into two different types of epilepsy either being generalized, or partial. A generalized epilepsy syndrome is associated with an overall hyperactivity in the brain, where electrical discharges occur all over the brain at once; this syndrome often has a genetic basis. While generalized epilepsy occurs all over the brain, partial epilepsy consists of a regional or localized hyperactivity, which means that the seizures occur conversely in one part of the brain or several parts at once.[2]"

https://en.wikipedia.org/wiki/Nocturnal_epilepsy

**Comment by LCCarmody** [comment]
Note: I found 2 'seizure' and 'generalized seizure' sections-one under behavioral phenotype (and not capitalized) and one under Abnormality of the nervous system.  There is only one 'partial seizure' that is listed under behavioral phenotype, but not under abnormality of the nervous system.  Since nocturnal seizure can be either a generalized or partial seizure, then I think a term needs to be added under Abnormality of the nervous system.   Unclear what the parent should be-just 'Seizure'?

![screen shot 2017-05-12 at 9 21 44 am](https://cloud.githubusercontent.com/assets/26067008/25999782/71981b12-36f4-11e7-8b8e-47d26583a770.png)

**Comment by pnrobinson** [comment]
I will see if I can get some guidance from a neurologist on this.

**Comment by pnrobinson** [comment]
Adding as HP_0031951
