### ISSUE TITLE
Aortic valve calcification

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2214]
From Stanford cardiology workshop
Aortic valve calcification

**Comment by pnrobinson** [comment]
@mellybelly @jmcmurry @cmungall 
We already have a term for aortic calcification. Was there something else?

**Comment by nicolevasilevsky** [comment]
I'm pasting in the notes here, but it doesn't seem like there was anything else related to aortic valve calcification, maybe they just missed it.
https://docs.google.com/document/d/10VcYh_qDSf9iPt40gBaOvrwUQTIUoMzxxR1fEtuqSuU/edit

**Comment by pnrobinson** [comment]
Thanks Nicole -- could you please add a link to the directory, and I will make a new google doc with questions for the cardiologist team -- we will bundle the questions and then send them the entire progress document.

**Comment by nicolevasilevsky** [comment]
@pnrobinson what do you mean by the directory?

**Comment by pnrobinson** [comment]
The folder where the file lives so I can add a new file :-0

**Comment by nicolevasilevsky** [comment]
Oh, ha, I was thinking you meant something more complicated than that! Here you go: https://drive.google.com/drive/folders/0B1ggMLKFepMxN1kxalVaZnVtYUk

**Comment by pnrobinson** [comment]
I am closing this since it seems as if we are done.
