### ISSUE TITLE
Electrophysiology

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2221]
From Stanford cardiology workshop

Electrophysiology

Two categories (under Abnormality of CV system physiology)
 - [x] Abnormality of the cardiovascular system physiology => need intermediate node for electrophysiology
Conduction system abnormalities
Arrhythmia
    
https://github.com/obophenotype/human-phenotype-ontology/issues/1447 
Move abnormal atrioventricular conduction to child of conduction system abnormality

Heart block needs to be under conduction system

Palpitations - maybe under electrophysiology that is some kind of symptoms related to electrophysiology?

**Comment by pnrobinson** [comment]
Check absent atrioventricular node - this term may not really exist! 
But if it exists, it should have both an anatomical and a physiological parent

Complete heart block with broad RS complexes => should be QRS

Escapes are missing

In conduction system dysfunction
Sinus node
Av node
Infranodal dysfunction


Bundle branch block should not be under AV

**Comment by psergouniotis** [comment]
Just a quick comment: we are using the term electrophysiology in ophthalmology as well (visual electrophysiology) so please consider adding ?cardiac before so that it is clearer

**Comment by pnrobinson** [comment]
Added ter,m Cardiac conduction abnormality HP_0031546

**Comment by pnrobinson** [comment]
There already was a term: Mobitz II atrioventricular block. There is often an infranodal block in type II.

**Comment by pnrobinson** [comment]
There was a term Ventricular escape rhythm. I have added a definition.
