### ISSUE TITLE
buccal cell phenotype

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2265]
From Stanford cardiology workshop

For buccal cell phenotype see:
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4785796/

**Comment by pnrobinson** [comment]
Suggested term name: Abnormal distribution of cell junction proteins in buccal mucosal cells.
Def: An anomalous amount or location of cell junction proteins such as plakoglobin. Buccal mucosal cells are harvested from the oral mucosa in the region of the cheek, and can be used as a surrogate tissue to measure cell junction proteins because it is difficult to obtain cells from a tissue of interest such as the myocardium. Cell junction proteins may have an abnormal distribution in diseases such as arrhythmogenic cardiomyopathy.

@mellybelly  Probably we should put this term under anb cellular phenotype? We should discuss how to expand that subhierarchy.

**Comment by nicolevasilevsky** [comment]
need to MIREOT in buccal cell mucosa

**Comment by nicolevasilevsky** [comment]
@mellybelly we should work on the logical def for this term together. @drseb MIROET'd in the term need needed (thank you Seb!)

**Comment by nicolevasilevsky** [comment]
this class is too complicated for a logical definition. We added comments for usage.

**Comment by cmungall** [comment]
the latest text def reads:

"An anomalous amount or location of cell junction proteins such as plakoglobin or Cx43."

It says nothing about the buccal mucosa

**Comment by pnrobinson** [comment]
I added a term Abnormal buccal mucosa cell morphology, and put the above term as a child.
HP_0031476
Def:Any structural anomaly of the cells of the mucosa of the oral cavity in the region of the cheek (buccal mucosa cells).
Comment:Buccal mucosa cells are easy to obtain and are a useful model of some other diseases. For instance, muccal mucosa cells from arrhythmogenic cardiomyopathy patients exhibit changes in the distribution of cell junction proteins similar to those seen in the heart.
