### ISSUE TITLE
Comodogenic acne

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2269]
What was the use case for this term? Acne is characterised my comedones and I am not sure what the differentia is.

**Comment by drseb** [comment]
Not sure. Maybe: https://www.omim.org/clinicalSynopsis/615147?highlight=comedogenic  ??

**Comment by pnrobinson** [comment]
Overview of acne phenotypes, e.g. 
http://www.aafp.org/afp/2012/1015/p734.pdf

**Comment by pnrobinson** [comment]
According to http://www.livestrong.com/article/231065-comedogenic-acne/
Comedogenic acne differs from acne vulgaris--the common form of acne characterized by large, pus-filled bumps and nodules-- in that it is triggered by external factors rather than physiological ones. 

However, 
https://www.ncbi.nlm.nih.gov/pubmed/18177407 claims that
Comedogenic acne refers to the condition where the majority of the lesions consist of comedones, [...]  facial acne (open and closed comedones comprising the majority of the lesions, with fewer than ten papules and pustules) -- See Figure 1 of that paper

**Comment by pnrobinson** [comment]
I think though that "comedogenic" is a word that means "generating comedones". This can apply to cosmetic products, and also the cause of the OMIM disease Seb mentions above is mutation in Retinol-binding protein (RBP) 4, and the biochemical abnormalities associated with that diseases are "generating comedones" (recall that some of the treatments for acne target this pathway). 

Therefore, I think that the phenotypic feature should be called "comedonal acne", defined as "A type of acne in which open and closed comedones comprise the majority of the lesions, with substantially fewer papules and pustules".

I think that "comedogenic acne" is best conceptiualized as a disease entity because the phrase is a description of a phenotype/disease - acne, together with the etiology of the disease. Therefore, I would make "comedogenic acne" a RELATED SYN
