### ISSUE TITLE
Logical definition for hematuria

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2275]
The logical definition of hematuria is a faithful representation of the English language text, which I wrote and which unfortunately is wrong. It is actually blood cells that are seen in  the urine for microscopic hematuria and gross blood for macrohematuria. Therefore, this definition is not always true;I think the definition is OK for macrohematuria but can we use erythrocyte for microhematuria? What would the class "hematuria" be defined as then?

'has part' some 
    ('increased amount'
     and ('inheres in' some 
        (blood
         and ('part of' some urine)))
     and ('has modifier' some abnormal))

**Comment by pnrobinson** [comment]
@cmungall @drseb Any ideas for this definition?

**Comment by cmungall** [comment]
OK, I'm not totally following. Can you write textual genus-differentia definitions for the 3 classes?

**Comment by Frank-Probst** [comment]
"Hematuria" is used in both cases.  I would break it into two subclasses:  "Hematuria, gross", meaning that the urine looks bloody to the eye, and "hematuria, occult", meaning that the urine looks (relatively) normal, but blood is seen on laboratory testing, usually a urine dipstick test.  If the dipstick is positive, the urine is usually looked at under the microscope, and you'll get an estimate of the number of red blood cells seen in one high-powered field (HPF) of the microscope view.

**Comment by pnrobinson** [comment]
I am adding the synoynm Occult hematuria. I think the definition is OK.
