### ISSUE TITLE
NTR: Multiple organ failure

### ISSUE THREAD

**Issue by JuliavC** [obophenotype/human-phenotype-ontology#2277]
>If this is a request for a new term, please provide us with the folloing information (c.f., https://github.com/obophenotype/human-phenotype-ontology/wiki/How-to-make-a-good-term-request).

>1. Preferred term label (e.g., Asplenia)_

Multiple Organ Failure

>2. Synonyms (e.g., Absent spleen)

Total Organ Failure
Multiple Organ Dysfunction Syndrome
Multisystem Organ Failure

>3. Textual definition (the definition should be understandable even for non-specialists. Include a PubMed ID to refer to any relevant article that provides additional information about the suggested term).

>4. Suggested parent term (Please look in the hierarchy of the HPO using the [HPO Browser](http://compbio.charite.de/hpoweb/showterm?id=HP:0000118) or other browsers such as [OLS](http://www.ebi.ac.uk/ols/ontologies/hp) and find the place in the HPO where the new term best fits)

HP:0025142 Constitutional symptom

>5. If you know of a disease that is characterized by this feature, please indicate it (e.g., by its Orphanet or OMIM id), and we will add the annotation to our database.

>6. If you would like a nanoattribution, please indicate your ORCID id or provide a label such as HPO:probinson (organization, first initial-last name)

**Comment by pnrobinson** [comment]
On thinking about this, I think that multiple organ failure probably should be conceptualized as a disease, because it is bundling many different phenotypic abnormalities. If you would like input about how to model this, please send me an email.
