### ISSUE TITLE
new term request: visible zygomatic arches

### ISSUE THREAD

**Issue by NuriaQueralt** [obophenotype/human-phenotype-ontology#2279]
>This is a request for a new term

>1. Preferred term label (e.g., Asplenia)_
Visible zygomatic arches

>2. Synonyms (e.g., Absent spleen)

>3. Textual definition (the definition should be understandable even for non-specialists. Include a PubMed ID to refer to any relevant article that provides additional information about the suggested term).
Facial dysmorphology

>4. Reference (PMID)
This reference relates this requested phenotype with the NGLY1-deficiency rare disease
https://www.ncbi.nlm.nih.gov/pubmed/27388694

>5. Suggested parent term 
http://compbio.charite.de/hpoweb/showterm?id=HP:0001999

>6. If you know of a disease that is characterized by this feature, please indicate it (e.g., by its Orphanet or OMIM id), and we will add the annotation to our database.
DO: DOID:0060728
ORPHANET: ORPHA:404454
OMIM:615273

>7. If you would like a nanoattribution, please indicate your ORCID id or provide a label such as HPO:probinson (organization, first initial-last name)
http://orcid.org/0000-0003-0169-8159

**Comment by pnrobinson** [comment]
Is this a synonym for Malar prominence, Increased prominence of the malar region (cheeks), as manifested by anterior positioning of the infraorbital and perialar regions or increased convexity of the face or increased naso-labial angle.

**Comment by NuriaQueralt** [comment]
Reading the publication [1] where this phenotype is described i would say that it is not a synonym of 'Malar prominence'.  Specifically, the descriptions in this paper are:

- Talking about dysmorphology and facial features: "Most affected individuals had hypotonic facies. The features of older individuals reflected their low weight, with thin facies, hollowed cheeks, and visible zygomatic arches."

- Figure 2 shows individuals with NGLY1 deficiency and their facial features. 

Thus, my guess is that zygomatic arches in this disease are visible due too low weight/hypotonic facies/thin facies, and not due to an abnormality of the bone. But, i am not an expert so i am not sure.


[1] https://www.ncbi.nlm.nih.gov/pubmed/27388694

**Comment by pnrobinson** [comment]
I am looking at the publication now, and I do not think that the clinical description is that precise. The zygomatic arches are visible to some extent in all faces, and one might codes this as "Prominence of the zygomatic bone"  (Definition: Large or prominent malar surface of the zygomatic bone of the skull, which is convex and forms the prominence of the 'cheek bones'). From the clinical pictures this feature is not very striking though. In any case, I do not think it is a new phenotypic concept that would deserve a new HPO term.
