### ISSUE TITLE
Low NAA (N-acetylaspartylglutamate plus N-acetylaspartate) in brain by MRS 

### ISSUE THREAD

**Issue by NuriaQueralt** [obophenotype/human-phenotype-ontology#2280]
>This is a request for a new term

>1. Preferred term label (e.g., Asplenia)_
Low NAA (N-acetylaspartylglutamate plus N-acetylaspartate) in brain by MRS 

>2. Synonyms (e.g., Absent spleen)

>3. Textual definition (the definition should be understandable even for non-specialists. Include a PubMed ID to refer to any relevant article that provides additional information about the suggested term).

>4. Reference (PMID)
This reference relates this requested phenotype with the NGLY1-deficiency rare disease
https://www.ncbi.nlm.nih.gov/pubmed/27388694

>5. Suggested parent term 
http://compbio.charite.de/hpoweb/showterm?id=HP:0012705

>6. If you know of a disease that is characterized by this feature, please indicate it (e.g., by its Orphanet or OMIM id), and we will add the annotation to our database.
DO: DOID:0060728
ORPHANET: ORPHA:404454
OMIM:615273

>7. If you would like a nanoattribution, please indicate your ORCID id or provide a label such as HPO:probinson (organization, first initial-last name)
http://orcid.org/0000-0003-0169-8159

**Comment by pnrobinson** [comment]
I am not an expert in this area, but looking at this article
https://www.ncbi.nlm.nih.gov/pubmed/20597122
it seems that it is difficult to measure N-acetylaspartylglutamate by MRS.
"The signal of NAAG, however, largely overlaps with its precursor and degrading product N-acetylaspartate (NAA) that by itself does not act in glutamatergic neurotransmission."
Therefore, it seems that the existing term
Reduced brain N-acetyl aspartate level by MRS (HP_0012708) is good for this!
