### ISSUE TITLE
Keratoconus (HP:563) is a diagnosis with several phenotypes

### ISSUE THREAD

**Issue by daboe01** [obophenotype/human-phenotype-ontology#2293]
the phenotypes are nicely summarized here:
https://www.ncbi.nlm.nih.gov/pubmed/20537579

**Comment by psergouniotis** [comment]
Further to Peter's comment on #2192, I think it would be nice to keep keratoconus in HPO (reflecting indeed a constellation of signs that can be mentioned in the definition) for a number of reasons including the fact that it has been used as a phenotypic features of other diseases (e.g. OMIM 609438).

**Comment by pnrobinson** [comment]
Thanks for noting this. The HPO term is meant to describe the thinned, cone-like bulge that is the main phenotype of this disease, since keratoconus itself is a feature of other diseases. Is there a better way of describing this? I will add the other phenotypic features as described in this article.

**Comment by pnrobinson** [comment]
The HPO term keratoconus is used to annotated 36 Mendelian diseases in our database.  In a sense, this is the "phenotype" that is reported to other physicians, even though keratoconus is a disease entity. For now, I have updated the definition to this:
A cone-shaped deformity of the cornea characterized by the presence of corneal distortion secondary to thinning of the apex.
I have added the following comment. : 
Keratoconus is an entity characterid by several phenotypic findings such as corneal distortion (secondary to thinning of the apex) and either Fleischer's ring or Vogt's striae. This HPO term intends to denote the finding of corneal distortion and bulge.

**Comment by psergouniotis** [comment]
I would propose the following definition for keratoconus (modified from OHO 2014):
" Keratoconus is a common corneal ectasia characterised by progressive conical distortion of the cornea with associated irregular astigmatism and axial corneal stromal thinning. Early signs of keratoconus include Vogt's striae (vertical lines in the corneal stroma which may disappear with pressure) scissoring reflex on retinoscopy, oil droplet reflex on ophthalmoscopy and prominet corneal nerves. Late signs of keratoconus include Fleischer ring (iron deposition at the base of the cone), Munson's sign (conical distortion of lower lid on downward gaze) and Rizutti's sign (abnormal focusing of a slit-beam orientated obliquely across the cone from the temporal side). "
