### ISSUE TITLE
MIREOT terms

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#2298]
@drseb, when you have a chance, could you please MIREOT in the following terms:
http://purl.obolibrary.org/obo/CL_0002336 (needed for #2265)
http://purl.obolibrary.org/obo/CHEBI_80298 (needed for #2063)
http://purl.obolibrary.org/obo/CHEBI_17002 (needed for #2014)

(I created a new label for MIREOT)

**Comment by drseb** [comment]
It seems the mireot pipeline is not working anymore. Running make is not working for me. We need a plan.

@cmungall Is this working for you?

**Comment by drseb** [comment]
@cmungall forget what I was saying. Got it to work. Thanks

**Comment by nicolevasilevsky** [comment]
@cmungall looks like the CL term were not actually MIREOT'd.
http://purl.obolibrary.org/obo/CL_0002336

**Comment by drseb** [comment]
I think I did this
