### ISSUE TITLE
oral motor deficits

### ISSUE THREAD

**Issue by NuriaQueralt** [obophenotype/human-phenotype-ontology#2303]
>This is a request for a new term

>1. Preferred term label (e.g., Asplenia)_
Oral motor deficits

>2. Synonyms (e.g., Absent spleen)

>3. Textual definition (the definition should be understandable even for non-specialists. Include a PubMed ID to refer to any relevant article that provides additional information about the suggested term).

>4. Reference (PMID)
This reference relates this requested phenotype with the NGLY1-deficiency rare disease
https://www.ncbi.nlm.nih.gov/pubmed/27388694

>5. Suggested parent term 

>6. If you know of a disease that is characterized by this feature, please indicate it (e.g., by its Orphanet or OMIM id), and we will add the annotation to our database.
DO: DOID:0060728
ORPHANET: ORPHA:404454
OMIM:615273

>7. If you would like a nanoattribution, please indicate your ORCID id or provide a label such as HPO:probinson (organization, first initial-last name)
http://orcid.org/0000-0003-0169-8159

**Comment by pnrobinson** [comment]
This is the sentence from the paper:  "Oral  motor  deficits,  including  persistent  nutritive  suckle  swallow  and  poor  oral  bolus formation,  were  present  in  10  of  11  subjects."
 I do not think that these items are true motor deficits, this is not good terminology. 
I have added a term for the bolus formation, and the current HPO term "suck reflex" (HP_0030906) is synonymous with "persistent  nutritive  suckle  swallow" (I will add the latter as a synonym).
Thus, I do not think that "Oral motor deficit" is accurate or a good HPO term.
