### ISSUE TITLE
Pharyngeal swallow response delays

### ISSUE THREAD

**Issue by NuriaQueralt** [obophenotype/human-phenotype-ontology#2306]
>This is a request for a new term

>1. Preferred term label (e.g., Asplenia)_
Pharyngeal swallow response delays

>2. Synonyms (e.g., Absent spleen)

>3. Textual definition (the definition should be understandable even for non-specialists. Include a PubMed ID to refer to any relevant article that provides additional information about the suggested term).

>4. Reference (PMID)
This reference relates this requested phenotype with the NGLY1-deficiency rare disease
https://www.ncbi.nlm.nih.gov/pubmed/27388694

>5. Suggested parent term 

>6. If you know of a disease that is characterized by this feature, please indicate it (e.g., by its Orphanet or OMIM id), and we will add the annotation to our database.
DO: DOID:0060728
ORPHANET: ORPHA:404454
OMIM:615273

>7. If you would like a nanoattribution, please indicate your ORCID id or provide a label such as HPO:probinson (organization, first initial-last name)
http://orcid.org/0000-0003-0169-8159

**Comment by pnrobinson** [comment]
I think the term label should be
Impaired oropharyngeal swallow response
Def: Delay or absence of the swallow response, reflexes triggered by the contact the food bolus makes with the anterior faucial pillars.
Comment: In the involuntary pharyngeal phase, the soft palate rises to close the nasopharynx and prevent nasal regurgitations. The hyoid bone rises, bringing the larynx up, while the epiglottis closes the entrance to the larynx. The base of the tongue contacts the pharyngeal wall, at the same time as the hyoid moves forward, coinciding with the relaxation of the cricopharyngeus muscle and the opening of the upper esophageal sphincter.
