### ISSUE TITLE
Elevated antibody rubeola/rubella titers after vaccination

### ISSUE THREAD

**Issue by NuriaQueralt** [obophenotype/human-phenotype-ontology#2318]
>This is a request for a new term

>1. Preferred term label (e.g., Asplenia)_
Elevated antibody rubeola/rubella titers after vaccination

>2. Synonyms (e.g., Absent spleen)
High antibody titers after rubella and rubeola vaccination 

>3. Textual definition (the definition should be understandable even for non-specialists. Include a PubMed ID to refer to any relevant article that provides additional information about the suggested term).

>4. Reference (PMID)
This reference relates this requested phenotype with the NGLY1-deficiency rare disease
https://www.ncbi.nlm.nih.gov/pubmed/27388694

>5. Suggested parent term 

>6. If you know of a disease that is characterized by this feature, please indicate it (e.g., by its Orphanet or OMIM id), and we will add the annotation to our database.
DO: DOID:0060728
ORPHANET: ORPHA:404454
OMIM:615273

>7. If you would like a nanoattribution, please indicate your ORCID id or provide a label such as HPO:probinson (organization, first initial-last name)
http://orcid.org/0000-0003-0169-8159

**Comment by pnrobinson** [comment]
Hi Nuria,
I am thinking that this phenotype is currently not sufficiently well described to be an HPO term. HPO terms are for characteristic abnormalities, and in this case, there is just a single publication, the phenotype was not well studied, and it is unclear if it is specific for rubeola/rubella or if other vaccinations also have the same effect. If this phenomenon is recorded in additional publications then I think we should think about adding the term and perhaps a hoierarchy of related terms like this.

**Comment by NuriaQueralt** [comment]
Agree.  Thank you!
