### ISSUE TITLE
Abnormal liver storage

### ISSUE THREAD

**Issue by NuriaQueralt** [obophenotype/human-phenotype-ontology#2331]
>This is a request for a new term

>1. Preferred term label (e.g., Asplenia)_
Abnormal liver storage

>2. Synonyms (e.g., Absent spleen)
liver storage | liver vacuolization|hepatocyte cytoplasmic storage material | Hepatocyte vacuolization

>3. Textual definition (the definition should be understandable even for non-specialists. Include a PubMed ID to refer to any relevant article that provides additional information about the suggested term).

>4. Reference (PMID)
This reference relates this requested phenotype with the NGLY1-deficiency rare disease
https://www.ncbi.nlm.nih.gov/pubmed/24651605

>5. Suggested parent term 
http://compbio.charite.de/hpoweb/showterm?id=HP:0001392

>6. If you know of a disease that is characterized by this feature, please indicate it (e.g., by its Orphanet or OMIM id), and we will add the annotation to our database.
DO: DOID:0060728
ORPHANET: ORPHA:404454
OMIM:615273

>7. If you would like a nanoattribution, please indicate your ORCID id or provide a label such as HPO:probinson (organization, first initial-last name)
http://orcid.org/0000-0003-0169-8159

**Comment by LCCarmody** [comment]
@pnrobinson, I was attempting to add this term, but I am not sure that 'abnormal liver storage' is the proper term for this.  This appears to be abnormality of glycosylation in the liver.  We did add the term 'abnormal hepatic glycogen storage' as a parent to 'Increased hepatic gylcogen' and thought that 'abnormal liver storage' could be a broad synonym for 'abnormal hepatic glycogen storage'.  We still would need another label for this term.  Could you suggest something?

**Comment by pnrobinson** [comment]
Adding as Storage in hepatocytes, def Hepatocytes (liver parenchymal cells) exhibit a bloated appearance because of expansion of the cytoplasm by  accumulated  material.
HP_0031137
