### ISSUE TITLE
Definition of HP_0002955 (Granulomatosis)

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#2336]
A granulomatous inflammation leading to granuloma formation is a specific type of inflammation. A granuloma is a focal compact collection of inflammatory cells, mononuclear cells predominating, usually as a result of the persistence of a non-degradable product and of active cell mediated hypersensitivity. (See James DG. A clinicopathological classification of granulomatous disorders. Postgrad Med J. 2000 Aug;76(898):457-65. Review. PMID: 10908370)

submitted by eheiden

**Comment by pnrobinson** [comment]
Thanks! I am updating the definition.
