### ISSUE TITLE
Joint swelling onset late infancy

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2338]
Please do not make terms like this without putting them on the tracker. This should be simply Joint swelling using an onset modifier. In general, very rarely should HPO labels have onset or etiologies except if this is being used as a shorthand to describe a specific phenotypic feature.

This is being used to annotate two diseases
OMIM:169170 PATTERSON PSEUDOLEPRECHAUNISM SYNDROME
	
OMIM:305450 OPITZ-KAVEGGIA SYNDROME

I will reannotate them as soon as Table editor is working

**Comment by drseb** [comment]
> Please do not make terms like this without putting them on the tracker.

Who are you talking to here?

**Comment by pnrobinson** [comment]
Everybody on the list--we need to really go through all of the terms we now have an do Q/C and add definitions as the HPO os now being used in EHRs etc.

**Comment by drseb** [comment]
This term was already in one of the first versions of HPO...  (see https://github.com/Human-Phenotype-Ontology/HPO-archive/tree/master/2009-2013/hpo-2009-1)

**Comment by pnrobinson** [comment]
This is one of many legacy terms that we need to revise. I am thinking we need to make an effort to supply a definition for all terms and while so doing check for obvious mistakes like this.

**Comment by pnrobinson** [comment]
I cannot now find any referenceto joint swelling in OMIM:305450 OPITZ-KAVEGGIA SYNDROME. I looked at several reference sources in pubmed and at the current OMIM record. This annotation was IEA fro 2009 and thus it may have related to an entry that OMIM has revised or corrected or it may have been a false positive. I am thereforeremoving it.

**Comment by pnrobinson** [comment]
OMIM:169170 PATTERSON PSEUDOLEPRECHAUNISM SYNDROME does have joint swelling with onset late infacncy. I am going to annotate it to simply joint swelling with an onset term, and then obsolete this term.
