### ISSUE TITLE
MIREOT terms need for 'Abnormality of the intrinsic pathway' children

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#2346]
@pnrobinson, @drseb - For the new children terms of HP_0010989 'Abnormality of the intrinsic pathway' how would we write the logical definition? Would we use terms from PRO, such as:
HP_0001929 Abnormal factor VIII activity be:
'has part' some 
    ('decreased rate'
     and ('inheres in' some 'coagulation factor VIII')
     and ('has modifier' some abnormal))

If yes, please MIREOT in the following terms:
- http://purl.obolibrary.org/obo/PR_000007302 (for  HP_0001929)
- http://purl.obolibrary.org/obo/PR_000003252 (for HP_0001976)
- http://purl.obolibrary.org/obo/PR_P00740 (for HP_0011858)
- http://purl.obolibrary.org/obo/PR_000007295 (for HP_0001929)
- http://purl.obolibrary.org/obo/PR_000007296 (for HP_0004841)
- http://purl.obolibrary.org/obo/PR_000009430 (for HP_0005527)

Related to #2317 

There don't seem to be terms in GO relating to the activity of these proteins.

**Comment by nicolevasilevsky** [comment]
@drseb @pnrobinson is the proposed logical def above correct?
Thanks @drseb for MIREOTing these terms.

**Comment by pnrobinson** [comment]
@drseb @cmungall 
I do not know if it is correct to say "decreased rate" inheres in  coagulation factor VIII
since otherwise we would say it inheres in 'coagulation factor VIII activity'
Could Chris or Seb weigh in?

**Comment by nicolevasilevsky** [comment]
I agree, decreased rate seems wrong.
I was trying to find a similar term with a logical def, and I found this one:
HP_0008972 Decreased activity of mitochondrial respiratory chain
'has part' some 
('decreased rate' and ('inheres in' some 'mitochondrial respiratory chain') and ('has modifier' some abnormal))

**Comment by nicolevasilevsky** [comment]
In MP, for a decreased protein/chemical level, they use a logical def like this:
MP_0005643 decreased dopamine level
'has part' some 
('decreased amount' and ('inheres in' some dopamine) and ('has modifier' some abnormal))

**Comment by nicolevasilevsky** [comment]
These text defs are mostly saying 'decreased activity', so should we be using a GO term in the logical definition? However, I don't think a GO term exists for most of these.

There is an exception with HP_0001976 Reduced antithrombin III activity
Text def:
An abnormality of coagulation related to a decreased concentration of antithrombin-III.

So this logical def could work, yes?
'has part' some
('decreased amount' and ('inheres in' some antithrombin-III) and ('has modifier' some abnormal))

**Comment by pnrobinson** [comment]
This definition makes more sense to me. However, the decreased level definitions and the decreased amount definitions will be very close in meaning except in those rare occasions when a mutation affects the rate of an enzyme without affecting the amount etc.  The problem is that we have often chosen one or the other patter based on the availability of the "E" term from ChEBI, PRO, GO etc. and not based on the biochemistry. We need to rethink this and possibly go back to old definitions.

**Comment by drseb** [comment]
I will closes this for now. Please re-open if needed

**Comment by drseb** [comment]
I mean, please file separate ticket if needed. The originial ticket was about MIREOTing, which I have done
