### ISSUE TITLE
Hepatoportal sclerosis

### ISSUE THREAD

**Issue by andrewdevereau** [obophenotype/human-phenotype-ontology#2349]
New term request

1. Preferred term label: Hepatoportal sclerosis

2. Synonyms: Idiopathic non-cirrhotic portal hypertension, Idiopathic portal hypertension, Obliterative portal venopathy, non cirrhotic portal fibrosis, incomplete septal cirrhosis

3. Definition: Hepatoportal sclerosis is a rare disorder characterized histologically by sclerosis of the intrahepatic portal veins of the liver and manifested by non-cirrhotic portal hypertension, features of which will include splenomegaly and varices. The diagnosis is based on histological examination of the liver. Clinical manifestations include encephalopathy, ascites and variceal bleeding.

Refs: 
Schouten JN et al. Idiopathic noncirrhotic portal hypertension. Hepatology 2011; 54(3): 1071-81. PMID: 21574171

Majumdar A et al. An autosomal dominant form of non-cirrhotic portal hypertension. Journal of Hepatology 2015; 63(2): 525-7. PMID: 25796481

4. Parent term: HP:0004941 Extrahepatic Portal Hypertension

5. Hepatoportal sclerosis (ORPHA:64743) – describes the condition

**Comment by pnrobinson** [comment]
I would think that "Intrahepatic portal vein sclerosis" is a better label for the phenotype, since "Hepatoportal sclerosis" seems to be used to describe the disease. I would add this as the primary term and the "Hepatoportal sclerosis" as a related synonym?

**Comment by andrewdevereau** [comment]
Thanks Peter - yes we are happy with your suggestion

**Comment by pnrobinson** [comment]
Adding term as HP_0031015
