### ISSUE TITLE
Wrong label for HP_0025480

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#2352]
Please fix label, it is a definition at the moment.

**Comment by pnrobinson** [comment]
I think you are referring to HP_002548. This is actually the label of the term, there is no shorter way of saying this. I am adding a definition as well.

**Comment by pnrobinson** [comment]
Definition: Parkinsonism is a clinical syndrome that is a feature of a number of different diseases, including Parkinson disease itself, other neurodegenerative diseases such as progressive supranuclear palsy, and as a side-effect of some neuroleptic medications. Some but not all individuals with Parkinsonism show responsiveness to dopaminergic medication defined as a substantial reduction of amelioration of the component signs of Parkinsonism (including mainly tremor, bradykinesia, rigidity, and postural instability) upon administration of dopaminergic medication.

**Comment by drseb** [comment]
Oh ok. Sorry.

**Comment by sdumitriu** [comment]
@pnrobinson: @drseb is right, the label for HP:0025480 is wrong, this isn't about HP:0002548.

[Current label](http://compbio.charite.de/hpoweb/showterm?id=HP:0025480):

> A type of spinal dysraphism presenting as a subcutaneous fatty mass, that is, a spinal defect associated with lipomatous tissue, and covered by skin. The most usual location for lipomyelomeningocele is at the gluteal cleft.

**Comment by drseb** [comment]
Ok. I think this has been fixed now in the latest dev version and will be online soon
