### ISSUE TITLE
Preferred term label: premature ovarian insufficiency

### ISSUE THREAD

**Issue by BrunOrpha** [obophenotype/human-phenotype-ontology#2362]
Concerning:
HP: 0008209 Premature ovarian failure
HP: 0001587 Primary ovarian failure
(abnormal internal genitalia morphology)
and
(puberty and gonadal disorders) 
HP: 0100805 Precocious menopause [this term is to obsolete, since insufficiency is not a permanent cessation of menses and since rare pregnancies have been described, as opposed to physiological menopause]

References:
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3727655 (ref 23)
https://www.ncbi.nlm.nih.gov/pubmed/?term=24945456
https://www.ncbi.nlm.nih.gov/pubmed/?term=27008889 (ESHRE consensus)

**Comment by pnrobinson** [comment]
According to the ESHRE consensus, the following labels have been used for "premature ovarian insufficiency" (which should be the preferred label):
(see Table 1.1 in https://www.eshre.eu/Guidelines-and-Legal/Guidelines/Management-of-premature-ovarian-insufficiency.aspx)

Primary Ovarian Insufficiency
Premature Ovarian Failure
Gonadal dysgenesis
Premature menopause
Early menopause
Hypergonadotropic hypogonadism
Premature Ovarian Insufficiency
Ovarian dysgenesis
Primary ovarian failure
Hypergonadotropic amenorrhea
Climacterium praecox
Menopause praecox

**Comment by pnrobinson** [comment]
This means that we need to merge the terms into a single term as suggested by BrunOrpha (thank you!)
