### ISSUE TITLE
Wrong syn for Macrotia?

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#2366]
Is _Large dysplastic ears_ a valid synonym _Macrotia_ ?

Other synonyms are: 
```
Large, prominent pinnae
Large prominent ears
Large, prominent ears
Large pinnae
Large, protruding ears
Large protruding ears
Large ears
Large, floppy ears
```

**Comment by pnrobinson** [comment]
Macrotia just means big ear, but without any other adjective. 
Something went wrong with these synonyms.

Valid syns are
Large ear (Lay person)
Large pinnae

large prominent/protruding probably mean the ears also stick out to the sides, but this is not well defined.

**Comment by drseb** [comment]
Can we fix?
