### ISSUE TITLE
Obsolete term 'Partial Cellular Immunodeficiency'

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#2369]
Obsolete term. HP:0005375

**Comment by pnrobinson** [comment]
This is used to annotate only one disease in our corpus,

OMIM:242850 | IMMUNE DEFICIENCY DISEASE

This OMIM entry refers to one publication only, from 1973, and it is unclear if this is a true disease entity.

**Comment by pnrobinson** [comment]
I will reannotate the disease with the corresponding cellular immune deficiency term

**Comment by pnrobinson** [comment]
I have removed the word partial from the label Partial humoral immunodeficiency (which was also used only to annotate this disease).
