### ISSUE TITLE
New terms request: 'Lack of thymic shadow' and athymia

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#2373]
>1. Preferred term label (e.g., Asplenia)_ 'Lack of thymic shadow' and athymia

>2. Synonyms (e.g., Absent spleen) These should be related synonyms.

>3. Textual definition (the definition should be understandable even for non-specialists. Include a PubMed ID to refer to any relevant article that provides additional information about the suggested term).
Athymia: Congenital absence of the thymus, often with associated immunodeficiency. 

>4. Suggested parent term (Please look in the hierarchy of the HPO using the [HPO Browser](http://compbio.charite.de/hpoweb/showterm?id=HP:0000118) or other browsers such as [OLS](http://www.ebi.ac.uk/ols/ontologies/hp) and find the place in the HPO where the new term best fits)
Combined immunodeficiency HP:0005387

**Comment by pnrobinson** [comment]
Athymia is synonymous with the current term "Aplasia of the thymus". I am adding it as a synonym.

**Comment by pnrobinson** [comment]
I am also adding Absent thymic shadow etc as RELATED synonyms to Aplasia of the thymus, as the meaning is nearly the same (but might be construed to include the possibility of a false positive xray finding,i.e.,thymus is present but there was no shadow for whatever reason).

**Comment by pnrobinson** [comment]
This was taken care of.
