### ISSUE TITLE
New term/edit terms:  Use 'proportional' instead of abnormal counts

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#2377]
Example/Suggestion:  Keep parent term "Abnormality of B cell number(or count)
but the child terms should be 'Abnormal immature B cell proportion' and 'Abnormal memory B cell proportion'.

In the definition, it should state that the X type of B cell is abnormal with respect to the total number of B cells.

**Comment by pnrobinson** [comment]
I am closing this issue since we are now adopting this pattern.
