### ISSUE TITLE
New term request:  Alloimmune, Drug-induced, or WHIM neutropenia

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#2378]
>1. Preferred term label (e.g., Asplenia)_ Requesting new terms for:
        A. Alloimmune neutropenia
        B. Drug-induced neutropenia
        C. WHIM-neutropenia

>3. Textual definition (the definition should be understandable even for non-specialists. Include a PubMed ID to refer to any relevant article that provides additional information about the suggested term).
Alloimmune neutropenia-s the result of antibodies directed against human neutrophil antigens (HNA) transplacentally transferred to the fetus from the maternal circulation. http://www.redcrossblood.org/hospitals/neutrophil-laboratory/clinical-indications/ann

Drug-induced neutropenia-drugs (like chemotherapeutics) can cause a predictable and dose-related decrease in neutrophil count.  PMID: 27990078

WHIM neutropenia- no definition

>4. Suggested parent term 
Abnormal neutrophil count HP:0011991

>5. If you know of a disease that is characterized by this feature, please indicate it (e.g., by its Orphanet or OMIM id), and we will add the annotation to our database. 

NOTE: the suggestion was to add 'WHIM neutropenia', but I don't think that is the term, I think we need to add WHIM (Warts, Hypogammaglobulinemia, Immunodeficiency, and Myelokathexis syndrome) to the database and link it to neutropenia.

**Comment by LCCarmody** [comment]
Did not add separate term for 'WHIM-neutropenia'

**Comment by pnrobinson** [comment]
I think that we should not start adding etiology-related phenotype terms, because then we would need to subtype essentially all of the terms in the HPO. It is better to address this with annotations.
