### ISSUE TITLE
NTR: Vitreomacular adhesion, Vitreomacular traction & Full-thickness macular hole

### ISSUE THREAD

**Issue by psergouniotis** [obophenotype/human-phenotype-ontology#2404]
As discussed in #1152, please consider adding the following terms:
* Vitreomacular adhesion
* Vitreomacular traction
* Full-thickness macular hole

1A. Preferred term label: Vitreomacular adhesion
2A. Synonyms: VMA
3A. Textual definition: Vitreomacular adhesion is defined as perifoveal vitreous separation with remaining vitreomacular attachment and unperturbed foveal morphologic features. It is an OCT finding that is almost always the result of normal vitreous aging, which may lead to pathologic conditions (PMID: 24053995)
4A. Suggested parent term: Macular thickening (HP:0030498)

1B. Preferred term label: Vitreomacular traction
2B. Synonyms: VMT
3B. Textual definition: Vitreomacular traction is characterized by anomalous posterior vitreous detachment accompanied by anatomic distortion of the fovea, which may include pseudocysts, macular schisis, cystoid macular edema, and subretinal fluid. Vitreomacular traction can be subclassified by the diameter of vitreous attachment to the macular surface as measured by OCT, with attachment of 1500 μm or less defined as focal and attachment of more than 1500 μm as broad (PMID: 24053995)
4B. Suggested parent term: Macular thickening (HP:0030498).

1C. Preferred term label: Full-thickness macular hole
2B. Synonyms: FTMH
3B. Textual definition: Full-thickness macular hole (FTMH) is defined as a foveal lesion with interruption of all retinal layers from the internal limiting membrane to the retinal pigment epithelium. Full-thickness macular hole is primary if caused by vitreous traction or secondary if directly the result of pathologic characteristics other than vitreomacular traction. Full-thickness macular hole is subclassified by size of the hole as determined by OCT and the presence or absence of vitreomacular traction (PMID: 24053995)
4B. Suggested parent term: Macular hole (HP:0011508).

**Comment by pnrobinson** [comment]
I am adding these terms now. I do not understand why the parent term should be Macular thickening? I am putting them as Abn of the macula for now, but please explain!

**Comment by psergouniotis** [comment]
Thanks you Peter. Valid point about the parent term:
* The term "full-thickness macular hole" should have "Macular hole" (HP:0011508) as a parent term.
* VMT and VMA are trickier. VMT is considered as stage 1 macular hole (impending) so it can be argued that it should also have macular hole (HP:0011508) as parent term. More importantly, VMT is associated with anatomic changes in the contour of the foveal surface and elevation of the fovea from the RPE, therefore macular thickening (HP:0030498) (https://www.ncbi.nlm.nih.gov/pubmed/24053995).

I am not sure what would be best at this stage but I would propose leaving VMA under abnormality of the macula, and considering adding VMT under macular thickening (HP:0030498).

**Comment by pnrobinson** [comment]
VMT is HP_0031151
VMA is HP_0031150
Full thickness macular hole is HP_0031152
