### ISSUE TITLE
NTR: macular dots & retinal dots

### ISSUE THREAD

**Issue by psergouniotis** [obophenotype/human-phenotype-ontology#2411]
>1A. Preferred term label: macular dots
>4A. Suggested parent term: yellow/white lesions of the macula (HP:0030500)

>1B. Preferred term label: retinal dots
>4B. Suggested parent term: yellow/white lesions of the retina (HP:0030506)

> as per request from KK ("I can't find macular dots. I realise that one mans dot is another mans fleck/drusen. I have seen a number patients with "benign dots of Moore" type lesions, and the "dot and fleck retinopathy" associated with Alport Syndrome and wonder how you'd classify these currently. Could dots be included under yellow/white lesson of the retina/macula?")

**Comment by pnrobinson** [comment]
@psergouniotis Hi Panos, could you provide us with a definition that would distingish dots from Flecks or Drusen? If they really are nearly the same thing, we could just add them as synonyms or RELATED synonyms. Also, is there a definition for "yellow/white lesions"? Thanks!

**Comment by pnrobinson** [comment]
@psergouniotis  is this issue superseded by the recent workshop? Is there a case for these terms?

**Comment by psergouniotis** [comment]
yes, these terms would be very helpful and should be introduced. I will work on some definitions (although this is one of those best described with images).

**Comment by pnrobinson** [comment]
@psergouniotis  Could you please provide definitions?
I am assuming these are not the same as Gunn's dots? 
https://www.ncbi.nlm.nih.gov/pubmed/25077537

**Comment by psergouniotis** [comment]
It could include Gunn's dots but also the dots seen in Alport syndrome, Stargardt disease etc (there is a nice review on this topic https://www.ncbi.nlm.nih.gov/pubmed/27173377)

Definition on macular dots: Yellow, white or greyish lesions in the macula that are well-defined/distinct, individual and mostly uniform in size

Definition of retinal dots: Yellow, white or greyish lesions in the retina that are well-defined/distinct, individual and mostly uniform in size

**Comment by pnrobinson** [comment]
added terms
