### ISSUE TITLE
NTR: subretinal fluid & intraretinal fluid

### ISSUE THREAD

**Issue by psergouniotis** [obophenotype/human-phenotype-ontology#2413]
>1A. Preferred term label: Subretinal fluid
>2A. Synonym: Sub-retinal fluid
>3A. Textual definition: oedema/fluid accumulating between the retinal pigment epithelium and Bruch's membrane.
>4A. Suggested parent term: Abnormality of the retina (HP:0000479)

>1B. Preferred term label: Intraretinal fluid
>2B. Synonym: Intra-retinal fluid
>3B. Textual definition: oedema/fluid accumulating within the retinal layers. 
>4B. Suggested parent term: Abnormality of the retina (HP:0000479)

> As per discussion with KK. I think that it would be more accurate if the relevant OCT terms would be used instead (e.g. subretinal hyporeflective spaces on macular OCT [HP:003062]) but I appreciate that many clinicians use these terms routinely.

**Comment by pnrobinson** [comment]
Are these terms then actually synonyms to OCT terms? We do not want to have different terms in the HPO that are actually synonyms. We can also add a link from an OCT term to the Abn. of the retina class, if that would be approrpriate.

**Comment by psergouniotis** [comment]
Thank you for the comment. No they are not synonymous to OCT terms. To diagnose these features, OCT is often but not always required (ie one could suspect them just by slit lamp examination). Please let me know if you would like any additional information. Many thanks. P
