### ISSUE TITLE
amending HPO tree for cone dysfunction syndrome (HP:0030637) 

### ISSUE THREAD

**Issue by psergouniotis** [obophenotype/human-phenotype-ontology#2414]
Please consider adding cone dysfunction syndrome (HP:0030637) as a subclass of "abnormality of the retina (HP:0000479)".

**Comment by pnrobinson** [comment]
We are trying to separate structural and functional abnormalities. Also, we are trying to not have "diseases" be used as phenotype terms. It would be better, maybe, to add a class called Abnormal retinal function, and then to rename this class simply Cone dysfunction. There could then be subclasses for the individual types of cone dysfunction??

**Comment by psergouniotis** [comment]
Thank you for the response. I know that terms including the word "syndrome" are not ideal, but as previously discussed in #1399, CDS is a widely used term that, in ophthalmic practice, reflects a specific phenotype.

It makes sense keeping structural and functional abnormalities separately but this will not be always accurate/possible. For example in CDS there is dysfunction (predominantly) but also a degree of degeneration. 

I do not have very strong feelings and if you prefer please leave it as it is. However, we are regularly using this phenotype to described the ocular presentation in our patients and not having it under "abnormality of the retina" creates some issues with Exomiser-type analysis. Many thanks

**Comment by pnrobinson** [comment]
We are going to have "Abnormal retinal morphology" and have a separate section for "Abnormal retinal physiology, and both will be children of  Abnormality of the retina,so Exomiser type groupings should still work actually.
