### ISSUE TITLE
  New term: Increased exhaustion markers on T cells

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#2416]
http://www.nature.com/ni/journal/v12/n6/full/ni.2035.html?wt.ec_id=ni-201106

**Comment by pnrobinson** [comment]
Adding term 
HP_0031514
Label: Increased proportion of exhausted T cells
Def: An abnormally elevated proportion of exhausted T cells (Tex) among circulating T cells. T cell exhaustion is a distinct differentiation state that can be distinguished from naive, effector, and memory T cells. Compared to effector (TE) and memory (TMEM) T cells, exhausted T cells (TEX) display impaired effector functions (e.g., rapid production of effector cytokines, cytotoxicity). TEX have limited proliferative potential, especially compared to some subsets of TMEM and naive T cells.
ref: PMID:26544946
