### ISSUE TITLE
All of 'flow' should be under cellular immunodeficieincy or linked to count abnormalities

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#2418]
All of flow should be under cellular immunodeficieincy or linked to count abnormalities

http://cvi.asm.org/content/23/4/254.full
![screen shot 2017-06-14 at 4 09 31 pm](https://user-images.githubusercontent.com/26067008/27303195-f6a1b81e-5507-11e7-913a-513e300252c3.png)

**Comment by nicolevasilevsky** [comment]
write in comments that the measure can be measured by flow cytometry

**Comment by nicolevasilevsky** [comment]
add a comment to this term re: flow cytometry:
HP_0002853 Increased proportion of HLA DR+ and CD57+ T cells

**Comment by pnrobinson** [comment]
This will be incorporated in the new design patterns for immune cell proportions.
