### ISSUE TITLE
Make 'combined immunodeficiency' a child of 'Cellular immunodeficiency'

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#2419]
Cellular immunodeficiency should be the label: combined should be a child of Cellular immunodeficience (HP_0005387)

**Comment by pnrobinson** [comment]
I think actually that it makes more sense to leave the current structure
-cellular
-humoral
-combined
since these are clinically not subtypes of each other but distinct manifestations.
