### ISSUE TITLE
New term: Cellular radiosensitivity

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#2422]
Parent term suggested 'combined immunodeficiency'HP:0005387.

Not sure this is the appropriate place

**Comment by pnrobinson** [comment]
@LCCarmody This is probably related to the existing term Chromosomal breakage, **HP_0040012**. Let's discuss this.

**Comment by pnrobinson** [comment]
I think this is a synonym of the existing term Chromosomal breakage induced by ionizing radiation. I am adding the synonym "INCREASED" Cellular radiosensitivity
