### ISSUE TITLE
New terms: Opportunistic infection (viral, fungal, parasite, etc.)

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#2424]
Opportunistic infection
1. severe viral infection
a. CMV
b. EBV
c. Adenovirus
d. Parainfluenza
2. Disseminated viral infection
a. Disseminated viral infection to live vaccine
3. local BCG infection
4. Disseminated BCG infection
5. Fungal infection
6. Disseminated cryptosporidial infection
7. Invasive parasitic infection

**Comment by nicolevasilevsky** [comment]
parent: HP_0010978 Abnormality of immune system physiology

**Comment by pnrobinson** [comment]
This parent term sounds correct!

**Comment by pnrobinson** [comment]
Adding these terms.
