### ISSUE TITLE
NTR bone loss around teeth

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#2427]
>If this is a request for a new term, please provide us with the folloing information (c.f., https://github.com/obophenotype/human-phenotype-ontology/wiki/How-to-make-a-good-term-request).

>1. Preferred term label (e.g., Asplenia)_
Alveolar bone loss around teeth

>2. Synonyms (e.g., Absent spleen)
Bone loss around teeth

>3. Textual definition (the definition should be understandable even for non-specialists. Include a PubMed ID to refer to any relevant article that provides additional information about the suggested term).

>4. Suggested parent term (Please look in the hierarchy of the HPO using the [HPO Browser](http://compbio.charite.de/hpoweb/showterm?id=HP:0000118) or other browsers such as [OLS](http://www.ebi.ac.uk/ols/ontologies/hp) and find the place in the HPO where the new term best fits)
HP_0000164 Abnormality of the teeth

>5. If you know of a disease that is characterized by this feature, please indicate it (e.g., by its Orphanet or OMIM id), and we will add the annotation to our database.

>6. If you would like a nanoattribution, please indicate your ORCID id or provide a label such as HPO:probinson (organization, first initial-last name)

**Comment by drseb** [comment]
I think this shouldn't be abnormality of the teeth. I read that alveolar bone is that part of the jaws that forms and supports the tooth, so I think this should be under "bone of jaw" or something. @pnrobinson or @markengelstad to advise

**Comment by pnrobinson** [comment]
@markengelstad  -- I would think that this belongs somewhere in the alveolar hierarchy?

**Comment by nicolevasilevsky** [comment]
I am talking to @markengelstad right now, we agree :)
should be abnormality of bone, not teeth

issue is with attachment of tooth to the bone, not the bone itself. Should have a periodontal attachment hierarchy, provides interface b/w tooth and bone

**Comment by markengelstad** [comment]
It actually belongs in the periodontium hierarchy. The parts of the
periodontium include the periodontal ligament, which connects to the
cementum of the tooth to the alveolar bone. So periodontium is neither
tooth nor bone, but something in between.

**Comment by nicolevasilevsky** [comment]
Currently there is not a hierarchy involving the periodontium, but there is HP_0000704 Periodontitis, which is a subclass of HP_0000164 Abnormality of the teeth

**Comment by nicolevasilevsky** [comment]
@markengelstad do you think we should create a new hierarchy for Abnormality of the periodontium and make 'Alveolar bone loss around teeth' a subclass?

Should Abnormality of the periodontium  be a subclass of HP_0000163 Abnormality of the oral cavity?
