### ISSUE TITLE
Cleft palate and Cleft secondary palate are inferred to be equivalent

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#2431]
@markengelstad We have two terms that are inferred to be equivalent:
HP_0000175 Cleft palate
HP_0410004 Cleft secondary palate

Should these be merged? Or should the logical definition of HP_0000175 Cleft palate be revised to include the hard and soft palate?

cc @drseb and @pnrobinson

**Comment by markengelstad** [comment]
For clinical usefulness of cleft palates, the phenotypes that would cover
almost all clinical instances are:


   - Cleft Alveolus  (this is technically a cleft primary palate)
   - Complete Cleft palate (This includes a cleft Alveolus, Hard, and soft
   palate, embryologically, this is a cleft primary and secondary palate)
   - Incomplete Cleft palate.  3 types
      - Cleft Alveolus and Hard palate
      - Cleft soft palate
      - Cleft uvula
