### ISSUE TITLE
NTR Labiopalatal cleft

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#2432]
@markengelstad does this seem like a reasonable term or should something else be used?

>1. Preferred term label (e.g., Asplenia)_
**Labiopalatal cleft**

>2. Synonyms (e.g., Absent spleen)

>3. Textual definition (the definition should be understandable even for non-specialists. Include a PubMed ID to refer to any relevant article that provides additional information about the suggested term).
**See: https://en.wikipedia.org/wiki/Cleft_lip_and_cleft_palate
Is this the same thing?**

>4. Suggested parent term (Please look in the hierarchy of the HPO using the [HPO Browser](http://compbio.charite.de/hpoweb/showterm?id=HP:0000118) or other browsers such as [OLS](http://www.ebi.ac.uk/ols/ontologies/hp) and find the place in the HPO where the new term best fits)
**HP_0000202 Oral cleft**

**Comment by pnrobinson** [comment]
@markengelstad @nicolevasilevsky  
It seems to be this is a "bundled" term and we should instead annotate with cleft lip and with cleft palate instead of having this term. So I would close this issue unless Mark says there is a reason to have the term.

**Comment by pnrobinson** [comment]
I am going to close this for now,then.
