### ISSUE TITLE
NTR: Abnormal distribution of CD56 bright/dim NK cells

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#2438]
**Preferred term label** 
Abnormal distribution of CD56 bright NK cells
Abnormal distribution of CD56 dim NK cells

**Suggested parent term** 
HP_0040089 (parent term needs a text def)

**Suggested def** 
An abnormal distribution in the number of CD56 bright NK cells, as measured by flow cytometry. CD56 the adhesion molecule mediating homotypic adhesion, and is used as a functional marker for NK cells.

An abnormal distribution in the number of CD56 dim NK cells, as measured by flow cytometry. CD56 the adhesion molecule mediating homotypic adhesion, and is used as a functional marker for NK cells.

**Comment**
The cytotoxic activity of CD56 dim NK cells is significantly higher than that of CD56 bright cells (the CD56bright CD16− population being the less cytotoxic)1,6 and they contain much more perforin, granzymes and cytolytic granules.

**dbxref**
PMID:19278419

**Comment by pnrobinson** [comment]
Adding term. After we have consulted with the immunologists, we probably should extend the proportions of various NK subsets. I added a reference and a comment to the parent term.
