### ISSUE TITLE
Increased CD25+ mast cells

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#2439]
**New term request:**
Increased CD25-positive mast cells
- Increased CD25-positive mast cells with associated KIT activating mutations

**Syn**
Increased CD25+ MCs
Increased CD25+ mast cells
- Increased CD25+ mast cells with associated KIT activating mutations
- Increased CD25+ MCs with associated KIT activating mutations

**text def**
An increased distribution in the number of CD25+ mast cells, as detected by immunolabeling methods. 

An increased distribution in the number of CD25+ mast cells with KIT activating mutations, as detected by immunolabeling methods. 

**Parent:** HP_0100494

**dbxref**
PMID:20616612

**Comment**
Aberrant CD2 and/or CD25 expression on mast cells provides one minor criterion for a diagnosis of systemic mastocytosis.

**CL:**
Mast cell
http://purl.obolibrary.org/obo/CL_0000097

The [notes](https://docs.google.com/document/d/1VWEj0z-bleRoiw5j25jTHYPIIwFF9RvkpjcR3nVfH_U/edit) said:
Mast cells: aggregates of mast cells; CD25+ MC, Kit+ cells.

**Comment by cmungall** [comment]
This is a straightforward filling in slots in a design pattern request yep? What's the CL ID?

**Comment by pnrobinson** [comment]
@nicolevasilevsky  @cmungall I do not think we should make "associated KIT activating mutations" part of the term definition!

**Comment by pnrobinson** [comment]
Adding as  HP_0031408
label:Increased CD25+ mast cell proportion
Def:An increased proportion of mast cells are positive for the cell surface marker CD25 (also called interleukin-2 receptor alpha chain).
Comment:Mast cells do not normally express CD25, but neoplastic mast cells may be CD25-positive.
