### ISSUE TITLE
IRF8 deficient dendritic cells

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#2441]
**Preferred term label**
IRF8 deficient dendritic cells

**parent**
HP_0001881 Abnormality of leukocytes

**synonym:**
IRF8 deficient DCs

**text def**
Dendritic cells that are deficient for the transcription factor, interferon regulatory factor, IRF8.

**dbxref**
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3136554/

**CL ID:
CL_0000451 dendritic cell

Notes:
The [immunology workshop notes](https://docs.google.com/document/d/1VWEj0z-bleRoiw5j25jTHYPIIwFF9RvkpjcR3nVfH_U/edit) requested:  IRF8--lacking dendritic cells in tissue

**Comment by pnrobinson** [comment]
I do not think this is a good term. The authors found mutations in the IRF8 gene in a type of immunodeficiency, thus, this is a genetic finding and not a phenotype.
