### ISSUE TITLE
NTR: MHC class II deficiency

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#2442]
**Preferred term label**
MHC class II deficiency 

**Synonyms**
Major histocompatibility complex class II deficiency

**Textual definition**
A lack of human leukocyte major histocompatibility complex class II gene expression in antigen, which causes an absence of cellular and humoral T-cell immune response to foreign antigens, and impaired antibody productions, resulting in extreme susceptibility to viral, bacterial and fungal infections.

**dbxref**
https://www.ncbi.nlm.nih.gov/pubmed/9012922

**Suggested parent term**
HP_0004332 Abnormality of lymphocytes

**associated GO term**
GO_0042613 MHC class II protein complex

**Comment by pnrobinson** [comment]
Adding this as "Reduced MHC II surface expression" (deficiency sounds too much like a disease)
