### ISSUE TITLE
NTR: Markedly reduced in vitro proliferation to mitogen

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#2444]
HP_0025462 Abnormal cellular physiology
-**NTR**: abnormal cell proliferation
 **def**: Any abnormality in the multiplication or reproduction of cells, which results in the expansion of a cell population.
 **Source**: GO:0008283

HP_0010978 Abnormality of immune system physiology
--**NTR**: Abnormal lymphocyte proliferation 
 **def**: Any abnormality in the multiplication or reproduction of lymphocytes, which results in the expansion of a cell population.
 **Source**: GO:0008283

---**NTR**: Abnormal T cell proliferation 
 **def**: Any abnormality in the multiplication or reproduction of T cells, which results in the expansion of a cell population.
 **Source**: Nicole

---**NTR**: Abnormal B cell proliferation 
 **def**: Any abnormality in the multiplication or reproduction of B cells, which results in the expansion of a cell population.
 **Source**: Nicole

 --- **NTR**: Decreased lymphocyte proliferation in response to mitogen 
  **Syn**: Markedly reduced lymphocyte proliferation to mitogen
  **Def**: A decreased proliferative response of lymphocytes in vitro or in vivo, when stimulated with mitogens, such as phytohemagglutinin (PHA).
  **Source**: http://hosted.usf.edu/ecoimmunology/wp-content/uploads/2014/07/Lymphocyte-Proliferation-Assay-Protocol.pdf

 --- **NTR**: Decreased lymphocyte proliferation in response to anti-CD3
  **Syn**: Markedly reduced lymphocyte proliferation to anti-CD3
  **Def**: A decreased proliferative response of lymphocytes in vitro or in vivo, when stimulated with an anti-CD3 antibody against the T-cell co-receptor, CD3.
  **Source**: https://en.wikipedia.org/wiki/CD3_(immunology)

**Comment by pnrobinson** [comment]
Sorry, didnt see assignee,added these terms.

**Comment by nicolevasilevsky** [comment]
no problem, thanks for adding!
