### ISSUE TITLE
New term request: Impaired antigen-specific response and children

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#2447]
**New term**: Impaired antigen-specific response
**Parent** HP_0010978 Abnormality of immune system physiology
(or maybe it should be a subclass of HP_0002958 Immune dysregulation? @pnrobinson what do you think?)
**Broad Syn**: Impaired adaptive immune response
**Def** An impaired immune response mediated by cells expressing specific receptors for antigen produced through a somatic diversification process, and allowing for an enhanced secondary response to subsequent exposures to the same antigen (immunological memory).
**Logical Def**
'has part' some 
('decreased rate' and ('inheres in' some 'adaptive immune response') and ('has modifier' some abnormal))
**Source** ISBN:0781735149

**Child term:** Impaired pathogen-specific CD8 cytoxicity
**Syn** Pathogen-specific CD8 cytoxicity defects
**Def** Impaired response of CD8 T cells to pathogens. CD8 T cells direct the killing of a target cell through the release of granules containing cytotoxic mediators or through the engagement of death receptors.
**Source** PMID:11911826

**Child term:** Impaired antigen-specific T-cell proliferation
**Syn** Antigen-specific T cell proliferation defect
**Syn** Impaired Ag-specific T cell proliferation
**Syn** Impaired activated T cell proliferation
**Def** Impaired proliferation and expansion of a T cell population following activation by an antigenic stimulus. 
**Source** GO:0050798
**Related GO term** GO:0050798 activated T cell proliferation
Should be child of Abnormal lymphocyte proliferation too, see #2444

**Comment by pnrobinson** [comment]
I think that the appropriate label should be "Reduced antigen-specific T cell proliferation"

**Comment by pnrobinson** [comment]
Impaired adaptive immune response => also, I am going to add "cellular" here!

**Comment by pnrobinson** [comment]
Sorry, I think I misunderstood the proposed hierarchy here, and I have now implemented these tersm as suggested. Please check.
