### ISSUE TITLE
need definition for HP_0002958 Immune dysregulation

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#2448]
Need text def for HP_0002958 Immune dysregulation

**Suggested def:** An improperly functioning immune system, which could be either overactive or under-active.
**Source**https://epidemicanswers.org/epidemic/root-causes/immune-dysregulation/

I wonder how this term is different from HP_0010978 Abnormality of immune system physiology because the logical def for this term is:
'has part' some 
(functionality and ('inheres in' some 'immune system') and ('has modifier' some abnormal))

Maybe these two terms should be merged?

**Comment by pnrobinson** [comment]
The term "immune dysregulation" is extremely imprecise and probably we should try to replace it. However, it is not always use as a synonym for  "An improperly functioning immune system, which could be either overactive or under-active." As far as I can see, it is generally used to mean an overreactive immune system. 
This is a typical usage: " In many immune deficiencies, lymphocytes may be present but dysfunctional, allowing for the development of excessive autoreactivity and resultant autoimmune disease. " (see https://www.ncbi.nlm.nih.gov/pubmed/26233425).  Another usage from a book can be summarized as "Immune dysregulation is characterized by lymphoid proliferation, immune activation, and autoimmune/inflammatory complications".
Therefore,my suggested definition is:
Altered immune function characterized by lymphoid proliferation, immune activation, and excessive autoreactivity often leading to autoimmune/inflammatory complications.
