### ISSUE TITLE
parental redundancy (at least in hp-edit.owl)

### ISSUE THREAD

**Issue by jmcmurry** [obophenotype/human-phenotype-ontology#2449]
Each HP term (at least in hp-edit.owl) is represented with any immediate parents, but also with at least one grandparent. This is confusing as it isn't even necessarily all the grandparents implicated by the lattice.

https://raw.githubusercontent.com/obophenotype/human-phenotype-ontology/master/src/ontology/hp-edit.owl
eg.
````
# Class: <http://purl.obolibrary.org/obo/HP_0005508> (Monoclonal immunoglobulin M proteinemia)

AnnotationAssertion(Annotation(<http://www.geneontology.org/formats/oboInOwl#hasDbXref> "HPO:probinson"^^xsd:string) Annotation(<http://www.geneontology.org/formats/oboInOwl#hasDbXref> "PMID:25815903") <http://purl.obolibrary.org/obo/IAO_0000115> <http://purl.obolibrary.org/obo/HP_0005508> "Presence of a monoclonal immunoglobulin M protein in the serum."^^xsd:string)
AnnotationAssertion(<http://www.geneontology.org/formats/oboInOwl#hasDbXref> <http://purl.obolibrary.org/obo/HP_0005508> "MSH:D008258"^^xsd:string)
AnnotationAssertion(<http://www.geneontology.org/formats/oboInOwl#hasDbXref> <http://purl.obolibrary.org/obo/HP_0005508> "SNOMEDCT_US:190817009"^^xsd:string)
AnnotationAssertion(<http://www.geneontology.org/formats/oboInOwl#hasDbXref> <http://purl.obolibrary.org/obo/HP_0005508> "SNOMEDCT_US:190818004"^^xsd:string)
AnnotationAssertion(<http://www.geneontology.org/formats/oboInOwl#hasDbXref> <http://purl.obolibrary.org/obo/HP_0005508> "SNOMEDCT_US:35562000"^^xsd:string)
AnnotationAssertion(<http://www.geneontology.org/formats/oboInOwl#hasDbXref> <http://purl.obolibrary.org/obo/HP_0005508> "UMLS:C0024419"^^xsd:string)
AnnotationAssertion(<http://www.geneontology.org/formats/oboInOwl#hasOBONamespace> <http://purl.obolibrary.org/obo/HP_0005508> "human_phenotype"^^xsd:string)
AnnotationAssertion(<http://www.geneontology.org/formats/oboInOwl#hasRelatedSynonym> <http://purl.obolibrary.org/obo/HP_0005508> "Waldenstrom macroglobulinemia")
AnnotationAssertion(<http://www.geneontology.org/formats/oboInOwl#id> <http://purl.obolibrary.org/obo/HP_0005508> "HP:0005508"^^xsd:string)
AnnotationAssertion(rdfs:comment <http://purl.obolibrary.org/obo/HP_0005508> "This is a characteristic feature of Waldenstrom macroglobulinemia (WM), which is defined as a B-cell lymphoplasmacytic lymphoma, characterized by monoclonal immunoglobulin M protein in the serum and infiltration of bone marrow with lymphoplasmacytic cells."^^xsd:string)
AnnotationAssertion(rdfs:label <http://purl.obolibrary.org/obo/HP_0005508> "Monoclonal immunoglobulin M proteinemia"^^xsd:string)
SubClassOf(<http://purl.obolibrary.org/obo/HP_0005508> <http://purl.obolibrary.org/obo/HP_0005523>)
SubClassOf(<http://purl.obolibrary.org/obo/HP_0005508> <http://purl.obolibrary.org/obo/HP_0031047>)
````

**Comment by cmungall** [comment]
In general the only people looking at hp-edit.owl should be editors.. we should have a way of getting snapshots for people who need to do an analysis on the latest and greatest..

The redundancies should be filtered out at release time so consumers shouldn't see these. The redundancy is potentially confusing to editors (though this disappears in the inferred view, which is where editors *should* be living), so we can just have a sparql query that reports these.

**Comment by drseb** [comment]
I don't understand. I have a Travis test for redundant links. What is wrong here?

**Comment by cmungall** [comment]
Julie, did you mean to use this example? I don't see the redundancy.

Seb - this is about redundancy in the edit file. The travis job checks 
on the release candidate `java -jar src/jar/CheckRedundantLinks.jar 
src/ontology/hp.obo`. We would expect this not to have redundancy if 
robot is used correctly.

**Comment by drseb** [comment]
We still don't use robot, as nobody knows how to use it...

**Comment by drseb** [comment]
Can somebody tell exactly what the two redundant links are?

**Comment by cmungall** [comment]
I'll make a PR

**Comment by drseb** [comment]
Ok. I had a look and as I expected I can't confirm a redundant link. 

`Monoclonal immunoglobulin M proteinemia` **is_a** `Lymphoproliferative disorder` and
`Monoclonal immunoglobulin M proteinemia` **is_a** `Paraproteinemia`

`Lymphoproliferative disorder` **is_a**   `Hematological neoplasm` and
`Paraproteinemia` **is_a** ` Increased antibody level in blood`

I don't see any redundancy. Has this been fixed since this ticket was issued?
I will close for now. Please re-open if necessary.
