### ISSUE TITLE
NTR: Abnormal CD25 upregulation upon TCR activation

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#2451]
**Parent:** Abnormal T-cell activation HP_0410035
**Label:** Abnormal CD25 upregulation upon TCR activation
**Syn:**Abnormal IL2RA upregulation upon TCR activation
**Text def:** Any abnormality in the upregulation of CD25 on T cells after activation via the T cell receptor (TCR). Typically, CD25 is upregulated by day 2 following TCR ligation and CD25 expression remains high out to day 4-5 then starts to go down on day 7. 
**dbxref:** http://orcid.org/0000-0001-5208-3432, https://www.researchgate.net/post/what_is_the_relationship_between_CD25_and_CD69_in_T_cell_activation

**Child term:** Decreased CD25 upregulation upon TCR activation
**Syn:**Abnormal IL2RA upregulation upon TCR activation
**Syn:** Poor CD25 upregulation upon TCR activation
**Text def:** Decreased or impaired upregulation of CD25 on T cells after activation via the T cell receptor (TCR). Typically, CD25 is upregulated by day 2 following TCR ligation and CD25 expression remains high out to day 4-5 then starts to go down on day 7. 
**dbxref:** http://orcid.org/0000-0001-5208-3432, https://www.researchgate.net/post/what_is_the_relationship_between_CD25_and_CD69_in_T_cell_activation

**Comment by drseb** [comment]
But they probably do not measure the upregulation, but rather the levels of that entity, right?

**Comment by nicolevasilevsky** [comment]
Yeah, you are right, they are probably measuring the relative protein expression levels. We could use the labels:
Abnormal CD25 expression after TCR activation
Decreased CD25 expression after TCR activation

**Comment by pnrobinson** [comment]
I am not sure how often this kind of testis performed in the clinic,but I think you essentially are doing a time series and measuring the difference, so upregulation is not necessarily wrong. See for example https://www.researchgate.net/publication/49651993_IFN-g_Upregulates_Survivin_and_Ifi202_Expression_to_Induce_Survival_and_Proliferation_of_Tumor-Specific_T_Cells/figures?lo=1

**Comment by nicolevasilevsky** [comment]
Yeah, I think it's usually time point measurements of the relative protein expression using flow cytometry. 

Should the definition say something about the assay? Like:
Label: Abnormal CD25 upregulation upon TCR activation
Text def: Any abnormality in the upregulation of CD25 on T cells after activation via the T cell receptor (TCR) _as measured by an immuno-assay (or immunolabeling?)_. Typically, CD25 is upregulated by day 2 following TCR ligation and CD25 expression remains high out to day 4-5 then starts to go down on day 7.

this ticket is related to #2452

**Comment by pnrobinson** [comment]
The definition above seems correct. as measured by an immuno-assay seems good (general enough). Should we just start a subhierarchy for these terms under Abnormality of T cell physiology?
