### ISSUE TITLE
diplegia

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2464]
_**Please consider a new term for diplegia.
Observed in Encephalocraniocutaneous lipomatosis.
Super class:Paralysis??
"I propose the same super class for hemiplegia".**_

**Comment by pnrobinson** [comment]
I am not seeing diplegia in several references for Encephalocraniocutaneous lipomatosis. Where did this come from? Also, there is a term for spastic diplegia -- are you refering to a non-spastic diplegia, i.e., can you use the current term?

**Comment by pnrobinson** [comment]
@LOURGHI Can we close this issue?

**Comment by pnrobinson** [comment]
I will close this issue for now. Please open a new issue with more context if needed. If so, please describe how the new term is different from the existing terms.
