### ISSUE TITLE
Unsatisfiable classes using 'occurs in'

### ISSUE THREAD

**Issue by balhoff** [obophenotype/human-phenotype-ontology#2467]
Logical definitions for these classes all create a `quality` as the subject of `occurs in`. The domain for `occurs in` should be `occurrent` (quality is a `continuant`). These produce incoherencies when HPO is used with the complete RO:

* [x] Abnormal bone ossification
* [x] Abnormal calcification of the carpal bones
* [x] Abnormal enchondral ossification
* [x] Abnormal epiphyseal ossification
* [x] Abnormal foot bone ossification
* [x] Abnormal hand bone ossification
* [x] Abnormal humeral ossification
* [x] Abnormal metatarsal ossification
* [ ] Abnormal ossification involving the femoral head and neck
* [x] Abnormal ossification of the pubic bone
* [x] Abnormal ossification of the scaphoid
* [x] Abnormal ossification of the trapezium
* [x] Abnormal ossification of the trapezoid bone
* [x] Abnormal rib ossification
* [x] Abnormal sternal ossification
* [x] Abnormal tarsal ossification
* [x] Abnormal vertebral ossification
* [x] Abnormality of carpal bone ossification
* [x] Abnormality of chorioretinal pigmentation
* [x] Abnormality of mitochondrial metabolism
* [x] Abnormality of skin pigmentation
* [x] Abnormality of skull ossification
* [x] Abnormality of urine homeostasis
* [x] Absent ossification of calvaria
* [x] Absent ossification of capital femoral epiphysis
* [x] Absent ossification of cervical vertebral bodies
* [x] Absent ossification of the trapezium
* [x] Absent ossification of thoracic vertebral bodies
* [x] Absent vertebral body mineralization
* [x] Advanced ossification of carpal bones
* [x] Advanced ossification of the hand bones
* [x] Advanced ossification of the humeral epiphysis
* [x] Advanced tarsal ossification
* [x] Astrocytosis
* [x] Cartilaginous ossification of larynx
* [x] Cartilaginous ossification of nose
* [x] Chorioretinal hyperpigmentation
* [x] Chorioretinal hypopigmentation
* [x] Decreased calvarial ossification
* [x] Decreased corneal reflex
* [x] Decreased cranial base ossification
* [x] Decreased skull ossification
* [x] Deficient ossification of hand bones
* [x] Delayed calcaneal ossification
* [x] Delayed epiphyseal ossification
* [x] Delayed femoral head ossification
* [x] Delayed humeral epiphyseal ossification
* [x] Delayed ossification of carpal bones
* [x] Delayed ossification of the hand bones
* [x] Delayed ossification of the scaphoid
* [x] Delayed ossification of the trapezium
* [x] Delayed ossification of the trapezoid bone
* [x] Delayed patellar ossification
* [x] Delayed phalangeal epiphyseal ossification
* [x] Delayed proximal femoral epiphyseal ossification
* [x] Delayed talus ossification
* [x] Delayed tarsal ossification
* [x] Dysharmonic maturation of the hand bones
* [x] Early ossification of capital femoral epiphyses
* [x] Foveal hyperpigmentation
* [x] Foveal hypopigmentation
* [x] Hyperpigmentation of eyelids
* [x] Hyperpigmentation of the fundus
* [x] Hypopigmentation of hair
* [ ] Hypopigmentation of the skin
* [x] Increased serum iduronate sulfatase activity
* [x] Increased skull ossification
* [x] Irregular ossification at anterior rib ends
* [x] Irregular ossification of hand bones
* [x] Irregular ossification of humeral metaphyses
* [x] Irregular ossification of the humeral epiphyses
* [x] Irregular ossification of the radial metaphysis
* [x] Irregular tarsal ossification
* [x] Lip hyperpigmentation
* [x] Macular hyperpigmentation
* [x] Macular hypopigmentation
* [x] Nonossified fifth metatarsal
* [x] Periorbital hyperpigmentation
* [x] Pigmentation of the sclera
* [x] Poorly ossified cervical vertebrae
* [x] Poorly ossified vertebrae
* [x] Progressive sclerosis of skull base
* [x] Severe carpal ossification delay
* [x] Slow-growing nails
* [x] Stippled calcification of hand bones
* [x] Two carpal ossification centers present at birth

For most of these I think they can be fixed by moving the `occurs in` expression to intersect with the bearer of the quality, e.g. for `Abnormality of mitochondrial metabolism`:

```
'has part' some 
    (quality
     and ('occurs in' some mitochondrion)
     and ('inheres in' some 'metabolic process')
     and ('has modifier' some abnormal))
```

should become

```
'has part' some 
    (quality
     and ('inheres in' some ('metabolic process' and ('occurs in' some mitochondrion)))
     and ('has modifier' some abnormal))
```

Maybe there are candidates for patterns in here.

**Comment by drseb** [comment]
Do we have  a pattern that uses `occurs in`?

**Comment by drseb** [comment]
I think Cindy and I have suggested this here: https://docs.google.com/document/d/10NCd9jXGXA4BETSBxdbVGfDFM2w4gAIbY6vpm4ERTBo/edit#heading=h.h5xj1f25b6pn

**Comment by nicolevasilevsky** [comment]
I'm with @balhoff at ICBO, any objections if we go ahead and fix these logical definitions?

**Comment by pnrobinson** [comment]
go for it!

**Comment by nicolevasilevsky** [comment]
When I revise the logical definitions for HP_0005599 Hypopigmentation of hair and HP_0001010 Hypopigmentation of the skin, the classes become inferred to be equivalent with HP_0007513 Generalized hypopigmentation and HP_0001022 Albinism.

![image](https://user-images.githubusercontent.com/6722114/30432283-199205be-9959-11e7-8d15-032d534fa598.png)

![image](https://user-images.githubusercontent.com/6722114/30432296-2103c602-9959-11e7-85b4-5b61466e7a9e.png)

The explanations don't show me anything:
![image](https://user-images.githubusercontent.com/6722114/30432320-2ea70080-9959-11e7-907e-853d7fd4a473.png)

Not sure what is wrong!

**Comment by balhoff** [comment]
It's because these are asserted subclasses of 'Hypopigmentation of hair', but it is an inferred superclass of them.

**Comment by balhoff** [comment]
For some reason explanations don't seem to work when there are reciprocal subclasses.

**Comment by balhoff** [comment]
It doesn't seem like 'Albinism' should be a subclass of 'Hypopigmentation of hair'.

**Comment by nicolevasilevsky** [comment]
Thanks @balhoff! I agree- if I remove the asserted superclass 'albism' from ' hypopigmentation of hair' that fixes it!

**Comment by balhoff** [comment]
Then there is a problem that 'Albinism' is equivalent to 'Generalized hypopigmentation'. This is because A is subclass of GH, but they have the same logical definition with one addition in GH. So GH logical definition is subclass of A logical definition.

**Comment by nicolevasilevsky** [comment]
Yes.

I think another issue is with the hiearchy: 'Generalized albinism' and 'Albinism' are a subclass of 'hypopigmentation of the skin', but the logical definition for 'hypopigmentation of the skin' occurs in the skin of body and the 'generalized hypopigmentation' and 'albinism' occur in the 'multicellular organism'.

I think the classification of 'Generalized albinism' and 'Albinsim' are wrong, they shouldn't be subclasses of 'Hypopigmentation of the skin'. The text def for 'Albinism' is "An abnormal reduction in the amount of pigmentation (reduced or absent) of skin, hair and eye (iris and retina)."

![image](https://user-images.githubusercontent.com/6722114/30433442-5f6b0a42-995c-11e7-8e68-0e4d37a319b9.png)

**Comment by nicolevasilevsky** [comment]
I think 'Generalized hypopigmentation' and the subclass 'Albinism' should be a subclass of 'Phenotypic abnormality'; these terms don't seem to properly fit under the 'Abnormality of skin' hierarchy. Then if I fix the logical definition for 'Hypopigmentation of skin' to the logical definition below, then it will be inferred to be a subclass of 'Generalized hypopigmentation' and 'Albinism'.

@pnrobinson, what do you think?

**Comment by nicolevasilevsky** [comment]
For 'Abnormal ossification involving the femoral head and neck', can we write a logical definition for a term with two anatomical regions?

**Comment by nicolevasilevsky** [comment]
I think this logical def could potential work for 'Abnormal ossification involving the femoral head and neck':

'has part' some
(quality and ('inheres in' some (ossification and ('occurs in' some 'head of femur')))
and
(quality and ('inheres in' some (ossification and ('occurs in' some 'neck of femur')))
and ('has modifier' some abnormal)))

**Comment by pnrobinson** [comment]
This issue seems to have been resolved. I will close for now, reopen with the remaining two terms if still needed.
