### ISSUE TITLE
Presence of  hyaline material in the vessel walls 

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2468]
_**Please consider a new term for Presence of  hyaline material in the vessel walls .
Observed in Cutaneous collagenous vasculopathy.PMID:26955587.
Superclass:Vascular skin abnormality?? **_

**Comment by pnrobinson** [comment]
@LOURGHI 
I am wondering whether this is similar to hyaline arteriolosclerosis
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1888226/
It is unclear to me from the publication what types of vessels are affected. Can you comment?

**Comment by LOURGHI** [comment]
In fact,Cutaneous collagenous vasculopathy is defined in this publication as idiopathic telengiectasia nothing more,and on HPO the telengiectasias are classified under the cutaneous vascular abnormalities without precision,but in this article http://www.nejm.org/doi/full/10.1056/NEJMicm1408473#t= it seems to me  that it is the capillaries that are affected.

**Comment by pnrobinson** [comment]
I am unable to figure out exactly what this article is reporting about the phenotype. I would prefer not to put an imprecise or wrong term into the HPO. I think that the disease could be annotated with Luse bodies and teleangiectasia. The hyaline material might be partly collagen deposits.
