### ISSUE TITLE
collagen   abnormality

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2469]
_**Please consider a new term for collagen   abnormality.
Observed in Cutaneous collagenous vasculopathy
Electron microscopy reveals “Luse bodies” representing collagen fibers with abnormally long spaces between electron-dense bands.
Superclass:Abnormality of glycoprotein metabolism??**_

**Comment by pnrobinson** [comment]
I think that this is best placed as 
Abnormal cutaneous collagen fibril morphology (HP_0031512), which 'is-a' Abnormality of skin morphology
