### ISSUE TITLE
Agalactia

### ISSUE THREAD

**Issue by BrunOrpha** [obophenotype/human-phenotype-ontology#2473]
Please consider new term: Agalactia

Synonym: lactation incapacity

Textual definition : incapacity of breastfeeding

Reference: PMID 24842349 
https://www.ncbi.nlm.nih.gov/pubmed/24842349

Parent term: HP0010311

Present in Sheehan syndrome: ORPHA91355

>If this is a request for a new term, please provide us with the folloing information (c.f., https://github.com/obophenotype/human-phenotype-ontology/wiki/How-to-make-a-good-term-request).

>1. Preferred term label (e.g., Asplenia)_

>2. Synonyms (e.g., Absent spleen)

>3. Textual definition (the definition should be understandable even for non-specialists. Include a PubMed ID to refer to any relevant article that provides additional information about the suggested term).

>4. Suggested parent term (Please look in the hierarchy of the HPO using the [HPO Browser](http://compbio.charite.de/hpoweb/showterm?id=HP:0000118) or other browsers such as [OLS](http://www.ebi.ac.uk/ols/ontologies/hp) and find the place in the HPO where the new term best fits)

>5. If you know of a disease that is characterized by this feature, please indicate it (e.g., by its Orphanet or OMIM id), and we will add the annotation to our database.

>6. If you would like a nanoattribution, please indicate your ORCID id or provide a label such as HPO:probinson (organization, first initial-last name)

**Comment by pnrobinson** [comment]
Adding term as HP_0031109
def:Failure of secretion of milk following childbirth associated with an inability to breastfeed an infant.
