### ISSUE TITLE
New annotation property?

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#2474]
I suggest to add a new annotation property, such as "short label" or something like this. This would be primarly for the terms below "Phenotypic abnormality", such that it would be easier to automagically generate figures (e.g. the one for the lay-person paper), where instead of "Abnormality of the eye" or "Abnormality of blood and blood-forming tissues" one would have the "short label"  "eye" or "blood"?

Any thoughts? Good idea? No good idea?

**Comment by nicolevasilevsky** [comment]
Sounds good to me.

--
Nicole Vasilevsky, PhD 
Research Assistant Professor
Library, Oregon Health & Science University
vasilevs@ohsu.edu<mailto:vasilevs@ohsu.edu> 
503-806-6900 
skype: nicolevasilevsky

**Comment by pnrobinson** [comment]
I agree with the idea. Perhaps it is better to use "display label" because "short label" might not be easy to understand for others?

**Comment by drseb** [comment]
ok. I will take a first pass on this.

**Comment by pnrobinson** [comment]
OK -- I have added the "display label" as a new annotation property.
