### ISSUE TITLE
New term request

### ISSUE THREAD

**Issue by Joiedavis** [obophenotype/human-phenotype-ontology#2475]
1. Preferred term label : Twin to Twin transfusion syndrome

>2. Synonyms : Feto-Fetal transfusion syndrome

>3. Textual definition: As a result of sharing a single placenta, the blood supplies of monochorionic twin fetuses can become connected, so that they share blood circulation: although each fetus uses its own portion of the placenta, the connecting blood vessels within the placenta allow blood to pass from one twin to the other.Depending on the number, type and direction of the interconnecting blood vessels (anastomoses), blood can be transferred disproportionately from one twin (the "donor") to the other (the "recipient"). This state of transfusion causes the donor twin to have decreased blood volume, retarding the donor's development and growth. The blood volume of the recipient twin is increased, which can strain the fetus's heart and eventually lead to heart failure,

>4. Suggested parent term : Abnormal Prenatal develop or birth
Didn't see a daughter term related to vascular abnormalities

>5. If you know of a disease that is characterized by this feature, please indicate it (e.g., by its Orphanet or OMIM id), and we will add the annotation to our database.

Publication:  Cristina, Rossi (2009). "The Efficacy of Quintero Staging System to Assess Severity of Twin-Twin Transfusion Syndrome Treated with Laser Therapy: A Systematic Review with Meta-Analysis". American Journal of Perinatology.

**Comment by pnrobinson** [comment]
Hi Joie -- I would suggest we make the term label sumply "twin to twin transfusion" (no syndrome). The full syndrome is a disease that may presents with other features like oligohydramnios

**Comment by Joiedavis** [comment]
Thank you Dr Robinson,
I totally agree, I just kept seeing it everywhere in the literature as a syndrome.
I appreciate your coaching.
Joie


--
Joie Davis PPNP-BC, AGN-BC
Nurse Practitioner, Genetics
NIH/National Institute of Allergy and Infectious Disease
National Human Genome Research Institute
Contractor: Medical Computer Science
828 595 2486

**Comment by pnrobinson** [comment]
Thank you! I am adding the term as HP_0031110

**Comment by Joiedavis** [comment]
I desperately need to use it now but I guess the HPO updates don’t happen to often
Joie

**Comment by drseb** [comment]
Making a release right now
