### ISSUE TITLE
Term for flat warts seen in immunodeficient patients

### ISSUE THREAD

**Issue by andrewSharo** [obophenotype/human-phenotype-ontology#2477]
1. Preferred term label : Verruca plana

2. Synonyms: flat wart

3. Textual definition
Slightly raised wart 2-5 mm in diameter often associated with viral infections, commonly persistent in immunodeficient individuals.  

4. Suggested parent term:
id: HP:0200043
name: Verrucae

5. If you know of a disease that is characterized by this feature, please indicate it:
ORPHA:183660

6. If you would like a nanoattribution
HPO:ucbasharo

**Comment by nicolevasilevsky** [comment]
Did not close this ticket because we don't know what to do with the ORPHA ID, does this need to be added to the disease annotation file?

cc @krageth

**Comment by pnrobinson** [comment]
Put a request onto the hpo-annotations tracker. We can add it to the OMIM annotations, and suggest it to Orphanet.

**Comment by nicolevasilevsky** [comment]
Thanks @pnrobinson, I created a ticket in the annotation tracker, closing this ticket
