### ISSUE TITLE
More insomnia related terms

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#2478]
_nocturnal insomnia_ and _chronic sleep deprivation_

**Comment by pnrobinson** [comment]
chronic sleep deprivation doesn't sound like a phenotype to me -- it sounds like a process that is causing somebody to loose sleep, e.g., a bad job or whatever.
nocturnal insomnia is probably the default type of insomnia -- please do not make a new term without considering the definition and the differentia; it would be good to consult some literature about current classifications if we want to add more detail here.

**Comment by drseb** [comment]
These are descriptions used by OMIM. Just searching for a place to put these. I may start some local extra-mappings if it is too complicated to add them to HPO.

**Comment by cmungall** [comment]
I don't seem to have institutional access to any of the relevant reviews, but it seems fairly standard to split insomnia into early/middle/late, e.g.
https://www.ncbi.nlm.nih.gov/pubmed/20625372

We'd define these in terms of normal sleep phases; these could live in GO

      po GO:0022410 ! circadian sleep/wake cycle process
       is_a GO:0042746 ! circadian sleep/wake cycle, wakefulness
       is_a GO:0042747 ! circadian sleep/wake cycle, REM sleep
       is_a GO:0042748 ! circadian sleep/wake cycle, non-REM sleep
       is_a GO:0050802 ! circadian sleep/wake cycle, sleep
        po GO:0042747 ! circadian sleep/wake cycle, REM sleep
        po GO:0042748 ! circadian sleep/wake cycle, non-REM sleep
      po GO:0050802 ! circadian sleep/wake cycle, sleep
       po GO:0042747 ! circadian sleep/wake cycle, REM sleep
       po GO:0042748 ! circadian sleep/wake cycle, non-REM sleep

**Comment by nicolevasilevsky** [comment]
I have access to the paper, Seb, I'll email it to you.

**Comment by pnrobinson** [comment]
I found
Sleep onset Insomnia 
https://www.e-jsm.org/journal/view.php?number=97
Maintenance insomnia
The inability to stay asleep. People with maintenance insomnia wake up during the night and have difficulty returning to sleep.
Terminal/late insomnia when you can fall asleep easily soon after you go to bed… but then wake up too early in the morning. 

I will add these as terms. 
A lot of the other descriptinos of insomnia sound more like diseases to me (stressor insomnia etc).
