### ISSUE TITLE
Important: fix Myelomeningocele

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#2482]
What has happened here? How can this happen?

![screen shot 2017-07-13 at 13 11 20](https://user-images.githubusercontent.com/5172897/28163816-f0329ce6-67cc-11e7-89c9-e8c0977d10e7.png)

Related to https://github.com/monarch-initiative/HPO-UMLS-Integration/issues/40

**Comment by pnrobinson** [comment]
Just corrected this. My bad (I guess). Can we add a check for this, I thought that Travis already picked up this kind of issue.

**Comment by drseb** [comment]
Thanks for taking care of this issue.

> Can we add a check for this, I thought that Travis already picked up this kind of issue.

I had this test and IMHO you were the one who asked to remove it.

**Comment by pnrobinson** [comment]
Right...the test was for the length of the definition. Some definitions are long. We need a test for new terms that have a definition but not a label, I guess..

**Comment by drseb** [comment]
> Right...the test was for the length of the definition. Some definitions are long. 

No. The test was for synonyms. Now synonym-length is only checked if there is no definition.

> We need a test for new terms that have a definition but not a label, I guess..

Sounds good.
