### ISSUE TITLE
Fusion HP:0000047 & HP:0003244 ?

### ISSUE THREAD

**Issue by cruzjaime** [obophenotype/human-phenotype-ontology#2483]
I think both codes have the same meaning.

Thank's

Jaime Cruz
Pediatric Endocrinology
Hospital 12 de Octubre
Madrid - Spain

**Comment by drseb** [comment]
@pnrobinson should these be merged?

**Comment by pnrobinson** [comment]
HP:0000047 is Hypospadias (Displacement of the urethral opening on the ventral (inferior) surface of the penis) and HP:000324 is Penile hypospadias (Location of the urethral opening on the inferior aspect of the penis.)
The term Hypospadias is meant to be the parent term and its definition is incorrect and should be amended to
Abnormal position of urethral meatus on the ventral penile shaft (underside) characterized by displacement of the urethral meatus from the tip of the glans penis to the ventral surface of the penis, scrotum, or perineum.
We should add this pubmed id
https://www.ncbi.nlm.nih.gov/pubmed/21968448
Please note that there are many classification systems for hypospadias and the HPO should be providing terms that would allow any classification to be used.

**Comment by drseb** [comment]
Will you fix the def and close the issue or will you assign e.g. @nicolevasilevsky or @LCCarmody ?

**Comment by pnrobinson** [comment]
Corrected definition.
