### ISSUE TITLE
HP:0030338 'arborescence 

### ISSUE THREAD

**Issue by BrunOrpha** [obophenotype/human-phenotype-ontology#2487]
**Concerning this current classification:**
[http://www.ontobee.org/ontology/HP?iri=http://purl.obolibrary.org/obo/HP_0030338](url)
                                    Increased circulating gonadotropin level- 
                                    Impaired FSH and LH secretion+ 
                                    Decreased circulating gonadotropin level+ 
                                    Abnormal circulating luteinizing hormone level+ 
                                    Abnormal circulating follicle-stimulating hormone level

**Please consider a simpler versionning, such as:**
-Abnormal gonadotropins
--Abnormal FSH plasma level
-----Increased FSH plasma level
-----Descreased FSH plasma level

--Abnormal LH plasma level
-----Increased LH plasma level
-----Descreased LH plasma level

&(--Decreased Fsh AND Lh plasma level)?

**Comment by pnrobinson** [comment]
I have revised the structure of the term labels and the structure around this part of the HPO. The term "Impaired FSH and LH secretion" is not precise and is currently being used for https://www.omim.org/entry/308750 (a single report from 1986) and https://www.omim.org/entry/308700 (where the correct annotation should be low FSH and low LH (two terms). I think that we should obsolete the term Impaired FSH and LH secretion+

**Comment by pnrobinson** [comment]
The sole article upon which MIM:308750 is based states this "[The proband III-4's] plasma testosterone was 0.45 nmol/l (normal range 10-42), follicle stimulating hormone (FSH) was 0.42 IU/I (normal range 0.33-5.0) and luteinizing hormone (LH) 2.5 IU/l (normal range 3.2-23)." 
Proband III-1 has "low serum testosterone and gonadotrophins." (LH,FSH)

Therefore, for this disease I think we can annotate to the terms Decreased circulating (FH,LSH)

**Comment by pnrobinson** [comment]
I have revised the annotations of MIM:308700 and MIM:308750 and will obsolete the HPO term "Impaired FSH and LH secretion"
