### ISSUE TITLE
Create a new term for intractable seizures

### ISSUE THREAD

**Issue by lizbutler17** [obophenotype/human-phenotype-ontology#2488]
>If this is a request for a new term, please provide us with the folloiwng information (c.f., https://github.com/obophenotype/human-phenotype-ontology/wiki/How-to-make-a-good-term-request).

>1. Preferred term label (e.g., Asplenia)_
Drug-resistant epilepsy

>2. Synonyms (e.g., Absent spleen)
Intractable epilepsy
Refractory epilepsy
Pharmacoresistant epilepsy

>3. Textual definition (the definition should be understandable even for non-specialists. Include a PubMed ID to refer to any relevant article that provides additional information about the suggested term).

PMID: 19889013

Definition:  Drug-resistant epilepsy indicates that an individual has failed to become and stay seizure free with adequate trials of two seizure medications.  The medications should have been tolerated by the individual and must have been chosen appropriately given the person’s seizure type.  The seizure medications may be tried alone or in combination with other seizure medications.

>4. Suggested parent term (Please look in the hierarchy of the HPO using the [HPO Browser](http://compbio.charite.de/hpoweb/showterm?id=HP:0000118) or other browsers such as [OLS](http://www.ebi.ac.uk/ols/ontologies/hp) and find the place in the HPO where the new term best fits)

Parent term: Primary ID HP:0001250 (Seizures)

>5. If you know of a disease that is characterized by this feature, please indicate it (e.g., by its Orphanet or OMIM id), and we will add the annotation to our database.
OMIM:616645
ORPHA:2382
OMIM:607208
ORPHA:33069
OMIM:613721
OMIM:300088
ORPHA:31709
OMIM:614558
OMIM:254780
ORPHA:1947
OMIM:600143
OMIM:610003
ORPHA:199
OMIM:300590
ORPHA:777
OMIM:300673
OMIM:312750
ORPHA:3095
ORPHA:352582
OMIM:103050
ORPHA:46
ORPHA:31709
OMIM:614558
OMIM:614959
OMIM:615005
ORPHA:85278
OMIM:613454
OMIM:308350
OMIM:239300
ORPHA:98811
OMIM:606777
ORPHA:1942
OMIM:616421
OMIM:300352
ORPHA:52503
ORPHA:3006
OMIM:266100
OMIM:615744
ORPHA:33069
ORPHA:2382
ORPHA:2382
OMIM:615362
ORPHA:847
OMIM:301040
OMIM:613477
ORPHA:777
ORPHA:199
OMIM:616341
ORPHA:1935
OMIM:300672
OMIM:612164
OMIM:613722
OMIM:615473
ORPHA:569
OMIM:141500
ORPHA:308
OMIM:612437
OMIM:245570
OMIM:616139
OMIM:300894
ORPHA:3006
OMIM:613402
OMIM:191100
ORPHA:805
ORPHA:805
OMIM:613254
ORPHA:1942
ORPHA:2382
OMIM:615369
OMIM:105830
OMIM:204500
OMIM:204200
OMIM:256731
OMIM:610042
ORPHA:308
OMIM:254800
OMIM:604364
OMIM:610127
OMIM:616366
OMIM:616187
OMIM:601780
OMIM:204300
ORPHA:439218
OMIM:613720
OMIM:616346
OMIM:615760
ORPHA:31709
OMIM:616409
OMIM:609304
ORPHA:1935

>6. If you would like a nanoattribution, please indicate your ORCID id or provide a label such as HPO:probinson (organization, first initial-last name)

**Comment by pnrobinson** [comment]
The HPO is intended to be an ontology of phenotypic manifestations of disease. This term is kind of on the borderline between a disease (that has a time course, an etiology, and a collection of phenotypic features, as well as a response to treatment), and a phenotypic feature. But the main issue is that each of the subclasses of seizures can be intractable, and thus if we put in one new term for intractable seizires we do not know which is meant. I have added a new modifier term "intractable" to the HPO that can be used to modify any other clinical HPO term. I think this is the best way to go. Depending on what software you are using to enter data you should be able to just add this modifier.

**Comment by lizbutler17** [comment]
Thank you.  I think having it as a modifier is a good solution.  We are working on adding the ability to add modifiers, so moving forward we will be able to capture this.

Liz

____________________________________________________
Elizabeth Butler, MS, CGC
Director, Genetic Counseling Program |  GeneDx  |  www.genedx.com<http://www.genedx.com/>
Direct: 301-519-2100 x6205  |  E-mail: liz@genedx.com<mailto:liz@genedx.com>
