### ISSUE TITLE
NTR: Pregnancy exposure

### ISSUE THREAD

**Issue by krageth** [obophenotype/human-phenotype-ontology#2496]
>If this is a request for a new term, please provide us with the folloing information (c.f., https://github.com/obophenotype/human-phenotype-ontology/wiki/How-to-make-a-good-term-request).

>1. Preferred term label (e.g., Asplenia)_
**Pregnancy exposure**

>2. Synonyms (e.g., Absent spleen)
**Exposure during pregnancy**

>3. Textual definition (the definition should be understandable even for non-specialists. Include a PubMed ID to refer to any relevant article that provides additional information about the suggested term).
**Exposure of pregnant women to toxins from any source, such as environmental toxins or chemicals, that may potentially cause problems such as miscarriage, preterm delivery, low birth weight, and, in some cases, developmental delays in infants.**

>4. Suggested parent term (Please look in the hierarchy of the HPO using the [HPO Browser](http://compbio.charite.de/hpoweb/showterm?id=HP:0000118) or other browsers such as [OLS](http://www.ebi.ac.uk/ols/ontologies/hp) and find the place in the HPO where the new term best fits)
**Prenatal maternal abnormality HP_0002686**

>5. If you know of a disease that is characterized by this feature, please indicate it (e.g., by its Orphanet or OMIM id), and we will add the annotation to our database.

>6. If you would like a nanoattribution, please indicate your ORCID id or provide a label such as HPO:probinson (organization, first initial-last name)
0000-0002-6387-4317

Suggested: 
**Maternal teratogenic exposure HP_0011438 - Should be a subclass**

**Comment by pnrobinson** [comment]
Adding term as HP_0031437
