### ISSUE TITLE
Increased CSF lactate

### ISSUE THREAD

**Issue by jxchong** [obophenotype/human-phenotype-ontology#2501]
>1. Preferred term label (e.g., Asplenia)_

Existing term: http://compbio.charite.de/hpoweb/showterm?id=HP:0002490

>2. Synonyms (e.g., Absent spleen)

Add alternate synonym "Increased CSF lactate"

**Comment by pnrobinson** [comment]
I do not understand -- the term label is currently "Increased CSF lactate" so there is no need to add it as a synonym?

**Comment by jxchong** [comment]
Ack! My apologies. I looked at the synonym list and didn't see it there but somehow didn't look at the main term label.

**Comment by pnrobinson** [comment]
No worries and thanks for the feedback!
