### ISSUE TITLE
NTR: chest tightness

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#2506]
**1. Preferred term label**
chest tightness

**2. Synonyms:**
Tightness in chest

**3. Textual definition**
A discomforting sensation experienced between the upper abdomen and the neck that can occur at any age.
Source: http://www.belmarrahealth.com/tightness-chest-causes-symptoms/ 

**4. Suggested parent term**
HP_0000765 Abnormality of the thorax
(note- chest pain is classified under this parent)

**6. If you would like a nanoattribution, please indicate your ORCID id or provide a label such as HPO:probinson (organization, first initial-last name)**
http://orcid.org/0000-0001-5208-3432

Related to #1411

**Comment by pnrobinson** [comment]
I would suggest we put this under consitutional symptom.
