### ISSUE TITLE
NTR: Cough

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#2507]
**1. Preferred term label**
Chronic cough

**2. Synonyms**
Persistent cough

**3. Textual definition**
A cough that lasts for eight or more weeks.
Source: http://www.healthline.com/health/chronic-cough

**4. Suggested parent term**
HP_0012735 Cough

**6. If you would like a nanoattribution, please indicate your ORCID id or provide a label such as HPO:probinson (organization, first initial-last name)**
http://orcid.org/0000-0001-5208-3432

Related to #1411

**Comment by pnrobinson** [comment]
I have added a few more specific types of cough. I would think that it is better to use the HPO modifier terms for acute, subacute a and chronic rather than have explicit children tersm for this, because we would run into a combinatorial explosion.

**Comment by nicolevasilevsky** [comment]
sounds good!
