### ISSUE TITLE
NTR  solar retinopathy

### ISSUE THREAD

**Issue by cerivs** [obophenotype/human-phenotype-ontology#2509]
>If this is a request for a new term, please provide us with the following information (c.f., https://github.com/obophenotype/human-phenotype-ontology/wiki/How-to-make-a-good-term-request).

>1. Preferred term label (e.g., Asplenia)_

light induced retinopathy

>2. Synonyms (e.g., Absent spleen)

solar retinopathy (narrow)
photic retinopathy
laser pointer-induced maculopathy  (narrow)
laser pointer-induced retinopathy (narrow)
solar retinitis (narrow)

>3. Textual definition (the definition should be understandable even for non-specialists. Include a PubMed ID to refer to any relevant article that provides additional information about the suggested term).

Damage to the retinal by exposure to intense visible light, usually the sun.  Intense light exposure such as staring at the sun causes fine structural anomalies in the outer segments of the photoreceptors and the retinal pigment epithelium (RPE) cells of the macula.  Symptoms usually develop within 1–4 h after exposure and include decreased vision, metamorphopsia, micropsia, and central or paracentral scotomas. Fundus examination typically shows a small yellow spot with a surrounding gray zone in the foveolar or parafoveolar area. Spontaneous evolution leads to the improvement of visual acuity.
Solar retinopathy in human PMID:    25323644  https://doi.org/10.1016/j.optom.2013.12.006
in zebrafish PubMed:28616037  http://dx.doi.org/10.4103/1673-5374.206651
Pointer-Induced Maculopathy PMID:   28611647

>4. Suggested parent term 

probably a child of 
HP:0000580 Pigmentary retinopathy

>5.  DOID:11282

>6. If you would like a nanoattribution, please indicate your ORCID id or provide a label such as HPO:probinson (organization, first initial-last name)

ORCiD: 0000-0002-2244-7917 

________________________________
There are a couple ways to go on nomenclature and I'm not sure which medical practitioners would find most helpful. 
One would be make the term name  photic retinopathy with child terms solar retinopathy and  Laser Pointer-Induced Maculopathy based on cause of the retinal damage.
The second options is as in the NTR above making narrow synonyms of the light damage term, I am not sure which is most consistent with the HPO development patterns.

**Comment by pnrobinson** [comment]
Thanks for this suggestion! One issue is that the term seems to be referring to a disease that has its own set of phenotypes. I wonder if we could instead add a term for the "a small yellow spot with a surrounding gray zone in the foveolar or parafoveolar area." Is there a standard name for this in ophthalmology? The HPO does not cover diseases, (although admittedly there are some inconsistencies which we are trying to address), and it would be better to create a disease term for this entity and then create the necessary HPO terms.

**Comment by cerivs** [comment]
The "a small yellow spot with a surrounding gray zone in the foveolar or parafoveolar area." sounds good.  I'm coming at this from the zebrafish angle and am not sure exactly how to translate the damage in zebrafish to HPO terms.

**Comment by psergouniotis** [comment]
Although it would be nice to have this in HPO, strictly speaking it is indeed a diagnosis. 
I think it would be reasonable to leave this out (and add it in ORDO) given that "solar" suggests aetiology and that a relevant history of sun exposure is required before assigning this feature to an individual.

**Comment by pnrobinson** [comment]
Thanks! I am adding this as HP_0031420. I have added the items such as solar retinopathy as RELATED_SYNONYMs because they refer to diseases whose main feature is this term.
