### ISSUE TITLE
Primitive reflex sub ontology is not abnormal

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#2510]
I have a question regarding the above mentioned sub ontology. 

The classes of this part of HPO seem to not strictly refer to abnormal concepts, which is one of the hallmark features of the the sub ontology "Phenotypic **abnormality**". "Primitive reflex" however is asserted to be subclass of "Abnormality of movement". Can anyone clarify what is going on and what the reasoning behind this is?

@pnrobinson did you add these?

**Comment by pnrobinson** [comment]
The abnormality is the presence of a primitive reflex (which can be normal in a newborn, but is abnormal at other life stages) at the inappropriate time stage--this is an important clinical sign. We should add this as a comment. MDs will use the phrase primitive reflex as in this subhierarchy.

**Comment by pnrobinson** [comment]
I think that the definition already covers this. There is no clinical term that is used that is like 'Appearance of primitive reflexes at an inappropriate time point' and I think that clinicians will grok this as is.
