### ISSUE TITLE
review/add new terms from MPO Fyler

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#2511]
Review this spreadsheet and add new terms if the term does not already exist:
https://docs.google.com/spreadsheets/d/13sBAq55KesjYl32WHw0o_BBSEH1kPV082l_4cG04LGo/edit#gid=33920039

**Comment by pnrobinson** [comment]
@nicolevasilevsky I have added some comments but let's skype next week!

**Comment by theoriste** [comment]
Thank you for taking this on. Any movement on adding the fyler codes into HPO?

**Comment by pnrobinson** [comment]
I would estimate we are about half through the list of terms with Fyler codes. Is there a good external reference for the codes we could use to check for completeness?

**Comment by theoriste** [comment]
I can't find the original Fyler code set. I'm still looking. Maybe the MPO people can share their reference? 
Technically the cardiac Fyler codes are now derived into the IPCCC, the International Paediatric and
Congenital  Cardiac  Code.  This won't be all Fyler codes, just the cardiac sets. 
http://ipccc.net/download-the-ipccc/
In that link, after signing up, there are some choices there. The Diagnosis Short List is easiest to go through. That IPCCC harmonization might be another git issue.

**Comment by theoriste** [comment]
With the fyler code document attached above, hopefully it will be helpful!

**Comment by theoriste** [comment]
Here is a Fyler Code spreadsheet attached, as a source of Fyler Codes.
We may be starting to assign some of these to HPO terms ourselves.  Would it be useful to cross-reference efforts?

[FylerCodes_051211.xlsx](https://github.com/obophenotype/human-phenotype-ontology/files/1451065/FylerCodes_051211.xlsx)

**Comment by pnrobinson** [comment]
It would be very useful to cross-reference. Can we skype about this? Maybe send me an email at peter.robinson@jax.org to coordinate?

**Comment by mellybelly** [comment]
Sorry for the delayed response, @nicolevasilevsky was working on these, can you give us a status report? We are happy to take your assignments but lets not duplicate efforts. Thanks!

**Comment by theoriste** [comment]
We appreciate all the work you are doing! We have some projects underway that will benefit from Fyler->HPO and we're hoping to help rather than confuse the efforts already underway.  I'll email Peter and we can set up a Skype call with our group.

**Comment by nicolevasilevsky** [comment]
Hi, checking in about this. Looks like there are still some open tickets. What would be a good way to move this forward?

**Comment by pnrobinson** [comment]
I think we should probably go through these 1 by 1, since I think many already exist and or need some TLC. We are currently nearing completion of the first round of cardiology edits. Should we try to set up a meeting with @LCCarmody  and @nicolevasilevsky and me and whoever else would like to attend and discuss how to do these final edits?

**Comment by LCCarmody** [comment]
Hi, I was unaware of this list.  I recognize some of these terms in the HPO, but not all. I have been working off of this list for cardiology: https://docs.google.com/spreadsheets/d/1mefkmkJfGIyU2JzyxdSGRUTr04QUF03zzZI7024FKeg/edit?usp=sharing

I think it would be a good idea to set up a meeting.

**Comment by nicolevasilevsky** [comment]
@LCCarmody, I don't think you were ever looped in before. :)

I'll work on setting up a call to discuss.

**Comment by nicolevasilevsky** [comment]
@theoriste sorry for the delayed reply! I met with Peter and Leigh about this today.

Please see the spreadsheet [here](https://docs.google.com/spreadsheets/d/13sBAq55KesjYl32WHw0o_BBSEH1kPV082l_4cG04LGo/edit#gid=33920039). We have mapped about 90% of the MPO flyer codes to HPO terms (22 codes are not mapped, and 190 are mapped). Of these, there are 8 terms that were deemed unsuitable to add to the HPO (see corresponding ticket in column M.) There are 15 open tickets that are still under review (linked in column M as well.)

@theoriste I would be happy to set up a call if you'd like to discuss further or if you have any questions about the spreadsheet.

**Comment by nicolevasilevsky** [comment]
I am going to close this ticket, because there are individual tickets in this tracker for the open term requests and related ticket #2568 about the subset tag.
