### ISSUE TITLE
HPO browser is down

### ISSUE THREAD

**Issue by johntiger1** [obophenotype/human-phenotype-ontology#2519]
http://compbio.charite.de/hpoweb/showterm?id=HP:0000118 gives the following:

http://imgur.com/a/qtf4p

**Comment by pnrobinson** [comment]
We have been having some issues with the HPO server, that unfortunately may take up to 1-2 more weeks to address. Sorry for any inconvenience. I will close this issue when the server is back up.
-Peter

**Comment by pnrobinson** [comment]
Thanks to @drseb the HPO browser is "up" again!
