### ISSUE TITLE
increased body mass index

### ISSUE THREAD

**Issue by slaulederkind** [obophenotype/human-phenotype-ontology#2520]
>If this is a request for a new term, please provide us with the folloing information (c.f., https://github.com/obophenotype/human-phenotype-ontology/wiki/How-to-make-a-good-term-request).

>1. Preferred term label (e.g., Asplenia)_: increased body mass index

>2. Synonyms (e.g., Absent spleen): increased BMI

>3. Textual definition (the definition should be understandable even for non-specialists. Include a PubMed ID to refer to any relevant article that provides additional information about the suggested term).

Abnormally increased weight-to-height squared ratio, calculated by dividing the individual's weight in kilograms by the square of the individual's height in meters and used as an indicator of underweight compared to averages. PMID:17973940

>4. Suggested parent term (Please look in the hierarchy of the HPO using the [HPO Browser](http://compbio.charite.de/hpoweb/showterm?id=HP:0000118) or other browsers such as [OLS](http://www.ebi.ac.uk/ols/ontologies/hp) and find the place in the HPO where the new term best fits)

Abnormality of body mass index (HP:0045081)

>5. If you know of a disease that is characterized by this feature, please indicate it (e.g., by its Orphanet or OMIM id), and we will add the annotation to our database.

>6. If you would like a nanoattribution, please indicate your ORCID id or provide a label such as HPO:probinson (organization, first initial-last name):  RGD:sjwang

I believe that "Increased body weight" (HP:0004324) is incorrectly identified by definition and synonyms as being identical to "increased body mass index".

**Comment by pnrobinson** [comment]
Thank you for the close reading of these terms, I fully agree with you and have made the corresponding changes to HP:0004324. I added "Increased body mass index" as HP_0031418
