### ISSUE TITLE
Reduced sex -hormone binding protein level 

### ISSUE THREAD

**Issue by slaulederkind** [obophenotype/human-phenotype-ontology#2523]
>If this is a request for a new term, please provide us with the folloing information (c.f., https://github.com/obophenotype/human-phenotype-ontology/wiki/How-to-make-a-good-term-request).

>1. Preferred term label (e.g., Asplenia)_

Reduced sex-hormone binding protein level

>2. Synonyms (e.g., Absent spleen)

>3. Textual definition (the definition should be understandable even for non-specialists. Include a PubMed ID to refer to any relevant article that provides additional information about the suggested term).

A decreased blood concentration of sex-hormone binding protein. PMID:24078159

>4. Suggested parent term (Please look in the hierarchy of the HPO using the [HPO Browser](http://compbio.charite.de/hpoweb/showterm?id=HP:0000118) or other browsers such as [OLS](http://www.ebi.ac.uk/ols/ontologies/hp) and find the place in the HPO where the new term best fits)

"Abnormality of circulating protein level" HP:0010876

>5. If you know of a disease that is characterized by this feature, please indicate it (e.g., by its Orphanet or OMIM id), and we will add the annotation to our database.

>6. If you would like a nanoattribution, please indicate your ORCID id or provide a label such as HPO:probinson (organization, first initial-last name)

RGD:sjwang

**Comment by pnrobinson** [comment]
Added term as HP_0031419
