### ISSUE TITLE
fixing cobalamin/vitamin b12

### ISSUE THREAD

**Issue by nlwashington** [obophenotype/human-phenotype-ontology#2527]
When browsing around for Vitamin B12, i found the following terms:

http://purl.obolibrary.org/obo/HP_0040126
Abnormal serum cobalamin level

http://purl.obolibrary.org/obo/HP_0100502
vitamin B12 deficiency 

These terms are sisters, rather than hierarchical.  Why is that?  If it is incorrect to say that `vitamin B12 deficiency is_a abnormal serum cobalamin level`, then can you define `vitamin 12 deficiency` to make the difference more clear (there is no definition)?  Otherwise, can the organization be fixed so that 'abnormal serum cobalamin level' is a parent of 'vitamin B12 deficiency'?

In addition, there is no logical expression for vitamin B12 deficiency (say, mapping to cobalamin).  Can that be added?

**Comment by pnrobinson** [comment]
Good pickup. I have made the suggested changes and also changed the prefered label to Abnormal vitamin B12 level.
