### ISSUE TITLE
abnormal circulating beta-C-terminal telopeptide level

### ISSUE THREAD

**Issue by slaulederkind** [obophenotype/human-phenotype-ontology#2530]
>If this is a request for a new term, please provide us with the folloing information (c.f., https://github.com/obophenotype/human-phenotype-ontology/wiki/How-to-make-a-good-term-request).

>1. Preferred term label (e.g., Asplenia)_

abnormal circulating beta-C-terminal telopeptide level
increased circulating beta-C-terminal telopeptide level
decreased circulating beta-C-terminal telopeptide level

>2. Synonyms (e.g., Absent spleen)

abnormal circulating beta-CTx level
increased circulating beta-CTx level
decreased circulating beta-CTx level

>3. Textual definition (the definition should be understandable even for non-specialists. Include a PubMed ID to refer to any relevant article that provides additional information about the suggested term).

A deviation from the normal concentration of beta-C-terminal telopeptide in the blood circulation.
An elevated level of beta-C-terminal telopeptide in the blood.
A reduced level of beta-C-terminal telopeptide in the blood.

>4. Suggested parent term (Please look in the hierarchy of the HPO using the [HPO Browser](http://compbio.charite.de/hpoweb/showterm?id=HP:0000118) or other browsers such as [OLS](http://www.ebi.ac.uk/ols/ontologies/hp) and find the place in the HPO where the new term best fits)

Abnormality of circulating protein level (HP:0010876)

>5. If you know of a disease that is characterized by this feature, please indicate it (e.g., by its Orphanet or OMIM id), and we will add the annotation to our database.

>6. If you would like a nanoattribution, please indicate your ORCID id or provide a label such as HPO:probinson (organization, first initial-last name)

RGD:sjwang

**Comment by pnrobinson** [comment]
I am going to interpret this as 
https://www.ncbi.nlm.nih.gov/pubmed/15309383
C-terminal telopeptide of type I collagen

Def: A deviation from the normal concentration of beta-C-terminal telopeptide of type I collagen in the blood circulation, a marker of the rate of bone turnover.
