### ISSUE TITLE
three cortex abnormality term requests

### ISSUE THREAD

**Issue by slaulederkind** [obophenotype/human-phenotype-ontology#2531]
>If this is a request for a new term, please provide us with the folloing information (c.f., https://github.com/obophenotype/human-phenotype-ontology/wiki/How-to-make-a-good-term-request).

Preferred term label (e.g., Asplenia)_

1. Small superior frontal cortex
2. Abnormality of the cerebellar cortex
3. Small cerebellar cortex

Synonyms (e.g., Absent spleen)

2. Cerebellar cortex abnormalities; Cerebellar cortex abnormality; Cerebellar cortex anomaly; Cerebellar cortex anomalies

Textual definition (the definition should be understandable even for non-specialists. Include a PubMed ID to refer to any relevant article that provides additional information about the suggested term).

1. Reduced size of the superior frontal portion of the cerebral cortex.
2. An abnormality of the cerebellar cortex. 
3. Reduced size of the cerebellar cortex.

>4. Suggested parent term (Please look in the hierarchy of the HPO using the [HPO Browser](http://compbio.charite.de/hpoweb/showterm?id=HP:0000118) or other browsers such as [OLS](http://www.ebi.ac.uk/ols/ontologies/hp) and find the place in the HPO where the new term best fits)

1. "Small cerebral cortex” (HP:0002472)
2. "Abnormality of the cerebellum” (HP:0001317)
3. "Abnormality of the cerebellar cortex” (new term). 

>5. If you know of a disease that is characterized by this feature, please indicate it (e.g., by its Orphanet or OMIM id), and we will add the annotation to our database.

>6. If you would like a nanoattribution, please indicate your ORCID id or provide a label such as HPO:probinson (organization, first initial-last name)

RGD:gth

**Comment by pnrobinson** [comment]
Small superior frontal cortex=HP_0031421
Abnormality of the cerebellar cortex => I added Abnormal morphology of the cerebellar cortex, HP_0031422
Small cerebellar cortex:HP_0031423
