### ISSUE TITLE
 White matter appeared dark (reversed cortical ribbon sign) 

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2532]
See https://www.ncbi.nlm.nih.gov/pubmed/?term=22305531

**Comment by pnrobinson** [comment]
See also this: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2765171/

**Comment by LCCarmody** [comment]
Should we add all the terms in the second paper?  We have:
 Molar tooth sign on MRI HP:0002419
Moyamoya phenomenon HP:0011834
Eye of the tiger anomaly of globes pallid us HP:0002454 
at first glance, but others may be present as there seem to be several ways of naming the phenomenons.

**Comment by pnrobinson** [comment]
@LCCarmody I think we should add these terms. Can we talk next week?

**Comment by pnrobinson** [comment]
These are relatively tricky terms -- I have started to add a few.

**Comment by pnrobinson** [comment]
- [ ] Empty delta sign
- [ ] Dural tail sign
- [ ] 
- [ ] 
- [ ]

**Comment by pnrobinson** [comment]
added terms
