### ISSUE TITLE
Please review new terms: Atrioventricular septal defect

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#2533]
I revised the text defintion for HP_0006695 _Atrioventricular canal defect_ and added logical definition. The text def previously said 'A defect of the atrioventricular septum of the heart', but I think the atrioventricular septum and canal are different - these are different terms in [Uberon](http://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0005989) (and have different definitions.)

I removed  the synonyms from HP_0006695 _Atrioventricular canal defect_:
_Atrioventricular septal defect_
_Atrioventricular septal defect, partial_

I created the new terms HP_0410044 _Atrioventricular septal defect_ and HP_0410045 _Intermediate atrioventricular septal defect_ (per the [MPO_fyler_terms spreadsheet](https://docs.google.com/spreadsheets/d/13sBAq55KesjYl32WHw0o_BBSEH1kPV082l_4cG04LGo/edit#gid=33920039).)

**Comment by pnrobinson** [comment]
I do not think this is correct. There are various subtypes of Atrioventricular canal defect (which is a terminology that emphasizes the defect in the embryological development) but this is not distinct from AV septal defect (which is a terminology that emphasizes the result). See the pictures and commentaries here:
1. https://www.cdc.gov/ncbddd/heartdefects/avsd.html
2. http://www.heart.org/HEARTORG/Conditions/CongenitalHeartDefects/AboutCongenitalHeartDefects/Complete-Atrioventricular-Canal-defect-CAVC_UCM_307023_Article.jsp#.WcMWehdrzCI
@nicolevasilevsky  What sources are you following? Can we consult the EPCC on this?

**Comment by nicolevasilevsky** [comment]
Good thing I asked! :) I was just looking at Uberon, and this citation: 
https://www.ncbi.nlm.nih.gov/pubmed/12632326

Is it okay if I just delete the new classes I added (HP_0410044 _Atrioventricular septal defect_ and HP_0410045 _Intermediate atrioventricular septal defect_) and I can change the definition back and add back the synonyms to HP_0006695 _Atrioventricular canal defect_

Should the logical definition for HP_0006695 _Atrioventricular canal defect_ be:
'has part' some 
    (quality
     and ('inheres in part of' some 'atrioventricular septum')
     and ('has modifier' some abnormal))
?

**Comment by pnrobinson** [comment]
I would suggest deleting or obsoleting these classes and that we ask the Stanford group for authoritative help.
