### ISSUE TITLE
Abnormality of hemoglobin not always abnormality of erythrocytes

### ISSUE THREAD

**Issue by cmungall** [obophenotype/human-phenotype-ontology#2537]
HPO has a hidden GCI:

```
  % HP:0000118 ! Phenotypic abnormality
   % HP:0001871 ! Abnormality of blood and blood-forming tissues
    % HP:0001877 ! Abnormality of erythrocytes
     % HP:0011902 ! Abnormal hemoglobin * 
```

should this not be split into hemoglobin in `{RBC, dopaminergic cell, ...?}`, e.g.

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2732704/

**Comment by pnrobinson** [comment]
I think that for now this is an acceptable simplification -- clinically, abnormality of hemoglobin is only interesting with respect to RBCs, and being more precise would just be confusing to users. We should reconsider this if we want to annotate non-RBC phenotypes.
