### ISSUE TITLE
Revise label for HP_0003468	Abnormality of the vertebrae?

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#2539]
Should HP_0003468 Abnormality of the vertebrae be renamed to Abnormality of the vertebrae morphology?

See [MPO flyer spreadsheet](https://docs.google.com/spreadsheets/d/13sBAq55KesjYl32WHw0o_BBSEH1kPV082l_4cG04LGo/edit#gid=33920039)

However, some of the subclasses may not fit under morphology such as:
HP_0100569 Abnormal vertebral ossification
HP_0100861 Vertebral body sclerosis

**Comment by pnrobinson** [comment]
I think that the actual phenotypes of the latter two terms is an abnormal morphology that isa result of an abnormal process,but since we do not observe the process itself, they should probably be morph terms.
