### ISSUE TITLE
NTR: lymphangiectasis

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#2540]
Preferred term label
lymphangiectasis

Textual definition
Dilation of the lymphatic vessels, the basic process that may result in the formation of a lymphangioma
xref: MP:0004038

Suggested parent term 
HP_0100766
Abnormal lymphatic vessel morphology

Note- this term is in MPATH (MPATH_98)

**Comment by pnrobinson** [comment]
There are many terms with lymphangiectasia. These probably should be arranged in a subclass hierarchy. I think lymphangiectasia and lymphangiectasis are largely synonyms, but I am not sure if there are any differential connotations in some contexts. Definition is simply "dilatation of the lymphatic vessels."

**Comment by cmungall** [comment]
Should we have a design pattern for vascular ectasia: `has-part some (dilated and inheres-in some 'blood vessel')`

**Comment by pnrobinson** [comment]
lymphangiectasia and lymphangiectasis can be regarded as exact synonyms.

**Comment by pnrobinson** [comment]
Should we have a design pattern for vascular ectasia: has-part some (dilated and inheres-in some 'blood vessel')  => Yes

**Comment by pnrobinson** [comment]
@cmungall @drseb 
I added this def for this term (HP_0031842)
```
'has part' some 
    (dilated
     and ('inheres in' some 'lymphatic vessel')
     and ('has modifier' some abnormal))
```
How do we do this for the child terms, e.g., Hepatic lymphangiectasia ?

**Comment by nicolevasilevsky** [comment]
I'll add this design pattern to the upheno repo:
https://github.com/obophenotype/upheno/tree/master/src/patterns

**Comment by nicolevasilevsky** [comment]
I am a bit unsure about this design pattern - what should the label be?
Should it be "%s lymphangiectasia' - where %s is an anatomical location?

**Comment by pnrobinson** [comment]
I think all action items have been completed...closing this issue.
