### ISSUE TITLE
New term request: Abnormal cranium morphology

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#2541]
**Label:** Abnormal cranium morphology	
**Parent class ID:** HP_0000929	
**Parent label:** Abnormality of the skull	Suggested text def: Any structural anomaly of the upper portion of the skull that excludes the mandible (when present in the organism).	
**Synonym(s)**: Abnormal morphology of bones of cranium; Abnormal morphology of upper part of skull;  Abnormal upper part of skull shape (Layperson)	
**Logical def**: has part' some(morphology and ('inheres in' some cranium) and ('has modifier' some abnormal))	
**Text def xref**: UBERON:0003128

**Comment by pnrobinson** [comment]
Many of the terms for the skull need some revision; the labels should be made consisten with mrohpology. Structure skull, cranium, calvaria, basis etc correctly.
