### ISSUE TITLE
New term request: Left-sided isomerism

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#2542]
Label: Left-sided isomerism	
Parent class ID: HP_0030853	
Parent label: Heterotaxy	
Suggested text def: Anomaly in the asymmetry of the visceral paired organs (e.g. lungs) such that organs on the left and right side have the morphology normally seen on the left side of the body; this may also be associated with the presence of multiple spleens.	
Text def xref: MP:0000542

**Comment by pnrobinson** [comment]
Note isomerism is a synonym if heterotaxy. Several relevant terms exist.

**Comment by nicolevasilevsky** [comment]
See ref: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3116098/
assigning this myself, I will look into this further.
