### ISSUE TITLE
New term request: Abnormal ear morphology

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#2545]
Label: Abnormal ear morphology 

Parent class: HP_0000598 Abnormality of the ear
(some of the children could fit under abnormal ear morphology but not all of them)

Suggested text def: Any structural anomaly of any of the structures involved in the ear or vestibular system 

Logical def: has part' some(morphology and ('inheres in' some ear) and ('has modifier' some abnormal))

Text def xref: MP:0002102

**Comment by pnrobinson** [comment]
I have added morphology and physiology parent terms and done a little rearranging. We will need to take a deep dive on this though!
