### ISSUE TITLE
New term request: abnormal heart left atrium morphology

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#2553]
Label: abnormal heart left atrium morphology 

Parent class ID: HP_0005120 
Parent label: Abnormality of cardiac atrium 

Suggested text def: Any structural anomaly of the left upper chamber of the heart.
Text def xref: MP:0003923

Logical def: has part' some (morphology and ('inheres in' some 'left cardiac atrium') and ('has modifier' some abnormal))

**Comment by pnrobinson** [comment]
adding term and rearraning hierarchy of atrial abnormalities
