### ISSUE TITLE
NTR: dilated heart right atrium/dilated heart left atrium

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#2554]
parent: HP_0005120	Abnormality of cardiac atrium

new terms:
dilated heart right atrium
dilated heart left atrium

text def:
The luminal space of the right upper chamber of the heart is increased in volume or area, usually with an increase in contained fluid.

The luminal space of the left upper chamber of the heart is increased in volume or area, usually with an increase in contained fluid.

xrefs:
MP:0004062
MP:0004063

logical defs:
has part' some (dilated and ('inheres in' some 'right cardiac atrium') and ('has modifier' some abnormal))
has part' some (dilated and ('inheres in' some 'left cardiac atrium') and ('has modifier' some abnormal))

**Comment by pnrobinson** [comment]
@nicolevasilevsky  I do not understand what "heart right atrium" is, it does not sound right. I guess we mean simply "dilated right atrium" (of the heart)? I am guessing yes, and then we already have a term for this, HP_0030718. Right atrial enlargement, and I am adding dilated right atrium as a synonym.

**Comment by nicolevasilevsky** [comment]
Sounds good, thanks!
