### ISSUE TITLE
New term request: Abnormal sinus arrhythmia

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#2555]
Label: Abnormal sinus arrhythmia 

Parent class ID: HP_0011675 
Parent label: Arrhythmia 

Suggested text def: Any anomaly in the normal phenomenon of mild acceleration and slowing of the heart rate that occurs during the respiratory cycle. 
Text def xref: MP:0004122

Synonym(s): Abnormal respiratory sinus arrythmia 

See [MPO flyer spreadsheet](https://docs.google.com/spreadsheets/d/13sBAq55KesjYl32WHw0o_BBSEH1kPV082l_4cG04LGo/edit#gid=33920039)

**Comment by pnrobinson** [comment]
This term seems inaccurate, and it is not abnormal.
Sinus arrhythmia is a normal physiological phenomenon, most commnonly seen in young, healthy people. 
The HPO has several terms for sinus-node related arrhythmias
