### ISSUE TITLE
New term request: Abnormal inferior vena cava morphology

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#2557]
Label: Abnormal inferior vena cava morphology 

Parent class ID: HP_0005345 
Parent label: Abnormal vena cava morphology 

Suggested text def: Any structural anomaly of the principal vein draining blood from the lower portion of the body.
Text def xref: MP:0006063

Logical def: has part' some (morphology and ('inheres in' some 'posterior vena cava') and ('has modifier' some abnormal))

**Comment by pnrobinson** [comment]
done
