### ISSUE TITLE
New term request: Abnormal superior vena cava morphology 

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#2558]
Label: Abnormal superior vena cava morphology 

Parent class ID: HP_0005345 
Parent label: Abnormal vena cava morphology 

Suggested text def: Any structural anomaly of the principal vein draining blood from the upper portion of the body and delivering it to the right ventricle of the heart.
Text def xref: MP:0006064

Logical def: has part' some (morphology and ('inheres in' some 'anterior vena cava') and ('has modifier' some abnormal)) 

See [MPO flyer spreadsheet](https://docs.google.com/spreadsheets/d/13sBAq55KesjYl32WHw0o_BBSEH1kPV082l_4cG04LGo/edit#gid=33920039)

**Comment by pnrobinson** [comment]
done
