### ISSUE TITLE
New term request: Abnormal ascending aorta morphology

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#2560]
Label: Abnormal ascending aorta morphology 

Parent class ID: HP_0001679 
Parent label: Abnormal aortic morphology 

Suggested text def: Any structural anomaly of the portion of the aorta that arises from the base of the left ventricle and extends upward to the aortic arch and from which the coronary arteries arise. 
Text def xref: MP:0009867

Logical def: has part' some (morphology and ('inheres in' some 'descending aorta') and ('has modifier' some abnormal)) 

See [MPO flyer spreadsheet](https://docs.google.com/spreadsheets/d/13sBAq55KesjYl32WHw0o_BBSEH1kPV082l_4cG04LGo/edit#gid=33920039)

**Comment by pnrobinson** [comment]
added term
