### ISSUE TITLE
New term request: Absent coronary sinus

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#2561]
Label: Absent coronary sinus 

Parent class ID: HP_0011642 
Parent label: Abnormal coronary sinus morphology 

Suggested text def: Absence of the short trunk that recieves most of the cardiac veins carrying the blood from the myocardium and delivers it to the right atrium. 
ext def xref: MP:0010437

Logical def: has part' some (absent and ('inheres in' some 'coronary sinus') and ('has modifier' some abnormal)) 

See [MPO flyer spreadsheet](https://docs.google.com/spreadsheets/d/13sBAq55KesjYl32WHw0o_BBSEH1kPV082l_4cG04LGo/edit#gid=33920039)

**Comment by pnrobinson** [comment]
added term with definition.
