### ISSUE TITLE
New term request: Pulmonary vein stenosis

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#2562]
Label: Pulmonary vein stenosis 

Parent class ID: HP_0030968 
Parent label: Abnormal pulmonary vein morphology 

Suggested text def: An narrowing or constriction of the lumen of the pulmonary vein.
Text def xref: MP:0010438

Logical def: has part' some (constricted and ('inheres in' some 'pulmonary vein') and ('has modifier' some abnormal))

See [MPO flyer spreadsheet](https://docs.google.com/spreadsheets/d/13sBAq55KesjYl32WHw0o_BBSEH1kPV082l_4cG04LGo/edit#gid=33920039)

**Comment by pnrobinson** [comment]
@nicolevasilevsky  @drseb @cmungall @mellybelly There is a term Pulmonary venous occlusion, that is basically severe stenosis. I cannot find a PATO term for occluded, but should we be making this distinction?

**Comment by nicolevasilevsky** [comment]
Hi @pnrobinson- this term HP_0006518 has the label 'Pulmonary venous occlusion', did you want to change it to 'Pulmonary venous stenosis' (and make 'Pulmonary venous occlusion' a synonym)?

**Comment by pnrobinson** [comment]
yes, sorry, let's change to "...stenosis"
