### ISSUE TITLE
New term request: Heart left ventricle hypoplasia

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#2563]
Label: Heart left ventricle hypoplasia 

Parent class ID: HP_0001711 
Parent label: Abnormal morphology of the left ventricle 

Suggested text def: Underdevelopment or reduced size of the heart left ventricle, often due to a reduced number of cells. 
Text def xref: MP:0010446

 Logical def: has part' some (hypoplastic and ('inheres in' some 'heart left ventricle') and ('has modifier' some abnormal)) 

See [MPO flyer spreadsheet](https://docs.google.com/spreadsheets/d/13sBAq55KesjYl32WHw0o_BBSEH1kPV082l_4cG04LGo/edit#gid=33920039)

**Comment by pnrobinson** [comment]
The HPO has Hypoplastic left heart. We need to relate this to Left Ventricular Hypoplasia
See https://www.sciencedirect.com/science/article/pii/S0735109711024260

**Comment by pnrobinson** [comment]
I am adding "Left Ventricular Hypoplasia" as a synonym. I do not think that "Heart left ventricle hypoplasia" is very idiomatic, but I will also add it as a synonym
