### ISSUE TITLE
New term request: Heart left ventricle dilatation 

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#2564]
Label: Heart left ventricle dilatation  

Parent class ID: HP_0001711 
Parent label: Abnormal morphology of the left ventricle 

Suggested text def: Thinning, stretching and bulging of a weakened heart left ventricular wall. 
Text def xref: MP:0010447

Synonym(s): Left ventricular dilatation; Heart left ventricle aneurysm

See [MPO flyer spreadsheet](https://docs.google.com/spreadsheets/d/13sBAq55KesjYl32WHw0o_BBSEH1kPV082l_4cG04LGo/edit#gid=33920039)

@pnrobinson per your email to Matt, we should use dilatation for ventricles

**Comment by pnrobinson** [comment]
I do not think this is accurate, since left ventricular dilatation and aneurysm are not identical.
