### ISSUE TITLE
New term request: Heart left ventricle outflow tract stenosis

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#2565]
Label: Heart left ventricle outflow tract stenosis 

Parent class ID: HP_0011103 
Parent label: Abnormality of the left ventricular outflow tract 

Suggested text def: Abnormal constriction or narrowing of the portion of the left ventricle through which blood normally flows into the aorta 
Text def xref: MP:0010448

Logical def: has part' some (constricted and ('inheres in' some 'outflow part of left ventricle') and ('has modifier' some abnormal))

See [MPO flyer spreadsheet](https://docs.google.com/spreadsheets/d/13sBAq55KesjYl32WHw0o_BBSEH1kPV082l_4cG04LGo/edit#gid=33920039)

**Comment by pnrobinson** [comment]
The label is wrong, but I think we mean simply
Left Ventricular Outflow Obstruction
The main causes of this are
Subaortic Stenosis, Bicuspid Aortic Valve, Supravalvar Aortic Stenosis, and Coarctation of the Aorta

We need to consider whether this should be in physiology or in morphology
