### ISSUE TITLE
 New term request: Heart right ventricle outflow tract stenosis 

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#2566]
Label: Heart right ventricle outflow tract stenosis 

Parent class ID: HP_0001705 
Parent label: Right ventricular outlet obstruction 

Suggested text def: Abnormal constriction or narrowing of part of the anteriosuperior, smooth-walled portion of the cavity of the right ventricle, beginning at the supraventricular crest and terminating in the pulmonary trunk. 
Text def xref: MP:0010449

Logical def: has part' some (constricted and ('inheres in' some 'outflow part of right ventricle') and ('has modifier' some abnormal))

**Comment by pnrobinson** [comment]
This is HP_0001705.
