### ISSUE TITLE
New term request: Abnormal aortic arch branch attachment

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#2567]
Label: Abnormal aortic arch branch attachment

Parent class ID: HP_0011587 
Parent label: Abnormal branching pattern of the aortic arch 

Suggested text def: Any anomaly of the connection site of the aortic branches to the aortic arch, including the attachment sites for the left common carotid artery, the left subclavian artery, and the brachiocephalic trunk which further splits to form the right subclavian artery and the right common carotid artery. 
Text def xref: MP:0010464

**Comment by pnrobinson** [comment]
This was HP_0011587.
