### ISSUE TITLE
New term request: Ascending aorta hypoplasia

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#2569]
Label: Ascending aorta hypoplasia	

Parent class ID: HP_0001679	
Parent label: Abnormal aortic morphology	

Suggested text def: Underdevelopment or reduced size of the portion of the aorta that arises from the base of the left ventricle and extends upward to the aortic arch and from which the coronary arteries arise, usually due to reduced cell number.
Text def xref: MP:0010469

Logical def: has part' some hypoplastic and ('inheres in' some 'ascending aorta') and ('has modifier' some abnormal))	

See [MPO flyer spreadsheet](https://docs.google.com/spreadsheets/d/13sBAq55KesjYl32WHw0o_BBSEH1kPV082l_4cG04LGo/edit#gid=33920039)

**Comment by pnrobinson** [comment]
Note there is a current term, Hypoplastic arota, defined as Underdevelopment of a large segment of the thoracic and the abdominal aorta. We will need to arrange this in a new hierarchy

**Comment by pnrobinson** [comment]
adding as HP_0031935
