### ISSUE TITLE
New term request: Descending aorta hypoplasia	

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#2570]
Label: Descending aorta hypoplasia	

Parent class ID: HP_0001679	
Parent label: Abnormal aortic morphology	

Suggested text def: Underdevelopment or reduced size of the descending aorta, usually due to reduced cell number.
Text def xref: MP:0010474

Logical def: has part' some hypoplastic and ('inheres in' some 'descending aorta') and ('has modifier' some abnormal))	

See [MPO flyer spreadsheet](https://docs.google.com/spreadsheets/d/13sBAq55KesjYl32WHw0o_BBSEH1kPV082l_4cG04LGo/edit#gid=33920039)

**Comment by pnrobinson** [comment]
adding as HP_0031935.
