### ISSUE TITLE
New term request: Left ventricle to aorta tunnel	

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#2571]
Label: Left ventricle to aorta tunnel	

Parent class ID: HP_0001679	
Parent label: Abnormal aortic morphology	

Suggested text def: An abnormal communication between the left ventricle and the ascending aorta in addition to the aortic valve	
Text def xref: MP:0010481

See [MPO flyer spreadsheet](https://docs.google.com/spreadsheets/d/13sBAq55KesjYl32WHw0o_BBSEH1kPV082l_4cG04LGo/edit#gid=33920039)

**Comment by pnrobinson** [comment]
adding term for L and R.
