### ISSUE TITLE
New term request: Abnormal aortic valve cusp morphology and children

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#2573]
Label: Abnormal aortic valve cusp morphology	

Parent class ID: 
HP_0001654	Parent label: Abnormality of the heart valves	

Suggested text def: Any structural anomaly of the three fibrous triangular components and associated flap of the aortic valve.
Text def xref: MP:0010595

Logical def: has part' some (morphology and ('inheres in' some 'aortic valve cusp') and ('has modifier' some abnormal))	

-

New term request: Thick aortic valve cusps	

Suggested Parent: Abnormal aortic valve cusp morphology	

Suggested text def: An increase in the ratio of the aortic valve cusp thickness to the aortic wall thickness.
Text def xref: MP:0010593

-
New term request: Absent aortic valve cusps

Suggested Parent: Abnormal aortic valve cusp morphology

Suggested text def: Absence of the three fibrous triangular components and associated flaps of the aortic valve.
Text def xref: MP:0010597

Logical def: has part' some (absent and ('inheres in' some 'aortic valve cusp') and ('has modifier' some abnormal))

See [MPO flyer spreadsheet](https://docs.google.com/spreadsheets/d/13sBAq55KesjYl32WHw0o_BBSEH1kPV082l_4cG04LGo/edit#gid=33920039)

**Comment by pnrobinson** [comment]
I am adding the term above as Thickened aortic valve cusp -- there are cases when just one of the leaflets is thickened (thickened is also better than simply thick!)
see: https://www.ncbi.nlm.nih.gov/pubmed/9360334
