### ISSUE TITLE
New term request: Common atrioventricular valve	

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#2575]
Label: Common atrioventricular valve	

Parent class ID: HP_0006705	
Parent label: Abnormality of the atrioventricular valves	

Suggested text def: The presence of a single atrioventricular valve instead of both a mitral and tricuspid valve, most commonly due to incomplete or failure of fetal atrioventricular canal septation.	
Text def xref: MP:0010607

See [MPO flyer spreadsheet](https://docs.google.com/spreadsheets/d/13sBAq55KesjYl32WHw0o_BBSEH1kPV082l_4cG04LGo/edit#gid=33920039)

**Comment by pnrobinson** [comment]
I do not think we should have a separate term for this, since it is a component of Complete atrioventricular canal: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1459121/
In any case, it is not an abnormality "of" the atrioventricular valves (ie., of mitral and tricuspid).
