### ISSUE TITLE
New term request: Aorta pulmonary collateral arteries	

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#2576]
Label: Aorta pulmonary collateral arteries	

Parent class ID: HP_0001679	
Parent label: Abnormal aortic morphology	

Suggested text def: Small ectopic arteries or arterial branches that connect the aorta, aortic branches and/or subclavian artery regions directly to the lung parenchyma, usually seen in conjunction with pulmonary atresia, ventricular septal defect (VSD) and/or closed ductus arteriosus.	
Text def xref: MP:0010635

See [MPO flyer spreadsheet](https://docs.google.com/spreadsheets/d/13sBAq55KesjYl32WHw0o_BBSEH1kPV082l_4cG04LGo/edit#gid=33920039)

**Comment by pnrobinson** [comment]
I think the correct label for this should be aortopulmonary collateral arteries

**Comment by nicolevasilevsky** [comment]
sounds good! Are you okay with adding this term? I can do so.

**Comment by nicolevasilevsky** [comment]
it doesn't look like this term was added. Would you like to add it as aortopulmonary collateral arteries?
