### ISSUE TITLE
New term request: Bronchial situs inversus	

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#2578]
Label: Bronchial situs inversus	

Parent class ID: HP_0030853	
Parent label: Heterotaxy	

Suggested text def: Anomaly in the asymmetry of the bronchi of the lung such that these structures on both the left and right side have the morphology normally seen on the opposite side of the body.	
Text def xref: MP:0011251

See [MPO flyer spreadsheet](https://docs.google.com/spreadsheets/d/13sBAq55KesjYl32WHw0o_BBSEH1kPV082l_4cG04LGo/edit#gid=33920039)

**Comment by pnrobinson** [comment]
In human medicine, this is more commonly refered to as bronchial isomerism, e.g., 
https://www.ncbi.nlm.nih.gov/pubmed/24472332
