### ISSUE TITLE
New term request: Situs inversus with levocardia

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#2579]
Label: Situs inversus with levocardia	

Parent class ID: HP_0011534	
Parent label: Abnormal spatial orientation of the cardiac segments	

Suggested text def: Situs inversus of thoracic and abdominal viscera with the heart remaining normally situated on the left; usually associated with congenital cardiac abnormalities such as transposition of the great vessels and/or spleen defects including asplenia or polysplenia.	
Text def xref: MP:0011253

See [MPO flyer spreadsheet](https://docs.google.com/spreadsheets/d/13sBAq55KesjYl32WHw0o_BBSEH1kPV082l_4cG04LGo/edit#gid=33920039)

**Comment by pnrobinson** [comment]
This is HP_0031592
