### ISSUE TITLE
New term request: Superior-inferior ventricles	

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#2580]
Label: Superior-inferior ventricles	

Parent class ID: HP_0011534	
Parent label: Abnormal spatial orientation of the cardiac segments	

Suggested text def: An abnormality in which the heart ventricles are in a superior-inferior relationship due to abnormal displacement of the ventricular mass along the horizontal plane of its long axis; this frequently occurs together with criss-cross atrio-ventricular relationships.
Text def xref: MP:0011254

See [MPO flyer spreadsheet](https://docs.google.com/spreadsheets/d/13sBAq55KesjYl32WHw0o_BBSEH1kPV082l_4cG04LGo/edit#gid=33920039)

**Comment by pnrobinson** [comment]
See https://www.ncbi.nlm.nih.gov/pubmed/11789809

**Comment by pnrobinson** [comment]
This is HP_0011543
