### ISSUE TITLE
New term request: Enlarged inferior vena cava valve

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#2581]
Label: Enlarged inferior vena cava valve	

Parent class ID: HP_0001654	
Parent label: Abnormality of the heart valves	

Suggested text def: Increased size of the semicircular fold of endocardium located on the right atrium at the point of attachment of the inferior vena cava. 	
Text def xref: MP:0011571

See [MPO flyer spreadsheet](https://docs.google.com/spreadsheets/d/13sBAq55KesjYl32WHw0o_BBSEH1kPV082l_4cG04LGo/edit#gid=33920039)

**Comment by pnrobinson** [comment]
I do not think that the parentage is entirely correct, since this valve does not have a function in the normal adult organism, see
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC140300/
