### ISSUE TITLE
New term request: D-loop transposition of the great arteries	

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#2583]
Label: D-loop transposition of the great arteries
	
Parent class ID: HP_0001669	
Parent label: Transposition of the great arteries	

Suggested text def: Complete transposition of the great arteries; the d- refers to the dextroposition of the bulboventricular loop (ie, the position of the right ventricle, which is on the right side); in addition, the aorta also tends to be on the right and anterior, and the great arteries are parallel rather than crossing.	
Text def xref: MP:0011665

See [MPO flyer spreadsheet](https://docs.google.com/spreadsheets/d/13sBAq55KesjYl32WHw0o_BBSEH1kPV082l_4cG04LGo/edit#gid=33920039)

**Comment by pnrobinson** [comment]
This is Dextrotransposition of the great arteries. Adding as synonym
