### ISSUE TITLE
New term request: Double outlet right ventricle, ventricular defect committed to aorta	

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#2584]
Label: Double outlet right ventricle, ventricular defect committed to aorta	

Parent class ID: HP_0001719	
Parent label: Double outlet right ventricle	

Suggested text def: A form of DORV in which a ventricular septal defect is located just below the aorta; the left ventricular outflow is directed toward the aorta, resulting in aortic oxygen saturations that exceed pulmonary saturations; pulmonary stenosis is also often present.	
Text def xref: MP:0011666

See [MPO flyer spreadsheet](https://docs.google.com/spreadsheets/d/13sBAq55KesjYl32WHw0o_BBSEH1kPV082l_4cG04LGo/edit#gid=33920039)

**Comment by pnrobinson** [comment]
I think that the proper term is doubly commited, see https://www.texasheart.org/heart-health/heart-information-center/topics/double-outlet-right-ventricle/
We already have these terms.
