### ISSUE TITLE
New term request: Double outlet right ventricle with atrioventricular septal defect	

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#2585]
Label: Double outlet right ventricle with atrioventricular septal defect	

Parent class ID: HP_0001719	
Parent label: Double outlet right ventricle	

Suggested text def: A form of DORV in which there is also a complete atrioventricular canal.	
Text def xref: MP:0011667

See [MPO flyer spreadsheet](https://docs.google.com/spreadsheets/d/13sBAq55KesjYl32WHw0o_BBSEH1kPV082l_4cG04LGo/edit#gid=33920039)

**Comment by pnrobinson** [comment]
I think that this is a BUNDLED term and that it is better for users to annotate using one of the DORV terms plus the appropriate ASD term.
