### ISSUE TITLE
New term request: Double outlet right ventricle, Taussig bing type	

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#2586]
Label: Double outlet right ventricle, Taussig bing type	

Parent class ID: HP_0001719	
Parent label: Double outlet right ventricle	

Suggested text def: A form of DORV in which blood from the left ventricle passes through a ventricular septal defect to the pulmonary artery, and blood from the right ventricle is directed to the aorta.	
Text def xref: MP:0011668

See [MPO flyer spreadsheet](https://docs.google.com/spreadsheets/d/13sBAq55KesjYl32WHw0o_BBSEH1kPV082l_4cG04LGo/edit#gid=33920039)

**Comment by pnrobinson** [comment]
This seems to have the preferred label Taussig-Bing anomaly
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2801930/

**Comment by pnrobinson** [comment]
Actually, looking at this, I am not certain we should use the term Taussig Bing anomaly, which is not precisely defined in the literature. 
The original description of the Taussig-Bing anomaly has been broadened to include all kinds of double-outlet right ventricles with subpulmonary VSD.
There are currently numerous subterms of DORV that were generated at a previous cardiology workshop. I would close this item for now, and we can revisit it if necessary in a larger context.
