### ISSUE TITLE
New term request: Double aortic arch, balanced arches	

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#2587]
Label: Double aortic arch, balanced arches	

Parent class ID: HP_0011590	
Parent label: Double aortic arch	

Suggested text def: A defect in which the aortic arch splits into equally sized large left and right branches, encircling the trachea and esophagus, before becoming one tube to go to the lower body.	
Text def xref: MP:0011675

See [MPO flyer spreadsheet](https://docs.google.com/spreadsheets/d/13sBAq55KesjYl32WHw0o_BBSEH1kPV082l_4cG04LGo/edit#gid=33920039)

**Comment by pnrobinson** [comment]
I am using the prefered label Balanced double aortic arch, and the definition: A type of double aortic arch in which the two branches are of equal size. In most cases of double aortic arch, the right aortic arch is larger and located higher than the left aortic arch. PMID:22073330
