### ISSUE TITLE
New term request: Aortic arch obstruction	

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#2589]
New term request: Aortic arch obstruction	

Parent: HP_0012303	Abnormal aortic arch morphology	

Suggested text def: Any impediment or blockage causing a cessation or reversal of the normal flow of the blood through the aortic arch.		
Text def x-ref: MP:0011676

Logical def: 
has part' some (obstructed and ('inheres in' some 'arch of aorta') and ('has modifier' some abnormal))

See [MPO flyer spreadsheet](https://docs.google.com/spreadsheets/d/13sBAq55KesjYl32WHw0o_BBSEH1kPV082l_4cG04LGo/edit#gid=33920039)

**Comment by pnrobinson** [comment]
see #2588
