### ISSUE TITLE
Synonym Edit Request

### ISSUE THREAD

**Issue by krageth** [obophenotype/human-phenotype-ontology#2592]
>1. term label: HP_0007641 , Dyschromatopsia

>2. Synonyms:
Current Synonym: (Exact synonym) Colorblindness
Should be: (Exact Synonym) Color blindness

Tudor's free text mining tool is not currently picking it out of a free text field in  Sanford's Self-Phenotyping survey because of the spacing error so it is not being associating with an HPO term.

**Comment by pnrobinson** [comment]
fixed!
