### ISSUE TITLE
Consider importing/cross referencing the Radiology Gamuts Ontology (RGO)

### ISSUE THREAD

**Issue by mellybelly** [obophenotype/human-phenotype-ontology#2593]
https://academic.oup.com/jamia/article-lookup/doi/10.1093/jamia/ocv020
http://www.gamuts.net/
http://www.gamuts.net/dev/ for REST service

May also relate/be useful for interventions ontology work.

**Comment by pnrobinson** [comment]
This is a nice site, especially the way they use thumbnails to show some images linked to articles. The terms are not categorized in a way that is easily compatible with our systems (they mix many axes, but presumably are useful)


Peter Robinson

Professor of Computational Biology

The Jackson Laboratory for Genomic Medicine

10 Discovery Drive

Farmington, CT 06032

860.837.2095 t | 860.990.3130 m

peter.robinson@jax.org<mailto:peter.robinson@jax.org>

www.jax.org

Robinson lab: https://robinsongroup.github.io/

New Book: Computational Exome and Genome Analysis<https://www.crcpress.com/Computational-Exome-and-Genome-Analysis/Robinson-Piro-Jager/p/book/9781498775984>

The Jackson Laboratory: Leading the search for tomorrow's cures

________________________________
