### ISSUE TITLE
'Neoplasm by Site' is incorrectly subclass of 'Urinary System Neoplasm'

### ISSUE THREAD

**Issue by balhoff** [obophenotype/human-phenotype-ontology#2594]
There is an axiom in HP:

```
'Neoplasm by Site' (NCIT:C3263) SubClassOf 'Urinary System Neoplasm' (NCIT:C3431)
```

Not sure where this could have come from, since this is not in NCIT. It creates a cycle and infers equivalence between these.

**Comment by drseb** [comment]
It is indeed present in hp-edit.owl. @cmungall do you have any idea or do you know whom to ask? Can I delete this axiom?

**Comment by drseb** [comment]
@pnrobinson what do you think?

**Comment by pnrobinson** [comment]
This is clearly a mistake -- is it present in the original NCIT?
