### ISSUE TITLE
dolichoectasia

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2597]
_**Please consider a new term for dolichoectasia.
Observed in Internal carotid agenesis.PMID:27332518.
It was defined as an hypertrophy of vertebral and basilar arteries.
Superclass:Abnormality of the cerebral vasculature??**_

**Comment by pnrobinson** [comment]
I will add a term Vertebrobasilar dolichoectasia (VBD) 
-- defined as vascular abnormalities characterized by elongation, dilatation, and/or tortuosity of the vertebrobasilar segment

I do not think that the term dolichoectasia itself is specific enough.

**Comment by pnrobinson** [comment]
Adding term as HP_0020038
