### ISSUE TITLE
enlarged posterior communicating arteries

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2599]
_**Please consider a new term for enlarged posterior communicating arteries.
Observed in Internal carotid agenesis.PMID:27332518.
Superclass:Abnormality of circle of Willis??**_

**Comment by pnrobinson** [comment]
We need a term called
Abnormal posterior circulating artery morphology 
Child of Abnormality of circle of Willis (which should be renamed with ...morphology)
def: Any structural anomaly of the posterior circulating artery (PCOM). 
Comment: The posterior circulating artery (PCOM) forms the posterior portion of the circle of Willis, connecting the interior carotid artery (proximal to its bifurcation into the anterior cerebral artery and the 
middle cerebral artery) with the posterior cerebral artery.

Place the current term Hypoplastic posterior communicating artery under that.

**Comment by pnrobinson** [comment]
NTR:
Posterior communicating artery aneurysm
def: A widening (ballooning) localized in the wall of the posterior communicating artery.
comment: Posterior communicating artery aneurysm can leads to an acute palsy of the third cranial nerve with ipsilateral pupil dilation.

**Comment by pnrobinson** [comment]
NTR
Posterior communicating artery infundibulum
Def: A funnel-shaped symmetrical enlargement of the origin of the posterior communicating artery at its junction with the internal carotid artery. PMID:9848859 
Comment: PCOM infundibula are often considered as normal anatomical variants devoid of pathogenic significance, but have been noted to progress to aneurysms in some cases.

**Comment by pnrobinson** [comment]
@LOURGHI Sorry for the delay. I have added the three terms above. As far as I can see the only ways to get an enlarged Posterior communicating artery are the aneurysm or the infundibulum. I do not thing that the term "enlarged" is good though because it is ambiguous. Please reopen this item if you need a different kind of enlargement but then supply the definition please.
