### ISSUE TITLE
cerebral collateral circulation

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2600]
_**Please consider a new term for cerebral collateral circulation.
Observed in Internal carotid agenesis.PMID:27190916.
Superclass:Abnormality of the cerebral vasculature??**_

**Comment by pnrobinson** [comment]
The term "cerebral collateral circulation" is probably too general. What the article describes is a very specific type. Do you know of any good general classification system? The one presented in the paper seems to mix up many things.

**Comment by pnrobinson** [comment]
I will close this for now. There is one term that describes a particular kind of cerebral collateral circulation:
https://hpo.jax.org/app/browse/term/HP:0011834
