### ISSUE TITLE
abnormal origin of the right subclavian artery from the descending aorta

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2603]
_**Please consider a new term for abnormal origin of the right subclavian artery from the descending aorta.
Observed in Internal carotid agenesis.PMID:12601459.
Superclass:Abnormality of the systemic arterial tree??**_

**Comment by pnrobinson** [comment]
Adding as HP:0031632. Anomalous origin of the right subclavian artery from the descending aorta
