### ISSUE TITLE
New term request: sitting imbalance

### ISSUE THREAD

**Issue by mariatab** [obophenotype/human-phenotype-ontology#2605]
New term request: Sitting imbalance
PMID: 25461826
Parent: HP:0002172 Postural instability
Parent: HP:0002078 Truncal ataxia
HPO:mtaboada

**Comment by pnrobinson** [comment]
I would suggest annotating this to "Postural instability", since I do not think that sitting imbalance is really a separate phenotype. I have amplified the definition of Postural instability.
