### ISSUE TITLE
New term request: Astasia

### ISSUE THREAD

**Issue by mariatab** [obophenotype/human-phenotype-ontology#2606]
New term request: Astasia
Suggested text def: Astasia refers to the inability to stand upright unassisted
PMID: 25564268
Parent: Standing instability (New term)
HPO:mtaboada

**Comment by pnrobinson** [comment]
I think that this is a better definition of Astasia
Astasia is a clinical postural disorder characterized by the inability to stand without external support despite having sufficient muscle strength.  (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5088164/)

**Comment by pnrobinson** [comment]
I think that the best parent term is "Functional motor problem" (I am going to rename the latter "Functional motor deficit")

**Comment by pnrobinson** [comment]
Adding as HP_0020037
