### ISSUE TITLE
GARD feedback about Brachydactyly type B

### ISSUE THREAD

**Issue by GARDInfoCenter** [obophenotype/human-phenotype-ontology#2611]
GARD received an inquiry with feedback about brachydactyly type B asking us to change the first line in the HPO table from "middle" phalanx to "end" phalanx. The HPO table currently includes the following phenotypes (among others):

2nd-5th toe middle phalangeal hypoplasia 
Short distal phalanx of finger
Aplasia/Hypoplasia of the distal phalanges of the hand
Short middle phalanx of finger

Currently there is no mention of the phenotype affecting the distal toes, which according to our research appears to be present in brachydactyly type B (mentioned in both OMIM and OJRD). While there does also appear to be middle phalangeal hypoplasia of the toes, we thought perhaps it was misleading to this inquirer to have this listed as the first phenotype occurring very frequently. 

We thought this could be reviewed to determine whether the phenotype relating to the distal toes, as well as whether the frequencies of phenotypes might be reconsidered.

Thanks!
Michelle Snyder
GARD Operations Manager

**Comment by LOURGHI** [comment]
Thank you for the correction,
Please take a look at PMID:9973295.It may be necessary to review just  the frequency of the phenotype.

**Comment by pnrobinson** [comment]
I have also updated our frequency data for the distal phalanges of toes and fingers.
