### ISSUE TITLE
GARD Feedback about inclusion body myositis

### ISSUE THREAD

**Issue by GARDInfoCenter** [obophenotype/human-phenotype-ontology#2612]
GARD received this feedback:

"I was looking again at the GARD webpage on inclusion body myositis, and I found a mistake. Under "Symptoms", there is a table of "Signs and Symptoms", with the information provided by the Human Phenotype Ontology. The second to last entry is "Feeding difficulties in infancy", which is said to be "Frequent (present in 30% - 70% of cases)". This is incorrect. Inclusion body myositis does not affect infants or children. In fact, onset before the age of 40 is quite rare."

Based on our research we didn't see any reference in problems in infancy. Could you review?

Thanks,
Michelle Snyder
GARD Operations Manager

**Comment by LOURGHI** [comment]
Thank you for the correction,
it may be in the patient's medical history I will review the annotation and keep you informed.

**Comment by pnrobinson** [comment]
I agree that this is an adult-onset disease, see http://stm.sciencemag.org/content/8/331/331ra41.short.
It seems as if this has been corrected on the Orphanet website
https://www.orpha.net/consor/cgi-bin/Disease_Search.php?lng=EN&data_id=690&Disease_Disease_Search_diseaseGroup=inclusion-body-myositis&Disease_Disease_Search_diseaseType=Pat&Disease(s)/group%20of%20diseases=Inclusion-body-myositis&title=Inclusion-body-myositis&search=Disease_Search_Simple
