### ISSUE TITLE
Add layperson synonym for intermittent

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#2615]
Per the HPO layperson paper, there is a request to consider an even more lay friendly/plain language term for "intermittent" that might be used by patients, e.g. "occasional" "now and then")

**Comment by drseb** [comment]
not sure it is ok to post the manuscript publicly. ping @mellybelly

**Comment by nicolevasilevsky** [comment]
good point @drseb, I removed the link

**Comment by drseb** [comment]
ok. thanks
