### ISSUE TITLE
Add "Renal Neoplasm" as another parent for nephroblastoma HP:0002667

### ISSUE THREAD

**Issue by jmcmurry** [obophenotype/human-phenotype-ontology#2616]
An additional parent term seems appropriate for nephroblastoma (HP:0002667). Current parents include Embryonal neoplasm
Embryonal renal neoplasm
but not renal neoplasm (HP:0009726); unless there's a good reason for this omission, please add it.

**Comment by cmungall** [comment]
it's there, two hops up, not one:

```
    % HP:0009726 ! Renal neoplasm "The presence of a neoplasm of the kidney."
      % HP:0011794 ! Embryonal renal neoplasm "The presence of an embryonal neoplasm of the kidney that primarily affects children."
       % HP:0002667 ! Nephroblastoma *  "The presence of a nephroblastoma, which is a neoplasm of the kidney that primarily affects children."
```

**Comment by jmcmurry** [comment]
but this would imply that all nephroblastoma is embryonal in nature, whereas the description specifically says "usually" in children.

**Comment by cmungall** [comment]
Yes, the issue here is that the definition of embryonal neoplasm is not explicit. In fact it means a neoplasm resembling embryonic tissue, rather than a neoplasm of the embryo.

I believe also that Embryonal renal neoplasm should be made a subclass of Embryonal neoplasm, and the latter should have a text definition added. 

This is the current structure:

![image](https://user-images.githubusercontent.com/50745/31696797-943b9234-b368-11e7-8cf6-546fd41da9ef.png)

**Comment by cmungall** [comment]
FWIW, I think DO gets this wrong:

```
[Term]
id: DOID:688
name: embryonal cancer
namespace: disease_ontology
def: "A germ cell cancer that is associated with an embryo." [url:http://www.cancer.gov/dictionary/?CdrID=44250]
synonym: "embryo neoplasm" EXACT [CSP2005:2000-3997]
synonym: "embryonal neoplasm" EXACT [NCI2004_11_17:C3264]
xref: MESH:D009373
xref: NCI:C3264
xref: UMLS_CUI:C0027654
is_a: DOID:2994  ! germ cell cancer
```

The definition xref goes to a generic def of "embryonic"

We always use NCIT as our reference for cancer:
http://purl.obolibrary.org/obo/NCIT_C3264

*A usually malignant neoplasm composed of primitive (immature) tissues that resemble fetal tissues. Medulloblastoma, Ependymoblastoma, Pineoblastoma, and Wilms tumor are representative embryonal neoplasms.*

**Comment by cmungall** [comment]
Note also that NCIT calls nephroblastoma a kidney wilms tumor: http://purl.obolibrary.org/obo/NCIT_C40407

we have an outstanding PR that will solve all this #904

**Comment by pnrobinson** [comment]
DO's definition is completely wrong!
It is a mystery why the provide this xref: https://www.cancer.gov/publications/dictionaries/cancer-terms/?CdrID=44250, they should have xref'd this
https://www.cancer.gov/publications/dictionaries/cancer-terms?CdrID=367442

**Comment by pnrobinson** [comment]
I have added Embryonal renal neoplasm as a child of Embryonal neoplasm and this should correct the issue!
