### ISSUE TITLE
Review logical definition for Gout

### ISSUE THREAD

**Issue by balhoff** [obophenotype/human-phenotype-ontology#2617]
From @pnrobinson in #2614:

> Please do not make causally upstream of part of the definition. Note there is a disease entity gout but we are talking about gouty arthritis, the pheno feature! I thought the current definition was at least reasonable.

**Comment by pnrobinson** [comment]
This is the current definition
```
'has part' some 
    ('increased amount'
     and ('inheres in' some 
        ('uric acid'
         and ('part of' some blood)))
     and ('has modifier' some abnormal)
     and ('causes or contributes to condition' some 
        ('increased amount'
         and ('inheres in' some 
            (arthritis
             and ('occurs in' some 'skeletal joint'))))))
```

**Comment by pnrobinson** [comment]
Gout is a disease, and our term is referring to the major phenotypic feature of the disease, which is gouty arthritis. 
This webpage has great background information (http://www.arthritis.org/about-arthritis/types/gout/diagnosing.php):
Uric acid can form needle-like crystals in a joint and cause sudden, severe episodes of pain, tenderness, redness, warmth and swelling.
(...) the diagnosis of gouty arthritis can be confirmed by the finding of uric acid crystals in the joint fluid.

**Comment by pnrobinson** [comment]
We could defined this as

```
'has part' some 
    ('increased amount'
     and ('inheres in' some 
        ('uric acid'
         and ('part of' some 'skeletal joint')))
     and ('has modifier' some abnormal)
     and ('inflammatory'
         and ('inheres in' some 'skeletal joint')))
```
(where inflammatory is from PATO), or could modify the current pattern that uses MPATH, or could provide one definition for the HPO term Arthritis and then add appropriate differentia (in this case, I think the differentia should be  ('inheres in' some 
        ('uric acid'
         and ('part of' some 'skeletal joint')
.

**Comment by pnrobinson** [comment]
One problem with the above is that it does not specify that we are talking about the same skeletal joint.
@balhoff  ?

**Comment by pnrobinson** [comment]
Also, I would change the primary label to "Gouty arthritis" and add Gout as a related synonym (it is a disease).

**Comment by balhoff** [comment]
> One problem with the above is that it does not specify that we are talking about the same skeletal joint.

You could possibly do this:

```
'has part' some 
    ('increased amount'
     and ('inheres in' some 
        ('uric acid'
         and ('part of' some ('skeletal joint' and ('bearer of' some 'inflammatory')))))
     and ('has modifier' some abnormal))
```

That would be the same at the instance level, however ELK wouldn't see it that way since it doesn't know about inverse properties.

**Comment by drseb** [comment]
@balhoff I think we usually use GOs inflammation process, right?

**Comment by balhoff** [comment]
You're right, here is another candidate. I'm not sure of the best relation of the uric acid to the joint.

```
'has part' some 
    ('increased rate' and 
    ('inheres in' some ('inflammatory response' and 
        ('occurs in' some ('skeletal joint' and 
            ('has part' some ('uric acid' and ('bearer of' some 'increased amount))))))) and 
    ('has modifier' some abnormal))
```

Maybe we could add a relational quality to PATO like 'has increased amount of' and do `'skeletal joint and ('bearer of' some ('has increased amount of' and (towards some 'uric acid')))`

**Comment by pnrobinson** [comment]
I have replaced the previous definition with this one, and everything seems fine. Gout is now inferred as a child of Increased inflammatory response, which seems correct!

**Comment by matentzn** [comment]
The definition of gout changed again to this:

```
'has part' some 
    ('increased rate'
     and ('inheres in' some 
        ('inflammatory response'
         and ('occurs in' some 
            ('skeletal joint'
             and ('has part' some 
                ('increased amount'
                 and ('inheres in' some 'uric acid')))))))
     and ('has modifier' some abnormal))
```

Which is logically inconsistent;

I changed it back for the time being to:

```
'has part' some 
    ('increased rate'
     and ('inheres in' some 
        ('inflammatory response'
         and ('occurs in' some 
            ('skeletal joint')))) and ('has part' some 
                ('increased amount'
                 and ('inheres in' some 'uric acid')))
     and ('has modifier' some abnormal))
```

Which is much weaker and removes fact that increased amount of uric acid has to be in the skeletal joint (so now, gout is defined us an increased inflammatory response in the joints in conjunction with increased amount of uric acid, whithout specifying that this increase has to be exactly in that skeletal joint where the inflammation occurs.)

I think this is a very interesting case here for the pattern team to look at @dosumis 
This is one degree more complex than anything in uPheno is dealing with right now.

**Comment by matentzn** [comment]
(if you are happy @pnrobinson with the change for now you can close the issue again, else we need to discuss some modelling alternatives that tie te skeletal joint to the the increased amount of uric acid).

**Comment by pnrobinson** [comment]
The first definition is more accurate. However, I do not think it is actually being used downstream for anything and so we could stick with the simpler definition -- the increase in uric acid is not limited to the joints, so the second definition is correct as well. Thanks!
I will close this later after there has been a chance for further comments.

**Comment by pnrobinson** [comment]
I guess there has been enough time for comments. I will close this
