### ISSUE TITLE
pathological saccharine test

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2618]
_**Please consider a new term for pathological saccharine test observed in familial nasal acilia.
PMID:8813877.
Super class:Abnormal test result??**_

**Comment by pnrobinson** [comment]
There are many tests used to measure nasal mucociliary clearance. I have therefore created a term called
Impaired nasal mucociliary clearance (HP_0031603).
Def: An abnormally increased amount of time required to clear mucus (and substances contained in the mucus) from the nasal mucosa. The nasal mucociliary clearance (NMC) system functions to transport the mucous layer lining the nasal epithelium towards the naso pharynx by ciliary beating in a metachronous fashion at a frequency of 7-16 Hz. NMC depends upon two principal components: physicochemical qualities and quantities of mucus and the properties of cilia that propel it. NMC is considered to be representative of pulmonary clearance. normal NMC time is determined to be up to 20 minutes. Duration of 30 minutes is considered as the cutoff point that discriminates normal subjects from subjects with impaired NMC. NMC can be measured by determination of the transport time of markers that are placed on the nasal mucosa including saccharine, radioactive markers, and dyes.
I will add Abnormal saccharine test as a narrow synonym.
