### ISSUE TITLE
stasis of nasal secretion 

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2619]
_**Please consider a new term for stasis of nasal secretion  observed in familial nasal acilia.PMID:4002006. Super class:Abnormality of the nose??**_

**Comment by pnrobinson** [comment]
This is a relevant article on acilia syndrome, which might be a better designation than Familial nasal acilia syndrome :
https://www.ncbi.nlm.nih.gov/pubmed/18512228

**Comment by pnrobinson** [comment]
I think that stasis of nasal secretion is probably the same thing as Impaired nasal mucociliary clearance

**Comment by LOURGHI** [comment]
_** In fact this article https://www.ncbi.nlm.nih.gov/pubmed/18512228 is on Primary ciliary dyskinesia and this entity already exists on our database,from an other side,there is a difference between acilia and ciliary dyskinesia so I imagine that patients haven't any nasal secretion if only by sneezing**_
