### ISSUE TITLE
unciliated epithelial cels of nasal mucosa

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2620]
_**Please consider a new term for unciliated epithelial cels observed in familial nasal acilia.
PMID:8813877
Superclass: Abnormality of the nasal mucosa??**_

**Comment by pnrobinson** [comment]
This disease entity was described apparently only once in 1985 and it is doubtful to me that this defect affects ONLY the nasal mucosa. I would advise against making an Orphanet disease entry for this unless there is further evidence for this disease in the literature. 
I would suggest annotating to Abnormal respiratory motile cilium morphology (HP_0005938) if you do choose to annotate this paper in Orphanet.
