### ISSUE TITLE
new term request: Usual Interstitial Pneumonia

### ISSUE THREAD

**Issue by pshultes** [obophenotype/human-phenotype-ontology#2622]
1. Preferred term label - Usual Interstitial Pneumonia

2. Synonyms- UIP

3. Textual definition -  Temporal and spatial heterogeneity in lungs based on presence of fibrosis and honeycombing 

4. Suggested parent term- HP:0006530 Interstitial Pulmonary Abnormality

5. OMIM: %26300 Interstitial Pneumonitis

6. Nanoattribution- UCB:pshultes

**Comment by pnrobinson** [comment]
According to this, there is a distinction between UIP and desquamative interstitial pneumonitis:
https://radiopaedia.org/articles/usual-interstitial-pneumonia
Therefore, could you please provide more context and a PubMed reference that supports this annotation?
thanks!

**Comment by pshultes** [comment]
**UIP vs DIP**
The distinctions between UIP and DIP (desquamative interstitial pneumonitis) lie both in the patterns of fibrotic development and in the responses to treatment.

http://www.sciencedirect.com/science/article/pii/S0012369215463809?via%3Dihub
	PMID:8697837

Differences in responses to treatment:
"Overall, 9 of the 12 patients with UIP showed an increase in extent of ground-glass attenuation or progression to irregular lines or honeycombing on follow-up scans while only 2 showed improvement. However, only two patients with DIP showed progression to irregular lines or honeycombing on follow-up scans while six showed improvement. The likelihood of progression of abnormalities was significantly greater in patients with UIP than in patients with DIP (p<0.01, X2 test)."

UIP is usually identified by a honeycombing pattern in a CT scan; in contrast, DIP is not associated with the honeycombing pattern of fibrotic tissue. The article above also demonstrated differences in how UIP and DIP progress with treatment: DIP tends to stabilize or improve after treatment, UIP often continues to progress ("irregular lines or honeycombing").

**Other Sources**

_How UIP is Characterized:_
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4228744/

“Honeycombing, clustered cysts with well-defined walls involving the subpleural lung, is the key finding for making a definite diagnosis of UIP pattern. “

_UIP is associated with autoimmune diseases such as rheumatoid arthritis (and rheumatoid arthritis- interstitial lung disease, or RA-ILD):_

http://www.sciencedirect.com/science/article/pii/S1323893015001756?via%3Dihub#bib13
	PMID:26666486

**Comment by pnrobinson** [comment]
THanks for this input and sorry very much for the delay. I am adding this as HP_0031950
