### ISSUE TITLE
new term request: Viral Bronchiolitis

### ISSUE THREAD

**Issue by pshultes** [obophenotype/human-phenotype-ontology#2624]
1. Preferred term label- Viral Bronchiolitis

2. Synonyms-RSV Bronchiolitis

3. Textual definition-usually found in children; viral cause of bronchiolitis; majority of cases are caused by Respiratory Syncytial Virus (RSV); characterized by inflamed bronchioles; generally short-term; contagious PMID:29045741

4. Suggested parent term-HP:0006530 Interstitial Pulmonary Abnormality

5. If you know of a disease that is characterized by this feature, please indicate it- N/A

6. nanoattribution- UCB:pshultes

**Comment by LCCarmody** [comment]
@pnrobinson @pshultes Is this different than (HP:0011945) Bronchiolitis?  Should there be separate classes for viral bronchiolitis?  If so, Bronchiolitis could be the parent.

**Comment by pnrobinson** [comment]
I think that we should have Viral bronchiolitis be a Mondo term. @nicolevasilevsky @cmungall it is probably worth adding an RSV subclass to this term:
https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0020680
