### ISSUE TITLE
New children for ABNORMALITY OF THE OPTIC NERVE 

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2625]
ABNORMALITY OF THE OPTIC NERVE (HP:0001138): we think that the subclasses « Temporal gray pigmentary crescent » and « Peripapillary atrophy » should be added to existing subclasses « Temporal pallor » (HP:0012511) and « Diffuse pallor » (HP:0012512).
(from @mitolab )

**Comment by LCCarmody** [comment]
Is "Temporal gray pigmentary crescent" the same thing as "optic nerve gray crescent"?   If so, suggested definition: "It has a characteristic appearance of a slate gray area of pigmentation within the disc margins and commonly appears along the inferotemporal or temporal neuroretinal rim areas. This type of disc rim pigmentation can create the impression of neuroretinal rim thinning, and thus lead to the misdiagnosis of glaucoma or "glaucoma suspect" with attendant implications for overtreatment or unnecessary close monitoring of such patients."  PMID: 24862768 

Suggested definition for "peripapillary atrophy":  "a clinical finding associated with chorioretinal thinning and disruption of the retinal pigment epithelium (RPE) in the area surrounding the optic disc. It is non-specific and can occur in both benign and pathologic conditions, including glaucoma 1 and high myopia 2 "(PMID: 20920826)

**Comment by mitolab** [comment]
According to us (and our reading of the literature), "temporal gray pigmentary crescent" and "optic nerve grey crescent" are synonymous.
