### ISSUE TITLE
New children for INCREASED CUP-TO-DISC RATIO 

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2626]
INCREASED CUP-TO-DISC RATIO (HP:0012796): we think that this class should be divided in two ranges of ratios with defined values [0,5-0,7] and [0,8-1].
(from @mitolab )

**Comment by pnrobinson** [comment]
@psergouniotis
Can you please comment on this term request?

**Comment by psergouniotis** [comment]
I think it would perhaps be more useful to have the whole range as it will facilitate more accurate phenotyping. I am not aware of anyone using ranges in the units that I have worked with. 

I would recommend having "Increased vertical cup-to-disc ratio" as a subclass of "increased cup-to-disc ratio" (no need to have horizontal as not used much)

I would then recommend having the following subclasses of ""Increased vertical cup-to-disc ratio":
* "Increased vertical cup-to-disc ratio"* "Increased vertical cup-to-disc ratio"

Therefore, please consider adding the following subclasses:

**Comment by pnrobinson** [comment]
I am adding  "Increased vertical cup-to-disc ratio" 
with definition
An abnormal increase in the ratio of the height of the cup of the optic nerve head to the height of the disc.

And also the subclasses

**Comment by pnrobinson** [comment]
@psergouniotis 
I am definition the other terms like this:
Ratio of the height of the cup of the optic nerve head to the height of the disc (The normal cup-to-disc ratio is 0.3).
Please reopen this issue if that is not correct.

**Comment by psergouniotis** [comment]
many thanks Peter. I would not include the mention to normal cup-to-disc ratio. It is unclear what normal is (many people have cup to disc ratio of 0.9 and this is still normal).

I would therefore modify the definition of the subclasses to:
"Ratio of the height of the cup of the optic nerve head to the height of the optic disc of 0.6" etc
