### ISSUE TITLE
septal reticulations on Chest radiography

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2630]
_**Please consider a new term for septal reticulations on Chest radiography observed in Autoimmune pulmonary alveolar proteinosis.PMID:21632797.
Superclass:Interstitial pulmonary abnormality??**_

**Comment by LCCarmody** [comment]
@pnrobinson  There is already "Reticular pattern on pulmonary HRCT" HP:0025390.  I don't recommend an additional term, but could be a child of this term.

**Comment by pnrobinson** [comment]
I think the NTR is actually best made as Interlobular septal thickening, which can also look net-like

**Comment by LCCarmody** [comment]
In that case, HP:0030879 (Interlobular septal thickening on pulmonary HRCT) already exists.

**Comment by pnrobinson** [comment]
OK, I think we can close then. We will need to revise all of the radiology related terms of the HPO, but we will do so in the course of the up and coming radiology/EHR project.
