### ISSUE TITLE
Anti-GM-CSF antibodies positivity

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2633]
_**Pleaes consider a new term for Anti-GM-CSF antibodies positivity(granocyte-macrophage colony stimulating factor).
Observed in Autoimmune pulmonary alveolar proteinosis.PMID:21632797.
Superclass:Autoimmune antibody positivity??**_

**Comment by pnrobinson** [comment]
Label: Anti-granocyte-macrophage colony stimulating factor antibody positivity
Syn: Anti-GM-CSF antibody positivity
Def:The presence of autoantibodies in the serum that react against granocyte-macrophage colony stimulating factor.

Comment: Anti-granulocyte macrophage-colony stimulating factor (GM-CSF) autoantibodies have been shown to cause acquired pulmonary alveolar proteinosis (PAP)(1, 2), a chronic lung disease characterized by abnormalities of surfactant metabolism. PMID:23509356
