### ISSUE TITLE
eosinophilic ascites infiltration

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2636]
_**Please consider a new term for eosinophilic ascites infiltration.
Observed in Eosinophilic Gastroenteritis .PMID:26770900.part of the diagnostic criteria.
Superclass:Ascites??**_

**Comment by pnrobinson** [comment]
See
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5037340/
