### ISSUE TITLE
eosinophilic infiltration of gastrointestinal tissue

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2637]
_**Pleaes consider a new term for eosinophilic infiltration of gastrointestinal tissue.
Observed in Eosinophilic Gastroenteritis.PMID:26770900.part of diagnostic criteria.
Superclass:Abnormality of the gastrointestinal tract??**_

**Comment by pnrobinson** [comment]
There are now various eosinophilic esophagitis/gastritis terms. They will become visibile on the website with the next update, probably next week.
