### ISSUE TITLE
increased concentration of stool  α -trypsin

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2638]
_**please consider a new term for increased concentration of stool α-trypsin .
Observed in Eosinophilic Gastroenteritis .This sign has confirmed Protein-losing enteropathy in 6 patients with Eosinophilic Gastroenteritis.
Superclass: Protein-losing enteropathy??**_

**Comment by pnrobinson** [comment]
This should be alpha1-antitrypsin not alpha trypsin!

**Comment by pnrobinson** [comment]
Term:Increased stool alpha1-antitrypsin concentration
Def: Increased stool alpha1-antitrypsin concentration
Comment:Alpha-1-antitrypsin is resistant to degradation by digestive enzymes and can therefore be used as a marker for the presence of blood proteins in the intestinal tract (e.g., protein-losing enteropathy).
