### ISSUE TITLE
Positif MAST test

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2639]
_**Please consider a new term Positif MAST test.
Observed in Eosinophilic Gastroenteritis.PMID:26770900.
Superclass:abnormal test result??**_

**Comment by pnrobinson** [comment]
This is multiple allergen simultaneous test (MAST) 
These tests can detect more than 30 allergen-specific IgE at once using  fluorescent enzyme immunoassays.
There are many different versions of the test on the market with different combinations of antigen tests.
I think that it would be better to use Increased IgE, or maybe we should have a new term called Increased antigen specific IgE @LOURGHI  please advise

**Comment by pnrobinson** [comment]
Please use HP:0003212, Increased IgE level
