### ISSUE TITLE
increased urinary excretion of galactosyl-hydroxylysine

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2640]
_**Please consider a new term for increased urinary excretion of galactosyl-hydroxylysine.
Observed in Spastic paraplegia-Paget disease of bone syndrome.PMID:21937.
Superclass:Osteolysis??**_

**Comment by pnrobinson** [comment]
see https://www.ncbi.nlm.nih.gov/pubmed/10222355

**Comment by pnrobinson** [comment]
adding term as HP_0031991
