### ISSUE TITLE
paresis

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2641]
_**Please consider a new term for paresis.Observed in susac syndrome.PMID:26219936.
related synonyme :Muscle weakness??**_

**Comment by pnrobinson** [comment]
@LOURGHI  do you see a difference between muscle weakness and paresis?

**Comment by LOURGHI** [comment]
_**in addition to the decrease in muscle strength, there is a limitation of movement**_

**Comment by pnrobinson** [comment]
@LOURGHI  As far as I know this is not a commonly accepted definition of Paresis (i.e., limitation of movement does not play a part in the definition, although it may be a consequence of the weakness, I suppose)., see
https://en.wikipedia.org/wiki/Paresis

**Comment by pnrobinson** [comment]
Please use the term for Muscle weakness, I do not think we should create a term that bundles weakness and reduced movement.
