### ISSUE TITLE
Migraine-like headaches

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2643]
_**Please consider a new term Migraine-like headaches Observed in Susac syndrom.PMID:26219936.
Superclass:Headache??**_

**Comment by pnrobinson** [comment]
Can we use the existing term Migraine? What differentiates the migraine like headache from a migraine?

**Comment by LOURGHI** [comment]
_**it seems to me that the term implies an origin other than migraine for this headache???**_

**Comment by pnrobinson** [comment]
Yes, but the HPO encodes phenotypes and not etiologies. So I would suggest that this disease be annotated with migraine.

**Comment by pnrobinson** [comment]
I have looked at the manuscript.
For one patient it says:
 She had a one-year history of progressive migraine-type headaches  with visual aura,
For another it says: "initially diagnosed as migraine with aura. "
=> I think they mean that the headaches in this syndrome are of the type migraine, i.e., the phenotypic feature is migraine. Therefore, I think this disease can be annotated as having the phenotypic feature "Migraine".
