### ISSUE TITLE
3 instances without aspect value

### ISSUE THREAD

**Issue by stvdrsch** [obophenotype/human-phenotype-ontology#2644]
Based on this table [Annotation documentation](http://human-phenotype-ontology.github.io/documentation.html#annot) a value for aspect is required. There are 3 instances in [phenotype_annotation.tab](http://compbio.charite.de/jenkins/job/hpo.annotations/lastStableBuild/artifact/misc/phenotype_annotation.tab) that do not have a value for this field.

OMIM    218800  CRIGLER-NAJJAR SYNDROME, TYPE I         HP:0040284      OMIM:218800     IEA                                             2017-07-13      HPO:skoehler
OMIM    245348  PYRUVATE DEHYDROGENASE E2 DEFICIENCY            HP:0040284      OMIM:245348     IEA                                             2017-07-13      HPO:skoehler
OMIM    612740  PORPHYRIA, ACUTE HEPATIC                HP:0040284      OMIM:612740     IEA                                             2017-07-13      HPO:skoehler

**Comment by pnrobinson** [comment]
I think that this issue has been dealt with by the new Q/C code for the phenotype annotation files. Please reopen if you notice a continuing problem.
