### ISSUE TITLE
Layperson additions?

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#2645]
Hey @nicolevasilevsky and others,

have we included this: https://research.singhealth.com.sg/PDF/CentralisedInstitutionalReviewBoard/Glossary%20of%20lay%20terms%20%5B2016-07-26%5D.pdf ? Some might be candidates for addition

**Comment by nicolevasilevsky** [comment]
@drseb I will take a look and add any layperson synonyms that are missing. Thanks for sharing this!

**Comment by pnrobinson** [comment]
I have reviewed this document and added a few more LP synonyms and corrected one error (the previous LP synonym for hemoptysis).

**Comment by nicolevasilevsky** [comment]
Thanks @pnrobinson!
