### ISSUE TITLE
Add synonyms for Bradycardia 

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#2650]
is this an exact synonym: bradyarrhythmia ?

lay:  slow, irregular heartbeats

**Comment by pnrobinson** [comment]
Brady-arrhythmia is a "bundled" term (like bushy eyebrows and eyelashes), so I would not add it.
Slow heartbeats is a good LP synonym for Bradycardia though!

**Comment by pnrobinson** [comment]
done
