### ISSUE TITLE
ascending aorta dilation vs. dilatation?

### ISSUE THREAD

**Issue by sophiemichalski** [obophenotype/human-phenotype-ontology#2656]
there are two HPO terms that are very similar - ascending aorta dilatation vs ascending aorta dilatation - the dilatation element says 'Ascending aorta dilation' is an exact synonym. one of these should be made obsolete.

HP:0002631 - Dilatation of ascending aorta
HP:0005111 - Ascending aorta dilation

**Comment by pnrobinson** [comment]
Thanks for picking up this oversight/error. We will correct it!

**Comment by pnrobinson** [comment]
I have merged these two terms. Note that we are in the process of revising the cardiology section of the HPO and have decided to standardize on "aneurysm" (dilatation and aneurysm can be used interchangably, but aneurysm is reserved for an abnormal dilatation).
