### ISSUE TITLE
typo in compensatory chin elevation definition (HP:0001477)

### ISSUE THREAD

**Issue by sophiemichalski** [obophenotype/human-phenotype-ontology#2657]
HP:0001477 - Compensatory chin elevation

definition makes reference to "child" instead of "chin" 

def: "A tendency to hold the child elevated by about 20 to 30 degrees to compensate for a limitation of eye movement." [HPO:probinson]

**Comment by pnrobinson** [comment]
Thanks for picking up this typo, I have just fixed it; the fix will be visible in the next release.
