### ISSUE TITLE
hypercortisolism

### ISSUE THREAD

**Issue by sophiemichalski** [obophenotype/human-phenotype-ontology#2661]
the names of the two terms for hypercortisolism are spelled incorrectly - they say "hypercorti**c**olism" instead of "hypercorti**s**olism" .

the two elements with the typo:
hp:0011744 - secondary hypercorticolism
hp:0001579 - primary hypercorticolism

**Comment by pnrobinson** [comment]
Thanks for pointing this out and sorry for the delay. I have corrected this, the new version should be online next week.
