### ISSUE TITLE
Term request: Presyncope

### ISSUE THREAD

**Issue by AlgyTaylor** [obophenotype/human-phenotype-ontology#2663]
>1. Preferred term label (e.g., Asplenia)_

Presyncope

>2. Synonyms (e.g., Absent spleen)

None known (to me)

>3. Textual definition (the definition should be understandable even for non-specialists. Include a PubMed ID to refer to any relevant article that provides additional information about the suggested term).

Presyncope is a state of lightheadedness, muscular weakness, blurred vision, and feeling faint. Presyncope is most often cardiovascular in cause.
https://www.ncbi.nlm.nih.gov/pubmed/?term="pre%20syncope"[All%20Fields]&cmd=DetailsSearch

>4. Suggested parent term (Please look in the hierarchy of the HPO using the [HPO Browser](http://compbio.charite.de/hpoweb/showterm?id=HP:0000118) or other browsers such as [OLS](http://www.ebi.ac.uk/ols/ontologies/hp) and find the place in the HPO where the new term best fits)

Syncope (http://compbio.charite.de/hpoweb/showterm?id=HP:0001279)

>5. If you know of a disease that is characterized by this feature, please indicate it (e.g., by its Orphanet or OMIM id), and we will add the annotation to our database.

>6. If you would like a nanoattribution, please indicate your ORCID id or provide a label such as HPO:probinson (organization, first initial-last name)

0000-0001-5835-5515

**Comment by xirasasa** [comment]
The NIAID/NIH GRIS team is also very interested in the incorporation of this term within the HPO. Could you let us know when it would be incorporated?
Thanks!

**Comment by pnrobinson** [comment]
Adding this term as HP_0031972.
Sorry for the long delay, things got veyr backed up after relocation.
This will be online next week.
