### ISSUE TITLE
Term request: Apical hypertrophic cardiomyopathy

### ISSUE THREAD

**Issue by AlgyTaylor** [obophenotype/human-phenotype-ontology#2664]
>If this is a request for a new term, please provide us with the folloing information (c.f., https://github.com/obophenotype/human-phenotype-ontology/wiki/How-to-make-a-good-term-request).

>1. Preferred term label (e.g., Asplenia)_

Apical hypertrophic cardiomyopathy

>2. Synonyms (e.g., Absent spleen)

>3. Textual definition (the definition should be understandable even for non-specialists. Include a PubMed ID to refer to any relevant article that provides additional information about the suggested term).

Apical hypertrophic cardiomyopathy is diastolic dysfunction due to abnormal stiffness of the left ventricle during diastole, with resultant impaired ventricular filling
https://www.ncbi.nlm.nih.gov/pubmed/8685759

>4. Suggested parent term (Please look in the hierarchy of the HPO using the [HPO Browser](http://compbio.charite.de/hpoweb/showterm?id=HP:0000118) or other browsers such as [OLS](http://www.ebi.ac.uk/ols/ontologies/hp) and find the place in the HPO where the new term best fits)

Hypertrophic cardiomyopathy - http://compbio.charite.de/hpoweb/showterm?id=HP:0001639

>5. If you know of a disease that is characterized by this feature, please indicate it (e.g., by its Orphanet or OMIM id), and we will add the annotation to our database.

>6. If you would like a nanoattribution, please indicate your ORCID id or provide a label such as HPO:probinson (organization, first initial-last name)

0000-0001-5835-5515

**Comment by pnrobinson** [comment]
Adding as HP_0031992
