### ISSUE TITLE
Term request: Subaortic ventricular septal bulge

### ISSUE THREAD

**Issue by AlgyTaylor** [obophenotype/human-phenotype-ontology#2665]
>1. Preferred term label (e.g., Asplenia)_

Subaortic ventricular septal bulge

>2. Synonyms (e.g., Absent spleen)

Sub-bulge

>3. Textual definition (the definition should be understandable even for non-specialists. Include a PubMed ID to refer to any relevant article that provides additional information about the suggested term).

https://www.ncbi.nlm.nih.gov/pubmed/9203495

>4. Suggested parent term (Please look in the hierarchy of the HPO using the [HPO Browser](http://compbio.charite.de/hpoweb/showterm?id=HP:0000118) or other browsers such as [OLS](http://www.ebi.ac.uk/ols/ontologies/hp) and find the place in the HPO where the new term best fits)

Abnormality of the left ventricular outflow tract
http://compbio.charite.de/hpoweb/showterm?id=HP:0011103

>5. If you know of a disease that is characterized by this feature, please indicate it (e.g., by its Orphanet or OMIM id), and we will add the annotation to our database.

>6. If you would like a nanoattribution, please indicate your ORCID id or provide a label such as HPO:probinson (organization, first initial-last name)

0000-0001-5835-5515

**Comment by pnrobinson** [comment]
Sorry for the delay. Adding this term as HP_0031971, it should be online next week.
