### ISSUE TITLE
Term/Modifier(?) Request: Aborted [Sudden Cardiac Death]

### ISSUE THREAD

**Issue by AlgyTaylor** [obophenotype/human-phenotype-ontology#2666]
_Either_ a subclass of [Sudden Cardiac Death](http://compbio.charite.de/hpoweb/showterm?id=HP:0001645) _OR_ an "Aborted" modifier that could be associated with other terms.

Def: Conditions that would have led to rapid and unexpected death had an intervention not taken place to prevent them.  eg https://www.ncbi.nlm.nih.gov/pubmed/25187745

ORCID: 0000-0001-5835-5515

**Comment by pnrobinson** [comment]
Thanks. I am modifying the definition to "Cardiac arrest that would have led to rapid and unexpected death had an intervention not taken place to prevent it." and I think this is best made a sibling of sudden cardiac death. This will become publicly visible at our next release with id HP:0031628
