### ISSUE TITLE
ataxic encephalopathy

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2667]
_**PLease consider a new term for ataxic encephalopathy.
observed in Cerebellar ataxia-areflexia-pes cavus-optic atrophy-sensorineural hearing loss syndrome.ORPHA:1171 PMID:20301294.
Superclass:Encephalopathy??**_

**Comment by pnrobinson** [comment]
@LOURGHI I think this is a bundled description and it would be better to annotate to Ataxia AND Encephalopathy.
