### ISSUE TITLE
dry coughing

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2669]
_**Please consider a new term for dry coughing.Observed in Idiopathic pulmonary fibrosis.PMID:21471066.
Superclass:cough.
I don't find the following  terms:HP:0031246 Nonproductive cough ,productive HP:0031245  and whooping coughHP:0031247 on HPO browser . **_

**Comment by LOURGHI** [comment]
_**https://www.ebi.ac.uk/ols/ontologies/hp/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FHP_0031246**_

**Comment by pnrobinson** [comment]
@LOURGHI  do you agree this is a synonym of nonproductive cough?
@drseb Can you update the HPO Browser, this term is not visible. THanks!

**Comment by drseb** [comment]
I see "dry cough" but not "dry coughing".

**Comment by LOURGHI** [comment]
thank you Seb,
I think dry cough=nonproductive cough(exact synonym).

**Comment by pnrobinson** [comment]
I will add dry coughing as a synonym.
