### ISSUE TITLE
usual interstitial pneumonia

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2671]
_**Please consider a new term for usual interstitial pneumonia observed in Idiopathic pulmonary fibrosis PMID: 21471066.
Superclass:Interstitial pulmonary abnormality??**_

**Comment by pnrobinson** [comment]
I think that usual interstitial pneumonia is actually a disease
see
https://en.wikipedia.org/wiki/Usual_interstitial_pneumonia
therefore, we should add a term in ORDO or @cmungall MONDO to this.
