### ISSUE TITLE
Use standard prefixes in xrefs

### ISSUE THREAD

**Issue by cmungall** [obophenotype/human-phenotype-ontology#2673]
In Monarch and GO we use 'MESH' rather than 'MSH'

most registries have MSH as a synonym:
https://prefixcommons.org/?q=MSH

HPO uses SNOMEDCT_US
https://prefixcommons.org/?q=SNOMEDCT_US
no results

this seems more standard
https://prefixcommons.org/?q=SNOMEDCT

In mondo and uber we're using SCTID but we should probably change this

This is something we should do across ontologies, see:
https://github.com/OBOFoundry/OBOFoundry.github.io/issues/525

**Comment by cmungall** [comment]
Not clear what to do for ICD, HPO uses `ICD-{9,10}` but the dash doesn't seem standard: https://prefixcommons.org/?q=ICD10

**Comment by cmungall** [comment]
@drseb @pnrobinson @jmcmurry thoughts on this?

**Comment by pnrobinson** [comment]
We are not currently making much use of these xrefs, but certainly if we ever want to then we need to standardize on the prefixes. 
Can we add a check for this as a part of the efforts to revise the Q/C pipeline? I think we should throw an error if somebody uses a non-standard prefix.
Also, for the database_cross_reference used for attributing definitions etc., we are using a lot of non-standard entries, and we should instead settle on a small number of allowable sources and not use raw URLs

**Comment by cmungall** [comment]
QC check: sounds good. What I imagine you'd want to do is define a subset of prefixcommons as valid for HPO (could be just a simple list in a text file). You could leverage prefixcommons itself for the expansions if you need it.

btw, it seems PMID is occasionally being used as a class-level xref - IMHO this should only be used as an xref on an axioms (syn or def). E.g.
https://www.ebi.ac.uk/ols/ontologies/HP/terms?iri=http://purl.obolibrary.org/obo/HP_0030001

Maybe create a new ticket for the QC check, and have this ticket be the switch from MSH and SNOMED_US?

For the text definitions: raw URLs are often perfectly fine IMHO. For example, for a reasonably authoritative website or wiki. Of course it's formally published then a DOI or PMID etc is reserved.

Btw, OXO is pretty good about mapping from prefix synonyms to what it believes are canonical (which is id.org, slightly different from ours):
https://www.ebi.ac.uk/spot/oxo/datasources/HP

Still worth giving @SimonJupp a heads-up

**Comment by pnrobinson** [comment]
I agree the  pmid's should only be used as database_xrefs for definitions and synonyms (maybe also comments, although I do not think anyone has been doing this).

We should add a Q/C check for this

The reason I do not like URLs is that for physicians, it is much preferable to reference an authoritative article in PubMed. There are a few other authoritative sources we xref to such as GeneReviews, OMIM, Orphanet etc., but we have xrefs to also some popular medical websites that are not really authoritative and it does not make much sense to put them here, i.e., there is no more weight than if we just assert it ourselves. So I would be in favor of a short catalog of prefixes and authorities that we want to be citable.

**Comment by nicolevasilevsky** [comment]
@pnrobinson sounds good to only use authoritative sources. Should we avoid cross referencing wikipedia then?

**Comment by pnrobinson** [comment]
I think that there is little use in xref'ing wikipedia, because it will be the first hit on any google search. Wikipedia is pretty good for medical stuff but I think that any physician would want to see something in PubMed before taking any action. Wikipedia is often superficial or covers only part of a topic, and I think we would increase the value of HPO by searching for good refs in PubMed as a general rule. I also think that GeneReviews, OMIM, and Orphanet can be regarded as authoritative, but since their focus is on disease, rarely will we be able to xref them for phenotypes. Medical textbooks are also OK, and we should reference them with ISBN (and keep a list so we can display this on our homepage). Maybe there are a few other items?

**Comment by nicolevasilevsky** [comment]
Sounds good, thanks Peter!

**Comment by pnrobinson** [comment]
OK, I think we can close this now. If there are specific action items please reopen.

**Comment by cmungall** [comment]
This was maybe closed prematurely but there is a new ticket with clearer action items #4923

**Comment by LCCarmody** [comment]
Follow up here: Did we decide on standards?  MSH vs. MESH and SNOMEDCT vs. SCTID
