### ISSUE TITLE
clumsy tandem walking

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2680]
_**Please consider a new term for clumsy tandem walking observed in Spinocerebellar ataxia type 37 PMID:23700170.
Superclass:Gait disturbance??**_

**Comment by pnrobinson** [comment]
Adding a term with preferred label Impaired tandem gait
def: Reduced ability to walk in a straight line while placing the feet heal to toe.
syn: clumsy tandem walking
