### ISSUE TITLE
abnormal horizontal poursuit

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2681]
_**Please consider a new term for abnormal horizontal poursuit observed in Spinocerebellar ataxia type 37.PMID:23700170.
Superclass:Abnormal conjugate eye movement??**_

**Comment by LOURGHI** [comment]
_**abnormal horizontal occular poursuit may be more correct**_

**Comment by pnrobinson** [comment]
This is HP:0001151, Impaired horizontal smooth pursuit
I am adding Abnormal horizontal ocular pursuit (Note correction of spelling error!) as a synonym.
