### ISSUE TITLE
abnormal horizontal saccades

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2683]
_**Please consider a new term for abnormal horizontal saccades.observed in Spinocerebellar ataxia type 37.PMID:23700170.
Superclass:Abnormal conjugate eye movement??**_

**Comment by pnrobinson** [comment]
Looking at the publication, there is no detail on how the horizontal saccades were abnormal, but the disease seems to be characterized by various types of abnormal saccades. THe HPO does have a term called slow horizontal saccades, which could be what is going on here but there is not enough information to know. I would suggest we not create a new term until we have some literature that tells us what the abnormality is. I would suggest using a term like "Abnormality of saccadic eye movements" to describe this family.
