### ISSUE TITLE
hyperphosphatasemia as a synonyme for hyperphosphatasia

### ISSUE THREAD

**Issue by petkraw** [obophenotype/human-phenotype-ontology#2687]
I am reviewing a paper which uses the term hyperphosphatasemia
I think it is a synonym to hyperphosphatasia: HP:0003155
Do you agree? If yes, could you add it to HPO as a synonyme?
Thanks!

**Comment by pnrobinson** [comment]
Hyperphosphatasia is used to denote increased levels of alkaline phosphatase in the blood ,
 see e.g., https://ghr.nlm.nih.gov/condition/mabry-syndrome
hyperphosphatasemia is also used in this sense, see, e.g., 
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4949803/
Therefore, I think we can add this as a synonym.

**Comment by pnrobinson** [comment]
Adding as synonym to Elevated alkaline phosphatase, HP_0003155
