### ISSUE TITLE
Lissencephaly 

### ISSUE THREAD

**Issue by MoHebe** [obophenotype/human-phenotype-ontology#2690]
>1. Lissencephaly includes agyria, pachygyria and subcortical band heterotopia. 
(compare Di Donato, N., et al., Lissencephaly: Expanded imaging and clinical classification. Am J Med Genet A, 2017. 173(6): p. 1473-1488.). 
Thus Lissencephaly is not a synonym for Agyria as suggested by HPO-Browser. Please consider a change.
Kind regards

**Comment by pnrobinson** [comment]
Thanks for pointing this out, I have rectified the error.
