### ISSUE TITLE
ENR-EYE NTR: Mixed astigmatism

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2728]
[added] Added//Mixed astigmatism//new term request (PS); parent- Myopic astigmatism [level: 8]; term- Mixed astigmatism [level: 8]

**Comment by pnrobinson** [comment]
I am adding with definition
A type of astigmatism in which an unequal curvature of the cornea and some cases additionally of the lens causes one meridian of the eye to be hyperopic (farsighted) and a second meridian that is perpendicular to the first to be myopic (nearsighted).
@psergouniotis Please reopen this issue if the definition is not correct.

**Comment by psergouniotis** [comment]
Definition: Refractive error which is hypermetropic in one meridian and myopic in the other.
Comment: A type of astigmatism in which an unequal curvature of the cornea and some cases additionally of the lens causes one meridian of the eye to be hyperopic (farsighted) and a second meridian that is perpendicular to the first to be myopic (nearsighted).
