### ISSUE TITLE
Young adult onset inconsistent with parent class

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/human-phenotype-ontology#273]
Adult onset is defined as: Onset of disease manifestations in adulthood, defined here as at the age of 20 years or later.
subClass Young adult onset defined as: Onset of disease at the age of between 15 and 40 years.

The subClass must be within the temporal range of the superclass.

Also, the onset terms in HPO are also inconsistent with the human developmental stage ontology https://code.google.com/p/developmental-stage-ontologies/wiki/HsapDv
We should reconcile usage here.

Reported by: mellybelly

Original Ticket: [obo/human-phenotype-requests/273](https://sourceforge.net/p/obo/human-phenotype-requests/273)

**Comment by fbastian** [comment]
@mellybelly, just see this issue you linked to from another one: what is the status of integration of HsapDV? Did you fork your own version? We are open to changes in the post-embryonic grouping classes...
