### ISSUE TITLE
ENR-EYE NTR: Irregular astigmatism

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2732]
[added] Added//Irregular astigmatism//new term request (PS); parent- Oblique astigmatism [level: 8]; term- Irregular astigmatism [level: 8]

**Comment by pnrobinson** [comment]
Adding term with def
A type of astigmatism in which the principle meridians are not 90 degrees apart and which is associated with loss of vision.
@psergouniotis, Please reopen if the definition needs work.

**Comment by psergouniotis** [comment]
Definition: Astigmatism in which the two principal meridians are not at right angles to each other.

(I do not think that we need to include loss of vision in the definition)
