### ISSUE TITLE
ENR-EYE NTR: Corneal astigmatism

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2733]
[added] Added//Corneal astigmatism//new term request (PS); parent- Irregular astigmatism [level: 8]; term- Corneal astigmatism [level: 8]

**Comment by pnrobinson** [comment]
Adding term with def: A type of refractive error related abnormal curvatures on the anterior or posterior surface of the cornea.

@psergouniotis. - please reopen item if the definition needs revision

**Comment by psergouniotis** [comment]
proposed modification:
A type of astigmatism associated with abnormal curvatures on the anterior and/or posterior surface of the cornea.
