### ISSUE TITLE
ENR-EYE NTR: Mild hypermetropia

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2737]
[added] Added//Mild hypermetropia//new term request (PS); parent- Axial hypermetropia [level: 8]; term- Mild hypermetropia [level: 8]

**Comment by pnrobinson** [comment]
@psergouniotis
Are the official definitions for mild, moderate, severe hypermetropia we should be referencing?

**Comment by psergouniotis** [comment]
As per Oxford Handbook of Ophthalmology 2014 (p828):
HYPERMETROPIA may be classified according to the size of refractive error. The The American Optometric Association (AOA) definitions are: low (≤+2D), moderate (2–5D), and high (>5D).

Also, see https://www.aoa.org/documents/optometrists/QRG-16.pdf.

On a different note, the AOA definitions for MYOPIA are: low (<–3D), moderate (–3 to –6D), or high (>–6D). Myopia may physiological or pathological

**Comment by pnrobinson** [comment]
added term
