### ISSUE TITLE
ENR-EYE NTR: High-grade hypermetropia

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2739]
[renamed] HP:0008499//Hypermetropia//Renamed//High-grade hypermetropia//HP:0000540//Hypermetropia//High hypermetropia (PS); parent- Moderate hypermetropia [level: 8]; term- High-grade hypermetropia [level: 8]

**Comment by psergouniotis** [comment]
please rename to "high hypermetropia"

see #2737 for definition of "High hypermetropia"

**Comment by pnrobinson** [comment]
added term
