### ISSUE TITLE
ENR-EYE NTR: Congenital myopia

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2745]
[suppressed] HP:0008012//Myopia//Suppressed//Congenital myopia//HP:0000545//Myopia//congenital can be added as a modifier (PS); parent- Moderate myopia [level: 8]; term- Congenital myopia [level: 8]

**Comment by psergouniotis** [comment]
consider suppressing (congenital can be added as a modifier)

**Comment by LCCarmody** [comment]
This term already exists (HP:0008012)  but is a child of Myopia (HP:0000545).   Should this be a child of Moderate myopia (HP:0031624)?

**Comment by pnrobinson** [comment]
I think the suggestion was to obsolete/suppress this term. 
The reason is that we can add "congenital" as an onset term.
Let's look at the annotated diseases and see if there is anything special about the kind of myopia the affected newborns have. I will try to look into this next week.

**Comment by psergouniotis** [comment]
There are two omim terms and both can be moved to myopia. 
I would recommend suppressing "congenital myopia". Users can select myopia plus the modifier congenital instead.

**Comment by pnrobinson** [comment]
I have re-annotated the two diseases (I think that only one of the two disease truly has congenital myopia, for the other, I find Mild myopia https://www.ncbi.nlm.nih.gov/pubmed/23664118). I have obsoleted/merged the term.
