### ISSUE TITLE
ENR-EYE NTR: Decreased tear drainage

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2756]
[added] Added//Decreased tear drainage//new term request (PS); parent- Lacrimal pump failure [level: 8]; term- Decreased tear drainage [level: 8]

**Comment by LCCarmody** [comment]
As per the other ticket, "Decreased tear drainage: A form of watery eye associated with obstruction of the nasolacrimal system. This may arise at the level of the punctum, the canaliculi, the sac or the nasolacrimal duct.

"Decreased tear drainage" may be associated with Nasolacrimal sac obstruction & Nasolacrimal duct obstruction. However, not all obstructions will cause decreased tear drainage and therefore I think it would be best not to have these associated (one could select both "Nasolacrimal sac obstruction" and "Decreased tear drainage")".  

@pnrobinson Any suggestions where to put this term?

**Comment by psergouniotis** [comment]
As per ERN-EYE spreadsheet consider adding "Decreased tear drainage" as a subclass of "Epiphora" (HP:0009926)

**Comment by pnrobinson** [comment]
@psergouniotis  Please note that Epiphora currently has the subclass

Lacrimal pump failure (HP_0031734) with definition: A form of watery eye associated with abnormal lid tone and/or lid position. The former is due to lid laxity (common involutional change in the elderly) or a weak orbicularis muscle (e.g. due to VII cranial nerve palsy). The latter is typically associated with ectropion causing punctal eversion.

Is this correct?  I am also adding "Decreased tear drainage: A form of watery eye associated with obstruction of the nasolacrimal system. This may arise at the level of the punctum, the canaliculi, the sac or the nasolacrimal duct.

Please reopen this issue if we need to revise anything.
