### ISSUE TITLE
ENR-EYE NTR: Buphthalmos

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2765]
[moved here] Moved here!//Buphthalmos//definition: Diffusely large eye (with megalocornea) associated with glaucoma; parent- Large eyes [level: 9]; term- Buphthalmos [level: 9]

**Comment by pnrobinson** [comment]
@psergouniotis
I do not entirely understand this suggestion. Should we give buphthalmos another parent?

**Comment by psergouniotis** [comment]
Yes, parent should be "Abnormally large globe" (please see #2766)

**Comment by pnrobinson** [comment]
done
