### ISSUE TITLE
ENR-EYE NTR: Increased axial globe length

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2766]
[added] Added//Increased axial globe length//HP:0100887//Abnormality of globe size//Increased axial length of the globe (PS)//also add as subclass of Abnormally large globe (PS); parent- Buphthalmos [level: 9]; term- Increased axial globe length [level: 9]

**Comment by pnrobinson** [comment]
This term already existed, see HP:0007800.
@psergouniotis -- is the term OK as is?

**Comment by psergouniotis** [comment]
The recommendation here is to rename the term "Increased axial globe length" to "Increased axial length of the globe" (keeping "Increased axial globe length" as a synonym).

Also, it is presently a subclass of "Abnormality of globe size".
I recommend adding the term "Abnormally large globe"# (subclass of "Abnormality of globe size") and moving the following as subclasses of this new term:
* Buphthalmos (definition Diffusely large eye (with megalocornea) associated with glaucoma)
*  Increased axial globe length (to be renamed to "Increased axial length of the globe"

#Large eyes: the content of this term should be merged with the new term "Abnormally large globe". 
Megalophthalmos should be a synonym of "Abnormally large globe". You can keep as a synonym or remove the term "large eyes". 
Large of palpebral fissures and increased size of palpebral fissues should NOT be synonyms here - they are different thing.

Proposed definition for "Abnormally large globe": Diffusely large eye (with megalocornea) without glaucoma.

**Comment by pnrobinson** [comment]
@psergouniotis  I think that we might be able to use the term Large eyes and change the primary label to Abnormally large globe?

**Comment by psergouniotis** [comment]
yes. Please use "Abnormally large globe" as primary label and consider having "large eye" and "megalophthalmos" as synonyms.

**Comment by pnrobinson** [comment]
I implemented the above suggestions.
