### ISSUE TITLE
ENR-EYE NTR: Abnormality of the suspensory ligament of lens

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2768]
[moved here] HP:0001090//Moved here!//Abnormality of the suspensory ligament of lens//HP:0012374//Abnormality of the globe; parent- Spontaneous rupture of the globe [level: 7]; term- Abnormality of the suspensory ligament of lens [level: 7]

**Comment by pnrobinson** [comment]
I have moved this term to Abnormal anterior segment morphology
@psergouniotis please reopen issue if there are additional suggestions, the worksheet was not clear.

**Comment by psergouniotis** [comment]
I cannot see " Abnormal anterior segment morphology" in the HPO workbench. 
There is "Abnormal anterior chamber morphology" though (notably anterior segment is not equal to anterior chamber).

The suspensory ligament of lens are technically not in the anterior chamber (but it is anterior segment). 
I think it would be best to have the following subclasses of "Abnormality of the anterior segment of the globe":
- Anterior segment developmental anomaly (current anterior segment dysgenesis)
- Abnormality of the suspensory ligament of lens
- Abnormality anterior chamber morphology
- Abnormality of the cornea
- Abnormality of the lens
- Abnormality of the iris
- Pseudoexfoliation

see also #3110
