### ISSUE TITLE
ENR-EYE NTR: Lisch nodules

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2775]
[No action] HP:0012054//Intraocular melanoma//Lisch nodules//HP:0010568//Hamartoma of the eye; parent- Retinal hamartoma [level: 8]; term- Lisch nodules [level: 8]

**Comment by Frank-Probst** [comment]
Again, I don't think melanoma is the correct word here.

**Comment by Frank-Probst** [comment]
Also, Lisch nodules are iris hamartomas.  It looks like they're being linked to retinal hamartomas here.

**Comment by pnrobinson** [comment]
@Frank-Probst These are issues from a recent workshop and the issues were transformed into github messages from an excel file. Sorry this is a bit confusing, but here no action is bveing suggested and the Lisch nodules are being classified as hamartomas of the eye

**Comment by pnrobinson** [comment]
no action
