### ISSUE TITLE
ENR-EYE NTR: Epicanthus superciliaris

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2848]
[added] Added//Epicanthus superciliaris//new term request (PS); parent- Epicanthus tarsalis [level: 7]; term- Epicanthus superciliaris [level: 7]

**Comment by pnrobinson** [comment]
Adding term with def: A type of epicanthus in which more extensive epicanthal folds with their origins in the eyebrow cover, pass in front of and lateral to the medial canthus (middle corner of the eye).

@psergouniotis. - please reopen item if the definition needs revision

**Comment by psergouniotis** [comment]
Many thanks

Other modifications are proposed for epicanthus include:

[I] Modifying the hierarchy of Epicanthus (subclass of Abnormality of the eyelid)
  | Epicanthus palpebralis
  | Epicanthus tarsalis
  | Epicanthus superciliaris
  | Epicanthus inversus

[II] Epicanthus palpebralis should be a separate term and not a synonym of Epicanthus.

[III] Add Definition of Epicanthus palpebralis: A type of epicanthus in which a medial vertical fold is present between upper and lower lids.

[IV] Add Definition of Epicanthus tarsalis: A type of epicanthus in which a, primarily upper lid, fold is present. This phenotype is frequently encountered in oriental races.

[V] Suppress the term "Prominent epicanthal folds" (this should be a synonym of "Epicanthus"

**Comment by pnrobinson** [comment]
Done.
Need to reannotate diseases
```
ORPHA:3369 | Trigonocephaly-short stature-developmental delay syndrome |  
ORPHA:96097 | Distal trisomy 5q |  
OMIM:243310 | BARAITSER-WINTER SYNDROME 1 | ACTB (60)
OMIM:614882 | PEROXISOME BIOGENESIS DISORDER 10A (ZELLWEGER) | PEX3 (8504)
ORPHA:3309 | Tetrasomy 5p |  
OMIM:257850 | OCULODENTODIGITAL DYSPLASIA, AUTOSOMAL RECESSIVE


originally annotated to prominent epicanthal fold

**Comment by pnrobinson** [comment]
done reannotating OMIM annotations.

**Comment by pnrobinson** [comment]
Sent updates also to Orphanet website

**Comment by psergouniotis** [comment]
great. many thanks
