### ISSUE TITLE
ENR-EYE NTR: Anterior blepharitis

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2851]
[added] Added//Anterior blepharitis//new term request (PS); parent- Blepharitis [level: 6]; term- Anterior blepharitis [level: 7]

**Comment by pnrobinson** [comment]
Adding with def: A type of blepharitis that affects the eyelid skin, base of the eyelashes, and the eyelash follicles.

@psergouniotis. - please reopen item if the definition needs revision

**Comment by psergouniotis** [comment]
see also #2852

agree with definition.
