### ISSUE TITLE
ENR-EYE NTR: Posterior blepharitis

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2852]
[added] Added//Posterior blepharitis//new term request (PS); synonym Meibomian gland dysfunction; parent- Anterior blepharitis [level: 7]; term- Posterior blepharitis [level: 7]

**Comment by pnrobinson** [comment]
Adding with def
A type of blepharitis that affects the meibomian glands and gland orifices.
-- Also added synonym as above

@psergouniotis. - please reopen item if the definition needs revision

**Comment by psergouniotis** [comment]
Blepharitis (subclass of Abnormality of the eyelid)
  | Anterior blepharitis
  | Posterior blepharitis
  | Seborrhoeic blepharitis

Notably, "Meibomian gland dysfunction" and "Meibomian gland disease" should be synonyms of "Posterior blepharitis".

Definition for "Posterior blepharitis":  A type of blepharitis that affects the meibomian glands and meobomian gland orifices. This abnormality can be associated with a spectrum of appearances ranging from meibomian seborrhoea (foaming meibomian gland secretions) and meibomianitis (inflamed meibomian glands), to chalazia.

**Comment by pnrobinson** [comment]
updated definition.
