### ISSUE TITLE
ENR-EYE NTR: Cicatricial ectropion

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2855]
[added] Added//Cicatricial ectropion//new term request (PS); parent- Ectropion [level: 6]; term- Cicatricial ectropion [level: 7]

**Comment by pnrobinson** [comment]
Adding term
Def: An outward turning (eversion) or rotation of the eyelid margin (i.e., ectropion) caused by shortening or contraction of the anterior or middle lamellae related to scarring.
Comment: Cicatricial ectropion may occur owing to burns, lacerations, or infection of the skin of the eyelid.


@psergouniotis. - please reopen item if the definition needs revision

**Comment by psergouniotis** [comment]
"Entropion" should be a subclass of "Abnormality of the eyelid"

Ectropion
  | Cicatricial ectropion
  | Involutional ectropion
  | Mechanical ectropion
  | Paralytic ectropion

Definition for ectropion: abnormal eversion of the eyelid (usually the lower) away from the globe. It is usually acquired as a result of involutional, cicatricial, mechanical, or paralytic processes, e.g. VIIn palsy, but may occasionally be congenital.

Definition for involutional ectropion: abnormal eversion of the eyelid away from the globe resulting from age-related tissue laxity.

Definition for cicatricial ectropion: abnormal eversion of the eyelid away from the globe associated with scarring that vertically shortens the anterior lamella of the eyelid. Causes may include trauma, burns, radiotherapy and dermatitis.

see also #2861
