### ISSUE TITLE
ENR-EYE NTR: Mechanical ectropion

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2857]
[added] Added//Mechanical ectropion//new term request (PS); parent- Involutional ectropion [level: 7]; term- Mechanical ectropion [level: 7]

**Comment by pnrobinson** [comment]
added term

**Comment by LCCarmody** [comment]
@pnrobinson This term doesn't exist in the HPO, but 'Mechanical entropion' does.  It is siblings with Involutional entropion--should it be a child?
