### ISSUE TITLE
ENR-EYE NTR: Involutional entropion

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2861]
[added] Added//Involutional entropion//new term request (PS); parent- Cicatricial entropion [level: 7]; term- Involutional entropion [level: 7]

**Comment by pnrobinson** [comment]
@psergouniotis please provide a definition

**Comment by psergouniotis** [comment]
"Entropion" should be a subclass of "Abnormality of the eyelid"

Entropion
  | Cicatricial entropion
  | Mechanical entropion
  | Involutional entropion

Definition for entropion: abnormal inversion of the eyelid (usually the lower) towards the globe. Usually acquired as a result of involutional or cicatricial processes but may occasionally be congenital

Definition for involutional entropion: abnormal inversion of the eyelid towards the globe resulting from inferior retractor muscle dysfunction with tissue laxity and, possibly, override of the preseptal orbicularis muscle over the pretarsal orbicularis muscle.

Definition for involutional entropion: abnormal inversion of the eyelid towards the globe occuring when scarring vertically shortens the posterior lamella of the eyelid.

**Comment by pnrobinson** [comment]
@psergouniotis 
I added this definition for Mechanical entropion, please reopen this issue if it need revisions
A type of entropion (abnormal inversion of the eyelid towards the globe) that is related to a mass effect of a lesion (e.g., a tumor) that pulls the eyelid margin away from the globe.

**Comment by psergouniotis** [comment]
The definition is incorrect (you are describing Mechanical ectropion [not entropion]).

A correct version would be:
A type of entropion (abnormal inversion of the eyelid towards the globe) that is related to a mass effect of a lesion (e.g., a tumor) that pushes the eyelid margin towards the globe
