### ISSUE TITLE
ENR-EYE NTR: Eyelid laxity

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2864]
[added] Added//Eyelid laxity//new term request; synonym lid laxity (PS); parent- Floppy eyelid syndrome [level: 6]; term- Eyelid laxity [level: 6]

**Comment by psergouniotis** [comment]
* see also #2863 
* subclass of "Abnormality of the eyelid" (and perhaps "Abnormal eyelid morphology" - or should it be physiology?)
* definition:  abnormally lax eyelid associated with tissue relaxation; it can be demonstrated by the eyelid distraction test and/or the eyelid snap test.
* synonym: lid laxity
* subclasses of "eyelid laxity":
- floppy eyelid
- lateral canthal tendon laxity 
- medial canthal tendon laxity
- horizontal eyelid laxity
- vertical eyelid laxity.
- upper eyelid laxity
- lower eyelid laxity 
(the latter two should perhaps be expressed with a modifier but no modifier "lower" or "upper" exist at present I think).

**Comment by pnrobinson** [comment]
@psergouniotis  I have added abnormal eyelid physiology and added eyelid laxity as a subclass. Can you provide a good source for definitions of the proposed subclass terms?
thanks Peter

**Comment by psergouniotis** [comment]
should "eyelid laxity" be under morphology or physiology (I would think the former would be more appropriate but the latter may also be relevant). Please find below some definitions (most modified from OHO 2014 or Eyewiki).

Definition for "floppy eyelid": Excessive eyelid tissue laxity, typically affecting both upper eyelids and associated with spontanteous tarsal eversion during sleep. It is more common in the obese, it may be associated with obstructive sleep apnoe and it may result in corneal exposure or chronic papillary conjunctivitis. 

Definition for "lateral canthal tendon laxity": Laxity of the tendon stabilising the lateral aspect of the tarsal plate to the zygomatic bone. This can result in rounded appearence of the lateral canthus. Also, when the eyelid is pulled medially,  more than 2 mm movement of the canthal angle may be observed

Definition for "medial canthal tendon laxity": Laxity of the tendon stabilising the medial aspect of the tarsal plate to the anterior and posterior lacrimal crests. This may lead to more than 2mm movement of the punctum when the eyelid is pulled laterally.

Definition for "horizontal eyelid laxity": abnormally lax eyelid associated with tissue relaxation, predominantly in the horizontal plane. It can be demonstrated by the horizontal eyelid distruction test (e.g. by pulling the eyelid medially and laterally). Medial and/or lateral canthal tendon laxity are often present.

Definition for "vertical eyelid laxity": abnormally lax eyelid associated with tissue relaxation, predominantly in the vertical plane. It can be demonstrated by vertical lid pull. Loosening of vertical stabilising structures (e.g. lower lid retractors) or tarsal atrophy are often present.

Definition for "upper eyelid laxity": abnormally lax upper eyelid associated with tissue relaxation.
Definition for "lower eyelid laxity": abnormally lax lower eyelid associated with tissue relaxation.

**Comment by pnrobinson** [comment]
adding all terms as suggested.
