### ISSUE TITLE
ENR-EYE NTR: Eyelid lipoma

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2865]
[added] Added//Eyelid lipoma//new term request (PS); parent- Eyelid laxity [level: 6]; term- Eyelid lipoma [level: 6]

**Comment by psergouniotis** [comment]
I had a bit of a rethink about this. The suggested change in the ERN-EYE spreadsheet was motivated by rationalising the structure around the existing term "Lipomas of upper eyelids" (HP:0040164). This is under "lipomatous tumor" >  "multiple lipomas" 
Also, it is under "Abnormality of the eyelid". Notably no disease has been associated to this and it is unclear to me why this has been included in HPO. I would therefore recommend **obsoleting "Lipomas of upper eyelid" (HP:0040164).**

Also, please ignore the above suggestion to include the term "eyelid lipoma".

The term that is truly needed is "**conjuctival dermolipoma"** (syn "conjuctival lipodermoid")
Please consider adding "conjuctival dermolipoma" as a subclass of "Abnormality of the conjunctiva" (or of "Abnormal conjunctival morphology")

proposed definition for  "conjuctival dermolipoma": A conjuctival lesion composed of adipose tissue and dense connective tissue. Such choristomas of dermal elements are normally found at the outer canthus, and have a gelatinous appearance. Classically, there is an indistinct posterior border (with the lesion frequently extending into the orbit) and a well-demarcated anterior border several millimetres posterior to the limbus.
