### ISSUE TITLE
ENR-EYE NTR: Lipomas of upper eyelids

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2867]
[renamed] Renamed//Lipomas of upper eyelids//Upper eyelid lipoma//term present in HPO (HP:0040164); please add a subclass of eyelid lipoma rather than abnormality of the eyelid; it should not be a subclass of multiple lipomas [one could use modifier] (PS); parent- Lower eyelid lipoma [level: 7]; term- Lipomas of upper eyelids [level: 7]

**Comment by psergouniotis** [comment]
please consider obsoleting this term (please see #2865). 
I cannot see any condition associated with this on HPO workbench

**Comment by drseb** [comment]
Please use HPO browser for looking up such things: http://compbio.charite.de/hpoweb/showterm?id=HP:0040164

Should this still be obsolted @psergouniotis ?

**Comment by psergouniotis** [comment]
thanks for highlighting this. I had a quick look at the literature around the condition "NASOPALPEBRAL LIPOMA-COLOBOMA SYNDROME".

The lipomas in these condition are not restricted to the upper eyelid. Therefore, please consider replacing the term "Lipomas of upper eyelids" with the term "Lipoma of the eyelid" (and annotate this with % 167730 etc).

The term "Lipoma of the eyelid" should be a subclass of "Abnormality of the eyelid" (or "Abnormal eyelid morphology"). 
I think that this term should no longer be a subclass of "Multiple lipomas". It should instead be a subclass of "Lipoma".
