### ISSUE TITLE
ENR-EYE NTR: Lid lag

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2869]
[added] Added//Lid lag//new term request; definition: A sign associated with an upper lid does not follow the eye fully when changing fixation from up to downgaze; synonym: eyelid lag, von Graefe sign (PS); parent- Cogan lid twitch [level: 6]; term- Lid lag [level: 6]

**Comment by pnrobinson** [comment]
This article claims lid lag and von Graefe's sign are not synonyms
https://www.ncbi.nlm.nih.gov/pubmed/17900690
@psergouniotis please advise

**Comment by pnrobinson** [comment]
I have created the term but do not yet have a definition.
Is this good?
An abnormality of eyelid movement in which an upper lid does not follow the eye fully when changing fixation from up to downgaze.
Comment: delay in moving the eyelid as the eye moves downwards.

**Comment by psergouniotis** [comment]
I can see the point that the paper is trying to make but Kaski Clincial Ophthalmology (8th edition) - a major textbook - states: "The von Graefe sign signifies retarded descent of the upper lid on downgaze" (and in the relevant figure  they state: "right lid lag on downgaze – von Graefe sign"). Same in other textbooks and (to my knowledge) in most ophthalmology units.

So strictly speaking the new term should be "lid lag on downgaze" (subclass of Abnormality of the eyelid) with possible definition: Delayed descent of the upper eyelid on downgaze. Also described by some authors as von Graefe sign.

**Comment by pnrobinson** [comment]
thanks! btw. we have created a new term under abnormal physiology for abnormal movement of the eyelid, and I would put the term there. This can be reviewed with the HPO Workbench.

**Comment by psergouniotis** [comment]
perfect thank you. HPO Workbench looks great
