### ISSUE TITLE
ENR-EYE NTR:  Brow ptosis

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2872]
[added] Added//Brow ptosis// //new term request (PS); parent- Abnormality of the eyebrow [level: 5]; term-   [level: 9]

**Comment by pnrobinson** [comment]
adding drooping brow as a layperson synonym

**Comment by pnrobinson** [comment]
@psergouniotis
I am adding this term as follows. Please reopen this issue of the definition needs to be changed.

def definition "Drooping of the upper eyebrow below the superior orbital rim."
comment: Eybrow ptosis can be caused by age-related changes in the periorbital soft tissues and soft tissues of the face.

**Comment by psergouniotis** [comment]
Please add brow ptosis as a subclass of "Abnormality of the eyebrow"

As a definition I would perhaps prefer something closer to the http://eyewiki.aao.org/Brow_Ptosis_and_Repair one: 
"Decent of the brow and brow fat pad; this abnormality is typically associated with advancing age"

Agree with the  layperson synonym
