### ISSUE TITLE
ENR-EYE NTR: Peri-ocular capillary hemangioma

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2874]
[added] Added//Peri-ocular capillary hemangioma//new term request (PS); parent- Capillary hemangiomas [level: 4]; term- Peri-ocular capillary hemangioma [level: 5]

**Comment by psergouniotis** [comment]
Please rename term "Capillary hemangiomas" (HP:0005306) to "Capillary hemangioma"

Please add "Peri-ocular capillary hemangioma (synonym Periocular capillary hemangioma and Peri-ocular capillary haemangioma) as a subclass of "Capillary hemangioma".
