### ISSUE TITLE
ENR-EYE NTR: Orbital rhabdomyosarcoma

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2880]
[added] Added//Orbital rhabdomyosarcoma//new term request (PS); parent- Rhabdomyosarcoma [level: 4]; term- Orbital rhabdomyosarcoma [level: 5]

**Comment by psergouniotis** [comment]
Please add "Orbital rhabdomyosarcoma" as a subclass of "rhabdomyosarcoma" (HP:0002859)

proposed definition: a mesenchymal tumour that is considered to be the commonest primary orbital malignancy in children. Histologically, it may be differentiated into embryonal, alveolar, and pleomorphic
types. It is usually intraconal or within the superior orbit.
