### ISSUE TITLE
ENR-EYE NTR:  Optic nerve sheath meningioma

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2882]
[added] Added//Optic nerve sheath meningioma// //new term request (PS); parent- Thick eyebrow [level: 6]; term-   [level: 8]

**Comment by psergouniotis** [comment]
Please consider adding ""Optic nerve sheath meningioma" as a subclass of "Meningioma (HP:0002858)".

proposed definition (as per Oxford Handbook of Ophthalmology 2014): A benign tumour of meningothelial cells of the meninges that usually occurs in middle age. It is typically unilateral and there is an association with neurofibromatosis type 2.
