### ISSUE TITLE
ENR-EYE NTR: Abnormality of horizontal rectus muscle

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2888]
[added] Added//Abnormality of horizontal rectus muscle//new term request (PS); parent- Abnormality of rectus muscle [level: 7]; term- Abnormality of horizontal rectus muscle [level: 8]

**Comment by pnrobinson** [comment]
@psergouniotis
Shouldnt this be the "lateral" rectus muscle?

**Comment by psergouniotis** [comment]
The following structure is proposed

Abnormality of horizontal rectus muscle
  | Abnormality of medial   rectus muscle
  |   | Medial rectus muscle   overaction
  |   | Medial rectus muscle   weakness
  |   |   | Medial rectus muscle underaction
  |   |   | Medial rectus muscle rescriction
  | Abnormality of lateral   rectus muscle
  |   | Lateral rectus muscle   overaction
  |   | Lateral rectus muscle   weakness
  |   |   | Lateral rectus muscle underaction
  |   |   | Lateral rectus muscle restriction

(for definitions of overaction, underaction & restriction see #2916)

Further to your question: The superclass should be "Abnormality of horizontal rectus muscle".
"Abnormality of lateral rectus muscle" and "Abnormality of medial rectus muscle" should be its subclasses.

Essentially there are two horizontal recti, the medial rectus and the lateral rectus.

**Comment by pnrobinson** [comment]
implemented these suggestions.
