### ISSUE TITLE
ENR-EYE NTR: Lateral rectus muscle restriction

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2898]
[added] Added//Lateral rectus muscle restriction//new term request (PS); parent- Lateral rectus muscle underaction [level: 11]; term- Lateral rectus muscle restriction [level: 11]

**Comment by psergouniotis** [comment]
proposed definition: "Abnormal range of movement of the lateral rectus muscle where the movement does not improve fully when testing ductions; typically associated with mechanical aetiology."
