### ISSUE TITLE
ENR-EYE NTR: Abnormality of superior rectus muscle

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2900]
[added] Added//Abnormality of superior rectus muscle//new term request (PS); parent- Abnormality of vertical rectus muscle [level: 8]; term- Abnormality of superior rectus muscle [level: 9]

**Comment by pnrobinson** [comment]
Adding term as
Abnormal superior rectus muscle physiology

Definition: A functional anomaly of the superior rectus muscle, an extraocular muscle that is innervated by the superior division of the oculomotor nerve, and whose primary function is the elevation of the globe.

@psergouniotis. - please reopen item if the definition needs revision

**Comment by psergouniotis** [comment]
Also, I would prefer "Abnormality of superior rectus muscle" from "Abnormal superior rectus muscle physiology" but  no strong feelings about this (one could be synonym perhaps)?
