### ISSUE TITLE
ENR-EYE NTR: Superior rectus muscle restriction

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2904]
[added] Added//Superior rectus muscle rescriction//new term request (PS); parent- Superior rectus muscle underaction [level: 11]; term- Superior rectus muscle rescriction [level: 11]

**Comment by pnrobinson** [comment]
Adding term with
def: Mechanical limitation of the range of movement of the superior rectus muscle.
comment: In contrast to deficits produced by primary muscle weakness, restriction means that the affected extraocular muscle cannot move passively any more than actively.
@psergouniotis please reopen if this definition is suboptimal

UManchester:psergouniotis

**Comment by psergouniotis** [comment]
A variant of the above definition that would perhaps be more accurate:
"Abnormal range of movement of the superior rectus muscle where the movement does not improve fully when testing ductions; often associated with mechanical aetiology."
