### ISSUE TITLE
ENR-EYE NTR: Inferior oblique muscle restriction

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2915]
[added] Added//Inferior oblique muscle rescriction//new term request (PS); parent- Inferior oblique muscle underaction [level: 11]; term- Inferior oblique muscle rescriction [level: 11]

**Comment by pnrobinson** [comment]
added

**Comment by psergouniotis** [comment]
possible definition:
"Abnormal range of movement of the inferior oblique muscle where the movement does not improve fully when testing ductions; typically associated with mechanical aetiology."

As per spreadsheet, consider also adding term: "Superior oblique muscle rescriction" (subclass of "Superior oblique muscle weakness") with similar definition to the one above
