### ISSUE TITLE
ENR-EYE NTR: Abnormality of superior oblique muscle

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2916]
[added] Added//Abnormality of superior oblique muscle//new term request (PS); parent- Inferior oblique muscle rescriction [level: 11]; term- Abnormality of superior oblique muscle [level: 9]

**Comment by pnrobinson** [comment]
Adding as Abnormal superior oblique muscle physiology

**Comment by pnrobinson** [comment]
Adding with def:A functional anomaly of the superior oblique muscle, a fusiform muscle that originates in the upper, medial side of the orbit. The superior oblique muscle abducts, depresses and internally rotates the eye, and is the only extraocular muscle innervated by the fourth cranial nerve.
comment: A neurological examination includes assessment of the trochlear nerve (CN IV) which innervates the superior oblique muscle. The test for CN IV function is for the patient to depress and adduct the eye (ie. to look down and in). This movement is impaired in the presence of a trochlear nerve palsy.

@psergouniotis. - please reopen item if the definition needs revision

**Comment by psergouniotis** [comment]
I propose the following structure regarding oblique muscles 

Abnormality of oblique muscle 
  |   | Abnormality of inferior oblique muscle
  |   |   | Inferior oblique muscle overaction
  |   |   | Inferior oblique muscle weakness
  |   |   |   | Inferior oblique muscle underaction
  |   |   |   | Inferior oblique muscle rescriction
  |   | Abnormality of superior oblique muscle
  |   |   | Superior oblique muscle overaction
  |   |   | Superior oblique muscle weakness
  |   |   |   | Superior oblique muscle underaction
  |   |   |   | Superior oblique muscle rescriction

Happy with the definition but I think the last sentence of the comment should not be included (as it discusses only "Superior oblique muscle underaction" rather "Abnormality of superior oblique muscle").

**Comment by psergouniotis** [comment]
Also, I would prefer "Abnormality of superior oblique muscle" from "Abnormal superior oblique muscle physiology" but  no strong feelings about this (one could be synonym perhaps)?
