### ISSUE TITLE
ENR-EYE NTR: Superior oblique muscle overaction

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2917]
[added] Added//Superior oblique muscle overaction//new term request (PS); parent- Abnormality of superior oblique muscle [level: 9]; term- Superior oblique muscle overaction [level: 10]

**Comment by pnrobinson** [comment]
Adding term with this definition, adapted from https://jamanetwork.com/journals/jamaophthalmology/fullarticle/267803

An ocular motility disorder characterized by vertical incomitance of the eyes in lateral gaze. In primary superior oblique muscle overaction, an downshoot of the adducting eye occurs when gaze is directed into the field of action of the inferior oblique muscle, producing a greater downward excursion of the adducted eye than of the abducted eye.


@psergouniotis. - please reopen item if the definition needs revision

**Comment by psergouniotis** [comment]
Proposed modification: An ocular motility abnormality characterized by an overacting superior oblique muscle resulting to vertical incomitance of the eyes in lateral gaze. On examination, this is commonly seen as a downshoot of the adducting eye occuring when gaze is directed into the field of action of the inferior oblique muscle, producing a greater downward excursion of the adducted eye than of the abducted eye.

**Comment by pnrobinson** [comment]
updated definition, thanks!
