### ISSUE TITLE
ENR-EYE NTR: Superior oblique muscle underaction

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2919]
[added] Added//Superior oblique muscle underaction//new term request (PS); parent- Superior oblique muscle weakness [level: 10]; term- Superior oblique muscle underaction [level: 11]

**Comment by pnrobinson** [comment]
Also, should Under-Depression in Adduction (UDA) be a synonym of  Superior Oblique Underaction.
@psergouniotis.
Please provide a definition!

**Comment by psergouniotis** [comment]
Yes they could be synonyms (with Superior Oblique Underaction as the primary term).

Defintion: Reduced ocular movement of the superior oblique muscle which improves on testing ductions, typically associated with neurogenic palsy.

see also #2916
