### ISSUE TITLE
ENR-EYE NTR: Supeiror oblique muscle restriction

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2920]
[added] Added//Supeiror oblique muscle rescriction//new term request (PS); parent- Superior oblique muscle underaction [level: 11]; term- Supeiror oblique muscle rescriction [level: 11]

**Comment by pnrobinson** [comment]
I will add this term (and the other restriction terms) with definitions such as

Mechanical limitation of the range of movement of the superior oblique muscle.
Comment: In contrast to deficits produces by primary muscle weakness, extraocular muscle restriction cannot move passively any more than actively.


@psergouniotis. - please reopen item if the definition needs revision

**Comment by psergouniotis** [comment]
A perhaps more accurate definition would be:
"Abnormal range of movement of the isuperior oblique muscle where the movement does not improve fully when testing ductions; typically associated with mechanical aetiology."
