### ISSUE TITLE
ENR-EYE NTR: Parafoveal fixation

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2922]
new term request (PS); parent- Eccentric Fixation [level: 8]; term- Parafoveal fixation [level: 9]

**Comment by pnrobinson** [comment]
@psergouniotis. - eccentric fixation is already defined as fixation other than in the fovea. Can you provide a definition for this term. Does it mean fixation right next to the fovea?

**Comment by psergouniotis** [comment]
Yes. "Parafoveal fixation" should be a subclass of "Eccentric fixation"

proposed definition for "Parafoveal fixation":  Fixation of an object in the area adjacent to the fovea.
proposed definition for "Eccentric fixation": A uniocular phenotype in which there is fixation of an object by a point other than the fovea. This point adopts the principal visual direction. The degree of the eccentric fixation is defined by its distance from the fovea in degrees.

A case when you have "Parafoveal' but not "Eccentric" fixation is the so-called "Peripheral Fixation" (ie eccentric fixation in the peripheral area of the retina, it may be steady or unsteady).

If you wish "Peripheral fixation" could be added as another subclass of "Eccentric fixation".

**Comment by pnrobinson** [comment]
thanks, adding terms and definitions.
