### ISSUE TITLE
ENR-EYE NTR: Absolute eccentric fixation

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2923]
[added] Added//Absolute eccentric fixation//new term request; definition: Eccentric fixation in which the angle of eccentricity equals the objective angle of deviation (PS); parent- Parafoveal fixation [level: 9]; term- Absolute eccentric fixation [level: 9]

**Comment by psergouniotis** [comment]
"Abnormal visual fixation" (HP:0025404) should have "Eccentric fixation" as a subclass (please introduce term "Eccentric fixation")
"Eccentric fixation" should have "Parafoveal fixation" and "Absolute eccentric fixation" as its subclasses (please introduce new terms).

proposed definition for "Absolute eccentric fixation": Eccentric fixation in which the angle of eccentricity equals the objective angle of deviation.
