### ISSUE TITLE
ENR-EYE NTR: Dissociated vertical deviation

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2925]
[added] Added//Dissociated vertical deviation//new term request (PS); parent- Abnormal ocular alignment [level: 7]; term- Dissociated vertical deviation [level: 8]

**Comment by psergouniotis** [comment]
please introduce "Abnormal ocular alignment" as a subclass of "Abnormality of eye movement" (HP:0000496)

please introduce 
  | Dissociated vertical deviation
  | Dissociated horizontal deviation
as subclasses of "Abnormal ocular alignment"

proposed definition for "Dissociated vertical deviation": An incomitant tendency for an occluded eye to elevate and extort which resolves on uncovering. 
Dissociated vertical deviation (DVD ) occurs when the level of illumination received by either eye is reduced sufficiently and as a result eye deviates progressively upwards, but reverts to its original position when the level of illumination returns to normally acceptable levels. It may sometimes be so asymmetrical as to be virtually unilateral and is associated with heterotropia usually of early onset.

(from Oxford Handbook of Ophthalmology 2014 & BIOS 2012)
