### ISSUE TITLE
ENR-EYE NTR: Dissociated horizontal deviation

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2926]
[added] Added//Dissociated horizontal deviation//new term request (PS); parent- Dissociated vertical deviation [level: 8]; term- Dissociated horizontal deviation [level: 8]

**Comment by pnrobinson** [comment]
@psergouniotis
Should this be a child of strabismus? Is see there is a suggestion for a term called abnormal ocular alignment, but isn't this the same as strabismus? Or do we want to say there are other subclasses of abnormal ocular alignment?

**Comment by psergouniotis** [comment]
- Dissociated horizontal deviation & Dissociated vertical deviation are not strabismus. 

- Proposed definition of dissociated vertical deviation:  an incomitant tendency for an occluded eye to elevate and extort with this resolving on uncovering. 
Comment: When the level of illumination received by either eye is reduced sufficiently that eye deviates progressively upwards, but reverts to its original position when the level of illumination returns to normally acceptable levels. It may sometimes be so asymmetrical as to be virtually unilateral and it is typically associated with heterotropia usually of early onset.

- Proposed definition of dissociated horizontal deviation: an incomitant tendency for an occluded eye to deviate horizontally with this resolving on uncovering. 

- DVD & DHD are associated with strabismus but are not strabismus. They should therefore not be a subclass of strabismus.

- I do not think there will be consensus with this but having a parent term "abnormal ocular alignment" and 3 subclasses: "dissociated vertical deviation", "dissociated horizontal deviation" & "strabismus" sounds reasonable to me.

**Comment by LCCarmody** [comment]
I added these as abnormality of ocular alignment (and not strabismus).
