### ISSUE TITLE
ENR-EYE NTR: Congenital strabismus

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2928]
[suppressed] HP:0000487//Strabismus//Suppressed//Congenital strabismus//HP:0000486//Strabismus//congenital could be added as a modifier (PS); parent- Alternating strabismus [level: 9]; term- Congenital strabismus [level: 9]

**Comment by pnrobinson** [comment]
We are in the process of revising the annotation file structure and cannot current reliably add this as a modifier. We will be revising the entire HPO once the update has been made.  @drseb

**Comment by pnrobinson** [comment]
We should now be able to move on this.
There are three annotated diseases
https://hpo.jax.org/app/browse/term/HP:0000487

**Comment by psergouniotis** [comment]
if the plan is to remove "congenital strabismus" as it can be expressed by selecting "strabismus" & the modifier congenital, the following is recommended regarding the annotated diseases:
I had a look and all can be moved to "Strabismus". 

The same applies for "congenital exotropia" (see also #2976)

**Comment by pnrobinson** [comment]
OK, I reannotated the diseases and merged the terms.
