### ISSUE TITLE
ENR-EYE NTR: Congenital exotropia

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2929]
[suppressed] HP:0008033//Congenital strabismus//Suppressed//Congenital exotropia//HP:0000487//Congenital strabismus//congenital could be added as a modifier (PS); parent- Congenital strabismus [level: 9]; term- Congenital exotropia [level: 10]

**Comment by LCCarmody** [comment]
This is a duplicate. See #2976. Close.
