### ISSUE TITLE
ENR-EYE NTR: Hyperdeviation

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2933]
[added] Added//Hyperdeviation//new term request (PS); parent- Excyclotropia [level: 10]; term- Hyperdeviation [level: 9]

**Comment by pnrobinson** [comment]
I am ading this term as a child of strabismus. 
Def: A type of strabismus in which the visual axis of one eye is higher than that of the other.
comment: Hyperphoria is a latent deviation where  the eyes remain aligned under normal binocular vision. Hypertropia is a manifest deviation in which the eyes are not aligned under binocular conditions.


@psergouniotis. - please reopen item if the definition needs revision

**Comment by psergouniotis** [comment]
see also #2934 and #2936
