### ISSUE TITLE
ENR-EYE NTR: Hypertropia

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2934]
[added] Added//Hypertropia//new term request (PS); parent- Hyperdeviation [level: 9]; term- Hypertropia [level: 10]

**Comment by pnrobinson** [comment]
A type of strabismus characterized by permanent upward deviation of the visual axis of one eye.
@psergouniotis. - please reopen item if the definition needs revision

**Comment by psergouniotis** [comment]
see #2936
"Hypertropia" should be a subclass of "Hyperdeviation"

Definitions (as per BIOS):
Hypertropia: A form of manifest strabismus (heterotropia) in which one eye is deviated upwards when both eyes are open.
