### ISSUE TITLE
ENR-EYE NTR: Alternating hypertropia

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2935]
[added] Added//Alternating hypertropia//new term request; also synonym of alternating strabismus (PS); parent- Hypertropia [level: 10]; term- Alternating hypertropia [level: 11]

**Comment by psergouniotis** [comment]
Please introduce "Hyperdeviation" as a subclass of "Strabismus" (HP:0000486)
Please introduce "Hypertropia" and "Hyperphoria" as subclasses of "Hyperdeviation"
Please introduce "Alternating hypertropia" as a subclass of 'Hypertropia".

proposed definition for "Alternating hypetropia": A type of vertical tropia in which, when one eye is fixing, the other eye is deviated upwards.

(as per BIOS 2012)
see also #2942, #2940, #2937
