### ISSUE TITLE
ENR-EYE NTR: Hyperphoria

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2936]
[added] Added//Hyperphoria//new term request (PS); parent- Alternating hypertropia [level: 11]; term- Hyperphoria [level: 10]

**Comment by pnrobinson** [comment]
Adding with def
Tendency for the visual ais of one eye to be higher than that of the other.

@psergouniotis. - please reopen item if the definition needs revision

**Comment by psergouniotis** [comment]
As per ERN-EYE spreadsheet,
"Hyperdeviation" should be a subclass of "Strabismus"
"Hyperphoria should be a subclass of "Hyperdeviation"
"Hypertropia" should be a subclass of "Hyperdeviation"

Definitions (as per BIOS):
Hyperphoria: A form of latent strabismus (heterophoria) in which, on dissociation, the occluded eye deviates upwards.
Hypertropia: A form of manifest strabismus (heterotropia) in which one eye is deviated upwards when both eyes are open.

see also #2934
