### ISSUE TITLE
ENR-EYE NTR: Alternating hyperphoria

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2937]
[added] Added//Alternating hyperphoria//new term request; also synonym of alternating strabismus (PS); parent- Hyperphoria [level: 10]; term- Alternating hyperphoria [level: 11]

**Comment by pnrobinson** [comment]
Adding term with definition:A type of cyclotropia (torsion of one or both eye about the visual axis of the eyes) in which the upper poles of the globes are rotated outward (laterally) to each other.

@psergouniotis please reopen issue if this definition needs revision

**Comment by pnrobinson** [comment]
Sorry, wrong issue.

**Comment by psergouniotis** [comment]
"Alternating hyperphoria" should be a subclass of "Hyperphoria". 

It should also be a subclass of subclass of "Alternating strabismus" (note error in the ERN-EYE spreadsheet - it meant to have subclass rather than synonym).

**Comment by psergouniotis** [comment]
Please introduce "Hyperdeviation" as a subclass of "Strabismus" (HP:0000486)
Please introduce "Hypertropia" and "Hyperphoria" as subclasses of "Hyperdeviation"
Please introduce "Alternating hyperphoria" as a subclass of 'Hyperphoria".

proposed definition for "Alternating hyperphoria": A type of vertical phoria in which, in dissociation, the occluded eye deviates upwards.

(as per BIOS 2012)
see also #2942
