### ISSUE TITLE
ENR-EYE NTR: Hypodeviation

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2938]
[added] Added//Hypodeviation//new term request (PS); parent- Alternating hyperphoria [level: 11]; term- Hypodeviation [level: 9]

**Comment by pnrobinson** [comment]
Adding term with def: A type of strabismus in which the visual axis of one eye is higher than that of the other.
Comment: Hypophoria is a latent deviation where the eyes remain aligned under normal binocular vision. Hypotropia is a manifest deviation in which the eyes are not aligned under binocular conditions.

@psergouniotis. - please reopen item if the definition needs revision

**Comment by psergouniotis** [comment]
see also #2941 and #2939 
"Hypodeviation" to be a subclass of "Strabismus"
