### ISSUE TITLE
ENR-EYE NTR: Hypotropia

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2939]
[added] Added//Hypotropia//new term request (PS); parent- Hypodeviation [level: 9]; term- Hypotropia [level: 10]

**Comment by pnrobinson** [comment]
Adding term with this definition
A type of strabismus characterized by permanent downward deviation of the visual axis of one eye.
@psergouniotis - please reopen item if the definition needs to be revised.

**Comment by psergouniotis** [comment]
see also #2941 and #2938

As per ERN-EYE spreadsheet,
"Hypodeviation" should be a subclass of "Strabusmus"
"Hypotropia" should be a subclass of "Hypodeviation"

Definitions (as per BIOS):
"Hypotropia": A form of manifest strabismus (heterotropia) in which one eye is deviated downwards when both eyes are open.
