### ISSUE TITLE
ENR-EYE NTR: Alternating hypotropia

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2940]
[added] Added//Alternating hypotropia//new term request; also synonym of alternating strabismus (PS); parent- Hypotropia [level: 10]; term- Alternating hypotropia [level: 11]

**Comment by psergouniotis** [comment]
Please introduce "Hypodeviation" as a subclass of "Strabismus" (HP:0000486)
Please introduce "Hypotropia" and "Hypophoria" as subclasses of "Hypodeviation"
Please introduce "Alternating hypotropia" as a subclass of 'Hypotropia".

proposed definition for "Alternating hypotropia": A type of vertical tropia in which, when one eye is fixing, the other eye is deviated downwards.

(as per BIOS 2012)
see also #2942, #2937
