### ISSUE TITLE
ENR-EYE NTR: Hypophoria

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2941]
[added] Added//Hypophoria//new term request (PS); parent- Alternating hypotropia [level: 11]; term- Hypophoria [level: 10]

**Comment by pnrobinson** [comment]
Adding this term as a child of strabismus with definition
A tendency towards downward deviation of the visual axis of an eye in the absence of visual stimuli.
@psergouniotis -- is the term placement and definition correct? Please re-open issue if not!

**Comment by psergouniotis** [comment]
No the placement is not correct.

As per ERN-EYE spreadsheet, 
"Hypodeviation" should be a subclass of "Strabusmus"
"Hypophoria should be a subclass of "Hypodeviation"
"Hypotropia" should be a subclass of "Hypodeviation"

Definitions (as per BIOS): 
Hypophoria": A form of heterophoria in which, on dissociation, the occluded eye rotates downwards.
"Hypotropia": A form of heterotropia in which one eye is deviated downwards when both eyes are open.

"

**Comment by pnrobinson** [comment]
reopenining issue.

**Comment by pnrobinson** [comment]
Updated placement and definitions.
