### ISSUE TITLE
ENR-EYE NTR: Alternating hypophoria

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2942]
[added] Added//Alternating hypophoria//new term request; also synonym of alternating strabismus (PS); parent- Hypophoria [level: 10]; term- Alternating hypophoria [level: 11]

**Comment by psergouniotis** [comment]
Please introduce "Hypodeviation" as a subclass of "Strabismus" (HP:0000486)
Please introduce "Hypotropia" and "Hypophoria" as subclasses of "Hypodeviation"
Please introduce "Alternating hypophoria" as a subclass of 'Hypophoria".

proposed definition for "Alternating hypophoria": A type of vertical phoria in which, in dissociation, the occluded eye deviates downwards.
