### ISSUE TITLE
ENR-EYE NTR: Microtropia

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2943]
[added] Added//Microtropia//new term request; definition: A small angle heterotropia (usually of 10 dioptres or less) in which a form of binocular single vision occurs. (PS); parent- Alternating hypophoria [level: 11]; term- Microtropia [level: 9]

**Comment by pnrobinson** [comment]
@psergouniotis I added this as a child of Strabismus -- please reopen this issue if that is incorrect.

**Comment by psergouniotis** [comment]
Yes this should be a subclass of strabismus.

Definition for "microtropia": A small angle heterotropia (usually of 10 dioptres or less) in which a form of binocular single vision occurs.

The following should be subclasses of "microtropia":
* Microtropia with identity 
* Microtropia without identity

**Comment by pnrobinson** [comment]
OK with definition
