### ISSUE TITLE
ENR-EYE NTR: Esodeviation

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2946]
[added] Added//Esodeviation; parent- Microtropia without identity [level: 10]; term- Esodeviation [level: 9]

**Comment by psergouniotis** [comment]
Esodeviation should be a subclass of Strabismus. It should have the following two subclasses:

Esophoria (On dissociation of the two eyes the occluded eye deviates nasally).
Esotropia (One or other eye deviates nasally when both eyes are open).

Definition for "Esodeviation": A manifest or latent ocular deviation in which one or other eye tends to deviate nasally.

**Comment by pnrobinson** [comment]
Adding term for Esodeviation and moving the other two terms.
