### ISSUE TITLE
ENR-EYE NTR: Esotropia

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2948]
[moved to…] HP:0000565//Strabismus//Moved to…//Esotropia//HP:0000486//Strabismus//new term request (PS); parent- Esophoria [level: 10]; term- Esotropia [level: 9]

**Comment by psergouniotis** [comment]
please see #2946

**Comment by psergouniotis** [comment]
As per spreadsheet, I propose the following subclasses of esotropia:

Accommodative esotropia
  | Fully accommodative esotropia
  | Partially accommodative esotropia
  | Convergence excess esotropia
Non-accomodative   esotropia
  | Infantile (constant) esotropia
  | Basic (constant) esotropia
  | Near esotropia
  | Distance esotropia
  | Cyclic esotropia
Secondary esotropia
Consecutive esotropia
Alternating esotropia

**Comment by pnrobinson** [comment]
Added this hierarchy for esotropia
