### ISSUE TITLE
ENR-EYE NTR: Accommodative esotropia

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2950]
[added] Added//Accommodative esotropia//new term request (PS); parent- Esotropia [level: 10]; term- Accommodative esotropia [level: 11]

**Comment by pnrobinson** [comment]
@psergouniotis  please reopn this issue if the following definition is not good!
Adding term with def
A form of esotropia (convergent deviation of the eyes) associated with activation of the accommodative reflex. 
Comment: Accommodative esotropia refers to strabismus (cross of the eyes) that occurs with focusing efforts of the eyes.

**Comment by psergouniotis** [comment]
definition looks good. 
alternative definition (as per BIOS):
A form of esotropia in which the convergent deviation is affected by the state of accommodation and this is a significant factor in the aetiology of the strabismus.

**Comment by psergouniotis** [comment]
synonyms: 
- Esotropia with an accommodative element
- Esotropia with an accommodative component
