### ISSUE TITLE
ENR-EYE NTR: Fully accommodative esotropia

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2951]
[added] Added//Fully accommodative esotropia//new term request (PS); parent- Accommodative esotropia [level: 11]; term- Fully accommodative esotropia [level: 12]

**Comment by pnrobinson** [comment]
@psergouniotis please provide definition

**Comment by psergouniotis** [comment]
proposed definition:
Esotropia in which normal binocular single vision is present for all distances when the hypermetropic refractive error is corrected.
