### ISSUE TITLE
ENR-EYE NTR: Patially accommodative esotropia

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2952]
[added] Added//Patially accommodative esotropia//new term request (PS); parent- Fully accommodative esotropia [level: 12]; term- Patially accommodative esotropia [level: 12]

**Comment by pnrobinson** [comment]
@psergouniotis please provide definition

**Comment by psergouniotis** [comment]
synonym: Constant esotropia with an accommodative element

A form of constant esotropia in which the angle of deviation is partly affected by accommodative effort.
