### ISSUE TITLE
ENR-EYE NTR: Convergence excess esotropia

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2953]
[added] Added//Convergence excess esotropia//new term request; definition: An intermittent esotropia with binocular single vision present at distance fixation but esotropia on accommodation for near fixation [BIOS 2012] (PS); parent- Patially accommodative esotropia [level: 12]; term- Convergence excess esotropia [level: 12]

**Comment by pnrobinson** [comment]
@psergouniotis please provide definition

**Comment by psergouniotis** [comment]
proposed definition:
An intermittent esotropia with binocular single vision present at distance fixation but esotropia on accommodation for near fixation. Usually associated with hypermetropia but patients can be emmetropic and rarely myopic. Associated with a high accommodative convergence/accommodation (AC/A) ratio.

I appreciate that this is a technical definition but this is quite a specific orthoptic term. Please let me know if you would like me to try to make it less accurate and more accessible.
