### ISSUE TITLE
ENR-EYE NTR: Non-accomodative esotropia

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2954]
[added] Added//Non-accomodative esotropia//new term request (PS); parent- Convergence excess esotropia [level: 12]; term- Non-accomodative esotropia [level: 11]

**Comment by pnrobinson** [comment]
@psergouniotis please provide definition

**Comment by psergouniotis** [comment]
proposed definition
A type of esotropia in which the angle of deviation is not affected by accommodative effort.
