### ISSUE TITLE
ENR-EYE NTR: Infantile (constant) esotropia

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2955]
[added] Added//Infantile (constant) esotropia//new term request (PS); parent- Non-accomodative esotropia [level: 11]; term- Infantile (constant) esotropia [level: 12]

**Comment by pnrobinson** [comment]
@psergouniotis please provide definition

**Comment by psergouniotis** [comment]
Proposed definition:
Constant esotropia occurring before 6 months of age. It is typically associated with a large angle of deviation, alternating fixation (therefore low risk of amblyopia) and poor potential for binocular single vision. Other features that might be present in individuals with infantile (constant) esotropia include latent nystagmus or manifest latent nystagmus, dissociated vertical divergence, cyclotropia, abnormal head posture, limited abduction.

**Comment by LCCarmody** [comment]
@psergouniotis Are "Infantile esotropia" and "Constant esotropia" synonyms?  Do we need the parenthesis in the term label?

**Comment by psergouniotis** [comment]
no they are not synonyms (not all infantile exotropias are constant and not all constant exotropias are infantile). 

both for esotropia and exotropia people would use the term infantile (or basic) not just to highlight the age of onset but also to refer specifically to a constant esotropia. this is why I have used parentheses.

**Comment by psergouniotis** [comment]
see also #2968

**Comment by pnrobinson** [comment]
adding definitions
