### ISSUE TITLE
ENR-EYE NTR: Basic (constant) esotropia

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2956]
[added] Added//Basic (constant) esotropia//new term request (PS); parent- Infantile (constant) esotropia [level: 12]; term- Basic (constant) esotropia [level: 12]

**Comment by psergouniotis** [comment]
Proposed definition: 
A form of convergent strabismus (esotropia) in which the deviation is present under all conditions (ie at all distances and at all times).

**Comment by pnrobinson** [comment]
done
