### ISSUE TITLE
ENR-EYE NTR: Distance esotropia

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2958]
[added] Added//Distance esotropia//new term request; synonym: Divergence insufficiency esotropia; definition: An intermittent esotropia where binocular single vision is present on near fixation and an esotropia on distance fixation [BIOS 2012] (PS); parent- Near esotropia [level: 12]; term- Distance esotropia [level: 12]

**Comment by pnrobinson** [comment]
@psergouniotis please provide definition

**Comment by pnrobinson** [comment]
@psergouniotis 
Is divergence insufficiency a synonym?
See https://jamanetwork.com/journals/jamaophthalmology/fullarticle/1558308
can we use the definition there?
Is Esotropia greater at distance another synonym?

**Comment by psergouniotis** [comment]
Possible definition for distance esotropia:
"An intermittent esotropia where binocular single vision is present on near fixation and an esotropia on distance fixation. Often associated with myopia and aging."

This might be controversial but as per Oxford Handbook of Ophthalmology "divergence insufficiency" should be a synonym of distance esotropia. 

Again some controversy here (I think the terms are used differently in the UK than in some parts of the US). I think it would be best to leave "Esotropia greater at distance" at this point.

**Comment by LCCarmody** [comment]
@pnrobinson @psergouniotis   Just to clarify: Distance esotropia is the label and "Divergence insufficiency" as _exact_synonym?  And do not include "Esotropia greater at distance" as a synonym at all?

**Comment by psergouniotis** [comment]
yes do not include "Esotropia greater at distance" as a synonym.

as above, the Oxford Handbook of Ophthalmology 2014 has "divergence insufficiency" as a synonym of distance esotropia. you can add it as a synonym at present although I appreciate that there might not be consensus around this.

**Comment by LCCarmody** [comment]
Maybe @pnrobinson can chime in but maybe this could be added as has_narrow_synonym or has_related_synonym?

**Comment by pnrobinson** [comment]
@LCCarmody let's go with this for now:
 Distance esotropia is the label and "Divergence insufficiency" as _exact_synonym? And do not include "Esotropia greater at distance" as a synonym at all?
We can always add the other term as a related synonym if there are requests.
