### ISSUE TITLE
ENR-EYE NTR: Secondary esotropia

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2960]
[added] Added//Secondary esotropia//synonym: Sensory esotropia (PS); parent- Cyclic esotropia [level: 12]; term- Secondary esotropia [level: 11]

**Comment by psergouniotis** [comment]
see also #2974, #2975, #2961

consider adding this as a subclass of "Esotropia".

proposed definition for "secondary esotropia": Convergent squint which follows loss or impairment of vision. 
proposed synonym for "secondary esotropia": "sensory esotropia" (consider using this as primary term and having "secondary esotropia as a synonym)

(definition from BIOS 2012)
