### ISSUE TITLE
ENR-EYE NTR: Consecutive esotropia

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2961]
[added] Added//Consecutive esotropia//new term request; definitino: Esotropia in a patient who has previously had exotropia or exophoria. (PS); parent- Secondary esotropia [level: 11]; term- Consecutive esotropia [level: 11]

**Comment by pnrobinson** [comment]
@psergouniotis please provide definition

**Comment by psergouniotis** [comment]
Definition as per BIOS:
"Esotropia in a patient who has previously had exotropia or exophoria"
