### ISSUE TITLE
ENR-EYE NTR: Exodeviations

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2963]
[No action] Exodeviations; parent- Alternating esotropia [level: 11]; term- Exodeviations [level: 9]

**Comment by pnrobinson** [comment]
@psergouniotis
I think this was just a comment on the ERN file. Please reopen if an action is required.

**Comment by psergouniotis** [comment]
Exodeviation should be a subclass of Strabismus. It should have the following two subclasses:
- Exophoria (On dissociation of the two eyes the occluded eye deviates temporally)
- Exotropia (One or other eye deviates temporally when both eyes are open)

Definition for "Exodeviation": A manifest or latent ocular deviation in which one or other eye tends to deviate temporally.

**Comment by pnrobinson** [comment]
added term and moved subclasses as suggested
