### ISSUE TITLE
ENR-EYE NTR: Exophoria

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2964]
[moved here] Moved here!//Exophoria; parent- Exodeviations [level: 9]; term- Exophoria [level: 10]

**Comment by pnrobinson** [comment]
@psergouniotis
-- please clarify the structure. Do we need a term or Exodeviation?

**Comment by psergouniotis** [comment]
please see #2963

**Comment by pnrobinson** [comment]
done
