### ISSUE TITLE
ENR-EYE NTR: Exotropia

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2965]
[moved to…] HP:0000577//Strabismus//Moved to…//Exotropia//HP:0000486//Strabismus; parent- Exophoria [level: 10]; term- Exotropia [level: 9]

**Comment by pnrobinson** [comment]
from #2966 [moved here] Moved here!//Exotropia; parent- Exotropia [level: 9]; term- Exotropia [level: 10]

**Comment by psergouniotis** [comment]
please also see #2963

**Comment by psergouniotis** [comment]
As per spreadsheet I propose the following subclasses of exotropia:

Constant exotropia
  | Infantile (constant) exotropia
  | Basic (constant) exotropia
Distance   exotropia
  | True distance exotropia
  | Simulated distance exotropia
Near   exotropia
Secondary   exotropia
Consecutive   exotropia
Congenital   exotropia
Alternating   exotropia
Cyclic   exotropia

**Comment by pnrobinson** [comment]
This is now implemented.
