### ISSUE TITLE
ENR-EYE NTR: Constant exotropia

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2967]
[added] Added//Constant exotropia//new term request (PS); parent- Exotropia [level: 10]; term- Constant exotropia [level: 11]

**Comment by pnrobinson** [comment]
Adding term with definition
A form of divergent strabismus (exotropia) in which the eye turns outward at all distances and at all times.
(@psergouniotis please reopen issue if the definition needs revision!)

**Comment by psergouniotis** [comment]
The BIOS dictionary (2012) defines constant exotropia as exotropia that is present under all conditions.

Consider therefore the following definition:
A form of divergent strabismus (exotropia) in which the deviation is present under all conditions (ie at all distances and at all times).
