### ISSUE TITLE
ENR-EYE NTR: Infantile (constant) exotropia

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2968]
[added] Added//Infantile (constant) exotropia//new term request (PS); parent- Constant exotropia [level: 11]; term- Infantile (constant) exotropia [level: 12]

**Comment by LCCarmody** [comment]
Duplicate.  Same as #2955.  Close.

**Comment by psergouniotis** [comment]
This is exotropia, #2955. is esotropia.

Proposed definition: Constant exotropia occurring before 6 months of age.; often associated with a large angle of deviation and ocular/CNS abnormalities.

**Comment by LCCarmody** [comment]
Ooops.  Reopened issue.

**Comment by pnrobinson** [comment]
@psergouniotis 
HP_0031713 has "Constant exotropia". Definition: A form of divergent strabismus (exotropia) in which the eye turns outward at all distances and at all times.
Is this correct and is Infantile (constant) exotropia or Basic (constant) exotropia the same thing?

**Comment by psergouniotis** [comment]
I do not think that there is widespread consensus about these terms. I would propose the following:
* keep "constant exotropia" as a subclass of "exotropia".
* move "basic constant exotropia" & infantile constant exotropia" as subclasses of "constant exotropia"
This is in keeping with OHO 2014 (p.750)

* add "constant esotropia" as a subclass of "non-accomodative esotropia".
* move "basic constant esotropia" & infantile constant esotropia" as subclasses of "constant esotropia"
This is in keeping with OHO 2014 (p.745)

Typically "infantile" suggests presentation at ≤6 months of age, while "basic" suggests later presentation (>6-12 months). (OHO 745 & 750)

**Comment by pnrobinson** [comment]
adding term

**Comment by psergouniotis** [comment]
Just to check, it would be great if the relevant terms were moved to the appropriate positions in the hpo tree (as per previous comment). Please let me know if something is unclear/counterintuitive and/or if you need definitions.

**Comment by pnrobinson** [comment]
I did make these changes!
