### ISSUE TITLE
ENR-EYE NTR: Distance exotropia

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2970]
[added] Added//Distance exotropia//new term request; synonym: divergence excess exotropia; definition: An intermittent exotropia where there is binocular single vision on near fixation and exotropia (intermittent or constant) on distance fixation [BIOS 2012]. (PS); parent- Basic (constant) exotropia [level: 12]; term- Distance exotropia [level: 11]

**Comment by pnrobinson** [comment]
I am adding the term with the following definition
A type of divergent strabismus (exotropia) in which an eye tends to turn outwards (i.e., the eye squints) mainly when looking at distant objects. The eyes tend to remain straight when they look at near objects. Distance exotropia may be constant or intermittant.
(@psergouniotis please reopen issue if the definition needs revision!)

**Comment by psergouniotis** [comment]
The BIOS dictionary (2012) defines Distance exotropia as
"An intermittent exotropia where there is binocular single vision on near fixation and exotropia (intermittent or constant) on distance fixation".
There is no consensus in the community on the definition but I would recommend the following:

A type of divergent strabismus (exotropia) in which there is is binocular single vision on near fixation and
exotropia (intermittent or constant) on distance fixation.
