### ISSUE TITLE
ENR-EYE NTR: True distance exotropia

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2971]
[added] Added//True distance exotropia//new term request (PS); parent- Distance exotropia [level: 11]; term- True distance exotropia [level: 12]

**Comment by pnrobinson** [comment]
@psergouniotis please provide a definition

**Comment by psergouniotis** [comment]
Proposed definition 
Exotropia (intermittent or constant) on distance fixation with binocular single vision on near fixation under all testing conditions. The accommodative convergence/accommodation (AC:A) ratio is within normal limits.

I appreciate that this is a technical definition but these are specialist terms. Please let me know if you would like me to try to simplify them (although there might be a trade-off with accuracy).

**Comment by pnrobinson** [comment]
I agree that the definition is hard to simplify, but the definition of exotropia itself is good for non-sepcialisits, so this should be OK!
