### ISSUE TITLE
ENR-EYE NTR: Simulated distance exotropia

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2972]
[added] Added// //Simulated distance exotropia//new term request (PS); parent- True distance exotropia [level: 12]; term- Simulated distance exotropia [level: 12]

**Comment by pnrobinson** [comment]
@psergouniotis please provide definition

**Comment by psergouniotis** [comment]
Proposed definition
Exotropia (intermittent or constant) worse for distance fixation in which the near angle of deviation increases (or near exophoria becomes exotropia) with: (1) prolonged disruption of fusion and/or (2) elimination of accommodation.

**Comment by pnrobinson** [comment]
added definition.
