### ISSUE TITLE
ENR-EYE NTR: Secondary exotropia

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2974]
[added] Added//Secondary exotropia//synonym: Sensory exotropia (PS); parent- Near exotropia [level: 11]; term- Secondary exotropia [level: 11]

**Comment by pnrobinson** [comment]
done

**Comment by psergouniotis** [comment]
see also #2960

consider adding this as a subclass of "Exotropia".

proposed definition for "secondary exotropia": Divergent squint which follows loss or impairment of vision. 
proposed synonym for "secondary exotropia": "sensory exotropia" (consider using this as primary term and having "secondary exotropia as a synonym)

(definition from BIOS 2012)
