### ISSUE TITLE
ENR-EYE NTR: Consecutive exotropia

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2975]
[added] Added//Consecutive exotropia//new term request; definition: Exotropia in a patient who has previously had esotropia or esophoria. (PS); parent- Secondary exotropia [level: 11]; term- Consecutive exotropia [level: 11]

**Comment by pnrobinson** [comment]
added term

**Comment by psergouniotis** [comment]
Definition as per BIOS:
Exotropia in a patient who has previously had esotropia or esophoria.
