### ISSUE TITLE
ENR-EYE NTR: Congenital exotropia

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2976]
[suppressed] HP:0008033//Exotropia//Suppressed// //Congenital exotropia//HP:0000577//Exotropia//congenital should be added as a modifier (PS); parent- Consecutive exotropia [level: 11]; term- Congenital exotropia [level: 11]

**Comment by pnrobinson** [comment]
This term is used to annotate only one disease
https://omim.org/entry/133705?search=133705&highlight=133705
I think it is probably OK to replace the label by "Infantile Exotropia ", which is defined as A divergent strabismus that begins during the first 6 months of life.
However, the suggested term is Infantile (constant) exotropia. -- Is it certain that all infantile exotropia is constant?
@psergouniotis please comment

**Comment by psergouniotis** [comment]
I had a look at the omim entry. I agree, "Congenital exotropia" can be suppressed and the relevant omim link merged with infantile (constant) exotropia.

Further to your question. Others might disagree with this but my intention here is to have the term "Infantile (constant) exotropia". A definition for this could be:
"Constant exotropia (ie divergent strabismus present under all conditions) occurring before 6 months of age.".

Not all Infantile exotropias will be Infantile (constant) exotropias but most will be. I do not think that we should introduce a term "Infantile exotropia" though. For this, the user can select "exotropia" and the relevant modifier.

If you think "Infantile constant exotropia" would be clearer than"Infantile (constant) exotropia" then fine by me to have one as primary term and the other as synonym. Same applies for "Basic (constant) exotropia" "Infantile (constant) esotropia" and "Basic (constant) esotropia"

**Comment by pnrobinson** [comment]
I have re-annotated the disease OMIM:133705 and am obsoleting this term.
