### ISSUE TITLE
ENR-EYE NTR: Double elevator palsy

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2982]
[added] Added//Double elevator palsy//new term request; shoud this be a subclass here? (PS); parent- Incomitant strabismus [level: 9]; term- Double elevator palsy [level: 10]

**Comment by psergouniotis** [comment]
proposed definition for Double elevator palsy: An ocular movement abnormality characterised by simultaneous weakness of the inferior oblique and superior rectus muscles of the same eye 
(https://www.aao.org/bcscsnippetdetail.aspx?id=38fd04e9-18d1-470f-a3ee-727b48f88ef4)

please see also comment on #2983

**Comment by pnrobinson** [comment]
@psergouniotis  I have modified the definition slightly to help for non-ophthalmologists. Please reopen if this is not OK
A type of incomitant strabismus in which both elevator muscles (i.e., the inferior oblique and superior rectus muscles) of the same eye are weak leading to restricted elevation and hypotropia.
