### ISSUE TITLE
ENR-EYE NTR: Double depressor palsy

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2983]
[added] Added//Double depressor palsy//new term request; shoud this be a subclass here? (PS); parent- Double elevator palsy [level: 10]; term- Double depressor palsy [level: 10]

**Comment by pnrobinson** [comment]
@psergouniotis please provide a definition.
Should we be adding Duane anomaly as a subclass of this term?

**Comment by psergouniotis** [comment]
As per spreadsheet, I propose the following subclasses of Strabismus:
* cyclodeviation
* hyperdeviation
* hypodeviation
* microtropia
* esodeviation
* exodeviation
* concomitant strabismus (renamed comitant strabismus)
* incomitant strabismus
* neurogenic strabismus
* mechanical strabismus
* myasthenic stabismus
* myopathic stabismus.

Double depressor palsy should be a subclass of incomitant strabismus (other subclasses of incomitant strabismus: 
* Double elevator palsy
* Double depressor palsy
* Duane anomaly (needs discussion in a different thread)
* Brown anomaly
* A pattern ocular deviation
* V pattern ocular deviation

**Comment by psergouniotis** [comment]
Duane anomaly should not be a subclass of this term.
Definition for Double depressor palsy: An ocular movement abnormality characterised by simultaneous weakness of the inferior rectus muscle and superior oblique muscle of the same eye.
