### ISSUE TITLE
ENR-EYE NTR: Vertically incomitant strabismus

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2986]
[added] Added//Vertically incomitant strabismus//new term request (PS); parent- Brown syndrome [level: 10]; term- Vertically incomitant strabismus [level: 10]

**Comment by pnrobinson** [comment]
@psergouniotis can you please help with the definition? Is there a good reference for this group of terms?

**Comment by psergouniotis** [comment]
I would recommend adding Incomitant strabismus:
definition (BIOS): Strabismus in which the angle of deviation differs depending upon the direction of gaze or according to which eye is fixing, associated with: (i) defective movement of the eye, (ii) asymmetrical accommodative effort.

You can have as subclasses of Incomitant strabismus the following:
Double elevator palsy
Double depressor palsy
Duane anomaly
  | Divergent Duane anomaly
  | Convergent Duane anomaly
Brown   anomaly
Vertically incomitant strabismus 
  | A   pattern ocular deviation
  | V   pattern ocular deviation
Horizontally incomitant strabismus

Def for Vertically incomitant strabismus:  A type of incomitabt strabismus in which the angle of deviation varies as the patient's gaze shifts upwards and/or downwards.

**Comment by pnrobinson** [comment]
@psergouniotis  SHould we be adding terms for  Divergent Duane anomaly and Convergent Duane anomaly as well as  A pattern ocular deviation and V pattern ocular deviation? All of the other terms have been added.

**Comment by psergouniotis** [comment]
Yes, please. 

"Divergent Duane anomaly" and "Convergent Duane anomaly" should be added as subclasses of "Duane anomaly".

"A pattern ocular deviation" and "V pattern ocular deviation" should be added as subclasses of "Vertically incomitant strabismus"
