### ISSUE TITLE
ENR-EYE NTR: Congenital nuclear cataract

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2997]
[suppressed] HP:0008024//Congenital cataract//Suppressed//Congenital nuclear cataract//HP:0000519//Congenital cataract//suboptimal term; can be described using other HPO terms (PS); parent- Nonnuclear polymorphic congenital cataract [level: 11]; term- Congenital nuclear cataract [level: 11]

**Comment by psergouniotis** [comment]
please consider making the recommended change and closing this issue. many thanks

**Comment by pnrobinson** [comment]
There were four diseases that were annotated to this term (including some slightly inaccurate annotations). I have revised the annotations and will now obsolete this term.
