### ISSUE TITLE
ENR-EYE NTR: Juvenile zonular cataracts

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2998]
[suppressed] HP:0007713//Juvenile cataract//Suppressed//Juvenile zonular cataracts//HP:0001118//Juvenile cataract//suboptimal term; can be described using other HPO terms (PS); parent- Juvenile cataract [level: 10]; term- Juvenile zonular cataracts [level: 11]

**Comment by pnrobinson** [comment]
@nicolevasilevsky Let's do this example today with PhenoteFX
The suggestions is that the HPO term "Juvenile zonular cataracts" should be obsoleted. I agree with this. Currently, the term is used to annotate only one disease
http://compbio.charite.de/hpoweb/showterm?id=HP:0007713
Here is some background
https://www.ncbi.nlm.nih.gov/pubmed/11471165
Can you access this article?

**Comment by pnrobinson** [comment]
The definition of pseudophakia would be having an artificial lens implanted after the natural eye lens has been removed.
@psergouniotis @drseb @cmungall @mellybelly  I am not sure where to place this in the hierarchy--currently we do not have surgical phenotypes but I agree this is needed. Please comment

**Comment by nicolevasilevsky** [comment]
@pnrobinson sounds good! Yes, I can access the article, I'll look through it.

**Comment by psergouniotis** [comment]
"Juvenile zonular cataracts" should be obsoleted as it can be expressed using:
* juvenile cataract (HP:0001118) and 
* zonular cataract (HP:0010920)

After checking the above article, I would move the content to both juvenile cataract (HP:0001118) and zonular cataract (HP:0010920).

on a different note, there is a term pseudophakia already (HP:0500081)

**Comment by pnrobinson** [comment]
I have reannotated the one disease with this to have Zonular cataract and Juvenile onset. I will now merge the term.
