### ISSUE TITLE
in vitro fertilization

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/human-phenotype-ontology#300]
We need a way to indicate when a person was conceived using in vitro fertilization. 
This is a process, not a phenotype, and as such doesn't really belong in the HPO - another case for being able to mireot in classes. There is a class in ERO: 

Term IRI: http://purl.obolibrary.org/obo/ERO_0000703
definition: A culture and propogation technique performed in vitro to the fuse of gametes to produce a new organism.

Perhaps add to HPO a 'Clinical history' or 'Clinical manipulations' (or some such) root with an Xref for now? What do you think? This is needed for the UDP.

Reported by: @mellybelly

Original Ticket: [obo/human-phenotype-requests/300](https://sourceforge.net/p/obo/human-phenotype-requests/300)

**Comment by pnrobinson** [comment]
Something like this will be extremely important for the precision/common medicine project. We should think hard about how to implement this!

Dr. med. Peter N. Robinson, MSc.
Professor of Medical Genomics
Institut für Medizinische Genetik und Humangenetik
Charité - Universitätsmedizin Berlin
Augustenburger Platz 1
13353 Berlin
Germany
+4930 450566006
Mobile: 0160 93769872
peter.robinson@charite.de
http://compbio.charite.de
http://www.human-phenotype-ontology.org
Introduction to Bio-Ontologies: http://www.crcpress.com/product/isbn/9781439836651

Von: obophenotype-user [mailto:notifications@github.com]
Gesendet: Freitag, 16. Oktober 2015 16:05
An: obophenotype/human-phenotype-ontology
Cc: Robinson, Peter
Betreff: Re: [human-phenotype-ontology] in vitro fertilization (#300)


@pnrobinson<https://github.com/pnrobinson>
This (see http://www.med-ed.virginia.edu/courses/pom1/pexams/hpexam/THE%20PAST%20MEDICAL%20HISTORY_HO.htm) is the structure of a typical clinical interview (probably about ten other items could be added). In a very broad sense, the medical phenotype of a patient includes the PMH, which comprises any information that might have an influence on the current illness. Therefore, it would be useful to have an ontological structure to capture this information, although it will require a lot of thought on how to model many of the items mentioned below (if we want to link out to other ontologies). If it would be helpful for the UDP right now, we could start off with a simple is-a hierarchy and then begin to worry about adding semantic links when the need arises.

Past Medical History

Major illnesses, beginning in childhood

Hospitalizations

Surgeries

Significant injuries

Medications

Allergies

Immunizations

Transfusions

Gynecologic and obstetric (women)

Psychiatric history

**Comment by pnrobinson** [comment]
I transferred this material to the wiki on this github repository.
