### ISSUE TITLE
ENR-EYE NTR: Subcapsular cataract

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3002]
[moved to…] HP:0000523//Polar cataract//Moved to…//Subcapsular cataract//HP:0010696//Polar cataract; parent- Polar cataract [level: 10]; term- Subcapsular cataract [level: 11]

**Comment by pnrobinson** [comment]
@psergouniotis  not sure what the suggestion is. Subcapsular cataract is already a subclass of Polar cataract

**Comment by psergouniotis** [comment]
pleasse see #3003

**Comment by pnrobinson** [comment]
done
