### ISSUE TITLE
ENR-EYE NTR: Posterior subcapsular cataract

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3003]
[moved to…] HP:0007787//Subcapsular cataract//Moved to…//Posterior subcapsular cataract//HP:0000523//Subcapsular cataract; parent- Subcapsular cataract [level: 11]; term- Posterior subcapsular cataract [level: 12]

**Comment by pnrobinson** [comment]
@psergouniotis
I do not understand the suggestion.
Posterior subcapsular cataract is already a subterm of Subcapsular cataract

**Comment by psergouniotis** [comment]
The issue is not with Posterior subcapsular cataract being a subterm of Subcapsular cataract.

The recommended change is about changing the parent term of Subcapsular cataract from "Polar cataract" (incorrect) to "Cataract".

**Comment by pnrobinson** [comment]
OK I have moved the term.
