### ISSUE TITLE
ENR-EYE NTR: Iridescent posterior subcapsular cataract

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3004]
[moved to…] HP:0007889//Posterior subcapsular cataract//Moved to…// //Iridescent posterior subcapsular cataract//HP:0007787//Posterior subcapsular cataract; parent- Posterior subcapsular cataract [level: 12]; term- Iridescent posterior subcapsular cataract [level: 13]

**Comment by pnrobinson** [comment]
@psergouniotis
I do not understand the suggestion.
Iridescent posterior subcapsular cataract is already a subterm of HP:0007935/Posterior subcapsular cataract

**Comment by psergouniotis** [comment]
The suggestion is to move "Subcapsular cataract" as a subclass of "Cataract" (it is presently a subclass of "Polar cataract" which is incorrect)
Please see #3005

**Comment by pnrobinson** [comment]
done
