### ISSUE TITLE
ENR-EYE NTR: Juvenile posterior subcapsular lenticular opacities

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3005]
[moved to…] HP:0007935//Posterior subcapsular cataract//Moved to…//Juvenile posterior subcapsular lenticular opacities//HP:0007787//Posterior subcapsular cataract; parent- Iridescent posterior subcapsular cataract [level: 13]; term- Juvenile posterior subcapsular lenticular opacities [level: 13]

**Comment by pnrobinson** [comment]
@psergouniotis
I do not understand the suggestion.
Juvenile posterior subcapsular lenticular opacities is already a subterm of  HP:0007935/Posterior subcapsular cataract

**Comment by psergouniotis** [comment]
The suggestion is to move "Posterior subcapsular cataract" (and all its subclasses) as a subclass of "Subcapsular cataract" (instead of the current incorrect "Polar cataract")

**Comment by pnrobinson** [comment]
OK. This is now correct
