### ISSUE TITLE
ENR-EYE NTR: Anterior subcapsular cataract

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3006]
[moved to…] HP:0010923//Subcapsular cataract//Moved to…//Anterior subcapsular cataract//HP:0000523//Subcapsular cataract; parent- Juvenile posterior subcapsular lenticular opacities [level: 13]; term- Anterior subcapsular cataract [level: 12]

**Comment by pnrobinson** [comment]
@psergouniotis
I do not understand the recommendation for placement of Anterior subcapsular cataract or Posterior subcapsular cataract
-- please advise! What is the correct parent ? Now it is "Subcapsular cataract", which seems correct?

**Comment by psergouniotis** [comment]
The comment is about moving "Subcapsular cataract" (and its subclasses) from a subclass of "Polar cataract" (current; incorrect) to a subclass of "Cataract" (desirable). 

The current parent term for Anterior subcapsular cataract or Posterior subcapsular cataract ("Subcapsular cataract") is correct

**Comment by pnrobinson** [comment]
term was moved.
