### ISSUE TITLE
ENR-EYE NTR: Coronary cataract

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3011]
[added] Added//Coronary cataract//new term request (PS); parent- Zonular cataract [level: 10]; term- Coronary cataract [level: 11]

**Comment by pnrobinson** [comment]
@psergouniotis
Is this a good definition?

A type of cataract in which opacities are distributed in a radial pattern that surrounds the nucleus of the lens and is said to resemble a crown (corona in Latin). The opacities may appear gray, brown, yellow, red or blue.

**Comment by psergouniotis** [comment]
proposed def: Round opacities in the deep lens cortex forming a ‘crown’.
