### ISSUE TITLE
ENR-EYE NTR: Lamellar cataract with riders

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3020]
[added] Added//Lamellar cataract with riders//new term request (PS); parent- Lamellar cataract [level: 11]; term- Lamellar cataract with riders [level: 12]

**Comment by pnrobinson** [comment]
@psergouniotis
Is this a good definition?
A type of lamellar cataract in which there are small linear opacities in the lens that resemble spokes of a wheel (riders) and that radiate towards the equator (periphery of the lens).

**Comment by psergouniotis** [comment]
proposed def: Lamellar cataracts with associated linear lens opacities radially extending towards the periphery of the lens.
