### ISSUE TITLE
ENR-EYE NTR: Total cataract

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3036]
[suppressed] HP:0010700//Cataract//Suppressed//Total cataract//HP:0000518//Cataract//suboptimal/vague term (PS); parent- Coralliform cataract [level: 11]; term- Total cataract [level: 10]

**Comment by pnrobinson** [comment]
@psergouniotis  this term appears to be in common use, e.g., https://medical-dictionary.thefreedictionary.com/total+cataract
Please comment on suggested suppression of the term.

**Comment by psergouniotis** [comment]
I feel that this is a suboptimal/vague term to describe a significant amount of lens opacification. I think it would be best to obsolete this term and use a modifier instead.

**Comment by psergouniotis** [comment]
please consider making the above change and closing this issue.

**Comment by pnrobinson** [comment]
reannotate -- https://hpo.jax.org/app/browse/disease/OMIM:116600

**Comment by pnrobinson** [comment]
done --
