### ISSUE TITLE
ENR-EYE NTR: Ectopia lentis

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3044]
[No action] HP:0001083//Abnormality of the lens//Ectopia lentis//HP:0000517//Abnormality of the lens; parent- Posterior capsular cataract [level: 11]; term- Ectopia lentis [level: 9]

**Comment by Frank-Probst** [comment]
I don't think this is always related to a posterior capsular cataract.  The lay term would be "dislocation of the lens" or "abnormal location of the lens".  In genetics, it's most often associated with Marfan syndrome and homocystinuria.

**Comment by pnrobinson** [comment]
As mentioned, the format of the ERN issues is complicated. This term is not related to posterior capsular cataract. No action needed.
