### ISSUE TITLE
ENR-EYE NTR: Congenital primary aphakia

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3050]
[renamed] HP:0007707//Aplasia/Hypoplasia of the lens//Renamed//Congenital primary aphakia//HP:0008063//Aplasia/Hypoplasia of the lens//Primary aphakia//congenital can be used as a modifier; note that primary suggests a diagnosis (so not completely appropriate for HPO); also add as a subclass of the newly proposed term Aphakia (PS), ; parent- Aplasia/Hypoplasia of the lens [level: 9]; term- Congenital primary aphakia [level: 10]

**Comment by pnrobinson** [comment]
@psergouniotis Should we just have a term called "Aphakia" and leave the "Congenital primary aphakia" as a disease then?

**Comment by psergouniotis** [comment]
"Aphakia" should be added as an "abnormality of the lens".

Possible def: Absence of the crystalline lens of the eye, typically associated with surgical removal or ocular maldevelopment. 

"Congenital primary aphakia" should be a disease and please consider suppressing this term.

**Comment by pnrobinson** [comment]
Currently, this term is being used to annotated Congenital primary aphakia and I think we can just change the term label. I see that it is also listed as annotating Bardet Biedl Syndrome type 1, which is a mistake.
I have changed the label to Aphakia. This is currently under Aplasia/Hypoplasia of the lens, so the surgical form of aphakia woiuld need to be coded differently.

**Comment by psergouniotis** [comment]
Agree. If the term is renamed to aphakia, then it should be a subclass of "Abnormality of the lens" (rather than a subclass of "Aplasia/Hypoplasia of the lens". It is not ideal but perhaps best of two evils

**Comment by LCCarmody** [comment]
@psergouniotis This term is listed in this hierarchy:
-Abnormality of the lens
   --Aplasia/hypoplasia of the lens
      --- Aphakia
Do you still want this to be a child of "Abnormality of the lens" and sibling to "Aplasia/hypoplasia of the lens"?

**Comment by psergouniotis** [comment]
Yes please. 

Aphakia should be a subclass of "Abnormality of the lens" (and not of "Aplasia/hypoplasia of the lens").

Also, pseudophakia should be a subclass of "Abnormality of the lens" (and not of "Aphakia")

**Comment by pnrobinson** [comment]
make aphakia and pseudophakia sibs of Apl/Hypopl

**Comment by pnrobinson** [comment]
@psergouniotis  Sorry -- I am confused. We now have a term called Aphakia, which is being used to annotate diseases with congenital aphakia. SHould we call this Lens agenesis with exact synonym congenital aphakia? ANd then make a new term for surgical aphakia?

**Comment by psergouniotis** [comment]
sounds like a good solution:
* "Lens agenesis" to be an exact synonym of "congenital aphakia" (this should be a subclass of "aplasia/hypoplasia of the lens")
* the term "surgical aphakia" to be added as a subclass of "Abnormality of the lens" 
* the term pseudophakia to be a subclass of "Abnormality of the lens" (and not of "Aphakia")
