### ISSUE TITLE
ENR-EYE NTR: Irido-fundal coloboma

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3063]
[suppressed] HP:0007748//Iris coloboma//Suppressed//Irido-fundal coloboma//HP:0000612//Iris coloboma//see comments above on this//see earlier comment; parent- Iridoretinal coloboma [level: 10]; term- Irido-fundal coloboma [level: 10]

**Comment by pnrobinson** [comment]
@psergouniotis 
The recommendation is therefore to obsolete this term?
This is a bundled term. 
 iris coloboma plus retinal coloboma (2 HPO terms)
The term
is being used to annotate the following three diseases in our corpus
In all cases it seems this is a bundled term and we should reannotate.
I will do so shortly.
* https://omim.org/entry/611638 (Microphthalmia with coloboma 5 )
* https://omim.org/entry/120200 (Ocular coloboma, PAX6)
* https://omim.org/entry/613702 (Klippel-Feil syndrome 3, autosomal dominant )

**Comment by psergouniotis** [comment]
Yes - my issue with this is that it is a bundled, not very useful term; the same applies to  "iridoretinal coloboma" (also incorrectly included as a subclass of iris coloboma). I would propose suppressing these  two terms and reannotating the content either on a case by case basis or (perhaps preferably) to "Coloboma" [HP:0000589]

**Comment by pnrobinson** [comment]
Reannotated 611638, 120200, 613702 and added the correct annotations.
Obsoleted the the term. I will now work on iridoretinal coloboma

**Comment by pnrobinson** [comment]
For iridoretinal coloboma,
I have reannotated
KAPUR-TORIELLO SYNDROME
and 
STEINFELD SYNDROME
and will obsolete the term
