### ISSUE TITLE
ENR-EYE NTR: Asymmetry of iris pigmentation

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3082]
[No action] HP:0200064//Abnormal iris pigmentation//Asymmetry of iris pigmentation//HP:0008034//Abnormal iris pigmentation; parent- Iris transillumination defect [level: 10]; term- Asymmetry of iris pigmentation [level: 10]

**Comment by pnrobinson** [comment]
@psergouniotis 
Is this actually a synonym of heterochromia iridis? If not, should the latter be a subclass of the former?

**Comment by psergouniotis** [comment]
"Asymmetry of iris pigmentation" is linked to two omim terms as per HPO browser. One suggests asymmetry between the two irides (OMIM:142500), while the other could suggest asymmetry between different parts of one iris (ORPHA:158000).

Perhaps "Asymmetry of iris pigmentation" should be a superclass of "Heterochromia iridis".

As per Kaski 2016 textbook:  Heterochromia iridis refers to a difference in colour between the iris of the two eyes.
