### ISSUE TITLE
ENR-EYE NTR: Iris nevus

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3087]
[No action] HP:0011525//Abnormality of the iris//Iris nevus//HP:0000525//Abnormality of the iris; parent- Iris melanoma [level: 9]; term- Iris nevus [level: 9]

**Comment by Frank-Probst** [comment]
I don't think "iris nevus" and "iris melanoma" are the same.  "Iris nevus" is what I think of as an "iris freckle".  "Iris melanoma" implies a malignant cancer (melanoma) originating from the iris.

**Comment by pnrobinson** [comment]
@Frank-Probst sorry, the format of the ERN EYE requests is confusing -- let's talk about this by skype!

**Comment by pnrobinson** [comment]
All is OK, iris nevus is a sibling of iris melanoma
