### ISSUE TITLE
ENR-EYE NTR: Anterior chamber flare

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3091]
[added] Added//Anterior chamber flare//new term request (PS); should this be also a subclass of anterior uveitis? Should this be under abnormal eye morphology?; parent- Abnormality of the anterior chamber [level: 8]; term- Anterior chamber flare [level: 9]

**Comment by pnrobinson** [comment]
@psergouniotis
Adding with definition
An abnormal appearance of the beam of light traveling through the anterior chamber of the eye in a slit lamp examination. The flare ius produced by an increased concentration of proteins in the aqueous humor in the anterior chamber.

**Comment by psergouniotis** [comment]
great. please consider adding the grades of flare as per recommendation in the spreadsheet and SUN consensus (https://www.ncbi.nlm.nih.gov/pubmed/16196117)

**Comment by pnrobinson** [comment]
Yes, I took the classification from that publication and have now added the xrefs to the terms!
