### ISSUE TITLE
ENR-EYE NTR: Anterior chamber cells

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3097]
[added] Added//Anterior chamber cells//new term request (PS); parent- Anterior chamber flare grade 4+ [level: 10]; term- Anterior chamber cells [level: 9]

**Comment by pnrobinson** [comment]
@psergouniotis
Should this term be for anterior chamber or anterior segment?

Can we use this as part of the definition? If so should the definition be "increased" cell count in the anterior chamber?
Inflammation in the anterior segment of the eye causes breakdown of the blood–aqueous barrier and results in an increase in the number of cells and the protein concentration of the aqueous humor. [PMID:23249705]

**Comment by psergouniotis** [comment]
The consensus (SUN) is to use "Anterior chamber cells" (http://www.ajo.com/article/S0002-9394(05)00407-1/fulltext)

proposed definition for "Anterior chamber cells": Tiny deposits corresponding to cells floating in the anterior chamber of the eye. This appearance is typically associated with intraocular inflammation leading to breakdown of the blood–aqueous barrier and resulting in an increase in the number of cells and in the aqueous humor.  Grading (SUN Working Group) is performed by estimating the number of cells in a 1 mm by 1 mm slit beam field, employing adequate light intensity and magnification on a slit lamp.

**Comment by pnrobinson** [comment]
Added the definition.
I could not open the link to the article but I think it is this
https://www.ncbi.nlm.nih.gov/pubmed/16196117
if this is not true then please reopen the issue.
