### ISSUE TITLE
ENR-EYE NTR: Anterior chamber inflammatory cells

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3104]
[added] Added//Anterior chamber inflammatory cells//new term request (PS); should this be also a subclass of anterior uveitis? Should this be under abnormal eye morphology?; parent- Anterior chamber cells grade 4+ [level: 10]; term- Anterior chamber inflammatory cells [level: 10]

**Comment by pnrobinson** [comment]
@psergouniotis

Shouldn't this be the same thing as "Anterior chamber cells"?  I do not understand where to put this one.

**Comment by psergouniotis** [comment]
"Anterior chamber cells" and "Anterior chamber inflam cells" is not the same (although it is often used interchangeably. One may or may not be certain that the cells they are seeing in the anterior chamber are of inflammatory origin. This is why I propose to have 
* "Anterior chamber inflammatory cells" and 
"Anterior chamber red blood cells"
as subclasses of "Anterior chamber cells". 
The different grading should also be subclasses of "Anterior chamber cells".

**Comment by pnrobinson** [comment]
So the grading is for whatever cells? But then wouldnt an investigator know what kind of cells they are in the end?

**Comment by psergouniotis** [comment]
The grading is for inflammation but sometimes it can be hard to distinguish the one from the other. A purist (I am not one) could select the grade and then specify that there are inflammatory by selecting the "Anterior chamber inflammatory cells". 

The reason why it is useful to have "Anterior chamber inflammatory cells" and "Anterior chamber red blood cells" is the scenario where you have both (a common occurrence after trauma). In this situation you may want to:
(i) grade the cells (hoping you are only counting inflam cells) and 
(ii) specify that you have both "Anterior chamber inflammatory cells" and "Anterior chamber red blood cells".

**Comment by pnrobinson** [comment]
OK that makes sense. I am adding the terms.

**Comment by pnrobinson** [comment]
I am adding this as a comment
The terms for anterior chamber cells can be used to select the grade (total number of cells) and then Anterior chamber red blood cells or inflammatory cells can be chosen to specificy whether one or both cells are present. In some scenarios, both cell types may be observed, e.g., followiong trauma.
