### ISSUE TITLE
ENR-EYE NTR: Anterior chamber red blood cells

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3105]
[added] Added//Anterior chamber red blood cells//new term request (PS); parent- Anterior chamber inflammatory cells [level: 10]; term- Anterior chamber red blood cells [level: 10]

**Comment by pnrobinson** [comment]
We recently added a term, Anterior chamber cells, but I think that this term is referring to leukocytes and not RBCs. This might be confusing. @psergouniotis

**Comment by psergouniotis** [comment]
please see discussion in #3104

**Comment by pnrobinson** [comment]
Term was added
