### ISSUE TITLE
ENR-EYE NTR: Slitlike anterior chamber angles in children

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3109]
[No action] HP:0007756//Shallow anterior chamber//Slitlike anterior chamber angles in children//HP:0000594//Shallow anterior chamber; parent- Shallow anterior chamber [level: 9]; term- Slitlike anterior chamber angles in children [level: 10]

**Comment by pnrobinson** [comment]
This is not a great term. First, we do not want to have "in children" as part of the label of the term. Second, it is only used to annotate one disease, https://omim.org/entry/267760?search=267760&highlight=267760
I think this is basically just a severe form of the parent term, "Shallow anterior chamber"
@psergouniotis -- should we say "Shallow anterior chamber" or "Shallow anterior chamber angle"?
Is there any reason to have the "Slit-like" term? SHould we obsolete it or should we remove the "in children" modifer from the term name?

**Comment by psergouniotis** [comment]
Yes suboptimal term indeed. I would obsolete and move the content to "Shallow anterior chamber".

"Shallow anterior chamber" is the correct term (there is no such thing as "Shallow anterior chamber angle"; you can use "Narrow anterior chamber angle" if you wish though - still though clearly not a synonym of "Shallow anterior chamber" ). 

No reason to have "Slit-like"

**Comment by LCCarmody** [comment]
Should we obsolete this term or change it to "Narrow anterior chamber angle"?

**Comment by psergouniotis** [comment]
you could rename to "Narrow anterior chamber angle" or, perhaps a better primary term would be "narrow iridocorneal angle" (with "Narrow anterior chamber angle" as a synonym)

**Comment by pnrobinson** [comment]
I have merged/obsoleted the term, and updated the annotation for OMIM:267760
