### ISSUE TITLE
ENR-EYE NTR: Anterior segment dysgenesis

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3110]
[renamed] HP:0007700//Abnormality of the anterior chamber//Renamed//Anterior segment dysgenesis//HP:0000593//Abnormality of the anterior chamber//Anterior segment developmental anomaly (PS)//Synonym: Anterior segment dysgenesis (PS); parent- Slitlike anterior chamber angles in children [level: 10]; term- Anterior segment dysgenesis [level: 9]

**Comment by pnrobinson** [comment]
@psergouniotis I am not sure what the action item is here?

**Comment by psergouniotis** [comment]
- The primary term should be "Anterior segment developmental anomaly"
- "Anterior segment dysgenesis" should be a synonym.
- The term is presently a subclass of "Abnormal anterior chamber morphology" which is inaccurate. It should instead be a subclass of "Abnormality of the anterior segment of the globe".

Notably, the following subclasses should be introduced or moved:

Anterior segment dysgenesis
  | Iridogoniodysgenesis
  |   | Axenfeld-Rieger malformation (to replace current term "Rieger anomaly" & "Axenfeld anomaly")
  | Peters anomaly
  | Aniridia
  | Aplasia/Hypoplasia affecting the anterior segment of the eye
  |   | Anterior segment of eye aplasia
  |   | Aplasia/Hypoplasia of the iris
  |   | Aplasia/Hypoplasia of the lens
  | Developmental cataract
  | Developmental glaucoma
  | Microcoria
  | Limbal stem cell deficiency
  | Limbal dermoid
  | Keratoglobus (also to be a subclass of corneal ectasia).

"Anterior segment developmental anomaly" is a very important term and classification and the ERN-EYE plans to do further work on refining this class.

**Comment by psergouniotis** [comment]
see also #2768

**Comment by psergouniotis** [comment]
please consider making the changes above - many thanks

**Comment by psergouniotis** [comment]
I do not have strong feelings about removing iridogoniodysgenesis (I have modified my above comment to reflect this) but I would still propose making the rest of the changes as above.
 
Indeed some of these terms need to be subclasses in two different locations in the hierarchy (e.g. keratoglobus) but this is relevant and not an unusual occurence in HPO. Also, I do not find this particularly bundled (all this relates to maldevelopment of the anterior segment of the eye). 

Anterior segment developmental abnormality (syn Anterior segment dysgenesis) is an important term and it would be really helpful to have it in HPO. It can be a feature of syndromes and I feel it is more a phenotype than a diagnosis. It is also a term that is (and probably will continue to be) used a lot to form virtual panels. Notably, at the ERN-EYE meeting (paeds WG) we had a relatively extensive discussion on which should be its subclasses and it would be great if these modifications were introduced.

In terms of congenital cataract, I think the plan was to keep it (#2995).  Same for congenital glaucoma.

**Comment by pnrobinson** [comment]
Anterior segment developmental abnormality is https://hpo.jax.org/app/browse/term/HP:0007700

Anterior segment dysgenesis
- [ ]  | Axenfeld-Rieger malformation (to replace current terms "Rieger anomaly" & "Axenfeld anomaly")
- [ ]   | Peters anomaly
- [ ]   | Aplasia/Hypoplasia affecting the anterior segment of the eye
- [ ]   |   | Anterior segment of eye aplasia
- [ ]   |   |  Aniridia (synonym Aplasia/Hypoplasia of the iris; see #3112)
- [ ]   |   | Aplasia/Hypoplasia of the lens
- [ ]   | Congenital cataract (or developmental cataract)
- [ ]   | Congenital glaucoma (or developmental glaucoma)
- [ ]   | Microcoria
- [ ]   | Limbal stem cell deficiency
- [ ]   | Limbal dermoid
- [ ]   | Keratoglobus (also to be a subclass of corneal ectasia).

**Comment by pnrobinson** [comment]
I have implemented this but am not sure that Limbal stem cell deficiency belongs in this subhierarchy -- please see:
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4691643/

I will open up a separate term for this.

**Comment by pnrobinson** [comment]
Also, I think that limbal dermoid is a synonym of Epibulbar dermoid? I will open up a new term request.

**Comment by pnrobinson** [comment]
see https://github.com/obophenotype/human-phenotype-ontology/issues/4195 and https://github.com/obophenotype/human-phenotype-ontology/issues/4196

**Comment by psergouniotis** [comment]
I had a quick look at the workbench and it seems that the "anterior segment dysgenesis" subclasses proposed in my 02.02 message have not been introduced. Please let me know if there is an issue or if you would like any additional information.

**Comment by pnrobinson** [comment]
You may need to update the HPO version via the edit menu. Also, I just introduced the "limbal terms" today and it will take until the next release to be able to see them in the workbench. But I think we are there!

**Comment by psergouniotis** [comment]
hi Peter. Following requests from colleagues, would you consider using "anterior segment dysgenesis" as the primary term for HP:0007700 (with anterior segment developmental abnormality as a synonym)

**Comment by psergouniotis** [comment]
sorry to bring this up again: would it be possible to modify the primary term of HP:0007700 from "anterior segment developmental abnormality" to "ocular anterior segment dysgenesis"? 

synonyms to include: anterior segment dysgenesis, anterior segment developmental abnormality
many thanks

**Comment by pnrobinson** [comment]
I have fixed this, thanks!
