### ISSUE TITLE
ENR-EYE NTR: Peters anomaly

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3111]
[No action] HP:0000659//Anterior segment dysgenesis//Peters anomaly//HP:0007700//Anterior segment dysgenesis; parent- Rieger anomaly [level: 10]; term- Peters anomaly [level: 10]

**Comment by Frank-Probst** [comment]
Technically not a single anomaly.  This is bundling of several findings.  Not sure how you usually disambiguate things like this.

**Comment by pnrobinson** [comment]
@Frank-Probst you are correct, but the HPO does have some terms that describe characteristic bundles like this, because that is how they are reported in the medical literature (almost always). So this is an exception to a general rule.

**Comment by psergouniotis** [comment]
please see #3110 
WG3 (ERN-EYE) has recommended to merge Peters anomaly (HP:0000659) and Axenfeld anomaly (HP:0001492)  into a new term: 
"Axenfeld-Rieger malformation" (Axenfeld-Rieger anomaly to be its synonym)
