### ISSUE TITLE
ENR-EYE NTR: Aniridia

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3112]
[moved here] Moved here!//Aniridia; parent- Axenfeld anomaly [level: 10]; term- Aniridia [level: 10]

**Comment by Frank-Probst** [comment]
Technically synonymous with "aplasia of the iris", but in practice is often used to describe significant hypoplasia of the iris.

**Comment by pnrobinson** [comment]
@psergouniotis
I think the suggestion was to suppress partial aniridia.
This term was originally requested by G. Black and defined as Sectoral aplasia of the iris. My question is whether "Sectoral aplasia of the iris." can be distinguished from Iris coloboma?

**Comment by psergouniotis** [comment]
Few thoughts on this:

* I agree with the comment above. that "Aplasia/Hypoplasia of the iris" and "Aniridia" are technically synonymous. I would therefore recommend making "Aplasia/Hypoplasia of the iris" a synonym of "Aniridia" (keeping aniridia as the primary term).

* I think the current synonym of aniridia "Absent iris" is inaccurate and not used. I would consider removing it. 

* I think "Aniridia" (and "Aplasia/Hypoplasia of the iris") should also be a subclasses of "Anterior segment developmental anomaiy"

* I recommend changing the definition of "Aniridia" to:
Abnormality of the iris characterized by, typically bilateral, complete or partial iris hypoplasia. The phenotype ranges from mild defects of anterior iris stroma only to almost complete absence of the iris.

* I recommend suppressing the term "Partial aniridia". It is vague and essentially in most cases aniridia is "partial". Instead, the user can choose a modifier to suggest if the phenotype is mild or severe.

**Comment by psergouniotis** [comment]
please consider making the above changes - many thanks

**Comment by pnrobinson** [comment]
@psergouniotis  Note that "Absent iris" is a lay person synonym -- it is intended for the "lay person English" translation at the cost of being not always 100% medically accurate. See https://www.ncbi.nlm.nih.gov/pubmed/29632381

**Comment by pnrobinson** [comment]
Please note that we have Aplasia/Hypoplasia all of the the ontology and it would not be consistent to have just one term for both. 
Also AAO uses Hypoplasia
https://www.aao.org/image/iris-hypoplasia-2
I would suggest we suppress the term Partial aniridia and otherwise leave the current structure. I will also add subclass relations to  "Anterior segment developmental abnormality".
Please reopen if necessary!

**Comment by psergouniotis** [comment]
many thanks.
I was not aware that "absent iris" was a lay person synonym - happy to keep it as such.
OK to keep aplasia/hypoplasia of the iris as a term (and not merge it with aniridia)
Thanks for suppressing "partial aniridia"
Thanks for adding "aniridia" and "aplasia/hypoplasia of the iris" as subclasses of "anterior segment dysgenesis".
Of note, it would be preferable if the primary term for "anterior segment dysgenesis" was "anterior segment developmental abnormality"
