### ISSUE TITLE
ENR-EYE NTR: Bilateral retinal coloboma

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3133]
[suppressed] HP:0007808//Retinal coloboma//Suppressed//Bilateral retinal coloboma//HP:0000480//Retinal coloboma//bilateral could be added as a modifier (PS); parent- Macular coloboma [level: 11]; term- Bilateral retinal coloboma [level: 11]

**Comment by LCCarmody** [comment]
Is suppressed the same as obsoleted?

**Comment by pnrobinson** [comment]
Suppressed is what we have been calling obsoletion with merging.
In this particular case, I would hold off on the obsoletion until the new HPO annotation format is completed in a few months.

**Comment by psergouniotis** [comment]
> Suppressed is what we have been calling obsoletion with merging.

I was not aware of this and might have been using this interchangibly - I hope I have not caused much confusion. in any case, thank you for clarifying.

>  I would hold off on the obsoletion until the new HPO annotation format is completed in a few months.

good to know that there is a new annotation format coming (although I still think that this should be obsoleted and the issue closed)

**Comment by pnrobinson** [comment]
This term is being used only for OMIM:107550. I have re-annotated this disease and obsoleted/merged the term.
