### ISSUE TITLE
ENR-EYE NTR: Retinopathy

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3134]
[No action] HP:0000488//Abnormality of the retina//Retinopathy//HP:0000479//Abnormality of the retina//I cannot find ROP? If not there it absolutely is missing. My suggestion would be dor make differentiation possible fe type1 and type 2 ROP.; parent- Bilateral retinal coloboma [level: 11]; term- Retinopathy [level: 10]

**Comment by pnrobinson** [comment]
duplicate item, closing.

**Comment by psergouniotis** [comment]
see also #3274
