### ISSUE TITLE
ENR-EYE NTR: Retinopathy of prematurity

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3135]
[added] WG: no consensous//Added//Retinopathy of prematurity//new term request; this term has an orphanet code (ORPHA:90050) but I think that it also represents a phenotype and should therefore also be in HPO (PS); parent- Retinopathy [level: 10]; term- Retinopathy of prematurity [level: 11]

**Comment by Frank-Probst** [comment]
The hierarchy of retinopathy of prematurity depends on how exhaustive you want to be here.  The disease has 4 descriptors:  zone (I-III), extent (1-12 clock hours, with boundaries), stage (1-5), and presence or absence of plus disease (or pre-plus disease, which is sort of a midway point between presence or absence of plus disease).  But it's important to note that these descriptors are NOT hierarchical.  You can have any zone combined with any extent combined with any stage combined with any no-plus, pre-plus, or plus status.  And since the extent also comes with zone borders, extent is more than just one number value.  I don't think it's practical to give each combo it's own designation.  Key ref:  https://jamanetwork.com/journals/jamaophthalmology/fullarticle/417157

**Comment by LCCarmody** [comment]
Added term and will add  all subsets listed above (but not combos).

**Comment by LCCarmody** [comment]
@Frank-Probst @pnrobinson 
I just wanted to clarify.  @Frank-Probst mentioned that there shouldn't be a hierarchy and that is how I began adding terms. But looking into the issues in github--there is a hierarchy suggested within each type (stage, zone, plus, threshold).  Also, there are no issues for 'extent'.
Issues suggest this hierarcy:
 Retinopathy of prematurity
 - Retinopathy of prematurity stage 1
  -- Retinopathy of prematurity stage 2
   --- Retinopathy of prematurity stage 3
    ---- Retinopathy of prematurity stage 4
       ----- Retinopathy of prematurity stage 5
-  Retinopathy of prematurity zone 1
  -- Retinopathy of prematurity zone 2
   --- Retinopathy of prematurity zone 3
-  Retinopathy of prematurity plus
 -- Retinopathy of prematurity preplus
- Retinopathy of prematurity threshold
  -- Retinopathy of prematurity pre-threshold

Just wanted to clarify that this is the proposed hierarchy.  Also, should extent 1-12 be added?


 Issues #3136, #3137, #3138, #3139, #3140, #3141, #3142 #3143, #3144, #3145, #3146.

**Comment by pnrobinson** [comment]
In general we have not used hierarchies to code severity, and therefore the above hierarchy does not look correct. @psergouniotis, can you help us with the hierarchy for these terms?

**Comment by psergouniotis** [comment]
Yes there shouldn't be a hierarchy and I cannot find any issues suggesting this (please see #3147).

The parent term is "Retinopathy of prematurity". All the following should be subclasses of these, each one at the same level as the other:
Retinopathy of prematurity stage 1 disease
Retinopathy of prematurity stage 2 disease
Retinopathy of prematurity stage 3 disease
Retinopathy of prematurity stage 4 disease
Retinopathy of prematurity stage 5 disease
Retinopathy of prematurity plus disease
Retinopathy of prematurity pre-plus disease
Retinopathy of prematurity zone I disease
Retinopathy of prematurity zone II disease
Retinopathy of prematurity zone III disease
Retinopathy of prematurity threshold disease
Retinopathy of prematurity prethreshold disease

I am not sure what you mean regarding "extent".

**Comment by LCCarmody** [comment]
Re: Extent, @psergouniotis 

It was mentioned above by @Frank-Probst  there is another class "extent (1-12 clock hours, with boundaries)".  In a JAMA paper, it is described as "Extent of disease:
The extent of disease is recorded as hours of the clock or as 30° sectors.1 As the observer looks at each eye, the 3-o’clock position is to the right and nasal in the right eye and temporal in the left eye, and the 9-o’clock position is to the left and temporal in the right eye and nasal in the left eye (Figure 1). The boundaries between sectors lie on the clock hour positions; that is, the 12-o’clock sector extends from 12 o’clock to 1 o’clock."

My inclination is to not include this, too, but I will add the terms if needed.

**Comment by pnrobinson** [comment]
Consensus -- do not include the extant at this time

**Comment by pnrobinson** [comment]
Note -- I am changing the refereince
Lee T. (2017) Classification of ROP. In: Kychenthal B. A., Dorta S. P. (eds) Retinopathy of Prematurity. Springer, Cham
to ISBN 978-3-319-52190-9 -- otherwise we will run into format errors!

**Comment by pnrobinson** [comment]
done!
