### ISSUE TITLE
ENR-EYE NTR: Retinopathy of prematurity prethreshold disease

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3147]
[added] WG: no consensous//Added//Retinopathy of prematurity prethreshold disease//new term request - please see ETROP for definition (PS); parent- Retinopathy of prematurity threshold disease [level: 12]; term- Retinopathy of prematurity prethreshold disease [level: 12]

**Comment by pnrobinson** [comment]
@psergouniotis
I guess we are talking about this classification
https://jamanetwork.com/journals/jamaophthalmology/fullarticle/417157
One thing is that maybe we should just have terms to describe the five main stages.
The other items are like this:
 A + symbol is added to the ROP stage number to designate the presence of plus disease. 
Thus they are added on top of the stages?

**Comment by psergouniotis** [comment]
As per spreadsheet, I think it would be appropriate to have the following Retinopathy of prematurity subclasses:

- Retinopathy of prematurity stage 1 disease
- Retinopathy of prematurity stage 2 disease
- Retinopathy of prematurity stage 3 disease
- Retinopathy of prematurity stage 4 disease
- Retinopathy of prematurity stage 5 disease
- Retinopathy of prematurity plus disease
- Retinopathy of prematurity pre-plus disease
- Retinopathy of prematurity zone I disease
- Retinopathy of prematurity zone II disease
- Retinopathy of prematurity zone III disease
- Retinopathy of prematurity threshold disease
- Retinopathy of prematurity prethreshold disease

**Comment by psergouniotis** [comment]
just noticed that I have not answered to your question Peter. Indeed one might need to select:
* Retinopathy of prematurity stage 1 disease
* Retinopathy of prematurity zone I disease
* Retinopathy of prematurity plus disease

to describe a specific phenotype (ie zone, stage & presence or absence of plus are different entities that can be combined). please let me know if you have any issues with the definitions
