### ISSUE TITLE
ENR-EYE NTR: Chorioretinal coloboma

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3149]
[No action] HP:0000567//Chorioretinal abnormality//Chorioretinal coloboma//HP:0000532//Chorioretinal abnormality; parent- Chorioretinal abnormality [level: 10]; term- Chorioretinal coloboma [level: 11]

**Comment by Frank-Probst** [comment]
@pnrobinson Oops.  Okay, this goes back to my previous comment.  Now I can see that chorioretinal abnormalities and retinal abnormalities are separated from one another (I think.).

**Comment by pnrobinson** [comment]
no action
