### ISSUE TITLE
ENR-EYE NTR: Tapetal-like fundal reflex

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3152]
[added] Added//Tapetal-like fundal reflex//new term request (KK); parent- Chorioretinal dystrophy [level: 11]; term- Tapetal-like fundal reflex [level: 11]

**Comment by pnrobinson** [comment]
@psergouniotis
Is there a good definition for this?

**Comment by psergouniotis** [comment]
Def for "Tapetal-like fundal reflex":  Golden, scintillating, particulate reflection noted on fundus examination (typically in the macula and sparing the fovea). The term tapetal is used to describe this "metallic" sheen appearance as it is thought to be similar to the "tapetal" reflex seen in the eyes of certain animals. 

(a picture can be found here: https://webeye.ophth.uiowa.edu/eyeforum/atlas/pages/Tapetal-sheen.htm). This appearance is typically seen in female carriers of X-linked RP associated mutations (so maybe the term should be associated with OMIM* 312610, OMIM# 312600 & OMIM* 300757.
