### ISSUE TITLE
ENR-EYE NTR: Chorioretinal lacunae

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3157]
[No action] HP:0007858//Chorioretinal abnormality//Chorioretinal lacunae//HP:0000532//Chorioretinal abnormality; parent- Chorioretinal dysplasia [level: 11]; term- Chorioretinal lacunae [level: 11]

**Comment by Frank-Probst** [comment]
@pnrobinson Is there a system to link very rare findings (like this one) to very rare diseases?  This one is almost pathognomonic for Aicardi syndrome (OMIM:  https://www.omim.org/entry/304050?search=aicardi%20syndrome&highlight=syndromic%20aicardi%20syndrome).

**Comment by pnrobinson** [comment]
@Frank-Probst there are annotation files for diseases that can be browsed here
http://compbio.charite.de/hpoweb/showterm?id=HP:0000118
and also can be downloaded (see download section). We would basically want to update the file for Aicardi once we make this term.

**Comment by pnrobinson** [comment]
@Frank-Probst @nicolevasilevsky 
We should reannotate this disease with PhenoteX

**Comment by nicolevasilevsky** [comment]
@pnrobinson looks like OMIM:304050 is already annotated with HP_0007858 Chorioretinal lacunae.

Is there something that needs to be changed?

![image](https://user-images.githubusercontent.com/6722114/34056993-19075012-e18a-11e7-8dc9-96f6834d8605.png)

**Comment by pnrobinson** [comment]
OK, then life is good! Thanks! I am closing this issue.
