### ISSUE TITLE
ENR-EYE NTR: Central serous chorioretinopathy

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3159]
[added] WG//Added//Central serous chorioretinopathy//new term request (PS); discussed at WG - need accurate definition; parent- Chorioretinal degeneration [level: 11]; term- Central serous chorioretinopathy [level: 12]

**Comment by pnrobinson** [comment]
Add syn:  Central serous retinopathy

**Comment by pnrobinson** [comment]
This article has a good definition
https://www.ncbi.nlm.nih.gov/pubmed/17662099

Central serous chorioretinopathy (CSC) is a disease of the retina characterized by serous detachment of the neurosensory retina secondary to one or more focal lesions of the retinal pigment epithelium (RPE). CSC occurs most frequently in mid-life and more often in men than in women. Major symptoms are blurred vision, usually in one eye only and perceived typically by the patient as a dark spot in the centre of the visual field with associated micropsia and metamorphopsia. Normal vision often recurs spontaneously within a few months. The condition can be precipitated by psychosocial stress and hypercortisolism. Ophthalmoscopic signs of CSC range from mono- or paucifocal RPE lesions with prominent elevation of the neurosensory retina by clear fluid - typical of cases of recent onset - to shallow detachments overlying large patches of irregularly depigmented RPE. The spectrum of lesions includes RPE detachments. Granular or fibrinous material may accumulate in the subretinal cavity. Serous detachment often resolves spontaneously.
https://www.ncbi.nlm.nih.gov/pubmed/17662099

@psergouniotis It does not seem that "degeneration" is the right parent term because recovery is possible? Please advise

**Comment by psergouniotis** [comment]
Agree about def. Valid point about parent term. It should perhaps be "Chorioretinal abnormality" (rather than the previously proposed "Chorioretinal   degeneration")

**Comment by pnrobinson** [comment]
Def: An anomaly of the retina with serous detachment of the neurosensory retina secondary to one or more focal lesions of the retinal pigment epithelium (RPE), and associated with blurred vision, usually in one eye only and perceived typically by the patient as a dark spot in the centre of the visual field with associated micropsia and metamorphopsia. Normal vision often recurs spontaneously within a few months. 
Comment: The condition can be precipitated by psychosocial stress and hypercortisolism. Ophthalmoscopic signs of CSC range from mono- or paucifocal RPE lesions with prominent elevation of the neurosensory retina by clear fluid - typical of cases of recent onset - to shallow detachments overlying large patches of irregularly depigmented RPE. The spectrum of lesions includes RPE detachments. Granular or fibrinous material may accumulate in the subretinal cavity. Serous detachment often resolves spontaneously.
PMID:17662099
