### ISSUE TITLE
ENR-EYE NTR: Exudative retinal detachment

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3172]
[No action] HP:0012231//Retinal detachment//Exudative retinal detachment//HP:0000541//Retinal detachment; parent- Rhegmatogenous retinal detachment [level: 11]; term- Exudative retinal detachment [level: 11]

**Comment by pnrobinson** [comment]
no action

**Comment by psergouniotis** [comment]
for definition see #3169
see also #3173
