### ISSUE TITLE
ENR-EYE NTR: Serous retinal detachment

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3173]
[added] added//Serous retinal detachment; parent- Exudative retinal detachment [level: 11]; term- Serous retinal detachment [level: 11]

**Comment by pnrobinson** [comment]
@psergouniotis
I thought that serous and exudate were synonyms? Can you please provide a definition if they are different?

**Comment by psergouniotis** [comment]
I think they are the same (http://eyewiki.aao.org/Retinal_Detachment). I would favour "Exudative retinal detachment " with " Serous retinal detachment " as the synonym.

**Comment by pnrobinson** [comment]
added synonym
