### ISSUE TITLE
ENR-EYE NTR: Retinal degeneration

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3174]
[No action] HP:0000546//Abnormality of the retina//Retinal degeneration//HP:0000479//Abnormality of the retina; parent- Serous retinal detachment [level: 11]; term- Retinal degeneration [level: 10]

**Comment by psergouniotis** [comment]
Some modifications are recommended in the subclasses of "Retinal degeneration"

[I] Progressive retinal degeneration: this terms should be removed as it is not frequently used and it should be instead expressed by selecting "retinal degeneration" and using "progressive" as a modifier.

[II] Cystic retinal degeneration - "Peripheral cystoid degeneration" should be the primary term and "Cystic retinal degeneration" should be the synonym. Also, this term should be moved as a subclass of "Peripheral retinal degeneration".

[III] Retinal atrophy - no change needed (definition pending). 
[IV] Peripheral retinal degeneration: although this can be expressed with a modifier, it is a frequently used term reflecting a distinct set of conditions. 
The following should be moved as subclasses of "Peripheral retinal degeneration": "Lattice retinal degeneration", "Reticular pigmentary degeneration", "Cystic retinal degeneration" (to be renamed).

[V] Progressive cone degeneration - suboptimal term that should be removed. "Progressive" can be added as a modifier. It is unusual to have degeneration of the cones with the rods not being affected at all. I checked the associated OMIM entries and they should be moved to "Retinal degeneration".

[VI] Vitreoretinal degeneration - this should be made a synonym of "Vitreoretinopathy". It should not be a subclass of "Retinal degeneration".

[VII] Tapetoretinal degeneration - no change needed (definition pending). 

[VIII] Reticular pigmentary degeneration - to be moved as a subclass of "Peripheral retinal degeneration".

[IX] Diffuse retinal cone degeneration - suboptimal term that should be removed. "Diffuse" can be added as a modifier. It is unusual to have degeneration of the cones with the rods not being affected at all. I checked the associated OMIM entries and they should be moved to "Cone/cone-rod dystrophy".

[X] Lattice retinal degeneration - to be moved as a subclass of "Peripheral retinal degeneration".

**Comment by pnrobinson** [comment]
@psergounitotis
Is this a good reference for cystoid retinal degeneration?
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3355342/
Can you help with a definition?

**Comment by psergouniotis** [comment]
Please see #3181
Advised renaming the term and using the following definition:
Degenerative changes of the peripheral retina consisting of close-packed tiny cystic spaces at the outer plexiform/inner nuclear retinal level. The degeneration is very common in adult eyes and starts adjacent to the ora serrata and extends circumferentially and posteriorly.

**Comment by psergouniotis** [comment]
please consider making the changes above. on a different note, "retinal degeneration" could be moved as a subclass of "retinopathy" (see also #3274)

**Comment by pnrobinson** [comment]
@psergouniotis  Looking at this
https://jamanetwork.com/journals/jamaophthalmology/article-abstract/625326
I am wondering if tapetoretinal degeneration is meaningful anymore? Or does it have a new definition somewhere?

**Comment by pnrobinson** [comment]
I moved vitreoretinal degeneration as suggested.

**Comment by pnrobinson** [comment]
@psergouniotis 
Given:
https://rarediseases.org/rare-diseases/cone-dystrophy/
maybe we should make two children of cone/cone-rod dystrophy for progressive and stationary? These are important distinctions and people could forget to add modifiers in real life. 
I am finished with the other items here (except for tapetoretinal).

**Comment by psergouniotis** [comment]
Tricky one. In inherited retinal disease context, the term dystrophy typically suggests progressive disease of inherited nature. Degeneration is a broader term and therefore cannot be a subclass.

Typically if I want to describe a phenotype with progressive cone degeneration that is probably hereditary I will use "cone/cone-rod dystrophy".

Describing the stationary phenotype is trickier. We have previously introduced the term "cone dysfunction syndrome". In practice I would use "Inherited disorder of cone function" (which is technically a synonym of cone dysfunction syndrome). 

A few points/recommendations:
* I know that you did not like the term "cone dysfunction syndrome" and I wanted to ask if you would prefer to change the primary term to "Inherited disorder of cone function"?

* Also, I have noticed that "Abnormality of color vision" is a subclass of "Cone dysfunction syndrome". This is incorrect. Sometimes optic nerve disease can cause abnormality of color vision and I feel that the following structure would be better

Abnormal eye physiology
  | Abnormality of color vision
  |   |  Color vision test abnormality
  |   |  Inherited disorder of cone function  (syn cone dysfunction syndrome)
  |   |  |  Dyschromatopsia (and subclasses)
  |   |  |  Achromatopsia
  |   |  |  Blue cone monochromacy

(the terms "cone monochromacy" and "monochromacy" are not really used and could be merged)

One issue is that Achromatopsia & Blue cone monochromacy are more than just an abnormalities of color vision (e.g. they are associated with quite reduced visual acuity). To reflect this would you consider also including "Inherited disorder of cone function " as a subclass of both 
* Abnormal eye physiology and
* Abnormality of color vision?

**Comment by pnrobinson** [comment]
@psergouniotis 
I think there are two open issues
1. Tapetoretinal degeneration -- I am wondering if tapetoretinal degeneration should simply be merged with Retinaitis pigmentosa and added as a related synonym? See this https://onlinelibrary.wiley.com/doi/pdf/10.1034/j.1600-0420.2000.078003244.x

2. Progressive cone degeneration -- I am wondering two things
-- We have a term cone/cone-rod dystrophy. I think we renamed this from cone dystrophy because you almost always have rod dystrophy as well, but if we want to allow for atomic phenotyping, maybe we should actually just have a term for the cones, and say in the comment that the rods are almost always affected as well. And isn't cone degeneration the same thing as cone dystrophy?

**Comment by psergouniotis** [comment]
Tapetoretinal degeneration is not used very much anymore. Should be OK to have it as a related synonym to retinitis pigmentosa.

Cone degeneration is not exactly the same as cone dystrophy. In the context of inherited eye disease, dystrophy suggests a hereditary, progressive condition. Technically "inherited progressive cone degeneration" is a "cone dystrophy".

Perhaps the middle ground would be:
* to introduce a term "cone dystrophy" as a subclass of "cone/cone-rod dystrophy". 
* to  transfer the annotations/content of "progressive cone degeneration" to "cone dystrophy" (I checked OMIM);
* to remove the term "progressive cone degeneration".

Cone dystrophy should not be a sublcass of "retinal degeneration"

**Comment by pnrobinson** [comment]
I have moved the term progressive cone degeneration as suggested and changed the primary label to Cone dystrophy with the definition "Inherited progressive cone degeneration". I have merged Tapetoretinal degeneration to rod-cone dystrophy (which is the Retinitis pigmentosa term).
