### ISSUE TITLE
ENR-EYE NTR: Vitreoretinal degeneration

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3176]
[No action] HP:0000655//Retinal degeneration//Vitreoretinal degeneration//HP:0000546//Retinal degeneration; parent- Tapetoretinal degeneration [level: 11]; term- Vitreoretinal degeneration [level: 11]

**Comment by pnrobinson** [comment]
@psergouniotis
I am updating the definition to this:
Gradual deterioration of the vitreous humor and retina. Vitreoretinal degeneration is a congenital liquefaction of the vitreous humor, and abnormalities of the interface between the vitreous and retina leading to increased traction on the retina and retinal detachment.
PMID:18179896 

Please advise if this definition is not good!

**Comment by psergouniotis** [comment]
proposed def for Vitreoretinal degeneration: 
"Ocular abnormality characterised by premature degeneration of the vitreous and the retina that may be associated with increased risk of retinal detachment."

**Comment by pnrobinson** [comment]
Updating the definition
