### ISSUE TITLE
ENR-EYE NTR: Diffuse retinal cone degeneration

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3185]
[suppressed] HP:0007829//Retinal degeneration//Suppressed//Diffuse retinal cone degeneration//HP:0000546//Retinal degeneration//diffuse can be used as a modifier; merge content with retinal degeneration (PS); parent- Snowflake vitreoretinal degeneration [level: 12]; term- Diffuse retinal cone degeneration [level: 11]

**Comment by pnrobinson** [comment]
This term is currently use to annotate only one disease
http://compbio.charite.de/hpoweb/showterm?id=HP:0007829
https://omim.org/entry/180020?search=180020&highlight=180020

@psergouniotis -- would it be good to have a term called "Retinal cone degeneration"? We could change the primary label of this term, and merge it with Progressive retinal cone degeneration.

**Comment by psergouniotis** [comment]
Diffuse retinal cone degeneration should be obsoleted (can be described with modifiers). I have checked OMIM%180020 and there is nothing distinctive - please re-allocate it to "Retinal degeneration".

In terms of having "cone degeneration" as a term please see my comment on #3189.

**Comment by psergouniotis** [comment]
@LCCarmody
please consider closing/finalising this:
* obsolete "Diffuse retinal cone degeneration" (and merge annotated content with "Retinal degeneration") 
(see also #3189)

**Comment by pnrobinson** [comment]
I updated the annotation and obsoleted this term.
