### ISSUE TITLE
ENR-EYE NTR: Progressive retinal degeneration

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3186]
[suppressed] HP:0007893//Retinal degeneration//Suppressed//Progressive retinal degeneration//HP:0000546//Retinal degeneration//progressive can be used as a modifier; merge content with retinal degeneration (PS); parent- Diffuse retinal cone degeneration [level: 11]; term- Progressive retinal degeneration [level: 11]

**Comment by psergouniotis** [comment]
Progressive retinal degeneration can be used as a modifier; obsolete and merge content with retinal degeneration.

**Comment by psergouniotis** [comment]
@LCCarmody 
please consider closing/finalising this:
* obsolete term "Progressive retinal degeneration"

**Comment by pnrobinson** [comment]
For OMIM:248500, I added "Retinal degeneration" with modifier Progressive, and Adult onset

**Comment by pnrobinson** [comment]
same for https://omim.org/entry/252650
I will merge the term.
