### ISSUE TITLE
ENR-EYE NTR: Reticular pigmentary degeneration

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3187]
[No action] HP:0007937//Retinal degeneration//Reticular pigmentary degeneration//HP:0000546//Retinal degeneration; parent- Progressive retinal degeneration [level: 11]; term- Reticular pigmentary degeneration [level: 11]

**Comment by pnrobinson** [comment]
@Frank-Probst
todo--get definition from literature

**Comment by Frank-Probst** [comment]
I found this one:

"[Peripheral Reticular Pigmentary Degeneration] PRPD is characterized by a reticular pigmentation that forms a polygonal, netlike arrangement of hyperpigmented lines forming geometric patterns in the peripheral fundus."

Here's the article:  https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5256899/

I don't think it's a great definition, but I'm only seeing 8 articles in PubMed about this, and half of those are more than 10 years old.  Based on this article, it looks like a skilled ophthalmologist can make the diagnosis with a regular dilated eye exam, but it's much more obvious with ultra-wide-field fluorescein angiography (UWFA).  This is an unusual technique, which is probably why the disease is considered rare, and why people outside the ophthalmology world don't know much (if anything) about it.  What they do is inject fluorescein (a fluorescent dye) into the vein in your elbow and then watch the retina with a wavelength of light that works on the dye.  So the dye goes from your arm to the heart, then to the lungs, then back to the heart, and then out to the rest of the body (including the eyes).  You can then watch the retina as the dye goes through the arterial network to the choroid layer and through the central retinal artery.  The retina is the only part of the body that this technique works on.  In this paper, it looks like there's a delay in blood flow to the central retinal artery, so lack of blood flow is probably a component of the disease.  It also looks like the complement factor H polymorphism (Y402H) that you see in age-related macular degeneration is strongly correlated with the phenotype (http://www.aaojournal.org/article/S0161-6420(07)00718-X/fulltext), so there's a genotype/phenotype link here.

All that being said, I'm not seeing much in terms of how this finding relates to any functional visual changes.  I'm not seeing anything about significant peripheral vision loss, and if you're studying age-related macular degeneration, visual field testing is one of the first things they do.  The 2008 paper (the second one I gave the link for) looks like the authors expected further studies to show peripheral vision loss, but if so, I'm not seeing it in the literature.

**Comment by pnrobinson** [comment]
I am adding the definition: A type of retinal reticular pigmentation that forms a polygonal, netlike arrangement of hyperpigmented lines forming geometric patterns in the fundus.

The phenotype is not always peripheral, seee
https://omim.org/entry/267800

@Frank-Probst  I am adding a nanoattribution for you as HPO:fprobst. Let me know if you would prefer ORCID or whatever else!
