### ISSUE TITLE
ENR-EYE NTR: Progressive cone degeneration

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3189]
[suppressed] HP:0008020//Retinal degeneration//WG//Suppressed//Progressive cone degeneration//HP:0000546//Retinal degeneration//progressive can be used as a modifier; merge content with retinal degeneration (PS); parent- Lattice retinal degeneration [level: 11]; term- Progressive cone degeneration [level: 11]

**Comment by pnrobinson** [comment]
@psergouniotis
Should the term be "Cone degeneration" and we add a modifier?
Here are the diseases that are annotated to this term
http://compbio.charite.de/hpoweb/showterm?id=HP:0008020

**Comment by psergouniotis** [comment]
Agree, term should be "Cone degeneration" and progressive should be added as a modifier. 

Looking at the annotated diseases there might be an argument to obsolete this vague term. Two options:
* keep it but also introduce the term "Rod degeneration" as a subclass of "Retinal degeneration".
* remove it and merge content with "retinal degeneration".

On a similar note, the following should be obsoleted 
* Diffuse retinal cone degeneration (diffuse can be used as a modifier; merge content with retinal degeneration)
* Progressive retinal degeneration (progressive can be used as a modifier; merge content with retinal degeneration)
* Peripheral retinal cone degeneration (mixed, vague term)

**Comment by psergouniotis** [comment]
@LCCarmody 
please consider closing/finalising this:
* introduce term "Rod degeneration" as a subclass of "Retinal degeneration" (HP:0000546)

* change/rename the term "Progressive cone degeneration" (HP:0008020) to "Cone degeneration". Also, remove synonym "Progressive cone dystrophy".

* remove/suppress the following terms:
- Diffuse retinal cone degeneration #3185
- Progressive retinal degeneration #3186
- Peripheral retinal cone degeneration (mixed, vague term)
