### ISSUE TITLE
ENR-EYE NTR: Retinal dystrophy

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3190]
[No action] HP:0000556//Abnormality of the retina//Retinal dystrophy//HP:0000479//Abnormality of the retina; parent- Progressive cone degeneration [level: 11]; term- Retinal dystrophy [level: 10]

**Comment by psergouniotis** [comment]
Comment on Retinal dystrophy HP:0000556.
This is a frequently used term. I think it should be a subclass of "Retinal degeneration". 

The rationale for this is as per https://www.ncbi.nlm.nih.gov/pubmed/2614796:
Dystrophy is defined as the process and consequences of hereditary progressive affections of specific cells in one or more tissues (...). Degeneration is an equivocal term used for both acquired and hereditary disorders (...) Dysplasias are different from dystrophies.

Definition: Retinal dystrophy is an abnormality of the retina associated with a hereditary process. Retinal dystrophies are defined by their predominantly monogenic inheritance and they are frequently associated with loss or dysfunction of photoreceptor cells as a primary or secondary event.

**Comment by psergouniotis** [comment]
In addition to being a subclass of "Retinal degeneration", should this also be a subclass of "Retinopathy"?

**Comment by pnrobinson** [comment]
adding definition. Let's discuss what to do about retinopathy in the issue about that term!
