### ISSUE TITLE
ENR-EYE NTR: Rod-cone dystrophy

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3191]
[No action] HP:0000510//Retinal dystrophy//Rod-cone dystrophy//HP:0000556//Retinal dystrophy; parent- Retinal dystrophy [level: 10]; term- Rod-cone dystrophy [level: 11]

**Comment by psergouniotis** [comment]
See issue #3275 (recently closed) for definition.

**Comment by pnrobinson** [comment]
no action
