### ISSUE TITLE
ENR-EYE NTR: Pattern dystrophy of the retina

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3199]
[No action] HP:0007963//Retinal dystrophy//Pattern dystrophy of the retina//HP:0000556//Retinal dystrophy; parent- Occult macular dystrophy [level: 12]; term- Pattern dystrophy of the retina [level: 11]

**Comment by pnrobinson** [comment]
@psergouniotis
1. Is the following a good definition?
2. I have seen that pattern dystrophy is subclassified into five types. Should we have terms for each (currently there is just one subtype).

Pattern dsytrophy is characterized by various patterns of deposits of the yellow, orange, or gray lipofuscin pigment in the macular area.

**Comment by psergouniotis** [comment]
Definition: A spectrum of fundoscopic appearances characterized by the development of a variety of patterns of deposits predominantly in the macular area. The deposits are typically bilateral, relatively symmetrical, yellow/white and associated with changes at the level of the retinal pigment epithelium. With time, retinal atrophy may occur. A number of pattern dystrophy subtypes have been described including butterfly-shaped dystrophy, reticular dystrophy (net-like pattern) and fundus pulverulentus (granular, mottled pigmentation).

I personally think that the subclassification of pattern dystrophy is very arbitrary and should not be used much. I would therefore prefer not to add the other subclasses (at least at this stage).

**Comment by pnrobinson** [comment]
OK. Added definition and will not add more subclsses
