### ISSUE TITLE
ENR-EYE NTR: Sub-ILM hemorrhage

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3210]
[added] WG//Added//Sub-ILM hemorrhage; parent- Intraretinal hemorrhage [level: 11]; term- Sub-ILM hemorrhage [level: 12]

**Comment by pnrobinson** [comment]
Adding term as
label:Sub‐inner limiting membrane haemorrhage
synonym:Sub-ILM hemorrhage (will also add UK spellings)
Definition: A type of intraretinal hemorrhage that is located in the superficial retina between the inner limiting membrane and the retinal nerve fibre layer.
Reference: PMID:17229799

Comment: Preretinal haemorrhages usually occur at the interface between the posterior hyaloid and inner limiting membrane (ILM). Less frequently, they are located in the superficial retina between the ILM and the retinal nerve fibre layer. These sharply demarcated, dome‐shaped haemorrhages show a predilection for the macular region and consequently lead to severe visual impairment.

**Comment by pnrobinson** [comment]
@psergouniotis  Please advise what parent this new term needs to have -- I will not add it for now

**Comment by pnrobinson** [comment]
I am adding this to retinal hemorrhage since there is a part of

**Comment by pnrobinson** [comment]
With the following definition, Protege infers this term to be a child of Retinal hemorrhage!
```
'has part' some 
    ('increased amount'
     and ('inheres in' some 
        ('hemorrhage and non-specified extravasation'
         and ('part of' some 'inner limiting layer of retina')))
     and ('has modifier' some abnormal))
```

**Comment by psergouniotis** [comment]
As per spreadsheet I would recommend introducing the term "Intraretinal hemorrhage" (subclass of "Retinal hemorrhage".

"Sub-ILM hemorrhage" could be a subclass of "Intraretinal hemorrhage"
