### ISSUE TITLE
ENR-EYE NTR: Dot-and-blot retinal hemorrhage

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3214]
[moved here] WG//Moved here!//Dot-and-blot retinal hemorrhage//WG; parent- Dot-and-blot retinal hemorrhage [level: 11]; term- Dot-and-blot retinal hemorrhage [level: 12]

**Comment by pnrobinson** [comment]
@psergouniotis  I do not understand what the action is here. Isn't it correct that this term is a child of Retinal hemorrhage?

**Comment by pnrobinson** [comment]
Looking at the excel sheet from the workshop again, there was no action, so I am closing this. The structure appears correct.

**Comment by psergouniotis** [comment]
The recommendation here is to:
* add "Intraretinal hemorrhage" as a new term ( subclass of "Retinal hemorrhage" )

Move the following terms as subclasses of "Intraretinal hemorrhage":
* Sub-ILM hemorrhage
* Flame-shaped retinal hemorrhage
* Dot-and-blot retinal hemorrhage

**Comment by psergouniotis** [comment]
the proposed action is described above - add new term ("Intraretinal hemorrhage") and make this its subclass.
