### ISSUE TITLE
ENR-EYE NTR: Angioid streaks of the retina

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3217]
[renamed] HP:0001102//Abnormality of the retina//WG//Renamed//Angioid streaks of the retina//HP:0000479//Abnormality of the retina//Angioid streak of the fundus (WG1+3); parent- Subretinal pigment epithelium hemorrhage [level: 11]; term- Angioid streaks of the retina [level: 10]

**Comment by pnrobinson** [comment]
@psergouniotis
Should this be renamed to
"Angioid streak of the fundus"

Should the definition be expanded upon?

**Comment by psergouniotis** [comment]
Yes please rename to "Angioid streaks of the fundus" (keeping "Angioid streaks of the retina" as syn)

Proposed definition:  Irregular lines in the deep retina that are typically configured in a radiating fashion and emanate from the optic disc. Angioid streaks are crack-like dehiscences in abnormally thickened and calcified Bruch’s membrane, resulting in atrophy of the overlying retinal pigment epithelium. They may be associated with a number of endocrine, metabolic, and connective tissue abnormalities but are frequently idiopathic.

**Comment by pnrobinson** [comment]
Renamed term and added your definition.
