### ISSUE TITLE
ENR-EYE NTR: Foveal depigmentation

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3226]
[added] WG//Added//Foveal depigmentation//new term request (WG); parent- Foveal hypopigmentation [level: 13]; term- Foveal depigmentation [level: 13]

**Comment by pnrobinson** [comment]
@psergionoutos
What is the distinction to hypopigmentation?
Logically, I would think that hypopigmentation is a developmental defect where there was never sufficient pigmentation and depigmentation means a loss of pigmentation, but it seems that some articles use depigmentation to mean hypopigmentation
e.g., https://www.ncbi.nlm.nih.gov/pubmed/9716335

**Comment by psergouniotis** [comment]
I think this should be consistent with the use of hypopigmentation and depigmentation for other tissues (e.g. skin).

There is no consensus that I could find. In my mind the description in this paper https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3764650/ is more correct than this https://en.wikipedia.org/wiki/Hypopigmentation or this http://www.wikidoc.org/index.php/Decreased_skin_pigmentation.

"While a decreased pigment production is reported as hypopigmentation, depigmentation has been defined as loss of pigment".

Please also consider adding the term "Depigmentation of the fundus" (syn "Fundal depigmenatation") as a subclass of Abnormality of fundus pigmentation (HP:0031605). 
On a similar note, I would think "fundal hypopigmentation" occurs in albinism while "fundal depigmentation" occurs in VKH.
