### ISSUE TITLE
ENR-EYE NTR: Macular degeneration

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3231]
[No action] HP:0000608//Abnormality of the macula//Macular degeneration//HP:0001103//Abnormality of the macula; parent- Absent foveal reflex [level: 12]; term- Macular degeneration [level: 11]

**Comment by psergouniotis** [comment]
"Macular degeneration" should be a subclass of "Retinal degeneration".

Consider changing definition for "Retinal degeneration" to: 
A nonspecific term denoting degeneration of the retinal pigment epithelium and/or retinal photoreceptor cells.

Consider changing definition for "Macular degeneration" to:
A nonspecific term denoting degeneration of the retinal pigment epithelium and/or retinal photoreceptor cells of the macula lutea.

**Comment by pnrobinson** [comment]
made changes as advised
