### ISSUE TITLE
ENR-EYE NTR: Macular atrophy

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3232]
[No action] HP:0007401//Macular degeneration//Macular atrophy//HP:0000608//Macular degeneration; parent- Macular degeneration [level: 11]; term- Macular atrophy [level: 12]

**Comment by Frank-Probst** [comment]
@pnrobinson Peter, Could you use this one as an example of how the hierarchy works, or at least how to see the hierarchy?  (It may be easier to do by e-mail, or just wait until we can chat, but I wanted to flag it as an example to use.)

**Comment by psergouniotis** [comment]
Proposed definition for "Macular atrophy": well-demarcated area(s) of partial or complete depigmentation in the macula, reflecting atrophy of the retinal pigment epithelium with associated retinal photoreceptor loss.

"Macular atrophy" should be a subclass of "Retinal atrophy" (HP:0001105)

Along the same lines you could use the following definition for "Retinal atrophy" (HP:0001105): well-demarcated area(s) of partial or complete depigmentation in the fundus, reflecting atrophy of the retinal pigment epithelium with associated retinal photoreceptor loss.

It would be useful to add the term "Geographic atrophy" (syn geographic retinal atrophy) as a subclass of "Retinal atrophy". 
Proposed definition for "Geographic atrophy": Sharply demarcated area of partial or complete depigmentation of the fundus reflecting atrophy of the retinal pigment epithelium with associated retinal photoreceptor loss. The margins of the de-pigmented area are usually scalloped and the large choroidal vessels are visible through the atrophic retinal pigment epithelium. (source: RCOphth AMD guidelines 2013)

**Comment by Frank-Probst** [comment]
I don't know what the ophthalmologic definition of this is, and I think we just made up the term when I was at BCM, but I would add "bull's eye maculopathy" (or a better term that describes this finding), which is the specific pattern of pathology that you see in Cohen syndrome.

**Comment by pnrobinson** [comment]
* Bull's eye maculopathy was HP_0011504.
* However, the HPO does not currently have an annotation to Cohen syndrome. I will add this. I found this reference: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1771382/
* I added the definitions for Macular atrophy and Retinal atrophy as suggested
*

**Comment by pnrobinson** [comment]
* Bull's eye maculopathy was HP_0011504.
* However, the HPO does not currently have an annotation to Cohen syndrome. I  added this based on this reference: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1771382/
* I added the definitions for Macular atrophy and Retinal atrophy as suggested

**Comment by pnrobinson** [comment]
Adding geographic atrophy. 
I am using this ref, https://www.ncbi.nlm.nih.gov/pubmed/24158023/
which I think is the same thing but is a pubmed id.
