### ISSUE TITLE
ENR-EYE NTR: Age-related macular degeneration

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3235]
[suppressed] HP:0007868//Macular degeneration//Suppressed//Age-related macular degeneration//HP:0000608//Macular degeneration//please remove - this is a diagnosis (PS); parent- Disciform macular scar [level: 14]; term- Age-related macular degeneration [level: 12]

**Comment by psergouniotis** [comment]
Age-related macular degeneration is a very useful term but it can be argued that it is a disease rather than a phenotype. I cannot decide if it should be kept or not. What do others think?

**Comment by pnrobinson** [comment]
ARMD is used to annotate a number of gene loci. I think that once we have MONDO (the Monarch disease ontology) running, then we can replace terms like this or at least make it logically coherent that they can refer to a disease. This will be a project for 1-2 years, though. I would say let's keep this term for now. Please reopen if you (violently) disagree :-0.

**Comment by psergouniotis** [comment]
Good point about the loci. Probably best to keep it.
