### ISSUE TITLE
ENR-EYE NTR: Granular macular appearance

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3242]
[No action] HP:0007793//Abnormality of macular pigmentation//Granular macular appearance//HP:0008002//Abnormality of macular pigmentation; parent- Abnormality of macular pigmentation [level: 11]; term- Granular macular appearance [level: 12]

**Comment by pnrobinson** [comment]
@psergouniotis  This term has the synonym: "Macular retinal pigment epithelial mottling". Is this correct? If so, should we make it a subclass of RPE mottling?

**Comment by psergouniotis** [comment]
Yes. Granular macular appearance should also be a subclass of "Retinal pigment epithelial mottling". 

Also, "Retinal pigment epithelial mottling" should have "RPE mottling" as a synonym.

**Comment by pnrobinson** [comment]
done
