### ISSUE TITLE
ENR-EYE NTR: Choroidal neovascularization of the macula

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3262]
[No action] HP:0011506//Abnormality of the macula//Choroidal neovascularization of the macula//HP:0001103//Abnormality of the macula; parent- Macular crystals [level: 12]; term- Choroidal neovascularization of the macula [level: 11]

**Comment by pnrobinson** [comment]
@psergouniotis  COuld you take a look at the terms around  Choroidal neovascularization (HP_0011506). This is currently under "Abnormal macular morphology, which would mean that it is restricted to the macula. What was intended with this entry in the excel file?

**Comment by psergouniotis** [comment]
The current term is "Choroidal neovascularization of the macula". It is acceptable to have this as a subclass of "Abnormal macular morphology". I have not done much on CNV in the excel spreadsheet (have left this to the retina WG). 

Choroidal neovascularization needs some work. Technically it is this is an "Abnormality of the choroid" but the retina is typically affected. I think we should have "Abnormality of the choroidal vasculature" as a subclass of "Abnormality of the choroid".

Proposed subclasses of "Abnormality of the choroidal vasculature" (new term):
* Dilatation of large choroidal vessels [HP:0030979]
* Choroidal haemangioma [HP:0007872]
* Choroidal neovascularization (new term) ([HP_0011506] could be a subclass of this)
*  Choroidal hyperpermeability (new term)
*  Polypoidal choroidal vasculopathy (new term)

**Comment by pnrobinson** [comment]
Adding term
Polypoidal choroidal vasculopathy
Def: The presence of aneurysmal polypoidal lesions in the choroidal vasculature. The aneurysmal dilatations, also known as polyps, may be found at subfoveal, juxtafoveal, extrafoveal, peripapillary or even peripheral regions. These polypoidal dilatations may be visible as reddish-orange subretinal nodules during ophthalmoscopic examination. The polypoidal lesions are best detected on indocyanine green angiography (ICGA) and might be associated with a branching vascular network (BVN) of neovascularization. (referencing https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3957043/)

**Comment by pnrobinson** [comment]
Adding term
Choroidal vascular hyperpermeability 
Def: Increased tendency of choiroidal blood vessels to allow fluids to leak characterized by multifocal choroidal hyperfluorescence on indocyanine green angiography (ICGA).
see https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4334323/

**Comment by pnrobinson** [comment]
Finished this reorganization as suggested. Please reopen if you have any additional comments.
