### ISSUE TITLE
ENR-EYE NTR: Macular exudation

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3267]
[No action] HP:0030496//Abnormality of macular vasculature//Macular exudation//HP:0030495//Abnormality of macular vasculature; parent- Macular microaneurysm/hemorrhage [level: 12]; term- Macular exudation [level: 12]

**Comment by pnrobinson** [comment]
@psergouniotis Can you help with a definition?
There are various kinds of exudate including the hard exudates found in diabetic retinopathy
Would this definition be OK?
Def: Distinct yellow-white intra-retinal deposits which can vary from small specks to larger patches and located in the macula.
Do we need to distinguish between various kinds of macular exudate?

**Comment by psergouniotis** [comment]
Macular exudation: the primary term should be macular exudate (syn macular exudation, macular exudates). These should be a subclass of: 
(i) "Retinal exudate (HP:0001147) (proposed syn retinal exudation, retinal exudates).
(ii) "Yellow/white lesions of the macula"

Definition: Yellow-white intraretinal deposits in the macula typically associated  with damaged outer blood-retina barrier and exudation of serous fluid and lipids from the retinal microvasculature. 

I would not recommend distinguishing between different types of exudates. People talk about hard or soft exudates but this is a bit arbitrary (plus the so-called soft exudates are not really exudates).
