### ISSUE TITLE
ENR-EYE NTR: Macular thickening

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3268]
[No action] HP:0030498//Abnormality of the macula//Macular thickening//HP:0001103//Abnormality of the macula; parent- Macular exudation [level: 12]; term- Macular thickening [level: 11]

**Comment by psergouniotis** [comment]
Proposed definition for macular thickening:
"Abnormal increase in retinal thickness in the macular area observed on fundoscopy or fundus imaging"
