### ISSUE TITLE
ENR-EYE NTR: Macular edema

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3270]
[No action] HP:0040049//Macular thickening//Macular edema//HP:0030498//Macular thickening; parent- Macular schisis [level: 12]; term- Macular edema [level: 12]

**Comment by pnrobinson** [comment]
We need a definition for this. 
Proposal
Abnormal leakage and accumulation of extracellular fluid in the macula as a nonspecific re­sponse to a breakdown in the blood-retinal barriers.
Comment: Macular edema can be observed in diabetes mellitus, retinal venous oc­clusion, uveitis, and other conditions including intraocular surgery.

**Comment by psergouniotis** [comment]
Please add "macular oedema" as a synonym.

Definition: Accumulation of extracellular fluid in the macula as a nonspecific response to blood-retinal barrier breakdown. Macular edema is a common pathological response to a wide variety of ocular insults, most commonly after intraocular (e.g. cataract) surgery or in association with retinal vascular (e.g. diabetic eye disease, retinal vein occlusion) or inflammatory (e.g. uveitis) disease.
