### ISSUE TITLE
ENR-EYE NTR: Pigmentary retinopathy

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3274]
[No action] HP:0000580//Abnormality of retinal pigmentation//Pigmentary retinopathy//HP:0007703//Abnormality of retinal pigmentation; parent- Abnormality of retinal pigmentation [level: 10]; term- Pigmentary retinopathy [level: 11]

**Comment by psergouniotis** [comment]
definition and subclasses discussed in #3278, #3279, #3280.
Notably, "Rod-cone dystrophy" should not be a subclass of "Pigmentary retinopathy"

**Comment by psergouniotis** [comment]
Also, please consider adding this as a subclass of "Retinopathy" HP:0000488

**Comment by pnrobinson** [comment]
@psergouniotis Do you think the term "retinopathy" is good? It seems so general that maybe we should merge it with "Abnormal retinal morphology"? Or is there somethiing that makes "Retinopathy" a specific kind of "Abnormal retinal morphology"?

**Comment by Frank-Probst** [comment]
As a non-ophthalmologist, "abnormal retinal morphology" makes me think of a gross structural abnormality of the retina, such as a retinochoroidal coloboma.  "Retinopathy" technically just means there's something wrong with the retina, but in common usage I think of it as meaning that you started with a structurally normal retina, that's now showing an abnormality.

**Comment by psergouniotis** [comment]
Retinopathy is indeed a vague term and I cannot see myself using it to describe a phenotypic abnormality. We could have it though as an intermediate node/term between "abnormality of the retina" and relevant lower level terms (abnormality of retinal pigmentation, retinal dystrophy, retinal degeneration, abnormality of the retinal vasculature etc). I struggle a bit to come up with a definition for retinopathy though - I will have a think about this.

I cannot find "abnormal retinal morphology" on the HPO explorer. Do you plan to add this as a subclass of "abnormality of the retina"? Should I be checking elsewhere for a more updated version of HPO?

In a way, "abnormal retinal morphology" could include things like retinoblastoma, retinal coloboma, retinal perforation etc. I do not think that the term retinopathy will be commonly used to describe these phenotypes.

**Comment by pnrobinson** [comment]
@psergouniotis @Frank-Probst I think the best thing to do is to merge Retinopathy with Abnormal morphology of the retina (which is now the label for Abnormality of the retina). Please comment if you think this is a bad idea

**Comment by psergouniotis** [comment]
I am not sure if it would be the right thing to do. Of the subclasses of "Abnormal retinal morphology" I feel that only the following would be intuitively classified as retinopathy:
* retinal dystrophy
* retinopschisis
* retinal degeneration.
* some subclasses of "abnormality of retinal vasculature"

Most of the rest are perhaps too specific to be considered "Retinopathies". And then there is "Retinopathy of prematurity" and "diabetic retinopathy"...

**Comment by pnrobinson** [comment]
Let us then leave Retinopathy for now, perhaps it is useful for some non-specific annotations when no further information is available.

**Comment by psergouniotis** [comment]
Agree. Many thanks

**Comment by psergouniotis** [comment]
I was just checking "Retinopathy" on HPO workbench. Since we are keeping this, it might be reasoble to move the following as subclasses:
* retinal dystrophy
* retinoschisis
* retinal degeneration

Also, the following could also be included as subclasses 
* hypertensive retinopathy
* exudative retinopathy
* pigmentary retinopathy
