### ISSUE TITLE
ENR-EYE NTR: Pigmentary retinal degeneration

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3278]
[No action] HP:0001146//Pigmentary retinopathy//Pigmentary retinal degeneration//HP:0000580//Pigmentary retinopathy; parent- Retinitis pigmentosa inversa [level: 13]; term- Pigmentary retinal degeneration [level: 12]

**Comment by psergouniotis** [comment]
I am not sure why "Retinal exudates" is a synonym here. This is incorrect. 
"Retinal exudates" should Instead be a synonym of HP:0001146 ("Retinal exudate").

**Comment by pnrobinson** [comment]
OK, I removed this synonym. Please see other request -- is "Pigmentary retinal degeneration" a synonym of "Pigmentary retinopathy"? If not, please provide a definition!

**Comment by pnrobinson** [comment]
@psergouniotis I saw your comment in the other issue. It is hard to find a definition for this term. Also, another issue is that the children of a term should evenly divide up the space. I think that other children such as Bone spiccule pigmentation can also be progressive. I am thinking it might be better to obsolete this term, and use a modification called "progressive" if we want to emphasize that a disease or a patient has "progressive" pigmentary retinopathy.

**Comment by psergouniotis** [comment]
Valid point - I agree, best to obsolete the term "Pigmentary retinal degeneration". Users could use the modifier progressive instead.

**Comment by pnrobinson** [comment]
revised up to 180210

**Comment by pnrobinson** [comment]
revised annotations. Term has been merged
