### ISSUE TITLE
ENR-EYE NTR: Pigmentary retinal deposits

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3279]
[No action] HP:0007702//Pigmentary retinopathy//Pigmentary retinal deposits//HP:0000580//Pigmentary retinopathy; parent- Pigmentary retinal degeneration [level: 12]; term- Pigmentary retinal deposits [level: 12]

**Comment by psergouniotis** [comment]
I think this term (Pigmentary retinal deposits) should be made a synonym of its parent term (Pigmentary retinopathy).

**Comment by pnrobinson** [comment]
Are you OK with making Pigmentary retinal deposits the primary label?  Pigmentary retinopathy sounds more like a disease than a phenotype, and so I would make it a synonym.

**Comment by psergouniotis** [comment]
Not an easy one. Your point is valid but "Pigmentary retinopathy" is a widely used term to describe an appearance/phenotype rather than a diagnosis (for example pigmentary retinopathy can be due to rubella, retinitis pigmentosa or drug toxicity). I would therefore be inclined to keep "Pigmentary retinopathy" as the primary term. 

On a different note, perhaps "Bone spicule pigmentation of the retina" and "Nummular pigmentation of the retina" should be subclasses of "Pigmentary retinopathy" (/ "Pigmentary retinal deposits")

**Comment by pnrobinson** [comment]
OK. I have merged the classes as recommended. Do you agree with this definition of Pigmentary retinopathy:

An abnormality of the retina that is characterized by deposits of pigment with associated loss of vision. Pigmentary retinopathy is caused by migration and proliferation of macrophages or retinal pigment epithelial (RPE) cells into the retina. The melanin contained by these cells causes the pigmentary changes. Pigmentary retinopathy is a common final pathway of many retinal diseases usually associated with a progressive loss of vision.

**Comment by pnrobinson** [comment]
One more thing -- "Pigmentary retinal deposits" had "Retinal pigment clumping" as a synonym. I am also adding this as a synonym to "Pigmentary retinopathy" Is this correct?

**Comment by pnrobinson** [comment]
What about the other subclass, Pigmentary retinal degeneration. That sounds like a synonym too. The latter term has an exact synonym of "Retinal exudates" but I think this is a mistake. Should we have a separate term for Retinal exudates?

**Comment by psergouniotis** [comment]
(i) Definition of pigmentary retinopathy: 
Perhaps: An abnormality of the retina characterized by pigment deposition. It is typically associated with migration and proliferation of macrophages or retinal pigment epithelial cells into the retina; melanin from these cells causes the pigmentary changes. Pigmentary retinopathy is a common final pathway of many retinal conditions and is often associated with visual loss.

The reason for the modification is that rubella retinopathy (an emblematic cause of pigmentary retinopathy) is often associated with normal electrodiagnostic testing (suggesting mild or no visual dysfunction). 

(ii) I think I would add both  "Pigmentary retinal deposits" and "Retinal pigment clumping" as synonyms of "Pigmentary retinopathy".

(iii) "Pigmentary retinal degeneration". This is subtle. For me "Pigmentary retinal degeneration" should perhaps remain a subclass of "Pigmentary retinopathy" as it suggests a degenerative process with likely progression. In contrast, forms of pigmentary retinopathy are stationary with no ongoing degeneration.

(iv) I have commented on "Retinal exudates" in a different thread. It should be made a synonym of "Retinal exudate" (HP:0001147).

**Comment by pnrobinson** [comment]
(i) done
(ii) done
(iii) ok, let's leave the class as is
(iv) ok with suggestions for retinal exudates
