### ISSUE TITLE
ENR-EYE NTR: Rarefaction of retinal pigmentation

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3280]
[No action] HP:0007961//Pigmentary retinopathy//Rarefaction of retinal pigmentation//HP:0000580//Pigmentary retinopathy; parent- Pigmentary retinal deposits [level: 12]; term- Rarefaction of retinal pigmentation [level: 12]

**Comment by psergouniotis** [comment]
This term is not used in ophthalmic practice. I could find one reference (PMID: 10748412) and this is not from an ophthalmology group. I propose suppressing this term and merging the content with "Abnormality of fundal pigmentation".

**Comment by pnrobinson** [comment]
In our corpus, the term is used only once for Spondylocarpotarsal synostosis

https://www.ncbi.nlm.nih.gov/pubmed/10748412
The abstract states:
Lens opacities, rarefaction of retinal pigmentation, and narrowing of retinal vessels, detected in two patients, are findings that have not been described to date in this condition.
As far as I can see, this was not described in any further patients.

**Comment by psergouniotis** [comment]
I think it would be reasonable to remove this term - it is suboptimal and poorly defined. There is no further information or images in the Steiner et al paper and I could not figure out what they mean despite checking other papers on spondylocarpotarsal synostosis

**Comment by pnrobinson** [comment]
OK, this term has been obsoleted!
