### ISSUE TITLE
ENR-EYE NTR: Retinal pigment epithelial atrophy

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3281]
[No action] HP:0007722//Abnormality of retinal pigmentation//Retinal pigment epithelial atrophy//HP:0007703//Abnormality of retinal pigmentation; parent- Rarefaction of retinal pigmentation [level: 12]; term- Retinal pigment epithelial atrophy [level: 11]

**Comment by psergouniotis** [comment]
"Retinal pigment epithelial atrophy" should not be a subclass of "Abnormality of retinal pigmentation". Instead it should be added as a subclass of "Retinal atrophy (HP:0001105)"

**Comment by pnrobinson** [comment]
Moved this class as recommended
