### ISSUE TITLE
ENR-EYE NTR: With preservation around the retinal arterioles

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3283]
[No action] With preservation around the retinal arterioles; parent- Patchy atrophy of the retinal pigment epithelium [level: 12]; term- With preservation around the retinal arterioles [level: 12]

**Comment by psergouniotis** [comment]
No further subclasses are recommended for "Patchy atrophy of the retinal pigment epithelium". I am not sure what "With preservation around the retinal arterioles" refers to.

**Comment by pnrobinson** [comment]
I think this was supposed to be
Retinal pigment epithelial atrophy
--Patchy atrophy of the retinal pigment epithelium
--With preservation around the retinal arterioles

Were these comments or should they be new terms? @psergouniotis

**Comment by psergouniotis** [comment]
I am not sure about the comment. I do not think "With preservation around the retinal arterioles" should be added as a subclass. 

Also, I would consider changing the definition for "Retinal pigment epithelial atrophy":
Loss of the retinal pigment epithelium observed on fundoscopy or fundus imaging.

**Comment by pnrobinson** [comment]
OK -- I have slightly modified the suggested definition as follows:
Atrophy (loss or wasting) of the retinal pigment epithelium observed on fundoscopy or fundus imaging.
Let me know if this is not good.
