### ISSUE TITLE
ENR-EYE NTR: Bone spicule pigmentation of the retina

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3284]
[No action] HP:0007737//Abnormality of retinal pigmentation//Bone spicule pigmentation of the retina//HP:0007703//Abnormality of retinal pigmentation; parent- With preservation around the retinal arterioles [level: 12]; term- Bone spicule pigmentation of the retina [level: 11]

**Comment by psergouniotis** [comment]
No changes recommended for this term.
Possible textual definition: Pigment migration into the retina in a bone-spicule configuration (resembling the nucleated cells within the lacuna of bone).

**Comment by pnrobinson** [comment]
Altered the definition as suggested
