### ISSUE TITLE
ENR-EYE NTR: Retinal pigment epithelial mottling

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3285]
[No action] HP:0007814//Abnormality of retinal pigmentation//Retinal pigment epithelial mottling//HP:0007703//Abnormality of retinal pigmentation; parent- Bone spicule pigmentation of the retina [level: 11]; term- Retinal pigment epithelial mottling [level: 11]

**Comment by psergouniotis** [comment]
This should remain as a subclass of "Abnormality of retinal pigmentation" (NOT "Bone spicule pigmentation of the retina").
Textual definition for "Retinal pigment epithelial mottling": Localised or generalised fundal pigment granularity associated with processes at the level of the retinal pigment epithelium.

**Comment by pnrobinson** [comment]
OK -- I have changed the definition to 
Mottling (spots or blotches with different shades) of the retinal pigment epithelium, i.e., localized or generalized fundal pigment granularity associated with processes at the level of the retinal pigment epithelium.
because I wanted to have some definition of what mottling is for non-specialists. Is this OK so?

**Comment by psergouniotis** [comment]
Perhaps:
"Localized or generalized fundal pigment granularity associated with processes at the level of the retinal pigment epithelium. Mottling suggests spots/blotches with different shades."

The reason why I recommend this modification is because mottling is observed in the fundus but the appearance suggests RPE degeneration/dysfunction.

**Comment by pnrobinson** [comment]
My worry is that I do not think that non ophthalmologists will understand what fundal pigment granularity is. How about this

"Localized or generalized fundal pigment granularity (mottling, i.e., spots/blotches with different shades) suggesting pathological processes at the level of the retinal pigment epithelium.

**Comment by psergouniotis** [comment]
The one you proposed should work well. 

> "Localized or generalized fundal pigment granularity (mottling, i.e., spots/blotches with different shades) suggesting pathological processes at the level of the retinal pigment epithelium.

**Comment by pnrobinson** [comment]
OK!
