### ISSUE TITLE
disease-phenotype associations request for the NGLY1 deficiency

### ISSUE THREAD

**Issue by NuriaQueralt** [obophenotype/human-phenotype-ontology#3287]
Dear HPO team,

I have 101 disease-phenotype associations that i curated from https://www.ncbi.nlm.nih.gov/pubmed/27388694. See the file attached.
[ngly1_deficiency_hpo_annotation_AndrewSuLab_v2017.zip](https://github.com/obophenotype/human-phenotype-ontology/files/1520605/ngly1_deficiency_hpo_annotation_AndrewSuLab_v2017.zip)

Please, if this is of your interest, let me know the convenient file format to add the curated disease-phenotype associations for the NGLY1 deficiency to the HPO/Monarch projects. 

Thanks!

Núria

**Comment by pnrobinson** [comment]
Thanks, Nuria, this is very useful. We will try to add this in the next few days. We would not use the DO id for the disease, this is not the main source of rare disease identifiers, though.

**Comment by NuriaQueralt** [comment]
Excellent! glad to hear that it is of interest. The disease is also identified by OMIM:615273, ORPHA:404454. Please, let me know whatever you need from me in this regard. Thanks Dr Robinson.

**Comment by pnrobinson** [comment]
@LCCarmody  Could we talk about how to incorporate this?

**Comment by LCCarmody** [comment]
Sure, we can go over this. Thx.

**Comment by pnrobinson** [comment]
sorry for the delay. I added most of these suggested annotations and frequencies. Thanks again!
