### ISSUE TITLE
"small eyes" synonym of "Narrow palpebral fissure" ?

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#3288]
@markengelstad you are listed as creator of the lay-synonym "small eyes" for the class "Narrow palpebral fissure". I am not really convinced that this is correct. Are you sure about this?

**Comment by pnrobinson** [comment]
What about "Narrow space between the eyelids"

**Comment by drseb** [comment]
So you agree that "small eyes" is wrong?

**Comment by pnrobinson** [comment]
Yes, I think that Small eyes is not really a synonym

**Comment by Frank-Probst** [comment]
TEST
Agree that "small eyes" isn't really correct.  That would be microphthalmia, which is when the globe of the eye itself is small.  Subgroups would be left, right, and bilateral microphthalmia, since it doesn't always affect both eyes.

"Narrow space between the eyelids" isn't really a good synonym here, because it doesn't specify horizontal space (which is what the term means) versus vertical space, which may seem illogical, because that depends on how far open the eyelids are, but I think people will read this definition as how far open the eyelids USUALLY are and confuse the term with ptosis (droopy eyelids).

Unfortunately, I don't think this term really has a lay synonym, even though it's usually obvious when you actually see it.
TEST

**Comment by Frank-Probst** [comment]
@pnrobinson Am I doing this right?

**Comment by pnrobinson** [comment]
@Frank-Probst yes, this looks great. @drseb So we should definitely remove small eyes as a synonym. Unless somebody can think of a better lay person synonym, I would close this issue.

**Comment by markengelstad** [comment]
I agree with you guys completely. Small eyes is not accurate and should be deleted as a synonym. Perhaps "narrow set eyes" or, as PR suggests, " narrow space between the eyes"

**Comment by markengelstad** [comment]
Or "eyes close together"

**Comment by Frank-Probst** [comment]
"Narrow set eyes", "narrow space between the eyes", and "eyes close together" all sound like hypotelorism to me.  "Short palpebral fissures" is probably a synonym but not a lay term.

**Comment by markengelstad** [comment]
Yes, the preferred clinical label ( not lay) would be hypotelorism

**Comment by markengelstad** [comment]
Yes, the preferred clinical label ( not lay) would be hypotelorism

**Comment by drseb** [comment]
Thanks everybody. Please remember that this ticket was about "Narrow palpebral fissure" and not about hypotelorism. 
I will fix this tomorrow, add suggested synonyms to Hypotelorism, and close afterwards.

**Comment by drseb** [comment]
Ah, I see. I will only remove the lay-synonym and leave Hypotelorism as it is. Thanks.

**Comment by markengelstad** [comment]
Okay, now I'm slightly less confused why I suggested small eyes. We are talking about narrow palpebral fissure here, not reduced distance between the eyelids. In that case, instead of small eyes, perhaps small eyelid opening or narrow eyelid opening would be better.

**Comment by pnrobinson** [comment]
Of all suggestion I think Narrow eyelid opening sounds like the best LP synonym!

**Comment by Frank-Probst** [comment]
I agree on the LP synonym but would still suggest "short palpebral fissures" (if it's not already there) as a clinical synonym.  It's not really accurate terminology, but it's still widely used in clinical genetics.

**Comment by Frank-Probst** [comment]
Just checked--"short palpebral fissure(s)" is the preferred term in the genetics world.  (I don't think the picture is very good, though.)  https://elementsofmorphology.nih.gov/index.cgi?tid=8ea165ff88fe04c3

**Comment by psergouniotis** [comment]
Agree with all:
* "small eyes" not a synonym of "narrow palpebral fissure",
* "narrow eyelid opening" is an appropriate lay person synonym for "narrow palpebral fissure".
* "short palpebral fissure" can be a synonym of "narrow palpebral fissure"

I note that in the explorer "narrow palpebral fissure" seems to be a synonym of "blepharophimosis". This is not accurate (we could open a new thread on this)

**Comment by drseb** [comment]
Thanks. I have kept _narrow palpebral fissure_ and _short palpebral fissure_ separate classes. I have moved the synonym "narrow palpebral fissures" from "blepharophimosis" to "narrow palpebral fissure" (note singular vs plural, which is the reason why the QC pipeline didn't catch this one)
