### ISSUE TITLE
Autosomal recessive intellectual disability 58

### ISSUE THREAD

**Issue by GARDInfoCenter** [obophenotype/human-phenotype-ontology#3290]
The Genetic and Rare Diseases Information Center (GARD) recently received an inquiry from a mother whose child has autosomal recessive intellectual disability 58. She was confused regarding the frequency information for the symptoms associated with this genetic condition. All the symptoms currently listed, including intellectual disability, are "Very Rare". We are asking that you please review the frequency designation for these symptoms. 

Signs and Symptoms | Approximate number of patients (when available)

Delayed speech and language development | Very rare (present in 1%-4% of cases)
Hyperreflexia | Very rare (present in 1%-4% of cases)
Intellectual disability | Very rare (present in 1%-4% of cases)
Muscular hypotonia of the trunk | Very rare (present in 1%-4% of cases)
Pica | Very rare (present in 1%-4% of cases)
Poor head control | Very rare (present in 1%-4% of cases)
Self-injurious behavior | Very rare (present in 1%-4% of cases)
Spastic diplegia | Very rare (present in 1%-4% of cases)
Aggressive behavior | -
Autosomal recessive inheritance | -
Choreoathetosis | -
Congenital onset | -
Progressive | -

Thank you, 
Maria Della Rocca 
Bilingual Information Specialist 

Genetic and Rare Diseases Information Center
Email: maria.dellarocca@icf.com

**Comment by drseb** [comment]
I do not know where you pull your data from. I do not find a disease with this name in our annotation-data. Can you give us more information?

**Comment by GARDInfoCenter** [comment]
http://compbio.charite.de/hpoweb/showterm?disease=OMIM:617270


My apologies. At GARD, we have changed all our terms to not include mental retardation. We have been told to use "intellectual disability" instead.


Maria

________________________________

**Comment by drseb** [comment]
Ok. Thanks. If possible, please mention Orphanet or OMIM identifiers in the tickets please.

I will look into the frequency data

**Comment by LOURGHI** [comment]
The entity does not exist in orphanet but I think it is possible to create it I transmitted the information to the health team and I will keep you informed of its creation or not.

**Comment by pnrobinson** [comment]
The human genetics community has supported the move from MR to ID. Please note, howeer, that some disease names still use the "mental retardation" form, e.g., http://omim.org/entry/309530?search=mental%20retardation&highlight=retardation%20mental
Therefore, an automatic substitution might not be a good idea.

**Comment by GARDInfoCenter** [comment]
Do you have a way to continue to list terms for historical purposes, but not list them as the main term?

**Comment by cmungall** [comment]
We're going to implement MR->ID in MONDO: https://github.com/monarch-initiative/mondo-build/issues/34

We will record the original terms as a synonym marked 'deprecated' (perhaps 'historic' would be better)

**Comment by cmungall** [comment]
@pnrobinson when you say an automatic substitution not be a good idea because "some disease names still use the "mental retardation" form, e.g., http://omim.org/entry/309530?search=mental%20retardation&highlight=retardation%20mental"

Are you saying we should not change "MENTAL RETARDATION, X-LINKED 1; MRX1"

to something like "intellectual disability, X-linked 1"

(retaining synonyms for all OMIM lexical forms)

what would be the negative consequences of making the change? People would still find the disease if they searched using the OMIM string. Is it the case that clinical geneticists would be expecting to find the string "MENTAL RETARDATION, X-LINKED 1" as the primary label?

**Comment by pnrobinson** [comment]
Well I am concerned that by introducing new names we may not be reducing the overall amount of confusion. Traditionally, OMIM has been the naming authority in human genetics. Perhaps we should ask them if they would be willing to do a s/MR/ID/g, retaining legacy synonyms. I suspect the reason that they might be reticent to do so is that it would make it more difficult to find things in the literature.

**Comment by pnrobinson** [comment]
I have added the frequency information. This is a rare disease and so there are not many patients recorded in the literature (2 patients, both of whom had ID).
