### ISSUE TITLE
McArdle disease

### ISSUE THREAD

**Issue by GARDInfoCenter** [obophenotype/human-phenotype-ontology#3291]
The Genetic and Rare Diseases Information Center (GARD) received an inquiry from a person who thought "Adult onset" should not appear as a medical term associated with McArdle disease. Although most cases are not diagnosed until adulthood, onset is actually in childhood.  Please reconsider this symptom. 

Best regards,
Maria Della Rocca
Bilinqual Information Specialist
maria.dellarocca@icfi.com

**Comment by pnrobinson** [comment]
This is a nice review
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3658246/
The disease is GLYCOGEN STORAGE DISEASE V in our corpus and is annotated to the term Adult onset. I believe this annotation is derived from the OMIM entry, and yet that entry states in the text "McArdle disease is an autosomal recessive metabolic disorder characterized by onset of exercise intolerance and muscle cramps in childhood or adolescence." Therefore I think it is correct to say that the initial symptoms often appear early, in childhood or adolescence, but the severe symptoms often appear in adulthood. Probably the best way of capturing this information is to annotate the individual terms with onset information. But I agree that the overall disease onset should be set to childhood.
(todo)

**Comment by nicolevasilevsky** [comment]
@pnrobinson I can help update this, if you like.

**Comment by pnrobinson** [comment]
please do so.!

**Comment by pnrobinson** [comment]
I am going to annotate this as Juvenile onset (5-15 years) according to this publication
https://www.ncbi.nlm.nih.gov/pubmed/22250184
In the majority of patients (86%), symptoms started within the first two decades of life; indeed, in 58% of patients, symptoms started in the first decade, typically in school sport activities.

I am also updating some of the other annotations
