### ISSUE TITLE
Phenotypic variability

### ISSUE THREAD

**Issue by GARDInfoCenter** [obophenotype/human-phenotype-ontology#3293]
Although many diseases have phenotypic variability, we here at the Genetic and Rare Diseases Information Center (GARD) are not seeing that this symptom is being used consistently or frequently. We recommend removing this term as a symptom since it is not being used consistently. The disease name for the case we were working on was Joubert disease. 

Thank you,
Maria Della Rocca
Bilingual Information Specialist
maria.dellarocca@icf.com

**Comment by pnrobinson** [comment]
@drseb Please comment
I think that the term Phenotypic variability is currently a parent for "incomplete penetrance" and "variable expressivity", which are probably useful in some situations. Currently, HPO annotates some diseases with "Phenotypic variability", and I agree that this is not being done in a consistent fashion. Probably these diseases need to be re-annotated.

**Comment by drseb** [comment]
Hmm... is there a way to systematically determine which disease are missing the annotation to "Phenotypic variability"?

**Comment by pnrobinson** [comment]
The thing is that all (really "all"!) diseases have some degree of phenotypic variability. Otherwise we would have frequency=100% for all of our annotations. I do not think that the term is really that useful and think that we should not use it for direct annotations. The child term "decreased penetrance" can be useful. The child term "increased expressivity" is also something that is better captured by frequency. In any case, I do not think we would loose anything by just deleting all annotations to "Phenotypic variability".

**Comment by drseb** [comment]
ok.

**Comment by nicolevasilevsky** [comment]
Hi- I spoke to some folks at GARD today and I want to see if I can help address these open tickets. Sounds like phenotypic variability should be removed from all of the annotations? Can I help with this?

**Comment by pnrobinson** [comment]
Hi Nicole,
it would be great to have your work on the open issues from GARD. I think that it might be easiest to remove the phenotypic variability terms while we are updating the annotation format. I wanted to take another look at that and see how many times the term has been used in our corpus first

**Comment by pnrobinson** [comment]
@drseb @nicolevasilevsky I think we dropped the ball on this.
There are 677 annotations in our corpus
https://hpo.jax.org/app/browse/term/HP:0003812
Unless somebody is against this, I would propose the following
1. I will go through about 20 diseases and see exactly how the term is being used. I think that probably it either means "Decreased penetrance" or "Highly variable clinical expressivity". These terms are not themselves useful for computations but they might be useful for human consumption.
2. If (1) is correct, then I would suggest that we slowly revise these annotations, and then remove the term "phenotypic variability", which is close to meaningless.
3. If the annotation is used in an inconsistent way across the diseases, then we should remove automatically.

**Comment by nicolevasilevsky** [comment]
@pnrobinson this sounds like a good plan. 

I can work on reviewing/updating these annotations in the next few weeks as well.

**Comment by pnrobinson** [comment]
@drseb I thnk we should probably remove this term -- as stated above, it is used inconsistently. I checked a bunch of diseases, and in some cases OMIM has removed the annotation. Can you easily do this with a script?

**Comment by drseb** [comment]
Should we just use `sed` for this?

**Comment by pnrobinson** [comment]
Hi @drseb 
Should we then just do the following
```
 sed -i  '/HP:0003812/d' *.tab
```
HP:0003812 is the id for Phenotypic variability. I tested this without the ``-i`` (-i changes in place) and it seemed to work. Will this break anything on your side?

**Comment by drseb** [comment]
@pnrobinson please do that! note that the way you use the option -i only works on linux-machines. (parameters are different on a mac)

**Comment by pnrobinson** [comment]
Well, I have a linux box. But if you have a better way of doing this could you please do the honors?

**Comment by pnrobinson** [comment]
Sorry seb I misunderstood you message I will do this tomorrow

**Comment by pnrobinson** [comment]
OK, I have removed all of these terms. @drseb please do not forget to skip Phenotypic variability for text mining. I will create a phenotype-omit.txt file in a sec.
