### ISSUE TITLE
Add Definition/Synonyms to Knee Joint Hypermobility

### ISSUE THREAD

**Issue by krageth** [obophenotype/human-phenotype-ontology#3294]
>1. Preferred term label (e.g., Asplenia)_
Existing Label: Knee Joint Hypermobility
HP_0045086

>2. Synonyms (e.g., Absent spleen)
Syn: Knee Hyperextension, Knee  joint over-flexibility
Both could be Lay Person Synonyms 
PMID:28599980

>3. Textual definition (the definition should be understandable even for non-specialists. Include a PubMed ID to refer to any relevant article that provides additional information about the suggested term).

The  ability of the knee to move past its normal range of motion, (knee hyperextension is greater than 10°), passive knee joint hypermobility allows one to place the palms flat on the floor with the knees fully extended.
(not sure if all of that definition is needed)

>4. Suggested parent term (Please look in the hierarchy of the HPO using the [HPO Browser](http://compbio.charite.de/hpoweb/showterm?id=HP:0000118) or other browsers such as [OLS](http://www.ebi.ac.uk/ols/ontologies/hp) and find the place in the HPO where the new term best fits)
HP_0001382

>5. If you know of a disease that is characterized by this feature, please indicate it (e.g., by its Orphanet or OMIM id), and we will add the annotation to our database.

**Comment by pnrobinson** [comment]
I am leaving this out: Passive knee joint hypermobility allows one to place the palms flat on the floor with the knees fully extended.
because it is not the only factor -- the back and arms need a certain flexibility as well? If this is wrong we can add this as a comment.

**Comment by pnrobinson** [comment]
@krageth Should this term be made a synonym to Genu recurvatum?
https://www.ncbi.nlm.nih.gov/pubmed/9580896

**Comment by pnrobinson** [comment]
I am seeing there are 3 terms that seem to be near synonyms
* Knee joint hypermobility
* Genu recurvatum
* Hyperextensibility of the knee
we need to consider merging or better differentiating these terms.

**Comment by pnrobinson** [comment]
I am seeing there are 3 terms that seem to be near synonyms
* Knee joint hypermobility
* Genu recurvatum
* Hyperextensibility of the knee
we need to consider merging or better differentiating these terms.

**Comment by krageth** [comment]
@pnrobinson I agree with your previous above comment. I think knee joint hypermobility should be a synonym of Genu recurvatum. To me this makes the most sense. I think it adds definition clarity as well.

**Comment by pnrobinson** [comment]
For now I have made Knee joint hypermobility and Genu recurvatum subclasses of Hyperextensibility of the knee, because their definitions are distinct and the Hyperextensibility term is the most general. We may need to revise this with orthopedic input in the future.
