### ISSUE TITLE
New Term: Recurrent Shoulder Dislocation

### ISSUE THREAD

**Issue by krageth** [obophenotype/human-phenotype-ontology#3295]
>If this is a request for a new term, please provide us with the folloing information (c.f., https://github.com/obophenotype/human-phenotype-ontology/wiki/How-to-make-a-good-term-request).
This phenotype and Recurrent patellar dislocation are part of the Beighton Hypermobility diagnostic Score. Recurrent patellar dislocation (HP_0005001) is in the ontology so I thought maybe we should evaluate this phenotype since it is part of the same score but Recurrent should dislocate is not defined, nor does it have a term. 

>1. Preferred term label (e.g., Asplenia)_
Recurrent Shoulder dislocation

>2. Synonyms (e.g., Absent spleen)
Syn/LaySyn: Multiple shoulder dislocation

>3. Textual definition (the definition should be understandable even for non-specialists. Include a PubMed ID to refer to any relevant article that provides additional information about the suggested term).
Shoulder  dislocation occurring repeated times
https://www.ncbi.nlm.nih.gov/books/NBK1244/
PMID: 29197942

>4. Suggested parent term (Please look in the hierarchy of the HPO using the [HPO Browser](http://compbio.charite.de/hpoweb/showterm?id=HP:0000118) or other browsers such as [OLS](http://www.ebi.ac.uk/ols/ontologies/hp) and find the place in the HPO where the new term best fits)
HP_0003834

>5. If you know of a disease that is characterized by this feature, please indicate it (e.g., by its Orphanet or OMIM id), and we will add the annotation to our database.

>6. If you would like a nanoattribution, please indicate your ORCID id or provide a label such as HPO:probinson (organization, first initial-last name)
0000-0002-6387-4317

**Comment by pnrobinson** [comment]
Added as HP_0031610
