### ISSUE TITLE
New Term Request: Pelvic organ prolapse

### ISSUE THREAD

**Issue by krageth** [obophenotype/human-phenotype-ontology#3298]
>If this is a request for a new term, please provide us with the folloing information (c.f., https://github.com/obophenotype/human-phenotype-ontology/wiki/How-to-make-a-good-term-request).

>1. Preferred term label (e.g., Asplenia)_

Pelvic organ prolapse

>2. Synonyms (e.g., Absent spleen)

protrusion of pelvic organs, POP,

>3. Textual definition (the definition should be understandable even for non-specialists. Include a PubMed ID to refer to any relevant article that provides additional information about the suggested term).

weakness   in the supporting structures of the pelvic floor allowing the pelvic viscera   to descend or one or more of the pelvic organs drop from their normal   position

PMCID: PMC3056425

>4. Suggested parent term (Please look in the hierarchy of the HPO using the [HPO Browser](http://compbio.charite.de/hpoweb/showterm?id=HP:0000118) or other browsers such as [OLS](http://www.ebi.ac.uk/ols/ontologies/hp) and find the place in the HPO where the new term best fits)

>5. If you know of a disease that is characterized by this feature, please indicate it (e.g., by its Orphanet or OMIM id), and we will add the annotation to our database.

>6. If you would like a nanoattribution, please indicate your ORCID id or provide a label such as HPO:probinson (organization, first initial-last name)
0000-0002-6387-4317

**Comment by pnrobinson** [comment]
Added term. Using nanoattribution Sanford:krageth, let me know if that is suboptimal

**Comment by krageth** [comment]
@pnrobinson that works! Thank you!
