### ISSUE TITLE
Term Definition: Cystocele

### ISSUE THREAD

**Issue by krageth** [obophenotype/human-phenotype-ontology#3299]
>If this is a request for a new term, please provide us with the folloing information (c.f., https://github.com/obophenotype/human-phenotype-ontology/wiki/How-to-make-a-good-term-request).
Just Needs a Quick Definition Check

>1. Preferred term label (e.g., Asplenia)_

cystocele

HP_0100645
>2. Synonyms (e.g., Absent spleen)

Prolapsed bladder, dropped bladder (LaySyn), bladder hernia (LaySyn)

https://www.niddk.nih.gov/health-information/urologic-diseases/bladder-control-problems-women/cystocele-prolapsed-bladder

>3. Textual definition (the definition should be understandable even for non-specialists. Include a PubMed ID to refer to any relevant article that provides additional information about the suggested term).
Current Definition: When   the tough fibrous wall between a woman's bladder and her vagina (the   pubocervical fascia) is torn, allowing the bladder to herniate into the   vagina. 

(Definition check - the bladder tissue remains covered by the vaginal  skin, therefore, not torn??), I think it should be the following, "bulging  or dropping of the bladder into the vagina,"

https://www.health.harvard.edu/womens-health/uterine-and-bladder-prolapse

>4. Suggested parent term (Please look in the hierarchy of the HPO using the [HPO Browser](http://compbio.charite.de/hpoweb/showterm?id=HP:0000118) or other browsers such as [OLS](http://www.ebi.ac.uk/ols/ontologies/hp) and find the place in the HPO where the new term best fits)

>5. If you know of a disease that is characterized by this feature, please indicate it (e.g., by its Orphanet or OMIM id), and we will add the annotation to our database.

>6. If you would like a nanoattribution, please indicate your ORCID id or provide a label such as HPO:probinson (organization, first initial-last name)

**Comment by pnrobinson** [comment]
Thanks! I am updating the definition as follows and will add the synonyms.
Anterior vaginal wall prolapse with bulging of the bladder into the vagina. 
Comment: Cystocele occurs owing to weakening and stretching of the suppoortive tissue between the bladder and the vaginal wall.
