### ISSUE TITLE
Logical definition for 'beaded ribs' HP:0000923

### ISSUE THREAD

**Issue by azankl** [obophenotype/human-phenotype-ontology#3300]
How about:
Intersection of
    - fractured
    - 'inheres in' some 
      rib
    - 'has modifier' some 
      abnormal

However, beaded ribs are characterised by multiple fractures in one rib, is there a way to express this?

ORCID: 0000-0001-8612-1062

**Comment by cmungall** [comment]
the equivalence axiom should reflect the text def, this doesn't seem 
right.

**Comment by azankl** [comment]
Hi Chris,

Another example of imprecise medical terminology. The current textual
definition refers to the 'rachitic rosary' type lesions seen in rickets and
related disorders. But beaded ribs can also refer to multiple rib fractures
with associated callus formation giving the appearance of beaded ribs. See
Figure 7 in this paper:
http://pubs.rsna.org/doi/pdf/10.1148/radiographics.22.1.g02ja1287

In my opinion, beaded ribs more commonly refers to multiple fractures
rather than rachitic rosary. The 4 conditions annotated with beaded ribs
all have beaded ribs caused by multiple fractures. So would suggest
changing the textual definition for beaded ribs to 'multiple rib fractures
with associated callus formation giving the appearance of beaded ribs'.
There is already a term for rachitic rosary (HP:0000897).

If you agree with the new textual definition, how do we express the fact
that there have to be *multiple* fractures in the logical definition?

Also, one could argue that beaded ribs only applies if the multiple
fractures happen to exhibit the beaded appearance, so beaded ribs and
multiple fractures is not totally equivalent, but I believe that level of
detail would be hard to express in a logical definition and thus my
definition would be acceptable. That problem would apply to many logical
definitions (is it better to have a logical definition that is pretty close
to the textual one than having no logical definition at all?). Would be
interested in your thoughts! Start to warm to the concept of logical
definitions, but struggle with problems like the above. Have also cc'ed
Peter in case he some thoughts on this.

Regards
Andreas

**Comment by pnrobinson** [comment]
Hi Andreas,
thanks for these suggestions. But note that the HPO terms try note to refer to the etiology of a condition. In theory, the term should be something that you could diagnose just by looking at a chest x ray without knowing the diagnosis. Also, the definition is circular
multiple rib fractures with associated callus formation giving the appearance of beaded ribs'.
Can we come up with a definition that will describe the beading?
Here is one: https://en.wikipedia.org/wiki/Rachitic_rosary
and here is another: 
https://radiopaedia.org/articles/rachitic-rosary
These two definitions do not seem to be equivalent!

**Comment by azankl** [comment]
Hi Peter,

How about the following textual definition: “multiple rounded expansions along the ribs”. Rachitic rosary caused by rickets is different from beaded ribs caused by fractures. Since beaded ribs is mostly assigned to bone fragility disorders, I believe beaded ribs refers to multiple fractures and not rickety changes.

Amazing how hard it is to be precise and consistent!

If we try to avoid mentioning fractures, what would the logical definition be? Something like:

Intersection of
expanded
- 'inheres in' some
 rib
 - 'has modifier' some
 abnormal

Still wonder how to express the ‘multiple’ aspect in a logical definition.

Regards
Andreas

**Comment by cmungall** [comment]
Are these rounded expansions seen on bones other than ribs? If so, then 
we want a standard pattern for representing this.

If not, then there is no value in making a specific PATO class that 
would only be used once.

**Comment by pnrobinson** [comment]
@azankl AFAIK the adjective "beaded" is only used for ribs. Is this true?

**Comment by azankl** [comment]
@pnrobinson yes, 'beaded' is only used with ribs.
@cmungall these rounded expansions are only seen on ribs, so I think we can stick with 'expanded' for the logical definition, which is already in PATO.  Can you please tell me how to handle the 'multiple' aspect?

**Comment by cmungall** [comment]
You can't really formally do this and stay within EL++. In fact it's not clear that DL would give a satisfactory representation. You could simple pre-coordinate 'multiple beaded expansions' in PATO, but if this is never used anywhere else then there is no inferential power gained. Is there a use case for a more granular representation?

**Comment by azankl** [comment]
I just discovered HP:0006640 'multiple rib fractures', maybe beaded ribs
should be a child of this term?

**Comment by azankl** [comment]
I was trying to come up with a logical definition in the spirit of
'everything should have a logical definition to facilitate cross-species
phenotype comparisons'. Maybe its too specialised a term to be worth it.
But I still think the textual definition should be changed as the
definition currently refers to rachitic rosary, but the term is annotated
to disorders with increased bone fragility.

**Comment by pnrobinson** [comment]
Hi Andreas,
according to WP, beaded ribs and rachitic rosary are synonymous
https://en.wikipedia.org/wiki/Rachitic_rosary
According to their reference, this goes back to an article from 1900.
Noting that the HPO does not intend to code etiologies, I think it is probably OK to leave it. We currently have a separate term for Rachitic rosary -- I will leave both, as I think the phenotypes are different, although it is hard to define this unambiguously in English.
I modified the definition of beaded ribs slightly:
Def: The presence of a row of multiple rounded expansions (beadlike prominences) at the junction of a rib and its cartilage.
