### ISSUE TITLE
hyperplasia

### ISSUE THREAD

**Issue by mellybelly** [obophenotype/human-phenotype-ontology#3301]
need parent term, there are many potential child terms
there is also a NCIT term NCIT:C113

An abnormal increase in the number of cells in an organ or a tissue with consequent enlargement.

**Comment by pnrobinson** [comment]
I would suggest that we rely on the logical definitions to get this if needed. It would strike any physician as strange to see a term called Hyperplasia at a very high level, and in clinical reality, things may be mixed or unknown.
