### ISSUE TITLE
abnormal hypoxanthine-guanine phosphoribosyltransferase level

### ISSUE THREAD

**Issue by slaulederkind** [obophenotype/human-phenotype-ontology#3308]
>If this is a request for a new term, please provide us with the folloing information (c.f., https://github.com/obophenotype/human-phenotype-ontology/wiki/How-to-make-a-good-term-request).

>1. Preferred term label (e.g., Asplenia)_
abnormal hypoxanthine-guanine phosphoribosyltransferase level
increased hypoxanthine-guanine phosphoribosyltransferase level
decreased hypoxanthine-guanine phosphoribosyltransferase level

>2. Synonyms (e.g., Absent spleen)

abnormal 6-hydroxypurine phosphoribosyltransferase level;abnormal 6-mercaptopurine phosphoribosyltransferase level;abnormal GMP pyrophosphorylase level;abnormal GPRT level;           abnormal HGPRT level;abnormal HGPRTase level;abnormal HPRT level;abnormal IMP pyrophosphorylase level;abnormal IMP-GMP pyrophosphorylase level;abnormal guanine phosphoribosyltransferase level;       abnormal guanosine 5'-phosphate pyrophosphorylase level;abnormal guanosine phosphoribosyltransferase level;abnormal guanylate pyrophosphorylase level;abnormal guanylic pyrophosphorylase level;abnormal inosinate pyrophosphorylase level;abnormal inosine 5'-phosphate pyrophosphorylase level;abnormal inosinic acid pyrophosphorylase level;abnormal inosinic pyrophosphorylase level;abnormal purine-6-thiol phosphoribosyltransferase level;abnormal transphosphoribosidase level

The equivalent "increased" and "decreased" synonyms could be used for the second two term requests.

>3. Textual definition (the definition should be understandable even for non-specialists. Include a PubMed ID to refer to any relevant article that provides additional information about the suggested term).

altered level of the enzyme that catalyzes conversion of hypoxanthine to inosine monophosphate and guanine to guanosine monophosphate via transfer of the 5-phosphoribosyl group from 5-phosphoribosyl 1-pyrophosphate

>4. Suggested parent term (Please look in the hierarchy of the HPO using the [HPO Browser](http://compbio.charite.de/hpoweb/showterm?id=HP:0000118) or other browsers such as [OLS](http://www.ebi.ac.uk/ols/ontologies/hp) and find the place in the HPO where the new term best fits)

Abnormal enzyme/coenzyme activity (HP:0012379)

>5. If you know of a disease that is characterized by this feature, please indicate it (e.g., by its Orphanet or OMIM id), and we will add the annotation to our database.

>6. If you would like a nanoattribution, please indicate your ORCID id or provide a label such as HPO:probinson (organization, first initial-last name)

RGD:sjwang

**Comment by pnrobinson** [comment]
Sorry for the delay, adding these terms as HP_0031821-2-3
