### ISSUE TITLE
Nummular pigmentation of the retina

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3310]
@psergouniotis
Is the following correct?

We have a term "Nummular pigmentation of the retina" that has no definition and that is not currently being used to annotate a disease.
The only thing I can find is Nummular Loss of the Pigment Epithelium (e.g., http://www.ajo.com/article/s0002-9394(04)01365-0/abstract)
see here for images
http://imagebank.asrs.org/file/11442/nummular-depigmented-or-atrophic-pigment-epithelium
The word nummular comes from the Latin word for coin.
So I would propose
1. Change the preferred label to "Nummular atrophy of retinal pigment epithelium"
2. Add def: Coin-like (nummular) loss of pigmentation of the retinal pigment epithelium leading to the appearance of one or more coin-like lighter areas in the retina upon fundoscopy.
3. Synonyms
Nummular depigmented retinal pigment epithelium

**Comment by psergouniotis** [comment]
I do not agree with the above.

"Nummular pigmentation of the retina" should be used to annotate OMIM*603208,  OMIM*604210 and OMIM*616432, OMIM*604485

It is not the same as the paper and image you sent (these describe depigmentation while the term describes pigmentation).  For an example see https://www.sciencedirect.com/science/article/pii/S0002929711002552#fig2 (B-3 in top row)

The source of pigmentation is the RPE so the primary term should perhaps be "Nummular pigmentation of the fundus" (with "Nummular pigmentation of the retina" being a synonym). 

Proposed definition: Clumped pigmentary changes of nummular appearance (ie thought to resemble the shape of a coin or multiple coins stuck together) at the level of the retinal pigment epithelium.

**Comment by psergouniotis** [comment]
@LCCarmody 
please consider implementing this (changing primary term, adding synonym & definition) & closing the issue. please let me know if you would like any additional information/clarification
