### ISSUE TITLE
logical definition of heart valve

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3312]
@cmungall @balhoff @drseb 

This definition does not capture the subclasses (e.g., aortic valve).
```
'has part' some 
    (functionality
     and ('inheres in' some 
        ('cardial valve'
         and ('part of' some heart)))
     and ('has modifier' some abnormal))
```
We should revise it, and possible we need to add a class 'heart valve' to uberon?

**Comment by balhoff** [comment]
Hi @pnrobinson I don't think I understand. I see that 'aortic valve' is a subclass (indirect) of 'cardial valve'. Also, every 'cardial valve' is part of some heart, so you could leave that off. But I think I am missing the question.

**Comment by pnrobinson** [comment]
I think I may have been sleepy when I posted this issue. Will close now sorry.
