### ISSUE TITLE
Logical definition for Abnormality of cells of the lymphoid lineage

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3313]
Our definition takes the precursor cell (the CL term is for lymphoid progenitor cell) rather than the mature cell category lymphocyte (https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000542)
Is there any reason for this or can I change it?
@cmungall @mellybelly @drseb 
```
'has part' some 
    (quality
     and ('inheres in part of' some 'lymphoid lineage restricted progenitor cell')
     and ('has modifier' some abnormal))
```

**Comment by cmungall** [comment]
for reference, this is the class

```
id: HP:0012140
name: Abnormality of cells of the lymphoid lineage
namespace: human_phenotype
def: "An anomaly of cells that originate from the lymphoid lineage restricted progenitor cell." [HPO:probinson]
```

whatever we do we should use consistent language in the class label, the text def and the label of the filler class. If the filler class label is weird then we push back e.g. to CL.

We can see already a big problem in the current language gap. The text def and label says cells that **originate** from the lymphoid lineage. The owldef says cells that are **progenitors**. i.e. we only get pro-T and pro-B cells. So clearly something is wrong. One of the points of the DP approach is to clearly analyze these differences, we are not leveraging this to the full!

We can also use the existing asserted hierarchy as a way to quantify the most accurate owl definition. The underlying assumption is that the asserted is-a hierarchy is asserted by experts and represents the underlying intent (which I think is the correct assumption here)!

We have an obscure test in owltools for that!

```
$ owltools --eval-equiv-axiom -h
--eval-equiv-axiom [-c CLASSLIST]          tests the classification power of an existing equivalence axiom on an owlclass. Attempts to recapitulate classification of all subclasses with and without axiom. measures jaccard similarity of superclass list before and after
```

I tried this with both:

## Test 1

 - [CL:0000838](http://purl.obolibrary.org/obo/CL_0000838) ! lymphoid lineage restricted progenitor cell

```
$ owltools  --use-catalog hp-edit.owl --reasoner elk --silence-elk --eval-equiv-axiom -c HP:0012140
EVAL: HP:0012140 'Abnormality of cells of the lymphoid lineage'
  testing power of: EquivalentClasses(HP:0012140 'Abnormality of cells of the lymphoid lineage' ObjectSomeValuesFrom(has_part 'has part' ObjectIntersectionOf(PATO:0000001 'quality' ObjectSomeValuesFrom(inheres_in_part_of 'inheres in part of' CL:0000838 'lymphoid lineage restricted progenitor cell') ObjectSomeValuesFrom(qualifier 'has modifier' PATO:0000460 'abnormal'))) )
 score withAxiom jaccard sim average=0.658111424394319  n=16
 score withoutAxiom jaccard sim average=0.6223971386800333  n=16
DIFF FOR: HP:0012140 'Abnormality of cells of the lymphoid lineage'
  withAxiom : HP:0000118 'Phenotypic abnormality'
  withAxiom : UPHENO:0001002 'abnormal phenotype'
  withAxiom : UPHENO:0001001 'Phenotype'
  withAxiom : HP:0000001 'All'
```

## Test 2

 - [CL:0000542](http://purl.obolibrary.org/obo/CL_0000542) `lymphocyte`

```
EVAL: HP:0012140 'Abnormality of lymphocytes'
  testing power of: EquivalentClasses(HP:0012140 'Abnormality of lymphocytes' ObjectSomeValuesFrom(has_part 'has part' ObjectIntersectionOf(BFO:0000019 'quality' ObjectSomeValuesFrom(inheres_in_part_of 'inheres in part of' CL:0000542 'lymphocyte') ObjectSomeValuesFrom(qualifier 'has modifier' PATO:0000460 'abnormal'))) )
 score withAxiom jaccard sim average=0.6838827872021652  n=22
 score withoutAxiom jaccard sim average=0.6391169469817795  n=22
DIFF FOR: HP:0012140 'Abnormality of lymphocytes'
  withAxiom : HP:0000118 'Phenotypic abnormality'
  withAxiom : HP:0002715 'Abnormality of the immune system'
  withAxiom : UPHENO:0001002 'abnormal phenotype'
  withAxiom : HP:0010987 'Abnormality of cellular immune system'
  withAxiom : UPHENO:0001001 'Phenotype'
  withAxiom : HP:0001871 'Abnormality of blood and blood-forming tissues'
  withAxiom : HP:0000001 'All'
  withAxiom : HP:0001881 'Abnormality of leukocytes'
  withAxiom : HP:0004332 'Abnormality of lymphocytes'
DIFF FOR: HP:0012176 'Abnormal natural killer morphology'
  withAxiom : HP:0012140 'Abnormality of lymphocytes'
DIFF FOR: HP:0001922 'Vacuolated lymphocytes'
  withAxiom : HP:0012140 'Abnormality of lymphocytes'
```

`lymphocyte` is more accurate according to current hierarchy. But it's actually penalized as it introduces new inferences not already asserted: specifically the class becomes a subclass of HP:0002715 'Abnormality of the immune system'

**Comment by cmungall** [comment]
wait a minute.. we already have HP:0004332 'Abnormality of lymphocytes'

it's not totally clear to me what the intent was in introducing HP:0012140... looks like you made this in 2012 peter?

The two asserted subclasses of HP:0012140 are Lymphocytosis and Lymphopenia

The asserted subclasses of HP:0004332 include Lymphocytosis and Lymphopenia but also include others about T cell count, B cell morphology etc

I think we just want to obsolete HP:0012140?

**Comment by pnrobinson** [comment]
This change was implemented -- closing this issue.
