### ISSUE TITLE
HPO terms that were not found

### ISSUE THREAD

**Issue by shaytzur** [obophenotype/human-phenotype-ontology#3317]
Dear HPO managers,

I got the following terms from physicians that submitted their cases to our platform.  I dont have further medical information that can describe them better. I thought it might be useful to update you for further evaluation and consideration: 

- Phosphohydroxylysinuria
- AMP deaminase deficiency
- Bacteremia
- Birbeck granule deficiency
- Chitotriosidase deficiency
- Congenital disorder of glycosylation
- Early sleep onset

Regards, shay
emedgene

**Comment by pnrobinson** [comment]
Some of these items are really diseases. For insance, the phenotypic feature associated with the first item is
elevated phosphohydroxylysine in the urine (related synonym Phosphohydroxylysinuria).
Thanks for the suggestions, we will add the terms.

**Comment by pnrobinson** [comment]
Phosphohydroxylysinuria: HP_0031870
Absent Birbeck granules in Langerhans cells:HP_0031872
Bacteremia--added previosly
AMP deaminase deficiency--this is a disease not a phenotype
Congenital disorder of glycosylation--this is a disease not a phenotype

**Comment by pnrobinson** [comment]
Added terms for early/late chronotype with related synonyms "early/late sleep onset".
