### ISSUE TITLE
definition of HP_0040218 (Reduced natural killer cell number) 

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#3334]
Current def: 

> Less than normal number of natural killer cells, a type of lymphocyte in the innate immune system that contains cytoplasmic granzymes, i.e., small granules with perforin and proteases that allow natural killer cells to form pores in the cell membrane of the target cell through which the granzymes and associated molecules can enter, inducing apoptosis

Comment by eheiden at crowdin:

The pore forming protein, perforin 1 (PRF1), along with granzymes (GZMs) are members of a family of serine proteases and they are the dominant constituents of the cytolytic granules. Granzymes themselves are not the granules containing perforin and proteases. See: Martínez-Lostao L, et al.How Do Cytotoxic Lymphocytes Kill Cancer Cells? Clin Cancer Res. 2015 Nov 15;21(22):5047-56

**Comment by pnrobinson** [comment]
Agree with adding this as a comment.

**Comment by drseb** [comment]
I think the comment was intended to improve the current definition!?

**Comment by pnrobinson** [comment]
This is defining part of what a NK cell is, but does not define Reduced natural killer cell number. Perhaps it would be best to put this as a comment higher up in the hierarchy, actually.

**Comment by pnrobinson** [comment]
Looking at the hierarchy, I think that our 'Abnormal natural killer cell morphology" has a good definition. There are many other attributes of NK cells other than PRF1, and I think this is simply too detailed to be good for the definition or comment.

**Comment by Charite-heidene** [comment]
Hi, The comment has to do with the statement that granzymes are granules (cytoplasmic granzymes, i.e., small granules with perforin and proteases), and not with the "Reduced natural killer cell number".
Granzymes are proteins, not granules. The definition would be correct if "i.e., small granules" is removed.

**Comment by pnrobinson** [comment]
I see, sorry that I misunderstood initially! We will correct this.

**Comment by pnrobinson** [comment]
Sorry for the delay--things have been insanely busy..
I have revised the definition to avoid the above mistake. I consulted https://www.ncbi.nlm.nih.gov/pubmed/23993353
New definition: Less than normal number of natural killer cells, a type of lymphocyte in the innate immune system with an ability to mediate cytotoxicity and produce cytokines after the ligation of a germline-encoded activation receptor.

**Comment by drseb** [comment]
@Charite-heidene can we close this issue?

**Comment by Charite-heidene** [comment]
…yes, you can!

Thanks.
EH

Dr. Esmeralda Heiden
Qualitätsmanagement – FBL Histologie
Charité - Universitätsmedizin Berlin
Experimentelle Neurologie
Charitéplatz 1
10117 Berlin

Tel: +49 30 450 527032
esmeralda.heiden@charite.de<mailto:esmeralda.heiden@charite.de>

Von: Sebastian Köhler <notifications@github.com>
Gesendet: Freitag, 13. Juli 2018 13:31
An: obophenotype/human-phenotype-ontology <human-phenotype-ontology@noreply.github.com>
Cc: Heiden, Esmeralda <Esmeralda.Heiden@charite.de>; Mention <mention@noreply.github.com>
Betreff: [ext] Re: [obophenotype/human-phenotype-ontology] definition of HP_0040218 (Reduced natural killer cell number) (#3334)


@Charite-heidene<https://github.com/Charite-heidene> can we close this issue?
