### ISSUE TITLE
question about term Chronic hepatitis due to cryptospridium infection [HP:0200124]

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#3340]
I am trying find a definition for this term: Chronic hepatitis due to cryptospridium infection [HP:0200124], but I am not finding anything about the crytosporidium infection causing chronic hepatitis, rather that they co-occur. See this article:
https://www-ncbi-nlm-nih-gov.liboff.ohsu.edu/pubmed/21992928

cc @pnrobinson

**Comment by pnrobinson** [comment]
Actually, Fig S1 shows that cryptosporidia were found in the liver of an affected person,
Some glands contained microorganisms on the luminal surface of the epithelial cells, which 
could be identifi
 ed as cryptosporidia by immunohistochemistry
https://www.ncbi.nlm.nih.gov/pubmed/23440042
(I was coauthor on this paper, our group in Berlin, especially PK, did the exome analysis!)
I will update the definition.
