### ISSUE TITLE
consider new classification for Chronic recurrent multifocal osteomyelitis [HP:0005901]

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#3342]
Chronic recurrent multifocal osteomyelitis [HP:0005901] is classified as a child of 'Osteomyelitis', but according to wikipedia (https://en.wikipedia.org/wiki/Chronic_recurrent_multifocal_osteomyelitis), it is not actually caused by infection but is likely an autoimmune disease. It has osteomyelitis in the name because of the similar symptoms to osteomyelitis, but I don't think it is a proper child.

cc @LCCarmody

**Comment by pnrobinson** [comment]
It seems that Chronic recurrent multifocal osteomyelitis is better conceptualized as a disease and we should make a MONDO term if needed. I will reannotate the disease terms @LOURGHI we should also do this with the Orphanet entry!
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5705736/

**Comment by nicolevasilevsky** [comment]
We have this class in MONDO already: MONDO_0009813

**Comment by pnrobinson** [comment]
This is the disease in OMIM: https://omim.org/entry/259680
@drseb, I think this term is simply a mistake and so we need to merge it. This is a heads up in case you have any annotations to it, but I would be surprised.

**Comment by pnrobinson** [comment]
The term is bein guse to annotate only one disease in our corpus,  OMIM:259680 -- a tautology

**Comment by pnrobinson** [comment]
merged
