### ISSUE TITLE
Clarification on Pre-B-cell acute lymphoblastic leukemia [HP:0004812]

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#3343]
Question: Is this the same a B-cell precursor acute lymphoblastic leukemia?  If so: suggested definition: Leukemias stemming from B cell precursors. PMID: 26301807

Also, suggest exact synonym BCP ALL.

**Comment by LCCarmody** [comment]
Also, I assume this is distinct from B cell acute lymphoblastic leukemia (B-ALL).  Shouldn't B-ALL also be a term since T-ALL is?

**Comment by pnrobinson** [comment]
yes but we should reference the NCIT.  Let's talk tomorrow!

**Comment by cmungall** [comment]
In theory anything we do with neoplasms should be brainlessly mirroring NCIT, see https://github.com/obophenotype/human-phenotype-ontology/pull/904 cc @balhoff

**Comment by nicolevasilevsky** [comment]
I added the def to 'lymphatic vessel neoplasm' and mirrored the def from NCIT and xref'd them.

**Comment by pnrobinson** [comment]
There are currently no diseases annotated to this term. I think this is synonymous with
B Acute Lymphoblastic Leukemia 
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI_Thesaurus&code=C8644&ns=ncit
I am going to change the preferred label, add a definition and an xref.
