### ISSUE TITLE
Question about Exaggerated cellular immune processes [HP:0005397]

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#3344]
We added this term Exaggerated cellular immune processes [HP:0005397], I think as an outcome of the immunology workshop.

Leigh made a note that this may be a synonym of delayed hypersensitivity. In this [article](https://www.myvmc.com/anatomy/allergy-and-the-immune-system/), it seems like they are describing an exaggerated cellular immune response as a type I hypersensitivity reaction.

However- my question is- these are biological processes and are already captured in GO. Is this 'exaggerated process' term appropriate for HPO?

cc @LCCarmody

**Comment by pnrobinson** [comment]
I do not think that "Exaggerated cellular immune processes" is a great HPO term as is. An HPO term should correspond to an observation of a phenotype (including tests) and not an inference as to the biological processes that are going wrong.
I do not think that delayed hypersensitivity is a good synonym (DH is a normal response to some stimuli and is not per se exaggerated). I will try to get more feedback.

**Comment by nicolevasilevsky** [comment]
I agree!

**Comment by pnrobinson** [comment]
WE are using the term to annotate only one disease
Sarcoidosis, Susceptibility To, 1 OMIM:181000
-- I have revised the annotations to that disease and will now obsolete/merge this term.
