### ISSUE TITLE
Duplicate term: severe viral infection/s

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#3346]
We have two almost identical terms:
HP_0005364 Severe viral infections (no def)
HP_0031691 Severe viral infection (def: An unusually severe viral infection.)

Do we need to have both of these terms?

**Comment by pnrobinson** [comment]
I think the plural form means a history of multiple severe viral infections. Even one severe viral infection can be a sign of a compromised immune system, and so the immunologists wanted a separate term for it. So I think we need two terms.
We probably want to unify the way we are naming a history of recurrent infections. Let's have a look in the literature, but perhaps it would be better moving forward to standardize on something like
History of recurrent XYZs
and
XYZ
where XYZ is a phrase like "Severe viral infection"
?

**Comment by nicolevasilevsky** [comment]
Oh right, 'severe viral infections' is classified under 'Recurrent viral infections'. Would you like to rename this class (and similar classes to) 'History of recurrent severe viral infections' or other suggestion is 'Recurrent severe viral infections'. (Some of the siblings are named in this way:
HP_0002743 Recurrent enteroviral infections
HP_0011371 Recurrent viral skin infections

Suggested text def for 'severe viral infections': Increased susceptibility to  viral infections, as manifested by recurrent episodes of viral infections.

**Comment by cmungall** [comment]
+1

@nicolevasilevsky can you encode this in a DP?

**Comment by nicolevasilevsky** [comment]
@cmungall do you want a pattern for just the text definition for 'recurrent X infections', or do we want to create a pattern for the logical definition too? It seems we don't currently have a standard pattern for 'recurrent X infections', the only class that has a logical def is:

**HP_0002718 Recurrent bacterial infections**
'has part' some 
('increased susceptibility toward' and (towards some 'defense response to bacterium') and ('has modifier' some abnormal))

I could create a DP like this. One question is do we want to use 'towards'? Or 'inheres in'?

**Comment by pnrobinson** [comment]
Note that having one "opportunistic" infection can be taken to be increased susceptibility, as can recurrent infections. We may want to introduce subproperties to distinguish between the two.

**Comment by nicolevasilevsky** [comment]
I came across an example of a logical definition that used has modifier recurrent:

HP_0001988 Recurrent hypoglycemia
'has part' some 
('decreased amount' and ('inheres in' some blood) and (towards some glucose) and ('has modifier' some recurrent) and ('has modifier' some abnormal) and ('has modifier' some pathological))

is this what you mean @pnrobinson ?

**Comment by pnrobinson** [comment]
I think that would be good!

**Comment by pnrobinson** [comment]
done revising annotations.

**Comment by pnrobinson** [comment]
merged
