### ISSUE TITLE
add logical def to Absence of bactericidal oxidative 'respiratory burst' in phagocytes [HP:0002723]?

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#3347]
I just added the text def to Absence of bactericidal oxidative 'respiratory burst' in phagocytes [HP:0002723]

@pnrobinson could you please review and make sure you think it's okay?

If yes, I think we could add the logical def:
'has part' some 
('lacking processual parts' and ('inheres in' some 
('respiratory burst after phagocytosis')) and ('has modifier' some abnormal))

We would need to MIREOT the GO term: GO:0045728

**Comment by pnrobinson** [comment]
This looks great to me!
Maybe we should remove the single quotation marks from the primary label of this term?

**Comment by nicolevasilevsky** [comment]
Yes, I thought the single quotation marks were weird too! I'll remove them.

@drseb - Another MIREOT request (please!) 
We need: GO:0045728

**Comment by pnrobinson** [comment]
I have added the logical definition and removed the single quotes. We are good.
