### ISSUE TITLE
add logical def to HP_0011993 Impaired neutrophil bactericidal activity?

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#3348]
should we add the logical def:
'has part' some 
('decreased rate' and ('inheres in' some 'neutrophil mediated killing of bacterium
') and ('has modifier' some abnormal))

If yes, we need to MIREOT GO:0070944

**Comment by pnrobinson** [comment]
looks good to me!

**Comment by pnrobinson** [comment]
@drseb Could we mireot this. Please tell me how to do this!

**Comment by drseb** [comment]
@pnrobinson this is explained in the readme.

**Comment by drseb** [comment]
@pnrobinson let me know if you need further information. I will now start mireoting several classes

**Comment by drseb** [comment]
mireoted go-term
