### ISSUE TITLE
question about HP_0006721 Acute lymphoblastic leukemia equiv class assertion

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#3349]
HP_0006721 Acute lymphoblastic leukemia is asserted to be equivalent to HP_0004848 Ph-positive acute lymphoblastic leukemia.

I wonder if this is a mistake, because Ph-positive acute lymphoblastic leukemia seems to be a subtype of Acute lymphoblastic leukemia, from what I can tell.

**Comment by pnrobinson** [comment]
Thanks for picking up that error Nicole!
We will be coordinating with NCIT, and the corresponding term is
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI_Thesaurus&version=17.12d&code=C36312&ns=ncit
I think we can make a term Ph-positive acute lymphoblastic leukemia as a subclass of acute lymphoblastic leukemia, linking to the NCIT terms

**Comment by nicolevasilevsky** [comment]
I fixed this in the ontology
