### ISSUE TITLE
design pattern for weakness

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3350]
The current strategy for defining muscle weakness is to create a definition like this:

'has part' some ('decreased strength' and ('inheres in' some 'extra-ocular muscle') and ('has modifier' some abnormal))

The problem with this is that reasoners infer that weakness is a morphological abnormality (because the definition is using the E/Q pattern with the entity being a muscle term in uberon and the quality being 'decreased strength' in PATO. Currently, GO terms to describe the function of all the various muscles are not available.

@drseb @cmungall 
* Solutions?
** can we place weakness under decreased functionality in PATO?
** Is there an appropriate GO term?

**Comment by cmungall** [comment]
I'm not sure I follow - can you post a screenshot of a Protege explanation? I'm not sure how you'd end up inferred it as a morphological abnormality

![image](https://user-images.githubusercontent.com/50745/35021592-6a3cd2d4-fae6-11e7-9abc-dd9158f5ec7e.png)

**Comment by pnrobinson** [comment]
This was my mistake apparently. Closing this issue.
