### ISSUE TITLE
Merge: Glioblastoma -> Glioblastoma multiforme

### ISSUE THREAD

**Issue by cmungall** [obophenotype/human-phenotype-ontology#3352]
I recommend shadowing NCIT for neoplasm classification. These should be merged (the 2nd is undefined, I assume this is just a mistake rather than a deliberate attempt to make two distinct terms

```
[Term]
id: HP:0012174
name: Glioblastoma multiforme
namespace: human_phenotype
def: "A tumor arising from glia in the central nervous system with macroscopic regions of necrosis and hemorrhage. Microscopically, glioblastoma multiforme is characterized by regions of pseudopalisading necrosis, pleomorphic nuclei and cells, and microvascular proliferation." [HPO:probinson, pmid:10841526]
xref: MSH:D005909
xref: SNOMEDCT_US:393563007
xref: SNOMEDCT_US:63634009
xref: UMLS:C1621958
is_a: HP:0009733  ! Glioma

[Term]
id: HP:0100843
name: Glioblastoma
namespace: human_phenotype
xref: MSH:D005909
xref: SNOMEDCT_US:63634009
xref: UMLS:C0017636
is_a: HP:0009592  ! Astrocytoma
```

You might also want to consider the NCIT def

_The most malignant astrocytic tumor (WHO grade IV).  It is composed of poorly differentiated neoplastic astrocytes and it is characterized by the presence of cellular polymorphism, nuclear atypia, brisk mitotic activity, vascular thrombosis, microvascular proliferation and necrosis. It typically affects adults and is preferentially located in the cerebral hemispheres. It may develop from diffuse astrocytoma WHO grade II or anaplastic astrocytoma (secondary glioblastoma, IDH-mutant), but more frequently, it manifests after a short clinical history de novo, without evidence of a less malignant precursor lesion (primary glioblastoma, IDH- wildtype). (Adapted from WHO)_ [NCIT:C3058]

This is the correct SNOMED ID to use: SCTID:393563007

As an aside: NCIT takes the somewhat unusual step of reserving the term "Astrocyte" for astrocytic tumors excluding GBM, and uses the more general term "astrocytic tumor" for the union of these.

**Comment by pnrobinson** [comment]
Agree, and we should reference NCIT C3058
