### ISSUE TITLE
Incorrectly formatted definition xref

### ISSUE THREAD

**Issue by cmungall** [obophenotype/human-phenotype-ontology#3353]
```
$ owltools hp.obo 
2018-01-15 09:57:58,696 WARN  (OBOFormatParser:1505) LINE: 136411 accepting bad xref with spaces:American College of Rheumatology  LINE:
def: "Symmetrical thickening, tightening and induration of the skin of the fingers and the skin proximal to the metacarpophalangeal or metatarsophalangeal joints. These changes can involve the entire limb, face, neck and trunk." [American College of Rheumatology, RGD:gthayman]
```

this is probably the cause of parse failure for ontolib

Let me check why the SPARQL checks aren't catchingthis

**Comment by pnrobinson** [comment]
This was not the reason for the format errors as it turns out. However, we should attempt to provide database_Cross_refs to PMIDs and not to organisations (it would be difficult to trace "American College of Rheumatology").
I have replaced the xref by PMID:7378088
