### ISSUE TITLE
Send travis notifications to a mail list rather than individuals

### ISSUE THREAD

**Issue by cmungall** [obophenotype/human-phenotype-ontology#3354]
The travis notifications are hardwired to a group of people. I recommend setting up a mail list on groups.io and sending to that. Makes it easier for people to selectively monitor

**Comment by drseb** [comment]
great idea

**Comment by drseb** [comment]
Maybe I am not seeing it, but how can I make the travis-user a member of the mailing list? Wouldn't that require kind of "acceptance-action" taken by their email-server? Do you understand what I mean? (I mean this user/email-verification-step)

**Comment by cmungall** [comment]
I'm hoping it's easy to do with groups.io, in which you can clear an email address such that it doesn't require moderation, yet keep strict controls on the group.

I set up a test one here, which is meant as a dumping ground for travis checks from *all* ontologies
https://groups.io/g/obo-ci-reports-all/

I'll try adding obo-ci-reports-all@groups.io to HPO  and see what happens..

**Comment by drseb** [comment]
made this work
