### ISSUE TITLE
Add a test to ensure the generated hp.obo file parses using ontolib

### ISSUE THREAD

**Issue by cmungall** [obophenotype/human-phenotype-ontology#3355]
ontolib uses it's own obo parser rather than the canonical OWLAPI parser. The set of valid documents is likely to differ between the two. We should therefore add tests to ensure that the released obo file is within the intersection of valid document types.

I assume this is simply a matter of building ontolib from maven and running a java jar command in the Makefile after creation of the hp.obo file

**Comment by pnrobinson** [comment]
This should work, ontolib is on maven central.

**Comment by pnrobinson** [comment]
This issue has gotten stale. There have not been any problems with parsing with the new phenol library for over a year, therefore, I am closing the issue.
