### ISSUE TITLE
Abnormal ventriculo-arterial connection synonym with Transposition of great arteries?

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#3356]
Abnormal ventriculo-arterial connection (HP:0011563) does not currently have a definition or synonyms associated.  During my research, I found that Abnormal ventriculo-arterial connection may be a synonym to Transposition of great arteries instead of Transposition of great arteries (HP:0001669) being a child of Abnormal ventriculo-arterial connection.
PMID: 12658191
http://bioportal.bioontology.org/ontologies/SNOMEDCT?p=classes&conceptid=204296002

Synonym suggestions: Transposition of the great arteries, abnormal ventriculoarterial connection, Transposition of great vessels, discordant ventriculoarterial connections

**Comment by pnrobinson** [comment]
There are different kinds of Abnormal ventriculo-arterial connection
https://www.ncbi.nlm.nih.gov/pubmed/7847949
I will ask Matt

**Comment by pnrobinson** [comment]
According to https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4014757/
The cardiac malformations with abnormal ventriculo-arterial connections in situs solitus and atrio-ventricular concordance include the TF throughout the different forms of DORV to TGA
This paper is also relevant
https://www.annalsthoracicsurgery.org/article/0003-4975(94)00839-Y/pdf

**Comment by pnrobinson** [comment]
I am adding this term with definition:
An abnormality of the circulatory connection between the ventricles and the pulmonary artery and aorta.
and comment
The cardiac malformations with abnormal ventriculo-arterial connections in situs solitus and atrio-ventricular concordance include the tetralogy of Fallot as well as different forms of double-outlet right ventricle and transposition of the great arteries.
