### ISSUE TITLE
Abnormal atrioventricular connection (HP:0011546) synonym with discordant atrioventricular connection (HP:0011553)

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#3357]
Abnormal atrioventricular connection (HP:0011546) has_exact_synonym with discordant atrioventricular connection (HP:0011553)

I believe these are exact synonyms even though discordant atrioventricular connection is a child of Abnormal atrioventricular connection currently.

Am I missing something?

**Comment by pnrobinson** [comment]
I think "discordant atrioventricular connection " is a particular kind of "Abnormal atrioventricular connection"
I have added a reference: https://www.ncbi.nlm.nih.gov/pubmed/23804932
