### ISSUE TITLE
Absent left- and right- sided atrioventricular connections-questions about synonyms

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#3359]
>1. Preferred term label (e.g., Asplenia)_
Absent left-sided atrioventricular connections HP:0011547
Absent right-sided atrioventricular connections HP:0011548
These terms already exist and are the preferred terms

>2. Synonyms (e.g., Absent spleen)
Suggested: left-sided/right-sided atrioventricular atresia as has_exact_synonym

Not sure if we should include 'mitral valve atresia' for left and tricuspid valve atresia for right as narrow_synonym.  There seems to be some confusion/controversy in the literature and several papers citing change of nomenclature.  I don't think this is an appropriate term, but it seems some older papers include this.  PMID: 7104116

>3. Textual definition (the definition should be understandable even for non-specialists. Include a PubMed ID to refer to any relevant article that provides additional information about the suggested term).
Suggested definition: A defect where there is no connection between the left atrium and left ventricle. PMID: 7104116

**Comment by pnrobinson** [comment]
I do not think these are synonyms. I am going to add this reference PMID:7104116
