### ISSUE TITLE
Short palm

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#3360]
It's noted on ontobee that:
Short palm has_exact_synonym: Short palm; Short hands; Hypoplastic hands
Short palm has related synonym:Short palms

I think that Short palm has_exact_synonym: Short palms
                  Short palm has related synonym: Short hands; Hypoplastic hands.
is more logical??

**Comment by nicolevasilevsky** [comment]
+1

**Comment by pnrobinson** [comment]
agree,. Please note there is a "plural form" synonym type we should be using; one day it will be useful for text mining!

**Comment by pnrobinson** [comment]
Thanks, I updated the synonym types!
