### ISSUE TITLE
Biventricular heart with straddling right sided atrioventricular valve and absent left sided atrioventricular connection HP:0011550-should be obsolete? 

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#3361]
"Biventricular heart with straddling right sided atrioventricular valve and absent left sided atrioventricular connection " (HP:0011550) and "Right sided atrium to left ventricle and absent left sided atrioventricular connection" (HP:0011551)  are two terms in the HPO as children of absent atrioventricular connections.

Should these two be terms in the HPO?  They are more descriptions than terms.  Also, the term 'Straddling atrioventricular valve' (HP:0011562) and 'left-sided atrioventricular connection' are already present. There possibly needs to be 'right-sided straddling atrioventricular valve' and 'left-sided atrioventricular valve' added as children to 'Straddling atrioventricular valve' (I will add a new github ticket for this), but might it make more sense to have these as individual terms instead of as combined terms?  Also, if I understand the nomenclature, aren't HP:0011550 and HP:0011551 the same thing?

**Comment by pnrobinson** [comment]
I think that it is difficult to find short words to describe phenotypes like this that are conceptualized as unified events in cardiology. Optimally we will be able to go through items such as this in a future workshop, but I think they are ok, as this term was a cardiologist request.
