### ISSUE TITLE
Wrong (?) 'replace_by' tag for HP:0040316 in hp.obo

### ISSUE THREAD

**Issue by rolfschr** [obophenotype/human-phenotype-ontology#3365]
As of 22.01.18, the file http://purl.obolibrary.org/obo/hp.obo contains the following content:

```
[Term]
id: HP:0040316
name: obsolete Aplasia of the penis
is_obsolete: true
replaced_by: HP_0030261
```

I believe the last line should have been ``replaced_by: HP:0030261``, i.e. using : instead of _ to denote the replacement term. This is similar to #667.

**Comment by pnrobinson** [comment]
Thanks for picking this up. @drseb, we should put this in the travis script. We will correct this in the next release.
