### ISSUE TITLE
Episodes of ventricular tachycardia (HP:0005141) and Paroxysmal ventricular tachycardia (HP:0004751) the same thing?

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#3366]
Just wanted to clarify: Episodes of ventricular tachycardia (HP:0005141) and Paroxysmal ventricular tachycardia (HP:0004751) are the same thing or two different phenomena?  In the literature, it appears they are the same thing, but there may be a subtle distinction I am missing.

**Comment by pnrobinson** [comment]
Let me take a look at the annotated diseases and see if there is any intended difference.

**Comment by pnrobinson** [comment]
I agree this is a synonym. I have merged the terms and added some definitions.
