### ISSUE TITLE
Synonym: Taussig-Bing Anomaly

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#3367]
Is Taussig-Bing anomaly an appropriate synonym for HP:0011658 Double outlet right ventricle with subpulmonary ventricular septal defect without pulmonary stenosis 

see:
https://www-sciencedirect-com.liboff.ohsu.edu/science/article/pii/S0003497599012473?via%3Dihub#BIB18 

This paper says:
The earliest classification of DORV by Neufeld and associates [16, 17] was based on three considerations: (1) the relationship of the VSD to the crista supraventricularis; (2) the relationship of the VSD to the great arteries; and (3) the presence or absence of pulmonary stenosis; and is as follows:
- Type I: VSD subcristal
  - Type IA: VSD subaortic ± pulmonary stenosis
  - Type IB: VSD remote from great arteries
- Type II: VSD supracristal
  - Type IIA: VSD subpulmonary (Taussig-Bing)
  - Type IIB: VSD subpulmonary and subaortic

Here is another ref about Taussig-Bing
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2801930/

**Comment by pnrobinson** [comment]
I agree and have added the synonym and the PMID
