### ISSUE TITLE
Suggesting new child term of "Allergy"

### ISSUE THREAD

**Issue by oleraj** [obophenotype/human-phenotype-ontology#3368]
Suggest creating new child term of Allergy [HP:0012393] 
New term label:
New term definition:
New term comment (if any):
New term synonyms(if any):
New term lay person synonyms (if any):
Reference (e.g., PubMed ID):
Your biocurator ID for nanoattribution (if desired):

**Comment by pnrobinson** [comment]
Thanks--we will be working on further allergy and immunology terms and will be in contact with Morgan about details.
