### ISSUE TITLE
NTR: metabolomics terms

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#3369]
JP has a list of metabolomics term requests for HPO, see the spreadsheet [here](https://docs.google.com/spreadsheets/d/1MtPIizS1KB46pX4vDvz8OqPW5FAQe4QnM1ENzjKM9DM/edit#gid=0).

These look pretty straightforward, I can start working on adding these.

cc @pnrobinson

**Comment by drseb** [comment]
It would be better not to "only" add to HPO, but let HPO and HPOA go hand in hand here. I.e. for each new term, add the mentioned HPOA from the spreadsheet.

**Comment by pnrobinson** [comment]
I completely agree with Seb, please also add to HPOA!!
As an aside, here is a new tool for doing HPO biocuration that might be helpful
https://github.com/TheJacksonLaboratory/HPOworkbench

**Comment by nicolevasilevsky** [comment]
Sounds good!

**Comment by nicolevasilevsky** [comment]
@pnrobinson and @drseb - to add the annotations, I should use the HPO Phenote tool that you showed me, Peter?

But if I just added a new term to the HPO, will it take a bit before it is available in the HPO Phenote?

**Comment by pnrobinson** [comment]
Hi Nicole,
if you add a term, it will not be available via the automatic download until the next HPO release. However, you can create a local version of the HPO and import it, and then you will see the new terms
http://hpo-workbench.readthedocs.io/en/latest/latest.html
@drseb I think we need to increase the pace of releases because we are doing lots of biocuration and will need to add the new terms to HPOA. Or is there another way?

**Comment by nicolevasilevsky** [comment]
@drseb would you mind MIREOTing these Chebi terms for me, and I will add logical definitions to all of these metabolomics terms:
CHEBI:16070
CHEBI:16831
CHEBI:15676
CHEBI:17113
CHEBI:16024
CHEBI:48300
CHEBI:16813
CHEBI:24148
CHEBI:18089
CHEBI:2181
CHEBI:16015
CHEBI:16997
CHEBI:15963
CHEBI:33942
CHEBI:17151

**Comment by nicolevasilevsky** [comment]
@pnrobinson I am done adding the new terms, but I still need to add the logical definitions.

I also need to add the annotations to the diseases. The [instructions ](http://hpo-workbench.readthedocs.io/en/latest/index.html) to get the latest version of hp.obo worked great, I was able to get the latest hpo.obo version without issue.

Where I am having issues though is with the workbench. Using the workbench, I can only suggest new annotations, not directly add new annotations, is that correct?

I can directly add new annotations via HPhenote, that you showed me around Christmas time, but that does not have the latest version of HPO. Is there a way to get the latest version of the HPO file in that tool, then I can directly add the annotations.

Thank you!

**Comment by pnrobinson** [comment]
Hi Nicole,
I am going to add a new feature to the workbench that shows disease annotations according to organ system. We should probably rethink the way we are managing annotations and github--either we put this on the main HPO tracker or we use more the annotation tracker. But the current feature can also be used to suggest a new annotation, just change the text in the dialog.

**Comment by nicolevasilevsky** [comment]
I just added a new ticket via the workbench. Might I suggest some clarifications to the instructions, because I wasn't able to properly follow the instructions the first time. My suggestions are in _italics._

**Viewing annotated diseases**
The diseases annotated to a given HPO term (including direct and implied annotations) can be viewed in the browser. If desired, users can limit the diseases to one of the databases, Orphanet, OMIM, or DECIPHER. To find the disease of interest, choose the radio button diseases _in the upper left_ and use the autocomplete field to find the disease, and click on the GO button.

**Suggesting new annotations**
First navigate to a disease of interest as above. Then, click on the New annotation radio button _in the upper left._ Then use the autocomplete field or the HPO ontology hierarchy on the left to find the term you would like to propose as a new annotation for the disease. Then, click on the Suggest new annotation button _on the bottom of the screen_ to open a new GitHub issue as above. Again, please modify the text to provide information to support the suggestion. _You will need your GitHub ID and password to submit a new issue._ Use the Report mistaken annotation if you have found an error in the annotations for some disease.

**Comment by nicolevasilevsky** [comment]
@pnrobinson - is this the workflow you'd like me to use, to create tickets for the new annotations that are needed?

**Comment by nicolevasilevsky** [comment]
(Apologies for all the questions...!) 
Some diseases are common diseases, like chronic renal failure. To clarify - I don't need to annotate these, yes?

**Comment by pnrobinson** [comment]
Hi Nicole
thanks!, Let us try to do some items like this. However, for uncontroversial new disease annotations, we could also use PhenoteFX directly. We can do the first N annotations together.
I am going to release a second version of HPO Workbench with a couple of improvements probably in the next few days. I will update the HowTo (which now appears in a new dialog window that shows the read the docs pages) according to your suggestions but I am probably going to revise everything since a few changes were made to the gui.

**Comment by nicolevasilevsky** [comment]
Ok, we have a call scheduled on Friday, we can review adding the annotations in PhenoteFX together then, or I'll ask Eileen if you have any time this week sooner than that.

Is PhenoteFX different than HPhenote?

**Comment by nicolevasilevsky** [comment]
@pnrobinson and @drseb I downloaded OWLTools per your instructions in the HPO workbench documentation. Does that mean I could MIREOT terms on my own now? If yes, could you provide me with some instructions of what code to run? (The instructions in the workbench were super helpful!)

**Comment by pnrobinson** [comment]
Hi @nicolevasilevsky I have expanded the entire documentation section, let me know if it works better!
I do not know how to MIREOT terms, I think Seb has been doing that the entire time.

**Comment by drseb** [comment]
@balhoff I regenerated go_import. But since I do not know how to use/setup robot I switched back to my owltools-pipeline. Let me know if go_import is also ok, when generated through this pipeline.

**Comment by drseb** [comment]
@nicolevasilevsky let me know if there are more requests that I have missed

**Comment by balhoff** [comment]
@drseb the only import targets I set up for robot so far are ZFA and RO—so you can probably run the GO import target. But I suspect your file is okay, I probably can't test anything until much later today.

**Comment by nicolevasilevsky** [comment]
@drseb for some reason, I only see some of the CHEBI terms in HP, many of them are still missing. These are missing:
CHEBI_16070
CHEBI_16831
CHEBI_17113
CHEBI_4208
CHEBI_48300
CHEBI_16534
CHEBI_18089
CHEBI_2181
CHEBI_16997

**Comment by drseb** [comment]
well... I was stupid. I re-generated go_import not chebi_import... sorry

**Comment by nicolevasilevsky** [comment]
No worries! At least it is an obvious fix. :)

**Comment by nicolevasilevsky** [comment]
@drseb would you be able to MIREOT the CHEBI terms? Thank you!

**Comment by drseb** [comment]
Let me know if all the classes are available now. Thanks.

**Comment by nicolevasilevsky** [comment]
@drseb yes, thank you! I added logical definitions to all of these terms.

Reminder, @pnrobinson, as we discussed on the phone today, you will will add the local import file with the current version of the ontology to PhenoteFX, and then I will update the disease annotations.

Thanks!

**Comment by nicolevasilevsky** [comment]
added new terms and created a new ticket in annotation repo
https://github.com/monarch-initiative/hpo-annotation-data/issues/174

**Comment by nicolevasilevsky** [comment]
closing - all the terms have been added. I created a new ticket in the HPOA tracker.
