### ISSUE TITLE
Is Restrictive heart failure (HP:0005130)= Diastolic heart failure

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#3370]
Not finding much on specifically 'restrictive heart failure', but is it Diastoclic heart failure? http://sydneycardiology.com.au/wp-content/uploads/2013/04/The-problem-of-heart-failure.pdf**

**Comment by pnrobinson** [comment]
Restrictive heart failure and diastolic often go together but are not the same thing. I will try to provide better text definitions after consulting my cardiology text book which is at home.

**Comment by LCCarmody** [comment]
You have a cardiology textbook? I would love to see it!  I was thinking of asking to buy a couple of these textbooks for the lab.  I think it would be helpful.  Maybe we could get one for the ophthalmology project?

**Comment by pnrobinson** [comment]
I think this should probably be merged with restrictive cardiomyopathy. Let us ask the cardiologists.

**Comment by pnrobinson** [comment]
After review, I do not think restrictive heart failure is the correct term. Restrictive cardiomyopathy can cause heart failure.

**Comment by pnrobinson** [comment]
The term is being used to annotate only one disease in our corpus: http://omim.org/entry/601419. I will reannotate and merge @drseb  -- this was a mistake and we need to merge, please see if any issues occur.

**Comment by pnrobinson** [comment]
merged
