### ISSUE TITLE
abnormality of lipoprotein particle size

### ISSUE THREAD

**Issue by slaulederkind** [obophenotype/human-phenotype-ontology#3371]
>If this is a request for a new term, please provide us with the folloing information (c.f., https://github.com/obophenotype/human-phenotype-ontology/wiki/How-to-make-a-good-term-request).

>1. Preferred term label (e.g., Asplenia)_

1. abnormality of lipoprotein particle size
2. increase in the size of low-density lipoprotein particles
3. decrease in the size of low-density lipoprotein particles

>2. Synonyms (e.g., Absent spleen)

2. increase in the size of LDL particles
3. decrease in the size of LDL particles

>3. Textual definition (the definition should be understandable even for non-specialists. Include a PubMed ID to refer to any relevant article that provides additional information about the suggested term).

1. An increase or decrease in the average size of a lipoprotein particle.  PMID:9973300
2. An increase in the average size of a low-density lipoprotein particle. 
3, A decrease in the average size of a low-density lipoprotein particle. PMID:9973300

>4. Suggested parent term (Please look in the hierarchy of the HPO using the [HPO Browser](http://compbio.charite.de/hpoweb/showterm?id=HP:0000118) or other browsers such as [OLS](http://www.ebi.ac.uk/ols/ontologies/hp) and find the place in the HPO where the new term best fits)

1. Abnormality of cholesterol metabolism (HP:0003107)
2. abnormality of lipoprotein particle size
3. abnormality of lipoprotein particle size

>5. If you know of a disease that is characterized by this feature, please indicate it (e.g., by its Orphanet or OMIM id), and we will add the annotation to our database.

3. coronary disease

>6. If you would like a nanoattribution, please indicate your ORCID id or provide a label such as HPO:probinson (organization, first initial-last name)

ORCID:0000-0001-5356-4174
--

**Comment by pnrobinson** [comment]
Sorry for the delay!
I have not been able to find any instance of medical relevance for abnormally increased LDL particle size and so for now I am just creating one term
HP_0032193
Decreased low-density lipoprotein particle size
def:An abnormal decrease in the average size of low-density lipoprotein particle size in the blood circulation. 
comment:Elevated levels of low-density lipoprotein (LDL) cholesterol are associated with an increased risk of developing coronary artery disease. LDL particles are the major cholesterol-carrying lipoproteins in the blood circulation, consisting of a hydrophobic core of cholesterol esters and triglycerides surrounded by phospholipds, free cholesterol, and one molecule of apolipoprotein B-100 on the surface of the molecule. The LDL particle population is heterogeneous with the respect to size, density and composition. Distinct subpopulations vary in isoelectric point, electrical charge, hydrodynamic properties and immunoreactivity.
