### ISSUE TITLE
New annotation suggestion for #246450 3-@HYDROXY-3-METHYLGLUTARYL-CoA LYASE DEFICIENCY

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#3372]
Suggest creating new annotation for disease #246450 3-@HYDROXY-3-METHYLGLUTARYL-CoA LYASE DEFICIENCY [OMIM:246450] 
New annotation: Increased level of 3-hydroxy-3-methylglutaric acid in urine [HP:0410051]
Reference (e.g., PubMed ID):
Your biocurator ID for nanoattribution (if desired): nvasilevsky
Anything else:

**Comment by pnrobinson** [comment]
Added annotation
