### ISSUE TITLE
Astrocytoma and Glioblastoma

### ISSUE THREAD

**Issue by cmungall** [obophenotype/human-phenotype-ontology#3374]
(accidentally sent to DO tracker first time https://github.com/DiseaseOntology/HumanDiseaseOntology/issues/466)

If we are to take NCIT as canonical for neoplasms then we must change

```
        is_a HP:0009733 ! Glioma
         is_a HP:0009592 ! Astrocytoma
          is_a HP:0100843 ! Glioblastoma *** 
```

See
https://github.com/NCI-Thesaurus/thesaurus-obo-edition/issues/23#issuecomment-361999516

Note from the linked ticket that HP does is in the same way as everyone except NCIT, who are more careful to separate these concepts. What is our policy here?

**Comment by pnrobinson** [comment]
HP:0100843 was obsoleted last year and the current structure of HPO matches (is a subset of) the NCIT structure.
