### ISSUE TITLE
need new subset tag for "top_level_grouping"

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#3375]
@jmcmurry asked if I could add a subet tag "top_level_grouping" to the terms in this list that are top level categories from the biolink closure bins: https://github.com/biolink/biolink-api/blob/master/biolink/api/bio/closure_bins.py

@pnrobinson could I just add this subset tag in the annotation property hierarchy as a child of subset_property, with the ID http://purl.obolibrary.org/obo/hp#top_level_grouping, and then tag all these terms?
(I've never done this before, but that seems like the workflow.)

**Comment by pnrobinson** [comment]
tbh I think this is something we need to think through. There is no canonical top-level grouping in the community, and there is even less agreement on second level groupings. I do not think we should be encoding our decisions for the website within the ontology. I think that we may also want to rearrange parts of the top levels of the HPO for more consistency--this is something we should discuss!

**Comment by nicolevasilevsky** [comment]
on huddle call - discussed having a OWL import file that is an application-specific file (like eagle-i-app.owl)
Want the file to be dynamic and not hard coded into the application(s)

Question of where to store the file: create a repo for Monarch application ontologies
under Monarch repo, BioLink repo, Phenotype Ontologies repo?

**Comment by pnrobinson** [comment]
I am closing this as I think we need to have different top-level terms for different use cases and I do not think that this should live in the ontology, since there really will not be a one-fits-all solution here. There is some example code in HPO Workbench that is an example.
