### ISSUE TITLE
glucose tolerance

### ISSUE THREAD

**Issue by slaulederkind** [obophenotype/human-phenotype-ontology#3377]
What is the difference between "Decreased glucose tolerance"  (HP:0040270) and "Glucose intolerance" (HP:0000833)?  It seems like the two terms should be merged.  If they can't be merged, the definitions should indicate why the two terms are different.

**Comment by pnrobinson** [comment]
Thanks for picking this up. I think that we need one term for Impaired GTT and another term for impaired fasting glucose. I will track down the current official definitions.

**Comment by pnrobinson** [comment]
According to this they are not synonyms:
https://www.ncbi.nlm.nih.gov/books/NBK499910/
Glucose intolerance (GI) can be defined as dysglycemia that comprises both prediabetes and diabetes. It includes the conditions of impaired fasting glucose (IFG) and impaired glucose tolerance (IGT) and diabetes mellitus (DM). 
-- I will update the hierarchy to reflect this and update the definitions.

**Comment by pnrobinson** [comment]
@drseb I would like to merge
Abnormal glucose tolerance
with 
Glucose intolerance

because they are actually synonymous according to the definition.
Will this cause problems?

**Comment by drseb** [comment]
what is the exact procedure to merge?

**Comment by pnrobinson** [comment]
The one procedure have always used -- 
To merge term A and B, take the id of A and set term B to 'term replaced by id of A'. Add the id and ay other relevant information from B to A (has_alternateId and has_exact_synonym etc). Set Term B to owl:deprecated true.

**Comment by drseb** [comment]
ok. perfect. thanks. (just wanted to make sure we are speaking about the same _merging_)

go ahead. these kind of merges are no problem at all. (the only problem are non-trivial obsoletions, where it is impossible to replace an existing annotation without information loss)
