### ISSUE TITLE
Correction to term Increased intraocular pressure

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3383]
Suggestion about term Increased intraocular pressure [HP:0007906]
Current definition: no definition available
Current comment: no comment available
Current synonym list: High eye pressure

My suggestion: Please add definition @psergouniotis

**Comment by nicolevasilevsky** [comment]
Should Increased intraocular pressure [HP:0007906] be a child of glaucoma? Can't you have increased pressure without having glaucoma?

Suggested text def for intraocular pressure [HP:0007906]:
An increase in the intraocular pressure, which is determined by the balance of aqueous humour inflow and outflow.
xref: PMID:15106943

Suggested synonyms:
Elevated intraocular pressure
IOP (abbreviation)

**Comment by pnrobinson** [comment]
@psergouniotis glaucoma is of course a disease and perhaps we should try to disentangle this better.

**Comment by psergouniotis** [comment]
Hi

> Should Increased intraocular pressure [HP:0007906] be a child of glaucoma? Can't you have increased pressure without having glaucoma?> 

Yes, very clearly increased intraocular pressure can be present without glaucoma. In fact it is only a risk factor for glaucoma.

Definition for "Increased intraocular pressure": intraocular pressure that is 2 standard deviations above the population mean (typically corresponding to >21 mmHg using a Goldmann applanation tonometer) 

Agree with possible synonyms: Elevated intraocular pressure, raised intraocular pressure, increased IOP, elevated IOP, raised IOP.  "High eye pressure" can be used as a lay synonym

Another possible synonym for "increased intraocular pressure" could be "ocular hypertension" although this is often used as a diagnosis ("ocular hypertension when used as a diagnosis describes an IOP >21mmHg in the presence of a healthy optic disc and normal visual field")
