### ISSUE TITLE
Correction to term Postexertional malaise

### ISSUE THREAD

**Issue by cgunter624** [obophenotype/human-phenotype-ontology#3385]
Suggestion about term Postexertional malaise [HP:0030973]
Current definition: A subjective feeling of tiredness characterized by a lack of energy and motivation and that is induced by exertion or exercise.
Current comment: no comment available
Current synonym list: Exercise-induced fatigue;Exercise-induced malaise;Postexertional fatigue

My suggestion: Add to comments: Symptoms can include dead, heavy feeling after starting to exercise, next-day soreness or fatigue after non-strenuous, everday activities, mentally tired after slight effort, and physically drained or sick after mild activity.

**Comment by pnrobinson** [comment]
thanks, I have added this to the comments
