### ISSUE TITLE
incorrect uberon class used in owldef of HP:0006488 ! Bowing of the arm

### ISSUE THREAD

**Issue by cmungall** [obophenotype/human-phenotype-ontology#3389]
owl def uses
'forelimb stylopod'[UBERON:0003822]

in fact the HP class groups bowing of stylopod and zeugopod

Should use: UBERON:0008962 ! forelimb bone

(I bet this mistakes goes back to when we used FMA for the anatomy, FMA has an odd idea of what 'arm' and 'leg' means)

**Comment by nicolevasilevsky** [comment]
fixed
