### ISSUE TITLE
bad owldef for abnormality of face

### ISSUE THREAD

**Issue by cmungall** [obophenotype/human-phenotype-ontology#3390]
http://purl.obolibrary.org/obo/HP_0000271

this has two owl defs. Maybe a merge gone bad? 1st obv wrong:

has part some (quality and (inheres in part of some orbital region) and (has modifier some abnormal))
has part some (quality and (inheres in part of some face) and (has modifier some abnormal))

**Comment by pnrobinson** [comment]
agree with deleting the first definition. I do not know where this came from.

**Comment by drseb** [comment]
seems to have happened between 2015 and 2016. strange.

**Comment by nicolevasilevsky** [comment]
should we just remove the first def? I can fix it, if yes.
