### ISSUE TITLE
rename children of HP_0003468 Abnormal vertebral morphology

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#3391]
These two terms are children of HP_0003468 'Abnormal vertebral morphology':
HP_0100569 Abnormal vertebral ossification
HP_0100861 Vertebral body sclerosis

Peter commented on #2539  that the actual phenotypes of these two terms is an abnormal morphology that is a result of an abnormal process, but since we do not observe the process itself, they should probably be morph terms.

Suggested new labels:
HP_0100569 _suggested label:_  Abnormally ossified vertebrae

HP_0100861 _suggested label:_ Sclerotic vertebral body 
_suggested logical def:_
'has part' some 
    ('decreased mass density'
     and ('inheres in' some  'bony vertebral centrum')
     and ('has modifier' some abnormal))

**Comment by pnrobinson** [comment]
Nicole, these are great suggestions!

**Comment by drseb** [comment]
This will lead to a gap in interoperability, if not changed in a coordinated fashion within HPO but also with external ontologies. I think this is a bad idea.

**Comment by pnrobinson** [comment]
@drseb could you expand on this -- do you mean that we will lose links to Gene Ontology? 
Maybe we can have a separate file that would include things like decreased mass density that inheres in bone "results from" abnormalities in GO processes (using appropriate rules).
In any case, I think that we could adjust the primary labels as suggested, is that OK?

**Comment by drseb** [comment]
The suggestion is in principle totally correct and has been made at least two years ago. The problem is, that all ossification phenotypes now use _GO-ossification_ and not _PATO-decreased mass density_ . So all the inferred equivalencies, which were based on these axioms will not be found anymore. This has really long-ranging consequences - think about the opposite-phenotype-pipeline for example.

**Comment by pnrobinson** [comment]
Thanks, I understand now.
What about this plan
1. Change the labels as suggested
2. Continue work on ontology design patterns
3. Refactor hp-edit.owl once dust has settled from (2)

**Comment by nicolevasilevsky** [comment]
I like this plan.

**Comment by pnrobinson** [comment]
@drseb Does this work for you?

**Comment by drseb** [comment]
Well, except for 3, as the real issue is still not resolved. But go ahead. I have some ideas to keep things working.

**Comment by pnrobinson** [comment]
I have changed the labels. I will not alter the definitions. Probably we need an in person workshop to go over all of this.
