### ISSUE TITLE
change label of HP_0001707 Abnormal right ventricle morphology

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#3392]
could we rename this to Abnormal morphology of the right ventricle, to make it consistent with the left ventricle label (HP_0001711 'Abnormal morphology of the left ventricle') and the design pattern for abnormal morphology

**Comment by pnrobinson** [comment]
I would do this vice versa since we have tried to use the pattern Abnormal X morphology!
