### ISSUE TITLE
"Abnormality of lacrimal sac morphology" vs "Abnormality of lacrimal sac"

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#3396]
Opening a new issue from closed ticket #2808.
@pnrobinson

Below is a comment from 
@psergouniotis
This term can confuse things a bit as although it is typically due to "abnormal morphology" it can sometimes be due to "abnormal physiology" (known functional obstruction).

One option would be to keep "Abnormality of lacrimal sac" (as per HPO browser) rather than replace it with "Abnormal lacrimal sac morphology".

A perhaps better option would be to define it as a morphological abnormality and add a term "Functional nasolacrimal system obstruction" as a subclass of "Nasolacrimal system physiology" (or sth like that).

What do you think?

This would be Peter's call (@pnrobinson), but we could add:
"Abnormal physiology of the nasolacrimal system"
--- "Abnormal lacrimal sac physiology" (child)
---"Nasolacrimal sac obstruction" (same term, but an additional position as child "Abnormal lacrimal sac physiology" so it appears in both places? Just a thought.

**Comment by pnrobinson** [comment]
@LCCarmody @psergouniotis
We will need to work a little on the structure of the terms. Right now, there is a term called lacrimation abnormality, and we can add terms underneath that.
It is not possible to have the same term being a functional and a morphological abnormality (this is a limitation of the system of logical definitions we are using). I would guess that the morphological abnormality (which should be thought of as a picture that is taken at one moment in time) is Nasolacrimal sac stenosis, and the physiological abnormality (which can be compared to a movie) is Nasolacrimal sac obstruction. Note that the actual phenotype one observes might be just "reduced lacrimation -- unless it is possible to observe the amount of tears coming out of the nasolacrimal sac.
@psergouniotis - please advise!

**Comment by pnrobinson** [comment]
@psergouniotis
also, shouldnt it be Nasolacrimal duct obstruction (not sac) ?

**Comment by psergouniotis** [comment]
the current HPO terms is "Nasolacrimal duct obstruction" (HP:0000579) which is correct. 

indeed we need to work on the structure of terms (e.g. #3408). I think it would be useful to have a chat at some point to understand a bit better how the physiological / morphological split is implemented in other subspecialties. 

the main thing that I struggle with is terms corresponding to common symptoms which could be associated with functional or strucural abnormalities.

back to our topic. I find it conseptually hard to have "Nasolacrimal duct obstruction" as a physiological abnormality and "Nasolacrimal duct stenosis" as a morphological one (as per example above). I would be more inclined to have them both as morphological but I need to give it a good think. 

any guidance would be greatly appreciated.

**Comment by pnrobinson** [comment]
@psergouniotis I would like to take another go at finishing these terms.
I would say that we actually observe "stenosis" as a morphological issue that has physiological abormalities as a consequence. The real point of functional abnormality terms is for things like lacrimation defects, which can have multiple anatomical correlates. So in this particular case, I think it is probably OK to have Nasolacrimal duct obstruction or stenosis as a morphological term. Sometimes we cannot be 100% purist....

**Comment by pnrobinson** [comment]
OK, then I think we can close this issue.
