### ISSUE TITLE
NTR: Bacteremia

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#3398]
@kingmanzhang noticed that this was not in the HPO.

My question is: should sepsis be a child?
>If this is a request for a new term, please provide us with the folloing information (c.f., https://github.com/obophenotype/human-phenotype-ontology/wiki/How-to-make-a-good-term-request).

>1. Preferred term label (e.g., Asplenia)_  Bacteremia

>2. Synonyms (e.g., Absent spleen) has_narrow_synonym Sepsis

>3. Textual definition (the definition should be understandable even for non-specialists. Include a PubMed ID to refer to any relevant article that provides additional information about the suggested term).
Presence of bacteria in the blood

>4. Suggested parent term (Please look in the hierarchy of the HPO using the [HPO Browser](http://compbio.charite.de/hpoweb/showterm?id=HP:0000118) or other browsers such as [OLS](http://www.ebi.ac.uk/ols/ontologies/hp) and find the place in the HPO where the new term best fits)

-Abnormality of the immune system physiology
  --Bacteremia
     ---Sepsis
        ----Neonatal sepsis

>5. If you know of a disease that is characterized by this feature, please indicate it (e.g., by its Orphanet or OMIM id), and we will add the annotation to our database.

>6. If you would like a nanoattribution, please indicate your ORCID id or provide a label such as HPO:probinson (organization, first initial-last name)

**Comment by pnrobinson** [comment]
I do not think bacteremia is an abnormality of immune system physiology.
For now I added "Bloodstream infectious agent" / "Bactermia" under Abnormal metabolism/homeostasis (which has as a synoynm Laboratory abnormality, which in retrospect may be the better name!)

HP_0031864
