### ISSUE TITLE
heart rate variability

### ISSUE THREAD

**Issue by slaulederkind** [obophenotype/human-phenotype-ontology#3402]
>If this is a request for a new term, please provide us with the folloing information (c.f., https://github.com/obophenotype/human-phenotype-ontology/wiki/How-to-make-a-good-term-request).

>1. Preferred term label (e.g., Asplenia)_

1. decreased heart rate variability
2. increased heart rate variability

>2. Synonyms (e.g., Absent spleen)

1. decreased respiratory sinus arrhythmia; reduced heart rate variability
2. increased respiratory sinus arrhythmia

>3. Textual definition (the definition should be understandable even for non-specialists. Include a PubMed ID to refer to any relevant article that provides additional information about the suggested term).

1. reduced variation of beat-to-beat intervals of the heart that occurs in conjunction with the respiratory cycle
2. increased variation of beat-to-beat intervals of the heart that occurs in conjunction with the respiratory cycle

>4. Suggested parent term (Please look in the hierarchy of the HPO using the [HPO Browser](http://compbio.charite.de/hpoweb/showterm?id=HP:0000118) or other browsers such as [OLS](http://www.ebi.ac.uk/ols/ontologies/hp) and find the place in the HPO where the new term best fits)

Abnormal electrophysiology of sinoatrial node origin (HP:0011702)

>5. If you know of a disease that is characterized by this feature, please indicate it (e.g., by its Orphanet or OMIM id), and we will add the annotation to our database.

>6. If you would like a nanoattribution, please indicate your ORCID id or provide a label such as HPO:probinson (organization, first initial-last name)

ORCID:0000-0001-5356-4174

**Comment by pnrobinson** [comment]
A think it is more appropriate to have a term, "Abnormal heart rate variability" as a child of Arrhythmia -- the etiologies are not limited to primary sinus.
