### ISSUE TITLE
increased waist to hip ratio

### ISSUE THREAD

**Issue by slaulederkind** [obophenotype/human-phenotype-ontology#3403]
>If this is a request for a new term, please provide us with the folloing information (c.f., https://github.com/obophenotype/human-phenotype-ontology/wiki/How-to-make-a-good-term-request).

>1. Preferred term label (e.g., Asplenia)_

increased waist to hip ratio

>2. Synonyms (e.g., Absent spleen)

increased waist-to-hip ratio; increased WHR; increased waist–hip ratio

>3. Textual definition (the definition should be understandable even for non-specialists. Include a PubMed ID to refer to any relevant article that provides additional information about the suggested term).

Increased waist-to-hip ratio (WHR) is a measurement above the average for the dimensionless ratio of the circumference of the waist to that of the hips. WHR is calculated as waist measurement divided by hip measurement ( W ÷ H ).

>4. Suggested parent term (Please look in the hierarchy of the HPO using the [HPO Browser](http://compbio.charite.de/hpoweb/showterm?id=HP:0000118) or other browsers such as [OLS](http://www.ebi.ac.uk/ols/ontologies/hp) and find the place in the HPO where the new term best fits)

Increased body weight (HP:0004324)

>5. If you know of a disease that is characterized by this feature, please indicate it (e.g., by its Orphanet or OMIM id), and we will add the annotation to our database.

Obesity, OMIM:601665 

>6. If you would like a nanoattribution, please indicate your ORCID id or provide a label such as HPO:probinson (organization, first initial-last name)

ORCID:0000-0001-5356-4174

**Comment by slaulederkind** [comment]
PMID:12872269

**Comment by pnrobinson** [comment]
Thanks, adding this term. I think a better parent is Abnormality of body weight/Abnormal WHR/ the high and low WHR terms.
