### ISSUE TITLE
Retinopathy of prematurity: Logical definition question

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#3404]
Hi All,
I am still new to learning how to write logical definitions and need some help.  I've asked @nicolevasilevsky and @pnrobinson, there wasn't a definitive answer.
I created a new logical definition for Retinopathy:
'has part' some 
    (damaged
     and ('inheres in' some retina)
     and ('has modifier' some abnormal))

My issue is with the term 'Retinopathy of prematurity' (and its children).  It is a form of retinopathies that happen in premature infants.

It is not a prematurity of the retinopathy, so I don't think it would be similar to 'Premature chromatid separation' : “'has part' some
    (premature
     and ('inheres in' some 'sister chromatid segregation')
     and ('has modifier' some abnormal)) “

Is there a way to say this?

@cmungall @balhoff  @cindyJax

**Comment by balhoff** [comment]
I didn't see any patterns related to age or onset in the Upheno repo or in the"MP/HP Logical Definitions Best Practices" doc. Are there any other terms which are restricted to occurrence in a life stage?

**Comment by pnrobinson** [comment]
?THe HPO would use the age of onset modifier for this. Actually lots of terms have these modifiers. We need to extend the ragne of diseases though!

-Peter


Peter Robinson

Professor and Donald A. Roux Chair, Genomics and Computational Biology

The Jackson Laboratory for Genomic Medicine

10 Discovery Drive

Farmington, CT 06032

860.837.2095 t | 860.990.3130 m

peter.robinson@jax.org<mailto:peter.robinson@jax.org>

www.jax.org

Robinson lab: https://robinsongroup.github.io/

New Book: Computational Exome and Genome Analysis<https://www.crcpress.com/Computational-Exome-and-Genome-Analysis/Robinson-Piro-Jager/p/book/9781498775984>

The Jackson Laboratory: Leading the search for tomorrow's cures

________________________________

**Comment by pnrobinson** [comment]
btw The HPO Onset classes are designed from the Oxford Genetics Handbook ranges which are pretty much standard, so I do not think we should change any of the definitions, we spent a lot of time with Helen getting these right.


Peter Robinson

Professor and Donald A. Roux Chair, Genomics and Computational Biology

The Jackson Laboratory for Genomic Medicine

10 Discovery Drive

Farmington, CT 06032

860.837.2095 t | 860.990.3130 m

peter.robinson@jax.org<mailto:peter.robinson@jax.org>

www.jax.org

Robinson lab: https://robinsongroup.github.io/

New Book: Computational Exome and Genome Analysis<https://www.crcpress.com/Computational-Exome-and-Genome-Analysis/Robinson-Piro-Jager/p/book/9781498775984>

The Jackson Laboratory: Leading the search for tomorrow's cures

________________________________

**Comment by mellybelly** [comment]
Not suggesting that we necessarily change HPO but I believe that HPO is still not fully aligned with stage ontology - we should create new classes if needed
for example, see #273, #511, #383
Since we are updating the annotations and going to be reviewing age of onset, seems like a good time to review and reconcile anything.

**Comment by nicolevasilevsky** [comment]
Should the logical definition for 'Retinopathy of prematurity' use one of the HPO onset terms in the logical definition? The text definition is: An avascular or abnormally vascularized retina that occurs in premature infants and can lead to blindness.

I don't think any of the onset terms would really fit though, as this seems to occur in premies, which is more specific than 'neonatal onset.' 

So should this term not have a logical definition?

**Comment by cmungall** [comment]
The first question for any logical def: is it both necessary and sufficient?

 1. Is any retinopathy that occurs in stage P an instance of RoP?
 2. Is every instance of RoP an instance of R that occurs during P?

If only 2 is true, make a subclass axiom.

If neither is always true, don't make any axiom.

Only if you know both are true then make the equivalence axiom.

**Comment by LCCarmody** [comment]
I believe #2 is true, but I am not sure if all retinopathies that occur in premies is RoP.  Maybe @psergouniotis can help?

**Comment by psergouniotis** [comment]
indeed 2 is true and a subclass axiom seems the best option for me.

**Comment by pnrobinson** [comment]
I am not sure that it is a good idea to make logical axioms for the RoP terms -- even if we could figure out a way to define it, we have a total of ca. 15 terms for various categories of RoP, and there is no way that we could make good definitions for all of this. The terms already are defined via the structure of the ontology itself using subclass axioms, so I think we are done.
