### ISSUE TITLE
Recurrent bronchitis/infections for Stickler syndrome

### ISSUE THREAD

**Issue by GARDInfoCenter** [obophenotype/human-phenotype-ontology#3405]
GARD received an email from an inquirer who would like to know the sources/articles that provide information about recurrent bronchitis/infection in Stickler syndrome. According to Orphadata, the finding/feature/symptom is present in 30-79% of people with Stickler syndrome. Could you please point us to the sources of information? 

Do you have this type of information in your database? We are frequently asked for the specific sources of information in which the findings were reported. 

Maria Della Rocca
GARD Information Center

ATTN: @nicolevasilevsky

**Comment by pnrobinson** [comment]
Here is a mention of recurrent bronchitis in the "Syndromes of the Head and Neck" book
https://books.google.com/books?id=mSUnOoCvQWAC&pg=PA354&lpg=PA354&dq=bronchitis+stickler+collagen&source=bl&ots=dsYmThgNhh&sig=9fN9Uf_IEy20qjdOzIYWoysNR70&hl=en&sa=X&ved=0ahUKEwjaiZqvm8HZAhUEcq0KHRnSAkAQ6AEIbTAE#v=onepage&q=bronchitis%20stickler%20collagen&f=false
We should either add this as an ISBN reference or (better) try to find a PMID that supports this.

**Comment by nicolevasilevsky** [comment]
I added this ISBN dbxref to HP_0002837 recurrent bronchitis.

Is recurrent bronchitis/infection a phenotype seen in Stickler syndrome? I don't see this annotation in the HPO annotation record or in the [Orphanet record](http://www.orpha.net/consor/cgi-bin/Disease_Search.php?lng=EN&data_id=824&Disease_Disease_Search_diseaseGroup=Stickler-syndrome&Disease_Disease_Search_diseaseType=Pat&Disease(s)/group%20of%20diseases=Stickler-syndrome&title=Stickler-syndrome&search=Disease_Search_Simple).

This [reference](https://books.google.com/books?id=8H9oAgAAQBAJ&pg=PA393&lpg=PA393&dq=bronchitis+and+Stickler+syndrome&source=bl&ots=lWSr_as-2n&sig=FMhc8Gw_YAbcH2Citj1eJrXI-dc&hl=en&sa=X&ved=0ahUKEwj4s-zeq87ZAhWhilQKHf6tD5MQ6AEIZTAG#v=onepage&q=bronchitis%20and%20Stickler%20syndrome&f=false) notes a related syndrome that has recurrent respiratory infections, but it is not Stickler Syndrome.

Maria (@GARDInfoCenter), could you share the link to the reference from Orphadata that you mentioned above?

Thank you!

**Comment by GARDInfoCenter** [comment]
Nicole (@nicolevasilevsky), if you look at http://compbio.charite.de/hpoweb/showterm?disease=ORPHA:828#disease=ORPHA:828 and open up the Excel spreadsheet for that record, you will see on line 72 "Recurrent respiratory infections"

Maria

**Comment by nicolevasilevsky** [comment]
@GARDInfoCenter you are right! I see it.
@pnrobinson and @drseb maybe we should revisit this annotation?

**Comment by pnrobinson** [comment]
@GARDInfoCenter  I have looked all throughout PubMed and cannot find any article that mentions "Recurrent respiratory infections", but I think it is correct because of the description in this book:
https://books.google.com/books?id=mSUnOoCvQWAC&pg=PA354&lpg=PA354&dq=bronchitis+stickler+collagen&source=bl&ots=dsYmThgNhh&sig=9fN9Uf_IEy20qjdOzIYWoysNR70&hl=en&sa=X&ved=0ahUKEwjaiZqvm8HZAhUEcq0KHRnSAkAQ6AEIbTAE#v=onepage&q=bronchitis%20stickler%20collagen&f=false
I am afraid that this is probably the best we can do at this time!
