### ISSUE TITLE
Gitelman syndrome - review of current HPO term "abdominal pain" and consider adding other symptoms

### ISSUE THREAD

**Issue by GARDInfoCenter** [obophenotype/human-phenotype-ontology#3407]
I am submitting the issue below on behalf on one of GARD's information specialists who was updating the Gitelman syndrome webpage on the GARD website. 

We kindly offer the following suggestions and medical reference and ask that the HPO table for Gitelman syndrome be reviewed. 

•	Currently the HPO table’s first term listed is for “abdominal pain.” Based upon our review of the literature, this is not a symptom Gitelman syndrome. 

•	Secondly, we ask for your particular attention towards the following terms which are common symptoms of Gitelman syndrome, but are not in the current HPO table
o	Nocturia  
o	Fatigue
o	Salt craving
o	Thirst, polydipsia
o	Dizziness
o	Palpitations
o	Hypotension
o	Polyuria

•	Lastly we wish to recommend the following consensus article. It includes a table of symptoms and their frequency: 

Blanchard A1, Bockenhauer D2, Bolignano D3, Calò LA4, Cosyns E5, Devuyst O6, Ellison DH7, Karet Frankl FE8, Knoers NV9, Konrad M10, Lin SH11, Vargas-Poussou R12. Gitelman syndrome: consensus and guidance from a Kidney Disease: Improving Global Outcomes (KDIGO) Controversies Conference. Kidney Int. 2017 Jan;91(1):24-33. 
Free Full-text http://www.kidney-international.theisn.org/article/S0085-2538(16)30602-0/fulltext

We thank-you for your attention to this matter.

Many thanks for the great work you do! 

Maria Della Rocca
Genetic and Rare Diseases Information Center (GARD)

ATTN: @nicolevasilevsky

**Comment by drseb** [comment]
Thanks. 

Can you comment on the issue, that https://www.omim.org/entry/263800 states the following?

> Clinical features include transient periods of muscle weakness and tetany, abdominal pains, and chondrocalcinosis (summary by Glaudemans et al., 2012).

**Comment by pnrobinson** [comment]
We should certainly include at least the features in tables 1 and 2 of the Blanchard paper
The features in OMIM are indeed reported in this article
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3283182/
so they should also be included.

**Comment by GARDInfoCenter** [comment]
Great. We appreciate your adding the information from the Blanchard paper. When do you think the changes will be pushed? We refresh the HPO data on the GARD pages on a monthly basis. Do you think it will be in effect in March or April?

**Comment by pnrobinson** [comment]
I have updated the annotations as described above. I was only able to add the frequency "Very rare" to the items named "rare" in the table -- the categories used in the article do not match the Orphanet categories we are using for general frequency categories.
