### ISSUE TITLE
Hierarchy of Abnormality of eyelid morphology vs. Abnormality of eyelid physiology

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#3408]
I moved this discussion from #2863 so it doesn't get lost.  Copied below is the discussion:

"Abnormal eyelid morphology" seems to have replaced "Abnormality of the eyelid" as the primary term for HP:0000492. This is inaccurate and quite a few of the children terms are functional rather than morphological abnormalities. Pleas consider to keep HP:0000492 as "Abnormality of the eyelid".

 @pnrobinson
  Contributor
pnrobinson commented 2 days ago
@psergouniotis we should move the physiology terms to the abn or eyelid physiology term then! The overall structure is that there is a top level Abnormality of X term (where X is eye in this case) and then everything goes to morphology or physiology.

 @psergouniotis
  
psergouniotis commented 2 days ago
thanks Peter. The issue with these terms is that they are ocular adnexa, not eye. So it would be perhaps reasonable to have "abnormality of the eyelid" or "abnormality of nasolacrimal system" etc as top level terms and then everything goes to morphology or physiology.

also, what do you usually do for symptoms which could be either due to a morphological or a physiological abnormality (e.g. epiphora or nyctalopia)?

 @pnrobinson
  Contributor
pnrobinson commented 2 days ago
I would say that epiphora is clearly a physiological finding, and if it is due to a morphological abnormality then both items should be coded separately (same for nyctalopia). This strategy helps to keep the ontology more streamlined.

 @psergouniotis
  
psergouniotis commented 2 days ago
thanks for the response. the issue is that in terms of hierarchy, there will be quite a few terms in which certain subclasses will be morphological abnormalities and certain subclasses physiological.

in any case, back to the initial issue, I think it would be quite parsimonious to have:

"Abnormality of the ocular adnexa" with the following subclasses:
Abnormality of the nasolacrimal system
Abnormality of the common tendinous ring
Abnormality of the conjunctiva
Abnormality of the eyelid
Abnormality of the extraocular muscles
Abnormality of the eyebrow
Then for each one of these there should be "Abnormal #### morphology" plus, where appropriate, "Abnormal #### physiology".

The current HPO workbench version (where Abnormality of the eyelid is a synonym of Abnormal eyelid morphology) is inaccurate

**Comment by psergouniotis** [comment]
Thanks for summarising these. 

I would proposed the following:

"Abnormality of the ocular adnexa" (to replace HP:0030669) to have the following subclasses:
  |  Abnormality of the nasolacrimal system
  |    |   Abnormal nasolacrimal system morphology
  |    |   Abnormal nasolacrimal system physiology
  |  Abnormality of the common tendinous ring
  |    |   Abnormal common tendinous ring morphology
  |    |   Abnormal common tendinous ring physiology
  |  Abnormality of the conjunctiva
  |    |   Abnormal conjuctival morphology
  |    |   Abnormal conjuctival physiology
  |  Abnormality of the eyelid
  |    |   Abnormal eyelid morphology
  |    |   Abnormal eyelid physiology
  |  Abnormality of the extraocular muscles
  |    |   Abnormal extraocular muscle morphology
  |    |   Abnormal extraocular muscle physiology
  |  Abnormality of the eyebrow
  |    |   Abnormal eyebrow morphology
  |    |   Abnormal eyebrow physiology

This is will ensure that we  have a logical structure and we can then go and work on whether a term should be under morphology or physiology.

**Comment by pnrobinson** [comment]
This sounds good but please note that we are moving towards only having Abnormality of X terms for very high level terms, e.g., eye, and now are making the split into morphology and physiology at a very high point up in the hierarchy.

**Comment by psergouniotis** [comment]
great. please consider implementing on HPO workbench (and closing issue) so that we could start looking at the lower levels.

**Comment by pnrobinson** [comment]
@psergouniotis  Note that we updated the release version of hp.obo today and so if you re-download hpo.obo and restart HPO Workbench, you should see the new version.

**Comment by LCCarmody** [comment]
![screen shot 2018-03-20 at 4 18 32 pm](https://user-images.githubusercontent.com/26067008/37680464-672953a6-2c5a-11e8-9b6d-2212d2a045f3.png)
This is the current hierarchy.  @pnrobinson Do you want a new subclass of 'Abnormality of the orbital region' called "Abnormal ocular adnexa physiology" and new physiology terms to be added there?

**Comment by psergouniotis** [comment]
I have updated my hpo.obo by still I cannot see the new version - please consider implementing the suggestion in my abobe comment so that I could start looking at the lower levels. many thanks

**Comment by pnrobinson** [comment]
I have rearranged a number of items into a more sensible structure that separates physiology and morphology better. I will close this issue now because so much has been revised. We can discuss and open new updated issues if needed.

**Comment by psergouniotis** [comment]
OK. many thanks
