### ISSUE TITLE
NTR:Abnormal biotinidase activity

### ISSUE THREAD

**Issue by jpgourdine** [obophenotype/human-phenotype-ontology#3409]
>If this is a request for a new term, please provide us with the following information (c.f., https://github.com/obophenotype/human-phenotype-ontology/wiki/How-to-make-a-good-term-request).

>1. Preferred term label (e.g., Asplenia)_

Abnormal biotinidase activity

>2. Synonyms (e.g., Absent spleen)

>3. Textual definition (the definition should be understandable even for non-specialists. Include a PubMed ID to refer to any relevant article that provides additional information about the suggested term).

An abnormality in biotinidase activity, an enzyme that releases biotin from biocytin, the product of biotin-dependent carboxylases degradation.

PMID: 29359854

>4. Suggested parent term (Please look in the hierarchy of the HPO using the [HPO Browser]

Abnormal enzyme/coenzyme activity (HP:0012379)

>5. If you know of a disease that is characterized by this feature, please indicate it (e.g., by its Orphanet or OMIM id), and we will add the annotation to our database.

OMIM:253260

>6. If you would like a nanoattribution, please indicate your ORCID id or provide a label such as HPO:probinson (organization, first initial-last name)
Hi @pnrobinson tell me if it is OK, thanks !

**Comment by nicolevasilevsky** [comment]
@jpgourdine you also need to request the term 'decreased biotinidase activity'. Can you please write up the structured new term request as you did above in a comment on this ticket?

**Comment by nicolevasilevsky** [comment]
@pnrobinson could you also add @jpgourdine to the HPO repo?

**Comment by nicolevasilevsky** [comment]
@pnrobinson if these term requests (this and #3410) look okay, I can work with JP to add these to HPO

**Comment by pnrobinson** [comment]
This term as well as #3410 look great (we should have abnormal as well as decreased/increased). I had previously added JP to the repo. thanks :-0

**Comment by nicolevasilevsky** [comment]
@drseb could you please MIREOT GO:0047708 biotinidase activity?
Thank you!

**Comment by nicolevasilevsky** [comment]
created pull request for disease annotation
https://github.com/monarch-initiative/hpo-annotation-data/pull/179

**Comment by pnrobinson** [comment]
closing this then!
