### ISSUE TITLE
CDKL5 deficiency disorder 

### ISSUE THREAD

**Issue by GARDInfoCenter** [obophenotype/human-phenotype-ontology#3414]
While updating the GARD CDKL5 deficiency disorder, we reviewed the HPO table on our site and would like to propose that "cortical visual impairment” (HP:0100704) be added to CDKL5 deficiency disorder. 
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5458338/#ddx119-B13

When we pull up the phenotype "Impaired social interaction" in the HPO browser, we see EPILEPTIC ENCEPHALOPATHY, EARLY INFANTILE, 2 listed as 1 of the 54 associated diseases (http://compbio.charite.de/hpoweb/showterm?id=HP:0000735#id=HP_0000735); however, if you go to the disease page for EPILEPTIC ENCEPHALOPATHY, EARLY INFANTILE, 2 (http://compbio.charite.de/hpoweb/showterm?disease=OMIM:300672#disease=OMIM:300672), "Impaired social interaction" is not 1 of he 29 associated HPO classes. Why is that? 

Which file should we be using to import data into our database? 
http://compbio.charite.de/hudson/job/hpo.annotations/lastSuccessfulBuild/artifact/misc/phenotype_annotation.tab
http://compbio.charite.de/jenkins/job/hpo.annotations/lastStableBuild/artifact/misc/phenotype_annotation.tab

We currently use the first file (.../hudson/....lastSuccessfulBuild/...).

Maria Della Rocca
GARD

**Comment by drseb** [comment]
It is annotated to "HP:0000817 - Poor eye contact", which is a subclass of "Impaired social interaction"

**Comment by pnrobinson** [comment]
What about cortical visual impairment though?

**Comment by drseb** [comment]
@pnrobinson what do you mean?

**Comment by pnrobinson** [comment]
I might be misunderstanding but I thought the OP suggested a new annotation for  "cortical visual impairment”  -- the reference supplied is for a mouse model, and I think we should look and see if there is evidence for this in humans and then update our annotations if we can find something.

**Comment by drseb** [comment]
Ah ok. There were two questions and I answered only one. Ticket is open, please add annotation and close afterwards if you think the annotation is appropriate.

**Comment by nicolevasilevsky** [comment]
didn't mean to close this! reopened

**Comment by pnrobinson** [comment]
adding the cortical visual impairment annotation.
