### ISSUE TITLE
Some inconsistencies in lay person annotations

### ISSUE THREAD

**Issue by kshefchek** [obophenotype/human-phenotype-ontology#3419]
The majority of lay person annotations use the IRI:
http://purl.obolibrary.org/obo/hp.owl#layperson

However, I have found at least one case where this annotation doesn't exist but rather uses the string "layperson synonym" or "layperson term":

    <oboInOwl:hasSynonymType rdf:datatype="http://www.w3.org/2001/XMLSchema#string">layperson synonym</oboInOwl:hasSynonymType>

and 

    <oboInOwl:hasSynonymType rdf:datatype="http://www.w3.org/2001/XMLSchema#string">layperson term</oboInOwl:hasSynonymType>

This is for the term:
HP:0003326 ! Myalgia

**Comment by kshefchek** [comment]
that was fast - thanks!

**Comment by drseb** [comment]
thanks @kshefchek 

@pnrobinson I added a "hacky" test to https://github.com/Phenomics/hpo-owl-qc

this caught multiple related errors.
