### ISSUE TITLE
Lay Person Synonyms for HPO Terms

### ISSUE THREAD

**Issue by GARDInfoCenter** [obophenotype/human-phenotype-ontology#3420]
We would like for you to consider the following terms as possible Exact Layperson terms.

**HPO Class	HPO ID	Proposed Exact Layperson Synonym**
Chronic fatigue (HP:0012432) - Chronic extreme exhaustion 
Slender build	(HP:0001533) - Thin build
Spontaneous pneumothorax	(HP:0002108) - Spontaneous collapsed lung
Arthralgia/arthritis	(HP:0005059) - Joint pain/Joint inflammation
Lens luxation (HP:0012019) -	Dislocated lens 
Scoliosis	(HP:0002650) - Abnormal curving of the spine
Dolichocephaly (HP:0000268) - Long, narrow head
Hemoptysis (HP:0002105) - Coughing up blood
Muscular hypotonia	 (HP:0001252) - Low or weak muscle tone

Maria Della Rocca 
GARD

@nicolevasilevsky

**Comment by nicolevasilevsky** [comment]
@pnrobinson I can add these if they look okay to you.

**Comment by pnrobinson** [comment]
Please do -- these are great suggestions!

**Comment by nicolevasilevsky** [comment]
@GARDInfoCenter Maria, do you have an ORCID? (If not, do you want to sign up for one) - I can give you nano-attribution for these synonyms in the HPO.

**Comment by GARDInfoCenter** [comment]
Nicole, my ORCID is https://orcid.org/0000-0002-6548-5200 
Thanks

**Comment by LCCarmody** [comment]
Added nanoattribution to all of the laypersons terms.  I am getting an error in Travis though because both  Ectopia lentis (HP:0001083) and  Lens luxation (HP:0012019) has the synonym "Dislocated lens".  Which should have the synonym?

**Comment by nicolevasilevsky** [comment]
I think it should be a synonym for Lens luxation (HP:0012019), as that is a complete dislocation. Ectopia lentis is more general and could include complete or partial displacement.

**Comment by pnrobinson** [comment]
I agree.

**Comment by nicolevasilevsky** [comment]
I'll fix
