### ISSUE TITLE
Loinc 883-9:  "ABO group [Type] in Blood"

### ISSUE THREAD

**Issue by kingmanzhang** [obophenotype/human-phenotype-ontology#3422]
Suggest creating a new term for Loinc: 883-9 [ABO group [Type] in Blood] 
New term label: ABO blood type
New term comment (if any): (TEST) Some loinc tests are not for "abnormal" phenotypes. Does HPO consider such terms?
Your biocurator ID for loinc2hpo (if desired): null

**Comment by pnrobinson** [comment]
@cmungall @mellybelly @drseb 
Should we introduce a branch of HPO to capture some medically important non-abnormal phenotypes such as blood group?

**Comment by drseb** [comment]
Searching bioportal for blood group makes me think this is a good idea. But maybe @cmungall @mellybelly know more

**Comment by pnrobinson** [comment]
@drseb @cmungall @mellybelly 
-- OK so I will introduce a new subontology for blood group. This will be useful for the common disease project and would mean we could provide this information with Exomiser etc. Shout if anybody disagrees!

**Comment by pnrobinson** [comment]
@kingmanzhang can we discuss how LOINC represents this? I think that the proper phenotype is presence of an antigen (anti-A, anti-B). It will be difficult to represent the blood group O in this fashion though, and so for the ABO system maybe we also want to record the inference of A, B, AB, and O.
For all of the other systems, I think it is the presence of antigen that is recorded.

**Comment by kingmanzhang** [comment]
Sure. Yes, AB and O are tricky. The current annotation format does not allow logical operations. So for AB, we have to create a term like presence of BOTH anti-A and anti-B; for O, it needs negation of Presence of anti-A AND negation of Presence of anti-B. This becomes pretty complicated. Maybe an easier solution is just create individual terms for each?

**Comment by cmungall** [comment]
Yes, precompose and provide OWL definitons

**Comment by kingmanzhang** [comment]
I agree with your point. That does make a lot of sense if there are separate LOINC tests for anti-A and anti-B. But I do not think LOINC reports such granular findings:

https://r.details.loinc.org/LOINC/883-9.html?sections=Comprehensive

It appears that internally the antigens findings are selected but then an outcome is inferred (Type A, Type B, Type AB or Type O) and reported.

**Comment by pnrobinson** [comment]
created terms under HP_0032224 @kingmanzhang

**Comment by callahantiff** [comment]
Sorry, I know this is closed as well. While LOINC does not report separate blood types, there are several SNOMED CT diagnosis terms related to different blood types. Would you consider discussing this further? Happy to open a new issue if you prefer.

**Comment by pnrobinson** [comment]
@callahantiff Let's make this a new issue. We are planning on adding more blood type terms that should then be conneced to LOINC terms...

**Comment by callahantiff** [comment]
OK, great! I will make an issue and start by compiling examples from the data I have.
