### ISSUE TITLE
airborne particle hypersensitivity

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3429]
New term request: airborne particle hypersensitivity

**Comment by pnrobinson** [comment]
Particles can be defined as any small bits of material or droplets either inorganic or organic, viable or nonviable, that can become airborne. They can range from small molecules less than 0.001 micrometer to pollens and spores ranging between 2 and 50 μm and very large visible dust particles in the range of 1000 micrometer. Particles can also assume many shapes including long, fibrous varieties with a length greater than three times diameter, spheres, oddly shaped or irregularly shaped material, oblong, crescent-shaped varieties, or other peculiar shapes, such as certain pollen grains and mold spores.   PMID:8077583

**Comment by pnrobinson** [comment]
@jdmilner  I am struggling to find a good definition of PubMed citation for this. Does the proposed term refer to a phenotype that is observed via some kind of aerosol challenge? If not, how would one measure this phenotype?

**Comment by jdmilner** [comment]
Hi—Aerosol challenge is a gold standard of establishment of the symptom. Usually it is a history that is used to best establish it in the medical record. It usually takes into account seasonality, and lack of comorbid symptoms consistent with infection, etc.
We need to split a little here—particle hypersensitivity (diesel exhaust, metals, inorganic material) vs. allergen (including pollen dander, etc) hypersensitivity. The responses are usually different and testing for allergen hypersensitivity is done in concert with serum IgE and or skin testing to the suspected allergen.
This is interesting
https://www.ncbi.nlm.nih.gov/pubmed/30408667
