### ISSUE TITLE
food induced anaphylaxis

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3436]
New term request: food induced anaphylaxis 
Synonym:   
c.f. 2016 revision to the WHO classification of myeloid neoplasms and acute leukemia Arber D et al Blood 2016;127:(20):2391-2405
Diagnostic Criteria and Classification of Mastocytosis in 2014 Akin C and Valent P Immunol Allergy Clin N Am 34:207-218
Mast Cells, Mastocytosis and Related Disorders Theoharides T et al 2015 N Engl J Med 373;2
Definitions, Criteria and Global Classification of Mast Cell Disorders with Special Reference to Mast Cell Activation Syndromes: A Consensus Proposal Valent P et al 2012 Int Arch Allergy Immunol 157:215-225 
parent: anaphylaxis

**Comment by pnrobinson** [comment]
Note that we now have triggered by terms that could be added to our current anaphylaxis term. It may be difficult for the immunologists to use the modifier terms given we do not even have software ourselves that can do it at this time. In any case I think the terms with analphylaxis are OK, but we should use logical definitions that include our triggered by terms.

**Comment by LCCarmody** [comment]
Added NT but did not add logical term.

**Comment by pnrobinson** [comment]
term was added
