### ISSUE TITLE
allergic asthma

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3443]
New term request: allergic asthma

**Comment by pnrobinson** [comment]
This should be a MONDO term.
@cmungall @mellybelly We should try to schedule a call with the immunologists and discuss whether they would like to use MONDO plus HPO for their projects. There are a lot of terms in the recent list (see open immunology issues) that will require new disease terms.

**Comment by nicolevasilevsky** [comment]
this is in MONDO: MONDO_0004784

**Comment by pnrobinson** [comment]
Closing this as it is not a good HPO term
