### ISSUE TITLE
eosinophilic esophagitis

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3444]
New term request: eosinophilic esophagitis 
Synonym:   
c.f. 2016 revision to the WHO classification of myeloid neoplasms and acute leukemia Arber D et al Blood 2016;127:(20):2391-2405
Diagnostic Criteria and Classification of Mastocytosis in 2014 Akin C and Valent P Immunol Allergy Clin N Am 34:207-218
Mast Cells, Mastocytosis and Related Disorders Theoharides T et al 2015 N Engl J Med 373;2
Definitions, Criteria and Global Classification of Mast Cell Disorders with Special Reference to Mast Cell Activation Syndromes: A Consensus Proposal Valent P et al 2012 Int Arch Allergy Immunol 157:215-225 
parent: eosinaphilic gastrointestinal disease

**Comment by pnrobinson** [comment]
The issues with this term request are like those with eosinophilic gastritis, see #3447 .
* Eosinophilic esophagitis should be a MONDO term. See https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4848242/ for definitions
* The phenotypic feature of this disease that we want to capture in the HPO is this: presence of ≥ 15 eosinophils/high power field in at least 1 esophageal biopsy with few exceptions;
* In more detail: infiltration of numerous eosinophils (usually > 15 per high power field) into the squamous epithelium, layering of eosinophils on the surface layer and eosinophilic microabscess formation (clusters of ≥ 4 eosinophils). Often necrotic squamous cells are also seen on the surface layer
* Let us create HPO terms for
** Eosinophilic infiltration of the esophagus (definitions based on the above)
** Eosinophilic microabscess formation in the esophagus
** Please add UK synonyms with Oesophagus

**Comment by nicolevasilevsky** [comment]
Eosinophilic esophagitis  is already in MONDO: MONDO_0005361

**Comment by nicolevasilevsky** [comment]
do you think the parent term for these terms should be: HP_0100633 Esophagitis?

Suggested new terms/defs (based on what you wrote above. If these look okay, I can add them):
**Label:** Eosinophilic infiltration of the esophagus 
**def:** Infiltration of numerous eosinophils (usually > 15 per high power field) into the squamous epithelium of the esophagus, and layering of eosinophils on the surface layer of the esophagus.
**xref:** PMID:27158535 
**synonym:** Eosinophilic infiltration of the oesophagus

**Label:**  Eosinophilic microabscess formation in the esophagus
**def:** The formation of small localized collection of eosinophiles (an eosinophilic microabscess) in the esophagus. Usually clusters of ≥ 4 eosinophils are seen, that appear as exudates or white spots or white plaques.
**xref:** PMID:27158535 
**synonym:** Eosinophilic microabscess formation in the oesophagus
**synonym:** Eosinophilic micro-abscess formation in the esophagus

**Comment by pnrobinson** [comment]
re:  parent term => yes!

**Comment by pnrobinson** [comment]
looks good, I am closing this item.
