### ISSUE TITLE
eosinaphilic gastrointestinal disease

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3446]
New term request: eosinaphilic gastrointestinal disease

**Comment by pnrobinson** [comment]
This should probably be a grouping term in MONDO. Let us speak with the immunologists before making an HPO or MONDO term though.

**Comment by pnrobinson** [comment]
Closing this as it is not a good HPO term

**Comment by nicolevasilevsky** [comment]
should we add this as a synonym in MONDO?
We currently have MONDO_0016129 'eosinophilic gastroenteritis'

**Comment by cmungall** [comment]
can you make a ticket for this in the mondo tracker Nicole? Disease term needs reviewed there are oddities

**Comment by cmungall** [comment]
Also this may be closer: [MONDO:0018438](http://purl.obolibrary.org/obo/MONDO_0018438) ! primary eosinophilic gastrointestinal disease
