### ISSUE TITLE
eosinaphilic gastritis

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3447]
New term request: eosinaphilic gastritis 
Synonym:   
c.f. 2016 revision to the WHO classification of myeloid neoplasms and acute leukemia Arber D et al Blood 2016;127:(20):2391-2405
Diagnostic Criteria and Classification of Mastocytosis in 2014 Akin C and Valent P Immunol Allergy Clin N Am 34:207-218
Mast Cells, Mastocytosis and Related Disorders Theoharides T et al 2015 N Engl J Med 373;2
Definitions, Criteria and Global Classification of Mast Cell Disorders with Special Reference to Mast Cell Activation Syndromes: A Consensus Proposal Valent P et al 2012 Int Arch Allergy Immunol 157:215-225 
parent: eosinaphilic gastrointestinal disease

**Comment by pnrobinson** [comment]
Note spelling is eosinOphilic.
I think that this is an example where the item can be conceived of as a disease whose major feature is the phenotype of the same name. See eosinophilic ascites for a similar term (HP_0031780). 
* We should make a MONDO term (see https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3728613/ for definitions)
* The key phenotypic finding is the presence of eosinophils in the inflammed stomach wall, see e.e.g "The diagnosis is usually confirmed by an upper endoscopy and microscopy that shows more than 20 eosinophils per high-power field in the association with peripheral eosinophilia and the absence of secondary cause of eosinophilia. "
* I think that to distinguish the phenotype from the disease we should call the HPO term 
 "Eosinophilic infiltration in the stomach mucosa". I think that the parent term can be Gastritis.

**Comment by nicolevasilevsky** [comment]
I will add this term with these annotations:
**Parent class:** Gastritis
**New term label:** Eosinophilic infiltration in the stomach mucosa
**Syn:** Eosinophilic gastritis
**Def:** Infiltration of eosinophils in the stomach mucosa, that is diagnosed by an upper endoscopy and microscopy that shows more than 20 eosinophils per high-power field in association with peripheral eosinophilia and the absence of secondary cause of eosinophilia.
**Ref:** PMID:23904840

**Comment by nicolevasilevsky** [comment]
Note, this term is already in MONDO: MONDO_0016129

**Comment by pnrobinson** [comment]
1+
