### ISSUE TITLE
allergic proctocolitis

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3449]
New term request: allergic proctocolitis 
Synonym: milk protein proctocololitis

**Comment by pnrobinson** [comment]
This is a disease entity, see e.g., https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5004981/
Possibly the best label is  Food protein-induced allergic proctocolitis
It should be a term in MONDO
Let us hold off on creating an HPO term until we have spoken with the immunologists

**Comment by nicolevasilevsky** [comment]
@pnrobinson and @cmungall should we make new term requests for these terms in MONDO, if they do not already exist?

**Comment by cmungall** [comment]
yes. And you have an ID range so you can go ahead and add them!

**Comment by nicolevasilevsky** [comment]
Ok, cool! :)

**Comment by pnrobinson** [comment]
Closing this as it is not a good HPO term
