### ISSUE TITLE
idiopathic urtcaria

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3456]
New term request: idiopathic urtcaria 
Synonym:   
c.f. 2016 revision to the WHO classification of myeloid neoplasms and acute leukemia Arber D et al Blood 2016;127:(20):2391-2405
Diagnostic Criteria and Classification of Mastocytosis in 2014 Akin C and Valent P Immunol Allergy Clin N Am 34:207-218
Mast Cells, Mastocytosis and Related Disorders Theoharides T et al 2015 N Engl J Med 373;2
Definitions, Criteria and Global Classification of Mast Cell Disorders with Special Reference to Mast Cell Activation Syndromes: A Consensus Proposal Valent P et al 2012 Int Arch Allergy Immunol 157:215-225 
parent: physical urticaria

**Comment by nicolevasilevsky** [comment]
In the literature, I see there is chronic idiopathic urticaria, but I don't see 'idiopathic urticaria' by itself.

I would guess this would be defined as 'urticaria with an unknown cause'?

**Comment by pnrobinson** [comment]
This sounds more like a disease description to me. Let's hold off and ask the immunologists for a precise definition.

**Comment by nicolevasilevsky** [comment]
ok!

**Comment by nicolevasilevsky** [comment]
note, I did add some of the other urtcaria terms.

**Comment by pnrobinson** [comment]
Closing this as it is not a good HPO term
