### ISSUE TITLE
Suggestions for Exact Layperson Terms - Adiposis Dolorosa

### ISSUE THREAD

**Issue by GARDInfoCenter** [obophenotype/human-phenotype-ontology#3461]
Please consider the following suggestions for Exact layperson terms. 

**HPO** **Class	HPO ID	Proposed Exact Layperson Synonym**
Anxiety 	HP:0000739	Excessive, persistent worry and fear
Obesity	HP:0001513	Having too much body fat
Subcutaneous nodule	HP:0001482	Firm lump under the skin
Sparse axillary hair	HP:0002215	Little underarm hair
Arthritis 	HP:0001369	Joint inflammation
Telangiectasia	HP:0002604	Small, enlarged blood vessels near skin
Chronic pain	HP:0012532	Long-lasting pain
Painful subcutaneous lipoma	HP:0007596	Painful noncancerous fat tissue tumor under the skin

Maria Della Rocca
GARD
https://orcid.org/0000-0002-6548-5200

@nicolevasilevsky

**Comment by nicolevasilevsky** [comment]
@pnrobinson I can add these, if there are no objections. :)

**Comment by pnrobinson** [comment]
They look accurate to me!
