### ISSUE TITLE
should orcid have https:// or no?

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#3465]
I can't remember if we wanted to include the https:// in the orcid dbxref or not?

In MONDO, we are including the https://

**Comment by cmungall** [comment]
GO has been using http

https://github.com/geneontology/go-site/blob/master/metadata/users.yaml

whatever we decide, where do we record the decision in a way to maximize update? cc @mellybelly @kltm

**Comment by pnrobinson** [comment]
hmm, I think it would be simpler just to have
ORCID:0000-0000-0000-0123
but I do no thave strong feelings as long as we standardize and Q/C it!

**Comment by drseb** [comment]
I also vote for the simpler solution

**Comment by balhoff** [comment]
There is a bit of a mix of CURIEs vs IRIs in these text xref values. And I think in some places IRIs are stored as IRIs. Not necessarily in HPO, but in a bunch of ontologies. I think it would be good to clean this up, and if it is going to be a CURIE then stick with it, perhaps with a more standardized way to convert to IRI.

**Comment by pnrobinson** [comment]
On today's call we decided to standardize on ORCID:123, and not to use http

see https://github.com/monarch-initiative/hpoannotqc/issues/5


TODO -- remove the http from current ORCIDs
