### ISSUE TITLE
omit-list.txt

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3470]
I am adding a file called ``omit-list.txt`` to the directory rare-diseases/annotated
It will contain a list of files that do not describe medically relevant phenotypes.
I have added just one entry for now, but we should continue unless somebody would like to do this in another fashion.
```
#List of OMIM entries that we want to omit from further analysis
#DiseaseId    Reason
OMIM:107850   trait
```
I will add a page about this to http://hpo-annotation-qc.readthedocs.io/en/latest/index.html that will include a list of reasons.
We can (optionally) not include these files in the "big" file, but I think we should retain and continue to work on the small files.

Here are the contents of the file mentioned above
```
OMIM:107850	107850 ARM FOLDING PREFERENCE					HP:0010982	Polygenic inheritance			IEA	IEA						OMIM-CS:INHERITANCE > NON-MENDELIAN, ? HERITABILITY	OMIM:107850	HPO:skoehler	Apr 3, 0017	
```
See also https://github.com/monarch-initiative/hpo-annotation-data/issues/140
@drseb @mellybelly @cmungall 

If everybody is OK with this, then let us revise the files in https://github.com/monarch-initiative/hpo-annotation-data/issues/140 and add them to the omit-list.txt file as necessary.

**Comment by drseb** [comment]
Just a reminder, please don't remove those entries, but move them to another folder.

**Comment by pnrobinson** [comment]
OK, this is implemented and I am closing this issue.
