### ISSUE TITLE
spasticity at rest 

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#3472]
_**Please consider a new term for spasticity at rest .
Observed in Spastic Paraplegia 4.PMID:20301339.
Super class:Spasticity. **_

**Comment by pnrobinson** [comment]
Looking at this, the text says:
gait ****without***** (or with only mild) spasticity at rest 
Therefore, I think that what they are basically saying is that this is relatively mild spasticity (at least in early stages). 
I do not think that there is spasticity at rest but not upon movement and therefore I do not think this is a good term. I would recommend annotating the disease with the term for "Spasticity"
