### ISSUE TITLE
NTR: malaria-related symptoms

### ISSUE THREAD

**Issue by Aqua1ung** [obophenotype/human-phenotype-ontology#3473]
**Editor preferred term:** bipedal edema
**Textual definition:** Edema in both feet of a human subject.
**Definition source:** EuPath team
**Proposed parent:** edema
**Example of usage:** 
**Submitted by:** EuPath team

**Editor preferred term:** undernourished
**Textual definition:** Malnutrition caused by undernourishment (i.e. having been supplied with less than the minimum amount of the foods essential for sound health and growth).
**Definition source:** EuPath team
**Proposed parent:** malnutrition
**Example of usage:** 
**Submitted by:** EuPath team

**Editor preferred term:** flaky paint skin appearance
**Textual definition:** Dermatological manifestation of systemic disorder characterized by the appearance of skin as fragile and peeling away, in a manner that resembles flaky paint.
**Definition source:** EuPath team
**Proposed parent:** Dermatological manifestation of systemic disorder
**Example of usage:** 
**Submitted by:** EuPath team

**Comment by pnrobinson** [comment]
Sorry for the delay!
For Bipedal edema, try the term Pedal edema (HP:0010741). Edema is generally bilateral, and so unless you are distinguishing between unilateral and bilateral edema in your study, it should be fine to use this term.

**Comment by pnrobinson** [comment]
undernourished -- this is probably best conceptualized as a disease (it is not a specific phenotype, it is an inference based on the medical history and perhaps on various phenotypic features such as low body weight).

**Comment by pnrobinson** [comment]
I have added flaky paint dermatosis as HP_0032178
