### ISSUE TITLE
ballismus

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#3477]
_**Please consider a new term for ballismus observed in Paroxysmal kinesigenic dyskinesia.
PMID:11346027.
Suer class:Involuntary movements??  **_

**Comment by pnrobinson** [comment]
see: https://hpo.jax.org/app/browse/term/HP:0100248
Ballism refers to very large-amplitude choreic movements of the proximal parts of the limbs, causing flinging and flailing limb movements (see Chapter 15). Ballism is most frequently unilateral, in which case it is referred to as hemiballism
https://www.sciencedirect.com/topics/neuroscience/hemiballismus

Let's add ballism as an exact synonym with type "plural"
