### ISSUE TITLE
stifness of lower limb

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#3479]
_**Please consider a new term for stifness of lower limb observed in Autosomal dominant spastic paraplegia type 3.
PMID:17502470.
Superclass:Rigidity??**_

**Comment by pnrobinson** [comment]
@LOURGHI don't the authors actually just mean Lower-limb spasticity?
https://hpo.jax.org/app/browse/term/HP:0002061

If you think the patients actually had a different phenotype, please provide details and reopen this issue. thanks!
