### ISSUE TITLE
ineffective esophageal peristalsis

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#3483]
_**Please consider a new term as a related synonym?? for ineffective esophageal peristalsis observed in Eosinophilic esophagitis.
PMID:27158535.
Super class:Abnormality of esophagus physiology
Related syn:Achalasia??**_

**Comment by pnrobinson** [comment]
I think this is a subtype of Hypoperistalsis. Achalasia is also related.
