### ISSUE TITLE
Check synonyms of Ulnar deviation of the 2nd finger

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3484]
HP:0009464
name: Ulnar deviation of the 2nd finger
alt_id: HP:0004102
alt_id: HP:0005811
def: "Displacement of the 2nd (index) finger towards the ulnar side." [HPO:curators]
synonym: "Medially deviated index finger" EXACT [] --> is this correct?

**Comment by drseb** [comment]
If not, please also update:

`OMIM-112600.tab:OMIM:112600	#112600 BRACHYDACTYLY, TYPE A2; BDA2;;BRACHYMESOPHALANGY II;;MOHR-WRIEDT TYPE BRACHYDACTYLY					HP:0009464	Ulnar deviation of the 2nd finger			IEA	IEA						OMIM-CS:SKELETAL_HANDS > MEDIALLY DEVIATED INDEX FINGER	OMIM:112600	HPO:skoehler	Oct 17, 2012`
