### ISSUE TITLE
NTR: Startle seizures-listed as a phenotype

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#3485]
Not sure if this should be added or not, but "Startle seizures" is listed as a phenotype for patient 257982 in PMID:28327575.  

This could be added with seizure and add a modifier 'startle-induced', however, I do not how to code this using the HRMD tool without the addition of a completely new HPO term.

Possible definition: Startle seizures are induced by sudden and unexpected stimuli.

**Comment by pnrobinson** [comment]
I think this should be a new term
see here for some background
https://www.epilepsy.com/learn/professionals/about-epilepsy-seizures/reflex-seizures-and-related-epileptic-syndromes/startle

**Comment by shiva-g** [comment]
Epilepsiome Task Force consensus:
Suggest category of reflex seizures given the known genetic association (e.g. SYNGAP1), startle-induced seizures is a subbranch of reflex seizures. Will be provided to HPO team with larger revision of epilepsy HPO terms

**Comment by pnrobinson** [comment]
See https://github.com/obophenotype/human-phenotype-ontology/issues/5296, we are adding term as HP_0020214
