### ISSUE TITLE
congenital hypotonia 

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3486]
This is popping up as a synonym for hypotonia in males -- check this

**Comment by LCCarmody** [comment]
There is no term 'congenital hypotonia', but it is listed as a 'related synonym' to 'Severe neonatal hypotonia in males'.  There is a comment that this term should be obsoleted.  Should congenital hypotonia become a term? Or should it be a synonym for Neonatal hypotonia (HP:0001319) or Generalized neonatal hypotonia (HP:0008935) ?

**Comment by pnrobinson** [comment]
I have transfered the annotations and will merge/obsolete this term.
