### ISSUE TITLE
Loinc 718-7:  "Hemoglobin [Mass/volume] in Blood"

### ISSUE THREAD

**Issue by kingmanzhang** [obophenotype/human-phenotype-ontology#3489]
Suggest creating a new child term of HP:0011902 [Abnormal hemoglobin] for Loinc 718-7 [Hemoglobin [Mass/volume] in Blood]
New term label: "Increased hemoglobin" is not a child of "Abnormal hemoglobin; "Decreased hemoglobin" is required.
New term comment (if any):
Your biocurator ID for loinc2hpo (if desired): null

**Comment by LCCarmody** [comment]
Agreed.  This section of the HPO needs to be reworked considerably.

@pnrobinson Should 'Increased hemoglobin' continue to be a subclass of Polycythemia?  I agree it should be a child of Abnormal hemoglobin.  I think it should be parent to  'Elevated hemoglobin A1c' and 'Increased HbA2 hemoglobin'.  

Is there a consensus on if we use 'Increased' vs. 'elevated'?

**Comment by pnrobinson** [comment]
This should be the new term 
Abnormal hemoglobin concentration HP_0020061
