### ISSUE TITLE
Loinc 789-8:  "Erythrocytes [#/volume] in Blood by Automated count"

### ISSUE THREAD

**Issue by kingmanzhang** [obophenotype/human-phenotype-ontology#3490]
Suggest creating a new term for Loinc: 789-8 [Erythrocytes [#/volume] in Blood by Automated count] 
New term label: Increased/Decreased Erythrocyte Count
New term comment (if any):
Your biocurator ID for loinc2hpo (if desired): null

**Comment by pnrobinson** [comment]
see term HP_0020058
