### ISSUE TITLE
Loinc 10056-0:  "S wave duration in lead V5"

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3494]
Suggest creating a new child term of HP:0012249 [Abnormal ST segment] for Loinc 10056-0 [S wave duration in lead V5]
New term label:
New term comment (if any):
Your biocurator ID for loinc2hpo (if desired): HPO:probinson

Do we need terms for abnormal S wave duration?

**Comment by pnrobinson** [comment]
@kingmanzhang can we collect all of the EKG terms in LOINC? We should not add them one by one.

**Comment by kingmanzhang** [comment]
@nicolevasilevsky @LCCarmody @jpgourdine  Who is good at EEG/EKG terms? There are maybe a few hundred such terms. Could someone take charge of them? I can help scripting this, but I am not familiar with the topic.

**Comment by LCCarmody** [comment]
Yeah, these terms are pretty complicated.  It may require going outside our network for help. I know when I just started, Peter and group had a cardiology hackathon.  I wonder if any of those people would be interested in helping.

**Comment by nicolevasilevsky** [comment]
do we still want to work on this?

**Comment by pnrobinson** [comment]
I would suggest let's close this issue for now, since it does not make sense to work one just one such term. Let' keep our eyes open for a good opportunity to do more with EKG data. I think we will encounter a lot more of it in EHR data in the future.
