### ISSUE TITLE
Loinc 1742-6:  "Alanine aminotransferase [Enzymatic activity/volume] in Serum or Plasma"

### ISSUE THREAD

**Issue by kingmanzhang** [obophenotype/human-phenotype-ontology#3497]
Suggest creating a new term for Loinc: 1742-6 [Alanine aminotransferase [Enzymatic activity/volume] in Serum or Plasma] 
New term label: A lot of terms seem to be required for live function tests on various aminotransferases
New term comment (if any): (This is also a Github test)
Your biocurator ID for loinc2hpo (if desired): JGM:Aaron

**Comment by kingmanzhang** [comment]
sorry, liver function is what I meant.

**Comment by pnrobinson** [comment]
adding term as HP_0031964
