### ISSUE TITLE
“cock-gait”

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#3498]
_**Please consider a new term for “cock-gait” observed in Manganese poisoning.
PMID:20403794,it's not clearly described in the article but it was used in another article: Inherited manganism: the "cock-walk" gait and typical neuroimaging features.PMID: 24746291.
Superclass:gait disturbance. **_

**Comment by LOURGHI** [comment]
I found this link on YouTube, on which you can see patients with this clinical sign.
https://www.youtube.com/watch?v=GCrmSelWrnk

**Comment by pnrobinson** [comment]
adding with def: An abnormality of gait that can be observed in individuals with dystonic posture in which the individual walks with an extended trunk and flexed arms, while strutting on the toes without the heels touching the floor.
PMID:24746291

**Comment by LOURGHI** [comment]
was also observed in Cirrhosis-dystonia-polycythemia-hypermanganesemia syndrome PMID:18392750.
