### ISSUE TITLE
Difficulty walking backward

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#3499]
_**Please consider a new term for Difficulty walking backward observed in Manganese poisoning.
PMID:20403794.wich is described as  falls tendancy when walking backward.
Superclass:Gait disturbance.**_

**Comment by pnrobinson** [comment]
Adding this term HP_0031847
Def:Reduced ability to walk (ambulate) in a backwards direction.
Comment: We walk backward on a daily basis, such as when backing away from the kitchen sink or stepping back from a curb as a swiftly moving bus passes. This task may be particularly difficult for some individuals who can fall as a result of moving or being perturbed in the backward direction. Some individuals with Parkinson disease exhibit this feature.
