### ISSUE TITLE
segmental dystonia

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#3508]
_**Please consider a new term for segmental dystonia observed in Primary dystonia, DYT6 type.
PMID:17702011.
Segmental dystonia is the term given to the dystonic condition when 2 areas of the body 
are next to each other,Dystonic spasms affect at least 2 adjacent areas of the body.
Superclass:Dystonia**_

**Comment by pnrobinson** [comment]
I think it is difficult to add this as an HPO term since any combination of adjacent dystonias is classificed as segmental. Probably it is better to do this at the disease annotation level.
