### ISSUE TITLE
dystonic gait

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#3514]
_**Please consider a new term for dystonic gait observed in  Primary dystonia, DYT4 type.
PMID:21956287.
Superclass:Gait disturbance??
interesting classification of gait disturbance on this paper:https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5318488/

Gait disorder |              Characteristics
1. Hemispastic gait | Unilateral extension and circumduction
2. Paraspastic gait | Bilateral extension and adduction, stiff
3. Ataxic gait | Broad base, lack of coordination
4. Sensory ataxic gait | Cautious, worsening without visual input
5. Cautious gait | Broad based, cautious, slow, anxious
6. Freezing gait | Blockage, e. g. on turning
7. Propulsive gait | Centre of gravity in front of body, festination
8. Astasia | Primary impairment of stance/balance
9. Dystonic gait | Abnormal posture of foot/leg
10. Choreatic gait | Irregular, dance-like, broad-based
11. Steppage gait | Weakness of foot extensors
12. Waddling gait | Broad-based, swaying, drop of swinging leg
13. Antalgic gait | Shortened stance phase on affected side
14. Vertiginous gait | Insecure, tendency to fall to one side
15. Psychogenic gait disorder | Bizarre, rarely falls**_

**Comment by pnrobinson** [comment]
Thanks for this, these are great references. I am adding the term and have revised the gait section.
