### ISSUE TITLE
bradykinetic tongue

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#3516]
_**Please consider a new term for bradykinetic tongue observed in   Primary dystonia, DYT4 type.
PMID:21956287
Superclass:Bradykinesia,Movement abnormality of the tongue??**_

**Comment by pnrobinson** [comment]
I think that they are actually describing the dystonic tongue
https://hpo.jax.org/app/browse/term/HP:0031008
i.e., the tongue affected by dystonia is slow to move, but this is not a separate phenotype. It is actually a little confusing to have the authors describe the tongue dystonia in this way!
