### ISSUE TITLE
Loinc 26478-8:  "Lymphocytes/100 leukocytes in Blood"

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#3518]
Suggest creating a new child term of HP:0040088 [Abnormal lymphocyte count] for Loinc 26478-8 [Lymphocytes/100 leukocytes in Blood]
New term label: Abnormal ratio of lymphocytes/100 leukocytes in blood
New term comment (if any): Not 100% sure this is the correct label
Your biocurator ID for loinc2hpo (if desired): HPO:nvasilevsky

**Comment by pnrobinson** [comment]
This is pretty unusual, at least I have not seen this exact test. But it would be measuring the relative proportion of lymphocytes. Let's try to get some feedback on this one.

**Comment by pnrobinson** [comment]
I think this is just lymphocytosis--probably this is not a commonly used test though.
