### ISSUE TITLE
Loinc 4548-4:  "Hemoglobin A1c/Hemoglobin.total in Blood"

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#3519]
Suggest creating a new child term of HP:0011902 [Abnormal hemoglobin] for Loinc 4548-4 [Hemoglobin A1c/Hemoglobin.total in Blood]
New term label: Abnormal hemoglobin A1c/hemoglobin in blood
New term comment (if any): not sure if this is the best parent
Your biocurator ID for loinc2hpo (if desired): HPO:nvasilevsky

**Comment by pnrobinson** [comment]
I think this is actually just Elevated hemoglobin A1c (HP_0040217)
See this (https://labtestsonline.org/tests/hemoglobin-a1c)
That is, the "Abnormal hemoglobin A1c/hemoglobin" is either a percentage or a proportion (same difference). 

I do not think that there is any abnormally low value for this, so we need to code high and normal -- @kingmanzhang -- should we just leave the left field empty, even though this is a Qn code?

 Hemoglobin A1c, also called A1c or glycated hemoglobin, is hemoglobin with glucose attached. The A1c test evaluates the average amount of glucose in the blood over the last 2 to 3 months by measuring the percentage of glycated (glycosylated) hemoglobin.

**Comment by kingmanzhang** [comment]
Sorry I did not catch the email notification for the ticket. Yes, it's totally fine to leave a field empty if it is not applicable. If we encounter a test result that says "L" (low) in real world, the app will say "I don't know how to convert this test because it is not annotated"--a fine outcome.

**Comment by pnrobinson** [comment]
OK, then I think we can close this issue!
