### ISSUE TITLE
akathisia

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#3521]
Please consider a new term for akathisia observed in  Postencephalitic parkinsonism.
PMID:7299406.
Superclass:Involuntary movements??
the concept exists on HPO in the definition of Abnormality of extrapyramidal motor function and akathisia is defined as inability to remain motionless.

**Comment by pnrobinson** [comment]
See this reference
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1123446/

**Comment by LOURGHI** [comment]
it seems to me Restlessness is the most  adequate parent according to this paper.

**Comment by pnrobinson** [comment]
adding term as HP_0031943
