### ISSUE TITLE
irregular respiratory rhythm

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#3523]
_**Please consider a new term for irregular respiratory rhythm observed in Postencephalitic parkinsonism.
PMID:7299406.
Superclass:Functional respiratory abnormality.
This term was used in this article
https://www.ncbi.nlm.nih.gov/pubmed/27799864**_

**Comment by pnrobinson** [comment]
THis is HP_0012195, Irregular respiration. 
I will add this as a synonym.
