### ISSUE TITLE
released palmar grasping

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#3524]
_**Please consider a new term for released palmar grasping observed in Postencephalitic parkinsonism.
 PMID:7299406
Superclass:Diminished movement??**_

**Comment by pnrobinson** [comment]
I think that the phenotype is actually the grasp reflex (which is abnormal if it is NOT released!)
https://hpo.jax.org/app/browse/term/HP:0030903
So the authors are basically saying that the patient did NOT have this phenotype.
