### ISSUE TITLE
Optokinetic nystagmus(OKN)

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#3526]
_**Please consider a new term for Optokinetic nystagmus observed in Kufor-Rakeb syndrome.
PMID:15986421.
Superclass:Nystagmus**_

**Comment by pnrobinson** [comment]
Optokinetic nystagmus is a normal phenomenon and not an abnormal phenotype, see:
https://en.wikipedia.org/wiki/Optokinetic_response
I do not have access to this article right now, but please reopen this issue if there is actually a medically abnormal type of Nystagmus in this case.
