### ISSUE TITLE
clasp-knife sign 

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#3531]
_**Please consider a new term for clasp-knife sign observed in Kufor-Rakeb syndrome.
PMID: 15986421.
Superclass:Corticospinal tract dysfunction??**_

**Comment by pnrobinson** [comment]
Definition: Clasp-knife phenomonen refers to increased muscle tone while bending or stretching a limb, whereby there is a sudden relaxtion (decrease in resistance) as the muscle continues to be streched. This phenomenon has been likened to opening a clasp knife.
