### ISSUE TITLE
irregular jerky movements of the ﬁngers

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#3534]
_**Please consider a new term for irregular jerky movements of the ﬁngers observed in Kufor-Rakeb syndrome.
PMID:15986421.
Superclass:Abnormality of finger??**_

**Comment by pnrobinson** [comment]
THe patients in this article are described as having FFF minimyoclonus.
The FFF stands for Facial-faucial-finger (faucial=related to the passage from the back of the mouth to the pharynx, bounded by the soft palate, the base of the tongue, and the palatine arches).

**Comment by pnrobinson** [comment]
I am adding polyminimyoclonus as HP_0031986
