### ISSUE TITLE
tachylalia/tachylogia

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#3537]
_**Please consider a new term for tachylalia/tachylogia observed in Atypical pantothenate kinase-associated neurodegeneration.
PMID:20301663.
Superclass:Speech disorder?? **_

**Comment by pnrobinson** [comment]
Definition: Extreme rapidity of speech.
This maybe needs to go under neurological speech impairment, but we may want to change that label.

**Comment by pnrobinson** [comment]
Adding as HP_0031937
