### ISSUE TITLE
freezing of gait

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#3539]
_**Please consider a new term for freezing of gait observed in Atypical pantothenate kinase-associated neurodegeneration.
PMID: 26828213.
Superclass:Gait disturbance??**_

**Comment by pnrobinson** [comment]
Here is a good definition:
https://www.ncbi.nlm.nih.gov/pubmed/23625316

**Comment by pnrobinson** [comment]
added as HP_0031825
