### ISSUE TITLE
Update neoplasm usages to use NCIT

### ISSUE THREAD

**Issue by balhoff** [obophenotype/human-phenotype-ontology#3540]
There are a few logical definitions that accidentally use DOID terms instead of NCIT. Here is the list, along with suggested replacements:

- [x] [HP:Insulinoma](http://purl.obolibrary.org/obo/HP_0012197) definition -> reference [NCIT:Pancreatic Insulinoma](http://purl.obolibrary.org/obo/NCIT_C95598)
- [x] [HP:Neuroendocrine neoplasm](http://purl.obolibrary.org/obo/HP_0100634) definition -> reference [NCIT:Neuroendocrine Neoplasm](http://purl.obolibrary.org/obo/NCIT_C3809)
- [x] [HP:Leukemia](http://purl.obolibrary.org/obo/HP_0001909) definition -> reference [NCIT:Leukemia](http://purl.obolibrary.org/obo/NCIT_C3161)
- [x] [HP:Endometrial carcinoma](http://purl.obolibrary.org/obo/HP_0012114), [HP:Esophageal carcinoma](http://purl.obolibrary.org/obo/HP_0011459), [HP:Fallopian tube carcinoma](http://purl.obolibrary.org/obo/HP_0030394), [HP:Laryngeal carcinoma](http://purl.obolibrary.org/obo/HP_0012118), [HP:Pituitary carcinoma](http://purl.obolibrary.org/obo/HP_0011763) definitions -> reference [NCIT:Carcinoma](http://purl.obolibrary.org/obo/NCIT_C2916)

These are all my best guesses. If there is some reason these aren't perfect replacements, please let me know.

**Comment by balhoff** [comment]
@pnrobinson I can update the definitions if you are okay with the suggested terms—I was proposing to just replace the usage of the DO term with the corresponding NCIT term. So that's where NCIT:Carcinoma comes from.

**Comment by pnrobinson** [comment]
OK, but this is still not a great definition, and we should try to come up with a general plan--should we just wait until after the NCI Semantic meeting?

**Comment by pnrobinson** [comment]
@drseb @balhoff @cmungall  -- is there any reason for us to keep the DO in the hp-edit file?
In any case, I tried to update leukemia but I think the NCIT term for leukemia is not mireoted -- could we document the process for doing this? thanks

**Comment by pnrobinson** [comment]
@drseb @balhoff @cmungall 
ping :-0
-- should we mireot these terms and remove reference to DO in the ho-edit file?

**Comment by balhoff** [comment]
> should we mireot these terms and remove reference to DO in the ho-edit file?

Yes I think so.

**Comment by pnrobinson** [comment]
@balhoff @matentzn @drseb -- can we remove the DO import and close this issue?

**Comment by matentzn** [comment]
Haha I never realised that Jim has already raised that issue last year. https://github.com/obophenotype/human-phenotype-ontology/pull/4319/

**Comment by matentzn** [comment]
DOID is now removed, can be closed.
