### ISSUE TITLE
abnormal Finger chase test

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#3541]
_**Please consider a new term for abnormal Finger chase test observed in Autosomal recessive congenital cerebellar ataxia due to MGLUR1 deficiency.
PMID: 22901947.
Superclass:Dysmetria??
this sign is part of the of SARA score,should we also create a term for this score?? **_

**Comment by pnrobinson** [comment]
The finger chase test measures Dysmetria (HP_0001310). I will extend the definition and add Abnormal finger chase test as a synonym.

**Comment by pnrobinson** [comment]
Adding this as a new comment
Dysmetria can result in moving beyond the target (hypermetria) or failing to reach the target (hypometria) during a voluntary movement. Dysmetria can be assessed clinically by the finger chase test, whereby the examiner and the proband are sitting, and the examiner suddenly moves his or her finger five times in an unpredictable direction in a frontal plane, with movements having an amplitude of about 30 cm and a frequency of once every two seconds. The proband is asked to follow the movements with his or her index finger. The test is abnormal if the proband substantially under- or overshoots or cannot perform pointing movements at all. The finger-nose-finger test is similar, and the proband is asked to alternately touch his or her own nose and then to point to the finger of the examiner.
Adding Abnormal finger chase test and Abnormal finger-nose-finger test as related synonyms.
