### ISSUE TITLE
difficulty sitting

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#3542]
_**Please consider a new term for difficulty sitting observed in Autosomal recessive congenital cerebellar ataxia due to MGLUR1 deficiency.
PMID:22901947.
Superclass:Functional motor deficit??**_

**Comment by pnrobinson** [comment]
@LOURGHI in the paper you refer to the authors are referring to a cerebellar deficit. Difficulty sitting can also be a result of lower back pain and other items. I am wondering if actually the term Truncal ataxia is correct here? Please comment

**Comment by pnrobinson** [comment]
I would suggest that we not make a term called difficulty sitting because it is too imprecise. We can reopen this issue if more information becomes available.
