### ISSUE TITLE
Add synonym to HP_0005952 'Decreased pulmonary function'  

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#3543]
impaired pulmonary function should be a synonym for HP_0005952 'Decreased pulmonary function' 

Also should add synonyms 'impaired lung function'

**Comment by pnrobinson** [comment]
The subhierarchy in this area needs a little TLC, but I think it is OK for now to add "impaired pulmonary function" as EXACT and 'impaired lung function' as EXACT LAYPERSON.
