### ISSUE TITLE
add synonym to ‘breathing dysregulation’ (HP_0005957

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#3544]
add ‘trouble breathing’ as a synonym

**Comment by nicolevasilevsky** [comment]
@pnrobinson does this look okay to you? I can go ahead and add it if there are no objections.

**Comment by pnrobinson** [comment]
No, actually breathing dysregulation is a very specific phenotype but trouble breathing is very broad. I am seeing that the other synonyms of HP_0005957 also are too broad, we need to revise this -- I am a the airport now, will have a closer look soon.

**Comment by nicolevasilevsky** [comment]
Ok, thanks @pnrobinson!

**Comment by nicolevasilevsky** [comment]
add as synonym for HP_0002094 Dyspnea
