### ISSUE TITLE
NTRs: Abn of musculature

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#3546]
**NTR:** Abnormality of the chest musculature
**Parent:** HP_0003011 'Abnormality of the musculature'
**Syn:** Muscle issues in the chest
**Def:** Any abnormality of the chest muscles.
**Ref:** https://orcid.org/0000-0001-5208-3432
**Logical def:** 
'has part' some 
(quality and ('inheres in part of' some 'chest muscle') and ('has modifier' some abnormal))

**NTR:** Abnormality of the back musculature
**Parent:** HP_0003011 'Abnormality of the musculature'
**Syn:** Muscle issues in the back
**Def:** Any abnormality of the back muscles.
**Ref:** https://orcid.org/0000-0001-5208-3432
**Logical def:** 
'has part' some 
(quality and ('inheres in part of' some 'muscle of back') and ('has modifier' some abnormal))

**NTR:** Abnormality of the shoulder musculature
**Parent:** HP_0003011 'Abnormality of the musculature'
**Syn:** Muscle issues in the shoulder
**Def**: Any abnormality of the shoulder muscles.
**Ref:** https://orcid.org/0000-0001-5208-3432
**Logical def:** 
'has part' some 
(quality and ('inheres in part of' some 'musculature of shoulder') and ('has modifier' some abnormal))

**Comment by pnrobinson** [comment]
looks good to me @nicolevasilevsky but I am not sure if "muscle issues in the shoulder" etc is really that clear?

**Comment by nicolevasilevsky** [comment]
These terms are for PCORI, for the self-phenotyping survey. I will add the synonyms as broad synonyms.
