### ISSUE TITLE
Loinc 26511-6:  "Neutrophils/100 leukocytes in Blood"

### ISSUE THREAD

**Issue by kingmanzhang** [obophenotype/human-phenotype-ontology#3549]
Suggest creating a new term for Loinc: 26511-6 [Neutrophils/100 leukocytes in Blood] 
New term label: Neutrophils Percentage Abnormality (?)
New term comment (if any): There appears to be quite a lot of tests on the percentage of some cell types. Not sure what is the best way to model them, but maybe something like a child term under the abnormality in cell count.
Your biocurator ID for loinc2hpo (if desired): JGM:azhang

**Comment by pnrobinson** [comment]
This can be coded with simply Neutrophilia etc. @kingmanzhang

**Comment by kingmanzhang** [comment]
done
