### ISSUE TITLE
Pseudocleft

### ISSUE THREAD

**Issue by petkraw** [obophenotype/human-phenotype-ontology#3550]
_For new term requests, please provide us with the following information:_
pseudocleft 1. Preferred term label

### 2. Synonyms

first you think it's a cleft, then you realize it's not 3. Textual definition (should be understandable even for non-specialists, please include a PubMed ID for relevant articles providing additional information about the suggestion)

abnormality of the cleft 4. Parent term (use [HPO Browser](http://compbio.charite.de/hpoweb/showterm?id=HP:0000118) or [OLS](http://www.ebi.ac.uk/ols/ontologies/hp))

https://omim.org/entry/113620?search=113620&highlight=113620#23 5. Which diseases are characterized by this term ? (e.g. Orphanet- or OMIM-id)

 https://orcid.org/0000-0002-3194-8625 6. Your nano-attribution (ORCID-id or label, e.g. _HPO:probinson_ (organization:name))

**Comment by pnrobinson** [comment]
@markengelstad can you provide a definition for Pseudocleft? Is pseudocleft one of the Tessier levels? Or is it just a "mild" cleft? Should we have a separate term for this?

**Comment by pnrobinson** [comment]
I cannot find any decent definition for this and would suggest using Cleft perhaps with a Mild modifier. If we can find a more precise definition with a PMID then please reopen the issue!
