### ISSUE TITLE
Loinc 5770-3:  "Bilirubin.total [Presence] in Urine by Test strip"

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#3551]
Suggest creating a new child term of HP:0003573 [Increased total bilirubin] for Loinc 5770-3 [Bilirubin.total [Presence] in Urine by Test strip]
New term label: Abnormal bilirubin level in urine
New term comment (if any): add increased and decreased terms too
Your biocurator ID for loinc2hpo (if desired): HPO:nvasilevsky

**Comment by pnrobinson** [comment]
Blirubinuria is HP_0031811
