### ISSUE TITLE
Loinc 10839-9:  "Troponin I.cardiac [Mass/volume] in Serum or Plasma"

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#3552]
Suggest creating a new child term of HP:0500020 [Abnormal cardiac biomarker test] for Loinc 10839-9 [Troponin I.cardiac [Mass/volume] in Serum or Plasma]
New term label: Abnormal troponin I level in blood
New term comment (if any): not sure if this is ever decreased? increased levels are detected after a heart attack, yes?
Your biocurator ID for loinc2hpo (if desired): HPO:nvasilevsky

**Comment by pnrobinson** [comment]
There is no relevant situation with reduced troponin concentrations, and so we only need a term for elevated cardiac troponin I in the blood. Let's figure out the current gold standard for the various troponin isoforms, see also https://labtestsonline.org/tests/troponin

**Comment by nicolevasilevsky** [comment]
Looks like there are LOINC codes for Troponin I and Troponin T (and according to the website you linked above, these are the two markers that are measured.)

**Comment by nicolevasilevsky** [comment]
@drseb can you please MIREOT:
PR_000016509 troponin T, cardiac muscle
PR_000016503 troponin C, skeletal muscle

**Comment by pnrobinson** [comment]
This is  HP_0410173
