### ISSUE TITLE
Loinc 3084-1:  "Urate [Mass/volume] in Serum or Plasma"

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#3553]
Suggest creating a new child term of HP:0012610 [Abnormality of urinary uric acid concentration] for Loinc 3084-1 [Urate [Mass/volume] in Serum or Plasma]
New term label: abnormality of urate in blood
New term comment (if any): need increased/decreased terms too
Your biocurator ID for loinc2hpo (if desired): HPO:nvasilevsky

**Comment by pnrobinson** [comment]
This is hyper/hypouricemia
