### ISSUE TITLE
Loinc 2276-4:  "Ferritin [Mass/volume] in Serum or Plasma"

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#3557]
Suggest creating a new term for Loinc: 2276-4 [Ferritin [Mass/volume] in Serum or Plasma] 
New term label: Abnormal ferritin level in serum or plasma
New term comment (if any): need increased/decreased terms too. Should be parent of abn serum ferritin
Your biocurator ID for loinc2hpo (if desired): HPO:nvasilevsky

**Comment by pnrobinson** [comment]
This should be HP_0040133, Abnormal serum ferritin. We should probably rename the term. There is no medical difference if you measure in serum or plasma, and thus no need for two different HPO terms.

**Comment by pnrobinson** [comment]
I have added the obvious alternate labels with "plasma" as synonyms and updated the definition to
A deviation from the normal circulating concentration of ferritin. Ferritin concentration can be measured in serum or plasma.
comment; Ferritin is an iron storage protein present in all cells of the organism. A small amount is found in plasma and serum, which is a reflection of iron stores in healthy individuals. A low serum ferritin concentration is usually regarded as an indicator of iron depletion, although the interpretation of normal or high serum ferritin values is challenging in the presence of acute or chronic inflammatory processes, as ferritin is increased in iron overload states and inflammation.
