### ISSUE TITLE
Loinc 43983-6:  "Amphetamines [Presence] in Urine by Screen method >500 ng/mL"

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#3558]
Suggest creating a new term for Loinc: 43983-6 [Amphetamines [Presence] in Urine by Screen method >500 ng/mL] 
New term label: Presence of ampehtamine in urine
New term comment (if any): related to #3421
Your biocurator ID for loinc2hpo (if desired): HPO:nvasilevsky

**Comment by LCCarmody** [comment]
I just added 'Positive urine amphetamine test' (Issue #3561). Do we need a separate term for an amephetamine test>500ng/ml? @nicolevasilevsky @kingmanzhang @pnrobinson

**Comment by pnrobinson** [comment]
I would suggest we just have one term at this point -- positive or negative.

**Comment by LCCarmody** [comment]
Closing this issue.
