### ISSUE TITLE
Loinc 19550-3:  "Methadone [Presence] in Urine by Screen method"

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#3559]
Suggest creating a new term for Loinc: 19550-3 [Methadone [Presence] in Urine by Screen method] 
New term label: presence of methadone in urine
New term comment (if any): related to #3421
Your biocurator ID for loinc2hpo (if desired): HPO:nvasilevsky

**Comment by nicolevasilevsky** [comment]
I added Blood xenobiotic (HP_0410172). I think we can close this ticket now?

**Comment by LCCarmody** [comment]
I'm closing this ticket.
