### ISSUE TITLE
Loinc 14314-9:  "Benzoylecgonine [Presence] in Urine by Screen method"

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#3560]
Suggest creating a new term for Loinc: 14314-9 [Benzoylecgonine [Presence] in Urine by Screen method] 
New term label: Presence of benzoylecgonine in urine
New term comment (if any): related to #3421
Your biocurator ID for loinc2hpo (if desired): HPO:nvasilevsky

**Comment by LCCarmody** [comment]
This is a major metabolite of cocaine.  Should we include this under 'Positive cocaine urine test' as my definition was "Detection of cocaine or its major metabolite, benzoylecgonine, in urine." Or should we separate the two and have two distinct terms?
@nicolevasilevsky @kingmanzhang @pnrobinson

**Comment by pnrobinson** [comment]
I think for now this can go under Positive cocaine urine test, since there is no clinical need to know about the specific metabolites as far as I am aware!

**Comment by LCCarmody** [comment]
Closing issue.
