### ISSUE TITLE
Loinc 728-6:  "Hypochromia [Presence] in Blood by Light microscopy"

### ISSUE THREAD

**Issue by jpgourdine** [obophenotype/human-phenotype-ontology#3563]
Suggest creating a new term for Loinc: 728-6 [Hypochromia [Presence] in Blood by Light microscopy] 
New term label:Hypochromia
New term comment (if any):
Your biocurator ID for loinc2hpo (if desired): OHSU:JP

**Comment by pnrobinson** [comment]
adding as HP_0032231 @kingmanzhang

**Comment by kingmanzhang** [comment]
done
