### ISSUE TITLE
Loinc 20407-3:  "Nitrite [Mass/volume] in Urine by Test strip"

### ISSUE THREAD

**Issue by jpgourdine** [obophenotype/human-phenotype-ontology#3564]
Suggest creating a new term for Loinc: 20407-3 [Nitrite [Mass/volume] in Urine by Test strip] 
New term label:abnormal nitrite level in the urine
New term comment (if any):need increase and decrease level as well
Your biocurator ID for loinc2hpo (if desired): OHSU:JP

**Comment by pnrobinson** [comment]
suggest label abnormal urine nitrite concentration

**Comment by pnrobinson** [comment]
label: Nitrituria
def: Presence of nitrites in the urine.
comment: Nitrituria may be diagnosed on the basis of a positive test result on a urine dipstick test. Nitrites are not found in normal urine. Some gram-positive and gram-negative bacteria metabolize nitrates in urine to nitrites, and a positive urine dipstick test for nitrites most commonly suggests a bacterial urinary tract infection.
PMID:27377945

**Comment by pnrobinson** [comment]
added term as HP_0031812

**Comment by pnrobinson** [comment]
added LOINC annotations
