### ISSUE TITLE
Loinc 5770-3:  "Bilirubin.total [Presence] in Urine by Test strip"

### ISSUE THREAD

**Issue by jpgourdine** [obophenotype/human-phenotype-ontology#3565]
Suggest creating a new child term of HP:0002904 [Hyperbilirubinemia] for Loinc 5770-3 [Bilirubin.total [Presence] in Urine by Test strip]
New term label:Abnormal bilirubin in the urine
New term comment (if any):increase level and decrease level of bilirubin in the urine should be added to
Your biocurator ID for loinc2hpo (if desired): OHSU:JP

**Comment by pnrobinson** [comment]
Suggest label: Abnormal urine bilirubin concentration

**Comment by pnrobinson** [comment]
Actually, the label should be Bilirubinuria (which is either present or absent)
Definition: Presence of conjugated bilirubin in the urine.
Comment: Bilirubinuria may lead to a dark yellow to orange color of the urine. Conjugated bilirubin is excreted in the urine and thus conjugated hyperbilirubinemia may lead to bilirubinuria.

**Comment by pnrobinson** [comment]
Note that there is no "abnormally decreased" level of bilirubin in the urine, and so simply having the term Hyperbilirubinuria is correct.

**Comment by pnrobinson** [comment]
term added as HP_0031811

**Comment by pnrobinson** [comment]
see https://github.com/TheJacksonLaboratory/loinc2hpoAnnotation/issues/5
