### ISSUE TITLE
Loinc 51703-7:  "Ganglioside GM1 IgM Ab [Units/volume] in Serum by Immunoassay"

### ISSUE THREAD

**Issue by jpgourdine** [obophenotype/human-phenotype-ontology#3566]
Suggest creating a new child term of HP:0004345 [Abnormality of ganglioside metabolism] for Loinc 51703-7 [Ganglioside GM1 IgM Ab [Units/volume] in Serum by Immunoassay]
New term label: Abnormality in GM1-ganglioside metabolism
New term comment (if any): Increase and decrease GM1-ganglioside should also be added 
In this case, there are 2 measurements, 1)direct measurement is anti-GM1 ganglioside IgM antibodies concentration 2)indirect measurement: inferred an increase of the epitope GM1-ganglioside. Not sure how to deal with this one
Your biocurator ID for loinc2hpo (if desired): OHSU:JP

**Comment by pnrobinson** [comment]
Perhaps a better label is Abnormal GM1-gangloside metabolism (or abnormality "of", not "in"). The HPO tries not to include the measurement, and so probably there should be one term and we can describe the measurement modalities in a comment -- unless they are measuring different entities.

**Comment by pnrobinson** [comment]
This should be a child of "Autoimmune antibody positivity"
I am creating a term called  IgM anti-ganglioside GM1 antibody positivity
definition: The presence of autoantibodies (immunoglobulins) of the IgM class in the serum that react against GM1 ganglioside.
comment:Autoantibodies directed against gangliosides are often polyclonal and of the IgM isotype. They are characterised by low avidity binding to the carbohydrate moiety of the ganglioside molecule. Although the pathogenic impor- tance of these antibodies is unclear, they are in many cases reactive against the GM1 ganglioside. The latter is the most abundant ganglioside in neuronal membranes but is rare outside the nervous system.5 GM1 is exposed at the surface of spinal motor neurones, in contrast to the peripheral nerves where its expression is limited to the node and para- nodal region.6 Increased titres of antiganglioside antibod- ies (AGA) have been recorded in many upper and lower motor neurone syndromes and several autoimmune conditions but very high titres tend to be found in patients with multifocal motor neuropathy with conduction block. There is, however, a considerable overlap in the serum titres of AGA found in normal healthy people and patients with autoimmune and neurological disease.
PMID:8027366

**Comment by pnrobinson** [comment]
@jpgourdine I am going to add your nanoattribution as OHSU:jpgourdine to match the style of the other ones, OK?

**Comment by pnrobinson** [comment]
@jpgourdine @nicolevasilevsky @kingmanzhang 
Should we leave these terms open until we have also added the LOINC annotation? I just created the term HP_0031810 but I have not yet added the LOINC. Aaron can we do this together on Monday to make sure we agree on the SOP of how to do this?

**Comment by kingmanzhang** [comment]
@pnrobinson Sure. We have a lot to talk on Monday.

**Comment by jpgourdine** [comment]
@pnrobinson I will contribute more after Tuesday, after my presentation about Molecular Phenotyping with Glycans to some to NIH folks

**Comment by nicolevasilevsky** [comment]
@pnrobinson yes, I think it would be good to leave tickets open until we add the LOINC annotation.

I created a project board for this project, to keep track of the open tickets.

**Comment by pnrobinson** [comment]
I think the best SOP is just to add a NTR to the Loinc annotation and to close these issues

Anti-ganglioside GM1 IgM antibody positivity is now HP_0031810

see https://github.com/TheJacksonLaboratory/loinc2hpoAnnotation/issues/6
