### ISSUE TITLE
 New Term Request : Archibald's sign

### ISSUE THREAD

**Issue by pbuczkowicz** [obophenotype/human-phenotype-ontology#3568]
### 1. Preferred term label: 

Archibald's sign

### 2. Synonyms: 

Archibald's metacarpal sign
Knuckle knuckle dimple dimple

### 3. Textual definition (should be understandable even for non-specialists, please include a PubMed ID for relevant articles providing additional information about the suggestion):

Shortening of the fourth and fifth metacarpals when the fist is clenched.

### 4. Parent term:

HP:0001163 Abnormality of the metacarpal bones

### 5. Which diseases are characterized by this term ?:

OMIM #612463 ALBRIGHT HEREDITARY OSTEODYSTROPHY  (aka PSEUDOPSEUDOHYPOPARATHYROIDISM)

ORDO881 TURNER SYNDROME

### 6. Your nano-attribution (ORCID-id or label, e.g. _HPO:probinson_ (organization:name))

_Gene42:pbuczkowicz_

**Comment by pnrobinson** [comment]
I am going to add the synonym "dimpling over the knuckles of a clenched fist". I am not sure about the word duplications for Knuckle knuckle dimple dimple
see
https://academic.oup.com/qjmed/article/106/1/83/1531761
