### ISSUE TITLE
NTR: phenotypes for Anti-NMDA Receptor Encephalitis

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#3569]
@jmcmurry requested some new phenotype terms for the disease 'Anti-NMDA Receptor Encephalitis'

See: https://github.com/monarch-initiative/mondo/issues/151

- Changes in speech
- Disorganization
- Movement abnormalities
- Executive dysfunction

@pnrobinson do you think these terms would be suitable for HPO? If yes, I'll work on adding them.

**Comment by pnrobinson** [comment]
@jmcmurry I think that in the article that I think you found (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3983958/) there are much better descriptions of the phenotype than the above (which are very high level). I think that we actually already have all the HPO terms needed. The common disease format should be finished relatively soon and we can give things a go.
