### ISSUE TITLE
NTR: optic ataxia

### ISSUE THREAD

**Issue by cmungall** [obophenotype/human-phenotype-ontology#3570]
_For new term requests, please provide us with the following information:_
### 1. Preferred term label

Optic ataxia

### 3. Textual definition (should be understandable even for non-specialists, please include a PubMed ID for relevant articles providing additional information about the suggestion)

a high order deficit in reaching to visual goals that occurs with posterior parietal cortex (PPC) lesions.

https://www.ncbi.nlm.nih.gov/pubmed/24607223

### 4. Parent term (use [HPO Browser](http://compbio.charite.de/hpoweb/showterm?id=HP:0000118) or [OLS](http://www.ebi.ac.uk/ols/ontologies/hp))

HP:0011446 ! Abnormality of higher mental function

### 5. Which diseases are characterized by this term ? (e.g. Orphanet- or OMIM-id)

```
[Term]
id: MONDO:0018211
name: Balint syndrome
def: "Balint syndrome is a rare neurologic disease characterized by the triad of optic ataxia, ocular apraxia and simultanagnosia due to posterior parietal lobe lesions. Patients report ophthalmologic difficulties in the absence of underlying ophthalomologic anomalies and present severe visual and spatial disabilities in locating and reaching objects, initiating voluntary eye movements and perceiving more than one object at a time." [Orphanet:363746]
subset: ordo_disease {source="Orphanet:363746"}
synonym: "psychic paralysis of visual fixation" EXACT [PMID:13208876, MONDO:cjm]
synonym: "Balint-Holmes syndrome" EXACT [Orphanet:363746]
synonym: "Optic ataxia-gaze apraxia-simultanagnosia syndrome" EXACT [Orphanet:363746]
xref: ICD10:H51.8 {source="Orphanet:363746", source="ORDO:363746/ntbt"}
xref: Orphanet:363746 {source="MONDO:Leader", source="MONDO:equivalentTo"}
xref: UMLS:C0270706 {source="Orphanet:363746"}
is_a: MONDO:0020009 {source="Orphanet:363746"} ! rare neurologic disease
```

### 6. Your nano-attribution (ORCID-id or label, e.g. _HPO:probinson_ (organization:name))

https://orcid.org/0000-0002-6601-2165

**Comment by pnrobinson** [comment]
Adding term HP_0031868
def:Difficulty reaching to visually guided goals in peripheral vision, with the deficit leaves voluntary eye movements largely unaffected.
domment:Optic ataxia is related to a cortical neurologic deficit that is a result of a lesion to the superior parietal lobule (SPL) and areas around the intraparietal sulcus (IPS). The phenomenon is thought not to be an apraxia (a disorder in executing learned behaviors), but rather a lack of coordination between visual input and motor outputs, and thus the term ataxia, Greek for Lack of Order.

PMID:24607223

**Comment by pnrobinson** [comment]
Please use ORDIC:0000-0002-6601-2165
