### ISSUE TITLE
NTR: Gonadal agenesis

### ISSUE THREAD

**Issue by cmungall** [obophenotype/human-phenotype-ontology#3571]
_For new term requests, please provide us with the following information:_
### 1. Preferred term label

Gonadal agenesis

### 2. Synonyms

Lack of development of the gonads

### 3. Textual definition (should be understandable even for non-specialists, please include a PubMed ID for relevant articles providing additional information about the suggestion)

Agenesis of the gonads

### 4. Parent term (use [HPO Browser](http://compbio.charite.de/hpoweb/showterm?id=HP:0000118) or [OLS](http://www.ebi.ac.uk/ols/ontologies/hp))

http://purl.obolibrary.org/obo/HP_0000133 gonadal disgenesis

OR: consider adding as narrow syn

NOTE: the two exact syns for HP_0000133 are disjoint, these should be narrow

```
synonym: "Mixed gonadal dysgenesis" EXACT []
synonym: "Pure gonadal dysgenesis" EXACT []
```

### 5. Which diseases are characterized by this term ? (e.g. Orphanet- or OMIM-id)

```
id: MONDO:0010838
name: gonadal agenesis
def: "A congenital disorder characterized by the complete absence of gonadal tissue." [NCIT:C27228]
synonym: "GONADAL AGENESIS" RELATED [OMIM:600171]
xref: NCIT:C27228 {source="MONDO:kboom-pr-1.00/0.92/31.20", source="MONDO:equivalentTo"}
xref: OMIM:600171 {source="MONDO:Leader", source="MONDO:equivalentTo"}
xref: UMLS:C0949331 {source="NCBI:mim2gene_medline", source="OMIM:600171", source="NCIT:C27228"}
```

https://omim.org/entry/600171

perhaps the disease should be called "AR gonadal agenesis" to distinguish from the feature?

**Comment by cmungall** [comment]
note the OMIM only has 2 annots so far

```
OMIM    600171  600171 GONADAL AGENESIS         HP:0000007-Autosomal recessive inheritance      OMIM:600171     IEA                            I
                2009-02-17      HPO:curators
OMIM    600171  600171 GONADAL AGENESIS         HP:0000119-Abnormality of the genitourinary system      OMIM:600171     IEA                    O
                2009-02-17      HPO:curators
```

**Comment by pnrobinson** [comment]
Note the parent term is wrong-- it is DYSgenesis and not DISgenesis. Probably these need to be sibs, but I think there may be an existing synonym, please post here before making a new term.

**Comment by pnrobinson** [comment]
There is currently a related term, "Absent gonadal tissue" that presumably means the same thing or is a very close synonym. I will look at the annotated disease and write a definition and either create a new term or change the primary label to Gonadal agenesis as appropriate

**Comment by pnrobinson** [comment]
OMIM https://omim.org/entry/600908 uses Agonadism, and this is synonymous with Gonadal agenesis
Same is true for Pagod syndrome (we need an OMIM entry for this, https://omim.org/entry/202660?search=%20Pagod%20Syndrome&highlight=pagod%20syndromic%20syndrome)
True for https://omim.org/entry/241090

-These are synonymous terms.

**Comment by pnrobinson** [comment]
I changed the primary label of Absent gonadal tissue to Agonadism and added Gonadal agenesis as a synonym.
New def: Absence of sex glands (gonads are the organs that produce gametes; testis in males and ovary in females).
New comment: Gonadal agenesis refers to the lack of development of gonads during fetal development; it may not be possible clinically to determine if gonal tissue was present at any point of development. For this reason, we regard agonadism and gonadal agenesis as synonymous.
