### ISSUE TITLE
decreased waist to hip ratio

### ISSUE THREAD

**Issue by slaulederkind** [obophenotype/human-phenotype-ontology#3573]
_

    If this is a request for a new term, please provide us with the folloing information (c.f., https://github.com/obophenotype/human-phenotype-ontology/wiki/How-to-make-a-good-term-request).

1. Preferred term label (e.g., Asplenia)_

decreased waist to hip ratio

2. Synonyms (e.g., Absent spleen)

decreased waist-to-hip ratio; decreased WHR; decreased waist–hip ratio

3. Textual definition (the definition should be understandable even for non-specialists. Include a PubMed ID to refer to any relevant article that provides additional information about the suggested term).

Decreased waist-to-hip ratio (WHR) is a measurement below the average for the dimensionless ratio of the circumference of the waist to that of the hips. WHR is calculated as waist measurement divided by hip measurement ( W ÷ H ).  PMID:12872269

4.Suggested parent term (Please look in the hierarchy of the HPO using the HPO Browser or other browsers such as OLS and find the place in the HPO where the new term best fits)

Decreased body weight (HP:0004325)

5. If you know of a disease that is characterized by this feature, please indicate it (e.g., by its Orphanet or OMIM id), and we will add the annotation to our database.

OMIM:125853
DIABETES MELLITUS, NONINSULIN-DEPENDENT

6. If you would like a nanoattribution, please indicate your ORCID id or provide a label such as HPO:probinson (organization, first initial-last name)

RGD:gthayman

**Comment by pnrobinson** [comment]
Adding this as HP_0031820 -- thanks!
Will add the annotation shortly.
