### ISSUE TITLE
decreased circulating parathyroid hormone level

### ISSUE THREAD

**Issue by slaulederkind** [obophenotype/human-phenotype-ontology#3574]
_For new term requests, please provide us with the following information:_
### 1. Preferred term label

decrease circulating parathyroid hormone level

### 2. Synonyms
decreased circulating PTH level ;  decreased serum parathyroid hormone ;   decreased serum parathyroid hormone level ;   decreased serum pth ;   decreased serum parathyroid hormone

### 3. Textual definition (should be understandable even for non-specialists, please include a PubMed ID for relevant articles providing additional information about the suggestion)

An abnormal decreased concentration of parathyroid hormone. PMID:1302009

### 4. Parent term (use [HPO Browser](http://compbio.charite.de/hpoweb/showterm?id=HP:0000118) or [OLS](http://www.ebi.ac.uk/ols/ontologies/hp))

Abnormality of circulating hormone level (HP:0003117); Abnormality of calcium-phosphate metabolism (HP:0100530)

### 5. Which diseases are characterized by this term ? (e.g. Orphanet- or OMIM-id)

OMIM:146200 

### 6. Your nano-attribution (ORCID-id or label, e.g. _HPO:probinson_ (organization:name))

RGD:gthayman

**Comment by pnrobinson** [comment]
thanks, adding this term as HP_0031817. We will add the annotation shortly.
