### ISSUE TITLE
decreased proinsulin processing

### ISSUE THREAD

**Issue by slaulederkind** [obophenotype/human-phenotype-ontology#3575]
_For new term requests, please provide us with the following information:_
### 1. Preferred term label

decreased proinsulin processing

### 2. Synonyms

proinsulin processing deficiency

### 3. Textual definition (should be understandable even for non-specialists, please include a PubMed ID for relevant articles providing additional information about the suggestion)

A decrease in the amount of proinsulin converted to insulin.

### 4. Parent term (use [HPO Browser](http://compbio.charite.de/hpoweb/showterm?id=HP:0000118) or [OLS](http://www.ebi.ac.uk/ols/ontologies/hp))

Beta-cell dysfunction (HP:0006279)

### 5. Which diseases are characterized by this term ? (e.g. Orphanet- or OMIM-id)

OMIM:106210; ANIRIDIA 1

### 6. Your nano-attribution (ORCID-id or label, e.g. _HPO:probinson_ (organization:name))

RGD:gthayman

**Comment by pnrobinson** [comment]
Thanks @slaulederkind -- do you have references for how this is measured? "proinsulin processing deficiency" is an inference, but would it be better to have a term for proinsulin:insulin ratio or something like that which is closer to the entity that is actually observed?

**Comment by slaulederkind** [comment]
PMID:19034419 Proinsulin and insulin were both measured by RIA.  A ratio was reported as well as individual plasma concentrations.

**Comment by pnrobinson** [comment]
OK thanks, I will create a term using this paper as a model.
