### ISSUE TITLE
need superclass for abnormal lab value

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#3576]
There are a lot of open term requests that are for the presence of a xenobiotic in the blood or urine. We need a new superclass to group these terms, such as 'Abnormal presence of xenobiotic'

Synonym: Abnormal lab value

Could we discuss what the superclass should be named?

Related ticket: #3421

**Comment by nicolevasilevsky** [comment]
See https://en.wikipedia.org/wiki/Xenobiotic

**Comment by pnrobinson** [comment]
What about "Presence of xenobiotic" ?

**Comment by LCCarmody** [comment]
The only synonym I could find for xenobiotic is 'exobiotic'.  That said: 'endobiotic' is naturally occurring...but that may be a way to classify changes in metabolomic homeostasis?  Just a thought.

**Comment by pnrobinson** [comment]
Adding term as:
HP_0031838
Presence of xeonobiotic
Def: Presence of a chemical substance found within an individual that is not naturally produced or expected to be present in human tissues or bodily fluids.
Comment: The presence of a xenobiotic in body tissues or fluids can be the result of ingestion of or exposure to substantances such as drugs, environmental pollutants, food additives, hydrocarbons, and pesticides.
