### ISSUE TITLE
Decreased serum zinc

### ISSUE THREAD

**Issue by slaulederkind** [obophenotype/human-phenotype-ontology#3577]
_For new term requests, please provide us with the following information:_
### 1. Preferred term label

Decreased serum zinc

### 2. Synonyms

Hypozincemia

### 3. Textual definition (should be understandable even for non-specialists, please include a PubMed ID for relevant articles providing additional information about the suggestion)

An increased concentration of zinc in the blood. PMID:16518702

### 4. Parent term (use [HPO Browser](http://compbio.charite.de/hpoweb/showterm?id=HP:0000118) or [OLS](http://www.ebi.ac.uk/ols/ontologies/hp))

Abnormality of zinc homeostasis (HP:0008277)

### 5. Which diseases are characterized by this term ? (e.g. Orphanet- or OMIM-id)

OMIM:125853 combined with OMIM:108725

### 6. Your nano-attribution (ORCID-id or label, e.g. _HPO:probinson_ (organization:name))

RGD:gthayman

**Comment by pnrobinson** [comment]
Adding as HP_0031831
