### ISSUE TITLE
Abnormal superoxide dismutase activity

### ISSUE THREAD

**Issue by slaulederkind** [obophenotype/human-phenotype-ontology#3578]
_For new term requests, please provide us with the following information:_
### 1. Preferred term label

1. Abnormal superoxide dismutase activity
2. Increased superoxide dismutase activity
3. Decreased superoxide dismutase activity

### 2. Synonyms

1. Abnormal superoxide:superoxide oxidoreductase activity 
2. Increased superoxide:superoxide oxidoreductase activity 
3. Decreased superoxide:superoxide oxidoreductase activity 

### 3. Textual definition (should be understandable even for non-specialists, please include a PubMed ID for relevant articles providing additional information about the suggestion)

1. An abnormal level of catalysis of the reaction: 2 superoxide + 2 H+ = O2 + hydrogen peroxide.
2. Increased catalysis of the reaction: 2 superoxide + 2 H+ = O2 + hydrogen peroxide.
3. Decreased catalysis of the reaction: 2 superoxide + 2 H+ = O2 + hydrogen peroxide.
PMID:18349110 

### 4. Parent term (use [HPO Browser](http://compbio.charite.de/hpoweb/showterm?id=HP:0000118) or [OLS](http://www.ebi.ac.uk/ols/ontologies/hp))

1. Abnormal enzyme/coenzyme activity (HP:0012379) and Abnormality of superoxide metabolism (HP:0004358)
2. Abnormal superoxide dismutase activity (new term)
3. Abnormal superoxide dismutase activity (new term)

### 5. Which diseases are characterized by this term ? (e.g. Orphanet- or OMIM-id)

OMIM:125853 

### 6. Your nano-attribution (ORCID-id or label, e.g. _HPO:probinson_ (organization:name))

RGD:gthayman

**Comment by pnrobinson** [comment]
Thanks! Added terms as HP_0031835 (Abn) and the two subsequent ids.

**Comment by pnrobinson** [comment]
I will add this as an xref: PMID:25276767
