### ISSUE TITLE
NTR: hippocampal atrophy

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#3579]
_For new term requests, please provide us with the following information:_
### 1. Preferred term label
Hippocampal atrophy

### 2. Synonyms
- Atrophy of the hippocampus
- Degeneration of the hippocampus

### 3. Textual definition (should be understandable even for non-specialists, please include a PubMed ID for relevant articles providing additional information about the suggestion)
Partial or complete wasting (loss) of hippocampus tissue that was once present.

### 4. Parent term (use [HPO Browser](http://compbio.charite.de/hpoweb/showterm?id=HP:0000118) or [OLS](http://www.ebi.ac.uk/ols/ontologies/hp))
HP_0012444 'Brain atrophy'

### 5. Which diseases are characterized by this term ? (e.g. Orphanet- or OMIM-id)
MONDO_0021081 anti-NMDA receptor encephalitis

### 6. Your nano-attribution (ORCID-id or label, e.g. _HPO:probinson_ (organization:name))
https://orcid.org/0000-0001-5208-3432

### 7. Logical def:
'has part' some 
    (atrophied
     and ('inheres in' some 'hippocampal formation')
     and ('has modifier' some abnormal))

**Comment by pnrobinson** [comment]
Looks good to go but could we also add Abnormal morphology of the hippocampus as a parent term @nicolevasilevsky

**Comment by nicolevasilevsky** [comment]
added new classes:
'Abnormal morphology of the hippocampus'
'Hippocampal atrophy'
