### ISSUE TITLE
fractures of the femur

### ISSUE THREAD

**Issue by slaulederkind** [obophenotype/human-phenotype-ontology#3580]
_For new term requests, please provide us with the following information:_
### 1. Preferred term label

Fractures of the femur

### 2. Synonyms

fractured thigh bone; fractured femoral bone

### 3. Textual definition (should be understandable even for non-specialists, please include a PubMed ID for relevant articles providing additional information about the suggestion)

An increased tendency to fractures of the femur.  PMID:22948905

### 4. Parent term (use [HPO Browser](http://compbio.charite.de/hpoweb/showterm?id=HP:0000118) or [OLS](http://www.ebi.ac.uk/ols/ontologies/hp))

Fractures of the long bones (HP:0003084)

### 6. Your nano-attribution (ORCID-id or label, e.g. _HPO:probinson_ (organization:name))

RGD:gthayman

**Comment by pnrobinson** [comment]
Note that PMID:22948905 is referring to a population assocation for increased risk of femur fractures, but it is not the case that any one individual has multiple femur fractures in this study. 
I think it is therefore more appropriate to make a term called Femur fracture. (HP_0031846)
