### ISSUE TITLE
UMLS concepts to be mapped

### ISSUE THREAD

**Issue by cmungall** [obophenotype/human-phenotype-ontology#3581]
HP does not have xrefs for the following UMLS IDs. 

```
UMLS:C0001344   pharyngitis
UMLS:C0008684   gingivitis
UMLS:C0013369   diarrhea
UMLS:C0013882   elephantiasis
UMLS:C0021845   intestinal perforation
UMLS:C0024291   hemophagocytic lymphohistiocytosis
UMLS:C0024517   major depressive disorder
UMLS:C0027947   neutropenia
UMLS:C0029630   heart conduction disease
UMLS:C0031345   pharyngitis
UMLS:C0031350   pharyngitis
UMLS:C0038984   sweat
UMLS:C0086768   pancreatic cholera
UMLS:C0152249   acne
UMLS:C0154319   dementia
UMLS:C0154409   major depressive disorder
UMLS:C0155020   blindness
UMLS:C0155824   pharyngitis
UMLS:C0155937   gingivitis
UMLS:C0158157   joint effusion
UMLS:C0158670   Congenital lip pit
UMLS:C0221280   Elliptocyte
UMLS:C0231218   malaise
UMLS:C0232286   precordial pain
UMLS:C0232493   epigastric pain
UMLS:C0236033   muscle hypertrophy
UMLS:C0237314   Heart arrhythmia
UMLS:C0239571   fetor hepaticus
UMLS:C0239575   remittent fever
UMLS:C0332575   erythema
UMLS:C0424767   Continuous fever
UMLS:C0751226   recurrent hypersomnia
UMLS:C0853089   self-injury
UMLS:C0856449   acid reflux
UMLS:C0865142   toxic thyroid adenoma
UMLS:C0877717   burning mouth
UMLS:C1510416   coffee ground vomiting
UMLS:C2936755   macroglobulinemia
```

These all came from symptoms queries in wikidata:

```
SELECT ?dX ?sX ?sN WHERE {?d <http://www.wikidata.org/prop/direct/P780> ?s . ?d <http://www.wikidata.org/prop/direct/P699> ?dX . ?s <http://www.wikidata.org/prop/direct/P2892> ?sX . ?s <http://www.w3.org/2000/01/rdf-schema#label> ?sN . FILTER (LANG(?sN) = "en")}
```

I am happy to do further analysis on these. Some will be NTRs, some will be xrefs for existing terms

E.g. my list contains

UMLS:C0013369   diarrhea

this comes from https://www.wikidata.org/wiki/Q2447562 (balantidiasis)
which links to https://www.wikidata.org/wiki/Q40878 (diarrhea) under 'symptoms'
wikidata links this to [UMLS:C0013369](https://ncim-stage.nci.nih.gov/ncimbrowser/ConceptReport.jsp?dictionary=NCI%20Metathesaurus&code=C0013369)
which is a disease, not a symptom/finding/phenotype

The HP has:

```
id: HP:0002014
name: Diarrhea
...
xref: UMLS:C0011991
```

this is actually correct, because this is the sign/symptom:

https://ncim-stage.nci.nih.gov/ncimbrowser/ConceptReport.jsp?dictionary=NCI%20Metathesaurus&code=C0011991

so in this case wikidata is wrong, or at least conflating the disease and the symptom here.

If you like you can close this ticket until I have further filtered the list to exclude these, I just didn't want to lose track of my work so far

**Comment by cmungall** [comment]
OK, I further filtered the list, remove UMLS IDs that map to a MONDO ID

ignore the list above, this is a better one:

```
UMLS:C0038984   sweat <-- consider new superclass of HP:0025278  and HP:0025277
UMLS:C0158670   Congenital lip pit
UMLS:C0221280   Elliptocyte
UMLS:C0231218   malaise
UMLS:C0232286   precordial pain
UMLS:C0232493   epigastric pain
UMLS:C0237314   Heart arrhythmia
UMLS:C0239571   fetor hepaticus
UMLS:C0239575   remittent fever
UMLS:C0332575   erythema
UMLS:C0424767   Continuous fever
UMLS:C0853089   self-injury
UMLS:C0856449   acid reflux
UMLS:C0865142   toxic thyroid adenoma
UMLS:C0877717   burning mouth
UMLS:C1510416   coffee ground vomiting
```

**Comment by cmungall** [comment]
I note that Arrhythmia has multiple UMLS xrefs - but none to C0237314

```
id: HP:0011675
name: Arrhythmia
namespace: human_phenotype
alt_id: HP:0001656
alt_id: HP:0001661
alt_id: HP:0001665
alt_id: HP:0001666
alt_id: HP:0001687
alt_id: HP:0001721
alt_id: HP:0004351
alt_id: HP:0005158
def: "Any cardiac rhythm other than the normal sinus rhythm. Such a rhythm may be either of sinus or ectopic origin and either regular or irregular. An arrhythmia may be due to a disturbance in impulse formation or conduction or both." [DDD:dbrown, pmid:19063792]
synonym: "Abnormal heart rate" EXACT layperson []
synonym: "Abnormality of cardiac conduction" EXACT []
synonym: "Arrhythmias" EXACT []
synonym: "Cardiac arrhythmia" EXACT []
synonym: "Cardiac arrhythmias" EXACT []
synonym: "Cardiac conduction abnormalities" EXACT []
synonym: "Cardiac conduction defects" EXACT []
synonym: "Cardiac rhythm disturbances" EXACT []
synonym: "Heart rhythm disorders" EXACT layperson []
synonym: "Irregular heart beat" EXACT layperson []
synonym: "Irregular heartbeat" EXACT layperson []
xref: MSH:C562490
xref: MSH:D001145
xref: SNOMEDCT_US:102594003
xref: SNOMEDCT_US:44808001
xref: SNOMEDCT_US:698247007
xref: UMLS:C0003811
xref: UMLS:C0264886
xref: UMLS:C0522055
xref: UMLS:C0855329
xref: UMLS:C1832603
xref: UMLS:C1842820
is_a: HP:0030956  ! Abnormality of cardiovascular system electrophysiology
```

**Comment by drseb** [comment]
Note that the UMLS xrefs are derived from (and have been sent to me by) the UMLS.

**Comment by drseb** [comment]
i.e. Oliver has sent them to me

**Comment by pnrobinson** [comment]
@drseb @cmungall -- what is our preferred procedure for mapping these UMLS terms? Shouldn't we just report this to the UMLS team?

**Comment by pnrobinson** [comment]
- [ ] UMLS:C0038984   sweat <-- consider new superclass of HP:0025278  and HP:0025277
- [ ]  UMLS:C0158670   Congenital lip pit
- [ ]  UMLS:C0221280   Elliptocyte
- [ ] UMLS:C0231218   malaise
- [ ] UMLS:C0232286   precordial pain
- [ ] UMLS:C0232493   epigastric pain
- [ ] UMLS:C0237314   Heart arrhythmia
- [ ] UMLS:C0239571   fetor hepaticus
- [ ] UMLS:C0239575   remittent fever
- [ ] UMLS:C0332575   erythema
- [ ] UMLS:C0424767   Continuous fever
- [ ] UMLS:C0853089   self-injury
- [ ] UMLS:C0856449   acid reflux
- [ ] UMLS:C0865142   toxic thyroid adenoma
- [ ] UMLS:C0877717   burning mouth
- [ ] UMLS:C1510416   coffee ground vomiting

**Comment by pnrobinson** [comment]
UMLS:C0038984 sweat - not an abnormal phenotype, we cannot map this
lip pit is congenital https://hpo.jax.org/app/browse/term/HP:0100267
we have elliptocytosis (https://hpo.jax.org/app/browse/term/HP:0004445), I will add this as RELATED
it is hard to define malaise exactly, but I think it is a RELATED for fatigue.
Adding precordial pain
heart arrhythmia is redundant.

**Comment by pnrobinson** [comment]
epigastric pain https://hpo.jax.org/app/browse/term/HP:0410019
we have the fever terms, not sure these are needed
https://hpo.jax.org/app/browse/term/HP:0010783 Erythema
will add self-injury as synonym to https://hpo.jax.org/app/browse/term/HP:0100716
acid reflux https://hpo.jax.org/app/browse/term/HP:0002020
toxic thyroid ademona might be better as MONDO
will add Burning mouth
added coffee ground emesis.

**Comment by pnrobinson** [comment]
All done. I am assuming that we will leave it to UMLS to do the mapping.
