### ISSUE TITLE
Loinc 32093-7:  "Methadone [Presence] in Unspecified specimen"

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#3588]
Suggest creating a new child term of HP:0031838 Presence of xenobiotic for Loinc 32093-7 [Methadone [Presence] in Unspecified specimen]
New term label:
- Unspecified specimen xenobiotic 
-- Positive unspecified specimen methadone test
New term comment (if any):
Your biocurator ID for loinc2hpo (if desired): HPO:nvasilevsky

**Comment by pnrobinson** [comment]
I think as a general rule we cannot annotate the Unspecific specimen entries in Loinc -- this does not match the logic of the HPO, since we do not really know what is being measured. @kingmanzhang @nicolevasilevsky @jpgourdine  -- let's mark Unspecified terms such as this "Unannotatable" in the annotation software!

**Comment by kingmanzhang** [comment]
I am going to write a terminal script to put all such tests into such a group. I will also implement this feature in the software so you can do this as well.

**Comment by kingmanzhang** [comment]
@nicolevasilevsky @nicolevasilevsky This feature has been implemented. All LOINC tests with "unspecified specimen" were now in a separate list and colored plum. Try it if you can compile the develop branch.

**Comment by kingmanzhang** [comment]
@nicolevasilevsky I removed the "unspecified specimen" loinc codes that you added to the "unable_to_annotate" list and moved them into the new list "unspecified specimen". The original list is intended to mark codes that are difficult to annotate (but someone else might be able to!).

**Comment by nicolevasilevsky** [comment]
Ok- thanks!
