### ISSUE TITLE
Loinc 43595-8:  "Methadone [Presence] in Meconium"

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#3591]
Suggest creating a new term for Loinc: 43595-8 [Methadone [Presence] in Meconium] 
New term label:
Parent: Presence of xenobiotic
NTRs:
- Meconium xenobiotic
-- Positive meconium methadone test
New term comment (if any):
Your biocurator ID for loinc2hpo (if desired): HPO:nvasilevsky

**Comment by pnrobinson** [comment]
@nicolevasilevsky  sounds good!
