### ISSUE TITLE
Loinc 18370-7:  "Nitrite [Mass/volume] in Blood"

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#3593]
Suggest creating a new term for Loinc: 18370-7 [Nitrite [Mass/volume] in Blood] 

Parent:  'Abnormality of metabolism/homeostasis'
NTR: 
-> Abnormality of nitrite homeostasis
--> Presence of nitrites in the blood
-->Presence of nitrites in dialysis fluid
--> Presence of nitrites in unspecified specimen

Your biocurator ID for loinc2hpo (if desired): HPO:nvasilevsky

**Comment by pnrobinson** [comment]
I cannot find any references to nitritemia. I suggest we close this until we get some actual data with this LOINC code.
