### ISSUE TITLE
Loinc 12535-1:  "Amyl nitrite [Presence] in Blood"

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#3594]
Suggest creating a new term for Loinc: 12535-1 [Amyl nitrite [Presence] in Blood] 
New term label:

Parent class: Presence of nitrite in blood (see issue #3593)
-> Presence of amyl nitrite in blood
--> Presence of amyl nitrite in serum or plasma

New term comment (if any): Not sure if we want the more granular class, or we should just annotate with the blood class

Your biocurator ID for loinc2hpo (if desired): HPO:nvasilevsky

**Comment by pnrobinson** [comment]
Amyl nitrite is not a naturally occuring metabolite, but it is a medication. 
see https://en.wikipedia.org/wiki/Amyl_nitrite
I think this is probably uncommonly measured and I would suggest we mark this is not annotatable for now @kingmanzhang @nicolevasilevsky
