### ISSUE TITLE
Loinc 19161-9:  "Urobilinogen [Units/volume] in Urine by Test strip"

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#3596]
Suggest creating a new term for Loinc: 19161-9 [Urobilinogen [Units/volume] in Urine by Test strip] 

New term label: 
**parent**: HP_0003110 'Abnormality of urine homeostasis'
**new term requests**:
-Presence of urobilinogen in urine
def: The presence of urobilinogen in the urine.

--Presence of bilirubin and urobilingen in urine
def: The presence of bilirubin and urobilinogen in the urine.

**Note**:
They also detect urobilinogen in the stool and body fluid - need new term for these too. Should these be children of 'Abnormality of metabolism/homeostasis'? Should we create new classes like 'Abnormality of stool metabolites' and 'Abnormality of body fluid metabolites' (or something like that?)

For LOINC annotations - search on Urobilinogen

Your biocurator ID for loinc2hpo (if desired): HPO:nvasilevsky

**Comment by pnrobinson** [comment]
I think we should make subclasses for the various fluids that are being tested for metabolites. Can we generate a list from the LOINC codes? For now, I made a term Increased urine urobilinogen HP_0031890

**Comment by nicolevasilevsky** [comment]
Yes, there are a lot of terms like this. @kingmanzhang is it possible to automatically generate a list of these types of terms? Or I can review all the LOINC codes and create one manually.

**Comment by nicolevasilevsky** [comment]
@pnrobinson and @kingmanzhang, if there are bundled terms, like Presence of bilirubin and urobilingen in urine, could we annotate it with two HPO terms?

**Comment by kingmanzhang** [comment]
@nicolevasilevsky is it possible to automatically generate a list of these types of terms?
--Not now. Searching for the metabolite for LOINC codes might be the way to go. 

could we annotate it with two HPO terms
--Not now. Currently we assume each outcome of LOINC maps to a unique HPO term.

**Comment by nicolevasilevsky** [comment]
Ok, thanks @kingmanzhang.

@pnrobinson I can work on creating a list of the various metabolites that are measured in the LOINC codes.

**Comment by pnrobinson** [comment]
I do not understand why you are syaing this is bundled, @nicolevasilevsky , isnt it just urobilinogen for this LOINC code?

**Comment by nicolevasilevsky** [comment]
above you mentioned there is a code that is the Presence of bilirubin and urobilingen in urine, that is why I was asking. I think I've come across other bundled terms like this too. I'll add some more examples as I come across them.

**Comment by kingmanzhang** [comment]
@pnrobinson I think I also came across a LOINC code for non-HDL measurement. Annotating the test requires either HPO terms on (LDL + IDL) or combining HPO terms on LDL and HPO terms on IDL. I vote for the latter way, but haven't got a clear idea on this issue.

**Comment by pnrobinson** [comment]
Sorry, this is simply Increased urine urobilinogen
