### ISSUE TITLE
Redundant definitions: HP_0001471 and HP_0001743

### ISSUE THREAD

**Issue by matentzn** [obophenotype/human-phenotype-ontology#3597]
There are two (redundant) definitions for the following concepts:

***HP_0001471***
Definition 1:

```
'has part' some 
    (hypoplastic
     and ('inheres in part of' some 'muscle of pelvis')
     and ('has modifier' some abnormal))
```

Definition 2:

```
'has part' some 
    (aplastic/hypoplastic
     and ('inheres in part of' some 'muscle of pelvis')
     and ('has modifier' some abnormal))
```

Since aplastic/hypoplastic is a superclass of hypoplastic, Definition 1 implies Definition 2.

***HP_0001743***

Definition 1:

```
'has part' some 
    (quality
     and ('inheres in part of' some spleen)
     and ('has modifier' some abnormal))
```

Definition 2:

```
'has part' some 
    ('increased amount'
     and ('inheres in' some 
        (abscess
         and ('part of' some spleen)))
     and ('has modifier' some abnormal))
```
 
Definition 2 implies Definition 1 (redundant). Explanation: 

![screen shot 2018-05-09 at 10 40 18](https://user-images.githubusercontent.com/7070631/39807908-76de6592-5375-11e8-9a13-8ecebb082d75.png)

Perhaps the implied definitions should be removed?

**Comment by pnrobinson** [comment]
Thanks for pointing this out. I have corrected both errors.
