### ISSUE TITLE
Loinc 2161-8:  "Creatinine [Mass/volume] in Urine"

### ISSUE THREAD

**Issue by kingmanzhang** [obophenotype/human-phenotype-ontology#3598]
Suggest creating a new term for Loinc: 2161-8 [Creatinine [Mass/volume] in Urine] 
New term label: Abnormal creatinine concentration in urine (and child terms)
New term comment (if any): There are many similar LOINC tests on the same parameter in a wide range of tissues. Creating a term for each is the most straighford way, but is it the best?
Your biocurator ID for loinc2hpo (if desired): JGM:azhang

**Comment by pnrobinson** [comment]
@cmungall @mellybelly @kingmanzhang 
This is an interesting case because a spot check of creatinine in the urine is not really all that useful and cannot be used to diagnose kidney issues AFAIK. There is some utility for a 24h urine creatinine or a urine creatinine to albumin ratio. 
I doubt that this test is used very often, and think we need to come up with some way of marking tests that are not reliable enough to call an abnormality (i.e., to reliably call an HPO term based on the result of the test).

**Comment by kingmanzhang** [comment]
@cmungall once asked whether we would like a probability number associated with each test. I am wondering whether we need to pursue this idea.

**Comment by nicolevasilevsky** [comment]
@kingmanzhang what do you mean by probability number?

**Comment by nicolevasilevsky** [comment]
Ah, got it. Thanks for the clarification.

**Comment by pnrobinson** [comment]
This is not the case actually--you do not need to have eacy of the time points be positive to get a diagnosis of impaired glucose tolerance. Physicians will look at the pattern of blood glucose and then determine what is going on. It is not really possible to make the call from just the 0.5h test, for example. See 
https://www.medicinenet.com/glucose_tolerance_test/article.htm#what_about_glucose_tolerance_testing_during_pregnancy
Probably we need to have some post-processing of the values of the individual components. I think that this would be a really nice example and something that we can flesh out -- essentially, the library would first collect all of the values from any glucose tolerance test (GTT) and code them as hyperglycemia or not. The second stage would then take these values and determine whether there is impaired glucose tolerance according to appropriate rules. This is not really easy to do but it would be really important.

**Comment by pnrobinson** [comment]
@kingmanzhang I think that we need to mark this term as not able to annotate!
