### ISSUE TITLE
Loinc 13969-1:  "Creatine kinase.MB [Mass/volume] in Serum or Plasma"

### ISSUE THREAD

**Issue by kingmanzhang** [obophenotype/human-phenotype-ontology#3599]
Suggest creating a new child term of HP:0040081 [Abnormal levels of creatine kinase in blood] for Loinc 13969-1 [Creatine kinase.MB [Mass/volume] in Serum or Plasma]
New term label: Reduced serum creatine phosphokinase
New term comment (if any): see http://clinchem.aaccjnls.org/content/44/5/905
Your biocurator ID for loinc2hpo (if desired): JGM:azhang

**Comment by pnrobinson** [comment]
also see this for isoforms
http://clinchem.aaccjnls.org/content/35/1/7.long

**Comment by pnrobinson** [comment]
done
