### ISSUE TITLE
Loinc 2705-2:  "Oxygen [Partial pressure] in Venous blood"

### ISSUE THREAD

**Issue by kingmanzhang** [obophenotype/human-phenotype-ontology#3601]
Suggest creating a new child term of HP:0012415 [Abnormal blood gas level] for Loinc 2705-2 [Oxygen [Partial pressure] in Venous blood]
New term label: Abnormal blood O2 level, Abnormal blood CO2 level
New term comment (if any): adjust current children accordingly
Your biocurator ID for loinc2hpo (if desired): JGM:azhang

**Comment by pnrobinson** [comment]
I do not think we should annotate this now. Venous partial pressure interpretation is context dependent and I am not sure this is something we can do in isolation
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4666443/

**Comment by kingmanzhang** [comment]
done
