### ISSUE TITLE
NTR: Presence of NMDAR antibody in the CSF or blood

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#3602]
**Parent:** HP_0010701 'Abnormal immunoglobulin level'
**NTR: Presence of NMDAR antibody in CSF**
**Syn:** Presence of anti-NMDAR antibody in CSF
**Syn:** Presence of anti-NMDAR antibody in cerebrospinal fluid
**Syn:** Presence of anti-N-methyl-D-aspartate Receptor antibody in CSF
**Def:** Detection of anti-N-methyl-D-aspartate Receptor (NMDAR) antibody in the cerebrospinal fluid.
PMID:29651625

**Parent:** HP_0010702 'Increased antibody level in blood'
**NTR: Presence of NMDAR antibody in the blood**
**Syn:** Presence of anti-NMDAR antibody in blood
**Syn:** Presence of anti-N-methyl-D-aspartate Receptor antibody in blood
**Def:** Detection of anti-N-methyl-D-aspartate Receptor (NMDAR) antibody in the blood.
PMID:29651625

For common disease curation practice round - curation of **MONDO_0021081 anti-NMDA receptor encephalitis**

**Comment by nicolevasilevsky** [comment]
or maybe the parent class should be HP_0011111 'Abnormality of immune serum protein physiology'?

**Comment by pnrobinson** [comment]
We probably need a term like CSF Antibody positivity -- let's try to search for the best name!

**Comment by pnrobinson** [comment]
adding this with new CSF autoantibody term
