### ISSUE TITLE
Loinc 29959-4:  "Ganglioside GM1 IgG Ab [Mass/volume] in Serum by Immunoassay"

### ISSUE THREAD

**Issue by jpgourdine** [obophenotype/human-phenotype-ontology#3604]
Suggest creating a new term for Loinc: 29959-4 [Ganglioside GM1 IgG Ab [Mass/volume] in Serum by Immunoassay] 
New term label:Anti-ganglioside GM1 IgG antibody positivity
New term comment (if any):
Your biocurator ID for loinc2hpo (if desired): OHSU:JP

**Comment by jpgourdine** [comment]
I wonder if we should not be as this granular level on the antibodies types (IgG, IgM, etc.) and the glycolipids types (GM1, GM1b, etc.) as the medical indication in these cases are **"Anti-ganglioside antibody positivity"** for disease like Guillain-Barre syndrome disorders look [here](https://s.details.loinc.org/LOINC/29959-4.html?sections=Comprehensive). Maybe, should we regroup in this more generic term? @pnrobinson

**Comment by pnrobinson** [comment]
I agree with your assessment that we do not need to include the various antibody types for the HPO term, which should be just "Anti-ganglioside antibody positivity". If we ever need more subtypes in the future, we can go back and add them.

**Comment by LCCarmody** [comment]
Changed term to Anti-ganglioside antibody positivity.
