### ISSUE TITLE
NTR: Increased cotinine level

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#3605]
NTR: Increased cotinine level
Parent: HP_0004364 HP_0031840 'Urine xenobiotic'
Def: Increased concentration of cotinine in the urine.
Comment: This is used as a measure for exposure to tobacco smoke.
Logical def:

'has part' some 
('increased amount' and ('inheres in' some 
((−)-cotinine and ('part of' some urine))) and ('has modifier' some abnormal))

Need to MIREOT: CHEBI:68641  (−)-cotinine

@pnrobinson I can add this if it looks okay.

**Comment by nicolevasilevsky** [comment]
Or should this be a child of Abnormality of HP_0004364 nitrogen compound homeostasis? But it will be inferred to be a child of this, via the logical definition.

**Comment by pnrobinson** [comment]
This is a good reference about cotinine - https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3467453/
TODO--write a short comment about what cotinine is and why it is measured.
I think this should probably be a child of urine xenobiotic -- for now, I would say let us put the xenobiotics in their own categories and not assert additional subclass relations (we can always get this via reasoning on the basis of the definitions if we need it).

**Comment by nicolevasilevsky** [comment]
@drseb could you please MIREOT: CHEBI:68641 (−)-cotinine

**Comment by drseb** [comment]
mireot done
