### ISSUE TITLE
Loinc 18262-6:  "Cholesterol in LDL [Mass/volume] in Serum or Plasma by Direct assay"

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#3608]
Suggest creating a new child term of HP:0008158 [Hyperapobetalipoproteinemia] for Loinc 18262-6 [Cholesterol in LDL [Mass/volume] in Serum or Plasma by Direct assay]
New term label: Abnormal LDL level

New term comment (if any):
Need increased and decreased terms too

Your biocurator ID for loinc2hpo (if desired): HPO:nvasilevsky

**Comment by pnrobinson** [comment]
see https://github.com/TheJacksonLaboratory/loinc2hpoAnnotation/issues/14
