### ISSUE TITLE
Loinc 13458-5:  "Cholesterol in VLDL [Mass/volume] in Serum or Plasma by calculation"

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#3609]
Suggest creating a new sibling term of HP:0031243 [Decreased circulating very-low-density lipoprotein levels] for Loinc 13458-5 [Cholesterol in VLDL [Mass/volume] in Serum or Plasma by calculation]
New term label: Increased circulating VLDL

New term comment (if any):
Add parent class - Abnormal circulating VLDL

Your biocurator ID for loinc2hpo (if desired): HPO:nvasilevsky

**Comment by pnrobinson** [comment]
see https://github.com/TheJacksonLaboratory/loinc2hpoAnnotation/issues/14
