### ISSUE TITLE
Loinc 11054-4:  "Cholesterol in LDL/Cholesterol in HDL [Mass Ratio] in Serum or Plasma"

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#3610]
Suggest creating a new term for Loinc: 11054-4 [Cholesterol in LDL/Cholesterol in HDL [Mass Ratio] in Serum or Plasma] 
New term label:
Abnormal circulating LDL/HDL ratio

New term comment (if any):
Add increased and decreased terms as well (if that makes sense)

Your biocurator ID for loinc2hpo (if desired): HPO:nvasilevsky

**Comment by pnrobinson** [comment]
see https://github.com/TheJacksonLaboratory/loinc2hpoAnnotation/issues/14
