### ISSUE TITLE
Loinc 13459-3:  "Cholesterol in LDL/Cholesterol.total [Mass Ratio] in Serum or Plasma"

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#3611]
Suggest creating a new term for Loinc: 13459-3 [Cholesterol in LDL/Cholesterol.total [Mass Ratio] in Serum or Plasma] 

New term label: Abnormal circulating LDL/total cholesterol ratio

New term comment (if any):
need increased and decreased terms as well

Your biocurator ID for loinc2hpo (if desired): HPO:nvasilevsky

**Comment by pnrobinson** [comment]
see https://github.com/TheJacksonLaboratory/loinc2hpoAnnotation/issues/14
