### ISSUE TITLE
Loinc 3298-7:  "Acetaminophen [Mass/volume] in Serum or Plasma"

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#3613]
Suggest creating a new term for Loinc: 3298-7 [Acetaminophen [Mass/volume] in Serum or Plasma] 
New term label:
Positive blood acetaminophen test

Child of Presence of xenobiotic 

Your biocurator ID for loinc2hpo (if desired): HPO:nvasilevsky

**Comment by pnrobinson** [comment]
@nicolevasilevsky  looks good!
