### ISSUE TITLE
Need new subclasses for 'Abnormality of nitrogen compound homeostasis'

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#3616]
**Parent:** 'Abnormality of nitrogen compound homeostasis'

**Child terms:**
-Abnormal level of ammonia in blood
--HP_0001987 Hyperammonemia
---Increased ammonia in plasma
---Increased ammonia in serum
--HP_0100493 Hypoammonemia)
---Decreased ammonia in plasma
---Decreased ammonia in serum

-Abnormal level of ammonia in body fluid
--Increased ammonia in body fluid
--Decreased ammonia in body fluid

-Abnormal level of ammonia in tissue
--Increased ammonia in tissue
--Decreased ammonia in tissue

-Abnormal level of ammonia in CSF
--Increased ammonia in CSF
--Decreased ammonia in CSF

-Abnormal level of ammonia in urine
--Increased ammonia in urine
--Decreased ammonia in urine

-Abnormal level of ammonia in unspecified specimen
--Increased ammonia in unspecified specimen
--Decreased ammonia in unspecified specimen

-Abnormal level of ammonia in dialysis fluid
--Increased ammonia in dialysis fluid
--Decreased ammonia in dialysis fluid

**For LOINC annotations**

**Comment by pnrobinson** [comment]
Note that it is immaterial if you measure ammonia in plasma or serum, and therefore there is no need for these classes:
---Increased ammonia in plasma
---Increased ammonia in serum
(etc.)

**Comment by nicolevasilevsky** [comment]
Ok, sounds good!
Is it okay to add the other terms? I can do so.

**Comment by pnrobinson** [comment]
In general, we probably cannot add terms for tissues other than blood, urine and CSF. For instance, having ammonia in dialysis fluid would be impossible for us to interpret with HPO. 
In this particular case, I do not think any of the other terms have a clinical interpretation that I know of, and I do not think we need to map them. Let us mark them "do not map" terms in the LOINC file.
