### ISSUE TITLE
NTRs: Abn metabolite measurements for LOINC

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#3619]
I started a google doc with a list of metabolites measured in LOINC and the location (ie blood, urine, etc.)

This is work in progress. Related to #3596

https://docs.google.com/document/d/1VCQbb-1J1atJ6mP_bXCt2nPHHAmvt5WesyMycncvA3w/edit

@pnrobinson let me know if this looks okay and if I am on the right track. I think there are going to be a lot of terms.

**Comment by pnrobinson** [comment]
@nicolevasilevsky thanks--I added some comments, it'd be great if you could make the terms

**Comment by nicolevasilevsky** [comment]
@drseb could you please MIREOT:
PR_000007749 glucose-6-phosphate 1-dehydrogenase

**Comment by nicolevasilevsky** [comment]
Note to self: added HP_0410176 'Abnormal glucose-6-phosphate dehydrogenase level' and children, need to add logical defs.

**Comment by drseb** [comment]
I mireoted the terms

**Comment by pnrobinson** [comment]
@nicolevasilevsky  Can we close this issue? I am not sure if there are any action items left?

**Comment by nicolevasilevsky** [comment]
yeah, I think we can close.
