### ISSUE TITLE
novel HPO term Serrated polyposis

### ISSUE THREAD

**Issue by Stefan-Aretz** [obophenotype/human-phenotype-ontology#3620]
_For new term requests, please provide us with the following information:_
### 1. Preferred term label
Serrated polyposis

### 2. Synonyms
serrated polyposis syndrome, hyperplastic polyposis, hyperplastic polyposis syndrome, Sessile serrated polyposis cancer syndrome

### 3. Textual definition (should be understandable even for non-specialists, please include a PubMed ID for relevant articles providing additional information about the suggestion)

A gastrointestinal polyposis syndrome characterised by the presence of multiple serrated polyps (hyperplastic polyps, sessile serrated adenomas, traditional serrated adenomas), in the colorectum

PMID: 27499922, PMID: 22654442, PMID: 21228663, PMID: 21660283 

### 4. Parent term (use [HPO Browser](http://compbio.charite.de/hpoweb/showterm?id=HP:0000118) or [OLS](http://www.ebi.ac.uk/ols/ontologies/hp))
superclasses "Neoplasm of the gastrointestinal tract" - "Neoplasm of the colon" / "Colorectal polyposis" / "Intestinal polyp" / "Large intestinal polyposis"

### 5. Which diseases are characterized by this term ? (e.g. Orphanet- or OMIM-id)
OMIM #617108, Sessile serrated polyposis cancer syndrome; 
ORPHA:157798, Hyperplastic polyposis syndrome

### 6. Your nano-attribution (ORCID-id or label, e.g. _HPO:probinson_ (organization:name))
0000-0002-5228-1890

**Comment by pnrobinson** [comment]
Hi!
We are in the process of integrating the HPO with the National Cancer Institute's thesaurus.
I am going to link this new HPO term with this NCI entry
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI_Thesaurus&version=18.04e&ns=ncit&code=C96470&key=1483568567&b=1&n=null
Please get back to me if this is not what you intended.
