### ISSUE TITLE
Downloadable gene file

### ISSUE THREAD

**Issue by GARDInfoCenter** [obophenotype/human-phenotype-ontology#3624]
@nicolevasilevsky @cmungall 

As discussed during our last call, GARD plans to add gene information to the GARD disease webpages. We would like a downloadable file of the following DisorderGeneAssociationType information for the diseases in HPO: Disease-causing germline muation(s) (loss of function) in, Disease-causing germline mutation(s) (gain of function) in, Disease-causing somatic mutation(s) in, and Part of a fusion gene in. It would also be helpful to have the gene location.  Could you provide this information?

Maria

**Comment by nicolevasilevsky** [comment]
@cmungall - can you answer this? I'm not sure of the answer.

**Comment by pnrobinson** [comment]
@cmungall This is something that we should do as a part of the MONDO project. Currently, there is no file that adequately does what Maria would like to see, although there is a lot of information out there that provides partial solutions. 
Probably however a good bit of this information is in biolink already, even if incomplete?

**Comment by cmungall** [comment]
Yes, biolink will give access to information already integrated in Monarch. We don't use the exact same relations as requested above (working on it, see https://github.com/monarch-initiative/dipper/issues/641)

API here: https://api.monarchinitiative.org/api/

You can use either `/disease/{id}/gene`, or to download in bulk use `/mart/disease/gene/NCBITaxon:9606`

**Comment by pnrobinson** [comment]
Closing this as Chris' answer seems to address the issue. Reopen if necessary.
