### ISSUE TITLE
Loinc 739-3:  "Metamyelocytes [#/volume] in Blood by Manual count"

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3625]
Suggest creating a new term for Loinc: 739-3 [Metamyelocytes [#/volume] in Blood by Manual count] 
New term label:
New term comment (if any):
Your biocurator ID for loinc2hpo (if desired): HPO:probinson

**Comment by pnrobinson** [comment]
See: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4355545/

it is necessary to recall the various forms of immature neutrophils that appear during granulopoiesis in the bone marrow. A 7-day mitotic stage (myeloblast → promyelocyte → myelocyte) is followed by a 7-day maturation stage (myelocyte → metamyelocyte → band cell → mature segmented neutrophil), whereupon mature neutrophils are held in storage pools before their entry into the circulation

**Comment by pnrobinson** [comment]
add terms for three kinds of immature neutrophils, see HP_0032237 etc.

**Comment by kingmanzhang** [comment]
done
