### ISSUE TITLE
Loinc 7795-8:  "Pappenheimer bodies [Presence] in Blood by Light microscopy"

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3627]
Suggest creating a new term for Loinc: 7795-8 [Pappenheimer bodies [Presence] in Blood by Light microscopy] 
New term label:
New term comment (if any):
Your biocurator ID for loinc2hpo (if desired): HPO:probinson

Check if this can be added as a synonym to siderocyte

**Comment by pnrobinson** [comment]
A cell containing Pappenheimer bodies is a siderocyte (https://en.wikipedia.org/wiki/Pappenheimer_bodies)

https://www.ncbi.nlm.nih.gov/pubmed/15054821
In 1945, Pappenheimer et al. described three pati-
ents whose red blood cells, after splenectomy, showed
inclusions when stained with Giemsa or Wright stain
[1]. They described these bodies as red–purple, usually
coccoid, and adjacent to the cell membrane, and they
demonstrated that the cells stained for iron with Prus-
sian blue stain.

**Comment by pnrobinson** [comment]
added as HP_0020081

**Comment by pnrobinson** [comment]
@kingmanzhang  this can be LOINCed

**Comment by kingmanzhang** [comment]
done
