### ISSUE TITLE
Loinc 17588-5:  "Sjogrens syndrome-B extractable nuclear IgG Ab [Presence] in Serum by Immunoassay"

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3634]
Suggest creating a new term for Loinc: 17588-5 [Sjogrens syndrome-B extractable nuclear IgG Ab [Presence] in Serum by Immunoassay] 
New term label:
New term comment (if any):
Your biocurator ID for loinc2hpo (if desired): HPO:probinson

**Comment by pnrobinson** [comment]
Therefore
Label: Anti-Ro/SSA antibody positivity
Def: The presence of autoantibodies (immunoglobulins) in the serum that react against the Ro/Sjogrens syndrome antigen.
Comment: Anti-Ro/SSA and anti-La/SSB are considered hallmarks of Sjogrens syndrome and are associated with systemic disease, but are also present in the sera of systemic lupus erythematodes patients. The most common antinuclear antibodies in Sjögren’s patients are those directed against the autoantigens Ro/SSA and La/SSB. The Ro/La particle is a protein-RNA complex formed by the association of the Ro60, and La/SSB proteins with small cytoplasmic RNA (hyRNA). Anti-Ro/SSA and anti-La/SSB antibodies are detected in 50 to 70 percent of primary Sjögren’s patients. Anti-Ro/SSA and anti-La/SSB antibodies are correlated with younger age at diagnosis, longer disease duration, more severe dysfunction of the exocrine glands, recurrent parotid gland enlargement and higher intensity of the lymphocytic infiltrates in the minor salivary glands. PMID:27431345

**Comment by pnrobinson** [comment]
Label: Anti-La/SSA antibody positivity
Def: The presence of autoantibodies (immunoglobulins) in the serum that react against the La/Sjogrens syndrome antigen.
Comment-same as above

**Comment by kingmanzhang** [comment]
done
