### ISSUE TITLE
Presence of xenobiotic children question

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#3636]
I'm adding several terms for methadone presence in various samples. 
I have added:
Gastric fluid xenobiotic
Hair xenobiotic
Stool xenobiotic
  -Meconium xenobiotic
(Blood xenobiotic) (already added)
  -Plasma/serum xenobiotic

My question is: should 'Meconium xenobiotic' be a child of stool xenobiotic? It would be sibling to Positive stool methadone test.  The same question goes for Plasma/serum xenobiotic.

@pnrobinson @nicolevasilevsky

**Comment by pnrobinson** [comment]
I would agree that making the meconium items be children of stool would be good for now!

**Comment by LCCarmody** [comment]
Okay.  Added and closed.
