### ISSUE TITLE
NTR: Abn ketone subclasses

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#3637]
**need new terms:** 
**parent:** HP_0001946 Ketosis
-Abnormal methyl propyl ketone level
-- Abnormal methyl propyl ketone level in blood
--- Increased methyl propyl ketone level in blood
--- Decreased methyl propyl ketone level in blood
-- Abnormal methyl propyl ketone level in urine
--- Increased methyl propyl ketone level in urine
--- Decreased methyl propyl ketone level in urine
**Need to MIREOT:** CHEBI:16472 pentan-2-one

**parent:** HP_0001946 Ketosis
-Abnormal methyl ethyl ketone level
-- Abnormal methyl ethyl ketone level in blood
--- Increased methyl ethyl ketone level in blood
--- Decreased methyl ethyl ketone level in blood
-- Abnormal methyl ethyl ketone level in urine
--- Increased methyl ethyl ketone level in urine
--- Decreased methyl ethyl ketone level in urine
-- Abnormal methyl ethyl ketone level in body fluid
--- Increased methyl ethyl ketone level in body fluid
--- Decreased methyl ethyl ketone level in body fluid
**Need to MIREOT:** CHEBI:22951 butanone

**parent:** HP_0001946 Ketosis
-Abnormal methyl amyl ketone level
-- Abnormal methyl amyl ketone level in blood
--- Increased methyl amyl ketone level in blood
--- Decreased methyl amyl ketone level in blood
-- Abnormal methyl amyl ketone level in urine
--- Increased methyl amyl ketone level in urine
--- Decreased methyl amyl ketone level in urine
**Need to MIREOT:** CHEBI:5672 heptan-2-one

**Comment by nicolevasilevsky** [comment]
There are a lot of LOINC codes with these specific ketones, do we want HPO classes for all of these?

In addition to those above, there these subtypes:
- Methyl isoamyl ketone (in blood in urine)
- Methyl butyl ketone (in blood and urine)
- Methyl isobutyl ketone (in blood, urine and air)
- Diisobutylketone (in blood and urine)
- phenylketone (in blood and urine)

**Comment by pnrobinson** [comment]
Let's hold off on these to do more research. I think that some of them are environmental exposures and not related to the ketone bodies that can be seen in catabolism or diabetes.
See for instance. https://www.osha.gov/dts/chemicalsampling/data/CH_235400.html

**Comment by nicolevasilevsky** [comment]
Ok - sounds good!

**Comment by drseb** [comment]
I mireoted the chebi-terms

**Comment by pnrobinson** [comment]
It is also the case that (afaik) there is no medically relevant "Decreased" for any of these ketones. I would actually suggest that we make terms only after we get some data that we cannot map. These seem absolutely super rare, I have never heard of them. I would suggest we close this issue unless we can find some medical relevance and a PMID or two....

**Comment by pnrobinson** [comment]
I cannot really find this and I never have heard of anyone using these in clinical practice. I would suggest we not annotate them for now, and if we start to get data with these tests, we can go back to them.
@kingmanzhang @nicolevasilevsky

**Comment by nicolevasilevsky** [comment]
sounds good! I'll mark these unable to annotate
