### ISSUE TITLE
Hi, how can I see how an ontology for epilepsies may be structured within the HPO? Thanks, Austin

### ISSUE THREAD

**Issue by LAustin1** [obophenotype/human-phenotype-ontology#3638]
_For new term requests, please provide us with the following information:_

**Comment by pnrobinson** [comment]
I am not sure I understand you question. Here is a link to the seizures subhierarchy of the HPO
https://hpo.jax.org/app/browse/term/HP:0001250
Can you specify what you goal is?

**Comment by LOURGHI** [comment]
Just click on the graphic review at the bottom  of epilepsy page ,here is the link 
http://compbio.charite.de/hpoweb/showterm?id=HP:0000118#id=HP:0001250
I hope we have answered your question
Halima.

**Comment by LAustin1** [comment]
Sorry, I just see now that it's above ^^
Thank you.
Austin

**Comment by pnrobinson** [comment]
Thanks for the input. Please contact us again if there are more questions.
