### ISSUE TITLE
Loinc 33801-2:  "E selectin [Mass/volume] in Serum or Plasma"

### ISSUE THREAD

**Issue by jpgourdine** [obophenotype/human-phenotype-ontology#3640]
Suggest creating a new term for Loinc: 33801-2 [E selectin [Mass/volume] in Serum or Plasma] 
New term label:Elevated E-selectin level
New term comment (if any):parent term Abnormality of circulating protein level (HP:0010876)
Your biocurator ID for loinc2hpo (if desired): OHSU:JP

**Comment by pnrobinson** [comment]
added as HP_0032240
