### ISSUE TITLE
Loinc 709-6:  "Blasts/100 leukocytes in Blood by Manual count"

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3644]
Suggest creating a new term for Loinc: 709-6 [Blasts/100 leukocytes in Blood by Manual count] 
New term label:
New term comment (if any):
Your biocurator ID for loinc2hpo (if desired): HPO:probinson

**Comment by pnrobinson** [comment]
added HP_0032372 @kingmanzhang 
there is no "too low" term

**Comment by kingmanzhang** [comment]
done
