### ISSUE TITLE
Decreased concentration 

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#3649]
_**Please consider a new term for Decreased concentration (concentration problems)
 Observed in : Autosomal spastic paraplegia type 72 PMID:24388663
                    : Postpoliomyelitis syndrome PMID: 15599928
Superclass:Abnormality of higher mental function??**_

**Comment by pnrobinson** [comment]
Adding the term with label "Diminished ability to concentrate" and synonym "Lack of concentration"
with definition:
An abnormal reduction in the capability of focussing on certain aspects of a task or experience to the exclusion of others.
