### ISSUE TITLE
retinitis

### ISSUE THREAD

**Issue by slaulederkind** [obophenotype/human-phenotype-ontology#3651]
_For new term requests, please provide us with the following information:_
### 1. Preferred term label

retinitis

### 3. Textual definition (should be understandable even for non-specialists, please include a PubMed ID for relevant articles providing additional information about the suggestion)

Inflammation of the retina.  PMID:11564593 

### 4. Parent term (use [HPO Browser](http://compbio.charite.de/hpoweb/showterm?id=HP:0000118) or [OLS](http://www.ebi.ac.uk/ols/ontologies/hp))

Inflammatory abnormality of the eye (HP:0100533)

### 6. Your nano-attribution (ORCID-id or label, e.g. _HPO:probinson_ (organization:name))

RGD:gthayman

**Comment by psergouniotis** [comment]
it is slightly different. "Chorioretinitis" suggests that the origin of the process is predominantly in the choroid while "Retinitis" suggests that the process is mainly in the retina"

A widely accepted nomenclature for these condition can be found here: https://www.ncbi.nlm.nih.gov/pubmed/16196117. 
I suggest to have "Retinitis" as a subclass of "Abnormal retinal morphology"

On a different note, we have previously discussed that it is slightly counterintuitive to have "Abnormal chorioretinal morphology" as a subclass of "Abnormal retinal morphology" but there is no clear guidance on what to do with these mixed terms.

**Comment by pnrobinson** [comment]
OK, adding the term Retinitis and putting the above statement as a comment.
