### ISSUE TITLE
Loinc 1452-2:  "Creatinine [Mass/volume] in 24 hour Urine --24 hours post 40 ug corticotropin IM BID 3 day"

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#3652]
Suggest creating a new term for Loinc: 1452-2 [Creatinine [Mass/volume] in 24 hour Urine --24 hours post 40 ug corticotropin IM BID 3 day] 
New term label: Abnormal creatnine level in urine 
New term comment (if any): and children, as appropriate
Your biocurator ID for loinc2hpo (if desired): HPO:nvasilevsky

**Comment by pnrobinson** [comment]
I think this LOINC is too detailed for us to annotate it to an HPO term at this time.
