### ISSUE TITLE
Loinc 19270-8:  "Barbiturates [Presence] in Urine by Screen method"

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#3653]
Suggest creating a new term for Loinc: 19270-8 [Barbiturates [Presence] in Urine by Screen method] 
New term label: Positive urine barbiturate test
New term comment (if any):
Your biocurator ID for loinc2hpo (if desired): HPO:nvasilevsky

**Comment by LCCarmody** [comment]
Duplicate. Same as #3554.  Closing.
