### ISSUE TITLE
Loinc 18282-4:  "Cannabinoids [Presence] in Urine by Screen method"

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#3654]
Suggest creating a new term for Loinc: 18282-4 [Cannabinoids [Presence] in Urine by Screen method] 
New term label: Positive urine cannoabinoid test
New term comment (if any):
Your biocurator ID for loinc2hpo (if desired): HPO:nvasilevsky

**Comment by LCCarmody** [comment]
Duplicate. Same as #3555. Closing.
