### ISSUE TITLE
Loinc 14316-4:  "Benzodiazepines [Presence] in Urine by Screen method"

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#3655]
Suggest creating a new term for Loinc: 14316-4 [Benzodiazepines [Presence] in Urine by Screen method] 
New term label: Positive urine benzodiazepine test
New term comment (if any):
Your biocurator ID for loinc2hpo (if desired): HPO:nvasilevsky

**Comment by LCCarmody** [comment]
Duplicate. Same as #3556.  Closing.
