### ISSUE TITLE
Loinc 19359-9:  "Cocaine [Presence] in Urine by Screen method"

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#3657]
Suggest creating a new term for Loinc: 19359-9 [Cocaine [Presence] in Urine by Screen method] 

New term label: Positive urine cocaine test 

Your biocurator ID for loinc2hpo (if desired): HPO:nvasilevsky

**Comment by LCCarmody** [comment]
Duplicate. Same as #3421. Closing.
