### ISSUE TITLE
upper limb ataxia

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#3658]
_**Please consider a new term for upper limb ataxia observed in  Autosomal recessive spastic paraplegia type 76 PMID:27153400.
Superclass:limb ataxia.**_

**Comment by pnrobinson** [comment]
My interpretation of this is that the ataxia affects both legs and arms (gait ataxia and upper extremity), https://www.cell.com/ajhg/fulltext/S0002-9297(16)30097-0
but I do not think this is specifically upper limb. I think it would be best to annotated with limb ataxia, and perhaps to use the modifier superior if you really want to emphasize the upper limbs.
