### ISSUE TITLE
increased velocity of large saccades

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#3661]
_**Please consider a new term for increased velocity of large saccades observed in   Autosomal recessive cerebellar ataxia-saccadic intrusion syndrome.PMID:14681893.
Superclass:Abnormality of saccadic eye movements.**_

**Comment by pnrobinson** [comment]
I think the main phenotype here is overshoot, which already exists as a term. I think the 'increased velocity' is very rarely reported and so let's hold off on making an HPO term for now.
