### ISSUE TITLE
macrosaccadic oscillations

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#3662]
_**Please consider a new term for macrosaccadic oscillations observed in  Autosomal recessive cerebellar ataxia-saccadic intrusion syndrome.PMID:14681893.
Superclass:Abnormality of saccadic eye movements??**_

**Comment by psergouniotis** [comment]
yes. A few suggestions

The term "Abnormality of saccadic eye movements" (HP:0000570) should have the following subclasses:
* **saccadic oscillation**; definition: An involuntary abnormality of fixation in which there is an abnormal saccade away from fixation followed by an immediate corrective saccade.

* **saccadic intrusion**; definition: An involuntary abnormality of fixation in which there is an abnormal saccade away from fixation followed by a delayed corrective saccade.

**Comment by psergouniotis** [comment]
saccadic oscillation should have the following subclasses:
* **ocular flutter**; definition: bursts of moderate-amplitude horizontal saccades without intersaccadic interval.
* **opsoclonus**; definition: bursts of large-amplitude multidirectional saccades without intersaccadic interval

**Comment by psergouniotis** [comment]
saccadic intrusion should have the following subclasses:
* **Square-wave jerks**; definition: horizontal 1–5° excursions from fixation and back again.
* **Macrosquare-wave jerks**; definition: horizontal 10–40° excursions from fixation and back again.
** Macrosaccadic oscillation; definition: series of hypermetric saccades attempting to narrow in on the target; ‘ocular past-pointing’.

all definitions as per Oxford Handbook of Ophthalmology 2018.

**Comment by pnrobinson** [comment]
Added all of these terms as suggested
