### ISSUE TITLE
decrased pinprick sensivity

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#3664]
_**Please consider a new term for decrased pinprick sensivity observed in Autosomal recessive spastic paraplegia type 28.PMID:15786464.
Superclass:Pain insensitivity?? **_

**Comment by pnrobinson** [comment]
The pinprick test is used to assess pain sensation and so this is equivalent to 
https://hpo.jax.org/app/browse/term/HP:0007328
In English, the correct term would be Decreased pinprick sensation -- I will add this as a synonym.
