### ISSUE TITLE
Pseudobulbar Dysarthria

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#3667]
_**Please consider a new term for Pseudobulbar Dysarthria observed in Autosomal recessive complex spastic paraplegia type 9B.PMID:26026163.
Superclass:Dysarthria**_

**Comment by pnrobinson** [comment]
I think that the combination of signs as here is a characteristic phenotype
https://hpo.jax.org/app/browse/term/HP:0007024
but we do not want to code the individual items with their pathophysiology!
