### ISSUE TITLE
archaic reflexes

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#3668]
_**Please consider a new term for archaic reflexes as a synonym of  Primitive reflex.observed in Autosomal recessive complex spastic paraplegia type 9B.PMID:26026163. **_

**Comment by pnrobinson** [comment]
I think the word archaic is mainly used in Romance languages (e.g.,  réflexes archaïques  ), but occasionally this phrase is seen in English so I will add it as a synonym.
