### ISSUE TITLE
elevated threonine 

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#3670]
_**Please consider a new term for elevated threonine observed in Cirrhosis-dystonia-polycythemia-hypermanganesemia syndrome.PMID:18392750.
Superclass:Abnormality of amino acid metabolism??? **_

**Comment by pnrobinson** [comment]
That is this: https://hpo.jax.org/app/browse/term/HP:0003354
I am adding as a synoynm, Elevated circulating threonine
