### ISSUE TITLE
elevated Hepatic manganese content

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#3671]
_**Please consider a new term for elevated Hepatic manganese content observed in Cirrhosis-dystonia-polycythemia-hypermanganesemia syndrome.PMID:18392750.
Superclass:Abnormality of the liver??
                Abnormality of manganese metabolism once created **_

**Comment by pnrobinson** [comment]
I think that probably this is too detailed for now since I think there is elevated manganese in multiple tissues but the liver happened to be investigated here. For now please just use hypermanganesemia
