### ISSUE TITLE
Term Request for Gomez-Lopez-Hernandes syndrome

### ISSUE THREAD

**Issue by petkraw** [obophenotype/human-phenotype-ontology#3675]
_For new term requests, please provide us with the following information:_
### 1. Preferred term label

a) trigeminal anesthesia
b) Rhombencephalosynapsis

### 2. Synonyms

b) maybe fusion of the cerebellar hemispheres:
http://compbio.charite.de/hpoweb/showterm?id=HP:0000118#id=HP:0006899

### 4. Parent term (use [HPO Browser](http://compbio.charite.de/hpoweb/showterm?id=HP:0000118) or [OLS](http://www.ebi.ac.uk/ols/ontologies/hp))

a) Abnormality of the fifth cranial nerve

### 5. Which diseases are characterized by this term ? (e.g. Orphanet- or OMIM-id)

GOMEZ-LOPEZ-HERNANDEZ SYNDROME
http://omim.org/entry/601853?search=gomez%20lopez&highlight=gomez%20lopez

### 6. Your nano-attribution (ORCID-id or label, e.g. _HPO:probinson_ (organization:name))

 https://orcid.org/0000-0002-3194-8625

**Comment by pnrobinson** [comment]
adding trigeminal anesthesia as HP_0031912 with def: Decreased or absent sensation in the distribution of the trigeminal nerve, which provides tactile, proprioceptive, and nociceptive sensation in the area of the face and mouth.

**Comment by pnrobinson** [comment]
Adding Rhombencephalosynapsis as HP_0031912 with def:Rhombencephalosynapsis is a rare brain malformation defined by midline fusion of the cerebellar hemispheres with partial or complete loss of the intervening vermis.
