### ISSUE TITLE
question about synonym for HP_0002091 Restrictive ventilatory defect

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#3677]
HP_0002091 Restrictive ventilatory defect has a synonym: 'Restrictive lung disease', but the comment on this term says 'The most commonly used term for this feature is restrictive lung disease, but we choose the term Restrictive ventilatory defect to emphasize that this term refers to a phenotypic feature rather than a disease entity.'

It looks like I added this synonym, but I don't remember why, and based on the comment, I wonder if this synonym should be a narrow synonym because it is more specific? Or maybe removed?

**Comment by pnrobinson** [comment]
In general, we should classify diseases that are also used to name phenotypic features as RELATED. I have done this.
