### ISSUE TITLE
NTR: fat embolism

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#3678]
_For new term requests, please provide us with the following information:_
### 1. Preferred term label
Fat embolism

### 2. Synonyms
Pulmonary fat embolism

### 3. Textual definition (should be understandable even for non-specialists, please include a PubMed ID for relevant articles providing additional information about the suggestion)
The release of fat globules into the venous circulation, thereby blocking blood circulation to the lung.
PMID:24468004 

### 4. Parent term (use [HPO Browser](http://compbio.charite.de/hpoweb/showterm?id=HP:0000118) or [OLS](http://www.ebi.ac.uk/ols/ontologies/hp))
HP_0002204 'Pulmonary embolism'

### 5. Which diseases are characterized by this term ? (e.g. Orphanet- or OMIM-id)
Sickle Cell Disease

### 6. Your nano-attribution (ORCID-id or label, e.g. _HPO:probinson_ (organization:name))
 https://orcid.org/0000-0001-5208-3432

**Comment by pnrobinson** [comment]
adding as HP_0032008
