### ISSUE TITLE
Duffy

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3679]
I am in the process of editing the "omit" list that will allow us to filter out phenotypes that are not diseases if we so desire. We have a lot of blood group entries such as the following:
https://omim.org/entry/110700
currently, we have wrong annotations:

* HP:0000006	Autosomal dominant inheritance				
* HP:0001939	Abnormality of metabolism/homeostasis								
* HP:0002715	Abnormality of the immune system			

The "abnormality" terms result from the way our text mining system looks at the CS way back when. 
We have two options
1. Completely remove these annotations because they are wrong
2. Add in HPO terms that describe things such as blood group -- i.e., non-abnormal phenotypes. This would have to go into a separate subontology, such as blood group phenotype or even trait. 

I am in favor of (2) because for the common disease project, we may want to know and analyze what blood group a patient has. @drseb @mellybelly @cmungall thoughts?

**Comment by pnrobinson** [comment]
@kingmanzhang  Do we have a LOINC annotation for Duffy? I think it should be either presence or absence of the antigen.

**Comment by kingmanzhang** [comment]
@pnrobinson Sorry for being late. Yes, there is a LOINC 13309-0 Duffy group Ag[Type] on Red Blood Cells. Also support (2). It appears we are already doing that. Reopen this in case this helps completing blood group sub ontology.

**Comment by kingmanzhang** [comment]
Sorry, it appears we already have Duffy terms.
