### ISSUE TITLE
Subontologies

### ISSUE THREAD

**Issue by LAustin1** [obophenotype/human-phenotype-ontology#3680]
Hi,

I would like to know a little more about the mode of inheritance, and onset and clinical course subontologies, and how they are connected to the organ abnormality (or phenotype) subontology please..

Thank you,
Austin

**Comment by pnrobinson** [comment]
If you look on the HPO browser
https://hpo.jax.org/app/browse/term/HP:0000001
you can explore the different subontologies. Essentially, each of the subontologies is used to describe different things. Please let us know if you have specific questions after browsing this!
