### ISSUE TITLE
Suggesting new child term of "Abnormality of the hepatic vasculature"

### ISSUE THREAD

**Issue by theoriste** [obophenotype/human-phenotype-ontology#3681]
Suggest creating new child term of Abnormality of the hepatic vasculature [HP:0006707] 
New term label: Congenital absence of portal vein 
New term definition: Anomaly where the intestinal and the splenic venous drainage bypass the liver and drain into systemic veins through other possible venous shunts.
New term comment (if any):
New term synonyms(if any): CAPV; missing portal vein
New term lay person synonyms (if any):
Reference (e.g., PubMed ID): 2053351;18932274
Your biocurator ID for nanoattribution (if desired):

**Comment by theoriste** [comment]
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2760189/

**Comment by pnrobinson** [comment]
thanks for the suggestion. Adding as HP_0031942
