### ISSUE TITLE
Hi, how can I view annotations to a HPO term in graph view

### ISSUE THREAD

**Issue by LAustin1** [obophenotype/human-phenotype-ontology#3686]
_For new term requests, please provide us with the following information:_

**Comment by pnrobinson** [comment]
We do not provide a graph based viewer for the annotations but you may be interested in the beta version of the HPO website that provides various infos about the annotations and diseases, e.g., 
https://hpo.jax.org/app/browse/term/HP:0001081

**Comment by LAustin1** [comment]
Ok thank you.
