### ISSUE TITLE
HPO term for non-affected/healthy status - a discussion

### ISSUE THREAD

**Issue by shaytzur** [obophenotype/human-phenotype-ontology#3688]
Hello,

Adding HPO terms is becoming an essential step in most bioinformatic systems and it helps to define the symptoms of the affected proband very well.  The root term of HPO is "Abnormal phenotype", but I think it could be very helpful to also have some kind of a definition/HPO code for "non-affected/healthy/unknown phenotypes"  individuals as well (maybe for a certain age group). 

For big bioinformatic systems, such a code for non-affected will allow adding a real defined HPO value for non affected family members in the phenotypes sections, instead of indicating NULL or NOT values,  that can also be useful when a genome of a healthy person is being analyzed. In general, that will allow amore organized sample set.

I assume it is not a straightforward decision, and should be discussed.

Shay Tzur, PhD
Emedgene

**Comment by pnrobinson** [comment]
@drseb @cmungall @mellybelly 
Potentially a small set of terms like this could go under Clinical Modifier. This would not be under the root Abnormal phenotype and would be convenient for a number of groups. Thoughts/Opinions?

**Comment by drseb** [comment]
@pnrobinson do you have a more concrete plan that you can share? Which terms would you add under "non-affected"?

**Comment by pnrobinson** [comment]
I was basically proposing a skype to discuss this. Which might be difficult given current travel schedules. What about if we come up some with ideas here or on google docs and then set up a skype?

**Comment by cmungall** [comment]
Let's continue with ideas here for now as I'm not completely clear on requirements. What is required that can't be done using a negation construct?

**Comment by pnrobinson** [comment]
I think that the need is for simple to use terms for non-index persons in larger studies. There are multiple ways to do this bioinformatically, but many people have asked us simply to make a term for "Unaffected proband/relative". I am wondering if we should try to do a requirements analysis and have a small subhierarchy with probably 5-20 terms for unaffected status? Or maybe just a few terms?

**Comment by shaytzur** [comment]
potential ideas to consider : 1) (sub term?) differ between the definition of 'unaffected' for early onset severe-genetic disease and adult onset common diseases.  2) (sub term?)  another possibility is to connect the 'unaffected' definition with 'age group' in parallel to the 'Onset' term which is under the parent  'Clinical modifier'  ( Infantile, Antenatal, Neonatal, Congenital, Adult, Childhood, Juvenile).  That will allow higher resolution of control/healthy designation in studies. 3) a general  'parent' generic term for 'unaffected'  can also be useful .

**Comment by pnrobinson** [comment]
see https://github.com/obophenotype/human-phenotype-ontology/issues/4286

**Comment by pnrobinson** [comment]
This has been added, see https://github.com/obophenotype/human-phenotype-ontology/issues/4286
