### ISSUE TITLE
QC: Add check for undesired equivalences

### ISSUE THREAD

**Issue by matentzn** [obophenotype/human-phenotype-ontology#3690]
We have been talking about the problem of unintended equivalences: no two classes in HP/MP should be really logically equivalent, as that suggests either a redundant term (i.e. synomym) or a mistake in the logical modelling. Currently, there are 11 definitions that are exactly the same, used across multiple classes, and a further 9 equivalence classes that are inferred, mostly due to the "sublass has more general definition problem". For example, 'Long fingers' (<http://purl.obolibrary.org/obo/HP_0100807>) is asserted to have a sub-class 
'Arachnodactyly' (<http://purl.obolibrary.org/obo/HP_0001166>). However, Arachnodactyly is defined in terms of more general terms (Uberon:digit) then 'Long fingers' (Uberon:digit of manus), causing both to be inferred equivalent). As this is clearly unintended, I propose to add this check to the QC pipeline of HP. @cmungall already has a workflow for that I believe.

**Comment by pnrobinson** [comment]
@matentzn  can this issue be closed?

**Comment by matentzn** [comment]
Not yet. I have implemented the check in the new QC pipeline,  but it is not live yet. I will close it once the release pipeline changed to ODK
