### ISSUE TITLE
11 Classes with equal (not just equivalent) definitions

### ISSUE THREAD

**Issue by matentzn** [obophenotype/human-phenotype-ontology#3691]
As outlined [here](https://github.com/obophenotype/human-phenotype-ontology/issues/3690), we have 11 definitions in HP that are shared by more than one class. The default way to deal with this is to simply delete the definition (i.e. logical equivalence axiom) of the subclass; However, it would be better if a curator would find alternative definitions instead (see for example the case of 'Cleft palate' which is defined in terms of the secondary palate).

'Lacrimal duct stenosis' (<http://purl.obolibrary.org/obo/HP_0007678>)
'Delayed canalization of nasolacrimal duct' (<http://purl.obolibrary.org/obo/HP_0500048>)
---------------
'Hypoplasia of the pyramidal tract' (<http://purl.obolibrary.org/obo/HP_0007348>)
'Corticospinal tract hypoplasia' (<http://purl.obolibrary.org/obo/HP_0007016>)
---------------
'Malar flattening' (<http://purl.obolibrary.org/obo/HP_0000272>)
'Hypoplasia of the zygomatic bone' (<http://purl.obolibrary.org/obo/HP_0010669>)
---------------
'Synostosis of thumb phalanx' (<http://purl.obolibrary.org/obo/HP_0009635>)
'Symphalangism of the thumb' (<http://purl.obolibrary.org/obo/HP_0009656>)
---------------
'Camptodactyly of finger' (<http://purl.obolibrary.org/obo/HP_0100490>)
'Interphalangeal joint contracture of finger' (<http://purl.obolibrary.org/obo/HP_0001220>)
---------------
'Abnormal cartilage morphology' (<http://purl.obolibrary.org/obo/HP_0002763>)
'Abnormality of cartilage morphology' (<http://purl.obolibrary.org/obo/HP_0410007>)
---------------
'Cleft palate' (<http://purl.obolibrary.org/obo/HP_0000175>)
'Cleft secondary palate' (<http://purl.obolibrary.org/obo/HP_0410004>)
---------------
'Multicystic kidney dysplasia' (<http://purl.obolibrary.org/obo/HP_0000003>)
'Polycystic kidney dysplasia' (<http://purl.obolibrary.org/obo/HP_0000113>)
---------------
'Absent/hypoplastic paranasal sinuses' (<http://purl.obolibrary.org/obo/HP_0005453>)
'Aplasia/Hypoplasia involving the sinuses' (<http://purl.obolibrary.org/obo/HP_0009120>)
---------------
'Aplasia/Hypoplasia of the pyramidal tract' (<http://purl.obolibrary.org/obo/HP_0007363>)
'Aplasia/Hypoplasia involving the corticospinal tracts' (<http://purl.obolibrary.org/obo/HP_0007365>)
---------------
'Aplasia/hypoplasia of the extremities' (<http://purl.obolibrary.org/obo/HP_0009815>)
'Aplasia/hypoplasia involving bones of the extremities' (<http://purl.obolibrary.org/obo/HP_0045060>)

**Comment by pnrobinson** [comment]
@matentzn @drseb @LCCarmody @nicolevasilevsky can we discuss and fix these definitions on some upcoming call?

**Comment by LCCarmody** [comment]
Could we discuss this at the end of the Phenotype ontology call this Thursday @12pm EST?

**Comment by matentzn** [comment]
Probably the best would be to have @nicolevasilevsky develop some suggestions for each of them (essentially more precise fillers). I am not sure I can help much. I do, however, recommend to remove the logical definition of one of these until a better definition can be found. Then this issue can be closed, and seperate issues can be made for making new ones. It is really confusing to have equivalent or worse, equal logical definitions across terms representing distinct concepts.. :P

**Comment by matentzn** [comment]
Haha Leigh, same second comment :P Good. I thought of it, but I think the issue is too HP specific to be discussed with the hole group. Do you still have an HP editors call?

**Comment by LCCarmody** [comment]
We have one another call on Friday, Feb. 8th at 1p EST with Peter, Nicole, and I, but that might be too late for the Europeans. @drseb ?

**Comment by nicolevasilevsky** [comment]
Hi all - I can take a look at these terms and suggest alternative definitions, as @matentzn suggested.

I would be happy to join a call too, let me know what time works best.

**Comment by nicolevasilevsky** [comment]
## 'Lacrimal duct stenosis' (HP_0007678) and 'Delayed canalization of nasolacrimal duct' (HP_0500048)

**Notes:**
- the logical defs for stenosis are not consistent for _stenosis_ terms, they either use _constricted_ or _decreased width_ as the quality
- Must terms use 'constricted' as the quality, for example:
  - 'Choanal stenosis'
  - 'Anal stenosis'

- term using 'decreased width' instead of 'constricted':
  - 'Stenosis of the external auditory canal'

**Recommendation:**
Remove logical def from _Delayed canalization of nasolacrimal duct_. The logical def doesn't seem consistent with the text def (A very common condition in which the extreme end of the nasolacrimal duct underneath the inferior turbinate fails to complete its canalization in the newborn period.)
**Logical def for _Delayed canalization of nasolacrimal duct_:**
'has part' some 
    (constricted
     and ('inheres in' some 'nasolacrimal duct')
     and ('has modifier' some abnormal))

**Comment by nicolevasilevsky** [comment]
## 'Hypoplasia of the pyramidal tract' (HP_0007348) and 'Corticospinal tract hypoplasia' (HP_0007016)

**Recommendation**
_pyramidal tract_ is a broad synonym for corticospinal tract. I think we should make a NTR to Uberon for _pyramidal tract_, and remove the current logical defintiion from _Hypoplasia of the pyramidal tract_ and add it back when the new Uberon term is created.

**Comment by nicolevasilevsky** [comment]
## 'Malar flattening' (HP_0000272) and 'Hypoplasia of the zygomatic bone' (HP_0010669)

**Recommendation**
The sibling classes for _malar flattening_ use _zygomatic arch_ in the logical definitions, and based on the text def, I think _zygomatic arch_ should be used in place of _jugal bone_ in the logical def.

Proposed new logical def:
'has part' some 
    (hypoplastic
     and ('inheres in' some 'zygomatic arch')
     and ('has modifier' some abnormal))

**Comment by nicolevasilevsky** [comment]
'Synostosis of thumb phalanx' (HP_0009635) and 'Symphalangism of the thumb' (HP_0009656)

It seems that all the synostosis terms and symphalangism terms use the same pattern for the logical definitions.

Proposed new logical def for _Symphalangism of the thumb_

'has part' some 
    ('fused with'
     and ('inheres in' some 'interphalangeal joint of manual digit 1')
     and (towards some 'interphalangeal joint of manual digit 1')
     and ('has modifier' some abnormal))

(I think all of the Symphalangism terms should be revised to refer to the joints and not just the bones)

**Comment by nicolevasilevsky** [comment]
## 'Camptodactyly of finger' (HP_0100490) and 'Interphalangeal joint contracture of finger' (HP_0001220)

According to [Wikipedia](https://en.wikipedia.org/wiki/Camptodactyly), camptodactyly is a medical condition that causes one or more fingers to be permanently bent. It involves fixed flexion deformity of the proximal interphalangeal joints. 

Not sure if this revised logical def would work for _Camptodactyly of finger_:
'has part' some 
    (bent
     and ('inheres in' some 'interphalangeal joint of manus')
     and ('has modifier' some abnormal))

**Comment by nicolevasilevsky** [comment]
## 'Abnormal cartilage morphology' (HP_0002763) and 'Abnormality of cartilage morphology' (HP_0410007)

Looks like these are duplicate classes! And it seems that I created HP_0410007. I think these should be merged.

**Comment by nicolevasilevsky** [comment]
## 'Cleft palate' (HP_0000175) and 'Cleft secondary palate' (HP_0410004)

Looks like 'Cleft secondary palate' (HP_0410004) has been obsoleted in the hp-edit.owl file.

**Comment by nicolevasilevsky** [comment]
## 'Multicystic kidney dysplasia' (HP_0000003) and 'Polycystic kidney dysplasia' (HP_0000113)

The text def of _Multicystic kidney dysplasia_ is:
Multicystic dysplasia of the kidney is characterized by multiple cysts of varying size in the kidney and the absence of a normal pelvicaliceal system. The condition is associated with ureteral or ureteropelvic atresia, and the affected kidney is nonfunctional.

I think this is more complex than the logical def, and the logical def for _Multicystic kidney dysplasia_ should be removed.

**Comment by nicolevasilevsky** [comment]
## 'Absent/hypoplastic paranasal sinuses' (HP_0005453) and 'Aplasia/Hypoplasia involving the sinuses' (HP_0009120)

_sinus_ is a broad synonym for _paranasal sinus_ in [Uberon](https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0001825). Maybe we should make a NTR to Uberon for _sinus_ as its own class?

**Comment by nicolevasilevsky** [comment]
## 'Aplasia/Hypoplasia of the pyramidal tract' (HP_0007363) and 'Aplasia/Hypoplasia involving the corticospinal tracts' (HP_0007365)

**Current logical def:**
'has part' some 
    (aplastic/hypoplastic
     and ('inheres in' some 'corticospinal tract')
     and ('has modifier' some abnormal))

Same issue as above - 
pyramidal tract is a broad synonym for corticospinal tract. Should we make a NTR to Uberon for pyramidal tract, and remove the current logical defintiion from Hypoplasia of the pyramidal tract and add it back when the new Uberon term is created?

**Comment by pnrobinson** [comment]
Camptodactyly is an isolated congenital flexion deformity of the proximal interphalangeal (PIP) joint.
Flexion contracture (...) is more general

**Comment by pnrobinson** [comment]
The definitions for Symphalangism  look wrong--we need to talk!

**Comment by pnrobinson** [comment]
@matentzn @nicolevasilevsky @LCCarmody @drseb can we move forward on this? Would this be a good topic for an upcoming curators meeting?

**Comment by matentzn** [comment]
We will address this during @nicolevasilevsky and my next modelling session on Wednesday! Thanks for reminding us :)

**Comment by nicolevasilevsky** [comment]
working with @matentzn now, we edited the following:
removed logical def from HP_0007348, HP_0500048, HP_0009656, HP_0100490, HP_0001220, HP_0410007, HP_0000003, HP_0009120, HP_0007363 and revised logical def for HP_0000272
