### ISSUE TITLE
9 (almost certainly unintended) equivalence classes in HP

### ISSUE THREAD

**Issue by matentzn** [obophenotype/human-phenotype-ontology#3692]
As outlined [here](https://github.com/obophenotype/human-phenotype-ontology/issues/3690), we have 9 equivalence classes in HP that are almost certainly unintended (as they 'contradict' the asserted subsumption). Almost all of these (8) are consequences of the “subclass more general definition” problem, i.e. the (asserted) subclasses have definitions that make use of more general concepts than their parents, thereby making them equivalent. 

I saw four cases: 

* the sub definition included a generalising “or”
* The sub definition included a more general relation (inheresinpartof)
* The sub definition included a mereological parent (part of transitive!)
* The sub definition included a more general term (digit compared to manus digit).

Especially when considering the last case in the following list, (not every 'Inflammation of the large intestine' is automatically an 'acute colitis'), it is obvious that the logical equivalence is unintended. It is important to note that tools like OWLSim rely on such implications, and therefore may return unintended phenotype suggestions (probably not veeery wrong, but still :). 

There is one definition, that suffers from the 'hidden implied restriction' problem: 'Lack of subcutaneous fatty tissue' and 'Absence of subcutaneous fat' are asserted to be siblings, but one of their definitions contain the restriction 'part of some multicellular organism' which is already implied by the preceding concept, making them both equivalent. 

---------------
'Long fingers' (<http://purl.obolibrary.org/obo/HP_0100807>)
'Arachnodactyly' (<http://purl.obolibrary.org/obo/HP_0001166>)
---------------
'Frontoparietal cortical dysplasia' (<http://purl.obolibrary.org/obo/HP_0006930>)
'Cortical dysplasia' (<http://purl.obolibrary.org/obo/HP_0002539>)
---------------
'Neoplasia of the nasopharynx' (<http://purl.obolibrary.org/obo/HP_0100630>)
'Neoplasm of the pharynx' (<http://purl.obolibrary.org/obo/HP_0100638>)
---------------
'Lack of subcutaneous fatty tissue' (<http://purl.obolibrary.org/obo/HP_0007519>)
'Absence of subcutaneous fat' (<http://purl.obolibrary.org/obo/HP_0007485>)
---------------
'Fetal pyelectasis' (<http://purl.obolibrary.org/obo/HP_0010945>)
'Dilatation of the renal pelvis' (<http://purl.obolibrary.org/obo/HP_0010946>)
---------------
'Retinal dystrophy' (<http://purl.obolibrary.org/obo/HP_0000556>)
'Chorioretinal dystrophy' (<http://purl.obolibrary.org/obo/HP_0001135>)
---------------
'Abnormal choroid morphology' (<http://purl.obolibrary.org/obo/HP_0000610>)
'Abnormal chorioretinal morphology' (<http://purl.obolibrary.org/obo/HP_0000532>)
'Abnormal retinal morphology' (<http://purl.obolibrary.org/obo/HP_0000479>)
---------------
'Foot acroosteolysis' (<http://purl.obolibrary.org/obo/HP_0001842>)
'Osteolytic defects of the phalanges of the toes' (<http://purl.obolibrary.org/obo/HP_0010177>)
---------------
'Inflammation of the large intestine' (<http://purl.obolibrary.org/obo/HP_0002037>)
'Colitis' (<http://purl.obolibrary.org/obo/HP_0002583>)
'Enterocolitis' (<http://purl.obolibrary.org/obo/HP_0004387>)
'Acute colitis' (<http://purl.obolibrary.org/obo/HP_0100282>)
---------------

**Comment by pnrobinson** [comment]
@matentzn can we go over these and find a solution?
Let's start with this

```
Frontoparietal cortical dysplasia ==
'has part' some 
    (dysplastic
     and (('inheres in' some 'cerebral cortex') or ('inheres in' some 'parietal cortex'))
     and ('has modifier' some abnormal))
```
Frontoparietal cortical dysplasia (FCD) is defined like this:
The presence of developmental dysplasia of the cortex of frontal lobe and the cortex of parietal lobe.
```
The presence of developmental dysplasia of the cortex of frontal lobe and the cortex of parietal lobe.
Is this better
```
'has part' some 
    (dysplastic
     and (('inheres in' some 'frontal cortex') and ('inheres in' some 'parietal cortex'))
     and ('has modifier' some abnormal))
```
I am not sure about the best place for the "and"'s ?

**Comment by matentzn** [comment]
alright, lets do this :)

You solution technically works, but it does not have the intended semantics. As you say, then "and" is the issue here: To do what you want it to do, you would need something like this:

```
'has part' some 
    (dysplastic
     and (('inheres in' some 'frontal cortex' or 'parietal cortex'))
     and ('has modifier' some abnormal))
```

However, because of reasoning limitations, we decided not to do that in our EQ definitions. So the way to go here is this: We need to order a new UBERON term for **frontal parietal cortex** (or "region of the frontal or parietal cortex"), and make it superclass of both frontal cortex and parietal cortex. Then your definition should be rewritten as:

```
'has part' some 
    (dysplastic
     and ('inheres in' some 'frontal parietal cortex')
     and ('has modifier' some abnormal))
```

The second change we need is to replace `inheres in` by `inheres in part of` for both of these definitions, if we want to be sure imply that something that affects the "frontal parietal cortex" also affects the "cerebral cortex". What do you think? I dont mind to do a pull request on UBERON. Need to get the practice in any case.

**Comment by balhoff** [comment]
Is the dysplasia always in both? If so then you could say:

```
('has part' some 
    (dysplastic
     and ('inheres in' some 'frontal cortex') 
     and ('has modifier' some abnormal)))
and
('has part' some 
    (dysplastic
     and ('inheres in' some 'parietal cortex') 
     and ('has modifier' some abnormal)))
```

**Comment by balhoff** [comment]
I guess it depends on the desired subsumption hierarchy. Imagine my expression is A and yours is B, and another phenotype for 'dysplasia of frontal cortex' = C. We would have the hierarchy `A SubClassof C SubClassof B`. I don't think it's totally obvious which is desired; I think Sub-Q kind of makes it harder to model this.

**Comment by matentzn** [comment]
My careful suggestion here is that dysplasia of frontal cortex should not be subsumed by dysplasia of frontal parietal cortex.. On second thought therefore, maybe this new class I suggested is not the disjunction of fc and pc, but the mereological sum of it (fcm has part fc, fcm has part pc). If you do it like this, then you dont get that  'dysplasia of frontal cortex' is a subclass of fpc, which perhaps is for the best? Maybe lets wait for Peters opinion.

Peter, does a patient with 'dysplasia of frontal cortex' necessarily also have 'Frontoparietal cortical dysplasia'?
