### ISSUE TITLE
15 definitions use BFO:'quality' instead of PATO:'quality'. Intended?

### ISSUE THREAD

**Issue by matentzn** [obophenotype/human-phenotype-ontology#3694]
There are 15 classes/definitions that make use of quality (BFO_0000019) and 3618 that make use of the corresponding PATO_0000001. Both are called 'quality' in Protege. Was this intended?

Here is a [list](https://docs.google.com/spreadsheets/d/1aZ-pXVpLB7XCy1tEF-q_on29_GzOKkj-zonRyXQulC8/edit?usp=sharing) of the 15 classes plus their definitions.

**Comment by pnrobinson** [comment]
This sounds like a mistake -- we should be using the PATO quality term for all definitions. @drseb can we script a fix for this? Do you agree?

**Comment by drseb** [comment]
There seem to be a lot of duplicates in the list @matentzn

**Comment by matentzn** [comment]
Indeed. My bad: I included HP classes as they are used by other ontologies (like EFO), which import ancient versions of HP definitions. Now it should be correct: Only 15 definitions to fix. The list further included MP classes, I will create tickets for them separately once I finish my analysis of their patterns.

**Comment by matentzn** [comment]
the RO import also re-defines PATO:morphology to be a BFO:quality (which it is not in the context of PATO itself). This axiom in conjunction with the problem mentioned here actually is responsible for five inferred subclass relations. @drseb do you believe this axiom is really necessary?

**Comment by pnrobinson** [comment]
@drseb @matentzn -- unsure how to proceed here. Can we just switch PATO:quality into these definitions?

**Comment by matentzn** [comment]
I think this is just a mistake. Will create a PR some time next week to fix this!

**Comment by pnrobinson** [comment]
@matentzn Can we close this issue?

**Comment by drseb** [comment]
grep on BFO_0000019 leads to no more hits. I will close
