### ISSUE TITLE
Remove apostrophe's from primary labels

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3698]
Where appropriate at least. These are the labels

Abnormality of Descemet's membrane
Basal lamina 'onion bulb' formation
Beevor's sign
Bull's eye maculopathy
Crohn's disease
Ebstein's anomaly of the tricuspid valve
Ewing's sarcoma
Exaggerated cupid's bow
Heberden's node
Lester's sign
Peau d'orange
Schmorl's node
Widow's peak
Writer's cramp

**Comment by drseb** [comment]
Don't you think you can just fix your R code?

**Comment by pnrobinson** [comment]
The R code is fine, but in general people are moving away from the 's possessive form -- for instance, it is recommended not to say Marfan's syndrome but instead Marfan syndrome. We currently have both forms in primary labels, for instance, Descemet's membrane and Descemet membrane.
My proposal is that we standardize the primary labels to the Descemet membrane form.
We cannot change Writer's cramp etc though, and so we cannot change everything in this list!

**Comment by pnrobinson** [comment]
I have removed the apostrophe from a few of these -- only those that are appropriate and where the form without apostrophe is found in PubMed etc.
