### ISSUE TITLE
Loinc 29959-4:  "Ganglioside GM1 IgG Ab [Mass/volume] in Serum by Immunoassay"

### ISSUE THREAD

**Issue by jpgourdine** [obophenotype/human-phenotype-ontology#3701]
Suggest creating a new term for Loinc: 29959-4 [Ganglioside GM1 IgG Ab [Mass/volume] in Serum by Immunoassay] 
New term label:Anti-ganglioside antibody positivity
New term comment (if any):Autoimmune antibody positivity (parent)
Your biocurator ID for loinc2hpo (if desired): OHSU:JP

**Comment by LCCarmody** [comment]
Hi JP,  Is this different than 'Anti-gangloside GM1 IgM antibody positivity' (HP:0031810)?

**Comment by nicolevasilevsky** [comment]
I think it is the same

**Comment by LCCarmody** [comment]
then I,m closing this ticket.

**Comment by jpgourdine** [comment]
Yes, it is the same as we discuss with Peter [here](https://github.com/obophenotype/human-phenotype-ontology/issues/3604#issuecomment-387896117), we are not going to be to granular right now. Sorry for late response. Thanks
