### ISSUE TITLE
verrucous pigmented skin lesions

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#3711]
_**Please consider a new term for verrucous pigmented skin lesions observed in epidermal nevus syndrome
PMID: 25928347.
Superclass:Abnormality of skin morphology??**_

**Comment by pnrobinson** [comment]
I think this is actually refering to an Epidermal nevus
https://hpo.jax.org/app/browse/term/HP:0010816
todo-- consult the following article for subclassification of EN
https://www.ncbi.nlm.nih.gov/pubmed/20542174/

**Comment by pnrobinson** [comment]
added reference.
