### ISSUE TITLE
calf myalgia

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#3713]
_**Please consider a new term for calf myalgia observed in Corticosteroid-sensitive aseptic abscess syndrome.
PMID:17505254.
Superclass:Abnormality of the calf musculature??**_

**Comment by pnrobinson** [comment]
I think they are referring to Gastrocnemius Myalgia
https://www.ncbi.nlm.nih.gov/pubmed/29491286
I will make Gastrocnemius Myalgia the primary label.
