### ISSUE TITLE
chipmunk face appearance

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#3717]
_**Please consider a new term for chipmunk face appearance.observed in Sagliker syndrome.
PMID:24413727.
Superclass:Abnormal facial shape.
I don't know if from an ethical  view? can we continue to create  similar terms ??**_

**Comment by pnrobinson** [comment]
I agree that we should not use the phrase chipmunk face.
Also, chipmunk face is a bundled term with two components, viz., 
https://medical-dictionary.thefreedictionary.com/chipmunk+face
Let's look into this in more detail, I will make a suggestion about how to annotate this.

**Comment by pnrobinson** [comment]
There is no description of the facial appearance in the article you mention, but here is a good source:

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5268604/

Changes in facial and cranial bones have been identified as the overexpansion of the bone marrow results in a typical facial appearance. The craniofacial features of thalassemia major patients include larger cheekbones, a rodent or “squirrel-like” face, a depressed nasal bridge, and a protruding maxilla. The deformations of the “squirrel-like” face are attributed to multi-directional growth, covering the maxillary region in particular, and dental protrusion involving the affected teeth [4–6]. Features characterized by prominent frontal and parietal bones, a collapsed nasal bridge, depression of the zygomaticus, and upward-slanted eyes are defined as a slightly mongoloid facial deformity in some patients [4, 6].

**Comment by pnrobinson** [comment]
This is definitely a bundled term and so it would be preferable to annotate to the individual components. I think that there are already HPO terms for all of them.
