### ISSUE TITLE
positive direct antiglobulin test

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#3718]
_**Please consider a new term for positive direct antiglobulin test.observed in Evans syndrome.
PMID:26190425.
Superclass:abnormal test result??**_

**Comment by pnrobinson** [comment]
Currently, we have this term
https://hpo.jax.org/app/browse/term/HP:0004844
Coombs-positive hemolytic anemia
Note that A positive Coombs test is a synonym for direct antiglobulin test
-- I am thinking that we this term should be entitled Positive Coombs test and that the diseases should be encoded with hemolysis and the direct Coombs test. I will look at the annotations.

**Comment by pnrobinson** [comment]
The direct antiglobulin test (DAT) and the indirect antiglobulin test (IAT) are both forms of the antiglobulin test. The antiglobulin test is a method of demonstrating the presence of antibody or complement bound to red blood cell (RBC) membranes by the use of anti-human globulin to form a visible agglutination reaction. The IAT tests for antibodies circulating in the patient's plasma, while the DAT tests for antibodies or complement bound directly to the patient's RBCs, indicating in vivo sensitization. [PMID:28134589]

**Comment by pnrobinson** [comment]
The DAT is a method used to detect immunoglobulin or complement bound in vivo to RBCs, using anti-human reagents. There are 3 different reagents that may be used: monospecific reagents to detect either bound immunoglobulin G (IgG) or bound complement (C3) and polyspecific reagents that can simultaneously detect IgG and/or C3. In screening of RBCs for the presence of bound globulins and/or C3, many laboratories may choose to use the polyspecific reagent initially (ie, as a screen for any bound IgG and/or complement) and, if positive, subsequently use monospecific reagents to specifically distinguish what is bound to the RBC surface.

**Comment by pnrobinson** [comment]
@kingmanzhang We should add a LOINC annotation for direct antiglobulin test, it is a common procedure.

**Comment by pnrobinson** [comment]
added as HP_0032366

**Comment by kingmanzhang** [comment]
@nicolevasilevsky You expertise is needed to review direct antiglobulin tests
