### ISSUE TITLE
myelosuppression

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#3721]
_**Please consider a new term for myelosuppression observed in Colchicine poisoning.
PMID:24353429.
Superclass:Abnormality of blood and blood-forming tissues?**_

**Comment by pnrobinson** [comment]
Myelosuppression is not the phenotype, I think, but it is the interpretation of what has happened (for instance after colchicine poisoning). 
It is defined as "A condition in which bone marrow activity is decreased, resulting in fewer red blood cells, white blood cells, and platelets."
Therefore, the annotations would be terms like "Thrombocytopenia".
