### ISSUE TITLE
house dust mite allergy

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#3722]
_**Please consider a new term for house dust mite allergy observed in Acral peeling skin syndrome.
PMID:26684698.
Superclass:Allergy??**_

**Comment by cmungall** [comment]
@pnrobinson @drseb we currently have a lot of very specific X-allergy terms in MONDO. Will happily move them and the corresponding DPs to HP - or if we maintain two hierarchies we should have a plan for syncing

**Comment by pnrobinson** [comment]
@cmungall I think that it is very often the case that if somebody has allergy, they are allergic to multiple items, and this would be an argument for making those items phenotype terms and making the diseases be things like "allergic rhinitis" i.e. hay fever, which in any one person might manifest as runny nose etc with the positive lab test skin prick test for birch, grass, etc

**Comment by pnrobinson** [comment]
I think this term is now taken care of in the course of the LOINC project.
