### ISSUE TITLE
macerated erythema

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#3723]
_**Please consider a new term for macerated erythema observed in Acral peeling skin syndrome.
PMID:26684698.
Superclass:Erythema?**_

**Comment by pnrobinson** [comment]
We should make a class called Maceration: softening and breaking down of skin resulting from prolonged exposure to moisture
there are 2 subclasses, red and white maceration.

**Comment by pnrobinson** [comment]
adding as HP_0032007
