### ISSUE TITLE
multiorgan failure

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#3724]
_**Please consider a new term if possible for multiorgan failure observed in Hepatic veno-occlusive disease.
PMID:21656652.
Superclass:Constitutional symptom??**_

**Comment by pnrobinson** [comment]
I think this is a bundled term and not a phenotypic feature--which instead would be the phenotypic abnormalities that led to the inference of multi-organ failure (this should be in MONDO) @nicolevasilevsky

**Comment by nicolevasilevsky** [comment]
we have multiple organ failure in MONDO, but should add a synonym (MONDO_0043726)
