### ISSUE TITLE
Increased serum level of N,N-dimethylglycine(DMG)

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#3725]
_**Please consider a new term forIncreased serum level of N,N-dimethylglycine(DMG).observed in Dimethylglycine dehydrogenase deficiency.
PMID:10102904.
Superclass:Abnormality of metabolism/homeostasis??  **_

**Comment by pnrobinson** [comment]
Added as HP_0031945
Note that N,N-dimethylglycine is a (non-protein) amino acid, so I put this class there.
