### ISSUE TITLE
Inspiratory crepitation

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#3727]
_**Please consider a new term for Inspiratory crepitation observed in Pulmonary fibrosis-hepatic hyperplasia-bone marrow hypoplasia syndrome.PMID:19401489.
SuperclassRales.:**_

**Comment by pnrobinson** [comment]
Here is a great review of the various kinds of respiratory sounds
https://www.ncbi.nlm.nih.gov/pubmed/26229557

**Comment by pnrobinson** [comment]
Crackles, crepitations, or rales are synonyms, but the recommended term is crackles.

**Comment by pnrobinson** [comment]
adding term.
