### ISSUE TITLE
HYPOPARATHYROIDISM, SENSORINEURAL DEAFNESS, AND RENAL DISEASE (Barakat syndrome)

### ISSUE THREAD

**Issue by GARDInfoCenter** [obophenotype/human-phenotype-ontology#3731]
GARD was updating its disease page on HYPOPARATHYROIDISM, SENSORINEURAL DEAFNESS, AND RENAL DISEASE (HDR), also known as Barakat syndrome ( http://compbio.charite.de/hpoweb/showterm#disease=OMIM:146255) with the help of Dr. Barakat, who first described the syndrome back in 1977. He expressed some concerns regarding some of the phenotypes listed through HPO. Below are some of the issues he mentioned:

- The following phenotypes are listed under the present in 100% of patients: Hypoparathyroidism; 
Progressive sensorineural hearing impairment; Renal dysplasia.  About 65% of people with this syndrome have all three of these, and many have only one or more. Hearing impairment is the most common but even that is not 100%. Original reports have described the syndrome to consist of this triad, but subsequent reports have described very variable expression. Here is a link to Dr. Barakat's recent article: https://onlinelibrary.wiley.com/doi/abs/10.1002/ajmg.a.38693

The article states:
1)	In our review of 180 cases, “H” occurred in 93.3% of patients. (H is hypoparathyroidism)
2)	Hearing loss is the most consistent feature of the syndrome, occurring in 96.7% of the reviewed patients.
3)	Renal involvement in this syndrome is heterogeneous and occurred in 72.2% of the reviewed cases.
4)	Though the syndrome is phenotypically defined by the triad of “H,” “D,” and “R” the literature identifies cases with different components consisting of “HD,” “DR,” “HR,” “R,” and “D” with, or without, GATA3 defects making the definition of the syndrome confusing. In our review, “HDR” was found in 64.4% of patients with the syndrome

- He  also said the term “renal dysplasia” should be changed to “renal disease” as some people have functional vs structural abnormalities of the kidney or urinary tract. Also from his article: 40% of renal disease in these patients is due to congenital anomalies of the kidney and urinary tract. Nephrotic syndrome, hematuria, proteinuria, proximal and distal renal tubular acidosis, nephrocalcinosis, and CKD have also been described.

Could you please take a look at these phenotypes and reconsider changing the frequency associated with each of them? 

Thank you,
Maria

**Comment by nicolevasilevsky** [comment]
@pnrobinson and @drseb I made a PR with some updates: https://github.com/monarch-initiative/hpo-annotation-data/pull/232

A couple questions:
1) not sure how to annotate HDR, as we usually don't have a grouped phenotype such as this. 
2) @GARDInfoCenter we have chronic kidney disease as an annotation (in addition to renal dysplasia. Renal dysplasia is described in the [OMIM record](https://www.omim.org/clinicalSynopsis/146255), so not sure we'd want to remove it. 
3) Not sure how to indicate that 40% of renal disease is due to congenital abnormalities

**Comment by pnrobinson** [comment]
@nicolevasilevsky  it is not possible to annotate data such as 1 and 2. 
I am also going to revise the annotations to put them in the form of N/M patients instead of X%. This is more precise and easier to use for algorithms!

**Comment by pnrobinson** [comment]
done
