### ISSUE TITLE
decreased thickness of the stratum corneum 

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#3739]
_**Please consider a new term for thickness of the stratum corneum  observed in Circumscribed palmoplantar hypokeratosis .PMID:24068139.
Superclass:Abnormality of the cornea??**_

**Comment by pnrobinson** [comment]
The stratum corneum in this request is in the skin, not the cornea.  I think that for now "Thin skin" is the best annotation option:
https://hpo.jax.org/app/browse/term/HP:0000963
I think we will need to have a derm annotation jamboree to decide on the best options for the skin subontology.
