### ISSUE TITLE
brachymetacarpalia

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#3740]
_**Please consider a new term for brachymetacarpalia observed in Spondyloepiphyseal dysplasia, Cantu type
PMID:17515304.
Superclass:Abnormality of the metacarpal bones?? **_

**Comment by pnrobinson** [comment]
This means abnormal shortness of the metacarpal bones and is equivalent to Short metacarpal.
https://hpo.jax.org/app/browse/term/HP:0010049
I will add as a synonym
