### ISSUE TITLE
Text-Definition of "Autistic behavior"

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#3744]
Comment by zafush:
>  DSM-IV should be updated to DSM-V

drseb: 

> is the definition the same in DSM-V ?

answer by zafush: 

> There are two ways: Easier is to take out DSM citation. The second way is to add the diagnostic criteria for "Autism Spectrum Disorders" which is now the new nomenclature for the entity = _The essential features of autism spectrum disorder are persistent impairment in reciprocal social communication and social interaction (Criterion A), and restricted, repetitive patterns of behavior, interests, or activities (Criterion B). These symptoms are present from early childhood and limit or impair everyday functioning (Criteria C and D)_

@pnrobinson can you take care of this?

**Comment by cmungall** [comment]
We should make MONDO consistent when you have decided on defs for HPO, cc @nicolevasilevsky

**Comment by pnrobinson** [comment]
The HPO should have a hierarchy deriving from "Autistic behavior" and MONDO from "Autism" etc -- let us revisit these terms!

**Comment by pnrobinson** [comment]
I have updated the definition to Persistent deficits in social interaction and communication and interaction as well as a markedly restricted repertoire of activity and interest as well as repetitive patterns of behavior.
PMID:28879490
There is an enormous range of behaviors exhibited by children with autism, and we should probably revisit this in the context of a workshop if possible, but I am closing now. I have removed the references to DMV-IV
