### ISSUE TITLE
Text-Definition of Osteopenia

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#3745]
zafush reported:

Original WHO def: _BMD between 1.0 and 2.5 SD below that of a “young normal” adult (T-score between −1.0 and −2.5, whereas osteoporosis as a T score at −2.5 or lower"_

**Comment by drseb** [comment]
Should we change the existing def?

**Comment by pnrobinson** [comment]
I have updated the definition to
Osteopenia is a term to define bone density that is not normal but also not as low as osteoporosis. By definition from the World Health Organization osteopenia is defined by bone densitometry as a T score -1 to -2.5.
this is from https://www.ncbi.nlm.nih.gov/pubmed/21234807
Thanks for picking up the mistake.
