### ISSUE TITLE
Text-Definition of Osteoporosis

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#3746]
zafush says:

_According to the WHO criteria, osteoporosis is defined as a BMD that lies 2.5 standard deviations or more below the average value for young healthy adults (a T-score of <-2.5 SD)_

**Comment by drseb** [comment]
What do you think @pnrobinson ?

**Comment by pnrobinson** [comment]
This is our current definition, which seems to be saying the same thing. What is the issue?

Osteoporosis is a systemic skeletal disease characterized by low bone density and microarchitectural deterioration of bone tissue with a consequent increase in bone fragility. According to the WHO, osteoporosis is characterized by a value of BMD 2.5 standard deviations or more below the young adult mean.

**Comment by pnrobinson** [comment]
I think this is OK. I updated the comment. See also https://github.com/obophenotype/human-phenotype-ontology/issues/3745
