### ISSUE TITLE
Synonym correct?

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#3748]
Not sure, but I would like to delete the synonym _Coaractation of the aorta_. It is wrong, is it?

**Comment by drseb** [comment]
Correct form is _Coarctation of the aorta_

**Comment by pnrobinson** [comment]
Yes, Coaractation is wrong but Coarctation is correct!

**Comment by pnrobinson** [comment]
I have removed the misspelled synonym.
