### ISSUE TITLE
Atria septal defect

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#3749]
Is this a correct synonym of Atrial septal defect ?

**Comment by pnrobinson** [comment]
Is what a correct synonym?

**Comment by drseb** [comment]
The title of the issue, i.e. is "Atria septal defect" a synonym of "Atrial septal defect". 

Has been asked by a collaborator and google does show results for this (except HPO and HPO-derived resources as medgen)

**Comment by pnrobinson** [comment]
I think it used MUCH less often that atria**L** septal defect but occasionally you see it and it is not wrong.
