### ISSUE TITLE
limb rigidity

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#3751]
_**Please consider a new term for limb rigidity observed in Cyanide-induced parkinsonism PMID: 2733710.
Superclass:Rigidity??**_

**Comment by pnrobinson** [comment]
I do not believe that there is a clinical feature of localized limb rigidity -- the paper that you cite states, "axial and limb rigidity", which would be equivalent to simply annotating with "Rigidity"
https://hpo.jax.org/app/browse/term/HP:0002063
so I would recommend avoiding making two new terms and instead annotating with this one.
