### ISSUE TITLE
horizontal smile

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#3753]
_**Please consider a new term for horizontal smile observed in Classic pantothenate kinase-associated neurodegeneration.PMID: 20882425.
Superclass:Abnormality of the nasolabial region??**_

**Comment by pnrobinson** [comment]
I am not really sure what horizontal smile means, and could not find any other reference to it in PubMed. Therefore, this seems to be a description that will not be easy to translate into an HPO term, which should denote a characteristic feature that can be recognized independently from a disease. I will close this issue, but if there is a good definition/description of this feature we can reconsider.
