### ISSUE TITLE
Choose different example disease on HPO site

### ISSUE THREAD

**Issue by cmungall** [obophenotype/human-phenotype-ontology#3764]
https://hpo.jax.org/app/

The example is Bladder Cancer which isn't the best demonstration of HPO annotations, a single annotation to Transitional cell carcinoma of the bladder.

A Mendelian disease would be better

We may want a different example gene than TP53 too

(sorry if wrong tracker don't know hpo website github)

**Comment by pnrobinson** [comment]
I agree.
Let's use
Arachnodactly
Marfan syndrome
FBN1

**Comment by pnrobinson** [comment]
I am moving this here:https://github.com/TheJacksonLaboratory/hpo-web/issues/31
