### ISSUE TITLE
Loinc 10340-8:  "Molindone [Mass/volume] in Serum or Plasma"

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#3765]
Suggest creating a new term for Loinc: 10340-8 [Molindone [Mass/volume] in Serum or Plasma] 
New term label: Positive blood molidone test
Your biocurator ID for loinc2hpo (if desired): HPO:nvasilevsky

**Comment by pnrobinson** [comment]
@nicolevasilevsky looks good!
