### ISSUE TITLE
Loinc 10341-6:  "Norpropoxyphene [Mass/volume] in Serum or Plasma"

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#3766]
Suggest creating a new term for Loinc: 10341-6 [Norpropoxyphene [Mass/volume] in Serum or Plasma] 
New term label: Positive Norpropoxyphene blood test
Parent: Blood xenobiotic
Your biocurator ID for loinc2hpo (if desired): HPO:nvasilevsky

**Comment by pnrobinson** [comment]
@nicolevasilevsky  looks good!
