### ISSUE TITLE
Loinc 17376-5:  "Norpropoxyphene [Presence] in Urine by Confirmatory method"

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#3767]
Suggest creating a new child term of HP:0031840 [Urine xenobiotic] for Loinc 17376-5 [Norpropoxyphene [Presence] in Urine by Confirmatory method]
New term label: Positive urine norpropoxyphene test
Your biocurator ID for loinc2hpo (if desired): HPO:nvasilevsky

**Comment by pnrobinson** [comment]
@nicolevasilevsky  looks good!
