### ISSUE TITLE
Loinc 16135-6:  "Beta 2 glycoprotein 1 IgG Ab [Units/volume] in Serum"

### ISSUE THREAD

**Issue by jpgourdine** [obophenotype/human-phenotype-ontology#3769]
Suggest creating a new term for Loinc: 16135-6 [Beta 2 glycoprotein 1 IgG Ab [Units/volume] in Serum] 
New term label: anti-beta 2 glycoprotein 1 antibody positivity
New term comment (if any): Parent (Autoimmune antibody positivity HP:0030057)
Your biocurator ID for loinc2hpo (if desired): OHSU:JP

**Comment by pnrobinson** [comment]
@kingmanzhang  added as HP_0032376

**Comment by kingmanzhang** [comment]
done
