### ISSUE TITLE
Loinc 76688-1:  "Alpha-1-acid glycoprotein/Creatinine [Mass Ratio] in Urine"

### ISSUE THREAD

**Issue by jpgourdine** [obophenotype/human-phenotype-ontology#3770]
Suggest creating a new term for Loinc: 76688-1 [Alpha-1-acid glycoprotein/Creatinine [Mass Ratio] in Urine] 
New term label: Alpha-1-acid glycoproteinuria
New term comment (if any): Need to create a new parent class: Glycoproteinuria (subclass of Proteinuria HP:0000093)
Your biocurator ID for loinc2hpo (if desired): OHSU:JP

**Comment by pnrobinson** [comment]
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6097268/

**Comment by pnrobinson** [comment]
added as HP_0032377  @kingmanzhang

**Comment by kingmanzhang** [comment]
done
