### ISSUE TITLE
 Coppock-like cataract 

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3772]
@psergouniotis do we need this term? 
Coppock-like cataract refers to a dustlike opacity of the fetal nucleus with frequent involvement of the zonular lens.
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1288278/

**Comment by psergouniotis** [comment]
this is tricky and goes back to 1906 when Nettleship described "Coppock cataract". This is said to be the first trait mapped to an autosome (https://www.ncbi.nlm.nih.gov/pubmed/14059288).

Coppock cataract is also known as "central pulverulent cataract" (a dust-like disc-like opacity involving the embryonal and fetal nucleus; http://webeye.ophth.uiowa.edu/eyeforum/atlas/pages/coppock.htm). The primary term could therefore be "central pulverulent cataract" with "Coppock cataract" as a synonym.

As per paper that you mention, Coppock-like cataract is  a dustlike opacity of the fetal nucleus with frequent involvement of the zonular lens. I think this could probably be merged with "central pulverulent cataract"?

**Comment by pnrobinson** [comment]
adding synonym
