### ISSUE TITLE
NTR: cellular hypersensitivity to MMC and DEB

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#3773]
_For new term requests, please provide us with the following information:_
### 1. Preferred term label
cellular hypersensitivity to mitomycin C  
cellular hypersensitivity to diepoxybutane

### 2. Synonyms
cellular hypersensitivity to MMC 
cellular hypersensitivity to DEB, cellular hypersensitivity to 1,3-butadiene diepoxide

### 3. Textual definition (should be understandable even for non-specialists, please include a PubMed ID for relevant articles providing additional information about the suggestion)
An increased cellular sensitivity to the DNA cross-linking agent, mitomycin C (MMC). MMC causes increased FA cell death, chromosome breakage, and accumulation in the G2 phase of the cell cycle. 
PMID:9650445
Comment: Cellular hypersensitivity to mitomycin C is used in diagnostic criteria for Fanconi Anemia.

An increased cellular sensitivity to the DNA cross-linking agent, diepoxybutane (DEB). DEB causes increased FA cell death, chromosome breakage, and accumulation in the G2 phase of the cell cycle. 
PMID:14679584
Comment: Cellular hypersensitivity to diepoxybutane is used in diagnostic criteria for Fanconi Anemia.

### 4. Parent term (use [HPO Browser](http://compbio.charite.de/hpoweb/showterm?id=HP:0000118) or [OLS](http://www.ebi.ac.uk/ols/ontologies/hp))
Abnormality of DNA repair HP:0003254 

### 5. Which diseases are characterized by this term ? (e.g. Orphanet- or OMIM-id)
Fanconi Anemia

### 6. Your nano-attribution (ORCID-id or label, e.g. _HPO:probinson_ (organization:name))
https://orcid.org/0000-0001-5208-3432

@pnrobinson and @dnahotline if this looks okay, I can add.

**Comment by pnrobinson** [comment]
@nicolevasilevsky  This looks good, but I am not sure that we want to use the abbreviation increased FA cell death. We should say what cell type is typically assayed and not use FA in the definition because then the phenotype would only apply to FA (whereas I think it is probably in practice often FA related but not pathgnomonic)

**Comment by pnrobinson** [comment]
I modified the definition to(...)  In the presence of increased sensitivity, DEB causes cell death, chromosome breakage, and accumulation in the G2 phase of the cell cycle.
