### ISSUE TITLE
Hyperaldosteronism, Familial, Type Iv

### ISSUE THREAD

**Issue by uisch** [obophenotype/human-phenotype-ontology#3774]
This is an existing term, disease gene association is lacking. Please add CACNA1H as disease gene as provided by the associated OMIM record.

### Which diseases are characterized by this term ? (e.g. Orphanet- or OMIM-id)
https://www.omim.org/entry/617027

**Comment by pnrobinson** [comment]
This is a disease and not a phenotypic feature. The HPO project provides not only the ontology but also computational disease models. I see that the model for this disease does not have much detail, and so perhaps we can improve it: https://hpo.jax.org/app/browse/disease/OMIM:617027
Please let us know if you have suggestions for this.

**Comment by uisch** [comment]
As mentioned before, the gene associated with the disease is mentioned in omim (see link), but was not entered in the HPO record. Please add the gene. Thank you.

**Comment by pnrobinson** [comment]
I am unsure of what you mean -- the HPO records are phenotypes and not genes. Some of our software uses disease-gene associations--are you referring to this (e.g., Exomiser)?

**Comment by drseb** [comment]
@uisch please have a look at http://compbio.charite.de/hpoweb/showterm?id=HP:0000118#gene=8912 until the HPO-Jax-Browser is being updated. Let's have a call this or next week.

**Comment by pnrobinson** [comment]
The webapp was updated today and it now shows this association
https://hpo.jax.org/app/browse/disease/OMIM:617027
thanks for pointing this out!
