### ISSUE TITLE
Loinc 56132-4:  "Cholesterol in HDL 2a [Moles/volume] in Serum or Plasma"

### ISSUE THREAD

**Issue by kingmanzhang** [obophenotype/human-phenotype-ontology#3781]
Suggest creating a new child term of HP:0031888 [Abnormal HDL cholesterol concentration] for Loinc 56132-4 [Cholesterol in HDL 2a [Moles/volume] in Serum or Plasma]
New term label: Abnormal HDL1, HDL2(a, b), 3(a, b, c), 4, 5 cholesterol concentration
New term comment (if any): There are many tests for subclasses of HDL. For classification, refer to http://www.lipidcenter.com/pdf/HDL_Classification_Slides.pdf
Your biocurator ID for loinc2hpo (if desired): JGM:azhang

**Comment by pnrobinson** [comment]
This is a good reference
https://lipidworld.biomedcentral.com/articles/10.1186/1476-511X-11-54

**Comment by pnrobinson** [comment]
@kingmanzhang  Added this term and all of the others for the most important HDL subfractions.  HP_0032418.
