### ISSUE TITLE
Loinc 2161-8:  "Creatinine [Mass/volume] in Urine"

### ISSUE THREAD

**Issue by kingmanzhang** [obophenotype/human-phenotype-ontology#3783]
Suggest creating a new term for Loinc: 2161-8 [Creatinine [Mass/volume] in Urine] 
New term label: Abnormal urine creatine concentration
New term comment (if any): child-elevated urine creatine concentration
Your biocurator ID for loinc2hpo (if desired): JGM:azhang

**Comment by pnrobinson** [comment]
This is used for quality control and is not an abnormal phenotype per se. We need to annotate it as such!

**Comment by nicolevasilevsky** [comment]
Should we keep an eye out for these types of terms that are used for QC? How do you know this - is it because it is mass/volume?

**Comment by kingmanzhang** [comment]
I see... I am going to create a list for such tests. May need your help to populate it @pnrobinson

**Comment by pnrobinson** [comment]
@nicolevasilevsky I know this because when you study medicine you memorize about ten telephone books worth of information -- finally it is coming in handy! :-0

**Comment by pnrobinson** [comment]
We need to mark this as not annotatable! @kingmanzhang
