### ISSUE TITLE
Loinc 14118-4:  "Lactate [Mass/volume] in Serum or Plasma"

### ISSUE THREAD

**Issue by kingmanzhang** [obophenotype/human-phenotype-ontology#3784]
Suggest creating a new child term of HP:0002151 [Increased serum lactate] for Loinc 14118-4 [Lactate [Mass/volume] in Serum or Plasma]
New term label: consider changing its relationship with Lactic acidosis
New term comment (if any):
Your biocurator ID for loinc2hpo (if desired): JGM:azhang

**Comment by pnrobinson** [comment]
Let's revise the definitions and terms according to this
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3975915/

**Comment by pnrobinson** [comment]
This is the important sentence
The terms lactate and lactic acid are often used interchangeably but lactate (the component measured in blood) is strictly a weak base whereas lactic acid is the corresponding acid. “Lactic acidosis” is often used clinically to describe elevated lactate but should be reserved for cases where there is a corresponding acidosis (pH < 7.35).1
Therefore, I think we can keep the current terms but I will update the definition.
For the LOINC project note that we are not interested in too LOW lactate clinically, and so we only need one term.
