### ISSUE TITLE
Loinc 28642-7:  "Oxygen saturation in Arterial cord blood"

### ISSUE THREAD

**Issue by kingmanzhang** [obophenotype/human-phenotype-ontology#3785]
Suggest creating a new child term of HP:0012415 [Abnormal blood gas level] for Loinc 28642-7 [Oxygen saturation in Arterial cord blood]
New term label: Abnormal blood oxygen level / Abnormal blood CO2 level
New term comment (if any): put Hypo-/Hyper-xemia, Hypo-/Hyper-capnia under them. But also create grandchildren for Hyper-/Hypo-oxemia in Arterial/Venous blood, Hypo-/Hyper-capnia in Arterial/Venous blood
Your biocurator ID for loinc2hpo (if desired): JGM:azhang

**Comment by nicolevasilevsky** [comment]
Add 'abnormal cord blood measurement', as child of 'Abnormality of prenatal development or birth'
