### ISSUE TITLE
Loinc 3051-0:  "Triiodothyronine (T3) Free [Mass/volume] in Serum or Plasma"

### ISSUE THREAD

**Issue by kingmanzhang** [obophenotype/human-phenotype-ontology#3786]
Suggest creating a new child term of HP:0011788 [Increased serum free triiodothyronine] for Loinc 3051-0 [Triiodothyronine (T3) Free [Mass/volume] in Serum or Plasma]
New term label: Decreased serum free triiodothyronine
New term comment (if any):
Your biocurator ID for loinc2hpo (if desired): JGM:azhang

**Comment by nicolevasilevsky** [comment]
need to expand current hierarchy - need total and free
we have HP_0011788 'Increased serum free triiodothyronine'

use T3 in label and make triiodothyronine a syn
