### ISSUE TITLE
glucose in urine

### ISSUE THREAD

**Issue by kingmanzhang** [obophenotype/human-phenotype-ontology#3787]
There are maybe >100 LOINC tests on glucose in urine. Many are time points measurement (either Qn or Ord) in glucose challenge experiments. Should they all map to Glycosuria? Or Hyperglycemia?

**Comment by drseb** [comment]
Hyperglycemia refers to the glucose concentration in blood and not in urine.

**Comment by kingmanzhang** [comment]
""   | LOINC_NUM | LONG_COMMON_NAME
-- | -- | -- 
1 | 10966-0 | Glucose [Presence] in Urine by Test strip --2.5 hours post 75 g glucose PO
2 | 10967-8 | Glucose [Presence] in Urine by Test strip --3.5 hours post 75 g glucose PO
3 | 10968-6 | Glucose [Presence] in Urine by Test strip --4.5 hours post 75 g glucose PO
4 | 1491-0 | Glucose [Mass/volume] in Urine --30 minutes post 100 g glucose PO
5 | 1495-1 | Glucose [Mass/volume] in Urine --1.5 hours post 100 g glucose PO
6 | 1503-2 | Glucose [Mass/volume] in Urine --1 hour post 100 g glucose PO
7 | 1505-7 | Glucose [Mass/volume] in Urine --1 hour post 50 g glucose PO
8 | 15076-3 | Glucose [Moles/volume] in Urine
9 | 1509-9 | Glucose [Mass/volume] in Urine --1 hour post 75 g glucose PO
10 | 1516-4 | Glucose [Mass/volume] in Urine --2 hours post 100 g glucose PO
11 | 1520-6 | Glucose [Mass/volume] in Urine --2 hours post 75 g glucose PO
12 | 1532-1 | Glucose [Mass/volume] in Urine --3 hours post 100 g glucose PO
13 | 1538-8 | Glucose [Mass/volume] in Urine --4 hours post 100 g glucose PO
14 | 1541-2 | Glucose [Mass/volume] in Urine --5 hours post 100 g glucose PO
15 | 1546-1 | Glucose [Mass/volume] in Urine --6 hours post 100 g glucose PO
16 | 1555-2 | Glucose [Mass/volume] in Urine --12 hours fasting
17 | 16904-5 | Glucose [Presence] in Urine --1st specimen post XXX challenge
18 | 16905-2 | Glucose [Presence] in Urine --2nd specimen post XXX challenge
19 | 16906-0 | Glucose [Presence] in Urine --3rd specimen post XXX challenge
20 | 16907-8 | Glucose [Presence] in Urine --4th specimen post XXX challenge
21 | 16908-6 | Glucose [Presence] in Urine --5th specimen post XXX challenge
22 | 16909-4 | Glucose [Presence] in Urine --6th specimen post XXX challenge
23 | 16910-2 | Glucose [Presence] in Urine --7th specimen post XXX challenge
24 | 16911-0 | Glucose [Presence] in Urine --8th specimen post XXX challenge
25 | 16912-8 | Glucose [Presence] in Urine --9th specimen post XXX challenge
26 | 20406-5 | Deprecated Glucose [Mass/volume] in Urine by Test strip
27 | 22705-8 | Glucose [Moles/volume] in Urine by Test strip
28 | 2349-9 | Glucose [Presence] in Urine
29 | 2350-7 | Glucose [Mass/volume] in Urine
30 | 25428-4 | Glucose [Presence] in Urine by Test strip
31 | 25664-4 | Glucose [Mass/volume] in Urine --1 hour post dose glucose
32 | 25667-7 | Glucose [Mass/volume] in Urine --2 hours post dose glucose
33 | 25670-1 | Glucose [Mass/volume] in Urine --30 minutes post dose glucose
34 | 25675-0 | Glucose [Mass/volume] in Urine --4 hours post dose glucose
35 | 25678-4 | Glucose [Mass/volume] in Urine --1.5 hours post dose glucose
36 | 26537-1 | Glucose [Presence] in Urine by Test strip --2.5 hours post dose glucose
37 | 26538-9 | Glucose [Presence] in Urine by Test strip --3.5 hours post dose glucose
38 | 26540-5 | Glucose [Mass/volume] in Urine --3 hours post dose glucose
39 | 26542-1 | Glucose [Mass/volume] in Urine --5 hours post dose glucose
40 | 26545-4 | Glucose [Mass/volume] in Urine --6 hours post dose glucose
41 | 26546-2 | Glucose [Presence] in Urine by Test strip --1 hour post dose glucose
42 | 26547-0 | Glucose [Presence] in Urine by Test strip --2 hours post dose glucose
43 | 26548-8 | Glucose [Presence] in Urine by Test strip --30 minutes post dose glucose
44 | 26549-6 | Glucose [Presence] in Urine by Test strip --3 hours post dose glucose
45 | 26550-4 | Glucose [Presence] in Urine by Test strip --4 hours post dose glucose
46 | 26551-2 | Glucose [Presence] in Urine by Test strip --5 hours post dose glucose
47 | 26552-0 | Glucose [Presence] in Urine by Test strip --6 hours post dose glucose
48 | 26553-8 | Glucose [Presence] in Urine by Test strip --1.5 hours post dose glucose
49 | 35212-0 | Glucose [Mass or Moles/volume] in Urine
50 | 35662-6 | Glucose [Mass/volume] in Urine collected for unspecified duration
51 | 40849-2 | Glucose [Mass/volume] in Urine by Test strip --1st specimen post XXX challenge
52 | 40850-0 | Glucose [Mass/volume] in Urine by Test strip --2nd specimen post XXX challenge
53 | 42604-9 | Glucose [Mass/volume] in Urine --3 hours post dose lactose PO
54 | 42609-8 | Glucose [Mass/volume] in Urine --6 hours post dose lactose PO
55 | 42611-4 | Glucose [Mass/volume] in Urine --1 hour post dose lactose PO
56 | 42613-0 | Glucose [Mass/volume] in Urine --2 hours post dose lactose PO
57 | 42615-5 | Glucose [Mass/volume] in Urine --30 minutes post dose lactose PO
58 | 42629-6 | Glucose [Mass/volume] in Urine --4 hours post dose lactose PO
59 | 42631-2 | Glucose [Mass/volume] in Urine --5 hours post dose lactose PO
60 | 45204-5 | Glucose [Mass/volume] in Urine by Test strip --3rd specimen post XXX challenge
61 | 45205-2 | Glucose [Mass/volume] in Urine by Test strip --4th specimen post XXX challenge
62 | 45206-0 | Glucose [Mass/volume] in Urine by Test strip --5th specimen post XXX challenge
63 | 50555-2 | Glucose [Presence] in Urine by Automated test strip
64 | 53328-1 | Glucose [Mass/volume] in Urine by Automated test strip
65 | 53868-6 | Glucose tetrasaccharide/Creatinine [Molar ratio] in Urine
66 | 56124-1 | Glucose [Mass/volume] in Urine --1 hour post meal
67 | 5792-7 | Glucose [Mass/volume] in Urine by Test strip
68 | 57970-6 | Glucose [Mass/volume] in Urine --3 hours post 75 g glucose PO
69 | 59156-0 | Glucose [Moles/volume] in Urine by Automated test strip
70 | 6747-0 | Glucose [Presence] in Urine by Test strip --1 hour post 50 g lactose PO
71 | 6748-8 | Glucose [Presence] in Urine by Test strip --1 hour post 75 g glucose PO
72 | 6750-4 | Glucose [Presence] in Urine by Test strip --2 hours post 50 g lactose PO
73 | 6751-2 | Glucose [Presence] in Urine by Test strip --2 hours post 75 g glucose PO
74 | 6753-8 | Glucose [Presence] in Urine by Test strip --30 minutes post 50 g lactose PO
75 | 6754-6 | Glucose [Presence] in Urine by Test strip --30 minutes post 75 g glucose PO
76 | 6755-3 | Glucose [Presence] in Urine by Test strip --3 hours post 75 g glucose PO
77 | 6757-9 | Glucose [Presence] in Urine by Test strip --4 hours post 75 g glucose PO
78 | 6758-7 | Glucose [Presence] in Urine by Test strip --5 hours post 75 g glucose PO
79 | 6759-5 | Glucose [Presence] in Urine by Test strip --6 hours post 75 g glucose PO
80 | 6761-1 | Glucose [Presence] in Urine by Test strip --1.5 hours post 50 g lactose PO
81 | 6763-7 | Glucose [Presence] in Urine by Test strip --1.5 hours post 75 g glucose PO
82 | 74351-8 | Glucose [Moles/volume] in Urine collected for unspecifie

**Comment by pnrobinson** [comment]
These terms are mainly for glucose tolerance test. I do not think we want to have one term for each of them. Also, it is probably better to place this under some functional category. Let's consider.

**Comment by pnrobinson** [comment]
I would suggest that for now we do not annotate any of these terms. In the future, perhaps, we can work with EHR data and experts to figure out better rules to infer the actual result of these tests, "Impaired glucose tolerance", but I think it is not possible to do this in the current state of the project.
