### ISSUE TITLE
Loinc 5631-7:  "Copper [Mass/volume] in Serum or Plasma"

### ISSUE THREAD

**Issue by kingmanzhang** [obophenotype/human-phenotype-ontology#3788]
Suggest creating a new term for Loinc: 5631-7 [Copper [Mass/volume] in Serum or Plasma] 
New term label: Abnormal copper concentration in blood
New term comment (if any): and children terms
Your biocurator ID for loinc2hpo (if desired): JGM:azhang

**Comment by nicolevasilevsky** [comment]
need to figure out what this LOINC term means, we have 'High nonceruloplasmin-bound serum copper' HP_0010838

May need to add a new term

**Comment by kingmanzhang** [comment]
@nicolevasilevsky Our current annotation is good. This is for toxicity studies.
