### ISSUE TITLE
renal hypophosphatemia should be a child of abn physiology(?)

### ISSUE THREAD

**Issue by jmcmurry** [obophenotype/human-phenotype-ontology#3789]
It is a bit of an odd duck out there on its own but begs question as to whether chemistry is physiology per se.

https://www.ebi.ac.uk/ols/ontologies/hp/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FHP_0008732

**Comment by pnrobinson** [comment]
I have added a definition

Renal hypophosphatemia is defined as reduced serum phosphate (e.g., below 0.70 mmol/l) and an inappropriately high renal phosphate excretion.

The logical definition was wrong, I have deleted it
```
'has part' some 
    (Hypophosphatemia
     and ('inheres in' some kidney)
     and ('has modifier' some abnormal))
```

**Comment by pnrobinson** [comment]
This is a bundled term, but it is useful and I think justified. It is one of many terms that is somewhere in between pure morphology and physiology. I think we should leave it where it is for now, because there are lots of different things that can cause it.
