### ISSUE TITLE
NTR: venom hypersensitivty

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3795]
New term request: venom hypersensitivty. Synonyms: IgE- mediated venom hypersensitivity, venom allergy\
Definition: \
Source: \
Parent: \
Disease association: immunologic hypersensitivity

**Comment by LCCarmody** [comment]
- [ ] Proposed definition "A form of hypersensitivity that is triggered by exposure to venom"
- [ ] Parent term: Immunologic hypersensitivity  https://hpo.jax.org/app/browse/term/HP:0100326

Note: Venom-induced anaphylaxis has been added. https://hpo.jax.org/app/browse/term/HP:0500096

**Comment by pnrobinson** [comment]
A think the venom analphylaxis is the term.
