### ISSUE TITLE
NTR: hereditary angioedema

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3798]
New term request: hereditary angioedema. Synonyms: \
Definition: \
Source: \
Parent: \
Disease association: angioedema

**Comment by LCCarmody** [comment]
- [ ] Angioedema https://hpo.jax.org/app/browse/term/HP:0100665 is already a term and Angioedema, Hereditary is listed as a disease (OMIM:106100, OMIM:610618, ORPHA:91378)
- [ ] If this is still a phenotype, could we add the modifier 'Autosomal recessive inheritance (https://hpo.jax.org/app/browse/term/HP:0000007) or 'Familial predisposition'  (https://hpo.jax.org/app/browse/term/HP:0000005) or other type of inheritance?

**Comment by pnrobinson** [comment]
This is a disease description e.g., https://hpo.jax.org/app/browse/disease/ORPHA:91378
