### ISSUE TITLE
NTR: angioedema with urticaria

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3799]
New term request: angioedema with urticaria. Definition: \
Source: \
Parent: \
Disease association:

**Comment by LCCarmody** [comment]
- [ ] Both angioedema ( https://hpo.jax.org/app/browse/term/HP:0100665 ) and Uticaria ( https://hpo.jax.org/app/browse/term/HP:0001025 )are present in the HPO.  Is it a different phenotype when combine?

**Comment by pnrobinson** [comment]
I think these are bundled terms, and annotation should use the individual HPO terms
