### ISSUE TITLE
NTR: angioedema without urticaria

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3800]
New term request: angioedema without urticaria. Definition: \
Source: \
Parent: \
Disease association:

**Comment by LCCarmody** [comment]
- [ ] Is this a distinctly separate phenotype from Angioedema https://hpo.jax.org/app/browse/term/HP:0100665 ?

**Comment by pnrobinson** [comment]
I think these are bundled terms, and annotation should use the individual HPO terms
