### ISSUE TITLE
NTR: idiopathic angioedema

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3801]
New term request: idiopathic angioedema. Definition: \
Source: \
Parent: \
Disease association:

**Comment by LCCarmody** [comment]
- [ ] In general, prefer not to use 'idiopathic' because that is a cause.  Angioedema ( https://hpo.jax.org/app/browse/term/HP:0100665 )  is present as an HPO term and disease.

**Comment by pnrobinson** [comment]
I think we should not create a separate HPO term, the phenotype is simply Angioedema.
