### ISSUE TITLE
NTR: exercise induced anaphylaxis

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3802]
New term request: exercise induced anaphylaxis. Synonyms: \
Definition: \
Source: \
Parent: \
Disease association: anaphylaxis

**Comment by LCCarmody** [comment]
- [ ] Term already added https://hpo.jax.org/app/browse/term/HP:0410139

**Comment by pnrobinson** [comment]
closed since term exists
