### ISSUE TITLE
NTR: food induced anaphylaxis

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3803]
New term request: food induced anaphylaxis. Synonyms: \
Definition: \
Source: \
Parent: \
Disease association: anaphylaxis

**Comment by LCCarmody** [comment]
- [ ] Term already added: https://hpo.jax.org/app/browse/term/HP:0500095

**Comment by pnrobinson** [comment]
closing, term added previously
