### ISSUE TITLE
NTR: idiopathic anaphylaxis

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3805]
New term request: idiopathic anaphylaxis. Synonyms: \
Definition: \
Source: \
Parent: \
Disease association: anaphylaxis

**Comment by LCCarmody** [comment]
- [ ] Term already added: https://hpo.jax.org/app/browse/term/HP:0410148
- [ ] Generally, we don't use 'idiopathic' because it defines cause and not phenotype.

**Comment by pnrobinson** [comment]
closed since term exists
