### ISSUE TITLE
NTR: alpha-gal syndrome

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3807]
New term request: alpha-gal syndrome. Synonyms: \
Definition: \
Source: \
Parent: \
Disease association: delayed anaphylaxis

**Comment by LCCarmody** [comment]
- [  ] This is a disease and should be added to MONDO? @cmungall @nicolevasilevsky @pnrobinson 
- [  ] Possibly, could the term be 'Alpha-gal allergy' or 'Meat allergy'?
- [  ] Possible source: https://www.ncbi.nlm.nih.gov/pubmed/29986992

**Comment by nicolevasilevsky** [comment]
this is in MONDO: MONDO_0100001 'alpha-gal syndrome'
syn: allergic galactose-alpha-1,3-galactose disease

**Comment by LCCarmody** [comment]
@nicolevasilevsky Thanks. Not sure how I missed that!

**Comment by pnrobinson** [comment]
What about Increased alpha-gal immunoglobulin E
