### ISSUE TITLE
NTR: eosinophilic esophagitis

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3809]
New term request: eosinophilic esophagitis. Synonyms: \
Definition: \
Source: \
Parent: \
Disease association: eosinaphilic gastrointestinal disease

**Comment by LCCarmody** [comment]
- [ ] This is a disease MONDO:0005361 https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0005361

**Comment by LCCarmody** [comment]
#3956 is a duplicate. Closing.
