### ISSUE TITLE
NTR: eosinophilic colitis

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3810]
New term request: eosinophilic colitis. Synonyms: \
Definition: \
Source: \
Parent: \
Disease association: eosinaphilic gastrointestinal disease

**Comment by LCCarmody** [comment]
- [ ] This is a disease: MONDO:0018439 https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0018439

**Comment by LCCarmody** [comment]
#3972 Is a duplicate.  Closing.
