### ISSUE TITLE
NTR: eosinaphilic gastrointestinal disease

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3811]
New term request: eosinaphilic gastrointestinal disease. Definition: \
Source: \
Parent: \
Disease association:

**Comment by LCCarmody** [comment]
- [ ] Term misspelled: Possibly 'eosinaphilic gastrointestinal disease'?
- [ ] Term is a disease: MONDO:0018438 https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0018438
