### ISSUE TITLE
NTR: eosinaphilic gastritis

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3812]
New term request: eosinaphilic gastritis. Synonyms: \
Definition: \
Source: \
Parent: \
Disease association: eosinaphilic gastrointestinal disease

**Comment by LCCarmody** [comment]
- [ ] Term misspelled: Possibly 'eosinophilic gastritis'
- [ ]Term is a disease? MONDO:0002840  https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0002840

**Comment by LCCarmody** [comment]
#3962 is a duplicate. Closing.
