### ISSUE TITLE
NTR: Food protein-induced enterocolitis syndrome

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3813]
New term request: Food protein-induced enterocolitis syndrome. Definition: \
Source: \
Parent: \
Disease association:

**Comment by LCCarmody** [comment]
- [ ] This is a disease: MONDO:0100008 https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0100008

**Comment by pnrobinson** [comment]
This is a disease, closing the issue
