### ISSUE TITLE
NTR: allergic proctocolitis

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3814]
New term request: allergic proctocolitis. Synonyms: milk protein proctocololitis\
Source: \
Parent: \
Disease association:

**Comment by LCCarmody** [comment]
- [ ] The term Proctocolitis is a disease: MONDO:0024278 https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0024278 
- [ ] Is the term Proctocolitis sufficient? or should 'Allergic proctocolitis' be added to Mondo? @pnrobinson

**Comment by pnrobinson** [comment]
I think this is definitely a disease
see
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4405595/
I will put reference this on the MONDO tracker. @nicolevasilevsky

**Comment by pnrobinson** [comment]
Sorry, I see Nicole already took care of this
https://github.com/monarch-initiative/mondo/issues/101
