### ISSUE TITLE
NTR: monoclonal mast cell activation syndrome

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3815]
New term request: monoclonal mast cell activation syndrome. Definition: \
Source: \
Parent: \
Disease association:

**Comment by LCCarmody** [comment]
- [ ] Should this be considered a collection of phenotypes or a separate term for MONDO? 
- [ ] If added to MONDO, Mast cell activation disorder (MCAD) should be parent and idiopathic mast cell activation syndrome (MCAS) should be added as a sibling. https://www.ncbi.nlm.nih.gov/pubmed/23642289 
@pnrobinson

**Comment by nicolevasilevsky** [comment]
I have an open PR for Mast cell activation syndrome:
https://github.com/monarch-initiative/mondo/pull/266, waiting for @cmungall to approve.

idiopathic mast cell activation syndrome (MCAS) was added as a child.

**Comment by pnrobinson** [comment]
I think this is a disease and not a phenotype, closing.
