### ISSUE TITLE
NTR: physical urticaria

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3816]
New term request: physical urticaria. Synonyms: \
Definition: \
Source: \
Parent: \
Disease association: urticaria

**Comment by LCCarmody** [comment]
- [ ] This is a term: https://hpo.jax.org/app/browse/term/HP:0410134

**Comment by LCCarmody** [comment]
- [ ] Change the hierarchy to include-
        Dermatographic urticaria HP:0011971
