### ISSUE TITLE
NTR: idiopathic urtcaria

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3821]
New term request: idiopathic urtcaria. Synonyms: \
Definition: \
Source: \
Parent: \
Disease association: physical urticaria

**Comment by LCCarmody** [comment]
- [ ] Is this a separate phenotype from Urticaria https://hpo.jax.org/app/browse/term/HP:0001025 ? Chronic idiopathic urticaria is present: https://hpo.jax.org/app/browse/term/HP:0410133.

**Comment by pnrobinson** [comment]
I think this is covered by https://hpo.jax.org/app/browse/term/HP:0410133
