### ISSUE TITLE
NTR: chronic idiopathic urticaria

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3823]
New term request: chronic idiopathic urticaria. Definition: \
Source: \
Parent: \
Disease association:

**Comment by LCCarmody** [comment]
- [ ] This term is present: https://hpo.jax.org/app/browse/term/HP:0410133

**Comment by LCCarmody** [comment]
- [ ] make this a disease? Chronic and acute are the phenotype but maybe use the modifier.

**Comment by pnrobinson** [comment]
closing-- I think this can be a feature of other diseases so let's leave it as an HPO term
