### ISSUE TITLE
NTR: vocal cord dysfunction

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3824]
New term request: vocal cord dysfunction. Synonyms: \
Definition: \
Source: \
Parent: \
Disease association: Abnormality of the vocal cords

**Comment by LCCarmody** [comment]
- [ ] This is a term: https://hpo.jax.org/app/browse/term/HP:0031801

**Comment by pnrobinson** [comment]
closing because term exists
