### ISSUE TITLE
NTR: Mastocytosis

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3825]
New term request: Mastocytosis. Synonyms: \
Definition: *reference\
Source: *reference\
Parent: \
Disease association:

**Comment by LCCarmody** [comment]
- [ ] This is a term: https://hpo.jax.org/app/browse/term/HP:0100495

**Comment by LCCarmody** [comment]
- [ ] Note: this is also a MONDO term: MONDO:0007950 https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0007950

**Comment by pnrobinson** [comment]
Closing since term already exists
