### ISSUE TITLE
NTR: Cutaneous mastocytosis 

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3826]
New term request: Cutaneous mastocytosis . Synonyms: Abnormality of mast cells\
Definition: *reference\
Source: *reference\
Parent: \
Disease association:

**Comment by LCCarmody** [comment]
- [ ] Note: this is also a MONDO term:MONDO:0019023 https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0019023

**Comment by pnrobinson** [comment]
Closing since term already exists
