### ISSUE TITLE
NTR: Diffuse cutaneous mastocytosis

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3827]
New term request: Diffuse cutaneous mastocytosis. Synonyms: Abnormality of mast cells\
Definition: *reference\
Source: *reference\
Parent: \
Disease association: Cutaneous mastocytosis

**Comment by LCCarmody** [comment]
- [ ] Note: this is also a MONDO term MONDO:0019315 https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0019315

**Comment by pnrobinson** [comment]
cutaneous mastocytosis is already a term
https://hpo.jax.org/app/browse/term/HP:0200151
If 'diffuse' needs to be annotated, please use the modifier term "Diffuse"
https://hpo.jax.org/app/browse/term/HP:0020034
