### ISSUE TITLE
NTR: Eosinophilic cholecystitis

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3833]
New term request: Eosinophilic cholecystitis. Synonyms: \
Definition: Inflammatory condition of the gallbladder, confirmed by a cellular infiltrate comprised of >90% eosinophils within the gallbladder\
Source: Inflammatory condition of the gallbladder, confirmed by a cellular infiltrate comprised of >90% eosinophils within the gallbladder\
Parent: https://www.ncbi.nlm.nih.gov/pubmed/17522376\
Disease association: Eosinophilia

**Comment by LCCarmody** [comment]
#3952 is a duplicate. Closing.
