### ISSUE TITLE
NTR: Eosinophilic cystitis

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3834]
New term request: Eosinophilic cystitis. Synonyms: \
Definition: Characterized by transmural inflammation of the bladder predominantly with eosinophils, associated with fibrosis with or without muscle necrosis\
Source: Characterized by transmural inflammation of the bladder predominantly with eosinophils, associated with fibrosis with or without muscle necrosis\
Parent: https://www.ncbi.nlm.nih.gov/pubmed/15857336\
Disease association: Eosinophilia

**Comment by LCCarmody** [comment]
#3953 is a duplicate. Closing.
