### ISSUE TITLE
NTR: Drug rash with eosinophilia and systemic symptoms

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3839]
New term request: Drug rash with eosinophilia and systemic symptoms. Synonyms: DRESS\
Definition: Distinct, severe, idiosyncratic reaction to a drug characterized by a prolonged latency period\
Source: Distinct, severe, idiosyncratic reaction to a drug characterized by a prolonged latency period\
Parent: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3718748/\
Disease association: Eosinophilic skin disorders

**Comment by LCCarmody** [comment]
#3958 is a duplicate. Closing.
