### ISSUE TITLE
NTR: Eosinophilic enteritis

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3845]
New term request: Eosinophilic enteritis. Synonyms: Eosinophilic gastroenteritis, EGE\
Definition: Characterized by eosinophilic infiltration of the bowel wall with various gastrointestinal manifestations\
Source: Characterized by eosinophilic infiltration of the bowel wall with various gastrointestinal manifestations\
Parent: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3746377/\
Disease association: Eosinophilic gastrointestinal disease

**Comment by LCCarmody** [comment]
#3964 is a duplicate. Closing.
