### ISSUE TITLE
NTR: Eosinophilic myositis

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3846]
New term request: Eosinophilic myositis. Synonyms: \
Definition: Heterogeneous group of disorders characterized by eosinophil infiltration of skeletal muscle of undetermined cause and multiple organ system dysfunction\
Source: Heterogeneous group of disorders characterized by eosinophil infiltration of skeletal muscle of undetermined cause and multiple organ system dysfunction\
Parent: https://www.ncbi.nlm.nih.gov/pubmed/24424174\
Disease association: Eosinophilia

**Comment by LCCarmody** [comment]
#3965 is a duplicate. Closing.
