### ISSUE TITLE
NTR: Chronic eosinophilic pneumonia

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3847]
New term request: Chronic eosinophilic pneumonia. Synonyms: CEP\
Definition: Characterized by chronic respiratory and general symptoms, alveolar and/or blood eosinophilia, and peripheral pulmonary infiltrates\
Source: Characterized by chronic respiratory and general symptoms, alveolar and/or blood eosinophilia, and peripheral pulmonary infiltrates\
Parent: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1464381/\
Disease association: Respiratory Disorders

**Comment by LCCarmody** [comment]
#3966 is a duplicate. Closing.
