### ISSUE TITLE
NTR: Myeloid hypereosinophilic syndrome without abnormalities of PDGFRA, PDGFRB or FGFR1, JAK2

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3848]
New term request: Myeloid hypereosinophilic syndrome without abnormalities of PDGFRA, PDGFRB or FGFR1, JAK2. Synonyms: Clonal hypereosinophilic syndrome, HES-M, HES-N\
Definition: A myeloproliferative disorder characterized by persistent eosinophilia that is associated with damage to multiple organs\
Source: A myeloproliferative disorder characterized by persistent eosinophilia that is associated with damage to multiple organs\
Parent: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2045078/\
Disease association: Eosinophilia

**Comment by LCCarmody** [comment]
#3967 is a duplicate. Closing.
