### ISSUE TITLE
NTR: Lymphoid hypereosinophilic syndrome

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3849]
New term request: Lymphoid hypereosinophilic syndrome. Synonyms: L-HES; lymphocytic hypereosinophilic syndrome\
Definition: Subtype of hypereosinophilic syndrome defined by the presence of a monoclonal T cell population detected in conjunction with immunophenotypically aberrant T cell populations. \
Source: Subtype of hypereosinophilic syndrome defined by the presence of a monoclonal T cell population detected in conjunction with immunophenotypically aberrant T cell populations. \
Parent: http://www.hematology.org/Thehematologist/Mini-Review/7884.aspx\
Disease association: Eosinophilia

**Comment by LCCarmody** [comment]
#3968 is a duplicate. Closing.
