### ISSUE TITLE
NTR: Idiopathic hypereosinophilic syndrome

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3850]
New term request: Idiopathic hypereosinophilic syndrome. Synonyms: IHES\
Definition: Characterized by persistently elevated eosinophil counts without any underlying cause\
Source: Characterized by persistently elevated eosinophil counts without any underlying cause\
Parent: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4299705/\
Disease association: Eosinophilia

**Comment by LCCarmody** [comment]
#3969 is a duplicate. Closing.
