### ISSUE TITLE
NTR: IgG4-related eosinophilic angiocentric fibrosis

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3855]
New term request: IgG4-related eosinophilic angiocentric fibrosis. Synonyms: EAF\
Definition: Tumefactive lesion of the orbit and upper respiratory tract of unknown etiology characterized histologically by concentric layers of fibrosis around small-caliber arteries and a mixed inflammatory infiltrate dominated by eosinophils\
Source: Tumefactive lesion of the orbit and upper respiratory tract of unknown etiology characterized histologically by concentric layers of fibrosis around small-caliber arteries and a mixed inflammatory infiltrate dominated by eosinophils\
Parent: https://www.ncbi.nlm.nih.gov/pubmed/21502911\
Disease association: Eosinophilia

**Comment by LCCarmody** [comment]
#3974 is a duplicate. Closing.
