### ISSUE TITLE
NTR: Eosinophilic lymphogranuloma

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3856]
New term request: Eosinophilic lymphogranuloma. Synonyms: Kimura's disease\
Definition: Chronic inflammatory disorder characterized by head and neck lymphadenopathy often accompanied by eosinophilia and elevated serum IgE. \
Source: Chronic inflammatory disorder characterized by head and neck lymphadenopathy often accompanied by eosinophilia and elevated serum IgE. \
Parent: https://www.researchgate.net/publication/263324144_Kimura's_Disease_in_a_Caucasian_Female_A_Very_Rare_Cause_of_Lymphadenopathy\
Disease association: Eosinophilic skin disorders

**Comment by LCCarmody** [comment]
#3975 is a duplicate. Closing.
