### ISSUE TITLE
NTR: Acute eosinophilic pneumonia

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3857]
New term request: Acute eosinophilic pneumonia. Synonyms: AEP\
Definition: Characterized by acute febrile respiratory failure associated with diffuse radiographic infiltrates and pulmonary eosinophilia\
Source: Characterized by acute febrile respiratory failure associated with diffuse radiographic infiltrates and pulmonary eosinophilia\
Parent: https://www.atsjournals.org/doi/abs/10.1164/rccm.2112056\
Disease association: Respiratory Disorders

**Comment by LCCarmody** [comment]
#3976  is a duplicate. Closing.
