### ISSUE TITLE
NTR: Endomyocardial fibrosis

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3858]
New term request: Endomyocardial fibrosis. Synonyms: Loeffler's endocarditis; eosinophilic endocarditis; EMF; tropical endomyocardial fibrosis\
Definition: Restrictive cardiomyopathy of unknown cause characterized by the deposition of fibrous tissue in the endomyocardium, which leads to a restrictive physiology
Source: Restrictive cardiomyopathy of unknown cause characterized by the deposition of fibrous tissue in the endomyocardium, which leads to a restrictive physiology
Parent: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5634427/
Disease association: Eosinophilia

**Comment by LCCarmody** [comment]
#3977 is a duplicate. Closing.

**Comment by pnrobinson** [comment]
This is https://hpo.jax.org/app/browse/term/HP:0006685.
Updating the definition a bit
