### ISSUE TITLE
NTR: Eosinophilic cellulitis

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3859]
New term request: Eosinophilic cellulitis. Synonyms: Well's syndrome\
Definition: A recurrent inflammatory granulomatous dermatitis with eosinophila\
Source: A recurrent inflammatory granulomatous dermatitis with eosinophila\
Parent: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3383552/\
Disease association: Eosinophilic skin disorders

**Comment by LCCarmody** [comment]
#3978 is duplicate. Closing.
