### ISSUE TITLE
NTR: Increased CD3 positive T-cells

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3907]
New term request: Increased CD3 positive T-cells. Definition: \
Source: \
Parent: \
Disease association:

**Comment by pnrobinson** [comment]
- [ ] Aren't T cells (nearly) always CD3 positive? Please provide more detail

**Comment by MorganSimiluk** [comment]
Sorry for the long delay here.  Yes, T cells are typically CD3 positive.  So I believe this term suggestion was as much about increased T cells as increased DC3 positive T cells.  Immunologists sometimes add a CD marker so they can be specific about how they are defining the T cells in reference.  Perhaps this term is better revisited more systematically with the flow cytometry project.

**Comment by pnrobinson** [comment]
OK, then I think for now the term Increase T Cell Count can be used
https://hpo.jax.org/app/browse/term/HP:0100828
We can also consider increased proportion of T cells/total lymphocyte count if also needed.
