### ISSUE TITLE
NTR: Kartagener syndrome

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3912]
New term request: Kartagener syndrome. Synonyms: Immotile ciliary syndrome, Primary ciliary dyskinesia, PCD\
Source: \
Parent: \
Disease association:

**Comment by pnrobinson** [comment]
- [ ] THis is a disease, see e g https://hpo.jax.org/app/browse/disease/OMIM:244400

**Comment by nicolevasilevsky** [comment]
this term is in MONDO: MONDO_0016575 'primary ciliary dyskinesia' (Kartagener syndrome is a syn)

**Comment by pnrobinson** [comment]
Closing since this is not a phenotype
