### ISSUE TITLE
NTR: Mallory-Weiss syndrome

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3929]
New term request: Mallory-Weiss syndrome. Synonyms: MWS\
Source: \
Parent: \
Disease association:

**Comment by pnrobinson** [comment]
- [ ] I think that the phenotype term should be Mallory-Weiss tear with def=A longitudinal mucosal laceration at the gastroesophageal junction or gastric cardia. 
- [ ] The disease Mallory-Weiss syndrome would then be characterized by Mallory Weiss tear, and  terms such as hematemesis https://hpo.jax.org/app/browse/term/HP:0002248  @nicolevasilevsky

**Comment by pnrobinson** [comment]
- [ ] This could be the parent of MW tear: https://hpo.jax.org/app/browse/term/HP:0004295

**Comment by nicolevasilevsky** [comment]
This term is in MONDO: MONDO_0043247

**Comment by pnrobinson** [comment]
adding term as HP_0002031
