### ISSUE TITLE
NTR: Meniere disease

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3930]
New term request: Meniere disease. Synonyms: \
Definition: \
Source: \
Parent: \
Disease association:

**Comment by pnrobinson** [comment]
A disease. See here: https://hpo.jax.org/app/browse/disease/OMIM:156000

**Comment by nicolevasilevsky** [comment]
this is in MONDO: MONDO_0007972

**Comment by pnrobinson** [comment]
Closing because this is a disease
