### ISSUE TITLE
NTR: Urinary tract pain

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3940]
New term request: Urinary tract pain. Definition: \
Source: \
Parent: \
Disease association:

**Comment by pnrobinson** [comment]
- [ ] Can we make this more specific?

**Comment by MorganSimiluk** [comment]
Hmmm... a term like interstitial cystitis seems too specific and is actually a cause of pain.  More 'disease' than 'feature/phenotype.' 

What do you think of the approach of choosing the HPO term, "Pain" then modifying with 'localized pain' and a comment saying bladder [in phenotips]?

**Comment by MorganSimiluk** [comment]
Bladder pain would also be acceptable.
