### ISSUE TITLE
NTR: Chronic eosinophilic pneumonia

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3966]
New term request: Chronic eosinophilic pneumonia. Synonyms: CEP\
Definition: Characterized by chronic respiratory and general symptoms, alveolar and/or blood eosinophilia, and peripheral pulmonary infiltrates
Source: Characterized by chronic respiratory and general symptoms, alveolar and/or blood eosinophilia, and peripheral pulmonary infiltrates
Parent: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1464381/
Disease association: Respiratory Disorders

**Comment by pnrobinson** [comment]
This is a disease with the phenotypic features (most of which are in HPO)
- [ ] NTR bronchoalveolar lavage eosinophilia (NTR), proposaed synonym alveolar eosinophilia,

Also, add to MONDO @nicolevasilevsky @cmungall

**Comment by nicolevasilevsky** [comment]
Chronic eosinophilic pneumonia is in MONDO_0004806

**Comment by cmungall** [comment]
Thanks! Nicole, can you add mondo tickets for these issues? For each one 
do a search in bioportal to see if this is already represented anywhere

**Comment by pnrobinson** [comment]
This is actually a disease. I am adding a term HP_0032071
Eosinophilic pulmonary infiltration, (which is a feature of various diseases), defined as
The presence of eosinophils in the lungs as detected by bronchoalveolar lavage or tissue biopsy, with or without blood eosinophilia.
