### ISSUE TITLE
NTR: Eosinophilic lymphogranuloma

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3975]
New term request: Eosinophilic lymphogranuloma. Synonyms: Kimura's disease
Definition: Chronic inflammatory disorder characterized by head and neck lymphadenopathy often accompanied by eosinophilia and elevated serum IgE. 
Source: Chronic inflammatory disorder characterized by head and neck lymphadenopathy often accompanied by eosinophilia and elevated serum IgE. 
Parent: https://www.researchgate.net/publication/263324144_Kimura's_Disease_in_a_Caucasian_Female_A_Very_Rare_Cause_of_Lymphadenopathy
Disease association: Eosinophilic skin disorders

**Comment by pnrobinson** [comment]
- [ ] THis is a disease @nicolevasilevsky (MONDO), but we should check if the lymphadenopathy has a specific phenotypic appearance.

**Comment by nicolevasilevsky** [comment]
this is a syn for MONDO_0018830 'Kimura disease'

**Comment by pnrobinson** [comment]
Orphanet has a great description of the disease
https://www.orpha.net/data/patho/GB/uk-kimura.pdf
Here is a relevant article
http://www.scielo.br/scielo.php?pid=s0365-05962006000200009&script=sci_arttext&tlng=en
THe term'eosinophilic lymphoid follicular hyperplasia' has been used as a synoynm for Kimura's disease, but I think it is also a good name for one of the phenotypic features seen in the disease,

**Comment by nicolevasilevsky** [comment]
ok, so it should be added as a new term in HPO?

**Comment by pnrobinson** [comment]
This is a disease and thus not a good HPO term.
