### ISSUE TITLE
NTR: Eosinophilic cellulitis

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3978]
New term request: Eosinophilic cellulitis. Synonyms: Well's syndrome
Definition: A recurrent inflammatory granulomatous dermatitis with eosinophila
Source: A recurrent inflammatory granulomatous dermatitis with eosinophila
Parent: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3383552/
Disease association: Eosinophilic skin disorders

**Comment by pnrobinson** [comment]
- [ ] This is a disease rather than a phenotype (@cmungall @nicolevasilevsky ). There are two main symptoms, 

Wells’ syndrome, also known as eosinophilic cellulitis, was first described by Dr GC Wells in 1971 as a recurrent granulomatous dermatitis with eosinophila

There are myriad cutaneous lesions with associated erythema, presenting as blisters, bullae, papules and/or nodules.

- [ ] Therefore, should we have a NTR for Granulomatous dermatitis. This can present linear subcutaneous cords, known as rope sign.

- Possible parent
https://hpo.jax.org/app/browse/term/HP:0002955

**Comment by nicolevasilevsky** [comment]
We have Wells Syndrome in MONDO (MONDO_0019547) and Eosinophilic cellulitis is a synonym.

**Comment by pnrobinson** [comment]
I will add a term
HP_0032022: Eosinophilic dermal infiltration
(Synonym eosinophilic dermatitis)
Def: Presence of abnormally increased amounts of intraepidermal inflammatory cells with a predominance of eosinophils.
