### ISSUE TITLE
Synonym of HP:0045063 (Increased PIVKA-II)

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#3984]
What should the definition really read? Currently it is : _Increased protein increased in vitamin K's absence-II_

Currently it makes not too much sense because of the strange name that PIVKA stands for.

@pnrobinson

**Comment by pnrobinson** [comment]
Ups. PIVKA-II is an acronym for prothrombin induced by vitamin K absence-II (PIVKA-II) 
Def: Prothrombin induced by vitamin K absence-II (PIVKA-II) is an abnormal prothrombin protein that is elevated in hepatocellular carcinoma.PMID:25852278

**Comment by drseb** [comment]
Sorry @pnrobinson . The def of the class is correct, but what I wrote is an _exact synonym_. Should we change/remove it?

**Comment by pnrobinson** [comment]
The exact synonym should be 
Increased prothrombin induced by vitamin K absence-II
