### ISSUE TITLE
Eythromelalgia

### ISSUE THREAD

**Issue by andrewdevereau** [obophenotype/human-phenotype-ontology#3985]
submitted on behalf of David Bennett, Professor of neurology and neurobiology, Nuffield department of clinical neurosciences, Uni. of Oxford

_For new term requests, please provide us with the following information:_
### 1. Preferred term label
Primary erythromelalgia

### 3. Textual definition (should be understandable even for non-specialists, please include a PubMed ID for relevant articles providing additional information about the suggestion)
Pain and erythema of the extremities that is exacerbated by warming and relieved by cooling. Initially episodic but may become persistent.
PMID: 14985375
PMID: 24813307

### 4. Parent term (use [HPO Browser](http://compbio.charite.de/hpoweb/showterm?id=HP:0000118) or [OLS](http://www.ebi.ac.uk/ols/ontologies/hp))
Chronic pain HP:0012532

### 5. Which diseases are characterized by this term ? (e.g. Orphanet- or OMIM-id)
Primary erythromelalgia – OMIM 133020

### 6. Your nano-attribution (ORCID-id or label, e.g. _HPO:probinson_ (organization:name))
https://orcid.org/0000-0002-1089-1543

**Comment by pnrobinson** [comment]
@andrewdevereau  This is a disease that is characterized by a number of phenotypic features. I think that the primary phenotypic characteristic, that is not currently in HPO, is something like this

Episodic painful reddish skin discoloration

This itself is a bundled term, but because it occurs in an atomic way in Primary erythromelalgia and some other diseases, I think it is appropriate to be an HPO term.

**Comment by pnrobinson** [comment]
I am thinking that probably "Erythromelalgia" is the best primary term label with definition
Def: Recurrent episodes of redness, burning pain, and warmth of the extremities following exposure to heat or exercise with symptoms predominantly involving the feet. 
Comment: Warmth, ambulation, physical exercise, sitting, leg dependence and wearing shoes or gloves can provoke and aggravate symptoms while immersion in ice/cold water, uncovering affected areas, ventilation and elevation can ameliorate these symptoms. Pain attacks usually start with an itchy-like feeling and then progress to a severe burning sensation as was reported by most patients, with the durations of which ranging from several minutes to hours and even days. Erythromelalgia can be a Mendelian trait or can be triggered by polycythemia vera, lymphoproliferative disorders, hypertension, and hyperviscosity.

**Comment by pnrobinson** [comment]
Adding term as HP:0032147
