### ISSUE TITLE
Paroxysmal Extreme Pain Disorder 

### ISSUE THREAD

**Issue by andrewdevereau** [obophenotype/human-phenotype-ontology#3987]
submitted on behalf of David Bennett, Professor of neurology and neurobiology, Nuffield department of clinical neurosciences, Uni. of Oxford

_For new term requests, please provide us with the following information:_
### 1. Preferred term label
Paroxysmal extreme pain disorder

### 3. Textual definition (should be understandable even for non-specialists, please include a PubMed ID for relevant articles providing additional information about the suggestion)
Paroxysmal extreme pain disorder (formerly known as familial rectal pain) is characterised by paroxysmal episodes of severe perineal and rectal, ocular, and mandibular pain. Pain is associated with autonomic features that can include flushing (which sometimes results in harlequin colour change), lacrimation, rhinorrhoea, and tonic attacks with apnoea and bradycardia. 
PMID: 17679678
PMID: 24813307

### 4. Parent term (use [HPO Browser](http://compbio.charite.de/hpoweb/showterm?id=HP:0000118) or [OLS](http://www.ebi.ac.uk/ols/ontologies/hp))
Chronic pain HP:0012532

### 5. Which diseases are characterized by this term ? (e.g. Orphanet- or OMIM-id)
Paroxysmal Extreme Pain Disorder OMIM: 167400	

### 6. Your nano-attribution (ORCID-id or label, e.g. _HPO:probinson_ (organization:name))
https://orcid.org/0000-0002-1089-1543

**Comment by pnrobinson** [comment]
This is also a disease entity and not a phenotypic feature. 
I am adding a term for the primary phenotypic feature of this disease,
Paroxysmal rectal pain (HP:0032150)
