### ISSUE TITLE
Small fibre neuropathy

### ISSUE THREAD

**Issue by andrewdevereau** [obophenotype/human-phenotype-ontology#3988]
submitted on behalf of David Bennett, Professor of neurology and neurobiology, Nuffield department of clinical neurosciences, Uni. of Oxford

_For new term requests, please provide us with the following information:_
### 1. Preferred term label
Small fibre neuropathy

### 3. Textual definition (should be understandable even for non-specialists, please include a PubMed ID for relevant articles providing additional information about the suggestion)
Small fibre neuropathy is characterised by structural injury selectively affecting small diameter sensory and/or autonomic axons.  The clinical presentation is dominated by pain. 
Small fibre neuropathy is defined by symptoms (pain and altered temperature sensibility) in hands and feet, clinical signs (reduced pin prick sensitivity and ability to discriminate warm/cool) of small fibre damage, normal nerve conduction studies, and can be confirmed through the investigations that include lowered intra-epidermal nerve fibre density at the ankle and/or abnormal quantitative sensory testing of thermal thresholds at the foot.
PMID: 18524793
PMID: 22641108

### 4. Parent term (use [HPO Browser](http://compbio.charite.de/hpoweb/showterm?id=HP:0000118) or [OLS](http://www.ebi.ac.uk/ols/ontologies/hp))
Sensory neuropathy HP:0000763

### 5. Which diseases are characterized by this term ? (e.g. Orphanet- or OMIM-id)
OMIM: 133020, 615551, 615552

### 6. Your nano-attribution (ORCID-id or label, e.g. _HPO:probinson_ (organization:name))
https://orcid.org/0000-0002-1089-1543

**Comment by pnrobinson** [comment]
This entity is a disease that is characterized by a number of phenotypic features. I have added the ones that overlap with erythromelalgia and I think the remaining features were previously represented in HPO. Please reopen this issue if phenotypic features are missing!
