### ISSUE TITLE
Loinc 80700-8:  "CD25+CD127- (regulatory T) cells/100 CD3+CD4+ cells in Blood"

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#3991]
Suggest creating a new term for Loinc: 80700-8 [CD25+CD127- (regulatory T) cells/100 CD3+CD4+ cells in Blood] 

New term comment (if any): Do we want to annotate ratios, such as this?

Your biocurator ID for loinc2hpo (if desired): HPO:nvasilevsky

**Comment by pnrobinson** [comment]
adding as HP_0020111, @kingmanzhang

**Comment by kingmanzhang** [comment]
done
