### ISSUE TITLE
do we want various CD marker phenotypes?

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#3994]
I think this has been brought up before but I don't remember the consensus - there are lot of blood phenotypes in LOINC with various combinations of CD markers. Do we want HPO classes for all of these?

related: #3993, #3992, #3991, #3990

**Comment by pnrobinson** [comment]
The combinations of surface markers operationally define immune cell subsets, and after some discussions with Derya I thnk it is probably better to use the marker combinations rather than descriptive terminology. This is a major question for the NIAID workshop.

**Comment by nicolevasilevsky** [comment]
hold off on making marker terms for now
@pnrobinson consider discussing with folks in Vienna

**Comment by pnrobinson** [comment]
After lots of dicussions, the consensus is not to name the terms according to the surface markers if it is possible to assign them to immune cell subtypes. There are two reasons: (1) different labs use different markers (2) the markers used change with time. We should therefore mainly go with categories suchas 'Naive T-cell' and define them using 'typical' combinations of markers in the definition.
