### ISSUE TITLE
Wrong synonym in HP:0009623 (Proximal placement of thumb)

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#3997]
- Low implantation of the thumb 
- --> **_Proximally placed halluces_**  <<--
- Proximally placed thumbs

**Comment by drseb** [comment]
Question. Simply remove? Or shall we move to another class?

**Comment by pnrobinson** [comment]
hallux is the big toe, so this does not belong here.

**Comment by pnrobinson** [comment]
I will add the synonym to 
https://hpo.jax.org/app/browse/term/HP:0011926
using the 'plural form' synonym type.
