### ISSUE TITLE
Allergy hierarchy suggestion

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#3999]
Allergy
    -Food
      --cow milk
      --peanut
      --
      --IgE mediated
      --non-IgE mediate
 
     -airborne/Environmental
         --indoor/outdoor
               ---dust mite
               ---pollen
               ---mold
               --- animal
               ---perineal 
         --IgE mediated
        --non-IgE mediate
     -Drug
         --IgE mediated
        --non-IgE mediate
             -- Aspirin
             --  Latex
     -Venom
         --IgE mediated
        --non-IgE mediate
  (*Dermatitis is where contact go*)

**Comment by drseb** [comment]
Are you suggesting to put _Venom_ under _Allergy_?

**Comment by pnrobinson** [comment]
Something like this is what is meant: https://www.aaaai.org/conditions-and-treatments/library/allergy-library/stinging-insect-allergy

**Comment by drseb** [comment]
So rather a label as "venom-induced anaphylaxis"?

**Comment by drseb** [comment]
Or "abnormal allergic reaction to venom"?

**Comment by pnrobinson** [comment]
We are awaiting further feedback from the NIAID group about this subhierarchy. Seb''s questions are to the point. There are two major groups of reactions to insect stings (etc), one is allergic. We need to figure out how to disambiguate this. But please do not create the terms until we have received more fedback!

**Comment by nicolevasilevsky** [comment]
We currently have 'Increased IgE level' and subclasses (I pasted an image below).
![image](https://user-images.githubusercontent.com/6722114/51065937-655adf80-15bc-11e9-8e4b-7e1e487d64e1.png)

Do we want to create a parallel hierarchy under allergy with these terms with the structure:
**Label:** [Antigen] allergy
**Synonym:** Allergy to [antigen]
**Definition:** Hypersensitivity in form of an adverse immune reaction against [antigen].

For example:
**Label:** Alpha-gal allergy
**Synonym:** Allergy to alpha-gal
**Definition:** Hypersensitivity in form of an adverse immune reaction against galactose-alpha-1, 3 galactose (alpha-gal), a carbohydrate found in mammalian meat.

Note - the IgE Ab terms are for antigens that were in LOINC.

**Comment by pnrobinson** [comment]
@LCCarmody @nicolevasilevsky I think that Nicole's suggestion is good but I would suggest we modify the definition as follows
@drseb  can these terms be added from a template?

Definition: Hypersensitivity to [antigen] manifesting as allergic reactions such as skin rash, sneezing, swollen lips, or asthma. 
comment: Note that an HPO term such as Increased anti-seafood IgE antibody level refers to the laboratory measurement and not to the clinical features of allergy that may be associated with increased circulating antibody levels in some, but not all cases. The finding of an increased antibody level to an antigen may be used to support the inference that an allergy is present, but in general, the diagnosis of an allergy requires a history of allergic reactions to an antigen and does not depend solely on the finding of increased circulating antibodies.

**Comment by nicolevasilevsky** [comment]
we have this pattern:
https://github.com/obophenotype/upheno/blob/master/src/patterns/increasedImmunoglobulinComplexAgainstEntity.yaml

but we don't have an allergy pattern, should we try to create one? I am not sure how to write a logical definition for these terms though.

The pattern above doesn't have a logical def (and I am also a bit unsure if we want to have patterns like that, that just create labels and text defs?)

If we don't create a pattern, I'd be happy to manually add these terms in Protege (because I actually really enjoy editing in Protege!)

**Comment by pnrobinson** [comment]
@nicolevasilevsky Could you add these terms in Protege? This is a clinical finding and so it will be difficult to make a pattern similar to the one you mention here.

**Comment by nicolevasilevsky** [comment]
@pnrobinson yes, I'll work on adding these terms :)

**Comment by nicolevasilevsky** [comment]
Ok - all done, let me know if there are any issues. Closing.

**Comment by callahantiff** [comment]
@nicolevasilevsky would you also consider adding (I have with patients with diagnoses of the following):
  - fungal allergy
  - insect allergy (insect venom and bite) 
  - animal product allergy (like milk -- I saw you added meat)  
  - plant product allergy (including grains and tree nuts)

**Comment by callahantiff** [comment]
Whoops, forgot two (maybe too broad?):
  - food allergy  
  - environment allergy

**Comment by nicolevasilevsky** [comment]
added HP_0410339 insect bite allergy
added synonym to HP_0410334 fungi allergy
we have HP_0500093 food allergy (and Dairy allergy and Cow milk allergy are subclasses) and HP_0410320 Animal protein allergy and 'Animal dander allergy' is a subclass. Do we need animal product allergy too? 
We have HP_0410338 Plant product allergy
We have HP_0410332 Nut based food allergy, I made it a subclass of 'Plant based food allergy'

**Comment by nicolevasilevsky** [comment]
we have food allergy HP_0500093

**Comment by callahantiff** [comment]
Thanks for adding those, sorry I missed some of those!

**Comment by nicolevasilevsky** [comment]
No worries @callahantiff. Thanks for reviewing these terms.

@pnrobinson what do you think about environment allergy? I feel like it could be a parent to almost all of these terms, as most allergens come from the environment.

@callahantiff can you provide examples of the LOINC terms that would be mapped to environment allergy? 

When I hear environment allergy, I think of dust, grass, etc (but not so much food or drugs or infectious agents like bacteria).

**Comment by callahantiff** [comment]
I have [LOINC: 79151-7 Known allergies to food or environmental agents](https://r.details.loinc.org/LOINC/79151-7.html?sections=Comprehensive). I also have several ICD, SNOMED CT, and UMLS codes (not sure what the decision was on using those).

**Comment by nicolevasilevsky** [comment]
Thanks for the clarification @LCCarmody. 

@callahantiff I agree with Leigh that the code above should be mapped to allergy, as we cannot map to two terms at the moment.

**Comment by callahantiff** [comment]
Sounds great, I had mapped to that originally and I'll leave it that way. Thank you both!

**Comment by nicolevasilevsky** [comment]
I think we can close this ticket again :)
