### ISSUE TITLE
NTR: Molluscum

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#4004]
Requested in infectious disease hackathon

**Comment by LCCarmody** [comment]
Already added #4266

**Comment by pnrobinson** [comment]
? not related to #4266

**Comment by LCCarmody** [comment]
OOPS! https://github.com/obophenotype/human-phenotype-ontology/issues/4216

**Comment by pnrobinson** [comment]
Restructured the "Unusual infection" hierarchy and added term as HP_0032163 -- @LCCarmody let's discuss this, I think we can now move forward with this design pattern.
