### ISSUE TITLE
Loinc 14283-6:  "Acylcarnitine [Moles/volume] in Urine"

### ISSUE THREAD

**Issue by jpgourdine** [obophenotype/human-phenotype-ontology#4007]
Suggest creating a new term for Loinc: 14283-6 [Acylcarnitine [Moles/volume] in Urine] 
New term label:Abnormal concentration of acylcarnitine in the urine
New term comment (if any): Parent Abnormality of acetylcarnitine metabolism HP:0012071
Your biocurator ID for loinc2hpo (if desired): OHSU:JP

**Comment by nicolevasilevsky** [comment]
ok to add

**Comment by pnrobinson** [comment]
see https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3526046/
