### ISSUE TITLE
abnormal eye morphology & abnormal globe morphology

### ISSUE THREAD

**Issue by psergouniotis** [obophenotype/human-phenotype-ontology#4009]
I believe these should be synonyms (rather than abnormal globe morphology being a subclass of abnormal eye morphology)

Also, as subclasses of Abnormal globe morphology there are:
"Abnormal anterior segment morphology"
"Abnormal morphology of thr posterior segment of the eye"

For symmetry consider renaming the former to: "Abnormal morphology of the anterior segment of the eye"

On a different note, a few minor things:
"Abnormal sclera morphology" - consider renaming to "Abnormal scleral morphology"
"Abnormal ocular adnexa morphology"- consider renaming to "Abnormal ocular adnexal morphology"

**Comment by drseb** [comment]
Didn't we separate these because the eye is more than just the globe?

**Comment by psergouniotis** [comment]
I vaguely remember discussing this when we were trying to decide if we should include ocular adnexa under eye. The wikipedia definition of globle (which I think is incorrect) is:
"The globe of the eye, or bulbus oculi, is the eyeball apart from its appendages"(https://en.wikipedia.org/wiki/Globe_(human_eye)

However I think we decided that appendages such as eyelids should not be subclasses of abnormality of the eye. We have therefore included them under "Abnormality of the ocular adnexa".

The current structure is counterintuitive as "Abnormal eye morphology" has only two subclasses:
* Neoplasm of the eye
* Abnormal globe morphology.
This does not justify the extra node for "Abnormal globe morphology".

I would be grateful for yout thoughts (and also if you would consider the other changes that I recommended above)

**Comment by drseb** [comment]
I think you should discuss with @pnrobinson as he has worked on ophthalmology with you since a long while now. I agree that restructuring is a good option, but also I think we should have the subclasses of "Abn of the eye" for _extraocular_ (structures outside of the globe) and the _ocular_ (the globe + intraocular structures). Let's hear what Peter has to say.
