### ISSUE TITLE
Loinc 10342-4:  "Sulfamethoxazole [Mass/volume] in Serum or Plasma"

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#4010]
Suggest creating a new term for Loinc: 10342-4 [Sulfamethoxazole [Mass/volume] in Serum or Plasma] 
New term label: Positive sulfamethoxazole test
Parent: 'Plasma/serum xenobiotic'

Your biocurator ID for loinc2hpo (if desired): HPO:nvasilevsky

**Comment by nicolevasilevsky** [comment]
see #4011

**Comment by pnrobinson** [comment]
THis is an antibiotic, I am not sure we really need a term for this in HPO, I have never seem something like this being used clinically.
