### ISSUE TITLE
Loinc 10344-0:  "Tranylcypromine [Mass/volume] in Serum or Plasma"

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#4011]
Suggest creating a new term for Loinc: 10344-0 [Tranylcypromine [Mass/volume] in Serum or Plasma] 
New term label: Postive antidepressant test
Parent: 'Plasma/serum xenobiotic'
Question: do we want to add specific drugs or just annotate the general class of drug?
Your biocurator ID for loinc2hpo (if desired): HPO:nvasilevsky

**Comment by nicolevasilevsky** [comment]
see #4012

**Comment by pnrobinson** [comment]
I do not think this test is commonly used and would suggest we not make a term right now
