### ISSUE TITLE
Loinc 10345-7:  "Trihexyphenidyl [Mass/volume] in Urine"

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#4012]
Suggest creating a new term for Loinc: 10345-7 [Trihexyphenidyl [Mass/volume] in Urine] 
New term label: Positive antiparkinsonian drug test 
Parent: Urine xenobiotic
Your biocurator ID for loinc2hpo (if desired): HPO:nvasilevsky

**Comment by nicolevasilevsky** [comment]
annotate as presence of urine xenobiotic

**Comment by nicolevasilevsky** [comment]
@cmungall would it be possible to create design patterns for terms like these that use DrugCentral terms?

cc @pnrobinson

**Comment by pnrobinson** [comment]
Trihexyphenidyl is an anticholinergic medication that is used to treat symptoms of idiopathic or drug-induced Parkinsonism. PMID:30137772

https://www.ncbi.nlm.nih.gov/pubmed/30137772

**Comment by pnrobinson** [comment]
For now I do not think we should record medication levels in the HPO, we need to figure out a proper framework for having subtherapeutic, therapeutic, and toxic levels of a medication.
