### ISSUE TITLE
Loinc 11555-0:  "Base excess in Blood by calculation"

### ISSUE THREAD

**Issue by jpgourdine** [obophenotype/human-phenotype-ontology#4021]
Suggest creating a new term for Loinc: 11555-0 [Base excess in Blood by calculation] 
New term label: Base excess in blood
New term comment (if any):Parent Abnormality of acid-base homeostasis HP:0004360
Your biocurator ID for loinc2hpo (if desired): OHSU:JP

**Comment by pnrobinson** [comment]
I am adding a term for abnormal base excess. This is an extremely tricky value to use clinically, and I would suggest we not annotate more at this time without seeing how it is used in practice.

**Comment by callahantiff** [comment]
In the pediatric labs I am annotating, we have this lab in addition to [LOINC 1925-7: Base excess in Arterial blood by calculation](https://r.details.loinc.org/LOINC/1925-7.html?sections=Comprehensive) and [LOINC 19236-9: Base excess standard in Capillary blood by calculation](https://r.details.loinc.org/LOINC/19236-9.html?sections=Comprehensive). 

For all of these labs, we have patients with results that are higher and lower than the reference range. Would you also recommend that I use "abnormal base excess"?

**Comment by callahantiff** [comment]
Confirming after today's meeting that we will only annotate **NOT(HP_0032281 : Abnormal base excess)** for normal lab results and will not annotate high/low results at this time.
