### ISSUE TITLE
HPO Terms translated into Plain Language

### ISSUE THREAD

**Issue by GARDInfoCenter** [obophenotype/human-phenotype-ontology#4022]
@nicolevasilevsky 

Please find attached additional terms GARD has
[HPO Medical Terms 25+_135+_final.xlsx](https://github.com/obophenotype/human-phenotype-ontology/files/2258170/HPO.Medical.Terms.25%2B_135%2B_final.xlsx)
 translated into plain language. 

Thanks,
Maria

**Comment by nicolevasilevsky** [comment]
Got it, thanks @GARDInfoCenter. I'll get to work on this asap.

**Comment by nicolevasilevsky** [comment]
@GARDInfoCenter I'm working on adding synonyms. Can you please send me one of your ORCIDs for attribution?

**Comment by GARDInfoCenter** [comment]
https://orcid.org/0000-0002-6548-5200 - my ORCID

**Comment by nicolevasilevsky** [comment]
Working through the terms in this spreadsheet:
https://docs.google.com/spreadsheets/d/1oSTYR-NPmpHp9-9Ty5dSVHZwDK0jK5FchuDFxMKOWtI/edit#gid=873268145

**Comment by nicolevasilevsky** [comment]
Added all the synonyms
