### ISSUE TITLE
Suggest name change to Abnormal erythrocyte morphology HP:0001877

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#4023]
The children to Abnormal erythrocyte morphology (HP:0001877) are not all morphological abnormalities
![screen shot 2018-07-12 at 4 08 17 pm](https://user-images.githubusercontent.com/26067008/43742632-a411d30c-99a0-11e8-9e28-db290803041a.png)

@nicolevasilevsky

**Comment by drseb** [comment]
@LCCarmody are you sure this is the screenshot you wanted to upload here? I don't see erythrocytes there...

**Comment by LCCarmody** [comment]
Ooops. Try this one...

<img width="508" alt="screen shot 2018-08-06 at 5 46 10 pm" src="https://user-images.githubusercontent.com/26067008/43913132-39f6a9dc-9bd2-11e8-8163-1cdaedd15b5f.png">

**Comment by pnrobinson** [comment]
Morphilogy essentially refers to things you could see in a photograph, while physiologyt refers to things you could see in a video. We should think about how to classify terms such as those for osmotic fragility, which are  physiology. I would not rename the term label, but think it is better to add a section on abnormal RBC physiology

**Comment by LCCarmody** [comment]
Should RBC physiology be a child of erythrocyte morphology or a sibling?

**Comment by nicolevasilevsky** [comment]
I think a sibling

**Comment by pnrobinson** [comment]
I added a term for RBC physio and moved a few RBC terms thither.
