### ISSUE TITLE
HPO term has been removed without an alternative term being given. 

### ISSUE THREAD

**Issue by James-CG** [obophenotype/human-phenotype-ontology#4024]
The term HP:0002755 has been replaced in the June 2018 release but no term_alternative_id has been given. Without an alternative id for `hpo.term.id = 2755`, we can't migrate our records over to the new version of HPO, as they do not have a suitable phenotype. I suggest that HP:0002754 would be appropriate, as it's the generic osteomyelitis term.

**Comment by drseb** [comment]
This class has already been obsoleted in October 2017. It does have a proper replaced_by annotation. I hope this solves the issue.


```
[Term]
id: HP:0002755
name: obsolete Osteomyelitis due to immunodeficiency
is_obsolete: true
replaced_by: HP:0002754
```

**Comment by James-CG** [comment]
We were not using the obo file. We were using the SQL download from Jun 2018, and I cannot see a replacement for term 2755 in there.

**Comment by drseb** [comment]
We do not provide the SQL dump anymore, which has been announced on our mailinglist and on twitter. So this is not part of the releases anymore.

- [Tweet](https://twitter.com/hp_ontology/status/1022757016790556674)
- [Mail](https://groups.io/g/human-phenotype-ontology/message/7#)
- [Latest release](http://compbio.charite.de/jenkins/job/hpo.annotations.monthly/lastSuccessfulBuild/artifact/annotation/)

**Comment by drseb** [comment]
Please note that there are a lot of HPO classes that have no alt_id-based replacement. These will have a replaced_by or consider annotation. (I.e. having the sql-dump, as we provided it before, will not help with your specific problem here)
