### ISSUE TITLE
Please return the SQL file or provide an alternative makefile to generate this.

### ISSUE THREAD

**Issue by James-CG** [obophenotype/human-phenotype-ontology#4025]
We have made extensive use of the "MYHPO" SQL dump for our pipelines, and I was surprised that this extremely useful feature of HPO has been removed without any warning. Without a Makefile or parser I am unable to generate the SQL myself. Please could you either include it again, or provide the means for users to generate this for themselves from the source data in the Jenkins build.

**Comment by drseb** [comment]
We have filed several warnings and previously requested feedback of our users on this plan - we got no sign of anybody using these files. We will investigate if we find the resources to provide a solution.

**Comment by James-CG** [comment]
I could not see anything on the mailing list or the website about plans to remove the SQL dump, until the announcement on Jul. 27. I would be happy to sign up to submit feedback or recieve updates through any other channel you are using, as I am keen to stay informed about the progress of HPO.

**Comment by pnrobinson** [comment]
Hi James, sorry for the inconvenience -- we have been extremely busy with many parts of the overall pipeline. Please send us an email if this is still necessary; so far we have not heard from any others who require the SQL ingest, and so we can try to help you create a script if this is still needed. @drseb

**Comment by drseb** [comment]
Hi. 

As I have written in https://groups.io/g/human-phenotype-ontology/message/9 we are working on this, but as Peter said, we are pretty busy. The plan would be to create a jar that can be run locally, so that we move a bit of resource-requirement to the users.
