### ISSUE TITLE
Change "cerebral hamartomata" to "cerebral hamartoma"

### ISSUE THREAD

**Issue by brittneyj** [obophenotype/human-phenotype-ontology#4032]
One of the users of PhenoTips noticed that the HPO term cerebral hamartomata is plural, which is inconsistent with the other terms listed, which use the singular form hamartoma (ex, renal hamartoma, retinal hamartoma, cutaneous hamartoma, etc.) Is it possible to have this term changed to cerebral hamartoma for consistency?

**Comment by nicolevasilevsky** [comment]
done
