### ISSUE TITLE
Loinc 1959-6:  "Bicarbonate [Moles/volume] in Blood"

### ISSUE THREAD

**Issue by jpgourdine** [obophenotype/human-phenotype-ontology#4033]
Suggest creating a new term for Loinc: 1959-6 [Bicarbonate [Moles/volume] in Blood] 
New term label:Abnormal bicarbonate concentration in the blood
New term comment (if any):Parent term to be created Abnormality of blood homeostasis -->parent term abnormality of metabolims/homeostasis HP:0002146 
Your biocurator ID for loinc2hpo (if desired): OHSU:JP

**Comment by pnrobinson** [comment]
adding these terms, see HP_0032067
