### ISSUE TITLE
overlapping synonyms with HP_0001315 'Reduced tendon reflexes' and HP_0001265 Hyporeflexia

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#4034]
HP_0001315 'Reduced tendon reflexes' and HP_0001265 Hyporeflexia have some similar and overlapping synonyms.

**Synonyms for HP_0001315 'Reduced tendon reflexes':**
has_exact_synonym "Absent or decreased deep tendon reflexes"
has_exact_synonym "Decreased to absent deep tendon reflexes"
has_exact_synonym "Decreased/absent deep tendon reflexes"
has_exact_synonym "Diminished or absent deep tendon reflexes"
has_exact_synonym "Diminished or absent tendon reflexes"
has_exact_synonym "Hypoactive to absent deep tendon reflexes"
has_exact_synonym "Impaired tendon reflexes"
has_exact_synonym "Reduced/absent deep tendon reflexes"
has_exact_synonym "Weak or absent deep tendon reflexes"
has_broad_synonym "Decreased reflex response"

**Synonyms for HP_0001265 Hyporeflexia:**
has_exact_synonym "Decreased deep tendon reflexes"
has_exact_synonym "Decreased tendon reflexes"
has_exact_synonym "Depressed tendon reflexes"
has_exact_synonym "Diminished deep tendon reflexes"
has_broad_synonym "Decreased reflexes"

@pnrobinson @drseb @LCCarmody - do you think these should be revised?

**Comment by drseb** [comment]
Yes. Maybe put everything that refers explicitly to tendon under HP_0001315 and all others under HP_0001265!?
