### ISSUE TITLE
Misspelling in HP:0025356 "Pschomotor retardation"

### ISSUE THREAD

**Issue by evans-dan** [obophenotype/human-phenotype-ontology#4036]
Searching https://hpo.jax.org/app/browse for the term "psychomotor retardation" yields 0 results.  However searching for "motor retardation" yields the following page:

https://hpo.jax.org/app/browse/term/HP:0025356 "Pschmotor retardation"

There appears to be a misspelling of "psychomotor" in the term name only, as psychomotor is spelled correctly in the comment.

Thank you.

**Comment by nicolevasilevsky** [comment]
Thanks, I fixed the typo.
