### ISSUE TITLE
NTR: Increased intestinal transit time

### ISSUE THREAD

**Issue by cmungall** [obophenotype/human-phenotype-ontology#4038]
to be added as a sib of:

```
     is_a HP:0030896 ! Abnormal gastrointestinal transit time
        is_a HP:0030897 ! Decreased intestinal transit time
```

```
def: "An increase in the length of time required for food to pass through the intestines." []
is_a: HP:0030896  ! Abnormal gastrointestinal transit time
```

@nicolevasilevsky - can you suggest DPs for GI motility phenotypes?

**Comment by cmungall** [comment]
Also: consider hypo and hypermotility for constructing syns of this term and its existing sib

**Comment by nicolevasilevsky** [comment]
would these logical defs work for these terms? If yes, I can add and create DPs.

'has part' some 
    (duration
     and ('inheres in' some 'intestinal motility')
     and ('has modifier' some abnormal))

'has part' some 
    ('in/decreased duration'
     and ('inheres in' some 'intestinal motility')
     and ('has modifier' some abnormal))

**Comment by nicolevasilevsky** [comment]
For synonyms, do you think hypomotility of the intestine and hypermotility of the intestine would work?

And/or intestinal hypomotility/hypermotility?

**Comment by pnrobinson** [comment]
The logical def's seem good.
The English lang def's need to be expanded a bit.
Here is a ref https://bmcgastroenterol.biomedcentral.com/articles/10.1186/1471-230X-11-145

**Comment by pnrobinson** [comment]
added definitions. @nicolevasilevsky  @drseb  
I think we need to mireot this to make the logical def's:
http://amigo.geneontology.org/amigo/term/GO:0120054

**Comment by drseb** [comment]
done

> On 12. Jan 2019, at 15:30, Peter Robinson <notifications@github.com> wrote:
> 
> added definitions. @nicolevasilevsky @drseb
> I think we need to mireot this to make the logical def's:
> http://amigo.geneontology.org/amigo/term/GO:0120054
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

--
Prof. Dr. Sebastian Köhler
Berlin Institute of Health | Charité | Einstein Center Digital Future
sebastian.koehler@charite.de
www.bihealth.org | www.digital-future.berlin | drseb.github.io | phenomics.github.io


Diese Nachricht (inklusive aller Anhänge) ist vertraulich. Sie darf ausschließlich durch den vorgesehenen Empfänger und Adressaten gelesen, kopiert oder genutzt werden. Sollten Sie diese Nachricht versehentlich erhalten haben, bitten wir, den Absender (durch Antwort-E-Mail) hiervon unverzüglich zu informieren und die Nachricht zu löschen. Jede unerlaubte Nutzung oder Weitergabe des Inhalts dieser Nachricht, sei es vollständig oder teilweise, ist unzulässig. Bitte beachten Sie, dass E-Mail-Nachrichten an den Absender nicht für fristgebundene Mitteilungen geeignet sind. Fristgebundene Mitteilungen sind daher ausschließlich per Post oder per Telefax zu übersenden. Wir haben diese E-Mail beim Ausgang einer Virenkontrolle unterzogen, raten aber wegen der Gefahr einer Kontamination auf den Übertragungswegen zu einer Vireneingangskontrolle. Eine Haftung für Virenfreiheit schließen wir aus.

This message (including any attachments) is confidential and may be privileged. It may be read, copied and used only by the intended recipient. If you have received it in error please contact the sender (by return e-mail) immediately and delete this message. Any unauthorised use or dissemination of this message in whole or in part is strictly prohibited. Please note that, for organisational reasons, the personal e-mail address of the sender is not available for matters subject to a deadline. Therefore, please send matters subject to deadline exclusively by mail or by fax. This e-mail was checked for virus contamination before being sent. Nevertheless it is advisable to check for any contamination occuring during transmission. We cannot accept any liability for virus contamination.
