### ISSUE TITLE
NTR: Pulmonary lesions

### ISSUE THREAD

**Issue by MorganSimiluk** [obophenotype/human-phenotype-ontology#4039]
_For new term requests, please provide us with the following information:_
@pnrobinson What's the best way to include findings from imagining?

### 1. Preferred term label
Pulmonary lesions, also brain lesion, also spinal cord lesion, liver lesion...

**Comment by pnrobinson** [comment]
I think we need to be a little more specific than this. Pulmonary lesion is essentially anything abnormal in the lung.

**Comment by MorganSimiluk** [comment]
That's fine.  We can close this.  I think the request was for the non-specific imagining finding of a 'pulmonary lesion' NOS but agree that's not very useful

**Comment by pnrobinson** [comment]
OK. If absolutely needed, we could go for Abnormal X morphology. Additionally, we will be mapping some of the radiology terminology in the near future.
