### ISSUE TITLE
NTR: hx of stillbirth

### ISSUE THREAD

**Issue by MorganSimiluk** [obophenotype/human-phenotype-ontology#4042]
_For new term requests, please provide us with the following information:_
@pnrobinson should miscarriage be used here even if the delivery was at term?

**Comment by pnrobinson** [comment]
@drseb @cmungall @mellybelly similar to the recent comment a few minutes ago, I would add a few items under maternal past history. This will simplify things and is important for prenatal genomics etc etc

If you do not object I will add in a few days.

**Comment by pnrobinson** [comment]
Adding this term with definition: One or more previous pregnancies resulted in stillbirth, defined as death of a fetus in the later stages of pregnancy (definitions in the literature vary, with cut-offs ranging from 20 to 28 weeks gestation).
