### ISSUE TITLE
HPO Medical Terms translated Plain Language (1to156)

### ISSUE THREAD

**Issue by GARDInfoCenter** [obophenotype/human-phenotype-ontology#4043]
@nicolevasilevsky 
We have reviewed about 150 more HPO medical terms. See attached for details. 
[HPO Medical Terms 10-24_1to156.xlsx](https://github.com/obophenotype/human-phenotype-ontology/files/2297883/HPO.Medical.Terms.10-24_1to156.xlsx)

Maria
GARD
ORCID 0000-0002-6548-5200

**Comment by nicolevasilevsky** [comment]
Great, I'll take a look. :)

**Comment by nicolevasilevsky** [comment]
https://github.com/monarch-initiative/mondo/issues/326

**Comment by pnrobinson** [comment]
@GARDInfoCenter @nicolevasilevsky where are we on this? Would it be easier to script the remaining items to the tracker? It is hard to keep track of an excel file...

**Comment by nicolevasilevsky** [comment]
I added all the synonyms. @GARDInfoCenter let me know if you'd like any further revisions. Closing this ticket.
