### ISSUE TITLE
Loinc 10715-1:  "Schistosoma sp identified in Urine sediment by Light microscopy"

### ISSUE THREAD

**Issue by jpgourdine** [obophenotype/human-phenotype-ontology#4044]
Suggest creating a new term for Loinc: 10715-1 [Schistosoma sp identified in Urine sediment by Light microscopy] 
New term : Schistosomuria (presence of Schistosome in the urine)
New term comment (if any): parent term HP:0003110 (abnormality in urine homeostasis)
Your biocurator ID for loinc2hpo (if desired): OHSU:JP
References: PMID: 25685452

**Comment by nicolevasilevsky** [comment]
Will not annotate microbial infections in LOINC2HPO
