### ISSUE TITLE
NTR: cervical dysplasia

### ISSUE THREAD

**Issue by MorganSimiluk** [obophenotype/human-phenotype-ontology#4046]
_For new term requests, please provide us with the following information:_
### 1. Preferred term label
cervical dysplasia

### 3. Textual definition (should be understandable even for non-specialists, please include a PubMed ID for relevant articles providing additional information about the suggestion)
The development of abnormal cells in the narrow neck of a woman's uterus (the cervix).

### 5. Which diseases are characterized by this term ? (e.g. Orphanet- or OMIM-id)
Cervical cancer

**Comment by pnrobinson** [comment]
old article but lucid
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC497441/pdf/jclinpath00494-0009.pdf

**Comment by pnrobinson** [comment]
adding as HP_0032131
