### ISSUE TITLE
abnormal retinal physiology (NTR) & congenital stationary night blindness (HP:0007642)

### ISSUE THREAD

**Issue by psergouniotis** [obophenotype/human-phenotype-ontology#4055]
This frequently used term is perhaps more a physiological than a morphological abnormality
It is presently a subclass of "retinal dystrophy"

I would propose to instead to create a term "Abnormal retinal physiology" (subclass of "abnormal eye physiology". The following terms should be its subclasses:
* abnormal electroretinogram (to also stay as a subclass of abnormal visual electrophysiology)
* abnormal electrooculogram (to also stay as a subclass of abnormal visual electrophysiology)
* cone dysfunction syndrome (to be renamed to "congenital stationary cone dysfunction", see #3174)
* retinal hemorrhage
* congenital stationary night blindness

Following this landmark paper (PMID 28559085) I would propose adding "Congenital stationary synaptic dysfunction" as a synonym for "incomplete congenital stationary night blindness"

**Comment by pnrobinson** [comment]
The physiology section probably should try to not have reference to anatomical parts unless really necessary, because lots of items in the physiology part could have some connection to the retina, not just the ones listed above. The idea is that physiology is often coming from multiple anatomical parts and therefore needs a separate hierarchy to represent it.

**Comment by pnrobinson** [comment]
The current term cone dysfunction syndrome https://hpo.jax.org/app/browse/term/HP:0030637
is being used to annotate a series of diseases. Not all of them are "congenital stationary cone dysfunction", and so we might need to reorganize this section.

**Comment by psergouniotis** [comment]
Thanks for highlighting this Peter.  The annotation of OMIM:304020 to "cone dysfunction syndrome" is imprecise. Instead  OMIM:304020 should be annotated to cone/cone-rod dystrophy.

Then I think we should proceed with renaming "cone dysfunction syndrome" to "congenital stationary cone dysfunction" (with "cone dysfunction syndrome retained as a synonym)

**Comment by pnrobinson** [comment]
I have renamed the term. I will add the annotation to our separate github tracker for annotations.
