### ISSUE TITLE
Similar Layperson Translations for Medical Terms

### ISSUE THREAD

**Issue by GARDInfoCenter** [obophenotype/human-phenotype-ontology#4056]
@nicolevasilevsky @pnrobinson 

We have two pairs of words that have very similar layperson synonyms. Does the database allow for these types of instances? Although there are differences within the pairs, the differences may not be important to the layperson when encountering the medical terms separately for a disease.

Palmoplantar keratoderma 0000982- Thickening of palms and soles (proposed GARD lay term translation)
Palmoplantar hyperkeratosis 0000972- Thickened palms and soles; Thick palms and soles (already in HPO) 

Lissencephaly 0001339 - Fewer or absent grooves in brain (already in HPO)
Pachygyria 0001302 - Fewer and broader ridges in brain (proposed GARD lay term translation)

Below are additional terms we have translated. 

Corneal erosion - damage to outer layer of cornea of eye
Deviation of finger - finger pointing in a different direction than typical; finger pointing in atypical direction
Diastema - space between teeth
Hernia - internal organ bulging through weak surrounding area
Nystagmus - rhythmic involuntary eye movement
Contracture - flexed joint that cannot be straightened

Maria 
GARD
ORCID: 0000-0002-6548-5200

**Comment by pnrobinson** [comment]
@GARDInfoCenter Currently, we require that synonyms be distinct (this is a result of the fact that we are using OWL/Protege and the general way we have set up the system). 
Could we suggest that we try to find different synoynms.
For instance, 
Keratoderma is thickening of the skin
Hyperkeratosis is a thickening of the outer layer of the skin. 
I will add these synonyms as above right now.

**Comment by pnrobinson** [comment]
I added the missing synonyms (some were already there)
