### ISSUE TITLE
NTR: Conjunctival icterus

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#4080]
_For new term requests, please provide us with the following information:_
### 1. Preferred term label
Conjunctival icterus 

### 2. Synonyms
Scleral icterus, Yellow sclera, yellow conjunctiva

### 3. Textual definition (should be understandable even for non-specialists, please include a PubMed ID for relevant articles providing additional information about the suggestion)
Conjunctival icterus is a condition where there is yellowing of the whites of the eyes. This is most commonly seen in patients who have liver disease.

PMID: 28721815
### 5. Which diseases are characterized by this term ? (e.g. Orphanet- or OMIM-id)
RED CELL PHOSPHOLIPID DEFECT WITH HEMOLYSIS OMIM:179700,
Jaundice

Note: this is a phenotype listed in PMID: 3090825.  I was trying to annotate OMIM:179700 which has too few annotations (https://github.com/monarch-initiative/hpo-annotation-data/issues/208)  and they listed the phenotype "Scleral icterus".  Upon research, it appears that "Conjunctival icterus" is more appropriate, but I am not sure we should include this as a synonym or maybe in one of the comments?   Is there another term currently being used for this?  @psergouniotis  @pnrobinson

**Comment by psergouniotis** [comment]
This seems to be an appropriate term (although it is not used in major textbooks such as Kanski, Oxford manual etc, there are many reports on pubmed, e.g. https://www.ncbi.nlm.nih.gov/pubmed/28721815)

**Comment by pnrobinson** [comment]
added term
