### ISSUE TITLE
NTR: Chronic Valley Fever aka coccidiomycosis

### ISSUE THREAD

**Issue by MorganSimiluk** [obophenotype/human-phenotype-ontology#4084]
_For new term requests, please provide us with the following information:_

**Comment by pnrobinson** [comment]
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3702223/
 In recent years, it has become evident that persons with immunodeficiency diseases are also particularly vulnerable.

**Comment by pnrobinson** [comment]
@MorganSimiluk  -- I cannot find references to "chronic" Coccidioidomycosis, but it seems that any infection with Coccidioidomycoides may be regarded as possibly opportunistic. Can we drop the "chronic" and classify Coccidioidomycosis as an Opportunisitc infection? We will have a few subtypes as well, e.g., meningitis.

**Comment by MorganSimiluk** [comment]
Yes, just fine.  Thanks Peter.

**Comment by pnrobinson** [comment]
adding term
