### ISSUE TITLE
NTR: extrapulmonary tuberculosis

### ISSUE THREAD

**Issue by MorganSimiluk** [obophenotype/human-phenotype-ontology#4093]
_For new term requests, please provide us with the following information:_

**Comment by pnrobinson** [comment]
The two types of clinical manifestation of tuberculosis (TB) are pulmonary TB (PTB) and extrapulmonary TB (EPTB). The former is most common. EPTB refers to TB involving organs other than the lungs (e.g., pleura, lymph nodes, abdomen, genitourinary tract, skin, joints and bones, or meninges). A patient with both pulmonary and EPTB is classified as a case of PTB. [PMID:25861336]

Comment
Extrapulmonary involvement can be seen in patients with concurrent AIDS and tuberculosis. The risk of extrapulmonary tuberculosis and mycobacteremia increases with advancing immunosuppression. https://www.aafp.org/afp/2005/1101/p1761.html  [PMID:16300038]
