### ISSUE TITLE
Acylcarnitine questions

### ISSUE THREAD

**Issue by jpgourdine** [obophenotype/human-phenotype-ontology#4101]
Hi @pnrobinson ,

we have a lot of acylcarnitine test (sebacylcarnitine, palmitoylcarnitine, glutarylcarnitine, etc.) 

Should we gather them under the same acylcarnitine levels HP:0045045 or create new terms?

JP

**Comment by pnrobinson** [comment]
@jpgourdine  I am not that familiar with this area, but I would suggest that if there are any OMIM diseases annotated to the metabolites, then we make new terms, otherwise we can wait and see if we get requests or data with them.
