### ISSUE TITLE
Loinc 30152-3:  "Mannose-binding protein [Mass/volume] in Serum"

### ISSUE THREAD

**Issue by jpgourdine** [obophenotype/human-phenotype-ontology#4102]
Suggest creating a new term for Loinc: 30152-3 [Mannose-binding protein [Mass/volume] in Serum] 
New term label:Abnormal mannose-binding protein level
New term comment (if any):PArent term Abnormality of circulating protein (HP:0010876)
Your biocurator ID for loinc2hpo (if desired): OHSU:JP

**Comment by jpgourdine** [comment]
Relevant publications 
- increased level in rheumatic heart disease (PMID: 15544631)
- decreased level in mannose-binding protein deficiency and  mannose-binding protein in general (PMID: 25783214 )

**Comment by jpgourdine** [comment]
@pnrobinson , yes it is the same (MONDO:0013714)

**Comment by pnrobinson** [comment]
Thanks, I have added the above information (three terms).
