### ISSUE TITLE
Loinc 5798-4:  "Leucine crystals [Presence] in Urine sediment by Light microscopy"

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#4103]
Suggest creating a new term for Loinc: 5798-4 [Leucine crystals [Presence] in Urine sediment by Light microscopy] 
New term label: Leucineuria (?) 
Parent term: Aminoaciduria
New term comment (if any):Cannot find specifically the term 'leucine-uria' but 'Valine-leucine-uria' does exit PMID: 5974899

Your biocurator ID for loinc2hpo (if desired): JGM:lccarmody

**Comment by pnrobinson** [comment]
added as HP_0020075 @kingmanzhang

**Comment by kingmanzhang** [comment]
done
