### ISSUE TITLE
Loinc 39789-3:  "Potassium [Moles/volume] in Venous blood"

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#4105]
Suggest creating a new term for Loinc: 39789-3 [Potassium [Moles/volume] in Venous blood] 
New term label: Hypokalemia in venous blood
Parent term: Hypokalemia
New term comment (if any): There should be several new terms added for elevated or decreased potassium in venous or arterial blood.  Not sure if we should keep Hypokalemia and Hyperkalemia for labels when discussing venous or arterial blood, but it makes sense.  PMID: 720090

Your biocurator ID for loinc2hpo (if desired): JGM:lccarmody

**Comment by pnrobinson** [comment]
I am not sure this is currently used much, and venous blood is the default for electrolytes anyway.
I would say we can map this to hyperkalemia etc

**Comment by LCCarmody** [comment]
Okay, I'll curate this. Close.
