### ISSUE TITLE
review urate terms with Peter

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#4108]
@pnrobinson there are a lot of urate-type terms in LOINC, I am hoping we can review these when we meet next week.

(note to self - search on urate)

**Comment by pnrobinson** [comment]
@nicolevasilevsky is there an open action item here?

**Comment by nicolevasilevsky** [comment]
I don't think there are any open action items anymore. Looks like we have increased/decreased urate terms in urine and blood, and the other LOINC codes I'll mark as do not annotate (like urate in tissue or urate in body fluid.) Closing this ticket.
