### ISSUE TITLE
NTR: Amino acid levels in blood

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#4114]
There are numerous amino acid levels in blood that need to be annotated in LOINC.  Most have high levels but are missing the term for low levels ( See #4110).

It appears that most should have high and low levels listed, but a few AA (like phosphoserine) don't have a lower limit based on a Mayo clinic chart ( https://www.mayomedicallaboratories.com/test-catalog/Clinical+and+Interpretive/9265 ).  Would this chart be an accurate representation of what is clinically relevant?  I.e., There are too high and too low levels of Taurine, but only too high levels of phosphoserine?

Should the labels be hypertaurinemia, hypotaurinemia, and hyperphosphoserinemia, respectively?  
Should any of these not be included in the HPO?
@pnrobinson Let me know if this is okay and I will add them to the HPO and annotate in LOINC.

**Comment by LCCarmody** [comment]
@pnrobinson @nicolevasilevsky @jpgourdine @kingmanzhang 
I've gone through the list of amino acids that need to be curated in LOINC (and curated the ones that could be curated).  Below is a list of the terms that I think need to be added to the HPO based on the link I posted before.  Let me know if you disagree @pnrobinson 
Valine: HP:0010910 Hypervalinemia
[ ] Need Hypovalinemia

Tyrosine: HP:0003231 Hypertyrosinemia
[ ] Need Hypotyrosinemia

Tryptophan: 
[ ] Need: Hypertryptophanemia and 
[ ] Hypotryptophanemia

Threonine: HP:00003354 Hyperthreoninemia
[ ] Need Hypothreoninemia

Taurine: 
[ ] Need Hyper/
[ ] hypotaurinemia 

Serine: HP:0012279 Hyposerineemia
[ ] need hyperserineemia

Proline: HP:0008358 Hyperprolinemia
[ ] Need hypoprolinemia

Hydroxyproline: HP:0003260 Hydroxyprolinemia
[ ] Need hypoprolinemia

Phenylalanine: HP:0004923 Hyperphenylalanineia
[ ] Need hypo

Methionine: none needed

Lysine: HP:0002161 Hyperlysinemia
[ ] Need Hypo

Leucine: HP:0010911 Hyperleucinemia
[ ] Need Hypo

Isoleucine: HP:0010913 Hyperisoleucinemia
[ ] Need hypo

Histidine: HP:0010906 Hyperhistidinemia
[ ] Need hypo

Glycine: None needed

Glutamine: HP:0003217 Hyperglutaminemia
[ ] need hypo

Glutamate: 
[ ] Need Hyper/hypoglutamatemia—I think. Not sure what the levels should be, but there is a LOINC test for it.

Cystine: 
[ ] Need Hyper/hypo (possibly only Hyper as low limits are 2 or 3)

Cystathionine: None needed.  Note: Only cystathioninemia exists, but there isn’t a lower limit.

Arginine: HP:0005961 Hypoargininemia:
[ ] Need Hyper

Alanine: HP:00003348 Hyperalaninemia
[ ] Need Hypo

Asparagine: 
[ ] Need Hypo/
[ ] hyper

Aspartate: 
[ ] Need Hyper/hypo Note: I think. Not sure what the levels are.

Carnosine: 
[ ] Need Hyper. Note: no lower limit.

Ethanolamine: 
[ ] Need Hyper. Note: no lower limit.

Homocystine: 
[ ] Need Hyper
[ ] hypo Note: I think. Not sure what the levels are.

Ornithine: HP:0012026 Hyperornithinemia 
[ ] Need Hypo.

**Comment by pnrobinson** [comment]
@LCCarmody these sound like good suggestions, let's go ahead!

**Comment by LCCarmody** [comment]
@drseb Could you MIREOT 'glutamate metabolic process'. GO:0006536  
Thanks.

**Comment by LCCarmody** [comment]
I have added all the terms that I know where they should go.
I have questions about a few terms:  Hypertaurinemia/Hypotaurinemia .  Taurine is an acid and has an amino group, but technically is not a traditional amino acid.  I think it should go under Abnormality of sulfur amino acid metabolism, but I am not certain.  Any thoughts @pnrobinson @jpgourdine anyone?

Also, ethanolamine may require a new parent class of "Abnormality of amino alcohol metabolism" that is sibling class to the "Abnormality of carboxylic acid metabolism".  Does that sound right?

Also, also: I did not use the terms 'hyper/hypocarnosinemia' because  'carnosinemia (OMIM: 212200)'
 is a disease of carnosine deficiency.  Instead, I used 'increased/decreased level of carnosine'.  Similarly, Hydroxyprolinemia is a term used for increased hydroxyproline (but not hyperhydroxyproline), so I used 'Decreased hydroxyproline levels'.  Let me know if that looks okay.

**Comment by jpgourdine** [comment]
@LCCarmody Not sure here, gotta give it some thoughts but quick look.  Taurine is not an[ amino acid](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:33709) per se (no carboxylic fucntion but sulfonic acid) nor a sulfur amino acid but an [aminoethylsulfonic acid](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:15891) but a sulfur amino acid derivative.

**Comment by drseb** [comment]
@LCCarmody mireoted

**Comment by LCCarmody** [comment]
Still need
Hypertaurinemia
  hypotaurinemia
Hyperethanolaminia

@drseb  has added the terms for the logical definitions. I cannot add the terms until we fix all the imports I have in my HPO account--which will be later this week. 
I can add them at that time or someone else can.

**Comment by pnrobinson** [comment]
@LCCarmody can we move forward with these? Talk tomorrow?

**Comment by LCCarmody** [comment]
I can do this today.
