### ISSUE TITLE
Coats disease should have annotation to Leukocoria

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#4115]
After reading wiki article. https://en.wikipedia.org/wiki/Coats%27_disease 

@psergouniotis @pnrobinson

**Comment by pnrobinson** [comment]
This is true
Here is a PMID
https://www.ncbi.nlm.nih.gov/pubmed/29567893
@LCCarmody could we add this with PhenoteFX?

**Comment by LCCarmody** [comment]
Not sure why I am having trouble with this, but I cannot find OMIM:300216 (https://omim.org/entry/300216?search=coats&highlight=coat) when using PhenoteFX.  There is no file as such and it isn't in obsoleted terms.  When looking up on the HPO browser, Coats does appear and it does have annotations, but using the ORPHA:190.  Is there a new version of PhenoteFX to look up Orpha IDs?

**Comment by pnrobinson** [comment]
@LCCarmody we do not have an entry for Coats via OMIM. Let's meet next week to create one!

**Comment by pnrobinson** [comment]
We were missing the file for Coats disease. I added it with some annotations including leukocoria.
