### ISSUE TITLE
Glaucoma and IOP should be inversed ?

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#4116]
Glaucoma is defined as "_Glaucoma refers loss of retinal ganglion cells in a characteristic pattern of optic neuropathy usually associated with increased intraocular pressure._"

IOP is defined as "_An increase in the intraocular pressure which is determined by the balance of aqueous humour inflow and outflow, and that is 2 standard deviations above the population mean._"

Isn't Glaucoma a more specific form of IOP?

Currently IOP is a subclass of Glaucoma. Is that correct?

@psergouniotis @pnrobinson

**Comment by pnrobinson** [comment]
Glaucoma is a disease that often but not always has increased IOP. Glaucoma is being used as a phenotypic feature for 227 diseases, and so it is commonly used as a phenotypic feature. I think that the "loss of retinal ganglion cells in a characteristic pattern of optic neuropathy " is representing the phenotypic feature, and it seems to be morphology. Increased IOP seems to be physiology.
@psergouniotis -- suggestions?

**Comment by psergouniotis** [comment]
Agree with Peter. IOP should not be a subclass of glaucoma.

A nice lay term for glaucoma can be found in this patient information leaflet (https://www.rcophth.ac.uk/wp-content/uploads/2017/10/2017_Understanding-Glaucoma.pdf)

"Glaucoma is an eye condition where your optic  nerve is damaged by the pressure of the fluid  inside the eye (intraocular pressure). This may be because the eye pressure is  higher than normal, or because of a weakness to the optic nerve"

**Comment by psergouniotis** [comment]
I would propose renaming "Increased intraocular pressure" to "Ocular hypertension" (keeping  "Increased intraocular pressure" as a synonym),

Perhaps the definition should be altered slightly: "intraocular pressure that is 2 standard deviations above the population in the presence of a healthy optic disc and a normal/non-glaucomatous visual field.

 "Ocular hypertension" should be a subclass of "abnormal eye physiology" and not of "glaucoma"

**Comment by pnrobinson** [comment]
I have added the term Narrow angle glaucoma and modified the definitions. I think that normal tension glaucoma is a disease and should be coded as a MONDO term. @nicolevasilevsky -- we could use this definition and add the microattribution UManchester:psergouniotis
