### ISSUE TITLE
Loinc 16110-9:  "11-Deoxycorticosterone [Mass/time] in 24 hour Urine"

### ISSUE THREAD

**Issue by jpgourdine** [obophenotype/human-phenotype-ontology#4117]
Suggest creating a new term for Loinc: 16110-9 [11-Deoxycorticosterone [Mass/time] in 24 hour Urine] 
New term label:Abnormal urinary 11-Deoxycorticosterone concentration
New term comment (if any):Parent term Abnormality of urine hormone level (HP:0012029) 
Your biocurator ID for loinc2hpo (if desired): OHSU:JP

**Comment by jpgourdine** [comment]
Increase of urinary 11-Deoxycorticosterone is associated with Congenital adrenal hyperplasia due to 11 beta-hydroxylase (CYP11B1) deficiency (MONDO:0008729).
Also patients with DOC-secreting tumors also exhibit hypertension ([LOINC](https://s.details.loinc.org/LOINC/16110-9.html?sections=Comprehensive))

--

**Comment by pnrobinson** [comment]
added
