### ISSUE TITLE
Loinc 42572-8:  "11-Deoxycortisol [Mass/volume] in Urine"

### ISSUE THREAD

**Issue by jpgourdine** [obophenotype/human-phenotype-ontology#4118]
Suggest creating a new term for Loinc: 42572-8 [11-Deoxycortisol [Mass/volume] in Urine] 
New term label:Abnormal urinary 11-deoxycortisol concentration
New term comment (if any): Parent term Abnormality of urine hormone level (HP:0012029)
Your biocurator ID for loinc2hpo (if desired): OHSU:JP

**Comment by jpgourdine** [comment]
Increase of urinary 11-Deoxycortisol is associated with Congenital adrenal hyperplasia due to 11 beta-hydroxylase (CYP11B1) deficiency (MONDO:0008729). ([LOINC reference](https://s.details.loinc.org/LOINC/34206-3.html?sections=Comprehensive))

**Comment by pnrobinson** [comment]
Adding as Increased urinary 11-deoxycortisol level. HP_0032329

**Comment by pnrobinson** [comment]
added as HP_0032329 @kingmanzhang

**Comment by kingmanzhang** [comment]
done
