### ISSUE TITLE
Loinc 29881-0:  "2-Hydroxyglutarate [Presence] in Urine"

### ISSUE THREAD

**Issue by jpgourdine** [obophenotype/human-phenotype-ontology#4120]
Suggest creating a new term for Loinc: 29881-0 [2-Hydroxyglutarate [Presence] in Urine] 
New term label:2-hydroxyglutaric aciduria
New term comment (if any):Parent term dicarboxylic aciduria HP:0003215 (HPO has  L-2-hydroxyglutarate aciduria and D-2-hydroxyglutarate aciduria but LOINC term in more general, also those )
Your biocurator ID for loinc2hpo (if desired): OHSU:JP

**Comment by jpgourdine** [comment]
HPO has L-2-hydroxyglutarate aciduria (HP:0040144) and D-2-hydroxyglutarate aciduria (HP:0012321) but LOINC term in more general, also those two terms should be child of the new general term 2-hydroxyglutarate aciduria

**Comment by pnrobinson** [comment]
Adding the general term as HP_0032278

**Comment by kingmanzhang** [comment]
done
