### ISSUE TITLE
NTR: Edema of the hand?

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#4121]
Trying to update too general of phenotypes: PEHO SYNDROME [OMIM:260565]: Abnormality of the hand [HP:0001155]

This is edema of the hand PMID:2070547.

Not sure if this should be added or this should be skipped. https://github.com/monarch-initiative/hpo-annotation-data/issues/214

**Comment by LCCarmody** [comment]
There is a paper describing dorsum vs. volar (and not general).  It is describing the distinct areas.  I can add them to the HPO. Not sure if you were thinking of anything additional: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2600075/pdf/296.pdf

**Comment by pnrobinson** [comment]
The paper is not describing edema (which is accumulation of fluid) but other lesions we should probably add.

**Comment by pnrobinson** [comment]
added some more information
