### ISSUE TITLE
should 'Abnormality of cranial nerve' be a synonym for 'Abnormality of cranial nerve'?

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#4122]
When we were reviewing the craniofacial terms, I noted that 'Abnormality of cranial nerve' should be a synonym for 'Abnormality of cranial nerve' - is this correct?

Thanks!

**Comment by pnrobinson** [comment]
? these are the same strings ?

**Comment by nicolevasilevsky** [comment]
Oops - sorry! I meant  Abnormality of the twelfth cranial nerve  HP:0010826

**Comment by pnrobinson** [comment]
It seems that this term
https://hpo.jax.org/app/browse/term/HP:0010826
is not a child of Abn of cranial nerve, which is wrong. Is that what you mean?

**Comment by nicolevasilevsky** [comment]
No, I had a note that Abnormality of cranial nerve should be a synonym for 'Abnormality of the twelfth cranial nerve' (HP:0010826), but that seems more general.

**Comment by pnrobinson** [comment]
No it is not -- there are 12 cranial nerves!

**Comment by nicolevasilevsky** [comment]
yes, thanks! That seemed wrong to me :)
