### ISSUE TITLE
Chorioretinitis superclass missing?

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#4123]
Shouldn't Chorioretinitis also be an "Abnormality of the immune system"?

@psergouniotis @pnrobinson

**Comment by pnrobinson** [comment]
I think chorioretinis (as well as most of the other -itis terms in the HPO) can be regarded as a normal response of the immune system to an abnormal stimulus (for instance various causes are listed here: https://en.wikipedia.org/wiki/Chorioretinitis). 
We are in the process of revamping the immunology part of the HPO with NIAID and ECID and we will be following some recommendations to denote 'unusual infections' that can be regarded as abnormalities of the immune system (warning, this is German, see ELVIS: https://medonline.at/allgemeinmedizin/medical-tribune/n/2017/217287/elvis-garfield-entlarven-immundefekte/). 
According to this, possibly some types of chorioretinitis may be considered abnormalities of the immune system (e.g., CMV). Others cannot. Therefore, the term itself should not be classified as an Abnormality of the immune system. We are currently waiting for the final report from the Vienna meeting and then will begin revising. I would suggest we think about CMV chorioretinitis etc during that revision. @psergouniotis - ideas?

**Comment by pnrobinson** [comment]
I think we can close this.
