### ISSUE TITLE
Loinc 8098-6:  "Thyroglobulin Ab [Units/volume] in Serum or Plasma"

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#4126]
Suggest creating a new term for Loinc: 8098-6 [Thyroglobulin Ab [Units/volume] in Serum or Plasma] 
New term label: Decreased circulating thyroglobulin
New term comment (if any): Parent term-Abnormal circulating Thyroglobulin
Your biocurator ID for loinc2hpo (if desired): JGM:lccarmody

**Comment by nicolevasilevsky** [comment]
I added this annotation in LOINC2HPO
