### ISSUE TITLE
Issues with HP:0031927 in OBO

### ISSUE THREAD

**Issue by kchennen** [obophenotype/human-phenotype-ontology#4127]
The term **HP:0031927** has format issues in the OBO file for the xref field and the ref PMID:

[Term]
id: HP:0031927
name: Flexner-Wintersteiner rosette
comment: The tumor cells that form the Flexner-Wintersteiner rosette circumscribe a central lumen that contains small cytoplasmic extensions of the encircling cells; however, unlike the center of the Homer Wright rosette, the central lumen does not contain the fiber-rich neuropil. **{xref="PMID:16551982"}**
**xref: A type of rosette in which a halo of cells surrounds a largely empty central hub. Small cytoplasmic extensions from the cells project into the lumen.**
is_a: HP:0031925 ! Rosette
property_value: http://purl.org/dc/elements/1.1/creator "peter" xsd:string
property_value: http://purl.org/dc/elements/1.1/date 2018-07-04T13:26:44Z xsd:dateTime

**Comment by pnrobinson** [comment]
Thanks for pointing this out. There was in fact a format error, which I have repaired.
