### ISSUE TITLE
NTM: Mycobacterium abscessus abscessus infection

### ISSUE THREAD

**Issue by MorganSimiluk** [obophenotype/human-phenotype-ontology#4128]
_For new term requests, please provide us with the following information:_
### 1. Preferred term label
Mycobacterium abscessus abscessus infection
Very important infection, per requested by Amy Klion and Steve Holland at NIAID

### 3. Textual definition (should be understandable even for non-specialists, please include a PubMed ID for relevant articles providing additional information about the suggestion)
Mycobacterium abscessus complex comprises a group of rapidly growing, multidrug-resistant, nontuberculous mycobacteria that are responsible for a wide spectrum of skin and soft tissue diseases, central nervous system infections, bacteremia, and ocular and other infections. 
PMID: 26295364

**Comment by pnrobinson** [comment]
added as a type of opportunistic infection
