### ISSUE TITLE
question about term Hypoplasia of maxilla relative to mandible

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#4130]
I am adding the term: Hypoplasia of maxilla relative to mandible

@markengelstad would this also be considered an underbite?

![image](https://user-images.githubusercontent.com/6722114/45986756-50187000-c022-11e8-9c57-c8f8ed42dbf6.png)
From: https://www.researchgate.net/figure/Lateral-view-showing-hypoplastic-maxilla-and-relative-prognathic-mandible_fig1_277918795

**Comment by pnrobinson** [comment]
hmm, I have never heard of this being use for dysmorphology. Unless @markengelstad thinks we need this, I would suggest we use the existing terms. I will close for now, reopen if needed!
