### ISSUE TITLE
NTR: intranasal adhesion

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#4131]
Intranasal adhesions are on Mark's list of craniofacial terms, but looks like this is due to a surgery complication, or trauma (like cocaine use). Do we want to add this to HPO?

See: https://www.uofmhealth.org/health-library/tu6508
https://www.ncbi.nlm.nih.gov/pubmed/3416505
https://myhealth.alberta.ca/Health/Pages/conditions.aspx?hwid=tu6508

**Comment by pnrobinson** [comment]
Let's hold off on this term for now I would say--if we start to do surgical phenotypes, we should do it in a systematic fashion and not ad hoc.
