### ISSUE TITLE
is Adhesions of temporomandibular joint different from 'Temporomandibular joint ankylosis'?

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#4132]
@markengelstad are these terms synonyms?
Adhesions of temporomandibular joint

'Temporomandibular joint ankylosis' HP_0012478
Def: Fusion of the mandibular condyle to the base of the skull, resulting in limitation of jaw opening.

If yes, could you provide a text def for 'Adhesions of temporomandibular joint'?

Thanks!

**Comment by pnrobinson** [comment]
These terms are not synonymous, see https://www.ncbi.nlm.nih.gov/pubmed/12139272
here are some photographs: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2702314/
Ankylosis is bony fusion, adhesion is the formation of fibrous strands.
We do not have a term for temporomandibular joint adhesion, I will add.

**Comment by pnrobinson** [comment]
Label: Temporomandibular joint adhesion
Def:Formation of one or more fibrous bands within the temporomandibular joint (TMJ) with resulting limitation of movement of the TMJ. Adhesions may be seen in degenerative processes that involve the TMJ.  PMID:19534789 and PMID:12139272
Comment:See Figure 1 of PMID:19534789.

Add "bony fusion" to definition of ankylosis
