### ISSUE TITLE
Loinc 41653-7:  "Glucose [Mass/volume] in Capillary blood by Glucometer"

### ISSUE THREAD

**Issue by kingmanzhang** [obophenotype/human-phenotype-ontology#4135]
Suggest creating a new term for Loinc: 41653-7 [Glucose [Mass/volume] in Capillary blood by Glucometer] 
New term label: Not sure how to handle this one
New term comment (if any):
Your biocurator ID for loinc2hpo (if desired): JGM:azhang

**Comment by pnrobinson** [comment]
@kingmanzhang I think that we can use the existing hyper/hypo glycemia terms for this -- it is a different test for the same thing, and the differences in interpretation of the test are minimal. Please close this term after making the LOINC annotation
