### ISSUE TITLE
Loinc 8247-9:  "Mucus [Presence] in Urine sediment by Light microscopy"

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#4136]
Suggest creating a new term for Loinc: 8247-9 [Mucus [Presence] in Urine sediment by Light microscopy] 

Do we want to create a new term for this or mark unable to annotate?

**Comment by pnrobinson** [comment]
duplicate with https://github.com/obophenotype/human-phenotype-ontology/issues/4137
