### ISSUE TITLE
Loinc: 46702-7 [Leukocytes [#/area] in Urine sediment by Automated count]

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#4138]
should we create a new term for the presence of leukocytes in the urine?

**Comment by nicolevasilevsky** [comment]
Also have Loinc: 33219-7 [Epithelial cells.squamous [#/area] in Urine sediment by Automated count]

**Comment by pnrobinson** [comment]
This is probably https://hpo.jax.org/app/browse/term/HP:0012085
