### ISSUE TITLE
Loinc 3034-6:  "Transferrin [Mass/volume] in Serum or Plasma"

### ISSUE THREAD

**Issue by jpgourdine** [obophenotype/human-phenotype-ontology#4139]
Suggest creating a new term for Loinc: 3034-6 [Transferrin [Mass/volume] in Serum or Plasma] 
New term label:Abnormal transferrin level
New term comment (if any):Increased and decreased transferrinlevel (parent term abnormal circulating beta globulin level HP:0025465) 
Your biocurator ID for loinc2hpo (if desired): OHSU:JP

**Comment by jpgourdine** [comment]
Increased or decreased level of transferrin level is associated with anemia (Fe dependent or not) PMID: 19787826 @pnrobinson

**Comment by pnrobinson** [comment]
added trio of terms HP_0032385
@kingmanzhang

**Comment by kingmanzhang** [comment]
done
