### ISSUE TITLE
NTR: pyrogenic infection (or possible synonym?)

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#4142]
_For new term requests, please provide us with the following information:_
### 1. Preferred term label pyrogenic infection
Pyrogenic infection

### 3. Textual definition (should be understandable even for non-specialists, please include a PubMed ID for relevant articles providing additional information about the suggestion)

An infection caused by pus-producing organisms. 

### 5. Which diseases are characterized by this term ? (e.g. Orphanet- or OMIM-id)

OMIM: 614372
MANNOSE-BINDING LECTIN DEFICIENCY;

**Comment by pnrobinson** [comment]
Hmm pyrogenic means fever-causing, and I am not sure this in itself is abnormal. 

WE prob do not need this to annotate
https://omim.org/entry/614372
