### ISSUE TITLE
Organic acid synonyms

### ISSUE THREAD

**Issue by jpgourdine** [obophenotype/human-phenotype-ontology#4145]
@nicolevasilevsky  
the suffix "ate" indicates the anionic form of the organic acid
For instance, a search for pyruvic acid should give the same results then pyruvate

Glutarate = Glutaric acid ([source](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:24329)) 

Malate = Malic acid ([source](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:25115))

Pyruvate = Pyruvic acid

Citrate = Citric acid

And so on the monocarboxylic and dicarboxylic aciduria

JP

**Comment by nicolevasilevsky** [comment]
@jpgourdine what HP terms are you requesting synonyms for?

**Comment by jpgourdine** [comment]
HP:0012404 Abnormal urine citrate concentration or Abnormal urine citric acid concentration
