### ISSUE TITLE
NTR: Mandibular hypoplasia

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#4147]
_For new term requests, please provide us with the following information:_
### 1. Preferred term label
Mandibular hypoplasia

### 2. Synonyms
Underdeveloped jaw
Underdeveloped lower jaw

### 3. Textual definition (should be understandable even for non-specialists, please include a PubMed ID for relevant articles providing additional information about the suggestion)
Underdevelopment of the mandible.

### 4. Parent term 
'Aplasia/Hypoplasia of the mandible'

**Comment by drseb** [comment]
Why not use **Micrognathia**?

**Comment by pnrobinson** [comment]
Might be a synonysm
https://en.wikipedia.org/wiki/Micrognathism
but please check elements of morphology

**Comment by nicolevasilevsky** [comment]
Oh yeah, thanks! I missed that for some reason.
