### ISSUE TITLE
NTR: premature onset?

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#4149]
In the Kid's First portal, there is a term CHRONIC LUNG DISEASE-PREMATURITY, should we have a modifier for premature? Or should I create a new term for 'Premature chronic lung disease'? (or just annotate it to 'chronic lung disease')?

**Comment by pnrobinson** [comment]
This is not a good term, probably they mean bronchopulmonary dysplasia or a sequela thereof.

**Comment by nicolevasilevsky** [comment]
Ok, closing
