### ISSUE TITLE
Synonym request: Abnormality of stapedial reflex

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#4153]
_For new term requests, please provide us with the following information:_
### 1. Preferred term label
Abnormality of stapedial reflex (make synonym of HP:0040121

### 2. Synonyms
Abnormality of acoustic reflex (HP:0040121),middle-ear-muscles (MEM) reflex, attenuation reflex, or auditory reflex

### 5. Which diseases are characterized by this term ? (e.g. Orphanet- or OMIM-id)
% 611572
OTOSCLEROSIS

**Comment by pnrobinson** [comment]
done
