### ISSUE TITLE
add syn to 'Subvalvular aortic stenosis'

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#4154]
add syn to 'Subvalvular aortic stenosis': Left Ventricular Outflow Tract Obstruction

@pnrobinson I am just assigning you so you can review this suggestion (and other tickets I submitted recently), I can add this.

**Comment by pnrobinson** [comment]
Probably LVOT should be physiology and all of the causes of LVOT should be in morphology

**Comment by nicolevasilevsky** [comment]
I think these hierarchies are already arranged properly. I didn't add any synonyms. Closing this ticket.
