### ISSUE TITLE
Suggesting new child term of "Focal seizures"

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#4158]
Suggest creating new child term of Focal seizures [HP:0007359] 
New term label: Migrating focal seizures
New term definition:  see http://n.neurology.org/content/77/4/e21
New term comment (if any): Check if a valid phjenotypic feature
New term synonyms(if any):
New term lay person synonyms (if any):
Reference (e.g., PubMed ID): see http://n.neurology.org/content/77/4/e21
Your biocurator ID for nanoattribution (if desired):

**Comment by shiva-g** [comment]
Epilepsiome Task Force consensus:
Term for migrating focal seizures added under non-ILAE classified focal seizures, will be provided to HPO team with epilepsy term revision

**Comment by pnrobinson** [comment]
This was replaced by issue: https://github.com/obophenotype/human-phenotype-ontology/issues/5402
