### ISSUE TITLE
Adding facial features for Helsmoortel-Van der Aa syndrome

### ISSUE THREAD

**Issue by ankevandijck** [obophenotype/human-phenotype-ontology#4167]
OMIM:615873

Please add the following missing Head and Neck features in bold:
These are all congenital features
Reference: Supplementary Table S4 in **PMID: 29724491**

   Facial feature,  Frequency, Total 
- [x] Thin upper vermillion70.3% 45/64 
- [x] Prominent forehead 65.6% 42/64
- [x] Wide nasal bridge 50.0% 33/66
- [x] **High hairline 50.0% 33/66**
- [x] Short nose 49.2% 31/63
- [ ] **Malformed ears 48.5% 32/66**
- [x] Upturned nasal tip 46.7% 28/60
- [ ] **Everted lower lip 45.5% 25/55**
- [ ] **Long philtrum 39.3% 22/56**
- [ ] Thick lower vermillion 36.4% 20/55
- [ ] Downward slant palpebral fissures 33.3% 20/60
- [ ] **Widely spaced teeth 34.6% 18/52**
- [ ] **Broad nasal base 29.6% 16/54**
- [ ] **Broad nasal tip 26.3% 15/57**
- [ ] **Teeth problems 24.5% 13/53**
- [ ] **Narrow palpebral fissures 24.1% 14/58**
- [ ] **Large mouth 23.2% 13/56**
- [ ] **Low nasal bridge 20.6% 13/63**
- [ ] **Eversion/notch eyelid 19.0% 12/63**
- [ ] **thick eyebrows 18.3% 11/60**
- [ ] **Coarse face 16.9% 11/65**
- [ ] **Prominent eyelashes 16.7% 10/60**
- [ ] **Broad philtrum 16.1% 9/56**
- [ ] **Low-set or posteriorly rotated ears 14.7% 10/68**
- [ ] **Abnormal hair thickness 14.0% 8/57**
- [ ] **Sagging periorbital skin 13.6% 8/59**
- [ ] **Small ears 11.6% 8/69**
- [ ] **Thick alae nasi 11.3% 6/53**

AND
- [ ] **Advanced eruption of teeth 81.5% 44/54** _source:_ **PMID: 28221363**

**Comment by pnrobinson** [comment]
thanks so much for this! I have added the frequencies.
