### ISSUE TITLE
NTR focal to bilateral tonic-clonic seizure

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#4169]
See https://www.ncbi.nlm.nih.gov/pubmed/28276062

**Comment by pnrobinson** [comment]
This was
Generalized tonic-clonic seizures with focal onset
https://hpo.jax.org/app/browse/term/HP:0007334
do we still need
Generalized tonic-clonic seizures without focal onset
https://hpo.jax.org/app/browse/term/HP:0025190
according to the new classification?

**Comment by ihelbig** [comment]
Hi Peter, our HPO revision team is currently at full steam. We should leave this term for now as this is an informative term from a prior classification that some patients may be been given. We can pull some data on how many individuals we have who were given this term and what would be lost if we detracted this. 
For now, I would leave this as is, but we'll discuss this amongst our team.

**Comment by pnrobinson** [comment]
I think this issue has been superceded by https://github.com/obophenotype/human-phenotype-ontology/issues/5333
