### ISSUE TITLE
Definition of Hyperactivity

### ISSUE THREAD

**Issue by ankevandijck** [obophenotype/human-phenotype-ontology#4172]
**Textual definition** 
Hyperactivity is a state of constantly being unusually or abnormally active, including in situations in which it is not appropriate.
_Source:_ https://www.nimh.nih.gov/health/topics/attention-deficit-hyperactivity-disorder-adhd/index.shtml

**### 5. Which diseases are characterized by this term ? (e.g. Orphanet- or OMIM-id)**
Helsmoortel-Van der Aa syndrome, OMIM 615873

**### 6. Your nano-attribution (ORCID-id or label, e.g. _HPO:probinson_ (organization:name))**
ORCID 0000-0002-6713-2943

**Comment by pnrobinson** [comment]
adding definition, thanks!

**Comment by pnrobinson** [comment]
added pmid to annotation.
