### ISSUE TITLE
Loinc 1798-8:  "Amylase [Enzymatic activity/volume] in Serum or Plasma"

### ISSUE THREAD

**Issue by jpgourdine** [obophenotype/human-phenotype-ontology#4173]
Suggest creating a new term for Loinc: 1798-8 [Amylase [Enzymatic activity/volume] in Serum or Plasma] 
New term label:Abnormal circulating Amylase level
New term comment (if any):child terms hyperamylasemia and hypoamylasemia, parent term Abnormality of circulating protein level HP:0010876
Your biocurator ID for loinc2hpo (if desired): OHSU:JP

**Comment by jpgourdine** [comment]
@pnrobinson and @nicolevasilevsky Hyperamylasemia is associated with pancreatitis and other diseases (PMID: 1702756) and hypoamylasemia with obesity and heart diseases (PMID: 27022442)

**Comment by nicolevasilevsky** [comment]
@pnrobinson if this looks okay to you, I can add it

**Comment by nicolevasilevsky** [comment]
note to self - need to add the children terms

**Comment by nicolevasilevsky** [comment]
I made a new term request to PRO for amylase. Closing this for now.
https://sourceforge.net/p/pro-obo/term-requests/131/

**Comment by nicolevasilevsky** [comment]
This term was added to PRO and will be available in the next PRO release:
id: PR:000049996
name: active alpha-amylase isozyme (human)

We should MIREOT it when it is available

**Comment by pnrobinson** [comment]
@nicolevasilevsky @drseb How are we doing with this?

**Comment by nicolevasilevsky** [comment]
Looks like this term is now available in PRO, I will add the logical def to this term.
