### ISSUE TITLE
Loinc 11178-1:  "Beta galactosidase IgE Ab [Units/volume] in Serum"

### ISSUE THREAD

**Issue by jpgourdine** [obophenotype/human-phenotype-ontology#4177]
Suggest creating a new term for Loinc: 11178-1 [Beta galactosidase IgE Ab [Units/volume] in Serum] 
New term label:beta galactosidase antibody positivity
New term comment (if any):parent term HP0030057 autoimmune antibody positivity
Your biocurator ID for loinc2hpo (if desired): OHSU:JP

**Comment by nicolevasilevsky** [comment]
@pnrobinson if this looks okay to you, I can add it

**Comment by pnrobinson** [comment]
@jpgourdine  I have tried to find some disease where these antibodies go up -- it seems to be extremely rare. I would suggest we not add this term, but if we can find a pubmed or so with these autoantibodies, lets reopen the issue.
