### ISSUE TITLE
NTR: meatus stenosis 

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#4180]
NTR: Meatus stenosis 
parent: HP_0000036 'Abnormality of the penis'
def: An abnormal narrowing of the urethral opening (meatus).
PMID:28537045

**Comment by pnrobinson** [comment]
Note that females also have a urethral meatus, and so this is not necessarily an abn of the penis. I am renaming to male meatus stenosis.
