### ISSUE TITLE
Review/Translation of HPO Medical Terms

### ISSUE THREAD

**Issue by GARDInfoCenter** [obophenotype/human-phenotype-ontology#4181]
@nicolevasilevsky 

We have reviewed our last batch of HPO Medical Terms. See attached document for our recommendations/suggestions. Some of the recommended terms are better suited for definition purposes. 
[HPO Medical Terms 10-24_301+_final_submitted.xlsx](https://github.com/obophenotype/human-phenotype-ontology/files/2466068/HPO.Medical.Terms.10-24_301%2B_final_submitted.xlsx)

@GARDInfoCenter
ORCID: 0000-0002-6548-5200

**Comment by nicolevasilevsky** [comment]
@GARDInfoCenter I added all the synonyms in your spreadsheet, please see this [google doc ](https://docs.google.com/spreadsheets/d/1oSTYR-NPmpHp9-9Ty5dSVHZwDK0jK5FchuDFxMKOWtI/edit#gid=1000495672) for any comments or revisions. Let me know if you have any questions. Closing this ticket but feel free to reopen if needed.
