### ISSUE TITLE
Synovial cyst of popliteal space

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#4182]
_For new term requests, please provide us with the following information:_
### 1. Preferred term label

Synovial cyst of popliteal space

### 2. Synonyms

Baker's cyst

### 3. Textual definition (should be understandable even for non-specialists, please include a PubMed ID for relevant articles providing additional information about the suggestion)

A fluid-filled cyst that causes a bulge and the feeling of tightness behind the knee.

Reported via email: 

> I evaluated a child with a probable genetic disease not yet diagnosed. He had a popliteal cyst; I used phenomizer, and I couldn't find this phenotype finding in hpo, that's why I asked for it inclusion.

**Comment by pnrobinson** [comment]
good reference: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4481672/
