### ISSUE TITLE
structure of Eosinophilia 

### ISSUE THREAD

**Issue by kingmanzhang** [obophenotype/human-phenotype-ontology#4183]
*Eosinophilia* and *Decreased eosinophil count* are currently under *Abnormal eosinophil morphology*. Is this the best design? Can we at least create an intermediate term such as *Abnormal eosinophil count*?

**Comment by nicolevasilevsky** [comment]
yes, I agree. A lot of terms are structured that way, like abnormality of neutrophils, abnormal neutrophil count are children of abnormal granulocyte morphology.

@pnrobinson could we restructure the hierarchy for all these terms? I think it would be nice to have a term 'abnormal leukocyte count' as a child of 'Abnormality of cellular immune system'

**Comment by pnrobinson** [comment]
Well, I think that abnormal count can be considered as a subtype of abnormal morphology, and the advantage of leaving it here would be that HPO users can also differentiate between physioliogy and things that you can see in a 2d picture (like abnormal shape or abnormal count). In PATO, I think the abnormal count terms are all under morphology? @drseb

**Comment by LCCarmody** [comment]
With the current dichotomy being between physiology and morphology, I would argue this would go under morphology.  I am not sure PATO helps that argument: has number and morphology are sibling classes.  https://www.ebi.ac.uk/ols/ontologies/pato/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0001241

**Comment by nicolevasilevsky** [comment]
sounds like it is best to leave it under abn morphology. Should we create an intermediate class for eosinophils, Abnormal eosinophil count, as @kingmanzhang suggested?

**Comment by kingmanzhang** [comment]
@nicolevasilevsky I think this is agreed on.
