### ISSUE TITLE
Issue in phenotype_annotation.tab file

### ISSUE THREAD

**Issue by kchennen** [obophenotype/human-phenotype-ontology#4184]
In the column the 4th column (qualifiers) found the words Moderate, MODERATE, PROFOUND, PROGRESSIVE, RECURRENT, REFRACTORY. Shouldn't theses words be converted in HPO terms as well? Ex: HP:0031375 instead of REFRACTORY.

**Comment by pnrobinson** [comment]
Thanks for this suggestion!
The HPO project is experimenting with new annotation formats -- the file phenotype.hpoa actually implements your suggestion, see here:
https://hpo.jax.org/app/download/annotation
We are probably going to move to making the new format our main format by the end of the year.
