### ISSUE TITLE
missing some intermediate nodes for cranial skeletal system

### ISSUE THREAD

**Issue by mellybelly** [obophenotype/human-phenotype-ontology#4185]
It would be great for example, to have:

Abnormality of the skeletal system
--Abnormality of the cranial skeletal system (new)
----Abnormality of the dentition 

This is just one example, the Uberon cranial skeletal features have had a lot of review by many experts and we should review what the classification would look like if it mirrored Uberon.

**Comment by pnrobinson** [comment]
There are lots of terms that reflect the way clinicians categorize the bones in the head. Currently, I do not think that teeth are connected to skull in the hierarchy, but I am not sure that people are expecting this. Let's talk about use cases!

**Comment by pnrobinson** [comment]
@mellybelly I have reviewed the terms and do not see anything that I think a clinician would miss at this point. I would suggest it would be great to have a workshop on this topic if possible but it is probably best not to work on this in an ad hoc fashion unless there are concrete mistakes. The dental section is part of oral cavity/mouth/head and should be easy to navigate.
