### ISSUE TITLE
Further Ophthalmoparesis terms? 

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#4186]
_For new term requests, please provide us with the following information:_
### 1. Preferred term label

Vertical ophthalmoparesis

Horizontal ophthalmoparesis

@psergouniotis

**Comment by pnrobinson** [comment]
OK. I also add this definition, please reopen if it is suboptimal

A type of incomitant strabismus in which the angle of deviation varies as the patient's gaze shifts horizontally.

(similar for vertical)
