### ISSUE TITLE
Typo in Preauricular skin tag HP:0000384

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#4192]
HP:0000384

A rudimentary tag of sking often containing ear tissue including a core of cartilage and located just anterior to the auricle (outer part of the ear).

**Comment by pnrobinson** [comment]
@nicolevasilevsky  in case this was copy pasted please note spelling error above!

**Comment by nicolevasilevsky** [comment]
i fixed sking to skin
