### ISSUE TITLE
Limbal stem cell deficiency

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#4196]
NTR see https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4691643/

**Comment by pnrobinson** [comment]
@psergouniotis, see https://github.com/obophenotype/human-phenotype-ontology/issues/3110

**Comment by psergouniotis** [comment]
term: "Limbal stem cell deficiency"

definition: "A condition characterized by a loss or deficiency of the stem cells in the limbus that are vital for re-population of the corneal epithelium and to the barrier function of the limbus." (http://eyewiki.aao.org/Limbal_Stem_Cell_Deficiency)

parent term: "Abnormal anterior segment morphology" (please ignore #3110)
