### ISSUE TITLE
Homeostasis terms

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#4197]
I am beginning to wonder if it wouldnt be better to rename of the the terms such as

Abnormality of potassium homeostasis 

to 

Abnormal potassium concentration

-- since many people will not really understand what we mean by "Homeostasis"  

@drseb @mellybelly @cmungall @nicolevasilevsky @LCCarmody  -- comments?

**Comment by drseb** [comment]
I am a big fan of labels (and logical definitions) that reflect what is really measured. And in most cases it is the concentration/amount that is measured and not the process (homeostasis, pigmentation, etc). I am going to discuss this in the phenotype-onto-call in 2 weeks as well...

**Comment by pnrobinson** [comment]
It looks like Seb and I are in agreement and nobody else violently disagrees. I think we are scheduled to talk about the immunology terms this Friday, let's also try to finalize a plan for this!

**Comment by pnrobinson** [comment]
I think that we are all in agreement with this, and so let's go ahead and rename these terms. @LCCarmody @nicolevasilevsky could we speak about this after thanksgiving?

**Comment by LCCarmody** [comment]
These are the ones I could find.  Change them to 'Abnormality of x concentration'?  It looks like it should work for all.

- [ ] 'Abnormality of ion homeostasis' <http://purl.obolibrary.org/obo/HP_0003111>
- [ ] 'Abnormality of iron homeostasis' <http://purl.obolibrary.org/obo/HP_0011031>
- [ ] 'Abnormality of zinc homeostasis' <http://purl.obolibrary.org/obo/HP_0008277>
- [ ] 'Abnormality of urine homeostasis' <http://purl.obolibrary.org/obo/HP_0003110>
- [ ] 'Abnormality of cation homeostasis' <http://purl.obolibrary.org/obo/HP_0010929>
- [ ] 'Abnormality of copper homeostasis' <http://purl.obolibrary.org/obo/HP_0010836>
- [ ] 'Abnormality of sodium homeostasis' <http://purl.obolibrary.org/obo/HP_0010931>
- [ ] 'Abnormality of calcium homeostasis' <http://purl.obolibrary.org/obo/HP_0004363>
- [ ] 'Abnormality of chloride homeostasis' <http://purl.obolibrary.org/obo/HP_0011422>
- [ ] 'Abnormality of acid-base homeostasis' <http://purl.obolibrary.org/obo/HP_0004360>
- [ ] 'Abnormality of magnesium homeostasis' <http://purl.obolibrary.org/obo/HP_0004921>
- [ ] 'Abnormality of phosphate homeostasis' <http://purl.obolibrary.org/obo/HP_0100529>
- [ ] 'Abnormality of potassium homeostasis' <http://purl.obolibrary.org/obo/HP_0011042>
- [ ] 'Abnormality of metabolism/homeostasis' <http://purl.obolibrary.org/obo/HP_0001939>
- [ ] 'Abnormality of blood volume homeostasis' <http://purl.obolibrary.org/obo/HP_0011104>
- [ ] 'Abnormality of nitrogen compound homeostasis' <http://purl.obolibrary.org/obo/HP_0004364>
- [ ] 'Abnormality of carbohydrate metabolism/homeostasis' <http://purl.obolibrary.org/obo/HP_0011013>
- [ ] 'Abnormality of divalent inorganic cation homeostasis' <http://purl.obolibrary.org/obo/HP_0010927>
- [ ] 'Abnormality of transition element cation homeostasis' <http://purl.obolibrary.org/obo/HP_0011030>
- [ ] 'Abnormality of monovalent inorganic cation homeostasis' <http://purl.obolibrary.org/obo/HP_0010930>

**Comment by pnrobinson** [comment]
I have refactored the above items. Still some work to be done, but I think we can close this issue.
