### ISSUE TITLE
Proposed humoral immunity hierarchy

### ISSUE THREAD

**Issue by mh11** [obophenotype/human-phenotype-ontology#4200]
Please find the updated structure suggestion for the humoral immunity attached, which was proposed during the Immunodeficiency HPO meeting in Vienna.

![humoral_immunity_1](https://user-images.githubusercontent.com/946740/46954211-45d11b00-d090-11e8-96b2-6ab9b3ee4a61.jpg)
![humoral_immunity_2](https://user-images.githubusercontent.com/946740/46954212-45d11b00-d090-11e8-8ee1-ae487d0703de.jpg)

**Comment by LCCarmody** [comment]
Related ticket: https://github.com/obophenotype/human-phenotype-ontology/issues/3957

**Comment by pnrobinson** [comment]
Most of these terms are now in place, but we still need to add the detailed terms.

**Comment by nicolevasilevsky** [comment]
I reviewed all the terms on page 1 of the handwritten doc and here is what is missing:

- (Near) absent IgA in blood (parent: 'Decreased circulating total IgA')
- Partially reduced IgA in blood (parent: 'Decreased circulating total IgA')
- (Near) absent IgE in blood (parent: 'Decreased circulating total IgE')
- Partially reduced IgE in blood (parent: 'Decreased circulating total IgE')
- (Near) absent IgM in blood (parent: 'Decreased circulating total IgM')
- Partially reduced IgM in blood (parent: 'Decreased circulating total IgM')

- Abnormal natural antibody to blood group agents (isohemoglutinin) (_**note:**_ we have HP_0032139 'Reduced isohemagglutinin level', is this different?)
  - Absent natural antibody to blood group agents
  - Decreased natural antibody to blood group agents

- Need children of 'Decreased specific antibody response to vaccination':
- Decreased specific antibody response to protein vaccine
  - Complete or near-complete absence of specific antibody response to tetanus vaccine
  - Complete or near-complete absence of specific antibody response to hepatitis B vaccine
  - Partial absence of absence of specific antibody response to tetanus vaccine
  - Partial absence of absence of specific antibody response to hepatitis B vaccine
- Decreased specific antibody response to polysaccharide vaccine
  - Complete or near-complete absence of specific antibody response to pneumococcus vaccine
  - Partial absence of absence of specific antibody response to pneumococcus vaccine
- Decreased specific antibody response to protein-conjugated polysaccharide vaccine
  - Complete or near-complete absence of specific antibody response to haemophilus H type B vaccine
  - Complete or near-complete absence of specific antibody response to meningococcus vaccine
  - Partial absence of absence of specific antibody response to haemophilus H type B vaccine
  - Partial absence of absence of specific antibody response to meningococcus vaccine
- Decreased specific antibody response to injection


@pnrobinson - I can add these if this looks okay to you

**Comment by pnrobinson** [comment]
Hi Nicole -- these look great. I think that Reduced isohemagglutinin level is a synonym for Decreased natural antibody to blood group agents (Reduced isohemagglutinin level should be the primary label). 
The three children of Decreased specific antibody response to vaccination look good. I am not sure what is meant by  Decreased specific antibody response to injection ?? Is this obvious to you or should we ask the immunologists for input?

**Comment by nicolevasilevsky** [comment]
I am not sure about 'Decreased specific antibody response to injection' means either - please do ask the immunologists for input.

I'll work on adding these other terms.

**Comment by nicolevasilevsky** [comment]
@pnrobinson I have a question about these terms:
 
- (Near) absent IgA in blood (parent: 'Decreased circulating total IgA')
- Partially reduced IgA in blood (parent: 'Decreased circulating total IgA')
- (Near) absent IgE in blood (parent: 'Decreased circulating total IgE')
- Partially reduced IgE in blood (parent: 'Decreased circulating total IgE')
- (Near) absent IgM in blood (parent: 'Decreased circulating total IgM')
- Partially reduced IgM in blood (parent: 'Decreased circulating total IgM')

The parent class 'Decreased circulating total IgA' is defined as:
Undetectable serum immunoglobulin A level at a value < 5 mg/dL (0.05 g/L).

I think the current def for 'decreased circulating total IgA' is better suited for the (near) absent term.

I think Partially reduced IgX in blood could be a synonym for 'Decreased circulating total IgX'.
 
[Medline](https://emedicine.medscape.com/article/885348-workup) describes partial IgA deficiency as a serum IgA level less than that expected for the patient's age (ie, < 2 standard deviations from the mean). (ref: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1182202/).

**Comment by nicolevasilevsky** [comment]
Note: based on the diagram above, it was recommended that 'Abnormal isohemagglutinin level' be a child of 'Decreased circulating level of specific antibody', I added it this way, but it seems wrong to have an abnormal term be a child of a 'decreased' term. Should I move 'Abnormal isohemagglutinin level' and its children to be a child of 'Abnormal immunoglobulin level' or create a new grouping class 'Abnormal circulating level of specific antibody'?

**Comment by nicolevasilevsky** [comment]
These are the terms from the second screenshot. The terms in **bold** need to be added to HPO.

- Increased antibody level in blood
-- Increased total IgG in blood
--- **Increased monoclonal IgG in blood**
--- **Increased oligo/polyclonal IgG in blood**
-- **Increased IgG subclass**
--- **Increased IgG1**
---- **Increased monoclonal IgG1**
---- **Increased oligo/polyclonal IgG1**
--- **Increased IgG2**
---- **Increased monoclonal IgG2**
---- **Increased oligo/polyclonal IgG**
--- **Increased IgG3**
---- **Increased monoclonal IgG3**
---- **Increased oligo/polyclonal IgG3**
--- **Increased IgG4**
---- **Increased monoclonal IgG4**
---- **Increased oligo/polyclonal IgG4**
-- Increased total IgA in blood - **we have HP_0003261 'Increased IgA level'** *_See question below_
--- **Increased monoclonal IgA in blood**
--- **Increased oligo/polyclonal IgA in blood**
-- Increased total IgM in blood **we have HP_0003496 ''Increased IgM level'** *_See question below_
--- **Increased monoclonal IgM in blood**
--- Increased oligo/polyclonal IgM in blood - **we have HP_0003459 'Polyclonal elevation of IgM'. Add this as primary label and make polyclonal elevation of IgM a synonym?**
-- Increased total IgE in blood - **we have HP_0003212 'Increased IgE level'** *_See question below_
--- **Increased monoclonal IgE in blood**
--- **Increased oligo/polyclonal IgE in blood**

***Question:**
For HP_0410244 'Abnormal IgD level', there is a subclass HP_0410245 'Decreased circulating total IgD'. 

HP_0003237 'Increased IgG level' has a synonym, Increased total IgG in blood.

Should the total Ig term be a synonym or a subclass of the Increased IgX level term?

**Comment by mh11** [comment]
> I am not sure about 'Decreased specific antibody response to injection' means either - please do ask the immunologists for input.
> 
> I'll work on adding these other terms.

Hi @nicolevasilevsky 
I checked with the author and it should read 

**Decreased specific antibody response to infection** 

Apologies from the author for the poor hand writing / confusion.
Hope this helps.

**Comment by nicolevasilevsky** [comment]
@mh11 thanks for the clarification!

@pnrobinson I will add Decreased specific antibody response to infection as a child of 'Decreased circulating level of specific antibody'

**Comment by pnrobinson** [comment]
@nicolevasilevsky  I have added some terms and restructured a bit. The old "increased" Ig* terms always refered to increased total Ig*. I think that oligo and poly terms are meant to be separate. If you can help to add some of the remaining ones that would be great, I am confused a little as to where we are...

**Comment by pnrobinson** [comment]
See also this for https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4519726/

**Comment by pnrobinson** [comment]
I think we have now added all of the relevant terms and should have the immunology teams review this before proceding further.
