### ISSUE TITLE
Proposed lymphocyte count structure

### ISSUE THREAD

**Issue by mh11** [obophenotype/human-phenotype-ontology#4201]
Please find the updated structure suggestion for the lymphocyte count attached, which was proposed during the Immunodeficiency HPO meeting in Vienna.

![lymphocyte_count](https://user-images.githubusercontent.com/946740/46954421-d27bd900-d090-11e8-9e14-2d47e6dfcc31.jpg)

**Comment by LCCarmody** [comment]
Related ticket: https://github.com/obophenotype/human-phenotype-ontology/issues/4054

**Comment by pnrobinson** [comment]
- [ ] naive
- [ ] transitional
- [ ] non-switched memory B cells
- [ ] CD21low B cells
- [ ] plasmablasts

**Comment by pnrobinson** [comment]
done!
