### ISSUE TITLE
Proposed neutrophils changes

### ISSUE THREAD

**Issue by mh11** [obophenotype/human-phenotype-ontology#4202]
Please find the updated structure suggestion for the neutrophils attached, which was proposed during the Immunodeficiency HPO meeting in Vienna.

[Updated_structure_neutrophils.xlsx](https://github.com/obophenotype/human-phenotype-ontology/files/2478949/Updated_structure_neutrophils.xlsx)

**Comment by nicolevasilevsky** [comment]
Related: #4218

**Comment by nicolevasilevsky** [comment]
Added new term 'neutropenia   in myeloid maturation arrest in bone marrow' - what does the note 
HAXI ELANE   JAGNI, 66PC3, CDF3R, 6FI1, WAS (GoF) mean?

**Comment by nicolevasilevsky** [comment]
Added new term: Absent neutrophil specific granules - there is a note to add gene SMARCD2

**Comment by nicolevasilevsky** [comment]
Obsoleted HP_0005549 Congenital neutropenia
Note- updated annotations for OMIM files below, to Neutropenia with clinical modifier, congenital onset:
OMIM-257100
OMIM-300299
OMIM-613107

**Comment by nicolevasilevsky** [comment]
Everything in the spreadsheet has been addressed with the exception of the autoimmune neutropenia question above

**Comment by mh11** [comment]
Thanks for the quick workup - will check regarding the autoimmune neutropenia question.

**Comment by pnrobinson** [comment]
I think the answer is yes, and I am adding this as a synonym and extending the definition.
