### ISSUE TITLE
Proposed immune system physiology changes

### ISSUE THREAD

**Issue by mh11** [obophenotype/human-phenotype-ontology#4203]
Please find the updated structure suggestion for the immune system physiology attached, which was developed during the Immunodeficiency HPO meeting in Vienna.

[Update_structure_infections.xlsx](https://github.com/obophenotype/human-phenotype-ontology/files/2478969/Update_structure_infections.xlsx)

**Comment by nicolevasilevsky** [comment]
sure thing @pnrobinson!

**Comment by mh11** [comment]
A big thank you for going through the notes. Please let me know if you would like some feedback on the new structure.

**Comment by pnrobinson** [comment]
@LCCarmody @nicolevasilevsky can we split the work to get these terms in? Can we talk next week?

**Comment by pnrobinson** [comment]
I have added the terms. Some refer to simple infections (not unusual infections), but I think that they mean the unusual varieties, and I think that current terms largely cover this.
