### ISSUE TITLE
"Increased anti-meat allergen IgE antibody level" include mammalian

### ISSUE THREAD

**Issue by jpgourdine** [obophenotype/human-phenotype-ontology#4204]
Increased anti-meat allergen IgE antibody level

Should be rephrased as

Increased anti-**mammalian** meat allergen IgE antibody level

Based on the given definition (Increased level of IgE antibody against a mammalian meat, directed against the mammalian oligosaccharide epitope galactose-alpha-1,3-galactose.)

It is confusing for the annotation of non-mammalian type of meat (duck, chicken).

Thanks

@pnrobinson and @nicolevasilevsky

**Comment by nicolevasilevsky** [comment]
good catch - I'll revise the definition.

**Comment by nicolevasilevsky** [comment]
I updated the definition, @jpgourdine, so we can still use this term for any meat allergy terms

**Comment by jpgourdine** [comment]
Ok, I gotta corrected some annotation then !
Thanks
