### ISSUE TITLE
Loinc annotation question for D-Lactate in serum

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#4205]
@kingmanzhang started this annotation but had a question.  I think the alternative should be used, but would like another opinion.

Currently, it is annotated as 'Lactic acidosis' (HP:0003128)  is high for this test, but 'Increased serum lactate' is also a choice.  I would argue that it should be 'Increased serum lactate' (HP:0002151).  These are two sibling classes, also.   Should 'Lactic acidosis' be a child of Increased serum lactate'? Or synonyms?
There are several loinc annotation terms that would be resolved by answering this question  @pnrobinson  Or others?

**Comment by kingmanzhang** [comment]
@jpgourdine  annotated many lactate tests as *Increased serum lactate*. Maybe we should just choose this?

**Comment by jpgourdine** [comment]
Lactic acidosis HP:0003128 is defined on HPO as "An abnormal buildup of lactic acid in the body, leading to acidification of the **blood and other bodily fluids**".
while Increased serum lactate is only in the blood
So maybe "Increased serum lactate" for D-Lactate in serum?

**Comment by LCCarmody** [comment]
Sounds reasonable.  Do you think the two should remain sibling classes then?

**Comment by nicolevasilevsky** [comment]
@LCCarmody yes, I think so

**Comment by jpgourdine** [comment]
I don't think so, Lactic acidosis should be the parent of "Increased serum lactate" or  [lactacidemia ](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4842792/) let's double check with @nicolevasilevsky  and @pnrobinson

**Comment by nicolevasilevsky** [comment]
Oh sorry, all, I wasn't looking at this very closely.

Lactic acidosis is defined in the text def as increased lactic acid in the blood and other body fluids, but the logical def says it is just in the blood (and the logical def uses '[rac-lactic acid](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:28358)'.

The logical def for 'Increased serum lactate' is in the blood serum. 

I think these two terms should be siblings, because 'increased serum lactate' is more specific than 
Lactic acidosis. Blood and blood serum are siblings in UBERON.

**Comment by pnrobinson** [comment]
So, I think that what we measure is just in the blood; we infer that the acidosis affects tissue in general -- this is for instance why muscles hurt if we go anaerobic. I think we should probably revise the English-language definition to describe the test more precisely, which is in fact for lactate in blood only!

**Comment by pnrobinson** [comment]
Also, in general the HPO terms do not care about the distinctions between plasma, serum, blood -- I think there are very few cases where too high in serum does not have the same interpretation as too high in blood etc. So we should not have separate terms for plasma/serum/blood

**Comment by LCCarmody** [comment]
Increased lactate in circulation

**Comment by pnrobinson** [comment]
revise definition according to https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3975915/

**Comment by pnrobinson** [comment]
duplicate -- see https://github.com/obophenotype/human-phenotype-ontology/issues/3784
