### ISSUE TITLE
def is wrong

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#4208]
An elevation in bone density in one or more distal phalanges of the fourth finger. Sclerosis is normally detected on a radiograph as an area of increased opacity.

**Comment by pnrobinson** [comment]
def of what term?

**Comment by drseb** [comment]
Please have a look at this commit: https://github.com/obophenotype/human-phenotype-ontology/commit/caf45c4b4364fdabb49b0c1405d52205eb71ab48

There were several terms that were not about the distal part of the phalanges, but their definition was IMHO referring to the wrong part (i.e. the distal part). I hope it is ok now. Is it?

**Comment by pnrobinson** [comment]
So you removed "distal" in the definition for terms like  (Sclerosis of 5th finger phalanx) -- yes, that makes sense.

**Comment by drseb** [comment]
Exactly. Will close then
