### ISSUE TITLE
Loinc 3040-3:  "Lipase [Enzymatic activity/volume] in Serum or Plasma"

### ISSUE THREAD

**Issue by kingmanzhang** [obophenotype/human-phenotype-ontology#4211]
Suggest creating a new child term of HP:0031209 [Decreased lipoprotein lipase activity] for Loinc 3040-3 [Lipase [Enzymatic activity/volume] in Serum or Plasma]
New term label: Increased lipase activity (sort of)
New term comment (if any): An additional point is that we may need to create intemediate terms like *Abnormal X enzyme activity*, otherwise mapping normal finding of one particular enzyme to NOT *Abnormal enzyme/coenzyme activity* is an overinterpretation of a LOINC test.
Your biocurator ID for loinc2hpo (if desired): JGM:azhang

**Comment by pnrobinson** [comment]
I think there are multiple lipases -- we need to find out which one  this is talking about. I am not sure that a generic lipase term makes much sense.

**Comment by kingmanzhang** [comment]
It does not appear to me there are detailed tests. Here is a list of LOINC that has "lipase" in their names. Not all are lipoprotein lipases. But I don't see various phospholipases except A2. I suggest we create the parent term and child for A2, and add others in future when necessary.

LOINC_NUM     | LONG_COMMON_NAME
----------------|-------------------------
10888-6 | Lipase [Enzymatic activity/volume] in Urine
15212-4 | Lipase [Enzymatic activity/volume] in Body fluid
15932-7 | Phospholipase IgE Ab RAST class [Presence] in Serum
25543-0 | Lipase [Enzymatic activity/time] in 24 hour Urine
2572-6 | Lipoprotein lipase [Enzymatic activity/volume] in Serum or Plasma
25992-9 | Lipase [Enzymatic activity/volume] in 24 hour Urine
3039-5 | Lipase [Enzymatic activity/volume] in Amniotic fluid
3040-3 | Lipase [Enzymatic activity/volume] in Serum or Plasma
32722-1 | Lipase [Enzymatic activity/volume] in Peritoneal fluid
35313-6 | Lipase [Enzymatic activity/volume] in Body fluid --5th specimen post Sincalide
35314-4 | Lipase [Enzymatic activity/volume] in Body fluid --4th specimen post Sincalide
35315-1 | Lipase [Enzymatic activity/volume] in Body fluid --3rd specimen post Sincalide
35316-9 | Lipase [Enzymatic activity/volume] in Body fluid --2nd specimen post Sincalide
35364-9 | Lipase [Enzymatic activity/volume] in Body fluid --1st specimen post Sincalide
39804-0 | Lipoprotein associated phospholipase A2 [Mass/volume] in Serum or Plasma
47418-9 | Lipase [Enzymatic activity/volume] in Pleural fluid
55934-4 | Lipase [Enzymatic activity/volume] in Dialysis fluid
58983-8 | Honey bee phospholipase A2 native (nApi m) 1 IgE Ab [Units/volume] in Serum
60241-7 | Honey bee phospholipase A2 recombinant (rApi m) 1 IgE Ab RAST class [Presence] in Serum
60421-5 | Honey bee phospholipase A2 recombinant (rApi m) 1 IgE Ab [Units/volume] in Serum
72272-8 | Amylase and triacylglycerol lipase panel - Serum or Plasma
73737-9 | Phospholipase A2 receptor IgG Ab [Units/volume] in Serum by Immunoassay
7600-0 | Phospholipase IgE Ab [Units/volume] in Serum
76614-7 | Lysosomal acid lipase [Enzymatic activity/mass] in Fibroblast by 4-MU-oleate substrate
76615-4 | Lysosomal acid lipase [Enzymatic activity/mass] in Fibroblast by 4-MU-palmitate substrate
76621-2 | Lysosomal acid lipase panel - Fibroblast
76622-0 | Lysosomal acid lipase [Interpretation] in Fibroblast Narrative
81201-6 | Phospholipase A2 receptor IgG Ab [Titer] in Serum by Immunofluorescence
82009-2 | Honey bee phospholipase A2 native (nApi m) 1 IgE Ab RAST class [Presence] in Serum
82991-1 | Phospholipase A2 receptor IgG Ab [Presence] in Serum or Plasma by Immunofluorescence
82883-0 | Lysosomal acid lipase [Enzymatic activity/mass] in Leukocytes by 4-MU-palmitate substrate
82926-7 | Phospholipase A2 receptor IgG Ab [Presence] in Serum by Immunoassay
86951-1 | Lipoprotein associated phospholipase A2 [Enzymatic activity/volume] in Serum or Plasma
87717-5 | Honey bee phospholipase A2 recombinant (rApi m) 2 IgE Ab RAST class [Presence] in Serum

**Comment by LCCarmody** [comment]
For the general lipase, I believe they are refering to triacylglycerol lipase. PR doesn't have a general  'triacylglycerol lipase' but uses 'hepatic  triacylglycerol lipase' or 'pancreatic  triacylglycerol lipase'.  Maybe this should be a PR request?

**Comment by nicolevasilevsky** [comment]
yes, I think it is triacylglycerol lipase and I think we should request the more general term from PR

**Comment by pnrobinson** [comment]
As far as I can see there is no current use where one would just measure lipase activity. There are a number of more specific enzymes that can be measured in various circumstances. I suspect that this is a legacy LOINC, or something that is not performed much in modern hospitals.  There is not a lot in PubMed about this and so I propose we close this until we get some more specific disease annotations.
