### ISSUE TITLE
Logical Def question about hyperoxemia and hyperoxemia in cord blood

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#4213]
@nicolevasilevsky and I were working on blood gas terms.  Nicole suggested these definitions.  Should we use 'oxygen atom' or  ‘oxygen molecular entity’ ?  Also, not sure if we should manually assert that 'Hyperoxemia in cord blood' is a child of Hyperoxemia.  Currently they are in separate branches.

@drseb @pnrobinson 

Hyperoxemia
'has part' some
    ('increased amount'
and ('part of' some 'oxygen atom'
and ('inheres in' some blood))
     and ('has modifier' some abnormal))
 
'Hyperoxemia in cord blood'
'has part' some
    ('increased amount'
and ('part of' some 'oxygen atom'
and ('inheres in' some 'umbilical cord blood'))
     and ('has modifier' some abnormal))

**Comment by nicolevasilevsky** [comment]
@drseb can you MIREOT CHEBI:15379 dioxygen
