### ISSUE TITLE
Loinc 2336-6:  "Globulin [Mass/volume] in Serum"

### ISSUE THREAD

**Issue by jpgourdine** [obophenotype/human-phenotype-ontology#4214]
Suggest creating a new term for Loinc: 2336-6 [Globulin [Mass/volume] in Serum] 
New term label:Abnormal circulating globulin 
New term comment (if any):Child term : abnormal beta globulin level HP0025465
Your biocurator ID for loinc2hpo (if desired): OHSU:JP
@nicolevasilevsky

**Comment by jpgourdine** [comment]
Hi @pnrobinson ,
It looks like it Globulin test is still in used.
I found [here](https://medlineplus.gov/lab-tests/globulin-test/) that globlulin test are used for diagnoses of Liver damage or disease, Kidney disease, Nutritional problems, Autoimmune disorders, certain types of cancer. Globulin test are preformed by [Serum Protein Electrophoresis ](https://www.uofmhealth.org/health-library/hw43650) or Total Protein test (Albumin/Globulin ration)

**Comment by pnrobinson** [comment]
fixed the alpha-globulin mistake

**Comment by pnrobinson** [comment]
Adding Abnormal circulating globulin level as HP_0032179
