### ISSUE TITLE
Synonym 'Facial Dysmorphism' is duplicated in HP:0001999 (hp.obo)

### ISSUE THREAD

**Issue by kennethcywong** [obophenotype/human-phenotype-ontology#4215]
In the hp.obo file (releases/2018-10-09), below 2 synonyms of Term HP:0001999 are duplicated. Their content are the same, but with different SCOPE.

synonym: "Facial Dysmorphism" BROAD [ORCID:0000-0001-5889-4463]
synonym: "Facial dysmorphism" EXACT [ORCID:0000-0001-5889-4463]

When these synonym names are imported to MySQL DB, the second name is skipped (as the name is defined as primary key). Would you please help to answer the following questions:

1. Which SCOPE should the synonym 'facial dysmorphism'(case-insensitive) belongs to ? EXACT or BROAD?
2. Should the 2 synonym names be combined into 1? If not, is there any reason behind keeping these 2 synonym names with same content, but having different SCOPE?

Similar case was found in HP:10011529:
synonym: "Multiple bilateral CHRPE" EXACT []
synonym: "Multiple bilateral chrpe" EXACT []

Thanks for your help and reply!
Kenneth Wong

**Comment by pnrobinson** [comment]
Strange. This is the term
https://hpo.jax.org/app/browse/term/HP:0001999
actually, facial dysmorphism is one of those terms that is a little difficult to define exactly in text. I think we can classify it as an exact synonym and delete the "BROAD"-this was a mistake. 

The other term is this
https://hpo.jax.org/app/browse/term/HP:0011529
We should delete this: "Multiple bilateral chrpe"

**Comment by pnrobinson** [comment]
done

**Comment by kennethcywong** [comment]
Many thanks for your promptly help!
