### ISSUE TITLE
Make template definition for Unusual X infection

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#4216]

**Comment by pnrobinson** [comment]
See https://www.ncbi.nlm.nih.gov/pubmed/22052638

**Comment by LCCarmody** [comment]
Not sure if this should be added.  There was a request at the hackathon (https://github.com/obophenotype/human-phenotype-ontology/issues/4004) for this term as a phenotype.  It is a phenotype in OMIM: 618131, OMIM:243700  and others.  Should it also be a MONDO term?

**Comment by pnrobinson** [comment]
This is an important phenotype for many immunological diseases. I do not think that the specific subterms are usually called Unusual X infection though

**Comment by LCCarmody** [comment]
That makes sense. I am happy to add it.  I assume Molluscum contagiosum should be under 'Opportunistic infections'.  But I think there needs to be a bit more added to the hierarchy, since it doesn't fit under 'Severe viral infections' or 'Disseminated viral infections'.  Should another term be added as 'Opportunistic viral infections' as parent of all 3?  

If this looks okay, I will add it and close #4004 

>Opportunistic infections
   >> Opportunistic viral infections
      >>>Molluscum contagiosum
      >>> Dissemeniated viral infections
      >>> Severe viral infections

**Comment by cmungall** [comment]
Does this term violate the TPR as we move to common disease?

"A type of infection that is regarded as a sign of a pathological susceptibility to infection."

E.g

https://www.ebi.ac.uk/ols/ontologies/hp/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FHP_0031700

![image](https://user-images.githubusercontent.com/50745/54089672-dd861d00-4341-11e9-8eee-7e0fc8679068.png)

**Comment by pnrobinson** [comment]
This is being modelled as an unusual infection. These terms are basically a history of an unusual infection and are not modelling the disease itself, which will go in Mondo and which in the future we need to explicitly link to. Perhaps it would be better to relable the term "Opportunistic parasitic infection" -- is that what you are referring to @cmungall  ?

**Comment by pnrobinson** [comment]
I think we now have a good structure in this area, closing.
