### ISSUE TITLE
neutrophil azurophil granules

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#4221]
Do we need a term for abnormalities of these granules? They are one of two neutrophil granule types.

**Comment by nicolevasilevsky** [comment]
not sure if this is needed.

This paper describes a patient with neutropenia where the specific granules are affected, but not the azurophil granules: https://www.ncbi.nlm.nih.gov/pubmed?term=1174707

There is this disease in [OMIM](https://www.omim.org/entry/245480?search=azurophil%20granules&highlight=azurophil%20granule), where the specific granules are affected, not the azurophil granules

**Comment by pnrobinson** [comment]
I also could not find anything. Let's close this for now.
