### ISSUE TITLE
Mistaken annoation

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#4222]
(from email request): "OMIM:170400" ? The description of Hypokalemic Periodic Paralysis, Type 1 was  associated with a fall in blood potassium levels while the definition of "HP:0007215" was associated with elevated levels of potassium in the blood.

-> This seems to be a mistake in our file, we will correct it!

**Comment by LCCarmody** [comment]
Updated in PhenoteFX.  Should we put annotations issues here? or in hpo-annotation-data?
