### ISSUE TITLE
NTR: children of hemangioma

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#4223]
New terms needed for Kid's First curation:

Parent term: HP_0001028 Hemangioma
- **airway hemangioma**: A hemangioma, a benign tumor of the vascular endothelial cells, located in the airway, typically below the vocal chords, that can cause severe obstruction of the airway. **Syn:** subglottic hemangioma. **Source:** PMID:30174006 
  - **supraglottic hemangioma**: A hemangioma, a benign tumor of the vascular endothelial cells, located in the upper part of the larynx (voice box) including the epiglottis; the area above the vocal cords. **Source:** PMID:16866116
- **visceral hemangioma**: A hemangiomas arising from within visceral structures, the internal organs of the body. **Source:** https://doi.org/10.1016/j.epsc.2014.06.004 
  - **intestinal hemangioma**: A hemangioma, a benign tumor of the vascular endothelial cells, located in the intestines, which includes the bowel. **Syn:** intestinal hemangioma
  - **spleen hemangioma**: A hemangioma, a benign tumor of the vascular endothelial cells, that is located in the spleen. **Syn:** Splenic hemangioma Source:** **PMID:11307096
- **labial hemangioma**: A hemangioma, a benign tumor of the vascular endothelial cells, that is located in the upper lip. **Source**: http://www.jpss.eu/index.php/current-issue/item/457-forty-four-cases-of-labial-hemangioma-therapeutic-management
- **esophageal hemangioma**:  A hemangioma, a benign tumor of the vascular endothelial cells, that is located in the esophagus. **Source: **PMID: 10626176
- **throat hemangioma**: A hemangioma, a benign tumor of the vascular endothelial cells, that is located in the glottic or supraglottic regions. **Source: ** PMID:28419860 **Syn:** Laryngeal Hemangioma
- **vulvar hemangioma**: A hemangioma, a benign tumor of the vascular endothelial cells, that is located in the vulva. **Source: ** PMID:29980161
- **retropharyngeal hemangioma**: A hemangioma, a benign tumor of the vascular endothelial cells, that is located in the retropharyngeal space, the portion of the peripharyngeal space that is located posterior to the pharynx.. **Source**: PMID:26011223, UBERON:0035619
- **spinal cord hemangioma**: A hemangioma, a benign tumor of the vascular endothelial cells, that is located in the spinal cord, that are generally benign and usually asymptomatic. **Source**: PMID:26030216
  - **Lumbosacral hemangioma**: A spinal cord hemangioma located in the lumbosacral spine region. **source**: PMID:25449217 **Syn**: Lumbar/sacral hemangioma
- **paraspinal hemangioma**: A hemangioma, a benign tumor of the vascular endothelial cells, that is located in the paraspinal muscular region, the muscles next to the spine. **Source:** http://ispub.com/IJOS/11/1/8101#

There are descriptions of **chest hemagiomas** and **intrathoracic hemangiomas**, I wonder if these are the same thing? I'll try to get more clarification.
Related article: https://www.jtcvs.org/article/S0022-5223(07)01237-8/abstract) 

Are these terms below too granular? Perhaps these could be annotated to something more general, like HP_0032060 'epitheliod hemangioma'? Or cutaneous (skin) hemangioma? (We would need a new term for that)
- **back hemangioma**: A hemangioma, a benign tumor of the vascular endothelial cells, located on the back.
- **arm hemangioma**
- **leg hemangioma**
- **Buttock hemangioma**

@pnrobinson I can go ahead and add these if they look okay to you.

**Comment by pnrobinson** [comment]
Hi Nicole!
these terms look great. One note is that we should probably use the more unambiguous medical terminology and use the plain label as a LP synonym. For instance, the primary label of throat hemangioma should be Laryngeal hemangioma.

As to the skin hemangioma terms, I think that the current Hemangioma term is possibly just that, and we should check the annotations, but we do need to disambiguate better. 
On the run today in Shanghai! More later

**Comment by nicolevasilevsky** [comment]
@drseb can you MIREOT UBERON:0035619 please?

**Comment by nicolevasilevsky** [comment]
I think everything on this ticket has been addressed. Closing.
