### ISSUE TITLE
Size stated in Definition correct?

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#4231]
definition of HP:0011426 (Fetal choroid plexus cysts):

currently: 

> Fetal choroid plexus cysts (CPCs) are sonographically discrete, small cysts (3 mm or more) found in the choroid plexus within the lateral cerebral ventricles of the developing fetus at 14 to 24 weeks gestation. Imaging of the choroid plexus is performed in the transverse plane of the fetal head at the same level that the lateral cerebral ventricle is evaluated. The choroid plexus should be inspected bilaterally for the presence of cysts. The size of CPCs is not of clinical relevance (pmid:16100637)

Question by translator:
The source string states that the cysts have a size of 3mm or more. Literature on that topic states the cysts are 0,3 mm or more, up to 2mm. That could mean that the source had a typing error or such ? Given that the sizes differ that much, I think its significant but it has no clinical relevance if the cyst is 1 or 2 mm.

@pnrobinson : I can't access the article referenced. Can you comment?

**Comment by pnrobinson** [comment]
I think that probably the 3mm is from older literature. Sources from the 1990s seems to be saying that it is difficult to visualize cysts less than 5mm. I am not able to find a newer article that says anything about the expected size of the cysts. Can you ask the translator to provide a PMID? Otherwise I will look next week.

**Comment by pnrobinson** [comment]
Here is a good review
http://www.jabfm.org/content/19/4/422.long
It seems that there may be some clinical importance whether the cysts are greater or less than 5mm in diameter. I have consulted various literature and there does not seem to be any size criterion, and so I think the best thing is to remove the reference to size and to add some more explanation to the comment. I will do so.
