### ISSUE TITLE
New definition suggesiton for HP:0025254 (Ameliorated by)

### ISSUE THREAD

**Issue by zafush** [obophenotype/human-phenotype-ontology#4234]
I would like to suggest new definition:
An ameliorating factor is defined as an external factor that leads to a sign or symptom that is already present improving or becoming more bearable

instead of:
An ameliorating factor is defined as an external factor that leads to the manifestation of a sign or symptom in a person improving or becoming more bearable

Background: A similar definition is better understood in this way when compared with the above definition: "An aggravating factor is defined as an external factor that leads to a sign or symptom that is already present getting worse or becoming more severe"

**Comment by pnrobinson** [comment]
Thanks -- this is a good suggestion.
