### ISSUE TITLE
AML should be alias for Acute Myeloid Leukemia not Acute Monocytic Leukemia

### ISSUE THREAD

**Issue by davmlaw** [obophenotype/human-phenotype-ontology#4236]
Evidence:

https://www.omim.org/entry/601626
https://www.google.com/search?q=AML

I recommend:

* Remove synonym "AML" from "Acute monocytic leukemia" (HP_0004845)
* Add synonym "AMoL" to "Acute monocytic leukemia" (HP_0004845)
* Add synonym "AML" to "Acute myeloid leukemia" (HP_0004808)

Thanks!

**Comment by pnrobinson** [comment]
Thanks for the suggestion, I agree and have made these changes.
