### ISSUE TITLE
Abnormal muscle phenotype

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#4237]
We need a high-level term for muscle (morphology/physiology) and we need to separate the relevant terms (see e.g., https://hpo.jax.org/app/browse/term/HP:0009127).

**Comment by LCCarmody** [comment]
There are already terms 'Abnormal muscle morphology' and 'Abnormal muscle physiology', but they are currently sibling classes to the 'Abnormal musculature of the ...'  Not sure how discreetly the phenotypes in the 'Abnormal musculature of the...' fit under either of those.

**Comment by pnrobinson** [comment]
@LCCarmody @drseb @nicolevasilevsky @cmungall @mellybelly 
-- I think that the muscle section of HPO needs some TLC. Right now, we mix morphology and physiology/ I think it is better not to have many grouping terms such as "Abnormality of some muscle X" with "Abnormal X morphology" and "Abnormal X physiology" underneath. Instead, I would put all of the muscle weakness terms under physiology. I thnk that the vast majority of the "Abnormality of some muscle X" mean morphology and we not used for direct annotations, and so I would tend to rename them "Abnormal X morphology" and clean up the hierarchy in this way. We will need to be careful and do this one by one.
Thoughts? If I hear nothing I will proceed.

**Comment by pnrobinson** [comment]
implemented.
