### ISSUE TITLE
NTR: Anomalous hepatic venous drainage

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#4241]
_For new term requests, please provide us with the following information:_
### 1. Preferred term label
Anomalous hepatic venous drainage

### 2. Synonyms
N/A

### 3. Textual definition
Anomalous hepatic venous drainage into the left atrium of the heart.
[PMID:16122505](https://www.ncbi.nlm.nih.gov/pubmed/16122505)

### 4. Parent term 
HP_0031941 'Abnormal portal venous system morphology'

@cmungall and @pnrobinson I'm not sure about this term, it is in a dataset of diseases for Kid's First, but would this be a phenotype?

**Comment by pnrobinson** [comment]
This is a phenotypic abnormality. If this is all you have, then the phrase will be used to describe the disease, but you will have some abnormal physiology as well. I will add the term.

**Comment by pnrobinson** [comment]
However, I will title "anomalous hepatic venous drainage into the left atrium" because there can be multiple types I think

**Comment by pnrobinson** [comment]
see HP_0032181
