### ISSUE TITLE
Add lay synonyms "upset stomach" and "indigestion"

### ISSUE THREAD

**Issue by kshefchek** [obophenotype/human-phenotype-ontology#4242]
Does this make sense as a lay synonym to HP:0002018?

**Comment by kshefchek** [comment]
Agreed that 'upset stomach seems more general than nausea, but more specific than abdominal symptom.  Perhaps abdominal pain (HP:0002027)?

**Comment by nicolevasilevsky** [comment]
It could also be added as a broad synonym to nausea. I feel like it would work as a broad synonym for nausea and abdominal pain but unfortunately, we can't add the same synonym to multiple classes. I think a broad syn for abdominal pain is the best fit. 

@pnrobinson - do you want to comment?

**Comment by kshefchek** [comment]
I think indigestion should also be present somewhere in the HPO as a term or synonym.

**Comment by nicolevasilevsky** [comment]
nausea already exists: HP_0002018

+1 for indigestion

**Comment by jmcmurry** [comment]
Ah! My ballot was already counted then. ;)

**Comment by pnrobinson** [comment]
Here is a definition from the net
upset stomach - a disorder of digestive function characterized by discomfort or heartburn or nausea. dyspepsia, indigestion, stomach upset. symptom - (medicine) any sensation or change in bodily function that is experienced by a patient and is associated with a particular disease.

So essentially, upset stomach is a disease, if you will, that is characteriszed by one or more terms underneath "abdominal symptom"

**Comment by pnrobinson** [comment]
I think indigestion is typically used to describe pain/discomfort/bloating in the abdominal region following eating. The medical term is dyspepsia, I think, and so indigestion is closer to being an atomic phenotype than upset stomach. Possibly we could make indigestion/dyspepsia a new term (child of abdominal pain), or make it a broad synonym of abdominal pain. Upset stomach should be a related synonym of abdominal symptom.

**Comment by nicolevasilevsky** [comment]
dyspepsia is already in MONDO: MONDO_0002268

**Comment by kshefchek** [comment]
+1, thanks @pnrobinson and @nicolevasilevsky!

**Comment by nicolevasilevsky** [comment]
I think we should add indigestion/dyspepsia as a new term (child of abdominal pain) - I will go ahead and do this now

**Comment by nicolevasilevsky** [comment]
and I'll add upset stomach as a related synonym of abdominal symptom
