### ISSUE TITLE
Add lay synonym 'loss of appetite' to HP:0004396 (Poor appetite)

### ISSUE THREAD

**Issue by kshefchek** [obophenotype/human-phenotype-ontology#4243]
See also: https://github.com/obophenotype/human-phenotype-ontology/issues/1044

**Comment by nicolevasilevsky** [comment]
I agree loss of appetite should be a syn for poor appetite (and not anorexia, anorexia is a disorder and I don't think it is a loss of appetite but more so not wanting to eat for fear of gaining weight.)

**Comment by nicolevasilevsky** [comment]
Thinking about it more, it seems like it would be confusing to add loss of appetite as a syn for anorexia, as anorexia is a medical condition, and you could just have loss of appetite for other reasons, right?

**Comment by pnrobinson** [comment]
I agree that loss of appetite is not the same as anorexia, and lay people will understand the word anorexia. I am not so sure it is a good synoynm for poor appetite (which we are using as a more or less permanent condition). Loss of appetite to me sounds like something that lasts for a day and then gets better. I would propose not adding it.

**Comment by kshefchek** [comment]
I think loss of appetite is a valid phenotype (or constitutional symptom), it is certainly a symptom of some common diseases and cancers, and a common side effect of many medications.
