### ISSUE TITLE
Synonym correct for "Decreased methionine synthase activity" ?

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#4248]
There is a difference between Synthase and Synthetase. Both is listed Synonym.

Refers to HP:0003524

**Comment by pnrobinson** [comment]
I cannot find a methionine synthetase, and "synthase" appears correct for MTR (https://www.genecards.org/cgi-bin/carddisp.pl?gene=MTR), and we should list the full name as a synonym.

Synthetase occurs in this name

https://en.wikipedia.org/wiki/S-adenosylmethionine_synthetase_enzyme

**Comment by pnrobinson** [comment]
corrected the synonym to read ...synthase...
