### ISSUE TITLE
Decreased specific antibody response to injection

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#4264]
This is a request from this issue
https://github.com/obophenotype/human-phenotype-ontology/issues/4200
we need to get a definition and more context to make this term.

**Comment by pnrobinson** [comment]
This was a typo and should have been
```
Decreased specific antibody response to infection 
```

**Comment by nicolevasilevsky** [comment]
I added this HP_0410308 'Decreased specific antibody response to infection'
