### ISSUE TITLE
Merge or group: Central retinal artery occlusion + Retinal arterial occlusion

### ISSUE THREAD

**Issue by cmungall** [obophenotype/human-phenotype-ontology#4266]
* HP:0025342 ! Central retinal artery occlusion [DEF: "Blockage of blood flow in the central retinal artery."]
 * HP:0025326 ! Retinal arterial occlusion [DEF: "Blockage of the retinal artery, generally associated with interruption of blood flow and oxygen delivery to the retina."]

At present the MRCA of these classes is the very general 'Abnormality of head blood vessel':

![image](https://user-images.githubusercontent.com/50745/48984045-7488db00-f0ab-11e8-8e36-f58d2024d691.png)

These should be brought closer. The main artery supplying the eye is the central retina, so there is an argument that HP:0025326 really intends to mean CRAO (the def says "THE retinal artery")

I suggest based on https://www.asrs.org/patients/retinal-diseases/32/retinal-artery-occlusion

 * RAO
    * CRAO
    * BRAO (new term)

Other potential RA/CRA confusions:

```
     is_a HP:0000630 ! Abnormal retinal artery morphology 
        is_a HP:0000631 ! Retinal arterial tortuosity
           is_a HP:0007768 ! Central retinal vessel vascular tortuosity
        is_a HP:0001136 ! Retinal arteriolar tortuosity
        is_a HP:0007985 ! Retinal arteriolar occlusion
        is_a HP:0008014 ! Central fundal arteriolar microaneurysms
        is_a HP:0008030 ! Retinal arteritis
        is_a HP:0008043 ! Retinal arteriolar constriction
        is_a HP:0010729 ! Cherry red spot of the macula
        is_a HP:0025326 ! Retinal arterial occlusion
        is_a HP:0025355 ! Retinal arterial macroaneurysms
```

**Comment by cmungall** [comment]
See also NCIT:

```
       is_a NCIT:C35317 ! Arterial Disorder
        is_a NCIT:C35318 ! Arterial Occlusion
         is_a NCIT:C34978 ! Retinal Artery Occlusion *** 
          is_a NCIT:C34436 ! Retinal Arterial Branch Occlusion
          is_a NCIT:C34456 ! Central Retinal Artery Occlusion
          is_a NCIT:C35192 ! Partial Retinal Arterial Occlusion
          is_a NCIT:C35193 ! Transient Retinal Arterial Occlusion
```

**Comment by pnrobinson** [comment]
THe distinction to be made is between CENTRAL and BRANCH, see this: https://www.merckmanuals.com/professional/eye-disorders/retinal-disorders/central-retinal-artery-occlusion-and-branch-retinal-artery-occlusion
@psergouniotis can you take a look at this?

**Comment by pnrobinson** [comment]
@psergouniotis can you please suggest if we should have a term for central and branch?

**Comment by psergouniotis** [comment]
sorry I have not seen replied to this before. 
I think there should be terms for:
* branch retinal artery occlusion (BRAO) 
* central retinal artery occlusion (CRAO)
* cilioretinal artery occlusion
* ophthalmic artery occlusion (presenting with a similar picture to CRAO; however, profound choroidal ischaemia also occurs)
* branch retinal vein occlusion (BRVO) (equating to occlusion anterior to the cribriform plate)
* central retinal vein occlusion (CRVO) (equating to occlusion posterior to the cribriform plate)
* hemiretinal vein occlusion (HRVO) (which has a similar appearance to BRVO, but the entire superior or inferior hemisphere is involved)

please let me know if you would like any additional information or definitions

**Comment by pnrobinson** [comment]
@psergouniotis  -- I was able to find good definitions for all of these terms and have added them, thanks! They will appear with the next HPO release.
