### ISSUE TITLE
Remove ASD abbreviation from atrial septal defect?

### ISSUE THREAD

**Issue by jxchong** [obophenotype/human-phenotype-ontology#4270]
I wonder if ASD should be removed as a synonym for atrial septal defect. 

From what we're seeing in our userbase (MyGene2), most people entering "ASD" mean "autism spectrum disorder" instead of atrial septal defect, although I'm also familiar with the latter usage in the heart disease community. I would suggest that if an abbreviation like that has multiple equally probable uses, neither term should have the abbreviation assigned as an official synonym because tools that attempt to automatically extract HPO terms from free text cannot differentiate between the two uses.

**Comment by pnrobinson** [comment]
Currently, ASD is only associated with Atrial septal defect. I do not think that OWL will let us use the same acronym for two different terms. @cmungall is there some way around this?
One thing that might be helpful in the future is that we have been adding a "hasSynonymType abbreviation" tag to synoynms like this, and so software could show some special warning to users that they need to look before doing an autocomplete.

**Comment by drseb** [comment]
OWL is not the problem. It is the qc pipeline that prevents this. I could modify the qc to exclude abbreviations. Not sure what the best solution is.

**Comment by LCCarmody** [comment]
There are a  lot of abbreviations that overlap in a similar way. I have been routinely not adding them because of the qc module--unless it is something like "MRI" or "EKG"/"ECG" where it is fairly universally known.

**Comment by cmungall** [comment]
That doesn't sound too good! We should not be blocking ourselves from adding useful synonyms!

ROBOT v1.2 introduces the report command, we should migrate as much of our QC to this and only write code for things that are truly HPO specific

http://robot.obolibrary.org/report_queries/

It's highly customizable but the defaults are good for any OBO Library ontology

These are the checks that are run, plus their default severity:
http://robot.obolibrary.org/report_queries/

By default exact synonym dupes are caught and exact labels, but broad/narrow/related synonyms can be shared:
http://robot.obolibrary.org/report_queries/duplicate_exact_synonym

**Comment by drseb** [comment]
I don't see how moving our QC to robot will help. We will only loose control over the QC and robot has, as far as I can tell, just copied a lot of HPO's QC. The current plan is to move the release pipeline to robot-based releases anyway, but I will keep running our QC-scripts in parallel for now. 

@pnrobinson shall we allow duplicate synonyms for different classes?

**Comment by mellybelly** [comment]
In my humble opinion, it would be good to have all the ontologies using the same management pipeline/QC processes, and conversely, everyone benefits when one creates additions or enhancements to shared QC or other processes. For example, the synonym best practices implemented in ROBOT have been in place for OBO for quite a long time, and are checked across all of the OBO collection. HPO being on a different pipeline means different processes in different places. The more we work on multiple/additional ontologies, the harder it will be to keep doing things differently for one. There is funding to help all OBO ontologies work more consistently together, and ROBOT is part of this funding.

As someone who originally helped define the synonym rule, I would say yes, you should/could allow the same synonyms so long as they are not exact. Of course other communities do things differently, and may use a "see also" or somesuch, but doing it this way would be consistent with the rest of OBO.

**Comment by drseb** [comment]
As I said, we are going to use robot as well, as soon nico and I have moved everything required for that into the HPO-repo. But I will not make myself dependent on just robot, if I can prevent this. I don't see any problems.

**Comment by mellybelly** [comment]
sounds great!

**Comment by pnrobinson** [comment]
In general, the HPO Q/C pipeline has done everything we need it to. I would say that if we need to improve something, then we need to improve the pipeline for the annotations the most.
In this case, it is not that two terms share the same synonym, it is an acronym that stands for two different things (A.S.D.). The acronym is not RELATED, it is in fact EXACT for both terms. At present, we have been trying to label abbreviations/acronym synonyms as such. Perhaps it would be a better idea to have a new relation called has_acronym for which it would be allowable to have duplicates. But AFAIK this is the only instance that has caused problems. I would say that in general, if two terms have the same synonym, this is a sign that there is a modeling problem.

**Comment by drseb** [comment]
I think this makes sense, but you see exactly what I mean: this will cause problems with robot for us. In this case it will only print a _warning_, but imagine we want to avoid warnings: will we have a way to "HPersonalise" robot and change this test? (From my experience: I really want to avoid such dependencies)

**Comment by mellybelly** [comment]
New annotation properties should go in a central place, unless human phenotype specific, e.g. they should be added to RO or IAO, please make a ticket. Regardless, this is a case where HPO was not following the same QC rules as other OBO ontologies, but not for any intentional reason that I can see. 

There should be a way to customize ROBOT for HPO specific needs - we should not throw the baby out with the bathwater! Please make tickets, this is good for everyone to help our collective tools get better and work better for all OBO ontologies.

**Comment by pnrobinson** [comment]
@drseb should we go ahead and create a has_acronym relation? One problem is that other tools will also need to know where to look.

**Comment by drseb** [comment]
we have several synonym-types:

<img width="203" alt="screenshot 2019-01-28 at 09 57 30" src="https://user-images.githubusercontent.com/5172897/51824660-2a0e1f80-22e3-11e9-8104-fe9e0d56feae.png">

we also have abbreviation. You are however speaking about acronym. I am not sure if we have mixed up "abbreviation" and "acronym" so far. Doesn't matter as it seems we haven't used it so far (which is sad - we should train curators)
Should I add "acrnoym" as SynonymTypeProperty?

**Comment by pnrobinson** [comment]
I am using abbreviation to mean that or acronym actually, but this is only for new terms. I think the issue is that we still cannot use ASD for two different terms without causing an error.

**Comment by drseb** [comment]
I think it should now be possible to have shared acronyms between different HPO classes. So please go ahead and solve the initial ASD-issue.

**Comment by pnrobinson** [comment]
@drseb should we use has_exact_synonym for this?

**Comment by pnrobinson** [comment]
@drseb I am not sure if there is an open action item here, can we close or what should we do?

**Comment by drseb** [comment]
Please try to have asd as synonym for the two classes. Both should be annotated as abbreviationsa and the qc-pipeline should allow this. 

Sent from mobile

**Comment by pnrobinson** [comment]
done!
