### ISSUE TITLE
Process for converting from Abnormal ion homeostasis to Abnormal ion level

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#4271]
Currently, terms such as Abnormal magnesium concentration are defined with the GO terms for magnesium homeostasis. We have decided to convert these to the actual observations (concentrations) for terms that just measure the level. What is the SOP for converting from GO to ChEBI based definitions here? This is the way the definitions currently look
```
'has part' some 
    (amount
     and ('inheres in' some 'manganese ion homeostasis')
     and ('has modifier' some abnormal))
```
@matentzn @drseb @cmungall

**Comment by matentzn** [comment]
We have not yet reached consensus on the chemical concentration problem yet; my lay-mans sense would be that you simply swap the homeostasis term for the chebi term; the pato class 'amount' seems to fit the chebi scenario more than the homeostasis scenario in any case (for processes we tend to prefer '[increased rate](https://github.com/obophenotype/upheno/blob/master/src/patterns/increasedMolecularFunction.yaml)' or something similar, or [not even specify the quality](https://github.com/obophenotype/upheno/blob/master/src/patterns/abnormalMolecularFunction.yaml)). For your case, the correct solutions as they currently stand are [abnormalLevelOfChemical](https://github.com/obophenotype/upheno/blob/master/src/patterns/abnormalLevelOfChemical.yaml) or [abnormalLevelOfMolecularEntity](https://github.com/obophenotype/upheno/blob/master/src/patterns/abnormalLevelOfMolecularEntity.yaml).

**Comment by pnrobinson** [comment]
This is duplicate with #4268
