### ISSUE TITLE
HP:0000655 is obsolete AND has "is_a" attribute

### ISSUE THREAD

**Issue by rolfschr** [obophenotype/human-phenotype-ontology#4272]
Hi,

I found that in the Oct 2018 release the term `HP:0000655` is marked as obsolete. It has furthermore the `is_a` relationship `is_a: HP:0007773 ! Vitreoretinopathy`. This is the only obsolete term I could see that has additionally the `is_a` relationship. 

Our hp.obo parser stumbled over this since we had the assumption that a term is either obsolete OR has an ancestor.

I am not saying `HP:0000655` is wrongly curated. I would simply like to point this out in case this was not intended.

**Comment by drseb** [comment]
Thanks. This has already been fixed and will be visible in the next release due next week.
