### ISSUE TITLE
22 annotations (comments) with trailing whitespace

### ISSUE THREAD

**Issue by matentzn** [obophenotype/human-phenotype-ontology#4274]
In our slow move to a more extensive QC, the following 22 annotations (all rdfs:comment) have trailing or leading whitespace (a space, tab or similar before or after the textual value of the annotation). In order to pass the initial tests, it would be good if someone could fix those quickly. Perhaps consider reviewing punctuation for those (some comments seem to be missing a period in the end). 
 

- [x] http://purl.obolibrary.org/obo/HP_0030125,http://www.w3.org/2000/01/rdf-schema#comment,This anomaly is observed at about 3.5 percent of people and is usually bilateral. 
- [x]  http://purl.obolibrary.org/obo/HP_0030244,http://www.w3.org/2000/01/rdf-schema#comment,"There is evidence to suugest that maternal fever during pregnancy may negatively affect offspring healthneural tube defects, congenital heart defects, and oral clefts, in which meta-analyses suggested between a 1.5- and nearly 3-fold increased risk with fever exposure in the first trimester. "
- [x]  http://purl.obolibrary.org/obo/HP_0030022,http://www.w3.org/2000/01/rdf-schema#comment,"Relatively few cases have been reported. Variation from a small notch to complete separation of the helix from the lobe is noted, there may be unilateral or bilateral involvement. The lobe is relatively laterally recessed compared to the upper portion of the ear and the scapha may be absent. This is distinct from a Cleft helix where the cleft is within the helix. "
- [x]  http://purl.obolibrary.org/obo/HP_0030038,http://www.w3.org/2000/01/rdf-schema#comment,Most patients have no symptoms. Enchondromas are often identified as incidental findings on X-ray examinations. Enchondromas usually have a radiographic appearance that is long and oval with well-defined margins. 
- [x] http://purl.obolibrary.org/obo/HP_0030023,http://www.w3.org/2000/01/rdf-schema#comment,This feature is best visualized when the lobe is tilted anteriorly. 
- [x]  http://purl.obolibrary.org/obo/HP_0030439,http://www.w3.org/2000/01/rdf-schema#comment,"Differentiating true anal canal adenocarcinoma from low rectal adenocarcinoma can be challenging. Most anal canal adenocarcinomas originate from anal glands, but cases developing in chronic tracts from fistula in ano are described. Multiple factors, including infection with HPV and HIV, history of receptive anal intercourse, smoking, and immunosuppression have been identified as risk factors. Clinical features include anal pain, induration of the anal canal, or abscess formation and a palpable lump. "
- [x] http://purl.obolibrary.org/obo/HP_0030024,http://www.w3.org/2000/01/rdf-schema#comment,"Pretragal ectopia refers to structures that are frequently complex and should be distinguished from preauricular tags. They may be difficult to distinguish from striated muscle hamartomas or tragal duplications. Pretragal ectopias often appear helix-like, and in such cases may be called Polyotia. "
- [x]  http://purl.obolibrary.org/obo/HP_0008330,http://www.w3.org/2000/01/rdf-schema#comment,"Von Willebrand factor (VWF) is a key hemostatic protein, but documenting its function through laboratory tests is not always straightforward. VWF serves as a carrier protein for factor VIII (FVIII), and also facilitates platelet adhesion through its interaction with platelet GPIb on the platelet surface and through its binding to the subendothelial matrix. This interaction is driven in vivo by shear stress, which induces a conformational change in VWF that allows it to bind platelet GPIb. In vitro, however, this interaction is induced by the antibiotic ristocetin, which enables VWF and platelet GPIb to interact in the absence of shear forces. Laboratory testing of VWF utilizes ristocetin in the VWF ristocetin cofactor activity assay (VWF:RCo), which is a measure of VWF binding to platelets, or by ristocetin-induced platelet aggregation (RIPA). "
- [x]  http://purl.obolibrary.org/obo/HP_0002816,http://www.w3.org/2000/01/rdf-schema#comment,"Individuals with genu recurvatum may experience knee pain, display an extension gait pattern, and have poor proprioceptive control of terminal knee extension. "
- [x]  http://purl.obolibrary.org/obo/HP_0000533,http://www.w3.org/2000/01/rdf-schema#comment,"Choroidal sclerosis is a descriptive term applied to the ophthalmoscopic appearance of prominent white choroidal vessels in which the blood columns are not seen or are sheathed by white lines. Choroidal sclerosis is a term used to describe a group of genetically heterogeneous retinal dystrophies that share a common funduscopic phenotype of scalloped, well-circumscribed, and confluent chorioretinal atrophic lesions that extend beyond the macula. The term choroidal sclerosis was initially coined because of the sclerotic appearance of choroidal vessels which frequently appear white or light-yellow. However, histologic studies have demonstrated the term to be a misnomer as the principle abnormality is the loss of choriocapillaris, retinal pigment epithelium (RPE), and the outer retina in the absence of abnormal sclerotic changes in the choroidal vasculature. Therefore, we are making choroidal sclerosis a synonym of chorioretinal atrophy. "
- [x]  http://purl.obolibrary.org/obo/HP_0100841,http://www.w3.org/2000/01/rdf-schema#comment,"Patients with microgastria usually have poor growth, inadequate food consumption, or a complication of the small gastric cavity and gastroesophageal reflux, including frequent vomiting or pneumonia. "
- [x] http://purl.obolibrary.org/obo/HP_0030154,http://www.w3.org/2000/01/rdf-schema#comment,"Clinical presentation of a ruptuerd gallbladder can range from an acute generalised peritonitis to benign non-specific abdominal symptom. Gallbladder perforation is a rare but life-threatening complication of acute cholecystitis, with a reported mortality rate of 12 to 42 percent. The bile leak from a ruptured gallbladder might be contained in the extra peritoneal gallbladder fossa, and hence might not produce symptoms of peritonitis immediately. "
- [x]  http://purl.obolibrary.org/obo/HP_0030438,http://www.w3.org/2000/01/rdf-schema#comment,"Patients typically present with bright red bleeding, pain, and/or a palpable mass. When a clinically suspicious lesion is identified, diagnosis relies on cytologic or histologic confirmation. "
- [x] http://purl.obolibrary.org/obo/HP_0030361,http://www.w3.org/2000/01/rdf-schema#comment,"The icosanoids include the prostaglandins, prostacyclins, thromboxanes, leukotrienes, and epoxyeicosatrienoic acids. Icosanoids have various roles in processes that regulate inflammation, fever, blood pressure, blood clotting, immune system function, reproductive processes and tissue growth, and the sleep/wake cycle. "
- [x]  http://purl.obolibrary.org/obo/HP_0006527,http://www.w3.org/2000/01/rdf-schema#comment,"Associated clinical manifestations often include fever, cough, and shortness of breath. "
- [x]  http://purl.obolibrary.org/obo/HP_0030031,http://www.w3.org/2000/01/rdf-schema#comment,"This is an acknowledged bundled term. There are no standards for this finding, clinical judgment must be used. The affected toes should be numbered. "
- [x]  http://purl.obolibrary.org/obo/HP_0030033,http://www.w3.org/2000/01/rdf-schema#comment,"This is a bundled term, comprising Short finger and Slender digit, but it is so widely used that it is included. This term is only used if the finger has the normal number of phalangeal segments. An appropriate alternative term for the first digit is Small thumb, when it is the only digit affected. When a thumb and one or more fingers are affected, it may be more economical to specify Small fingers, F1-5 instead of separately specifying Small thumb and Small fingers F2-5. "
- [x]  http://purl.obolibrary.org/obo/HP_0030133,http://www.w3.org/2000/01/rdf-schema#comment,The type Vicenza variant of von Willebrand disease (VWD) is characterized by a low plasma von Willebrand factor (VWF) level and supranormal VWF multimers. 
- [x] http://purl.obolibrary.org/obo/HP_0030009,http://www.w3.org/2000/01/rdf-schema#comment,One of the known risk factors for preterm birth is cervical insufficiency. 
- [x] http://purl.obolibrary.org/obo/HP_0030066,http://www.w3.org/2000/01/rdf-schema#comment,"Ependymoblastoma is a rare tumor that occurs in infants and young children in the first two years of life. Both sexes are affected equally. Patients present with signs and symptoms of raised intracranial pressure and hydrocephalus. Focal neurological signs may be present in older children. On MRI, ependymoblastomas are large heterogeneously enhancing lesion with associated brain edema and mass effect. Ependymoblastomas are well-circumscribed lesions, with a distinct margin between tumor and normal brain, though focal microscopic extension and leptomeningeal invasion are common. Histologically, an ependymoblastoma is a primitive neuroectodermal tumor with tumor cell arranged in multilayered rosettes consisting of an outer rim of tumor cells merging with the surrounding undifferentiated neuroectodermal cells. The tumor cells are immunopositive for S100, vimentin, cytokeratin and GFAP, and show high mitotic activity. "
- [x] http://purl.obolibrary.org/obo/HP_0030176,http://www.w3.org/2000/01/rdf-schema#comment," This feature may be observed in hereditary neuropathy with liability to pressure palsies, but also in acquired inflammatory neuropathies."
- [x]  http://purl.obolibrary.org/obo/HP_0030248,http://www.w3.org/2000/01/rdf-schema#comment,"Mesenteric venous thrombosis may be associated with abdominal pain and bloating, diarrhea, fever, gastrointestinal bleeding, and vomiting "

There is also this weird one here (a blank node with an ISBN with whitespace):

```
- _:b0,http://www.geneontology.org/formats/oboInOwl#hasDbXref, ISBN:0-7216-0179-0
```
If someone wants to get to the bottom of it.

**Comment by drseb** [comment]
We don’t do qc on the comments. But we can fix next week.

**Comment by matentzn** [comment]
Yeah, it is one of the standard tests of the ODK release pipeline, that is why we noticed it. It is not important, I will omit the test, for now, to continue working on the move. Do you want to do this test in general? Or shall I get rid of it for good? I personally favour keeping it, but I understand if this puts too much of a load on curators.

**Comment by pnrobinson** [comment]
The `` ISBN:0-7216-0179-0`` issue was an *initial* whitespace (fixed)

**Comment by pnrobinson** [comment]
fixed the WS errors and added a missing period etc.
