### ISSUE TITLE
Remove extra.owl from HP imports

### ISSUE THREAD

**Issue by matentzn** [obophenotype/human-phenotype-ontology#4275]
hp-edit imports `http://purl.obolibrary.org/obo/upheno/imports/extra.owl`

This file contains six axioms, all of which belong into Upheno, none of which into HP IMHO:

- `EquivalentClasses(obo:HP_0000118 obo:UPHENO_0001002)` <-makes HP:phenotypic abnormality equivalent to UPHENO:Abnormal phenotype. 
- `SubClassOf(obo:MPATH_576 'trichofolliculoma' obo:MPATH_575 'basaloid follicular neoplasms
')` <- This either should to go into MPATH, or just go away. 
- `EquivalentClasses(obo:PATO_0000069 'deviation from normal' ObjectIntersectionOf(obo:PATO_0000068 'qualitative' ObjectSomeValuesFrom(obo:RO_0002573 'has modifier' obo:PATO_0000460 'abnormal')))` <- this just does not belong here at all. This is an important assumption made about PATO: either it should be in PATO, or nowhere. 
- `EquivalentClasses(obo:UPHENO_0001001 ObjectSomeValuesFrom(obo:UPHENO_0000001 owl:Thing))` <- ineffectual upheno axiom that has no effect on HP.
- `EquivalentClasses(obo:UPHENO_0001002 ObjectIntersectionOf(obo:UPHENO_0001001 ObjectSomeValuesFrom(obo:BFO_0000051 ObjectSomeValuesFrom(obo:RO_0002573 obo:PATO_0000460))))` <- relevant only to upheno. 
- `SubClassOf(obo:UPHENO_0001002 obo:UPHENO_0001001)` <- relevant only to upheno

@cmungall @pnrobinson @drseb

**Comment by cmungall** [comment]
I can do some archaology on these later, the MPATH thing just seems like a mistake

**Comment by matentzn** [comment]
No effect on class hierarchy, ditched through:
https://github.com/obophenotype/human-phenotype-ontology/commit/859c0ec84d05d4e88918e2aa5eb3606ff0f4d42f
