### ISSUE TITLE
Require clarification for the role of ro_extra.owl in HP. Is it necessary for HP?

### ISSUE THREAD

**Issue by matentzn** [obophenotype/human-phenotype-ontology#4277]
ro_extra contains the following 11 axioms:

- SubObjectPropertyOf(obo:RO_0000052 obo:RO_0002502)
- SubObjectPropertyOf(obo:RO_0000052 obo:UPHENO_0000001)
- SubObjectPropertyOf(obo:RO_0002314 obo:RO_0002502)
- SubObjectPropertyOf(obo:RO_0002314 obo:UPHENO_0000001)
- SubObjectPropertyOf(obo:RO_0002425 obo:RO_0002424)
- SubObjectPropertyOf(obo:RO_0002426 obo:RO_0002424)
- SubObjectPropertyOf(obo:RO_0002502 obo:UPHENO_0000001)
- SubClassOf(obo:UBERON_0000465 obo:CARO_0000006)
- SubObjectPropertyOf(ObjectPropertyChain(obo:BFO_0000051 obo:RO_0002502) obo:UPHENO_0000001)
- SubObjectPropertyOf(ObjectPropertyChain(obo:RO_0000052 obo:BFO_0000050) obo:RO_0002314)
- SubObjectPropertyOf(ObjectPropertyChain(obo:UPHENO_0000001 obo:BFO_0000050) obo:UPHENO_0000001)

@cmungall are they necessary for HP to function (I can see how Upheno needs it)? Or do we need to run classification diff experiments to make sure? 

I tend to like to drop this import and replace by a regular ro.owl dependency.

**Comment by drseb** [comment]
I think it can be removed and we will see if any axioms were required for correct classification of hp. But as our product contains only assertions, it is save for now. It would still be good to know why we did put it into HP in the first place

**Comment by cmungall** [comment]
can we do a reasoner-diff?

**Comment by matentzn** [comment]
extra.owl has no effect on class hierarchy save that it imports ro_import.owl. I replaced ro_extra.owl with ro_import.owl to prepare HP for the ODK move.

**Comment by pnrobinson** [comment]
@matentzn can we close this issue?

**Comment by matentzn** [comment]
@pnrobinson Review [this](https://github.com/obophenotype/human-phenotype-ontology/pull/4288) and we can close.

**Comment by pnrobinson** [comment]
Closing, thanks!
