### ISSUE TITLE
New QC: DOID import causes cyclic dependency with HP

### ISSUE THREAD

**Issue by matentzn** [obophenotype/human-phenotype-ontology#4282]
DOID imports HP, HP imports DOID, this causes version clashes. The solution is to solve https://github.com/obophenotype/human-phenotype-ontology/issues/4281 and the remove the import from hp-edit.owl

**Comment by matentzn** [comment]
I just checked, the DOID import has no effect on HP save a few labels, which will soon be gone. If you want, I can strip the import right now! For your amusement, breakdown of a few other imports and there effect on inferred subsumption (how many **non-asserted** subsumptions between phenotypes are contributed to HP through imported ontologies?):

DOID 0
GO   51
RO  219
UBERON  446
all imports 1525

**Comment by mellybelly** [comment]
Why does HP import DO? that seems very odd to me. Seems like a good idea to remove.

**Comment by matentzn** [comment]
The reason was that there were some ancient DOID dependencies:
https://github.com/obophenotype/human-phenotype-ontology/issues/4281

**Comment by drseb** [comment]
Don't remove for now. See: https://github.com/obophenotype/human-phenotype-ontology/issues/4281#issuecomment-453587431

**Comment by drseb** [comment]
I would suggest to discuss the situation with MP folks on one of the next phenotype-editors call

**Comment by pnrobinson** [comment]
@matentzn I think we can remove the DO import now, see
https://github.com/obophenotype/human-phenotype-ontology/issues/4281#issuecomment-453587431
can we close here?

**Comment by matentzn** [comment]
yes, i will take care of the import! :)
