### ISSUE TITLE
Neutral hyperaminoaciduria needs a definition

### ISSUE THREAD

**Issue by jmcmurry** [obophenotype/human-phenotype-ontology#4283]
https://hpo.jax.org/app/browse/term/HP:0008353

I for one am confused by the combination of neutral and hyper

**Comment by pnrobinson** [comment]
Please add definition:
"The presence of an abnormally increased concentration of neutral amino acids in the urine. The neutral amino acids are tryptophan, alanine, asparagine, glutamine, histidine, isoleucine, leucine, phenylalanine, serine, threonine, tyrosine and valine."
citation: PMID:30177408
