### ISSUE TITLE
Rickets (HP:0002748) needs a definition

### ISSUE THREAD

**Issue by jmcmurry** [obophenotype/human-phenotype-ontology#4284]
Rickets is a softening and weakening of bones in children, usually due to inadequate vitamin D.
Source: https://www.mayoclinic.org/diseases-conditions/rickets/symptoms-causes/syc-20351943

https://hpo.jax.org/app/browse/term/HP:0002748

**Comment by pnrobinson** [comment]
I have updated the definitions. It will be hard to remove this term right now since this is a manifestation of several other diseases. Please derive definitions from PubMed listed articles only!
