### ISSUE TITLE
Family history of cancer

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#4286]
Just to provide a little more context surrounding the request. I was performing the gene curation for TP53 in Li-Fraumeni Syndrome. As I am sure you are well aware, part of the diagnostic criteria for Classic Li-Fraumeni (Classic LFS), Li-Fraumeni like syndrome  (LFL), and the Chompret criteria require a “family history of cancer” for diagnosis of this disease entity. Our current gene curation guidelines for inclusion and scoring of segregation and estimation of a LOD score requires a specific number of genotype+/ phenotype+ individuals in a pedigree. Given that there are thousands of papers on TP53, and we are not setting out to curate every single individual, I was unfortunately unable to find a proband that met the criteria for the inclusion of scoring, mostly because the pedigrees only genotyped the proband and potentially one other family member (we need 4 genotype+/phenotype+ for this inheritance pattern). 

Sharon Plon, ClinGen co-PI and Chair of the Hereditary Cancer Working Group, requested for me to see if there was a current HPO term for family history of cancer. I let her know there was not, but that I was willing to speak to you.

After speaking with Jonathan Berg, we began to see that given how ontologies work it could be that you would have to set up a new node (parent node) of “Family History” in which case it would most likely need to be populated with every type of disease that is known to have familial inheritance. Otherwise, there is a possibility to add the node as an orphan term under “cancer”, or even the specific type of cancer, (which would not be helpful with LFS given that the family history could be multiple different types). However, how would this distinguish between a person “having cancer” AND having a family history of the same OR different cancer?
[from Courtney Thaxton, Ph.D.]

**Comment by courtneythaxton** [comment]
Thank @pnrobinson for generating this ticket!

Adding on @ahamosh and @orphanet to get some input from them.

best,
@courtneythaxton

**Comment by pnrobinson** [comment]
@drseb @cmungall @mellybelly 
We have gotten many similar requests. I think we should add a small new subontology called
Family history
We could have terms such as 
FH of cancer
FH of heart disease etc 
(a limited number of top level terms intended to be used if we do not have enough information to make a decent PED file)
Also, we could have something like
Health status
def: health status of a family member with respect to the disease being investigated in a proband
--Unaffected
--Affected
--Healthy (def: No history of any serious disease, including the disease being investigated in the proband)

This subontology would not interfere with anything or or with computation, and it would be convenient for at least several groups who are using HP.

If nobody objects, I would add this after a few days.

**Comment by drseb** [comment]
sounds ok

**Comment by pnrobinson** [comment]
see https://github.com/obophenotype/human-phenotype-ontology/issues/3688

**Comment by shaytzur** [comment]
thank you, that will be a very useful term.

**Comment by pnrobinson** [comment]
done, this will be released with the next HPO release
