### ISSUE TITLE
Abnormal T cell subtype distribution

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#4289]
Related #2396 #2436 #2445 #2461

Let's start with a list of the t cell subtypes and start to add the markers as synonyms.

**Comment by pnrobinson** [comment]
Please if you choose a cell to work on, add it here:

- [ ] Memory T cell [Peter]
- [ ] xyz
- [ ] xyz
- [ ] xyz
- [ ] xyz
- [ ] xyz
- [ ] xyz
- [ ] xyz

**Comment by LCCarmody** [comment]
Are we doing all these cells?  And abnormal count and activation?  It is hard to tell jumping from ticket to ticket.  In any event, it was decided to use CL for the hierarchy.  We would need to MIREOT the following if we plan to do all those listed. * gamma-delta T cell
* CD4-positive, alpha-beta memory T cell
* immature gamma-delta T cell
* intraepithelial lymphocyte
* central memory CD4-positive, alpha-beta T cell
* effector memory CD4-positive, alpha-beta T cell
* CD8-positive, alpha-beta memory T cell
* 
central memory CD8-positive, alpha-beta T cell
effector memory CD8-positive, alpha-beta T cell

**Comment by drseb** [comment]
can you give me the purls or ids of the classes to mireot?

**Comment by LCCarmody** [comment]
@drseb Updated above and listed below.  Wasn't sure which was better.

http://purl.obolibrary.org/obo/CL_0000798 
http://purl.obolibrary.org/obo/CL_0000897
http://purl.obolibrary.org/obo/CL_0000799
http://purl.obolibrary.org/obo/CL_0002496 
http://purl.obolibrary.org/obo/CL_0000904
http://purl.obolibrary.org/obo/CL_0000905
http://purl.obolibrary.org/obo/CL_0000909
http://purl.obolibrary.org/obo/CL_0000907 
 http://purl.obolibrary.org/obo/CL_0000913

**Comment by drseb** [comment]
currently having problems regenerating cl_import due to internet connection problems. please remind me if forget to re-run this later

**Comment by drseb** [comment]
sorry. regenerating cl_import currently does not change the cl-import. need help from @matentzn

**Comment by nicolevasilevsky** [comment]
Do we want to add logical definitions for terms that are 'abnormal proportion fo [cell type]? I don't think we have a pattern for that, and I am not sure how to write the logical def.

**Comment by pnrobinson** [comment]
Note that the pattern should include the numerator and denominator, and we will likely have to adjust some according to feedback. i.e., the proportion with respect to X cell type can be different.

**Comment by nicolevasilevsky** [comment]
I added new terms:
**Abnormal/increased/decreased** proportion of **CD4** and **CD8**-positive, alpha-beta memory T cells
and
**Abnormal/increased/decreased** proportion of **CD4** and **CD8**-positive, alpha-beta **effector** and **central** memory T cells

as children of HP_0032182 'Abnormal proportion of memory T cells'

**Comment by pnrobinson** [comment]
I added a few more terms. At this point, I think we really need to see if we are going in the right direction and get some feedback from the immunologists as to what is missing and whether the proportions (denominator) are correct. Let's hold off on this until we get more feedback. I would even close this term and make individual issues for the cell types, these mega issues are really hard to deal with> @nicolevasilevsky

**Comment by pnrobinson** [comment]
@nicolevasilevsky Can we touch bases about this and try to close this issue?

**Comment by nicolevasilevsky** [comment]
sure! Did you you get any feedback from the immunologists?

**Comment by pnrobinson** [comment]
@nicolevasilevsky @LCCarmody  I think it would be good to add terms for the cell types listed in Leigh's message above, but not for intraepithelial lymphocyte, which is not circulating. Can we touch bases to coordinate this?

**Comment by nicolevasilevsky** [comment]
Yes, do you want to set up a meeting @pnrobinson?

**Comment by pnrobinson** [comment]
@LCCarmody @nicolevasilevsky could we meet this week to work on this?

**Comment by nicolevasilevsky** [comment]
Per the call today, here are our action items:

- [ ] Nicole: request new terms to PATO: increased proportion, decreased proportion
- [ ] Nicole: create patterns in uPheno for: abnormalProportionOfCellTypeInAnatomicalEntity, decreasedProportionOfCellTypeInAnatomicalEntity, increasedProportionOfCellTypeInAnatomicalEntity
(Note- this is dependent on the new PATO terms above)
- [ ] Leigh and Nicole: need a list of all the cell types that should be added to HPO via the DOSDP
- [ ] Leigh and Nicole: coordinate with @matentzn to add these new terms to HPO

**Comment by matentzn** [comment]
Nice one!

**Comment by nicolevasilevsky** [comment]
@pnrobinson @LCCarmody 
cc @matentzn and @dosumis 

@matentzn and @dosumis - On a call today with @pnrobinson and @LCCarmody, we decided we needed a pattern for:
Abnormal T cell proportion
Increased T cell proportion
Decreased T cell proportion

I suggested this pattern:
  text: "'has_part' some ('proportionality to' and ('inheres_in' some (%s and ('part_of' some %s))) and ('has_modifier' some 'abnormal'))"
  vars:
  - cell
  - location

@matentzn commented:
This sounds like a relational quality... Proportionality compared to what? All other cell types in the location?

On our call though, we didn't want to state that the abnormal (or increased or decreased) proportion was relative to other cells. Do we need to have that in order to use this quality?

@pnrobinson would you mind explaining the rationale for that?

**Comment by LCCarmody** [comment]
I'm linking a [google doc](https://docs.google.com/spreadsheets/d/1MnR8T-itI8cHnfprxcDdqk_TbqSCTh1woysd-dHycsQ/edit?usp=sharing) collected just from terms that are listed as 'proportional' in HP.  Most are straight forward and have a relational quality listed in the text definition (ie. proportional to B cells or T cells).  A few aren't stated.  

There are a number of cells I can't find terms that match in CL. EIther it is too vague or I think it is a duplicate.  HP hasn't been consistent with naming or location of these terms, so I suspect a number of terms are redundant and need to be merged, but I am not absolutely positive.   In particular, most of these terms are listed under abnormal T cell distribution, but many are listed directly under decreased/increased count of some cell type.    
@pnrobinson @nicolevasilevsky Could you look to see if some of these terms are the same?  I used the notes section to suggest which I thought were the same.

**Comment by nicolevasilevsky** [comment]
From Huddle:
Peter said we should use functional cell terms from the CL
Add to comments in HPO - this combination of markers is used to measure cells

We should make individual issues for terms where we have questions and we can share with the immunologists

**Comment by nicolevasilevsky** [comment]
- [ ] @nicolevasilevsky and @LCCarmody- we should go through each of these terms and create a ticket for each, and @pnrobinson will try to find PMIDs for each term.

**Comment by pnrobinson** [comment]
done
