### ISSUE TITLE
Invalid synonym type?

### ISSUE THREAD

**Issue by njoannin** [obophenotype/human-phenotype-ontology#4294]
_Question regarding existing term:_
### 1. Node in question:

[Term]
id: HP:0500163
name: Hypoornithinemia
def: "An abnormal decrease in ornithine in the blood." [http://orcid.org/0000-0001-7941-2961]
synonym: "Decreased blood ornithine concentrations" EXACT layperson [http://orcid.org/0000-0001-7941-2961]
synonym: "Low blood ornithine levels" EXACT hasDbXref []
is_a: HP:0003112 ! Abnormality of serum amino acid level
is_a: HP:0012025 ! Abnormality of ornithine metabolism
property_value: http://purl.org/dc/elements/1.1/creator http://orcid.org/0000-0001-7941-2961
property_value: http://purl.org/dc/elements/1.1/date 2018-10-12T13:25:49Z xsd:dateTime

### 2. Problematic line:

synonym: "Low blood ornithine levels" EXACT hasDbXref []

### 3. Question:

Should this synonym be "EXACT hasDbXref" ?

It is the only one in the whole ontology, and it breaks my pipeline. I use the Python pronto package, which complains with the following message:

ValueError: Undefined synonym type: hasDbXref

**Comment by nicolevasilevsky** [comment]
yep, that was an error, just fixed it. Thanks for reporting that.

**Comment by drseb** [comment]
I would say end of january? would that be ok?

**Comment by njoannin** [comment]
That would be great! Thanks :)

**Comment by drseb** [comment]
Ok. I added a QC-step, so that this shouldn't happen again in the future. Thanks for reporting. 

(I am still not sure if pronto is correct in throwing an error here :-) )

**Comment by njoannin** [comment]
I don't know about pronto... If it hadn't raised an error, we would probably never have noticed the issue ;)
