### ISSUE TITLE
hemangioma and carcinoma terms should not inhere in phenotypes

### ISSUE THREAD

**Issue by matentzn** [obophenotype/human-phenotype-ontology#4298]
The following terms are inhering in HP phenotypes rather than NCIt terms:

'Esophageal hemangioma'
'Hepatic hemangioma'
'Intestinal hemangioma'
'Laryngeal hemangioma'
'Ovarian carcinoma'
'Spleen hemangioma'

For example [spleen hemangioma](https://www.ebi.ac.uk/ols/ontologies/hp/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FHP_0410268):

```
'has part' some 
('increased amount' and ('inheres in' some 
(Hemangioma and ('part of' some spleen))) and ('has modifier' some abnormal))
```

Where Hemangioma refers to the HP term HP_0001028. To ensure the consistency of HP, it would be great if someone could update the logical definitions with references to NCIt terms instead of HP terms. Compare for example [Retropharyngeal hemangioma](https://www.ebi.ac.uk/ols/ontologies/hp/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FHP_0410273) where it was done correctly.

**Comment by pnrobinson** [comment]
@matentzn according to what I understand about our plans for NCIT integration, these logical definitions are all wrong. Can we skype about this.

**Comment by matentzn** [comment]
Yeah, no problem, I will organise a call for next week. I just wanted this issue documented, no need to act right this minute.

**Comment by pnrobinson** [comment]
@matentzn according to what I understand about our plans for NCIT integration, these logical definitions are all wrong. Can we skype about this.

**Comment by nicolevasilevsky** [comment]
Hi @matentzn and @pnrobinson - I added some of these terms and the logical definitions. Can I join the call (if it is convenient), or can you let me know what you decide? Happy to help fix these logical definitions once we come to a consensus.

**Comment by matentzn** [comment]
Of course! Also, just as a heads up, species reject ncit for being too obviously human specific. Talk soon.

**Comment by pnrobinson** [comment]
can we close this @matentzn  ?

**Comment by matentzn** [comment]
Ah, this is still a problem in a few cases; but @nicolevasilevsky @LCCarmody and I have an eye on it and will take care of this. However, right now, there are still quite a few of these, inculding the above [spleen hemangioma](https://www.ebi.ac.uk/ols/ontologies/hp/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FHP_0410268). If you check the logical definition, you will see that it inheres in another HP term; which it shouldnt. 

@LCCarmody (or @nicolevasilevsky), if you open HP, and run this DL query:

```
'has part' some ('inheres in part of' some 'Phenotypic abnormality')
```

You will find the following classes defined in this way. I recommend removing the logical definition for all of them, as they are currently meaningless!

'Esophageal hemangioma'
'Hepatic hemangioma'
'Intestinal hemangioma'
'Laryngeal hemangioma'
'Multiple epiphyseal dysplasia'
'Ovarian carcinoma'
'Spleen hemangioma'
'Vulvar hemangioma'

**Comment by LCCarmody** [comment]
@pnrobinson I can take care of this later, if you'd like.

**Comment by pnrobinson** [comment]
@LCCarmody could you please take care of this and close the issue!

**Comment by matentzn** [comment]
@nicolevasilevsky will do it.. In the end this did not happen. Miscommunication.. Sorry all!
