### ISSUE TITLE
Obsoletion strategy in the future

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#4305]
We have started to discuss obsoletion and the probable consequences for downstream users. In the case that lead to that discussion, the class "congenital neutropenia" was obsoleted (as per community request). However, in Solve-RD we have still patient-descriptions using this class and it is not trivial to replace the links to the class without loosing information. 
1. We can't easily request a **timely re-annotation** of the patient as the data-analyist-to-data-provider path is very long. 
2. There is no **information-preserving** automated replaced-by strategy. In that case, the replace by annotation refers to a class that does not the contain the onset information. 

We now have two options as per discussions.

- Change our obsoletion strategy. Classes will be marked as soon-to-be-obsoleted and we will thus try to avoid the issues such as in 1)
- Find a way to obsolete in a computer-interpretable way, such that it is possible to automatically replace the annotation to "congenital neutropenia" with an annotation to "neutropenia" with onset modifier "congenital"

Request for options by everybody, but especially @cmungall @mellybelly @pnrobinson @balhoff

**Comment by balhoff** [comment]
> Change our obsoletion strategy. Classes will be marked as soon-to-be-obsoleted and we will thus try to avoid the issues such as in 1)

We've had some discussions along these lines for GO: https://github.com/geneontology/go-ontology/issues/15532

Not a lot of detail there, but the idea would be to put annotations into the ontology so that others could build functionality into their systems to give themselves some early warning.

**Comment by drseb** [comment]
Thanks. I asked at the linked ticket about the best strategy to re-use what has been done in GO.

**Comment by pnrobinson** [comment]
I would add that there are terms which are just mistakes, and I think there is still a case for rapid merging of these, because they will also lead to suboptimal results in analysis and we do not want anybody using them. There are other terms which may be suboptimal (e.g., congenital XYZ, where we would rather have just XYZ plus a modifer). These terms may have been used a lot and we should be much more careful.

**Comment by drseb** [comment]
Sounds good. We will soon add the needed relation for marking planned obsoletions.
see https://github.com/information-artifact-ontology/ontology-metadata/issues/32

**Comment by matentzn** [comment]
I would also like to chip in that we are interested to create more comprehensive guidelines for community-wide obsoletion. We based it on this [wiki](https://github.com/obophenotype/human-phenotype-ontology/wiki/Obsoletion). It would be great that whatever you decide here will be reflected there.

**Comment by pnrobinson** [comment]
I think we can transfer this to the HPO wiki as above? Seb and I spoke about this in person also and I think we have consensus. If nobody shouts, I will write a summary to the wiki.

**Comment by pnrobinson** [comment]
I think we have reached agreement here. I extended the texts in the wiki
https://github.com/obophenotype/human-phenotype-ontology/wiki/Obsoletion
PLEASE everybody who is editing HPO, make sure you are aware of the information in the WIki!
