### ISSUE TITLE
new term: cANCA, pANCA positivity

### ISSUE THREAD

**Issue by yankeetomer** [obophenotype/human-phenotype-ontology#4308]
Hi, I was reviewing a few papers on genetic susceptibility to inflammatory bowel disease which I tried to annotate and realized that there are no specific terms for **perinuclear** or **cytoplasmic** anti-neutrophil antibody positivity (p-ANCA or c-ANCA respectively). These antibodies are often used in rheumatology especially in the setting of vasculitides in order to differentiate between different diseases and specifying between the two is valuable to the phenotype.

### 1. Preferred term label:
- Perinuclear antineutrophil antibody (p-ANCA) positivity
- Cytoplasmic antineutrophil antibody (c-ANCA) positivity

### 2. Synonyms
- p-ANCA positivity
- c-ANCA positivity

### 3. Textual definition

The presence of autoantibodies in the serum that react against proteins predominantly expressed in cytoplasmic granules or perinuclear region of neutrophils (c-ANCA and p-ANCA respectively).

PubMed References:
-Antineutrophil cytoplasmic antibodies (ANCA) testing: detection methods and clinical application. PMID: 24854381
-The clinical presentation and therapy of diseases related to anti-neutrophil cytoplasmic antibodies (ANCA). PMID: 27481040 
-The value of serum antibodies in differentiating inflammatory bowel disease, predicting disease activity and disease course in the newly diagnosed patient. PMID: 28661185

### 4. Parent term  
[HPO Browser](http://compbio.charite.de/hpoweb/#id=HP:0003453)

### 5. Which diseases are characterized by this term ? (e.g. Orphanet- or OMIM-id)
-GRANULOMATOSIS WITH POLYANGIITIS; (MIM: 608710)
-CHOLANGITIS, PRIMARY SCLEROSING (MIM: 613806)
-RHEUMATOID ARTHRITIS (MIM:180300)
-INFLAMMATORY BOWEL DISEASE (MIM: 266600)

### 6. Your nano-attribution 
Tomer Talmy M.D.
Organization: Emedgene Technologies
ORCID: https://orcid.org/0000-0002-7440-8864

**Comment by pnrobinson** [comment]
adding terms & annotations, thanks, they should be visible in February on our webpage
