### ISSUE TITLE
new terms: Abnormal drug response

### ISSUE THREAD

**Issue by yankeetomer** [obophenotype/human-phenotype-ontology#4309]
HPO does not currently have any entries that relate to pharmacogenomics. The topic has been brought up here in the past but I still believe there is a vital need for at least a few basic terms that can serve researchers in annotating clinical phenotypes. Here are my suggestions:

### 1. Preferred term label

- Abnormal drug response

Subclasses:
1. Increased blood drug concentration
2. Decreased blood drug concentration
3. Adverse drug response
4. Decreased drug efficacy
5. Refractory drug response

### 2. Synonyms
**Abnormal drug response**

- Altered drug response

**Increased blood drug concentration**

- Elevated blood drug concentration
- Increased serum drug concentration
- Elevated serum drug concentrations
- Elevated plasma drug concentration
- Increased plasma drug concentration

**Decreased blood drug concentration**

- Reduced blood drug concentration
- Decreased serum drug concentration
- Reduced serum drug concentrations
- Reduced plasma drug concentration
- Decreased plasma drug concentration

**Adverse drug response**

- Adverse drug reaction
- Toxic drug response

**Reduced drug efficacy**

- Decreased drug efficacy

**Refractory drug response**

- Drug resistance

### 3. Textual definition (should be understandable even for non-specialists, please include a PubMed ID for relevant articles providing additional information about the suggestion)

**Abnormal drug response**
Individual variation in metabolic or immune response to drugs varying from potentially from potentially life-threatening adverse drug reactions to alteration of therapeutic efficacy.
PMID: 16948615
**Increased blood drug concentration**
High plasma concentration of a drug as compared to previously measured thresholds. 
PMID: 26075072
**Decreased blood drug concentration**
Low plasma concentration of a drug as compared to previously measured thresholds. 
PMID: 26075072
**Adverse drug response**
An unpleasant or harmful reaction resulting from treatment with a drug. 
PMID:11072960
**Reduced drug efficacy**
Decreased response to a drug intervention in comparison to the expected response.
PMID: 26178435 
**Refractory drug response**
Absent or significantly reduced efficacy of drug intervention characterized by lack of measurable benefit or deterioration of disease course. 
PMID: 29188449

### 4. Parent term
Phenotypic abnormality 
HP:0000118 
(http://compbio.charite.de/hpoweb/showterm?id=HP:0000118)

### 5. Which diseases are characterized by this term ? (e.g. Orphanet- or OMIM-id)
One example: 
EPILEPTIC ENCEPHALOPATHY, EARLY INFANTILE, 7; EIEE7
OMIM: 613720 (Drug-resistant epilepsy)

See https://www.pharmgkb.org/ for a wide spectrum of genotype-phenotype connections relevant to these terms. 

### 6. Your nano-attribution 

Tomer Talmy M.D.
Organization: Emedgene Technologies
ORCID: https://orcid.org/0000-0002-7440-8864

**Comment by pnrobinson** [comment]
I think these are good suggestions, but I would say that the HPO should not start to provide terms for each medication --- this would require other software to link say an ontology term from DrugCentral (http://drugcentral.org/) that denotes a certain medication. Would this work for you? @drseb @kingmanzhang @mellybelly @cmungall  thoughts?

**Comment by yankeetomer** [comment]
I fully agree with you that HPO is not the place for specific terms per medication but rather something more encompassing that may help researchers and clinicians denote certain drug-related prototypes. 
Thanks a lot for the quick response!

**Comment by nicolevasilevsky** [comment]
In LOINC, there are several tests for the presence of specific drugs in the blood, which I think we could potentially add as drug classes - like increased level of anticonvulsants in the blood, or increased level of antibiotics. These could be subclasses of 'Elevated blood drug concentration'.

Some examples of anticonvulsant drugs are:
31019-3 | Low | 10-Hydroxycarbazepine [Mass/volume] in Serum or Plasma
3432-2 | High | Carbamazepine serum/plasma
3487-6 | High | Clobazam serum/plasma
3616-0 | High | Ethosuximide serum/plasma
6948-4 | High | Lamotrigine serum/plasma
31019-3 | High | 10-Hydroxycarbazepine [Mass/volume] in Serum or Plasma
35107-2 | High | Norclobazam [Mass/volume] in Serum or Plasma
3948-7 | High | Phenobarbital serum/plasma
3968-5 | High | Phenytoin serum/plasma
4086-5 | High | Valproate serum/plasma
29620-2 | High | Zonisamide serum/plasma

**Comment by pnrobinson** [comment]
I added the terms today. Sorry very much for the delay, and thanks again for the great suggestion. I put the terms under 'Abnormality of metabolism/homeostasis'. They will be visible with the next HPO release in August.

**Comment by pnrobinson** [comment]
@nicolevasilevsky  I think we should explore ways of using slots -- we can use the HPO term and logically modify it with the compound. Otherwise, we will get lots and lots of terms.
