### ISSUE TITLE
Final decision on what to do with NCIt: EQ or xref ONLY

### ISSUE THREAD

**Issue by matentzn** [obophenotype/human-phenotype-ontology#4323]
Which of these is the final executive HP decision
1. We remove all NCIt references from EQs and push them into xrefs
2. We replace all NCIt references in EQs by something else (what?)
3. NCIt will be used to refer to physical entities (tumors etc) (they remain in the EQs)

I have attached a list of [NCIt references](https://github.com/obophenotype/human-phenotype-ontology/files/2808022/ncit_classes_with_refs_in_hp.txt) that still occur in the EQs (207 affected HP classes). The procedure for the diligent curators is:

1. Open hp-edit
2. Search for NCIt term in above list. Click on it.
3. Click on Usage tab in protege to find all HP classes referencing that NCIt class 
4. Delete EQ (or edit, if there is a replacement)
5. Add xref to the NCIT term

But please, be very sure this is a good idea. **I am against it;** I would rather pretend NCIt is about something that it is not (physical entities, not diseases), but I understand your arguments not to make that assumption, so no need to re-iterate here. Just decide what to do!

@cmungall @pnrobinson @drseb @dosumis

**Comment by pnrobinson** [comment]
Option 3 is actually 180 degrees wrong. The HPO by definition refers to a phenotypic feature (the physical entity, tumor) and not to the disease entity. In principle, the NCIT definition should be

```
Lung carcinoma
equivalent to
 {disease
    <keep all of the current NCIT logical statements, which are a work of art>
   characterized_by HPO:lung_carcinoma (meaning the physical tumor)
}
```

The HPO definition should be something like
```
Lung carcinoma
equivalent to
carcinoma (MPATH or NCIT)
and 
<Some differentia>
```
or (probably better)
```
Lung carcinoma
characteristic_feature_of NCIT:lung carcinoma
```

**Comment by dosumis** [comment]
@matentzn -  seems like a reasonable approach, pending agreement on logical definitions.

**Comment by pnrobinson** [comment]
@matentzn did we have a clear action item here? Downstream alg's can use xrefs by the way if they really want to, and I am not sure that this decision currently will impinge much on our software stack. Having these items as xrefs would in principle allow us to automagically generate definitions once we have settled the modeling.

**Comment by matentzn** [comment]
There is only one last optional action item remaining here:

Someone could open src/ontology/hp_ncit_eq.owl in protege and for every HP class in there, make sure that in hp-edit.owl, the appropriate xref is present. So if you see:
HP:1000 equivalentTo: has part some X and inheres in some NCIT:0011, make sure that in hp-edit.owl, HP:1000 has an xref to NCIT:0011. That is all! 

 @nicolevasilevsky probably the best to do that?

**Comment by nicolevasilevsky** [comment]
@matentzn i am just doing this now - I looked at the first five terms in hp_ncit-eq.owl and I don't see the NCIt terms xref'd in hp-edit.owl, as you described above. Sounds like the should be though, yes?

Should I check all the terms in hp_ncit-eq.owl against hp-edit.owl, or does it already seem like something is wrong/missing?

**Comment by matentzn** [comment]
I would assume none of the terms in the ncit eq file currently have xrefs; so yes, if you want them they need to be added!

**Comment by nicolevasilevsky** [comment]
I talked to @matentzn and I am going to add NCIT xrefs to the HPO terms, as they currently do not exist.

**Comment by nicolevasilevsky** [comment]
this term: HP_0030741 'Mediastinal teratoma'. already has a NCIT xref to: NCIT:C6438 Mediastinal teratoma, which is more specific than the NCIT term used in the logical def in the hp_ncit_eq.owl file (which uses NCIT_C3403 teratoma.) Do you want to update the hp_ncit_eq.owl file, @matentzn?
