### ISSUE TITLE
HP_0031859 minor weirdness with synonym obsoletion

### ISSUE THREAD

**Issue by matentzn** [obophenotype/human-phenotype-ontology#4324]
if you open Protege and search for HP_0031859 an annotation property named 'obsolete' that annotates a single class (Mesomelic short stature) with the property has_synonym_type. Someone must have accidentally drag and dropped it wrong. Not sure what this is supposed to mean, but my sense is that it means:

the synonym Mesomelic dwarfism for the class Mesomelic short stature is obsolete. If so, please, fix the syntax to something sensible (right now, obsolete (HP_0031859) is an annotation property, so maybe it can be used like so):

HP_0031859 value 'true'

@pnrobinson @nicolevasilevsky @LCCarmody

**Comment by nicolevasilevsky** [comment]
Yes, seems like the synonym Mesomelic dwarfism should be obsoleted? I think normally we just remove synonyms that we no longer want to include?

In MONDO, there is an annotation called excluded_synonym (see MONDO_0001319 'bladder lateral wall cancer', for an example of this annotation being used). Maybe we would want to use this annotation in HPO too?

**Comment by pnrobinson** [comment]
@drseb 
The reason for this is that the synonym was used extensively in older literature but the term dwarfism is now considered offensive. Hence, the synonym is called obsolete. We discussed this a few years ago, and "obsolete" was the best label we came up with. Is this interfering with something else?

**Comment by drseb** [comment]
as long as you "obsolete" this synonym correctly, it won't interfere with anything.

**Comment by matentzn** [comment]
What is the policy on obsoleting synonyms? I could not find it in your obsoletion docs.. Did you want to have an annotation property like "obsolete synonym"?

**Comment by pnrobinson** [comment]
We do not want to obsolete the synonym we want to say that it should not be used going forward. We need to keep it for text mining and because not everybody uses the currently accepted terminology. If this is not causing a problem, then we should leave it as is!

**Comment by drseb** [comment]
I think we use SynonymType and annotated it as obsolete. All ok. We have done this before

**Comment by pnrobinson** [comment]
I think we do not need to change anything, and can close this issue.

**Comment by matentzn** [comment]
Sorry to re-open this briefly.

Can we use a different syntax for this? right now it is:

```
has_synonym_type obsolete;
```
where obsolete is a non-standard annotation property in the HP namespace (http://purl.obolibrary.org/obo/HP_0031859)

This is weird for two reasons:
1) Grammatically, you use an annotation property in the place where an annotation value should be used. So if you have to stick with that, http://purl.obolibrary.org/obo/HP_0031859 should be an individual, not an annotation property.
2) There are already standard obsoletion mechanisms that would work here. Why not use them? `owl:deprecated true`? So you say:
AnnotationAssertion(HP1,has_synonym,"Dwarfism") owl:deprecated true. So it will still be there (for text mining tools), but clearly flagged as obsolete.

If the standard way does not work for you, you should use this one:
* Rename http://purl.obolibrary.org/obo/HP_0031859 to 'obsolete synonym'
* Annotate the above assertion with `'obsolete synonym' true`.
Note I still prefer the the standard way, but either way works; just not so much the one that is there right now.

**Comment by drseb** [comment]
I don't think there is a standard way of obsoleting a synonym. If so, where is this documented? 

Also, we have used "has_synonym_type" for all our synonyms, so this change cannot be done in isolation only for the obsoletion-case.

**Comment by matentzn** [comment]
Okay, lets leave it for now. I dont really mind so much; it will keep being flagged up by QC, but we can just ignore it for now until we have some more critical use case that justifies the effort (other than nicos pedantic self).

**Comment by pnrobinson** [comment]
We are NOT obsoleting the synonym. We are marking the synonym as obsolete but keeping it for mining legacy texts etc. Maybe we should document this bettersssss

**Comment by drseb** [comment]
we had the relabelling discussion before. not sure if "obsolete" is the best option. but so far we haven't found a better label than "obsolete" :-/

**Comment by balhoff** [comment]
I know we went through a bunch of options before, but I thought of a new one that I think would work well: "outmoded".

**Comment by pnrobinson** [comment]
well, outmoded just means out of fashion(=mode), and we want to say -- DO NOT USE THIS ANYMORE!

**Comment by matentzn** [comment]
use_discouraged true?
