### ISSUE TITLE
new term: Pseudoseizures

### ISSUE THREAD

**Issue by yankeetomer** [obophenotype/human-phenotype-ontology#4328]
### 1. Preferred term label

- Pseudoseizures

### 2. Synonyms

- Psychogenic nonepileptic seizures (PNES)

### 3. Textual definition (should be understandable even for non-specialists, please include a PubMed ID for relevant articles providing additional information about the suggestion)

**Pseudoseizures**
Sudden, involuntary seizure-like attacks that, unlike epileptic seizures, are not related to electrographic ictal discharges. (PMID: 23251092)

Definitions:
PMID: 23251092

Examples of cases caused by inherited disease:
PMID: 25885783

### 4. Parent term
Seizures
HP:0001250
(http://compbio.charite.de/hpoweb/showterm?id=HP:0001250)

### 5. Which diseases are characterized by this term ? (e.g. Orphanet- or OMIM-id)

Syndrome described Sirrs et al. (PMID: 25885783) caused by defect of FATTY ACID AMIDE HYDROLASE 2; FAAH2 (OMIM: 300654)

### 6. Your nano-attribution 

Tomer Talmy M.D.
Organization: Emedgene Technologies
ORCID: https://orcid.org/0000-0002-7440-8864

**Comment by nicolevasilevsky** [comment]
@yankeetomer I don't think HP:0001250 Seizures is the best parent class, because pseudoseizures, by definition, are not seizures.
I suggest the parent HP_0012638 'Abnormality of nervous system physiology'

@pnrobinson if this looks okay to you, I can add this.

**Comment by yankeetomer** [comment]
@nicolevasilevsky Thanks, I agree that Seizures as a parent class does not fit, but I was wary of placing the term under abnormalities of behavior. 'Abnormality of nervous system physiology' seems like a fitting parent term.
Thanks again,
Tomer

**Comment by pnrobinson** [comment]
https://jamanetwork.com/journals/jama/fullarticle/2732484?guestAccessKey=4eccef4d-0563-4cfe-b45b-7d07522d9d9f&utm_source=silverchair&utm_medium=email&utm_campaign=article_alert-jama&utm_content=olf&utm_term=042619

**Comment by pnrobinson** [comment]
@DLewisSmith
Adding 
Psychogenic Non-Epileptic Seizure
 under Behavioral abnormality
Def: Psychogenic non-epileptic seizures (PNES) are an important cause of apparently treatment-resistant epilepsy and remain a major diagnostic challenge in epileptology. The two main PNES groups are panic disorder (also occurring as a reaction in people with epilepsy) and dissociative disorder (pseudoseizure), often developing inpatients with no history of epilepsy. The main markers distinguishing PNES from epileptic seizures are (i) the way the patient tells the story (not focusing on the seizure symptoms, avoidance of the word seizure, etc) )ii) that they are prolonged (many minutes); (iii) associated with hyperventilation and eyes closed; and that they present as treatment-resistant epilepsy despite an often normal intellect and brain imaging. Note that patients with PNES may bite their tongue (though usually the front not the side), may injure themselves (though usually cuts, carpetburns or wrist injury from falling on to an out-stretched arm) and may report seizures from sleep (the night time being a vulnerable time for panicsymptoms and likely to be awake at the onset). (https://pubmed.ncbi.nlm.nih.gov/22976060/)

And adding the existing term Panick attach as a child and creating new term

Label: Pseudoseizure
Sudden, involuntary seizure-like attacks that, unlike epileptic seizures, are not related to electrographic ictal discharges. 
PMID:23251092


Comment: Psychogenic non-epileptic seizures (PNES) are an important cause of apparently treatment-resistant epilepsy and remain a major diagnostic challenge in epileptology. The two main PNES groups are panic disorder (also occurring as a reaction in  people  with  epilepsy)  and  dissociative disorder (‘pseudoseizure’), often developing inpatients with no history of epilepsy. The mainmarkers  distinguishing  PNES  from  epilepticseizures are:•the way the patient tells the story (not focusing onthe seizure symptoms, avoids using the word‘seizure’, etc);3•that they are prolonged (many minutes);•associated with hyperventilation and eyes closed;and that they present as treatment-resistant epilepsydespite an often normal intellect and brain imaging.Note that patients with PNES may bite theirtongue (though usually the front not the side),may injure themselves (though usually cuts, carpetburns or wrist injury from falling on to an out-stretched arm) and may report seizures from sleep(the night time being a vulnerable time for panicsymptoms and likely to be awake at the onset).
