### ISSUE TITLE
revise logical definition for HP_0003155 'Elevated alkaline phosphatase'

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#4339]
The logical def of HP_0003155 'Elevated alkaline phosphatase' is:
'has part' some 
('increased amount' and ('inheres in' some 'alkaline phosphatase, tissue-nonspecific isozyme') and ('has modifier' some abnormal))

but i think it should be:
'has part' some 
('increased amount' and ('inheres in' some 'alkaline phosphatase activity') and ('has modifier' some abnormal))

The children should use 'alkaline phosphatase activity' too, as well as the sibling class HP_0003282 'Low alkaline phosphatase'

**Comment by drseb** [comment]
Increases amount is not a process quality. Do you mean increased activity?

Sent from mobile

**Comment by nicolevasilevsky** [comment]
the logical def currently uses 'increased amount' - so that should be revised too!

**Comment by pnrobinson** [comment]
Essentially, you can have increased/decreased amount of an enzyme (which might be measured by ELISA or other antibody based assay)  or increased/decreased activity (which can be a reflection of amount of the enzyme or of other things), which is measured by an assay that looks a conversation of a colored substrate etc.
In this case, I believe that if you measure overall alk phos, you are measuring activity, but if you measure the subtypes of alk phos, you use electrophoresis. I do not believe it is possible to distinguish between the activities of the various isozymes.
This means that this part of the HPO 
https://hpo.jax.org/app/browse/term/HP:0003155
is conflating activity and amount. However, these are methodological details, and I do not think users of the HPO would thank us if we separated them out. Also, there are different measurement tests.

I think Nicole's suggestion is correct though, and I have revised the two terms (increased/decreased).
