### ISSUE TITLE
question re: HP_0000744 'Low frustration tolerance'

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#4340]
The logical def for HP_0000744 'Low frustration tolerance' is
'has part' some 
('increased rate' and ('inheres in' some 'frustration behavior') and ('has modifier' some abnormal))

To me this sounds like there is increased frustration.

This term seems difficult to logically define, I feel like using decreased rate would imply decreased frustration.

There isn't a text def either.

**Comment by pnrobinson** [comment]
Are there animal models that display something that can be construed as increased frustration behavior? It seems like this definition to an NBO (?) term is not more enlightening (it is basically a tautology with weak bells and whistles)  than the subclass assertion itself.

**Comment by nicolevasilevsky** [comment]
yes, frustration behavior is an NBO term

Not sure about the animal models. Looks like it's been annotated to some diseases:
https://hpo.jax.org/app/browse/term/HP:0000744

Maybe it would help to add a text def. Thinking about this more, I guess I do understand what the logical definition means - it means someone has a low tolerance for frustration, ie gets frustrated easily (so increased frustration is correct).

Here is a wikipedia article:
https://en.wikipedia.org/wiki/Low_frustration_tolerance

**Comment by pnrobinson** [comment]
Possible definition:
The feeling of frustration can be defined as an emotional reaction that occurs if a desired goal is not achieved. Frustration intolerance is defined as an age-inappropriate response to frustration characterized by crying or temper tantrums (in children) or aggressive or other undesirable behaviors.

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3065082/

**Comment by pnrobinson** [comment]
I have added the text definition. I think the logical definition is decent, although I do think we need to go through all of the behavior definitions at some point @nicolevasilevsky  close if you are OK

**Comment by nicolevasilevsky** [comment]
looks good, thanks @pnrobinson!
