### ISSUE TITLE
HP:0031993's parent

### ISSUE THREAD

**Issue by BrunOrpha** [obophenotype/human-phenotype-ontology#4341]
Maybe the parent of 
HP:0031993 HOFFMAN SIGN 
should be
HP:0007256 ABNORMAL PYRAMIDAL SIGN,
since it is the clinical equivalent of Babinski's sign, but for the upper limbs ?
Best,
Bruno

### 4. Parent term (use [HPO app](https://hpo.jax.org/app/), [HPO Browser](http://compbio.charite.de/hpoweb/showterm?id=HP:0000118) or [OLS](http://www.ebi.ac.uk/ols/ontologies/hp))
HP:0007256

**Comment by pnrobinson** [comment]
This is a good suggestion.
We should expand the definition also on the basis of this https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2989225/

**Comment by pnrobinson** [comment]
revised parentage, thanks for the suggestion!

**Comment by BrunOrpha** [comment]
Thank you !
