### ISSUE TITLE
NTR: Increased circulating 1-methylhistidine level

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#4343]
### 1. Preferred term label
abnormal/Increased/decreased circulating 1-methylhistidine level

### 2. Textual definition

An increased concentration of 1-methylhistidine in the blood.

### 3. Parent term
HP_0010906 Hyperhistidinemia

For LOINC code: 20633-4 1-Methylhistidine [Moles/volume] in Serum or Plasma

**Comment by pnrobinson** [comment]
We should also add 3-methylhistidine
https://www.ncbi.nlm.nih.gov/pubmed/29573154

Increased circulating 1-methylhistidine level
def:An increased concentration of 1-methylhistidine in the blood.
comment: 1‐methylhistidine (1‐MH; N‐pi‐methylhistidine) is mainly synthesized in muscle of animals but not in humans and occurs as part of the dipeptide anserine (beta‐alanyl‐N1‐methyl‐histidine).

**Comment by callahantiff** [comment]
> We should also add 3-methylhistidine
> https://www.ncbi.nlm.nih.gov/pubmed/29573154
> 
> Increased circulating 1-methylhistidine level
> def:An increased concentration of 1-methylhistidine in the blood.
> comment: 1‐methylhistidine (1‐MH; N‐pi‐methylhistidine) is mainly synthesized in muscle of animals but not in humans and occurs as part of the dipeptide anserine (beta‐alanyl‐N1‐methyl‐histidine).

@pnrobinson - Does #4346 cover 3-methylhistidine?

**Comment by pnrobinson** [comment]
Actually I am wondering if there is an "abnormal" phenotype for 1-methylhistidine level -- it seems that you get this in your blood by eating meat, but I am not sure if there are normal levels or not.

**Comment by pnrobinson** [comment]
as with the other terms, this does not seem to translate well into an HPO term since there is no clear abnormal level, the level varies according to diet.
