### ISSUE TITLE
NTR: Positive anticonvulsant medication blood test

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#4344]
**New term:** Positive anticonvulsant medication blood test
**Parent:** HP_0410172 Blood xenobiotic
**Def:** Detection of acetaminophen in the blood.
**Notes:** There are several LOINC codes noted below that detect levels of anti-convulsant drugs in the blood. Or should this be a child of 'Elevated blood drug concentration'? see #4309 

LOINC code | High/Low | Label
-- | -- | --
31019-3 | Low | 10-Hydroxycarbazepine [Mass/volume] in Serum or Plasma
3432-2 | High | Carbamazepine serum/plasma
3487-6 | High | Clobazam serum/plasma
3616-0 | High | Ethosuximide serum/plasma
6948-4 | High | Lamotrigine serum/plasma
31019-3 | High | 10-Hydroxycarbazepine [Mass/volume] in Serum or Plasma
35107-2 | High | Norclobazam [Mass/volume] in Serum or Plasma
3948-7 | High | Phenobarbital serum/plasma
3968-5 | High | Phenytoin serum/plasma
4086-5 | High | Valproate serum/plasma
29620-2 | High | Zonisamide serum/plasma

**Comment by pnrobinson** [comment]
For now, I do not think we can represent this kind of test in the HPO -- there is a therapeutic and a toxic range, but this has a different logic than HPO terms and thus if we want to represent it we will need another framework.
