### ISSUE TITLE
NTR: Increased circulating 3-methylhistidine

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#4346]
NTR: Increased circulating 3-methylhistidine (and decreased, abnormal)
Parent: HP_0010906 Hyperhistidinemia

For LOINC code:
20635-93-Methylhistidine [Moles/volume] in Serum or Plasma

**Comment by pnrobinson** [comment]
see https://www.ncbi.nlm.nih.gov/pubmed/29573154
It seems the level is related to diet and there is no "abnormal" level
