### ISSUE TITLE
NTR: Increased circulating vitamin B6 levels

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#4347]
NTR: Increased circulating vitamin B6 levels
and decreased, abnormal
Source: PMID:18754531 

Parent: HP_0004340 Abnormality of Vitamin B Metabolism

For LOINC code:
1688-1 4-Pyridoxate [Mass/volume] in Serum or Plasma

**Comment by pnrobinson** [comment]
see new term HP_0004341 @nicolevasilevsky @kingmanzhang

**Comment by kingmanzhang** [comment]
done

**Comment by jmcmurry** [comment]
Just flagging that according to OLS, the new term is actually HP_0032477
