### ISSUE TITLE
NTR: Decreased alanine level in cerebral spinal fluid

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#4348]
NTR: Decreased alanine level in cerebral spinal fluid
and increased, abnormal

Parent: HP_0002921 Abnormality of the Cerebrospinal Fluid

For LOINC code:
22657-1 Alanine [Moles/volume] in Cerebral spinal fluid

**Comment by callahantiff** [comment]
@nicolevasilevsky approved editing to this request to the following:

**LOW LAB RESULT:**
**NTR:** Decreased alanine level in cerebral spinal fluid
**Parent:** NTR Abnormal alanine level in cerebral spinal fluid (Issue #4416)
**For LOINC Code:** 22657-1 Alanine [Moles/volume] in Cerebral spinal fluid

**HIGH LAB RESULT:**
**NTR:** Increased alanine level in cerebral spinal fluid
**Parent:** NTR Abnormal alanine level in cerebral spinal fluid (Issue #4416)
**For LOINC Code:** 22657-1 Alanine [Moles/volume] in Cerebral spinal fluid
