### ISSUE TITLE
Positive blood antibiotic test

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#4350]
**NTR:** Positive blood antibiotic test

**Parent:** HP_0410172Blood xenobiotic'

**Note: ** There are several LOINC codes for various antibiotics. Or should this be a child of 'Elevated blood drug concentration'? See: https://github.com/obophenotype/human-phenotype-ontology/issues/4309

LOINC Code | High/Low | Label
-- | -- | --
3319-1 | High | Amikacin [Mass/volume] in Serum or Plasma --peak
3663-2 | High | Gentamicin [Mass/volume] in Serum or Plasma --peak
20578-1 | High | Vancomycin [Mass/volume] in Serum or Plasma
35670-9 | High | Tobramycin [Mass/volume] in Serum or Plasma

**Comment by pnrobinson** [comment]
I do not think we can annotate this at this time, as it is not an abnormal finding.
