### ISSUE TITLE
NTR: Increased circulating arachidate level

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#4351]
**NTR:** Increased circulating arachidate level
and abnormal, decreased

**Parent:** HP_0045016 Elevated Serum Long-Chain Fatty Acids

**For LOINC code:**
35169-2 Arachidate (C20:0) [Moles/volume] in Serum or Plasma

**Comment by pnrobinson** [comment]
This is a xenobiotic, correct? So we should probably not put it under Elevated Long-Chain Fatty Acids?
 @nicolevasilevsky

**Comment by nicolevasilevsky** [comment]
sure, we could classify as a child of 'Blood xenobiotic'

**Comment by pnrobinson** [comment]
I think this reflects dietary intake and is not an abnormal phenotype.
