### ISSUE TITLE
NTR: Abnormal/Increased/Decreased circulating band form neutrophils 

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#4353]
NTR: Abnormal/Increased/Decreased circulating band form neutrophils 

Parent: HP_0011991 'Abnormal neutrophil count'

For LOINC code:
26507-4 Band form neutrophils [#/volume] in Blood

**Comment by pnrobinson** [comment]
Please see new HPO terms (not release yet but in hp-edit)

**Comment by pnrobinson** [comment]
This is HP_0032239.
I do not think that the decreased form is used clinically?
I have added the synonym
