### ISSUE TITLE
NTR: Positive caffeine blood test

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#4354]
NTR: Positive caffeine blood test
Parent: HP_0410172	Blood xenobiotic'

For LOINC code:
3422-3 Caffeine [Mass/volume] in Serum or Plasma

**Comment by pnrobinson** [comment]
This is probably for overdose or therapeutic. This is not something we can easily represent in the HPO right now (it is not the case that a therapeutic level is NOT abnormal). I do not think we can map this at this time.
