### ISSUE TITLE
NTR: Elevated cancer Ag 19-9 level

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#4355]
NTR: Elevated cancer Ag 19-9 level
Parent: HP_0010876 Abnormal circulating protein level'

For LOINC code:
24108-3 Cancer Ag 19-9 [Units/volume] in Serum or Plasma

**Comment by pnrobinson** [comment]
This is a marker for pancreas cancer, see https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3244191/

**Comment by pnrobinson** [comment]
Ag 19-9 is not a protein, it is a carbohydrate that can be attached to proteins or lipids. It is not easy to classify but I put it under Abn circulating carbohydrate level.

**Comment by kingmanzhang** [comment]
done
