### ISSUE TITLE
NTR: Increased immunoreactive trypsinogen level

### ISSUE THREAD

**Issue by callahantiff** [obophenotype/human-phenotype-ontology#4356]
**NTR:** Increased immunoreactive trypsinogen level

**Parent:**  
HP_0012379 Abnormal enzyme/coenzyme activity

**For LOINC code:** 
3067-6 Trypsinogen I Free [Mass/​volume] in Serum or Plasma

**Biocurator ID for loinc2hpo:**  UCDenver:tjcallahan

**Comment by pnrobinson** [comment]
I think this is not an activity it is a concentration?

**Comment by callahantiff** [comment]
I investigated this term in my database and found it is mapped to the referenced LOINC code also to a SNOMED CT code. I think the SNOMED code right be more accurate.

The SNOMED code,  [428742001: Increased immunoreactive trypsinogen level (finding)](https://phinvadsstg.cdc.gov/vads/ViewCodeSystemConcept.action?oid=2.16.840.1.113883.6.96&code=428742001) has parent terms:
  - [Finding of enzyme level (finding) {365767001 , SNOMED CT}](https://phinvadsstg.cdc.gov/vads/ViewCodeSystemConcept.action?oid=2.16.840.1.113883.6.96&code=365767001)   
  - [Measurement finding above reference range (finding) {442756004 , SNOMED-CT }](https://phinvadsstg.cdc.gov/vads/ViewCodeSystemConcept.action?oid=2.16.840.1.113883.6.96&code=442756004)  

I see that when measured, it's an important component of the cystic fibrosis screening ([PMC2065933](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2065933/)). I do agree that it's likely a concentration, but doesn't it also measure activity? Specifically, activity related to the pancreatic ducts?

**Comment by pnrobinson** [comment]
Added as HP_0032493 @callahantiff
