### ISSUE TITLE
NTR: Increased circulating hexadecadienoate level

### ISSUE THREAD

**Issue by callahantiff** [obophenotype/human-phenotype-ontology#4357]
**NTR:** Increased circulating hexadecadienoate level

**Parent:** 
HP_0045016 Elevated Serum Long-Chain Fatty Acids

**For LOINC code:**
35154-4 Hexadecadienoate (C16:2) [Moles/volume] in Serum or Plasma

**Biocurator ID for loinc2hpo:**  UCDenver:tjcallahan

**Comment by pnrobinson** [comment]
As far as I know, this does not have abnormal medical phenotypes, e.g., http://www.hmdb.ca/metabolites/HMDB0031050
