### ISSUE TITLE
NTR: Increased circulating globulin level

### ISSUE THREAD

**Issue by callahantiff** [obophenotype/human-phenotype-ontology#4358]
**NTR:** Increased circulating globulin level

**Parent:**
HP_0032179 Abnormal circulating globulin level

**For LOINC code:**
2336-6 Globulin [Mass/volume] in Serum

**Biocurator ID for loinc2hpo:**  UCDenver:tjcallahan

**Comment by pnrobinson** [comment]
also added decreased term

**Comment by callahantiff** [comment]
Great! Both terms will be included with the next LOINC2HPO submission.
