### ISSUE TITLE
NTR: Increased circulating hexadecenoate level

### ISSUE THREAD

**Issue by callahantiff** [obophenotype/human-phenotype-ontology#4359]
**NTR:** Increased circulating hexadecenoate level

**Parent:**
HP_0045016 Elevated Serum Long-Chain Fatty Acids

**For LOINC code:**
35155-1 Hexadecenoate (C16:1w9) [Moles/volume] in Serum or Plasma

**Biocurator ID for loinc2hpo:**  UCDenver:tjcallahan

**Comment by pnrobinson** [comment]
There does not seem to be an abnormally increased level of this metabolite, which at least in part comes from diet. Thus, we cannot represent it in HPO. Please reopen if indicated.
