### ISSUE TITLE
NTR: Granulocytosis

### ISSUE THREAD

**Issue by callahantiff** [obophenotype/human-phenotype-ontology#4363]
**NTR:** Granulocytosis

**Parent:**
HP_0001911 Abnormal Granulocyte Morphology

**For LOINC code:**
53115-2 Immature granulocytes [#/volume] in Blood by Automated count

**Biocurator ID for loinc2hpo:**  UCDenver:tjcallahan

**Comment by pnrobinson** [comment]
Note there are some new terms for immature granulocytes that are not released yet.

**Comment by pnrobinson** [comment]
Adding Granulocytosis (HP_0032310)
@callahantiff  Note that Granulocytosis means an increased count of granulocytes, and is not talking about immature granulocytes. We are working on terms for increased immature granulocytes in the peripheral circulation.

**Comment by callahantiff** [comment]
Great! This will be included with the next LOINC2HPO submission, but only for labs that reference granulocytes (not immature granulocytes, as you mentioned).

I also saw that you added **Abnormal granulocyte count**. I will use the negated form of this term to annotate a normal result on the same lab test.
