### ISSUE TITLE
NTR: Positive lithium blood test

### ISSUE THREAD

**Issue by callahantiff** [obophenotype/human-phenotype-ontology#4365]
**NTR:** Positive lithium blood test

**Parent:**
HP_0410172 Blood xenobiotic

**For LOINC code:**
14334-7 Lithium [Moles/volume] in Serum or Plasma

**Biocurator ID for loinc2hpo:**  UCDenver:tjcallahan

**Comment by pnrobinson** [comment]
I think that this test is used to determine therapeutic ranges and overdose of lithium treatment. Currently the HPO cannot represent a "therapeutic range" for lithium treatment. I do not think that a positive test alone makes much sense. I will close this for now.

**Comment by callahantiff** [comment]
OK, that makes sense to me. Thank you for considering.
