### ISSUE TITLE
NTR: Increased circulating mead acid level 

### ISSUE THREAD

**Issue by callahantiff** [obophenotype/human-phenotype-ontology#4366]
**NTR:** Increased circulating mead acid level 

**Parent:**
HP_0045016 Elevated Serum Long-Chain Fatty Acids

**For LOINC code:**
35172-6 Mead acid (C20:3w9) [Moles/volume] in Serum or Plasma

**Biocurator ID for loinc2hpo:**  UCDenver:tjcallahan

**Comment by pnrobinson** [comment]
see https://pubchem.ncbi.nlm.nih.gov/compound/mead_acid

**Comment by callahantiff** [comment]
Thanks for the link! Are you suggesting that a better parent term for this lab would be [HP:0004354: Abnormality of carboxylic acid metabolism](https://hpo.jax.org/app/browse/term/HP:0004354)?

**Comment by pnrobinson** [comment]
Adding as HP_0020148 @callahantiff

**Comment by pnrobinson** [comment]
added
