### ISSUE TITLE
NTR: Increased circulating myristoleate level

### ISSUE THREAD

**Issue by callahantiff** [obophenotype/human-phenotype-ontology#4367]
**NTR:** Increased circulating myristoleate level

**Parent:**
HP_0045016 Elevated Serum Long-Chain Fatty Acids

**For LOINC code:**
35158-5 Myristoleate (C14:1) [Moles/volume] in Serum or Plasma

**Biocurator ID for loinc2hpo:**  UCDenver:tjcallahan

**Comment by pnrobinson** [comment]
added as HP_0025628 @callahantiff @kingmanzhang

**Comment by kingmanzhang** [comment]
done
