### ISSUE TITLE
NTR: Increased circulating octadecanoate level

### ISSUE THREAD

**Issue by callahantiff** [obophenotype/human-phenotype-ontology#4368]
**NTR:** Increased circulating octadecanoate level

**Parent:**
HP_0045016 Elevated Serum Long-Chain Fatty Acids

**For LOINC code:**
35149-4 Octadecanoate (C18:0) [Moles/volume] in Serum or Plasma

**Biocurator ID for loinc2hpo:**  UCDenver:tjcallahan

**Comment by pnrobinson** [comment]
added as HP_0025627 @callahantiff @kingmanzhang

**Comment by kingmanzhang** [comment]
done
