### ISSUE TITLE
NTR: Increased circulating oleate level

### ISSUE THREAD

**Issue by callahantiff** [obophenotype/human-phenotype-ontology#4369]
**NTR:** Increased circulating oleate level

**Parent:**
HP_0045016 Elevated Serum Long-Chain Fatty Acids

**For LOINC code:**
35166-8 Oleate (C18:1w9) [Moles/volume] in Serum or Plasma

**Biocurator ID for loinc2hpo:**  UCDenver:tjcallahan

**Comment by pnrobinson** [comment]
added as HP_0025626 @callahantiff @kingmanzhang

**Comment by kingmanzhang** [comment]
done
