### ISSUE TITLE
NTR: Increased circulating omega 3 fatty acid level

### ISSUE THREAD

**Issue by callahantiff** [obophenotype/human-phenotype-ontology#4370]
**NTR:** Increased circulating omega 3 fatty acid level

**Parent:**
HP_0045016 Elevated Serum Long-Chain Fatty Acids

**For LOINC code:**
35178-3 Omega 3 fatty acids (w3) [Moles/volume] in Serum or Plasma

**Biocurator ID for loinc2hpo:**  UCDenver:tjcallahan

**Comment by pnrobinson** [comment]
this is a trait (response to ingestion) and not an abnormality, we cannot annotate this in HPO currently.
