### ISSUE TITLE
NTR: Increased circulating palmitate level

### ISSUE THREAD

**Issue by callahantiff** [obophenotype/human-phenotype-ontology#4371]
**NTR:** Increased circulating palmitate level

**Parent:**
HP_0045016 Elevated Serum Long-Chain Fatty Acids

**For LOINC code:**
35161-9 Palmitate (C16:0) [Moles/volume] in Serum or Plasma

**Biocurator ID for loinc2hpo:**  UCDenver:tjcallahan

**Comment by pnrobinson** [comment]
adding as HP_0032462 @callahantiff

**Comment by callahantiff** [comment]
Thank you very much @pnrobinson!
