### ISSUE TITLE
NTR: Increased circulating palmitoleate level

### ISSUE THREAD

**Issue by callahantiff** [obophenotype/human-phenotype-ontology#4372]
**INR:** Increased circulating palmitoleate level

**Parent:**
HP_0045016 Elevated Serum Long-Chain Fatty Acids

**For LOINC code:**
35162-7 Palmitoleate (C16:1w7) [Moles/volume] in Serum or Plasma

**Biocurator ID for loinc2hpo:**  UCDenver:tjcallahan

**Comment by pnrobinson** [comment]
I do not think that this would lead to an abnoral HPO pehnotype term, see e.g., https://www.sciencedirect.com/topics/agricultural-and-biological-sciences/palmitoleic-acid
