### ISSUE TITLE
NTR: Increased circulating procalcitonin level

### ISSUE THREAD

**Issue by callahantiff** [obophenotype/human-phenotype-ontology#4373]
**INR:** Increased circulating procalcitonin level

**Parent:**
HP_0100530 Abnormality level of calcium-phosphate regulating hormone

**For LOINC code:**
33959-8 Procalcitonin [Mass/volume] in Serum or Plasma

**Biocurator ID for loinc2hpo:**  UCDenver:tjcallahan

**Comment by pnrobinson** [comment]
Def: An elevated concentration of procalcitonin in the blood circulation
Comment:Procalcitonin is a 116 amino acid peptide that has an approximate MW of 14.5 kDa and belongs to the calcitonin (CT) superfamily of peptides. It can be divided into 3 sections including the amino terminus of the PCT region, immature calcitonin, and calcitonin carboxyl-terminus peptide-1 (CCP-1). Procalcitonin is encoded by CALC-1 gene located on chromosome 11. Cleavage in 1 site of the primary transcript of CALC-1 gene produces pre-PCT, which further undergoes proteolytic cleavage of its signal sequence to produce PCT. The synthesized PCT then undergoes post-translational processing to produce small peptides and mature CT. PCT is a biomarker that exhibits greater specificity than other proinflammatory markers (eg, cytokines) in identifying patients with sepsis and can be used in the diagnosis of bacterial infections. PMID:28794881

**Comment by pnrobinson** [comment]
Note--PCT is not normally present at detectable levels and thus there is no need for a too low term

**Comment by callahantiff** [comment]
Great! This will be included with the next LOINC2HPO submission.

Just to confirm, since we have the results, I should mark both a **low** and **normal** result (as you noted low results on this lab are normal) should be annotated to **NOT** Increased circulating procalcitonin level?
