### ISSUE TITLE
NTR: Positive salicylic acid blood test

### ISSUE THREAD

**Issue by callahantiff** [obophenotype/human-phenotype-ontology#4374]
**INR:** Positive salicylic acid blood test

**Parent:**
HP_0410172 Blood xenobiotic

**For LOINC code:**
4024-6 Salicylates [Mass/volume] in Serum or Plasma

**Biocurator ID for loinc2hpo:**  UCDenver:tjcallahan

**Comment by pnrobinson** [comment]
Should this perhaps be Increased? If somebody takes one aspirin this is not worrisome and I think this test is mainly used for suspected overdose. @callahantiff

**Comment by callahantiff** [comment]
That's a great point, increased would be a much better fit for this.

**Comment by pnrobinson** [comment]
I am also thinking that this is difficult to put into the HPO at the present time since there is really no "normal level" -- let's hold off for now.
