### ISSUE TITLE
NTR: Increased circulating tetradecadienoate level

### ISSUE THREAD

**Issue by callahantiff** [obophenotype/human-phenotype-ontology#4375]
**INR:** Increased circulating tetradecadienoate level

**Parent:**
HP_0045016 Elevated Serum Long-Chain Fatty Acids

**For LOINC code:**
35148-6 Tetradecadienoate (C14:2) [Moles/volume] in Serum or Plasma

**Biocurator ID for loinc2hpo:**  UCDenver:tjcallahan

**Comment by pnrobinson** [comment]
I cannot find an abnormal medical phenotype for this in the literature and so it is hard to create an HPO term for it. Please reopen if we can provide a definition and an example of relevant disease states. @callahantiff

**Comment by callahantiff** [comment]
> I cannot find an abnormal medical phenotype for this in the literature and so it is hard to create an HPO term for it. Please reopen if we can provide a definition and an example of relevant disease states. @callahantiff

OK, sounds good. I will do some digging and re-open again if I can find better evidence.
