### ISSUE TITLE
NTR: Positive brochodilator drug blood test

### ISSUE THREAD

**Issue by callahantiff** [obophenotype/human-phenotype-ontology#4376]
**INR:** Positive brochodilator drug blood test

**Parent:**
HP_0410172 Blood xenobiotic

**For LOINC code:**
4049-3 Theophylline [Mass/volume] in Serum or Plasma

**Biocurator ID for loinc2hpo:**  UCDenver:tjcallahan

**Comment by pnrobinson** [comment]
This is probably for overdose or therapeutic. This is not something we can easily represent in the HPO right now (it is not the case that a therapeutic level is NOT abnormal). I do not think we can map this at this time.
