### ISSUE TITLE
NTR: Decreased urine urobilinogen level

### ISSUE THREAD

**Issue by callahantiff** [obophenotype/human-phenotype-ontology#4377]
**INR:** Decreased urine urobilinogen level

**Parent:**
HP_0003110 Abnormality of Urine Homeostasis

**For LOINC code:**
3107-0 Urobilinogen [Mass/volume] in Urine

**Biocurator ID for loinc2hpo:**  UCDenver:tjcallahan

**Comment by callahantiff** [comment]
Requesting a small edit (see [LOINC2HPO Issue #98](https://github.com/TheJacksonLaboratory/loinc2hpoAnnotation/issues/98)):

**Normal results**
  - **NTR:** Abnormal urine urobilinogen
  - **Parent:** HP_0003110 Abnormality of Urine Homeostasis
  - **For LOINC code:** 3107-0 Urobilinogen [Mass/volume] in Urine

**Low results**
  - **NTR:** Decreased urine urobilinogen level
  - **Parent:** NTR Abnormal urine urobilinogen
  - **For LOINC code:** 3107-0 Urobilinogen [Mass/volume] in Urine

**High results** 
Existing term *HP:0031890 (Increased urine urobilinogen)* would then also become the child of Abnormal urine urobilinogen

**Comment by pnrobinson** [comment]
Added these terms, see HP_0032473 @callahantiff @kingmanzhang

**Comment by kingmanzhang** [comment]
done
