### ISSUE TITLE
NTR: Increased circulating vaccenate level

### ISSUE THREAD

**Issue by callahantiff** [obophenotype/human-phenotype-ontology#4378]
**INR:** Increased circulating vaccenate level

**Parent:**
HP_0045016 Elevated Serum Long-Chain Fatty Acids

**For LOINC code:**
35167-6 Vaccenate (C18:1w7) [Moles/volume] in Serum or Plasma

**Biocurator ID for loinc2hpo:**  UCDenver:tjcallahan

**Comment by pnrobinson** [comment]
@callahantiff what is the clinical utility of this? Is this a xenobiotic (from cow's milk?) Unsure how to define this.

**Comment by callahantiff** [comment]
From what I was able to find, it looks like this long chain amino acid has been linked to colorectal cancer in feces [HMDB](http://www.hmdb.ca/metabolites/HMDB0240219), but blood is more tricky and what I did find seemed to be related to monitoring levels of trans-fatty acids when there is concern of CVD ([1](https://www.sciencedirect.com/science/article/pii/S1043452610590016), [2](https://www.sciencedirect.com/science/article/pii/B9781630670368000020)). It has also been associated with increased risk of hip fracture [here](https://www.plefa.com/article/S0952-3278(16)30012-6/abstract).

**Comment by pnrobinson** [comment]
AS far as I can see this is a product of dairy foods. There is no clear "abnormally high level". We will need other means to represent this.
