### ISSUE TITLE
NTR: Increased circulating variant lymphocytes

### ISSUE THREAD

**Issue by callahantiff** [obophenotype/human-phenotype-ontology#4379]
**INR:** Increased circulating variant lymphocytes

**Parent:**
HP_0004332 Abnormal Lymphocyte Morphology

**For LOINC code:**
735-1 Variant lymphocytes/100 leukocytes in Blood by Manual count

**Biocurator ID for loinc2hpo:**  UCDenver:tjcallahan

**Comment by pnrobinson** [comment]
Se https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1995771/

**Comment by pnrobinson** [comment]
I think that if we really want to map this LOINC term them use just Abnormal Lymphocyte Morphology

There is no one abnormal cell type that maps to "Variant lymphocyte"  see below from the above article.

 A confused terminology is used for abnormal lymphocytes, for example, variant lymphocytes, atypical lymphocytes and even combinations of several cells are used (e.g. monocytoid lymphocytes and plasmacytoid lymphocytes). I
