### ISSUE TITLE
NTR: Increased zinc level in urine

### ISSUE THREAD

**Issue by callahantiff** [obophenotype/human-phenotype-ontology#4380]
**INR:** Increased zinc level in urine

**Parent:**
HP_0008277 Abnormality of Zinc Homeostasis

**For LOINC code:**
5765-3 Zinc [Mass/time] in 24 hour Urine

**Biocurator ID for loinc2hpo:**  UCDenver:tjcallahan

**Comment by pnrobinson** [comment]
adding as HP_0025639
