### ISSUE TITLE
NPR: Decreased circulating cholinesterase level

### ISSUE THREAD

**Issue by callahantiff** [obophenotype/human-phenotype-ontology#4383]
**NPR:** Decreased circulating cholinesterase level

**Parent**
HP_0010876 Abnormal circulating protein level

**For LOINC code:**
39354-6 Cholinesterase in Serum or Plasma --dibucaine/Cholinesterase

**Biocurator ID for loinc2hpo:** UCDenver:tjcallahan

**Comment by pnrobinson** [comment]
This is a difficult term because it is measuring two related enzymes
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3378013/

**Comment by pnrobinson** [comment]
adding as HP_0020175 @callahantiff

**Comment by pnrobinson** [comment]
done
