### ISSUE TITLE
NPR: Increased circulating docosahexaenoic acid level

### ISSUE THREAD

**Issue by callahantiff** [obophenotype/human-phenotype-ontology#4384]
**NPR:** Increased circulating docosahexaenoic acid level

**Parent**
HP_0008167 Very Long Chain Fatty Acid Accumulation

**For LOINC code:**
35174-2 Docosahexaenoate (C22:6w3) [Moles/volume] in Serum or Plasma

**Biocurator ID for loinc2hpo:** UCDenver:tjcallahan

**Comment by pnrobinson** [comment]
https://www.ncbi.nlm.nih.gov/pubmed/27426911

**Comment by pnrobinson** [comment]
@callahantiff I am unable to find a reference for "increased/decreased circulating docosahexaenoic acid level"
The amount in serum appears to depend on diet. I do not think we can annotate this at this time.
