### ISSUE TITLE
NPR: Increased circulating docosapentaenoic acid level

### ISSUE THREAD

**Issue by callahantiff** [obophenotype/human-phenotype-ontology#4385]
**NPR:** Increased circulating docosapentaenoic acid level

**Parent**
HP_0008167 Very Long Chain Fatty Acid Accumulation

**For LOINC code:**
35180-9 Docosapentaenate (C22:5w3) [Moles/volume] in Serum or Plasma

**Biocurator ID for loinc2hpo:** UCDenver:tjcallahan

**Comment by callahantiff** [comment]
This term would also be able to annotate: **LOINC 35181-7: Docosapentaenate (C22:5w6) [Moles/volume] in Serum or Plasma**

**Comment by pnrobinson** [comment]
I think this is also primarily a nutrient
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4467567/
There were a few articles about schizophrenia, but they seem erroneous (https://www.ncbi.nlm.nih.gov/pubmed/15179668) and I cannot find any clearly abnormal values for this metabolite. I will close this for now, please reopen if we can figure out that there is a clearly abnormal range for individuals.

**Comment by callahantiff** [comment]
> I think this is also primarily a nutrient
> https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4467567/
> There were a few articles about schizophrenia, but they seem erroneous (https://www.ncbi.nlm.nih.gov/pubmed/15179668) and I cannot find any clearly abnormal values for this metabolite. I will close this for now, please reopen if we can figure out that there is a clearly abnormal range for individuals.

I agree, I will keep looking for good resources. I will also run it by the pediatricians and pathologists on my team.
