### ISSUE TITLE
NPR: Increased circulating docosenoate level

### ISSUE THREAD

**Issue by callahantiff** [obophenotype/human-phenotype-ontology#4387]
**NPR:** Increased circulating docosenoate level

**Parent**
HP_0008167 Very Long Chain Fatty Acid Accumulation

**For LOINC code:**
35160-1 Docosenoate (C22:1) [Moles/volume] in Serum or Plasma

**Biocurator ID for loinc2hpo:** UCDenver:tjcallahan

**Comment by pnrobinson** [comment]
THis is present in some seeds. There is no "abnormally high" level of it that I am aware of. I do not think we can annotate this at this time.
