### ISSUE TITLE
NPR: Increased circulating eicosapentaenoate level

### ISSUE THREAD

**Issue by callahantiff** [obophenotype/human-phenotype-ontology#4388]
**NPR:** Increased circulating eicosapentaenoate level

**Parent**
HP_0008167 Very Long Chain Fatty Acid Accumulation

**For LOINC code:**
35173-4 Eicosapentaenoate (C20:5w3) [Moles/volume] in Serum or Plasma

**Biocurator ID for loinc2hpo:** UCDenver:tjcallahan

**Comment by pnrobinson** [comment]
also reduced, see https://jamanetwork.com/journals/jamapsychiatry/fullarticle/206794

**Comment by callahantiff** [comment]
With both increased and decreased levels of eicosapentaenoate, would we also want a new parent term for these? Something like Abnormal circulating eicosapentaenoate level?

**Comment by pnrobinson** [comment]
Actually this seems to be an exogenous fatty acid and it is unclear if there are truly abnormally low/high levels. I do not think we can annotate this.
