### ISSUE TITLE
NPR: Increased blood alcohol level

### ISSUE THREAD

**Issue by callahantiff** [obophenotype/human-phenotype-ontology#4389]
**NPR:** Increased blood alcohol level

**Parent**
HP_0410172 Blood xenobiotic

**For LOINC code:**
5643-2 Ethanol [Mass/volume] in Serum or Plasma

**Biocurator ID for loinc2hpo:** UCDenver:tjcallahan

**Comment by pnrobinson** [comment]
I am not sure if 'Increased' is the right term since 'normally' there is none...?

**Comment by callahantiff** [comment]
That's a very good point. I wonder if we could say "presence of alcohol in blood" or "alcohol detected in blood"?

**Comment by nicolevasilevsky** [comment]
Or 'Positive blood alcohol test'?

**Comment by pnrobinson** [comment]
Are there "normal" values for this? It will be hard to annotate in our framework if FHIR does not have this. Also, what is normal is very context dependent. I am not sure we should try to map this. @kingmanzhang

**Comment by callahantiff** [comment]
That's a good question. If it's helpful, I found the original article cited with the lab test [PMID3802510](https://www.ncbi.nlm.nih.gov/pubmed/3802510).

Looking closely at the labs, there is a reference range of 0-10 mg/dL provided.

**Comment by kingmanzhang** [comment]
Let's wait for the test with real EHR data. It looks more like a test by cops rather than doctors. We make a decision then.

**Comment by callahantiff** [comment]
This came from real EHR data, do you mean wait until you see it across multiple EHRs?

**Comment by kingmanzhang** [comment]
I hope to see whether this is frequently done. I think it is very context dependent: it could be a disease whether a hint is abnormal (https://en.wikipedia.org/wiki/Auto-brewery_syndrome), or a behavior where it is okay to have certain amount.

**Comment by callahantiff** [comment]
Great, sounds perfect.

**Comment by pnrobinson** [comment]
Definitely you would see blood alcohol tests in emergency rooms. Let's just put positive blood alcohol test and not worry about the exact level.

**Comment by kingmanzhang** [comment]
sounds good

**Comment by pnrobinson** [comment]
After some deliberation, we think that this trait probably should be encoded elsewhere and not as an HPO term.
