### ISSUE TITLE
NPR: Increased urine alcohol level

### ISSUE THREAD

**Issue by callahantiff** [obophenotype/human-phenotype-ontology#4390]
**NPR:** Increased urine alcohol level

**Parent**
HP_0031840 Urine xenobiotic

**For LOINC code:**
5645-7 Ethanol [Mass/volume] in Urine

**Biocurator ID for loinc2hpo:** UCDenver:tjcallahan

**Comment by pnrobinson** [comment]
this is a trait (response to ingestion) and not an abnormality, we cannot annotate this in HPO currently.
