### ISSUE TITLE
NPR: Decreased circulating globulin level

### ISSUE THREAD

**Issue by callahantiff** [obophenotype/human-phenotype-ontology#4393]
**NPR:** Decreased circulating globulin level

**Parent**
HP_0032179 Abnormal circulating globulin level

**For LOINC code:**
2336-6 Globulin [Mass/volume] in Serum

**Biocurator ID for loinc2hpo:** UCDenver:tjcallahan

**Comment by callahantiff** [comment]
Referenced parent term [here](https://github.com/obophenotype/human-phenotype-ontology/issues/4214)

**Comment by pnrobinson** [comment]
This is HP_0032312

**Comment by callahantiff** [comment]
Thanks!
