### ISSUE TITLE
human phenotype ontology is spelled lower case in OBO metadata

### ISSUE THREAD

**Issue by matentzn** [obophenotype/human-phenotype-ontology#4396]
as you can see [here](https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/ontology/hp.md), human phenotype ontology is spelt lowercase.

This makes shows for example in [OLS](https://www.ebi.ac.uk/ols/ontologies/hp) where all other ontologies are typically written with capital first letters.

If you want me to change 
human phenotype ontology 
to
Human Phenotype Ontology in the OBO foundry metadata, let me know.

**Comment by drseb** [comment]
Thanks. I created a PR and revised other fields as well: https://github.com/OBOFoundry/OBOFoundry.github.io/pull/827
