### ISSUE TITLE
Add HPO term for Interhemispheric cyst 

### ISSUE THREAD

**Issue by GenomeDeb** [obophenotype/human-phenotype-ontology#4398]
_For new term requests, please provide us with the following information:_
### 1. Preferred term label
Interhemispheric Cyst

### 3. Textual definition (should be understandable even for non-specialists, please include a PubMed ID for relevant articles providing additional information about the suggestion)
A fluid filled cyst located between the brain hemispheres.  

### 5. Which diseases are characterized by this term ? (e.g. Orphanet- or OMIM-id)
Associated with agenesis of corpus callosum. Found with some syndromic conditions such as orofacial digital syndrome Type 1. 

### 6. Your nano-attribution (ORCID-id or label, e.g. _HPO:probinson_ (organization:name))
Deb Ritter

**Comment by pnrobinson** [comment]
This is the corresponding UBERON term
https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0002921
Therefore, I will put this term under Abnormal subarachnoid space morphology

**Comment by pnrobinson** [comment]
Adding term as HP:0032327
