### ISSUE TITLE
Change placement of term: urticaria

### ISSUE THREAD

**Issue by MorganSimiluk** [obophenotype/human-phenotype-ontology#4402]
Urticaria is currently listed under cardiovascular.  I do not know the rationale for this.  If this is an error, can we move urticaria under cutaneous?

**Comment by pnrobinson** [comment]
Urticaria has multiple parentage, but its direct parent is Vascular skin abnormality
https://hpo.jax.org/app/browse/term/HP:0011276
which in turn is both a Generalized abnormality of the skin and an Abnormality of he vasculature.

The skin section of the HPO needs work overall, but the reason for the placement under cardiovasculature is that urticaria is a vascular skin abnormality...

**Comment by MorganSimiluk** [comment]
Okay, thanks. I already let the requesting physician know about the multiple parentage issue, which I think largely resolved the concern.

Sent from my iPhone

On Feb 15, 2019, at 5:15 PM, Peter Robinson <notifications@github.com<mailto:notifications@github.com>> wrote:


Urticaria has multiple parentage, but its direct parent is Vascular skin abnormality
https://hpo.jax.org/app/browse/term/HP:0011276
which in turn is both a Generalized abnormality of the skin and an Abnormality of he vasculature.

The skin section of the HPO needs work overall, but the reason for the placement under cardiovasculature is that urticaria is a vascular skin abnormality...
