### ISSUE TITLE
Four definitions clearly copy-pasted, need content

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#4406]
Please revise the definitions of:

- [x] HP:0010052 (Abnormality of the proximal phalanx of the hallux)
- [x] HP:0010035 (Aplasia of the 1st metacarpal)
- [x] HP:0010034 (Short 1st metacarpal)
- [x] HP:0009618 (Abnormality of the proximal phalanx of the thumb)

**Comment by pnrobinson** [comment]
I have tried to make the definitions more expressive and clear.
