### ISSUE TITLE
Error processing OBO file: "created-by" not supported

### ISSUE THREAD

**Issue by julie-sullivan** [obophenotype/human-phenotype-ontology#4408]
Hello!! I downloaded the new OBO file and got this error from the library I am using:

```
Error: Attempted to set created-by field of object which does not support modification metadata.
on line: 17 of file:/data/hpo/2019-02-13/hp.obo
charnum: -1
line: created_by: Sebastian Köhler, Peter Robinson, The Human Phenotype Ontology Consortium, Monarch Initiative
```

I double checked, and it looks like `created-by` is not supported by the [specifications](http://owlcollab.github.io/oboformat/doc/GO.format.obo-1_2.html).

Was this an accidental inclusion? Or is this line something I'd have to remove post-download?

Thank you for such a great ontology!!

**Comment by drseb** [comment]
According to this it is allowed (at least for classes) https://owlcollab.github.io/oboformat/doc/GO.format.obo-1_4.html

I moved our dc:creator annotations to created_by, but maybe this wasn't a good idea. 
@cmungall we discussed this before and we tried to get rid of dc-creator. Do you think the current solution is wrong? I would then bring the dc-creator and dc-contributor tags back.

@julie-sullivan , this would be fixed in the next release. sorry for any inconvenience.

**Comment by julie-sullivan** [comment]
Wow thanks for the super-fast response! No worries, I appreciate your attention!

**Comment by cmungall** [comment]
The spec should be used over the guide:

http://owlcollab.github.io/oboformat/doc/obo-syntax.html

but `created_by` is allowed in both, for terms

I think line 17 is in the header:

```
logical-definition-view-relation: has_part
created_by: Sebastian Köhler, Peter Robinson, The Human Phenotype Ontology Consortium, Monarch Initiative

[Term]
```

I wouldn't recommend this. Use dc:author and dc:contributor in the ontology header

**Comment by cmungall** [comment]
Now I read again it looks like your error message is for `created-by` (with a hyphen). This is indeed an error. The field should use underscore.

This must have been a transient error, as it's gone:

```
curl -s -L http://purl.obolibrary.org/obo/hp.obo | grep created-by
```

**Comment by drseb** [comment]
No. I think the line it is trying to parse uses underscore. It is just in the error message that it is shown with hyphen. I will fix this and it should be gone in the next release. Sorry, we were removing all the dc-creator tags for the ontology-classes. Then I went too far and removed it also from the header.
