### ISSUE TITLE
Copy-paste errors in definitions

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#4410]
The following classes have the same definition, none of which actually explains the specific abnormality:

- HP:0009676 (Bracket epiphysis of the distal phalanx of the thumb)
- HP:0009665 (Bracket epiphysis of the proximal phalanx of the thumb)
- HP:0009503 (Bracket epiphysis of the distal phalanx of the 2nd finger)
- HP:0009347 (Bracket epiphysis of the proximal phalanx of the 3rd finger)
- HP:0009336 (Bracket epiphysis of the distal phalanx of the 3rd finger)
- HP:0009322 (Bracket epiphysis of the middle phalanx of the 3rd finger)
- HP:0009262 (Bracket epiphysis of the proximal phalanx of the 4th finger)
- HP:0009251 (Bracket epiphysis of the distal phalanx of the 4th finger)
- HP:0009215 (Bracket epiphysis of the middle phalanx of the 4th finger)
- HP:0009204 (Bracket epiphysis of the middle phalanx of the 5th finger)
- HP:0009197 (Bracket epiphysis of the proximal phalanx of the 5th finger)
- HP:0009187 (Bracket epiphysis of the distal phalanx of the 5th finger)

The definition is:

> The epiphysis is normally located on the proximal surface of the phalanges. Bracket epiphysis refers to an abnormality in which the epiphysis surrounds the phalanx, having a bracket-like form and reaching from the proximal side of the phalanx to the distal side

Is this intended?

**Comment by pnrobinson** [comment]
This seems to be have been corrected. The new definitions are great, thanks!

**Comment by drseb** [comment]
Ok great. Thanks
