### ISSUE TITLE
Add lung function test abnormalities

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#4411]
See Tiffany's spread sheet for corresponding LOINC terms

**Comment by pnrobinson** [comment]
https://www.aafp.org/afp/2014/0301/p359.html

**Comment by pnrobinson** [comment]
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3229853/

**Comment by pnrobinson** [comment]
Added some terms. See subhierarchy around HP_0030878

**Comment by kingmanzhang** [comment]
@callahantiff Where is your spreadsheet?

**Comment by callahantiff** [comment]
All of the terms have been added, we should be good to go and able to close this issue:

LOINC | RESULT | LOINC LABEL | HPO ID | HPO LABEL | ISSUE
-- | -- | -- | -- | -- | --
69973-6 | Low | FEF 25-75% --post bronchodilation | HP:0032361 | Decreased post bronchodilator forced expiratory flow 25-75% | Issue #4461
69972-8 | Low | FEF 25-75% --pre bronchodilation | HP:0032360 | Decreased pre bronchodilator forced expiratory flow 25-75% | Issue #4462
69971-0 | Low | FEF 25-75% Predicted | HP:0032359 | Decreased forced expiratory flow 25-75% | Issue #4463
20150-9 | Low | FEV1 | HP:0032342 | Reduced forced expiratory volume in one second | Issue #4464
20155-8 | Low | FEV1 --post bronchodilation | HP:0032358 | Decreased post bronchodilator forced expiratory volume in one second | Issue #4465
19870-5 | Low | Forced vital capacity [Volume] Respiratory system | HP:0032341 | Reduced forced vital capacity | Issue #4466
19875-4 | Low | Forced vital capacity [Volume] Respiratory system --post bronchodilation | HP:0032357 | Decreased post bronchodilator forced vital capacity | Issue #4467
19877-0 | Low | Forced vital capacity [Volume] Respiratory system --pre bronchodilation | HP:0032356 | Decreased pre bronchodilator forced vital capacity | Issue #4468
19935-6 | Low | Maximum expiratory gas flow Respiratory system airway by Peak flow meter | HP:0032355 | Decreased peak expiratory flow | Issue #4469

**Comment by kingmanzhang** [comment]
Great! I will treated this as solved issue.

**Comment by kingmanzhang** [comment]
I correct some mappings by removing mapping "H" to NOT "Decreased ...". I still think we should rely on labs providing the correct normal range (in this case, below one threshold is "L", above it is "N"; no "abnormally high").
