### ISSUE TITLE
'during' is not a correct relation

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#4413]
need to fix def:

```
'has part' some 
('increased volume' and ('inheres in' some 'amniotic fluid') and ('has modifier' some abnormal) and (during some 'female pregnancy'))
```

needs to use https://www.ebi.ac.uk/ols/ontologies/ro/properties?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0002092

cc @matentzn

**Comment by drseb** [comment]
This is the def of HP:0001561

**Comment by matentzn** [comment]
Done: https://github.com/obophenotype/human-phenotype-ontology/pull/4574/files
