### ISSUE TITLE
NTR: Increased CSF albumin

### ISSUE THREAD

**Issue by callahantiff** [obophenotype/human-phenotype-ontology#4414]
**NTR:** Increased CSF albumin

**Parent:**
HP_0025456 Abnormal CSF protein level

**For LOINC Code:**
1746-7 Albumin [Mass/volume] in Cerebral spinal fluid

**Biocurator ID for loinc2hpo:** UCDenver:tjcallahan

**Comment by pnrobinson** [comment]
@callahantiff I think that CSF albumin in isolation is not an interesting quantity but rather it is used to calculate some ratios, e.g., https://www.ncbi.nlm.nih.gov/pubmed/26476775
If this is the case, then we might have something that is difficult to capture from the LOINC test using our current setup.
