### ISSUE TITLE
NTR: Abnormal CSF amino acid level

### ISSUE THREAD

**Issue by callahantiff** [obophenotype/human-phenotype-ontology#4415]
**NTR:** Abnormal CSF amino acid level

**Parent:**
HP_0002921 Abnormality of the Cerebrospinal Fluid

**For LOINC Code:** NA, see note

**Biocurator ID for loinc2hpo:** UCDenver:tjcallahan

**NOTE:** Adding a new concept to help organize the amino acid CSF labs

**Comment by pnrobinson** [comment]
added as HP:0032364
