### ISSUE TITLE
NTR: Increased aspartic acid level in cerebral spinal fluid

### ISSUE THREAD

**Issue by callahantiff** [obophenotype/human-phenotype-ontology#4421]
**NTR:** Increased aspartic acid level in cerebral spinal fluid

**Parent:**
NTR Abnormal CSF amino acid level (Issue #4415)

**For LOINC Code:**
22655-5 Aspartate [Moles/volume] in Cerebral spinal fluid

**Biocurator ID for loinc2hpo:** UCDenver:tjcallahan

**SOURCE:** https://www.questdiagnostics.com/testcenter/testguide.action?dc=TS_AminAcidAnal

**Comment by LCCarmody** [comment]
@drseb Could you MIREOT a few terms for some of these amino acid terms.
aspartate family amino acid
http://purl.obolibrary.org/obo/CHEBI_22658

L-aspartic acid
http://purl.obolibrary.org/obo/CHEBI_17053 

L-asparagine
http://purl.obolibrary.org/obo/CHEBI_17196

Thanks.

**Comment by LCCarmody** [comment]
@drseb Could you also MIREOT the following:
pyruvate family amino acid  CHEBI:26463
http://purl.obolibrary.org/obo/CHEBI_26463

homocarnosine
http://purl.obolibrary.org/obo/CHEBI_28050

alpha-aminobutyrate
http://purl.obolibrary.org/obo/CHEBI_86508

Thanks.

**Comment by drseb** [comment]
I have to wait until we have the new ODK running. Sorry.

**Comment by LCCarmody** [comment]
That's okay. Just wanted this ticket open to remember this. Let me know whenever it is done.
