### ISSUE TITLE
NTR: Increased glutamic acid level in cerebral spinal fluid

### ISSUE THREAD

**Issue by callahantiff** [obophenotype/human-phenotype-ontology#4423]
**NTR:** Increased glutamic acid level in cerebral spinal fluid

**Parent:**
NTR Abnormal CSF amino acid level (Issue #4415)

**For LOINC Code:**
22652-2 Glutamate [Moles/volume] in Cerebral spinal fluid

**Biocurator ID for loinc2hpo:** UCDenver:tjcallahan

**SOURCE:** https://www.questdiagnostics.com/testcenter/testguide.action?dc=TS_AminAcidAnal

**Comment by callahantiff** [comment]
I think this somehow got combined with annotations for Glutamate, but there should be separate annotations to glutamate and glutamic acid. Unless we are considering these the same?

**Comment by LCCarmody** [comment]
Since glutamate is glutamic acid + sodium, I am considering them the same and used synonyms to express this.  They are often used interchangeably for tests in CSF.  Do we have any experts in the area who can weigh in?

@pnrobinson

**Comment by pnrobinson** [comment]
I think that glutamate and glutamic acid are used interchangeably in medical contexts. I am not aware of any difference in the CSF measures and so we could add synonyms

**Comment by callahantiff** [comment]
OK, that works for me. I just wanted to double-check. Thank you both!
