### ISSUE TITLE
NTR: Decreased circulating corticosterone level

### ISSUE THREAD

**Issue by callahantiff** [obophenotype/human-phenotype-ontology#4459]
**NTR:** Decreased circulating corticosterone level

**Parent:**
HP:0012112 Abnormality of circulating corticosterone Level

**For LOINC Code:**
87385 Corticosterone [Mass/volume] in Serum or Plasma

**Biocurator ID for loinc2hpo:** UCDenver:tjcallahan

**SOURCE:** https://endocrinology.testcatalog.org/show/CORTC

**Comment by pnrobinson** [comment]
adding as HP_0032363. @callahantiff @kingmanzhang

**Comment by kingmanzhang** [comment]
done
but for a different loinc code. 87385 is not valid.
