### ISSUE TITLE
NTR: Increased circulating corticosterone level

### ISSUE THREAD

**Issue by callahantiff** [obophenotype/human-phenotype-ontology#4460]
**NTR:** Increased circulating corticosterone level

**Parent:**
HP:0012112 Abnormality of circulating corticosterone Level

**For LOINC Code:**
87385 Corticosterone [Mass/volume] in Serum or Plasma

**Biocurator ID for loinc2hpo:** UCDenver:tjcallahan

**SOURCE:** https://endocrinology.testcatalog.org/show/CORTC

**Comment by pnrobinson** [comment]
adding term HP_0032362 @callahantiff @kingmanzhang
