### ISSUE TITLE
NTR: Decreased post bronchodilator forced expiratory flow 25-75%

### ISSUE THREAD

**Issue by callahantiff** [obophenotype/human-phenotype-ontology#4461]
**NTR:** Decreased post bronchodilator forced expiratory flow 25-75%

**Parents:**
HP:0030878 Abnormality on pulmonary function testing
HP:0030877 Obstructive deficit on pulmonary function testing

**Synonyms:** Decreased post bronchodilator FEF 25-75%

**For LOINC Code:**
69973-6 FEF 25-75% --post bronchodilation

**Biocurator ID for loinc2hpo:** UCDenver:tjcallahan

**SOURCE:** https://www.aafp.org/afp/2014/0301/p359.html

**Comment by pnrobinson** [comment]
adding HP_0032361 @callahantiff @kingmanzhang

**Comment by kingmanzhang** [comment]
done
