### ISSUE TITLE
NTR: Decreased pre bronchodilator forced expiratory flow 25-75%

### ISSUE THREAD

**Issue by callahantiff** [obophenotype/human-phenotype-ontology#4462]
**NTR:** Decreased pre bronchodilator forced expiratory flow 25-75%

**Parent:**
HP:0030878 Abnormality on pulmonary function testing

**Synonyms:** Decreased pre bronchodilator FEF 25-75%

**For LOINC Code:**
69972-8 FEF 25-75% --pre bronchodilation

**Biocurator ID for loinc2hpo:** UCDenver:tjcallahan

**SOURCE:** https://www.aafp.org/afp/2014/0301/p359.html

**Comment by pnrobinson** [comment]
added HP_0032360 @callahantiff @kingmanzhang

**Comment by kingmanzhang** [comment]
done
