### ISSUE TITLE
NTR: Decreased predicted forced expiratory flow 25-75%

### ISSUE THREAD

**Issue by callahantiff** [obophenotype/human-phenotype-ontology#4463]
**NTR:** Decreased predicted forced expiratory flow 25-75%

**Parent:**
HP:0030878 Abnormality on pulmonary function testing

**Synonyms:** Decreased predicted FEF 25-75%

**For LOINC Code:**
69971-0 FEF 25-75% Predicted

**Biocurator ID for loinc2hpo:** UCDenver:tjcallahan

**SOURCE:** https://www.aafp.org/afp/2014/0301/p359.html

**Comment by pnrobinson** [comment]
I do not think the word "predicted" belongs in the term label. It is a decreased compared to predicted that is being tested.

**Comment by pnrobinson** [comment]
adding as HP_0032359 @callahantiff @kingmanzhang

**Comment by kingmanzhang** [comment]
done
