### ISSUE TITLE
NTR: Decreased forced expiratory volume in one second

### ISSUE THREAD

**Issue by callahantiff** [obophenotype/human-phenotype-ontology#4464]
**NTR:** Decreased forced expiratory volume in one second

**Parent:**
HP:0030878 Abnormality on pulmonary function testing

**Synonyms:** Decreased FEV1

**For LOINC Code:**
20150-9 FEV1

**Biocurator ID for loinc2hpo:** UCDenver:tjcallahan

**SOURCE:** https://www.aafp.org/afp/2014/0301/p359.html

**Comment by callahantiff** [comment]
Looks like this was already added #4411?

**Comment by pnrobinson** [comment]
Yeah, I already started with a few terms, but your new suggestions are spot on and we should add them to the same subhierarchy

**Comment by pnrobinson** [comment]
already added!
