### ISSUE TITLE
NTR: Decreased post bronchodilator forced expiratory volume in one second

### ISSUE THREAD

**Issue by callahantiff** [obophenotype/human-phenotype-ontology#4465]
**NTR:** Decreased post bronchodilator forced expiratory volume in one second

**Parent:**
HP:0030878 Abnormality on pulmonary function testing

**Synonyms:** Decreased post bronchodilator FEV1

**For LOINC Code:**
20155-8 FEV1 --post bronchodilation

**Biocurator ID for loinc2hpo:** UCDenver:tjcallahan

**SOURCE:** https://www.aafp.org/afp/2014/0301/p359.html

**Comment by pnrobinson** [comment]
added term as HP_0032358 @callahantiff @kingmanzhang

**Comment by kingmanzhang** [comment]
done
