### ISSUE TITLE
NTR: Decreased forced vital capacity

### ISSUE THREAD

**Issue by callahantiff** [obophenotype/human-phenotype-ontology#4466]
**NTR:** Decreased forced vital capacity

**Parent:**
HP:0030878 Abnormality on pulmonary function testing

**Synonyms:** Decreased FVC

**For LOINC Code:**
19870-5 Forced vital capacity [Volume] Respiratory system

**Biocurator ID for loinc2hpo:** UCDenver:tjcallahan

**SOURCE:** https://www.aafp.org/afp/2014/0301/p359.html

**Comment by callahantiff** [comment]
Looks like this was already added #4411?

**Comment by pnrobinson** [comment]
already added! HP_0032341
