### ISSUE TITLE
NTR: Decreased post bronchodilator forced vital capacity

### ISSUE THREAD

**Issue by callahantiff** [obophenotype/human-phenotype-ontology#4467]
**NTR:** Decreased post bronchodilator forced vital capacity

**Parent:**
HP:0030878 Abnormality on pulmonary function testing

**Synonyms:** Decreased post bronchodilator FVC

**For LOINC Code:**
19875-4 Forced vital capacity [Volume] Respiratory system --post bronchodilation

**Biocurator ID for loinc2hpo:** UCDenver:tjcallahan

**SOURCE:** https://www.aafp.org/afp/2014/0301/p359.html

**Comment by pnrobinson** [comment]
added as HP_0032357 @callahantiff @kingmanzhang

**Comment by kingmanzhang** [comment]
done
