### ISSUE TITLE
NTR: Decreased pre bronchodilator forced vital capacity

### ISSUE THREAD

**Issue by callahantiff** [obophenotype/human-phenotype-ontology#4468]
**NTR:** Decreased pre bronchodilator forced vital capacity

**Parent:**
HP:0030878 Abnormality on pulmonary function testing

**Synonyms:** Decreased pre bronchodilator FVC

**For LOINC Code:**
19877-0 Forced vital capacity [Volume] Respiratory system --pre bronchodilation

**Biocurator ID for loinc2hpo:** UCDenver:tjcallahan

**SOURCE:** https://www.aafp.org/afp/2014/0301/p359.html

**Comment by pnrobinson** [comment]
added as HP_0032356. @callahantiff @kingmanzhang

**Comment by kingmanzhang** [comment]
done
