### ISSUE TITLE
NTR: Decreased peak expiratory flow

### ISSUE THREAD

**Issue by callahantiff** [obophenotype/human-phenotype-ontology#4469]
**NTR:** Decreased peak expiratory flow

**Parent:**
HP:0030878 Abnormality on pulmonary function testing

**Synonyms:** Decreased PEF airway PFM

**For LOINC Code:**
19935-6 Maximum expiratory gas flow Respiratory system airway by Peak flow meter

**Biocurator ID for loinc2hpo:** UCDenver:tjcallahan

**SOURCE:** https://www.aafp.org/afp/2014/0301/p359.html"

**Comment by pnrobinson** [comment]
added as HP_0032355 @callahantiff @kingmanzhang

**Comment by kingmanzhang** [comment]
modified
