### ISSUE TITLE
NTR: Abnormal urinary methylhistidine concentration

### ISSUE THREAD

**Issue by callahantiff** [obophenotype/human-phenotype-ontology#4470]
**NTR:** Abnormal urinary methylhistidine concentration

**Parent:**
HP:0003110 Abnormality of urine homeostasis

**For LOINC Code:**
28606-2 1-Methylhistidine/Creatinine [Ratio] in Urine

**Biocurator ID for loinc2hpo:** UCDenver:tjcallahan

**SOURCE:** https://www.questdiagnostics.com/testcenter/testguide.action?dc=TS_AminAcidAnal

**Comment by nicolevasilevsky** [comment]
@callahantiff we can use HP_0410313 'Abnormal urinary 1-methylhistidine concentration' for this annotation, yes?

**Comment by callahantiff** [comment]
I think the reason we initially created this was so that we could group abnormal  1-Methylhistidinuria and 3-Methylhistidinuria concepts together, but perhaps that is not needed anymore?

**Comment by nicolevasilevsky** [comment]
Yes, I think so too, but I don't think we really need it.

**Comment by nicolevasilevsky** [comment]
Can I close this ticket, if you agree?

**Comment by callahantiff** [comment]
Yep, that works for me! 👍
