### ISSUE TITLE
NTR: Decreased urinary 1-methylhistidine

### ISSUE THREAD

**Issue by callahantiff** [obophenotype/human-phenotype-ontology#4471]
**NTR:** Decreased urinary 1-methylhistidine

**Parent:**
NTR Abnormal urinary methylhistidine concentration (Issue #4470)

**For LOINC Code:**
28606-2 1-Methylhistidine/Creatinine [Ratio] in Urine

**Biocurator ID for loinc2hpo:** UCDenver:tjcallahan

**SOURCE:** https://www.questdiagnostics.com/testcenter/testguide.action?dc=TS_AminAcidAnal

**Comment by nicolevasilevsky** [comment]
@drseb can you please MIREOT CHEBI:70958 - 1-methylhistidine

**Comment by nicolevasilevsky** [comment]
@callahantiff I added:
HP_0410313 'Abnormal urinary 1-methylhistidine concentration'

**Comment by callahantiff** [comment]
Thank you! Shoot, I should have put these together, just to be complete issue #4472 covers the high result for this lab. Sorry for separating out the terms.

**Comment by nicolevasilevsky** [comment]
It's all good, they were cross-referenced in the tickets, so I figured it all out. :)
