### ISSUE TITLE
NTR: 2-Methylbutyryl glycinuria

### ISSUE THREAD

**Issue by callahantiff** [obophenotype/human-phenotype-ontology#4474]
**NTR:** 2-Methylbutyryl glycinuria

**Parent:**
HP:0003355 Aminoaciduria

**For LOINC Code:**
27097-5 2-Methylbutyrylglycine/Creatinine [Mass Ratio] in Urine

**Biocurator ID for loinc2hpo:** UCDenver:tjcallahan

**Comment by pnrobinson** [comment]
Definition: Increased concentration of 2-methylbutyryl glycine in the urine. PMID:17883863 
Comment: This phenotype can be related to a defect in the degradation pathway of L- isoleucine leading to increased urinary excretion of 2-methylbutyryl glycine.

**Comment by pnrobinson** [comment]
@callahantiff adding as HP_0020147

**Comment by pnrobinson** [comment]
done
