### ISSUE TITLE
NTR: Increased urinary alanine

### ISSUE THREAD

**Issue by callahantiff** [obophenotype/human-phenotype-ontology#4475]
**NTR:** Increased urinary alanine

**Parent:**
HP:0003355 Aminoaciduria

**For LOINC Code:**
30068-1 Alanine/Creatinine [Ratio] in Urine

**Biocurator ID for loinc2hpo:** UCDenver:tjcallahan

**SOURCE:** https://www.questdiagnostics.com/testcenter/testguide.action?dc=TS_AminAcidAnal

**Comment by pnrobinson** [comment]
added as HP_0020078 @callahantiff @kingmanzhang

**Comment by kingmanzhang** [comment]
done
