### ISSUE TITLE
NTR: Alpha-aminoadipic aciduria

### ISSUE THREAD

**Issue by callahantiff** [obophenotype/human-phenotype-ontology#4476]
**NTR:** Alpha-aminoadipic aciduria

**Parent:**
HP:0003355 Aminoaciduria

**For LOINC Code:**
28598-1 Alpha aminoadipate/​Creatinine [Ratio] in Urine

**Biocurator ID for loinc2hpo:** UCDenver:tjcallahan

**SOURCE:** https://link.springer.com/article/10.1007/BF01805581

**Comment by nicolevasilevsky** [comment]
@pnrobinson I can add this if it looks okay to you

**Comment by nicolevasilevsky** [comment]
@drseb can you please MIREOT CHEBI:37024 - 2-aminoadipic acid

**Comment by nicolevasilevsky** [comment]
@callahantiff I added this term:
HP_0410309 'Alpha-aminoadipic aciduria'

**Comment by callahantiff** [comment]
Thank you!
