### ISSUE TITLE
NTR: Alpha-aminobutyric aciduria

### ISSUE THREAD

**Issue by callahantiff** [obophenotype/human-phenotype-ontology#4477]
**NTR:** Alpha-aminobutyric aciduria

**Parent:**
HP:0003355 Aminoaciduria

**For LOINC Code:**
28590-8 Alpha aminobutyrate/Creatinine [Ratio] in Urine

**Biocurator ID for loinc2hpo:** UCDenver:tjcallahan

**SOURCE:** https://www.questdiagnostics.com/testcenter/testguide.action?dc=TS_AminAcidAnal

**Comment by pnrobinson** [comment]
added as HP_0025631 @callahantiff @kingmanzhang

**Comment by kingmanzhang** [comment]
done
