### ISSUE TITLE
NTR: Anserinuria

### ISSUE THREAD

**Issue by callahantiff** [obophenotype/human-phenotype-ontology#4478]
**NTR:** Anserinuria

**Parent:**
HP:0003355 Aminoaciduria

**For LOINC Code:**
28596-5 Anserine/Creatinine [Ratio] in Urine

**Biocurator ID for loinc2hpo:** UCDenver:tjcallahan

**SOURCE:** https://www.questdiagnostics.com/testcenter/testguide.action?dc=TS_AminAcidAnal

**Comment by pnrobinson** [comment]
https://en.wikipedia.org/wiki/Anserine

**Comment by pnrobinson** [comment]
I think this is mainly a marker of meat consumption and not an abnormal phenotype. As such, it seems to be out of scope for HPO. Please reopen with more information if indicated.
