### ISSUE TITLE
NTR: Argininosuccinic aciduria

### ISSUE THREAD

**Issue by callahantiff** [obophenotype/human-phenotype-ontology#4479]
**NTR:** Argininosuccinic aciduria

**Parent:**
HP:0003355 Aminoaciduria

**For LOINC Code:**
28603-9 Argininosuccinate/Creatinine [Ratio] in Urine

**Biocurator ID for loinc2hpo:** UCDenver:tjcallahan

**SOURCE:** https://ghr.nlm.nih.gov/condition/argininosuccinic-aciduria

**Comment by pnrobinson** [comment]
adding as HP_0025630 @callahantiff @kingmanzhang

**Comment by kingmanzhang** [comment]
done
