### ISSUE TITLE
NTR: Increased level of asparagine in urine

### ISSUE THREAD

**Issue by callahantiff** [obophenotype/human-phenotype-ontology#4480]
**NTR:** Increased level of asparagine in urine

**Parent:**
HP:0003355 Aminoaciduria

**For LOINC Code:**
28588-2 Asparagine/Creatinine [Ratio] in Urine

**Biocurator ID for loinc2hpo:** UCDenver:tjcallahan

**SOURCE:** https://www.questdiagnostics.com/testcenter/testguide.action?dc=TS_AminAcidAnal

**Comment by pnrobinson** [comment]
added as HP_0032403 @callahantiff @kingmanzhang

**Comment by kingmanzhang** [comment]
done
