### ISSUE TITLE
NTR: Aspartic aciduria

### ISSUE THREAD

**Issue by callahantiff** [obophenotype/human-phenotype-ontology#4481]
**NTR:** Aspartic aciduria

**Parent:**
HP:0003355 Aminoaciduria

**For LOINC Code:**
32229-7 Aspartate/Creatinine [Ratio] in Urine

**Biocurator ID for loinc2hpo:** UCDenver:tjcallahan

**SOURCE:** https://www.questdiagnostics.com/testcenter/testguide.action?dc=TS_AminAcidAnal

**Comment by pnrobinson** [comment]
adding as HP_0032401 @callahantiff @kingmanzhang

**Comment by pnrobinson** [comment]
we need to reannotate this disease
https://www.omim.org/entry/222730

**Comment by kingmanzhang** [comment]
done
