### ISSUE TITLE
NTR: Beta-alaninuria

### ISSUE THREAD

**Issue by callahantiff** [obophenotype/human-phenotype-ontology#4482]
**NTR:** Beta-alaninuria

**Parent:**
HP:0003355 Aminoaciduria

**For LOINC Code:**
30061-6 Beta alanine/Creatinine [Ratio] in Urine

**Biocurator ID for loinc2hpo:** UCDenver:tjcallahan

**SOURCE:** https://www.questdiagnostics.com/testcenter/testguide.action?dc=TS_AminAcidAnal

**Comment by pnrobinson** [comment]
added as HP_0020079 @callahantiff @kingmanzhang

**Comment by kingmanzhang** [comment]
done
