### ISSUE TITLE
NTR: Beta-Aminoisobutyric Aciduria

### ISSUE THREAD

**Issue by callahantiff** [obophenotype/human-phenotype-ontology#4483]
**NTR:** Beta-Aminoisobutyric Aciduria

**Parent:**
HP:0003355 Aminoaciduria

**For LOINC Code:**
27892-9 Beta aminoisobutyrate/Creatinine [Ratio] in Urine

**Biocurator ID for loinc2hpo:** UCDenver:tjcallahan

**SOURCE:** https://www.questdiagnostics.com/testcenter/testguide.action?dc=TS_AminAcidAnal

**Comment by pnrobinson** [comment]
adding as HP_0032480 @callahantiff @kingmanzhang

**Comment by kingmanzhang** [comment]
done
