### ISSUE TITLE
NTR: Increased level of N-Butyrylglycine in urine

### ISSUE THREAD

**Issue by callahantiff** [obophenotype/human-phenotype-ontology#4484]
**NTR:** Increased level of N-Butyrylglycine in urine

**Parent:**
HP:0040156 Elevated urinary carboxylic acid

**For LOINC Code:**
28602-1 Butyrylglycine/Creatinine [Mass Ratio] in Urine

**Biocurator ID for loinc2hpo:** UCDenver:tjcallahan

**SOURCE:** http://www.hmdb.ca/metabolites/HMDB0000808

**Comment by pnrobinson** [comment]
@callahantiff adding as HP_0025638 @kingmanzhang

**Comment by kingmanzhang** [comment]
done
