### ISSUE TITLE
NTR: Carnitinuria

### ISSUE THREAD

**Issue by callahantiff** [obophenotype/human-phenotype-ontology#4485]
**NTR:** Carnitinuria

**Parent:**
HP:0040156 Elevated urinary carboxylic acid

**For LOINC Code:**
17866-5 Carnitine/Creatinine [Ratio] in Urine

**Biocurator ID for loinc2hpo:** UCDenver:tjcallahan

**SOURCE:** http://www.hmdb.ca/metabolites/HMDB0000062

**Comment by pnrobinson** [comment]
adding as HP_0020077 @callahantiff @kingmanzhang

**Comment by kingmanzhang** [comment]
done
