### ISSUE TITLE
NTR: Citrullinuria

### ISSUE THREAD

**Issue by callahantiff** [obophenotype/human-phenotype-ontology#4486]
**NTR:** Citrullinuria

**Parent:**
HP:0003355 Aminoaciduria

**For LOINC Code:**
30161-4 Citrulline/Creatinine [Ratio] in Urine

**Biocurator ID for loinc2hpo:** UCDenver:tjcallahan

**SOURCE:** https://www.questdiagnostics.com/testcenter/testguide.action?dc=TS_AminAcidAnal

**Comment by pnrobinson** [comment]
adding as HP_0032397 @callahantiff @kingmanzhang

**Comment by kingmanzhang** [comment]
done
