### ISSUE TITLE
NTR: Glutaminuria

### ISSUE THREAD

**Issue by callahantiff** [obophenotype/human-phenotype-ontology#4489]
**NTR:** Glutaminuria

**Parent:**
HP:0003355 Aminoaciduria

**For LOINC Code:**
50332-6 Glutamine/Creatinine [Ratio] in Urine

**Biocurator ID for loinc2hpo:** UCDenver:tjcallahan

**SOURCE:** https://www.questdiagnostics.com/testcenter/testguide.action?dc=TS_AminAcidAnal

**Comment by pnrobinson** [comment]
added as HP_0032354 @callahantiff @kingmanzhang

**Comment by kingmanzhang** [comment]
Multiple errors here: 
LOINC 50332-6 is for a different test
HP:0032354 does not exist.
Mapped HP:0025376 Hyperglutaminuria to a few tests for Glutamine/creatine in urine

**Comment by pnrobinson** [comment]
The term id is: HP_0025376
https://hpo.jax.org/app/browse/term/HP:0025376
This term has exact synonym Glutaminuria
