### ISSUE TITLE
NTR: Increased level of hexadecanedioic acid in urine

### ISSUE THREAD

**Issue by callahantiff** [obophenotype/human-phenotype-ontology#4490]
**NTR:** Increased level of hexadecanedioic acid in urine

**Parent:**
HP:0008293 Long-chain dicarboxylic aciduria

**For LOINC Code:**
50332-6 Hexadecanedioate/Creatinine [Mass Ratio] in Urine

**Biocurator ID for loinc2hpo:** UCDenver:tjcallahan

**SOURCE:**

**Comment by LCCarmody** [comment]
There are only 3 pubmed papers referencing this in urine from the 80s and 90s.  There is a hexadecanoic acid that seems to be much more prevalent.   I might recommend we not annotate this.
@pnrobinson  Thoughts?

**Comment by pnrobinson** [comment]
@LCCarmody agree!

**Comment by callahantiff** [comment]
That seems reasonable to me!

**Comment by LCCarmody** [comment]
Great! I will close this.
