### ISSUE TITLE
NTR: Increased level of isoleucine in urine

### ISSUE THREAD

**Issue by callahantiff** [obophenotype/human-phenotype-ontology#4494]
**NTR:** Increased level of isoleucine in urine

**Parent:**
HP:0003355 Aminoaciduria

**For LOINC Code:**
30052-5 Isoleucine/​Creatinine [Ratio] in Urine

**Biocurator ID for loinc2hpo:** UCDenver:tjcallahan

**SOURCE:** https://www.questdiagnostics.com/testcenter/testguide.action?dc=TS_AminAcidAnal

**Comment by pnrobinson** [comment]
this is HP_0032371
@callahantiff

**Comment by callahantiff** [comment]
Thank you!
