### ISSUE TITLE
NTR: Leucinuria

### ISSUE THREAD

**Issue by callahantiff** [obophenotype/human-phenotype-ontology#4495]
**NTR:** Leucinuria

**Parent:**
HP:0003355 Aminoaciduria

**For LOINC Code:**
30053-3 Leucine/Creatinine [Ratio] in Urine

**Biocurator ID for loinc2hpo:** UCDenver:tjcallahan

**SOURCE:** https://www.questdiagnostics.com/testcenter/testguide.action?dc=TS_AminAcidAnal

**Comment by pnrobinson** [comment]
added as HP_0032353 @callahantiff @kingmanzhang

**Comment by kingmanzhang** [comment]
done
