### ISSUE TITLE
NTR: Methioninuria

### ISSUE THREAD

**Issue by callahantiff** [obophenotype/human-phenotype-ontology#4496]
**NTR:** Methioninuria

**Parent:**
HP:0003355 Aminoaciduria

**For LOINC Code:**
30063-2 Methionine/​Creatinine [Ratio] in Urine

**Biocurator ID for loinc2hpo:** UCDenver:tjcallahan

**SOURCE:** https://www.questdiagnostics.com/testcenter/testguide.action?dc=TS_AminAcidAnal

**Comment by pnrobinson** [comment]
@callahantiff @kingmanzhang adding term as HP_0032352

**Comment by kingmanzhang** [comment]
done
