### ISSUE TITLE
NTR: Increased level of 2-Octanamidoacetic acid in urine

### ISSUE THREAD

**Issue by callahantiff** [obophenotype/human-phenotype-ontology#4497]
**NTR:** Increased level of 2-Octanamidoacetic acid in urine

**Parent:**
HP:0040156 Elevated urinary carboxylic acid

**For LOINC Code:**
38367-9 N-octanoylglycine/​Creatinine [Mass Ratio] in Urine

**Biocurator ID for loinc2hpo:** UCDenver:tjcallahan

**SOURCE:** https://www.questdiagnostics.com/testcenter/testguide.action?dc=TS_AminAcidAnal

**Comment by LCCarmody** [comment]
@pnrobinson 

Similar issue with #4490.  I can't find the term or its common name directly in Pubmed.  I did find [this ](http://www.hmdb.ca/metabolites/HMDB0000832) which led me to a 1983 paper (PMID: 6616873) which associates this metabolite with mitochondrial fatty acid beta-oxidation disorders.  I am not sure if that's enough to add the term or not.  Let me know what you think.

**Comment by pnrobinson** [comment]
@callahantiff I cannot find any other link -- if there is some clear link to disease let's add this term (e.g., 'modern' PubMed reference), otherwise, let's not annotate for now.

**Comment by callahantiff** [comment]
> @callahantiff I cannot find any other link -- if there is some clear link to disease let's add this term (e.g., 'modern' PubMed reference), otherwise, let's not annotate for now.

OK, this may require more digging, but this was the only semi-clear connection I was able to find and it's not really what we are looking for - [Human Metabolome Database](http://www.hmdb.ca/metabolites/HMDB0000832):

**Disease:** Medium Chain Acyl-CoA Dehydrogenase Deficiency 
**OMIM:** [OMIM_201450](http://omim.org/entry/201450): Medium Chain Acyl-CoA Dehydrogenase Deficiency   
**Source:** [PubMed:6616873](https://reader.elsevier.com/reader/sd/pii/0009898183902462?token=90712A15945097F7E0CFD4B92E0BA53B68A95F2C38652B5D0229957A0A7D956C570D1A198251B126A7C9246E882FFF3A) - published 1983 😟 

But honestly, the paper seemed to suggest that there is not a "good" explanation for the decreased amounts that were observed (see description below from paper; octanoylglycine): 

<img width="580" alt="Screen Shot 2019-07-06 at 14 32 09" src="https://user-images.githubusercontent.com/8030363/60760908-e094cf80-9ffa-11e9-89a8-9799329479e8.png">

**Comment by pnrobinson** [comment]
I think that what we need is basically a lab test whose result can be normal or high for an individual. A lot of these metabolites have been investigated in studies but it does not seem there are normal ranges etc for individuals. Also, the above text is about the biochemistry of the metabolite but not about the medical relevance. I would suggest we not add terms like this unless there is a clear relevance! I will close for now, but reopen any of these if we have more information!
