### ISSUE TITLE
NTR: Increased level of phenylalanine in urine

### ISSUE THREAD

**Issue by callahantiff** [obophenotype/human-phenotype-ontology#4498]
**NTR:** Increased level of phenylalanine in urine

**Parent:**
HP:0003355 Aminoaciduria

**For LOINC Code:**
30055-8 Phenylalanine/​Creatinine [Ratio] in Urine

**Biocurator ID for loinc2hpo:** UCDenver:tjcallahan

**SOURCE:** https://www.questdiagnostics.com/testcenter/testguide.action?dc=TS_AminAcidAnal

**Comment by pnrobinson** [comment]
adding term as HP_0032351
@callahantiff @kingmanzhang

**Comment by kingmanzhang** [comment]
done
