### ISSUE TITLE
NTR: Increased level of phosphoserine in urine

### ISSUE THREAD

**Issue by callahantiff** [obophenotype/human-phenotype-ontology#4499]
**NTR:** Increased level of phosphoserine in urine

**Parent:**
HP:0003355 Aminoaciduria

**For LOINC Code:**
28600-5 Phosphoserine/​Creatinine [Ratio] in Urine

**Biocurator ID for loinc2hpo:** UCDenver:tjcallahan

**SOURCE:** https://www.questdiagnostics.com/testcenter/testguide.action?dc=TS_AminAcidAnal

**Comment by pnrobinson** [comment]
adding as HP_0032405  @callahantiff @kingmanzhang

**Comment by kingmanzhang** [comment]
done
