### ISSUE TITLE
NTR: Serinuria

### ISSUE THREAD

**Issue by callahantiff** [obophenotype/human-phenotype-ontology#4500]
**NTR:** Serinuria

**Parent:**
HP:0003355 Aminoaciduria

**For LOINC Code:**
30058-2 Serine/​Creatinine [Ratio] in Urine

**Biocurator ID for loinc2hpo:** UCDenver:tjcallahan

**SOURCE:** https://tmu.pure.elsevier.com/en/publications/therapeutic-effect-of-amino-acid-mixture-on-type-1-diabetes-melli

**Comment by pnrobinson** [comment]
added as HP_0032349

**Comment by pnrobinson** [comment]
@callahantiff @kingmanzhang  added term

**Comment by callahantiff** [comment]
Thank you!

**Comment by kingmanzhang** [comment]
done
