### ISSUE TITLE
NTR: Sulfocysteinuria

### ISSUE THREAD

**Issue by callahantiff** [obophenotype/human-phenotype-ontology#4501]
**NTR:** Sulfocysteinuria

**Parent:**
HP:0003355 Aminoaciduria

**For LOINC Code:**
34168-5 Sulfocysteine/Creatinine [Ratio] in Urine

**Biocurator ID for loinc2hpo:** UCDenver:tjcallahan

**SOURCE:** https://www.orpha.net/consor/cgi-bin/Disease_Search.php?lng=EN&data_id=468&Disease_Disease_Search_diseaseType=ORPHA&Disease_Disease_Search_diseaseGroup=833&Disease(s)/group%20of%20diseases=Sulfocystinuria&title=Sulfocystinuria&search=Disease_Search_Simple

**Comment by pnrobinson** [comment]
@callahantiff @kingmanzhang added as HP_0032350

**Comment by kingmanzhang** [comment]
done
