### ISSUE TITLE
NTR: Increased level of tetradecanedioic acid in urine

### ISSUE THREAD

**Issue by callahantiff** [obophenotype/human-phenotype-ontology#4502]
**NTR:** Increased level of tetradecanedioic acid in urine

**Parent:**
HP:0008293 Long-chain dicarboxylic aciduria

**For LOINC Code:**
30054-1 Tetradecanedioate/Creatinine [Mass Ratio] in Urine

**Biocurator ID for loinc2hpo:** UCDenver:tjcallahan

**Comment by pnrobinson** [comment]
I do not think there is an abnormally high level of this metabolite, and thus it is not in scope for an HPO term. Please reopen if this is incorrect.
