### ISSUE TITLE
NTR: Alkalemia

### ISSUE THREAD

**Issue by callahantiff** [obophenotype/human-phenotype-ontology#4503]
**NTR:** Alkalemia

**Parent:**
HP:0004360 Acid-base homeostasis

**For LOINC Code:**
11558-4 pH of Blood

**Biocurator ID for loinc2hpo:** UCDenver:tjcallahan

**Comment by LCCarmody** [comment]
According to Merck manual https://www.merckmanuals.com/professional/endocrine-and-metabolic-disorders/acid-base-regulation-and-disorders/acid-base-disorders, below are the definitions.  We have both Acidosis and Alkalosis.  Should this be a child of alkalosis? @pnrobinson 
Acidemia is serum pH < 7.35.
Alkalemia is serum pH > 7.45.
Acidosis refers to physiologic processes that cause acid accumulation or alkali loss.
Alkalosis refers to physiologic processes that cause alkali accumulation or acid loss.

**Comment by LCCarmody** [comment]
Sorry, just noticed this ticket.  https://github.com/obophenotype/human-phenotype-ontology/issues/736

**Comment by pnrobinson** [comment]
Yes, this is correct. But could we please add PMIDs to support the definitions. This one might work https://www.ncbi.nlm.nih.gov/pubmed/28232934

**Comment by callahantiff** [comment]
Thanks @LCCarmody for referencing that issue, I'm sorry I did not include that in the original post. I also realized I have not been including definitions. I will try to work back through the recent posts and suggest definitions with PMIDs.

**Comment by LCCarmody** [comment]
That's fine.   I'll work on the sources.  Just want to make sure that you are okay with it being a child of Alkalosis

**Comment by callahantiff** [comment]
Absolutely, that makes sense to me!

**Comment by pnrobinson** [comment]
Possible they should be sibs?

**Comment by LCCarmody** [comment]
I guess because the definition of Alkalosis is defined as "Depletion of acid or accumulation base in the body fluids." in HP, alkalemia, a high pH in serum would be a subclass.  I will put it either way

The logical definition of Alkalosis is:
'has part' some 
    ('increased amount'
     and ('inheres in' some 
        (base
         and ('part of' some 'bodily fluid')))
     and ('has modifier' some abnormal))

I was thinking of below for Alkemia:
'has part' some 
    ('increased amount'
     and ('inheres in' some 
        (base
         and ('part of' some 'blood serum')))
     and ('has modifier' some abnormal))

**Comment by pnrobinson** [comment]
see #736

**Comment by pnrobinson** [comment]
added term and log def
