### ISSUE TITLE
Definitions for laboratory abnormalities

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#4506]
Following the revision to the metabolism/homeostasis terms, many of the logical definitions are no longer correct. Yesterday we had the problem of a BFO quality being difficult to replace by the PATO quality, but as it turns out the definition needed updating anyway
```
'has part' some 
    (quality
     and ('inheres in' some 'carboxylic acid metabolic process')
     and ('has modifier' some abnormal))
```
was updated to
```
'has part' some 
    (amount
     and ('inheres in' some ('carboxylic acid'
  and ('part of' some blood)))
     and ('has modifier' some abnormal))
```

@drseb @matentzn   is there any way of doing all of this automagically?

**Comment by pnrobinson** [comment]
The term is question is https://hpo.jax.org/app/browse/term/HP:0004354

**Comment by pnrobinson** [comment]
@LCCarmody @nicolevasilevsky @matentzn can we please check if the updated pattern is OK as suggested?

**Comment by matentzn** [comment]
The pattern is exactly correct; and we still need to define it officially. So far, we only have increased or decreased level of chemical entity in location; You have just defined a new pattern:

abnormalLevelOfChemicalEntityInLocation. I will add it to the uPheno repo. Thank you!

Regarding automatic: yes; but not this month. We are almost there in terms of infrastructure. Late April is realistic.

**Comment by matentzn** [comment]
https://github.com/obophenotype/upheno/blob/master/src/patterns/dosdp-dev/abnormalLevelOfChemicalEntityInLocation.yaml

**Comment by pnrobinson** [comment]
@matentzn  So we can close this issue?

**Comment by matentzn** [comment]
Can be closed!
