### ISSUE TITLE
Suggestion to merge Heterotopia and gray matter heterotopias

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#4508]
Related to https://github.com/obophenotype/human-phenotype-ontology/issues/4382
Renske, are you basically say that "Gray matter heterotopia" is a synonym for "Heteropia"?

On of the annotated diseases is Chudley-mccullough Syndrome. According to COST:neuromig, this disease is characterized by Mesial parasagittal subcortical heterotopia. (The current OMIM annotation is Subcortical nodular gray matter heterotopia).
Another annotated disease is FraX sundrome, which currently is annotated to Periventricular heterotopia  in OMIM.
We should revise all of these annotations in light of the new terms.

**Comment by Renske-Oegema** [comment]
Yes, if they are in the brain they are, but heterotopic tissue can be present in /  and consist of other tissue. 

If these could potentially be confusing, we could go for gray matter heterotopia as the main term, but this term is not in use by our expert netwerk. 

And these heterotopia in Chudley-mccullough Syndrome are not nodular. 

"Another annotated disease is FraX sundrome, which currently is annotated to Periventricular heterotopia in OMIM." > you don't need to change it.

**Comment by pnrobinson** [comment]
Yes, because heterotopia can also be present in other organs/ tissues this is potentially confusing

Gray matter heterotopia are the same as neuronal heterotopia. Both terms can be used, I would prefer gray matter heterotopia, it is a bit more common and also more understandable to the lay.

I notice that the english vs american differs in the spelling of the word grey/ gray. Should we add both terms?

**Comment by pnrobinson** [comment]
merged these two. Also added the British spelling
