### ISSUE TITLE
Thick cerebral cortex DELETE

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#4509]
Related to #4382 
https://hpo.jax.org/app/browse/term/HP:0006891

Used to annotate the following diseases:
https://omim.org/entry/257320  (Lissencephaly 2)
https://omim.org/entry/236670 Muscular dystrophy-dystroglycanopathy (congenital with brain and eye anomalies), type A, 1

**Comment by pnrobinson** [comment]
Type I lissencephaly is characterized by microcephaly and a thickened cortex with 4 rather than 6 layers. (see e.g., https://www.ncbi.nlm.nih.gov/pubmed/8306354). Therefore, probably there is no need to have a separate annotation.

**Comment by pnrobinson** [comment]
From my reading ofthe OMIM entry, the annotation for OMIM:236670 is incorrect. I will remove it.

**Comment by Renske-Oegema** [comment]
thick cerebral tem is a very vague term and was used for different disorders
in lissencephaly 2 OMIM 257320  this is describing pachygyria (HP:0001302)
in OMIM 236670 it is describing cobblestone (HP:0007260), but you've already removed this link.

**Comment by pnrobinson** [comment]
But is this really a vague term -- increased thickness of the cortical layer can be clearly observed, I thought? We probably cannot always make a diagnosis of the particular type of pachygyria etc, and so can we retain this term?

**Comment by pnrobinson** [comment]
@Renske-Oegema  can we finish up the few remaining terms? I would leave this for now.

**Comment by pnrobinson** [comment]
I think we can leave this term for now.  The lissencephaly type X terms are inferences but there is an observation of a thick cortex.
