### ISSUE TITLE
Focal lissencephaly DELETE

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#4511]
Related to #4382

https://hpo.jax.org/app/browse/term/HP:0007187

The term is used to annotate only one disease
https://omim.org/entry/250220
There is literature that says it is associated with "partial lissencephaly" but I have not been able to find details yet
https://jmg.bmj.com/content/51/7/470.long

**Comment by Renske-Oegema** [comment]
Yes, lissencephaly can affect a part of the brain, but focal is not equal to partial
I would have to look into this papers

**Comment by pnrobinson** [comment]
@Renske-Oegema can you get back to me on this?

**Comment by Renske-Oegema** [comment]
Apparently the term partial lissencephaly was used in the paper Peeden PMID: 1481828, which I do not have access to. It has been cited by others in case reports concerning Sedaghatian-type spondylometaphyseal dysplasia , but as far as I can see it has not been described again in this disorder. According to Aygun 2012; https://doi.org/10.1002/ajmg.a.35306, who also cite this paper: One patient had a partial lissencephaly, which is a neuronal migration disorder or could also well be SGP [Peeden et al., 1992].
It's probably obsolete, as the terminology back in 1992 was not as detailed as it is now. But to be on the safe side ,we could leave it in for now as a separate term until we can find someone with access to this original paper.

**Comment by Renske-Oegema** [comment]
We have read the paper Peeden PMID: 1481828, it does not contain reliable imaging and/or pathological description. We suggest to refer to this feature with Abnormal cortical gyration (HP:0002536).

**Comment by pnrobinson** [comment]
@Renske-Oegema  This is the paper where the term partial/focal lissencephaly is used
https://jmg.bmj.com/content/51/7/470.long
-- do you think this is valid? Or how should we annotate these patients?

**Comment by pnrobinson** [comment]
I would suggest we keep this term now, also in conformance with https://omim.org/entry/250220
