### ISSUE TITLE
Delete: Frontoparietal polymicrogyria

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#4571]
Related to #4382

see https://hpo.jax.org/app/browse/term/HP:0007095

-- Renske, we will need to reannotate the three annotated disease (see above). How does this term relate to the new term requests?

**Comment by pnrobinson** [comment]
This reference cites Frontoparietal polymicrogyria
https://www.ncbi.nlm.nih.gov/books/NBK1329/
-- what is the motivation for deleting this term?

**Comment by pnrobinson** [comment]
@Renske-Oegema please comment!

**Comment by Renske-Oegema** [comment]
We replaced it with bilateral frontoparietal polymicrogyria, but it would be OK to leave it for now
There is a group working on the polymicrogyria terms, and we'll see how we incorporate this term into that.

**Comment by pnrobinson** [comment]
OK, I will close this issue for now then!
