### ISSUE TITLE
NTR: Reduced C-Reactive Protein Level

### ISSUE THREAD

**Issue by callahantiff** [obophenotype/human-phenotype-ontology#4575]
**NTR:** Reduced C-Reactive Protein Level

**Parent:** HP:0010876 Abnormality of Circulating Protein Level

**For LOINC Code:** 1988-5 C reactive protein [Mass/volume] in Serum or Plasma

**Biocurator ID for loinc2hpo:** UCDenver:tjcallahan

**SOURCE:** https://www.ncbi.nlm.nih.gov/pubmed/17852082

Created in reference to [issue #90](https://github.com/TheJacksonLaboratory/loinc2hpoAnnotation/issues/90).

**Comment by pnrobinson** [comment]
adding term as HP_0032437 (also new parent term) @callahantiff

**Comment by callahantiff** [comment]
Wonderful, thank you! I'll make a note and ensure that annotations are updated accordingly.
