### ISSUE TITLE
Add abbreviations to HPO

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#4579]
https://en.wikipedia.org/wiki/List_of_medical_abbreviations

@nicolevasilevsky @LCCarmody @pnrobinson 

can we do this?

**Comment by nicolevasilevsky** [comment]
sure thing, we can tag them abbreviation

**Comment by LCCarmody** [comment]
This is probably another thing to add to the documentation.

**Comment by drseb** [comment]
@LCCarmody do you know how to do it?

**Comment by LCCarmody** [comment]
Do I know how to add to the documentation or to add abbreviations?

The answers are I'm not sure (In the readme? or is there a Wiki I have forgotten about?) and I'm almost positive, respectively.

**Comment by drseb** [comment]
Both:

- to add a synonymtype property, please look at other examples
- to add to the documentation: please ask @pnrobinson (I think we are currently on a wiki)

**Comment by drseb** [comment]
maybe this one? https://github.com/obophenotype/human-phenotype-ontology/wiki

**Comment by nicolevasilevsky** [comment]
I created a [google spreadsheet](https://docs.google.com/spreadsheets/d/15XOgYfJPT_E3MNl2xUGyq5qFL1MoUu8-v4W49D0_lZY/edit#gid=0) for us to track these abbreviations as we add them

**Comment by LCCarmody** [comment]
Wow! That's helpful!

**Comment by drseb** [comment]
The spreadsheet or the abbreviations 😀?

**Comment by LCCarmody** [comment]
BOTH! :)

**Comment by nicolevasilevsky** [comment]
@LCCarmody FYI - I deleted rows in the spreadsheet where the terms didn't exist in HPO/the abbreviations are not needed. So we have a shorter list to work with now. :)

**Comment by LCCarmody** [comment]
Good.  Although this is tedious.

**Comment by drseb** [comment]
thanks!

**Comment by nicolevasilevsky** [comment]
Thanks for finishing these, @LCCarmody!
