### ISSUE TITLE
Odd EQ def in comment of HP_0008180 Mildly elevated creatine kinase

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#4581]
'has part' some 
('increased amount' and ('inheres in' some blood) and (towards some IMR_0002602) and ('has modifier' some 'mild intensity') and ('has modifier' some abnormal))

Is listed as a comment and not an EQ def.  Should I just delete it? 
@pnrobinson @drseb

**Comment by pnrobinson** [comment]
I added the def and removed the comment.
