### ISSUE TITLE
HP:0004337 Abnormality of amino acid metabolism has no children

### ISSUE THREAD

**Issue by kingmanzhang** [obophenotype/human-phenotype-ontology#4585]
I run into this during analysis. This term has 0 children. I thought it is parents of Abnormal circulating XXX amino acids? @pnrobinson

**Comment by pnrobinson** [comment]
This term means that the metabolism (and not necessarily the concentration) of an amino acid is abnormal. It would cover functional tests of metabolism. I think we can leave this for now, but for the LOINC terms we currently have we should use the Abnormal circulating level parent term.
