### ISSUE TITLE
NTR: Increased circulating arachidonate level

### ISSUE THREAD

**Issue by callahantiff** [obophenotype/human-phenotype-ontology#4595]
**NTR:** Increased circulating arachidonate level

**Parent:** HP_0045016 Elevated Serum Long-Chain Fatty Acids

**For LOINC code:** 35168-4 Arachidonate (C20:4w6) [Moles/volume] in Serum or Plasma

**Source**: [PMC6052660](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6052660/)

**Biocurator ID for loinc2hpo:** UCDenver:tjcallahan

**Comment by pnrobinson** [comment]
Is this the correct parent?
https://hpo.jax.org/app/browse/term/HP:0030361

**Comment by callahantiff** [comment]
That's a good question. I'm not expert here, but it sort of looks like eicosanoids are a product of certain chemical processes that act on arachidonic acid [source](https://en.wikipedia.org/wiki/Eicosanoid)?

**Comment by LCCarmody** [comment]
In general, I have been trying to look in CHEBI and find the best parent present in the HPO (and/or create a parent if it is obvious and not present).  I have also been adding the logical definitions with CHEBI terms, so when reasoning, they should move to their correct positions. We may need a few parent terms once all of these are in there.  At least, this was my thought pattern.  Let me know if I should be doing something different. @pnrobinson

**Comment by pnrobinson** [comment]
I think Abn circulating long-chain fatty acid... is better. Arachidonate is metabolised to an eicosanoid, but I do not think it is itself one. Added as HP_0020197 @callahantiff
