### ISSUE TITLE
NTR: Add new terms for blood types

### ISSUE THREAD

**Issue by callahantiff** [obophenotype/human-phenotype-ontology#4597]
**NTR:** Adding new HPO terms to specify different combinations of ABO blood group and Rh blood types. This request is made in response to **issue #3422**. These terms should be linked to LOINC tests.

Could consider adding the following new terms to account for the different combinations of blood group results:

**NTR:** Rhesus system blood type
**Parent:** HP_0032223 Blood Group

**NTR:** Rh positive
**Parent:** NTR Rhesus system blood type

**NTR:** Rh negative
**Parent:** NTR Rhesus system blood type

My question is how you would then combine the ABO group and Rh system to specify things like:
 - O positive
 - O negative
 - A positive
 - A negative
 - B positive
 - B negative
 - AB positive
 - AB negative

**Comment by callahantiff** [comment]
I did not add CUIs or SNOMED CT codes for these terms, but am happy to do that if it would be helpful.

**Comment by pnrobinson** [comment]
Well, there could be one term for ABO status and one term for Rh status. I do not think it is a good idea to have compound terms for ABO+Rh, because why stop there?

**Comment by callahantiff** [comment]
I'd take that! Sounds like a reasonable plan to me.

**Comment by pnrobinson** [comment]
I am still not sure we are allowed to use SNOMED codes like this in what will be a publicly available resource. @kingmanzhang @mellybelly @cmungall do you have thoughts on this?

**Comment by callahantiff** [comment]
I have terms as ICD9, ICD10 or CUIs and the source codes are ICD. If that is a better option?

**Comment by pnrobinson** [comment]
@kingmanzhang @aeyates can we incorporate mutliple such codes for mapping?

**Comment by kingmanzhang** [comment]
https://r.details.loinc.org/LOINC/883-9.html?sections=Comprehensive
https://r.details.loinc.org/LOINC/10331-7.html?sections=Comprehensive
 
LOINC has SNOMED code mappings. Yes, we can map codes from multiple systems, ie, you could provide many mappings to type A. I do not think you need to try to be comprehensive. We might wait until we collect more real world use cases before we decide which system is essential for mapping.

**Comment by pnrobinson** [comment]
I think we can close this. Let us code each blood type system separately -- we have always avoided bundled terms in the HPO

**Comment by callahantiff** [comment]
Sounds good, please let me know if I can do anything to help!
