### ISSUE TITLE
Glycophenotypes in HPO

### ISSUE THREAD

**Issue by jpgourdine** [obophenotype/human-phenotype-ontology#4598]
I am combining glycophenotypes I have captured in this [doc](https://docs.google.com/spreadsheets/d/1cNWlT-OjUJmASsbwzJ87I0EAYNqlcNnLXXddFqTKG0E/edit?usp=sharing
) @pnrobinson and @nicolevasilevsky 

JP

**Comment by nicolevasilevsky** [comment]
@pnrobinson if these terms look okay to you, I can add them

**Comment by pnrobinson** [comment]
These look great
Probably we should go for more concise labels
Decreased circulating heparan sulfate level 
with the other label as a synonym

can we try to find out the least confusing labels from e.g., http://www.jbc.org/content/283/12/7354.full
what do you think @jpgourdine 
thanks!

**Comment by jpgourdine** [comment]
@pnrobinson sounds good. More concise but still precise.

**Comment by nicolevasilevsky** [comment]
@pnrobinson I can add these new terms in this spreadsheet, if these terms look okay to you:
https://docs.google.com/spreadsheets/d/1cNWlT-OjUJmASsbwzJ87I0EAYNqlcNnLXXddFqTKG0E/edit#gid=216018414

**Comment by pnrobinson** [comment]
These look great! One revision is that the term labels should be Abnormal X glycan level (and not Abnormal X glycans level etc).

**Comment by nicolevasilevsky** [comment]
I updated this in the spreadsheet, and will work on adding these terms. :)

**Comment by nicolevasilevsky** [comment]
I have a question - some of these terms are classified under 'Abnormal protein glycosylation', which is a process, but the terms are Abnormal protein level. In general, there is a mix of terms that are abnormal processes, vs abnormal protein levels in the hierarchies. Is this okay or is this something we should try to untangle?

**Comment by nicolevasilevsky** [comment]
I added all the terms in the spreadsheet.

@jpgourdine let us know if there are any additional terms you'd like to add.
