### ISSUE TITLE
Loinc 84873-9:  "Myelin oligodendrocyte glycoprotein IgG Ab [Titer] in Serum or Plasma by Immunofluorescence"

### ISSUE THREAD

**Issue by jpgourdine** [obophenotype/human-phenotype-ontology#4600]
Suggest creating a new term for Loinc: 84873-9 [Myelin oligodendrocyte glycoprotein IgG Ab [Titer] in Serum or Plasma by Immunofluorescence] 
New term label:Anti-Myelin oligodendrocyte glycoprotein antibody positivity
New term comment (if ):Autoimmune antibody positivity (HP:0030057)
Your biocurator ID for loinc2hpo (if desired): OHSU:jpgourdine

**Comment by pnrobinson** [comment]
Presence of antibodies in the serum that react against myelin oligodendrocyte glycoprotein.
Comment Myelin oligodendrocyte glycoprotein (MOG), a member of the immunoglobulin (Ig) superfamily, is a myelin protein solely expressed at the outermost surface of myelin sheaths and oligodendrocyte membranes. MOG Abs can be found in a subset of predominantly pediatric patients with acute disseminated encephalomyelitis, aquaporin-4 seronegative neuromyelitis optica spectrum disorders, monophasic or recurrent isolated optic neuritis, or transverse myelitis, in atypical multiple sclerosis, and in N-methyl-d-aspartate receptor-encephalitis.
PMID:28533781
