### ISSUE TITLE
NTR: Elevated malate

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#4601]
PMID: 24781757

**Comment by pnrobinson** [comment]
Was malate measured in blood in this paper? It seems this was an experimental investigation or am I misunderstanding? @LCCarmody

**Comment by LCCarmody** [comment]
Ooops.  I took it from their Supp table one. It is

"Alterations   in urinary organic acids" 
elevated lactate, malate, succinate,  or
[SuppTable1.pdf](https://github.com/obophenotype/human-phenotype-ontology/files/3068844/SuppTable1.pdf)

 glutaric acid
-- | -- | --

**Comment by pnrobinson** [comment]
closing, not in scope as reported above.
