### ISSUE TITLE
NTR: airway hyperresponsiveness

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#4606]
### 1. Preferred term label
Airway hyperresponsiveness

### 2. . Textual definition
An increased sensitivity of the airways to an inhaled constrictor agonist, a steeper slope of the dose-response curve, and a greater maximal response to the agonist.
PMID:12629006

### 3. Parent term
HP_0002795 'Functional respiratory abnormality'

### 4. Which diseases are characterized by this term ? (e.g. Orphanet- or OMIM-id)
https://www.omim.org/entry/600807

@pnrobinson I can add this if it looks okay

**Comment by pnrobinson** [comment]
This is largely overlapping with Asthma, which is used as a phenotype but can also be considered to be a disease on its own. I think that the best thing is to use this as the primary label for the Asthma term.

**Comment by nicolevasilevsky** [comment]
Just to confirm - we should relabel HP_0002099 Asthma to airway hyperresponsiveness and make Asthma a synonym (narrow?)

**Comment by pnrobinson** [comment]
@nicolevasilevsky  I think this needs more thought, I will try to revise this section in the next few weeks.

**Comment by pnrobinson** [comment]
On further review, this term is only a component of Asthma and so cannot be a replacement. I will add the term. At some point, we will want to replace the Asthma HPO term with the Mondo term, or at least reference it. I am not sure how hard this would be for downstream software, but it would improve our modeling. I will add this term for now as suggested.
