### ISSUE TITLE
Add synonym to 'Hypoplastic hippocampus'

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#4607]
add synonym to 'Hypoplastic hippocampus'
small hippocampus

**Comment by pnrobinson** [comment]
Should this be lay person? I don't remember if normal people know what a hippocampus is? :-0

**Comment by nicolevasilevsky** [comment]
I'm not sure either!

**Comment by pnrobinson** [comment]
I guess this is a LP synonym, adding.
