### ISSUE TITLE
NTR: Generalized dilating diathesis

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#4608]
### 1. Preferred term label
Generalized dilating diathesis

### 2. Synonyms
n/a

### 3. Textual definition 
PMID:1642543

### 4. Parent term 
HP_0001892 'Abnormal bleeding'

Or is this the same thing? @pnrobinson 

### 5. Which diseases are characterized by this term ? (e.g. Orphanet- or OMIM-id)
https://www.omim.org/entry/100070

**Comment by pnrobinson** [comment]
I think this is clinical slang for tendency (diathesis) for arteries to increase in diameter (dilating). 
It is a phrase that intentionally tries to be as difficult to understand as possible so as to sound extra scientific, but it is not actually a phenotypic observation (it is an inference).

**Comment by pnrobinson** [comment]
I will close this, it is not a good term!
