### ISSUE TITLE
Merge candidate: Hypotrichosis and sparse hair

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#4618]
Are these terms actually synonyms?

**Comment by pnrobinson** [comment]
I think they are synonyms. We now have Abnormal hair quantity and Abnormal hair density, and I think that these parent classes might be synonyms. There are also several duplicates in the children of Hypotrichosis.

**Comment by drseb** [comment]
are you doing this or should I do this?

**Comment by pnrobinson** [comment]
I will start the merge procedure.

**Comment by pnrobinson** [comment]
Just to mention it. The two hierarchies have different definitions
```
'has part' some 
    ('decreased amount'
     and ('inheres in' some 
        ('strand of hair'
         and ('part of' some scalp)))
     and ('has modifier' some abnormal))
```
and
```
'has part' some 
    (sparse
     and ('inheres in' some 'hair of head')
     and ('has modifier' some abnormal))
```
Both seem to be correct. I will choose the second one (and analogously for the other terms).
I will choose "Sparse X hair" as the primary label, because Hypotrichosis is (also) the name of a disease that has other features including say scarring of follicles.
