### ISSUE TITLE
NTR: Focal epithelial hyperplasia of oral mucosa

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#4625]
### 1. Preferred term label
Focal epithelial hyperplasia of oral mucosa

### 2. Synonyms
Oral mucosa epithelial hyperplasia
Focal epithelial hyperplasia of the lining of mouth

### 3. Textual definition 
Enlargement due to increased cell numbers in the epithelial lining of the oral mucosa.

### 4. Parent term 
HP_0011830

### 5. Which diseases are characterized by this term ? (e.g. Orphanet- or OMIM-id)
https://www.omim.org/entry/136400

**Comment by nicolevasilevsky** [comment]
@pnrobinson I can add this if it looks okay to you

**Comment by pnrobinson** [comment]
Let's try to find a better definiton with a PubMed reference. Enlargement of what? What does it look like to the clinician? Is it just one lesion or can it be multifocal? Can it occur anywhere in the mouth? etc.

**Comment by nicolevasilevsky** [comment]
@pnrobinson 
Revised def below:
The occurrence of multiple or unique whitish or normal in color small papules or nodules in oral cavity, especially on labial and buccal mucosa, lower lip and tongue, and less often on the upper lip, gingiva and palate.
PMID:23204755

**Comment by pnrobinson** [comment]
thanks, sounds great!
