### ISSUE TITLE
Review and update user docs

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#4626]
Update the wiki with current SOPs.

- [x] How to make a good term request
- [x] What makes up a good HPO term?
- [ ] General definitions
- [x] Bundled terms
- [x] Immunology
- [x] Nephrology
- [ ] Neurology
- [x] Skeletal
- [x] Ophthalmology
- [x] Assays
- [x] Downloadable files

**Comment by LCCarmody** [comment]
I think the  [General Definitions](https://github.com/obophenotype/human-phenotype-ontology/wiki/General-definitions) section should be in the Editors' Docs.  
Also, this section has a lot of info that is under discussion with the patternization of HPO and uPheno, etc.  Maybe @nicolevasilevsky could review this section?

**Comment by LCCarmody** [comment]
@pnrobinson Should we keep the Immunology, Nephrology, Neurology, Skeletal, and Ophthalmology sections?  These appear to be notes from Hackathons, but have largely been implemented and have annotations within the HPO.  If we do keep the sections, maybe they could be rephrased to say something like, "Ophthalmology: Electroretinogram (ERG): Curators used the terms and standards outlined in PMID: 25502644."

**Comment by pnrobinson** [comment]
My suggestions:
- [ ] Delete the Immunology page
- [ ] Delete the neurology page, move the contents to official patternization docs
- [ ] delete downloadable files

keep skeletal, ophthalmology, Assays, nephrology page, but consider merging this information to a single page with sections. These pages have information that is useful when creating English-language definitions.
