### ISSUE TITLE
Review, break apart, update Editors' Guide for HPO developers

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#4628]
- [ ] Editing environment
- [x] Pre-edit checklist
- [ ] Getting started
- [ ] Creating new terms
- [ ] Obsoleting
- [ ] Merging
- [ ] MIREOTing
- [ ] Checklist
 

https://github.com/obophenotype/human-phenotype-ontology/wiki/Editor-Guide

**Comment by LCCarmody** [comment]
In combination, review (and remove) the README-editors.txt file.  There is significant overlap between the file above and this file.  
https://github.com/obophenotype/human-phenotype-ontology/blob/master/src/ontology/README-editors.txt

**Comment by LCCarmody** [comment]
Instead of removing the README-editors.txt file, point it to the Wiki.

**Comment by LCCarmody** [comment]
Who is working on this? @drseb ? I tried to go through the first little bit (the wiki version is definitely more up-to-date), but I have a couple of issues.
(1) Could someone put a short wiki together about how to add the updated ELK pluggin or pluggins in general?  I had to ask @matentzn help when I needed to update ELK.
(2) HP ID ranges.  I am a bit confused. I have opened hp-idranges.owl, but there doesn't appear to be anything in it? Am I missing something?

**Comment by nicolevasilevsky** [comment]
1) That would be great, Nico helped me too, but I don't remember how to do it, so it would be great to have it documented.

2) @LCCarmody you should open the HP ID ranges file in a text editor (like TextEdit or Sublime Text). I am not sure why it is saved as an OWL file, that is how it is done in a lot of ontologies, but I am not sure why.

**Comment by LCCarmody** [comment]
@nicolevasilevsky Opening in a text editor worked.  That should be added to the wiki, I think.  I am not sure I understand a lot of the directions that are listed for the ID ranges.

**Comment by nicolevasilevsky** [comment]
@LCCarmody I updated the instructions and added some images, does this make sense now?
https://github.com/obophenotype/human-phenotype-ontology/wiki/Editor-Guide

**Comment by matentzn** [comment]
Installing ELK:

1) Go to the [ELK pages](https://github.com/liveontologies/elk-reasoner/wiki/GettingElk)
2) Scroll down and click on **Protege Plugin latest build**
3) When downloaded, unzip and copy puli and elk jars (to .jar files) in the unpacked directory.
4) Paste these files in your Protege plugin directory. This is in one of two locations:
  * ~/.Protege/plugins (note this is usually hidden from finder, but you can see it in the terminal) or
  * Go to Protege in **Applications** (Finder), right click, 'Show package contents' -> Java -> plugins

Feel free to add these instructions to wiki!

**Comment by nicolevasilevsky** [comment]
Thanks @matentzn!
Are these instructions just for Mac users?

I added this to this wiki page: https://github.com/obophenotype/human-phenotype-ontology/wiki/Editor-Guide

**Comment by matentzn** [comment]
yeah, just for Mac users. But unix users can follow it roughly as well. For windows users not sure 100%. but should work the usual way! Copy the jars in the plugins dir.

**Comment by pnrobinson** [comment]
I think the new wiki is now relatively nice and would suggest we open specific terms for individual pages as needed!
