### ISSUE TITLE
Loinc 63396-6:  "Myelin associated glycoprotein Ab [Presence] in Body fluid by Immunoblot"

### ISSUE THREAD

**Issue by jpgourdine** [obophenotype/human-phenotype-ontology#4629]
Suggest creating a new term for Loinc: 63396-6 [Myelin associated glycoprotein Ab [Presence] in Body fluid by Immunoblot] 
New term label:Myelin associated glycoprotein antibody positivity
New term comment (if any): Parent term Autoimmune antibody positivity HP:0030057
Your biocurator ID for loinc2hpo (if desired): OHSU:jpgourdine

**Comment by pnrobinson** [comment]
I am adding a term for serum autoantibodies against MAG. I do not think we should add terms like this for "body fluid"--this is not specific enough for HPO. So we cannot easily map this LOINC term.
