### ISSUE TITLE
Loinc 56532-5:  "Asialoglycoprotein receptor Ab [Units/volume] in Serum by Immunoassay"

### ISSUE THREAD

**Issue by jpgourdine** [obophenotype/human-phenotype-ontology#4631]
Suggest creating a new term for Loinc: 56532-5 [Asialoglycoprotein receptor Ab [Units/volume] in Serum by Immunoassay] 
New term label:Asialoglycoprotein receptor antibody positivity
New term comment (if any):Parent term Autoimmune antibody positivity HP:0030057
Your biocurator ID for loinc2hpo (if desired): OHSU:jpgourdine

**Comment by pnrobinson** [comment]
adding as HP_0032469 @kingmanzhang

**Comment by kingmanzhang** [comment]
done
