### ISSUE TITLE
Redirect and Update Design Pattern files/documents

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#4634]
Close #4626 and reference #4627, several files need condensing and/or rearranging.

- [x] [General Definitions](https://github.com/obophenotype/human-phenotype-ontology/wiki/General-definitions)
- [x] [Neurology (needs to go where ever patternization docs go](https://github.com/obophenotype/human-phenotype-ontology/wiki/Neurology-(needs-to-go-where-ever-patternization-docs-go))
- [x] General-rules-for-design-patterns
- [x] Design Patterns for Lab Values
- [ ] Movement
- [ ] Spectra and subclasses
- [ ] Restrictions for phenotype logical definitions
- [x] Terms with identical logical definitions

**Comment by pnrobinson** [comment]
Neurology was not longer useful, I deleted it.
The other files contain items that are still being discussed, but I do not think that the wiki is the best place to hold the discussion. Should we just delete them for now?

**Comment by pnrobinson** [comment]
@LCCarmody I think we can delete the three pages that are still not checked off -- this is not superceded by the logical def work. Unless there is a reason to keep them I would suggest we delete them and close this issue.
