### ISSUE TITLE
Strategy docs

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#4635]
- [x] [Past Medical History](Past Medical History)
- [x] Craniofacial musings

- [ ] Other files?

**Comment by pnrobinson** [comment]
I think that this section is no longer current and should be deleted.

**Comment by nicolevasilevsky** [comment]
I'll delete this section. @pnrobinson do you want to delete the past medical history page too?

**Comment by pnrobinson** [comment]
We have implented the past medical history and so I think the page should be deleted -- it was mainly a reminder!

**Comment by nicolevasilevsky** [comment]
Ok, will do!

**Comment by nicolevasilevsky** [comment]
I deleted past medical history and craniofacial musings. @LCCarmody are there other files that need to be addressed under this ticket? If no, I think this can be closed.

**Comment by LCCarmody** [comment]
No files that I was aware of.  I left the final bullet point in case we had some strategy thoughts/docs moving forward.  It sounds like we don't so I will close this.
