### ISSUE TITLE
revise label: 'Abnormal vasculature of the conjunctiva morphology'

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#4636]
this label sounds very awkward:
'Abnormal vasculature of the conjunctiva morphology'

Could we revise it to:
Abnormal morphology of the conjunctiva vasculature

**Comment by pnrobinson** [comment]
Good suggestion. Perhaps Abnormal morphology of the conjunctivaL vasculature and Abnormal morphology of the conjunctiva vasculature as an exact synonym?

**Comment by nicolevasilevsky** [comment]
sure! I'll revise the label and add the synonym.
