### ISSUE TITLE
question re: logical def for 'Global developmental delay'

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#4637]
I have a question about the logical def for '**global developmental delay**':
'has part' some 
    (delayed
     and ('inheres in' some 'developmental process')
     and ('has modifier' some abnormal))

HP_0000823 '**Delayed puberty**' is inferred to be a subclass of this, I think because global developmental delay uses the GO class 'development process'

The logical def for HP_0000823 '**Delayed puberty**'  is
'has part' some 
    (delayed
     and ('inheres in' some 'development of secondary sexual characteristics')
     and ('has modifier' some abnormal))

I don't think delayed puberty is a type of global developmental delay, which has the text def:
A delay in the achievement of motor or mental milestones in the domains of development of a child, including motor skills, speech and language, cognitive skills, and social and emotional skills. This term should only be used to describe children younger than five years of age.

I think the easiest approach would be to remove the logical def from global developmental delay. Not sure if this is the best approach though, but I'm not sure how to logically define it otherwise.

**Comment by pnrobinson** [comment]
I do not think the logical def is correct. The GO term ``developmental process`` is defined as
```
A biological process whose specific outcome is the progression of an integrated living unit: an anatomical structure (which may be a subcellular structure, cell, tissue, or organ), or organism over time from an initial condition to a later condition.
```
However, here, we are talking about the motor and mental development of a human including abilities to walk talk, think etc etc. So I agree with Nicole,  I do not think we can logically define this term. Thoughts @cmungall @drseb @matentzn

**Comment by cmungall** [comment]
> I do not think we can logically define this term

+1000

**Comment by matentzn** [comment]
If you believe it is wrong, drop it! We will come back to these kinds of classes later.

**Comment by drseb** [comment]
> If you believe it is wrong, drop it! We will come back to these kinds of classes later.

wait @nicolevasilevsky . Please don't just drop them. Keep asking first on the tracker. Thanks.

For this special case: if we really don't have a term that refers to the abstract "mental development", then yes, we currently (!) can't define it.

**Comment by matentzn** [comment]
yeah, I did not mean to say, all of them, just this one :P Sorry.

**Comment by drseb** [comment]
ah okay :-)
