### ISSUE TITLE
Need to merge/obsolete: 'Increased urinary orotic acid concentration'

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#4638]
These two terms are equivalent and should be merged:
HP_0010928 'Increased urinary orotic acid concentration'
HP_0003218 Oroticaciduria

**Comment by pnrobinson** [comment]
All of the direct annotations are to HP_0003218 and none are to HP_0010928. I will therefore retain HP_0003218 as the primary term.
