### ISSUE TITLE
revise logical def for: HP_0003111 'Abnormal blood ion concentration'

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#4639]
Currently the logical def for HP_0003111 'Abnormal blood ion concentration' does not include part of blood, but the text def does not include blood either. Should the text def and logical def include blood? Or should the label be revised to 'abnormal ion concentration?

If it is meant to be an abnormality in the blood, the logical def should be:

'has part' some 
(amount and ('inheres in' some ('monoatomic ion' and ('part of' some blood))) and ('has modifier' some abnormal))

Right now, Elevated sweat chloride is being incorrectly inferred to be a child of Abnormal blood ion concentration

**Comment by nicolevasilevsky** [comment]
looks like HP_0010929 'Abnormal blood cation concentration' does not have part of blood in the logical def either, but it probably should

**Comment by pnrobinson** [comment]
Agree with Nicole -- it should have ('part of' some blood)

**Comment by nicolevasilevsky** [comment]
there are some sublcasses in this branch that should have blood in the logical def too. I'll address these later.

**Comment by pnrobinson** [comment]
@nicolevasilevsky  what is the status of this issue? Is it closeable?

**Comment by nicolevasilevsky** [comment]
Yes, I think this can be closed, looks like all of the logical defs for the terms have been addressed.
