### ISSUE TITLE
revisit logical def for 'Storage in hepatocytes'

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#4641]
I'm not sure if the logical def for 'Storage in hepatocytes' properly captures the definition of this term:
'has part' some 
    ('increased amount'
     and ('inheres in' some 
        ('organic molecular entity'
         and ('part of' some hepatocyte)))
     and ('has modifier' some abnormal))

Maybe this term should not have a logical def?

**Comment by pnrobinson** [comment]
Well,I think it is correct logically speaking -- there is an accumulation of a substance. Usually we mean a macromolecule, perhaps that is better than organic molecular entity. There should be subterms with particular types of stored entity, probably we need a few more terms here.

**Comment by nicolevasilevsky** [comment]
I will update this to use CHEBI_33839 CHEBI_33839
