### ISSUE TITLE
New QC: dealing with equal synonyms

### ISSUE THREAD

**Issue by matentzn** [obophenotype/human-phenotype-ontology#4643]
In the new quality reports, we (thanks to ROBOT) check whether two classes use the same synonym. For example, both 'Autistic behaviour' and 'Atrial septal defect' have **ASD** as 'exact synonym'. For now, these will only be flagged as warnings. What would you like the HP policy to be on this issue, if any? Is warning enough, or should this be an ERROR?

```
WARN	duplicate_exact_synonym	HP:0000729	oboInOwl:hasExactSynonym	ASD	
WARN	duplicate_exact_synonym	HP:0001631	oboInOwl:hasExactSynonym	ASD	
```

**Comment by nicolevasilevsky** [comment]
I vote for warning, because in this case this is legitimate, but it is probably good to double check.

**Comment by nicolevasilevsky** [comment]
I like the new ROBOT quality reports too.

**Comment by pnrobinson** [comment]
We decided that if the synonyms are listed as synonymType abbreviation that we allow them. Therefore, there should not even be a warning for these. For all other cases of exact synonym, this should be an ERROR.

**Comment by matentzn** [comment]
@drseb Is there anything like what @pnrobinson says in your QC?

I am not sure what 'listed as synonymType abbreviation' means. In the case (ASD) above, is that the case?

**Comment by drseb** [comment]
Yes. This is done.

**Comment by drseb** [comment]
And yes. ASD has synonymType abbreviation

**Comment by matentzn** [comment]
Thanks! I will leave this ticket open, so that I remember at some point to change the setting for the report here. This is in any case reported by travis. Thanks all!
