### ISSUE TITLE
HP replace during and results_in relations

### ISSUE THREAD

**Issue by matentzn** [obophenotype/human-phenotype-ontology#4646]
> subsetdef: hposlim_core "Core clinical terminology"
> subsetdef: secondary_consequence "Consequence of a disorder in another organ system."
7a10
> synonymtypedef: layperson "layperson term"

**Comment by matentzn** [comment]
Seems to have been solved by adding the correct namespaces..

**Comment by matentzn** [comment]
during is replaced in [PR](https://github.com/obophenotype/human-phenotype-ontology/pull/4574).

@drseb @pnrobinson Asking for permission to remove the reference from these two logical definitions:

Proximal spinal muscular atrophy:
```
'has part' some 
    ('lacks parts or has fewer parts of type'
     and ('inheres in' some 'spinal cord')
     and (towards some 'motor neuron')
     and ('has modifier' some abnormal)
     and ('results in' some 'Proximal amyotrophy'))
```

and Spinal muscular atrophy:
```
'has part' some 
    ('lacks parts or has fewer parts of type'
     and ('inheres in' some 'vertebral column')
     and (towards some 'motor neuron')
     and ('has modifier' some abnormal)
     and ('results in' some 'Skeletal muscle atrophy'))
```

The reason for removing this relation is that we currently have not decided on how to do this properly, and this relation is 'rogue', i.e. not in RO (we are currently hunting down rogue relations everywhere, and HP has only this one remaining AFAICS). I can open a ticket to preserve the information if its needed, but I would like to drop this ASAP.

**Comment by matentzn** [comment]
Above comment pertains to results_in relation.

**Comment by drseb** [comment]
Ok. Let's remove but open a ticket to memorize the defs for later generations.  this is should go into the causality-project.

**Comment by drseb** [comment]
can you do this @matentzn ?
