### ISSUE TITLE
Candidate phenotypes for causal relations

### ISSUE THREAD

**Issue by matentzn** [obophenotype/human-phenotype-ontology#4649]
We use this issue to collect candidates of phenotypes that are (potentially) causally related. At a later point in time, we will implement mechanisms (patterns) to represent them. Currently, there is no agreed upon solution.

In this [issue](https://github.com/obophenotype/human-phenotype-ontology/issues/4646), we decided to strip the two causal relations that HP already had, so I will mention them here again:

Proximal spinal muscular atrophy:
```
'has part' some 
    ... and ('results in' some 'Proximal amyotrophy'))
```

and Spinal muscular atrophy:
```
'has part' some 
    ... and ('results in' some 'Skeletal muscle atrophy'))
```

**Comment by pnrobinson** [comment]
@matentzn @drseb can we skype about this? I would like to understand what our plans are here.

**Comment by matentzn** [comment]
There is no concrete plan at the moment. This issue is not so much an action item, more a reminder and a place where we can document if we think two abnormalities are causally related; At some point, we could reflect that (abnormal growth -> abnormal size). As soon as the first peep of something concrete comes up, I will let you know and set up a Skype! Is that ok?

**Comment by drseb** [comment]
We have started this project and it is very preliminary. Let's skype when there is more to discuss.

**Comment by pnrobinson** [comment]
OK, I see that sounds great!

**Comment by pnrobinson** [comment]
Can we close this here? What is the action item?

**Comment by matentzn** [comment]
Let’s close this for now; there are afaict no concrete action items!
