### ISSUE TITLE
Obsolete classes from other ontologies unrelated to HP

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#4650]
There are few obsolete classes ending up in hp-edit (in the protege-view). It seems not trivial to find out where these are coming from:

- CHEBI_48505
- GO_0004872
- GO_0005605
- GO_0043234
- GO_0044699
- GO_0044707
- GO_0044708
- GO_0044765

**Comment by matentzn** [comment]
Posted this:
https://github.com/ontodev/robot/issues/456

See what will happen. We will probably have to add some kind of postprocessing here!

**Comment by drseb** [comment]
Status? Any chance to fix this before April 2019 release?

**Comment by matentzn** [comment]
No, not yet. We will 1) have to live with them for this release, or 2) remove them ourselves (either automatically or manually, since there are only a handful. Will take about 5 minutes).

**Comment by drseb** [comment]
will close for now and nudge @matentzn in a few months again if issue does not get resolve automagically by a robot-fix
