### ISSUE TITLE
Loinc 31666-1:  "Sulfate-3-Glucuronyl paragloboside IgM Ab [Units/volume] in Serum"

### ISSUE THREAD

**Issue by jpgourdine** [obophenotype/human-phenotype-ontology#4651]
Suggest creating a new term for Loinc: 31666-1 [Sulfate-3-Glucuronyl paragloboside IgM Ab [Units/volume] in Serum] 
New term label:Anti-Sulfate-3-Glucuronyl Paragloboside antibody positivity
New term comment (if any):Parent term Autoimmune antibody positivity HP:0030057
Your biocurator ID for loinc2hpo (if desired): OHSU:jpgourdine

**Comment by pnrobinson** [comment]
@jpgourdine  This seems to be related to anti-myelin-associatedglycoprotein (MAG) IgM autoantibody 
-- do we need a new term? What is the difference?

**Comment by jpgourdine** [comment]
Hi @pnrobinson 
My bad, I need to put it in Anti-ganglioside antibody positivity
(it is a glycolipid)
https://www.ncbi.nlm.nih.gov/pubmed/29747820
