### ISSUE TITLE
Review text def for  Decreased body weight

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#4654]
Need to revisit the text def for this term below

**Suggeted revision of textual definition**

http://purl.obolibrary.org/obo/HP_0004325 | Decreased body weight |   |   | Lower than normal average weight. | PMID:10709991
-- | -- | -- | -- | -- | --

From [Missing defs spreadsheet](https://docs.google.com/spreadsheets/d/15L6ZHi5tS4t1wkCutvVvFhOKLYIxcC8iWOmQPwSZTmA/edit?ts=5c91796c#gid=0)

**Comment by pnrobinson** [comment]
-- please check whether the hierarchy here makes sense and we give guidance to users as to which terms to choose.

**Comment by nicolevasilevsky** [comment]
@ShahimEssaid would you mind reviewing this hierarchy and consider if this definition makes sense?

Maybe we just need to add a comment on this term to indicate a more specific term should be used for annotations, when possible?

**Comment by pnrobinson** [comment]
done
