### ISSUE TITLE
add synonym to 'Hyperconvex nail'

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#4664]
**HPO term**
'Hyperconvex nail'

**Synonym to be added**
Curved nail

**broad/exact/narrow/plural/abbreviation ?**
Exact

**Comment by pnrobinson** [comment]
@nicolevasilevsky  -- this could be either hyperconvex or concave -- where is this coming from?

**Comment by nicolevasilevsky** [comment]
it is for this disease: https://www.omim.org/entry/239300?search=239300&highlight=239300

**Comment by pnrobinson** [comment]
I am going to add Increased nail curvature, I think that Curved nail is ambiguous!
