### ISSUE TITLE
Add parent class to Abnormality of the lymphatic system

### ISSUE THREAD

**Issue by jxchong** [obophenotype/human-phenotype-ontology#4667]
**HPO term**
Abnormality of the lymphatic system HP:0100763

**Suggested revision and reasons**
Should also be a subclass of Abnormality of the vasculature HP:0002597 because that is one of the main roles of the lymphatic system (to process plasma back into the blood stream)

**Comment by pnrobinson** [comment]
@jxchong  Thanks for picking up this omission. I have fixed it!
