### ISSUE TITLE
subclasses of Abnormal liver morphology

### ISSUE THREAD

**Issue by cmungall** [obophenotype/human-phenotype-ontology#4668]
**HPO term**

HP:0410042 Abnormal liver morphology

**Suggested revision and reasons**

Current def is "Any **structural anomaly** of the bile-secreting organ ", which maybe encompasses more than is meant by morphology in other domains?

these are some of the subclasses:

 * Abnormal hepatic iron concentration
 * Depletion of mitochondrial DNA in liver; this is a structural change to a liver part but doesn't seem like a morphological change
 * Ectopic liver; in PATO we don't treat ectopic as morphological

These aren't subclasses in the pato sense of morphological. It may be that this is the hierarchy clinicians expect but in this case we should include some kind of internal curator note and use a different pato class in the definition, which is currently

```
Equivalent to: 
has part some (
    morphology and 
    inheres in some liver and 
    has modifier some abnormal)
```

**Comment by pnrobinson** [comment]
@cmungall for me all three of these terms are clearly morphology -- the divide is basically between items that can be in principle observed in a snapshot and those for which a time course is necessary.

As for PATO, ectopic is definitely morphology for the organism with ectopic X, and I guess it is a modeling decision whether ectopic is also morphology for X, but I would suggest that this would be the most consistent way of doing things.

I do not understand your distinction between structural and morphological -- I thought that these words are nearly synonymous, e.g. Wikipedia: Morphology is a branch of biology dealing with the study of the form and structure of organisms and their specific structural features.

**Comment by cmungall** [comment]
I like your distinction, it is very clear and easy to apply.

I had thought morphology was used in a more restrictive sense in some ontologies but I may be wrong.

It seems that PATO needs some work here as it's conception of morphology is much more restricted than how it is used in HP and MP. E.g. PATO does not include color or ectopic under morphology, in contrast to how it is used in HP, MP, TO and others. cc @matentzn @dosumis

**Comment by pnrobinson** [comment]
@cmungall Should we move this discussion to the PATO tracker? I have had a look at the hierarchy near here and think it is OK.

**Comment by cmungall** [comment]
yep - can you organize the pato morphology tickets @nicolevasilevsky ?

**Comment by nicolevasilevsky** [comment]
Yes, will do!

**Comment by nicolevasilevsky** [comment]
I created a ticket in the PATO tracker, I will close this here
