### ISSUE TITLE
Synonyms/Subclasses for HP:0031049 (Heavy-chain paraproteinemia)

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#4673]
**HPO term**
HP:0031049 (Heavy-chain paraproteinemia)

**Synonym to be added**

This is in german @pnrobinson !

Should we add some of those? https://www.msdmanuals.com/de-de/profi/h%C3%A4matologie-und-onkologie/plasmazellkrankheiten/schwerkettenkrankheiten

**broad/exact/narrow/plural/abbreviation ?**

**Comment by pnrobinson** [comment]
Good suggestion. Let me try to find some pubmed articles for these subclasses!

**Comment by pnrobinson** [comment]
One sees Alpha heavy chain disease (alpha=IgA, etc), but only rarely alpha-heavy chain paraproteinemia, which is the phenotype. But I think these are the correct labels for the HPO terms.
See e.g. https://www.ncbi.nlm.nih.gov/pubmed/25125965

**Comment by pnrobinson** [comment]
There are Alpga (IgA) Gamma (IgG) and Mu (IgM) subterms.

**Comment by drseb** [comment]
will you implement this or should I do this?

**Comment by pnrobinson** [comment]
added these terms!
