### ISSUE TITLE
Consistent spelling of tensor tympani(i)

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#4675]
**HPO term**

all of them...

**Bug description**

sometimes "tensor tympani" sometimes "tensor tympanii".

todo: find out what is more correct and fix the "wrong" ones. thanks

**Comment by pnrobinson** [comment]
one "i" is fine. I think the spelling with two "i" is also correct, it is a variant form that is less common.
https://en.wikipedia.org/wiki/Tensor_tympani_muscle

**Comment by LCCarmody** [comment]
According to pubmed: "Search results
Items: 1 to 20 of 3903<< First< PrevPage 

Showing results for tympani. Your search for tympanii retrieved no results."

I did find one 1923 paper and a 2012 paper that uses tympanii, but it appears to be much less common.  Maybe it could just be a synonym?
