### ISSUE TITLE
Need clarification on def of HP:0001708 (Right ventricular failure)

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#4676]
**HPO term**

HP:0001708 (Right ventricular failure)

**Bug description**

"often leading top pitting peripheral edema, ascites, and hepatomegaly"

is it "top pitting" or "to pitting"?

**Comment by drseb** [comment]
@pnrobinson ping

**Comment by pnrobinson** [comment]
to pitting is correct
