### ISSUE TITLE
General question about "HP:0004758 (Effort-induced polymorphic ventricular tachycardias)"

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#4677]
**HPO term**

HP:0004758 (Effort-induced polymorphic ventricular tachycardias)

**Bug description**

is it really "Effort-induced" ? Is this different from "exercise-induced"? How?

**Comment by pnrobinson** [comment]
Are you asking if we should add a synonym? I think there are a range of X-induced terms that are all very close, exercise-induced, catecholamine induced, effort-induced. I will read up on this a bit and try to improve the definition and add synonyms as appropriate.

**Comment by drseb** [comment]
this comes from a translator. usually we used exercise-induced for such cases. I think it was just kind of surprising to read "effort-induced" and it is unclear if there is any difference.

**Comment by drseb** [comment]
If you think it is okay as it is, please just close.

**Comment by pnrobinson** [comment]
I will try to improve the term definition and figure out what synonyms it should have

**Comment by pnrobinson** [comment]
I extended the definition and added this as a synoynm.
