### ISSUE TITLE
Remove synonyms? Obsolete it? HP:0100814 (Blue nevus)

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#4678]
**HPO term**

HP:0100814 (Blue nevus)

**Synonym to be removed**

remove?: "Mongolian spot"

In german we wouldn't use this term anymore.

**Comment by pnrobinson** [comment]
This is a case with synonym type obsolete -- meaning that we recommend that nobody use the synonym anymore, but that we retain it in order to keep the link to older literature.

**Comment by drseb** [comment]
Ok. Will obsolete the synonym.

**Comment by drseb** [comment]
I will not do anything for now. Please @pnrobinson check the relation to the class HP:0011369 (Mongolian blue spot) and maybe merge / revise hierachy. Thanks

**Comment by pnrobinson** [comment]
I added the hasSynonymType "obsolete" property.
