### ISSUE TITLE
Synonym typo for HP:0011002 (Osteopetrosis)

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#4680]
**HPO term**

HP:0011002 (Osteopetrosis)

**Bug description**

Albers-Schönberg OR Albers-Schoenberg

reported by @zafush

**Comment by pnrobinson** [comment]
If you are refering to the synonym, for better or worse in English the ö sometimes gets transformed into a plain o, and thus we should retain Albers-Schonberg. I would suggest also adding Albers-Schoenberg. I do not know if we have a policy about non ASCII chars?

https://rarediseases.org/rare-diseases/osteopetrosis/

**Comment by drseb** [comment]
ok. new todo: add back "Albers-Schonberg"
