### ISSUE TITLE
HP:0005155 (Ventricular escape rhythm)

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#4681]
**HPO term**

HP:0005155 (Ventricular escape rhythm)

**Suggeted revision of textual definition**

"Escape rate is usually 20-40 bpm, often associated with broad QRS complexes are broad (at least 120 ms)"

--> last sentence, "are broad" is redundant and should be removed

**Comment by pnrobinson** [comment]
fixed
