### ISSUE TITLE
HP:0012193 (Anaplastic large-cell lymphoma)

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#4682]
**HPO term**

HP:0012193 (Anaplastic large-cell lymphoma)

**Suggeted revision of textual definition**

some content is unnecessarily repeated in the def (lobulated and indented nuclei). compare first and second sentence.

"A type of T-cell lymphoma that is characterized by so-called hallmark cells with a pleomorphic appearance that express the CD30 antigen, are lobulated, and have indented nuclei. These so-called hallmark cells have lobulated and indented nuclei"

**Comment by pnrobinson** [comment]
The second sentence can be deleted
