### ISSUE TITLE
Fix definition of HP:0012398 (Peripheral edema)

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#4684]
**HPO term**

HP:0012398 (Peripheral edema)

**Suggeted revision of textual definition**

"An abnormal accumulation of the accumulation of interstitial fluid in the soft tissues of the limbs" shall be replaced by "_An abnormal accumulation of interstitial fluid in the soft tissues of the limbs_"

**Comment by pnrobinson** [comment]
fixed
