### ISSUE TITLE
HP:0031363 (Palpable purpura)

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#4687]
**HPO term**

HP:0031363 (Palpable purpura)

**Suggeted revision of textual definition**

There is a spelling mistake: "purpuira" should be "purpura". Additionally, "appreciated" does not fit well as a term. Perhaps "felt", "sensed", "noticed" or "observed" would be better?

**Comment by pnrobinson** [comment]
Actually, the following is idiomatic English, appreciated has two different meanings, 1. I appreciate your help etc and 2. I recognize the meaning of. I think we should leave it after the spelling error is corrected.

A type of purpura in which the lesions are raised (and can therefore be appreciated upon palpation).
