### ISSUE TITLE
HP:0031410 (Abnormal distribution of CD56 bright/dim natural killer cells)

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#4688]
**HPO term**

HP:0031410 (Abnormal distribution of CD56 bright/dim natural killer cells)

**Suggeted revision of textual definition**

In the second sentence in the english source string, there is a grammar mistake. It should be "CD56 *is/functions as* the adhesion molecule mediating(...)"

**Comment by pnrobinson** [comment]
CD56, an adhesion molecule mediating homotypic adhesion, is used as a functional marker for NK cells.
