### ISSUE TITLE
HP:0002635 (Type IV atherosclerotic lesion)

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#4689]
**HPO term**

HP:0002635 (Type IV atherosclerotic lesion)

**Suggested revision of textual definition**

The 3rd last sentence is referring to a report that isn't quoted here. What does this mean?

**Comment by pnrobinson** [comment]
=> We should remove "The nature and derivations of the lipid that constitutes the core are discussed in the section on the extracellular matrix at the end of this report."
