### ISSUE TITLE
 Arthrogryposis is not an exact synonym for AMC

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#4694]
**HPO term**
https://hpo.jax.org/app/browse/term/HP:0002804

**Bug description**

Arthrogryposis is not an exact synonym

**Comment by pnrobinson** [comment]
@drseb Actually, after reviewing this I would say that I was wrong and Arthrogryposis can be used as a synonym. In general, AMC is used as a disease description, but there is not phrase for just the phenotype. I have reviewed the definition, revised it, and added a pubmed id.
TODO -- check this article to revise definition of DA https://www.ncbi.nlm.nih.gov/pubmed/8923935

**Comment by pnrobinson** [comment]
I updated the definition. The arthrogryposes are actually diseases, although people seem to use the term arthrogryposis as a phenotypic feature as well. This is the best we can do. In the future, we should refer to Mondo terms also.

**Comment by drseb** [comment]
Ok. Thanks!
