### ISSUE TITLE
obsoletion of HP:0004038 (was about typo before)

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#4699]
**HPO term**

HP:0004038 Bony spikule of ulnar epiphyseal plate

**Bug description**

"spikule" should be "spicule"?

**Comment by pnrobinson** [comment]
I fixed the typoe but there are no disease associations and there is no definition. Let's write a definition and figure out what diseases this might apply to.

**Comment by pnrobinson** [comment]
I think this is actually a normal finding.
bone tissue is laid down upon spicules of calcified cartilage matrix.
There are no annotated diseases. I think this term was simply an error, and needs to be completely deleted (not merged). @drseb -- do you see any problems?

**Comment by drseb** [comment]
ok. go ahead and obsolete it.
