### ISSUE TITLE
Loinc 42176-8:  "1,3 beta glucan [Mass/volume] in Serum"

### ISSUE THREAD

**Issue by jpgourdine** [obophenotype/human-phenotype-ontology#4705]
Suggest creating a new term for Loinc: 42176-8 [1,3 beta glucan [Mass/volume] in Serum] 
New term label:Positive 1,3 beta glucan plasma/serum test
New term comment (if any): Parent term Plasma/serum xenobiotic (HP:0500100) PMID: 23850953
Your biocurator ID for loinc2hpo (if desired): OHSU:jpgourdine

**Comment by pnrobinson** [comment]
Beta-1,3-Glucan is a major constituent of all of the characterized fungal cell walls, making up between 30% and 80% of the mass of the wall. It is a biomarker of fungal infections such as invasive pulmonary aspergillosis

PMID:27475024
