### ISSUE TITLE
Loinc 31019-3:  "10-Hydroxycarbazepine [Mass/volume] in Serum or Plasma"

### ISSUE THREAD

**Issue by jpgourdine** [obophenotype/human-phenotype-ontology#4706]
Suggest creating a new term for Loinc: 31019-3 [10-Hydroxycarbazepine [Mass/volume] in Serum or Plasma] 
New term label:Positive dibenzoazepines plasma/serum test
New term comment (if any):Parent term Plasma/serum xenobiotic (HP:0500100)
dibenzodiazepine includes 10-hydroxycarbazepine,  carbamazepine, etc. see CHEBI:47804
Your biocurator ID for loinc2hpo (if desired): OHSU:jpgourdine

**Comment by nicolevasilevsky** [comment]
There is also this code:
20563-3 Carboxyhemoglobin/Hemoglobin.total in Blood

Should we add a new term or mark it unable to annotate?

**Comment by pnrobinson** [comment]
this is a drug test and not currently able to be represented.
