### ISSUE TITLE
definition of HP:0031179 (Nuchal rigidity)

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#4709]
**HPO term**

definition of HP:0031179 (Nuchal rigidity)

**Bug description**

first word: spelling error

**Comment by pnrobinson** [comment]
If you mean meningism, it is correct -- https://en.wikipedia.org/wiki/Meningism

**Comment by drseb** [comment]
What? No: First word of the definition not the comment: "Resistnace" ...

**Comment by pnrobinson** [comment]
I see, of course!
