### ISSUE TITLE
Loinc 3040-3:  "Lipase [Enzymatic activity/volume] in Serum or Plasma"

### ISSUE THREAD

**Issue by jpgourdine** [obophenotype/human-phenotype-ontology#4711]
Suggest creating a new term for Loinc: 3040-3 [Lipase [Enzymatic activity/volume] in Serum or Plasma] 
New term label: Abnormal (Increase/Decrease) serum triacylglycerol lipase activity
New term comment (if any): Parent term Abnormal enzyme/coenzyme activity (HP:0012379)
PMID: 29101470 for increased lipase for pancreatic fracture
PMID: 29081212 for decreased lipase for pancreatitis
Your biocurator ID for loinc2hpo (if desired): OHSU:jpgourdine

**Comment by pnrobinson** [comment]
Here is some background
https://www.ncbi.nlm.nih.gov/books/NBK537346/

**Comment by pnrobinson** [comment]
Normally levels are very low, so there is no abnormal low finding. I am adding a term
Increased circulating pancreatic triacylglycerol lipase activity
