### ISSUE TITLE
Loinc 2395-2:  "Glycolate [Mass/volume] in Serum or Plasma"

### ISSUE THREAD

**Issue by jpgourdine** [obophenotype/human-phenotype-ontology#4712]
Suggest creating a new term for Loinc: 2395-2 [Glycolate [Mass/volume] in Serum or Plasma] 
New term label:Elevated serum/blood glycolate (PMID: 2002628)
New term comment (if any):Parent term Abnormal homeostasis (HP:0012337) 
Your biocurator ID for loinc2hpo (if desired): OHSU:jpgourdine

**Comment by pnrobinson** [comment]
adding as HP_0025641
