### ISSUE TITLE
Revise subclass relationship: 'Abnormality of iron homeostasis'

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#4713]
**HPO term**
HP_0011031 'Abnormality of iron homeostasis'

**Suggested revision and reasons**
The logical def for 'Abnormality of iron homeostasis' is:
'has part' some 
    (amount
     and ('inheres in' some 
        ('iron cation'
         and ('part of' some blood)))
     and ('has modifier' some abnormal))

but these terms are children:
'Abnormal hepatic iron concentration'
  'Elevated hepatic iron concentration'

Should these liver iron terms should be reclassified?

**Comment by pnrobinson** [comment]
Probably they need to go here: https://hpo.jax.org/app/browse/term/HP:0032243

**Comment by nicolevasilevsky** [comment]
yes, agreed! I can revise this.
