### ISSUE TITLE
reclassify: HP_0011729 'Abnormality of joint mobility'

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#4714]
**HPO term**
HP_0011729 'Abnormality of joint mobility'

**Suggested revision and reasons**
HP_0011729 'Abnormality of joint mobility' should not be a child of HP_0001367 'Abnormal joint morphology', as it is physiology, not morphology.

This change is needed for the GPI paper, and I will revise Figure 3 accordingly.

@pnrobinson do you think it should be moved up to be a subclass of HP_0011843 'Abnormality of skeletal physiology'?

I can make this change, if yes.

**Comment by pnrobinson** [comment]
Probably we need a class Abnormal joint physiology
we need to revise some of the terms beneath it.
Let's figure out how to revise the GPI illustrations -- I do not think we need so many that illustrate the HPO structure, though. Call tomorrow?

**Comment by nicolevasilevsky** [comment]
Yes, let's chat tomorrow - we have a call scheduled at 10am

**Comment by pnrobinson** [comment]
I moved the term to physiology
