### ISSUE TITLE
More neoplasm terms

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/human-phenotype-ontology#473]
Hi Peter,
I updated my list and added more terms that I learned from the "Counseling about Cancer" textbook by K.A. Schneider. I also wrote in the Term Request column the super-class that I felt was the best fit. These are just suggestions, I know you will organize them systematically.

Thanks,
Courtney

Reported by: courtneyhum

Original Ticket: [obo/human-phenotype-requests/473](https://sourceforge.net/p/obo/human-phenotype-requests/473)

**Comment by drseb** [comment]
It seems that all the classes have been added. I'll close this ticket for now. Please reopen if classes are missing and let us know which ones are missing. Thanks

**Comment by drseb** [comment]
The list of requested terms is uploaded [here](https://docs.google.com/spreadsheets/d/1AYgkTZBDRW9DWkFjg1CU5JsuyCga4hNVYciSrfDZ97k/edit?usp=sharing)

**Comment by CourtneyHum** [comment]
Please forgive me if I'm looking in the wrong place..but I can't seem to find any of the terms in the second part of the list (below the black line) in the update ontology.

**Comment by drseb** [comment]
I'm at a meeting the next days. Will get back to you soon

**Comment by drseb** [comment]
I still have the feeling that @pnrobinson has added the major fraction of the requested classes. I went through the first 15 of your list and found almost every class. Can you please check again? Where are you searching for the classes that you are missing?

Can you please file tickets for the classes you are not finding?

**Comment by mellybelly** [comment]
@drseb can we make a plan to use the NCIT for these terms?

**Comment by drseb** [comment]
Sure. Do you intend to xref to NCIT or replace the HP classes by NCIT-classes?

**Comment by CourtneyHum** [comment]
I must be looking in the wrong place

On Mon, Sep 21, 2015 at 10:42 AM, Sebastian Köhler <notifications@github.com
> wrote:

> Sure. Do you intend to xref to NCIT or replace the HP classes by
> NCIT-classes?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/obophenotype/human-phenotype-ontology/issues/473#issuecomment-142003070>
> .
>



-- 
Courtney Hum, MSc
Genetic Counsellor
Centre for Computational Medicine
The Hospital for Sick Children
T: 416-813-7654 x414028

**Comment by drseb** [comment]
Where are you looking?
