### ISSUE TITLE
update annotation files to include MOIs for ordo

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#4730]
read http://www.orphadata.org/data/xml/en_product9_ages.xml

**Comment by drseb** [comment]
probably need mapping to hpo inheritance modes

**Comment by drseb** [comment]
clarify strange data entries such as

```
<Disorder id="19519">
      <OrphaNumber>247353</OrphaNumber>
      <ExpertLink lang="en">http://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=en&amp;Expert=247353</ExpertLink>
      <Name lang="en">Generalized pustular psoriasis</Name>
      <DisorderType id="21394">
        <OrphaNumber>377788</OrphaNumber>
        <Name lang="en">Disease</Name>
      </DisorderType>
      <AverageAgeOfOnsetList count="1">
        <AverageAgeOfOnset id="23543">
          <OrphaNumber>409948</OrphaNumber>
          <Name lang="en">Adult</Name>
        </AverageAgeOfOnset>
      </AverageAgeOfOnsetList>
      <AverageAgeOfDeathList count="0">
      </AverageAgeOfDeathList>
      <TypeOfInheritanceList count="2">
        <TypeOfInheritance id="23417">
          <OrphaNumber>409930</OrphaNumber>
          <Name lang="en">Autosomal recessive</Name>
        </TypeOfInheritance>
        <TypeOfInheritance id="23494">
          <OrphaNumber>409941</OrphaNumber>
          <Name lang="en">Not applicable</Name>
        </TypeOfInheritance>
      </TypeOfInheritanceList>
    </Disorder>
```

**Comment by pnrobinson** [comment]
Is this referring to https://omim.org/entry/614204 ?If so, Autosomal recessive is correct,

**Comment by drseb** [comment]
You are confusing me. This is about adding MOI's for all ORDO entries. The thing that is unclear about the example entry above is of course that it is associated with both recessive MOI and "Not applicable". Not sure what this is supposed to mean

**Comment by pnrobinson** [comment]
I am not sure myself, but I am guessing it is a mistake. There is one form of Generalized pustular psoriasis that is recessive, but most cases of psoriasis are not Mendelian, perhaps that is what is meant here?

**Comment by pnrobinson** [comment]
I have added this functionality to phenol and the MOIs for ORDO should be visible in the next hpo-web release
