### ISSUE TITLE
Eyelid fissure

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#4743]
NTR simulconsult

**Comment by pnrobinson** [comment]
@MickeySegal
Is this distinct from Eyelid coloboma? https://hpo.jax.org/app/browse/term/HP:0000625

Eyelid fissure is of course just the normal palpebral fissure.

**Comment by MickeySegal** [comment]
Here is the context in which we found it:
https://www.ncbi.nlm.nih.gov/books/NBK7041/

- Microcornea
- Eyelid fissures
- Corneal leukoma

They provide 10 references from which their characterization may have come.  

I agree the term is unclear and may be worth merging into others.  

What do you think?

**Comment by pnrobinson** [comment]
It was not clear to me so I just sent an email to the authors of the GeneReviews article.

**Comment by MickeySegal** [comment]
We used to be a formal part of the GeneReviews review process because we kept coming up with issues to be clarified.  Your efforts serve a similar function.

**Comment by pnrobinson** [comment]
closing after further discussion by email, the genereviews annotation seems to have been an error.
