### ISSUE TITLE
Low intraocular pressure

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#4747]
simulconsult

**Comment by pnrobinson** [comment]
@MickeySegal HP:0032547
@psergouniotis
I am adding this term: -- please let me know (reopen this issue)  if the definition needs revision!

label: Low intraocular pressure
Def: An abnormal decrease of the pressure within the eye.
Comment:Ocular hypotony is defined statistically as an intraocular pressure (IOP) of less than 6.5 mmHg, three standard deviations below the mean. Clinically significant hypotony is when a patient’s IOP is so low that there is resultant visual loss. Hypotony has also been described as low pressure in an individual eye, leading to functional changes and structural changes.
Synonym: Ocular hypotony

**Comment by MickeySegal** [comment]
The definition looks fine to me, though this is not quite my area of expertise
