### ISSUE TITLE
femoral pulse weaker than radial pulse

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#4751]
simulconsult

**Comment by pnrobinson** [comment]
@MickeySegal
I think this is covered by the new term:
Blood pressure substantially higher in upper than lower extremities
Please reopen with more information otherwise!

**Comment by MickeySegal** [comment]
I agree.  Although this was one of our oldest terms we only used it for Takayasu arteritis.  

We have added references to pulses in the 2 differential blood pressure findings.
