### ISSUE TITLE
Radial artery absent

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#4752]
simulconsult

**Comment by pnrobinson** [comment]
@MickeySegal
Does this refer to congenital absence of the radial artery, e.g., https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4000061/

**Comment by MickeySegal** [comment]
Presumably congenital as in https://www.ncbi.nlm.nih.gov/books/NBK7047/

**Comment by pnrobinson** [comment]
@MickeySegal  adding as HP_0020118
