### ISSUE TITLE
Differential blood pressure between limbs

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#4754]
simulconsult

**Comment by pnrobinson** [comment]
@MickeySegal
I am wondering if we can make this term  "Difference in blood pressure between arms"
https://www.bmj.com/content/344/bmj.e2033

A difference between BP in arm and leg can be normal for instance if the person is standing.

**Comment by MickeySegal** [comment]
I've changed our finding title to "Different blood pressure in arms versus legs, abnormal".  We use it for Taksayasu arteritis e.g. https://www.annalsthoracicsurgery.org/article/S0003-4975(11)02197-7/pdf and aortic coarctation.

**Comment by pnrobinson** [comment]
@MickeySegal  I am wondering if the phenotype is not better described by "Decreased brachial pulse" or "Decreased brachial blood pressure"? Otherwise the direction of the difference is not clear from the term label.

**Comment by MickeySegal** [comment]
I agree.  We started out with this finding in Takayasu arteritis, where the difference can be in either direction, but then it got used for coarctation of the aorta, where it is always higher in arms.  

The best approach is to have 2 findings, each used where appropriate, so we have now split to:

- Blood pressure much higher in legs than arms

- Blood pressure much higher in arms than legs

and we should do one term for each.

**Comment by pnrobinson** [comment]
Adding as HP_0020141 Blood pressure substantially higher in lower than upper extremities
and HP_0020142 Blood pressure substantially higher in upper than lower extremities
@MickeySegal
