### ISSUE TITLE
Placental hamartoma

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#4763]
simulconsult

**Comment by pnrobinson** [comment]
This is actually https://hpo.jax.org/app/browse/term/HP:0100883 (Chorangioma)
see https://www.ncbi.nlm.nih.gov/pubmed/20594143
Adding synonym

**Comment by pnrobinson** [comment]
done

**Comment by MickeySegal** [comment]
The term we were trying to map was:
Placental hematoma in pregnant female
with synonym:
Retroplacental hematoma

https://hpo.jax.org/app/browse/term/HP:0011416 may work for that
