### ISSUE TITLE
knuckle pads on dorsal aspect of finger joints

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#4768]
see simulconsult

**Comment by pnrobinson** [comment]
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4603232/

**Comment by pnrobinson** [comment]
adding term as "Knuckle pad" HP:0032541 @MickeySegal

**Comment by MickeySegal** [comment]
This was helpful.  I changed our term to "knuckle pad" to make clear that the part about the dorsal aspect of fingers was explanatory rather than a subset.
