### ISSUE TITLE
muscle rupture

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#4771]

**Comment by pnrobinson** [comment]
Perhaps there needs to be a subsection for muscle injury?
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4799202/

**Comment by pnrobinson** [comment]
@MickeySegal -- I am wondering if this isn't actually "Tendon rupture" or do we mean specifically "Muscle rupture"?

**Comment by MickeySegal** [comment]
We used the term only once from https://www.ncbi.nlm.nih.gov/books/NBK1494/ "Tendon/muscle rupture", which we entered as both tendon rupture and muscle rupture.  But it can be hard to distinguish the two so including them in the same finding might be the best approach.

**Comment by pnrobinson** [comment]
@MickeySegal  please use https://hpo.jax.org/app/browse/term/HP:0100550
I have added Tendon/muscle rupture as a synonym

**Comment by MickeySegal** [comment]
We deleted muscle rupture, though we may re-add it if we find situations in which it occurs without tendon rupture.
