### ISSUE TITLE
Small joint

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#4774]

**Comment by pnrobinson** [comment]
@MickeySegal can you provide an example of this phenotype?

**Comment by MickeySegal** [comment]
Our term is "Joints: predominantly small affected" with explanatory terms "Includes fingers, toes, interphalangeal, metacarpophalangeal, metatarsophalangeal, wrists, ankles, vertebrae, neck"

We use this primarily for rheumatologic conditions, but an example for a genetic syndrome is "small joint laxity" in https://omim.org/entry/618292

**Comment by pnrobinson** [comment]
So we are talking about localization in small joints, not about the fact that the joints are too small --

**Comment by MickeySegal** [comment]
Correct.

**Comment by pnrobinson** [comment]
Adding as HP_0032544
with definition: Applies to an abnormality that mainly affects the small joints, including fingers, toes, interphalangeal, metacarpophalangeal, metatarsophalangeal, wrists, ankles, vertebrae, and neck.
@MickeySegal
