### ISSUE TITLE
Lymph nodes increased in number

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#4779]

**Comment by pnrobinson** [comment]
Do you have a definition for this @MickeySegal? I presume we are not talking about metastases to lymph nodes?

**Comment by MickeySegal** [comment]
https://www.ncbi.nlm.nih.gov/books/NBK1457/

"Whereas primary lymphedema is usually associated with hypoplasia or aplasia of the lymphatic vessels, LDS is associated with an increased number of lymphatic vessels and inguinal lymph nodes [Dale 1987, Brice 2003]."

**Comment by pnrobinson** [comment]
Adding as HP_0032536 @MickeySegal
