### ISSUE TITLE
More soft tissue sarcoma

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/human-phenotype-ontology#478]
Complete the list of soft tissue sarcomas

http://www.cancer.org/cancer/sarcoma-adultsofttissuecancer/detailedguide/sarcoma-adult-soft-tissue-cancer-soft-tissue-sarcoma

Reported by: pnrobinson

Original Ticket: [obo/human-phenotype-requests/478](https://sourceforge.net/p/obo/human-phenotype-requests/478)

**Comment by drseb** [comment]
@pnrobinson Let me know if should go ahead and make a first draft of this sub-ontology under [Soft tissue sarcoma](http://www.human-phenotype-ontology.org/hpoweb/showterm?id=HP:0030448).

**Comment by pnrobinson** [comment]
I am closing this for now pending further integration plans with NCI.
