### ISSUE TITLE
Acetylcholinesterase inhibitors improve/worsen condition

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#4799]
Tensilon (edrophonium) test; AChE, pyridostigmine, MestinonÔøΩ

**Comment by pnrobinson** [comment]
see HP:0032526 and HP:0032525 @MickeySegal

**Comment by MickeySegal** [comment]
I don't see anything at https://hpo.jax.org/app/browse/term/HP:0032526 or https://hpo.jax.org/app/browse/term/HP:0032525

**Comment by pnrobinson** [comment]
The new terms will go live after the next HPO release, which probably will happen in early June.

**Comment by MickeySegal** [comment]
If you can provide some of the text from these entries that would enable me to make a choice now rather than flagging this as something to which to return in a few weeks.
