### ISSUE TITLE
large noncompacted trabeculae 

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/human-phenotype-ontology#480]
http://omim.org/entry/615092

Reported by: pnrobinson

Original Ticket: [obo/human-phenotype-requests/480](https://sourceforge.net/p/obo/human-phenotype-requests/480)

**Comment by drseb** [comment]
@pnrobinson if you give more detail (definition, which superclass you think of), I can add the class and the annotation.

**Comment by pnrobinson** [comment]
Added term HP_0030682
