### ISSUE TITLE
Biotin supplementation positive test response

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#4800]

**Comment by pnrobinson** [comment]
@MickeySegal -- can you provide background/definition?

**Comment by MickeySegal** [comment]
https://www.ncbi.nlm.nih.gov/books/NBK1322/

> The activities of the carboxylases in fibroblasts of individuals with holocarboxylase synthetase deficiency become near-normal to normal when cultured in medium supplemented with biotin (high biotin).

We had the cost listed as too low so this was included even though the list I sent wasn't intended at this stage to include lab tests.

**Comment by pnrobinson** [comment]
@MickeySegal 
Would you agree with this label? Otherwise the label does not really match what is happening, I think.
Positive carboxylase test response to biotin supplementation
or perhaps even better
Positive holocarboxylase synthetase response to biotin supplementation

**Comment by pnrobinson** [comment]
@MickeySegal any update on this?

**Comment by MickeySegal** [comment]
We use "Positive holocarboxylase synthetase response to biotin supplementation".

If you are assigning an HPO term we will use it, but we have a list of a few thousand lab terms we could provide but were holding that for another stage and had included this with our clinical list because we had erroneously listed the cost as one for a clinical finding.

**Comment by pnrobinson** [comment]
@MickeySegal -- OK. I think we would love to add more lab tests to HPO in the future. Perhaps it is best to close this issue for now, and then to systematically go through the lab tests. Perhaps this approach is also interesting for your software (https://github.com/data2health/ehr2HPO.prj) and if you do see any areas of synergy we should talk. I will close this item for now.
