### ISSUE TITLE
Anesthetics trigger episodes

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#4801]
Halothane, sevoflurane, desflurane, enflurane, isoflurane, propofol, etomidate

**Comment by LCCarmody** [comment]
Do you want separate terms for each of the anesthetics? Or mention them in the comments of Anesthetics trigger episodes?

**Comment by pnrobinson** [comment]
I think one term is sufficient, and we caqn mention the anesthetics in the comment. AFAIK the effect would be the same for all anesthetics of this class

**Comment by MickeySegal** [comment]
Why was this closed without a term being assigned?

**Comment by LCCarmody** [comment]
The term was added.

**Comment by MickeySegal** [comment]
What is the HPO code number?

**Comment by nicolevasilevsky** [comment]
HP_0500261 'Triggered by anesthetics'
