### ISSUE TITLE
Smoking or tobacco use exacerbates symptoms

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#4809]

**Comment by pnrobinson** [comment]
@MickeySegal
Adding as HP:0032500, Exacerbated by tobacco use

**Comment by MickeySegal** [comment]
Was HP:0025223 close enough?

**Comment by pnrobinson** [comment]
Well, exacerbated by and triggered by are different. I think we can have both, they will be connected via logical definitions in case we ever want to aggregate.
