### ISSUE TITLE
Multiple def fields in obo file? (HP:0020097)

### ISSUE THREAD

**Issue by patzaw** [obophenotype/human-phenotype-ontology#4813]
Hi

We've noticed that the HP:0020097 entry has 2 def fields in the hp.obo file. I think that the only HP with such a behavior in this file.
Is it something normal or is it a typo?

Thank you

Best regards

Patrice

**Comment by drseb** [comment]
this is a clear mistake and we need to fix our QC pipeline ASAP. Thanks for reporting.

**Comment by drseb** [comment]
QC actually caught it, but wasn't marking the build as failed. @matentzn will take care of that. thanks
