### ISSUE TITLE
Invalid ISBN in HP

### ISSUE THREAD

**Issue by althonos** [obophenotype/human-phenotype-ontology#4814]
Hi there!

HP currently contains an invalid ISBN: `ISBN:0781735140`, used twice, where the valid ISBN is [`ISBN:0781735149`](https://www.amazon.com/Fundamental-Immunology-William-Paul/dp/0781735149).

Furthermore, the `ISBN-13` prefix shouldn't be used, since both ISBN-10 and ISBN-13 can be expanded to the same valid URN (`urn:isbn:XXXXXXXXXX` or `urn:isbn:XXXXXXXXXXXXX`), and the `ISBN-13` has not been declared properly in the document, so it can't be resolved in a semantically correct way, whereas the `ISBN` prefix can be expanded using the [GO `db-xrefs.yaml` catalog](https://github.com/geneontology/go-site/blob/master/metadata/db-xrefs.yaml) if HP does not provide one :smiley:

**Comment by nicolevasilevsky** [comment]
I updated the dbxef for HP_0005384 and HP_0005419

**Comment by pnrobinson** [comment]
Thanks for the suggestion! I am closing this.
