### ISSUE TITLE
OBSOLESCENCE plugin issue?

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#4815]
Wasn't quite sure where to put this: But I _finally_ updated to Protege 5.5 AND installed the obsolescence plugin! Yay! with @nicolevasilevsky 

We definitely have one issue with knowing how it works--because which one is it?  Before adding the the plugin, Protege 5.5 has a menu term called 'Make entity obsolete'.  And after you add the plugin, there are now 2 'Make entity obsolete' menu items (See screen shot) Which one? Maybe we should call it something else?
<img width="576" alt="Screen Shot 2019-05-01 at 2 40 28 PM" src="https://user-images.githubusercontent.com/26067008/57036105-55c1de00-6c21-11e9-85bb-546fee417b90.png">
<img width="527" alt="Screen Shot 2019-05-01 at 2 49 34 PM" src="https://user-images.githubusercontent.com/26067008/57036107-578ba180-6c21-11e9-99a9-48c36b133f45.png">

**Comment by pnrobinson** [comment]
I do not think that this plugin does what we want it to -- has anybody checked it? We want to merge, not to obsolete (with very rare exceptions).
@drseb @cmungall @balhoff it would be great if somebody could give me a hand with the OBO plugin -- I think it should be possible to adapt it but I have a few blockers

**Comment by nicolevasilevsky** [comment]
Does anybody know what the Deprecate entity plugin is? It seems pretty cool. It has profiles for GO and OBI. It lets you merge.

**Comment by balhoff** [comment]
@nicolevasilevsky I think you're talking about the new built-in functionality in Protege. It was just added in 5.5.

@LCCarmody I think you _may_ have two of my plugins installed. And then there is the new Protege `Deprecate entity...` item which @nicolevasilevsky is talking about. A long time ago I made the obo-actions plugin, which had obsoletion, but later this was merged into the updated OBO Annotations Editor plugin, which you can install through the Protege `Check for plugins...` menu.

**Comment by nicolevasilevsky** [comment]
@balhoff yes, that is what I am talking about - it seems really good. @pnrobinson and @LCCarmody maybe we could ask the Protege team if they could create a profile for HPO? 

@balhoff I am in the same boat as @LCCarmody, I see two "Make entity obsolete" options too, and I am also unsure if I have your plugin installed properly. We both downloaded it from https://github.com/balhoff/obo-actions/downloads and added it to the plugins folder in Protege.

These instructions are on our [wiki](https://github.com/obophenotype/human-phenotype-ontology/wiki/Editor-Guide), we should update this if it is out of date.

**Comment by balhoff** [comment]
@nicolevasilevsky yes that's out of date. Delete the obo-actions one and just use the one that can be installed directly within Protege "Check for plugins".

**Comment by balhoff** [comment]
> maybe we could ask the Protege team if they could create a profile for HPO?

@nicolevasilevsky does HPO have a different obsoletion protocol from GO?

**Comment by nicolevasilevsky** [comment]
> @nicolevasilevsky does HPO have a different obsoletion protocol from GO?

Good question - @pnrobinson do you think we could use the deprecate entity plugin?

> @nicolevasilevsky yes that's out of date. Delete the obo-actions one and just use the one that can be installed directly within Protege "Check for plugins".

Thanks @balhoff @pnrobinson and @LCCarmody, I will update the wiki.

**Comment by LCCarmody** [comment]
Has @drseb used the new deprecate entity plugin? Maybe he can say if it does what is required.

**Comment by pnrobinson** [comment]
@drseb @balhoff  I do not think this plugin is what we want, because we will generally want to merge and almost never want to actually obsolete a term without replacment. I have not been able to get the obo protege plugin to work, and so I think we should concentrate on making good documentation about how to do all of this manually.

**Comment by pnrobinson** [comment]
I am closing this issue, I do not think we can solve this problem at this time.
