### ISSUE TITLE
HP:0002282 has two separate "comment” attributes

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#4817]
HP:0002282 has two separate "comment” attributes

need to fix QC

**Comment by LCCarmody** [comment]
Are more than one comment not allowed?

**Comment by drseb** [comment]
According to [this](https://owlcollab.github.io/oboformat/doc/GO.format.obo-1_2.html#S.2.2.2) not. We will follow this and I added a QC step for this. 

I fixed this in an earlier commit today, so closing

**Comment by LCCarmody** [comment]
Oh, I had no idea. I don't think I created any, but I don't think I would have flagged it if I had seen it.
Thanks

**Comment by drseb** [comment]
No. I fixed two cases. In one case I just merged the comments - in the other case one of the comments was clearly the definition. So all good.
