### ISSUE TITLE
Increased HbA2

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/human-phenotype-ontology#482]
The phenotypic hallmark of b-thalassemia trait is the
raised level of Hb A 2 (>3.5%),
Add term

Reported by: pnrobinson

Original Ticket: [obo/human-phenotype-requests/482](https://sourceforge.net/p/obo/human-phenotype-requests/482)

**Comment by pnrobinson** [comment]
Increased HbA2 hemoglobin
parent http://www.human-phenotype-ontology.org/hpoweb/showterm?id=HP:0011902
Def: An elevated concentration in the blood of hemoglobin A2 (HbA2), which is a normal variant of hemoglobin A that consists of two alpha and two delta chains and is normally present at low levels in adults but may be increased in beta thalassemia.
xref: PMID:     26372049
