### ISSUE TITLE
Modifiers: relevance

### ISSUE THREAD

**Issue by buske** [obophenotype/human-phenotype-ontology#4821]
In the Clin/Pheno stream of the recent GA4GH meeting, we discussed the potential value of recording which phenotypic features are especially key or clinically distinctive in the patient.

It was proposed that this could be added as a modifier term to the HPO. There are many ways this could be implemented, but one would be to have a parent modifier along the lines of "distinction"/"distinctiveness"/"relevance", with a child term along the lines of "distinctive"/"important".

**Comment by pnrobinson** [comment]
@drseb @mellybelly @cmungall 
I like this suggestion. I would propose something like this
Clinical modifier
--Clinical relevance
----distinctive finding
----minor finding


There is no accepted clinical terminology for this AFAIK. Occasionally one sees major and minor finding (https://www.ncbi.nlm.nih.gov/pubmed/17163996). But I think that people use the words major and minor to refer to how common something is in a cohort, and not to the subjective impression that a certain feature is "distinctive" in a certain patient. I will ask colleagues at the Curating the Clinical Genome conference what they think about this also, but please add suggestions etc!

**Comment by drseb** [comment]
What about Orphanet's "pathognominic sign"?

**Comment by pnrobinson** [comment]
I think pathognomic can be used for the disease, but we are talking about a patient with an unknown diagnosis where the clinician thinks that say 3 of the 12 HPO terms are particularly important/characteristic. 
It also seems to be the case that Orphanet uses the term "pathognomonic" a lot, almost the majority of terms, and this is incorrect in my opinion.

**Comment by drseb** [comment]
A grep on "Pathognom" in "en_product4_HPO.xml" leads to 9 matches. Not sure where you are looking at. Can you explain?

**Comment by pnrobinson** [comment]
Sorry, I must have been thinking about something else. Is there also major/minor?

**Comment by drseb** [comment]
I guess you mean the field "<DiagnosticCriteria/>", which is present for every annotation, but usually empty. Not sure why they put this there.

However, I think you can go ahead and implement your idea, but we should think about how to xref to Orphanet or make an equivalence relation or something like this!? Not sure if the semantics are the same, because I don't know your exact definition and I don't know Orphanet's exact definition

**Comment by drseb** [comment]
@pnrobinson please check first draft

**Comment by pnrobinson** [comment]
I have updated the definitions a bit:

minor finding: In clinical parlance, findings are occasionally interpreted as being distinctive or minor, reflecting a subjective clinical impression of the importance of a feature for the differential diagnosis. A minor finding is taken to be one that is unlikely to help distinguish the correct diagnosis from other candidates in the differential.

distinctive finding: In clinical parlance, findings are occasionally interpreted as being distinctive or minor, reflecting a subjective clinical impression of the importance of a feature for the differential diagnosis. A minor finding is taken to be one that is likely to have high utility in distinguishing the correct diagnosis from other candidates in the differential.

@drseb @buske  -- please reopen if these definitions need more work!

**Comment by pnrobinson** [comment]
Also, definition for parent term:

Subontology for annotating phenotypic features as distinctive or minor findings in patients. The subontology is intended to be used to annotate subjective clinical impressions of whether a certain finding is important for the differential diagnosis.
