### ISSUE TITLE
Loinc 761-7:  "Neutrophils [#/volume] in Urine by Automated count"

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#4822]
Suggest creating a new term for Loinc: 761-7 [Neutrophils [#/volume] in Urine by Automated count] 
New term label: Abnormal neutrophil level in urine
New term comment (if any): Need parent term to pyuria for LOINC annotation
Your biocurator ID for loinc2hpo (if desired): JGM:lccarmody

**Comment by pnrobinson** [comment]
Since there is no "reduced urine neutrophil count" we only need a "Increased urine neutrophil count" term
