### ISSUE TITLE
Loinc 2695-5:  "Osmolality of Urine"

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#4824]
Suggest creating a new term for Loinc: 2695-5 [Osmolality of Urine] 
New term label: Abnormal osmolality of urine
New term comment (if any): Need a parent term to hyposthenuria. Also, need better organization of 
Your biocurator ID for loinc2hpo (if desired): JGM:lccarmody

**Comment by LCCarmody** [comment]
Had issue with the app, so didn't finish my thought. But Abnormality of urine homeostasis HP:0003110 is very poorly organized in general.

**Comment by pnrobinson** [comment]
@LCCarmody agree -- we should improve the hierarchy hand in hand with the new kidney terms

**Comment by pnrobinson** [comment]
I do not think we need a parent term -- there is no abnormally increased osmolality (it is a normal response to thirst). We should still work on the overall hierarchy.
