### ISSUE TITLE
HbS

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/human-phenotype-ontology#483]
sickle hemoglobin

Reported by: pnrobinson

Original Ticket: [obo/human-phenotype-requests/483](https://sourceforge.net/p/obo/human-phenotype-requests/483)

**Comment by pnrobinson** [comment]
Name HbS hemoglobin
Presence of an abnormal type of hemoglobin characterized by the subsitution of a glutamic acid residue at position 7 following the initial methionine residue by a valine (the mutation causative of sickle cell disease). The mutation promotes the polymerization of the HbS under conditions of low oxygen concentration. HbS can be identified by multiple methodologies including hemoglobin electrophoresis and high-performance liquid chromatography.

parent: http://www.human-phenotype-ontology.org/hpoweb/showterm?id=HP:0011902
xref:    PMID 3953566
