### ISSUE TITLE
Positive blood benzodiazepines test

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#4830]
Suggest creating a new term for Loinc: 42662-7 [Benzodiazepines [Presence] in Blood] 
New term label: Positive blood benzodiazepines test
New term comment (if any):
Your biocurator ID for loinc2hpo (if desired): HPO:nvasilevsky

**Comment by pnrobinson** [comment]
Let's not add drug tests to the HPO -- I think this is out of scope, or at least will require a lot more thought.
