### ISSUE TITLE
Suggest creating a new term for Loinc: 7790-9 [Burr cells [Presence] in Blood by Light microscopy] 

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#4831]
Suggest creating a new term for Loinc: 7790-9 [Burr cells [Presence] in Blood by Light microscopy] 
New term label: Presence of Burr cells in blood
Your biocurator ID for loinc2hpo (if desired): HPO:nvasilevsky

**Comment by pnrobinson** [comment]
http://www.bloodjournal.org/content/126/23/4540?sso-checked=true

**Comment by pnrobinson** [comment]
@nicolevasilevsky Adding as HP_0032519
