### ISSUE TITLE
question: annotations for calcium crystals

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#4832]
For these terms:
Loinc: 5775-2 [Calcium phosphate crystals [Presence] in Urine sediment by Light microscopy] 
Loinc: 5774-5 [Calcium oxalate crystals [Presence] in Urine sediment by Light microscopy] 
Loinc: 5773-7 [Calcium carbonate crystals [Presence] in Urine sediment by Light microscopy] 

could we annotate them as Hypercalciuria? Or should we create a new term(s)?

**Comment by pnrobinson** [comment]
These are subterms of crystalluria

https://www.ncbi.nlm.nih.gov/pubmed/3599249

**Comment by pnrobinson** [comment]
Adding all three terms, they can be annotated to the LOINC terms (e.g., HP_0020144).
