### ISSUE TITLE
NTR: congenital birth defect

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#4834]
**Preferred term label:**
congenital birth defect

I wonder why we don't already have a term like this, is this something we could add?

This is for a Kids First dataset, the description is "congenital birth defect". If we didn't add this term, I think the next closest term would be HP_0000118 Phenotypic abnormality?

**Comment by pnrobinson** [comment]
Birth defects are by definition congenital. This is so non-specific that it would not make a great term. I would suggest that we annotate to P_0000118 Phenotypic abnormality, onset Congenital, but the information carried by this annotation is extremely miniscule.

**Comment by nicolevasilevsky** [comment]
Got it, thanks for the feedback!
