### ISSUE TITLE
Revsion to mentions of Haemophilus H type B

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#4841]
Question:

Haemophilus H type B = Isn't it a better idea to mention Haemophilus influenzae type b (Hib)?

**Comment by pnrobinson** [comment]
This must be a typo, Haemophilus influenzae type b (Hib) is correct!

**Comment by drseb** [comment]
@nicolevasilevsky can you confirm?

**Comment by drseb** [comment]
Suggestions now:

- replace "Complete or near-complete absence of specific antibody response to **Haemophilus H type B** vaccine" with "Complete or near-complete absence of specific antibody response to **Haemophilus influenzae type b (Hib)** vaccine"
- replace "The inability to synthesize postvaccination antibodies against a **Haemophilus H type B**  antigen, as measured by antibody titer determination following vaccination." with "The inability to synthesize postvaccination antibodies against a **Haemophilus influenzae type b (Hib)** antigen, as measured by antibody titer determination following vaccination."
- replace "Partial absence of specific antibody response to **Haemophilus H type B** vaccine" with "Partial absence of specific antibody response to **Haemophilus influenzae type b (Hib)** vaccine"
- replace "A reduced ability to synthesize postvaccination antibodies against a **Haemophilus H type B** antigen, as measured by antibody titer determination following vaccination." with "A reduced ability to synthesize postvaccination antibodies against a **Haemophilus influenzae type b (Hib)** antigen, as measured by antibody titer determination following vaccination."

Anything to change for "Recurrent Haemophilus influenzae infections" (HP:0005376)??

**Comment by drseb** [comment]
This ticket is about the classes:

- HP:0005376
- HP:0410305
- HP:0410303

**Comment by drseb** [comment]
reported by @zafush

**Comment by nicolevasilevsky** [comment]
I agree with your suggested changes above @drseb

**Comment by nicolevasilevsky** [comment]
Add synonym to Recurrent Haemophilus influenzae infections" (HP:0005376): Recurrent H. influenzae infections
