### ISSUE TITLE
question about logical defs for calcified Anatomical Entity terms

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#4844]
should these terms follow the calcified anatomical entities pattern?
HP_0008420	Punctate vertebral calcifications
HP_0031051	Tarsal sclerosis

The pattern is:
equivalentTo:
  text: "'has_part' some ('calcified' and ('inheres_in' some %s) and ('has_modifier' some 'abnormal'))"
  vars:
    - anatomical_entity

@LCCarmody suggested revising the logical defs, respectively to:

**Punctate vertebral calcifications**
Should be similar to tarsal stipling "has part some (calcified and (inheres in some vertebra) and (has modifier some abnormal) and (has modifier some punctate))

**Tarsal sclerosis**
Need a Sclerosis pattern--but not sure this example is right "has part some (increased mass density and (inheres in some basicranium) and (has modifier some abnormal) and (has modifier some pathological))

**Comment by matentzn** [comment]
We have not yet started with double modifiers, but hs modifier punctuate is very unlikely to fly.. will raise at meeting today!

**Comment by nicolevasilevsky** [comment]
There are a lot of logical defs with double modifiers in HPO

**Comment by LCCarmody** [comment]
Yes.  I think we need to deal with them in some way--otherwise, two terms will end up with the same EQ or they should not have an EQ at all.

**Comment by pnrobinson** [comment]
The entities such as punctate (synonym stippled) need a separate modifer, I would say.
Note that tarsal refers to region in in the foot (http://purl.obolibrary.org/obo/UBERON_0009879, https://en.wikipedia.org/wiki/Tarsus_(skeleton)

 "has part some (increased mass density and (inheres in some ****tarsal skeleton******) and (has modifier some abnormal) and (has modifier some pathological))

**Comment by matentzn** [comment]
I think we need to clarify the lingo here: AFAICS [punctate](https://www.ebi.ac.uk/ols/ontologies/pato/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0001512) is a proper quality (surface has some kind of dots, holes or whatever). So is the case of *Punctate vertebral calcifications* perhaps better understood as 

```
has part some (calcified and punctate and (inheres in some vertebra) and (has modifier some abnormal))
```

Not sure yet about double qualities; we have never tried to really model those cases in uPheno. But I guess we could propose something like the above.

Peters example with abnormal and pathological is correct as is..

**Comment by matentzn** [comment]
@nicolevasilevsky @pnrobinson @drseb  Do you agree that punctate is a (morphological) quality rather than a modifier (a modifier is something like abnormal/normal/pathological, perhaps unilateral)?

**Comment by drseb** [comment]
I agree. But are we sure we're on the right track regarding modelling? IMHO we came up with the mod-punctate thing, because somebody wanted to (maybe) represent a weighting, i.e. first and foremost there is this calcification-problem (and everything with this calcification problem should be grouped together) and then there is this secondary "modifying quality", which is this punctated pattern. Can we analyse and discuss this? I do not feel like I know all the consequences this new modelling would have.

**Comment by matentzn** [comment]
I see. I would not be opposed to introducing a new relation to reflect the idea of 'secondary qualities'; I assume this will come up more and more now that we start tackling more complex phenotypes. I will raise this at the next meeting. Thanks for the clarification!

**Comment by drseb** [comment]
This was not a clarification :-) I was asking if I understood this correctly and it was in fact something like a "secondary quality". Probably best to hear from @pnrobinson

**Comment by pnrobinson** [comment]
Well, there's more than one way to do it, but I would vote for having a PATO term such as 'punctate-calcified'. If we are going to work on this, please let me know because there are many different morphologies of calcification and I would like to do a little research before we implemented this.

**Comment by matentzn** [comment]
@pnrobinson I am in principle in favour of that as well, but mindful of term proliferation. Can you give a very rough estimate of how many new calcifiedX or Xpunctate terms we might have to create to satisfy the HPO use case? are we talking dozens or hundreds?

**Comment by drseb** [comment]
I am not sure these combinations belong in PATO. Also, can we predetermine which inference we want to achieve and which solutions will lead to those? 

Another question: with a PATO-term 'punctate-calcified' you would have no weight. Does that mean you don't think the calcified should have a higher weight in this case?

**Comment by nicolevasilevsky** [comment]
I like the idea of secondary qualities, I agree it would be useful for modeling more complex phenotypes, there are a lot of examples in the HPO

**Comment by pnrobinson** [comment]
I am not sure we need to create new terms, but we may need to redefine existing ones.

**Comment by pnrobinson** [comment]
@nicolevasilevsky @matentzn @drseb  Can we make a decision about punctate? What is the status?

**Comment by matentzn** [comment]
Oh yes, fell of the radar. Thanks for the poke. Added to agenda, will come back to you about this in 6 days.

**Comment by pnrobinson** [comment]
@matentzn @nicolevasilevsky What is the status here?

**Comment by matentzn** [comment]
Unfortunately i can’t make a modelling decision right now :/ still not back to work (probably around 1. September). If this blocks you, I suggest keeping a list of the terms somewhere and not adding EQ logical definitions for now; we can add them later if we come up with a pattern. unless @dosumis has an idea how to do this properly?

**Comment by matentzn** [comment]
Cc @balhoff

**Comment by pnrobinson** [comment]
@nicolevasilevsky @matentzn @drseb what is the status here? 
We still have this
```
'has part' some 
    (calcified
     and ('inheres in' some vertebra)
     and ('has modifier' some abnormal))
```
and we need to add a clause like this
```
 and ('has modifier' some punctate)
```
There is now a PATO term called punctate
https://www.ebi.ac.uk/ols/ontologies/pato/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0001512
So I updated the definition to
```
'has part' some 
    (calcified
     and ('inheres in' some vertebra)
     and ('has modifier' some punctate)
     and ('has modifier' some abnormal))
```
I removed the (false) manual assertion that this is ectopic calcification.

**Comment by pnrobinson** [comment]
Tarsal sclerosis is currently defined as 
```
'has part' some 
    (calcified
     and ('inheres in' some 'tarsal bone')
     and ('has modifier' some abnormal))
```
This is not wrong but @LCCarmody suggestion is better (use increased density -- the cause of which is more calcium but this is not what the clinical term calcification is used for).

Other sclerosis terms seem to use MPATH
```
'has part' some 
    ('increased amount'
     and ('inheres in' some 
        (sclerosis
         and ('occurs in' some 'pedal digit 2 phalanx')))
     and ('has modifier' some abnormal))
```
This is fine with me, since we then have a central place to define what we mean with sclerosis.
I would most favor using the PATO increased mass density term (https://www.ebi.ac.uk/ols/ontologies/pato/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0001788)
```
'has part' some 
    ('increased mass density'
     and ('inheres in' some vertebra)
     and ('has modifier' some abnormal))
```
Can we make this decision? What else needs to happen to update the definitions -- can we DOSPD-ise this?

**Comment by matentzn** [comment]
```
'has part' some 
    ('increased mass density'
     and ('inheres in' some vertebra)
     and ('has modifier' some abnormal))
```

Is no problem according to the current patterns, so you can use this;

```
'has part' some 
    ('increased amount'
     and ('inheres in' some 
        (sclerosis
         and ('occurs in' some 'pedal digit 2 phalanx')))
     and ('has modifier' some abnormal))
```

--> we are trying to avoid pathological entities (from MPATH), unless they are necessary, to define our phenotype. Is there any way you could come up with a definition that uses a biological process (normal) rather than a pathological one?

Regarding the calcified/punctate discussion -> now I really (promise) put it on the meeting agenda to discuss this. Feel free to solve it in whatever way. The least controversial solution would be to create the calcified-punctate class in PATO, but yeah, for now, feel free to use whatever model to close the ticket - even if its a second modifier (has modifier some punctate). Maybe this will change, but there is no need for the ticket to stay open..

How many terms are affected by these modelling decisions? Just to judge whether we need to go all DOSDP on this one.

**Comment by pnrobinson** [comment]
@matentzn  There are tons of terms with sclerosis and various forms of calcification. Probably it would be good to have a DOSDP.
I do not understand why you say that the first definition in your comment is no problem so we can use the second definition :-0 ?

**Comment by matentzn** [comment]
I will come back to you on Friday about this! I need some help to determine the right answer :)

**Comment by dosumis** [comment]
Hi all,

I'm strongly inclined to support a pattern with 2 has_modifier clauses - at least for now.

e.g. 

calcifiedInlocationWithPattern

slots: 
 - location
 - pattern

has_part some ('calcified' and ('inheres_in' some 'vertebra') and ('has modifier' some punctate) and ('has modifier' some abnormal)

For sclerosis, wouldn't we be better having a PATO term 'sclerotic'?   We could then use the same pattern:

scleroticInlocationWithPattern
has_part some ('sclerotic' and ('inheres_in' some 'vertebra') and ('has modifier' some punctate) and ('has modifier' some abnormal)

**Comment by pnrobinson** [comment]
I agree with @dosumis suggestion. What about a new PATO term under structure?
https://www.ebi.ac.uk/ols/ontologies/pato/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0000141&viewMode=PreferredRoots&siblings=false

**Comment by matentzn** [comment]
We seem to have [punctate](https://www.ebi.ac.uk/ols/ontologies/pato/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0001512) and [calcified](https://www.ebi.ac.uk/ols/ontologies/pato/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0001447) (which also is under structure). Do we need any other terms in PATO?

**Comment by matentzn** [comment]
@pnrobinson in order to mass patternise, how can we identify (from the labels or something) all classes that should follow the `calcifiedAnatomicalEntityWithCalcificationPattern`? Any phenotype that contains the string "calcif*"?

**Comment by pnrobinson** [comment]
@matentzn  -- sounds like a plan -- if you send me an excel file I will check the entries. There are several different types of calcification we want to cover.

**Comment by pnrobinson** [comment]
This is a nice review.
https://insightsimaging.springeropen.com/articles/10.1007/s13244-018-0619-0
Probably OK to start off with punctate (I think we mean this is a synonym of stippled), calcified, linear calcification, ectopic calcification as patterns.

**Comment by matentzn** [comment]
@pnrobinson  @nicolevasilevsky  @LCCarmody I invited you to work on the calcification phenotypes here:
https://docs.google.com/spreadsheets/d/1IMSucZiqWYfPvp-m2x74IcE84xXV57mzz9rSNYZQLbc/edit#gid=0

Basically what I need to proceed:

1. an anatomical entity in every row C 
2. I dont care about D, but i suggest you also do that to make reviewing this easier
3. For punctate and similar calcification, fill in E (not for simple calcifications!)
4. Not necessary, but for transparency, I would like the pattern name in the G column. If too much work, no need!


What is in that table? 
1. Every phenotype that has "calcif" in the label
2. Every phenotype that currently matches ["calcifiedAnatomicalEntity" pattern ](https://raw.githubusercontent.com/obophenotype/upheno/master/src/patterns/dosdp-dev/calcifiedAnatomicalEntity.yaml)

So there will be some calcification phenotypes missing (those that don't have calcif in the name. If you see them when playing around, just add them to the table. Good luck and let me know when its done!

**Comment by LCCarmody** [comment]
@pnrobinson @nicolevasilevsky @matentzn I filled out as many as I could, mostly focusing on anatomy terms.  There were a few terms I had questions about so I either made a comment or put a question mark after it. I have a list of terms that don't really exist in Uberon which may need to be NTR. I'll paste below.

But, for patterns, there were a couple I made suggestions on, but I wasn't sure. First, should 'stippled' be punctate? It is a related synonym, so I used that.

Also, for 'diffuse', in PATO [distributed ](https://www.ebi.ac.uk/ols/ontologies/pato/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0001566&viewMode=PreferredRoots&siblings=false)is the term and diffuse is a synonym. So, that's what I suggested.  
Also, one term is 'hypocalcification' of enamel. I'm not sure about that, but maybe '[decreased distribution](https://www.ebi.ac.uk/ols/ontologies/pato/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0001672&viewMode=PreferredRoots&siblings=false)' would be appropriate?

FYI, are synonyms? and obsoleted?  The links don't seem to go anywhere.

HP:0033538 | Aortic annulus calcification
HP:0033640 | Aortic annular calcification



These are the suggested UBERON terms:  
Large arteries
medium-sized arteries
small arteries
peripheral arteries
lower extremity peripheral artery
middle cerebral artery
(tunica) media of large arteries
(tunica) media of medium-sized arteries
(tunica) media of small arteries
cranial artery (cranial blood vasculature as a parent)
cranial vein

**Comment by pnrobinson** [comment]
Thanks, Nicole!
I think we are treating punctate and stippled as synonyms as far as the logical defs are concerned.
'hypocalcification' of enamel. should be "reduced amount" rather than "reduced distribution"

HP:0033538 | Aortic annulus calcification
HP:0033640 | Aortic annular calcification
=> This seems to be a mistake, one of the terms needs to be obsoleted...I think I just added one and we have not released yet, @drseb can we just remove the new verion of Aortic annular calcification

**Comment by matentzn** [comment]
Looks you are all doing a great job.. I would recommend make one Uberon ticket for all new terms at once and share with @cmungall on slack to see which ones should terms - @nicolevasilevsky can do a single PR for them all and then we are sorted.

**Comment by nicolevasilevsky** [comment]
@LCCarmody are you going to make the Uberon NTRs?

**Comment by LCCarmody** [comment]
I guess I was confused at who was doing what. Are you an UBERON editor? I am not. I can make a ticket.

**Comment by dosumis** [comment]
> Are you an UBERON editor? I am not.

You can be if you like.

**Comment by LCCarmody** [comment]
Sure, as long as the PRs are reviewed by someone else.

**Comment by nicolevasilevsky** [comment]
Sounds great, thank you, Leigh! Someone will review the PRs before they are merged.

(I can edit Uberon too and can help if you run into any issues).

**Comment by LCCarmody** [comment]
good because terms like 'large arteries' will require some rearrangement and I'd like someone to check that work.

**Comment by LCCarmody** [comment]
I naively thought this would be easy, but according to this book chapter, top neuropathologistists 'had less than 50% agreement on the definition of small vessels' and 'the concept of large arteries and small vessels in the arterial classification are clinical, and not histological'. 

I am not sure I should continue with this?  @pnrobinson @cmungall 

[](url)
[arterysize.pdf](https://github.com/obophenotype/human-phenotype-ontology/files/5983014/arterysize.pdf)

**Comment by pnrobinson** [comment]
Hi everybody,
I think we should close these item, I do not think there are any additional action items and we have done what is possible.

**Comment by matentzn** [comment]
Wait this has been done? Are you sure? We have this huge spreadsheet that @LCCarmody was working on, and upon completion, I was supposed to merge all the revised definitions back in! Or did the plan change somehow?

**Comment by pnrobinson** [comment]
My misunderstanding possibly but I understood Leigh's last comment as saying it cannot/should not be done since we cannot distinguish between large and small. It might be good to close this issue and open a new one with the action item, I am confused here.

**Comment by matentzn** [comment]
This ticket has become too complicated and is now superseded by https://github.com/obophenotype/human-phenotype-ontology/issues/6877
