### ISSUE TITLE
Obliteration of frontal sinuses

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/human-phenotype-ontology#485]
Rethink term name and provide definition. See this OMIM entry, which is the only one that is annotated by the term  224300

Reported by: @pnrobinson 

Original Ticket: [obo/human-phenotype-requests/485](https://sourceforge.net/p/obo/human-phenotype-requests/485)

**Comment by drseb** [comment]
This ticket is related to https://github.com/monarch-initiative/HPO-UMLS-Integration/issues/11
