### ISSUE TITLE
Question re: 10371-3 Bite cells

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#4850]
LOINC has a code for Bite cells (10371-3)

These seem like abnormally shaped red blood cells: https://labtestsonline.org/glossary/bite-cells

Should we add a new term for this, or annotate up to HP_0001877 'Abnormal erythrocyte morphology'?

**Comment by pnrobinson** [comment]
These are https://en.wikipedia.org/wiki/Degmacyte

**Comment by nicolevasilevsky** [comment]
Ah, thanks! We don't have the term Degmacyte in HPO, should we add it?

**Comment by nicolevasilevsky** [comment]
pinging @pnrobinson

**Comment by pnrobinson** [comment]
label: Bite cells
syn: Degmacytes, Blister cells
def: red cells that appear to have parts of them bitten away. 
comment: This feature can be observed with acute hemolytic anemia (AHA) related to glucose-6-phosphate dehydrogenase (G6PD) deficiency. In this disorder, AHA can be triggered by ingestion of fave beans, infections, and certain medications. The blood film can show poikilocytosis with bite cells.
ISBN:978-0-07174889-6

**Comment by pnrobinson** [comment]
added term
