### ISSUE TITLE
NTR: 708-8 Blasts [#/​volume] in Blood by Manual count

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#4851]
LOIC has: 708-8 | Blasts [#/​volume] in Blood by Manual count

According to https://s.details.loinc.org/LOINC/708-8.html, Blast cells are precursors of white blood cells and are normally found in bone marrow. The presence of blasts in the peripheral blood is a marker for hematologic malignancy.

Should we add a new term?

**Comment by pnrobinson** [comment]
This is 
https://hpo.jax.org/app/browse/term/HP:0032372
I am adding another synonym. @nicolevasilevsky

**Comment by nicolevasilevsky** [comment]
Thanks!
