### ISSUE TITLE
question about LOINC Cardiolipin IgG Ab

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#4852]
There are these codes in LOINC:
8065-5	Cardiolipin IgG Ab [Units/volume] in Serum or Plasma
3182-3	Cardiolipin IgM Ab [Units/volume] in Serum by Immunoassay

Should we add new terms to HPO?

**Comment by pnrobinson** [comment]
HP_0020136 and HP_0020137
