### ISSUE TITLE
NTR: Choriogonadotropin

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#4854]
LOINC has codes:
2119-6 Choriogonadotropin [Moles/volume] in Serum or Plasma
2106-3 Choriogonadotropin (pregnancy test) [Presence] in Urine

Do we want to add these terms to HPO? Or mark these unable to annotate?

**Comment by pnrobinson** [comment]
AFAIK Choriogonadotropin  is mainly used as a pregancy test and so is out of scope.

**Comment by nicolevasilevsky** [comment]
thanks!
