### ISSUE TITLE
NTR: Reptilase time

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#4855]
There is the LOINC:
6683-7 Reptilase time

https://details.loinc.org/LOINC/6683-7.html
The Reptilase Clotting Time measures the conversion of fibrinogen to fibrin by snake venom Reptilase (Atroxin). The enzyme is similar to thrombin, but unlike thrombin, is not affected by the presence of heparin. It measures the availability of functional fibrinogen. It is sometimes used in lupus anticoagulant screening, along with thrombin time, as a reflex test if any of the screening test results are out of range in order to detect the presence of non-heparin anticoagulants, dysfibrogenemia, or hypofibrogenemia.

Should we add a new term or mark this as unable to annotate?

**Comment by pnrobinson** [comment]
https://www.ncbi.nlm.nih.gov/pubmed/23546720

**Comment by pnrobinson** [comment]
@nicolevasilevsky adding as HP_0020193
