### ISSUE TITLE
Merge??

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/human-phenotype-ontology#486]
Should we merge:
Abnormality of the eye
Abnormality of the ocular region

If not, structure has to be checked: see children eyebrow, eyelid, ...
This seems confusing.

Reported by: drseb

Original Ticket: [obo/human-phenotype-requests/486](https://sourceforge.net/p/obo/human-phenotype-requests/486)

**Comment by pnrobinson** [comment]
I do not think that Abnormality of the eye and Abnormality of the ocular region should be merged. It would be better to check the structure and revise as necessary!

**Comment by drseb** [comment]
Ok. Lets revise this section ASAP.

**Comment by mellybelly** [comment]
I agree these are not the same thing, in Uberon we define craniofacial regions and have: 
eye part_ of some ocular region 
also @markengelstad can make suggestions

**Comment by markengelstad** [comment]
I agree with you all.
Eye is useful
Ocular region is useful

But the 2 are distinct classes

**Comment by drseb** [comment]
The idea was not really to merge, but rather to improve the structure.
