### ISSUE TITLE
Pyuria

### ISSUE THREAD

**Issue by jpgourdine** [obophenotype/human-phenotype-ontology#4862]
**HPO term**
Pyuria

**Suggested revision of textual definition**

Presence of an increased number of leukocytes in the urine, a positive result on Gram’s staining of an unspun urine specimen, or a urinary dipstick test that is positive for leukocyte esterase.

PMID: 26061855
https://www.nejm.org/doi/10.1056/NEJMra1410052

This could clear up also @LCCarmody 's [ticket ](https://github.com/obophenotype/human-phenotype-ontology/issues/4822)

**Comment by pnrobinson** [comment]
added definition and reference, thanks
