### ISSUE TITLE
HPO web link broken

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#4864]
Link is broken to ICHPT data. See https://hpo.jax.org/app/help/mapping

**Comment by pnrobinson** [comment]
The IRDIRC site seems to have been down for the last two weeks (our link previously was correct). Hopefully IRDiRC is not going out of business, I will contact Kym.

**Comment by pnrobinson** [comment]
It looks like the URL has changed to http://www.irdirc.org/?s=ichpt
We will update this inthe next release

**Comment by pnrobinson** [comment]
I have transfered this issue to the hpo-web tracker.
