### ISSUE TITLE
Textual definition suggestion for Abnormal lung lobation HP_0002101: Lobes vs. lobules

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#4867]
**HPO term**
Abnormal lung lobation HP_0002101

**Suggested revision of textual definition**
Current definition: Defects in the formation of pulmonary lobules. 
Suggested: Defects in the formation of pulmonary lobes.

Source
"The distinction between lobes and lobules is arbitrary; lobes are evident upon gross inspection while lobules are evident to low power microscopy." http://www.siumed.edu/~dking2/intro/glands.htm#5

Either the textual definition needs to change or the logical definition need to change. THe logical definition is: has part some (quality and (inheres in some lung lobe formation) and (has modifier some abnormal))

**Comment by pnrobinson** [comment]
agree
