### ISSUE TITLE
Redirect HP purls to JAX browser?

### ISSUE THREAD

**Issue by matentzn** [obophenotype/human-phenotype-ontology#4879]
@pnrobinson @drseb 

Was thinking that it would be cool to have HP iris [redirect to JAX term browser rather than ontobee](https://github.com/OBOFoundry/purl.obolibrary.org/issues/530); 

What do you think?

**Comment by drseb** [comment]
Totally in favor of that. Never understood this ontobee-decision. Maybe @cmungall knows more. If not, a new redirect would be good!

**Comment by mellybelly** [comment]
I think they should go to the Jax browser also (though for ontology geeks, ontobee is a better way to navigate the ontology, but not for the average joe).

**Comment by pnrobinson** [comment]
Yes, please redirect to the JAX browser! Ontobee is pretty awesome, but we do display much more information that will be of interest to most users!

**Comment by pnrobinson** [comment]
@matentzn Can we implement this? What else needs to be done?

**Comment by matentzn** [comment]
@pnrobinson I [poked again](https://github.com/OBOFoundry/purl.obolibrary.org/issues/530) to get the instructions on how to do this.

**Comment by matentzn** [comment]
Done! 

http://purl.obolibrary.org/obo/HP_0002715
