### ISSUE TITLE
DIAB ontology new term suggestions

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/human-phenotype-ontology#488]
At the moment , the DIAB ontology is composed of both MP and HP terms,
mainly HP terms, MP terms have been used to cover terminology absent from
HP. To use PhenoDigm, we need to use only terms from one ontology. We have
mapped 124 MP terms to HP using both  manual and automatic curation
approaches.
Automatic curation involved mapping directly MP to HP using OWL sim
algorithm and manual curation did involve direct manual mapping and
assessment of the automatic approach.

I have created a google page to represent the results and facilitate
further editing, if you have issues accessing it , please let me know.

https://docs.google.com/spreadsheets/d/1Qaicnpxum-4f0vM_S2fv4WvOdMaJH1YkUizu65phQ8A/edit#gid=733779127

please use ONLY the spreadsheet named MP->HP for Peter-August2015 for editing

Reported by: @pnrobinson 

Original Ticket: [obo/human-phenotype-requests/488](https://sourceforge.net/p/obo/human-phenotype-requests/488)

**Comment by pnrobinson** [comment]
I have transferred all term requests that seemed applicable to clinical medicine to the main tracker and am closing this issue.
