### ISSUE TITLE
HP_0100368 is anonymous?

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#4882]
**HPO term**
HP_0100368

**Bug description**
What does this property mean? Is this a bug or is it intentional?
```
  "basicPropertyValues" : [ {
          "pred" : "http://www.geneontology.org/formats/oboInOwl#hasOBONamespace",
          "val" : "human_phenotype"
        }, {
          "pred" : "http://www.geneontology.org/formats/oboInOwl#is_anonymous",
          "val" : "true"
        } ]
```

**Comment by pnrobinson** [comment]
@drseb @matentzn --So I am assuming that this is a mistake and I am removing the "is anonymous" -true annotation from HP_0100368 and HP:0010999 -- the only two terms that have this annotation. I think that it must be a mistake. We should add this to our Q/C. I am picking this up with JSON based Q/C, and wonder if we should add that to our pipeline after the software has gotten more mature. It seems a little easier. 
Please reopen this issue if we need to keep is_anonymous for some reason.

**Comment by drseb** [comment]
yes. please remove these. not sure where these come from
