### ISSUE TITLE
QC for permitted and required annotations on HP classes

### ISSUE THREAD

**Issue by matentzn** [obophenotype/human-phenotype-ontology#4885]
Regarding the use of weird, [unexpected](https://github.com/obophenotype/human-phenotype-ontology/issues/4882) properties.

Rather than making a QC just for this above case, why not define a proper QC test that: 

1) checks for the presence of all required annotations (we have that, mostly, because only label is really required, but we could be more strict like requiring a definition and and created_by at some point)
2) checks that only *legal annotations* are used, say label, definition, comment, db:xref and so on. 

Here is a breakdown of currently existing annotations on HP classes:

| annotation | count |
| --------- | ---------- |
| http://www.w3.org/2000/01/rdf-schema#label | 14734 |
| http://www.geneontology.org/formats/oboInOwl#hasDbXref | 11687 |
| http://www.geneontology.org/formats/oboInOwl#id | 10657 |
| http://www.geneontology.org/formats/oboInOwl#hasOBONamespace | 10441 |
| http://www.geneontology.org/formats/oboInOwl#hasExactSynonym | 8109 |
| http://www.geneontology.org/formats/oboInOwl#created_by | 7906 |
| http://www.geneontology.org/formats/oboInOwl#creation_date | 4908 |
| http://www.w3.org/2000/01/rdf-schema#comment | 2905 |
| http://purl.org/dc/elements/1.1/date | 2649 |
| http://www.geneontology.org/formats/oboInOwl#hasAlternativeId | 1898 |
| http://www.geneontology.org/formats/oboInOwl#hasRelatedSynonym | 963 |
| http://www.geneontology.org/formats/oboInOwl#inSubset | 846 |
| http://www.geneontology.org/formats/oboInOwl#hasBroadSynonym | 320 |
| http://www.w3.org/2002/07/owl#deprecated | 242 |
| http://www.geneontology.org/formats/oboInOwl#hasNarrowSynonym | 199 |
| http://www.geneontology.org/formats/oboInOwl#consider | 71 |
| http://purl.org/dc/elements/1.1/contributor | 2 |
| http://www.geneontology.org/formats/oboInOwl#is_anonymous | 2 |
| http://purl.obolibrary.org/obo/hsapdv#editor_notes | 1 |

**Comment by drseb** [comment]
what do you mean by "database schema check"?

**Comment by matentzn** [comment]
I removed that comparison. Sorry for being confusing. This could simply be a check for cases were wrong annotation properties were used on HP classes unintentionally.

**Comment by pnrobinson** [comment]
Why do we need http://purl.org/dc/elements/1.1/date in addition to creation_date?

**Comment by drseb** [comment]
Because some people use _creation_date_ and others (*cough*) use _dc_date_ ... we need a decision. what does GO use? What does MP use?

**Comment by matentzn** [comment]
MP uses both but this seems to be unprincipled (i.e. they are used to mean the same thing, like here). @cmungall might have an opinion which one to use, and then we can move everyone to only use that one.

Another observation: we could simply automate the creation of id; there is no reason not to have 100% coverage.

**Comment by matentzn** [comment]
(I updated the list to include only HP classes, not HP properties)

**Comment by matentzn** [comment]
- Same that you said for date goes for hasAlternativeId and Id
- hasOBONamespace should also be automated.

**Comment by sbello** [comment]
I suspect the MP has both because of history rather than on going differences. Anna and I both use the automated new entities Metadata settings in the preferences menu in Protege. This automatically uses dc:date as the annotation. Prior to using the preferences settings we were all over the place.
Same situation goes for the addition of the creator annotation. We now have the preferences set to always add the creator's orcid.

**Comment by drseb** [comment]
alternative Id and Id are different

**Comment by LCCarmody** [comment]
I *think* I do the same as @sbello.  My preferences look like they do on the HPO editors' guide wiki: https://github.com/obophenotype/human-phenotype-ontology/wiki/Editors'-Guide

**Comment by pnrobinson** [comment]
@matentzn  Is there a remaining action item? Can this issue be closed?

**Comment by drseb** [comment]
I have added a lot of these checks to hpo-qc. I think we can close

**Comment by pnrobinson** [comment]
Thanks! @matentzn please reopen if necessary!
