### ISSUE TITLE
Please fix text definition

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#4887]
**HPO term**

"Erythroid dysplasia"

**Suggested revision of textual definition**

Is now: 

> Dysplasia in the erythroid lineage, which presents with a variety of morphological changes in the bone marrow, including nuclear budding or irregular nuclear contour in erythroblasts. In peripheral blood.

What should be done with the final "sentence"?

**Comment by pnrobinson** [comment]
We can delete "In peripheral blood"
