### ISSUE TITLE
about or around in textdef of Excyclotropia?

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#4889]
**HPO term**

Excyclotropia

**Suggested revision of textual definition**

replace **about** with **around**?

**Comment by pnrobinson** [comment]
"about" can be used with the meaning of "around" (encircling). I believe this is more common in the UK than in the US. While about is not incorrect, I agree with Seb that "around" is a better word choice in this instance.

**Comment by drseb** [comment]
thanks a lot!
