### ISSUE TITLE
Definition of "Chronic constipation"

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#4891]
**HPO term**

Chronic constipation

**Suggested revision of textual definition**

A german textbook defines it using "within last 6 months over a period of at least 12 weeks"

Why was the current definition chosen? (" ... for longer than three months ...")

**Comment by pnrobinson** [comment]
I think that there is no standard definition of this in terms of time. Here, for instance, they write "several weeks or longer" https://www.mayoclinic.org/diseases-conditions/constipation/symptoms-causes/syc-20354253.

This paper mentions criteria with 3 months:
https://www.ncbi.nlm.nih.gov/pubmed/28530898
Let's see if we can improve the definition a little though

**Comment by drseb** [comment]
If there is no generally accepted defintion, I don't think we need to improve something. We will follow the german definition for the german translation though. Thanks.
