### ISSUE TITLE
abort the expression ‘aborted sudden death’ ?

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#4894]
**HPO term**

HP:0031628 (Aborted sudden cardiac death)

**Reason for deprecation**

https://doi.org/10.1016/j.ijcard.2016.02.159

**Suggested replacement or term to consider**

???

**Comment by pnrobinson** [comment]
Despite this article, I think the term remains in common use. One synonym is sudden cardiac arrest, we should add that or possibly make it the primary label.

**Comment by pnrobinson** [comment]
I have added this as a synonym. This is a valid term
