### ISSUE TITLE
Merge patchy baldness terms?

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#4895]
What is the difference between "Patchy alopecia" and "alopecia areata" ?

If there is a difference, can we add a textual definition to make this clear?
If not, can we merge?

**Comment by pnrobinson** [comment]
Good pickup. I think these are synonyms, but this article seems to think there is a difference (subclassification). I will research this.

**Comment by pnrobinson** [comment]
merged terms.
