### ISSUE TITLE
HP_0040176 Abnormal level of phospholipids

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#4896]
**HPO term**
HP_0040176 Abnormal level of phospholipids

**Suggested revision of logical definition**
The current logical def is:

'has part' some 
    ('increased amount'
     and ('inheres in' some phospholipid)
     and ('has modifier' some abnormal))

Could we either revise the logical def to:

'has part' some 
    ('concentration of'
     and ('inheres in' some phospholipid)
     and ('has modifier' some abnormal))

Or revise the label to 'increased level of phospholipids"

(If we do the latter, we should reclassify this term)

**Comment by pnrobinson** [comment]
@matentzn @nicolevasilevsky @drseb  I do not think it is a good idea to distinguish between amount and concentration in the logical definitions. At the level of our modeling with OWL etc, there is no difference between the two, and sometimes this is just the difference of how we can measure some metabolite. The same comment applies for enzyme activity and level and concentration.

Note the current label is Abnormal circulating phospholipid concentration

**Comment by matentzn** [comment]
I agree with Peter; Are we also ok with using amount instead of concentration in the logical definitions in general (throughout HPO)?

**Comment by drseb** [comment]
@matentzn no. not throughout HPO. Maybe throughout all microscopic and submicroscopic entities, but still I would like to see a list of suggested revisions. 

e.g. _amount_ of **hair**/**teeth** should be _amount_ and not _concentration_.

**Comment by drseb** [comment]
but even for cells I would prefer amount.

**Comment by matentzn** [comment]
@drseb You know i dont really care what we do; its more that we do it consistently across all organisms. Can you then maybe add a comment [here](https://github.com/obophenotype/upheno/issues/334) indicating clearly under what circumstances we need to use concentration, and under what circumstances we should use amount (level), so that we can scope the patterns for the rest of the community appropriately?

**Comment by pnrobinson** [comment]
I should say I agree with Seb and my suggestion was to unify logical definitions ONLY for the amount/level/concentration of metabolites in blood, urine, CSF

**Comment by nicolevasilevsky** [comment]
Are we in agreement to use 'amount' (and 'increased amount', 'decreased amount') for metabolites, blood, urine, CSF?

The term HP_0040176 'Abnormal circulating phospholipid concentration' currently has the logical def:

'has part' some 
    (**'increased amount'**
     and ('inheres in' some phospholipid)
     and ('has modifier' some abnormal))

Shouldn't it be:
'has part' some 
    (**amount**
     and ('inheres in' some phospholipid)
     and ('has modifier' some abnormal))

**Comment by drseb** [comment]
So the idea would be to use amount for everything?

**Comment by nicolevasilevsky** [comment]
I think so?

**Comment by nicolevasilevsky** [comment]
Per our conversation today (with @drseb and @matentzn), I added this to the file abnormalConcentrationOfChemicalEntity.tsv
