### ISSUE TITLE
Question re: HP_0000140 Abnormality of the menstrual cycle

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#4897]
**HPO term**
HP_0000140 Abnormality of the menstrual cycle

** Question** 
There is a parent term HP_0000858 'Menstrual irregularites'- There is no textual definition, but maybe it should be a child of 'Abnormality of menstrual cycle' or possibly a broad synonym?  

Leigh noted that HP_0000858 has a strange logical definition using towards:'has part' some 
    ('irregular rhythm'
     and (towards some menstruation)
     and ('has modifier' some abnormal))"

**Comment by pnrobinson** [comment]
I think this subsection needs to be refactored slightly. There is 1. onset 2. frequency 2a. Abnormal periodicity 3. amount 4. pain

**Comment by pnrobinson** [comment]
HP:0000858 is used directly to annotate the following diseases
```
OMIM:110100	BLEPHAROPHIMOSIS, PTOSIS, AND EPICANTHUS INVERSUS		HP:0000858	OMIM:110100	IEA					P	HPO:iea[2009-02-17]
OMIM:101800	ACRODYSOSTOSIS		HP:0000858	OMIM:101800	TAS					P	HPO:probinson[2009-02-17]
OMIM:615962	#615962 GLUCOCORTICOID RESISTANCE, GENERALIZED;;GLUCOCORTICOID RECEPTOR DEFICIENCY;;GCCR DEFICIENCY;;GCR DEFICIENCY;;GRL DEFICIENCY;;CORTISOL RESISTANCE FROM GLUCOCORTICOID RECEPTOR DEFECTHP:0000858	OMIM:615962	TAS		HP:0040283			P	HPO:skoehler[2014-10-06]
OMIM:203800	ALSTROM SYNDROME		HP:0000858	OMIM:203800	IEA					P	HPO:iea[2009-02-17]
OMIM:311360	PREMATURE OVARIAN FAILURE 1		HP:0000858	OMIM:311360	IEA					P	HPO:iea[2009-02-17]
OMIM:216400	COCKAYNE SYNDROME, TYPE A		HP:0000858	OMIM:216400	TAS					P	HPO:skoehler[2009-02-17]
OMIM:616831	LUSCAN-LUMISH SYNDROME		HP:0000858	PMID:24852293	PCS					P	HPO:probinson[2017-06-17]
```
I think the best thing is to make these annotations more specific.

**Comment by pnrobinson** [comment]
I think that Menstrual irregularities needs to be renamed to Irregular menses and made a child of 
Abnormality of the menstrual cycle.
def: Abnormally high variation in the amount of time between periods.
comment: Most women have between 11 and 13 menstrual periods each year. Bleeding usually lasts around 5 days (range: 2 to 7 days). When menstruation first starts, it can take up to 2 years to establish a regular cycle. After puberty, most women’s menstruation is regular. The length of time between each period is similar. The normal menstrual cycle length is 28 days +/- 7 days with the menstruation lasting between 2 and 7 days. It can take up to 2 years from menarche to develop a mature hypothalamic-pituitary-gonadal (HPG) axis. Within 1 year, 75% of girls have a cycle between 21 and 45 days. By the fifth gynecological year, 90% of girls will have regular cycles with 75% having ovulatory cycles. 

PMID:29323693
