### ISSUE TITLE
Question: HP_0011922 Abnormal activity of mitochondrial respiratory chain

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#4898]
**HPO term**
HP_0011922 Abnormal activity of mitochondrial respiratory chain

**Suggested revision of logical definition**
This logical def uses GO_0005746 mitochondrial respirasome, which is a cellular component.

Could we revise it to:

'has part' some 
    (quality
     and ('inheres in' some 
        ('metabolic process'
         and ('occurs in' some 'mitochondrial respirasome')))
     and ('has modifier' some abnormal))

Or is there a GO biological process term we should use? (I don't see one, but could someone else check?)

**Comment by pnrobinson** [comment]
This seems correct to me

**Comment by nicolevasilevsky** [comment]
great, I'll update this

**Comment by nicolevasilevsky** [comment]
I think this should actually be:

'has part' some
('**process** quality'
and ('inheres in' some
('metabolic process'
and ('occurs in' some 'mitochondrial respirasome')))
and ('has modifier' some abnormal))

I update this as such.
