### ISSUE TITLE
Revise logical def for HP_0012535	Abnormal synaptic transmission

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#4899]
**HPO term**
HP_0012535	Abnormal synaptic transmission

**Suggested revision of logical definition**
'has part' some 
    ('process quality'
     and ('inheres in' some 'chemical synaptic transmission')
     and ('has modifier' some abnormal))

GO_0007268 chemical synaptic transmission

**Comment by pnrobinson** [comment]
This seems correct to me.

**Comment by nicolevasilevsky** [comment]
Ok great! I'll update this.
