### ISSUE TITLE
question re: logical def HP_0010945 Fetal pyelectasis

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#4900]
**HPO term**
HP_0010945 Fetal pyelectasis

**Suggested revision of logical definition**
The logical def for this term does not capture the text def.  It is dialation of renal pelvis and it is fetal as well. Should we leave it as is?

'has part' some 
    ('increased size'
     and ('inheres in' some 'renal pelvis')
     and ('has modifier' some abnormal))

(Note to self, if yes, add to abnormallyIncreasedSizeOfAnatomicalEntity.tsv file, see [spreadsheet](https://docs.google.com/spreadsheets/d/1GlZoh4kSi_xyv-m2obNdrntCg3WtB2bb58kG6w34pZc/edit#gid=713435893))

**Comment by pnrobinson** [comment]
This is a characteristic finding on fetal ultrasound. The definition should have something about the time period

**Comment by nicolevasilevsky** [comment]
I don't know if we can capture the time period in the logical definition, can we?

Should we leave it as is?

**Comment by nicolevasilevsky** [comment]
I added this to the TSV: abnormallyIncreasedSizeOfAnatomicalEntity, it will use this pattern

**Comment by nicolevasilevsky** [comment]
The text definition describes the fetal aspect:
Mild pyelectasis is defined as a hypoechoic spherical or elliptical space within the renal pelvis that measures at least 5mm and not more than 10 mm. The measurement is taken on a transverse section through the fetal renal pelvis using the maximum anterior-to-posterior measurement.
