### ISSUE TITLE
Revise logical def for HP_0040195 Decreased head circumference

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#4901]
**HPO term**
HP_0040195 Decreased head circumference

**Suggested revision of logical definition**
'has part' some 
    ('decreased circumference'
     and ('inheres in' some head)
     and ('has modifier' some abnormal))

**Comment by pnrobinson** [comment]
This is a matter of degree, medlically, but the terms are important to have.

**Comment by nicolevasilevsky** [comment]
I'm just suggesting revising the logical definition, does this revision look okay?

**Comment by pnrobinson** [comment]
Looks good, I changed the def.
