### ISSUE TITLE
Definitions for alopecia, atrichia, hypotrichia

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#4903]
https://jamanetwork.com/journals/jamadermatology/fullarticle/479599

**Comment by LCCarmody** [comment]
@nicolevasilevsky @matentzn This is the first time I've added a term to HP with a pattern.  I added it to AbnormallyDecreasedNumberOfAnatomicalEntity in the TODO list.  I think it is correct but wanted to make sure I did it correctly.
http://purl.obolibrary.org/obo/HP_0500262 | Atrichia | http://purl.obolibrary.org/obo/CL_0002559 | hair follicle cell
-- | -- | -- | --

**Comment by matentzn** [comment]
From a technical perspective its great! Thanks!

**Comment by LCCarmody** [comment]
Thanks, then closing.

**Comment by pnrobinson** [comment]
But did we update the textual definitions? I think this subsection required a little TLC?

**Comment by LCCarmody** [comment]
Yes, I used the definitions from the paper (and xref) and added the new term Atrichia.

**Comment by pnrobinson** [comment]
OK, so we can close!
