### ISSUE TITLE
Please revise textdef of HP:0030158 (Cervical ectropion)

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#4911]
**HPO term**

HP:0030158 (Cervical ectropion)

**Suggested revision of textual definition**

Very hard to read and not really understandable by our translators:

_Eversion of the endocervix with protrusion of the central (endocervical) columnar epithelium through the external os of the cervis into the vaginal milieu_

Make it two sentences? Add a few words?

**Comment by pnrobinson** [comment]
done
