### ISSUE TITLE
Illegal equivalent classes in HP

### ISSUE THREAD

**Issue by matentzn** [obophenotype/human-phenotype-ontology#4915]
@nicolevasilevsky This is a bit of a priority issue; remember, if there is no solution, one of the EQs has to go.

- [x] http://purl.obolibrary.org/obo/HP_0001166	Arachnodactyly http://purl.obolibrary.org/obo/HP_0100807	Long fingers (the latter is the super-class but inheres in a more specific term)
- [x] http://purl.obolibrary.org/obo/HP_0001626	Abnormality of the cardiovascular system	http://purl.obolibrary.org/obo/HP_0030680	Abnormality of cardiovascular system morphology (former has the wrong quality, should be just `quality`)
- [x] http://purl.obolibrary.org/obo/HP_0001842	Foot acroosteolysis	http://purl.obolibrary.org/obo/HP_0010177	Osteolytic defects of the phalanges of the toes (the latter is the super-class but inheres in a more specific term, but probably both EQs are wrong as they inhere in phenotypes)
- [x] http://purl.obolibrary.org/obo/HP_0002037	Inflammation of the large intestine	http://purl.obolibrary.org/obo/HP_0002583	Colitis (see next)
- [x] http://purl.obolibrary.org/obo/HP_0002583	Colitis	http://purl.obolibrary.org/obo/HP_0004387	Enterocolitis (the former is the super-class but inheres in a more specific term; if latter is fixed, all equivalences are removed)
- [x] http://purl.obolibrary.org/obo/HP_0007485	Absence of subcutaneous fat	http://purl.obolibrary.org/obo/HP_0007519	Lack of subcutaneous fatty tissue  ('part of' some 'multicellular organism' is redundant, so the two are exactly the same)
- [x] http://purl.obolibrary.org/obo/HP_0009815	Aplasia/hypoplasia of the extremities	http://purl.obolibrary.org/obo/HP_0045060	Aplasia/hypoplasia involving bones of the extremities (identical defs)
- [x] http://purl.obolibrary.org/obo/HP_0010945	Fetal pyelectasis	http://purl.obolibrary.org/obo/HP_0010946	Dilatation of the renal pelvis (interesting case, problem with PATO?)
- [x] http://purl.obolibrary.org/obo/HP_0040065	Abnormal morphology of bones of the upper limbs	http://purl.obolibrary.org/obo/HP_0040070	Abnormal upper limb bone morphology (identical defs)
- [x] http://purl.obolibrary.org/obo/HP_0040066	Abnormal morphology of bones of the lower limbs	http://purl.obolibrary.org/obo/HP_0040069 Abnormal lower limb bone morphology (identical defs)

**Comment by nicolevasilevsky** [comment]
Re: 'Osteolytic defects of the phalanges of the toes' and 'Foot acroosteolysis' - 'Foot acroosteolysis' seems more general than 'Osteolytic defects of the phalanges of the toes'. Should 'Foot acroosteolysis' be the parent of 'Osteolytic defects of the phalanges of the toes'?

We could add the logical def to 'Foot acroosteolysis':
'has part' some 
(Osteolysis and ('inheres in' some 'skeleton of pes') and ('has modifier' some abnormal))

**Comment by nicolevasilevsky** [comment]
these two terms seem like duplicates, I think they should be merged:
http://purl.obolibrary.org/obo/HP_0007485	Absence of subcutaneous fat http://purl.obolibrary.org/obo/HP_0007519	Lack of subcutaneous fatty tissue

**Comment by nicolevasilevsky** [comment]
I think HP_0004387 Enterocolitis is a more general term than its parent class  HP_0002583 Colitis. Enterocolitis is defined as:

An inflammation of the colon and small intestine. However, most conditions are either categorized as Enteritis (inflammation of the small intestine) or Colitis (inflammation of the large intestine).

Colitis is defined as:
Colitis refers to an inflammation of the colon and is often used to describe an inflammation of the large intestine (colon, cecum and rectum). Colitides may be acute and self-limited or chronic, and broadly fit into the category of digestive diseases.

Should Enterocolitis be a parent of Colitis?

**Comment by nicolevasilevsky** [comment]
I think these two terms are the same and should be merged:
http://purl.obolibrary.org/obo/HP_0009815	Aplasia/hypoplasia of the extremities http://purl.obolibrary.org/obo/HP_0045060	Aplasia/hypoplasia involving bones of the extremities

**Comment by nicolevasilevsky** [comment]
I think these two terms are the same and should be merged:
http://purl.obolibrary.org/obo/HP_0040065	Abnormal morphology of bones of the upper limbs http://purl.obolibrary.org/obo/HP_0040070	Abnormal upper limb bone morphology

**Comment by nicolevasilevsky** [comment]
I think these two terms are the same and should be merged:
http://purl.obolibrary.org/obo/HP_0040066	Abnormal morphology of bones of the lower limbs http://purl.obolibrary.org/obo/HP_0040069 Abnormal lower limb bone morphology

**Comment by nicolevasilevsky** [comment]
I did all these revisions on a PR
@drseb and @matentzn

**Comment by matentzn** [comment]
I am not opposed to the solution, but its better I am not involved in content discussions.. Maybe lets leave this to @drseb :P

**Comment by drseb** [comment]
I am going to move the merge requests to different tickets, okay?

**Comment by drseb** [comment]
@matentzn can you give more detail on what you are opposed to?

**Comment by matentzn** [comment]
Oh, I am NOT opposed to anything! I did not see anything wrong with the solution. :)

**Comment by drseb** [comment]
Ah okay. Thanks @matentzn

**Comment by matentzn** [comment]
I will re-open when necessary.
