### ISSUE TITLE
Merge 2 extremities-terms

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#4919]
I think these two terms are the same and should be merged:

http://purl.obolibrary.org/obo/HP_0009815	Aplasia/hypoplasia of the extremities http://purl.obolibrary.org/obo/HP_0045060	Aplasia/hypoplasia involving bones of the extremities

by @nicolevasilevsky

**Comment by drseb** [comment]
waiting for approval by @pnrobinson

**Comment by pnrobinson** [comment]
I do not think we can merge these. The extremities include muscle etc and not just bones. These are grouping terms and so we do need both!.

**Comment by drseb** [comment]
ok. @nicolevasilevsky , please delete the wrong logical def then. thanks
