### ISSUE TITLE
HPO browser: access?

### ISSUE THREAD

**Issue by diannafisk** [obophenotype/human-phenotype-ontology#492]
I'm not sure if this is the correct forum for this, but I am having trouble accessing the new HPO browser.

I am on a mac and have tried using both chrome and safari. With chrome I eventually got this message:
Proxy Error
The proxy server received an invalid response from an upstream server
The proxy server could not handle the request Post/hpoweb/showterm.

Reason: Error reading from remote server
Apache/2.2.16 (Debian) Server at www.human-phenotype-ontology.org Port 80

If this isn't the proper forum to report this issue, I'd deeply appreciate having someone point me in the right direction.

Thanks!

-Dianna

**Comment by drseb** [comment]
We are really sorry for the inconveniences. We are having some problems with the setup of a new server that hosts this service. It should run now.

Thank you for reporting this issue!
Sebastian

**Comment by diannafisk** [comment]
Thanks, Sebastian! All good now. It'll take some time to get used to this new tool, but I can already say that I really like the download option.

-Dianna

**Comment by drseb** [comment]
Keep posting issues and feature requests here. Thanks.
