### ISSUE TITLE
"upper limbs" and "lower limbs" terms: two merge-cases

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#4920]
I think these two terms are the same and should be merged:
http://purl.obolibrary.org/obo/HP_0040065	Abnormal morphology of bones of the upper limbs http://purl.obolibrary.org/obo/HP_0040070	Abnormal upper limb bone morphology

I think these two terms are the same and should be merged:
http://purl.obolibrary.org/obo/HP_0040066	Abnormal morphology of bones of the lower limbs http://purl.obolibrary.org/obo/HP_0040069 Abnormal lower limb bone morphology

by @nicolevasilevsky

**Comment by drseb** [comment]
second related commit is this: https://github.com/obophenotype/human-phenotype-ontology/commit/98a279499cdf74075f352f413ba03eb47b3123cd

**Comment by drseb** [comment]
for now all travis tests seem to have passed. I hope I did nothing wrong. Class merging is really an annoying and time-intensive task. We need to think about optimising this process somehow (any ideas welcome: @pnrobinson @cmungall @matentzn)

**Comment by pnrobinson** [comment]
Thanks! I think it would be good to collaborate on the obo editor plugin for protege to automatize this. Unfortunately, I was not able to get the plugin even to work and I expect it will be even harder as Java moves away from Java 8. For better or worse, I think we have a good standard operating procedure for doing this manually in Protege that is annoying and error prone, but our Q/C pipeline does a great job in catching those errors.
