### ISSUE TITLE
definition of HP:0040314 (Blind vagina)

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#4921]
**HPO term**

definition of HP:0040314 (Blind vagina)

**Suggested revision of textual definition**

the term "female reproductive canal" is a bit strange? perhaps replacing it with "tract" would be more fitting?

(submitted by emily)

**Comment by LCCarmody** [comment]
I think canal is commonly used to describe the vagina.  This definition seems okay to me, but others can comment.

**Comment by drseb** [comment]
ok. if nobody objects, we leave the def as it is. thanks

**Comment by pnrobinson** [comment]
I agree canal is correct
