### ISSUE TITLE
Tidy up xrefs and document them

### ISSUE THREAD

**Issue by cmungall** [obophenotype/human-phenotype-ontology#4923]
```
$ grep ^xref: ../../hp.obo | cut -f2 -d : | count-occ.pl | mysort -k1 -n
1        http
1        MeSH
1        RGD
1        HP
1        DOID
2        DOI
3        ICD-9
3        ICD-O
4        MPATH
5        PMID
6        ORPHA
10       MP
13       EPCC
22       pmid
38       ICD-10
93       MEDDRA
216      NCIT
222      Fyler
2175     MSH
4672     SNOMEDCT_US
13058    UMLS
```

 - [ ] add a check to ensure each prefix is registered, and the correct casing is used 
 - [ ] only allow certain kinds; e.g. disallow pmid, PMID, RGD
 - [ ] manually vet these
 - [ ] for every prefix, document it's intent, semantics (e.g. can be treated as equivalent? ore closely related to?) estimated completeness, process for updates
      - why do we have 10 MPs, 1 RGD?
      - why only 3 ICD-Os? Either we map all neoplasm terms or none
      - disallow HP xrefs. Why do we have 1 HP xref?
 - [ ] populate a subset of xrefs semi-automatically via MONDO
      - MONDO xrefs are up to date and annotated with semantics
      - there is a non-trivial overlap between HP and MONDO where we maintain xrefs that mean something like "not equivalent but 1:1, where the disease is the cognate of the phenotype"
      - chain the above two to populate

No need to write new code here, we can port metadata standards and workflow from MONDO

Related HP tickets:

 - #4276
 - #3580 loinc
 - #2673 - standard prefixes

**Comment by LCCarmody** [comment]
Happy to help, but I am not exactly sure I understand this entirely.
What does 'registering' a prefix mean?
I can find (and correct the HP reference), but I am confused by the PMIDs.  Following the other tickets, do you mean class level xrefs? Not sure how to find these using Protege, but maybe there is something I am missing.

**Comment by cmungall** [comment]
I mean class-level xrefs.

I don't know the best way of finding in Protege. You could do a SPARQL query. You could also just type the prefix followed by ':' in the search window. But I think the appropriate workflow is we first build the report that is detailed enough for you to work from.

**Comment by matentzn** [comment]
@LCCarmody if you need help with this, ping me on slack. Nice educational example of how you can use robot/sparql.

**Comment by matentzn** [comment]
I made a sorted list of all xrefs [here](https://github.com/obophenotype/human-phenotype-ontology/blob/master/src/ontology/reports/hp_xrefs.csv), sorted. If you want to regenerate this list:

```
cd src/ontology
sh run.sh make reports/hp_xrefs.csv -B
```

Maybe this helps. +1 on getting rid of MP, RGD, DOID, and documenting this all better. Once all this is done, maybe we can just export the xrefs table into csv form as part of the release process, potentially even broken down by source (xrefs_mesh.csv, xrefs_icd10.csv), if this is of interest. I would take only a few minutes to bake this into the HPO release process.

**Comment by LCCarmody** [comment]
Also commented on https://github.com/obophenotype/human-phenotype-ontology/issues/2673

Follow up here: Did we decide on standards? MSH vs. MESH and SNOMEDCT vs. SCTID

**Comment by LCCarmody** [comment]
Deleted class xrefs for pmid, PMID, HP, RGD, MeSH, http, and DOI and added them to xrefs for definitions and/or comments where necessary.  HP xref seemed to be a mistake so deleted.  
Did not check others.  Fixed the case for PMID in definition and comment annotations.

As for MP, it looks like they are just indicating that it is the same or very similar term.  These are old terms (c. 2011).

**Comment by cmungall** [comment]
ROBOT ticket here: https://github.com/ontodev/robot/issues/561

**Comment by pnrobinson** [comment]
@LCCarmody @matentzn is there a remaining open action item or can we close this issue?

**Comment by matentzn** [comment]
Let's close this and re-open if it becomes necessary!
