### ISSUE TITLE
HPO release has incorrect version IRI

### ISSUE THREAD

**Issue by balhoff** [obophenotype/human-phenotype-ontology#4926]
The current release of HPO has version IRI `http://purl.obolibrary.org/obo/hp/releases/2019-06-17`. It should instead be something like `http://purl.obolibrary.org/obo/hp/releases/2019-06-17/hp.owl` (which doesn't resolve).

The previous release seems to also have a bad version IRI: `http://purl.obolibrary.org/obo/hp/releases/2019-06-03`. If the filename is appended to this, it does resolve: `http://purl.obolibrary.org/obo/hp/releases/2019-06-03/hp.owl`

**Comment by balhoff** [comment]
cc @matentzn

**Comment by matentzn** [comment]
@drseb Ping me before next release! Easy fix.

**Comment by drseb** [comment]
thanks @balhoff and @matentzn
