### ISSUE TITLE
Synonym wrong in HP:0004453

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#4934]
**HPO term**

HP:0004453

**Bug description**

I removed "Reduced anterior-posterior diameter of vertebral bodies" from the term "Overfolding of the superior helices". Please move it to its appropriate place if needed.

**Comment by pnrobinson** [comment]
Thanks for picking up this error.
"Reduced anterior-posterior diameter of vertebral bodies" should be a synonym of https://hpo.jax.org/app/browse/term/HP:0008473. I will add it there.
