### ISSUE TITLE
New term requests for Kids First

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#4941]
@pnrobinson for the Kids First project, we are doing a mapping of HPO terms to diseases/phenotypes in this [spreadsheet](https://docs.google.com/spreadsheets/d/1CtHiUkwoKczB1noWDudkLekakgaH1NjR/edit#gid=1005596767)

There are number of new term requests, I am going to list them below:
- [x] Abnormal bulbus cordis (the description in the dataset is: Bulbus cordis anomalies)

- [x] Colloid Cyst. Reference: https://www.ncbi.nlm.nih.gov/books/NBK470314/

- [x] Is branchial cleft sinus the same as branchial sinus? If yes, could we add this as a synonym?

- [x] Could we add 'abnormal reductive brain morphology' as a subclass of HP:0012443 abnormal brain morphology. (The phenotype in the dataset is: Congenital reduction deformities of brain)

- [x] Would HP include 'vascular harmartoma'? (it is in NCIT: http://purl.obolibrary.org/obo/NCIT_C3438 )

cc @theoriste

**Comment by pnrobinson** [comment]
branchial cleft sinus the same as branchial sinus? YES. added

**Comment by pnrobinson** [comment]
I do not think that 'abnormal reductive brain morphology' is a great term because it is used as a hodgepodge that does not fit well with an ontology, e.g., https://www.unboundmedicine.com/icd/view/ICD-10-CM/889164/all/Q04_3___Other_reduction_deformities_of_brain

**Comment by pnrobinson** [comment]
added all terms except 'abnormal reductive brain morphology'
