### ISSUE TITLE
Annotations file does not seem to match documentation

### ISSUE THREAD

**Issue by pdl** [obophenotype/human-phenotype-ontology#4946]
The documentation of the columns of the annotation file at https://hpo.jax.org/app/help/annotations does not seem to correspond to the columns of the file http://compbio.charite.de/jenkins/job/hpo.annotations/lastStableBuild/artifact/misc/phenotype_annotation.tab linked to from https://hpo.jax.org/app/download/annotation

The file columns look like this:

```
$head -1 phenotype_annotation.tab | sed 's/\t/ \n/g' | nl
     1  DECIPHER
     2  1
     3  Wolf-Hirschhorn Syndrome
     4
     5  HP:0000252
     6  DECIPHER:1
     7  IEA
     8
     9
    10
    11  P
    12  WOLF-HIRSCHHORN SYNDROME
    13  HPO:skoehler
```

But the documentation says there are 14 columns, the last three being Aspect, Date_created, Assigned_by.

**Comment by pnrobinson** [comment]
Sorry for the confusion. We are transition to the new format described here
https://www.ncbi.nlm.nih.gov/pubmed/30476213
It can be downloaded here
http://compbio.charite.de/jenkins/job/hpo.annotations.current/
phenotype.hpoa
