### ISSUE TITLE
Synonym questionable?

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#4948]
**HPO term**

Congenital earlobe sinuses

**Bug description**

This term has "posterior wedging" as synonym. All other "wedging" terms seem related to "vertebral wedging". 
Is this synonym correct? @pnrobinson

**Comment by pnrobinson** [comment]
This does indeed seem to be a mistake. 
https://hpo.jax.org/app/browse/term/HP:0004461 needs a better definition.
posterior wedging should go to https://hpo.jax.org/app/browse/term/HP:0008444
I will work on this

**Comment by drseb** [comment]
Thanks. Please close when you're finished

**Comment by LCCarmody** [comment]
Is 'Congenital earlobe sinuses" the same as Preauricular sinus https://hpo.jax.org/app/browse/term/HP:0004467 ?

**Comment by pnrobinson** [comment]
@LCCarmody earlobe is on the earlobe but preauricular refers to the area right in front of the ears, so these are not synonyms.

**Comment by pnrobinson** [comment]
fixed
