### ISSUE TITLE
Review synonyms for HP_0000010 Recurrent urinary tract infections

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#4950]
**HPO term**
HP_0000010 Recurrent urinary tract infections

@pnrobinson there is a ticket in Mondo (https://github.com/monarch-initiative/mondo/issues/841) that asked whether HP_0000010 'Recurrent urinary tract infections' should be a dbxref for MONDO:0005247 'urinary tract infection (disease), as the Mondo disease is not recurrent.

@cmungall was wondering if the EXACT synonym scopes are correct for HP_0000010

```
id: obo:HP_0000010
name: Recurrent urinary tract infections
def: "Repeated infections of the urinary tract." [HPO:probinson]
synonym: "Recurrent UTIs" EXACT http://purl.obolibrary.org/obo/HP_0045077 []
synonym: "Urinary infection" EXACT layperson []
synonym: "Urinary tract infection" EXACT layperson []
synonym: "Urinary tract infections" EXACT layperson []
synonym: "Urinary tract infections, recurrent" EXACT layperson [HPO:skoehler]
synonym: "Frequent urinary tract infections" EXACT layperson []
```
Do you think we should make the synonyms Urinary infection, Urinary tract infection, Urinary tract infections broad synonyms instead?

(see https://github.com/monarch-initiative/mondo/pull/846)

**Comment by pnrobinson** [comment]
@nicolevasilevsky  The HPO term is referring to a medical history of recurrent UTIs, which can be a sign of an immune defect or other problem. It does not refer to an individual instance of an infection, which is an acute disease that should be referred to with a MONDO term. 
I am therefore going to remove this synonym
synonym: "Urinary infection" EXACT layperson []
the others are correct.
