### ISSUE TITLE
Unsatisfiable classes referencing CHEBI roles

### ISSUE THREAD

**Issue by balhoff** [obophenotype/human-phenotype-ontology#4952]
There are a number of HPO classes that are unsatisfiable when HPO is combined with RO, CHEBI, and GO:

- 'Abnormal CSF amino acid level' - _this class has been obsoleted_

_**these classes do not have a logical def**_
- 'Abnormal CSF glucose level' 
- 'Decreased CSF 5-hydroxyindolacetic acid' 
- 'Decreased CSF homovanillic acid'
- 'Increased CSF interferon alpha'
- 'Phenylpyruvic acidemia'
- Propionicacidemia
- Hypoglycorrhachia
- Hyperglycorrhachia

_**the terms below are using Chebi classes that are molecular entities:**_
- 'Abnormal CSF biopterin level'
- 'Abnormal CSF dopamine level'
- 'Abnormal CSF lactate level'
- 'Abnormal CSF neopterin level'
- 'Abnormal CSF urate concentration'
- 'D-2-hydroxyglutaric acidemia'
- 'Decreased CSF biopterin level'
- 'Decreased CSF neopterin level'
- 'Decreased level of erythritol in CSF'
- 'Dicarboxylic acidemia'
- 'Elevated CSF biopterin level'
- 'Elevated CSF dopamine level'
- 'Elevated CSF neopterin level'
- 'Glutaric acidemia'
- 'Increased CSF lactate'
- 'Increased CSF urate concentration'
- 'Reduced CSF dopamine level'
- 'Methylmalonic acidemia'
- 'Increased level of D-threitol in CSF'
- 'L-2-hydroxyglutaric acidemia'
- 'Low CSF 5-methyltetrahydrofolate'
- 'Reduced CSF lactate'

_**NV: I updated the logical def for these terms:**_
- 'Abnormal CSF metabolite level'
- Alkalemia
- Acidemia

All the ones I checked have to do with using the term `metabolite` as a material entity; however it is a `biological role`. Needs to be replaced with `'chemical entity' and 'has role' some metabolite`.

**Comment by balhoff** [comment]
cc @matentzn

**Comment by matentzn** [comment]
Oh that's a nice ticket, thanks; @nicolevasilevsky and I will take care of it on Wednesday, and make a pattern. So are you saying that given an EQ like:

[Abnormal CSF metabolite level:
](https://www.ebi.ac.uk/ols/ontologies/hp/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FHP_0025454)

```
has part some (
    amount and 
    inheres in some (
        metabolite and 
        part of some cerebrospinal fluid) and 
    has modifier some abnormal)
```

it should in  fact be:


```
has part some (
    amount and 
    inheres in some (
        cerebrospinal fluid and 
        has role some 'metabolite') and 
    has modifier some abnormal)
```

This seems somehow not the intention; I have no idea of biology, but it seems that in everyday parlance, a metabolite could be referred to as a  a material entity (Google says: "a substance formed in or necessary for metabolism.").

**Comment by pnrobinson** [comment]
Well, in the real world a metabolite IS a material entity. Why does this make the class unsatisfiable in the OWL world?

**Comment by matentzn** [comment]
Someone at CHEBI decided it is a biological role instead of a material entity.. MAybe we can find out why and use another class..

**Comment by pnrobinson** [comment]
A metabolite is a chemical (molecule). The role metabolite indicates that the molecule was created by processes of metabolism (and not say, by synthesis in a factory). In the HPO definitions, we are not modeling the provenance of the molecules and so the role is not important. The HPO definition does not appear to be wrong -- but there might be some situations in the future where we will want to reason that metabolites are molecules? Probably ok as is.

**Comment by balhoff** [comment]
It's just that CHEBI has this term (and some others like 'hormone') in a separate hierarchy. The way you use them as chemicals is to make an expression `'chemical entity and 'has role' some metabolite`. The resulting concept is the chemical you want. It has to be changed for reasoning to work.

@matentzn it should be like this:

```
'has part' some (
    amount and 
    'inheres in' some (
        ('chemical entity' and 'has role' some metabolite) and 
        'part of' some 'cerebrospinal fluid') and 
    has modifier some abnormal)
```

See for example the logical definition of [Decreased circulating androgen level](http://purl.obolibrary.org/obo/HP_0030349).

I have set up a daily Jenkins job for a bunch of ontologies that I'm trying to keep consistent. Hopefully it will catch this kind of stuff early on. At the moment it uses release versions, but it would be better to make it build base files from `master` of each ontology and merge those.

**Comment by pnrobinson** [comment]
@balhoff  -- this definition "feels right" to me.

**Comment by matentzn** [comment]
Alright, we will create a pattern for this; @nicolevasilevsky would you mind giving it a shot? I think an appropriate level of generality would be:

- abnormal[ChemicalEntity](http://purl.obolibrary.org/obo/CHEBI_24431)With[Role](http://purl.obolibrary.org/obo/CHEBI_50906) 
- abnormalChemicalEntityWith[Role](http://purl.obolibrary.org/obo/CHEBI_50906)InLocation 

After this is done we will assign all of the definitions above to that pattern.

**Comment by matentzn** [comment]
(I think I prefer chemical entity to be a slot, variable rather than hard backed into the pattern)

**Comment by matentzn** [comment]
@balhoff can you please take a look at:

http://purl.obolibrary.org/obo/upheno/patterns-dev/abnormallyIncreasedLevelOfChemicalEntityWithRoleInLocation.yaml

Nicole has created the analogous patterns for:
- abnormalLevelOfChemicalEntityWithRoleInLocation
- abnormalLevelOfChemicalEntityWithRole
- abnormallyDecreasedLevelOfChemicalEntityWithRoleInLocation
- abnormallyDecreasedLevelOfChemicalEntityWithRole
- abnormallyIncreasedLevelOfChemicalEntityWithRoleInLocation
- abnormallyIncreasedLevelOfChemicalEntityWithRole

Thanks.

**Comment by balhoff** [comment]
That looks good to me.

**Comment by nicolevasilevsky** [comment]
@matentzn asked me to work on this. I think my action item is to update the logical defs for the terms above. I am going to work on this now

**Comment by matentzn** [comment]
Thanks Nicole. yeah I am also starting to hit downstream problems because of the current pattern. With our new one, it will all be well!

**Comment by nicolevasilevsky** [comment]
@matentzn I revised the logical def for three terms that were using Chebi role terms:

- 'Abnormal CSF metabolite level'
- Alkalemia
- Acidemia

**Comment by nicolevasilevsky** [comment]
The rest of the classes listed above were either:
1. obsolete
2. did not have a logical def (maybe they did at one point?)
3. The chebi class is classified as a molecular entity. _In this case, is the logical def okay? Or should it be revised to conform to the role pattern above?_

**Comment by matentzn** [comment]
All ok!! Perfect thanks Nicole!

**Comment by matentzn** [comment]
As long as no metabolites are used with inheres in, I am happy.

**Comment by matentzn** [comment]
(And no chebi roles are connected to anything else with part of)

**Comment by nicolevasilevsky** [comment]
I think it should be good now, but let me know if I missed anything

**Comment by matentzn** [comment]
Re-open if necessary.
