### ISSUE TITLE
are HP_0000581 and HP_0045025 the same?

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#4964]
HP_0000581 Blepharophimosis
**Text def:** A fixed reduction in the vertical distance between the upper and lower eyelids with short palpebral fissures.
**Logical def:**
'has part' some 
    ('decreased width'
     and ('inheres in' some 'palpebral fissure')
     and ('has modifier' some abnormal))

HP_0045025 'Narrow palpebral fissure'
**text def**: Reduction in the vertical distance between the upper and lower eyelids.
**Logical def:**
'has part' some 
    ('decreased size'
     and ('inheres in' some 'palpebral fissure')
     and ('has modifier' some abnormal))

I had suggested to @drseb that we use 'decreased width' for 'Narrow palpebral fissure', but that would make it equivalent to HP_0000581 Blepharophimosis.

Do we need both of these terms, or should they be merged?

**Comment by pnrobinson** [comment]
I think that 'Narrow palpebral fissure' might have a mistaken text definition (horizontal rather than vertical). I will check on the annotated diseases.

**Comment by pnrobinson** [comment]
Check this again. HPO has long and short PFs and also narrow, this appears redundant, but we will need to check the annotated diseases.

**Comment by pnrobinson** [comment]
Blepharophimosis is distinct.
We can extend the comment a bit as here: https://onlinelibrary.wiley.com/doi/full/10.1002/ajmg.a.32597

I think Narrow=Short/Short Palpebral Fissure = Narrow eye opening.
I will check some of the annotated diseases to be sure of this.

**Comment by pnrobinson** [comment]
@nicolevasilevsky @drseb  @matentzn The logical def of blepharophimosis needs to be something like this -- can we construct something?

```
'has part' some
('decreased width' and `decreased height`
and ('inheres in' some 'palpebral fissure')
and ('has modifier' some abnormal))
```

**Comment by matentzn** [comment]
What information does this definition convey that `decreased size` does not? Just more specific? (I am just asking, not suggesting anything :)

**Comment by pnrobinson** [comment]
The definition says decreased width and decreased height. decreased size can be anything, including just decreased width.

**Comment by matentzn** [comment]
ok. I have added it to the meeting agenda next week; its a valid case and we will need to solve it.

**Comment by pnrobinson** [comment]
Wiedemann Steiner syndrome has vertically narrow palpebral fissures (https://onlinelibrary.wiley.com/doi/abs/10.1111/cge.12586). On the other hand, velocardial syndrome has short palpebral fissues (horizontal). I think this will require manual annotation of all of the annotated diseases. I will try to see if the group of annotated diseases has a preponderance of one or the other orientation.

**Comment by nicolevasilevsky** [comment]
terms are being added to PATO:
https://github.com/pato-ontology/pato/issues/300

**Comment by matentzn** [comment]
done. Can be used now.

**Comment by nicolevasilevsky** [comment]
I can take care of this
