### ISSUE TITLE
format for ORCIDs

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#4966]
What is the preferred format for ORCIDs as dbxrefs? It is still inconsistent in HPO (although this ticket says it was fixed https://github.com/obophenotype/human-phenotype-ontology/issues/2409)

Should we use the full URL? ie https://orcid.org/0000-0001-5208-3432?

**Comment by nicolevasilevsky** [comment]
we should add this to the editors guide when we have decided

https://github.com/obophenotype/human-phenotype-ontology/wiki/Editors'-Guide

**Comment by pnrobinson** [comment]
Could we settle on CURIE type identifiers? This will make it consistent and easier to parse, and if we ever need the URL it can be generated trivially.

**Comment by nicolevasilevsky** [comment]
so it would be:
ORCID:0000-0001-5208-3432

?

**Comment by pnrobinson** [comment]
yes!

**Comment by nicolevasilevsky** [comment]
ok, thanks! I updated the editors guide, and I will do this going forward

**Comment by sbello** [comment]
@nicolevasilevsky When you use the protege settings to add ORCID for the creator it goes in as ORCID:orcid.org/0000-0003-4606-0597 Do you care if the formatting is different for creator vs dbxref?

**Comment by nicolevasilevsky** [comment]
good question @sbello 
@pnrobinson what are your thoughts?

**Comment by pnrobinson** [comment]
This is one of the several weakness of using Protege as an ontology editor -- it is difficult to constrain choices globally, leading to lots of inconsistencies. I wonder if the easiest thing would be to just run some Q/C script over HPO to take care of all of these formats somehow. If we use ORCID for attributions for definitions or terms, then this format seems even more error prone than ORCID:xyz. How does the MP team deal with this?

**Comment by drseb** [comment]
Todo for @drseb : check if qc does this

**Comment by pnrobinson** [comment]
I am not sure if there is an open action item here other than that protege is not doing what we need it to do. Can we close?

**Comment by nicolevasilevsky** [comment]
sure, let's close
