### ISSUE TITLE
A term for carrier status?

### ISSUE THREAD

**Issue by callahantiff** [obophenotype/human-phenotype-ontology#4969]
I was hoping I could ask for advice on how to best map HPO concepts to clinical codes that reference a phenotype and a specific type of genetic carrier status (examples included below):
- [Carrier state, disease not expressed](https://bioportal.bioontology.org/ontologies/SNOMEDCT/?p=classes&conceptid=http%3A%2F%2Fpurl.bioontology.org%2Fontology%2FSNOMEDCT%2F24800002&jump_to_nav=true)
- [Carrier of hereditary factor VIII deficiency disease](https://bioportal.bioontology.org/ontologies/SNOMEDCT/?p=classes&conceptid=http%3A%2F%2Fpurl.bioontology.org%2Fontology%2FSNOMEDCT%2F234441009&jump_to_nav=true)  
- [Carrier of cystic fibrosis gene mutation](https://bioportal.bioontology.org/ontologies/SNOMEDCT/?p=classes&conceptid=http%3A%2F%2Fpurl.bioontology.org%2Fontology%2FSNOMEDCT%2F441520002&jump_to_nav=true)     

I apologize if I there is an existing term that I missed, but when exploring the ontology over the last few days I was unable to find a good fit. I didn't want to open a NTR without first getting your opinion, but am happy to add that information if needed.

Thanks so much for your advice! 🙏 🙇‍♀

**Comment by nicolevasilevsky** [comment]
@callahantiff I am not sure.

@pnrobinson do you have any advice for Tiffany? Would these be suitable terms for HPO?

**Comment by pnrobinson** [comment]
@callahantiff  I would suggest using these HPO terms for the clinical status
https://hpo.jax.org/app/browse/term/HP:0032319
The HPO avoids referring to the genetic status and this should be coded separately!

**Comment by callahantiff** [comment]
> @callahantiff I would suggest using these HPO terms for the clinical status
> https://hpo.jax.org/app/browse/term/HP:0032319
> The HPO avoids referring to the genetic status and this should be coded separately!

That works for me, thank you! 👍
