### ISSUE TITLE
HP:0011972 (Hypoglycorrhachia) contradictory synonyms

### ISSUE THREAD

**Issue by roland-ewald** [obophenotype/human-phenotype-ontology#4972]
[`HP:0011972` (Hypoglycorrhachia)](https://hpo.jax.org/app/browse/term/HP:0011972)

**Bug description**

`HP:0011972` has two seemingly contradictory synonyms:
- `Increased CSF glucose`
- `Decreased CSF glucose`

```owl
<owl:Class rdf:about="http://purl.obolibrary.org/obo/HP_0011972">
        <rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/HP_0031884"/>
        <obo:IAO_0000115 rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Abnormally low glucose concentration in the cerebrospinal fluid.</obo:IAO_0000115>
<!-- ... -->
        <oboInOwl:hasExactSynonym rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Decreased CSF glucose</oboInOwl:hasExactSynonym>
        <oboInOwl:hasExactSynonym>Increased CSF glucose</oboInOwl:hasExactSynonym>
<!-- ... -->
```

(also see the [MSeqDR browser](https://mseqdr.org/hpo_browser.php?11972;))

**Suggestion**

Associate `Increased CSF glucose` with [`HP:0031885`  (`Hyp-er-lycorrhachia`)](https://hpo.jax.org/app/browse/term/HP:0031885) instead.

**Comment by drseb** [comment]
Thanks. Fixed it.

**Comment by roland-ewald** [comment]
@drseb thanks for the quick fix!

**Comment by drseb** [comment]
@roland-ewald unfortunately you will have to wait until the next release to see this in the artefacts

**Comment by roland-ewald** [comment]
@drseb Sure, no worries. Thankfully HPO gets released regularly! :+1:
