### ISSUE TITLE
Label / synonym duplications

### ISSUE THREAD

**Issue by tudorgroza** [obophenotype/human-phenotype-ontology#4975]
Below is a list of pairs of terms that share at least one common label / synonym. The pairs will most likely appear at least twice in the list (because of the bi-directional mapping) - apologies for this. I took into account only labels and exact synonyms (including exact layperson synonyms).

- [x] HP:0002015 => Swallowing difficulties
 HP:0200136 => Difficulty swallowing

- [x] HP:0004281 => Increased bone density in hand bones
HP:0004054 => Increased bone density in hand bone

- [x] HP:0009444 => Patchy sclerosis of middle finger phalanges
HP:0009848 => Patchy sclerosis of middle phalanx of finger

- [x] HP:0002705 => Palate high-arched
HP:0000218 => High, arched palate

- [x] HP:0008422 => Vertebral wedging
HP:0004568 => Wedged vertebrae

- [x] HP:0005736 => Short shinbone
HP:0006436 => Shortening of the shinbone

- [x] HP:0011675 => Arrhythmia
HP:0031546 => Cardiac conduction abnormality

- [x] HP:0005736 => Short tibia
HP:0006436 => Shortening of the tibia

- [x] HP:0011675 => Cardiac conduction abnormalities
HP:0031546 => Cardiac conduction abnormality

- [x] HP:0100649 => Tumor of mouth
HP:0012290 => Mouth tumor

- [x] HP:0012804 => Corneal ulceration
HP:0000495 => Corneal ulcerations

- [x] HP:0045055 => Tiger tail banding
HP:0032461 => Tiger-tail banding

- [x] HP:0009004 => Underdeveloped muscle
HP:0003199 => Underdeveloped muscles

- [x] HP:0010711 => Webbed first and second toes
HP:0005767 => Webbed 1st-2nd toes

- [x] HP:0009702 => Carpal bone fusion
HP:0005048 => Fusion of carpal bones

- [x] HP:0001911 => Abnormality of neutrophil
HP:0001874 => Abnormality of neutrophils

- [x] HP:0009611 => Notched outermost bone of the thumb
HP:0005848 => Notched outermost bone of thumb

- [x] HP:0100222 => Speckled calcifications in end part of the innermost bone of the little toe
HP:0100233 => Speckled calcifications in the end part of the innermost bone of the little toe

- [x] HP:0009334 => Abnormality of the end part of the middle bone of the middle finger
HP:0009320 => Abnormality of end part of the middle bone of the middle finger

- [x] HP:0008798 => Widened sacrosciatic notch
HP:0010457 => Widening of the sacrosciatic notch

- [x] HP:0001977 => Abnormal blood clot
HP:0001928 => Abnormal blood clotting

- [x] HP:0012804 => Corneal ulceration
HP:0000495 => Corneal ulcerations

- [x] HP:0000278 => Retrognathia of lower jaw
HP:0000347 => Lower jaw retrognathia

- [x] HP:0009477 => Fused innermost and middle bone of index finger
HP:0009579 => Fused innermost and middle index finger bones

- [x] HP:0009441 => Bullet-shaped bones of middle finger
HP:0009845 => Bullet-shaped middle finger bones

- [x] HP:0008066 => Blisters
HP:0200037 => Blister

- [x] HP:0025319 => Neovascularization of the iris
HP:0011497 => Iris neovascularization

- [x] HP:0009611 => Bifid distal phalanx of the thumb
HP:0005848 => Bifid thumb distal phalanx

- [x] HP:0009198 => Abnormality of end part of the innermost bone of the pinkie finger
HP:0009153 => Abnormality of end part of the innermost bone of pinky finger

- [x] HP:0009606 => Duplication of distal thumb phalanx
HP:0009612 => Duplication of the distal phalanx of the thumb

- [x] HP:0007811 => Nystagmus, congenital horizontal
HP:0007859 => Congenital horizontal nystagmus

- [x] HP:0001627 => Cardiac abnormality
HP:0001626 => Cardiac anomaly

- [x] HP:0010049 => Shortened long bone of hand
HP:0005720 => Shortened long bones of hand

- [x] HP:0000065 => Enlargement of the vaginal lips
HP:0012882 => Enlarged vaginal lips 

- [x] HP:0009334 => Abnormality of the end part of the middle bone of the middle finger
HP:0009320 => Abnormality of end part of the middle bone of the middle finger

- [x] HP:0009702 => Carpal bone fusion
HP:0005048 => Fusion of carpal bones

- [x] HP:0006110 => Shortened middle finger bones
HP:0005819 => Short middle bone of finger

- [x] HP:0006337 => Advanced tooth eruption
HP:0006288 => Advanced eruption of teeth

- [x] HP:0009441 => Bullet-shaped bones of middle finger
HP:0009845 => Bullet-shaped middle finger bones

- [x] HP:0005957 => Breathing difficulty
HP:0002098 => Breathing difficulties

- [x] HP:0032105 => Macrosaccadic oscillations
HP:0032117 => Macrosaccadic oscillation

- [x] HP:0001592 => Agenesis of a tooth
HP:0009804 => Tooth agenesis

- [x] HP:0011332 => Decreased size of half of the face
HP:0011331 => Decrease in size of half of face

- [x] HP:0009004 => Underdeveloped muscle
HP:0003199 => Underdeveloped muscles

- [x] HP:0009198 => Abnormality of end part of the innermost bone of the pinkie finger
HP:0009153 => Abnormality of end part of the innermost bone of pinky finger

- [x] HP:0100810 => Spock's ear
HP:0100015 => Spock ear

- [x] HP:0001204 => Symphalangism, distal
HP:0100263 => Distal symphalangism

- [x] HP:0010221 => Pseudoepiphysis of the 2nd metacarpal
HP:0006179 => Pseudoepiphyses of second metacarpal

- [x] HP:0009606 => Duplication of distal thumb phalanx
HP:0009612 => Duplication of the distal phalanx of the thumb

- [x] HP:0011675 => Cardiac conduction abnormalities
HP:0031546 => Cardiac conduction abnormality

- [x] HP:0000193 => Cleft uvula
HP:0410032 => Cleft of uvula

- [x] HP:0001911 => Abnormality of neutrophil
HP:0001874 => Abnormality of neutrophils

- [x] HP:0006097 => Webbed 3rd-4th fingers
HP:0011939 => Webbed 3rd-4th finger

- [x] HP:0005924 => Abnormality of the end part of the hand bone
HP:0005920 => Abnormality of the end part of the hand bones

- [x] HP:0009183 => Fifth finger camptodactyly
HP:0009185 => 5th finger camptodactyly

- [x]  HP:0025439 => Swollen throat
HP:0011855 => Throat swelling

- [x]  HP:0001482 => Growth of abnormal tissue under the skin
HP:0200036 => Growth of abnormal tissue on or under the skin
- [x]  HP:0009611 => Bifid distal phalanx of the thumb
HP:0005848 => Bifid thumb distal phalanx
- [x]  HP:0007811 => Nystagmus, congenital horizontal
HP:0007859 => Congenital horizontal nystagmus
- [x]  HP:0100760 => Clubbing of feet
HP:0001762 => Club feet
- [x]  HP:0009467 => Second finger clinodactyly
HP:0040022 => Clinodactyly of the 2nd finger

- [x]  HP:0100222 => Speckled calcifications in end part of the innermost bone of the little toe
HP:0100233 => Speckled calcifications in the end part of the innermost bone of the little toe
- [x]  HP:0012782 => Perilobar nephrogenic rest
HP:0011796 => Perilobar nephrogenic rests
- [x]  HP:0008422 => Vertebral wedging
HP:0004568 => Wedged vertebrae
- [x]  HP:0002650 => Abnormal curving of the spine
HP:0010674 => Abnormal curve of the spine
- [x]  HP:0000065 => Enlargement of the vaginal lips
HP:0012882 => Enlarged vaginal lips
- [x]  HP:0500184 => Abnormal amino acid levels in cerebrospinal fluid
HP:0032364 => Abnormal cerebrospinal fluid amino acid level
- [x]  HP:0009198 => Abnormality of end part of the innermost bone of the pinkie finger
HP:0009153 => Abnormality of end part of the innermost bone of pinky finger
- [x]  HP:0012370 => Prominence of cheekbone
HP:0010620 => Cheekbone prominence
- [x]  HP:0025319 => Neovascularization of the iris
HP:0011497 => Iris neovascularization
- [x]  HP:0001162 => Polydactyly, postaxial
HP:0100259 => Postaxial polydactyly
- [x]  HP:0005957 => Breathing difficulty
HP:0002098 => Breathing difficulties
- [x]  HP:0009611 => Notched outermost bone of the thumb
HP:0005848 => Notched outermost bone of thumb

- [x]  HP:0004691 => Cutaneous 2,3 toe syndactyly
HP:0005709 => 2-3 toe cutaneous syndactyly
- [x]  HP:0002650 => Abnormal curving of the spine
HP:0010674 => Abnormal curve of the spine
- [x]  HP:0011332 => Decreased size of half of the face
HP:0011331 => Decrease in size of half of face
- [x]  HP:0001977 => Abnormal blood clot
HP:0001928 => Abnormal blood clotting
- [x]  HP:0005736 => Short tibia
HP:0006436 => Shortening of the tibia
- [x]  HP:0006110 => Shortened middle finger bones
HP:0005819 => Short middle bone of finger
- [x]  HP:0010049 => Shortened long bone of hand
HP:0005720 => Shortened long bones of hand

- [x]  HP:0001627 => Cardiac anomalies
HP:0001626 => Cardiac anomaly
- [x]  HP:0001748 => Accessory spleens
HP:0001747 => Accessory spleen
- [x]  HP:0100760 => Clubbing of feet
HP:0001762 => Club feet
- [x]  HP:0009477 => Fused innermost and middle bone of index finger
HP:0009579 => Fused innermost and middle index finger bones
- [x]  HP:0008798 => Widened sacrosciatic notch
HP:0010457 => Widening of the sacrosciatic notch
- [x]  HP:0006337 => Advanced tooth eruption
HP:0006288 => Advanced eruption of teeth
- [x]  HP:0012783 => Intralobar nephrogenic rest
HP:0011795 => Intralobar nephrogenic rests
- [x]  HP:0032105 => Macrosaccadic oscillations
HP:0032117 => Macrosaccadic oscillation
- [x]  HP:0009501 => Abnormality of end part of the outermost bone of the index finger
HP:0009499 => Abnormality of the end part of the outermost bone of the index finger
- [x]  HP:0009611 => Bifid distal phalanx of the thumb
HP:0005848 => Bifid thumb distal phalanx
- [x]  HP:0004691 => Cutaneous 2,3 toe syndactyly
HP:0005709 => 2-3 toe cutaneous syndactyly
- [x]  HP:0001382 => Increased mobility of joints
HP:0002761 => Increased joint mobility

- [x]  HP:0100649 => Tumor of mouth
HP:0012290 => Mouth tumor
- [x]  HP:0006088 => Webbed 1-5 fingers
HP:0010708 => Webbed 1st-5th fingers

- [x]  HP:0001482 => Growth of abnormal tissue under the skin
HP:0200036 => Growth of abnormal tissue on or under the skin
- [x]  HP:0045055 => Tiger tail banding
HP:0032461 => Tiger-tail banding
- [x]  HP:0100658 => Skin infection
HP:0001581 => Skin infections
- [x]  HP:0001162 => Polydactyly, postaxial
HP:0100259 => Postaxial polydactyly

- [x]  HP:0100658 => Skin infection
HP:0001581 => Skin infections
- [x]  HP:0005924 => Abnormality of the end part of the hand bone
HP:0005920 => Abnormality of the end part of the hand bones
- [x]  HP:0005736 => Short tibia
HP:0006436 => Shortening of the tibia
- [x]  HP:0009501 => Abnormality of end part of the outermost bone of the index finger
HP:0009499 => Abnormality of the end part of the outermost bone of the index finger
- [x]  HP:0010221 => Pseudoepiphysis of the 2nd metacarpal
HP:0006179 => Pseudoepiphyses of second metacarpal

- [x]  HP:0008066 => Blisters
HP:0200037 => Blister
- [x]  HP:0009177 => Fifth finger symphalangism
HP:0004218 => Symphalangism of the 5th finger

- [x]  HP:0100539 => Puffiness around the eyes
HP:0000629 => Puffiness around eye

**Comment by drseb** [comment]
Thanks a lot! I work on this. Can we re-run this after my first iteration? Some of them were actually wrongly assigned synonyms, but I am not sure I might have missed some...

**Comment by drseb** [comment]
@tudorgroza this one is wrong on your side. 

```
HP:0009444 => Patchy sclerosis of middle finger phalanges
HP:0009848 => Patchy sclerosis of middle phalanx of finger
```
one is the middle finger, the other is the middle phalanx. This is the real hard stuff for NLP, right?

**Comment by tudorgroza** [comment]
@drseb - Absolutely - I can re-run this after every release if you want.
W.r.t. your second comment ... it took me a good 30s to get it - but yeah, it's wrong on my side.

**Comment by tudorgroza** [comment]
@drseb - can you please ping me when this is done so I can redo the experiment? Thank you!

**Comment by drseb** [comment]
@tudorgroza : this one is also hard, as the intended difference is singular vs plural, i.e. agenesis of one ("a") tooth and a general "tooth agenesis"

> HP:0001592 => Agenesis of a tooth
HP:0009804 => Tooth agenesis

Can you solve this on your side or do you think we should fix this? I am not sure what is correct here

**Comment by tudorgroza** [comment]
You do whatever makes sense and is correct from an ontological perspective. In the worst case scenario, when text mining, this will lead to an ambiguity. Thank you!

**Comment by drseb** [comment]
This one is also correct:

> HP:0001482 => Growth of abnormal tissue under the skin
HP:0200036 => Growth of abnormal tissue on or under the skin

The first one refers to "under" the second one to "on or under". Thanks.

**Comment by drseb** [comment]
This one is also intentionally referring to one extra entity vs multiple extra entities

> HP:0001748 => Accessory spleens
HP:0001747 => Accessory spleen

**Comment by drseb** [comment]
Thanks. Please re-run this with the next release!
