### ISSUE TITLE
Illegal equivalence: HP:0006504 (Anomaly of the limb diaphyses)  and HP_0000940 (Abnormal diaphysis morphology)

### ISSUE THREAD

**Issue by matentzn** [obophenotype/human-phenotype-ontology#4986]
HP:0006504 (Anomaly of the limb diaphyses) and HP_0000940 (Abnormal diaphysis morphology) are currently being equivalent after assing the lattern to the abnormal morphology pattern: 

```
'has part' some 
(morphology and ('inheres in' some diaphysis) and ('has modifier' some abnormal))
```

The problem is that HP:0006504 (Anomaly of the limb diaphyses) is asserted to be a subclass of HP_0000940 (Abnormal diaphysis morphology), but its logical definition is more general: 

```
'has part' some 
(quality and ('inheres in part of' some diaphysis) and ('has modifier' some abnormal))
```

For now, I removed the EQ of HP:0006504 (Anomaly of the limb diaphyses); let me know how you want to add it back.

**Comment by drseb** [comment]
Revising the structure would be the preferred option.

**Comment by drseb** [comment]
please put logical def back. I changed the def of HP:0006504

**Comment by drseb** [comment]
@matentzn
