### ISSUE TITLE
subclass modeling of arterial branches

### ISSUE THREAD

**Issue by markengelstad** [obophenotype/human-phenotype-ontology#499]
when dealing with entities like 'abnormality of facial artery', what should be its superclass? 

Although the facial artery is a branch of the external carotid artery, its not ontologically proper to say the 'Abnormality of facial artery' is_a 'Abnormality of external carotid artery', so it doesn't seem right that 'Abnormality of facial artery' should be a subclass of 'Abnormality of external carotid artery' -- yet it's appealing to model it that way given the branching nature of arteries and veins. 

so, if 'abnormality of facial artery' isn't a subclass of 'abnormality of external carotid artery', then what should it be a subclass of?  
Abnormality of carotid arteries?
Abnormality of the systemic arterial tree?

Or would it be proper to create a class:  'Abnormality of branch of external carotid artery' ?

**Comment by drseb** [comment]
So "Abnormality of the carotid arteries" includes in its textual and logical definition all branches. 
Maybe we should make this the superclass. Ok?

**Comment by markengelstad** [comment]
to me, that makes the most sense  -- for now. 

uberon can handle the anatomic inferences, potentially (like abnormality of branches of external carotid artery)
