### ISSUE TITLE
Relationship of sacrosciatic notch classes?

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#4992]
**HPO terms**

HP:0008798 => Widened sacrosciatic notch
HP:0010457 => Widening of the sacrosciatic notch

Merge them? If yes, then what hierarchy is the correct one? If not, why not?

**Comment by pnrobinson** [comment]
This is a difficult term. There are two notches and it might be the case that simply the labels are wrong. I will investigate. Thanks for picking this up!

**Comment by drseb** [comment]
Thanks to @tudorgroza

**Comment by pnrobinson** [comment]
sacrosciatic notch is synonymous with sciatic notch (https://bioportal.bioontology.org/ontologies/UBERON?p=classes&conceptid=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0014411). Sciatic notch should be our preferred label, it is much more common.

**Comment by drseb** [comment]
Will you do this or should I?

**Comment by pnrobinson** [comment]
Let me do this one -- I am searching for better definitions and we will also need to change some of the annotation files.

**Comment by drseb** [comment]
Thanks a lot!

**Comment by pnrobinson** [comment]
I have rearranged and corrected this minihierarchy. Sacroiliac notch was an unusual synonym for greater sciatic notch, and wew had duplicates of everything. Should be ok now.
