### ISSUE TITLE
Revise logical defs

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#4995]
Using DOSDP, it seem almost impossible to easily change a logical def. It takes a lot of steps for one simple change! That is really a problem. 

This ticket is for bookkeeping that I somewhen need to change the following logical defs:

`EquivalentClasses(<http://purl.obolibrary.org/obo/HP_0000940> ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/BFO_0000051> ObjectIntersectionOf(<http://purl.obolibrary.org/obo/PATO_0000051> ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/RO_0000052> <http://purl.obolibrary.org/obo/UBERON_0004769>) ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/RO_0002573> <http://purl.obolibrary.org/obo/PATO_0000460>))))`

`EquivalentClasses(<http://purl.obolibrary.org/obo/HP_0009808> ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/BFO_0000051> ObjectIntersectionOf(<http://purl.obolibrary.org/obo/PATO_0000051> ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/RO_0000052> ObjectIntersectionOf(<http://purl.obolibrary.org/obo/UBERON_0004769> ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/BFO_0000050> <http://purl.obolibrary.org/obo/UBERON_0012475>))) ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/RO_0002573> <http://purl.obolibrary.org/obo/PATO_0000460>))))`

`EquivalentClasses(<http://purl.obolibrary.org/obo/HP_0012699> ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/BFO_0000051> ObjectIntersectionOf(<http://purl.obolibrary.org/obo/PATO_0000051> ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/RO_0000052> ObjectIntersectionOf(<http://purl.obolibrary.org/obo/UBERON_0004769> ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/BFO_0000050> <http://purl.obolibrary.org/obo/UBERON_0012476>))) ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/RO_0002573> <http://purl.obolibrary.org/obo/PATO_0000460>))))`

`EquivalentClasses(<http://purl.obolibrary.org/obo/HP_0006504> ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/BFO_0000051> ObjectIntersectionOf(<http://purl.obolibrary.org/obo/PATO_0000051> ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/RO_0000052> ObjectIntersectionOf(<http://purl.obolibrary.org/obo/UBERON_0004769> ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/BFO_0000050> <http://purl.obolibrary.org/obo/UBERON_0002091>))) ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/RO_0002573> <http://purl.obolibrary.org/obo/PATO_0000460>))))`

**Comment by pnrobinson** [comment]
@matentzn  can we get a tutorial on this? I thought DSODP was supposed to make things simpler?

**Comment by matentzn** [comment]
I will gladly give some tutorials; and I am also keen on making things easier! Very sorry to hear you were having problems @drseb !

**Comment by drseb** [comment]
@matentzn let's have a call on this. The current solution is not really practical from editors point of view. Let's schedule via slack or mail. Thanks!
