### ISSUE TITLE
Abnormal renal tubular epithelial morphology

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#4998]
Definition:

**Comment by nicolevasilevsky** [comment]
Suggested text def:
Any structural anomaly of the cellular avascular layer of the renal tubule luminar surfaces. Source: MP:0009640

we can use this pattern:
https://github.com/obophenotype/upheno/blob/master/src/patterns/dosdp-dev/abnormalMorphologyOfAnatomicalEntity.yaml

UBERON:0004810 nephron tubule epithelium

**Comment by pnrobinson** [comment]
@nicolevasilevsky  add term as HP_0032598. What is the process for adding the definition now?

**Comment by nicolevasilevsky** [comment]
I'll work with @matentzn on this, we have a meeting scheduled next week.

**Comment by nicolevasilevsky** [comment]
I talked to Nico today, the process for adding logical defs is to just add the logical defs via Protege, but we want to ensure that we have a pattern in uPheno before we add the logical def, and we follow the pattern.

I'll add the logical def for this term

**Comment by nicolevasilevsky** [comment]
Looks like the term 'renal tubule epithelial cell' does not exist in CL, I'll make a NTR

**Comment by nicolevasilevsky** [comment]
see https://github.com/obophenotype/cell-ontology/issues/609

**Comment by matentzn** [comment]
Sometimes in these cases using in location pattern could also work, like abnormal morphology of epithelial cell and part of some renal tubule. :) this can help avoiding term proliferation in cell and uberon ontologies! But for now, it’s fine I think!

**Comment by nicolevasilevsky** [comment]
Oh, good point! I already did a PR in CL, but if they don't like that term for some reason, this can be our plan B
