### ISSUE TITLE
Renal tubular epithelial cell apoptosis

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#4999]
Definition:tubular epithelial cells that are rounded with increased eosinophilia and contain fragmented, densely basophilic nuclear debris
Comment: A better definition would be: Apoptosis of tubular epithelial cell that is rounded … , ref:https://www.ncbi.nlm.nih.gov/pubmed/29537990

**Comment by nicolevasilevsky** [comment]
We can use this pattern:
https://github.com/obophenotype/upheno/blob/master/src/patterns/dosdp-dev/abnormallyIncreasedOccurrenceOfBiologicalProcessInLocation.yaml

I think this is the correct CL term:
CL_1000615 'kidney cortex tubule cell'

Note - this is a child of 'renal cortical epithelial cell'
