### ISSUE TITLE
Pain on standing, in response to exercise and in reponse to heat

### ISSUE THREAD

**Issue by helenp** [obophenotype/human-phenotype-ontology#500]
We have a dataset to annotate where the patients are described as suffering pain in response to stimuli

1. pain in response to heat
2. pain on standing
3. pain in response to exercise

The patients are diagnosed with Erythromelalgia - and therefore the muscle pain on exercise terms do not seem appropriate.
Could these be added to HP, or existing terms recommended please
thanks
Helen Parkinson

**Comment by pnrobinson** [comment]
Hi Helen,
pain in response to heat is not necessarily abnormal! Also in response to exercise, as I experience every weekend when I overdo it with jogging! (Sorry). Could you specify exactly what these phenotypes are? On the other hand, Erythromelalgia can be conceptualised both as a disease and as a disease feature, I believe. Would it be sufficient to have this as a term?

**Comment by helenp** [comment]
Hi
I don't have more details, and I take the point about not abnormal. In 
this case the data are iPSCs from patients, and as well as the diagnosis 
these 'pain triggers' - this is the label on the s/sheet column for the 
terms I requested.

I am happy to mint these in EFO if you think the are not in scope, but I 
thought I would ask,

thanks

Helen


On 16/09/2015 14:48, Peter Robinson wrote:
>
> Hi Helen,
> pain in response to heat is not necessarily abnormal! Also in response 
> to exercise, as I experience every weekend when I overdo it with 
> jogging! (Sorry). Could you specify exactly what these phenotypes are? 
> On the other hand, Erythromelalgia can be conceptualised both as a 
> disease and as a disease feature, I believe. Would it be sufficient to 
> have this as a term?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/obophenotype/human-phenotype-ontology/issues/500#issuecomment-140747349>.
>

-- 
Helen Parkinson, PhD
Team Leader
Samples, Phenotypes and Ontologies Team
-------------------------------------------
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom

EBI 01223 494672
For scheduling assistance please contact Lynn French lfrench@ebi.ac.uk, 01223 494 453
Skype: helen.parkinson.ebi
http://www.ebi.ac.uk/about/people/helen-parkinson

**Comment by mellybelly** [comment]
@helenp have you looked at the IPSC modeling in ERO?

I think you could add abnormally low/high pain in response to X.
This is essentially what we do for the models

**Comment by helenp** [comment]
Hi


I will. There were similar terms in HP so I asked here first

thanks

Helen

On 16/09/2015 15:19, Melissa Haendel wrote:
>
> @helenp <https://github.com/helenp> have you looked at the IPSC 
> modeling in ERO?
>
> I think you could add abnormally low/high pain in response to X.
> This is essentially what we do for the models
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/obophenotype/human-phenotype-ontology/issues/500#issuecomment-140755251>.
>

-- 
Helen Parkinson, PhD
Team Leader
Samples, Phenotypes and Ontologies Team
-------------------------------------------
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom

EBI 01223 494672
For scheduling assistance please contact Lynn French lfrench@ebi.ac.uk, 01223 494 453
Skype: helen.parkinson.ebi
http://www.ebi.ac.uk/about/people/helen-parkinson

**Comment by mellybelly** [comment]
@mbrush did this work and can send more info. Was extended requirements analysis on contract, would be good to get your feedback and contributions.

**Comment by drseb** [comment]
Ok, I hope it's ok to close for now. Please re-open if required.
