### ISSUE TITLE
Renal lymphocytic tubulitis

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#5009]
Definition:Lymphocytes seen within the tubular epithelium
, ref:https://www.ncbi.nlm.nih.gov/pubmed/29537990

**Comment by pnrobinson** [comment]
I am using the following definition, which I think is clearer:
infiltration of the renal tubular epithelium by lymphocytes.


@avizrosenberg
@yongqunh  
@beckysteck

If you disagree please let me know!

**Comment by avizrosenberg** [comment]
better indeed

**Comment by yongqunh** [comment]
Agree
