### ISSUE TITLE
Renal tubular atrophy

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#5018]
Definition:

**Comment by nicolevasilevsky** [comment]
We can use this pattern:
https://github.com/obophenotype/upheno/blob/master/src/patterns/dosdp-dev/atrophiedAnatomicalEntity.yaml

UBERON_0009773 'renal tubule'

**Comment by nicolevasilevsky** [comment]
Suggested text def:
Partial or complete wasting (loss) of the renal tubule that was once present.

**Comment by pnrobinson** [comment]
The definition is already there with this pattern, thanks!
