### ISSUE TITLE
Renal tublar atrophy, thyroidization-type

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#5021]
Definition:round tubules with simplified epithelium and casts and hence similar appearance to thyroid
, ref:https://www.ncbi.nlm.nih.gov/pubmed/7906246

**Comment by pnrobinson** [comment]
Is this the proper parent term?
https://hpo.jax.org/app/browse/term/HP:0000092

@avizrosenberg
@beckysteck
@yongqunh

**Comment by yongqunh** [comment]
I think Yes.

**Comment by pnrobinson** [comment]
https://www.ajkd.org/article/S0272-6386(16)30033-6/fulltext

**Comment by avizrosenberg** [comment]
agreed 


--
