### ISSUE TITLE
Cytomegalovirus

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#5023]
Definition:Tubulitis that is associated with characteristic intranuclear glassy-appearing basophilic inclusions with surrounding halo (owl's eye-type inclusion) and marked increase in the size of the cell (cytomegaly), particularly in tubular epithelial cells and in endothelial cells. CMV confirmation by IHC or PCR.
, ref:https://www.ajkd.org/article/S0272-6386(16)30514-5/fulltext

**Comment by nicolevasilevsky** [comment]
Should this label be more specific?

**Comment by pnrobinson** [comment]
@avirosenberg Adding term as follows (please reopen if necessary)

label: Renal tubular cytomegalovirus inclusions
def: Characteristic intranuclear glassy-appearing basophilic inclusions with surrounding halo (owl's eye-type inclusion) and marked increase in the size of the cell (cytomegaly), particularly in tubular epithelial cells and in endothelial cells. Often accompanied by cytopathic changes including patchy interstitial pleomorphic infiltrate with lymphocytes, plasma cells, and macrophages.  PMID:27884284

**Comment by pnrobinson** [comment]
@avizrosenberg -- created term
