### ISSUE TITLE
Adenovirus

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#5024]
Definition:Viral cytopathic changes consist of smudgy basophilic intranuclear inclusions with enlarged nuclei of infected cells. Distal tubules are more commonly involved than proximal tubules. There is associated acute tubular injury, often with frank tubular necrosis and destruction, with acute interstitial nephritis, often with a pleomorphic infiltrate composed of lymphocytes, histiocytes, plasma cells, and variable numbers of neutrophils, with interstitial edema and hemorrhage. Tubular destruction may be associated with necrotizing interstitial granulomas. Severe granulomatous tubulointerstitial nephritis appears to be characteristic of adenoviral infection and is quite rare in other viral infections. Focal wedge-shaped necrosis may occur in renal parenchyma. Immunostaining for adenovirus shows strong nuclear and cytoplasmic staining in infected cells.
, ref:https://www.ajkd.org/article/S0272-6386(17)31036-3/fulltext

**Comment by pnrobinson** [comment]
Adenovirus renal infections usually occur in immunocompromised patients, more commonly in bone marrow and stem cell transplant recipients.
=> This is both a "Severe infection" in the sence of the HPO (because it can indicate immunodeficiency) and the actual event is a Mondo disease. @nicolevasilevsky

**Comment by nicolevasilevsky** [comment]
We have MONDO_0043479 'adenoviridae infectious disease' in Mondo, and 'adenovirus infection' is an exact synonym.

**Comment by pnrobinson** [comment]
@nicolevasilevsky  We probably want Adenovirus renal infection as a Mondo term as well. We can chat next week about the definition.

**Comment by pnrobinson** [comment]
@avizrosenberg adding term as Renal tubular adenovirus inclusions. Please reopen if necessary.

Def: Viral cytopathic changes consist of smudgy basophilic intranuclear inclusions with enlarged nuclei of infected cells. The inclusions stain positive for adenovirus (e.g., Figure 3 of PMID:29273157). Distal tubules are more commonly involved than proximal tubules. Occasionally glomerular visceral and parietal epithelial cells can be infected. There is associated acute tubular injury, often with frank tubular necrosis and destruction, with acute interstitial nephritis, often with a pleomorphic infiltrate composed of lymphocytes, histiocytes, plasma cells, and variable numbersof neutrophils, with interstitial edema and hemorrhage.
