### ISSUE TITLE
Polyomavirus nephropathy

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#5026]
Definition:
, ref:https://www.ajkd.org/article/S0272-6386(16)30513-3/fulltext

**Comment by pnrobinson** [comment]
@avizrosenberg

This is a disease and not a phenotypic feature. We can try to ensure that we have all of the phenotypic features that characterize this disease in the HPO.
@nicolevasilevsky  We need to add a term to Mondo for this!

**Comment by nicolevasilevsky** [comment]
this exists in Mondo:
MONDO_0022529 'BK-virus nephropathy'

**Comment by nicolevasilevsky** [comment]
I think this can be closed? Please reopen if not
