### ISSUE TITLE
Abnormal renal tubular luminal morphology

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#5027]
Definition:

**Comment by nicolevasilevsky** [comment]
We can use this pattern:
https://github.com/obophenotype/upheno/blob/master/src/patterns/dosdp-dev/abnormalMorphologyOfAnatomicalEntity.yaml

Is this the correct Uberon term?
UBERON_0004810 'nephron tubule epithelium'

**Comment by pnrobinson** [comment]
@avizrosenberg
Should this be a child of https://hpo.jax.org/app/browse/term/HP:0000091
it is a little difficult to model ontologically because the lumen is the "space" between the walls of the lumen and the abnormal morphology is actually a property of the tubules. The suggestion of @nicolevasilevsky  is to instead talk about the epithelium of the tubules -- would that work?
