### ISSUE TITLE
Tubular luminal dilatation

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#5028]
Definition:diltation without simplification; synonym- partial loss of brush borders. Tubular cross section with attenuated brush border (apical PAS positivity >10% of the normal expected height, but unequivocally less than normal expected height), resulting in an apparent increase in the size of lumen, without simplification as defined below

**Comment by nicolevasilevsky** [comment]
We aren't consistent with the logical defs for dilatation. We have:

'has part' some 
    (dilated
     and ('inheres in' some 'anatomical entity')
     and ('has modifier' some abnormal))

and 

'has part' some 
    (ballooning
     and ('inheres in' some 'anatomical entity')
     and ('has modifier' some abnormal))

Also, I'm not sure what the correct Uberon term is.

**Comment by pnrobinson** [comment]
how are balooning and dilated related in uberon? I do not like 'balooning' since in the strict sense it is a synonym but it can also easily be understood as a literal baloon. In which case it could dilate spherically which is then not anatomically correct!

**Comment by nicolevasilevsky** [comment]
PATO_0002093 ballooning is a child of 'increased volume'

PATO_0001571 dilated is a sibling of 'increased volume, both are a child of 'increased size' in PATO.

I think dilated would be a more appropriate quality to use here.

Should we  revise the other logical defs that use 'ballooning' in the logical def, to use 'dilated' instead?

**Comment by pnrobinson** [comment]
@nicolevasilevsky 

I added this definition

'has part' some
(dilated
and ('inheres in' some 'renal tubule')
and ('has modifier' some abnormal))

I think we should use this pattern for all dilated terms!

**Comment by nicolevasilevsky** [comment]
sounds good, I can work on this
