### ISSUE TITLE
Renal tubular cysts

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#5029]
Definition:Tubular lumnal dilatation/prominence lined by simple layer of cuboidal-to-flat tublar epihelial cells.

**Comment by nicolevasilevsky** [comment]
We could use this logical def:

'has part' some 
    ('increased amount'
     and ('inheres in' some 
        (cyst
         and ('part of' some 'renal tubule')))
     and ('has modifier' some abnormal))

There is not a pattern for cysts in uPheno, @matentzn do you think we should create one? There are a lot of cyst terms in HPO.

**Comment by matentzn** [comment]
Yeap, you could perhaps model it after the [abscessInLocation](https://github.com/obophenotype/upheno/blob/master/src/patterns/dosdp-dev/abscessInLocation.yaml) pattern. Happy to give it a shot @nicolevasilevsky ?

**Comment by nicolevasilevsky** [comment]
Yes, will do!

**Comment by nicolevasilevsky** [comment]
@pnrobinson I can add this term and logical def
