### ISSUE TITLE
Microcystic change

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#5032]
Definition:#1: at least one tubular cross section with convoluted, dilated tubular cross section (>3 times the normal tubules) and simplified epithelium with lumen filled by eosinophilic material. #2: presence of dilated tubules (> twice the diameter of a normal proximal tubule) containing eosinophilic amorphous material, and is generally accompanied by scalloping of the cast profile. The epithelium lining the microcyst is generally flattened and does not reveal brush border

**Comment by pnrobinson** [comment]
Question: Is the the same as Renal cortical microcysts?

**Comment by pnrobinson** [comment]
@avizrosenberg Is the the same as Renal cortical microcysts?

**Comment by avizrosenberg** [comment]
What is the definition used for Renal cortical microcysts?

**Comment by avizrosenberg** [comment]
@pnrobinson just following up on this definition

**Comment by pnrobinson** [comment]
@avizrosenberg  This is the current term:
https://hpo.jax.org/app/browse/term/HP:0004734

**Comment by pnrobinson** [comment]
could of abc tubular LUMINAL morphology (will be new term)

**Comment by pnrobinson** [comment]
@avizrosenberg  adding as "Tubular microcystic change" (because there are other kinds of microcystic change in other body parts)
