### ISSUE TITLE
Tubular casts

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#5033]
Definition:

**Comment by pnrobinson** [comment]
@avizrosenberg
@yongqunh  
@beckysteck

isnt this the same thing as the existing HPO term:
https://hpo.jax.org/app/browse/term/HP:0012615

**Comment by avizrosenberg** [comment]
While synonymous Cylinduria reflects casts in urine, whereas the KPMP histopahology entries are on tissue examination and in fact no urinary casts/sediment may be present

**Comment by pnrobinson** [comment]
Adding as Renal intratubular casts, def:Urinary casts are formed in the distal convoluted tubule or the collecting duct by solidification of protein in the lumen of the kidney tubules. This term refers to casts located within the tubuli of the kidney. -- please reopen this issue if needed.

**Comment by avizrosenberg** [comment]
@pnrobinson casts can form in any leel of tubule show limiting to distal convoluted tubule dosent seem correct.

**Comment by avizrosenberg** [comment]
@pnrobinson casts can form in any level of tubule show limiting to distal convoluted tubule dosent seem correct.
