### ISSUE TITLE
Add a new category for perinatal (or neonatal?) abnormalities

### ISSUE THREAD

**Issue by sdumitriu** [obophenotype/human-phenotype-ontology#504]
Many subterms refer to the neonatal variant of a phenotype, such as "HP:0002643 Neonatal respiratory distress", "HP:0001319 Neonatal hypotonia", "HP:0012768 Neonatal asphyxia", etc, yet there is no common parent for all these terms.

This may also include congenital terms.

**Comment by drseb** [comment]
I do not think it is a goal for HPO to classify "phenotypes" based on the time of occurrence. The idea is to add meta-annotations to each disease-phenotype association. For this we have the subontology [*onset*](http://www.human-phenotype-ontology.org/hpoweb/showterm?id=HP:0003674).

The plan is to get rid of the HPO classes already containing this meta-information in their labels and move this information to the annotations.

**Comment by drseb** [comment]
@pnrobinson please comment/reopen if needed

**Comment by mellybelly** [comment]
I agree, the post-composition of these terms is logically equivalent and we don't want to over-populate the ontology with a pre-composed term for every stage of development. 

That said, I think there are potentially some very often used terms that we could leave in for convenience if needed.
