### ISSUE TITLE
Bilirubin casts

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#5040]
Definition:A type of acelluar casts that have a surface composed of granules, which can vary in size. On H&E (red brown), PAS (amaranth purple), trichrome (red with ragged contours), Hall (olive-emerald green)
, ref:https://www.ncbi.nlm.nih.gov/pubmed/28398539

**Comment by pnrobinson** [comment]
@avizrosenberg

I changed the label to Intratubular bilirubin casts and added as HP:0032624. Please reopen this issue of this requires revision.

**Comment by avizrosenberg** [comment]
@pnrobinson Definition:A type of acelluar casts with a granular appearance, and can be admixed with hyaline casts. On H&E (red brown), PAS (amaranth purple), trichrome (red with ragged contours), Hall (olive-emerald green), ref:https://www.ncbi.nlm.nih.gov/pubmed/28398539
