### ISSUE TITLE
Vancomycin Casts

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#5044]
Definition:nonspecific granular tubular and proteinaceous cast with vancomycin precipitates (by IHC or IR)
, ref:https://www.ncbi.nlm.nih.gov/pubmed/28082518

**Comment by pnrobinson** [comment]
Adding this term as Intratubular vancomycin casts. I added 

def: Intratubular casts composed of vancomycin aggregates and uromodulin.

comment: The casts appear as nonspecific proteinaceous casts within the  tubular lumenss on light microscopy. Immunostaining can be used to confirm the presence of vancomycin.

@avizrosenberg, please reopen if this needs revision.

**Comment by avizrosenberg** [comment]
Modified comment: The casts appear as nonspecific proteinaceous tubular casts on light microscopy. Immunostaining or infrared imaging can be used to confirm the presence of vancomycin within casts.
