### ISSUE TITLE
Cellular casts

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#5045]
Definition:A type of urinary cast composed of cells incorporated in a protein matrix. The cells can be those found in the urinary sediment (erythrocytes, leuklocytes, renal tubular epithelial cells).
Modified definition: A type of urinary cast composed of cells incorporated in a protein matrix. The cells can be those found in the urinary sediment (erythrocytes, leuklocytes, renal tubular epithelial cells).

**Comment by pnrobinson** [comment]
This is https://hpo.jax.org/app/browse/term/HP:0031197

I will add Cellular casts as a synonym and update the definition.

@avizrosenberg
@beckysteck
@yongqunh

**Comment by avizrosenberg** [comment]
So cellular casts will be incorporated under cylinduria as well? I do belive that from the histomorphological perspective Casts and cylinduria need to be discrete entities.
