### ISSUE TITLE
Morphologic abnormality of the renal interstitium

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#5049]
Definition:

**Comment by pnrobinson** [comment]
Def: Any structural anomaly of the interstitium of the kidney. The renal interstitium is defined as the intertubular, extraglomerular, extravascular space of the kidney. It is bounded on all sides by tubular and vascular basement membranes and is filled with cells, extracellular matrix, and interstitial fluid.
PMID:25813241
Comment: The distribution of the renal varies within the kidney; it accounts for approximately 8% of the total parenchymal volume in the cortex and up to 40% in the inner medulla. The term renal interstitium is often inadequately used to refer to the peritubular interstitium (the space between tubules, glomeruli, and capillaries); the periarterial connective tissue and the extraglomerular mesangium are considered specialized interstitia. It is debated whether microvessels and capillaries, which are located within the peritubular space, are actually part of the renal interstitium or just run through it. Furthermore, lymphatics are considered interstitial constituents. The tubular interstitium in the cortex and medulla differ with regard to their cellular constituents, extracellular matrix composition, relative volume, and endocrine function, justifying the consideration of cortical and medullary interstitium as separate entities.

**Comment by pnrobinson** [comment]
@avizrosenberg  is this definition OK?

**Comment by nicolevasilevsky** [comment]
We can use this pattern:
https://github.com/obophenotype/upheno/blob/master/src/patterns/dosdp-dev/abnormalMorphologyOfAnatomicalEntity.yaml

UBERON_0005215 'kidney interstitium'

**Comment by avizrosenberg** [comment]
@pnrobinson I need to give this one some more consideration

**Comment by pnrobinson** [comment]
@avizrosenberg 
My main question is how this new term should relate to this:
https://hpo.jax.org/app/browse/term/HP:0001969

**Comment by pnrobinson** [comment]
sorry, I think it is OK< I added the definition.
