### ISSUE TITLE
Interstitial edema

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#5050]
Definition:The interstitium is occupied by pale acellular material

**Comment by nicolevasilevsky** [comment]
We could use this logical def:
'has part' some 
    (edematous
     and ('inheres in' some 'kidney interstitium')
     and ('has modifier' some abnormal))

(I assume this is referring to the kidney interstitium?

**Comment by pnrobinson** [comment]
The definition in the spreadsheet for interstitial edema (The interstitium is occupied by pale acellular material) does not appear to be entirely correct or easy to contextualize. Can you please check this and if possible provide a more detailed definition?

@avizrosenberg
@yongqunh  
@beckysteck

**Comment by avizrosenberg** [comment]
I agree and will try to better formalize this

**Comment by avizrosenberg** [comment]
@pnrobinson I need to give this one some more consideration

**Comment by pnrobinson** [comment]
@avizrosenberg  thoughts on this?

**Comment by avizrosenberg** [comment]
@pnrobinson Edema is characterized but the acute swelling of the stroma, with expansion of the interstitial space without the a concurrent increase in interstitial cells or extracellular matrix. Histologically this change is appreciated as interstitial areas of lower optical density.
