### ISSUE TITLE
Interstitial Hemosiderin

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#5054]
Definition:golden-brown, granular pigment derived from ferritin deposited in interstitial cells

**Comment by pnrobinson** [comment]
Label: Renal interstitial hemosiderin
Def Deposition of hemosiderin (a golden-brown, granular pigment derived from ferritin) in interstitial cells of the kidney. PMID:26491580 

Comment: Hemosiderin is an iron-containing, golden-brown, granular pigment derived from ferritin, the initial iron-storage protein. As iron accumulates within the cell, aggregates of ferritin molecules form hemosiderin. Upon hemolysis of red blood cells, hemoglobin alpha-beta dimers are released that, if unbound to haptoglobin, are filtered by the glomerulus and appear in the urine as hemoglobinuria. The hemoglobin dimers are taken up by renal proximal tubular cells and degraded and the free chelatable iron is stored as hemosiderin in the lysosomes. Hemosiderin deposition in kidney tubular cells has been reported in different types of hemolytic anemia including autoimmune hemolytic anemia and PNH [1, 4, 5] and sickle cell anemia [6, 7] and after cardiac valve replacement with residual valvular regurgitation or perivalvular leak.

**Comment by yongqunh** [comment]
It's good to relabel it to Renal interstitial hemosiderin, since we meant for kidney. I am also wondering how to define the parent term of this term. It appears that a term like “Deposition of hemosiderin” would be a good parent term. However, there is no such term in HPO yet. Will such a term be added later to HPO?

**Comment by pnrobinson** [comment]
@beckysteck @avizrosenberg  -- is the above term definition OK?
Additionally, we will need to think about Oliver's suggestion for deposition of hemosiderin (as a general parent term for multiple organs).
