### ISSUE TITLE
Renal interstitial amyloid

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#5056]
Definition:Deposition of interstitial PAS-weak, silver negative material frequently congophilic with birefringence under polarized light. Composed of 10 nm (on average) fibrils. Can be composed most commonly of monoclonal light chains (AL), transthyretin (TTR), LECT2 etc or in the setting of long standing systemic inflammation (AA)

**Comment by pnrobinson** [comment]
There is a term Renal amyloidosis (HP:0001917)
https://hpo.jax.org/app/browse/term/HP:0001917

Is it corrrect to say that amyloidosis mainly affects the interstitium so that these terms are synonyms or nearly so? Or do we need different terms for the different parts of the kidney?
@avizrosenberg
@yongqunh  
@beckysteck

**Comment by avizrosenberg** [comment]
Amyloidosis can impact essentially any compartment within the kidney, hence I anticipate there will be a renal vascular entry and a glomerular entry.

**Comment by pnrobinson** [comment]
@avizrosenberg I am going to add the following comment to the parent term Renal amyloidosis. It is adapted from https://www.ncbi.nlm.nih.gov/pubmed/25852856

Is this OK?


On hematoxylin and eosin stain, amyloid is identified as extracellular amorphous material that is lightly eosinophilic. These deposits often stain weakly for periodic acid Schiff (PAS), demonstrate a blue-to-gray hue on the trichrome stain and are typically negative on the Jones methenamine silver (JMS) stain. These tinctorial properties contrast with the histologic appearance of collagen, a major component of basement membranes, mesangial matrix and areas of sclerosis, which demonstrates strong positivity for PAS and JMS (See Figure 1 of PMID:25852856) .In the kidney, amyloid deposits may be found in any of the parenchymal compartments, including glomeruli, tubules, interstitium and/or vessels. Glomeruli are most commonly involved, with 97% of cases in a study showing glomerular deposition. In most instances, amyloid accumulation involves the mesangium before the capillary walls. In early cases, the process can be subtle and involves only a few mesangial regions and therefore can easily be missed by routine histologic evaluation. More extensive involvement results in marked expansion of the mesangium, which can take on a nodular appearance and mimic mesangial sclerotic processes such as diabetic glomerulosclerosis. However, the often negative staining with PAS and JMS is more typical of amyloid.

**Comment by pnrobinson** [comment]
@avizrosenberg I also added the following definition for the term Renal interstitial amyloidosis. We can add other amyloid terms, I will add one for now for the glomerulus.

Deposition of amyloid in the interstitial tissue of the kidney.  Amyloid is is made up of 10 nm (on average) fibrils that are most commonly composed of monoclonal light chains (AL), transthyretin (TTR), amd LECT2, or occur in the setting of long standing systemic inflammation.

**Comment by pnrobinson** [comment]
Here is the term I added for glomeruli--is this OK?
Renal glomerular amyloid deposition
def:
Amyloid deposits located in the glomeruli in a focal segmental, diffuse segmental or diffuse global fashion. This abnormality can be accompanied by mesangial involvement and in later stages also involvement of the peripheral capillaries. PMID:21427073

https://www.ncbi.nlm.nih.gov/pubmed/21427073

**Comment by yongqunh** [comment]
Looks good!

**Comment by pnrobinson** [comment]
great, closing.

**Comment by avizrosenberg** [comment]
>  Amyloid deposits located in the glomeruli in a focal segmental, diffuse segmental or diffuse global fashion. This abnormality can be accompanied by mesangial involvement and in later stages also involvement of the peripheral capillaries. PMID:21427073

We will have a separate entry for glomeruli in the glomerular ontology that we are completing.
