### ISSUE TITLE
Renal interstitial light chain deposits

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#5057]
Definition:Deposition of monoclonal immunoglobulin light chains along tubular basement membranes or interstitium as determined by immunofluoresence microscopy

**Comment by pnrobinson** [comment]
@avizrosenberg
@beckysteck
@yongqunh

Does monoclonality need to be mentioned here?

**Comment by avizrosenberg** [comment]
I think so as this reflects a particular entity

**Comment by pnrobinson** [comment]
Thanks, @avizrosenberg 
Our rule is to add enough definition/comments so as the make the term accessible to nonspecialists. I have done a little reading and think we might want both light and heavy chain terms


Light-chain deposition disease (LCDD) is one of three entities (LCDD, light and heavy chain deposition disease, and heavy chain deposition disease) of non-amyloidotic monoclonal immunoglobulin deposition diseases (MIDD) [1, 2].  (from: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5413647/)

Therefore, I would propose the term
Renal monoclonal immunoglobulin deposition

Definition: Accumulation of an immunoglobulin in the interstitial tissue of the kidney. The immunoglobulin may be a monoclonal Ig or the corresponding heavy-chain (HC) or light-chain (LC) subunit. By convention this definition excludes Ig-derived amyloidosis (amyloidosis can be distinguished by its affinity for Congo red staining).  [PMID:28509073, PMID:11423587]

Comment: Monoclonal immunoglobulin deposition is characterized by nonorganized electron-dense granular deposits predominantly localized in basement membranes of the kidney (other organs may additionally be affected). By light microscopy, tubular lesions are characterized by the deposition of a refractile, eosinophilic, periodic acid-Schiff (PAS)-positive, ribbon-like material along the tubular basement membrane. immunofluorescence examination of the kidney. Immunofluoerescence may show evidence of monotypic light or heavy chain fixation along tubular basement membranes. Electron microscopy can show finely to coarsely granular electron-dense deposits along the outer (interstitial) aspect of the tubular basement membranes.

And then there would be light and heavy chain child terms.

**Comment by yongqunh** [comment]
Is it better to name it "Renal interstitial light chain deposits" or "Renal interstitial light chain deposition"? 
As seen in Light-chain deposition disease (LCDD), it's Light-chain deposition. so probably deposition is better than deposits?

**Comment by pnrobinson** [comment]
OK, then I will add this term. @yongqunh I think that deposits is what one actually sees and so this is probably the best primary label. One infers that "deposition" occured such that one sees "deposits". I will make deposition be a synonym.

**Comment by yongqunh** [comment]
I see. thanks.
