### ISSUE TITLE
Add term or synonym for dysmelia

### ISSUE THREAD

**Issue by petkraw** [obophenotype/human-phenotype-ontology#506]
Einfach Synonym zu "Abnormality of the limbs"?

**Comment by drseb** [comment]
Is not a synonym of *Abnormality of the limbs* as *Dysmelia* refers only to *malformations*.
@pnrobinson should we add new class *Morphological abnormality of the limbs* with synonym *Dysmelia*?

**Comment by pnrobinson** [comment]
Dysmelia is extremely non-specific, and we have added it as a related synonym to Abnormality of limbs (melos=limb)
