### ISSUE TITLE
Renal interstitial inflammation

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#5060]
Definition:Inflammation involving fibrotic as well as non-fibrotic renal cortex, composed of lymphocytes, monocytes, plasma cells

**Comment by nicolevasilevsky** [comment]
We could use this pattern:
https://github.com/obophenotype/upheno/blob/master/src/patterns/dosdp-dev/abnormallyIncreasedOccurrenceOfBiologicalProcessInLocation.yaml

GO_0006954 'inflammatory response'
UBERON_0005270 'renal cortex interstitium'

**Comment by pnrobinson** [comment]
@avirosenberg
Is this synonymous with 
label: tubulointerstitial nephritis
syn: interstitial nephritis, Renal interstitial inflammation

I am also wondering about the definition, which mentions "cortex" but that is not the same as "interstitial".
I would suggest:
Def: An immune-mediated infiltration of the kidney interstitium by inflammatory cells, composed of lymphocytes, monocytes, plasma cells
citation: https://www.ncbi.nlm.nih.gov/pubmed/27155873/

Comment: Tubulointerstitial nephritis can lead to non-oliguric or oliguric acute kidney injury

**Comment by avizrosenberg** [comment]
@pnrobinson interstitial inflammation can result in nephritis which is a functional implication. However, inflammation can be associated with scar or other reactive process and in and of itself not be driving a functional decline. Regarding cortex vs medulla, we spend much of our time as renal pathologists in the cortex however, inflammation of significance can occur in the medulla as well, so the definition can  be altered to reflect this.

**Comment by pnrobinson** [comment]
add two child terms for cortical and medulla
