### ISSUE TITLE
Interstitital neutrophils

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#5063]
Definition:Neutrophils are noted in >10% of the cortex or representing >10% of the inflammatory cells

**Comment by pnrobinson** [comment]
Proposed label: Renal interstitial neutrophil infiltration
def: Increased numbers of neutrophils in the interstitial tissues of the kidney, defined as neutrophils being demonstrated in over 10% of the renal cortex (Question to Avi -- what does this mean? 10 percent of high power fields???) or representing over 10% of all inflammatory cells found in the renal interstitium (Question to Avi -- this definition is VERY imprecise -- what if we find only one single inflammatory cell that happens to be a neutrophil, i.e., percentage is 100% but there is actually not much infiltration)

@avizrosenberg  @yongqunh   Thoughts?

**Comment by pnrobinson** [comment]
PS, should we be citing this paper?
https://www.ncbi.nlm.nih.gov/pubmed/29537990

**Comment by yongqunh** [comment]
Probably we don't need to mention over 10%, to make the term flexible and suitable for different scenarios.

**Comment by pnrobinson** [comment]
I have added the term with the simpler definition
Increased numbers of neutrophils in the interstitial tissues of the kidney PMID:29537990

**Comment by avizrosenberg** [comment]
I agree that the 10% cutoff is arbitrary and has no basis in the literature or practice to my knowledge. The reference is appropriate
.
