### ISSUE TITLE
Interstitital foam cells

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#5064]
Definition:Presence of interstitial foam cells containing optically clear vacuoles

**Comment by pnrobinson** [comment]
Label: Renal interstitial foam cells
Def: Accumulation of foam cells (FC) in the interstitium of the kidney. Renal FCs display phenotypic characteristics of macrophages and belong to the monocyte/macrophage lineage. Histologically, renal FCs are characterized by round cells with small nuclei and an abundant PAS-positive cytoplasm with lipid-containing vacuoles.  PMID:25887903, PMID: 19672113 


Comment: 
FCs are the outcome of cellular lipid accumulation due to lipid metabolic dysfunction. Normally, lipid is in a dynamic equilibrium outside and inside of the cell. When factors facilitate cell lipid intake or reduce its efflux, it subsequently resulted in cellular lipid accumulation and FC formation. Renal interstitial FCs are commonly encountered in Alport syndrome and are occasionally observed in various other kidney diseases, including idiopathic membranous nephropathy (IMN), IgA nephropathy (IgAN), focal and segmental glomerulosclerosis (FSGS), and membranoproliferative glomerulonephritis.

**Comment by pnrobinson** [comment]
See https://www.ncbi.nlm.nih.gov/pubmed/25887903/ also for glomerular FC accumulation

**Comment by pnrobinson** [comment]
@avizrosenberg
@yongqunh  
@beckysteck

Is this definition good?
Should the parent term be Abnormal renal insterstitial morphology?

**Comment by yongqunh** [comment]
I think this definition is good. It's also good to have the parent term "Abnormal renal insterstitial morphology". Thanks.

**Comment by pnrobinson** [comment]
added term.

**Comment by avizrosenberg** [comment]
Edited comment: Comment:
FCs are the outcome of cellular lipid accumulation due to lipid metabolic dysfunction. Normally, lipid is in a dynamic equilibrium outside and inside of the cell. When factors facilitate cell lipid intake or reduce its efflux, it subsequently resulted in cellular lipid accumulation and FC formation. Renal interstitial FCs are encountered in nephrotic states (irrespective of the primary glomerular process) and Alport syndrome.

**Comment by avizrosenberg** [comment]
Glomerular FC are a seperate entity for the glomerular ontology

**Comment by avizrosenberg** [comment]
For interstitial foam cells we can cite:     PMID: 5904202 and     PMID: 4129269. There arent many studies that have explored these cells and their implications to date in the renal parenchyma

**Comment by avizrosenberg** [comment]
@pnrobinson please see above
