### ISSUE TITLE
Interstitital plasma cells

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#5065]
Definition:Plasma cells are noted in >10% of the cortex or representing >10% of the inflammatory cells

**Comment by pnrobinson** [comment]
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5590419/

**Comment by avizrosenberg** [comment]
I dont think this ref accurately reflects the definition here as the implication of this entry is not necessarily a neoplastic process (i.e., myeloma) but rather reactive in the vast majority of cases

**Comment by pnrobinson** [comment]
@yongqunh @avizrosenberg  Is there a pubmed reference that better reflects the definition? Should we add a comment that interstitial plasma cells can be reactive/inflammatory or in some cases malignant?

**Comment by yongqunh** [comment]
I could not easily find a better reference.
The first word of the label appears to have a typo:
Interstitial plasma cells

**Comment by pnrobinson** [comment]
OK, I will add the term as "Renal interstitial plasma cell infiltration"

**Comment by pnrobinson** [comment]
done

**Comment by avizrosenberg** [comment]
Renal interstitial plasma cell infiltration is fine and would exclude the 10% values in definition as there is no consensus on this number
