### ISSUE TITLE
Interstitial xanthogranulomatous inflammation

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#5066]
Definition:Inflammation consisting of foamy macrophages admixed with plasma cells, lymphocytes and neutrophils and occasional giant cells

**Comment by pnrobinson** [comment]
Is this related to xanthogranulomatous pyelonephritis?
https://www.sciencedirect.com/science/article/pii/S2405579416300328
or do we require two terms?

@avizrosenberg
@yongqunh  
@beckysteck

**Comment by avizrosenberg** [comment]
Xanthogranulomatous Pyelonephritis would be a diangostic entity in which one can observe Interstitial xanthogranulomatous inflammation. However to capture the phenotype more broadly, I imagine we would want to disconnect the phenotype from the disease.

@yongqunh
@beckysteck

**Comment by avizrosenberg** [comment]
@pnrobinson

**Comment by pnrobinson** [comment]
OK, I see -- I added the original definition!
