### ISSUE TITLE
Necrotizing granulomata

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#5069]
Definition:Interstital aggregates of histiciocytes, occasionally multinucleated with associated lymphoplasmacytic and occcasionally eosinophilic inflammation. Organization can range from poorly-to-well defined and multinucleated giant cells may be present with necrosis appreciated

**Comment by pnrobinson** [comment]
see https://www.sciencedirect.com/science/article/pii/S2405579416300328

**Comment by pnrobinson** [comment]
Label: Renal necrotizing granuloma
Def: An organized collection of histiocytes (specifically macrophages) localized in the interstitial tissue of the kidney.  Through light microscopy, the activated histiocytes appear as epithelioid cells with round to oval nuclei, often with irregular contours and abundant granular eosinophilic cytoplasm with indistinct cell borders. They may also coalesce to form multinucleated giant cells. Granulomas may be associated with a peripheral cuff of lymphoplasmacytic and occcasionally eosinophilic inflammation. Organization can range from poorly-to-well defined. Granulomas can present as necrotizing or non-necrotizing. Microscopically, necrotizing granulomas distinctly have central necrosis with a palisaded lymphohistiocytic reaction and a cuff of chronic inflammation. [PMID:31723695]

Comment: Granulomatous inflammation is a distinctive form of chronic inflammation produced in response to various infectious, autoimmune, toxic, allergic, and neoplastic conditions.


@avirosenberg -- I have extended the definition and label to provide more context. Can you please check the definition?

**Comment by pnrobinson** [comment]
@avizrosenberg -- I have extended the definition and label to provide more context. Can you please check the definition?

**Comment by avizrosenberg** [comment]
@pnrobinson looks great!

**Comment by pnrobinson** [comment]
added as HP:0032642
