### ISSUE TITLE
Renal parenchymal necrosis

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#5070]
Definition:

**Comment by nicolevasilevsky** [comment]
We could add this logical def:

'has part' some
('having extra processual parts'
and ('inheres in part of' some 'renal parenchyma')
and (towards some 'necrotic cell death')
and ('has modifier' some abnormal))

**Comment by pnrobinson** [comment]
@avizrosenberg
Added this as Renal necrosis with Renal parenchymal necrosis as a synonym. (I did not think it was necessary to emphasize parenchyma -- as opposed to pelvis?, since necrosis cannot affect the pelvis).

Please reopen this issue if revisions are needed.
