### ISSUE TITLE
Renal papillary necrosis

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#5071]
Definition:Pale tissue with typical appearance of coagulative necrosis, affecting the renal papillae. Can be identified by pyknotic nuclei; simplified, flattened epithelium of proximal tubules. The tubular and glomerular basement membranes are still visible without viable nuclei

**Comment by nicolevasilevsky** [comment]
We could add this logical def:

'has part' some
('having extra processual parts'
and ('inheres in part of' some 'renal papilla')
and (towards some 'necrotic cell death')
and ('has modifier' some abnormal))

Note - we don't have UBERON 'renal papilla' in HP.

**Comment by pnrobinson** [comment]
@drseb @matentzn what is the procedure for mireoting UBERON 'renal papilla'? Can we add that to the HP wiki?

**Comment by matentzn** [comment]
I added renal papilla [here](https://github.com/obophenotype/human-phenotype-ontology/pull/5095). The instructions for adding a new term are [here](https://github.com/obophenotype/human-phenotype-ontology/wiki/Add-classes-from-external-ontologies).

**Comment by pnrobinson** [comment]
Def: premature death of cells in the renal papilla (the apex of a renal pyramid which projects into the cavity of a calyx of the kidney and through which collecting ducts discharge urine). Histologically, one observes pale tissue with typical appearance of coagulative necrosis, affecting the renal papillae. Necrosis can be identified by pyknotic nuclei and simplified, flattened epithelium of proximal tubules. The tubular and glomerular basement membranes are still visible without viable nuclei.

@avirosenberg I added a bit of context for the definition, please check.
