### ISSUE TITLE
Renal parenchymal abcess

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#5073]
Definition:Destruction of renal parenchyma with suppurative/neutroophil-rich inflammation and associated necrosis. Cortical abcesses can reflect hematogenous spread of microorganisms whereas corticomedullary location favors ascending infecions.

**Comment by nicolevasilevsky** [comment]
We have an abscess pattern:
https://github.com/obophenotype/upheno/blob/master/src/patterns/dosdp-dev/abscessInLocation.yaml

We can use the Uberon term UBERON_0008987 'renal parenchyma'

**Comment by nicolevasilevsky** [comment]
Are these terms ready to add? I can help add them if yes, please just assign me.

**Comment by pnrobinson** [comment]
@nicolevasilevsky  thanks -- we want to have somebody from the KPMP team sign off on all of these terms. I will provide some more details via email

**Comment by pnrobinson** [comment]
@avizrosenberg

Also added new term: Perinephric abscess

A perinephric abscess is a collection of suppurative material in the perinephric space (i.e., the connective and adipose tissues surrounding the kidney).
https://www.ncbi.nlm.nih.gov/pubmed/21492371

**Comment by pnrobinson** [comment]
@avizrosenberg
I added the term with primary label Intrarenal abscess and synonym as above.
I modified the definition to provide more context. Please reopen this issue if we should revise this!

def: An encapsulated collection of pus and necrotic material within the renal parenchyma. The destruction of renal parenchyma is associated with suppurative/neutrophil-rich inflammation and necrosis.

Comment: Most renal abscesses are caused by gram-negative bacteria and are commonly caused by ascending infection associated with urologic abnormality, obstruction or calculi.


 PMID:27998164

**Comment by avizrosenberg** [comment]
@pnrobinson Im not sure of the relevance of perinephric to our goal of describing renal parenchymal disorder. 

> @avizrosenberg
> 
> Also added new term: Perinephric abscess
> 
> A perinephric abscess is a collection of suppurative material in the perinephric space (i.e., the connective and adipose tissues surrounding the kidney).
> https://www.ncbi.nlm.nih.gov/pubmed/21492371

**Comment by avizrosenberg** [comment]
> 
> 
> @avizrosenberg
> I added the term with primary label Intrarenal abscess and synonym as above.
> I modified the definition to provide more context. Please reopen this issue if we should revise this!
> 
> def: An encapsulated collection of pus and necrotic material within the renal parenchyma. The destruction of renal parenchyma is associated with suppurative/neutrophil-rich inflammation and necrosis.
> 
> Comment: Most renal abscesses are caused by gram-negative bacteria and are commonly caused by ascending infection associated with urologic abnormality, obstruction or calculi.
> 
> PMID:27998164

@pnrobinson this should suit.
