### ISSUE TITLE
Renal tubulointerstitial microganisms

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#5074]
Definition:

**Comment by pnrobinson** [comment]
@avizrosenberg
I am wondering exactly how this feature is observed.
Is this usually an indirect inference? e.g. 

"A higher density of neutrophils and plasma cells are suggestive of bacterial etiology [of TIN]"

Or should we define these terms as the demonstration of microorganisms in tubulointerstitial tissue with appropriate stains?
Probably it is not a good idea to use terms for inferences, which can be wrong of course!

**Comment by avizrosenberg** [comment]
This wouldn't be an inference but by observation of bacteria on a bacterial stain (Brown and Hopps) or fungi on PAS or silver stain

**Comment by pnrobinson** [comment]
OK, added as HP:0032635
