### ISSUE TITLE
Renal tubulointerstitial bacterial organisms

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#5076]
Definition:Tubulointerstitial infiltration of bacteria identified on routine and/or special (Brown-Hopps) stains. Can be ascending or vascuolcentric/blood-born. Can be associated with neutrophil rich infiltrates.

**Comment by pnrobinson** [comment]
@avizrosenberg
@beckysteck
@yongqunh

Adding this term with primary label Tubulointerstitial bacterial infiltration

**Comment by avizrosenberg** [comment]
@pnrobinson 
So removing the renal from the label?

**Comment by pnrobinson** [comment]
@avizrosenberg 
The primary label is
Tubulointerstitial bacterial infiltration
A synonym is 
Renal tubulointerstitial bacterial infiltration
-please reopen if this is suboptimal!
