### ISSUE TITLE
Renal tubulointerstitial viral organisms

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#5077]
Definition:Tubulointerstitial cell infection by viral organisms identified by pathognomonic viral vytopathic changes and/or immunohistochemical/in situ techniques. Tissue reaction to viral infection varies by etiology

**Comment by avizrosenberg** [comment]
Corrected definition here

Definition:Tubulointerstitial cell infection by viral organisms identified by pathognomonic viral cytopathic changes and/or immunohistochemical/in situ techniques. Tissue reaction to viral infection varies by etiology.

**Comment by pnrobinson** [comment]
@avizrosenberg
@beckysteck
@yongqunh

THere are people who do not consider viruses to be organisms.
I would suggest we rename this Tubulointerstitial viral infiltration

I do not know of any other organ with Tubulointerstitial, so we can probably leave "Renal" off the label as well?

**Comment by avizrosenberg** [comment]
@pnrobinson 
should we use viral infiltration or infection? The later suggests a pathology adn replicative state that may be more accurate.
Re: Renal Tubulointerstitial vs Tubulointerstitial, I leave to this to the hierarchical ontology minds. Renal tubulointersitium would seem a more complete though I hear the perspective that it is already specific with tubulointerstitium.

**Comment by pnrobinson** [comment]
@avizrosenberg  The HPO encodes phenotypic observations, and so it would encode the fact that some test had shown viruses in the tubulointerstitium. How would pathologists make this diagnosis, EM? Viral infection is probably best conceptualized as a disease, since there is some inference that the viruses are connected to other manifestations of illness?

**Comment by avizrosenberg** [comment]
@pnrobinson We would make the diagnosis by cytologic features and histochemical approaches (ISH or IHC). Renal tubulointerstitial viral infection as a phenotype would then be appropriate.

**Comment by yongqunh** [comment]
yes. it is a consensus in microbiology that virus is not an organism since virus cannot replicate and survive without living in an organism.

**Comment by pnrobinson** [comment]
@avizrosenberg  -- Are we referring to something like Figure 5 in https://www.ncbi.nlm.nih.gov/pubmed/21436288
?
I am worried about this term because it seems to be describing a disease state (viral interstitial nephritis), i.e., including an etiology and indirectly implying other characteristics. Can we boil this term down to exactly what is observed on the kidney biopsy?

**Comment by avizrosenberg** [comment]
This is essentially a term describing interstitial nephritis associated with a virus. What would be observed on biopsy are viral inclusions which can be seen on routine stains or with special stains (immunohistochemistry)

**Comment by pnrobinson** [comment]
added term
I also add this as a synonym

Renal tubulointerstitial viral inclusions
