### ISSUE TITLE
Renal tubulointerstitial mycobacterial organisms

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#5078]
Definition:Tubulointerstitial infiltration of mycobacteria  identified on  acid-fast or Fite stains. Can be associated with granulomatous inflammation

**Comment by avizrosenberg** [comment]
Can modify definition as: Renal tubulointerstitial infiltration of mycobacteria identified on acid-fast or Fite stains. Can be associated with granulomatous inflammation

**Comment by pnrobinson** [comment]
@avizrosenberg 
Thanks, will do. I would also like to cite this article and direct the user to Figure 2
https://www.ncbi.nlm.nih.gov/pubmed/23303798/
Am I correct that pathologists would code this finding distinctly from an interstitial granuloma related to TB? Do we need a code for that?

**Comment by avizrosenberg** [comment]
@pnrobinson yes this paper is nice for this purpose and it would be coded sepertly from interstitial granulomata. There should be a discrete code for granulomata of various types (i.e., #5067)
