### ISSUE TITLE
Add synonym for anhidrosis

### ISSUE THREAD

**Issue by cmungall** [obophenotype/human-phenotype-ontology#5079]
**HPO term**

HP:0000970 Anhidrosis

**Synonym to be added**

Anhidrosis

**broad/exact/narrow/plural/abbreviation ?**

exact

Note: could also be added for the child, generalized anydrosis

**Comment by pnrobinson** [comment]
@cmungall  I do not understand -- this is identical to the label?

**Comment by cmungall** [comment]
This is just a trivial y vs i synonym

**Comment by pnrobinson** [comment]
Anhidrosis is the only correct form (there is no 'y' synonym). :-0

**Comment by cmungall** [comment]
Yes, I realize it's from the greek hidros...

I guess it depends on your philosophy of synonyms, if they are there to enforce a correct/preferred usage or are there to support search, NER, etc. I often include non-preferred forms and annotate the synonym. 

https://scholar.google.com/scholar?q=anhydrosis
4k articles. Even the BMJ seems to have allowed titles with the 'y' form

386k usages:
https://www.google.com/search?q=Anhydrosis

vs 779k for the preferred spelling

It's a synonym in various dictionary sources:

https://www.thefreedictionary.com/anhydrosis
https://medical-dictionary.thefreedictionary.com/anhydrosis

so the y form is in use, perhaps unfortunately. Wouldn't we want to be able to find these articles using NER etc?

**Comment by pnrobinson** [comment]
I guess we don't want to be the etymology police, but anhydrosis is ugly...but let's add it!
