### ISSUE TITLE
https://hpo.jax.org/ is down

### ISSUE THREAD

**Issue by njoannin** [obophenotype/human-phenotype-ontology#5081]
Not sure this is the best place to report this... but I don't know where else to look.

The website https://hpo.jax.org/ is down, and has been for several days.

**Comment by drseb** [comment]
Thanks for reporting. We're on it.

**Comment by pnrobinson** [comment]
Sorry for the inconvenience. Slightly difficult due to the holiday in the US right now, but we will get to this shortly!

**Comment by drseb** [comment]
Has been resolved
