### ISSUE TITLE
Symphalangism terms defs need revision

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#5082]
From this `'has part' some 
    ('Distal symphalangism'
     and ('inheres in' some pes)
     and ('has modifier' some abnormal))`

to this kind of pattern: `'has part' some 
    ('fused with'
     and ('inheres in' some 'distal phalanx of manus')
     and (towards some 'middle phalanx of manus')
     and ('has modifier' some abnormal))`

Also: add an EQ to **Distal symphalangism**

@matentzn @nicolevasilevsky @LCCarmody  let me know if you can take care of that or what you think is the best procedure to implement these changes/additions. Thanks

**Comment by matentzn** [comment]
https://github.com/obophenotype/upheno/blob/master/src/patterns/dosdp-dev/abnormallyFusedAnatomicalEntities.yaml

**Comment by nicolevasilevsky** [comment]
I can fix this in Protege
