### ISSUE TITLE
Harmonize logical defs

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#5083]
This:
<img width="394" alt="Screenshot 2019-11-29 at 15 09 58" src="https://user-images.githubusercontent.com/5172897/69874141-91597f00-12ba-11ea-9e0c-41b5ae215f90.png">

Versus this:

<img width="457" alt="Screenshot 2019-11-29 at 15 10 03" src="https://user-images.githubusercontent.com/5172897/69874147-974f6000-12ba-11ea-9c7d-0b02afa6539b.png">

**Comment by pnrobinson** [comment]
We definitely need "morphology" here. The rest of the definitions intend to be the same thing and I am guessing that at some point in the past we did not have an uberon term for epiphysis of phalanx of manus.
But where is thing coming from are there two terms with these definitions?

**Comment by drseb** [comment]
Yes. These are two terms. This ticket is just a reminder for me to harmonise them.

**Comment by pnrobinson** [comment]
@drseb  is this issue closable? What is the action item?

**Comment by drseb** [comment]
I think the inheres-in should be the same?!

**Comment by pnrobinson** [comment]
@drseb sorry, don't understand? What do we need to do here?

**Comment by pnrobinson** [comment]
Moving to infrastructure project board
