### ISSUE TITLE
QC: Clean up travis output

### ISSUE THREAD

**Issue by matentzn** [obophenotype/human-phenotype-ontology#5086]
Most irrelevant output from travis comes from ROBOTS `InvalidReferenceViolation`. These errors are virtually meaningless for ontology curators, but may provide inside for ontology engineers like myself. The goal of this issue is to first catalog and then clear the output of the QC pipeline. These are the subgoals:

- [ ] Identify all types of reference violations and divide into FIX and SUPPRESS OUTPUT.
- [ ] Fix all reference violations in the FIX category
- [ ] Report all reference violations in the SUPPRESS OUTPUT category to ROBOT for exclusion from output.

For now, I can see the following categories (386 errors in total):
- [ ] Obsolete class subclass of owl:Thing ([SUPPRESS](https://github.com/ontodev/robot/issues/601), 246)
- [ ] Obsolete classes with EQs (63, should be fixed now)
- [ ] Obsolete classes used in external axioms (33, should make tickets for those. AFAICS, ENVO and GO mostly..) 
- [ ] Dangling entities used in external axioms (40) -> not sure what to do with those yet. [SUPPRESS](https://github.com/ontodev/robot/issues/601)?

**Comment by pnrobinson** [comment]
@matentzn What is the status here?

**Comment by matentzn** [comment]
I have never prioritised this.. I would say: leave it open, one day I will get to it. But probably not this year!

**Comment by pnrobinson** [comment]
@matentzn sorry for being pesky but is this still relevant after all of the recent improvements?

**Comment by matentzn** [comment]
Never apologise! I honestly love your ticket hygiene!  This ticket came out from a complaint from you - feel free to close and reopen whenever!

**Comment by pnrobinson** [comment]
Thanks! The new QC script is Really helpful, I think we can close this!
