### ISSUE TITLE
best practice for obsoleting a class

### ISSUE THREAD

**Issue by markengelstad** [obophenotype/human-phenotype-ontology#509]
What’s best practice in protégé for obsoleting a class?

I’d like to obsolete HP:0010756  Aplasia/ Hypoplasia of the premaxilla

Both Aplasia of premaxilla and hypoplasia of premaxilla should be subclasses of abnormality of premaxilla

**Comment by cmungall** [comment]
Generic answer:

Edit->Obsolete

Requires the right plugin, for recommended plugins see here:
https://github.com/obophenotype/human-phenotype-ontology/blob/master/src/ontology/README-editors.txt

**BUT**

You should be very careful. There may be direct annotations to a class 
and obsoleting will cause churn. If there is a replaced_by it can be 
automatic but the operation must still be synchronized.

In this case there are no directs in either rare or common diseases, so 
this looks like a grouping class, but you should at least start with a 
ticket on the tracker and give everyone a chance to weight in, possibly 
even emailing here to saying "hey everyone comment on this obsoletion 
request".

I'm not totally seeing why obsoletion is merited in this case

**Comment by drseb** [comment]
Please do not obsolete/delete this class. In general all obsoletions should be discussed beforehand as many downstream effects are to be expected.

**Comment by mellybelly** [comment]
This is two requests. One is to understand when/how to obsolete a class (and as both Chris and Seb have suggested, this is to be done very carefully and with lots of discussion on the tracker). The Read me file has some info, though HP is different than other ontologies and we can always document better. The latter request is for the obsolescence of that particular class. @markengelstad if you still feel that class should be obsoleted or modified, can you open a separate ticket for that?

We have actually discussed the issues with the combined aplasia/hypoplasia terms before, and I agree they are a bit awkward, but we had decided to leave them be for now. I will try to find the documentation of those discussions, or maybe @nicolevasilevsky can point you at it and we can further discuss.

**Comment by pnrobinson** [comment]
The reason we made that grouping class is that aplasia and hypoplasia are often the same thing pathophysiologically, and it makes sense to group the genes associated with either term (in fact, aplasia can often be defined as hypoplasia so severe you cannot see the residual tissue with the naked eye or by a CT scan etc). The actual name is a bit clunky and we may need to rethink.

I agree it would be good to discuss major changes more on the tracker. When I want to add a term, if there is anything controversial about it I have gotten in the habit of putting a request to myself on the tracker. Perhaps this would be a good rule to follow in general until we have sort things out

1-- term maintenance (synonyms, definitions etc). No tracker unless there are questions etc
2--obsoleting -- always tracker, wait a day or two before killing the old term
3--making new terms -- always tracker but if there are obvious child terms no need for a separate tracker entry (e.g., add "abnormal count of x in blood" to the tracker but OK to also add "reduced count" and "increased count" without extra tracker entry)

Does this sound good?

Dr. med. Peter N. Robinson, MSc.
Professor of Medical Genomics
Professor in the Bioinformatics Division of the Department of Mathematics and Computer Science of the Freie Universität Berlin
Institut für Medizinische Genetik und Humangenetik
Charité - Universitätsmedizin Berlin
Augustenburger Platz 1
13353 Berlin
Germany
+4930 450566006
Mobile: 0160 93769872
peter.robinson@charite.de
http://compbio.charite.de
http://www.human-phenotype-ontology.org
Introduction to Bio-Ontologies: http://www.crcpress.com/product/isbn/9781439836651
I have learned from my mistakes, and I am sure I can repeat them exactly
ORCID ID:http://orcid.org/0000-0002-0736-9199
Scopus Author ID 7403719646
Appointment request: http://doodle.com/pnrobinson
________________________________
Von: Melissa Haendel [notifications@github.com]
Gesendet: Dienstag, 29. September 2015 21:36
An: obophenotype/human-phenotype-ontology
Betreff: Re: [human-phenotype-ontology] best practice for obsoleting a class (#509)


This is two requests. One is to understand when/how to obsolete a class (and as both Chris and Seb have suggested, this is to be done very carefully and with lots of discussion on the tracker). The Read me file has some info, though HP is different than other ontologies and we can always document better. The latter request is for the obsolescence of that particular class. @markengelstad<https://github.com/markengelstad> if you still feel that class should be obsoleted or modified, can you open a separate ticket for that?

We have actually discussed the issues with the combined aplasia/hypoplasia terms before, and I agree they are a bit awkward, but we had decided to leave them be for now. I will try to find the documentation of those discussions, or maybe @nicolevasilevsky<https://github.com/nicolevasilevsky> can point you at it and we can further discuss.

**Comment by cmungall** [comment]
On 29 Sep 2015, at 12:46, Peter Robinson wrote:

> The reason we made that grouping class is that aplasia and hypoplasia 
> are often the same thing pathophysiologically, and it makes sense to 
> group the genes associated with either term (in fact, aplasia can 
> often be defined as hypoplasia so severe you cannot see the residual 
> tissue with the naked eye or by a CT scan etc). The actual name is a 
> bit clunky and we may need to rethink.
>
> I agree it would be good to discuss major changes more on the tracker. 
> When I want to add a term, if there is anything controversial about it 
> I have gotten in the habit of putting a request to myself on the 
> tracker. Perhaps this would be a good rule to follow in general until 
> we have sort things out
>
> 1-- term maintenance (synonyms, definitions etc). No tracker unless 
> there are questions etc
> 2--obsoleting -- always tracker, wait a day or two before killing the 
> old term
> 3--making new terms -- always tracker but if there are obvious child 
> terms no need for a separate tracker entry (e.g., add "abnormal count 
> of x in blood" to the tracker but OK to also add "reduced count" and 
> "increased count" without extra tracker entry)
>
> Does this sound good?

It's rarely a bad idea to use the tracker.

Also using the tracker to describe a plan of work is also good.

**Comment by nicolevasilevsky** [comment]
This all sounds good to me too!
Thanks!
---
Nicole Vasilevsky, PhD
Project manager
Ontology Development Group<http://www.ohsu.edu/xd/education/library/about/departments/ontology/>
Oregon Health & Science University
vasilevs@ohsu.edu<mailto:vasilevs@ohsu.edu>
503-806-6900
skype: nicolevasilevsky

**Comment by drseb** [comment]
>1-- term maintenance (synonyms, definitions etc). No tracker unless there are questions etc

Depends on the background of the editor. But in general ok. We will anyway develop a system that reports the changes to us.

>2--obsoleting -- always tracker, wait a day or two before killing the old term

**Better:** Wait for OK from the HPO advisory board. This advisory board should consist of *computer scientists* and *medical experts*.

> 3--making new terms -- always tracker but if there are obvious child terms no need for a separate tracker entry (e.g., add "abnormal count of x in blood" to the tracker but OK to also add "reduced count" and "increased count" without extra tracker entry)

Disagree. Always use tracker. Give others a chance to check if there already exists the same class or a related class.

**Comment by pnrobinson** [comment]
I would be 100% good with Seb's suggestions, which go beyond mine but are definitely worth the extra work involved. Are there any other suggestions? I would suggest we put this on the github site soon and communicate this clearly to all involved. This is definitely not a rebuke or a criticism of anyone or anything but simply realism that we need to become much more formal to run a project that is becoming ever more collaborative and international, and the informal methods we had in the first 5 years simply are not scaling well.
I say this also partly iunder the impression of last week when I nearly trashed our local SVN despite have been doing this perfectly fine for years (I was sleepy and forgot to backup a file and then also used a bad flag, argh!)-- there really is no place for pride, we need to have rules that will make things reliable and as easy as possible!
-Peter

Dr. med. Peter N. Robinson, MSc.
Professor of Medical Genomics
Professor in the Bioinformatics Division of the Department of Mathematics and Computer Science of the Freie Universität Berlin
Institut für Medizinische Genetik und Humangenetik
Charité - Universitätsmedizin Berlin
Augustenburger Platz 1
13353 Berlin
Germany
+4930 450566006
Mobile: 0160 93769872
peter.robinson@charite.de
http://compbio.charite.de
http://www.human-phenotype-ontology.org
Introduction to Bio-Ontologies: http://www.crcpress.com/product/isbn/9781439836651
I have learned from my mistakes, and I am sure I can repeat them exactly
ORCID ID:http://orcid.org/0000-0002-0736-9199
Scopus Author ID 7403719646
Appointment request: http://doodle.com/pnrobinson
________________________________
Von: Sebastian Köhler [notifications@github.com]
Gesendet: Mittwoch, 30. September 2015 07:34
An: obophenotype/human-phenotype-ontology
Cc: Robinson, Peter
Betreff: Re: [human-phenotype-ontology] best practice for obsoleting a class (#509)


1-- term maintenance (synonyms, definitions etc). No tracker unless there are questions etc

Depends on the background of the editor. But in general ok. We will anyway develop a system that reports the changes to us.

2--obsoleting -- always tracker, wait a day or two before killing the old term

Better: Wait for OK from the HPO advisory board. This advisory board should consist of computer scientists and medical experts.

3--making new terms -- always tracker but if there are obvious child terms no need for a separate tracker entry (e.g., add "abnormal count of x in blood" to the tracker but OK to also add "reduced count" and "increased count" without extra tracker entry)

Disagree. Always use tracker. Give others a chance to check if there already exists the same class or a related class.

**Comment by nicolevasilevsky** [comment]
I agree, Seb’s suggestions work for me. I can add them to the github site if everyone is okay with it.

Are folks going to be on the Phenotype call tomorrow at 12pm PT?

---
Nicole Vasilevsky, PhD
Project manager
Ontology Development Group<http://www.ohsu.edu/xd/education/library/about/departments/ontology/>
Oregon Health & Science University
vasilevs@ohsu.edu<mailto:vasilevs@ohsu.edu>
503-806-6900
skype: nicolevasilevsky

**Comment by cmungall** [comment]
On 29 Sep 2015, at 22:34, Sebastian Köhler wrote:

>> 1-- term maintenance (synonyms, definitions etc). No tracker unless 
>> there are questions etc
>
> Depends on the background of the editor. But in general ok. We will 
> anyway develop a system that reports the changes to us.

It might be better to break these down further, rather than a hard and 
fast rule for all:

  - Fixing of obvious spelling errors in syns and defs
  - Addition of lay synonyms
  - Additional of compositional synonyms or lexical variants that 
conform to the style guide
  - Adding domain or specialist synonyms
  - Deleting synonyms with axiom annotation
  - Deleting synonyms lacking axiom annotation
  - Adding an axiom annotation to an existing synonym
  - Changing scope of an existing synonym

Some of these categories could be fast-tracked by an experienced editor, 
others would require the requisite +1s on the tracker

>> 2--obsoleting -- always tracker, wait a day or two before killing the 
>> old term
>
> **Better:** Wait for OK from the HPO advisory board. This advisory 
> board should consist of *computer scientists* and *medical experts*.

in GO, any term that has direct gene associations cannot be obsoleted 
until after a 2 week comment period. But we are more aggressive about 
terms that are not in direct use.

For HPO, it's harder to know what the direct associations are because of 
the number of non-public systems consuming it, so any obsoletion carries 
with it the possibility of causing churn to someone. I think it's wise 
to be conservative and transparent here. We don't have an hpo-announce 
list, maybe we should.

OTOH you may want to be careful not to be too sclerotic. Sometimes a 
refactor is necessary, and you can't be held up if someone has a crappy 
annotation system that persistently uses a massively out of date version 
of the HPO and they don't have the ability to map over replaced_by. So I 
think you should announce and give fair warning and allow petitioning 
for all obsoletions, but ultimately the main editors should reserve the 
right to act when they need to.

>> 3--making new terms -- always tracker but if there are obvious child 
>> terms no need for a separate tracker entry (e.g., add "abnormal count 
>> of x in blood" to the tracker but OK to also add "reduced count" and 
>> "increased count" without extra tracker entry)
>
> Disagree. Always use tracker. Give others a chance to check if there 
> already exists the same class or a related class.

Actually it's not a bad idea to always go the by tracker for all of 
these. Even if it *seems* like the editor is being a human termgenie, 
until we have the patterns rock solid it's good to always "show our 
working"

Of course no need to be literal, and make a separate ticket for each. I 
am a fan of plan-of-work style tickets. E.g.

"I am working on metabolites A, B and C. I'm going to add 
increased/decreased levels of X in {blood,urine} for all of these. I'm 
following the pattern here <link>. I've check CHEBI and the hierarchy 
looks good for these."
