### ISSUE TITLE
add synonym to Hypoxemia

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#5091]
**HPO term**
Hypoxemia HP:0012418

**Synonym to be added**
Hypoxia

**broad/exact/narrow/plural/abbreviation ?**
Exact

Related to #3904

**Comment by pnrobinson** [comment]
These are not synonyms. Hypoxemia is low (hypo) oxygen (ox) in the blood (heme). It is actually measured. Hypoxia is an inference about what is going on in the body. => See the comment of the term. Hypoxia can be entered as a RELATED syn.

**Comment by nicolevasilevsky** [comment]
Ok! I can add it as related. Or should it be added as a new term?

**Comment by pnrobinson** [comment]
Well, since we do not really directly observe it, it is probably not an ideal term -- it would partially overlap with hypoxemia. I would vote for related synonym,
