### ISSUE TITLE
electrolyte imbalance

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#5099]
**HPO term**
HP_0012591 'Abnormal urinary electrolyte concentration' 

**Synonym to be added**
electrolyte imbalance

**broad/exact/narrow/plural/abbreviation ?**
exact ?

see https://github.com/monarch-initiative/mondo/issues/1084

**Comment by pnrobinson** [comment]
electrolyte imbalance could be in urine or blood or even tissue.
"Urinary electrolyte imbalance" would be a better synonym.

**Comment by nicolevasilevsky** [comment]
Ok, I'll add this synonym and open a new ticket for electrolyte imbalance.
