### ISSUE TITLE
Add British English spellings to HPO term aliases

### ISSUE THREAD

**Issue by kkrysiak** [obophenotype/human-phenotype-ontology#5103]
It would be useful for searching when using aliases that support British English. There are a few examples but there are likely more.

**HPO term**

**Synonym to be added**
Pediatric == Paediatric
Hematopoietic == Haematopoietic
Estrogen == Oestrogen
Fiber == Fibre
Behavoir == Behaviour

**broad/exact/narrow/plural/abbreviation ?**

**Comment by kkrysiak** [comment]
A few more 

tumor == tumour
edema == oedema
etiology == aetiology
anemia == anaemia
hemoglobin == haemoglobin

**Comment by nicolevasilevsky** [comment]
@pnrobinson I'm happy to help work on adding these. Should we add them as exact synonyms? Should we tag them in some way as British spelling?

**Comment by pnrobinson** [comment]
Um, we actually already have 100s of UK synonyms. I have added them ad hoc. There is a synonym type for UK spelling. @nicolevasilevsky  -- it would be great if you could work on this. I guess it would mean searching for typical US spellings and adding UK synonyms if that made sense.
@kkrysiak  It is already possible to search for UK spellings (try tumour at https://hpo.jax.org/app/). 
Possilby Nico has a way of doing this automagically? @matentzn

**Comment by nicolevasilevsky** [comment]
Yep, that makes sense, I can work on this, unless @matentzn has a way to do it automagically (I love that word.) I'll add this to my meeting agenda to discuss with Nico.

**Comment by LCCarmody** [comment]
I can help if there is no automagic

**Comment by kkrysiak** [comment]
We came across this for pediatric. I did see some but wanted to request any additional support. I really appreciate your rapid response. This has come up in our resource as we utilize the HPO and related aliases. It's great. I was trying to pull examples that we come across relating to our resource (civicdb.org) but I didn't exhaustively search the recommended terms.

**Comment by nicolevasilevsky** [comment]
Note- @matentzn will write a script to take care of this, and keep it up to date.

Here is a [list](https://github.com/obophenotype/human-phenotype-ontology/blob/master/src/ontology/hpo_british_english_dictionary.csv) of terms, to which we will add UK spelling synonyms.

Please add any additional terms to this list if needed (or send terms to me and I will add them)

**Comment by pnrobinson** [comment]
@kkrysiak We were able to add an additional 400 or so UK synonyms thanks to @matentzn and they should now all have the synonym_type UK spelling tag. Please let us know if anything is missing!

**Comment by kkrysiak** [comment]
@pnrobinson this is wonderful news and such a fast response. This is greatly appreciated and I think it will aid not only our resource but other groups utilizing HPO for NLP efforts and other associations. Thank you so much.
