### ISSUE TITLE
Unrecognized synonyms: Pointed frontal hairline HP:0004544, Widow's peak HP:0000349

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#5104]
**HPO term**
https://hpo.jax.org/app/browse/term/HP:0004544
https://hpo.jax.org/app/browse/term/HP:0000349

**Reason for deprecation**
Check that these are in fact synonyms

@MickeySegal -- thanks for pointing this out!

**Comment by pnrobinson** [comment]
merged!

**Comment by MickeySegal** [comment]
When 2 terms are merged, how do we tell which is the surviving code?

**Comment by pnrobinson** [comment]
In this case, HP:0000349 is the survivor. It now has a new annotation:
alternate_id: HP:0004544
and the obsoleted term (HP:0004544) now has the annotations
owl:deprecated: true
term_replaced_by: HP:0000349

This will be in the next HPO release (February, I think), and is now in the development version on GitHub.
