### ISSUE TITLE
typo on HPO website

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#5105]
Gene2MP should be Geno2MP
on this page:
https://hpo.jax.org/app/help/users

**Comment by drseb** [comment]
ping @iimpulse

**Comment by iimpulse** [comment]
Thanks Seb,

Tracking here.. this can be closed.

https://github.com/TheJacksonLaboratory/hpo-web/issues/102

**Comment by drseb** [comment]
thanks
