### ISSUE TITLE
Pipeline that translates American lang labels into british lang synonyms, with synonym type property UK spelling

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#5107]
This workflow will address: https://github.com/obophenotype/human-phenotype-ontology/issues/5103

Workflow for Nico:
1. need table that has HP ID and label in one column
1. 2nd table with HP ID and synonym
1. Python script to automatically update- replace american english lang terms
1. In the script, make sure the synonyms are labeled with has_synonym_type, UK spelling (subclass of synonym_type_property)
1. ROBOT template will be translated into OWL, merge into edit file

Nicole to do (@matentzn I will check this box when I am done): 

- [x] make sure all the terms we’d like to translate are in this table: https://github.com/obophenotype/human-phenotype-ontology/blob/master/src/ontology/hpo_british_english_dictionary.csv

related: https://github.com/obophenotype/human-phenotype-ontology/issues/1351

**Comment by matentzn** [comment]
I finished the pipeline and found, so far, 442 new british english synonyms. I sent a list to Nicole for her diligent review.

**Comment by drseb** [comment]
I think if the pipeline is done this ticket can be closed. The PR is created and currently being reviewed. Thanks
