### ISSUE TITLE
British spelling in some Labels

### ISSUE THREAD

**Issue by matentzn** [obophenotype/human-phenotype-ontology#5110]
During my quest of developing a pipeline to automatically translate labels and synonyms into British English synonyms, a bug led me to some potential British English spellings on some of the HPO labels (maybe they should be AE?). Maybe I am wrong, but here you go: The list with what I believe should be the correct spelling. Maybe some of this is wrong. But since its just 10 happy checking.

- [x] http://purl.obolibrary.org/obo/HP_0002224 Wooly hair
- [x] http://purl.obolibrary.org/obo/HP_0005531 Biphenotypic acute leukemia
- [x] http://purl.obolibrary.org/obo/HP_0011785 Thyrotoxicosis with toxic multinodular goiter
- [x] http://purl.obolibrary.org/obo/HP_0030205 Increased jitter at single fiber EMG
- [x] http://purl.obolibrary.org/obo/HP_0030814 Orange discolored tonsils
- [x] http://purl.obolibrary.org/obo/HP_0031420 Small yellow foveal lesion with surrounding gray zone
- [x] http://purl.obolibrary.org/obo/HP_0040149 Wooly scalp hair
- [x] http://purl.obolibrary.org/obo/HP_0040242 Muscle hemorrhage
- [x] http://purl.obolibrary.org/obo/HP_0100320 Rosenthal fibers

**Comment by nicolevasilevsky** [comment]
@pnrobinson any objections to me making the primary label american english and making the UK spelling a synonym (with the subset tag)?

**Comment by pnrobinson** [comment]
@nicolevasilevsky  This is what we have done to date, although UK spelling came first haha. So, yes, let's go with your suggestion!

**Comment by pnrobinson** [comment]
something seems to be wrong with the pipeline though, because leukemia, goiter, fiber, discolored, hemorrhage are US spellings for words that have distinct UK spellings, not vice versa! Also Wooly is US, woolly is UK I think.

**Comment by matentzn** [comment]
Yes this was found because of a bug; what you see here is what the labels SHOULD be, check what they actually are in protege!

**Comment by pnrobinson** [comment]
Now I understand. Yes, I agree!

**Comment by pnrobinson** [comment]
wooly vs woolly are both acceptable in US and UK, they are just variants afaics. Added.

**Comment by pnrobinson** [comment]
done!
