### ISSUE TITLE
New term request: Diffusion weighted MRI Abnormality

### ISSUE THREAD

**Issue by yankeetomer** [obophenotype/human-phenotype-ontology#5115]
HPO does not currently have any entries that describe DWI abnormalities.

Preferred term label
Diffusion weighted MRI Abnormality

Synonyms

Diffusion weighted magnetic resonance imaging (DWI) abnormality
Diffusion weighted imaging (DWI) abnormality
MRI diffusion abnormality

Drug resistance
3. Textual definition (should be understandable even for non-specialists, please include a PubMed ID for relevant articles providing additional information about the suggestion)
Neurol Clin Pract. 2012 Dec; 2(4): 287–293.
doi: 10.1212/CPJ.0b013e318278bee1 :

Restricted diffusion is an imaging finding typically associated with acute cerebral infarction. Less frequently this MRI abnormality is seen with other conditions including neoplasms, intracranial infections, traumatic brain injury, and demyelinating processes.

>The vast majority of restricted-diffusion abnormalities result from acute stroke, and as such, the diagnosis may be problematic when this MRI feature results from other causes. Distinct patterns of restricted diffusion seen with various disease conditions can play an important diagnostic role. The association of certain diseases with a given restricted-diffusion pattern allows for a focused assessment to determine a specific etiology.

Parent term
Abnormality of brain morphology
HP:0012443
(http://compbio.charite.de/hpoweb/showterm?id=HP:0012443)

Which diseases are characterized by this term ? (e.g. Orphanet- or OMIM-id)
One example:
Leigh Syndrome in a recent article appearing in Genetics in Medicine:
"Axial diffusion-weighted imaging (F) shows bilateral symmetrical diffusion restriction in the putamina, thalami, and hippocampal tails"
https://www.sciencedirect.com/science/article/pii/S0002929719304653
DOI:https://doi.org/10.1016/j.ajhg.2019.12.001

Your nano-attribution
Tomer Talmy M.D.
Organization: Emedgene Technologies
ORCID: https://orcid.org/0000-0002-7440-8864

**Comment by pnrobinson** [comment]
@yankeetomer  -- I think you are refering ?only? to brain MRI here.
Abnormal diffusion weighted cerebral MRI morphology
syn 
Abnormal diffusion weighted cerebral MRI
Abnormal diffusion weighted cerebral MRI finding
-- what do you think of these labels?


I would probably go ahead and add a term for restricted diffusion weighted etc such as here https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5829469/

**Comment by yankeetomer** [comment]
Hi Peter,
I agree with your suggestion specifying brain MRI, DWI indeed would be relevant to cerebral MRI

**Comment by pnrobinson** [comment]
Adding term as HP:0032615
Abnormal diffusion weighted cerebral MRI morphology
def:A diffusion abnormality observed in diffusion-weighted magnetic resonance imaging (MRI) of the brain. Molecular diffusion refers to the notion that any type of molecule in a fluid (eg, water) is randomly displaced as the molecule is agitated by thermal energy. Restricted diffusion of water appears bright on diffusion-weighted images.
added your orcid.
