### ISSUE TITLE
Expanding HPO with terms that are repeatedly mentioned in literature

### ISSUE THREAD

**Issue by Marwaabdelhakim** [obophenotype/human-phenotype-ontology#5116]
I am attaching a list of phenotypes that are repeatedly mentioned in literature. Each phenotype has a list of references next to it that show that this phenotype has been used in literature
[Phenotypes with references__ Phenotypes with references.csv.pdf](https://github.com/obophenotype/human-phenotype-ontology/files/4082547/Phenotypes.with.references__.Phenotypes.with.references.csv.pdf)
. We hope to include those terms as part of HPO if possible

**Comment by pnrobinson** [comment]
@Marwaabdelhakim  Would it be possible to send this list as a text file or Excel file? Then I will write a script to add one issue per new suggestion, that will make things much easier!

**Comment by Marwaabdelhakim** [comment]
Hello Peter,

Thanks a lot for your response. I have attached here some of this list. As I had to modify the attached references for each term. It was done computationally so it had some mismatches. I have revised it manually.  I will do the same for the rest of the list and upload it accordingly. 
[First patch for HPO annotation.xlsx](https://github.com/obophenotype/human-phenotype-ontology/files/4146639/First.patch.for.HPO.annotation.xlsx)

**Comment by pnrobinson** [comment]
Hello, @Marwaabdelhakim,
I have scripted these requests to be individual issues. This makes it a lot easier to discuss and create the new terms. I have tagged you in each of these new issues and may have questions/comments. I will close this issue, but if you want to send another excel file send it to my email or just open another issue.
