### ISSUE TITLE
Typo: https://hpo.jax.org/app/browse/term/HP:0020141

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#5117]
**HPO term**

**Bug description**
https://hpo.jax.org/app/browse/term/HP:0020141
Should be Blood pressure substantially lower in upper than lower extremities

 or even more clear  Blood pressure substantially lower in upper extremities than lower extremities or the style in the description using arm and leg is even more clear, but it seems that you adhere to avoiding those terms because of their different meaning in medicine than to laypeople.

thanks to @MickeySegal for pointing this out.

**Comment by pnrobinson** [comment]
Let's try
Blood pressure substantially higher in legs than arms
syn
Blood pressure substantially lower in arms than legs
Blood pressure substantially higher in lower than upper extremities
Blood pressure substantially lower in upper than lower extremities

**Comment by MickeySegal** [comment]
Seems good; this is similar to what we use in SimulConsult.  But https://hpo.jax.org/app/browse/term/HP:0020142 should then use the same style.

It seems that UMLS has not adopted these 2 findings, so hopefully when they do they will have the new wording.

**Comment by pnrobinson** [comment]
Thanks, fixed this!
