### ISSUE TITLE
The link to teams in the readme file results in a 404

### ISSUE THREAD

**Issue by Relequestual** [obophenotype/human-phenotype-ontology#512]
Link in readme under the Teams heading results in page not found.

**Comment by cmungall** [comment]
This one?
https://github.com/orgs/obophenotype/teams/human-phenotype

Works for me, could be a deliberate feature of github that only teams 
can see teams?

**Comment by Relequestual** [comment]
Yeah I believe so! I can't see any way to make it public. Shame =[

**Comment by drseb** [comment]
Can be closed?

**Comment by Relequestual** [comment]
I dissagre. The issue hasn't been resolved. You could either remove the link, or include a list of the members outside of the github link.

**Comment by mellybelly** [comment]
@Relequestual try again, I just changed the visibility.

**Comment by Relequestual** [comment]
Nope. I think that you can't make github team listings public.

**Comment by drseb** [comment]
@cmungall can't we just remove this link?

**Comment by cmungall** [comment]
Sure remove the link. The page is mostly useful for people using github. Your fix creating a higher level summary on the web page of people is a good idea (I'd like to have this driven by metadata at some point but one step at a time).
