### ISSUE TITLE
Hypoxemia logical def problem

### ISSUE THREAD

**Issue by balhoff** [obophenotype/human-phenotype-ontology#5125]
**HPO term**
Hypoxemia `http://purl.obolibrary.org/obo/HP_0012418`

**Suggested revision of logical definition**

Current:
```
'has part' some 
    ('decreased amount'
     and (('part of' some dioxygen)
     and ('inheres in' some blood))
     and ('has modifier' some abnormal))
```

This is making the quality part of a material. I think it should be something like this:
```
'has part' some 
    ('decreased amount'
and 'inheres in' some (dioxygen and ('part of' some blood))
and ('has modifier' some abnormal))
```

Maybe there is a pattern that covers this?

**Comment by pnrobinson** [comment]
@balhoff  This sounds reasonable. May I ask what the motivation for the change is, i.e., what is the difference in inferences that we would expect with this change? thanks!

**Comment by matentzn** [comment]
The current def is just false; thanks @balhoff. Your suggestion seems correct to me. @nicolevasilevsky the pattern is this: 
https://raw.githubusercontent.com/obophenotype/upheno/master/src/patterns/dosdp-dev/abnormallyDecreasedLevelOfChemicalEntityInLocation.yaml

When this is fixed, maybe do a spot check like this:
1. Run ELK
2. Go to DL Query Tab
3. `'has part' some ('part of' some owl:Thing)` (or whatever the correct way to write this is).

@pnrobinson Generally, the PATO quality can never be part of something - it always 'inheres in' something!

**Comment by balhoff** [comment]
In my case it was noticed due to some downstream inferences (in a Data Translator application). We were finding that "Hypoxemia overlaps dioxygen". It just seemed weird, so I looked into it.

**Comment by matentzn** [comment]
Yeah I just queried for `'Phenotypic abnormality' and 'has part' some ('part of' some owl:Thing)`. There seem to be about 10 classes that need fixing.

**Comment by nicolevasilevsky** [comment]
I'll work on this

**Comment by nicolevasilevsky** [comment]
I think this can be closed. Please reopen if there are still issues
