### ISSUE TITLE
New term: Encephalomalacia

### ISSUE THREAD

**Issue by CourtneyHum** [obophenotype/human-phenotype-ontology#513]
Definition: Encephalomalacia is the softening or loss of brain tissue after cerebral infarction, cerebral ischemia, infection, craniocerebral trauma, or other injury.

Superclass: Abnormality of the cerebrum...or maybe Atrophy/degeneration affecting the cerebrum

**Comment by drseb** [comment]
Thanks. How should I put your name in the ontology. E.g. mine is *HPO:skoehler*. Should I use *PhenoTips:CHum* ?

**Comment by CourtneyHum** [comment]
Sure!

**Comment by drseb** [comment]
Ok. Then I can close this issue. *Encephalomalacia* has been added as subclass of *Abnormality of the cerebrum*

**Comment by CourtneyHum** [comment]
Thank you

On Mon, Oct 5, 2015 at 10:16 AM, Sebastian Köhler <notifications@github.com>
wrote:

> Closed #513
> <https://github.com/obophenotype/human-phenotype-ontology/issues/513>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/obophenotype/human-phenotype-ontology/issues/513#event-426827814>
> .
>



-- 
Courtney Hum, MSc
Genetic Counsellor
Centre for Computational Medicine
The Hospital for Sick Children
T: 416-813-7654 x414028
