### ISSUE TITLE
make sure pattern is consistent for dilated terms

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#5131]
'has part' some
(dilated
and ('inheres in' some 'renal tubule')
and ('has modifier' some abnormal))

Peter said we should use this pattern for all dilated terms

see #5028

**Comment by pnrobinson** [comment]
This seems good/correct!

**Comment by pnrobinson** [comment]
@nicolevasilevsky  what is the action item? Can we close this?

**Comment by pnrobinson** [comment]
closing, but moved to project board
