### ISSUE TITLE
PATO term for necrotic needs to be imported

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#5132]
I added a few definitions for Renal necrosis (new term, HP_0032618) and used this pattern. However, the label (necrotic) does not show up in Protege. Can one of our Protege gurus check this and repair damage if necessary?
```
'has part' some 
(PATO_0000647 
and ('inheres in part of' some 'renal parenchyma') 
and ('has modifier' some abnormal))
```

**Comment by nicolevasilevsky** [comment]
assigning to Nico

**Comment by matentzn** [comment]
Done.
