### ISSUE TITLE
revise logical def for 'Camptodactyly of toe'

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#5134]
**HPO term**
HP_0001836 'Camptodactyly of toe'

**Suggested revision of logical definition**
@matentzn would like to revise all the logical definitions that use an HP term in the place where a quality should be. The current logical def for HP_0001836 'Camptodactyly of toe' is:
'has part' some 
    ('Flexion contracture'
     and ('inheres in' some 'interphalangeal joint of pes')
     and ('has modifier' some abnormal))

The logical def for 'Flexion contracture' is:
'has part' some 
    ('decreased length'
     and ('inheres in' some tendon)
     and ('has modifier' some abnormal))

Would it make sense to revise the logical def of 'Camptodactyly of toe' to 
'has part' some 
    ('decreased length'
     and ('inheres in' some 'interphalangeal joint of pes')
     and ('has modifier' some abnormal))

ie, can a joint have a decreased length?

**Comment by nicolevasilevsky** [comment]
see also:

ID | Label
-- | --
http://purl.obolibrary.org/obo/HP_0009538 | Contracture of the distal interphalangeal   joint of the 2nd finger
http://purl.obolibrary.org/obo/HP_0100352 | Contracture of the distal interphalangeal joint of the 2nd toe
http://purl.obolibrary.org/obo/HP_0009469 | Contracture of the distal interphalangeal joint of the 3rd finger
http://purl.obolibrary.org/obo/HP_0100353 | Contracture of the distal interphalangeal joint of the 3rd toe
http://purl.obolibrary.org/obo/HP_0009275 | Contracture of the distal interphalangeal joint of the 4th finger
http://purl.obolibrary.org/obo/HP_0100354 | Contracture of the distal interphalangeal joint of the 4th toe
http://purl.obolibrary.org/obo/HP_0009470 | Contracture of the metacarpophalangeal joint of the 3rd finger
http://purl.obolibrary.org/obo/HP_0009277 | Contracture of the metacarpophalangeal joint of the 4th finger
http://purl.obolibrary.org/obo/HP_0009186 | Contracture of the metacarpophalangeal joint of the 5th finger
http://purl.obolibrary.org/obo/HP_0100356 | Contracture of the metatarsophalangeal joint of the 2nd toe
http://purl.obolibrary.org/obo/HP_0100357 | Contracture of the metatarsophalangeal joint of the 3rd toe
http://purl.obolibrary.org/obo/HP_0100358 | Contracture of the metatarsophalangeal joint of the 4th toe
http://purl.obolibrary.org/obo/HP_0100359 | Contracture of the metatarsophalangeal joint of the 5th toe
http://purl.obolibrary.org/obo/HP_0009624 | Contractures of the carpometacarpal joint of the thumb
http://purl.obolibrary.org/obo/HP_0100355 | Contractures of the distal interphalangeal joint of the 5th toe
http://purl.obolibrary.org/obo/HP_0009626 | Contractures of the interphalangeal joint of the thumb
http://purl.obolibrary.org/obo/HP_0100360 | Contractures of the joints of the upper limbs
http://purl.obolibrary.org/obo/HP_0009625 | Contractures of the metacarpophalangeal joint of the thumb
http://purl.obolibrary.org/obo/HP_0010215 | Contractures of the metatarsophalangeal joint of the hallux
http://purl.obolibrary.org/obo/HP_0002987 | Elbow flexion contracture
http://purl.obolibrary.org/obo/HP_0030044 | Flexion contracture of digit
http://purl.obolibrary.org/obo/HP_0012785 | Flexion contracture of finger
http://purl.obolibrary.org/obo/HP_0005830 | Flexion contracture of toe
http://purl.obolibrary.org/obo/HP_0003273 | Hip contracture
http://purl.obolibrary.org/obo/HP_0006380 | Knee flexion contracture
http://purl.obolibrary.org/obo/HP_0003044 | Shoulder flexion contracture
http://purl.obolibrary.org/obo/HP_0001239 | Wrist flexion contracture

**Comment by pnrobinson** [comment]
This logical definition does not make sense -- it is not the join that is shorter, it is a tendon that works together with the joint. If the tendon is shortened, then the joint loses its mobility. Please do not make this change!
If we really want to improve these definitions, then we would have to add all of the tendons to uberon and then to logically relate the tendons to the joints.

**Comment by matentzn** [comment]
Just out of curiosity from someone who has no idea, would this work?

**HP_0001836 'Camptodactyly of toe'**

```
'has part' some
('decreased length'
and ('inheres in' some ('tendon' and 'attaches_to' some 'interphalangeal joint of pes'))
and ('has modifier' some abnormal))
```

Attaches to seems to be the relation that UBERON uses:
https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0016496

**Comment by nicolevasilevsky** [comment]
This seems like it could work.
@pnrobinson what do you think?

**Comment by pnrobinson** [comment]
seems good to me!

**Comment by nicolevasilevsky** [comment]
Cool, I can revise these logical defs :)

**Comment by matentzn** [comment]
Remember to create a pattern as well! :P

**Comment by nicolevasilevsky** [comment]
Oh yeah, will do! :)

**Comment by nicolevasilevsky** [comment]
to do:
- [ ] create pattern

**Comment by pnrobinson** [comment]
@nicolevasilevsky can we implement this now?

**Comment by nicolevasilevsky** [comment]
Yes, I created the pattern:
https://github.com/obophenotype/upheno/blob/master/src/patterns/dosdp-dev/abnormallyDecreasedLengthOfAnatomicalEntityAttachedToLocation.yaml

(sorry for the delayed reply)

**Comment by pnrobinson** [comment]
@nicolevasilevsky @matentzn  what is the status here? Is this issue closeable?

**Comment by nicolevasilevsky** [comment]
I'll take care of this now, I don't think the logical def has been revised yet

**Comment by nicolevasilevsky** [comment]
never mind, the logical def was revised, this can be closed.
