### ISSUE TITLE
error with human-phenotype-ontology.org

### ISSUE THREAD

**Issue by lcdaugherty** [obophenotype/human-phenotype-ontology#515]
From “www.human-phenotype-ontology.org”:
Failed to load the bootstrap javascript: ./../VAADIN/vaadinBootstrap.js?v=7.5.0

**Comment by drseb** [comment]
Thanks. I am trying since several hours to re-configure our webserver. Hope to resolve this issue soon.

**Comment by drseb** [comment]
Seems to run now. Will try again later.

**Comment by lcdaugherty** [comment]
Yes, all back to normal. Thanks!
