### ISSUE TITLE
Alopecia totalis and alopecia universalis 

### ISSUE THREAD

**Issue by violetarosas** [obophenotype/human-phenotype-ontology#516]
Alopecia totalis (HP:0007418) and alopecia universalis (HP:0002289) are  terms reserved for alopecia areata.
Maybe the most accurate terms are total  alopecia and generalized alopecia ?

Please see Rook's textbook of Dermatology 
DOI: 10.1002/9781444317633.

**Comment by drseb** [comment]
Can you give more details? I don't have access to the book. What do you want to achieve that HPO currently doesn't?

**Comment by violetarosas** [comment]
Dear Sebastian
From Rook - ISBN: 978140516169-5
"Alopecia areata does not destroy hair follicles, and the potential for regrowth of hair is retained for many years, and is possibly lifelong. In some patients, patches of hair loss occur at infrequent intervals interspersed with long periods of normal hair growth. In others, alopecia areata is more persistent, so that new patches of hair loss continue to develop at the same time as
regrowth occurs elsewhere. In a relatively small number of patients, hair loss progresses to involve all of the scalp (alopecia totalis) or the entire skin surface (alopecia universalis).
See also : PMID:  24326541
Universal / total alopecia are used for extended hair loss not related to alopecia areata --> here some exemples :
 1. Mendes da Costa–van der Valk syndrome : Patients with this rare syndrome, determined by a sex-linked recessive gene, present at birth or in early infancy with universal
alopecia ....Rook- 58.20
2. Total alopecia (the scalp hair is often normal at birth but is shed between the frst and sixth months, after which no further growth occurs. In some cases the scalp has been totally hairless a tbirth and has remained so. Eyebrows, eyelashes and body hair may also be absent). Total alopecia can be an isolated defect or associated to other disorders  (papular atrichia, progeria, Clouston’s syndrome ...  )..Rook-66.59

So, i'm proposing to add these 2 terms (total alopecia and universal alopecia) to HPO.

Thanks,

Clara

**Comment by drseb** [comment]
Thanks for the information. Please note that HPO already contains:
 - [Alopecia (HP:0001596)](http://compbio.charite.de/hpoweb/?id=HP:0001596)
 - [Alopecia areata (HP:0002229)](http://compbio.charite.de/hpoweb/?id=HP:0002229)
 - [Alopecia universalis (HP:0002289)](http://compbio.charite.de/hpoweb/?id=HP:0002289)
 - [Alopecia totalis (HP:0007418)](http://compbio.charite.de/hpoweb/?id=HP:0007418)

Are you seeing those HPO classes in the HPO version you use?

**Comment by violetarosas** [comment]
Thanks for your reply, but I've already checked those HPO terms.
The issue is  that alopecia totalis  and alopecia universalis should be used exclusively for alopecia areata. 
Thanks,
Clara

**Comment by pnrobinson** [comment]
Dear Clara,
I do not understand your suggestion that "alopecia totalis and alopecia universalis should be used exclusively for alopecia areata", as they are distinct?
@drseb We should add "total alopecia" as an EXACT_SYNONYM for alopecia totalis and the same for "universal alopecia"

**Comment by violetarosas** [comment]
Dear Peter,
thanks for your reply.
Yes, alopecia totalis and alopecia universalis should be used exclusively for alopecia areata (please see my previous post).
Total alopecia and universal alopecia should be added,  not as exact synonyms rather as related synonyms.

Kind regards,

Clara Jaramillo
Clinical signs annotation
Orphanet
