### ISSUE TITLE
Quick discussion: Travis failure and external terms

### ISSUE THREAD

**Issue by matentzn** [obophenotype/human-phenotype-ontology#5175]
Currently, when you add an external term [as prescribed in our SOP](https://github.com/obophenotype/human-phenotype-ontology/wiki/Add-classes-from-external-ontologies), travis fails with a no-label violation. This is clean, this is correct, and this is annoying. I have amended the above SOP now with an optional instruction on how to actually refresh the import (which imports the external from its source), so that travis passes again. I know that @drseb @LCCarmody and me have ODKs installed, and at least on one machine @pnrobinson does too. @nicolevasilevsky I think? I will open this issue and close it immediately, as I believe Travis should fail until referenced external terms are properly imported, but I just wanted to use this opportunity to tell you that you can now refresh the imports yourself.

**Comment by pnrobinson** [comment]
PS, stupidly, I did not write down all of the steps for running travis locally. Can we make a short Wiki page as a how to?

**Comment by matentzn** [comment]
yes will do. But I just realised its not enough in any case.. Need to rethink this one more time

**Comment by matentzn** [comment]
Ok I added instructions for how to run qc locally here:

https://github.com/obophenotype/human-phenotype-ontology/wiki/Run-QC-locally

I have updated the SOP for how to refresh imports:

https://github.com/obophenotype/human-phenotype-ontology/wiki/Add-classes-from-external-ontologies

Its a bit hacky, but works; lets roll with this for a bit, and if we collect some more todos for the QC pipeline, make a concerted effort to improve everything at once.
