### ISSUE TITLE
Ataxia

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#5179]
**HPO term**
Ataxia

**Suggested revision of logical definition**
I suggest removing this logical def, because it uses an NBO term that is the same as the phenotype

Ataxia
'has part' some 
    ('increased rate'
     and ('inheres in' some ataxia)
     and ('has modifier' some abnormal))

**Comment by pnrobinson** [comment]
@nicolevasilevsky  I agree this definition is not good. 
What do we think about OBA?
https://www.ebi.ac.uk/ols/ontologies/oba/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOBA_1000775&viewMode=All&siblings=true
```
'has part' some
('decreased amount'
and ('inheres in' some 'motor coordination quality')
and ('has modifier' some abnormal))
```

**Comment by pnrobinson** [comment]
@nicolevasilevsky @matentzn @drseb  -- not sure what the status is wrt to NBO -- can we do anything about this issue now?

**Comment by matentzn** [comment]
The definition looks reasonable! The pattern we use is this one:
https://raw.githubusercontent.com/obophenotype/upheno/master/src/patterns/dosdp-dev/abnormallyDecreasedRateOfBehavior.yaml

So the definition would be:

```
'has part' some
('decreased rate'
and ('inheres in' some 'motor coordination')
and ('has modifier' some abnormal))
```

Dont get thrown by the name of the pattern `behavior` is a very brought in uPheno concept that covers reflexes etc as well.

**Comment by matentzn** [comment]
This is motor coordination: https://www.ebi.ac.uk/ols/ontologies/nbo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNBO_0000339

**Comment by pnrobinson** [comment]
thanks, I updated the definition.
