### ISSUE TITLE
Proposed antibody related changes

### ISSUE THREAD

**Issue by mh11** [obophenotype/human-phenotype-ontology#5180]
Please find an updated structure suggestion for the immune system physiology attached, which was developed during the Immunodeficiency HPO meeting in Vienna and during follow-up discussions. 
[HPO PAD requested changes.docx](https://github.com/obophenotype/human-phenotype-ontology/files/4204365/HPO.PAD.requested.changes.docx)

**Comment by pnrobinson** [comment]
@mh11 I am not sure I understand this document. For instance, what do the letters mean?
```
Decreased antibody level in blood -> A, B, C, D, E, F, G, H, I, J
```

**Comment by mh11** [comment]
Sorry, if the structure is not obvious.
The A, B, C, D, ... refers to the next text block in the document. The same for the A1,A2,A3,A4,A5
So in a tree like structure, it would look like below - hope this helps
```
 |- Decreased antibody level in blood
     |- Decreased circulating level of specific antibody  (is A) -> A1, A2, A3, A4, A5
         |- Decreased specific antibody response to vaccination (is A1) -> A1.1, A1.2, A1.3
              |- Decreased specific antibody response to protein-conjugated polysaccharide vaccine (is A1.1) -> A1.1.1, A1.1.2, A1.1.3, A1.1.4
                  |- .... (A1.1.1)
                  |- ....
              |- Decreased specific antibody response to protein vaccine (is A1.2) -> A1.2.1, A1.2.2, A1.2.3, A1.2.4
                  |- ....
              |- Decreased specific antibody response to polysaccharide vaccine (is A1.3) -> A1.3.1, A1.3.2
                  |- ....
         |- Abnormal isohemagglutinin level (is A2) -> A2.1, A2.2
              |- Reduced isohemagglutinin level (is A2.1) 
              |- Absent isohemagglutinin level (is A2.2) 
         |- Specific pneumococcal antibody deficiency (is A3) 
         |- Specific anti-polysaccharide antibody deficiency (is A4) 
         |- Decreased specific antibody response to infection (is A5) 
     |- Decreased circulating IgG level   (is B)
         |- ...
     |- Decreased circulating IgA level   (is C)
         |- ...
     |- Agammaglobulinemia  (is D)
     |- Panhypogammaglobulinemia  (is E)
     |- Decreased circulating total IgM  (is F)
     |- Decreased circulating total IgE (is G)
     |- Dysgammaglobulinemia (is H)
     |- Decreased circulating total IgD  (is I)
     |- Transient hypogammaglobulinemia of infancy (is J)
 |- Increased ....
     |- ...
         |- ...
    
```

**Comment by pnrobinson** [comment]
- [ ] Abnormal immunoglobulin level in blood -> I, II, III, IV, V, VI, VII, VIII Response: Added the word "circulating" to the primary labels for consistency with other HPO terms. Added the "...in blood" labels as synonyms.

**Comment by pnrobinson** [comment]
- [ ] Absent specific antibody response -> Abnormal specific antibody response
Currently, this term is used to annotate a type of SCID (https://omim.org/entry/102700), where there is an absent response. Can you specify what the reason is for the proposed change? Should we make a parent term "Abnormal specific anitibody response"? If so, what would the other children terms be (please open a separate issue for this!)

**Comment by pnrobinson** [comment]
Agammaglobulinemia: https://github.com/obophenotype/human-phenotype-ontology/issues/5605

**Comment by pnrobinson** [comment]
@mh11 I have transferred the issues from the Word doc to GitHub (use the 'immunology' label to see them), see https://github.com/obophenotype/human-phenotype-ontology/issues?q=is%3Aopen+is%3Aissue+label%3AImmunology

Most are clear but I have three questions:
1. See #5606 
2. How important is it to have "...in blood" as the primary label? For now, I have used "..circulating..." as the primary label for consistency with other HPO terms and added the "...in blood" variant as a synonym
3. I think I was able to figure out all of the requests, but please check!

**Comment by nicolevasilevsky** [comment]
I think this ticket can be closed, as all of the requests are now specific issues. Please reopen if needed.

**Comment by nicolevasilevsky** [comment]
I created a google doc: https://docs.google.com/document/d/1MWXsdl2h8RzJLjVeUKFqzUsamrWzWcFxg62OsUt92Y0/edit
