### ISSUE TITLE
Cyst vs Lesion

### ISSUE THREAD

**Issue by markengelstad** [obophenotype/human-phenotype-ontology#520]
'Cyst of the eyelid'    HP:0010604
     'Chalazion'
     'Hordeolum'
     'Xanthelesma'

The parent class 'Cyst of the eyelid' contains subclasses like 'Hordeolum' that aren't cysts (cysts are epithelium-lined lesions).   
So, Cyst is a specific type of lesion, but i am aware that it's also a lay term for any kind of soft developmental surface bump. 

Would it be a good practice to change this label to 'Lesion of the eyelid' and make 'Cyst of the eyelid' a narrow or exact synonym?

**Comment by drseb** [comment]
There is also the problem that we have *Epidermoid cyst* as superclass. 

*Hordeolum* is the only phenotype wrongly classified as *Cyst*, right?

**Comment by pnrobinson** [comment]
@drseb I think that hordeolum and Xanthelasma are both not a cyst. Perhaps they can be made siblings of cyst under "Nodular changes affecting the eyelids" (Note I do not like the latter term name, and maybe we need to clean this up a little in the future)
