### ISSUE TITLE
Flat midface

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#521]
@markengelstad Should this be a new class or is this a synonym of an existing class?

**Comment by markengelstad** [comment]
It's a synonym for hypoplasia of midface.

Midface needs a bit of work. There's a lot of confusion / overlap/
redundancy, etc in midface, zygoma, and malar.

**Comment by pnrobinson** [comment]
Please note that the HPO is using terminology from the elements of morphology project for the midface etc. Let us have a sykep to discuss before making any major changes!
-Peter

Dr. med. Peter N. Robinson, MSc.
Professor of Medical Genomics
Professor in the Bioinformatics Division of the Department of Mathematics and Computer Science of the Freie Universität Berlin
Institut für Medizinische Genetik und Humangenetik
Charité - Universitätsmedizin Berlin
Augustenburger Platz 1
13353 Berlin
Germany
+4930 450566006
Mobile: 0160 93769872
peter.robinson@charite.de
http://compbio.charite.de
http://www.human-phenotype-ontology.org
Introduction to Bio-Ontologies: http://www.crcpress.com/product/isbn/9781439836651
I have learned from my mistakes, and I am sure I can repeat them exactly
ORCID ID:http://orcid.org/0000-0002-0736-9199
Scopus Author ID 7403719646
Appointment request: http://doodle.com/pnrobinson
________________________________
Von: Sebastian Köhler [notifications@github.com]
Gesendet: Freitag, 9. Oktober 2015 17:16
An: obophenotype/human-phenotype-ontology
Betreff: [human-phenotype-ontology] Flat midface (#521)


@markengelstad<https://github.com/markengelstad> Should this be a new class or is this a synonym of an existing class?

**Comment by mellybelly** [comment]
please put suggested changes on the tracker, and we can comment there about EOM representations and discuss there and on the calls


On Oct 9, 2015, at 12:30 PM, Peter Robinson <notifications@github.com<mailto:notifications@github.com>> wrote:

Please note that the HPO is using terminology from the elements of morphology project for the midface etc. Let us have a sykep to discuss before making any major changes!
-Peter

Dr. med. Peter N. Robinson, MSc.
Professor of Medical Genomics
Professor in the Bioinformatics Division of the Department of Mathematics and Computer Science of the Freie Universität Berlin
Institut für Medizinische Genetik und Humangenetik
Charité - Universitätsmedizin Berlin
Augustenburger Platz 1
13353 Berlin
Germany
+4930 450566006
Mobile: 0160 93769872
peter.robinson@charite.de<mailto:peter.robinson@charite.de>
http://compbio.charite.de
http://www.human-phenotype-ontology.org
Introduction to Bio-Ontologies: http://www.crcpress.com/product/isbn/9781439836651
I have learned from my mistakes, and I am sure I can repeat them exactly
ORCID ID:http://orcid.org/0000-0002-0736-9199<http://orcid.org/0000-0002-0736-9199>
Scopus Author ID 7403719646
Appointment request: http://doodle.com/pnrobinson
________________________________
Von: Sebastian Köhler [notifications@github.com<mailto:notifications@github.com>]
Gesendet: Freitag, 9. Oktober 2015 17:16
An: obophenotype/human-phenotype-ontology
Betreff: [human-phenotype-ontology] Flat midface (#521)


@markengelstad<https://github.com/markengelstad> Should this be a new class or is this a synonym of an existing class?

—
Reply to this email directly or view it on GitHub<https://github.com/obophenotype/human-phenotype-ontology/issues/521>.

—
Reply to this email directly or view it on GitHub<https://github.com/obophenotype/human-phenotype-ontology/issues/521#issuecomment-146922276>.

Dr. Melissa Haendel

Associate Professor
Ontology Development Group, OHSU Library
www.ohsu.edu/library/ontology<http://www.ohsu.edu/library/ontology>
Department of Medical Informatics and Clinical Epidemiology
Oregon Health & Science University
haendel@ohsu.edu<mailto:haendel@ohsu.edu>
skype: melissa.haendel
503-407-5970

**Comment by drseb** [comment]
Ok, but coming to back to original issue: @pnrobinson do you agree that *Flat midface* should be a synonym of *Hypoplasia of midface*

**Comment by pnrobinson** [comment]
These are not synonyms, see https://elementsofmorphology.nih.gov/index.cgi?tid=5b7ad34ab35682b5

Dr. med. Peter N. Robinson, MSc.
Professor of Medical Genomics
Professor in the Bioinformatics Division of the Department of Mathematics and Computer Science of the Freie Universität Berlin
Institut für Medizinische Genetik und Humangenetik
Charité - Universitätsmedizin Berlin
Augustenburger Platz 1
13353 Berlin
Germany
+4930 450566006
Mobile: 0160 93769872
peter.robinson@charite.de
http://compbio.charite.de
http://www.human-phenotype-ontology.org
Introduction to Bio-Ontologies: http://www.crcpress.com/product/isbn/9781439836651
I have learned from my mistakes, and I am sure I can repeat them exactly
ORCID ID:http://orcid.org/0000-0002-0736-9199
Scopus Author ID 7403719646
Appointment request: http://doodle.com/pnrobinson
________________________________
Von: Sebastian Köhler [notifications@github.com]
Gesendet: Freitag, 9. Oktober 2015 19:30
An: obophenotype/human-phenotype-ontology
Cc: Robinson, Peter
Betreff: Re: [human-phenotype-ontology] Flat midface (#521)


Ok, but coming to back to original issue: @pnrobinson<https://github.com/pnrobinson> do you agree that Flat midface should be a synonym of Hypoplasia of midface

**Comment by markengelstad** [comment]
just to be sure, the elements of morphology says that "Midface retrusion is different from a Flat face.", with which I agree.
But we were referring to "flat midface", not "flat face". 
I think this is an example of how confusing these terms are currently. 

To a clinician, 'hypoplasia of midface' and 'flat midface' are at least 'related' synonyms, if not exact.

Its probably not worth modifying this one term without a more consistent overall approach to midface classes (which, like you say, needs to be done in concert w/ EOM).

**Comment by drseb** [comment]
I think you're right @markengelstad . 

@pnrobinson do you agree?

**Comment by pnrobinson** [comment]
Hi Mark, can we schedule a skype to go over all of this. We should extend our definitions for all of the malr, midface, face terms and make sure they are all consistent. EoM does not really say anything about this except that malar flattening replaces malar hypoplasia and midface retrusion replaces midface hypoplasia. Therefore is there a distinction between midface hypoplasia/flat midface and midface retrusion?

**Comment by markengelstad** [comment]
Yes, absolutely, let's have a call about it.
First I am going to finish the synonyms for head and neck HPO, then I'll put the midface issues together in some kind of synopsis, with some possible solutions, and then I'll schedule a call w/ that as the main topic.

**Comment by drseb** [comment]
Please discuss during Oregon-Meeting!! @pnrobinson @markengelstad

**Comment by markengelstad** [comment]
yes, i'll look forward to it.

**Comment by pnrobinson** [comment]
Should we make Midface retrusion the prefered name for midface hypoplasia (this is what they do in Elements of Morphology). It seems that flat midface is a synonym for midface retrusion (for instance, they are used synonymously for Stickler syndrome). So I agree with the merge.

**Comment by markengelstad** [comment]
So, is midface retrusion a subclass of midface hypoplasia? Like midface
Hypoplasia in an anterior - posterior dimension?
Elements of morphology naming conventions are not in line w all of the
other work (synonyms)  we were working on a few weeks ago. Terms like
retrusion are pretty nonspecific.

**Comment by drseb** [comment]
midface retrusion is now primary label.  midface hypoplasia is synonym
