### ISSUE TITLE
HP_0009949 - typo in synonym

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#523]
A synonym for the term: 
HP_0009949
Duplication of the middle phalanx of the 2nd finger

is: <new synonym>Partial/complete duplication of the middle phalanx of the 2nd finger

Should remove he <new synonym> part of the label

**Comment by cmungall** [comment]
You mean this synonym?

```
synonym: "<new synonym>Partial/complete duplication of the middle phalanx of the 2nd finger" EXACT []
```

Tip: github will treat '<'s as HTML tags, so always escape these!

There's another OBOEdit artefact here:
```
[Term]
id: HP:0100875
name: Hemimacroglossia
def: "Increased length and width of one half of the tounge." [HPO:sdoelken]
synonym: "<new synonym>" RELATED []
is_a: HP:0000158 ! Macroglossia
created_by: doelkens
creation_date: 2011-12-01T02:15:01Z
```

**Comment by nicolevasilevsky** [comment]
Yes, that is the one I mean, thanks for the tip about github tags.
