### ISSUE TITLE
NTR: Focal impaired awareness seizure with dissociation at onset

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#5272]
"-Focal impaired awareness cognitive seizure
-Focal cognitive seizure with dissociation
---Focal impaired awareness cognitive seizure with hallucination
---Focal impaired awareness cognitive seizure with expressive dysphasia / aphasia
---Focal impaired awareness cognitive seizure with deja vu / jamais vu
---Focal impaired awareness cognitive seizure with conduction dysphasia / aphasia
---Focal impaired awareness cognitive seizure with receptive dysphasia / aphasia
---Focal impaired awareness cognitive seizure with anomia
---Focal impaired awareness cognitive seizure with impaired responsiveness
---Focal impaired awareness cognitive seizure with left-right confusion
---Focal impaired awareness cognitive seizure with forced thinking
---Focal impaired awareness cognitive seizure with auditory agnosia
---Focal impaired awareness cognitive seizure with neglect
---Focal impaired awareness cognitive seizure with impaired attention
---Focal impaired awareness cognitive seizure with illusion
---Focal impaired awareness cognitive seizure with dysgraphia / agraphia
---Focal impaired awareness cognitive seizure with dyscalculia / acalculia
---Focal impaired awareness cognitive seizure with  memory impairment
---Focal impaired awareness cognitive seizure with dyslexia / alexia
---Focal aware cognitive seizure with dissociation
---NTR: Focal impaired awareness seizure with dissociation at onset
label: Focal impaired awareness seizure with dissociation at onset
def: A focal cognitive seizure with dissociation characterized by impairment of awareness at some point during the seizure.
http://purl.org/dc/elements/1.1/source: www.epilepsydiagnosis.org
@DLewisSmith
@galerp
@shiva-g
@ihelbig
@GBalagura
@hughkearney"
PMID:28276060: https://www.ncbi.nlm.nih.gov/pubmed/PMID:28276060

**Comment by pnrobinson** [comment]
@DLewisSmith
@galerp
@shiva-g
@ihelbig
@GBalagura
@hughkearney

I think the definition above should be the following:
A focal cognitive seizure with dissociation characterized by impairment of awareness at the onset of the seizure.

Please reopen this issue if it is not correct.

**Comment by DLewisSmith** [comment]
No, I think this should be:

Label: Focal impaired awareness seizure with dissociation at onset
Definition:  A focal cognitive seizure with dissociation characterized by impairment of awareness at some point during the seizure.

Thus it is a type of seizure both starting with a sense of dissociation, and during which at some point there is an impairment of awareness. It could include a seizure in which one feels dissociated but is aware at onset so long as they subsequently have an impairment of awareness during the seizure (thus meeting the definition of a focal impaired awareness seizure).

It is a child of (and its definition is refers to):
Label: Focal cognitive seizure with dissociation
Definition: A focal cognitive seizure characterized by an experience of being disconnected from, though aware of, self or environment as the initial semiological manifestation.

Does this make sense?
