### ISSUE TITLE
NTR: Focal automatism seizure

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#5287]
"-Focal motor seizure
---Focal clonic seizure
---Focal motor impaired awareness seizure
---Focal motor seizure with dystonia
---Focal motor seizure with dysarthria / anarthria
---Focal bilateral motor seizure
---Focal myoclonic seizure
---Focal motor aware seizure
---Focal-onset epileptic spasm
---Focal atonic seizure
---Focal hyperkinetic seizure
---Focal motor seizure with paresis / paralysis
---Focal motor seizure with version
---Focal motor seizure with negative myoclonus
---Focal tonic seizure
---NTR: Focal automatism seizure
-----Focal impaired awareness automatism seizure
-----Focal aware automatism seizure
label: Focal automatism seizure
def: A focal seizure characterized at onset by coordinated motor activity. This often resembles a voluntary movement and may consist of an inappropriate continuation of preictal motor activity.
comment: An automatism is a coordinated, repetitive motor activity, often resembling a voluntary movement, but undertaken without volition. Focal automatism seizures can be further described using the following descriptors:
- Orofacial: lip smacking, lip pursing, chewing, swallowing, clicking, eye-blinking.
- Manual: unilateral or bilateral, fumbling, tapping, manipulating or exploratory movements with The hands.
- Pedal: bilateral or unilateral movements of The feet/legs, these may include pacing, walking or running. The movement is more reminiscent of normal movements in amplitude, and is less frenetic or rapid in comparison to the movements seen in focal hyperkinetic seizures involving The legs. However, some automatisms overlap other motor behaviors.
- Perseverative: The movement consists of an inappropriate continuation of pre-seizure movement.
- Vocal: single or repetitive sounds such as shrieks or grunts.
- Verbal: single or repetitive words, phrases or brief sentences.
- Sexual: Sexual behaviours.
- Other: automatisms can include head nodding, undressing and a range of other automatic movements.
source: PMID: 11580774, 28276064, 28276060
seeAlso: Partial seizure with automatism at onset, Localized seizure with automatism at onset, Localised seizure with automatism at onset
http://webprotege.stanford.edu/RiCnLhdRh6VgSt0KNJ92ib: ILAE 2017
@DLewisSmith
@galerp
@shiva-g
@ihelbig
@GBalagura
@hughkearney"
PMID:28276060: https://www.ncbi.nlm.nih.gov/pubmed/PMID:28276060

**Comment by pnrobinson** [comment]
@DLewisSmith
@galerp
@shiva-g
@ihelbig
@GBalagura
@hughkearney

Would it make sense to make subterms for the various descriptors above?

**Comment by DLewisSmith** [comment]
Probably, I’ll put them on my to do list...

**Comment by DLewisSmith** [comment]
Peter could you create the following 9 child terms for ‘Focal automatism seizure’. These should reference ‘epilepsydioagnsis.org’ as the source.

> Label	Definition	Comment
> Focal orofacial automatism seizure	A type of focal automatism seizure characterized by orofacial automatisms at onset.	These may include involuntary lip smacking, lip pursing, chewing, swallowing, clicking sounds, or eye-blinking.
> Focal manual automatism seizure	A type of focal automatism seizure characterized by manual automatisms at onset. 	These may include involuntary unilateral or bilateral, fumbling, tapping, manipulating, or exploratory movements of the hands.
> Focal pedal automatism seizure	A type of focal automatism seizure characterized by coordinated bilateral or unilateral movements of the feet or legs at onset. The movement is more reminiscent of normal movements in amplitude, and is less frenetic or rapid in comparison to the movements seen in focal hyperkinetic seizures involving the legs.	These may include pacing, walking, or running. 
> Focal perseverative automatism seizure	A type of focal automatism seizure characterized by inappropriate continuation of pre-seizure movement or behavior at onset. 	 
> Focal vocal automatism seizure	A type of focal automatism seizure characterized by the production of single or repetitive meaningless vocal sounds such as shrieks or grunts at onset. 	 
> Focal verbal automatism seizure	A type of focal automatism seizure characterized by the production of single or repetitive words, phrases, or brief sentences at onset. 	 
> Focal sexual automatism seizure	A type of focal automatism seizure characterized by involuntary sexual behavior at onset. 	 
> Focal head nodding automatism seizure	A type of focal automatism seizure characterized by involuntary head nodding at onset. 	 
> Focal undressing automatism seizure	A type of focal automatism seizure characterized by involuntary undressing at onset. 	 



Each of these should a ‘Focal aware … automatism seizure’ and an ‘Focal impaired awareness … automatism seizure’ child term. These 18 should each have dual parentage with 'Focal aware automatism seizure’ or ‘Focal impaired awareness automatism seizure’ as appropriate.

Is this sufficient for you to work with Peter?

**Comment by pnrobinson** [comment]
Sounds good! I am adding these terms.
