### ISSUE TITLE
ancestors of Palmoplantar hyperkeratosis

### ISSUE THREAD

**Issue by cmungall** [obophenotype/human-phenotype-ontology#530]
![pp](https://cloud.githubusercontent.com/assets/50745/10987214/11e9e23a-83e6-11e5-9de2-86c9c2cc789b.png)

**Comment by cmungall** [comment]
* The two hyperkeratosis classes should be under the general palm/sole abnormalities
 * plantar skin abnormality should go up to foot
 * (Minor) consider aligning terminology. Either formal "palmar skin of hand" or informal "sole" - but use the same style for both

**Comment by cmungall** [comment]
Also, note the dual parentage to both 'generalize' and 'localized' skin abnormality. Which is it? I assume it should be localized and the weird link here should be removed:

```
    is_a HP:0000951 ! Abnormality of the skin
     is_a HP:0011354 ! Generalized abnormality of skin ***
      is_a HP:0011121 ! Abnormality of skin morphology  
```

**Comment by drseb** [comment]
Thanks. I think this has been improved now. Please re-open if this solution does not do what you had in mind.
