### ISSUE TITLE
NTR: Focal aware sensory seizure with visual features

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#5318]
"-Focal aware sensory seizure
-Focal sensory seizure with visual features
---Focal aware sensory seizure with somatosensory features
---Focal aware sensory seizure with hot-cold sensations
---Focal aware sensory seizure with cephalic sensation
---Focal aware sensory seizure with auditory features
---Focal aware sensory seizure with gustatory features
---Focal aware sensory seizure with olfaction
---Focal aware sensory seizure with vestibular features
---Focal impaired awareness sensory seizure with visual features
---NTR: Focal aware sensory seizure with visual features
label: Focal aware sensory seizure with visual features
def: A seizure characterized by elementary visual hallucinations such as flashing or flickering lights/colours, or other shapes, simple patterns, scotomata, or amaurosis.
comment: More complex visual hallucinations such as seeing formed images are considered a focal cognitive seizure. Focal sensory visual seizures arise in the occipital lobe.
http://webprotege.stanford.edu/RiCnLhdRh6VgSt0KNJ92ib: ILAE2017
http://purl.org/dc/elements/1.1/source: www.epilepsydiagnosis.org
@DLewisSmith
@galerp
@shiva-g
@ihelbig
@GBalagura
@hughkearney"
PMID:28276060: https://www.ncbi.nlm.nih.gov/pubmed/PMID:28276060

**Comment by pnrobinson** [comment]
@DLewisSmith
@galerp
@shiva-g
@ihelbig
@GBalagura
@hughkearney

The proposed definition does not take the "aware" into account, please check!

**Comment by DLewisSmith** [comment]
Yes, sorry Peter. I don’t know how they slipped through (worrying how much work we can put in and still miss things). Well done for picking up on it.

I suggest keeping our structure of 'A type of focal ... seizure during which awareness is retained throughout the seizure.’ or

'A type of focal ... seizure in which awareness is partially or fully impaired at some point during the seizure.'
