### ISSUE TITLE
NTR: Focal aware sensory seizure with hot-cold sensations

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#5329]
"-Focal aware sensory seizure
-Focal sensory seizure with hot-cold sensation
---Focal aware sensory seizure with somatosensory features
---Focal aware sensory seizure with visual features
---Focal aware sensory seizure with cephalic sensation
---Focal aware sensory seizure with auditory features
---Focal aware sensory seizure with gustatory features
---Focal aware sensory seizure with olfaction
---Focal aware sensory seizure with vestibular features
---Focal impaired awareness sensory seizure with hot-cold sensations
---NTR: Focal aware sensory seizure with hot-cold sensations
label: Focal aware sensory seizure with hot-cold sensations
def: A seizure characterized by sensations of feeling hot and then cold.
http://webprotege.stanford.edu/RiCnLhdRh6VgSt0KNJ92ib: ILAE2017
http://purl.org/dc/elements/1.1/source: www.epilepsydiagnosis.org
@DLewisSmith
@galerp
@shiva-g
@ihelbig
@GBalagura
@hughkearney"
PMID:28276060: https://www.ncbi.nlm.nih.gov/pubmed/PMID:28276060

**Comment by pnrobinson** [comment]
@DLewisSmith
@galerp
@shiva-g
@ihelbig
@GBalagura
@hughkearney

Can you please check this definition, it appears to pertain to the generic hot-cold seizure but does not include the "aware" part.

**Comment by DLewisSmith** [comment]
Yes, sorry Peter. I don’t know how they slipped through (worrying how much work we can put in and still miss things). Well done for picking up on it.

I suggest keeping our structure of 'A type of focal ... seizure during which awareness is retained throughout the seizure.’ or

'A type of focal ... seizure in which awareness is partially or fully impaired at some point during the seizure.'
