### ISSUE TITLE
Wrong synonym

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#533]
in Prominence of the zygomatic bone (HP:0012370)

**Comment by drseb** [comment]
@markengelstad Please make sure that labels/synonyms are not already present in the ontology. Here, the synonym "Malar prominence" is already the label of the class HP_0010620

**Comment by markengelstad** [comment]
Indeed, I usually do, and sometimes one gets by where I don't expect it to
be. I'll try to do better.

Zygoma/ malar / midface continues to be a hierarchy worth a bit of future
time to straighten out.
