### ISSUE TITLE
NTR: Focal aware sensory seizure with auditory features

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#5372]
"-Focal aware sensory seizure
-Focal sensory seizure with auditory features
---Focal aware sensory seizure with somatosensory features
---Focal aware sensory seizure with visual features
---Focal aware sensory seizure with hot-cold sensations
---Focal aware sensory seizure with cephalic sensation
---Focal aware sensory seizure with gustatory features
---Focal aware sensory seizure with olfaction
---Focal aware sensory seizure with vestibular features
---Focal impaired awareness sensory seizure with auditory features
---NTR: Focal aware sensory seizure with auditory features
label: Focal aware sensory seizure with auditory features
def: A seizure characterized by elementary auditory phenomena including buzzing, ringing, drumming or single tones.
comment: More complex auditory hallucinations such as voices are considered a focal cognitive seizure. Focal sensory auditory seizures involve auditory cortex in the lateral superior temporal lobe.
http://webprotege.stanford.edu/RiCnLhdRh6VgSt0KNJ92ib: ILAE2017
http://purl.org/dc/elements/1.1/source: www.epilepsydiagnosis.org
@DLewisSmith
@galerp
@shiva-g
@ihelbig
@GBalagura
@hughkearney"
PMID:28276060: https://www.ncbi.nlm.nih.gov/pubmed/PMID:28276060

**Comment by pnrobinson** [comment]
@DLewisSmith
@galerp
@shiva-g
@ihelbig
@GBalagura
@hughkearney

Also here the definition does not have "aware". Should I just fix cases like this? Please advise.

**Comment by DLewisSmith** [comment]
Yes, sorry Peter. I don’t know how they slipped through (worrying how much work we can put in and still miss things). Well done for picking up on it.

I suggest keeping our structure of 'A type of focal ... seizure during which awareness is retained throughout the seizure.’ or

'A type of focal ... seizure in which awareness is partially or fully impaired at some point during the seizure.'

**Comment by pnrobinson** [comment]
Thanks! Updating definition...
