### ISSUE TITLE
NTR: Focal aware sensory seizure with gustatory features

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#5405]
"-Focal aware sensory seizure
-Focal sensory seizure with gustation
---Focal aware sensory seizure with somatosensory features
---Focal aware sensory seizure with visual features
---Focal aware sensory seizure with hot-cold sensations
---Focal aware sensory seizure with cephalic sensation
---Focal aware sensory seizure with auditory features
---Focal aware sensory seizure with olfaction
---Focal aware sensory seizure with vestibular features
---Focal impaired awareness sensory seizure with gustation
---NTR: Focal aware sensory seizure with gustatory features
label: Focal aware sensory seizure with gustatory features
def: A seizure characterized by taste phenomena including acidic, bitter, salty, sweet, or metallic tastes.
comment: These seizures involve the parietal operculum and the insula.
http://webprotege.stanford.edu/RiCnLhdRh6VgSt0KNJ92ib: ILAE2017
http://purl.org/dc/elements/1.1/source: www.epilepsydiagnosis.org
@DLewisSmith
@galerp
@shiva-g
@ihelbig
@GBalagura
@hughkearney"
PMID:28276060: https://www.ncbi.nlm.nih.gov/pubmed/PMID:28276060

**Comment by pnrobinson** [comment]
@DLewisSmith
@galerp
@shiva-g
@ihelbig
@GBalagura
@hughkearney"


The super term is called

Focal aware sensory seizure with gustation

Should we adjust the labels for consistency?

**Comment by DLewisSmith** [comment]
Yes sorry Peter.

The focal sensory seizure subtypes ‘with gustation’ and ‘with olfaction’ should probably be ‘with gustatory features’ and with ‘with olfactory features’ respectively, each with aware and impaired awareness subtypes.
