### ISSUE TITLE
merge classes Pineoblastoma

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#541]
merge
* Pineoblastoma (HP:0030408) 
* Pinealoblastoma (HP:0040193)

**Comment by drseb** [comment]
note: structure has to be revised

**Comment by drseb** [comment]
@pnrobinson to advise

see [hpo-structure-pineoblastoma.pdf](https://github.com/obophenotype/human-phenotype-ontology/files/81158/hpo-structure-pineoblastoma.pdf) for current structure

**Comment by pnrobinson** [comment]
Revised the definition of this class and revised the structure and added cross refs to NCIT.
