### ISSUE TITLE
Roles in ChEBI

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#545]
We have used *hormone* in a logical def. But *hormone* is a **biological role** in ChEBI.

Repair def?
make quality check?

**Comment by drseb** [comment]
@cmungall possible to model something like: 'molecular entity' and ('has role' some 'hormone')

**Comment by cmungall** [comment]
We use this in GO http://purl.obolibrary.org/obo/go/extensions/substance_by_role.owl

So you could use
http://purl.obolibrary.org/obo/GOCHE_24621

(warning: not a registered ID space)

BUT this is all a bit contorted. It may be better to model the biology more directly, by using the classes below

```
 / GO:0003674 ! molecular_function
  is_a GO:0005488 ! binding
   is_a GO:0005515 ! protein binding
    is_a GO:0005102 ! receptor binding
     is_a GO:0005179 ! hormone activity *** 
      is_a GO:0005183 ! gonadotropin hormone-releasing hormone activity
      is_a GO:0005184 ! neuropeptide hormone activity
      is_a GO:0008437 ! thyrotropin-releasing hormone activity
      is_a GO:0008613 ! diuretic hormone activity
      is_a GO:0016084 ! myostimulatory hormone activity
      is_a GO:0016085 ! myoinhibitory hormone activity
      is_a GO:0016521 ! pituitary adenylate cyclase activating polypeptide activity
      is_a GO:0016608 ! growth hormone-releasing hormone activity
      is_a GO:0016913 ! follicle-stimulating hormone activity
      is_a GO:0017044 ! melanocyte-stimulating hormone activity
      is_a GO:0017045 ! corticotropin-releasing hormone activity
      is_a GO:0030354 ! melanin-concentrating hormone activity
      is_a GO:0046659 ! digestive hormone activity
      is_a GO:0070186 ! growth hormone activity
```

**Comment by cmungall** [comment]
See also definitions in https://github.com/cmungall/chiro

**Comment by pnrobinson** [comment]
I have moved this topic to the HPO wiki page on this github repository, "design patterns for lab values"

**Comment by cmungall** [comment]
On 23 Nov 2015, at 7:43, Sebastian Köhler wrote:

> [@cmungall](https://github.com/cmungall) possible to model something 
> like: 'molecular entity' and ('has role' some 'hormone')

Yes, in go-plus you will actually see named classes of this form (ID 
space "GOCHE"). We need to make this more visible and easier to use.
