### ISSUE TITLE
Decreased carnitine level in liver

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#547]
Same for decreased carnitine in heart
Make subclass of HP_0010967
Look at OMIM for PubMed citations and also reannotate this disease
http://www.omim.org/clinicalSynopsis/212140

**Comment by drseb** [comment]
It would be nicer if you could also file a ticket in the [annotation repository](https://github.com/monarch-initiative/hpo-annotation-data) when an HPO-edit requires updating annotations. Issues can be cross-referenced.
