### ISSUE TITLE
logical def is wrong for HP_0100008 Schwannoma?

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#5491]
**HPO term**
HP_0100008 Schwannoma

**Suggested revision of logical definition**
This is the logical def:

'has part' some 
    (quality
     and ('inheres in' some 'myelinating Schwann cell')
     and ('has modifier' some abnormal))

The text def is:
A benign nerve sheath tumor composed of Schwann cells.

I think we should delete the logical def

**Comment by pnrobinson** [comment]
I agree, the logical def is not that great!
