### ISSUE TITLE
question about PATO aplastic growth

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#5496]
Hi Peter,
There are three terms in HPO that use the PATO term 'aplastic growth' instead of 'agenesis' in the logical def:

ID | Label
-- | --
http://purl.obolibrary.org/obo/HP_0005938 | Abnormal respiratory motile cilium morphology
http://purl.obolibrary.org/obo/HP_0008459 | Cervical vertebral agenesis | http://purl.obolibrary.org/obo/UBERON_0002413
http://purl.obolibrary.org/obo/HP_0008715 | Testicular dysgenesis | http://purl.obolibrary.org/obo/UBERON_0000473

Is there a reason why these use 'aplastic growth' vs 'agenesis'? Or could we switch the PATO quality to 'agenesis'?

Thanks!

**Comment by pnrobinson** [comment]
We do not distinguish between aplasia and agenesis so go ahead and switch!

**Comment by nicolevasilevsky** [comment]
ok! :)
