### ISSUE TITLE
typo/definition/hierarchy for HP:0040185 Macrothrombozytopenia suggestions

### ISSUE THREAD

**Issue by lcdaugherty** [obophenotype/human-phenotype-ontology#550]
http://compbio.charite.de/hpoweb/showterm?id=HP:0040185
Currently HPO term is spelt : Macrothrombozytopenia, but this should be Macrothrombocytopenia (cytopenia not zytopenia)

Macrothrombozytopenia is currently a sub term of Increased mean platelet volume and Thrombocytopenia.

Thrombocytopenia simply means that platelet number is reduced. It does not imply any qualitative abnormality. Macrothrombocytopenia means that the platelets are reduced in number AND that they are abnormally large (could be on Mean Platelet Volume or morphology) which is a quite different qualitative abnormality. This might seem subtle but it leads down a completely different diagnostic path, so I wonder if Macrothrombozytopenia should also be associated to Giant platelets?

 Thanks!

**Comment by drseb** [comment]
Thanks @lcdaugherty 

So you are suggesting two changes:
 - ...zytopenia --> ...cytopenia . Ok.
 - add another superclass to *Macrothrombozytopenia*. Which one? (I didn't get that from your text)

**Comment by lcdaugherty** [comment]
@dseb I have now taken out <> tags from my original message, so hopefully it will now be less of a mystery! (but just in case...suggesting Giant Platelets)

**Comment by drseb** [comment]
@lcdaugherty So at the moment *Macrothrombozytopenia* is a subclass of:
 - *Increased mean platelet volume* and
 - *Thrombocytopenia*

Do I understand correctly, that you would like to replace *Increased mean platelet volume* with *Giant platelets* ?

**Comment by lcdaugherty** [comment]
@drseb You don't need to replace the subclass association. Please keep Macrothrombocytopenia as a subclass of Increased mean platelet volume and Thrombocytopenia.
My question relates to Giant platelets, they are only present in a subgroup of macrothrombocytopenias, so I wonder if Giant platelets should be a subgroup of macrothrombocytopenia, rather than at the same level?

**Comment by drseb** [comment]
Ok, I understand. Is it possible that you are mixing up *Giant platelet disease* with the isolated finding *Giant platelets*? 
In HPO we refer to the latter. E.g. the text-def of the HPO class states: "Giant platelets are larger than 7 micrometers and usually 10 to 20 micrometers.".
*Giant platelet disorder* on the contrary is associated with findings such as *Giant platelets*, *Thrombocytopenia* and others. 
Please re-open if you disagree.
ping: @pnrobinson
