### ISSUE TITLE
NCBITaxon_7742 has missing label in hp.owl

### ISSUE THREAD

**Issue by matentzn** [obophenotype/human-phenotype-ontology#5500]
This is because the term is used for some CL class definition, and we only import CL-base, not all its dependencies. There are 3 ways to deal with such cases:

1) We invent a way to remove stray terms prior to release
2) We import ncbitaxon (nooooooooo huuuuuuuge)
3) We revert to mirroring from cl.owl rather than cl-base.owl.

This is not of great importance right now, but I need to take care of this at some point in general.

**Comment by drseb** [comment]
remove stray terms

**Comment by pnrobinson** [comment]
@drseb @matentzn  What is the action item here? Is this still pending?

**Comment by matentzn** [comment]
Here is a fix (includes also refreshing of imports).
https://github.com/obophenotype/human-phenotype-ontology/pull/6622
