### ISSUE TITLE
Glucose intolerance should use increased restistance instead of abnormal resistance.

### ISSUE THREAD

**Issue by matentzn** [obophenotype/human-phenotype-ontology#5501]
**HPO term**
[HP_0001952](https://www.ebi.ac.uk/ols/ontologies/hp/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FHP_0001952)

**Suggested revision of logical definition**
Should use: [Increased resistance to (PATO_0001650)](https://www.ebi.ac.uk/ols/ontologies/pato/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0001650) rather than merely abnormal resistance to.

Additional suggestion: 
- [x] Abnormal glucose tolerance should NOT be an exact synonym, either a broader synonym or a related one.

**Comment by matentzn** [comment]
Sorry, edit: The definition is also missing the bearer. If I understand the concept correctly, it should also inhere in whole organism! See corresponding pattern:
https://raw.githubusercontent.com/obophenotype/upheno/master/src/patterns/dosdp-dev/abnormallyIncreasedResistanceOfWholeOrganismToChemicalEntity.yaml

**Comment by pnrobinson** [comment]
increased resistance to would be correct.
There is a complicated pathophysiology that cannot easily be captured in OWL, and it is not the whole organism that has the resistance (e.g., the hair does not). How are we doing this elsewhere?

**Comment by matentzn** [comment]
The [abnormallyIncreasedResistanceOfWholeOrganismToEntity pattern](https://raw.githubusercontent.com/obophenotype/upheno/master/src/patterns/dosdp-dev/abnormallyIncreasedResistanceOfWholeOrganismToEntity.yaml) has been agreed to be used for this case. I will raise it again today, I think we have glossed the question of "what exactly is intolerant".

Will raise it at the phenotype call today mentioning your concern.

**Comment by nicolevasilevsky** [comment]
I think this pattern should be:

'has part' some 
    ('resistance to'
     and (towards some ('glucose import' and ('inheres in' some cell)))
     and ('has modifier' some abnormal))

**Comment by dosumis** [comment]
> increased resistance to would be correct.
> There is a complicated pathophysiology that cannot easily be captured in OWL, and it is not the whole organism that has the resistance (e.g., the hair does not)

To say that  something inheres in the whole organism does not mean that every cell must be affected.  

'Complicated pathophysiology that cannot easily be captured in OWL' sounds like something we should punt into a PATO quality.  Wouldn't defining in terms of 'glucose import'  alone - esp glucose import on cell level - be too limiting re mechanism?

**Comment by pnrobinson** [comment]
inheres in some cell seems to be a reasonable definition!

**Comment by pnrobinson** [comment]
@matentzn @drseb 
I think 'increased resistance to' needs to be mireoted. Still don't know how to do this?

**Comment by matentzn** [comment]
Here:

https://github.com/obophenotype/human-phenotype-ontology/wiki/Add-classes-from-external-ontologies

But @nicolevasilevsky can also do this when she adds the EQs.

**Comment by pnrobinson** [comment]
@nicolevasilevsky can we implement this?

**Comment by nicolevasilevsky** [comment]
I added the PATO class 'increased resistance to' and revised the logical def to:

'has part' some
('increased resistance to'
and (towards some ('glucose import' and ('inheres in' some cell)))
and ('has modifier' some abnormal))

is this correct?

See linked PR

**Comment by pnrobinson** [comment]
@nicolevasilevsky  This seems correct!
Unless somebody has additional thoughts I think we can accept the PR

**Comment by matentzn** [comment]
Wait no; not exactly.

**Comment by matentzn** [comment]
‘has part' some
('increased resistance to'
and ('inheres in' some cell) and
(towards some 'glucose import')
and ('has modifier' some abnormal))

This would mean that the cell has an abnormally increased resistance to glucose import. @nicolevasilevsky did you make sure this corresponds exactly to the resistance pattern?

**Comment by nicolevasilevsky** [comment]
I think this sounds correct - the cell has increased resistance to glucose import.

This is the corresponding pattern, right?
https://github.com/obophenotype/upheno/blob/master/src/patterns/dosdp-dev/abnormallyIncreasedResistanceOfWholeOrganismToChemicalEntity.yaml

I see -  I have it backwards.
I fixed it.

**Comment by nicolevasilevsky** [comment]
I'll merge the PR when the build passes

Thank you @matentzn

**Comment by matentzn** [comment]
This is not the _exact_ pattern but close enough (no filler for anatomical entity). :) but that’s good then! I approve.

**Comment by pnrobinson** [comment]
OK so I am not going to quit my job and try to earn money as a LISP programmer, clearly lots of infernal stinky parentheses are too confusing...but thanks, it looks correct now, at least I think.

**Comment by matentzn** [comment]
Hahaha.
