### ISSUE TITLE
logical def for dysmotility terms

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#5502]
@pnrobinson on the phenotype editors call today, we discussed the logical defs for these terms, which currently follow the pattern below:
HP_0002579 Gastrointestinal dysmotility
HP_0012850 'Small intestinal dysmotility' 

equivalentTo:
  text: "'has_part' some ('contractility' and ('inheres_in' some %s) and ('has_modifier' some 'abnormal'))"
  vars:
  -anatomical_entity

Instead of using the PATO quality 'contractility' in the logical def, do you think we could use GO terms:

**HP_0002579 Gastrointestinal dysmotility**

'has part' some 
    ('decreased rate'
     and ('inheres in' some 'gastro-intestinal system smooth muscle contraction')
     and ('has modifier' some abnormal))

**HP_0012850 'Small intestinal dysmotility'** 

'has part' some 
    ('decreased rate'
     and ('inheres in' some 'small intestine smooth muscle contraction')
     and ('has modifier' some abnormal))

**Comment by nicolevasilevsky** [comment]
cc @matentzn

**Comment by pnrobinson** [comment]
The GO-based definitions seem reasonable. I guess the question is whether they will work in terms of subsumption inference for Q/C of HP?

**Comment by matentzn** [comment]
Yes, thanks @pnrobinson - We are keeping in an eye on these things. For now, the important bit is to determine common patterns for all cases and apply them consistently - contractility is such a specialised concept that I do not expect any changes in subsumption (maybe @nicolevasilevsky when you make the change, run the reasoner before and after and see what the reasoner says - this may be good practice whenever you change a pattern. What to look out for: new inferred super classes; new inferred subclasses).
