### ISSUE TITLE
Adding new terms to HPO

### ISSUE THREAD

**Issue by Marwaabdelhakim** [obophenotype/human-phenotype-ontology#5504]
[15 terms.xlsx](https://github.com/obophenotype/human-phenotype-ontology/files/4281182/15.terms.xlsx)

**Comment by drseb** [comment]
Thanks @Marwaabdelhakim .

Peter, can you have a look? Some suggestions don't really look too good for HPO

**Comment by pnrobinson** [comment]
I will script one issue each for these suggestions. Some look like good HPO terms, some will require some modifications or more information.

**Comment by pnrobinson** [comment]
These are the 15 items

- [ ] Globotriaosylceramide (Gb3) accumulation.	https://www.ncbi.nlm.nih.gov/pubmed/29982630	https://www.ncbi.nlm.nih.gov/pubmed/12427118		
- [ ] Membrane fluidity alterations	https://link.springer.com/article/10.1186/s13024-018-0300-6	https://www.ncbi.nlm.nih.gov/pubmed/29660499		
- [ ] High intraneuronal GSL storage	https://www.ncbi.nlm.nih.gov/pubmed/19750228			HP:0004343
- [ ] High excretion of 3-hydroxyisovaleric acid 	https://www.ncbi.nlm.nih.gov/pubmed/7133811			
- [ ] Impaired oxidative phosphorylation	https://www.ncbi.nlm.nih.gov/pubmed/15480852			
- [ ] Low bone marrow fat fraction value	https://www.ncbi.nlm.nih.gov/pubmed/30066229			
- [ ] Hypoglycosylation of serum glycoproteins	https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6331365/	https://omim.org/entry/602579?ux=4becea6b-ee45-4cb8-9aff-82ed18485918&ux2=6e40bb43-9c2b-45ae-b9cc-bb9b4782e6ed&ux3=&ux4=&uxconf=Y		
- [ ] High plasma levels of hexacosanoic acid	https://www.ncbi.nlm.nih.gov/pubmed/18026827	https://jnnp.bmj.com/content/jnnp/67/3/299.full.pdf	https://www.ncbi.nlm.nih.gov/pubmed/10870849	
- [ ] Primapterinuria	https://www.ncbi.nlm.nih.gov/pubmed/24204001			
- [ ] 3-methylcrotonyl-CoA accumulation	https://www.ncbi.nlm.nih.gov/pubmed/7474896			
- [ ] Abnormal substantial transport activity	https://www.ncbi.nlm.nih.gov/pubmed/29341259			
- [ ] Verruciform Xanthoma (VX) like lesions	https://www.ncbi.nlm.nih.gov/pubmed/29341259			
- [ ] Elevated Urinary 2,8-dihydroxyadenine (DHA) excretion	https://www.ncbi.nlm.nih.gov/pubmed/29241594			
- [ ] lipid peroxidation	https://www.ncbi.nlm.nih.gov/pubmed/28396261?dopt=Abstract	https://www.ncbi.nlm.nih.gov/pubmed/26141703		
- [ ] Elevated intraneuronal cholesterol	https://www.ncbi.nlm.nih.gov/pubmed/19750228?dopt=Abstract	https://www.intechopen.com/books/cyclodextrin-a-versatile-ingredient/use-of-2-hydroxypropyl-beta-cyclodextrin-for-niemann-pick-type-c-disease

**Comment by pnrobinson** [comment]
7-biopterin and primapterin seem to be synonyms => check. Primapterinuria
https://hpo.jax.org/app/browse/term/HP:0040210

**Comment by Marwaabdelhakim** [comment]
Yes, that’s correct. I hope it can be added as a synonym in the HPO term


On 22 Mar 2020, at 6:02 PM, Peter Robinson <notifications@github.com<mailto:notifications@github.com>> wrote:

primapterin

**Comment by pnrobinson** [comment]
- [ ] Elevated circulating globotriaosylceramide concentration. Def Increased concentration of globotriaosylceramide (Gb3) in the blood circulation. Globotriaosylceramide, also named ceramidetrihexoside (CTH), is the primary lipid storage in Fabry disease. 
--- child of https://hpo.jax.org/app/browse/term/HP:0004343  See https://pubmed.ncbi.nlm.nih.gov/17073606/

Intraneuronal glycosphingolipid accumulation  -- see https://pubmed.ncbi.nlm.nih.gov/19750228/

**Comment by pnrobinson** [comment]
- [ ] primapterinuria Increased level of primapterin (7-biopterin) in the urine. -- what is the optimal parent?

**Comment by pnrobinson** [comment]
- [ ]  https://www.ncbi.nlm.nih.gov/pmc/articles/PMC199271/  -- see for  3-methylcrotonyl-CoA accumulation

**Comment by pnrobinson** [comment]
@Marwaabdelhakim sorry for the delay, these are difficult terms. I have tried to find definitions and added the terms I could. In the future, please use our new template - but thanks for these suggestions!
