### ISSUE TITLE
genes_to_phenotype.txt order of header and content mismatch (HPO-Term-Name and HPO-Term-ID)

### ISSUE THREAD

**Issue by tobias2019** [obophenotype/human-phenotype-ontology#5505]
Hi,

I just noticed a mismatch of the header and the content in [genes_to_phenotype.txt](http://compbio.charite.de/jenkins/job/hpo.annotations/lastSuccessfulBuild/artifact/util/annotation/genes_to_phenotype.txt). 

While the header says `...HPO-Term-Name<tab>HPO-Term-ID...`, the content uses the reversed order.

`#Format: entrez-gene-id<tab>entrez-gene-symbol<tab>HPO-Term-Name<tab>HPO-Term-ID<tab>Frequency-Raw<tab>Frequency-HPO<tab>Additional Info from G-D source<tab>G-D source<tab>disease-ID for link
8192	CLPP	HP:0000007	Autosomal recessive inheritance			-	mim2gene	OMIM:614129`

**Comment by drseb** [comment]
Thanks. Will fix the header line in new release.

**Comment by pnrobinson** [comment]
@drseb can we close?
