### ISSUE TITLE
Add terms for BioGrid

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#5509]
See [spreadsheet](https://docs.google.com/spreadsheets/d/167Xb0ew231G5DASkgbNyiy4zA77q19VmgbINA4MKhY0/edit#gid=2093245390)

Related tickets:
https://github.com/obophenotype/upheno/issues/586
https://github.com/obophenotype/mammalian-phenotype-ontology/issues/3164

@pnrobinson could you review this spreadsheet and let me know if you have any objections to adding any of these terms? I'll coordinate with @sbello to ensure we are consistent with MP.

cc @matentzn

**Comment by nicolevasilevsky** [comment]
@pnrobinson I can work on adding these new terms on a PR, then assign you to review before commiting

**Comment by pnrobinson** [comment]
I would say that almost all of these terms are not good HPO terms. Abnormal resistance to chemicals for instance is an inference about molecular mechanism, not a phenotype observation. Can we know more about the use case?

**Comment by nicolevasilevsky** [comment]
Thanks for the feedback, @pnrobinson. Here is more info:

The BioGRID database:

https://thebiogrid.org/

has recently started curating phenotypes resulting from CRISPR screens in human cell lines and have compiled the results of their curation into the ORCS database:

https://orcs.thebiogrid.org/

They are currently assigning phenotypes (traits really) to the various screen hits to indicate what was observed during the screen (what was being screened for). These are the terms currently used:

cell cycle progression (APO:0000253)
protein transport (APO:0000129)
protein/peptide accumulation (APO:0000149)
regulation of signal transduction phenotype (CMPO:0000040)
resistance to chemicals (APO:0000087)
resistance to virus
toxin resistance (APO:0000215)
Tumorigenicity
viability (APO:0000111) 

Many terms are coming from APO (Ascomycete phenotype ontology) used by SGD and others in the yeast/fungi community and with which BioGRID is familiar as they have curated many genetic interactions in yeast. BioGRID would like to request more appropriate terms to apply to their annotations, but it isn't clear if these terms should be added to HPO, CMPO, or some other ontology as these are cell-line-specific phenotypes. I'm creating this ticket to discuss the matter. I've requested that BioGRID submit relative phenotype terms, e.g. "decreased viability", so as to clarify the needs.

(see ticket for more info: https://github.com/obophenotype/upheno/issues/586)

**Comment by pnrobinson** [comment]
I am going to close this issue -- as far as I can see these are not phenotype terms, these are pathomechanisms. Please open individual term requests as needed if this is incorrect!
