### ISSUE TITLE
Adrenal medullary hypoplasia HP:0008239 - revise EQ

### ISSUE THREAD

**Issue by anna-anagnostop** [obophenotype/human-phenotype-ontology#5511]
**HPO term**
Adrenal medullary hypoplasia HP:0008239

**Suggested revision of logical definition**

has part some (hypoplastic
      and (inheres
      in some 
      adrenal medulla) and (has
      modifier some 
      abnormal))
    
EQ currently uses **_hyperplastic_** (wrong)

**Comment by pnrobinson** [comment]
Thanks for pointing out this error, I just fixed it!

**Comment by anna-anagnostop** [comment]
Great, thank you.
Anna
