### ISSUE TITLE
mild albuminuria

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#5519]
Missing Term: ,HP:0012594,The presence of mildly increased concentrations of albumin in the urine (in adults, less than 30 mg per day).,Microalbuminuria

**Comment by pnrobinson** [comment]
Is this synonymous with Microalbuminuria?
https://hpo.jax.org/app/browse/term/HP:0012594

@avizrosenberg
@yongqunh  
@beckysteck

Also, is there a PMID for the albuminuria ranges? We will add the moderate/severe terms.

**Comment by LCCarmody** [comment]
fwiw, [this paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5875351/) seems to divide albuminuria into 3 categories: mild, moderate, and severe  and [this paper ](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2658722/) defines microalbuminuria in the same way the paper defines moderate albuminuria.

Based on this, I think it is distinct and is defined roughly as 'an ACR of less than 30 mg/g is normal to mildly increased albuminuria,'

**Comment by pnrobinson** [comment]
@avizrosenberg
@yongqunh  
@beckysteck

It seems that the definition of albuminuria is related to g crea not "per day", 

The three levels of albuminuria include an albumin-creatinine ratio (ACR)

    A1: ACR less than 30 mg/gm (less than 3.4 mg/mmol)
    A2: ACR 30 to 299 mg/gm (3.4 to 34 mg/mmol)
    A3: ACR greater than 300 mg/gm (greater than 34 mg/mmol).

https://pubmed.ncbi.nlm.nih.gov/30571025/

I am adding the three terms with the per g crea definitions -- please reopen this if needed!


https://www.ncbi.nlm.nih.gov/books/NBK535404/
