### ISSUE TITLE
Isosthenuria

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#5533]
missing terms: ,Urine specific gravity comparable to protein-free blood plasma, aproximately 1.01

**Comment by pnrobinson** [comment]
There is a term
https://hpo.jax.org/app/browse/term/HP:0030036
but the definition is different. Can you please check whether the definition is correct?
@avizrosenberg
@yongqunh  
@beckysteck

**Comment by pnrobinson** [comment]
@avizrosenberg
@yongqunh
@beckysteck

Did you get a chance to check this definition? See above. Thanks!

**Comment by yongqunh** [comment]
I checked this Wiki: https://en.wikipedia.org/wiki/Isosthenuria
"Isosthenuria refers to the excretion of urine whose specific gravity (concentration) is neither greater (more concentrated) nor less (more dilute) than that of protein-free plasma, typically 1.008-1.012.[1] Isosthenuria reflects damage to the kidney's tubules or the renal medulla." 

According, probably we can change "aproximately 1.01" to "typically 1.008-1.012"?

**Comment by pnrobinson** [comment]
I do not think the definition in the HPO needs to have these numbers -- especially since it does not seem to be 100% standardized. I think we can keep the term as is.
