### ISSUE TITLE
Urine pH

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#5535]
missing terms: ,Measurement of urine acid base status

**Comment by pnrobinson** [comment]
I added a term.
```
Abnormal urine pH
def: A deviation of urine pH from the normal range of 4.5 to 7.8.
comment:Urine pH typically is 5 as a result of daily net acid excretion. Any urine pH can be normal.
```

Please reopen if this is not what was intended
@avizrosenberg
@yongqunh  
@beckysteck

**Comment by yongqunh** [comment]
I don't quite understand the meaning of "Any urine pH can be normal". You mean Any urine pH during the normal range?

**Comment by pnrobinson** [comment]
urine pH is adjusted by the kidneys to maintain homeostasis. I do not think that there is a urine pH that always would be regarded as a kidney abnormality (as opposed to the kidney doing its job to make up for imbalances elsewhere)

**Comment by yongqunh** [comment]
I see. So it is not kidney abnormality. however, with some unusal urine pH abormality, it might be an indication related to other abnormality (but may not be kidney).

**Comment by pnrobinson** [comment]
For clarity, I have replaced "Any urine pH can be normal" by "The interpretation of the urine pH depends on the medical context."
