### ISSUE TITLE
Revise classification of HP_0000256 Macrocephaly?

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#5541]
MP has MP_0000434 megacephaly with the logical def:
'has part' some 
    ('increased size'
     and ('inheres in' some head)
     and ('has modifier' some abnormal))

This is currently the logical def for HP_0040194 'Increased head circumference'.

I think it may make more sense for this to the be the logical def for HP_0000256 macrocephaly, and I think  HP_0000256 macrocephaly should be a child of 'abnormality of skull size' instead of 'increased head circumference'.

I suggest revising the logical def of HP_0040194 'Increased head circumference' to
'has part' some 
    ('increased circumference'
     and ('inheres in' some head)
     and ('has modifier' some abnormal))

**Comment by nicolevasilevsky** [comment]
It would look like this (in the inferred branch):
![image](https://user-images.githubusercontent.com/6722114/77948247-fb3e6100-7279-11ea-9dad-b72276fc8fda.png)

**Comment by drseb** [comment]
I think the current structure is correct. It was developed together with experts in this field, especially w.r.t. to the textual definitions.

**Comment by nicolevasilevsky** [comment]
Ah, the experts certainly know better than me! :)

**Comment by drseb** [comment]
I don't know that, I just remember having several emails with people from UK or Netherlands and we agreed on this structure. See for example the text-defs. The one for the head-circumference is way more general than the on for Macro/Microcephaly.

**Comment by nicolevasilevsky** [comment]
I'm not sure what the best approach is for the MP and HP equivalences....

@sbello do you have any thoughts?

**Comment by sbello** [comment]
It may be that this is okay, the MP term needs to cover a broader range of head measurements but if in human, increased head size = increased head circumference than this is okay. It maybe that the MP should make the term 'macrocephaly' a narrow synonym to convet that this is increase in head size above a certain threshold. 
However, looking at OLS I see a secondary issue that I hadn't noticed before. The inferred parentage based on PATO makes broad head a child of megacephaly in the MP and makes Dolichocephaly a child of Increased head circumference in the HP (see https://www.ebi.ac.uk/ols/ontologies/hp/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FHP_0040194&viewMode=All&siblings=false ) Neither of us assert this relationship. This may be an issue to bring up at the pheno editors' call.

**Comment by pnrobinson** [comment]
I am not sure now why we have two terms, macrocephaly is defined often as head circumference above normal limits, although it has more of a connotation of an abnormal process. Let's revisit this.

**Comment by drseb** [comment]
Macrocephaly has a more specific definition - we follow the advice of experts here.

**Comment by drseb** [comment]
The related discussion was here: https://github.com/obophenotype/human-phenotype-ontology/issues/497

**Comment by pnrobinson** [comment]
I agree, in human medicine macrocephaly is defined based on circumference. Other possible abnormalities of head/skull size are not included. Closing
