### ISSUE TITLE
Wrong label?

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#5545]
**HPO term**

Tibial pseudoarthrosis

**Bug description**

Should it be Tibial pseudarthrosis ? i.e. without "o" ?

**Comment by pnrobinson** [comment]
Both spellings are OK, see e.g. https://www.sciencedirect.com/topics/medicine-and-dentistry/pseudarthrosis
We should add the without "o" version as a synonym (or maybe the primary label, it may be more common)

**Comment by drseb** [comment]
Ok. Thanks!

**Comment by pnrobinson** [comment]
added the synonym
