### ISSUE TITLE
add synonym to HP_0000224 'Decreased taste sensation'

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#5547]
**HPO term**
HP_0000224 'Decreased taste sensation'

**Synonym to be added**
ageusia

**broad/exact/narrow/plural/abbreviation ?**
Exact

see https://github.com/monarch-initiative/mondo/issues/1373

**Comment by pnrobinson** [comment]
Ageusia is not a synonym, (It means complete loss of taste sensation) ,but this should be a new term.
Here is a good reference
https://www.ncbi.nlm.nih.gov/books/NBK549775/

**Comment by nicolevasilevsky** [comment]
Got it, thanks, Peter! I'll add it as a new term.
