### ISSUE TITLE
review Abn protein metabolism terms

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#5549]
Related to https://github.com/obophenotype/human-phenotype-ontology/issues/4924

We should review the HPO terms and associated diseases (such as in OMIM), to see what they are actually measuring, whether it is truly metabolites or just protein levels.

Here is a list of terms to review:

- [ ] HP_0003649 'Abnormality of glycoside metabolism' 
- [ ] HP_0004342 'Abnormality of galactoside metabolism'
- [ ] HP_0008166 'Decreased beta-galactosidase activity'
- [ ] HP_0000816 'Abnormality of Krebs cycle metabolism'
- [ ] 'Decreased fumarate hydratase activity'
- [ ] 'Decreased methylmalonyl-CoA mutase activity'
- [ ] 'Decreased pyruvate carboxylase activity'
- [ ] 'Abnormality of superoxide metabolism'
- [ ] 'Decreased activity of NADPH oxidase'
- [ ] HP_0003524 'Decreased methionine synthase activity'
- [ ] HP_0003349 'Low cholesterol esterification rate'
- [ ] HP_0003353 'Propionyl-CoA carboxylase deficiency'
- [ ] 'Reduced lysosomal acid lipase activity' -> _I didn't change this term to 'Reduced lysosomal acid lipase activity_ because based on the definition, it seems that the activity is being measured here.

**Comment by pnrobinson** [comment]
Honestly I do not think this is an important distinction-- if you have a reduced amount of an enzyme, you will measure a reduced activity. The HPO has always conflated "equivalent" items to the same term/definition. I am going to close this because I do not think we have identified anything that is actually wrong here!
