### ISSUE TITLE
Look into defining casual relationships between phenotypes

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#5551]
related to https://github.com/obophenotype/human-phenotype-ontology/issues/4924

We would like to related abnormal protein levels (such as children under 'Abnormal enzyme/coenzyme activity' to their activity.

I'm copying over some notes from the other ticket.

@matentzn suggested a causal link. @dosumis said: while activity and levels can vary independently, increased levels will typically increase activity (and as Peter says, measurement of activity is often used as a proxy for measuring amount), so grouping level terms under activity terms might be a useful approximation if we have both. This looks to me similar to the situation with mixed development/morphology phenotype hierarchies - there is a causal link between two phenotypes that holds enough of the time that we want to group in the same hierarchy. GO uses this logic in GO-CAM models - treating regulation of levels of an enzyme as regulation of its activity. It shouldn't be too hard to come up with a GCI clause to add to patterns to support this link. We can add a materialization step to the release pipeline to make these explicit in the release files.

e.g. to infer 'increased AP levels' results_in 'increased AP activity' we could use this GCI (or subClassof axiom) to link patterns for the two terms:

GCI: ('has part' some
'increased amount'
and ('inheres in' some 'protein that capable_of some '%s')
SubClassOf results_in some
('has part' some
('process quality'
and ('inheres in' some '%s')
and ('has modifier' some abnormal)))
vars:
- enzyme_activity
- enzyme_activity

*1 Nico wrote: "GO does not maintain any connection between the activity and the alkaline phosphatase itself." The link is maintained in GO annotation - not the ontology
*2 Might be too specific

@drseb wants to make sure that causality is often not strictly given, and would suggest to use rather "possibly_results_in" than "results_in"

cc @cmungall in case he would like to weigh in. :)

**Comment by matentzn** [comment]
This ticket needs to be dealt with by @dosumis who is working on it.

**Comment by pnrobinson** [comment]
closing but adding to infrastructure project
