### ISSUE TITLE
Review HP_0003110 'Abnormality of urine homeostasis' branch

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#5552]
Per a discussion with @pnrobinson today, he suggested that we should review the 'Abnormality of urine homeostasis' branch.

We should consider adding some grouping classes, like 'Abnormal urine appearance' and make HP_0031967 'Cloudy urine' a child.

HP_0031504 'Foamy urine' could also probably be a child of 'Abnormal urine appearance'.

**Comment by pnrobinson** [comment]
Added a term for macroscopic urinanalysis and reaaranged as above.
