### ISSUE TITLE
HP:0032094, new definition

### ISSUE THREAD

**Issue by GrieseAG** [obophenotype/human-phenotype-ontology#5569]
**HPO term**
Increased circulating surfactant protein level HP:0032094

**Suggested revision of textual definition**
Pulmonary surfactant is a highly surface-active mixture of proteins and lipids that is synthesized and secreted onto the alveoli by type II epithelial cells. The protein part of surfactant constitutes of four types of surfactant proteins (SP), SP-A, SP-B, SP-C and SP-D. SP-A and SP-D are hydrophilic proteins that regulate surfactant metabolism and have immunologic functions. These two proteins are detectable in the bloodstream and an elevated level may reflect idiopathic pulmonary fibrosis (IPF). 

Comment: SP-B and SP-C are hydrophobic molecules, which play a direct role in the organization of the surfactant structure in the interphase and in the stabilization of the lipid layers during the respiratory cycle. But the measure in the blood is not reliable, in this case the measurement in the broncho-alveolar lavage fluid is informative. 

(PMID: 28591049)

**nano attribution** 
 LMU crapp
@mgriese
@katrinknoflach

**Comment by pnrobinson** [comment]
updated the definition
