### ISSUE TITLE
Obstructive lung disease (HP: 0006536) > Reduced FEV1/FVC ratio HP:0030877

### ISSUE THREAD

**Issue by GrieseAG** [obophenotype/human-phenotype-ontology#5570]
**HPO term**
Obstructive lung disease (HP: 0006536)

**Reason for deprecation**
Obstructive lung disease is a more a general term and describes a disease not a single characteristic feature. 

**Suggested replacement or term to consider**
Airflow obstruction is typically assessed by spirometry. Individuals with airflow obstruction have reductions in the forced expiratory volume at 1 s (FEV1) and in the ratio of FEV1 to forced vital capacity (FVC). Can be described by existing HPO terms: **Reduced FEV1/FVC ratio (HP:0030877)**, **Reduced forced expiratory volume in one second (HP:0032342)**, additional features are **Chronic bronchitis (HP:0004469)**, **Emphysema (HP:0002097)**

terms can be linked to disease via OMIM: 606963 (COPD), 613490 (Alpha 1 Antitrypsin deficiency), and to genetic associations (SERPINA1 OMIM:107400, TGFB1 OMIM: 190180)

PubMed: 15175276, 11914989

nano-attribution
LMU crapp, @mgriese, @katrinknoflach

**Comment by pnrobinson** [comment]
Label -- Chronic pulmonary obstruction

**Comment by pnrobinson** [comment]
relabeled.

**Comment by pnrobinson** [comment]
done
