### ISSUE TITLE
 Restrictive ventilatory defect (HP:0002091) > Synonym of Restrictive deficit on pulmonary function testing (HP:0002111)

### ISSUE THREAD

**Issue by GrieseAG** [obophenotype/human-phenotype-ontology#5571]
**HPO term**
 Restrictive ventilatory defect (HP:0002091) 

**Reason for deprecation**
Synonym for each other, Restrictive ventilatory defect seems more like a disease than a phenotypic feature. Better: Combination of both in one term: Restrictive deficit on pulmonary function testing (HP:0002111), with the Parent term: Abnormal spirometry test HP:0032340

**Suggested replacement or term to consider**
Restrictive deficit on pulmonary function testing (HP:0002111)

**combined proposed definition:**
Restrictive ventilatory defect is a condition marked by a reduced total lung capacity (TLC) and a FEV1 (forced expiratory volume in 1 second) and FVC (forced vital capacity) less than 80%. Because of that, the ratio FEV1/FVC is often normal. It is not associated with abnormalities of expiratory airflow or airway resistance. Restrictive lung disease may be caused by alterations in lung parenchyma, such as pulmonary fibrosis (abnormally stiff, non-compliant lungs), or by non-pulmonary deficits, including respiratory muscle weakness, disease of the neuromuscular apparatus, paralysis, and deformity or rigidity of the chest wall.

Comment: In a multivariate analysis, older age, male gender, heavy smoking, low education, and high body mass index were independently associated with having a restrictive ventilatory defect.

PMID: 22430039

Necessary to generate new term: Reduced total lung capacity (TLC)?
Parent term: Abnormal spirometry test HP:0032340

nano-attribution:
LMU crapp, @mgriese, @katrinknoflach

**Comment by pnrobinson** [comment]
I agree with merging.
I will make a new issue for Reduced total lung capacity (TLC)
Parent term: Abnormal spirometry test HP:0032340

**Comment by pnrobinson** [comment]
merged terms.
