### ISSUE TITLE
Deleting: Decreased pulmonary function (HP:0005952)

### ISSUE THREAD

**Issue by GrieseAG** [obophenotype/human-phenotype-ontology#5572]
**HPO term**
Decreased pulmonary function (HP:0005952)

**Reason for deprecation**
seems unnecessary, too unspecific

**Suggested replacement or term to consider**

nano-attribution
LMU crapp, @mgriese, @katrinknoflach

**Comment by mgriese** [comment]
Would keep, as sometimes details are not known; so can select this term.

**Comment by pnrobinson** [comment]
We will keep this one!
