### ISSUE TITLE
HP:0002017 Nausea and vomiting

### ISSUE THREAD

**Issue by paolaroncaglia** [obophenotype/human-phenotype-ontology#5586]
**HP:0002017 Nausea and vomiting**

Hello,

HP:0002017 'Nausea and vomiting' is not defined. 
Among its children are 'Nausea' and 'Vomiting'. 
There may be two issues here:
1) 'Nausea' and 'Vomiting' should be siblings of 'Nausea and vomiting', not children;
2) 'Nausea' is defined as "A sensation of unease in the stomach together with an urge to vomit.", which would be fitting for 'Nausea and vomiting' instead.

This affects EFO too.
Thanks in advance for looking into this!

**Comment by pnrobinson** [comment]
Nausea and vomiting was intended as a grouping term.
We did not model this after the NCIT, but I see that they do it in the same way
https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C3259&viewMode=All&siblings=false

I will look and see if there is a better label for the grouping term....

**Comment by pnrobinson** [comment]
I cannot think of any better label. I have added this definition

Nausea is a commonly encountered symptom that has been defined as an unpleasant painless subjective feeling that one will imminently vomit. Vomiting has been defined as the forceful expulsion of the contents of the stomach, duodenum, or jejunum through the oral cavity. While nausea and vomiting are often thought to exist on a temporal continuum, this is not always the case. There are situations when severe nausea may be present without emesis and less frequently, when emesis may be present without preceding nausea.
