### ISSUE TITLE
Muscular hypotonia

### ISSUE THREAD

**Issue by EZapataAldana** [obophenotype/human-phenotype-ontology#5589]
**HPO term** Muscular Hypotonia HP:0001252

**Reason for deprecation** The term of hypotonia depends on whether it is involving the Central Nervous System or the Peripheral Nervous System. Writing Muscular hypotonia, may not include Neuromuscular Junction or Peripheral Nerve.

**Suggested replacement or term to consider** Peripheral Hypotonia

**Comment by pnrobinson** [comment]
Note the HPO has grouping terms that are not used for primary annotations but instead form the upper nodes of the ontology tree. Also in some cases the type of muscular hypotonia may not be known clinically.

**Comment by pnrobinson** [comment]
see https://github.com/obophenotype/human-phenotype-ontology/issues/5590
