### ISSUE TITLE
Muscular Hyptonia definition

### ISSUE THREAD

**Issue by EZapataAldana** [obophenotype/human-phenotype-ontology#5590]
**HPO term** Muscular Hypotonia

**Suggested revision of textual definition** Muscular hypotonia is an abnormally low muscle tone (the amount of tension or resistance to movement in a muscle) _**due to skeletal muscle, neuromuscular junction, or peripheral nerve affection,**_ often involving reduced muscle strength. Hypotonia is characterized by a diminished resistance to passive stretching.

**Comment by pnrobinson** [comment]
Updated the definition, sorry for the delay.
