### ISSUE TITLE
11p15.4 Microduplication Syndrome Wrongfully classfied

### ISSUE THREAD

**Issue by EZapataAldana** [obophenotype/human-phenotype-ontology#5591]
**HPO term** Muscle Hypotonia

**Bug description**
11p15.4 Microduplication Syndrome is a disorder characterized by intellectual disability, dysmorphic features, and obesity. They do not have muscular involvement, thus It should be classified as Central Hypotonia HP:0011398
[2011. Sofos. A novel familial 11p15.4 microduplication.pdf](https://github.com/obophenotype/human-phenotype-ontology/files/4530317/2011.Sofos.A.novel.familial.11p15.4.microduplication.pdf)

**Comment by pnrobinson** [comment]
The annotations for this disease shown on the HPO website are derived from Orphanet
https://www.orpha.net/consor/cgi-bin/Disease_Search.php?lng=EN&data_id=21107&Disease_Disease_Search_diseaseGroup=11p15-4&Disease_Disease_Search_diseaseType=Pat&Disease(s)/group%20of%20diseases=11p15-4-microduplication-syndrome&title=11p15.4%20microduplication%20syndrome&search=Disease_Search_Simple
Please submit a bug report there!
