### ISSUE TITLE
Format  and rows not match on phenotype_annotation.tab file

### ISSUE THREAD

**Issue by frasator** [obophenotype/human-phenotype-ontology#5595]
The file [phenotype_annotation.tab](http://compbio.charite.de/jenkins/job/hpo.annotations/lastStableBuild/artifact/misc/phenotype_annotation.tab) defines 15 fields on the format line but all rows have 14 fields, seems one column in missing or something.
Just wanted to let you know.

Regards,

**Comment by pnrobinson** [comment]
Please note that the HPO has transitioned to a new annotation format that is described here:
https://hpo.jax.org/app/download/annotation
-- phenotype.hpoa

**Comment by frasator** [comment]
Thanks for the answer.

**Comment by drseb** [comment]
thanks @frasator . We have fixed the formatting issues and it will be available in the next release
