### ISSUE TITLE
Beevor's sign

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#560]
PMID: https://www.ncbi.nlm.nih.gov/pubmed/16015010
Def: Weakness of the inferior portion of the rectus abdominal muscle, which is ascertained clinically as follows. When a patient sits up or raises the head from a recumbent position, the umbilicus is displaced toward the head. This is the result of paralysis of the inferior portion of the rectus abdominal muscle, so that the upper fibres predominate pulling upwards the umbilicus.
Comment: Beevor’s sign is said to be characteristic of a spinal cord lesion at the T10  level, but is also described inter alia in amyotrophic lateral sclerosis and in facioscapulohumeral muscular dystrophy.

Should be a child of "Abdominal wall muscle weakness"

Annotate FSMD: Awerbuch GI, Nigro MA: Beevor’s sign in facioscapulohumeral muscular dystrophy. Arch Neurol 1990; 47: 1208–1209.

**Comment by drseb** [comment]
FSMD is http://www.omim.org/entry/158900

**Comment by pnrobinson** [comment]
Added new HPO term HP_0030664. Still need to annotate FSMD  http://www.omim.org/entry/158900
