### ISSUE TITLE
Morphology as a lay person term

### ISSUE THREAD

**Issue by kshefchek** [obophenotype/human-phenotype-ontology#5600]
I'm uncertain if morphology is a lay person term, for example "Abnormal eye morphology"

**Comment by pnrobinson** [comment]
I do not think that "morphology" in this context would mean anything to a non-ontologist!

**Comment by kshefchek** [comment]
This was my thinking as well, these are the lay terms that end with morphology:

synonym: "Abnormal eye morphology" EXACT layperson []
synonym: "Abnormal gallbladder morphology" EXACT layperson []
synonym: "Abnormal peripheral nervous system morphology" EXACT layperson []
synonym: "Abnormality of abdomen morphology" EXACT layperson []
synonym: "Abnormal feet morphology" EXACT layperson []
synonym: "Abnormality of esophagus morphology" EXACT layperson []
synonym: "Abnormality of lung morphology" EXACT layperson []
synonym: "Abnormal eye morphology" EXACT layperson []
synonym: "Abnormal gallbladder morphology" EXACT layperson []

**Comment by drseb** [comment]
Good catch. Thanks

**Comment by pnrobinson** [comment]
@kshefchek @drseb can we close this issue?

**Comment by pnrobinson** [comment]
I changed morphology to structure in the above LP synonyms
