### ISSUE TITLE
HPOA: wrong symptom in disease (Dravet Syndrome)

### ISSUE THREAD

**Issue by PabloBotas** [obophenotype/human-phenotype-ontology#5601]
**HPO term**
HP:0000992: Cutaneous photosensitivity

**Bug description**
At the HPOA file in https://data.monarchinitiative.org/tsv/disease_associations/, HP:0000992 appears as Dravet syndrome (MONDO:0011794). This was a mistake introduced some time ago and does not appear in either OMIM (https://www.omim.org/phenotypicSeries/PS308350) or Orphanet (https://www.orpha.net/consor/cgi-bin/Disease_HPOTerms.php?lng=EN&data_id=10307&Typ=Pat&diseaseType=Pat&from=rightMenu). Could this be fixed?

**Curiosity section**
How is the data pipeline working in this regard? Is the symptom present in a different source such that it gets included in HPOA? Is the file I pointed to the optimal way to retrieve disease-HPO maps?

**Thank you message:**
Thanks a lot for all the work!! :)

**Comment by pnrobinson** [comment]
We will take a look at this but there is some evidence of association:

Photosensitivity in Dravet Syndrome Is Under-Recognized and Related to Prognosis 
https://pubmed.ncbi.nlm.nih.gov/28042998/

**Comment by pnrobinson** [comment]
Sorry, I mis-read your message -- of course it is not cutaneous photosensitivity. We will forward this to the ORPHA team.

**Comment by pnrobinson** [comment]
This is the correct term
https://hpo.jax.org/app/browse/term/HP:0020216
citation: PMID:28042998

**Comment by kshefchek** [comment]
This looks like a monarch ingest issue, it has been fixed in Orphanet and the HPO annotation file, but has not yet propagated to Monarch, this should be fixed in our next release in a few weeks or so.

**Comment by PabloBotas** [comment]
Thank you @kshefchek  and @pnrobinson!

@pnrobinson, you are suggesting https://hpo.jax.org/app/browse/term/HP:0020216, but in Orphanet I am seeing HP:0001327 and HP:0007207, both of which "is_a" HP:0020216. I don't know how to judge here actually, but according to Orphanet you have those two instead of the more general term. I'll bring this up to some colleagues. What is the reasoning for choosing HP:0020216?

**Comment by pnrobinson** [comment]
@PabloBotas  -- sorry for any confusion, initially I was just trying to figure out what is going on. I think the subterms are correct.

**Comment by kshefchek** [comment]
the issue on our side was that we were pulling from http://compbio.charite.de/jenkins/job/hpo.annotations.current/lastSuccessfulBuild/artifact/misc_2018/phenotype.hpoa, which was outdated and removed, so the information on our site is somewhat old (Nov 2019).  Our May release will include data from http://compbio.charite.de/jenkins/job/hpo.annotations.current/lastSuccessfulBuild/artifact/current/phenotype.hpoa

**Comment by PabloBotas** [comment]
@pnrobinson, ok understood. I was a bit confused :)
@kshefchek: Thanks for the explanation. This will fix similar cases and prevent more from coming up in the future.

**Comment by pnrobinson** [comment]
I have revised the Dravet annotations a bit, thanks for the suggestions!
