### ISSUE TITLE
Typo in HP_0000787 comment

### ISSUE THREAD

**Issue by callahantiff** [obophenotype/human-phenotype-ontology#5604]
**HPO term**
HP_0000787

**Bug description**
Typo found in term comment:

>Urinary stone disease is caused by supersaturation of the urine by stone forming substances including calcium, oxalate, and uric acid. Crystals or foreign bodies can act as a nidus for further stone formation. THe resulting kidney stones (calculi) lead to symptoms if they become impacted in the ureter.

"THe" ➞ "The"

**Comment by pnrobinson** [comment]
Thanks! corrected
