### ISSUE TITLE
Absent specific antibody response

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#5606]
Absent specific antibody response -> Abnormal specific antibody response

Currently, this term is used to annotate a type of SCID (https://omim.org/entry/102700), where there is an absent response. Can you specify what the reason is for the proposed change? Should we make a parent term "Abnormal specific anitibody response"? If so, what would the other children terms be (please open a separate issue for this!)

**Comment by nicolevasilevsky** [comment]
@mh11 I think this question above is for you, thanks!

**Comment by pnrobinson** [comment]
I think that this is a synonym:
https://hpo.jax.org/app/browse/term/HP:0012475
I will add the above as a synonym, and make the 'Absent' term a child.
