### ISSUE TITLE
Dysgammaglobulinemia

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#5607]
**HPO term**
https://hpo.jax.org/app/browse/term/HP:0002961

**Suggested revision of textual definition**

Dysgammaglobulinemia	-> Decreased IgG-subclass in blood 
https://hpo.jax.org/app/browse/term/HP:0032135

**Comment by nicolevasilevsky** [comment]
@pnrobinson I'm unclear what the issue is, should HP:0002961 Dysgammaglobulinemia be a superclass of HP:0032135 Decreased IgG-subclass in blood?

**Comment by pnrobinson** [comment]
Actually, I think the definition is correct. Let's close this and we can reopen if needed!
