### ISSUE TITLE
Secretory IgA deficiency

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#5616]
**HPO term**
https://hpo.jax.org/app/browse/term/HP:0004433

**Suggested revision and reasons**

move as a ‘child’ under Increased immunoglobulin level in other fluids

**Comment by nicolevasilevsky** [comment]
related to https://github.com/obophenotype/human-phenotype-ontology/issues/5180
See doc: https://docs.google.com/document/d/1MWXsdl2h8RzJLjVeUKFqzUsamrWzWcFxg62OsUt92Y0/edit
