### ISSUE TITLE
Term request: flexion contracture of proximal interphalangeal joints of fingers

### ISSUE THREAD

**Issue by Joiedavis** [obophenotype/human-phenotype-ontology#562]
Existing presently is 
1. Contracture of distal interphalangeal joints of fingers 
2. Contracture of proximal interphalangeal joint of 2nd finger (only 2nd finger)

Seems reasonable to have 
Contracture of proximal interphalangeal joints of fingers (to reflect condition of all fingers)

**Comment by pnrobinson** [comment]
Added term Contracture of proximal interphalangeal joints of 2nd-5th fingers (HP_0030675)
