### ISSUE TITLE
pulmo: New Definition for Pulmonary Hemorrhage

### ISSUE THREAD

**Issue by GrieseAG** [obophenotype/human-phenotype-ontology#5621]
**HPO term**
Pulmonary hemorrhage HP:0040223

**Suggested revision of textual definition**
Pulmonary hemorrhage is a bleeding within the lungs. Older children and adults may spit blood or bloody sputum. Neonates, infants and young children usually do not spit up blood. Anemia, pulmonary infiltrates, increasingling bloody return on BAL and the presence of hemosiderin-laden macrophages in broncho-alveolar lavage (BAL) fluid or lung biopsy can diagnose lung bleeding. Alveolar macrophages contain phagocytosed red blood cells and stain positive for hemosiderin, a product of hemoglobin degradation, after about 48-72 hours following pulmonary hemorraghe. Previous or recurrent bleeding can thus be distinguished from fresh events. A differentiation into local or diffuse is of importance. Also differentiate if pulmonary hemorrhage is due to a primary lung disorder or a manifestation of a systemic disease. 

PMID: 16473816

**Comment by pnrobinson** [comment]
done!
