### ISSUE TITLE
pulmo, modification of: DIP, HP:0005942

### ISSUE THREAD

**Issue by GrieseAG** [obophenotype/human-phenotype-ontology#5623]
**HPO term**
Desquamative interstitial pneumonitis HP:0005942

**Suggested revision of textual definition**
Diffuse filling of the distal airsspaces oft he lungs, the alveoli, with macrophages. The DIP pattern is characterized additionally thickended alveolar septa by a sparse inflammatory infiltrate that often includes plasma cells and occasional eosinophils. The alveoli are lined by plump cuboidal pneumocytes. Lymphoid aggregates may be present.
 
Comment:
The name originated from the belief that the dominant histologic feature was desquamation of epithelial cells. However, this is now recognized to be intra-alveolar macrophage accumulation rather than desquamation of epithelial cells as originally thought by Liebow and Carrington. In adults the condition is almost invariable associated with cigarette smoke. However, rare cases occur in nonsmokers, some of whom have had exposure to environmental inhalation exposures including passive exposure to cigarette smoke. In children genetically caused surfactant dysfunction syndromes may have the histological pattern of DIP.

PMID: 16728712, PMID: 25657025,  PMID: 14338290, PMID: 16738196, PMID: 23728865

** Synonym:**
filling of the alveoli with alveolar macrophages

**Parent Term:**
Abnormalities of alveolar macrophages

**associated disease:**
Interstitial pneumonitis desquamative, familial, DIP, OMIM 263000

**Comment by pnrobinson** [comment]
done. The disease annotation already exists.
