### ISSUE TITLE
pulmo, Add Definition, Pulmonary arteriovenous malformation HP:0006548

### ISSUE THREAD

**Issue by GrieseAG** [obophenotype/human-phenotype-ontology#5624]
**HPO term**
Pulmonary arteriovenous malformation HP:0006548

**Suggested revision of textual definition**
Pulmonary arteriovenous malformation, a condition most commonly associated with hereditary hemorrhagic telangiectasia, is an abnormal communication between the pulmonary artery and pulmonary vein without an intervening capillary communication.
HRCT images usually show a coarse spidery appearance of the peripheral vascular markings in the lungs. More specific findings are obtained in the pulmonary angiogram where the normally invisible capillary phase is replaced by irregular vascular channels bridging the peripheral branches of pulmonary arteries and veins.

PMID: 788535,     PMID: 30386957

**synonym:** Pulmonary telangiectasia

> additional associated diseases: Teleangiectasia, Hereditary hemorrhagic type 1 (OMIM:187300), type 5 (615506)
> additional associated genes: GDF2 (605120)

**Comment by pnrobinson** [comment]
added definition, and revised disease associations
