### ISSUE TITLE
access to current builds (phenotype->gene)

### ISSUE THREAD

**Issue by ilmn-blajoie** [obophenotype/human-phenotype-ontology#5631]
Previously we were using the below files:

http://compbio.charite.de/jenkins/job/hpo.annotations.monthly/lastSuccessfulBuild/artifact/annotation/ALL_SOURCES_FREQUENT_FEATURES_diseases_to_genes_to_phenotypes.txt
http://compbio.charite.de/jenkins/job/hpo.annotations.monthly/lastSuccessfulBuild/artifact/annotation/ALL_SOURCES_FREQUENT_FEATURES_genes_to_phenotype.txt
http://compbio.charite.de/jenkins/job/hpo.annotations.monthly/lastSuccessfulBuild/artifact/annotation/ALL_SOURCES_FREQUENT_FEATURES_phenotype_to_genes.txt
    
Now all I see is:
http://compbio.charite.de/jenkins/job/hpo.annotations.current/lastSuccessfulBuild/artifact/current/phenotype.hpoa

Which no longer seems to contain a mapping between hpo/omim/disease -> gene?

Does such a file/resource exist?
Is it still possible to pull in a simple mapping between ID -> gene?

**Comment by blajoie** [comment]
^ Following on main git account

**Comment by pnrobinson** [comment]
Please see here
https://hpo.jax.org/app/download/annotation
we have transitioned to new, simpler file formats for the hpo/omim/disease -> gene information. 
Please join the hpo mailing list to stay abreast of developments like this (low-volume list!)
Please reopen this issue if anything is unclear
