### ISSUE TITLE
Modify: HP:0040168(Focal seizures, afebril)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#5638]
HP:0040168(Focal seizures, afebril)\
Parent: HP:0007359(Focal-onset seizure)\
Suggestion: Delete this term, the assumption is that all seizures are afebrile except those coded as a form of Febrile seizure\
Corrected parent: ()

**Comment by pnrobinson** [comment]
@DLewisSmith

I agree that this term is suboptimal. It is being used for afebrile infantile seizures for diseases such as 
https://omim.org/entry/602066
What would be the best way of encoding these infantile seizures using ILAE2017? Would we just use this term (https://hpo.jax.org/app/browse/term/HP:0007359) or are there other options for infants?

**Comment by DLewisSmith** [comment]
These should just be coded by their seizure types. A number of terms now exist encompassing various forms of seizure whilst febrile and where an individual has these then they should be used. Classical PRRT2 seizures would fall under this now:  Gastroenteritis-related afebrile seizure HP:0032893

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3511925/ amongst others

On 9 May 2020, at 11:47, Peter Robinson <notifications@github.com<mailto:notifications@github.com>> wrote:

⚠ External sender. Take care when opening links or attachments. Do not provide your login details.


@DLewisSmith<https://github.com/DLewisSmith>

I agree that this term is suboptimal. It is being used for afebrile infantile seizures for diseases such as
https://omim.org/entry/602066
What would be the best way of encoding these infantile seizures using ILAE2017? Would we just use this term (https://hpo.jax.org/app/browse/term/HP:0007359) or are there other options for infants?

**Comment by pnrobinson** [comment]
addressed by https://github.com/obophenotype/human-phenotype-ontology/issues/5839
