### ISSUE TITLE
Crohn's disease as large bowel disease

### ISSUE THREAD

**Issue by pontikos** [obophenotype/human-phenotype-ontology#564]
Crohn's disease has been classified as a large bowel disease, under colitis. 

Colitis means inflammation of the colon (i.e. large bowel) which is mainly a terminology for ulcerative colitis.

Crohn's Disease can affect any part of the gastrointestinal tract, from mouth to anus and shouldn't be classified as disease of large bowel. 

It should be classified under 'Gastrointestinal Inflammation'.

The team should consider small bowel disease as a separate entity when looking at GI disease.

**Comment by pnrobinson** [comment]
Thanks for pointing this out, I have changed the inheritance. Crohn's disease is not an ideal term in the HPO since it is a disease rather than a phenotypic feature. Still, it is useful right now because this term is used in so many phenotype databases.
