### ISSUE TITLE
Modify: HP:0025121(Simple partial occipital seizures)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#5644]
HP:0025121(Simple partial occipital seizures)\
Parent: HP:0002349(Focal aware seizure)\
Suggestion: Delete this term, it does not fit within a phenotypic classification, it is an anatomical classification based on semiological assumptions rather than phenotypic observation\
Corrected parent: ()

**Comment by pnrobinson** [comment]
This term (https://hpo.jax.org/app/browse/term/HP:0025121) is used to annotate only one disease, Epilepsy, progressive myoclonic 2B (Lafora) (https://omim.org/entry/254780). As far as I can see, the item comes from this publication:
- https://pubmed.ncbi.nlm.nih.gov/15781812/
The publication does not really give any details, but this one (https://academic.oup.com/brain/article/126/4/753/331918) talks about occipital seizures:
Visual hallucinations are the hallmark of occipital seizures, but are not invariably present. Hallucinations typically commence in the visual field contralateral to the affected visual cortex and then spread to involve the entire visual field.
Also consulting this paper about Lafora disease: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5777303/

I think that Simple partial occipital seizures probably is the same things as:

https://hpo.jax.org/app/browse/term/HP:0011165

@DLewisSmith

Does this sound correct? If so I will merge these two terms (in effect, retire Simple partial occipital seizures)

**Comment by DLewisSmith** [comment]
Seems reasonable but Simple partial occipital seizures should not become a synonym or appear in the entry for any of the new terms. The clinical manifestations used for seizure classification do not hold true to anatomical landmarks at this level of granularity. An additional dimension based on the anatomical onset of seizures would be too imprecise, and in many instances be incorrect. Whilst clinicians do still talk about a frontal/occipital/temporal/etc. lobe seizure, this is based on assumptions, typical features, or additional EEG or imaging findings.





On 9 May 2020, at 11:37, Peter Robinson <notifications@github.com<mailto:notifications@github.com>> wrote:

⚠ External sender. Take care when opening links or attachments. Do not provide your login details.


This term (https://hpo.jax.org/app/browse/term/HP:0025121) is used to annotate only one disease, Epilepsy, progressive myoclonic 2B (Lafora) (https://omim.org/entry/254780). As far as I can see, the item comes from this publication:

  *   https://pubmed.ncbi.nlm.nih.gov/15781812/
The publication does not really give any details, but this one (https://academic.oup.com/brain/article/126/4/753/331918) talks about occipital seizures:
Visual hallucinations are the hallmark of occipital seizures, but are not invariably present. Hallucinations typically commence in the visual field contralateral to the affected visual cortex and then spread to involve the entire visual field.
Also consulting this paper about Lafora disease: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5777303/

I think that Simple partial occipital seizures probably is the same things as:

https://hpo.jax.org/app/browse/term/HP:0011165

@DLewisSmith<https://github.com/DLewisSmith>

Does this sound correct? If so I will merge these two terms (in effect, retire Simple partial occipital seizures)

**Comment by pnrobinson** [comment]
done
