### ISSUE TITLE
issue with: HP_0010031 Patchy sclerosis of the 1st metacarpal

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#568]
These two terms have the same label:
HP_0010031 Patchy sclerosis of the 1st metacarpal
HP_0010072 Patchy sclerosis of the 1st metatarsal

But not the same logical def.

HP_0010031 has the same logical def as HP_0100914 Sclerosis of the 1st metacarpal (which is its parent).

**Comment by cmungall** [comment]
Aren't we spotting these equivs via travis?

**Comment by drseb** [comment]
Yes I am checking and fixing these regularly. This one I think is trivial, as they are not equivalent. Please have a look again at the labels and let me know if you agree at that 

* meta**carpal** &ne; meta**tarsal**

Please re-open if you disagree or this issue isn't solved for you

**Comment by nicolevasilevsky** [comment]
Apologies, I misread the labels, they are different, you are right!

**Comment by nicolevasilevsky** [comment]
I think the logical definition for HP_0010031 Patchy sclerosis of the 1st metacarpal still needs fixing though, it should have 
and ('has modifier' some patchy))

**Comment by pnrobinson** [comment]
agree and changed accordingly
