### ISSUE TITLE
HP_0008165 Decreased proportion circulating T-helper cells update label, change location in HP

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#5689]
**HPO term**

- HP_0008165 Decreased proportion circulating T-helper cells

**Bug description**

1. 'HP_0008165 Decreased proportion circulating T-helper cells' label should be helper T cells and/or synonym should be added.  I assume this is related to CL:0000912 | helper T cell
1.  'HP_0008165 Decreased proportion circulating T-helper cells' location should be revised--posissibly new terms (Abnormal proportion of helper T cells and Increased proportion of helper T cells) should be added.

Currently, it is a grandchild of Lymphopenia and child of HP_0005403 Decrease in T cell count.
However, under Abnormal T cell morphology, there is another branch, HP_0025540 Abnormal T cell subset distribution, which has the majority of these terms are in this branch. Multiple parentage or move the branch? Not sure. This applies to a few cell types. See image below.

<img width="439" alt="Screen Shot 2020-05-11 at 4 15 59 PM" src="https://user-images.githubusercontent.com/26067008/81608584-872cc800-93a4-11ea-940f-b829f704aaba.png">

**Comment by nicolevasilevsky** [comment]
1. I agree
2. What do you mean - the location should be revised? In the text def or logical def or both? The DOSDP pattern will add the location. Do you want to add it to the text def too?

I agree we we should add Abnormal and Increased terms. We can add those via the DOSDPs, yeah?

3. I think we should have multiple parentage.

**Comment by LCCarmody** [comment]
2. Sorry, maybe the DOSDP pattern will alter where in the HP hierarchy they should go...but there are two parts of the HP hierarchy with these types of terms reside. I think it is causing some of the redundant terms because of it. See screenshot above.

**Comment by nicolevasilevsky** [comment]
I think these abnormal proportion of cell terms s should be asserted under HP_0025540 Abnormal T cell subset distribution
