### ISSUE TITLE
"Agnathia" as synonym of mandibular aplasia

### ISSUE THREAD

**Issue by CourtneyHum** [obophenotype/human-phenotype-ontology#569]

**Comment by markengelstad** [comment]
I'm currently making synonyms for head/ neck phenotypes.
I'll add 'Agnathia' ... but it won't be in HPO til the synonyms are evaluated/ approved and a new release is made.

**Comment by CourtneyHum** [comment]
Alright, thanks Mark!

On Fri, Dec 11, 2015 at 1:09 PM, Mark Engelstad <notifications@github.com>
wrote:

> I'm currently making synonyms for head/ neck phenotypes.
> I'll add 'Agnathia' ... but it won't be in HPO til the synonyms are
> evaluated/ approved and a new release is made.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/obophenotype/human-phenotype-ontology/issues/569#issuecomment-164006426>
> .
>



-- 
Courtney Hum, MSc
Genetic Counsellor
Centre for Computational Medicine
The Hospital for Sick Children
T: 416-813-7654 x414028
