### ISSUE TITLE
HP_0020177 | Abnormal proportion of CD8-positive, alpha-beta TEMRA T cells cell type confirmation

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#5690]
**HPO term**

HP_0020177 | Abnormal proportion of CD8-positive, alpha-beta TEMRA T cells | CD8-positive, alpha-beta TEMRA T cells | possible | CL:0001062 | effector memory CD8-positive, alpha-beta T cell, terminally differentiated
-- | -- | -- | -- | -- | --
HP Text def: An abnormal proportion of CD8-positive, alpha-beta effector memory RA TEMRA T cells compared to the total number of T cells in the blood. These cells have the phenotype CD45RA-positive, CD45RO-negative, and CCR7-negative.

**Bug description**

1. Wanted to confirm that the cell type in the label and HP text description was the CL cell type that I think it is.

[CL:0001062](https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0001062) | effector memory CD8-positive, alpha-beta T cell, terminally differentiated
CL text def: A CD8-positive, alpha beta memory T cell with the phenotype CD45RA-positive, CD45RO-negative, and CCR7-negative.

1.  Is this in proportion to T cells?

1. Should there be increased and decreased of this cell type. We only have a term for Abnormal.

#4289

**Comment by nicolevasilevsky** [comment]
1. That looks correct (see https://www.frontiersin.org/articles/10.3389/fimmu.2018.02692/full)
2. Yes, in proportion to T cells (it says that in the HPO def)
3. The article above says "accumulation of Temra cells in humans is influenced by chronic infections, such as CMV" - so yeah, seems like we should add increased and decreased phenotypes. We can do this with DOSDP, yes?

**Comment by LCCarmody** [comment]
I'll add them to the sheet
