### ISSUE TITLE
Abnormal, Increased, Decreased proportion of non-class-switched memory B cells cell type confirmation

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#5691]
**HPO term**

HP_0032126\|HP_0032125\|HP_0032124 | Abnormal, Increased, Decreased proportion of non-class-switched memory B cells
-- | --

**Bug description**

1. I am nearly positive these are the unswitched memory B cells, but I want to make sure.  Preference would be to change the HP label to match CL term and add synonym, but it could be done the other way.

CL:0000970 | unswitched memory B cell
-- | --

#4289

**Comment by nicolevasilevsky** [comment]
Yes, that looks correct,

I'll submit a ticket to CL to add non-class-switched memory B cell as a synonym to unswitched memory B cell.

As you suggested, I agree we should relabel the HPO term to match CL.
