### ISSUE TITLE
HP_0005407	Decreased proportion of CD4-positive T cells cell type confirmation and label change, location change

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#5692]
**HPO term**

HP_0005407 | Decreased proportion of CD4-positive T cells
-- | --
HP Text def: A decreased proportion of circulating CD4-positive helper T cells relative to total T cell count.

**Bug description**

1.  Trying to confirm cell type. Label says 'CD4-positive T cells and text says 'CD4-positive helper T cells'.  I think this matches

CL:0000492 | CD4-positive helper T cell
-- | --

1.  Location should be revised--possibly new terms (Abnormal proportion of CD4-positive helper T cells and Increased proportion of  CD4-positive helper T cells should be added.
Currently, it is a grandchild of Lymphopenia and child of HP_0005403 Decrease in T cell count.
However, under Abnormal T cell morphology, there is another branch, HP_0025540 Abnormal T cell subset distribution, which has the majority of these terms are in this branch. Multiple parentage or move the branch? Not sure. This applies to a few cell types. See image below.
<img width="439" alt="Screen Shot 2020-05-11 at 4 15 59 PM" src="https://user-images.githubusercontent.com/26067008/81610147-06bb9680-93a7-11ea-9c81-860d55db1512.png">

#4289 #5689

**Comment by nicolevasilevsky** [comment]
1. I agree with the CL class. We should relabel the term or add a synonym.
2. I think we should have multiple parentage.
3. I think we should have the same terms for all of these terms - Abnormal, Increased and Decreased.
