### ISSUE TITLE
Cell type confirmation for HP_0005415 and HP_0031393

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#5693]
**HPO term**

HP_0005415 | Decreased proportion of CD8-positive T cells| HP Text Def: A decreased proportion of circulating CD8-positive, alpha-beta T cells relative to total number of T cells.
-- | --
HP_0031393 | Abnormal proportion of CD8 T cells| HP Text Def: Any abnormality in the proportion of CD8 T cells relative to the total number of T cells.

**Bug description**
1. Are these referring to the same cell type?
2. Are these (one or both) referring to 

CL:0000625 | CD8-positive, alpha-beta T cell
-- | --
?
3. If these are the same cells, they are not in a parent child relationship. If they are the same, they need to be moved. If they aren't, it needs to be clearer which cell type each refers to and suggest additional terms (Abnormal, Increased, Decreased) as needed.  

#4289

**Comment by nicolevasilevsky** [comment]
1. I think these are referring to the same cell type.

2. I think the CL term is CL:0000625, as you said.

3. 
- [ ] HP_0005415 Decreased proportion of CD8-positive T cells should be a child of HP_0031393  Abnormal proportion of CD8 T cells
- [ ] we should rename HP_0031393 to Abnormal proportion of CD8-positive T cells

**Comment by LCCarmody** [comment]
I am confused.  The label already uses Abnormal proportion of CD8 T cells, should it be changed Abnormal proportion of CD8-positive, alpha-beta T cells? Or should that be added as a synonym.

**Comment by nicolevasilevsky** [comment]
I think my comment suggested changing it to Abnormal proportion of CD8-**positive** T cells

**Comment by pnrobinson** [comment]
I would suggest we leave  alpha-beta  as default and just show it as a synonym -- otherwise the term names will be extremely long!
