### ISSUE TITLE
Abnormal/Reduced/Increased proportion of CD4 T cells cell type confirmation

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#5694]
**HPO term**

HP_0032219\|HP_0032218\|HP_0031392 | Reduced proportion of CD4 T cells\|Increased proportion of CD4 T cells\|Abnormal proportion of CD4 T cells
-- | --

**Bug description**
There are too many 'CD4-positive' type T cells in CL. I don't know which it is referring to.

#4289

**Comment by pnrobinson** [comment]
I think probably this?
https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000624&viewMode=All&siblings=false

**Comment by nicolevasilevsky** [comment]
I agree
