### ISSUE TITLE
Abnormal/Increased/Decreased proportion of CD4+ central memory cells cell type confirmation

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#5695]
**HPO term**

HP_0025620|HP_0025621|HP_0025622 | Abnormal proportion of CD4+ central memory cells|Elevated proportion of CD4+ central memory cells |Reduced proportion of CD4+ central memory cells
-- | --
HP text def: An abnormal proportion of central memory CD4+ T cells. These are memory cells that are located in the secondary lymphoid organs. These cells may have a CD3/CD4/CD62L+/CD45RA- phenotype.

**Bug description**
1.  IN A DIFFERENT part of HP, there also exists

HP_0410393\|HP_0410388 | Decreased, Increased proportion of central memory CD4-positive, alpha-beta T cells
-- | --

Are these the same as the other HP terms?

2. Are all these the same as this CL term? If so, some terms need to be obsoleted.

CL_0000904 | central memory CD4-positive, alpha-beta T cell
-- | --
CL text def: CD4-positive, alpha-beta memory T cell with the phenotype CCR7-positive, CD127-positive, CD45RA-negative, CD45RO-positive, and CD25-negative.

#4289

**Comment by nicolevasilevsky** [comment]
1. The latter terms (`HP_0410393 Decreased proportion of central memory CD4-positive, alpha-beta T cells` and ` HP_0410388 Increased proportion of central memory CD4-positive, alpha-beta T cells`) have a different set of markers in the def:

These cells have the phenotype of CCR7-positive, CD127-positive, CD45RA-negative, CD45RO-positive, and CD25-negative.

These HPO terms should use the CL term CL_0000904.

I think the former terms are correct too and are duplicates and should  be merged with the HP_0410393 and HP_0410388.

![image](https://user-images.githubusercontent.com/6722114/81615861-35ca0c00-9397-11ea-9618-9b0df66d3743.png)
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4810120/

**Comment by LCCarmody** [comment]
I can add these to the spreadsheet, BUT I don't know how to obsolete in HP. @drseb

**Comment by nicolevasilevsky** [comment]
I regularly obsolete terms in Mondo, and I think it's the same process in HPO. I could give it a try, if that's okay?

**Comment by nicolevasilevsky** [comment]
I can do it on PR

**Comment by LCCarmody** [comment]
Let me merge my current PR.  Could you make sure to add the labels as new synonyms? Thanks.

**Comment by nicolevasilevsky** [comment]
Sounds good - yes, will add the old labels as synonyms. 

I'm in meetings until this afternoon, so I'll work on this when your workday is over :)

**Comment by drseb** [comment]
All annotations should be moved to the new term. Definition needs to be manually handled. Does that work?

Sent from mobile

**Comment by nicolevasilevsky** [comment]
Yes - @LCCarmody and I created a PR
