### ISSUE TITLE
Proportion of CD4+ effector memory cells and effector memory CD4-positive, alpha-beta T cells confirmation and merge

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#5696]
**HPO term**
HP_0025623, HP_0025625, HP_0025624 Abnormal/Elevated/Reduced proportion of CD4+ effector memory cells

AND

HP_0410387, HP_0410382 Abnormal/Decreased proportion of effector memory CD4-positive, alpha-beta T cells
**Bug description**
1.  I think the HP terms are referring to the same thing and should be merged. 
2. Also, these are in different parts of the hierarchy, so should have multiple parentage.
3. I believe all are referring to 

CL_0001044 | effector CD4-positive, alpha-beta T cell
-- | --

At very least, the second set is, but we need confirmation that the first set is referring to this and then the terms could be merged.

#4289

**Comment by nicolevasilevsky** [comment]
I agree @LCCarmody

**Comment by LCCarmody** [comment]
- [ ] Obsolete HP_0410382 and replace/merge with HP_0025623 with Abnormal proportion of CD4+ effector memory cells 
- [ ] Obsolete HP_0410387 and replace/merge with HP_0025624 with proportion of CD4+ effector memory cells

@drseb

**Comment by pnrobinson** [comment]
done
