### ISSUE TITLE
CD25+ Mast cell confirmation, Add terms

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#5697]
**HPO term**

HP_0031408 | Increased proportion of CD25+ mast cells
-- | --

**Bug description**
1.  Not sure what CL term this matches to.  [Mast cell CL_0000097
](https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000097) text definition is "A cell that is found in almost all tissues containing numerous basophilic granules and capable of releasing large amounts of histamine and heparin upon activation. Progenitors leave bone marrow and mature in connective and mucosal tissue. Mature mast cells are found in all tissues, except the bloodstream. Their phenotype is CD117-high, CD123-negative, CD193-positive, CD200R3-positive, and FceRI-high. Stem-cell factor (KIT-ligand; SCF) is the main controlling signal of their survival and development. "  Is this the correct cell? Does there need to be a cell added to CL?
2.  This is the ONLY term like this in HP. Needs Abnormal proportion of CD25+ mast cells (minimally) and possibly 'Decreased' as well.

**Comment by LCCarmody** [comment]
Oh, and what is this in proportion to?  Other Mast cells?

**Comment by nicolevasilevsky** [comment]
the comment in HP says that neoplastic mast cells are CD25+, so I don't think the CL term above is correct. I will request a new child term in CL.

**Comment by nicolevasilevsky** [comment]
@LCCarmody I added this term to CL as CL:0011023

**Comment by LCCarmody** [comment]
I am assuming this is proportional to Mast cells, then?

**Comment by nicolevasilevsky** [comment]
Could we just leave it as proportion to cells? (Without getting as specific as mast cells)

**Comment by pnrobinson** [comment]
I think that the use case for this term is this:
Aberrant expression of CD2 and/or CD25 by bone marrow, peripheral blood or other extracutaneous tissue mast cells is currently used as a minor World Health Organization diagnostic criterion for systemic mastocytosis.  CD25 expression alone presented a similar sensitivity (100%) with a slightly higher specificity (99.2%).

https://www.nature.com/articles/modpathol2011192

See also
https://pubmed.ncbi.nlm.nih.gov/26525770/

There would be no "reduced proportion" term for this. 

I will work on providing a better definition!

**Comment by pnrobinson** [comment]
done
