### ISSUE TITLE
Increased proportion of HLA DR+ T cells cell confirmation, Add terms

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#5698]
**HPO term**

HP_0002853 | Increased proportion of HLA DR+ T cells
-- | --

**Suggested revision of textual definition**
1.  There isn't a CL term close to this one.  There is only reference to HLA DRA gene. This may require a new term in CL?

2.  Needs an 'Abnormal' term and possibly a 'Decreased' term?

#4289

**Comment by LCCarmody** [comment]
Also, what cell type is this in proportion to? T cell?

**Comment by nicolevasilevsky** [comment]
For proportion, the logical defs will just be in proportion to cells, so I think the text defs should be the same.

**Comment by nicolevasilevsky** [comment]
I am not sure if CL would want to add just HLA DR+ T cell. I wonder if we could add a logical def that is something like:

'has_part' some 
('proportionality to' 
and ('inheres_in' some (T cell and ('has plasma membrane part' some 'HLA-DRA (human)') and ('part_of' some blood))) and ('towards' some 'cell') and ('has_modifier' some 'abnormal'))

**Comment by nicolevasilevsky** [comment]
Maybe we could do this for https://github.com/obophenotype/human-phenotype-ontology/issues/5701 too (with CD3)

**Comment by matentzn** [comment]
It is in theory possible; but quite specific.. How many of these terms are there, and what do you think CL would not create these terms?

**Comment by LCCarmody** [comment]
Quick google search shows Human CD8+HLA-DR+ Regulatory T Cells, CD3+ CD4+ HLA-DR+ responder T cells (no idea what 'responder T cells' are),  CD38+HLA-DR+CD8+ T cells, HLA-DR+ CD38+ (DR+ 38+) CD4+ T.  Definitely don't know what the differences are. Some of these may be synonyms with cells already in CL, since HLA-DR is supposed to be the important marker for T cell activation. CL does have terms like activated 'CD8-positive, alpha-beta T cell
^ http://purl.obolibrary.org/obo/CL_0000906'.  So maybe we request synonyms?

**Comment by pnrobinson** [comment]
done
