### ISSUE TITLE
Increased proportion of exhausted T cells cell confirmation, Add terms

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#5699]
**HPO term**

HP_0031514 | Increased proportion of exhausted T cells
-- | --

**Suggested revision of textual definition**
1. There isn't a term for 'exhausted T cells' in CL.  Should this be added to CL?

2. Add 'Abnormal' and possibly 'Decreased' exhausted T cells.
#4289

**Comment by nicolevasilevsky** [comment]
These seem like a proper subset of T cells, I'll submit a ticket to CL

**Comment by pnrobinson** [comment]
There is no "reduced" exhausted T cells.
DEf: T cell exhaustion is a state of T cell dysfunction that arises during many chronic infections and cancer. It is defined by poor effector function, sustained expression of inhibitory receptors and a transcriptional state distinct from that of functional effector or memory T cells. PMID:
    21739672

**Comment by nicolevasilevsky** [comment]
I added this to CL as CL:0011025. For some reason I don't see it in the latest release though. I emailed the CL list.

**Comment by LCCarmody** [comment]
It's there when I open the owl file. Just use the CL:0011025 in the spreadsheet. I think it will work out

**Comment by nicolevasilevsky** [comment]
oh it is?! That's good. I don't see it for some reason. Ok, will do, I'll add it to the spreadsheet. I am going to try to work on adding the terms now (on a branch, just as a test.)

**Comment by LCCarmody** [comment]
Did you pull on the master?  I went straight to the owl file in your release, so I know it is there.

**Comment by nicolevasilevsky** [comment]
Nico said maybe it was a caching error, he said he sees it too

**Comment by pnrobinson** [comment]
done
