### ISSUE TITLE
Proportion of double-negative alpha-beta regulatory T cell  cell confirmation, merge terms, multiple parentage

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#5700]
**HPO term**

HP_0031399,HP_0002851,HP_0031401 | Abnormal,Elevated,Reduced proportion of double-negative alpha-beta regulatory T cell 
-- | --

HP_0031401,HP_0031399,HP_0002851 | Abnromal, Elevated, Reduced proportion of CD4-negative, CD8-negative, alpha-beta regulatory T cells
-- | --

**Suggested revision and reasons**
1. I am nearly positive these are referring to the same cell type, so these should be merged.
2. There is no match for this cell type in CL. Add a term to CL?
3.  I think the reason that there are duplicates is because they are in different branches of HP, so this requires multiple parentage.
#4289

**Comment by nicolevasilevsky** [comment]
1. I agree
2. I'll make a term request to CL
3. I agree

**Comment by pnrobinson** [comment]
terms added
