### ISSUE TITLE
proportion of CD3-positive T cells cell confirmation, Add term

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#5701]
**HPO term**

HP_0045080 | Decreased proportion of CD3-positive T cells
-- | --

**Suggested revision of textual definition**
1. This term does not exist in CL. Add term to CL?
2. Add 'Abnormal' and 'Decreased' terms as necessary.
#4289

**Comment by nicolevasilevsky** [comment]
I'll create a ticket for CL

**Comment by addiehl** [comment]
All mature T cells are CD3-positive.  A better HP term would simply be Decreased proportion of T cells.  The CD3 is redundant, and simply indicative of the use of CD3 as a general marker for mature T cells.

Alex

**Comment by nicolevasilevsky** [comment]
Thanks Alex, this is helpful! Or could we rename this to Decreased proportion of mature T cells? And we could note in the comment that CD3 is a general marker for mature T cells.

And we could use the CL term CL_0002419 'mature T cell'.

(I just noticed that CD3epsilon T cell is a synonym for mature T cell in CL.)

**Comment by pnrobinson** [comment]
I think this term is designed for situations like this:
https://ashpublications.org/blood/article/112/11/5311/62960/CD3-Negative-CD4-T-Cells-A-Useful-Diagnostic-Tool

**Comment by addiehl** [comment]
While CL might represent CD3-negative CD4-positive T cell, it seems like it is a abnormal neoplastic cell type and would not be appropriate in the standard T cell hierarchy in CL, but perhaps under 'neoplastic cell'.

**Comment by pnrobinson** [comment]
done!
