### ISSUE TITLE
Proportion of effector memory CD8-positive, alpha-beta T cells terms are in different parts of HP

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#5702]
**HPO term**

HP_0410383 | Abnormal proportion of effector memory CD8-positive, alpha-beta T cells
-- | --

HP_0410395| Increased proportion of effector memory CD8-positive, alpha-beta T cells
-- | --

HP_0410390 | Decreased proportion of effector memory CD8-positive, alpha-beta T cells
-- | --

**Suggested revision and reasons**
1. These are all in separate parts of the HP.  Abnormal term should be parent to Increased and Decreased terms.
2.  This CL term is an exact match

CL_0000913 | effector memory CD8-positive, alpha-beta T cell
-- | --

3.  May be able to put this in the DOSDP patterns directly (note, I haven't done this yet).  I think just moving this to the DOSDP patterns should take care of this parentage issue?

#4289

**Comment by pnrobinson** [comment]
I think that parentages are wrong, we should rearrange!

**Comment by LCCarmody** [comment]
@nicolevasilevsky @matentzn I think this should be fixed by putting this in the DOSDP pattern, but I am not sure.

**Comment by nicolevasilevsky** [comment]
I think thee DOSDP pattern will fix the classification.

**Comment by LCCarmody** [comment]
Added to the spreadsheet and closing this ticket

**Comment by LCCarmody** [comment]
Somehow this ticket never got closed. All has been implemented.
