### ISSUE TITLE
proportion of central memory CD8-positive, alpha-beta T cells terms in different part of the hierarchy

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#5703]
**HPO term**

HP_0410384 | Abnormal proportion of central memory CD8-positive, alpha-beta T cells
-- | --

HP_0410389 | Decreased proportion of central memory CD8-positive, alpha-beta T cells
-- | --

**Suggested revision and reasons**
1. Does there need to be an 'Increased' term?

2. These 2 terms are in separate parts of the hierarchy.  Possibly adding this to the DOSDP patterns will fix this issue?
3.  Think this 

CL_0000907 | central memory CD8-positive, alpha-beta T cell
-- | --

#4289

**Comment by nicolevasilevsky** [comment]
1. I think it would make sense to have increased
2. I think the DOSDP will give the correct classification
3. I agree with the CL term.
