### ISSUE TITLE
proportion naïve CD4 T cells cell confrimation

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#5704]
**HPO term**

HP_0410378,HP_0410373,HP_0410375 | Abnormal, reduced, elevated proportion naïve CD4 T cells
-- | --

**Suggested revision of textual definition**

1. Unknown cell type.  Closest in CL is below, but I don't think it is a match.

CL:0000895 | naive thymus-derived CD4-positive, alpha-beta T cell
-- | --
#4289

**Comment by pnrobinson** [comment]
What is the issue with this CL term? It seems pretty good?

**Comment by LCCarmody** [comment]
Is it correct?  There was too little information in the HP term, I wasn't sure. If it is correct, then I will add it.

**Comment by nicolevasilevsky** [comment]
it has the broad synonym naive CD4 T cell

I think it is okay to use this CL term

**Comment by LCCarmody** [comment]
Should we change the HP label or just add this cell type as synonym in HP ?
I.e., Abnormal proportion of naive thymus-derived CD4-positive, alpha-beta T cells

**Comment by nicolevasilevsky** [comment]
I think it should be a synonym.

**Comment by nicolevasilevsky** [comment]
I can add the synonym now

**Comment by nicolevasilevsky** [comment]
@LCCarmody I added these to the respective spreadsheets - we are all set on this one
