### ISSUE TITLE
proportion of naive CD8 T cells cell confirmation, need new term

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#5705]
**HPO term**

HP_0410377,HP_0410376 | Reduced proportion of naive CD8 T cells,Elevated proportion of naive CD8 T cells
-- | --

**Suggested revision of textual definition**

1. Need new 'Abnormal' term, these are in different parts of the HP hierarchy

2. This cell type doesn't match any in CL. Need new term? This is the closest, but I don't think it is correct.

CL:0000900 | naive thymus-derived CD8-positive, alpha-beta T cell
-- | --

#4389

**Comment by pnrobinson** [comment]
It looks like the hierarchy is mixing CD4 and CD8 positive cells. We should probably just separate. I do not think we need a parent term for general naive cell?

**Comment by nicolevasilevsky** [comment]
I think that CL term is okay, naive CD8+ T cell is a broad syn

**Comment by LCCarmody** [comment]
Same question as #5704

Should we change the HP label or just add this cell type as synonym in HP ?
I.e., Abnormal proportion of naive thymus-derived CD8-positive, alpha-beta T cells

**Comment by nicolevasilevsky** [comment]
synonym! :)

**Comment by pnrobinson** [comment]
done
