### ISSUE TITLE
New term "rubral tremor"

### ISSUE THREAD

**Issue by CourtneyHum** [obophenotype/human-phenotype-ontology#573]
As a sub-class of tremor... rubral tremor is a slow coarse tremor at rest that is exacerbated by postural adjustments and by guided voluntary movements

http://www.ncbi.nlm.nih.gov/pubmed/6568936

**Comment by pnrobinson** [comment]
Def: Rubral tremor is characterized by a slow coarse tremor at rest that is exacerbated by postural adjustments and by guided voluntary movements. (ref pmid:6568936)
Check is this the same as Holme's tremor?

**Comment by CourtneyHum** [comment]
Yes, you're right. I believe now that it is the same as Holmes' tremor

(ref: UpToDate "overview of tremor") 
Rubral tremor — Rubral tremor, sometimes called Holmes tremor, occurs with midbrain injury and is probably due to combined lesions of the superior cerebellar peduncle, substantia nigra, and red nucleus that interrupt the outflow pathway from the cerebellum to the motor thalamus. This tremor is present at rest but tends to have a slower frequency (3 to 5 Hz) than typical Parkinson tremor (5 to 7 Hz). It also persists unchanged or increases with postural changes or goal-directed activity. It may produce a combination of rest, postural, action, and intention (kinetic) tremors.

UpToDate organizes tremor like this:

Resting tremor
-Parkinson disease
-Parkinsonian syndromes
-Midbrain (rubral) tremor
-Wilson disease
-Severe essential tremor

Postural-action tremor
-Enhanced physiologic tremor
-Essential tremor
-Primary writing tremor
-Other extrapyramidal disorders
--Parkinson disease
--Wilson disease
--Dystonia
-Cerebellar disease
-Peripheral neuropathy

Intention tremor (cerebellar outflow)
-Cerebellar disease
-Multiple sclerosis
-Midbrain stroke
-Midbrain trauma

**Comment by pnrobinson** [comment]
I think that essential tremor and writing tremor are actually disease entities rather than phenotypic features. I have added a term for rubral tremor for now. We need to come back to this topic later on, it would be good to have a few neuro workshops.
