### ISSUE TITLE
synonym migration - do you agree?

### ISSUE THREAD

**Issue by markengelstad** [obophenotype/human-phenotype-ontology#577]
Based on an email string, we decided that if we found a class with an inappropriate synonym, the synonym should not be obsoleted or deleted but, instead, it should be preserved and migrated to the correct class instead. 

Just to make sure everyone agrees, one use case of this is the class "High palate", which currently has the synonym "High arched palate".   
However, "High arched palate" would be a more appropriate synonym for the class "High narrow palate".  
So, I will migrate the synonym "High arched palate" from the "High palate" class to the "High Narrow Palate" class.

Does everyone agree w/ this logic/ application of best practice?

**Comment by nicolevasilevsky** [comment]
Sounds okay to me.

**Comment by drseb** [comment]
moving synonyms around is totally ok!

**Comment by drseb** [comment]
Please close issues with your commits. Can we discuss this on the next call?

**Comment by markengelstad** [comment]
OK, its just that this will be part of a large commit, based on the spreadsheet based lay synonyms that we're working on -- outside of protege. So the issue will remain open for quite a while in that case.

**Comment by drseb** [comment]
Who is going to enter those edits into Protege then?

**Comment by markengelstad** [comment]
tudor G, via a script. 

but only after verification by the group.

**Comment by mellybelly** [comment]
We will review all the synonyms at the Feb meeting and get everyone's thoughts before they go in. We also need to discuss if we want to license them in any way.

**Comment by drseb** [comment]
Ok. Reviewing in Feb is fine. How many edits are there? I would like to see the script before being applied. (not sure why tudor is the one developing this!?)

Also, the edits collected now may be out of date or invalid before being added, because HPO is edited all the time and the edits might overlap...

**Comment by nicolevasilevsky** [comment]
I thought @cmungall was going to try to script them in.

Yes, good point @drseb. Not sure how we should address that?

**Comment by markengelstad** [comment]
I guess its not right to say tudor is developing this.
its more accurate to say tudor wrote a script that exported a csv file with classes and their synonyms so that we could work on them outside of protege, with the main goal being speed. 
He probably would have no role other than that.  I'm not sure.

**Comment by markengelstad** [comment]
to minimize chance of overlap, i'm not making any changes other than the addition of synonyms.   If synonyms are to be moved to another class, for instance, then that is a new github issue/ request. 
I'm also watching issue tracker to make sure no changes are made/ requested that would affect the addition of synonyms in the classes i'm working on (head and neck). 
I agree that the longer we work outside of protege on this, the higher the probability of overlap.

**Comment by drseb** [comment]
Ok perfect. Everything sounds fine! Just wanted to collect all the information. Thanks

**Comment by nicolevasilevsky** [comment]
Yes, true @markengelstad, I don't think we should have too many problems with overlap.

**Comment by nicolevasilevsky** [comment]
@drseb speaking of the next call, we don't have any future calls scheduled. Maybe you could try to schedule one?

**Comment by mellybelly** [comment]
seems fairly trivial to check for overlap. Seb - I think you and Chris can decide on the script together. I am hoping that we can finish this effort before our meeting so that we can move on to annotation!  Also need to decide if these go into a separate file or not, if we want different licensing.

**Comment by pnrobinson** [comment]
I have corrected the synonyms for narrow, highly arched palate, thanks for picking this up! Now will close this thread.
