### ISSUE TITLE
Prostate neoplasm subclass of neoplasms

### ISSUE THREAD

**Issue by c-schroeder** [obophenotype/human-phenotype-ontology#5785]
Prostate neoplasm - HP:0100787

Hi,

we tried to extract all children of neoplasm and were unable to find prostate neoplasm (HP:0100787) and prostate cancer in our results. It seems that prostate neoplasm is only related to abnormal prostate morphology. We think prostate neoplasm should also be linked to neoplasm by anatomical site.

Thanks.

Best regards,
Christopher

**Comment by pnrobinson** [comment]
Thanks for pointing out this omission. We have added a corresponding link that should be visible in the June release of HPO.
