### ISSUE TITLE
COVID 19 illness level terms in NIH treatment guidance

### ISSUE THREAD

**Issue by linikujp** [obophenotype/human-phenotype-ontology#5787]
Hi didn't find below terms in HPO:

[NIH COVID-19 treatment guidelines](https://www.covid19treatmentguidelines.nih.gov/overview/management-of-covid-19/) defined following illness categories:

- Asymptomatic or Presymptomatic Infection: Individuals who test positive for SARS-CoV-2 but have no symptoms

- Mild Illness: Individuals who have any of various signs and symptoms (e.g., fever, cough, sore throat, malaise, headache, muscle pain) without shortness of breath, dyspnea, or abnormal imaging

- Moderate Illness: Individuals who have evidence of lower respiratory disease by clinical assessment or imaging and a saturation of oxygen (SpO2) >93% on room air at sea level.

- Severe Illness: Individuals who have respiratory frequency >30 breaths per minute, SpO2 ≤93% on room air at sea level, ratio of arterial partial pressure of oxygen to fraction of inspired oxygen (PaO2/FiO2) <300, or lung infiltrates >50%

- Critical Illness: Individuals who have respiratory failure, septic shock, and/or multiple organ dysfunction

Please consider to add.

**Comment by pnrobinson** [comment]
These are not phenotypic features, these are disease (stages). @cmungall @nicolevasilevsky should these be Mondo terms?

**Comment by linikujp** [comment]
Is the Asymptomatic or Presymptomatic Infection a phenotypic feature? 
HPO has HP:0008247, Asymptomatic hyperthyroxinemia
and HP:0008162, Asymptomatic hyperammonemia

**Comment by nicolevasilevsky** [comment]
Thanks @pnrobinson, I added a ticket in Mondo.

@cmungall let me know if you have any concerns about adding these terms in Mondo.

**Comment by nicolevasilevsky** [comment]
@linikujp I added these terms to Mondo and they will be available in the next release (which will be at the end of this month/early next month).

I think this can be closed.

**Comment by linikujp** [comment]
Super! Thanks!
