### ISSUE TITLE
Test OLD way to do obsoletions

### ISSUE THREAD

**Issue by matentzn** [obophenotype/human-phenotype-ontology#5789]
@nicolevasilevsky found a way to obsolete terms which I never new existed. I just tried it out, and it seems to work will. @drseb can you check this:

```
cd src/ontology
sh run.sh owltools hp-edit.owl --obsolete-replace HP:0011112 HP:0030354 -o -f ofn hp-edit.owl
```

The command results in this diff:

https://github.com/obophenotype/human-phenotype-ontology/pull/5788/files

Let us know if that workflow works? @nicolevasilevsky can, if it does, add it to the Wiki as the new preferred workflow.

**Comment by matentzn** [comment]
@drseb please close (not merge) the pull request when you have inspected the diff.

**Comment by drseb** [comment]
Is the method documented somewhere? I am not sure all alt_ids are moved to the surviving class? Is it clear by the method call which class will survive? What about the text-definition if both classes have a text-def? Same for XP? Sorry for all these question, but I have seen so many merges gone wrong.

**Comment by matentzn** [comment]
We just discovered it - I guess we need to try. I don’t know of any documentation, but it seems to be used by mondo! Do you want to play with it maybe? It’s more that we saw this and thought you might like it!

**Comment by nicolevasilevsky** [comment]
This is documented in Mondo here: https://mondo.readthedocs.io/en/latest/editors-guide/merging-and-obsoleting/

**Comment by drseb** [comment]
Can I ask you for a favor to create a new branch and in that branch call the following commands?
`sh run.sh owltools hp-edit.owl --obsolete-replace HP:0003141 HP:0003259 -o -f ofn hp-edit.owl
`

and afterwards in a separate commit

`sh run.sh owltools hp-edit.owl --obsolete-replace HP:0003259 HP:0003141 -o -f ofn hp-edit.owl
`

**Comment by drseb** [comment]
or can I run owltools here locally as well?

**Comment by drseb** [comment]
sorry... a bit confused now

**Comment by matentzn** [comment]
Of course, you can run it locally! Why, is there a problem? Just do it on your own branch!

**Comment by drseb** [comment]
Well, in the olden days you had to find the right owltools jar somewhere, add it to your path, and hope for the best...

**Comment by matentzn** [comment]
ODK has owltools, so when you run `sh run.sh` it will find owltools in the ODK itself...

**Comment by drseb** [comment]
cool. didn't know that

**Comment by drseb** [comment]
Ok, here is my feedback. I think we should go this route but there are three things that need to be fixed or clearly documented before we make this an SOP in HPO. @matentzn I assume we do not want to work on the code, right? owltools is not under active development, right?

**Comment by drseb** [comment]
for my own record:

- make clear which class is obsoleted, and which one wins
- id tag is duplicated, so needs to be moved to alt_id
- one text-def is removed
- one eq has to go because they are duplicated

I will explain more on this later @nicolevasilevsky & nico

**Comment by drseb** [comment]
@balhoff I saw you are working on owltools. Is there active development on the core happening? Do you know if the version [you are working on](https://github.com/owlcollab/owltools) is the version of owltools that is pulled into odk? I would be interested in working on the `--obsolete-replace` command for HP.

**Comment by balhoff** [comment]
@drseb I am pretty much just contributing emergency maintenance to owltools. ODK does pull from the releases on GitHub now; currently it's using tag `2020-04-06`.

If you want to add some features, I'll be happy to make a release when you're done.

**Comment by LCCarmody** [comment]
So, is this the method we use? Should it be used for other ODK ontologies?

**Comment by nicolevasilevsky** [comment]
I use it for Mondo

**Comment by LCCarmody** [comment]
It didn't work for MAXO, but it is not critical. If this the preferred method for HPO, I will add it to the wiki.

**Comment by nicolevasilevsky** [comment]
@LCCarmody I wonder why it didn't work for MAxO? The first time I tried it for HPO, it didn't work either, and then @matentzn helped me figure it out and make it work. Maybe I could help you troubleshoot?

**Comment by LCCarmody** [comment]
I have don't have obsolete.owl file...at least not in the right place.  I could tool around, but I don't feel confident enough trying to alter it.  It may be because @matentzn set up an obsoletion path from a tsv file.  This is soooo not urgent. I put it on MAXO tracker, but this could wait a long time (for MAXO), but it would be nice if this were the method for HPO

**Comment by nicolevasilevsky** [comment]
Ah, I see.

I agree - it would be nice to use this method for HPO

**Comment by drseb** [comment]
You may use it for HPO, but see my previous comment - in its current implementation, there is still manual work to do!

**Comment by pnrobinson** [comment]
Trying to get to tracker zero in 2021! Is this issue closable?

**Comment by pnrobinson** [comment]
@drseb @matentzn  see above

**Comment by matentzn** [comment]
I think some tickets could stay open for the next push - the Moment we have some actual money to work on infrastructure. On the other hand I applaud your tracker zero. So maybe we can do this: make a project board and close the issues which we consider icebox, but add them on the project board so Sebastian and I can find them easily when the time comes. Tracker zero is actually something super awesome as a goal for all Monarch projects. Do you agree with that? Project board plus close issues to manage the icebox/backlog.

**Comment by drseb** [comment]
Sounds good

**Comment by pnrobinson** [comment]
adding to project board and closing here.
