### ISSUE TITLE
Typos in HP definitions

### ISSUE THREAD

**Issue by slaulederkind** [obophenotype/human-phenotype-ontology#5790]
Ochronosis (HP:0030764) – definition - "...skin tha can...": change to "...skin 'that' can..."
Skeletal dysplasia (HP:0002652) - definition – "...presence of a congenital defects..." (4th line red text): delete ‘a’ before "congenital defects..."
Ataxia (HP:0001251) – definition - "under-oder overshoot..." (line 5): change to "undershoot or overshoot in grasping movements"
Abnormality of the stomach (HP:0002577) - definition (red text): "the stomach the hollow": change to "the stomach is the hollow"
Increased hepatocellular lipid droplets (HP:0006565) – definition – (red text): ‘...cellular ipid storage...’ change to '...cellular lipid storage...'

**Comment by drseb** [comment]
Thanks!!! We will repair asap

**Comment by pnrobinson** [comment]
fixed! Thanks again
