### ISSUE TITLE
Abnormality monocyte morphology

### ISSUE THREAD

**Issue by slaulederkind** [obophenotype/human-phenotype-ontology#5794]
Abnormality monocyte morphology (HP:0012144) should be "Abnormal monocyte morphology" based on its siblings: 
Abnormal granulocyte morphology (HP:0001911)
Abnormal macrophage morphology (HP:0004311)
and its parent: 
Abnormal myeloid leukocyte morphology (HP:0010974)

**Comment by pnrobinson** [comment]
thanks for pointing this out - corrected!
