### ISSUE TITLE
Add definition, HP:0030873

### ISSUE THREAD

**Issue by GrieseAG** [obophenotype/human-phenotype-ontology#5795]
**HPO term**
Anticentromere antibody positivity HP:0030873

**Suggested revision of textual definition**
Add Comment: Anti-centromere antibodies are typically associated with pulmonary arterial hypertension and the limited cutaneous form of systemic sclerosis.

	PMID: 31858335
	DOI: 10.1007/s10067-019-04806-9

@mgriese, @katrinknoflach

**Comment by pnrobinson** [comment]
done
