### ISSUE TITLE
Add comment+synonym, HP: 0030859

### ISSUE THREAD

**Issue by GrieseAG** [obophenotype/human-phenotype-ontology#5796]
**HPO term**
Topoisomerase I antibody positivity HP:0030859

**Synonym**
Anti-Scl-70-AK

**Suggested revision of textual definition**
Add comment: Anti-topoisomerase I antibodies are classically associated with interstitial lung disease (ILD) and the diffuse cutaneous form of systemic sclerosis.

PMID: 31858335
 DOI: 10.1007/s10067-019-04806-9

@mgriese, @katrinknoflach

**Comment by pnrobinson** [comment]
added comment.
