### ISSUE TITLE
Add comment: Anti-mitochondrial M2 antibody positivity HP:0031907

### ISSUE THREAD

**Issue by GrieseAG** [obophenotype/human-phenotype-ontology#5800]
**HPO term**
Anti-mitochondrial M2 antibody positivity HP:0031907

**Suggested revision of textual definition**
Comment: Anti-mitochondrial antibody (AMA) can be tested via indirect immunofluorescence. AMAs are biomarkers of primary biliary cirrhosis (PBC) and can also be found in patients with idiopathic inflammatory myopathies.

The auto-antigens of AMA have been identified as pyruvate dehydrogenase complex-E2 (PDC-E2), branched-chain 2-oxo acid dehydrogenase complex and 2-oxoglutaric acid dehydrogenase complex. The antibody to these antigens is known as AMA-M2. AMA-M2 is more specific to PBC than AMA, and the determination of its titer is feasible 

PMID: 30579751
DOI: 10.1016/j.nmd.2018.11.004

**Diseases characterized by this term ? (e.g. Orphanet or OMIM number)**
ORPHA:186   (Disorder)   Primary biliary cholangitis
ORPHA:779   (Disorder)   Reynolds syndrome

**nano attribution**
lmu: chrapp, @katrinknoflach, @mgriese

**Comment by pnrobinson** [comment]
done
