### ISSUE TITLE
Modification, pulmo: Hypersensitivity pneumonitis HP:0006516

### ISSUE THREAD

**Issue by GrieseAG** [obophenotype/human-phenotype-ontology#5806]
**HPO term**
Hypersensitivity pneumonitis HP:0006516

**Synonym to be added**
exogen allergic alveolitis, extrinsic  allergic alveolitis

**broad/exact/narrow/plural/abbreviation ?**
EAA

**definition:**
Hypersensitivity pneumonitis involves inhalation of an antigen. This leads to an exaggerated immune response and a following inflammation of the alveoli within the lungs.  The main feature of chronic hypersensitivity pneumonitis on lung biopsies is expansion of the interstitium by lymphocytes accompanied by an occasional multinucleated giant cell or loose granuloma. After exposure to the provoking antigen, following symptoms can be seen: fever, chills, malaise, cough, hemoptysis, chest tightness, dyspnea, rash, swelling and headache and can be completely reversible, based on the duration of the illness, categorized as acute (HP:0011009), subacute (HP:0011011), and chronic (HP:0011010).

Comment: Hypersensitivity pneumonitis may also be called many different names, based on the provoking antigen
PMID 16635083, PMID 15316440, PMID 18051218

**nano contribution**
lmu: chrapp, @katrinknoflach, @mgriese

**Comment by mgriese** [comment]
definition:
Hypersensitivity pneumonitis involves inhalation of an organic antigen. This leads to an exaggerated immune response with inflammation of the alveoli, i.e. alveolitis or pneumonitis. Histopathology of lung biopsies shows a lymphocytic infiltrate of the interstitium, occasional multinucleated giant cells or loose (non-caseating) granuloma. 4-12 h after exposure to the provoking antigen fever, chills, malaise, cough, hemoptysis, chest tightness, dyspnea, rash, swelling and headache can occur. With removal of the antigen this is reversible, with continous expose lung fibrosis occurs. Acute (HP:0011009), subacute (HP:0011011), and chronic (HP:0011010) Hypersensitivity pneumonits may be differentiated. PMID: 23924322, PMID: 27836954.

Comment: Hypersensitivity pneumonitis is the general term. Based on the provoking antigen many different specifying terms are used. PMID 16635083, PMID 15316440, PMID 18051218. Grouped according to the source of antigen, exampels are:
Bacteria: Thermophilic actinomycetes => Farmer`s lung; bagasse worker`s lung; mushroom worker`s lung, potato riddler`s lung, compost worker`s lung, ventilation system`s lung; Lichtheimia corymbifera => Farmer`s lung; Acinetobacter, Ochrobactrum => Metal working fluid`s lung; Streptomyces albus => Compost worker`s lung; Klebsiella oxytoca=> Humidifier`s lung; Bacillus subtilis enzymes => Detergent industry lung; Mycobacterium avium complex and other nontuberculous mycobacteria => Spa worker`s lung. Mycobacterium immunogenum => Metal working fluid`s lung, machine operator´s lung.
Fungi: Alternaria alternate => Humidifier`s lung, wood worker`s lung; Aspergillus spp. => Stucco worker`s lung, tobacco grower`s lung, malt worker`s lung; Trichosporon cutaneum => Summer‐type HP; Penicillium glabrum=> Cork worker`s lung; Pencillium roqueforti => Cheese worker`s lung; Penicillium verrucosum => Food processor`s lung; Penicillium camemberti => Food processor`s lung; Penicillium citreonigrum => Peat moss processing worker`s lung; Cryptostroma corticale => Maple bark stripper`s lung, florist`s lung; Botrytis cinerea => Wine maker`s lung; Mucor stolonifera => Paprika slicer`s lung; Rhodotorula => Humidifier`s lung.
Mushrooms: Shiitaki, Bunashimeji, Pleurotus, Pholiota, Shimeji, Agaricus => Mushroom worker`s lung.
Enzymes: Phytase, subtilisin => Animal feeding lung, cleaner`s lung.
Animal & insect proteins: Avian serum and feather proteins => Bird breeder`s lung; Rat serum proteins= > Laboratory worker`s lung; Pearl => Pearl industry lung; Mollusk shell => Nacre industries’ lung; Silk => Textile worker`s lung; Carmine => Food and cosmetic industries’ lung; Sitophilus granaries => Farmer`s lung.
Plant proteins: Tiger nut => Food processor`s lung; Legumes (e.g. soy) => Food processor`s lung; Malt => Food processor`s lung; Alginate => Seaweed worker`s lung. 
Woods: Ramin, pine => Wood worker`s lung, Esparto dust => Stucco worker`s lung
Low molecular weight chemicals: Diisocyanates => Chemical and polyurethane industry, painter`s lung; Acid anhydrides => Plastic worker`s lung, aircraft industries’ lung; Acrylate compounds = > Dental technician`s lung; Triglycidyl isocyanurate => Painter`s lung (powder paint)
Pharmaceutical agents: penicillins, cephalosporins => Pharmaceutical industry’s lung; Dimethyl phthalate and styrene => Yacht manufacturing lung
Metals: Cobalt => Hard‐metal worker`s lung; Zinc => Smelter`s lung; Zirconium => Ceramic worker`s lung.

=> I suggest to make a term for each "disease"

**Comment by nicolevasilevsky** [comment]
@mgriese we would add diseases to [Mondo](https://mondo.monarchinitiative.org/), not HPO. 

@pnrobinson and @cmungall any objections to adding these diseases to Mondo?
It looks like we have a few of them already:
![image](https://user-images.githubusercontent.com/6722114/83912553-e622fa00-a722-11ea-953d-8acbb0b9930c.png)

I will make a ticket in Mondo

**Comment by pnrobinson** [comment]
@nicolevasilevsky @GrieseAG @cmungall  I agree that we should add the subtypes to MONDO. The HPO term can remain to refer to the typical phenotypic manifestation, although in the fullness of time we need to link this to the Mondo term as well. @nicolevasilevsky  Please close this issue as soon as we have linked to MONDO!

**Comment by pnrobinson** [comment]
I have linked this to the Mondo tracker, closing here. (https://github.com/monarch-initiative/mondo/issues/1821)
