### ISSUE TITLE
revise superclass for Hemophagocytosis HP:0012156

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#5809]
**HPO term**
Hemophagocytosis HP:0012156

**Suggested revision and reasons**

move Hemophagocytosis HP:0012156 to be a child of 'Abnormality of blood and blood-forming tissues'

or should we create a new term 'Abnormal leukocyte physiology' and add this as a child?

**Comment by pnrobinson** [comment]
I think what we observe is a macrophage with RBCs in it. I do not believe this phenotype is observed as an abnormal process. We would place this under physiology if you needed a movie to capture the phenotype, something like increased number of RBCs per minute in some test. Instead it is a histo phenotype, e.g., https://askhematologist.com/hemophagocytosis/

**Comment by nicolevasilevsky** [comment]
MP added this term and placed it as a child of 'abnormal macrophage physiology', but sounds like we should leave it where it is in HPO.

https://github.com/obophenotype/mammalian-phenotype-ontology/issues/3206

**Comment by nicolevasilevsky** [comment]
thanks @pnrobinson!
