### ISSUE TITLE
 “Abnormal morphology of the orbital region”

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#581]
Rename abnormality of the orbital region to  “Abnormal morphology of the orbital region”
from Panagiotis Sergouniotis [panagiotis.sergouniotis@manchester.ac.uk]

**Comment by drseb** [comment]
I think this is not valid, as "abnormality of the orbital region" has subclasses such as

 - Abnormality of the conjunctiva
 - Abnormality of the extraocular muscles
 - etc...

I will close this. Please file a separate issue if you request a more thorough restructuring of that part of HPO
