### ISSUE TITLE
revise superclass: Increased procalcitonin level (HP:0032308)

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#5810]
**HPO term**
Increased procalcitonin level (HP:0032308)

**Suggested revision and reasons**
make it a child of 'Abnormal circulating protein level'

procalcitonin is a pre-hormone, not a hormone

**Comment by pnrobinson** [comment]
This sort of measurement is essentially always done to assess the hormonal status, and users will appreciate having the terms be right near the calcitonin terms, even though this might be a slight error of logic. I would suggest we keep this hear and if there are any issues with the reasoner then we should extend the definition of https://hpo.jax.org/app/browse/term/HP:0003117 to include pro/pre hormones.
