### ISSUE TITLE
Please revise HP:0000233

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#5815]
**HPO term**

HP:0000233

**Bug description**

The list of synonyms need revision. Some of the synonyms need to be moved.

**Comment by LCCarmody** [comment]
Is it possible the definition, "Reduced width of the skin of vermilion border region of upper lip." needs to be changed as well?  Children of this term are 'thin upper lip vermilion' and 'thin lower lip vermilion'.  If this is the definition, should thin lower lip vermilion be moved somewhere else?

**Comment by pnrobinson** [comment]
@LCCarmody  I removed "upper" as suggested by Leigh. The list of synonyms appears correct to me. @drseb can you be specific about which synonym might not be correct?

**Comment by drseb** [comment]
I am confused about the mixing of the thickness of the border and the general volume of the lip. Can you explain why a thin border is equivalent to low volume of lip?

**Comment by pnrobinson** [comment]
I see what you mean. Well, if there is a lot of flesh (volume) in a lip, then the red part will be more prominent. If there is not much flesh in the lip, the red part will appear thin. This sign is very subjective and I think it is hard to define. 
We can do better than present though. Let's adapt the definitions from here (note -- there is no definition for thin lips in general)
https://onlinelibrary.wiley.com/doi/10.1002/ajmg.a.32602

Definition: Height of the vermilion of the medial part of the lip more than 2 SD below the mean, or  apparently reduced height of the vermilion of the lip in the frontal view. The vermilion is the red part of the lips (and confusingly, the vermilion itself is also often referred to as  being equivalent the lips).
PMID:19125428
Does that make more sense?

**Comment by pnrobinson** [comment]
updated definition as above

**Comment by drseb** [comment]
thanks
