### ISSUE TITLE
Anal neoplasm subclass of neoplasms

### ISSUE THREAD

**Issue by c-schroeder** [obophenotype/human-phenotype-ontology#5819]
Anal neoplasm - HP:0032186, Anal margin neoplasm - HP:0030440

Hi,

think for both HPO-terms the parent _Neoplasm_ (or one of its children) is missing. 

Thanks,
Christopher

**Comment by drseb** [comment]
Thanks! Would "Neoplasm of gastrointestinal tract" be a good choice here?

**Comment by drseb** [comment]
I have them there, let me know if there is a better option. Will close for now
