### ISSUE TITLE
dbXrefs format - use canonical URIs?

### ISSUE THREAD

**Issue by mellybelly** [obophenotype/human-phenotype-ontology#5820]
It would be great to improve the use of authoritative URIs in our Xrefs.
e.g. when linking to a SNOMED code, use http://snomed.info/id/2938472834 instead of :SNOMED_2938472834

@hsolbrig i know this is a favorite topic of yours!
requested by @epfaff 
@cmungall

**Comment by pnrobinson** [comment]
I do not see the advantage here because there is an easy 1:1 translation of CURIE to full URI if needed and CURIE's are much easier to human-grok. What is not working now?

**Comment by pnrobinson** [comment]
I will close this, I think we can generate URIs from the xrefs easily, and using CURIE makes it easier to change if needed.
