### ISSUE TITLE
Request definition change for Abnormal PR interval (HP:0031593)

### ISSUE THREAD

**Issue by jrsjrs** [obophenotype/human-phenotype-ontology#5825]
**HPO term**
Abnormal PR interval (HP:0031593)

**Suggested revision of textual definition**
This information was received by the Rat Genome Database (RGD) as a user request from Dr. Bjoern Diem (bhd@mein.gmx).  The request was as follows:

Presumed error in Ontology for "Abnormal PR interval" (HP:0031593)

Abnormal PR interval is currently defined as "An anomaly of the PR interval, which is the portion of the ECG from the end of the P wave to the beginning of the QRS complex. A normal PR interval in adults is 0.12-0.2 seconds."

--> the correct definition of PR interval is "from the beginning of the P wave to the beginning of the QRS complex."

source: e.g. https://www.sciencedirect.com/topics/medicine-and-dentistry/pq-interval

**Comment by pnrobinson** [comment]
Thanks for pointing out this error, we have corrected it!
