### ISSUE TITLE
Missing term-gene relation

### ISSUE THREAD

**Issue by leonschuetz** [obophenotype/human-phenotype-ontology#5831]
Hello,

I think the gene HK1 is missing in the term "HP:0000510 - Rod-cone dystrophy".

In OMIM this gene is associated with Retinitis pigmentosa which is listed as synonym for Rod-cone dystrophy in HPO:
[https://omim.org/entry/142600?search=HK1](https://omim.org/entry/142600?search=HK1)
[https://omim.org/entry/617460](https://omim.org/entry/617460)

Best,
Leon

**Comment by pnrobinson** [comment]
see #5832  and https://hpo.jax.org/app/browse/gene/3098

This disease has not been annotated yet (https://omim.org/entry/618547), thanks for pointing that out.

**Comment by pnrobinson** [comment]
We have now added the annotations to this disease and it should be in the public release in August. Thanks again for pointing this out.
