### ISSUE TITLE
Missing term-gene relation

### ISSUE THREAD

**Issue by leonschuetz** [obophenotype/human-phenotype-ontology#5832]
Hi,

I think the gene RP1L1 is missing in the term "HP:0030636 - Occult macular dystrophy".

At least it is associated with this term in OMIM:
[https://omim.org/entry/613587](https://omim.org/entry/613587)

Best,
Leon

**Comment by pnrobinson** [comment]
The corresponding link is not in the term but it is a so called annotation. If you look at the 'Associated diseases' tab here you will see it
https://hpo.jax.org/app/browse/gene/94137
Not sure if this is answering your question?

**Comment by leonschuetz** [comment]
The term [HP:0030636 - Occult macular dystrophy](https://hpo.jax.org/app/browse/term/HP:0030636) does not have any gene associations, but in OMIM the gene RP1L1 is associated with this phenotype ([https://omim.org/entry/613587](https://omim.org/entry/613587)).

**Comment by pnrobinson** [comment]
I understand now -- thanks for pointing this out, we will annotate this and it should appear at the next release of the HPO in August

**Comment by leonschuetz** [comment]
Thank You, 
(the same applies to #5831).

Is this the correct way to report missing gene associations or is there some template or guideline I missed?

**Comment by pnrobinson** [comment]
@leonschuetz thanks again for pointing this out, and if you find something like this in the future please use this tracker!
