### ISSUE TITLE
Add synonym "sore throat" where appropriate - pharyngitis?

### ISSUE THREAD

**Issue by JasonBarnettNC** [obophenotype/human-phenotype-ontology#5835]
**HPO term**https://hpo.jax.org/app/browse/term/HP:0025439

**Synonym to be added** Sore Throat

**broad/exact/narrow/plural/abbreviation ?**
@pnrobinson  - we also discussed whether this might be more of a constitutional symptom rather than specific to pharyngitis - I'm including here as a synonym request to start the discussion

**Comment by pnrobinson** [comment]
Added new term, "Throat pain", def: An unpleasant sensation characterized by physical discomfort (such as pricking, throbbing, or aching) and perceived to originate in the throat. with synonym "Sore throat. @JasonBarnettNC  This will be online in August.
