### ISSUE TITLE
Plural terms as synonyms - example "Red Eyes"

### ISSUE THREAD

**Issue by JasonBarnettNC** [obophenotype/human-phenotype-ontology#5836]
**HPO term**Red eye https://hpo.jax.org/app/browse/term/HP:0025337

**Synonym to be added** "Red Eyes" 

**broad/exact/narrow/plural/abbreviation ?**
This is really minor but I'm including to share a general search issue - if inputting "red eyes" in the https://hpo.jax.org/ site a match for the above is not found (presumably because of the plural "eyes") I hope this is helpful

**Comment by pnrobinson** [comment]
Thanks @JasonBarnettNC this is a good suggestion. We do try to add plural synonyms for terms like this!

**Comment by drseb** [comment]
Just a reminder to add the synonym-type „plural“ , just in case you don’t have this in mind. Thanks.

(I can also add those if you don’t have the time)
