### ISSUE TITLE
Dermoid cyst

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#584]
Orbital cyst (currently under “Abnormality of the orbital region”). A subclass of this should be “Dermoid cyst”.

Dermoid cyst seems to imply orbital location, but consider more specific term name

from Panagiotis Sergouniotis [panagiotis.sergouniotis@manchester.ac.uk]

**Comment by markengelstad** [comment]
or dermoid cyst of the orbital region
or periorbital dermoid cyst

... since dermoid cysts are found elsewhere (like intraorally)

**Comment by psergouniotis** [comment]
presently "orbital cyst" is a subclass of "abnormality of the periorbital region".
also, "periorbital dermoid cyst" is a subclass of "orbital cyst".

This is counterintuitive. 
* Consider moving "orbital cyst" as a subclass of "abnormality of the orbital region". 
* Consider introducing the term "periorbital cyst" as a subclass of  "abnormality of the periorbital region"
* Consider adding "periorbital dermoid cyst" as a subclass of "periorbital cyst".
*  "periorbital dermoid cyst" should not be a subclass of "orbital cyst"
