### ISSUE TITLE
synesthesia

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#5860]
**Preferred term label:**
synesthesia

See: https://github.com/monarch-initiative/mondo/issues/1688

should we add this to HPO?

**Comment by pnrobinson** [comment]
I think that this phenotypic feature has been reported by artists rarely, meaning for instance if you hear music you see color. I wish I had this feature myself, but in any case, I do not think it is used in medicine. If we find some examples of disease association we can add the term in the future.
