### ISSUE TITLE
Add synonym - HP:0020172

### ISSUE THREAD

**Issue by callahantiff** [obophenotype/human-phenotype-ontology#5861]
**HPO term**  
**[`HP:0020172`](https://hpo.jax.org/app/browse/term/HP:0020172)**

**Synonym to be added**   
"drug-induced response", "drug-induced reaction"

**broad/exact/narrow/plural/abbreviation ?**  
Exact - I think this would be appropriate

**Comment by pnrobinson** [comment]
thanks! Added both synonyms

**Comment by callahantiff** [comment]
Thank you very much! 🙇‍♀️ 👏
