### ISSUE TITLE
Move coloboma to  Abnormal morphology of the orbital region

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#587]
Coloboma 
 To move this to the class “Abnormal morphology of the orbital region” (as it includes eyelid coloboma as a subclass)

from 
Panagiotis Sergouniotis [panagiotis.sergouniotis@manchester.ac.uk]

**Comment by drseb** [comment]
related to #581 

I think this is a bigger issue. I will open a separate issue (see #653)
