### ISSUE TITLE
Abnormality of globe size

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#588]
Abnormality of globe size
This class needs some work. “Microphthalmos” should be renamed to “Microphthalmia” and together with “Anophthalmia” should be moved to the class “Aplasia/Hypoplasia of the globe”. “Cryptophthalmos” should be become a subclass of “Abnormality of the eyelid”. The terms “Large eyes” and “Increased axial globe length” should be deleted and the associated OMIM terms should be merged with “Myopia”

from 
Panagiotis Sergouniotis [panagiotis.sergouniotis@manchester.ac.uk]

**Comment by markengelstad** [comment]
I like what you are doing --- the routine use of 'globe' instead of 'eye'.
'eye'  is too non-specific.

**Comment by pnrobinson** [comment]
Renamed to microphthalmia.
Microphthalmia and Anophthalmia are in abn. of globe size.
Moved crypopthalmos to abn of the eyelid
I think increased axial globe length and large eyes are valid terms. They are almost always associated with myopia, but this is a separate phenotype.
