### ISSUE TITLE
Persistence of the hyaloid artery 

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#595]
Persistence of the hyaloid artery 
Term to be included as a synonym of “Remnants of the hyaloid vascular system”
from 
Panagiotis Sergouniotis [panagiotis.sergouniotis@manchester.ac.uk]

**Comment by drseb** [comment]
What does that mean? Add "Remnants of the hyaloid vascular system" as a synonyms or as a subclass?

**Comment by pnrobinson** [comment]
Not sure that "remnants of the hyaloid vascular system is a good term. Reopen if necessary.
