### ISSUE TITLE
Vitreitis

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#596]
Vitreitis
To correct the name to ”Vitritis”. To add the following subclasses: (i) “Vitreous inflammatory cells”, (ii) ”Vitreous haze”, (iii) “Snowballs in the vitreous”.
from 
Panagiotis Sergouniotis [panagiotis.sergouniotis@manchester.ac.uk]

**Comment by pnrobinson** [comment]
I changed the primary name to Vitritis and added vitreitis and also hyalitis as synonyms. Added Vitreous haze as a child term. Will check on other two suggestions.

**Comment by drseb** [comment]
The related commit https://github.com/obophenotype/human-phenotype-ontology/commit/532cf663a40d4f6b9e50459ae0bc6ee033b369ab contains errors. See my [notes](https://github.com/obophenotype/human-phenotype-ontology/commit/532cf663a40d4f6b9e50459ae0bc6ee033b369ab)
