### ISSUE TITLE
Add encoding test

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#605]
Add travis test to check if we stay in unicode-space.

**Comment by drseb** [comment]
E.g. 

    iconv -f UTF-8 -t ISO-8859-15 hp.obo > out.txt

should run without error message.

**Comment by cmungall** [comment]
All this time I've been using ad-hoc perl. This is much better, I will
implement this for multiple ontologies, thanls @drseb!

**Comment by drseb** [comment]
See our makefile and our travis.yml for more details

https://github.com/obophenotype/human-phenotype-ontology/blob/master/.travis.yml

https://github.com/obophenotype/human-phenotype-ontology/blob/master/src/format/Makefile
