### ISSUE TITLE
New term request: fracture modifiers

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#6050]
@pnrobinson we discussed on the bone fracture ticket (#3889) that you would make new terms in HPO under clinical modifier that could be used in annotations of bone fracture clinical data:
-fracture modifier
-Soft-tissue involvement, etc
-Displacement, etc
-Fragments, etc
-Mechanism, etc

I could add these, if you prefer.

I think all the modifiers we would need  are in columns F-O in this [spreadsheet](https://docs.google.com/spreadsheets/d/11Z6RoYvbo2-_YwRTve0iG3bINnHRlw6jga_j0Oy7_1A/edit#gid=0)

**Comment by pnrobinson** [comment]
@nicolevasilevsky @matentzn What is the status here? Are we still using these modifiers or was the decision to precompose?

**Comment by matentzn** [comment]
I don't know anything about this process, so @nicolevasilevsky will know :)

**Comment by nicolevasilevsky** [comment]
@pnrobinson I believe the action was for you to create the new subclasses of clinical modifier, and these would be available in the annotation files. Do we still want to proceed this way? I'm happy to create these new classes in HPO if you like.

**Comment by pnrobinson** [comment]
I am not sure I can find the final list of modifiers? But it also seems that we have created a bunch of precomposed terms -- we should probably just do one or the other, but not both pre and postcompos?

**Comment by nicolevasilevsky** [comment]
@pnrobinson 
all the modifiers we would need  are in columns F-O in this [spreadsheet](https://docs.google.com/spreadsheets/d/11Z6RoYvbo2-_YwRTve0iG3bINnHRlw6jga_j0Oy7_1A/edit#gid=0)

**Comment by pnrobinson** [comment]
Added these terms as modifiers underneath a new modifier term called ``Fracture type``
