### ISSUE TITLE
Grouping term for developmental pulmonary anomalies

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#6052]
@mgriese, @katrinknoflach

As discussed today, we agreed to think about a possible grouping term for developmental anomalies of the lung.

**Comment by mgriese** [comment]
I have appended a sugestion to ro-order developmental anaomalies of the lung, i.e. give a struccture in which new and establsihed termes can be organized.

[ROT ist HPO => GRÜN ist neu 2.8.2020.docx](https://github.com/obophenotype/human-phenotype-ontology/files/5012453/ROT.ist.HPOGRUN.ist.neu.2.8.2020.docx)

**Comment by pnrobinson** [comment]
implemented part of the reorganization (upper respiratory)
- [ ]  Question -- not every abnormality of the nose is a respiratory abnormality. We would need to subdivide the nose into facial etc and respiratory to make the latter part a subterm.
- [ ] Todo -- consider development terms

**Comment by pnrobinson** [comment]
Added a new term, 'Abnormal lung development'
