### ISSUE TITLE
Question: dyspnea vs respiratory distress 

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#6058]
dyspnea and respiratory distress have very similar definitions. These seem to be different but could we improve the definitions?

There are some overlap of synonyms too. I suggest the following text defs and synonyms:

Suggested defs:
**Dyspnea**
_def_: 
An intense tightening in the chest, air hunger, difficulty breathing, breathlessness or a feeling of suffocation.
source: It is a subjective experience that can be reported by the patient.
https://www.mayoclinic.org/symptoms/shortness-of-breath/basics/definition/sym-20050890
PMID:15183210

_synonyms_:
Add: 
Breathing difficulties (Layperson)
Difficulty breathing (Layperson)
Short of breath (Layperson)
Shortness of breath (Layperson) 

**Respiratory distress**
_def_: 
The physical or emotional suffering that results from the experience of dyspnea (shortness of breath).
PMID:15183210

_synonyms:_
Remove:
Breathing difficulties
Difficulty breathing
Short of breath (Layperson)
Shortness of breath (Layperson) 

cc @sbello

**Comment by pnrobinson** [comment]
I am not sure that I agree with the definitions above. I will ask our pulmology colleagues to help with this.

**Comment by nicolevasilevsky** [comment]
sounds good, thanks!

**Comment by mgriese** [comment]
I agree with the definition of 
*Dyspnoe is a subjective feeling only the patient can rate, i.e. on a Borg scale.
In contrast respiratory distress can be defined as
*Respiratory distress is objectively observable as the physical or emotional consequences from the experience of dyspnea.

**Comment by pnrobinson** [comment]
modified the definitions and retained both terms. thanks!
