### ISSUE TITLE
Hyperactivity -> should this be a behavioral abnormality?

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#6059]
**HPO term**
Hyperactivity

**Suggested revision and reasons**

should this be a behavioral abnormality instead of a movement disorder?

We discussed this on the KF INCLUDE call.

**Comment by nicolevasilevsky** [comment]
pinging @pnrobinson 
I can implement this change, if it sounds okay to you.

**Comment by pnrobinson** [comment]
good suggestion,, I just implemented
