### ISSUE TITLE
increased pulmonary respiratory rate? 

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#6060]
The MP has separate terms for tachypnea (MP:0005426) and increased pulmonary respiratory rate (MP:0005573). The HPO has a single term for these HP:0002789 (Tachypnea). MP did it this way as we may have cases where the rate is slightly but significantly increased but we wouldn't want to say that it is 'rapid'.

Do we want to separate these out into two terms or does it make sense to just have one term in HPO?

**Comment by pnrobinson** [comment]
I don't think this would be used like this clinically -- I think it makes more sense just to have a term for something that is clearly abnormal (Tachypnea)...

**Comment by nicolevasilevsky** [comment]
sounds good! I'll close.

cc @sbello
