### ISSUE TITLE
New terms for facial clefts

### ISSUE THREAD

**Issue by CourtneyHum** [obophenotype/human-phenotype-ontology#609]
I noticed that only two types of facial clefts are included in the HPO. Could we include all facial clefts in Tessier's classification?

Class: Facial cleft
Subclasses: Tessier cleft number 0-14, inclusive

Could organize them into 
- midline clefts (0, 14)
- paramedian clefts (1, 2, 12, 13)
- orbital clefts (3, 4, 5, 9, 10, 11)
- transverse clefts (6, 7, 8)

**Comment by markengelstad** [comment]
Funny you should write this as just today i was doing some cleft classification, starting w/ oral , then orofacial, and now facial clefts.  I was planning to add the tessier classifications.  To me, your hierarchy looks good. 
for instance: 
Midline facial cleft is a facial cleft
Tessier_14 facial cleft is a Midline facial cleft

**Comment by drseb** [comment]
I don't see any commits that add these terms. Why is this issue closed then?

**Comment by pnrobinson** [comment]
This is a good suggestion. Will need some work. See
http://digital.library.pitt.edu/c/cleftpalate/pdf/e20986v26n3.03.pdf
for definitions and explanations.

**Comment by pnrobinson** [comment]
Mark, do you have some time to work on this with me? Would this be a good suggestion?

**Comment by pnrobinson** [comment]
This was a difficult issue, but I have now added the various Tessier clefts!
