### ISSUE TITLE
Hierarchy cell abnormalities

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#6091]
@nicolevasilevsky @LCCarmody @matentzn 
Could you check and maybe revise the cell abnormalites branches - I don't think that the "count"-classes belong inside of the morphology-branches. Or did you decide this on purpose? See screenshot:
<img width="470" alt="Screenshot 2020-08-04 at 08 30 15" src="https://user-images.githubusercontent.com/5172897/89260689-10af0780-d62d-11ea-9709-18b81c2baac8.png">

**Comment by matentzn** [comment]
I believe you are absolutely correct; this subsumption is not supported by PATO, where `amount` (which is used by by the abnormalNumberOfAntomicalEntityPattern) is NOT a subclass of `morphology`. This should be fixed.

**Comment by pnrobinson** [comment]
Well, if we consider that we are talking about the set of ALL leukocytes in a body and then Leukopenia is a morphological abnormality of this set. I do not understand why this is not morphology?

**Comment by matentzn** [comment]
So `Abnormal leukocyte morphology` refers to an abnormality in the set of all leukocytes, or describes an actual morphological abnormality (increased size, say) in the structure of a leukocyte? Or should it capture both? These are very different things. You could have an average increase in the size of a leukocyte (ok that may not be biological feasible), and no change in the "size" of the set of all leukocytes, and vice versa. Which case did you intend this term to capture?

**Comment by pnrobinson** [comment]
There are enormous numbers of leukocytes at any point in time and so we do not care about any particular one, we are always referring to a feature that is found in some or all leukocytes. Count is a property of this. I do not think we would gain anything by adding a new subhierarchy. This is the hierarchy that an MD would expect to find, I think, whatever PATO says!

**Comment by pnrobinson** [comment]
I am going to close this issue, acknowledging the comments but for now it seems the most sensible thing. Reopen if we have a concrete additional proposal for this.
