### ISSUE TITLE
HP:0011461 fetal onset

### ISSUE THREAD

**Issue by ANiknejad** [obophenotype/human-phenotype-ontology#6098]
Hello HPO team,

HP:0011461 fetal onset

has definition 'Onset prior to birth but after 8 weeks of **gestation.'**

-> should be either **10 weeks of gestation**, or 8 weeks of **fertilisation**

Please see https://embryology.med.unsw.edu.au/embryology/index.php/Carnegie_stage_23

'8 weeks of **gestation.'**' corresponds to Carnegie stage 17, please see

https://embryology.med.unsw.edu.au/embryology/index.php/Carnegie_stage_17

[WP: The time interval of a gestation is called the gestation period. In human obstetrics, gestational age refers to the fertilization age plus two weeks. This is approximately the duration since the woman's last menstrual period (LMP) began. ]

Best,

Anne 

Anne Niknejad
Biocurator
https://bgee.org/
SIB | Swiss Institute of Bioinformatics
Unil, Department of Ecology and Evolution - Quartier Sorge, bâtiment Biophore - 1015 Lausanne
t: +41 21 692 42 21 - f: +41 21 692 41 65
Anne.Niknejad@sib.swiss - https://www.sib.swiss

**Comment by ANiknejad** [comment]
Please also consider to logically modifiy HP:0011460 (Embryonal onset) textual definition

**Comment by pnrobinson** [comment]
thanks for pointing this out, I have corrected the definition.
