### ISSUE TITLE
HP:0410280 Pediatric onset

### ISSUE THREAD

**Issue by ANiknejad** [obophenotype/human-phenotype-ontology#6099]
Hello HPO team,

HP:0410280 Pediatric onset
Onset of disease manifestations before adulthood, defined here as **before the age of 16 years**, but excluding neonatal or congenital onset.

but the upper limit (Juvenile onset) does not have the same definition:

HP:0003621 Juvenile onset
Onset of signs or symptoms of disease between the age of 5 and 15 years.
Synonyms:    Signs and symptoms begin **before 15 years** of age

Could you harmonize to make things logical, please?

Also see this issue 'Pediatric onset term request' https://github.com/obophenotype/human-phenotype-ontology/issues/4206
and the comment from  allisonheath commented on Oct 26, 2018:  "I think typically in cancers pediatric is considered **0-14** (https://www.cancer.gov/types/childhood-cancers) and increasingly there's a work on distinguishing it from adolescent and young adult cancers 15-39 (AYA https://www.cancer.gov/types/aya). "

See also comments from Chris Mungall about time boundaries, here https://github.com/obophenotype/human-phenotype-ontology/issues/382

and at the end, 'I added the comment to "childhood onset": This term refers to ages up to but not including the fifth birthday (see Juvenile onset).
Original comment by: pnrobinson'
So 
Childhood onset HP:0011463
Onset of disease at the age of **between 1 and 5 years.**
means until 4 year-old = before 5 year-old
property_value: start_ypb "1.0" xsd:float
property_value: end_ypb "5.0" xsd:float

So I would suggest to define 

HP:0410280 Pediatric onset
Onset of disease manifestations before adulthood, defined here as **_before the age of 15 years_**, but excluding neonatal or congenital onset.

**_before the age of 15 years_** means until 14 year-old = before 15 year-old
property_value: start_ypb "0.0" xsd:float
property_value: end_ypb "15.0" xsd:float

Do you agree? Any comments?
Thank you in advance for clarifying the time boundaries here.
Best,

Anne

**Comment by pnrobinson** [comment]
@ANiknejad  sorry for the delay in responding. I have changed the range to 15 years as suggested, thanks!
I am less convinced we should change young adult to start from 15 years -- we could easily find other definitions in the literature, and there is simply no way of making this term consistent across all resources. We have been using these terms for some time, and so if we change the definition, we would need to go back and reannotate all records involved (which we would do if this was a clear mistake!).
If you are annotating individual patients, probably the best thing is to actually capture the age using some appropriate combination of integers. The HPO definitions are meant to be relatively general groupings that can be used by algorithms.

**Comment by fbastian** [comment]
Hi @pnrobinson
> I am less convinced we should change young adult to start from 15 years

Then you have a gap in definition between 15 and 16yo, it really is the same type of problem as https://github.com/obophenotype/human-phenotype-ontology/issues/382. Making the term consistent across all resources is kind of the purpose of an ontology :p

> The HPO definitions are meant to be relatively general groupings that can be used by algorithms

Then could you remove the exact age range from the definition and the properties please? This way we could cross-ref to HPO in our developmental stage ontology in a consistent way.

**Comment by pnrobinson** [comment]
@fbastian  this is the same argument as with the various kinds of numbering for genome sequences
https://arnaudceol.wordpress.com/2014/09/18/chromosome-coordinate-systems-0-based-1-based/

The definitions are taken from a standard book in clinical genetics and are consistent in the way they are intended -- which is "one-based inclusive". For the clinical audience this is more intuitive.
