### ISSUE TITLE
Not placed in category

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#6107]
**HPO term**

[WARN] Not placed in category: Fractured thoracic segment of trunk: HP:0041054
[WARN] Not placed in category: Avulsion fractured pelvic region of trunk: HP:0041090
[WARN] Not placed in category: Fractured trunk: HP:0041158
[WARN] Not placed in category: Fractured pelvic region of trunk: HP:0041161

These terms need to be placed by assertion.

**Comment by pnrobinson** [comment]
@nicolevasilevsky  What was Fractured thoracic segment of trunk supposed to be? This sounds like a rib fracture (which already existed)
https://hpo.jax.org/app/browse/term/HP:0041054
Also, Fractured trunk is not something anybody would ever say, I am guessing it was meant to be something else?

**Comment by pnrobinson** [comment]
@nicolevasilevsky @matentzn  I am going to obsolete these terms, I think they are probably the result of some bug in the creation script?

**Comment by matentzn** [comment]
Oh yes, seems like the script failed to classify these four terms! Weird! 

@pnrobinson I think this is a clear case of 'you know best'! I really have know opinion. I would personally:

1. Manually classify them while you decide whether to obsolete them - their current location in the class hierarchy is just confusing and wrong.
2. Ask @callahantiff which is the original requestor of the terms, whether they are used/needed
3. Obsolete them if she doesn't need them

**Comment by pnrobinson** [comment]
I am going to obsolete these terms, I think they are malformed!
