### ISSUE TITLE
Remove label annotation

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#611]
Halberd-shaped pelvis bone HP_0002826

**Comment by drseb** [comment]
This label has the an "created_by" annotation, which we currently do not want in hp.owl.

**Comment by pnrobinson** [comment]
Added a definition for this class:
An anomalous radiographic appearance of the developing pelvis, in which the greater ischiadic noth (incisura ischiadica major) is shallow and the pelvis takes on the appearance said to resemble a halberd (a weapon especially of the 15th and 16th centuries consisting typically of a battle-ax and pike mounted on a handle).
Had to rename the class to Halberd-shaped pelvis (the previous label was not quite accurate).
also removed the stray label annotation.
