### ISSUE TITLE
Additional child terms to HP:0001626

### ISSUE THREAD

**Issue by jpazmandi** [obophenotype/human-phenotype-ontology#6148]
**HPO term**

HP:0001626 - Abnormality of the cardiovascular system

**Suggested revision and reasons**
We would like to request to add the following term + child terms to HP:0001626 (Abnormality of the cardiovascular system):

-HP:0001626 (Abnormality of the cardiovascular system)
      - Tissue ischemia (child term of HP:0001626)
                 - Digital ischemia (child term of Tissue ischemia)
                 - Testicular ischemia (child term of Tissue ischemia)
                 - Intestinal ischemia (child term of Tissue ischemia)

Definitions:
Tissue ischemia:  restriction in blood supply to tissues, causing a shortage of oxygen that is needed for cellular metabolism
Digital ischemia: inadequate supply of oxygenated blood to digital tissue
Testicular ischemia:  inadequate supply of oxygenated blood to the testes. It results from the injury to the vessels that course along the inguinal canal.
Intestinal ischemia: inadequate supply of oxygenated blood to the intestine.

**Comment by pnrobinson** [comment]
The issue with these terms is that they are inferences and not direct phenotypic observations. Can we rephrase in terms of what is actually observed clinically? @jpazmandi

**Comment by jpazmandi** [comment]
Can change the word ischemia to infarction- but the experts prefer ischemia because that is what they see (eg on a doppler ultrasound of the testicles- reduced blood flow), sometimes without infraction (if they treat it fast enough!)

**Comment by pnrobinson** [comment]
I think that this is the proper parent
https://hpo.jax.org/app/browse/term/HP:0025323
I agree that ischemia and infarction are not the same.

I am adding with this definition for the top level term

Ischemia is defined as a restriction of arterial blood supply to a tissue associated with insufficient oxygenation to support the metabolis requirements of the tissue. Depending on the involved tissues, clinical manifestations may include pain, pallor, lack of pulse, coldness, paresthesia, and paralysis. Additional associated manifestations include hemodynamic parameters (reduced blood pressure distal to the site of restricted arterial supply) and angiographic evidence of arterial occclusion.
