### ISSUE TITLE
Additional child terms to HP:0012649 (Increased inflammatory response)

### ISSUE THREAD

**Issue by jpazmandi** [obophenotype/human-phenotype-ontology#6149]
**HPO term**
Would like to add additional child terms to HP:0012649 (Increased inflammatory response).

**Suggested revision and reasons**
- HP:0012649 (Increased inflammatory response)
-- Systemic autoinflammation (child term of HP:0012649)
-- Neuroinflammation (child term of HP:0012649)
--- HP:0012486 (Myelitis) (child term of Neuroinflammation)
--- Non-infectius meningitis (child term of Neuroinflammation)
--- HP:0100653 (Optic neuritis) (child term of Neuroinflammation)

Definitions:
Systemic autoinflammation: chronic activation of the innate immune system.
Neuroinflammation: activation of the brain's innate immune system in response to an inflammatory challenge and is characterized by a host of cellular and molecular changes within the brain.
Non-infectius meningitis: inflammation of the layers of tissue that cover the brain and spinal cord (meninges) and of the fluid-filled space between the meninges (subarachnoid space) when it is caused by disorders that are not infections or by drugs or vaccines.

**Comment by pnrobinson** [comment]
added
