### ISSUE TITLE
Make Abnormality of the ocular region HP_0000284 obsolete.

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#615]
Abnormality of the ocular region HP_0000284 is being merged with Abnormality of the orbital region (HP_0000315). I have added an ALT ID to the latter class. We now need to make  Abnormality of the ocular region HP_0000284 obsolete. I am uncertain of the best way to do this in Protege 5. Please do so and document in the readme.

**Comment by cmungall** [comment]
Do you have the obsoletion plugin?

http://wiki.geneontology.org/index.php/Ontology_editor_plugins
