### ISSUE TITLE
HP:0000524

### ISSUE THREAD

**Issue by jpazmandi** [obophenotype/human-phenotype-ontology#6150]
**HPO term**
HP:0000524 (Conjunctival telangiectasia)

**Suggested revision and reasons**
Would like to add HP:0000524 (Conjunctival telangiectasia) as a child term of HP:0012372 (Abnormal eye morphology).
Suggested change:
-HP:0012372 
-- HP:0000524 (child term of HP:0012372)

Reason: by definition Conjunctival telangiectasia is the presence of small (ca. 0.5-1.0 mm) dilated blood vessels near the surface of the mucous membranes of the conjunctiva.

**Comment by pnrobinson** [comment]
This term has two parents, one of which is
https://hpo.jax.org/app/browse/term/HP:0008054
Abnormal morphology of the conjunctival vasculature

If you were looking at the HPO webpage note that terms with multiple parents have multiple grey bars at the top left to represent the parent terms.

**Comment by jpazmandi** [comment]
Thank you!
