### ISSUE TITLE
Addition to HP:0001939 and revision of HP:0011227

### ISSUE THREAD

**Issue by jpazmandi** [obophenotype/human-phenotype-ontology#6151]
**HPO term**
Would like to request an addition to HP:0001939 and revision of the location of HP:0011227

**Suggested revision and reasons**
Would like to request the following additions/revision:

-HP:0001939 (Abnormality of metabolism/homeostasis)
-- Elevated acute phase response (child term of HP:0001939)
--- Elevated C-reactive protein level (HP:0011227) (child term of Elevated acute phase response)
--- Elevated serum amyloid A  (child term of Elevated acute phase response)

Definitions.
Elevated acute phase response: elevated level of acute-phase proteins. 
Elevated serum amyloid A: Elevated level of amyloid A proteins in the serum.

**Comment by pnrobinson** [comment]
Elevated acute phase response probably should be named simply Acute phase response. Here is a review
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2798837/

**Comment by pnrobinson** [comment]
added
