### ISSUE TITLE
Additions to HP:0001881 (Abnormal leukocyte morphology)

### ISSUE THREAD

**Issue by jpazmandi** [obophenotype/human-phenotype-ontology#6152]
**HPO term**
We would like to request additions to HP:0001881 (Abnormal leukocyte morphology)

**Suggested revision and reasons**
- HP:0001881 (Abnormal leukocyte morphology)

-- Dysregulated immunoglobulin production (child term of HP:0001881 )
-- Abnormal leukocyte migration (child term of HP:0001881 )
-- Abnormal leukocyte adhesion (child term of HP:0001881 )
-- HP:0031378 (Abnormal lymphocyte proliferation) (child term of HP:0001881 )
--- HP:0031379 (Abnormal T-cell proliferation) (child term of HP:0031378)

Definitions:
Dysregulated immunoglobulin production: antibody deficiencies and overproduction of specific antibodies.
Abnormal leukocyte migration: abnormality of migratory behaviour of leukocytes.
Abnormal leukocyte adhesion: defect of cellular adhesion molecules resulting in clinical syndromes.

**Comment by pnrobinson** [comment]
@jpazmandi sorry for the delay with these terms. 
I do not understand what you mean by dysregulated immunoglobulin production. How is this different from Abnormal immunoglobulin level HP:0010701?

**Comment by pnrobinson** [comment]
Adding term 
id: HP_0033797
Label: Leukocyte migration defect
Def: Any abnormality of leukocyte motility in response to chemokines, which is required for the inflammatory response to infections, and for organ development, tissues homeostasis, and vascularization.
-- This is not Abnormal leukocyte morphology, it is physiology, under abnormal immune system physiology/abnormal leukocyte physiology.

**Comment by pnrobinson** [comment]
Adding term 
id:HP_0033798
label: Impaired leukocyte adhesion
def:During states of inflammation, white blood cells (leukocytes) play a key role in maintaining tissue homeostasis through elimination of pathogens and removal of damaged tissue. Leukocytes migrate to the site of inflammation by crawling over and through the blood vessel wall, into the tissue. This term refers to a defect in the attachment of leukocytes to the blood vessel wall, which is a key step required before they can pass through gaps of the endothelial cells of the blood vessel wall to migrate to the site of inflammation.
parent -- Leukocyte migration defect

**Comment by pnrobinson** [comment]
I have also added a link between the abnormal leukocyte physiology to Abnormality of blood and blood-forming tissues HP:0001871, which was missing.

I will close this issue now @jpazmandi but if my answer regarding dysregulated immunoglobulin production was not sufficient, please open a new issue.
