### ISSUE TITLE
Eosinophilic esophagitis

### ISSUE THREAD

**Issue by johannaest** [obophenotype/human-phenotype-ontology#6155]
**HPO term**
Eosinophilic infiltration of the esophagus

**Synonym to be added**
Eosinophilic esophagitis

**broad/exact/narrow/plural/abbreviation ?**

**Comment by pnrobinson** [comment]
That is this term
https://hpo.jax.org/app/browse/term/HP:0410151
I will add 'Eosinophilic esophagitis' as a synonym.
