### ISSUE TITLE
Eosinophilic gastritis

### ISSUE THREAD

**Issue by johannaest** [obophenotype/human-phenotype-ontology#6156]
**HPO term**
Eosinophilic infiltration in the stomach mucosa

**Synonyms**
Gastric Eosinophilia, Eosinophilic gastritis

**Suggested revision and reasons**
Add additional parent term "Gastrointestinal eosinophilia", since it is also part of the eosinophilic gastrointestinal infiltration

**Comment by pnrobinson** [comment]
That is this term
https://hpo.jax.org/app/browse/term/HP:0410147
I will add 'Eosinophilic gastritis' as a synonym
