### ISSUE TITLE
Left ventricular hypertrophy vs. Increased left ventricular size (Left ventricular enlargement)

### ISSUE THREAD

**Issue by tudorgroza** [obophenotype/human-phenotype-ontology#6165]
**HPO term**
`HP:0001712` - Left ventricular hypertrophy

**Bug description**
 * Background: we discussed with a pulmonary expert the differential diagnosis of PAH vs PH. Among others, we received as possibly discriminating features of PH (i.e., non-PAH PH) `Left ventricular hypertrophy` and `Increase left ventricular size` (as individual phenotypes)
 * `HP:0001712` is defined as: 'Enlargement or increased size of the heart left ventricle.' - which seems to merge the two phenotypes into one.
 * On a different note, `Left ventricular hypertrophy` is a thickening of the wall of the heart's main pumping chamber. (Mayo Clinic - https://www.mayoclinic.org/diseases-conditions/left-ventricular-hypertrophy/symptoms-causes/syc-20374314#dialogId63338924), while `Increase left ventricular size` is rather seen as an enlargement of the chamber.
 * Would it be possible to split this term into two?

Thank you!

**Comment by pnrobinson** [comment]
@tudorgroza sorry for the late response, 2020 was a difficult year.
The HPO needs to be explanded to better cover echocardiography.
I think that `Increased left ventricular size`` probably relates to this:

Left ventricular (LV) size is standardly reported by measurement of the internal diameter in diastole (IDD) in patients undergoing echocardiography.

see https://openheart.bmj.com/content/1/1/e000147

I do not think we would split the term in two, but it does seem reasonable to add terms related to internal diameter in diastole

I will leave this here in case you want to comment but will prob add in a few days.

**Comment by tudorgroza** [comment]
Thank you @pnrobinson ! I have no comments :) You're the expert.

**Comment by pnrobinson** [comment]
@tudorgroza coming back to this -- hypertrophy and increased size are not synonyms. I think it is better to leave the echocardiography terms for now until we get cardiology input.
