### ISSUE TITLE
Carcinoma

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#617]
A histological type of malignant neoplasm that is made up of epithelial cells tending to infiltrate the surrounding tissues and give rise to metastases.
MeSH: D002277
NCI thesaurus: C2916
(Note: Needed for completeness now, in future integration with NCI thesaurus is planned)

**Comment by drseb** [comment]
Where should this class go? Directly under Neoplasm?

**Comment by pnrobinson** [comment]
yes directly under neoplasm. We will need to make links to various kinds of carcinoma currently in the hierarchy.

**Comment by mellybelly** [comment]
Note for later- this is a pathological anatomical entity, not exactly a phenotype. Need to think about that more.



On Jan 31, 2016, at 9:24 AM, Peter Robinson <notifications@github.com<mailto:notifications@github.com>> wrote:


yes directly under neoplasm. We will need to make links to various kinds of carcinoma currently in the hierarchy.
