### ISSUE TITLE
Add Missing Definition: Anencephaly

### ISSUE THREAD

**Issue by callahantiff** [obophenotype/human-phenotype-ontology#6214]
**HPO term**
Anencephaly (`HP_0002323`)  

**Suggested revision of textual definition**
From The NIH Genetics Home Reference:
 > Anencephaly is a condition that prevents the normal development of the brain and the bones of the skull. This condition results when a structure called the neural tube fails to close during the first few weeks of embryonic development. The neural tube is a layer of cells that ultimately develops into the brain and spinal cord. Because anencephaly is caused by abnormalities of the neural tube, it is classified as a neural tube defect.

*Cite:* https://ghr.nlm.nih.gov/condition/anencephaly

**Comment by pnrobinson** [comment]
We try to have PMIDs for definitions, so I added one from here, https://pubmed.ncbi.nlm.nih.gov/31424828/
thanks for pointing this out!
