### ISSUE TITLE
Add Synonym: Anencephaly

### ISSUE THREAD

**Issue by callahantiff** [obophenotype/human-phenotype-ontology#6215]
**HPO term**
Anencephaly (`HP_0002323`)

**Synonym to be added**
Fetal anencephaly, Embryonic anencephaly, Neural tube defect

**broad/exact/narrow/plural/abbreviation?**  
*Broad:* Neural Tube Defect  
*Exact:*  
- Fetal Anencephaly  
- Embryonic Anencephaly

From The NIH Genetics Home Reference: https://ghr.nlm.nih.gov/condition/anencephaly

___

This is related to the definition request made for this term: #6214

**Comment by pnrobinson** [comment]
neural tube defect is too broad, ,and there are other HPO terms that would fall under it, e.g., spina bifida.
It is difficult to represent this in the HPO, which does not attempt to model embryology. 
I added the other two synonyms.
