### ISSUE TITLE
Re-Organizing the Asthma Phenotype Hierarchy

### ISSUE THREAD

**Issue by callahantiff** [obophenotype/human-phenotype-ontology#6216]
I'm curious what your thoughts are about expanding (with some slight reorganization) the existing asthma phenotype hierarchy. Currently, HPO includes the following terms under asthma:

Asthma (`HP_0002099`)  
- Aspirin-induced asthma (`HP_0012042`)  
- Exercise-induced asthma (`HP_0012652`)  
- Status asthmaticus (`HP_0012653`)  

<br>

Given the literature in this area ([American Academy of Allergy, Asthma & Immunology](https://www.aaaai.org/conditions-and-treatments/library/asthma-library/asthma-phenotypes#:~:text=Several%20different%20types%20or%20what,fixed%2Dobstruction%2C%20and%20occupational)), the clearly (ish) defined diagnostic procedures, and accumulating genotype evidence supporting these different types, I am wondering if we might be able to this instead:  

Asthma  (`HP_0002099`)  
- Extrinsic or Allergic Asthma ([PMID:25439351](https://pubmed.ncbi.nlm.nih.gov/25439351/)) --> `NTR`  
- Intrinsic or Non-Allergic Asthma ([PMID:25439352](https://pubmed.ncbi.nlm.nih.gov/25439352/)) --> `NTR`  
- Aspirin-induced asthma (`HP_0012042`)  --> add "asprin-sensitive" as a synonym
- Exercise-induced asthma (`HP_0012652`)   
- Severe Asthma ([PMID:29700091](https://pubmed.ncbi.nlm.nih.gov/29700091/), [PMID:28689839](https://pubmed.ncbi.nlm.nih.gov/28689839/)) --> `NTR`  
  - Status asthmaticus (`HP_0012653`)  
  - Neutrophilic Asthma ([PMID:28784414](https://pubmed.ncbi.nlm.nih.gov/28784414/)) --> `NTR`    
  - Fixed-Obstruction Asthma ([PubMed:12426229](https://pubmed.ncbi.nlm.nih.gov/12426229/)) --> `NTR`     
- Occupational Asthma ([PMID:30320613](https://pubmed.ncbi.nlm.nih.gov/30320613/)) --> `NTR`      

I think this would provide a strong foundation for further development of these phenotypes (and likely new subphenotypes) as our mechanistic understanding of asthma in pediatric and adult populations continues to grow. 

<br>

If you are willing to consider this, I am happy to create NTRs for each new term as well as to provide analytics and clinical domain expertise supporting these phenotypes in several clinical populations.

**Comment by LCCarmody** [comment]
This definitely needs to be done. I'll try to see if I can find my old NIAID notes from a hackathon.  Everyone could agree that it needed to be done, but no one could quite agree on how to do it.

**Comment by callahantiff** [comment]
> This definitely needs to be done. I'll try to see if I can find my old NIAID notes from a hackathon. Everyone could agree that it needed to be done, but no one could quite agree on how to do it.

Woo hoo! Thanks @LCCarmody -- please let me know how I can help.

**Comment by pnrobinson** [comment]
@mgriese @AGGriese can we discuss this?

**Comment by pnrobinson** [comment]
This is another case where there is a fuzzy boundary between disease and phenotypic feature. There are numerous Mendelian diseases with asthma as a feature, but certainly occupational asthma is a separate disease entity, and extrinsic and intrinsic are categories for the disease. I think it would be best to put the terms that Tiffany is suggesting into the Mondo hierarchy for disease. However, I think that status asthmaticus is a disease feature and is fine as an HPO term. Aspirin induced asthma can be both a feature of a disease course and there are affecteds who mainly only get asthma with aspirin ingestion, so it can be both. Therefore, I think the current HPO hierarchy does not need to be changed. @nicolevasilevsky  -- can we look at this in a future Monarch call.
