### ISSUE TITLE
Add Synonym:  Hyperacusis

### ISSUE THREAD

**Issue by callahantiff** [obophenotype/human-phenotype-ontology#6218]
**HPO term**
Hyperacusis (`HP_0010780`)

**Synonym to be added**
Recruitment 

**broad/exact/narrow/plural/abbreviation ?**  
Broad

**Comment by pnrobinson** [comment]
These terms are not actually synonymous
```
Listeners with hearing loss often struggle to detect low-level sounds, but as the sound intensity rises above threshold, loudness initially grows at a faster than normal rate, but the growth rate slows with increasing intensity so that normal loudness is achieved at high intensities  (Buus  and  Florentine,  2002).  This  phenomenon is referred to as loudness recruitment (Fowler,1937a). However, in some hearing-impaired listeners,loudness continues to grow more rapidly than normal at suprathreshold intensities causing moderately intense sounds to be perceived as louder than normal, a debilitating condition known as hyperacusis or loudness intolerance
```

see https://pubmed.ncbi.nlm.nih.gov/31669363/

I will add the term ``loudness intolerance`` as a new synonym and I think we need a new term for ``Noise-induced loudness recruitment``

**Comment by callahantiff** [comment]
Should I make a NTR for `Noise-induced loudness recruitment`?

**Comment by pnrobinson** [comment]
actually, I think that Noise-induced loudness recruitment is a normal phenomenon (see above definition). There is already a term for Hyperacusis (see above). I have added the above text and PMID to the comment for the latter term. Thanks!
