### ISSUE TITLE
Bilateral tonic-clonic seizure HP:0002069 not necessarily Motor

### ISSUE THREAD

**Issue by DLewisSmith** [obophenotype/human-phenotype-ontology#6227]
**HPO term**
Bilateral tonic-clonic seizure HP:0002069
**Suggested revision and reasons**
Should have single parentage "Seizure HP:0001250" because it cannot be said that all BTCS have a motor onset (see that definition of Motor seizure HP:0020219 we currently use is based on the onset of the seizure, not the presence of a motor feature at any point in the seizure). A BTCS with focal onset HP:0007334 (what the ILAE Classification calls a Focal to bilateral tonic-clonic seizure) may have a non-motor onset (e.g. an epigastric sensation).

**Comment by pnrobinson** [comment]
Thanks, fixed this!
