### ISSUE TITLE
Inconsistencies HPO API (and browser) and genes_to_phenotype.txt for genes 'ABCA4' and 'EBF3'

### ISSUE THREAD

**Issue by tobias2019** [obophenotype/human-phenotype-ontology#6236]
Hi, 

I think I found two inconsistencies in the HPO API (or HPO browser) and the `genes_to_phenotype.txt` and I have some issues about those that I do not understand.

1. Gene `ABCA4`

The gene `ABCA4` is on chromosome 1, but it is associated in `genes_to_phenotype.txt` with `X-linked recessive inheritance`, which does not make sense?

Interestingly, the HPO API as well as the HPO browser (https://hpo.jax.org/app/browse/gene/24) do not show this association. Do you have an additional process to filter specific associations for the API and browser and if so, is there a reason why it is possibly not applied for generating `genes_to_phenotype.txt`?

2. Gene `EBF3`

In the HPO API and the HPO browser, the gene `EBF3` is associated with the term `Ataxia` and not with `Infantile onset`. In contrast, in `genes_to_phenotype.txt`, it is not associated with `Ataxia` but with `Infantile onset`. Is there a reason for this mismatch?

Thanks in advance!

**Comment by drseb** [comment]
I think the ABCA4 issue is already resolved and should be visible in the next release. There were wrong associations in the corresponding disease model.

**Comment by drseb** [comment]
The answer for EBF3 is: the ataxia phenotype is already "covered" by the "Dysmetria" phenotype. Dysmetria is a subclass of Ataxia. This is why we only list 
`253738	EBF3	HP:0001310	Dysmetria	-		-	mim2gene	OMIM:617330
`

**Comment by drseb** [comment]
Thanks again for your feedback and questions. Let me know if there are more problems.

**Comment by tobias2019** [comment]
Thank you for the quick response!

> I think the ABCA4 issue is already resolved and should be visible in the next release. There were wrong associations in the corresponding disease model.

Thanks! One question here: That means the HPO browser already contains the fix right? If so, is there a hint on the website to directly notice that the HPO browser already contains fixes and consequently differ from the released data in `genes_to_phenotype.txt`? 

> The answer for EBF3 is: the ataxia phenotype is already "covered" by the "Dysmetria" phenotype. Dysmetria is a subclass of Ataxia. This is why we only list
> `253738 EBF3 HP:0001310 Dysmetria - - mim2gene OMIM:617330 `

Hm, thanks for the answer, but I do not understand why in this case "Ataxia" is listed explicitly in the associated terms of EBF3 in the HPO browser (https://hpo.jax.org/app/browse/gene/253738), because further super classes of other terms are also not listed explicitly in the associated terms.

**Comment by pnrobinson** [comment]
Diseases are annotated at different levels of specificity, and that is the case here, the disease is annotated to both together with metadata. I will have a closer look at the entry to double check!

**Comment by drseb** [comment]
@tobias2019 as Peter says - there are, in this case, two "overlapping" annotations. This is no problem at all. Some libraries decide to ignore the super-class annotations and only keep the most specific HPO-association. The latter is done when the gene-phenotype-association files are created.

I will check why the other issue - it shouldn't be out of sync between browser and the files
