### ISSUE TITLE
List of contributors out of date

### ISSUE THREAD

**Issue by nlharris** [obophenotype/human-phenotype-ontology#6238]
Contributors list on https://hpo.jax.org/app/help/contributors is out of date

**Comment by nicolevasilevsky** [comment]
I don't have edit access to the HPO website

**Comment by nlharris** [comment]
Neither does @drseb 😀 ! They must keep it closely guarded.

**Comment by drseb** [comment]
In the new setup, unfortunately only @iimpulse can edit.

**Comment by iimpulse** [comment]
Hi folks, editing the individual contributors csv file here https://github.com/monarch-initiative/hpo-web-config, will update that list!! I added nicole with write access to the repo, seb should already have it. Just open a pr and tag me for review and we can merge.

**Comment by nlharris** [comment]
Thanks, @iimpulse. That's the table at the bottom of the page. The out-of-date list I meant is the Core HPO/Monarch Initiative Team list at the top. I can't find that in this repo.

**Comment by iimpulse** [comment]
tracking: https://github.com/TheJacksonLaboratory/hpo-web/issues/139.. thanks @nlharris

**Comment by pnrobinson** [comment]
I will close this here, we will work on this from https://github.com/TheJacksonLaboratory/hpo-web/issues/139
