### ISSUE TITLE
Update terminology for Generalized tonic-clonic seizures on awakening HP:0007193

### ISSUE THREAD

**Issue by DLewisSmith** [obophenotype/human-phenotype-ontology#6246]
**HPO term**
Generalized tonic-clonic seizures on awakening HP:0007193
**Suggested revision of textual definition**
Change preferred name to "Bilateral tonic-clonic seizure on awakening" and keep the current historical name as a more specific synonym.

Change definition to: "Bilateral tonic-clonic seizure of either generalised or focal onset occurring on or soon after wakening (typically within 90 minutes of waking, regardless of the time of day)."

PMID: 26948972, PMID: 24395517

Comments **not** for inclusion in the HPO: This is not a type of seizure, but is believed by at least some clinicians and researchers to be of discriminatory value. The ILAE does not seem to have explicitly defined the period after wakening and 60 minutes and 90 minutes have been used by various authors in recent times. Both Generalized and Focal onset convulsive seizures can occur on awakening, although this is more typical of generalized than focal epilepsies (PMID: 26948972). Thus, it probably better to change the name as above to include both generalized and focal onset forms, which would also make the name consistent with this term's current relationships in the context of modern ILAE terminology (child of "Bilateral tonic-clonic seizure HP:0002069" rather than "Bilateral tonic-clonic seizure with generalized onset HP:0025190"). "Bilateral tonic-clonic seizure with generalized onset HP:0025190" or "Bilateral tonic-clonic seizure with focal onset HP:0007334" can be coded separately if known.

There could reasonably be a child term of "Bilateral tonic-clonic seizure with generalized onset HP:0025190" and "Bilateral tonic-clonic seizure on awakening HP:0007193" that is specifically generalized, as this is what is usually meant when referring to the classical but rare **syndrome** of 'Epilepsy with grand mal on awakening', the validity of which as a discrete syndrome is debated: many now consider this to be part of 'Epilepsy with generalized tonic-clonic seizures alone'. This would be called "Bilateral tonic-clonic seizure of generalized onset on awakening" and defined as "A generalized onset tonic-clonic seizure occurring on or soon after awakening (typically within 90 minutes of waking, regardless of the time of day)."

**Comment by pnrobinson** [comment]
done
