### ISSUE TITLE
NTR: Glomerular Hyalinosis (level 3)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#6258]
Glomerular Hyalinosis (level 3)
parent:Obliterative abnormalities of the renal glomerulus ()
def:Accumulation of amorphous, eosinophilic, glassy, PAS-positive, silver-negative material in the glomerulus. Distribution can include vascular pole, perihilar, tip or neither tip, perihilar or vascular @avizrosenberg @yongqunh

**Comment by avizrosenberg** [comment]
What is outstanding for this entry?

**Comment by pnrobinson** [comment]
Sorry, I forgot to close this, here is the new term
https://hpo.jax.org/app/browse/term/HP:0033216
