### ISSUE TITLE
NTR: Glomerular Hyalinosis Away from the Vascular and Tubular Poles (level 4)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#6261]
Glomerular Hyalinosis Away from the Vascular and Tubular Poles (level 4)
parent:Segmental Hyalinosis ()
def:Accumulation of amorphous, eosinophilic, glassy, PAS-positive, silver-negative material in the glomerulus at neither tip nor perihilar/vascular poles. Both the vascular and the tubular pole are present in the glomerular cross section. @avizrosenberg @yongqunh

**Comment by pnrobinson** [comment]
added but @arosenberg I am not sure about what the suggestion is for "Segmental hyalinosis"? Should this be a new term? It is listed in the "Parent" column but nowhere else.

**Comment by avizrosenberg** [comment]
segmental is to distiguish from global glomerulosclerosis with hyalinosis

**Comment by pnrobinson** [comment]
OK!
I am going to add this term as 
Segmental glomerular hyalinosis away from the vascular and tubular poles 

There is no reason to have an additional term called "Segmental glomerulosclerosis with hyalinosis" unless we have two children. We can always add later if needed.

Please reopen if this is mistaken.
