### ISSUE TITLE
NTR: Thickened basement membrane with hyaline-type subepithelial  deposits (level 7)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#6282]
Thickened basement membrane with hyaline-type subepithelial  deposits (level 7)
parent:Thickened basement membrane with subepithelial deposits (NEW TERM)
def:Prominent GBM reflecting an diffuse and relativly uniform increase in thickness (subjective estimate) with moderately electron-dense, generally homogenous, amorphous-appearing extracellular material located between the outer (epithelial) aspect of the GBM and the visceral epithelial cell, with varying degrees of  incorporation into the GBM @avizrosenberg @yongqunh

**Comment by pnrobinson** [comment]
@avizrosenberg @yongqunh  -- these terms are in effect grand children of the proposed term "Thickened glomerular basement membranes with electron dense deposits" (which we added as 'Glomerular basement membrane electron dense deposits').

However, is it correct to say that "hyaline" is an electron microscopy finding?

**Comment by avizrosenberg** [comment]
hyaline material can be identified on light or EM. its location as subepithelial is a EM finding

**Comment by pnrobinson** [comment]
@avizrosenberg @yongqunh I am adding this term with the following modifications that I hope will increase clarity for non-specialists. If anything is incorrect please reopen this issue.

label: Glomerular hyaline subepithelial deposits
def: A type of glomerular subepithelial deposit characterized by a moderately electron-dense, generally homogenous, amorphous-appearing extracellular material located between the outer (epithelial) aspect of the glomerular basement membrane (GBM) and the visceral epithelial cell, with varying degrees of incorporation into the GBM. This feature is associated with a prominent GBM reflecting an diffuse and relativly uniform increase in thickness (subjective estimate).
