### ISSUE TITLE
NTR: Thickened basement membrane with immunecomplex-type subepithelial deposits (level 7)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#6283]
Thickened basement membrane with immunecomplex-type subepithelial deposits (level 7)
parent:Thickened basement membrane with subepithelial deposits (NEW TERM)
def:Prominent GBM reflecting an diffuse and relativly uniform increase in thickness (subjective estimate) with finely granular material deposited between the outer (epithelial) aspect of the GBM and the visceral epithelial cell, with varying degrees of  incorporation into the GBM and corresponding to immunoglobulin and/or complement by immunofluorescence/immunohistochemistry. @avizrosenberg @yongqunh

**Comment by avizrosenberg** [comment]
What is outstnding here?

**Comment by pnrobinson** [comment]
@avizrosenberg @yongqunh I am adding this term with the following modifications that I hope will increase clarity for non-specialists. If anything is incorrect please reopen this issue.

name: Glomerular subepithelial immune-complex deposits
def:A type of fibrillar glomerular subepithelial deposit characterized by finely granular material deposited between the outer (epithelial) aspect of the glomerular basement membrane (GBM) and the visceral epithelial cell, with varying degrees of incorporation into the GBM and corresponding to immunoglobulin and/or complement by immunofluorescence/immunohistochemistry.  This feature is associated with a prominent GBM reflecting an diffuse and relativly uniform increase in thickness (subjective estimate).

**Comment by avizrosenberg** [comment]
looks good
