### ISSUE TITLE
NTR: Thickened basement membrane with fibrilar subepithelial deposits (level 7)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#6284]
Thickened basement membrane with fibrilar subepithelial deposits (level 7)
parent:Thickened basement membrane with subepithelial deposits (NEW TERM)
def:Prominent GBM reflecting an diffuse and relativly uniform increase in thickness (subjective estimate) with fibrillar deposits located between the outer (epithelial) aspect of the GBM and the visceral epithelial cell, with varying degrees of  incorporation into the GBM @avizrosenberg @yongqunh

**Comment by pnrobinson** [comment]
@avizrosenberg @yongqunh  I am adding this term with the following modifications that I hope will increase clarity for non-specialists. If anything is incorrect please reopen this issue.

label:Fibrillar glomerular subepithelial deposits
def:Fibrillar deposits located between the outer (epithelial) aspect of the glomerular basement membrane (GBM) and the visceral epithelial cell, with varying degrees of incorporation into the GBM. This feature is associated with a prominent GBM reflecting an diffuse and relativly uniform increase in thickness (subjective estimate).

**Comment by avizrosenberg** [comment]
small modification:

Fibrillar deposits located between the outer (epithelial) aspect of the glomerular basement membrane (GBM) and the visceral epithelial cell, with varying degrees of incorporation into the GBM. This feature is associated with a prominent GBM reflecting a diffuse and relatively uniform increase in thickness (subjective estimate).
