### ISSUE TITLE
NTR: Thickened basement membrane with fibrillary subepithelial deposits  (level 8)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#6285]
Thickened basement membrane with fibrillary subepithelial deposits  (level 8)
parent:Thickened basement membrane with fibrilar subepithelial deposits (NEW TERM)
def:Prominent GBM reflecting an diffuse and relativly uniform increase in thickness (subjective estimate) with extracellular aggregates of randomly arranged, straight, non-branching fibrils that are thicker than amyloid fibrils (average diameter ~20 nm) and are often admixed with smudgy, electron-dense material @avizrosenberg @yongqunh

**Comment by pnrobinson** [comment]
@avizrosenberg @yongqunh I am adding this term with the following modifications that I hope will increase clarity for non-specialists. If anything is incorrect please reopen this issue.

name: Fibrillary glomerular subepithelial deposits
def: A type of fibrillar glomerular subepithelial deposit characterized by extracellular aggregates of randomly arranged, straight, non-branching fibrils that are thicker than amyloid fibrils (average diameter about 20 nm) and are often admixed with smudgy, electron-dense material. This feature is associated with a prominent glomerular basement membrane (GBM) reflecting an diffuse and relativly uniform increase in thickness (subjective estimate).

**Comment by avizrosenberg** [comment]
Looks good

**Comment by yongqunh** [comment]
Looks good to me as well.
