### ISSUE TITLE
NTR: Thickened basement membrane with subepithelial deposits consistent with amyloid (level 8)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#6286]
Thickened basement membrane with subepithelial deposits consistent with amyloid (level 8)
parent:Thickened basement membrane with fibrilar subepithelial deposits (NEW TERM)
def:Prominent GBM reflecting an diffuse and relativly uniform increase in thickness (subjective estimate) with extracellular aggregates composed of fine, randomly oriented, non-branching fibrils 8 - 12 nm in diameter, often forming a cottony mass @avizrosenberg @yongqunh

**Comment by pnrobinson** [comment]
@avizrosenberg @yongqunh I am adding this term with the following modifications that I hope will increase clarity for non-specialists. If anything is incorrect please reopen this issue.

Label:Glomerular amyloid subepithelial deposits
def:A type of fibrillar glomerular subepithelial deposit characterized by extracellular aggregates composed of fine, randomly oriented, non-branching fibrils 8-12 nm in diameter, often forming a cottony mass. This feature is associated with a prominent glomerular basement membrane (GBM) reflecting an diffuse and relativly uniform increase in thickness (subjective estimate).

**Comment by avizrosenberg** [comment]
I think this is fine
