### ISSUE TITLE
NTR: Glomerular capillary wire loop deposits (level 7)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#6288]
Glomerular capillary wire loop deposits (level 7)
parent:Subendothelial deposits (NEW TERM)
def:Large subendothelial immune deposit identifiable by light microscopy @avizrosenberg @yongqunh

**Comment by avizrosenberg** [comment]
Is anything outstanding for this term?

**Comment by pnrobinson** [comment]
added
