### ISSUE TITLE
NTR: Glomerular Basement Membranes Wrinkling (level 3)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#6297]
Glomerular Basement Membranes Wrinkling (level 3)
parent:Abnormalities of the glomerular basement membrane ()
def:Wrinkling and folding of the GBM without glomerular epithelial cell hypertrophy and hyperplasia (formerly known an ischemic type of collapse). The urinary space is patent. The wrinkling is generally made by small regular infoldings of the GBM. @avizrosenberg @yongqunh

**Comment by pnrobinson** [comment]
@avizrosenberg @yongqunh

I added this term, but the definition is different from the consensus definition
"Irregular folding with an intact lamina densa"  (https://pubmed.ncbi.nlm.nih.gov/32866505/).

Is this the same item is this just a different definition?

**Comment by pnrobinson** [comment]
@avizrosenberg @yongqunh Please check the definition -- it differs from the consensus definition above, but is it OK?
https://hpo.jax.org/app/browse/term/HP:0033289

**Comment by avizrosenberg** [comment]
To avoid conflicts with pathology committee i think we need to commit to consensus definition as submitted.

**Comment by pnrobinson** [comment]
@avizrosenberg  Not sure I understand, but I think you are suggesting the following. Please reopen if I am mistaken

Def: Irregular folding with an intact lamina densa
Comment: Wrinkling and folding of the GBM without glomerular epithelial cell hypertrophy and hyperplasia (formerly known an ischemic type of collapse). The urinary space is patent. The wrinkling is generally made by small regular infoldings of the GBM.
