### ISSUE TITLE
NTR: Deflation of the glomerular tuft  (level 3)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#6301]
Deflation of the glomerular tuft  (level 3)
parent:Abnormalities of the glomerular capillary lumina ()
def:Wrinkling and folding of the GBM without glomerular epithelial cell hypertrophy and hyperplasia (formerly known an ischemic type of collapse). The urinary space is patent. The wrinkling is generally made by small regular infoldings of the GBM. @avizrosenberg @yongqunh

**Comment by pnrobinson** [comment]
added

**Comment by pnrobinson** [comment]
Actually, the definition seems to be a copy paste error (it is the same as the definition for Wrinkling)
Deflation of the capillary tuft is shown here (Fig 5A): https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4764351/

I will use this definition from NEPTUNE -- I am guesssing the "Segmental deflation" is a synonym? @avizrosenberg @yongqunh

Segmental deflation: wrinkling and folding of the capillaries without epithelial cell (podocyte) hyperplasia (formerly called ischemic type of collapse) involving o 80% of the glomerular tuft. The wrinkling is generally made by small regular folds of the GBM

I will leave this open to allow comments, please shout if the definition above is incorrect.

**Comment by avizrosenberg** [comment]
yes this seems correct, apologies for the error

**Comment by yongqunh** [comment]
Looks good. Thanks!
