### ISSUE TITLE
NTR: Glomerular fibrinoid necrosis (level 3)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#6313]
Glomerular fibrinoid necrosis (level 3)
parent:Abnormalities of the glomerular capillary lumina ()
def:Fibrin associated with GBM disruption and/or lysis of the mesangial matrix @avizrosenberg @yongqunh

**Comment by pnrobinson** [comment]
Making this a child of Abnormal glomerular capillary morphology
Please reopen if that is a mistake, but it seems to make more sense. @avizrosenberg @yongqunh

**Comment by pnrobinson** [comment]
I enhanced the definition to provide more context according to (https://pubmed.ncbi.nlm.nih.gov/29459092/), which is cited also in (https://www.kidney-international.org/article/S0085-2538(20)30965-0/fulltext).

Fibrin associated with glomerular basement membrane with disruption and/or lysis of the mesangial matrix; this lesion does not require the presence of karyorrhexis.

Please reopen if this was a mistake.@avizrosenberg @yongqunh

**Comment by pnrobinson** [comment]
@avizrosenberg @yongqunh 
I think this is OK, but please check that this term is what you wanted
https://hpo.jax.org/app/browse/term/HP:0033277
I will close this, but please reopen this issue if there is a problem.

**Comment by avizrosenberg** [comment]
Just small correction: 

Fibrin associated with glomerular basement membrane  disruption and/or lysis of the mesangial matrix; this lesion does not require the presence of karyorrhexis.
