### ISSUE TITLE
NTR: Nodular mesangiosclerosis (level 4)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#6325]
Nodular mesangiosclerosis (level 4)
parent:Abnormalities of the glomerular mesangial matrix ()
def:Lobular, round to oval mesangial lesions with an acellular hyaline/matrix core surrounded by compressed mesangial nuclei @avizrosenberg @yongqunh

**Comment by pnrobinson** [comment]
@avizrosenberg @yongqunh

Mesangiolysis with nodular glomerulosclerosis 
Paramesangial  GBM detachments from the mesangium resulting in capillary  microaneurysms, with a marked increase in mesangial matrix

from https://pubmed.ncbi.nlm.nih.gov/32866505/  ?

If so, should we use Mesangiolysis with nodular glomerulosclerosis  as the preferred label and Nodular mesangiosclerosis as a synonym?

**Comment by avizrosenberg** [comment]
nodular mesangiosclerosis is a pattern that may be independent of over mesangolysis. So while they are frequently related and observed together probably should not be clumped in the consensus definition

**Comment by pnrobinson** [comment]
added

**Comment by pnrobinson** [comment]
PS< I have added this comment, please reopen if not correct

Nodular mesangiosclerosis is a pattern that can be observed together with mesangolysis but may also occur independently and so should be coded separately.
