### ISSUE TITLE
NTR: Mesangial fibril deposition (level 3)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#6330]
Mesangial fibril deposition (level 3)
parent:Abnormalities of the glomerular mesangium  ()
def: @avizrosenberg @yongqunh

**Comment by pnrobinson** [comment]
what is the difference to Mesangial fibrillary deposits  (https://github.com/obophenotype/human-phenotype-ontology/issues/6332).

@avizrosenberg @yongqunh
Should this be defined using part of the consensus statement
Mesangial matrix fibrils = Unbranched curvilinear microfibrils within the mesangial matrix that may be bundled with parallel alignment; the background matrix should not contain immune deposits, and other fibril types may need to be ruled out by correlation with light microscopy and immunofluorescence/ immunohistochemistry (https://pubmed.ncbi.nlm.nih.gov/32866505/).

**Comment by pnrobinson** [comment]
@avizrosenberg looking again at the consensus, I see that this is a very reasonable superclass for a number of related terms with fibers etc. I am adding with the definition

Extracellular mesangial accumulation of slender proteinaceous fibers.

**Comment by avizrosenberg** [comment]
Agreed that this is a superclass

**Comment by yongqunh** [comment]
Agree as well.
