### ISSUE TITLE
NTR: Mesangial microfibril deposition (level 4)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#6331]
Mesangial microfibril deposition (level 4)
parent:Mesangial fibril deposition ()
def:unbranched noncollagenous microfibrils within the mesangial matrix, composed of proteins not present within the GBM, most notably fibrillin-1,that attach to mesangial cells and GBM structuralproteins @avizrosenberg @yongqunh

**Comment by pnrobinson** [comment]
@avizrosenberg @yongqunh  What is the difference between fibril and microfibril in this context?

**Comment by yongqunh** [comment]
I found these:
https://en.wikipedia.org/wiki/Microfibril
so: "A microfibril is a very fine fibril, or fiber-like strand, consisting of glycoproteins and cellulose."  
https://en.wikipedia.org/wiki/Fibril

**Comment by pnrobinson** [comment]
@yongqunh  my question is more whether there really are two distinct phenotypic abnormalities with (1) 'regular' fibrils and (2) 'really small' fibrils -- and if so whether we can get a PMID about what that difference is so that users will know which HPO term to choose.

**Comment by avizrosenberg** [comment]
I don’t believe we will make a distinction between these two entities

**Comment by yongqunh** [comment]
Check the reference: https://www.kidney-international.org/article/S0085-2538(15)32169-4/pdf 
Copied from the reference: 
"Among the various formed elements of the extracellular connective tissue, microfibrils represent a recent addition to the classical structures of the light microscopists, such as collagen, reticulum and elastic fibers, and basement membranes. In contrast to the rather thick (up to 100 nm) unit of collagen fibrils with conspicuous axial periodicity, structures classified as microfibrils by electron microscopists are thin aperiodic fibrils of less than 20 nm in diameter. They are quite ubiquitous [1] and are found in association with all the elements mentioned above. Recent studies have brought out the existence of three types of microfibrils [2]: large, 18 to 20 nm in diameter, which are susceptible to collagenase digestion and are believed to be precursors of unit collagen fibers; small, about 10 nm in diameter, first described as a component of the elastic tissue; and "thin filaments," 3 to 5 nm, which may be related to basement membranes. It is now realized that "small microfibrils" occur also independently of elastin and are found in a variety of tissues, including the renal glomerulus. They have a characteristic tubular structure and differ in chemical composition from collagen and from elastin but are similar in some respects to the basement membrane. "
So there appears to be some distinction.

**Comment by avizrosenberg** [comment]
I can bring this to pathology cmmt to see if any would include this distinction I don’t use it clinically or otherwise

**Comment by avizrosenberg** [comment]
Fibrils are  a parent class, microfibrils are a subclass

**Comment by pnrobinson** [comment]
added
