### ISSUE TITLE
NTR: Mesangial fibrillary deposits (level 4)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#6332]
Mesangial fibrillary deposits (level 4)
parent:Mesangial fibril deposition ()
def:extracellular mesangial aggregates composed of randomly arranged, straight, non-branching fibrils that are thicker than amyloid fibrils (average diameter ~20 nm) and are often admixed with smudgy, electron-dense material @avizrosenberg @yongqunh

**Comment by avizrosenberg** [comment]
What is outstanding for this entry?

**Comment by pnrobinson** [comment]
added
