### ISSUE TITLE
NTR: Mesangial immunotactoid deposits (level 4)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#6333]
Mesangial immunotactoid deposits (level 4)
parent:Mesangial fibril deposition ()
def:extracellular mesangial aggregates composed of non-branching fibrils, focally parralel >30 nM in diameter @avizrosenberg @yongqunh

**Comment by avizrosenberg** [comment]
what is concern with this entry?

**Comment by pnrobinson** [comment]
Extending the definition as follows

Extracellular mesangial aggregates composed of non-branching fibrils, focally parralel over 30 nM in diameter. The term immunotactoid refers to highly organized immune depositions appearing as rod-like microtubular structures in ultrastructural examination.

please reopen if that is not correct
