### ISSUE TITLE
NTR: Mesangial amyloid deposition (level 4)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#6334]
Mesangial amyloid deposition (level 4)
parent:Mesangial fibril deposition ()
def:extracellular mesangial aggregates composed of fine, randomly oriented, non-branching fibrils 8 - 12 nm in diameter, often forming a cottony mass (D'Agati et al Atlas) @avizrosenberg @yongqunh

**Comment by avizrosenberg** [comment]
What is the concern for this entry?

**Comment by pnrobinson** [comment]
added
