### ISSUE TITLE
NTR: Podocyte cytoskeletal consolidation (level 4)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#6340]
Podocyte cytoskeletal consolidation (level 4)
parent:Abnormalities of the visceral epithelial cells ()
def:Reorganization of podocyte cytoskeletal proteins at the GBM aspect of the cell, with associated cytoplasmic electron- density at the GBM aspect of the Podocyte (Barisoni et al, MH) @avizrosenberg @yongqunh

**Comment by pnrobinson** [comment]
@avizrosenberg @yongqunh
Can you provide the PMID of the Barisoni reference?
I have looked at a few articles but cannot find anything about cytoskeletal consolidation
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3118840/

**Comment by yongqunh** [comment]
@avizrosenberg 
Is the Barisoni reference from Laura Barisoni? 
https://medicine.duke.edu/faculty/laura-barisoni-md
We may ask her.

**Comment by avizrosenberg** [comment]
It’s front the em paper from Neptune will share PMID

**Comment by pnrobinson** [comment]
I found it here (https://pubmed.ncbi.nlm.nih.gov/27102348/). The paper uses the word "Condensation" instead of "Consolidation" -- I will make that change and add the term, please reopen if needed
