### ISSUE TITLE
NTR: Binucleated visceral epithelial cells (level 4)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#6346]
Binucleated visceral epithelial cells (level 4)
parent:Abnormalities of the visceral epithelial cells ()
def:Visceral epithelial cells with 2 nuclei. Can be observed on light or ultrastructral microscopy. @avizrosenberg @yongqunh

**Comment by pnrobinson** [comment]
Should we distinguish between binucleation and multinucleation?
as described here
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3814687/
@avizrosenberg @yongqunh

**Comment by yongqunh** [comment]
It appears good to distinguish. As seen in the PMC3814687 paper, these two terms are seperately mentioned.

**Comment by pnrobinson** [comment]
OK, I am making the term and will define it as
Visceral epithelial cells with more than two nuclei. Can be observed on light or ultrastructral microscopy.

Please reopen if this is wrong.@avizrosenberg @yongqunh
