### ISSUE TITLE
Depreciate Psychic auras HP:0011162 to synonym of Focal cognitive seizure HP:0032680

### ISSUE THREAD

**Issue by DLewisSmith** [obophenotype/human-phenotype-ontology#6375]
**HPO term**
Psychic auras HP:0011162
**Reason for deprecation**
Old term, now redundant. Should be a synonym of Focal cognitive seizure HP:0032680
**Suggested replacement or term to consider**
Focal cognitive seizure HP:0032680

**Comment by pnrobinson** [comment]
merged

**Comment by DLewisSmith** [comment]
@pnrobinson sorry this suggestion predates and is superseded by the suggestions on the spreadsheet we discussed that more accurately harmonises concepts from two classifications (I will re-send spreadsheet today). It is **not** an exact synonym of "Focal cognitive seizure" HP:0032680 and should have no synonym.


PMID: 30782582

-1x parent:
"Epileptic aura" (new HP required, previously HP:0011157)
- children:
"Experiential epileptic aura" HP:0012002
"Affective epileptic aura" HP:0012003
"Cognitive epileptic aura" new term
