### ISSUE TITLE
Focal autonomic seizure HP:0011154

### ISSUE THREAD

**Issue by DLewisSmith** [obophenotype/human-phenotype-ontology#6376]
**HPO term**
Focal autonomic seizure HP:0011154
**Suggested revision of textual definition**
Definition is fine. Please alter the comment to: "Focal seizures with a subjective or objectively documented alteration of autonomic nervous system function at onset, involving but not limited to, cardiovascular, pupillary, gastrointestinal, sudomotor, vasomotor and thermoregulatory functions."

**Comment by pnrobinson** [comment]
thanks, revised!
