### ISSUE TITLE
Vegetative auras HP:0011164 to become synonym of Focal autonomic seizure HP:0011154

### ISSUE THREAD

**Issue by DLewisSmith** [obophenotype/human-phenotype-ontology#6377]
**HPO term**
Vegetative auras HP:0011164
**Reason for deprecation**
This historical term should not be considered a sensory seizure in the new ILAE classification but instead should be a synonym of Focal autonomic seizure HP:0011154 which is separate to Focal sensory seizures.

**Suggested replacement or term to consider**
Focal autonomic seizure HP:0011154

**Comment by pnrobinson** [comment]
Currently no disease annotations.

**Comment by pnrobinson** [comment]
merged

**Comment by DLewisSmith** [comment]
@pnrobinson sorry this suggestion predates and is superseded by the suggestions on the spreadsheet we discussed that more accurately harmonises concepts from two classifications (I will re-send spreadsheet today). It is not an exact synonym of "Focal autonomic seizure" HP:0011154 because it only pertains to subjective experiences (the latter pertains to both subjective and objective).

It should be merged with "Autonomic epileptic aura" HP:0011164

PMID: 30782582

-2x parents:
"Epileptic aura" (new HP required, previously HP:0011157)
"Focal autonomic seizure" HP:0011154
- No children
