### ISSUE TITLE
Hippocampal atrophy HP:0410170

### ISSUE THREAD

**Issue by DLewisSmith** [obophenotype/human-phenotype-ontology#6381]
**HPO term**
Hippocampal atrophy HP:0410170

**Suggested revision and reasons**

Provide the following as a second parent to "Hippocampal atrophy HP:0410170" as the hippocampus is part of the temporal cortex (albeit allocortex rather than neocortex): "Temporal cortical atrophy HP:0007112"

**Comment by pnrobinson** [comment]
done, thanks!
