### ISSUE TITLE
Missing Gene-Disease association for six2

### ISSUE THREAD

**Issue by b8hale** [obophenotype/human-phenotype-ontology#6441]
**HPO term**
ORPHA:488437 Six2-related Frontonasal Dysplasia

**Bug description**
The disease is not associated with the six2-gene. Orphanet has the association between the two. 
![HPO six2-related frontonasal dysplasia](https://user-images.githubusercontent.com/42538679/98211007-b9794580-1f41-11eb-995e-55342a69ee08.png)

**Comment by pnrobinson** [comment]
@iimpulse This link is missing, let's investigate
https://hpo.jax.org/app/browse/disease/ORPHA:488437

**Comment by pnrobinson** [comment]
This is the original paper
https://pubmed.ncbi.nlm.nih.gov/26581443/
it is not in OMIM, but it is listed in ORPHANET (correctly, I think, although I am not sure if there is a second case report)
We are not picking up the SIX2 gene
https://hpo.jax.org/app/browse/disease/ORPHA:488437

**Comment by pnrobinson** [comment]
I am moving this to the HPO Web tracker.
