### ISSUE TITLE
Decreased LDL cholesterol concentration HP:0003563 logical definition

### ISSUE THREAD

**Issue by anna-anagnostop** [obophenotype/human-phenotype-ontology#6447]
**HPO term**
Decreased LDL cholesterol concentration HP:0003563

**Suggested revision of logical definition**

EQ currently uses:
has part some (decreased amount and (inheres in some (low-density lipoprotein and (part of some blood))) and (has modifier some abnormal)) 

EQ should be using low-density lipoprotein cholesterol  (CHEBI:47774)

Thanks, 

Anna

**Comment by pnrobinson** [comment]
Agree, thanks.

**Comment by pnrobinson** [comment]
updated, thanks again
