### ISSUE TITLE
Protein deficiency

### ISSUE THREAD

**Issue by johannaest** [obophenotype/human-phenotype-ontology#6449]
**HPO term**
Hypoproteinemia

**Synonym to be added**
Protein deficiency

**broad/exact/narrow/plural/abbreviation ?**
broad

**Comment by pnrobinson** [comment]
@johannaest  I do not think this is even a broad synonym. Protein deficiency is generally taken to mean that there is insufficient protein intake in the diet. Hypoproteinemia can be a sign of severe protein deficiency (kwashiorkor), but this does not make it a synonym.
If there is a use case that cannot be satisfied, please reopen this issue with more details.
