### ISSUE TITLE
An new term in Autoimmune antibody positivity 

### ISSUE THREAD

**Issue by MaudDLVT** [obophenotype/human-phenotype-ontology#6458]
**anti-aquaporin-4 antibody positivity**

**anti-AQP4 antibody positivity**

**NMOSD-IgG binding to AQP4, induces astrocyte injury and Blood Brain Barrier (BBB) breakdown causing NMOSD clinical symptoms, PMID: 24260168, PMID: 25889963, PMID: 24415568**

**HP:0030057**

**neuromyelitis optica spectrum disorders
(NMOSD)**

**0000-0002-3387-1836**

**Comment by pnrobinson** [comment]
added, thanks for the suggestion
