### ISSUE TITLE
Add comment, disease: Milky BAL HP:0033173

### ISSUE THREAD

**Issue by GrieseAG** [obophenotype/human-phenotype-ontology#6459]
**HPO term**
Milky appearance of bronchoalveolar lavage fluid HP:0033173

**Suggested revision of textual definition**
Return of lavage fluid characteristically has a milky apperance in pulmonary alveolar proteinosis (PAP). This is due to the accumulation of a mixture of pulmonary surfactant, which is a lipoprotein complex, in the alveolar space.

PMID: 28771412

**Diseases characterized by this term ? (e.g. Orphanet or OMIM number)**
PAP: 
ORPHA:747   (Disorder)   Autoimmune pulmonary alveolar proteinosis
ORPHA:264675   (Disorder)   Hereditary pulmonary alveolar proteinosis
ORPHA:572428   (Disorder)   Infantile-onset pulmonary alveolar proteinosis-hypogammaglobulinemia
ORPHA:420259   (Disorder)   Secondary pulmonary alveolar proteinosis
ORPHA:440427   (Disorder)   Severe early-onset pulmonary alveolar proteinosis due to MARS deficiency

**Your nano-attribution**
LMU chrapp; @katrinknoflach, @mgriese

**Comment by pnrobinson** [comment]
Slight revision

def: Return of lavage fluid with a milky apperance due to the accumulation of a mixture of pulmonary surfactant, which is a lipoprotein complex, in the alveolar space.
comment: This feature is characteristically observed in pulmonary alveolar proteinosis.

**Comment by pnrobinson** [comment]
Diseases
-  Surfactant metabolism dysfunction, pulmonary, 4 | 300770
- Surfactant metabolism dysfunction, pulmonary, 5 | 614370
 - Interstitial lung and liver disease | 615486

**Comment by pnrobinson** [comment]
done
