### ISSUE TITLE
Pulmo, add Siderophages to HP:0032979

### ISSUE THREAD

**Issue by GrieseAG** [obophenotype/human-phenotype-ontology#6460]
**HPO term**
Hemosiderin-laden macrophages in bronchoalveolar fluid HP:0032979

**Synonym to be added**
siderophages in the bronchoalveolar fluid
(siderophages are hemosiderin-containing macrophages)

•	PMID: 25515792
•	PMID: 16871595

**broad/exact/narrow/plural/abbreviation ?**

**Your nano-attribution (ORCID)**
LMU chrapp; @katrinknoflach, @mgriese

**Comment by pnrobinson** [comment]
added
