### ISSUE TITLE
New HPO terms for Bleeding, Platelet and Thrombosis disorder - BPD

### ISSUE THREAD

**Issue by ssivam** [obophenotype/human-phenotype-ontology#647]
We have generated a new list of HPO codes we found to be missing when trying to code all known Bleeding, Platelet and Thrombosis disorders. This list was verified by a team of experts in the field including Dr. Gomez, Prof. Freson and Prof. Ouwehand. Regards, Dr. Sivapalaratnam, Clinical research fellow at the University of Cambridge, department of Haematology.

[SET_Bridge_new_HPO_terms_110116.xlsx](https://github.com/obophenotype/human-phenotype-ontology/files/86067/SET_Bridge_new_HPO_terms_110116.xlsx)

**Comment by drseb** [comment]
Great. Thanks. Will work on this with @pnrobinson

**Comment by lcdaugherty** [comment]
#647 On behalf of the team, thank you for adding new terms relating to Bleeding, Platelet and Thrombosis disorders.

However, although the above classes were added by you I can’t find them
 > Invalid HPO id input
eg: Abnormality of fibrinolysis  http://compbio.charite.de/hpoweb/showterm?id=HP:0040224

Can you tell me how long we need to wait until these 28 terms are made public?

One of the tools we use to code our samples is updating this weekend (and hence the version of HPO), so it would be useful if this these terms could be made public as soon as possible.

Also, the proposed term Increased plasma vitamin K epoxide after vitamin K supplementation, seems to be missing, was there a reason why this was excluded?

Apologies if I have missed something from the HPO submission process please let me know if you require any more info from us before these terms can be made public.
