### ISSUE TITLE
Rename aura terms

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#6474]
Make singular and "aura" explicit

HP:0012006 | Jamais vu | Jamais-vu aura |  
HP:0012005 | Déjà vu | Déjà-vu aura |  
HP:0011162 | Psychic auras | Psychic aura |  
HP:0012002 | Experiential auras | Experiential aura |  

Suggestion of @DLewisSmith

**Comment by pnrobinson** [comment]
done

**Comment by DLewisSmith** [comment]
@pnrobinson, did we decide to make the "epileptic" explicit in all these seizure auras to avoid confusion with migrainous auras?

**Comment by pnrobinson** [comment]
I think so, I will make that the preferred label!
