### ISSUE TITLE
Subdural haematoma

### ISSUE THREAD

**Issue by LM-Ontologies** [obophenotype/human-phenotype-ontology#6489]
**HPO term**
The synonym Subdural haematoma under the parent Subdural hemorrhage https://hpo.jax.org/app/browse/term/HP:0100309

**Suggested revision and reasons**
Suggestion to add 'Subdural haematoma' as a unique term

**Preferred Term** 
Subdural haematoma

**Definition** 
Blood, which has more or less clotted and usually associated with a traumatic brain injury—collects or gathers between the inner layer of the dura mater and the arachnoid mater of the meninges surrounding the brain. 

**Distinction with Subdural hemorrhage**
Distinction with subdural hemorrhage where bleeding associated with a traumatic brain injury between the inner layer of the dura mater and the arachnoid mater of the meninges surrounding the brain is active and ongoing.

**Parent Term** 
https://hpo.jax.org/app/browse/term/HP:0100659

**Comment by pnrobinson** [comment]
I think that according to etymology, hemorrhage and hematoma seem to havee different meanings, with hemorrhage sounding like active bleeding and hematoma sounding like the result of bleeding (clotted blood). However, in clinical usage, these phrases are considered to be synonyms -- see for instance

https://www.health.harvard.edu/a_to_z/subdural-hematoma-a-to-z
https://my.clevelandclinic.org/health/diseases/21183-subdural-hematoma
("Other names for subdural hematoma are subdural hemorrhage or intracranial hematoma.")

Do we want to find a term that denotes "active" subdural bleeding? Could you describe the use case a bit?

**Comment by pnrobinson** [comment]
closing for now.
