### ISSUE TITLE
Livedo reticularis

### ISSUE THREAD

**Issue by LM-Ontologies** [obophenotype/human-phenotype-ontology#6490]
**HPO term**
The synonym Livedo reticularis under the parent Cutis marmorata https://hpo.jax.org/app/browse/term/HP:0000965

**Suggested revision and reasons**
Suggestion to add 'Livedo reticularis' as a unique term

**Preferred Term** 
Livedo reticularis

**Definition** 
Livedo reticularis is characterized by the presence of a bluish purple, mottled or netlike pattern in unbroken circles on the skin. Exposure to cold environments usually intensifies the vascular pattern. Presumably, the condition results from slow or stagnant blood flow, vessel-wall pathology, and decreased oxygen tension.

**Distinction with Cutis marmorata**
 In contrast to cutis marmorata, the mottling does not resolve when the skin is warmed, and the discoloration is bluish purple rather than red. The Livedo reticularis lesion is more intense and is persistent. 

**Parent Term** 
https://hpo.jax.org/app/browse/term/HP:0011276

**Comment by pnrobinson** [comment]
Thanks for pointing this out, I have added Livedo reticularis as a separate term as you suggest!
