### ISSUE TITLE
anti-carbonic anhydrase II

### ISSUE THREAD

**Issue by MaudDLVT** [obophenotype/human-phenotype-ontology#6501]
**anti-carbonic anhydrase II antibody positivity**

**CA-II antibody**

**https://doi.org/10.1007/s00535-006-1862-6**

**HP:0030057**

**Autoimmune pancreatitis (AIP)**

**0000-0002-3387-1836**

**Comment by pnrobinson** [comment]
thanks, added term, it will be visible with the next release in February.
