### ISSUE TITLE
Propionicacidemia should be Propionic acidemia ?

### ISSUE THREAD

**Issue by kanems** [obophenotype/human-phenotype-ontology#6506]
**HPO term**
HP:0003571
Propionicacidemia

**Bug description**

Per UMLS (C0268579) and MONDO (MONDO:0011628), this should be written as "Propionic acidemia."

**Comment by pnrobinson** [comment]
thanks for pointing this out, I fixed the error.

**Comment by kanems** [comment]
Hi @pnrobinson, just following up on this that this HPO page is still displaying the typo: https://hpo.jax.org/app/browse/term/HP:0003571

**Comment by pnrobinson** [comment]
We update the website about every two months -- it should be visible after the first week of February! @iimpulse
