### ISSUE TITLE
Anterior open bite concept?

### ISSUE THREAD

**Issue by kanems** [obophenotype/human-phenotype-ontology#6509]
I am wondering if there is a need for two separate terms for the concept of "anterior open-bite?" 
I see 
HP:0200095 "anterior open bite" 
and
 HP:0009102 "Anterior open-bite malocclusion" which lists "Anterior openbite" as a synonym. 

UMLS has opted to put these two HPO terms on one CUI: C0266060 “anterior open bite.”

**Comment by pnrobinson** [comment]
Just looked at this, and it appears to be a mistake, we will merge these two terms. Thanks for pointing this out.

**Comment by pnrobinson** [comment]
I have merged the two terms. The valid id is now HP:0009102, the preferred label is Anterior open-bite malocclusion", with the others being synonyms.
thanks
