### ISSUE TITLE
UMLS CUI reference on Micropenis HP:0000054

### ISSUE THREAD

**Issue by kanems** [obophenotype/human-phenotype-ontology#6510]
**HPO term**
Micropenis HP:0000054

**Bug description**

Looks like the wrong UMLS CUI is mapped to Micropenis HP:0000054. UMLS CUI si currently listed as C0266435 ("hypoplassia of penis" is the UMLS concept name) but it probably should be C4551492 ("micropenis").

**Comment by pnrobinson** [comment]
fixed
