### ISSUE TITLE
UMLS/SNOMED x-refs on Microcephaly

### ISSUE THREAD

**Issue by kanems** [obophenotype/human-phenotype-ontology#6511]
**HPO term**
Microcephaly HP:0000252

**Bug description**

UMLS X-ref may be incorrect... The SNOMED_CT and UMLS terms both point to "decreased head circumference" which are already linked to the parent concept (HP:0040195) . Suggest using the  X-ref to UMLS C4551563,

**Comment by pnrobinson** [comment]
fixed, thanks
