### ISSUE TITLE
UMLS X-ref on Oxycephaly, HP:0000263 

### ISSUE THREAD

**Issue by kanems** [obophenotype/human-phenotype-ontology#6512]
**HPO term**
Oxycephaly 
HP:0000263 

**Bug description**

Cross-references on this HPO term are currently pointing to C0030044 "turricephaly" (which includes oxycephaly as synonyms from other sources, which is sort of muddying the waters here), but UMLS C0030044 has a child term "Oxycephaly" C4551646, which may be a better X-ref for HP:0000263.

**Comment by msincan** [comment]
according to https://elementsofmorphology.nih.gov/index.cgi?tid=b1c6362251bad427, turricephaly and oxycephaly are not exact synonyms.

**Comment by kanems** [comment]
Thank you, @msincan ! I plan to follow up with UMLS regarding their mixing of "oxycephaly" and "turricephaly" on C0030044, so I will provide this as additional evidence for cleaning up that term. (Also, Hi!!)

**Comment by pnrobinson** [comment]
Happy new year and thanks for pointing this out! I have removed C0030044 from Oxycephaly; the same cross ref is used for HPO Turricephaly which is more precise as you point out.
