### ISSUE TITLE
Multiple UMLS X-ref errors

### ISSUE THREAD

**Issue by kanems** [obophenotype/human-phenotype-ontology#6513]
I am working to resolve discrepancies in the UMLS CUI/HPO mappings in the NIH MedGen/GTR database and I have found several examples where HPO seems to be citing incorrect UMLS CUIs and SNOMEDCT IDs as cross references. I am attaching an excel file with examples, but can say it is almost certainly not an exhaustive list. 

How are the Cross references on HPO terms determined? Does HPO compute these, or is it based on how UMLS has mapped/placed HPO concepts within their CUIs? How does HPO respond to/deal with UMLS mapping multiple HPO terms to a single UMLS CUI? (Or is this not problematic for your dataflow?)

[Dec2020_HPO_UMLSCrossRefs.xlsx](https://github.com/obophenotype/human-phenotype-ontology/files/5726429/Dec2020_HPO_UMLSCrossRefs.xlsx)

**Comment by pnrobinson** [comment]
@kanems  we would like to defer to your mapping, and I think all of the existing mappings in our file are legacy.
One request would be to help us with providing instructions to our users of how to get the mapping from UMLS. It would be great if we could provide users with a script that would generate the current mapping, but I am not aware of how to do this. Would this be possible? @drseb @matentzn thoughts?
In the meantime, I will remove these old legacy xrefs.

**Comment by pnrobinson** [comment]
These are the issues:

- [ ] HP:0000446 | Narrow Nasal Bridge | Multiple UMLS CUIs listed, but none that match the Preferred name, where UMLS maps this term. | Add C4551564 to UMLS Cross-refs. 
- [ ]  HP:0000480 | Retinal coloboma | Maps to UMLS C0240896 (chorioretinal coloboma) | Update UMLS Xref to C3540764 
- [ ]  HP:0000510 | Rod-cone dystrophy | Cites SNOMEDCT_US:28835009, but this map to "Retinitis pigmentosa" | No obvious replacement for the SNOMEDCT ID from UMLS browser, delete incorrect X-ref. 
- [ ]  HP:0000448 | cone/cone-rod dystrophy | cites UMLS C0730290, which is specific for cone dystrophy; Cites SNOMEDCT_US:28835009 and UMLS C0035334 which are for Retinitis Pigmentosa. | This HPO term seems to match most closely with C4085590, "cone-rod dystrophies"
- [ ]  HP:0008020 | Cone dystrophy | Maps to UMLS:C3665342 "progressive cone dystrophy" only | Add Xref to C0730290 , "cone dystrophy"  and SNOMEDCT_US 312917007 
- [ ]  HP:0000557 | Buphthalmos | multiple UMLS X-refs appear incorrectly mapped (UMLS:C0423221 & SNOMEDCT_US:246920008  map to "globe of large eye"; SNOMEDCT_US:204113001 and UMLS:C0020302 map to "congenital glaucoma", a parent term) | Should map to UMLS:C4551507 and SNOMEDCT_US 413728006
- [ ]  HP:0100639 | Erectile abnormalities | Current Xrefs C4022003, but this is no longer active | HPO term now mapped to C0242350 (this CUI also has HP:0000802 "impotence")
- [ ]  HP:0000892 | Bifid ribs | Currently X-ref UMLS:C0265695 and SNOMECT_US:66102006, both of which map to "rib fusion" | Consider UMLS: C4721788 instead (no SNOMED term)
- [ ]  HP:0000897 | Rachitic rosary | Has extraneous UMLS/SNOMED X-refs : UMLS:C0426824 (beading of ribs); SNOMEDCT_US:249702007(beading of ribs) | Keep  SNOMEDCT_US:15214001, and add UMLS:C4551565
- [ ]  HP:0000923 | Beaded ribs | Has extraneous SNOMED X-ref SNOMEDCT_US:15214001 | Remove SNOMEDCT_US:15214001

**Comment by pnrobinson** [comment]
Rod-cone dystrophy is the major phenotype of Retinitis pigmentosa, I think that is ok

**Comment by pnrobinson** [comment]
I have corrected the above items. We will work towards a better way of recording the UMLS mappings this year.
