### ISSUE TITLE
Make Clinical course a subclass of Clinical modifier

### ISSUE THREAD

**Issue by monicacecilia** [obophenotype/human-phenotype-ontology#6516]
**HPO term**
Clinical course HP:0031797
https://hpo.jax.org/app/browse/term/HP:0031797

**Suggested revision and reasons**
Hi team! 
A kind request to please consider making _Clinical course_ (HP:0031797) a subclass of _Clinical modifier_ (HP:0012823).
For instance, a _Diurnal_ (HP:0025302) temporal pattern could be actually considered a _Clinical modifier_, and it is currently only represented under _Clinical course_ - which is a subontology of its own, with no relationship to the collection of modifiers.

Discussed with @pnrobinson & @mellybelly; they both agree with the proposed change. 

Please let me know if you have any questions, and thank you!

🌷

**Comment by pnrobinson** [comment]
thanks for the suggestion, I agree, just modified.
