### ISSUE TITLE
Hepatomegaly and temporal pattern

### ISSUE THREAD

**Issue by PabloBotas** [obophenotype/human-phenotype-ontology#6517]
**HPO term**
https://hpo.jax.org/app/browse/term/HP:0006564
Fluctuating hepatomegaly

**Suggested revision and reasons**
I would assume that this term should in fact be split into hepatomegaly (https://hpo.jax.org/app/browse/term/HP:0002240) and fluctuating (https://hpo.jax.org/app/browse/term/HP:0031914). What is the policy with this type of situations? If it is not split then there should be a Non-fluctuating hepatomegaly that is not connected with an "is_a" relation with fluctuating hepatomegaly.

On a similar line, do you have any code that taking 2 versions of an ontology and creating a mapping with modified terms? I am thinking about the case where you decide to split fluctuating hepatomegaly. It'd be great to have this mapping as a *diff* that can then be applied to update disease/patient annotations.

Thanks for your work!
Pablo

**Comment by pnrobinson** [comment]
Hi @PabloBotas and Feliz Año Nuevo 2021. For this sort of thing we have tried not to make HPO terms for each possible combination of modifiers *except* if the combination is so commonly used that users will look for the term. This stance is a practical stance and not a logical stance. Most cases of hepatomegaly do not fluctuate, and so this is the norm and if an MD says just "hepatomegaly" basically it is the same as non-fluctuating hepatomegaly. 
This more or less works, with the top level term logically being undecided about fluctuation. 
It would be possible to make a diff and or to create more terms on the fly with all of the modifiers, but I doubt this would be very useful -- for one thing, we do not have that level of detail in the vast majority of case reports and for another most of these distinctions would not be useful for the differential diagnosis.
That is not to say that there are not individual places of inconsistency or error, but it is to say that I do not think we should systematically change things.
Hope this makes sense if not we can zoom.

**Comment by PabloBotas** [comment]
Hi @pnrobinson! Feliz año nuevo para ti también!

I completely understand and agree from the practical stand point of HPO as a vocabulary and from the usability perspective.

This however raises concerns regarding how automated reasoners would process this. For example, the following case:
Patient: hepatomegaly with fluctuation
Disease: non-fluctuating hepatomegaly

Since the patient presents fluctuating hepatomegaly it logically implies hepatomegaly. So it'd be a perfect match for some metrics in terms of that symptom with the current assumption that the parent of fluctuating hepatomegaly IS non-fluctuating hepatomegaly. If you try, for example, to create HP embeddings, you'd have the same problem.

So as it is it leads to inconsistencies when trying to reason on top of the ontology. The 2 solutions I see are either adding a non-fluctuating hepatomegaly term or removing the fluctuation detail and relying on modifiers. The 1st case implies that the softwares used to annotate HPO terms into cases should suggest more specific terms so that users use them... and the 2nd that the softwares used to annotate HPO terms are well designed to attach modifiers to the terms as they are added. Given that the former is (much) more common than the latter I would opt for it.

About the diff: it actually belongs to a different conversation, so I'll leave it there. It is not so important for HPO, but for MONDO it'd be interesting since the rate of term changes has an impact on patient cohorts being annotated with MONDO ids as main index. Anyway, it certainly belongs to a different conversation.

We can certainly move this to a zoom call if what I wrote does not make sense ;)
What do you think?

**Comment by pnrobinson** [comment]
mejor que hagamos una conferencia de zoom...pf mandame un email
