### ISSUE TITLE
hypoplasia of teeth roots

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#655]
add, because used in OMIM for 146400

**Comment by pnrobinson** [comment]
Please note "teeth roots" is poor English (I think), better would be dental roots or tooth roots.

**Comment by drseb** [comment]
thanks. will fix that!

**Comment by markengelstad** [comment]
hypoplasia of roots of teeth
or
hypoplasia of dental roots

both are in synonyms i'm adding.
