### ISSUE TITLE
Clarification: common atrioventricular canal/inlet ventricular septal defect

### ISSUE THREAD

**Issue by kanems** [obophenotype/human-phenotype-ontology#6557]
Hoping to get some clarification on these two related terms:
Complete atrioventricular canal defect, HP:0001674  
Inlet ventricular septal defect, HP:0011622

Right now there are cross-refs on HP:0011622 (IVSD) to SNOMEDCT_US:360481003, MSH:C535974, and UMLS:C0221215 all of which are "Common atrioventricular canal" (Per UMLS)

The cross-refs on HP:0001674 (CACD) include SNOMEDCT_US:253414002, UMLS:C1389018, MSH:C562831, which are all "atrioventricular septal defect" (per UMLS)  And the syns are Atrioventricular canal, Complete atrioventricular septal defect, Complete common AV canal, Common atrioventricular canal
Per the definition on this HP term: 
> "A congenital heart defect _characteizred_ [**typo**] by a specific combination of heart defects with a common atrioventricular valve, primum atrial septal defect and inlet ventricular septal defect"  
Thus, IVSD is a component of CACD, but these are not equivalent. Am I understanding this correctly?

If so, it seems UMLS C0221215 should map to HP:0001674 (along with the SNOMED and MSH terms), rather than HP:0011622 (as it is currently displaying on HPO and UMLS metathesaurus). 

Perhaps HP:0011622 IVSD should map to https://uts.nlm.nih.gov/uts/umls/concept/C3163736 "Ventricular septal defect of inlet of right aspect of ventricular septum?"  I'm not an expert in this, but based on the term name in UMLS and the definition in HPO, these seem to be the same concept... maybe?

The UMLS term currently mapped to HP:0001674 (UMLS:C1389018) is already appropriately mapped to Atrioventricular canal defect HP:0006695 (syn: atrioventricular septal defect), so it looks like it definitely doesn't belong on CACD.

If these changes appear to be correct, I can submit a ticket to UMLS to ask them to remap the HPO terms (FYI I think their deadline to incorporate changes for the 2021AA release is rather soon.)

**Comment by kanems** [comment]
@pnrobinson @nicolevasilevsky  Thanks in advance for taking a look at this!

**Comment by pnrobinson** [comment]
@kanems I am trying to get access to the new UMLS site.
In general, it would be good to generate a separate file with UMLS mappings where we would take your mappings as canonical. HPO users would love to have a simple TSV file with HPO to UMLS (and entities contained therein). I am not sure if this is possible with the UMLS licence? If you have time it would be great to touch bases, peter DT robinson A jax DT org

**Comment by kanems** [comment]
@pnrobinson I agree the new UMLS interface is a little tricky to navigate. I can try to pull their entries for these two terms and send at the email you provided, I'm not sure about the HPO:UMLS mappings and how these are generated (from either side). I'm not directly affiliated with the UMLS team, so I would have to look into what kind of data downloads come with the license.

**Comment by pnrobinson** [comment]
I see. Basically, the UMLS team has incorporated the HPO into the UMLS. Our files still have some mappings that we made previous to that. We are going to be removing this mappings from our files and referring everybody to the UMLS. However, I think the UMLS is relatively difficult to use and is not going to be familiar to many of our users so we are trying to figure out a way of offering the UMLS mappings in a simple file. For now I will correct the issues with the mappings by removing the erroneous ones, please just use the UMLS official mappings from now on!
