### ISSUE TITLE
Term request: maternal thrombophiia

### ISSUE THREAD

**Issue by Joiedavis** [obophenotype/human-phenotype-ontology#656]
Mother of a proband has Plasminogen activator inhibitor (PAI); she required heparin injections through out her pregnancy.

Here is what OMIM says:
Thrombophilia (see 188050) due to increased concentration of plasminogen activator inhibitor was described by Nilsson et al. (1985).  

Nilsson and Tengborn (1983) restudied 2 members of a large family in which venous thrombosis was thought originally to have been associated with deficiency of tissue plasminogen activator (PLAT; 173370). After venous occlusion, both members of the family showed a normal release of tissue plasminogen activator antigen, but low tissue plasminogen activator concentrations as measured by fibrin plates. The plasma contained 50 times more tissue plasminogen activator inhibitor than normal. However, Engesser et al. (1989) was unable to establish a connection between familial thrombophilia and inherited, persistent elevation of plasma PAI. The cause-and-effect relationship between increased PAI1 and thrombosis was supported by the observations of Erickson et al. (1990) who, from studies of mice transgenic for this gene, concluded that elevated levels contribute to the development of venous but not arterial occlusions.  

If there is an existing prenatal phenotip to describe this, I'm not seeing it.
Thank you
Joie

**Comment by pnrobinson** [comment]
Are you looking for a term like " increased concentration of plasminogen activator inhibitor" ?

**Comment by Joiedavis** [comment]
I guess that would work, if we can associate it with a maternal condition; maternal thrombophilia may still be needed also.

Joie
828 595 2486

**Comment by pnrobinson** [comment]
I see, so we are looking at it from the fetus' standpoint, a history of the mother having thrombophilia, sorry I did not get it the first time. Correct?

**Comment by Joiedavis** [comment]
Yes sir, that's correct.  Maternal thrombophilia due to  to PAI

Joie
828 595 2486
