### ISSUE TITLE
Frequency Ranges

### ISSUE THREAD

**Issue by austinant** [obophenotype/human-phenotype-ontology#6581]
I propose a suggestion here for several terms:

HP:0040284 "Very rare"
Definition: "Present in 1% to 4% of the cases."
https://hpo.jax.org/app/browse/term/HP:0040284

HP:0040283 "Occasional" 
Definition: "Present in 5% to 29% of the cases." 
https://hpo.jax.org/app/browse/term/HP:0040283

HP:0040282 "Frequent" 
Definition: "Present in 30% to 79% of the cases." 
https://hpo.jax.org/app/browse/term/HP:0040282

HP:0040281 "Very frequent" 
Definition: "Present in 80% to 99% of the cases." 
https://hpo.jax.org/app/browse/term/HP:0040281

These frequency ranges do not cover all possible values; I suggest a rephrasing of the definitions to more accurately reflect what are likely the intended ranges.  As an example, look at HP:0040284 "Very Rare"

What is wrong: The current definition reads "Present in 1% to 4% of cases", and the next highest frequency (HP:0040283 "Occasional") ranges from 5% to 29%.  

Why: this excludes 4%-5%.

Suggested alternatives: 
"Present in more than 0% and no more than 5% of cases" (to express that 0% < frequency <= 5%)
"Present in between 0% and 5% of cases (simpler and cleaner, more ambiguous as to whether endpoints should be included)

**Comment by pnrobinson** [comment]
@austinant  mathematically you are of course completely correct. However, these terms are not intended to be that precise -- basically they are approximate groups. 
We are trying to perform literature curation to obtain more precise frequencies. Here is a recent example
https://hpo.jax.org/app/browse/disease/OMIM:619004
Software such as [LIRICAL](https://pubmed.ncbi.nlm.nih.gov/32755546/) uses the frequency data to improve differential diagnostic predictions, and so we are aiming to increase the amount of precise frequency data. 

So therefore, if we are even thinking of the range of numbers between 4% and 5%, we would not be using these approximate terms. Also the range between 0 and 1% is intentially not covered -- this is in n=1 space and would be reported as such if we were able to do the curations.
