### ISSUE TITLE
Anti-ribonucleoprotein antibody positivity HP:0033028

### ISSUE THREAD

**Issue by eswietlik** [obophenotype/human-phenotype-ontology#6601]
**HPO term** Anti-ribonucleoprotein antibody positivity HP:0033028

**Synonym to be added**
Anti-U3 ribonucleoprotein antibody positivity 
Anti-Scl-34 antibody positivity

**broad/exact/narrow/plural/abbreviation ?**

**Comment by pnrobinson** [comment]
added
