### ISSUE TITLE
Anti-mitochondrial M2 antibody positivity HP:0031907

### ISSUE THREAD

**Issue by eswietlik** [obophenotype/human-phenotype-ontology#6602]
**HPO term** Anti-mitochondrial M2 antibody positivity HP:0031907

**Synonym to be added**
Anti-pyruvate dehydrogenase antibody positivity

**broad/exact/narrow/plural/abbreviation ?**

**Comment by pnrobinson** [comment]
@eswietlik  is this really a synonym? Anti-pyruvate dehydrogenase antibody ?=? mitochondrial M2 antibody

**Comment by eswietlik** [comment]
@pnrobinson M2 Ab recognise four closely related enzymes in the 2-oxoacid dehydrogenase complex; pyruvate dehydrogenase, branched chain α-ketoacid dehydrogenase, α-ketoglutarate dehydrogenase. In my lab they are called anti-pyruvate dehyrogenase Ab.

**Comment by pnrobinson** [comment]
I will add it as a narrow synonym!
