### ISSUE TITLE
Add definiton to "Inclusion bodies in leukocytes"

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#661]

**Comment by drseb** [comment]
related to https://github.com/obophenotype/human-phenotype-ontology/issues/647

**Comment by pnrobinson** [comment]
The presence of intraceullar inclusion bodies (aggregates of stainable substances, usually proteins) in leukocytes.
Note that we have a similar class for neutrophils (neutrophils are a subclass of leukocyte), and that this class has as a synonym "Dohle-like leukocyte inclusion bodies", which actually should be a synonym for "leukocyte inclusion bodies" (I think that "Leukocyte inclusion bodies" should be the prefered name).
