### ISSUE TITLE
Abnormality of cytokine/chemokine secretion use obsolete GO processes in EQ

### ISSUE THREAD

**Issue by matentzn** [obophenotype/human-phenotype-ontology#6623]
Obsoleted terms used:
GO_0050663
GO_0090195

**Comment by pnrobinson** [comment]
Both can be replaced by GO_0001816 (http://amigo.geneontology.org/amigo/term/GO:0032602)
This affects one term only
https://hpo.jax.org/app/browse/term/HP:0011113
@matentzn I think we need to import GO_0001816. -- does this sound about right?

**Comment by matentzn** [comment]
I think it affects HP:0011113 and HP:0011115. I think you should:
- [ ] Replace GO:0050663 with GO:0001816 (in EQ for HP:0011113)
- [ ] Replace GO:0090195 with GO:0032602 (in EQ for HP:0011115)

![image](https://user-images.githubusercontent.com/7070631/116859453-ef993880-abf7-11eb-8ea2-1f3b4277ebdd.png)

**Comment by pnrobinson** [comment]
@matentzn not able to fix   Abnormality of chemokine secretion, GO:0032602 is not present ?

**Comment by matentzn** [comment]
Sorry, yea only added the one term. Adding here: https://github.com/obophenotype/human-phenotype-ontology/pull/6879

**Comment by pnrobinson** [comment]
fixed!
