### ISSUE TITLE
Infantile onset HP:0003593

### ISSUE THREAD

**Issue by eswietlik** [obophenotype/human-phenotype-ontology#6624]
**HPO term**
Infantile onset HP:0003593

**Suggested revision and reasons**
I think the proper term is neonatal-onset, which also exist in the ontology Neonatal onset HP:0003623

**Comment by pnrobinson** [comment]
@eswietlik  these terms are not synonyms, not sure I understand the issue?

https://hpo.jax.org/app/browse/term/HP:0003623
Neonatal onset HP:0003623: 1-28 days
Infantile onset HP:0003593  28 days to 1 year

**Comment by eswietlik** [comment]
@pnrobinson Sorry my mistake, I must have misread the definition
