### ISSUE TITLE
Diverticulosis of trachea HP:0006509

### ISSUE THREAD

**Issue by eswietlik** [obophenotype/human-phenotype-ontology#6626]
**HPO term** Diverticulosis of trachea HP:0006509

**Synonyms**
Tracheoceles
Paratracheal air cyst
When tracheal diverticulum mimics pneumomediastinum it is called pseudopneumomediastinum

**Suggested revision of textual definition**
No definition at the moment

Tracheal diverticula are blind-ended outpouchings arising from the trachea. They are usually an incidental finding. Occasionally they can mimic pneumomediastinum. Tracheal diverticula are either congenital or acquired, in the latter case the most common causes are prolonged increased intraluminal pressure, e.g. chronic cough, COPD, tracheomalacia, iatrogenic, e.g. post-surgical 
PMID: 18544671, PMID: 27867581

**Comment by pnrobinson** [comment]
adding new definition.
