### ISSUE TITLE
Increased PIVKA-II (protein increased in vitamin K's absence; undercarboxylated prothrombin)

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#663]
Find better term label and better definition.

Suggestions came from here: https://github.com/obophenotype/human-phenotype-ontology/issues/647

Label: Increased PIVKA-II (protein increased in vitamin K's absence; undercarboxylated prothrombin)
Def: Increased level of PIVKA-II, indicating abnormal carboxylation of proteins secondary to vitamin K deficiency

Superclass: HP:0100831 Abnormality of Vitamin K metabolism

**Comment by pnrobinson** [comment]
The entitiy is also known as  prothrombin induced by vitamin K absence or antagonist-II (PIVKA-II) and Des-gamma carboxyprothrombin (DCP).

Term name: Increased PIVKA-II
Syn: see above
Def.Des-gamma   carboxyprothrombin   (DCP)   or   pro-
thrombin induced by vitamin K absence-II (PIVKA-II) is
an abnormal prothrombin protein that is increased in the
serum  of  patients  with  HCC.  Generation  of  DCP  is
thought to be a result of an acquired defect in the post-
translational carboxylation of the prothrombin precursor
in malignant cells.
PMID:    12717392

Comment: PIVKA-II can be measured by enzyme-linked immunosorbent assay (ELISA).


PMID:    18087182
