### ISSUE TITLE
Missing association between HP:0003198 - Myopathy and AMPD1 

### ISSUE THREAD

**Issue by marc-sturm** [obophenotype/human-phenotype-ontology#6641]
**HPO term**

HP:0003198 - Myopathy

**Bug description**

The association of the the term to the gene AMPD1 is missing:
https://omim.org/entry/102770
https://www.genecards.org/cgi-bin/carddisp.pl?gene=AMPD1

**Comment by pnrobinson** [comment]
thanks for pointing this out, I have updated the annotations -- this will be available on our next release 1 week of Feb.
