### ISSUE TITLE
BCGiosis

### ISSUE THREAD

**Issue by johannaest** [obophenotype/human-phenotype-ontology#6646]
**HPO term**
Disseminated Bacillus Calmette-Guerin infection

**Synonym to be added**
BCGiosis

**broad/exact/narrow/plural/abbreviation ?**
abbreviation

**Comment by pnrobinson** [comment]
Hm, I see we have two related terms
https://hpo.jax.org/app/browse/term/HP:0031698
and
https://hpo.jax.org/app/browse/term/HP:0020087

**Comment by pnrobinson** [comment]
merged the above synoynmous terms and added synonym BCGiosis.
Thanks!
