### ISSUE TITLE
Arterial hypertension

### ISSUE THREAD

**Issue by johannaest** [obophenotype/human-phenotype-ontology#6648]
**HPO term**
Increased blood pressure

**Synonym to be added**
Arterial hypertension

**broad/exact/narrow/plural/abbreviation ?**
exact

**Comment by pnrobinson** [comment]
Actually, this is the synonymous term
https://hpo.jax.org/app/browse/term/HP:0000822

Increased blood pressure can be transient, and so it is not synonymous. I will add the synonym to the latter term.
