### ISSUE TITLE
Polyposis nasi

### ISSUE THREAD

**Issue by johannaest** [obophenotype/human-phenotype-ontology#6656]
**HPO term**
Nasal polyposis

**Synonym to be added**
Polyposis nasi

**broad/exact/narrow/plural/abbreviation ?**
exact

**Comment by pnrobinson** [comment]
adding with def

Nasal polyps (NP) are benign lesions arising from the mucosa of the nasal sinuses (commonly at the outflow tract of one or more of the sinuses) or from the mucosa of the nasal cavity. The main presenting symptom of NP is nasal obstruction which is constant but can vary depending on the site and size of the polyps. Sufferers will also frequently complain of watery rhinorrhea and postnasal drip. Anosmia or hyposmia with an ensuing alteration in taste are also characteristic symptoms of NP PMID:18728843

**Comment by pnrobinson** [comment]
actually, the term already exists --
https://hpo.jax.org/app/browse/term/HP:0100582
I will add the synonym
