### ISSUE TITLE
Hydrocele testis and Vaginal hydrocele

### ISSUE THREAD

**Issue by LM-Ontologies** [obophenotype/human-phenotype-ontology#6666]
**HPO term**

Hydrocele testis: https://hpo.jax.org/app/browse/term/HP:0000034 under 'Abnormal testis morphology'
Vaginal hydrocele: https://hpo.jax.org/app/browse/term/HP:0100673 under 'Abnormality of the scrotum'
 
**Bug description**
What distinguishes 'Hydrocele testis' and 'Vaginal hydrocele'?
Why is one each added below abnormal test morphology and abnormality of the scrotum. Should they both be under those hierarchies or should the same preferred term be used to name those term entries?

**Comment by pnrobinson** [comment]
Thanks for pointing this out. Vaginal hydrocele is a subtype of Hydrocele testis
https://www.ncbi.nlm.nih.gov/books/NBK559125/
I will adapt the definition and hierarchy.

**Comment by pnrobinson** [comment]
done, thanks!
