### ISSUE TITLE
Delayed speech and language development is a form of Language impairment

### ISSUE THREAD

**Issue by DLewisSmith** [obophenotype/human-phenotype-ontology#6670]
**HPO term**
Delayed speech and language development HP:0000750

**Suggested revision and reasons**
Consider giving a second parent: Language impairment HP:0002463
The definition of Language impairment includes "Language abilities are substantially and quantifiably below age expectations", which should include delayed speech and language development.

**Comment by pnrobinson** [comment]
makes sense, added.
