### ISSUE TITLE
Hypertonia, spasticity and rigidity

### ISSUE THREAD

**Issue by DLewisSmith** [obophenotype/human-phenotype-ontology#6674]
**HPO term**

Hypertonia HP:0001276 and related concepts
**Suggested revision and reasons**
Both Spasticity HP:0001257 and Rigidity HP:0002063 are should be hyponyms of Hypertonia. Note, that Hypertonia should not be a hyponym of Upper motor neuron dysfunction HP:0002493 because this would not apply to rigidity (only to spasticity).

I would suggest making

- [x] **Spasticity HP:0001257** the _child_ of **Hypertonia HP:0001276** & **Upper motor neuron dysfunction HP:0002493**,

- [x] **Rigidity HP:0002063** the _child_ of **Hypertonia HP:0001276**.

- [x] **Hypertonia HP:0001276**. the _child_ of **Abnormal muscle tone HP:0003808** but not **Upper motor neuron dysfunction HP:0002493** as this does not apply to **Rigidity HP:0002063**.

(4) **Hyperreflexia HP:0001347** the _child_ of **Upper motor neuron dysfunction HP:0002493**.

(5) Consider making **Hyperkinetic movements HP:0002487** a _synonym_ of **Involuntary movements HP:0004305** as this is how neurologists conceptualise movement disorders.

(6) **Dystonia HP:0001332** the child of **Involuntary movements HP:0004305**/**Hyperkinetic movements HP:0002487** as this is how neurologists conceptualise hyperkinetic movement disorders.

(7) To me it seems that there is a challenge with the phenotypes at the intersection of primary muscle disorders and secondary movement/motor disorders due to neurological (as well as maybe skeletal) disorders. Several phenotypes currently located as hyponyms of muscle ancestors are at least as likely to be due to other (non-muscle) neurological or rheumatological dysfunction/lesions. Not all forms of **Abnormal muscle tone HP:0003808** can be said to be indicative of **Abnormal muscle physiology HP:0011804**.  For example, while Spasticity and Rigidity are manifest through the increased resistance to passive movement of muscles, they are usually indicative of an upper motor neurone abnormality and a basal ganglia/movement disorder respectively, rather than disorders of the muscles themselves. The various hypotonias are more likely to be due to Abnormal muscle physiology than CNS disorders, but can be due to certain types of cerebral, cerebellar, or spinal lesions. They can also occur due to peripheral nervous system disorders at the neuromuscular junction and peripheral nerve (and less applicably to monogenetic disorders also at the nervous plexuses or nerve roots). I am not immediately sure how best to suggest to arrange these. It may be better to consider renaming and redefining Abnormal muscle physiology HP:0011804 and Abnormality of the musculature HP:0003011 ("Abnormality originating in one or more muscles, i.e., of the set of muscles of body.") to something that does not imply primary muscle disorders. However, this would still need thought to be given to Abnormality of the musculoskeletal system HP:0033127 and its definition, and leaves me wondering if this would require a large proportion of the sub ontology of Abnormal nervous system physiology HP:0012638 (those phenotypes with motor manifestations) to be given second parentage under this. I think this challenge reflects the clinical difficulty of confidently localising the cause of motor disorders (e.g. to muscle, NMJ, nerve, CNS, etc.) without considering the evidence indicated by other phenotypes present in a patient.

**Comment by pnrobinson** [comment]
In a sense,  Abnormal muscle tone HP:0003808 is always indicative of Abnormal muscle physiology even though it does not indicate that the etiology has to do with muscles. This is an interesting case. I think we make our lives easier if we try to classify by observation rather than physiology, but admittedly the HPO has a mixture of terms.

**Comment by DLewisSmith** [comment]
I would argue that that abnormal muscle tone is not always indicative of abnormal muscle physiology but beyond primary myopathies, it is a normal muscle physiological response to abnormal neural input. Otherwise it seems to me that all neurological motor disorders would need to be hyponyms of abnormal muscle physiology as a common output pathway.

I agree that focusing on clinical observations or at least separating these more from physiology/histology/biochemistry would help but seems a big job.

**Comment by pnrobinson** [comment]
Recall that HPO tries not to encode pathophysiology. Even if there is a neurological etiology, the physiology of the muscle that we observe is to move and thus it is true in this sense that neurogenic muscle weakness is abnormal muscle physiology (as something we can observe).

**Comment by DLewisSmith** [comment]
Yes. However, it raises the question of the relationship between CNS movement phenotypes (including motor seizures, and potentially the boundary with behavioral abnormalities) and abnormal muscle physiology. As a neurologist, when I say that a person has tremor, ataxia, myoclonus, hemiparesis, etc., this is all based on how their muscles are functioning. I’m keen to explore this further with you in the longer term, even if it just a question of me understanding where the boundary lies (rather than anything changing).
