### ISSUE TITLE
Some Involuntary movements HP:0004305 are Abnormal central motor function HP:0011442 subtypes

### ISSUE THREAD

**Issue by DLewisSmith** [obophenotype/human-phenotype-ontology#6675]
**HPO term**
Abnormal central motor function HP:0011442

**Suggested revision and reasons**
In addition to Involuntary movements HP:0004305, the following should have Abnormal central motor function HP:0011442 as a second parent:

Myoclonus HP:0001336
Tremor HP:0001337
Chorea HP:0002072
Tics HP:0100033
Alien limb phenomenon HP:0032506
Hemiballismus HP:0100248
Athetosis HP:0002305
Paroxysmal dyskinesia HP:0007166
Clonus HP:0002169

**Comment by pnrobinson** [comment]
@DLewisSmith  I am wondering if there is a good grouping term such as CNS involuntary movements (Not that, but I could not find a phrase that is standard) -- in order to avoid having lots of related terms be directed children of ``Abnormal central motor function``.
Ideas?

**Comment by DLewisSmith** [comment]
I'll have a think. I would like to stay away from presumed mechanism and focus on phenomenology. "Centrally-mediated hyperkinetic movement disorder" may be an option for some (neurologists would omit the "Centrally-mediated" in usual parlance). However, I would not usually consider Clonus a hyperkinetic movement disorder - it is a an exaggerated muscular stretch reflex manifesting spasticity (although some degree of clonus is normal in health or after muscular fatigue).

**Comment by pnrobinson** [comment]
- [ ] Myoclonus HP:0001336
- [ ] Tremor HP:0001337
- [ ] Chorea HP:0002072
- [ ] Tics HP:0100033
- [ ] Alien limb phenomenon HP:0032506
- [ ] Hemiballismus HP:0100248
- [ ] Athetosis HP:0002305
- [ ] Paroxysmal dyskinesia HP:0007166
- [ ] Clonus HP:0002169

**Comment by pnrobinson** [comment]
@DLewisSmith  I added the second parentage. Maybe we can find some time to revise the structure at the upper level, but I agree this is correct as is.
