### ISSUE TITLE
Add description of pace of progression terms

### ISSUE THREAD

**Issue by PabloBotas** [obophenotype/human-phenotype-ontology#6676]
**HPO term**
https://hpo.jax.org/app/browse/term/HP:0003679

**Suggested revision of textual definition**
I don't have a suggestion, but none of the HP terms below pace of progression have textual descriptions. They do have very nice synonyms.

Thanks!
Pablo

**Comment by pnrobinson** [comment]
Thanks, I am adding some definitions, e.g., this for Progressive

```
Applies to a disease manifestation that increases in scope or severity over the course of time, i.e., that worsens with age.
```
