### ISSUE TITLE
Remove synonym now covered by separate term

### ISSUE THREAD

**Issue by DLewisSmith** [obophenotype/human-phenotype-ontology#6677]
**HPO term**

HP:0032680 Focal cognitive seizure
**Suggested revision and reasons**

This currently has "Psychic auras" as a synonym. However, subsequent development of the seizure subontology has incorporated the term "HP:0033346, Psychic epileptic aura", which is a better match. Thus, "Psychic auras" should no longer be a synonym of "HP:0032680 Focal cognitive seizure".

**Comment by pnrobinson** [comment]
done
