### ISSUE TITLE
Synonym for "Elevated RV/TLC ratio"

### ISSUE THREAD

**Issue by katrinknoflach** [obophenotype/human-phenotype-ontology#6708]
**HPO term**
Elevated RV/TLC ratio (HP:0033240)

**Synonym to be added**
Overinflation on pulmonary function test
Hyperinflation on pulmonary function test

**broad/exact/narrow/plural/abbreviation ?**

@mgriese, @crapp

**Comment by pnrobinson** [comment]
added
