### ISSUE TITLE
Term request: Intrauterine fetal demise of one twin after 17 weeks of gestation

### ISSUE THREAD

**Issue by Joiedavis** [obophenotype/human-phenotype-ontology#671]
6. Carlson NJ, Towers CV: Multiple gestation complicated by the death of one fetus. Obstet Gynecol 73:685, 1989.  
7. van Heteren CF, et al.. Risk for surviving twin after fetal death of co-twin in twin-twin transfusion syndrome. Obstet Gynecol. 1998;92:215-9. 
8. Saito K, et al. . Perinatal outcome and management of single fetal death in twin pregnancy: a case series and review. J Perinat Med. 1999;27:473-7. 
9. Bejar R, et al, . Antenatal origin of neurologic damage in newborn infants. II. Multiple gestations. Am J Obstet Gynecol. 1990;162:1230-6. 
10. Norton ME, et al. . Molecular zygosity studies aid in the management of discordant multiple gestations. J Perinatol. 1997;17:202-7.

**Comment by drseb** [comment]
When you write '17 weeks', is this a lower bound or an *exact date*? Why 17?

**Comment by pnrobinson** [comment]
I think that 17 weeks is simply midgestation. " Fetal loss of a twin during first trimester is not an uncommon event [1]. Loss of one twin in the first trimester does not appear to impair the development of the surviving twin. However, fetal death occurring after midgestation (17 weeks' gestation) may increase the risk of IUGR, preterm labor, preeclampsia and perinatal mortality"

I will change the name to "...after midgestation"
