### ISSUE TITLE
Neonatal seizure subontology revision in light of publication of finalised classification

### ISSUE THREAD

**Issue by DLewisSmith** [obophenotype/human-phenotype-ontology#6715]
**HPO term**

Neonatal electro-clinical sequential motor seizure HP:0032825

**Suggested revision and reasons**
The ILAE Seizure classification has now been finalised after the consultation period (this subontology was based on the draft proposal). The PMID 33522601 should be applied to the entire current subontology of root Neonatal seizure HP:0032807.

The only changes required regard Neonatal electro-clinical sequential motor seizure HP:0032825:

Preferred name to be changed to 'Neonatal electro-clinical sequential seizure'
Parent to be changed from Neonatal electro-clinical motor seizure HP:0032813 to Neonatal electro-clinical seizure HP:0032809
(This recognise that some sequential seizures may not be of motor onset.)

Thank you

**Comment by pnrobinson** [comment]
Should the synonyms ``Neonatal electro-clinical sequential motor seizure`` be removed? They do not seem to be correct anymore @DLewisSmith

**Comment by pnrobinson** [comment]
I have implemented the changes with the possible exception of the synonyms.

**Comment by DLewisSmith** [comment]
Sorry @pnrobinson I am a little confused. The only synonym I see for Neonatal electro-clinical sequential motor seizure HP:0032825 is Neonatal electroclinical sequential motor seizure (from which I suggest dropping the "motor"). The word "motor" should be dropped from the definition as well.

**Comment by pnrobinson** [comment]
That was exactly what I was asking and this makes sense. Done.
