### ISSUE TITLE
Intracranial forms of Arachnoid cystic

### ISSUE THREAD

**Issue by DLewisSmith** [obophenotype/human-phenotype-ontology#6737]
**HPO term**
Cerebellopontine angle arachnoid cyst HP:0012487
Intraventricular arachnoid cyst HP:0012488
Suprasellar arachnoid cyst HP:0012489
 
**Suggested revision and reasons**
Add second parent:
Intracranial cystic lesion HP:0010576
(these forms of subarachnoid cyst are intracranial).

(Also, note that Spinalarachnoid cyst HP:0009745 should probably have a space between 'spinal' and 'arachnoid').

**Comment by DLewisSmith** [comment]
Additionally Pineal cyst HP:0012683 is intracranial

**Comment by DLewisSmith** [comment]
We have subsequently made Cerebellopontine angle arachnoid cyst HP:0012487 a form of Posterior fossa cyst, which implies an Intracranial cystic lesion, so this term is already corrected (#6748). However, the others remain
--

**Comment by pnrobinson** [comment]
Thanks, I implemented these corrections.
