### ISSUE TITLE
Pontocerebellar atrophy second parent: Abnormality of the pons

### ISSUE THREAD

**Issue by DLewisSmith** [obophenotype/human-phenotype-ontology#6738]
**HPO term**
Pontocerebellar atrophy HP:0006879

**Suggested revision and reasons**
Suggest second parent required as both cerebellar and pontine atrophy present:
Abnormality of the pons HP:0007361

Also suggest synonym:
cerebellopontine atrophy

**Comment by pnrobinson** [comment]
thanks for the suggestion, added.
