### ISSUE TITLE
Merge Frontoparietal polymicrogyria and Perisylvian polymicrogyria?

### ISSUE THREAD

**Issue by DLewisSmith** [obophenotype/human-phenotype-ontology#6739]
**HPO term**
Frontoparietal polymicrogyria HP:0007095

**Reason for deprecation**
The Sylvian fissure is the fronto-parietal boundary. Thus I suggest merging the two and keeping Perisylvian as the preferred term (it is probably used more frequently).

**Suggested replacement or term to consider**
Perisylvian polymicrogyria HP:0012650

**Comment by pnrobinson** [comment]
thanks for pointing this out, done!
