### ISSUE TITLE
Hippocampal atrophy is a type of Abnormal morphology of the hippocampus

### ISSUE THREAD

**Issue by DLewisSmith** [obophenotype/human-phenotype-ontology#6741]
**HPO term**
Hippocampal atrophy  HP:0410170

**Suggested revision and reasons**
Suggest a second parent:
Abnormal morphology of the hippocampus HP:0025100

**Comment by pnrobinson** [comment]
This term already had that parentage!

**Comment by DLewisSmith** [comment]
Apologies. Not sure how I missed that one.


On 6 Mar 2021, at 13:04, Peter Robinson <notifications@github.com> wrote:

﻿

⚠ External sender. Take care when opening links or attachments. Do not provide your login details.

This term already had that parentage!
