### ISSUE TITLE
Hypoplasia of the cerebellar vermis is specific type of Hypoplasia of the cerebellum.

### ISSUE THREAD

**Issue by DLewisSmith** [obophenotype/human-phenotype-ontology#6742]
**HPO term**
Aplasia/Hypoplasia of the cerebellar vermis HP:0006817

**Suggested revision and reasons**
Additional parent: Aplasia/Hypoplasia of the cerebellum HP:0007360

The vermis is part of the cerebellum.

**Comment by pnrobinson** [comment]
This linkage already existed!

**Comment by DLewisSmith** [comment]
Sorry @pnrobinson, I can't see it on the hpo.jax browser.

I see:
Aplasia/Hypoplasia of the cerebellum HP:0007360 has progeny: Cerebellar hypoplasia HP:0001321, Cerebellar hemisphere hypoplasia HP:0100307, Olivopontocerebellar hypoplasia HP:0006955, and Cerebellar agenesis HP:0012642. Neither of these have progeny. Am I missing something?
