### ISSUE TITLE
Cerebral dysmyelination is a type of  Abnormality of the cerebral white matter

### ISSUE THREAD

**Issue by DLewisSmith** [obophenotype/human-phenotype-ontology#6749]
**HPO term**
Cerebral dysmyelination HP:0007266

**Suggested revision and reasons**

Additional parent:

Abnormality of the cerebral white matter HP:0002500

**Comment by pnrobinson** [comment]
Actually it is probably better to shift things around a bit so that all of the abnormal myelination terms are under "Abnormality of the cerebral white matter" (which I am renaming to Abnormal cerebral white matter morphology)?

**Comment by DLewisSmith** [comment]
I'm not sure it would be correct as some Abnormalties of myelination such as (Demyelinating peripheral neuropathy HP:0007108) pertain to the peripheral nervous system rather than the central nervous system. In fact even some of the CNS abnormalities of myelination may refer to spinal cord rather than brain on some occasions.

**Comment by pnrobinson** [comment]
OK, implemented your initial suggestion, thanks!
