### ISSUE TITLE
Subependymal nodules HP:0009716

### ISSUE THREAD

**Issue by DLewisSmith** [obophenotype/human-phenotype-ontology#6754]
**HPO term**
Subependymal nodules HP:0009716

**Suggested revision of textual definition**

Current def:
"Small nodular masses which originate in the subependymal region of the lateral ventricles and protrude into the ventricular cavity. They may represent subependymal hamartomas of tuberous sclerosis or nodular heterotopia of grey matter."

I suggest removing the "or nodular heterotopia of grey matter" as these are covered separately and are usually a distinct entity (Periventricular nodular heterotopia HP:0032388).

**Comment by pnrobinson** [comment]
done, thanks!
