### ISSUE TITLE
Aplasia/Hypoplasia of the cerebellar vermis is a Aplasia/Hypoplasia of the cerebellum

### ISSUE THREAD

**Issue by DLewisSmith** [obophenotype/human-phenotype-ontology#6756]
**HPO term**
Aplasia/Hypoplasia of the cerebellar vermis HP:0006817

**Suggested revision and reasons**

Add parent:

Aplasia/Hypoplasia of the cerebellum HP:0007360

**Comment by pnrobinson** [comment]
added
