### ISSUE TITLE
Colpocephaly is an Abnormality of the cerebral ventricles

### ISSUE THREAD

**Issue by DLewisSmith** [obophenotype/human-phenotype-ontology#6759]
**HPO term**

Colpocephaly HP:0030048
**Suggested revision and reasons**
second parent:
Abnormality of the cerebral ventricles HP:0002118

**Comment by pnrobinson** [comment]
It is currently a child of abn of lateral ventricles -- is this incorrect? @DLewisSmith

**Comment by DLewisSmith** [comment]
Looks correct. Apologies, not sure how I didn’t spot this on browser.

Sent from my phone

On 6 Mar 2021, at 13:01, Peter Robinson <notifications@github.com> wrote:

﻿

⚠ External sender. Take care when opening links or attachments. Do not provide your login details.

It is currently a child of abn of lateral ventricles -- is this incorrect? @DLewisSmith<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FDLewisSmith&data=04%7C01%7CDavid.Lewis-Smith%40newcastle.ac.uk%7Ce664f574e8c64349b30e08d8e09feb94%7C9c5012c9b61644c2a91766814fbe3e87%7C1%7C0%7C637506324741211088%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=AJGma8mwXYwuWw0SDY9ayxIZ1K%2B8D99kMSc7eInRfdY%3D&reserved=0>

**Comment by pnrobinson** [comment]
ok, closing
