### ISSUE TITLE
Lay term request: stubby fingers

### ISSUE THREAD

**Issue by jmcmurry** [obophenotype/human-phenotype-ontology#676]
I'm not sure what the corresponding term would be.

The use case is here: PMC4498842
<img width="330" alt="screen shot 2016-02-09 at 8 42 52 pm" src="https://cloud.githubusercontent.com/assets/3658863/12939419/24d55468-cf74-11e5-9295-3ccfd0aac786.png">

**Comment by nicolevasilevsky** [comment]
This child in the picture has camptodactyly and clinodactyly.

I added "stubby finger" and "stubby toe" to HP_0009381 Short finger and HP_0001831Short toe in my spreadsheet. I'll close this ticket when the terms are uploaded into HPO.

**Comment by jmcmurry** [comment]
> This child in the picture has camptodactyly and clinodactyly.

Agreed, however, the article specifically mentions "stubby fingers" which is why it may be worth  adding. Thanks :)

**Comment by nicolevasilevsky** [comment]
Sounds good, I will add stubby fingers as a synonym to 'short fingers'. :)

**Comment by drseb** [comment]
will appear in HP once lay-syns are imported (soon to happen)

so closing

**Comment by jmcmurry** [comment]
When we implement images, we should have an easter egg of a certain someone's stubby fingers. :/
