### ISSUE TITLE
Bilateral intracranial calcifications to Bilateral intracerebral calcifications

### ISSUE THREAD

**Issue by DLewisSmith** [obophenotype/human-phenotype-ontology#6762]
**HPO term**
Bilateral intracranial calcifications HP:0005671

**Suggested revision of textual definition**
Rename:
Bilateral intracerebral calcifications 

This is more consistent with the definition (specifies 'brain' not cranium) and semantic relationships.

**Comment by pnrobinson** [comment]
agreed. I left Bilateral intracranial calcifications as a synonym.
