### ISSUE TITLE
Discrepency between related diesease for HP:0001475 between HPO Browser and monthly dump

### ISSUE THREAD

**Issue by rolfschr** [obophenotype/human-phenotype-ontology#677]
Looking at 

http://compbio.charite.de/hpoweb/showterm?id=HP:0001475

it shows that HP:0001475 is associated with OMIM:153470 & OMIM:150590. However, in the monthly export

http://compbio.charite.de/jenkins/job/hpo.annotations.monthly/lastSuccessfulBuild/artifact/annotation/ALL_SOURCES_ALL_FREQUENCIES_diseases_to_genes_to_phenotypes.txt

"HP:0001475" does not occur at all. The browser does not use the exact same data found in the monthly export but it seems unlikely to that both associatons have been removed/added recently. The association can be found here:

http://compbio.charite.de/jenkins/job/hpo.annotations/lastSuccessfulBuild/artifact/misc/phenotype_annotation.tab

I therefore feel some data is missing in the monthly export file (or am I missing something here?)

**Comment by drseb** [comment]
the file name was supposed to give the hint here: phenotype_to_gene , i.e. this file only contains signs and symptoms (suclass of HP_0000118) and no inheritance, onset etc terms.

**Comment by rolfschr** [comment]
Thanks for the quick reply. I'm a bit confused, the file I mentioned is "ALL_SOURCES_ALL_FREQUENCIES_**diseases_to_genes_to_phenotypes**.txt" so I would have expected it to contain all terms linked to disease. If the is not the case: Is there a way  to find the relationship HP:0001475-OMIM:153470 or OMIM:153470-HP:0001475 in the monhtly dumps?

**Comment by drseb** [comment]
no. only contains the phenotypes not the inheritance terms etc. 
these annotations are in http://compbio.charite.de/jenkins/job/hpo.annotations/

**Comment by rolfschr** [comment]
Hi,

Thanks again for that quick reply. I checked out [1] and could indeed find the associations between HP:0001475 and OMIM:153470/OMIM:150590 as mentioned in the HPO Browser. But as another example, on the HPO browser HP:0011304 is linked to OMIM:101200 - an association I cannot find in [1] nor [2].

I'm sorry to still bother you again on this: I am trying to track back the HPOTerm-OMIM associations shown in the HPO Browser to one (any?) of jenkins build projects but I cannot seem to get the same results.

Thanks in advance!

[1] http://compbio.charite.de/jenkins/job/hpo.annotations/lastSuccessfulBuild/artifact/misc/phenotype_annotation.tab
[2] http://compbio.charite.de/jenkins/job/hpo.annotations.monthly/lastSuccessfulBuild/artifact/annotation/ALL_SOURCES_ALL_FREQUENCIES_diseases_to_genes_to_phenotypes.txt

**Comment by rolfschr** [comment]
Is Github the right place for this or should I rather send an email directly?

**Comment by drseb** [comment]
will look into this later

**Comment by rolfschr** [comment]
Ok, thanks!

**Comment by drseb** [comment]
In file `http://compbio.charite.de/jenkins/job/hpo.annotations/lastSuccessfulBuild/artifact/misc/phenotype_annotation.tab` in line `544` I see

```OMIM	101120	ACROCEPHALOPOLYSYNDACTYLY TYPE III		HP:0011304	OMIM:101120	TAS				O	ACPS III|ACPS WITH LEG HYPOPLASIA|ACROCEPHALOPOLYSYNDACTYLY TYPE 3|SAKATI SYNDROME|SAKATI-NYHAN SYNDROME|SAKATI-NYHAN-TISDALE SYNDROME|http://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=en&Expert=3128	2009.02.17	HPO:probinson```

**Comment by rolfschr** [comment]
OK, but I was looking for a link between ``HP:0011304`` and  ``OMIM:101200``, not ``OMIM:101120``. Here is what I checked:

```
$  grep 'HP:0011304' phenotype_annotation.tab  | awk -F '\t' '{ print "OMIM:"$2 }' | sort
```

This yields lines. However, [1] lists 45 diseases, ``OMIM:101200`` among them.

[1] http://compbio.charite.de/hpoweb/showterm?id=HP:0011304

**Comment by drseb** [comment]
`Apert syndrome` is annotated to `Broad distal phalanx of the thumb`


_p.s.: we can offer professional consulting for your company if required..._

**Comment by rolfschr** [comment]
Ah, ok I see. It uses the transivity like you did for phenotype_to_genes.txt. Thanks, that'll help. Also thank you for your offer.
