### ISSUE TITLE
dump a file of HPO terms that are missing text definitions

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#678]
@drseb 
please create a spreadsheet with the HPO terms that are missing text definitions, and I will draft text defs.

**Comment by drseb** [comment]
https://docs.google.com/spreadsheets/d/1KAyqIVtE9hp8jI_WOv0f5A47W34OB7FvdMH_9XlU-fg/edit?usp=sharing
