### ISSUE TITLE
Optic nerve coloboma HP:0000588

### ISSUE THREAD

**Issue by kanems** [obophenotype/human-phenotype-ontology#6807]
I am wondering about the synonyms on Optic nerve coloboma HP:0000588
Is "Optic disk[disc] coloboma" truly  synonymous with optic nerve coloboma? If not, this may be contributing to UMLS mixing the nerve/disc concepts on the same CUI (Coloboma of optic disc C0155299)

**Comment by pnrobinson** [comment]
I had a look at this and I think that clinically one does not distinguish between these two phrases, see https://en.wikipedia.org/wiki/Coloboma_of_optic_nerve and https://www.ncbi.nlm.nih.gov/books/NBK532877/. Therefore, I think we can maintain the current synonyms.

**Comment by psergouniotis** [comment]
hi. sorry for the late reply. I agree that those should be synonyms. 
Given the UMLS approach, I think the primary term for HP:0000588 should be "Optic disc coloboma" with "optic nerve coloboma" as a synonym. 
many thanks

**Comment by pnrobinson** [comment]
thanks, I made Optic disc coloboma the preferred label as recommended
