### ISSUE TITLE
Missing QC: double spaces in `rdfs:comment`

### ISSUE THREAD

**Issue by matentzn** [obophenotype/human-phenotype-ontology#6813]
If you don't want to do it, I can @drseb, just assign in back.

**Comment by drseb** [comment]
Hmm. I thought it is already checked, but maybe I skipped „comments“

**Comment by drseb** [comment]
@matentzn : comments are translated to obo, right?

**Comment by drseb** [comment]
I see the problem now. Only labels, synonyms, and definitions are checked. Where would you add the check @matentzn  if I would assign back to you?

**Comment by matentzn** [comment]
There are two places the check could be done:
1) In your OBO QC pipeline
2) In a custom sparql qc check. 

Both are easy enough - The latter will take me 5 min, the former about 30 (to get acquainted with the code)

Comments are translated from rdfs:comment to `comment` in OBO format!

**Comment by pnrobinson** [comment]
@drseb @matentzn is this still open?

**Comment by matentzn** [comment]
Yeah, if @drseb agrees I can fix it in a few seconds using SPARQL, unless he wants to add this to his Java QC.

**Comment by matentzn** [comment]
Done, thanks!
