### ISSUE TITLE
Hypoplasia of the cerebellar vermis is specific type of Hypoplasia of the cerebellum

### ISSUE THREAD

**Issue by DLewisSmith** [obophenotype/human-phenotype-ontology#6815]
**HPO term**
Cerebellar vermis hypoplasia HP:0001320

**Suggested revision and reasons**

Add second parent:

Cerebellar hypoplasia HP:0001321
(supplementing: Aplasia/Hypoplasia of the cerebellar vermis HP:0006817)

I think in #6742 I confused term names with their IDs when making multiple submission as part of the batch of cerebellar revisions. Apologies

**Comment by pnrobinson** [comment]
thanks, added!
