### ISSUE TITLE
Unilateral perisylvian polymicrogyria is a form of Unilateral polymicrogyria

### ISSUE THREAD

**Issue by DLewisSmith** [obophenotype/human-phenotype-ontology#6816]
**HPO term**
Unilateral perisylvian polymicrogyria HP:0032406

**Suggested revision and reasons**
Add second parent:
Unilateral polymicrogyria HP:0006927

because Unilateral perisylvian PMG is not only perisylvian but unilateral.

**Comment by pnrobinson** [comment]
thanks, added.
