### ISSUE TITLE
Mandibulofacial dysostosis HP:0005321

### ISSUE THREAD

**Issue by kanems** [obophenotype/human-phenotype-ontology#6818]
**HPO term**
Mandibulofacial dysostosis HP:0005321

**Bug description**

It is possible to remove "Treacher Collins syndrome" as  syn on this phenotype? Or if the goal is to not be redundant between HPO and Mondo, then it seems this term is already represented there? MONDO:0015483 (Certainly TCS already is there- MONDO:0002457)

**Comment by pnrobinson** [comment]
This synonym is already used -- https://hpo.jax.org/app/browse/term/HP:0005321
The term is used in the literature and so is kept in the HPO but it is a so-called bundled term that represents many individual abnormalities and for new annotations we would recommend using the specific abnormalities. The definition of the term provides some guidance.
