### ISSUE TITLE
Unsure about synonym for HP_0100603 Toxemia of pregnancy

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#683]
Is this synonym correct:
Hypertensive disorder of pregnancy

seems like it may be a consequence of toxemia, but not a proper synonym

**Comment by drseb** [comment]
lets review http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3279097/

**Comment by nicolevasilevsky** [comment]
You're right, my bad. Closing.
