### ISSUE TITLE
New term request : Purpura fulminans

### ISSUE THREAD

**Issue by lcdaugherty** [obophenotype/human-phenotype-ontology#684]
Add new subclass Purpura fulminans (syn: Purpura gangrenosa) to superclass Purpura HP:0000979

- Purpura HP:0000979
--Anaphylactoid purpura HP:0200144
--Purpura fulminans HP: new

**Comment by pnrobinson** [comment]
Purpura Fulminans is a disease entity and thus should not be an HPO term, rather it should be a disease term. I have sent a request to Disease Ontology. Anaphylactoid purpura is also not a good HPO term, and we will obsolete it.
