### ISSUE TITLE
Stereotypy: behavior/behaviors/behaviour/behaviours

### ISSUE THREAD

**Issue by pdl** [obophenotype/human-phenotype-ontology#6844]
**HPO term**
Stereotypy https://hpo.jax.org/app/browse/term/HP:0000733

**Synonym to be added**
All four of behavior/behaviors/behaviour/behaviours should be present for:

- Stereotyped behavior
- Stereotypic behavior
- Stereotyped, repetitive behaviour (note this exists in BrE only currently)
- Repetitive or self-injurious behavior
- Stereotypical motor behavior

**broad/exact/narrow/plural/abbreviation ?**
Plural, British/American English Exact

**Comment by drseb** [comment]
Ping @matentzn : should your script be able to find all of those?

**Comment by matentzn** [comment]
You mean the british english spelling script - it would catch the `ou` s, but not the plural forms. These need to be curated, or we need another pipeline.

**Comment by pnrobinson** [comment]
adding, but not Repetitive or self-injurious behavior, which is not a synonym
