### ISSUE TITLE
Hemolytic-uremic syndrome HP:0005575

### ISSUE THREAD

**Issue by RichardKlaus** [obophenotype/human-phenotype-ontology#6869]
**HPO term**
Hemolytic-uremic syndrome HP:0005575

**Suggested revision of textual definition**
Currently no definition exits.

Definition: 
A thrombotic microangiopathy with presence of non-immune, intravascular hemolytic anemia, thrombocytopenia and acute kidney injury. A vicious cycle of complement activation, endothelial cell damage, platelet activation, and thrombosis is the hallmark of the disease.

Synonyms: 
HUS

Source: PMID: 19846853, PMID: 28416508

Furthermore I would like to add three subterms (I also created seperate issues for them

2.	Shiga-toxin-related hemolytic-uremic syndrome (New term)
Synonyms: typical HUS, STEC-HUS, Shiga-toxin-associated HUS
Definition: A form of hemolytic-uremic syndrome induced by Shiga-toxin, typically a few days after gastrointestinal infection with Shiga-toxin producing Escherichia coli. Shiga toxin binds cell membrane glycolipid Gb3 on the endothelium and causes damage to or activation of endothelium, red cells, and platelets and thereby initiates the disease process.
Source: PMID: 19846853, PMID: 28416508
Mother term: Hemolytic-uremic syndrome HP:0005575

3.	Atypical hemolytic-uremic syndrome (New term)
Synonym: aHUS, familial HUS, genetic HUS
Definition: Genetic or acquired defect in regulation of complement activation leading to complement overactivation.
Source: PMID: 19846853, PMID: 28416508
Mother term: Hemolytic-uremic syndrome HP:0005575
Related Genes: CFH, CFH/CFHRs, CFHR1/CFHR3, CFHR1/CFHR4, MCP, CFI, C3, CFB, THBD, DGKE 
 
4.	Secondary hemolytic-uremic syndrome (New term)
Definition: HUS initiated by a coexisting disease or condition. The most frequently reported diseases that lead to clinically evident secondary HUS include infections, especially those caused by Streptococcus pneumoniae and the influenza virus. Secondary HUS may be associated with transplantation (solid organ or bone marrow), autoimmune disease, cancer, pregnancy and the use of certain cytotoxic drugs (e.g. calcineurin-inhibitors).
Source: PMID: 19846853, PMID: 28416508
Mother term: Hemolytic-uremic syndrome HP:0005575

**Comment by pnrobinson** [comment]
thanks, added
