### ISSUE TITLE
New Disease-Phenotype Annotation for HP:0011533 (Snowflake vitreoretinal degeneration)

### ISSUE THREAD

**Issue by azankl** [obophenotype/human-phenotype-ontology#6874]
[HP:0011533 (Snowflake vitreoretinal degeneration)](https://hpo.jax.org/app/browse/term/HP:0011533)
is associated with
[VITREORETINAL DEGENERATION, SNOWFLAKE TYPE; SVD (OMIM: 193230)](https://www.omim.org/entry/193230)
based on [PMID:18179896](https://pubmed.ncbi.nlm.nih.gov/18179896/)

Sorry, could not find a template for new Disease-Phenotype associations.

**Comment by pnrobinson** [comment]
thanks, added this annotation
