### ISSUE TITLE
Missing 'New Annotation' Template

### ISSUE THREAD

**Issue by azankl** [obophenotype/human-phenotype-ontology#6875]
According to [this](https://hpo.jax.org/app/help/collaboration), there should be a template to submit new Disease Annotations, but I cannot find it.

**Comment by drseb** [comment]
Thanks! Great suggestion

**Comment by pnrobinson** [comment]
Hi @azankl  we are just about to publish a web-based annotation tool that can be used to suggest new annotations, that will make it a lot easier for us to collaborate with others on extending the HPO annotation base. We are in the final stages of testing and it might be public in about one month.We would love to have your collab for skeletal diseases. We will be revising the documentation then, so prob it is easier not to change the current documentation just for one month.

**Comment by azankl** [comment]
Hi @pnrobinson, would be keen to try out your new annotation tool!

**Comment by drseb** [comment]
I added the new issue template since the new tool is not there yet and also to make it possible for users to not have to use yet another tool. Thanks, @azankl for flagging this inconsistency on the hpo website.
