### ISSUE TITLE
Harmonise logical definitions of "Calcified Anatomy" terms

### ISSUE THREAD

**Issue by matentzn** [obophenotype/human-phenotype-ontology#6877]
@pnrobinson  @nicolevasilevsky  @LCCarmody I invited you to work on the calcification phenotypes here:
https://docs.google.com/spreadsheets/d/1IMSucZiqWYfPvp-m2x74IcE84xXV57mzz9rSNYZQLbc/edit#gid=0

Basically what I need to proceed:

1. an anatomical entity in every row C 
2. I dont care about D, but i suggest you also do that to make reviewing this easier
3. For punctate and similar calcification, fill in E (not for simple calcifications!)
4. Not necessary, but for transparency, I would like the pattern name in the G column. If too much work, no need!

What is in that table? 
1. Every phenotype that has "calcif" in the label
2. Every phenotype that currently matches ["calcifiedAnatomicalEntity" pattern ](https://raw.githubusercontent.com/obophenotype/upheno/master/src/patterns/dosdp-dev/calcifiedAnatomicalEntity.yaml)

So there will be some calcification phenotypes missing (those that don't have calcif in the name. If you see them when playing around, just add them to the table. Good luck and let me know when its done!

_Originally posted by @matentzn in https://github.com/obophenotype/human-phenotype-ontology/issues/4844#issuecomment-773238940_

Action items (in that order)
- [x] @LCCarmody to finish table as far as she can
- [X] @LCCarmody @matentzn Update/add definitions of calcifiedAnatomicalEntity in HPO
- [X] Add pattern calcifiedAnatomicalEntityByCalcificationPattern
- [x] @LCCarmody submit pattern to uPheno
- [x] @LCCarmody [add this](https://docs.google.com/spreadsheets/d/1IMSucZiqWYfPvp-m2x74IcE84xXV57mzz9rSNYZQLbc/edit#gid=0) to our meeting minutes TODO

**Comment by pnrobinson** [comment]
any progress here? @LCCarmody @matentzn  -- I'd love to clean up all of the old issues!

**Comment by matentzn** [comment]
Removing EQs without replacement:
Missing pattern and/of Uberon terms:
- HP:0004966 (Medial calcification of large arteries): No way to express "large arteries"


I think there are still some uncertainties in that spreadsheet. @LCCarmody can you separate the questions by domain:
- Questions of the kind "is this the right Uberon term" (uPheno repo issue)
- Questions of the kind "is this the right PATO term" (uPheno repo issue)
- Other questions: Email to hpo editors list. 

Action item: 
- [ ] @LCCarmody to tell Nico when the spreadsheet has no more uncertainties or comments in it :)

Thanks!

**Comment by LCCarmody** [comment]
Don't think we will make EQs for the following terms because it may take too much time to determine subcategories.
<google-sheets-html-origin><style type="text/css"></style>

-- | --
HP:0012457 | Medial calcification of medium-sized arteries
HP:0012458 | Medial calcification of small arteries
HP:0031301 | Peripheral arterial calcification
HP:0031302 | Lower extremity peripheral arterial calcification
HP:0004966 | Medial calcification of large arteries

**Comment by matentzn** [comment]
@pnrobinson please check whether the following anatomy assignments are reasonable for the EQs:

- [ ] HP:0007045 | Midline brain calcifications | UBERON:1000009 | midline crest
- [ ] HP:0007346 | Subcortical white matter calcifications | UBERON:0011299 | white matter of telencephalon
- [ ] HP:0031306 | Intracranial arterial calcification | UBERON:0011362 | cranial blood vasculature??
- [ ] HP:0025477 | Periarticular calcification | UBERON:0000982 | skeletal joint

**Comment by LCCarmody** [comment]
After discussion with @matentzn, decided not to patternize 
<google-sheets-html-origin><style type="text/css"></style>

Modifier |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | --
HP:0006906 | Congenital intracerebral calcification | UBERON:0001893 | telencephalon | HP_0003577 | congenital onset | calcifiedAnatomicalEntitybyOnset | Not sure this is worth a pattern
HP:0006694 | Early progressive calcific cardiac valvular disease | UBERON:0000946 | cardial valve | HP_0003676 | progressive | calcifiedAnatomicalEntitybyOnset | There isn't an 'early progressive' term
HP:0005849 | Diffuse cerebral calcification | UBERON:0001893 | telencephalon | PATO:0001566 | distributed | calcifiedAnatomicalEntityByCalcificationType | distributed has 'diffuse' as synonym
HP:0011084 | Hypocalcification of dental enamel | UBERON:0005176 | tooth enamel organ | PATO:0001672 | decreased distribution | calcifiedAnatomicalEntityByCalcificationType | Not sure if this is the correct modifyer
HP:0005671 | Bilateral intracerebral calcifications | UBERON:0001893 | telenceophalon | HP_0012832 | bilateral | calcifiedAnatomicalEntityByPosition | Not sure if this is worth a pattern

**Comment by pnrobinson** [comment]
@matentzn @LCCarmody what is the action item here?

**Comment by matentzn** [comment]
@pnrobinson because I also keep asking that question, I have recently started to encourage the use of checkbox syntax:

- [ ] Example checkbox

To show action items. You can scroll through this ticket and see all of these, on who they are assigned to (some to you!)

**Comment by pnrobinson** [comment]
OK, but note the checkbox syntax is not great if there is a series of questions that require an answer -- see above!

**Comment by matentzn** [comment]
Ah ok, so now its for @LCCarmody do sort this out - I see you edited my comment with your questions. I did not see that before!

**Comment by LCCarmody** [comment]
Hi @matentzn I am not sure what you mean by I edited your comment with my questions. BUT I think this ticket should be closed because we cannot patternize the remaining terms.  Either they are very complicated or there isn't a good term in UBERON (see https://github.com/obophenotype/uberon/issues/1933).

**Comment by dosumis** [comment]
Just looking at this with @rays22  as he's encountered some of these patterns while looking for newuPheno patterns. We'd like to track down: calcifiedAnatomicalEntityByCalcificationPattern.  The checkbox says it's done but a search of the uPheno repo doesn't pull it up.  (This is the reason I don't like checkboxes).

**Comment by matentzn** [comment]
I think thats it: https://github.com/obophenotype/human-phenotype-ontology/blob/master/src/patterns/dosdp-patterns/calcifiedAnatomicalEntityWithCalcificationPattern.yaml

**Comment by dosumis** [comment]
Ta. Assumed it would be on uPheno.

**Comment by matentzn** [comment]
Yeah, that checkbox wasnt checked yet :) @LCCarmody will probably do that at some point?

**Comment by LCCarmody** [comment]
Sorry, still having trouble following this thread. I did read the old comments, but I think my brain is slow. 
What exactly will I do at some point?
Suggestions:
1. implement https://github.com/obophenotype/human-phenotype-ontology/blob/master/src/patterns/dosdp-patterns/calcifiedAnatomicalEntityWithCalcificationPattern.yaml into HPO?
2. implement https://github.com/obophenotype/upheno/issues/813 in upheno? FTR, I've edited upheno patterns, but I am not exactly sure what the action beyond that is. I will comment on that ticket.
3. or check a box?

It seems @rays22  beat me to 2, so maybe he should check the box?

Also, ftr, I finally got a computer that can actually do things...like run releases, etc. So, I will work on updating/editing ontologies soon, but I'm mighty rusty. :)

**Comment by LCCarmody** [comment]
Okay, sorry, finally getting around to adding starting the PR. One question about HP:0007045 | Midline brain calcifications (see above comment). Would this be an appropriate def? or should we leave without a def?
@rays22 @matentzn 

 'has part' some 
    (calcified
     ('medial orientation' and ('characteristic of' some brain)
     and ('has modifier' some abnormal)
     and ('has modifier' some punctate))
     
     where medial orientation is http://purl.obolibrary.org/obo/PATO_0002498

**Comment by matentzn** [comment]
@rays22 can you give it a shot to model as an EQ?

**Comment by rays22** [comment]
Need new UBERON term 'brain midline'?

**Comment by pnrobinson** [comment]
@LCCarmody @rays22 the above definition (April 21) seemed OK -- I do not think that there is actually a defineable and delineable region for brain midline -- it does not seem that it would be a great uberon term

**Comment by LCCarmody** [comment]
Actually, I used the term '[midline crest](https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_1000009)' in pull request #7599, which is defined as "A ridge or peak located along the middle part of the head, located approximately equidistant from the left and the right sides of the head. "

If this is not correct, then it should be edited in the HP--as the pull request was approved. I should have closed this ticket, but I seem to have forgotten.
