### ISSUE TITLE
question about synonym for HP_0001373 Joint dislocation

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#688]
There is a synonym for HP_0001373 Joint dislocation, which is: "dislocations". This seems too broad to me.

**Comment by nicolevasilevsky** [comment]
Another similar example is:
HP_0001324	Muscle weakness
Synonym: weakness

**Comment by drseb** [comment]
I think it is ok to remove them. Can you do that?

**Comment by nicolevasilevsky** [comment]
Will do!
