### ISSUE TITLE
NTR: Abnormalities of Extrarenal Arteries (not sampled by biopsy) (level 3)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#6889]
()

**Comment by pnrobinson** [comment]
@avizrosenberg @yongqunh

This is not a good HPO term because without the context of a kidney biopsy, it could mean any other artery in the body. If there is some other term we could use to cover the things that you mean to cover here, please open a new issue.

**Comment by yongqunh** [comment]
I agree. Extrarenal Arteries = NOT (renal arteries). We don't need the NOT expression here.
