### ISSUE TITLE
Prenatal Phenotypes - Multiple Requests

### ISSUE THREAD

**Issue by CourtneyHum** [obophenotype/human-phenotype-ontology#690]
[Prenatal Term Requests.xlsx](https://github.com/obophenotype/human-phenotype-ontology/files/143398/Prenatal.Term.Requests.xlsx)

I will start making these into separate GitHub issues...just wanted a place to put the spreadsheet

**Comment by pnrobinson** [comment]
I think we have now covered all these terms, thanks very much!
