### ISSUE TITLE
NTR: Abnormalities of arterioles (level 2)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#6916]
An arteriole can be defined as a vessel with no more than 2-3 layers of media, absence of complete internal elastic lamina, and typically with a diameter less than 20% of the glomerular diameter  ()

**Comment by pnrobinson** [comment]
@avizrosenberg @yongqunh

Should we say whether we mean the afferent or the efferent arteriole or does not that matter here?
Also, I would like to name this term

``Abnormal glomerular arteriole morphology``, is that OK?

**Comment by yongqunh** [comment]
I agree. It's good to use singular instead of plural.

**Comment by pnrobinson** [comment]
@avizrosenberg -- what about differentiating between afferent/efferent arterioles - or do they tend to be similarly affected?

**Comment by avizrosenberg** [comment]
They are hard to distinguish histological PY

**Comment by pnrobinson** [comment]
OK, thanks! I will add a corresponding comment. Adding this.

**Comment by pnrobinson** [comment]
Abnormal renal arteriole morphology
def -- Any structural anomaly of the glomerular arterioles. The interlobar arteries of the kidney branch into arcuate arteries, cortical radiate arteries, and then into afferent arterioles. After passing through the renal corpuscle, the capillaries form the efferent arteriole. The afferent and efferent arterioles are difficult to distinguish histologically and are thus both included in this term and its descendents.
