### ISSUE TITLE
NTR: Abnormalities of Extrarenal Veins (not sampled by biopsy) (level 3)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#6943]
Veins located outside the kidney parenchyma  ()

**Comment by pnrobinson** [comment]
@avizrosenberg @yongqunh
similarly to the extrarenal artery, this is not a good HPO term (because it could be any vein in the body). If there are specific items that are needed, please make new term requests.

**Comment by yongqunh** [comment]
I agree on this.
