### ISSUE TITLE
NTR: Medullary angiitis within peritubular capillaries (level 5)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#6974]
Interstitial hemorrhage with associated neutrophil infiltration and karyorrhectic debris  ()

**Comment by pnrobinson** [comment]
@avizrosenberg @yongqunh

according to this
https://pubmed.ncbi.nlm.nih.gov/23079202/

"Renal medullary angiitis is a lesion involving the vasa recta of the medulla."

To my knowledge the peritubular capillaries are close to but distinct from the vasa recta.

Would it be better to name this term "Renal medullary angiitis" and to modify the definition or is this term something different?

**Comment by pnrobinson** [comment]
@avizrosenberg @yongqunh can you comment on this question? :smile:

**Comment by avizrosenberg** [comment]
I will need to mull on this.

Actually has been a point of discussion recently with some of our vasculitis colleagues 

Avi

**Comment by pnrobinson** [comment]
@avizrosenberg any update on this?

**Comment by pnrobinson** [comment]
@avizrosenberg  ping!

**Comment by pnrobinson** [comment]
@avizrosenberg I will close this for now. We are going to be doing a lot more work on kidney pathology and may be scheduling a workshop in Berlin at some point in the next year or two, it would be great to have your attendance and it is probably easier to deal with really detailed terms like this in the setting of a workshop.

**Comment by avizrosenberg** [comment]
I very much look forward to participating in the workshop!Sent from my iPhoneOn Feb 24, 2024, at 04:17, Peter Robinson ***@***.***> wrote:﻿
@avizrosenberg I will close this for now. We are going to be doing a lot more work on kidney pathology and may be scheduling a workshop in Berlin at some point in the next year or two, it would be great to have your attendance and it is probably easier to deal with really detailed terms like this in the setting of a workshop.

**Comment by yongqunh** [comment]
Based on the paper (https://pubmed.ncbi.nlm.nih.gov/23079202/), it appears that we can rename the term to "Renal medullary angiitis" and then update it's definition. 
Based on wiki: 
https://en.wikipedia.org/wiki/Vasa_recta_(kidney)
"The vasa recta of the kidney are the straight arterioles, and the straight venules of the kidney – a series of blood vessels in the blood supply of the kidney that enter the medulla as the straight arterioles, and leave the medulla to ascend to the cortex as the straight venules."
It is possible that "Medullary angiitis within peritubular capillaries" is a subclass of "Renal medullary angiitis" if the two have different meanings.

I would also like to participate in the workshop in Berlin ! 
Thanks!

**Comment by avizrosenberg** [comment]
these should be synonymous

Avi
