### ISSUE TITLE
Typo in synonym SSRS for Steroid-resistant nephrotic syndrome?

### ISSUE THREAD

**Issue by LM-Ontologies** [obophenotype/human-phenotype-ontology#6977]
**HPO term**

HP:0012588: Steroid-resistant nephrotic syndrome

https://hpo.jax.org/app/browse/term/HP:0012588

**Bug description**

Steroid-resistant nephrotic syndrome entry contains the synonym 'SSRS'. Should this instead be 'SRNS'?

**Comment by nicolevasilevsky** [comment]
Good catch, I will fix
