### ISSUE TITLE
Autonomic epileptic aura and Focal autonomic seizure

### ISSUE THREAD

**Issue by DLewisSmith** [obophenotype/human-phenotype-ontology#6981]
**HPO term**
Autonomic epileptic aura HP:0033722
Focal autonomic seizure HP:0011154

**Suggested revision and reasons**
Focal autonomic seizure HP:0011154 should **not** be child of Epileptic aura HP:0033348 as many Focal autonomic seizures are not purely subjective (required to be called an aura). Focal autonomic seizure HP:0011154 should be a child of Focal non-motor seizure HP:0032679, only.

Autonomic epileptic aura HP:0033722 should be a child of Focal autonomic seizure HP:0011154 (in addition to Epileptic aura HP:0033348) as Autonomic epileptic auras are purely subjective forms of Focal autonomic seizure.

@pnrobinson you may still have an email from me with graphical representation of the above sent 2020-11-29.

**Comment by pnrobinson** [comment]
thanks, done!
