### ISSUE TITLE
hypoplastic vs absent nasal bone

### ISSUE THREAD

**Issue by BimalChaudhari** [obophenotype/human-phenotype-ontology#6987]
**HPO term**
HP:0011430

**Suggested revision and reasons**
I suggest distinguishing hypoplastic nasal bone (<2.5%ile but detectable) from ABSENT nasal bone but making both terms children of a new term 'abnormality of fetal nasal bone' or similar which would be a child of 'fetal ultrasound soft marker'
https://doi.org/10.1016/j.ajog.2019.08.049

**Comment by patt1morgan** [comment]
@Shagun1976, @fcradio, @Green-eve. Thank you for agreeing to work with us to advance the perinatal section of the HPO. We would appreciate it if you could review this new term request and approve it or help us improve it. Any suggestions welcome!

**Comment by pnrobinson** [comment]
terms added as suggested
