### ISSUE TITLE
New term - premature atrial contractions

### ISSUE THREAD

**Issue by CourtneyHum** [obophenotype/human-phenotype-ontology#699]
**Proposed definition:** premature heartbeats originating in the atria

**Synonyms:** PACs, atrial premature complexes

**Superclass:** HP:0011675 arrhythmia

Could also consider inserting a class in between arrythmia and premature atrial contractions called "ectopic beats" because both premature atrial contractions and premature ventricular contractions (HP:0006682) could be under the "ectopic beats" class

**Comment by pnrobinson** [comment]
There already was an HPO class called Ectopic supraventricular rhythms which is synonymous. I have changed the name to PAC and added a definition.
