### ISSUE TITLE
MedDRA to HP cross-references

### ISSUE THREAD

**Issue by ireneisdoomed** [obophenotype/human-phenotype-ontology#6999]
Hi,

from an analysis of FAERS data, we have obtained a list of over 1,200 MedDRA to HP mappings that we believe have a very high level of confidence:
[meddra-hp-xref-0995-1.json.zip](https://github.com/obophenotype/human-phenotype-ontology/files/6585952/meddra-hp-xref-0995-1.json.zip)

This is part of an emerging pipeline we are working on to integrate the different methods of automatic disease mapping into a single tool.

The algorithm performs very well as long as it is already captured in the ontology. However, we are aware of a systemic error when the MedDRA label refers to a less common/more severe disorder in a set of diseases and we map it to the closest EFO term, e.g:
```
{"traitId":"10032168","traitName":"Other insomnia","score":1,"efoId":"EFO_0004698","efoName":"insomnia"}
{"traitId":"10031712","traitName":"Other cardiovascular syphilis","score":0.999,"efoId":"EFO_1001206","efoName":"syphilitic aortitis"}
{"traitId":"10032033","traitName":"Other endocarditis","score":1,"efoId":"EFO_0000465","efoName":"endocarditis"}
```

Could you please examine the mappings and consider how best to include this annotation in the ontology? The SPOT team has already imported the MedDRA xrefs whose labels match an EFO/Orphanet term and are now in the process of curating the ones of less confidence. Both EFO and Open Targets would benefit a lot if you could include them similarly.

Any feedback or comments is much appreciated.

Thanks!

**Comment by matentzn** [comment]
@ireneisdoomed That is great! I am also very interested in consolidating disease mappings across the board, see for example [here.](https://github.com/monarch-initiative/mondo/tree/sssom-rewrite/src/ontology/mappings)

If you are interested to collaborate on the effort, I am very happy to (working always closely with EFO team, and sometimes David, Daniel and Miguel from Open Targets). 

 We are developing a whole ecosystem around the dissemination of mappings building a community standard [here](https://github.com/mapping-commons/SSSOM/blob/master/SSSOM.md), which we are also working on integrating wit OxO. 

Our main focus so far has been phenotype mappings, see for example [here](https://github.com/mapping-commons/mh_mapping_initiative), but we are really.. ehem, primitive, on the side of automated matching algorithms at the moment (working hard to change that, but I am sure you could teach us a great deal). Anyways, let me know if you are interested to talk, one way or another I would like to follow what you are doing!

**Comment by drseb** [comment]
We already have a hpo-meddra mapping. Did you check that before? 

https://github.com/obophenotype/human-phenotype-ontology/tree/master/src/mappings

**Comment by pnrobinson** [comment]
@ireneisdoomed -- the HPO has been incorporated into the UMLS, and so this will be the easiest place to get HPO-Meddra mappings
https://www.nlm.nih.gov/research/umls/sourcereleasedocs/current/HPO/metarepresentation.html
We need to provide better ways or how-tos of how to access the various mappings in the future, but I cannot give a date.
Please reopen this issue if the UMLS mappings do not provide what you need.
