### ISSUE TITLE
Abnormal anatomic location of the heart

### ISSUE THREAD

**Issue by sbello** [obophenotype/human-phenotype-ontology#7001]
**HPO term**
Abnormal anatomic location of the heart (HP:0004307) has the definition "Thickening of the left ventricle wall with congenital onset." I don't think this is the correct definition for this term. 

I would have expected a definition more along the lines of "the heart is displaced from the normal left-sided position and/or orientation" based on the term label (definition lifted from the MP term abnormal heart position or orientation (MP:0006065)) I'm basing this on both the term label and the child terms which overlap broadly with the child terms of the MP term.

**Comment by pnrobinson** [comment]
@sbello thanks for pointing out this error. Corrected!
