### ISSUE TITLE
Synonyms ending with period character

### ISSUE THREAD

**Issue by matentzn** [obophenotype/human-phenotype-ontology#7014]
To improve our QC, we want to introduce a check that ensures no synonym ends with a period. To merge this, we need the following to be fixed:

x,label,syn_type
- [x] HP:0011089,"The fusion can be complete or be limited to the crown or the root. Typically, incisors and canines form double teeth. Double teeth are more common in the deciduous dentition and rare in the permanent dentition. Double teeth encompasses fusion, concrescence, and gemination of teeth, which some authors describe with the twinning.",oio:hasExactSynonym
- [x] HP:0025058,Partial or complete wasting (loss) of hypothalamus tissue that was once present.,oio:hasExactSynonym
- [x] HP:0025200,Accumulation in muscle cells of filaments composed of actin.,oio:hasExactSynonym
- [x] HP:0025458,CSF albumin level is below the lower limit of normal.,oio:hasExactSynonym
- [x] HP:0025574,Bleeding occurring within the macula lutea of the retina.,oio:hasExactSynonym
- [x] HP:0025636,Endometrial inflammation.,oio:hasExactSynonym
- [x] HP:0031509,Abnormally dry skin in the area of the nipple of the breast.,oio:hasExactSynonym
- [x] HP:0031625,A contained rupture of an artery with a disruption in all 3 layers of the arterial wall.,oio:hasExactSynonym
- [x] HP:0032098,A reduction below the normal concentration of manganese in the blood.,oio:hasExactSynonym
- [x] HP:0032164,"An elevated circulating concentration of folic acid, which is also known as vitamin B9.",oio:hasExactSynonym
- [x] HP:0032205,An increased circulation of galectin-3 in the blood circulation.,oio:hasExactSynonym
- [x] HP:0032342,An abnormal reduction in the amount of air a person can forcefully expel in one second.,oio:hasExactSynonym
- [x] HP:0032511,The position of the umbilicus (belly button) is abnormally high (superior).,oio:hasExactSynonym
- [x] HP:0033095,An elevated level of a sulfur-containing amino acid in the urine.,oio:hasExactSynonym
- [x] HP:0033096,An elevated level of an aspartate family amino acid in the urine.,oio:hasExactSynonym
- [x] HP:0033145,Elevated concentration of ceruloplasmin in the blood circulation.,oio:hasExactSynonym
- [x] HP:0033169,Abnormally reduced volume of air in the lungs upon the maximum effort of inspiration.,oio:hasExactSynonym
- [x] HP:0033181,A severe pyogenic infection of the epidural space.,oio:hasExactSynonym
- [x] HP:0033464,Increased concentration of 3-hydroxypalmitoleylcarnitine in the blood circulation.,oio:hasExactSynonym
- [x] HP:0033551,A granuloma located in the lung that is not associated with necrotic changes.,oio:hasExactSynonym
- [x] HP:0033793,Applies to a sign or symptom that is provoked or brought about by eating a certain food.,oio:hasExactSynonym
- [x] HP:0033848,Wernicke aphasia.,oio:hasExactSynonym
- [x] HP:0040164,Fatty tumors on the eyelids.,oio:hasExactSynonym
- [x] HP:0040164,Fatty tumours on the eyelids.,oio:hasExactSynonym
- [x] HP:0100543,"An individual with cognitive impairment may have trouble remembering, learning new things, concentrating, or making decisions.",oio:hasExactSynonym
- [x] HP:0410051,An increase in the level of 3-hydroxy-3-methylglutaric acid in the urine.,oio:hasExactSynonym
- [x] HP:0410358,An abnormal decrease in the concentration of high-mannose N-glycans on glycoproteins.,oio:hasExactSynonym
- [x] HP:0500104,Reduced diastolic blood pressure.,oio:hasExactSynonym
- [x] HP:0500229,Abnormal glycine levels in cerebrospinal fluid.,oio:hasExactSynonym

**Comment by pnrobinson** [comment]
Fixed. Most were definitions or comments -- Protege does not make it easy to enter things in the right place <sigh>. Some were synonyms with trailing periods.
