### ISSUE TITLE
Periventricular white matter hyperdensities HP:0030891

### ISSUE THREAD

**Issue by DLewisSmith** [obophenotype/human-phenotype-ontology#7019]
**HPO term**
Periventricular white matter hyperdensities HP:0030891

**Suggested revision of textual definition**

I suggest using the current synonym "Periventricular white matter hyperintensities" as the preferred name to be consistent with parents and children. MRI measures T2 and T1 weighted signals (and a few variations of these) where as density is measured by CT. Density and T2 signal do not necessarily correlate.

**Comment by pnrobinson** [comment]
This was a mistake. I will go through the annotations and then relabel.

**Comment by pnrobinson** [comment]
thanks for pointing this out, I have fixed it.
