### ISSUE TITLE
Subependymal pseudocyst

### ISSUE THREAD

**Issue by patt1morgan** [obophenotype/human-phenotype-ontology#7029]
**HPO term**  Subependymal cysts HP:0002416

**Synonym to be added**
Subependymal pseudocyst, also subependymal germinolytic cyst  
PMID:12423490,PMID: 3907508

**broad/exact/narrow/plural/abbreviation ?**

**Comment by pnrobinson** [comment]
Subependymal pseudocysts (also known as subependymal germinolytic cysts) are cerebral cysts, usually located in the wall of the caudatenucleus or in the caudothalamic groove. They are found in up to 5% of all neonates, using transfontanellar ultrasound in the first days of life. Pseudocysts are likely to result from a remnant germinative zone, which normally disappears by the time the baby is delivered, and this could explain why they are found more often in preterm neonates. Pseudocysts have been described in the neonatal period. 
PMID:12423490
Comment: Isolated subependymal cysts regress spontaneously and their prognosis is good. Associated cerebral or morphological abnormalities carry a poor prognosis as they are suggestive of vascular disorders (hemorrhage or infarction), infections (cytomegalovirus, rubella) or chromosomal abnormalities. The neurological outcome is poor in these cases.
