### ISSUE TITLE
CCTGA

### ISSUE THREAD

**Issue by patt1morgan** [obophenotype/human-phenotype-ontology#7034]
**HPO term**Congenitally corrected transposition of the great arteries HP:0011540

**Synonym to be added**  CCTGA, also seen as ccTGA   PMID: 32274202 ,PMID: 27777298 

**broad/exact/narrow/plural/abbreviation ?** abbreviation

**Comment by pnrobinson** [comment]
@patt1morgan  Thanks! Added.
