### ISSUE TITLE
Vasa Previa

### ISSUE THREAD

**Issue by patt1morgan** [obophenotype/human-phenotype-ontology#7048]
**HPO term**Abnormal insertion of umbilical cord HP:0011418

**Suggested revision and reasons**  Vasa previa is listed as a synonym for abnormal insertion of the umbilical cord.  I believe it should be listed as a child of abnormal insertion of the umbilical cord.
Definition of vasa previa- Occurs when the membranes that contain the umbilical cord traverse the membranes overlying the internal os of the cervix.  There is a high risk of fetal mortality if not identified perinatally.  PMID: 32028503
Comment: This  abnormality is problematic because of the location of the unprotected vessels. If the fetal head compresses these vessels, it can result in fetal hypoperfusion and acidemia. If the vessels rupture it can  lead to fetal hemorrhage   PMID: 33880195

**Comment by pnrobinson** [comment]
Thanks, @patt1morgan , I made this change.
