### ISSUE TITLE
Refractory drug response implies Refractory

### ISSUE THREAD

**Issue by DLewisSmith** [obophenotype/human-phenotype-ontology#7064]
**HPO term**
Refractory drug response HP:0020174
Refractory HP:0031375

**Suggested revision and reasons**
Should Refractory drug response HP:0020174 have Refractory HP:0031375 as a second parent (in addition to existing parent Abnormal drug response HP:0020169)?

I am also not entirely sure that Refractory drug response HP:0020174 per se should necessarily be considered a type of Abnormality of metabolism/homeostasis HP:0001939. A person's illness may be refractory to a particular drug because the drug does not target the specific mechanism of disease in them. For example, sodium channel blockers tend to be inefficacious for seizures in Dravet syndrome because in Dravet syndrome it is the loss of function of the sodium channel that results in the disease so further blockade of sodium channels is not beneficial (in fact it can exacerbate the seizures). In this case should the refractory response to sodium channel blockers be considered an abnormality of metabolism/homeostasis when the person is probably metabolising the drug the same way as anyone else?

**Comment by pnrobinson** [comment]
@DLewisSmith  The modifier terms such as Refractory essentially form a separate ontology. Some of the "main" HPO terms include descriptors such as in this case that are equivalent. It looks as if we are getting funding from NIH for HPO as a resource and if so we will be including pharmacology as one of ten topics (neurodev also). I would suggest that for now we leave as is, but I agree we need to work on this section!
