### ISSUE TITLE
New term - intrathoracic teratoma

### ISSUE THREAD

**Issue by CourtneyHum** [obophenotype/human-phenotype-ontology#707]
**Superclass:** teratoma (HP:0009792); abnormality of the thorax (HP:0000765)

**Comment by pnrobinson** [comment]
Since there are a number of teratomas within the thorax (e.g., the HPO has already cardiac teratoma), I wonder if we could make this more specific. Do you mean mediastinal teratoma?

**Comment by CourtneyHum** [comment]
@pnrobinson Yes! Mediastinal to be precise
