### ISSUE TITLE
NIH clinical trials age definition and HPO (and Hsapdv.obo) alignment

### ISSUE THREAD

**Issue by ANiknejad** [obophenotype/human-phenotype-ontology#7089]
sorry in advance for this issue, just needing to report these NIH definitions of age group, that obviously does not fit our Bgee hsapdv.obo and HPO current definitions, right?

https://clinicaltrials.gov/ct2/about-studies/glossary

Age or age group
    A type of eligibility criteria that indicates the age a person must be to participate in a clinical study. This may be indicated by a specific age or the following age groups:

    The age groups are:

        Child (birth-17)
        Adult (18-64)
        Older Adult (65+)

**Comment by pnrobinson** [comment]
Hi again @ANiknejad  I think that there is no way to accommodate additional definitions. Please note however that for recording data about an individual patient we would recommend the new GA4GH Phenopacket format -- this allows a much more flexible representation of age and time.
https://phenopacket-schema.readthedocs.io/en/latest/
