### ISSUE TITLE
Typo in HPO annotation file for presence of *epicanthus* in *Al Kaissi syndrome*

### ISSUE THREAD

**Issue by ielis** [obophenotype/human-phenotype-ontology#7094]
**HPO term**

- [Al Kaissi syndrome (OMIM:617694)](https://hpo.jax.org/app/browse/disease/OMIM:617694) 
- [Epicanthus](https://hpo.jax.org/app/browse/term/HP:0000286)

**Bug description**

Frequency of *Epicanthus* reported for [Al Kaissi syndrome (OMIM:617694)](https://hpo.jax.org/app/browse/disease/OMIM:617694) is **9/7**. This is most likely a typo, since the Table 1 in the [source](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5591019/) lists presence of *Bilateral epicanthal folds* for **9/9** individuals with *CDK10* mutations.

**Comment by ielis** [comment]
The same applies for:

- *Hypertonia* reported for [Neurodevelopmental Disorder With Dysmorphic Features, Spasticity, And Brain Abnormalities](https://hpo.jax.org/app/browse/disease/OMIM:615802), where the frequency should be (likely) changed from **2/1** to **1/2**. 
Patient 1 - *... She showed a tonus regulation disorder with hypertonia in the beginning up to age 2 years and later significant hypotonia...*. No hypertonia is mentioned for Patient 2.
- *Elevated urinary delta-aminolevulinic acid* reported for [Coproporphyria](https://hpo.jax.org/app/browse/disease/OMIM:121300), where the frequency should be changed to *4/6*, considering that Father, Patient, Brother 1, and Sister had level of delta aminolevulinic acid above normal (Table 1)

**Comment by pnrobinson** [comment]
@ielis Thanks for pointing out these errors, I have just fixed them.
