### ISSUE TITLE
Possibly revise label for "originates from" ?

### ISSUE THREAD

**Issue by ddooley** [obophenotype/human-phenotype-ontology#7099]
The "position" qualities encode spatial object relations, which is fine, though it suggests that many of those qualities attach between objects in a complementary way ( e.g. 'adjacent to').  But I'm just interested in "originates from" whose label belies a more specific meaning - its positional quality.  Perhaps that quality could be renamed "position originates from" or "originates from position"?  My motivation is that FoodOn is considering asking for an object relation "originates from" that connects between an entity and another entity it originates from via some processing or no processing at all but just a reference to a part of a whole without implying the whole. E.g. " 'whole apple' 'originates from' exactly 1 'pome fruit' ".

**Comment by pnrobinson** [comment]
@ddooley I am not sure which term this refers to, could you clarify please?

**Comment by ddooley** [comment]
OMG! I mistook PATO and HPO github repos !  Apologies!
