### ISSUE TITLE
New term - ectopic liver

### ISSUE THREAD

**Issue by CourtneyHum** [obophenotype/human-phenotype-ontology#710]
**Superclass:** abnormality of the liver (HP:0001392)

**Comment by pnrobinson** [comment]
Reconsider definition (see http://link.springer.com/article/10.1007%2Fs10620-005-2944-7#page-2)

**Comment by CourtneyHum** [comment]
Ah I see. I had, incorrectly, assumed that it was analgous to an ectopic kidney. But ectopic liver is present in addition to what some refer to as the "mother"  liver. 

How do you feel about taking the first line as the definition: **autonomous islands of normal liver parenchyma located outside the liver**

**Comment by pnrobinson** [comment]
Def: Ectopic liver is a rare developmental anomaly in which liver tissue is situated outside the liver. Thus, ectopic liver refers to  autonomous islands of normal liver parenchyma located outside the liver.  The term "ectopic liver" is also used, to include liver appendices attached to the native liver by a thin stalk although being fully separated from the latter PMID:    637502,    11988792
syn: Choristoma
Comment: Ectopic liver tissue can occur in several different organs, but the gallbladder is the commonest site of origin.
