### ISSUE TITLE
New term - megalourethra

### ISSUE THREAD

**Issue by CourtneyHum** [obophenotype/human-phenotype-ontology#712]
**Proposed definition:** dilation and elongation of the penile urethra associated with absence or hypoplasia of the corpora spongiosa and cavernosa

**Superclass:** abnormality of the urethra (HP:0000795)

http://www.ncbi.nlm.nih.gov/pubmed/20981865

**Comment by pnrobinson** [comment]
It seems that Congenital megalourethra is a better term name, since this finding (the specific combination) is a congenital one only. Please reopen this issue if you disagree!
