### ISSUE TITLE
Acrocyanosis

### ISSUE THREAD

**Issue by cmrn-rhi** [obophenotype/human-phenotype-ontology#7122]
**HPO term**
Acrocyanosis

**Suggested revision of textual definition**
Bluish discoloration around the mouth and extremities, with the remaining area pink. [PMID: 32644593]

**Comment**
It is a functional peripheral vascular disorder characterized by bluish discoloration of skin and mucous membrane due to diminished oxyhemoglobin. [PMID:24249890]

**Comment by pnrobinson** [comment]
There is a distinction between peripheral cyanosis and acrocyanosis. I will add this reference, which is useful, but this is not a correct definition of Acrocyanosis. Please see my comment on a related issue.
