### ISSUE TITLE
Abnormal blood ion concentration

### ISSUE THREAD

**Issue by cmrn-rhi** [obophenotype/human-phenotype-ontology#7129]
**HPO term**
HP:0003111 - Abnormal blood ion concentration

**Synonym to be added**
Electrolyte disturbance

**broad/exact/narrow/plural/abbreviation ?**
exact and/or layperson term (based on the current synonym/layperson term "Electrolyte disorders" already present)

**Comment by pnrobinson** [comment]
added, thank you!
