### ISSUE TITLE
Possible bug in definition of "Aplasia/hypoplasia of the proximal phalanx of the 3rd toe"

### ISSUE THREAD

**Issue by turnovec** [obophenotype/human-phenotype-ontology#7137]
**HPO term**
HP:0100375 - Aplasia/hypoplasia of the proximal phalanx of the 3rd toe

**Bug description**
I'm not sure if I understand correctly (I'm not a native English speaker) a definition for this term which states:
"Absence (agenesis) or underdevelopment of one or more of the proximal phalanges of the 3rd toe."

Why "one or more"? I though that 3rd toe can have only one proximal phalanx. Or is it meant as from one or booth feet? Should it then be "of the proximal phalanges of the 3rd toeS."?

There are similar unclarities also for other toes...

**Comment by pnrobinson** [comment]
Thanks for pointing out this error, which must have been a copy&paste error. I have corrected the term and several other terms.
