### ISSUE TITLE
HPOA: strip whitespace from cells

### ISSUE THREAD

**Issue by matentzn** [obophenotype/human-phenotype-ontology#7140]
We were doing an (amazing!) kozathon today working with multiple teams on the HPOA ingest, learning a lot about python, biolink, koza and ingesting. 

We noticed your `OMIM:618800 ` annotations have additional whitespace - which crashed our systems :D (we will deal with it, but maybe you want to sort it out as well.

**Comment by pnrobinson** [comment]
Thanks! I would have loved to join but was hindered by other meetings. When we transition to SQL we will add Q/C for this, but this is a deficit of the current pipeline.

**Comment by pnrobinson** [comment]
I fixed the file
