### ISSUE TITLE
Incorrect notation of HPO ID

### ISSUE THREAD

**Issue by 1Seungbeom** [obophenotype/human-phenotype-ontology#7144]
**HPO term**
HP:0025621

**Bug description**
The id 'HP:0410393' linked to 'HP:0025621' by 'replaced_by' tag is written as 'HP_0410393.'

**Comment by nicolevasilevsky** [comment]
I'll fix this now

**Comment by 1Seungbeom** [comment]
Thank you!
I found a similar typo on HP:0410387. The term corresponding to 'replaced_by' tag is written as HP_0025624.
If this is fixed, I'll close this issue.

**Comment by nicolevasilevsky** [comment]
I fixed the one above too. The pull request is still pending and the ticket will be closed when I merge the PR.
