### ISSUE TITLE
Nutritional deficiency phenotype logical axioms

### ISSUE THREAD

**Issue by laurenechan** [obophenotype/human-phenotype-ontology#7154]
I am looking to axiomatize the nutritional deficiency disease terms in Mondo with the associated HP phenotypes (e.g. 'scurvy' has major feature some 'low levels of vitamin C'. Looking at some of the existing axioms for these phenotypes it seems some vitamin status terms do not include axioms and there is at least one that refers to an obsolete term (Vitamin C).
 
Can we include this axiom for the terms which do not yet include a logical axiom? 
has part some (decreased amount and characteristic of some vitamin X and has modifier some abnormal)

Additionally, I noticed that phenotypes such as 'low levels of vitamin X' are all listed under 'abnormality of vitamin metabolism'. If someone were to use this term to describe a low vitamin status due to inadequate intake, does that still qualify as abnormal metabolism? I don't know if I agree with that statement, but I would be interested in hearing others' thoughts on that topic and the existing hierarchy.

**Comment by pnrobinson** [comment]
@laurenechan Can we touch bases to do a session to revise this portion of the HPO together?

**Comment by pnrobinson** [comment]
@laurenechan is this still active?

**Comment by pnrobinson** [comment]
@laurenechan @LCCarmody @nicolevasilevsky please touch bases during an upcoming curation call if this is still active, closing for now.
