### ISSUE TITLE
Gyral disorganization

### ISSUE THREAD

**Issue by peupeubangbang** [obophenotype/human-phenotype-ontology#7161]
**HPO term**
HP:0002536 Abnormal cortical gyration

**Synonym to be added**
Gyral disorganization

**broad/exact/narrow/plural/abbreviation ?**
Broad/plural term often used to describe dysgyria, polymicrogyria and other gyral anomalies.
PMID: 24860126

**Comment by pnrobinson** [comment]
thanks, added as broad synoynm
