### ISSUE TITLE
Dysgyria as subclass of Abnormal cortical gyration

### ISSUE THREAD

**Issue by peupeubangbang** [obophenotype/human-phenotype-ontology#7162]
**HPO term**
HP:0032398 Dysgyria

**Suggested revision and reasons**
Dysgyria as subclass of HP:0002536 Abnormal cortical gyration. Can then be classified in the same group but distinct from other gyral anomalies. See below from PMID: 32895508.

"As highlighted in the previous section, polymicrogyria can be difficult to differentiate from COB, and might also be confused with dysgyria or pachygyria."

"Dysgyria translates as abnormal gyration and can therefore be applied to almost every type of MCD (malformations of cortical development). However, this term was introduced to describe cortical malformations that do not meet classic features of any of the abovementioned well-established MCD types. Dysgyria describes a cortex of variable thickness and an abnormal gyral pattern characterized by abnormalities of sulcal depth or orientation (for example, obliquely oriented sulci directed radially towards the centre of the cerebrum and narrow gyri separated by abnormally deep or shallow sulci)30,31. In the vast majority of cases, the term dysgyria describes an abnormal non-lissencephaly, non-polymicrogyria cortex within the spectrum of tubulinopathies."

"Abnormalities of the cortex can be obvious or subtle, and the range encompasses microlissencephaly, pachygyria with a cortical thickness >10 mm, pachygyria with a 5–10 mm thick cortex (often more prominent in the perisylvian regions), polymicrogyria, dysgyria and a simplified gyral pattern17,30,131,132."

**Comment by pnrobinson** [comment]
Thanks for this suggestion, I have added the link and the comment as above.
