### ISSUE TITLE
Failure to thrive HP:0001508

### ISSUE THREAD

**Issue by kanems** [obophenotype/human-phenotype-ontology#7173]
**HPO term**
Failure to thrive HP:0001508

**Bug description**
The definition ("Failure to thrive (FTT) refers to a _child_ whose physical growth is substantially below the norm.") and some the stored X-refs point to a pediatric phenotype, however, UMLS and SNOMED have separate terms for generic FTT (not age-restricted) as well as different age of onset FTT phenotypes.  Would it be possible to change the HPO preferred name to be "pediatric failure to thrive" to clearly distinguish it from the broader term in UMLS? (I didn't even realize there was an "adult failure to thrive syndrome" till I looked into why we had two potential CUI matches for this HPO concept in MedGen!)
Current listed X-refs
SNOMEDCT_US:432788009 & UMLS:C2315100= pediatric FTT (this is where UMLS maps the primary HPO term)
and UMLS:C0231246 and SNOMEDCT_US:36440009 = "failure to gain weight" (which has a narrower child concept: C3472702 "childhood failure to gain weight" with source of SNOMEDCT_US 351000119100)

Alternative/conflicting named terms:
UMLS CUI: C0015544 and SNOMEDCT 54840006: "Failure to thrive"
and screenshot of the SNOMEDCT FTT tree from UMLS browser:
![image](https://user-images.githubusercontent.com/71083858/137782646-eabaf54a-fac8-421f-9696-5f82bc620937.png)

**Comment by pnrobinson** [comment]
I had never heard of adult failure to thrive and do not think it is a standard term. 

The word "thrive" means "grow or develop well or vigorously.", and failure to thrive is typically used with children

https://www.hopkinsmedicine.org/health/conditions-and-diseases/failure-to-thrive

"Adult failure to thrive" is about losing capabilities, not about failing to gain them, and thus I do not think it is a proper term.

**Comment by pnrobinson** [comment]
Closing this issue. I do not think that "Adult failure to thrive" is a valid term. I would suggest that UMLS needs to be changed here as well.
