### ISSUE TITLE
Merge HP:0030276 Small scrotum with HP:0000046 Scrotal hypoplasia?

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#7175]
Hi! 

**HPO term**
Merge HP:0030276 Small scrotum with HP:0000046 Scrotal hypoplasia

**Reason for deprecation**
Either merge the two or make definitions more clear to how these are different. One has text def and one has logical def.

**Suggested replacement or term to consider**
Merging to small scrotum would be prefered, but other options are a possibility. Add synonym 'Undeveloped scrotum' (or new term as needed)

**Comment by pnrobinson** [comment]
done!
