### ISSUE TITLE
Vasa previa subclassification

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#7178]
Do we need subterms for Vasa previa?

**Comment by patt1morgan** [comment]
Hi Peter, 
From what I can find, there are 2 subclasses of vasa previa.
 Type I: Velamentous cord insertion and fetal vessels that run freely within the amniotic membranes overlying the cervix or in close proximity of it (2cm from os). (Pregnancies with low lying placentas or resolved placenta previa are at risk).  90% of vasa previa are type I. 
Type II: Succenturiate lobe or multilobe placenta (bilobed) and unprotected fetal vessels connecting both lobes course over or in close proximity of cervix (2cm from os).
PMID: 34441302,https://obgyn.onlinelibrary.wiley.com/doi/10.1002/uog.20347

**Comment by pnrobinson** [comment]
Consensus was we do not need these subtypes
