### ISSUE TITLE
Battledore placenta

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#7179]
**Preferred term label:**
Battledore placenta: The cord is attached to the margin of the placenta. It is named so because of its resemblance to the bat used in the medieval game of battledore and shuttlecock.

Is this a relevant abnormality? Should it be an HPO term?

**Comment by patt1morgan** [comment]
I agree., although it is not a term commonly used,  I have seen Battledore placenta used interchangeably with marginal cord insertion.   PMID: 29201670

**Comment by pnrobinson** [comment]
Added synoynm
