### ISSUE TITLE
Add "otocephaly" as synonym of "synotia" (HP:0100663)

### ISSUE THREAD

**Issue by CourtneyHum** [obophenotype/human-phenotype-ontology#718]

**Comment by pnrobinson** [comment]
According to http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3173934/

Otocephaly is a rare and lethal malformation complex involving the first arch and consists of microstomia, aglossia, agnathia and synotia. The defect is in the ventral portion of the arch.[1] I

Therefore, this does not appear to be a proper synonym. If this is wrong please reopen this issue or email me. Thanks! peter
