### ISSUE TITLE
Permalinks for annotations

### ISSUE THREAD

**Issue by eric-czech** [obophenotype/human-phenotype-ontology#7183]
Hi @pnrobinson, is there a way to get permalinks to annotations files at https://hpo.jax.org/app/download/annotation that are fixed to specific HPO releases (much like the tags available for the obo/owl files in this repo)? 

Thanks!

**Comment by pnrobinson** [comment]
@drseb @matentzn can we move forward with this?

**Comment by matentzn** [comment]
@pnrobinson this is just @drseb todo - he when running the next release ne needs to do the 3 todo things above. Maybe share it in slack with him as I am not sure if he reads github messages frequently!

**Comment by matentzn** [comment]
We are very close to this now:

https://github.com/OBOFoundry/purl.obolibrary.org/pull/825

Before closing, please make sure that @drseb has updated the documentation and checked the remaining task box in the comment above.

**Comment by matentzn** [comment]
Note that this only introduces versioned HPOA files from the current release onwards - past release will not have HPOA version IRIs attached with them!

**Comment by matentzn** [comment]
From today, we provide versioned PURLs to our HPOA annotation files, for example:

http://purl.obolibrary.org/obo/hp/releases/hpoa/2022-02-14/genes_to_phenotype.txt

Finally! :) This can be closed once @drseb has documented how to maintain this in the release notes.

**Comment by pnrobinson** [comment]
@matentzn @drseb I am not sure where the release instructions are? Can we close this?

**Comment by matentzn** [comment]
I will work on this on Tuesday, but no need to keep it open!
