### ISSUE TITLE
HPO term for G6PD is not linked to G6PD phenotype

### ISSUE THREAD

**Issue by conlinl** [obophenotype/human-phenotype-ontology#7188]
I have no idea if this the right place to put this issue, but it seems to be a major issue for this disorder, since the HPO term that is most used by our clinicians for children with the phenotype are not linked to one another.

So, the HPO term (plus it's children):
Abnormal glucose-6-phosphate dehydrogenase level HP:0410176

Is NOT listed as one of the terms linked to the phenotype:
Anemia, Nonspherocytic Hemolytic, Due To G6pd Deficiency OMIM:300908

and is is NOT linked to the gene G6PD

This HPO term is the one that (at least at our institution) clinicians are using the most when there is a G6PD deficiency, since it is very specific and appears to be the "best fit" for the G6PD deficiency phenotype, in part because it's the only HPO term that shows up when you search for "G6PD".  However, since it is not linked to the phenotype, it doesn't help our pipelines prioritize this for the patient.

**Comment by pnrobinson** [comment]
Thanks for pointing this out. I have updated the annotations, which should be available with our next release in December.
