### ISSUE TITLE
Clarification request: choanal atresia vs. posterior choanal atresia

### ISSUE THREAD

**Issue by kanems** [obophenotype/human-phenotype-ontology#7189]
What is the difference between Posterior choanal atresia HP:0004496 and Choanal atresia HP:0000453?
 OMIM https://www.omim.org/entry/608911 seems to use these two terms interchangeably. And Mondo MONDO:0012155 also seems to equate CA and PCA as exact synonyms. Literature searches in PubMed seem to favor the use of the term "choanal atresia" vs. posterior CA in more recent years, but some authors seem to also use them interchangeably.

**Comment by pnrobinson** [comment]
@kanems  -- I think these are exact synonyms. I will merge the Posterior choanal atresia term into the main Choanal atresia term and update the annotations. Thanks for pointing this out!
