### ISSUE TITLE
Beth is testing submitting a bug

### ISSUE THREAD

**Issue by BethSundberg** [obophenotype/human-phenotype-ontology#7194]
**Testing**

**Mike you should get this?**

**Attempting to enter a bug - enjoy this old photo
![Halloween2019_Dave_costumes](https://user-images.githubusercontent.com/11503959/139689097-751d48b2-b6e2-428f-b42b-2a932ddc38ee.jpg)
**

**Comment by BethSundberg** [comment]
Halloween - everyone is dressed up as Dave.

**Comment by pnrobinson** [comment]
Looks like a nice party -- hope it was fun!
