### ISSUE TITLE
File request

### ISSUE THREAD

**Issue by MaudDLVT** [obophenotype/human-phenotype-ontology#7198]
Hello HPO Team,
@matentzn Can you generate and share an Excel file with all the HPO codes under HP:0030057?
Many thanks in anticipation for your help.
Maud

**Comment by matentzn** [comment]
@MaudDLVT 

Can you review this table:
https://api.triplydb.com/s/cGh-ZkK6r

What other information do you want us to include in the results?

**Comment by MaudDLVT** [comment]
Seems perfect! I will keep you updated if we need something else with @e-lbtn. Many thanks again @matentzn

**Comment by matentzn** [comment]
@MaudDLVT you should not use the linked table in your paper, because it may be a bit out of date (its probably fine). I have produced the official report here:
https://github.com/obophenotype/human-phenotype-ontology/blob/master/src/ontology/reports/autoimmune-antibody-report.tsv

Please let me know if you need anything else, or need it updated.

**Comment by MaudDLVT** [comment]
Many thanks @matentzn 
I have an error alert "We can make this file beautiful and searchable if this error is corrected: Any value after quoted field isn't allowed in line 48."
How can I export the table?

**Comment by matentzn** [comment]
Just click on "Raw" and then File>Save as in your browser!

**Comment by MaudDLVT** [comment]
Hi @matentzn, best wishes for the new year! Can I have an update file with all the new terms added at the end of December? Many thanks.

**Comment by matentzn** [comment]
@MaudDLVT I ran the report against the current EDIT file

https://github.com/obophenotype/human-phenotype-ontology/blob/master/src/ontology/reports/autoimmune-antibody-report.tsv

so some of these terms are not released yet. Just bear this in mind - the report could change before the next release. 

Review the table carefully and let us know if there are problems.

**Comment by pnrobinson** [comment]
I think what we need to do is release the HPO and then recheck the terms. I had to revise a number of the term requests in the list for existing terms/synonyms etc. I think we are basically done with this list.

**Comment by MaudDLVT** [comment]
Hi @matentzn and @pnrobinson , many thanks for your work. May I have an extra column in the file with the synonyms? It will be quite helpful for your MD colleagues. Many thanks.

**Comment by matentzn** [comment]
I updated the table to show exact synonyms as well (not broad, narrow or related ones, just exact syonyms).
