### ISSUE TITLE
Adding HPO terms to Farber disease 

### ISSUE THREAD

**Issue by kcrosby11** [obophenotype/human-phenotype-ontology#7208]
**Farber disease ORPHA:333 and Farber lipogranulomatosis OMIM:228000**

**Osteolytic defects of the phalanges of the hand HP:0009771, Foot acroosteolysis HP:0001842, Osteolysis involving bones of the feet HP:0009134**

**The Farber disease and associated Farber lipogranulomatosis entries should be updated to include Osteolytic defects of the phalanges of the hand and feet, or acroosteolysis. This has been a reported symptom in older patients with more slowly progressive disease. Reported in PMID: 26945816 and PMID: 32706452. Documenting this association will assist in the diagnosis of patients with this rare disease who may present with a primary symptom of osteolysis**

**Comment by pnrobinson** [comment]
Thanks. I will also add a term "Decreased acid ceramidase activity"
I have added the terms and the pmid citation.
