### ISSUE TITLE
Recurrent joint dislocation as both preferred name and syn. 

### ISSUE THREAD

**Issue by kanems** [obophenotype/human-phenotype-ontology#7212]
**HPO term**
Recurrent joint dislocation HP:0031869

**Bug description**
The parent concept (Joint dislocation HP:0001373) includes a synonym of "Recurrent joint dislocations."  Suggest removing this synonym since it is its own concept in the hierarchy.

**Comment by pnrobinson** [comment]
Thanks, I have moved this synonym to Recurrent joint dislocation HP:0031869
