### ISSUE TITLE
 Distal sensory loss to/of all modalities

### ISSUE THREAD

**Issue by kanems** [obophenotype/human-phenotype-ontology#7213]
**HPO term**
Distal sensory impairment of all modalities HP:0003409

**Bug description**
Provided Synonyms:    Distal sensory loss _to_ all modalities
But there is also the child term: Distal sensory loss _of_ all modalities HP:0006984

I am trying to determine if MedGen should split these to represent the HPO hierarchy or merge onto one CUI/term as UMLS has lumped these concepts onto "Distal sensory impairment of all modalities," UMLS CUI: C1836527 Thanks for any insight/clarification you can provide.

**Comment by pnrobinson** [comment]
I think these two terms are actually synonymous, and we will merge them. HP:0003409 will be the id of the main term.

**Comment by pnrobinson** [comment]
Check and adjust annotations for the following entries that were annotated to the child term that we will merge

- [ ] OMIM:162400 | Neuropathy, Hereditary Sensory And Autonomic, Type Ia
- [ ] OMIM:613640 | Neuropathy, Hereditary Sensory And Autonomic, Type Ic
- [ ] OMIM:613708 | Neuropathy, Hereditary Sensory, Type Id
- [ ] OMIM:256840 | Neuropathy, Hereditary Sensory, With Spastic Paraplegia, Autosomal Recessive

**Comment by pnrobinson** [comment]
I have updated the annotations  TODO -- merge the terms

**Comment by pnrobinson** [comment]
done
