### ISSUE TITLE
Herpes encephalitis HP:0020098

### ISSUE THREAD

**Issue by kanems** [obophenotype/human-phenotype-ontology#7214]
**HPO term**
Herpes encephalitis HP:0020098
Definition from HPO: "Infection of the brain parenchyma with herpes simplex virus, resulting in inflammation of the brain parenchyma with neurologic dysfunction."

**Reason for deprecation**
Appears to be redundant with Herpes simplex encephalitis HP:0012302

**Suggested replacement or term to consider**
Herpes simplex encephalitis HP:0012302
(note: UMLS has both of these HPO IDs on "Herpes encephalitis," UMLS CUI: C0276226)

**Comment by pnrobinson** [comment]
Thanks @kanems for pointing out this error. I have merged the two terms
