### ISSUE TITLE
Second metatarsal bone in toes 3rd to 5th

### ISSUE THREAD

**Issue by turnovec** [obophenotype/human-phenotype-ontology#7215]
**HPO term**
HP:0100357, HP:0100358, HP:0100359

**Bug description**
In definitions for all these three terms there are sentence:
"The joint between the second metatarsal and the proximal phalanx of the..."

I think there should not be "second", but "third", "fourth" and "fifth", respectively.

**Comment by pnrobinson** [comment]
Thanks for pointing out this error -- fixed
