### ISSUE TITLE
New term - idiopathic right atrial dilation

### ISSUE THREAD

**Issue by CourtneyHum** [obophenotype/human-phenotype-ontology#722]
**Proposed definition:** dilation of the right atrium in the absence of tricuspid valve disease or tricuspid regurgitation

**Superclass:** right ventricular dilation (HP:0005133)

**Comment by pnrobinson** [comment]
The HPO tries not to include the disease etiology ("idiopathic"), since this can cause problems with bioinformatic analysis. I have added a term Right atrial enlargement, let me know if this is not sufficient.

**Comment by CourtneyHum** [comment]
That is sufficient. I realized that the superclass I proposed is incorrect
- it says ventricular dilation

On Thu, Feb 25, 2016 at 4:32 PM, Peter Robinson <notifications@github.com>
wrote:

> The HPO tries not to include the disease etiology ("idiopathic"), since
> this can cause problems with bioinformatic analysis. I have added a term
> Right atrial enlargement, let me know if this is not sufficient.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/obophenotype/human-phenotype-ontology/issues/722#issuecomment-188996869>
> .
>



-- 
Courtney Hum, MSc
Genetic Counsellor
Centre for Computational Medicine
The Hospital for Sick Children
T: 416-813-7654 x414028
