### ISSUE TITLE
'Abnormal thyroid hormone level' has invalid logical definition

### ISSUE THREAD

**Issue by balhoff** [obophenotype/human-phenotype-ontology#7224]
**HPO term**

[Abnormal thyroid hormone level](http://purl.obolibrary.org/obo/HP_0031508) refers to `thyroid hormone' and ('part of' some blood)`, but 'thyroid hormone' is a CHEBI role. CHEBI roles are not modeled as material entities, so can't be part of blood. This makes this class unsatisfiable when used with GO-plus and RO.

**Suggested revision of logical definition**

The definition should be:

```
'has part' some 
(amount and ('characteristic of' some  
(('chemical entity' and 'has role' some 'thyroid hormone') and ('part of' some blood))) and ('has modifier' some abnormal))
```

See also #4952.

**Comment by pnrobinson** [comment]
fixed, thanks

**Comment by balhoff** [comment]
Thanks Peter! I opened a PR on RO that will help to avoid this if it gets merged: https://github.com/oborel/obo-relations/pull/528
