### ISSUE TITLE
Ataxia term clarification

### ISSUE THREAD

**Issue by kanems** [obophenotype/human-phenotype-ontology#7225]
**HPO term**
Ataxia HP:0001251
(and Dyssynergia HP:0010867)

**Bug description**
HP:0001251 definition and synonym indicate this term is specific to _Cerebellar ataxia_ which is the concept where UMLS maps this HPO term (Cerebellar Ataxia UMLS CUI: C0007758).
However on the UMLS term Ataxia (UMLS CUI: C0004134) they have instead mapped HP:0010867 Dyssynergia  (which is a separate issue I will bring to UMLS for their review, just wanted to bring it your attention as well). 

Is the intent for HP:0001251 to be focused on cerebellar ataxia or the more inclusive term "ataxia"? The provided cross-references, synonym and textual definition support mapping to "cerebellar ataxia" but the preferred/primary name is causing some confusion for me.

**Comment by pnrobinson** [comment]
When physicians say 'ataxia' without further specification, then cerebellar ataxia is meant. One can speak also of sensory ataxia but this is clinically different. In the web you can find the term vestibular ataxia as well but I am not convinced this is a useful terminology. Clinically all three are different and I do not think there is much use for a grouping term -- the English-language labels imply there should be but medically I do not think that it would be accurate.
