### ISSUE TITLE
Inconsistent capitalization in synonyms for Abnormality of the skin

### ISSUE THREAD

**Issue by turnovec** [obophenotype/human-phenotype-ontology#7227]
**HPO term**
HP:0000951 Abnormality of the skin

**Bug description**
There are these synonyms:
"Skin abnormality, dermatopathy, Abnormality of the skin, dermopathy"
I thought that in synonyms all first letters are in upper case, but there are two synonyms where the first letters are in lower case.

**Comment by pnrobinson** [comment]
Fixed, thanks!
