### ISSUE TITLE
Inconsistent capitalization in synonyms for Pruritus

### ISSUE THREAD

**Issue by turnovec** [obophenotype/human-phenotype-ontology#7229]
**HPO term**
HP:0000989 Pruritus

**Bug description**
Synonyms: pruritis, Itchy skin, Skin itching, Itching
The first synonym is not capitalized.

**Comment by pnrobinson** [comment]
I have removed "pruritis", this was a mistake. By default all term labels/synonyms are capitalized and there should be no duplications unless in the case where we add a synonym label such as layperson.
thanks!
