### ISSUE TITLE
Crazy-paving pattern HP:0033659

### ISSUE THREAD

**Issue by kanems** [obophenotype/human-phenotype-ontology#7230]
**HPO term**
Crazy (-)paving pattern HP:0033659 or HP:0025391

**Reason for deprecation**
These terms appear to be redundant, varying only in terms of hyphen vs. space. 

**Suggested replacement or term to consider**

**Comment by pnrobinson** [comment]
Thanks, this was a mistake, I am merging the two terms. The non-obsolete term will have the id HP:0025391
