### ISSUE TITLE
What exactly is "Broad secondary alveolar ridge"?

### ISSUE THREAD

**Issue by turnovec** [obophenotype/human-phenotype-ontology#7231]
**HPO term**
HP:0000216 Broad secondary alveolar ridge 

**Suggested revision of textual definition**
What does exactly this term mean? We are currently translating HPO with several colleagues to Czech language to be able to translate it precisely we want to know or understand the original term. We know what alveolar ridge is, we can imagine how it looks when it's broad, but there are some primary and secondary one? We also asked one dentist and she never heard about it... And in HPO the definition for this term is also missing. Or it does mean that it's not congenital and it's because some later pathologies (abscess) or surgery?

**Comment by pnrobinson** [comment]
I have reviewed this more.
The HPO has three diseases that were annotated to this term
1. Simpson-golabi-behmel Syndrome, Type 1 -- this term appears to have been used rarely, but I cannot find the original literature and the papers I have examined do not describe abnormalities of the alveolar ridge. Instead, I think they were actually describing gingival hypertrophy.
2. [Trigonocephaly With Short Stature And Developmental Delay](https://omim.org/entry/314320). This is a clinically defined entity with sparse data, but the OMIM CS reports "Secondary alveolar ridges", implying the existence of an additional ridge
3. [Yunis-varon Syndrome](https://omim.org/entry/216340). Here, the description comes from this [report](https://pubmed.ncbi.nlm.nih.gov/20932945/). Here, the term is used once but not defined and there is no photograph. The authors are not native English speakers, and so it seems likely that this term is actually not a standard terminology

**Comment by pnrobinson** [comment]
I think therefore that there is no such thing as "Broad secondary alveolar ridge" and I am merging this term with its parent term [Broad alveolar ridges HP:0000187](https://hpo.jax.org/app/browse/term/HP:0000187). 
Thanks for pointing out this error, which will be corrected in the Feb release of HPO.
