### ISSUE TITLE
Organisation under "Abnormal serum bile acid concentration"

### ISSUE THREAD

**Issue by e-lbtn** [obophenotype/human-phenotype-ontology#7233]
Hello, 

In the arborescence under "Abnormal serum bile acid concentration (HP:0030984)", we can find : 
- Increased serum bile acid concentration (HP:0012202)
- Decreased serum bile concentration (HP:0030985)

Could it be preferable to name the second one : "Decreased serum bile acid concentration" ? 

Thanks

**Comment by pnrobinson** [comment]
Thank you for picking up this mistake. I have fixed it.
