### ISSUE TITLE
New term - sacroccygeal teratoma

### ISSUE THREAD

**Issue by CourtneyHum** [obophenotype/human-phenotype-ontology#724]
**Superclass:** teratoma (HP:0009792); abnormality of the sacrum (HP:0005107)

**Comment by pnrobinson** [comment]
Currently, the HPO has presacrtal teratoma. I saw this classification:

Sacrococcygeal teratoma SCTs are classified morphologically according to their relative extent outside and inside the body:

    Altman type I — entirely outside, sometimes attached to the body only by a narrow stalk
    Altman type II — mostly outside
    Altman type III — mostly inside
    Altman type IV — entirely inside; this is also known as a presacral teratoma or retrorectal teratoma

I am not familiar with this, but should we accept this as our classification?

**Comment by CourtneyHum** [comment]
It is a classification system used by the American Academy of Pediatric Surgery I believe, so I would accept it if you are okay with it as well.

**Comment by CourtneyHum** [comment]
I've seen the Altman classification referenced in a few articles, as
recently as 2014 in my quick search. It is a classification system written
by the American Academy of Pediatric Surgery so I would accept it if you
are okay with it as well.

On Thu, Feb 25, 2016 at 4:03 PM, Peter Robinson <notifications@github.com>
wrote:

> Currently, the HPO has presacrtal teratoma. I saw this classification:
>
> Sacrococcygeal teratoma SCTs are classified morphologically according to
> their relative extent outside and inside the body:
>
> Altman type I — entirely outside, sometimes attached to the body only by a narrow stalk
> Altman type II — mostly outside
> Altman type III — mostly inside
> Altman type IV — entirely inside; this is also known as a presacral teratoma or retrorectal teratoma
>
> I am not familiar with this, but should we accept this as our
> classification?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/obophenotype/human-phenotype-ontology/issues/724#issuecomment-188986969>
> .
>



-- 
Courtney Hum, MSc
Genetic Counsellor
Centre for Computational Medicine
The Hospital for Sick Children
T: 416-813-7654 x414028
