### ISSUE TITLE
NBO seizure branch in HPO? Rearrange, suppress, or merge?

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#7246]
**HPO term**
http://purl.obolibrary.org/obo/NBO_0000648
http://purl.obolibrary.org/obo/HP_0002384
**Suggested revision and reasons**

Hi All--having a little issue with the behavioral phenotype branch (NBO) that is coming up in HP.

The above terms are synonyms, but since I was looking for 'complex partial seizure' as a term name, the NBO term came up first.  Is there a reason why the NBO branch is in there? 

Suggestions: if NBO is needed but it isn't the actual phenotypic term, could we suppress it from coming up in OLS? If they are terms, can they replace/merge/what not with the HP terms?

Thanks. :)

**Comment by pnrobinson** [comment]
I agree, we should not be using NBO to logically define seizures in HPO.

**Comment by pnrobinson** [comment]
I am not sure where this is coming from? @matentzn @drseb is there a case to be made for removing NBO from our definitions by script?
