### ISSUE TITLE
Error in definition of Cone-shaped epiphysis of the proximal phalanx of the thumb - there's no middle phalanx of the thumb

### ISSUE THREAD

**Issue by turnovec** [obophenotype/human-phenotype-ontology#7254]
**HPO term**
HP:0009666 Cone-shaped epiphysis of the proximal phalanx of the thumb 

**Bug description**
First sentence of definition: "A cone-shaped appearance of the epiphysis of the middle phalanx of the thumb of the hand, producing a 'ball-in-a-socket' appearance."
As far as I know the thumb have just two phalanges (proximal and distal) so there couldn't be any middle one.

**Comment by pnrobinson** [comment]
fixed, thanks for picking up this error!
