### ISSUE TITLE
Move "Poor Eye Contact" Under "Impaired Use of Nonverbal Behaviors"

### ISSUE THREAD

**Issue by bcoleman96** [obophenotype/human-phenotype-ontology#7258]
**HPO term**
Poor eye contact (HP:0000817)

**Suggested revision and reasons**
Remove relationship between "Poor eye contact" and "Impaired social interaction". Make "Poor eye contact" a child of "Impaired use of nonverbal behaviors" (and thus grandchild of "Impaired social interaction").

**Comment by pnrobinson** [comment]
done, thanks (PS, please provide your ORCID id for future issues!)
