### ISSUE TITLE
Wrong definition for HP:0006134 Enlarged metacarpal epiphyses

### ISSUE THREAD

**Issue by turnovec** [obophenotype/human-phenotype-ontology#7259]
**HPO term**
HP:0006134 Enlarged metacarpal epiphyses 

**Bug description**
Current definition:
"Abnormally large size of the metaphyseal epiphyses."

Shouldn't it be this?
"Abnormally large size of the metacarpal epiphyses."

**Comment by pnrobinson** [comment]
Thanks for pointing out this error. I changed the definition to 

```
Abnormally large size of one or more growth plates (epiphyses) of the metacarpal bones (i.e., the tubular bones of the hand between the carpus and the phalanges).
```
