### ISSUE TITLE
Wrong synonym for HP:0009495 Pseudoepiphyses of the 2nd finger

### ISSUE THREAD

**Issue by turnovec** [obophenotype/human-phenotype-ontology#7260]
**HPO term**
HP:0009495 Pseudoepiphyses of the 2nd finger

**Bug description**
Current synonym is:
"Accessory index finger phalanges"

Shouldn't it be like this?
"Accessory index finger epiphysis"

**Comment by pnrobinson** [comment]
THanks for pointing out this mistake, I fixed it. I also changed the primary label to the singular form, which is more correct.
