### ISSUE TITLE
Singular should be changed to plural in definitions for HP:0010021 and HP:0010155

### ISSUE THREAD

**Issue by turnovec** [obophenotype/human-phenotype-ontology#7261]
**HPO term**
HP:0010021 Ivory epiphysis of the 1st metacarpal 
HP:0010155 Ivory epiphysis of the 1st metatarsal 

**Bug description**

"The epiphysis of the 1st metacarpal are hard and dense like ivory. Such an epiphysis has a uniformly dense appearance on radiographs."

"The epiphysis of the 1st metatarsal are hard and dense like ivory. Such an epiphysis has a uniformly dense appearance on radiographs."

The "epiphysis" in first sentences of both definitions should be changed to "epiphyses" (if the following verb is "are").

**Comment by pnrobinson** [comment]
Thanks for pointing out this error. I changed it to

The epiphysis of the 1st metacarpal appears hard and dense like ivory. An ivory epiphysis has a uniformly dense appearance on radiographs.
