### ISSUE TITLE
Anti-multiple nuclear dots antibody positivity HP:0025353

### ISSUE THREAD

**Issue by MaudDLVT** [obophenotype/human-phenotype-ontology#7267]
**HP:0025353**

**Anti-MND antibodies positivity and Anti-sp100 antibody positivity are not completely equivalent. 
From:
Pr Olivier CHAZOUILLERES
Service d’Hépatologie
Centre de Référence Maladies Rares : « Maladies Inflammatoires des Voies Biliaires »
Filière Maladies Rares du Foie de l’Adulte et de l’Enfant (FILFOIE)
Hôpital Saint Antoine, 75012, PARIS, FRANCE
He said:
"Effectivement, les aspects « nuclear dots » correspondent principalement aux anti-sp100, mais ces mots ne sont pas équivalents. Aussi « nuclear dots » est un aspect de fluorescence nucléaire, alors que sp100 est une protéine du noyau."
Meaning:
"Indeed, the nuclear dots aspects correspond mainly to anti-sp100, but these words are not equivalent. Also "nuclear dots" is a nuclear fluorescence aspect, while sp100 is a nuclear protein."
I will get more details with an other MD. I will keep you updated.
I strongly suggest that anti-sp100 should be under anti-MND.

**

**Comment by pnrobinson** [comment]
added as suggested above @MaudDLVT  -- with this, I think we have added all of the suggested autoantibody terms. We will be releasing the next version of HPO next week and this should be available shortly.
