### ISSUE TITLE
Periventricular leukomalacia HP:0006970

### ISSUE THREAD

**Issue by jagcsun** [obophenotype/human-phenotype-ontology#7268]
**HPO term**
Periventricular leukomalacia

**Suggested revision of textual definition**
Periventricular leukomalacia is a major neuropathological white matter brain injury; affected infants show definitive signs of cerebral palsy (PMID: 28406931). The neuropathologic hallmarks of PVL are microglial activation and focal and diffuse periventricular depletion of premyelinating oligodendroglia (PMID: 18852342).

**Synonym to be added**
PVL

**Comment**
Magnetic resonance imaging–based neuroimaging techniques provide greater diagnostic sensitivity for PVL than does head ultrasonography and often document the involvement of telencephalic gray matter and long tracts in addition to periventricular white matter (PMID: 18852342).

@pnrobinson

**Comment by pnrobinson** [comment]
added thanks
