### ISSUE TITLE
New term - thoracoabdominal eventration

### ISSUE THREAD

**Issue by CourtneyHum** [obophenotype/human-phenotype-ontology#728]
**Proposed definition:** abdominal wall defect that has extended upwards to include the lower sternum and possible diaphragm

**Superclass:** thoracoabdominal wall defects (HP:0100656)

**Comment by pnrobinson** [comment]
Difficult to find references. I thiink this is the same as the current term celosomia (HP_0100657). Please comment.

**Comment by CourtneyHum** [comment]
Agree

**Comment by drseb** [comment]
ok. then I will close

**Comment by pnrobinson** [comment]
I believe that thoracoabdominal eventration is better as the primary term name and that celosomia could be a synonym. Does this sound OK, Courtney?

**Comment by CourtneyHum** [comment]
Yes, putting thoracoabdominal eventration as the primary may make it easier for users to find the term. Seeing as I missed it completely! Thanks Peter

**Comment by pnrobinson** [comment]
I swapped the primary term name and synonym accordingly, thanks!
