### ISSUE TITLE
Neurodevelopmental delay HP:0012758

### ISSUE THREAD

**Issue by jagcsun** [obophenotype/human-phenotype-ontology#7283]
**HPO term**
Neurodevelopmental delay HP:0012758

**Suggested revision of textual definition**
Neurodevelopmental delay (NDD) refers to delays in the maturation of the brain and central nervous system; infants and young children with NDD may experience delays in the development of one or more skills including gross motor abilities, fine-motor coordination, language abilities and ability to solve increasingly complex problems (PMID: 31783983). 

**Comment**
Though the definitions of NDD vary broadly in the literature, all are used to signify a delay in one or more developmental domains compared to typical development.

**Synonym to be added**
NDD

**Your nano-attribution (ORCID)**
0000-0002-6670-9157

@pnrobinson

**Comment by pnrobinson** [comment]
added, thanks!
