### ISSUE TITLE
Speech apraxia HP:0011098

### ISSUE THREAD

**Issue by jagcsun** [obophenotype/human-phenotype-ontology#7285]
**HPO term**
Speech apraxia HP:0011098

**Synonym to be added**
speech dyspraxia

**broad/exact/narrow/plural/abbreviation ?**

**Your nano-attribution (ORCID)**
0000-0002-6670-9157

@pnrobinson

**Comment by pnrobinson** [comment]
I do not think these are exact synonyms, essentially apraxia is complete and dyspraxia is partial, but it is possible they are used interchangeably by many. I will add this as a related synonym.
