### ISSUE TITLE
Type II pneumocyte hyperplasia definition

### ISSUE THREAD

**Issue by sbello** [obophenotype/human-phenotype-ontology#7289]
**HPO term**
Type II pneumocyte hyperplasia (HP:0033328)

**Suggested revision of textual definition**
Current definition specifies "Enlargement of type II pneumocytes..." suggest this be changed to "Increase in the number of type II pneumocytes..." to match the label and distinguish this from Type II pneumocyte hypertrophy (HP:0033246). I think "enlargement" could imply increase in size rather than number.

**Comment by pnrobinson** [comment]
Thanks for pointing out this inconsistency @sbello 
@mgriese -- we currently have terms for both Type II pneumocyte hyperplasia and hypertrophy. Are both used clinically or is the distinction not one that is made in clinical use? Can we review these two terms?

**Comment by mgriese** [comment]
Typically there is Type II pneumocyte hyperplasia, which means that the numbers of these cells are increased in several conditions

Rarely, in the literature Type II pneumocyte hypertrophy is used; then it is the individual cell which is larger than usual (PMID: 17554398). 

Terms are different, not synonymous

**Comment by pnrobinson** [comment]
thanks, both, agree and I have made these changes.
