### ISSUE TITLE
Meningocele definition

### ISSUE THREAD

**Issue by sbello** [obophenotype/human-phenotype-ontology#7292]
**HPO term**
Meningocele (HP:0002435)
Current definition "Protrusion of the meninges through a defect of the vertebral column."

**Suggested revision of textual definition**
"Protrusion of the meninges through a defect of the skull or vertebral column."
source: Taber's edition 19 ISBN 0-8036-0655-9 

The existing term has children that refer to skull defects but the current text definition is limited to vertebral column.

**Comment by pnrobinson** [comment]
Thanks for pointing this out @sbello I have corrected the definition.
