### ISSUE TITLE
Toe walking HP:0040083

### ISSUE THREAD

**Issue by jagcsun** [obophenotype/human-phenotype-ontology#7293]
**HPO term**
Toe walking HP:0040083

**Suggested revision of textual definition**
Inability to generate a heel strike during the contact phase of the gait cycle.(PMIDs: 35055626; 25223807).

**Comment**
Up to 2 to 3 years of age, walking on the toes or balls of the feet is assumed to be common gait deviation (PMIDs: 35055626; 25223807)

**Your nano-attribution (ORCID)**
0000-0002-6670-9157

@pnrobinson

**Comment by pnrobinson** [comment]
Is the current definition incorrect?

**Comment by jagcsun** [comment]
Currently there is no definition given for Toe walking

**Comment by pnrobinson** [comment]
Wait, I see that there are two terms
[Toe walking HP:0040083](https://hpo.jax.org/app/browse/term/HP:0040083)
and
[Tip-toe gait HP:0030051](https://hpo.jax.org/app/browse/term/HP:0030051)
that might need to be merged. I will investigate

**Comment by pnrobinson** [comment]
These are synonyms. I merged them and updated the definition.
