### ISSUE TITLE
Acetabular dysplasia HP:0008807

### ISSUE THREAD

**Issue by jagcsun** [obophenotype/human-phenotype-ontology#7294]
**HPO term**
Acetabular dysplasia HP:0008807

**Suggested revision of textual definition**
A smaller than normal acetabulum that has insufficient femoral head coverage leading to abnormal hip joint contact pressures, instability and pain (PMID: 23764788; 34377520)

**Comment**
Acetabular dysplasia is known to lead to hip pain and early-onset of hip osteoarthritis.

**Your nano-attribution (ORCID)**
0000-0002-6670-9157

@pnrobinson

**Comment by pnrobinson** [comment]
updated
