### ISSUE TITLE
Upper limb hypertonia HP:0200049

### ISSUE THREAD

**Issue by jagcsun** [obophenotype/human-phenotype-ontology#7295]
**HPO term**
Upper limb hypertonia HP:0200049

**Suggested revision of textual definition**
Hypertonia, increased muscle tone, which is observed in the upper limbs of the affected person (PMID:21642056)

**Your nano-attribution (ORCID)**
0000-0002-6670-9157

@pnrobinson

**Comment by pnrobinson** [comment]
added
