### ISSUE TITLE
Scarring HP:0100699

### ISSUE THREAD

**Issue by jagcsun** [obophenotype/human-phenotype-ontology#7296]
**HPO term**
Scarring HP:0100699

**Suggested revision of textual definition**
Functional and cosmetic deformities appearing in the form of scar which happens due to injury and aberrant wound healing or tissue repair process (PMID: 16012249; 12521975). 

**Comment**
Though scars are the normal and inevitable outcome of the tissue repair process, they can cause unpleasant symptoms and be aesthetically distressing, disfiguring, and psychosocially or functionally disabling (PMID: 12521975).

**Your nano-attribution (ORCID)**
0000-0002-6670-9157

@pnrobinson

**Comment by pnrobinson** [comment]
I think this term refers to abnormal scarring. The above definition would be good for "normal" scars, which are a normal physiological response to injury. Let's search for more precise definitions, e.g. https://www.ncbi.nlm.nih.gov/labs/pmc/articles/PMC3775400/ and https://www.ncbi.nlm.nih.gov/labs/pmc/articles/PMC1125033/

**Comment by pnrobinson** [comment]
On second thought, I think this term is intended to be general, I added the definition
A scar refers to a lesion in which wound, burn, or sore has not healed completely and fibrous connective tissue has developed.
