### ISSUE TITLE
Epispadias

### ISSUE THREAD

**Issue by sbello** [obophenotype/human-phenotype-ontology#7302]
**HPO term**
Epispadias (HP:0000039)

Both MP and HPO have terms for epispadias but in the MP (MP:0003598) the term applies to both males and females while in the HPO it is limited to males. I find multiple sources that support the phenotype occurring in both males and females. 

Sources:
https://www.hopkinsmedicine.org/health/conditions-and-diseases/epispadias
https://www.urologyhealth.org/urology-a-z/e/epispadias
https://my.clevelandclinic.org/health/diseases/21551-epispadias
https://www.chop.edu/conditions-diseases/epispadias

**Suggested revision of textual definition**

Consider revising the definition to 
congenital failure of the urethra to form a complete tube with the urethral opening somewhere on the dorsum of the penis at any point below the internal sphincter in males; in females, the malformed urethral opening is often located between the clitoris and labia but may rarely  be located on the belly
https://www.chop.edu/conditions-diseases/epispadias
https://www.hopkinsmedicine.org/health/conditions-and-diseases/epispadias

Alternatively you may want to modify the term label of the existing term to Male epispadias to match the existing definition.

**Comment by pnrobinson** [comment]
@sbello thanks for pointing this out, you are correct. Epispadias is rare in females.
I am revising the definition as follows

Epispadias is a urogenital malformation characterized by the failure of the urethral tube to tubularize on the dorsal aspect. Unlike in hypospadias, where the meatus is on the ventral aspect, children with epispadias have a wide-open urethral plate on the dorsum. It is commonly seen as a component in the spectrum of bladder exstrophy-epispadias-complex. Isolated epispadias constitutes less than 10 percent of the total cases of epispadias. 
Comment: Male epispadias is often associated with characteristic anatomic abnormalities, including a short-stubby phallus with a dorsally located meatus, upward-pointing phallus, and ventral hooding of the prepuce. Female epispaidas can be associated with bifid clitoris, patulous urethral opening, anteriorly placed vaginal opening, and ill-formed or absent mons. 
PMID: 33085327
