### ISSUE TITLE
Panypogammaglobulinemia - Not synonym, just a typo?

### ISSUE THREAD

**Issue by turnovec** [obophenotype/human-phenotype-ontology#7303]
**HPO term**
HP:0003139 Panhypogammaglobulinemia

**Bug description**
It looks like the "synonym" for Panhypogammaglobulinemia is "Panypogammaglobulinemia" - but I think it's not a synonym, but just a typo with one letter missing...

**Comment by pnrobinson** [comment]
thanks for pointing out this error -- fixed
