### ISSUE TITLE
Wrong capitalization of "Treacher collins"

### ISSUE THREAD

**Issue by turnovec** [obophenotype/human-phenotype-ontology#7309]
**HPO term**
HP:0005321 Mandibulofacial dysostosis 

**Bug description**
Mandibulofacial dysostosis has a synonym "Treacher collins syndrome".

But it should be "Treacher Collins syndrome" (capital C, the name of the doctor after it was named was Edward Treacher Collins).

**Comment by pnrobinson** [comment]
thanks for pointing this out. Corrected!
