### ISSUE TITLE
New term - ureterovesical junction obstruction

### ISSUE THREAD

**Issue by CourtneyHum** [obophenotype/human-phenotype-ontology#731]
**Proposed definition:** blockage at the level of the bladder and the ureter caused by stenosis of the ureteral valves or failure of a narrow juxtavesical ureteral segment to dilate due to segmented fibrosis or localized absence of muscle

**Synonym:** UVJ

**Superclass:** ureteral obstruction (HP:0006000)

**Comment by pnrobinson** [comment]
Added as HP_0030735
