### ISSUE TITLE
Re HP:0007054. Hyperreflexia proximally

### ISSUE THREAD

**Issue by grahamponting** [obophenotype/human-phenotype-ontology#7316]
I am mapping HPO terms to SNOMED, but I would be grateful if you would provide some more detailed information on this term, where there is no definition. In particular what you mean by proximal here ? is it for example abdominal superficial reflexes ??
Many thanks for your help.
Graham Ponting. grahamaponting@hotmail.com

**Comment by pnrobinson** [comment]
The links were missing.
I updated the definition to
Hyperactive stretch reflexes of muscles that move proximal joints (elbow, knee).
and added the subclass relations.
Thanks for pointing out this inconsistency.
