### ISSUE TITLE
HP:0005347. Cartilaginous trachea

### ISSUE THREAD

**Issue by grahamponting** [obophenotype/human-phenotype-ontology#7326]
Hi
A definition would be helpful here, as a trachea is normally cartilaginous, so it's not clear what the abnormality is.
Many thanks.
Graham Ponting

**Comment by pnrobinson** [comment]
Note to me -- up date annotation to Pfeiffer syndrome via PMID:15996217

**Comment by pnrobinson** [comment]
done
