### ISSUE TITLE
HP:0007561 Telangiectases in sun-exposed and nonexposed skin

### ISSUE THREAD

**Issue by grahamponting** [obophenotype/human-phenotype-ontology#7327]
A definition would be helpful here. If  a feature of "sun-exposed and nonexposed skin", that is skin in general, how does it differ from the parent HP:0100185 ?
Thanks. Graham Ponting

**Comment by pnrobinson** [comment]
This was an OMIM-derived term that comes from https://pubmed.ncbi.nlm.nih.gov/12789646/.
I think it is best to merge this term.
If we will want to emphasize sun exposure, we should use a triggered by sun exposure modifier term instead.
I will merge with Telangiectasia of the skin HP:0100585

Thanks for pointing this out.
