### ISSUE TITLE
HP:0030327. Abnormal osteoclast count

### ISSUE THREAD

**Issue by grahamponting** [obophenotype/human-phenotype-ontology#7328]
Hi,
For the above concept, could I check what the specimen is please. I assume it is bone but could be marrow or other tissue. Many thanks.
Graham Ponting

**Comment by pnrobinson** [comment]
Thanks for pointing this out. The finding relates to bone tissue, for instance, https://pubmed.ncbi.nlm.nih.gov/3513575/
I have updated the definition to 
Decreased number of osteoclasts in bone tissue.
I have corrected the parentage to  [Abnormal bone structure HP:0003330](https://hpo.jax.org/app/browse/term/HP:0003330)
