### ISSUE TITLE
HP:0006187. Fusion of midphalangeal joints

### ISSUE THREAD

**Issue by grahamponting** [obophenotype/human-phenotype-ontology#7329]
Hi,
The above concept refers to a midphalangeal joint, in the hand, but there is only a proximal and distal joint in the fingers, so could you confirm/define.
Many thanks and apologies for all these questions, but it is part of a mapping between HPO and SNOMED.
Graham Ponting

**Comment by pnrobinson** [comment]
Looking at our annotations, we only have one annotation to this term, [Multiple Synostoses Syndrome 1](https://hpo.jax.org/app/browse/disease/OMIM:186500).
Looking at the literature, the affected individuals have proximal symphalangism especially of fingers 4 and 5. 
This term was derived from text mining 13 years ago, but I think that it is not precise enough and so I will merge it with  Symphalangism affecting the phalanges of the hand HP:0009773

Thanks for pointing this out.
