### ISSUE TITLE
HP:0007451. Ipsilateral lack of facial sweating

### ISSUE THREAD

**Issue by grahamponting** [obophenotype/human-phenotype-ontology#7330]
Hi,
Ipsilateral implies the lack of facial sweating is the same side as something else. Does this relate to facial paralysis. ? or to Horners syndrome HP:0006837.
Many thanks

**Comment by pnrobinson** [comment]
In fact this is intended to be a feature of Horner syndrome. I have added the definition
def: Inability to sweat on the same side of the face that is affected by ptosis and miosis. This is a feature of Horner syndrome.
