### ISSUE TITLE
HP:0006825. Pallor of dorsal columns of the spinal cord

### ISSUE THREAD

**Issue by grahamponting** [obophenotype/human-phenotype-ontology#7331]
It would be helpful to know how this pallor of the dorsal columns  is being viewed. Is it by imaging, post mortem or some other method. This would provide context and help in mapping to SNOMED CT.
Many thanks - Graham Ponting

**Comment by pnrobinson** [comment]
I think this finding can only be made by path examination. The annotation is used for OMIM:602433  from this publication

Gross inspection of the spinal cord demonstrated atrophy of the ventral and dorsal roots. Microscopic evaluation of the spinal cord parenchyma disclosed loss of anterior horn cells and pallor of the dorsal columns. (https://pubmed.ncbi.nlm.nih.gov/9497266/). 

I am adding the following definition
An abnormally pale appearance of the dorsal portion of the gray substance of the spinal cord. This finding can be observed by histological examination.
