### ISSUE TITLE
HP:0025658 and HP:0025715, potential duplicates

### ISSUE THREAD

**Issue by grahamponting** [obophenotype/human-phenotype-ontology#7332]
Hi Peter,

HP:0025658	Abnormal umbilical artery Doppler pattern in pregnancy
HP:0025715	Abnormal umbilical artery doppler waveform during pregnancy

These two new concepts both refer to abnormalities in umbilical artery Doppler waveform during pregnancy, and on the face of it, are very similar, and I can't see any difference between the two. 
Many thanks.
Graham Ponting

**Comment by sparkste** [comment]
Hi all,

Yes, I agree that "abnormal umbilical artery Doppler pattern in pregnancy" and "abnormal umbilical artery Doppler waveform during pregnancy" are synonyms.

We typically describe UA Dopplers as: 1) normal umbilical artery Dopplers, 2) elevated umbilical artery Dopplers, 3) absent end diastolic flow in umbilical artery Dopplers, and 4) reversed flow in umbilical artery Dopplers. Numbers 2-4 would all technically fall under "abnormal" UA Dopplers.

Does this help? Let me know if you want further clarification!

Teresa



Teresa Sparks, MD, MAS

Maternal Fetal Medicine and Clinical Genetics

Department of Obstetrics, Gynecology, & Reproductive Sciences

University of California, San Francisco

________________________________

**Comment by pnrobinson** [comment]
Thanks, I merged these two terms.
I also added three terms as below. @sparkste please reopen this issue if the definitions of the new terms need work.

**Comment by pnrobinson** [comment]
Reversed end-diastolic umbilical artery flow
Def: An anomaly that is visualized by umbilical artery Doppler velocimetry.  Flow in the umbilical artery should be in the forward direction in normal circumstances. This anomaly is characterized by an reversal of flow in the umbilical artery at the end of diastole (i.e., backwards flow).

**Comment by pnrobinson** [comment]
Absent end-diastolic umbilical artery flow
def: An anomaly that is visualized by umbilical artery Doppler velocimetry.  Flow in the umbilical artery should be in the forward direction in normal circumstances. This anomaly is characterized by an absence of flow in the umbilical artery at the end of diastole.

**Comment by pnrobinson** [comment]
Elevated umbilical artery pulsatility
Def: Human umbilical artery (UA) blood flow pulsatility measured by Doppler ultrasound is a widely used biomarker for the detection of elevated placental vascular resistance. Elevated UA pulsatility, which in the most extreme cases manifests as absent or even reversed end-diastolic velocity, is associated with intrauterine growth restriction (IUGR) and still-birth.
