### ISSUE TITLE
Adducted thumb HP:0001181

### ISSUE THREAD

**Issue by jagcsun** [obophenotype/human-phenotype-ontology#7335]
**HPO term**
Adducted thumb HP:0001181

**Synonym to be added**
Thumb-in-palm deformity, Thumb-in-palm pattern

**Comment**
The thumb-in-palm is one of the most common upper limb deformities in patients with spastic cerebral palsy that impairs the ability to use the thumb and thus severely limits hand function (PMID: 16235349 and 33396294)

**broad/exact/narrow/plural/abbreviation ?**

**Your nano-attribution (ORCID)**
0000-0002-6670-9157

@pnrobinson

**Comment by pnrobinson** [comment]
added
