### ISSUE TITLE
Automatically generating additional relationships from the EQs

### ISSUE THREAD

**Issue by matentzn** [obophenotype/human-phenotype-ontology#7347]
After months of debate, we now have a working proposal to get around the issue of users wanting to access the associated entities from the EQs directly. For example: to get from "Abnormal head morphology" to the "head" term (which was extremely difficult due to the sophistical logical structure of the EQs).

We have finally developed an extension that allows us simply generate direct relationships from EQs. We generate two relationships:

- "phenotype has associated entity", which is a very loose associative relationship that connects the phenotype to all entities mentioned by the EQ. 
- "has phenotype affecting", which is a more strong logical assertion between the phenotype and the (possibly complex) entity defined by the EQ.

Having these direct relationships is important for many use cases, e.g. grouping:
- Machine Learning (adding additional links to create signal)
- Give me all the phenotypes related to "head". 

We are rolling this out now across all phenotype ontologies. I am hoping to be able to add these relationships to HPO as well.

This is an example on how this looks like in Protege:

<img width="417" alt="image" src="https://user-images.githubusercontent.com/7070631/156775491-913aebfe-44c3-475c-a5aa-b20f6e5b069f.png">

@pnrobinson thank you for your feedback!

**Comment by pnrobinson** [comment]
From a software engineering point of view this seems suboptimal. Instead, we should develop some scripts using OWL API to generate a CSV file with information like this for downstream use. It is never good to represent the same information in two different ways in a database, right? :smile:

**Comment by matentzn** [comment]
I agree, but then people would have to always consider multiple files - in this case, the redundancy is managed by an automated pipeline, so no one would notice it.. Its not that I think you are wrong.. You are not. Let us see what others say and gather some pros and cons: 

Pros:
- Single file
- Beautiful knowledge graph queries (SPARQL etc)

Cons:
- Duplicated content considered bad engineering

**Comment by caufieldjh** [comment]
I'm in favor of including the associated entity relationships in the same file, for the sake of easier KG ingests and hopefully more informative models (e.g., phenotype entities should have more immediate neighbors describing their high-level involvement).
I'm curious about how those "phenotype has associated entity" are generated, though. If there's some degree of parameter tuning required to get the "right" amount and specificity of relationships then I can see how generating them after the fact would be preferable.

**Comment by cmungall** [comment]
I am in favor of including in the ontology file releases (owl, obo, obojson). Many bioinformatics users consume one of these files, or work with existing public ontology services that consume these files

**Comment by pnrobinson** [comment]
@matentzn @cmungall I do not have really strong feelings about this one way or another but agree this will be a useful feature. It seems the majority opinion is to put this in the same file. I guess this would mean a script that automagically modifies the hp OWL release file at each release and thence the json and obo files? 
This would be a great topic for the next Nucleic Acids Research update article -- can we write a paragraph or two while we are doing this work? It will be easier than coming back to this topic later on

**Comment by matentzn** [comment]
Awesome @pnrobinson this is what I wanted to hear. This will make for an excellent paragraph in the NAR paper (we can also get a draft release of the languages thing done for that one).

**Comment by pnrobinson** [comment]
@matentzn is this still active?

**Comment by matentzn** [comment]
I will try to push it through for the NAR paper.

**Comment by pnrobinson** [comment]
@matentzn what is the current status? 😄

**Comment by matentzn** [comment]
Still on my list, but edging closer to the top (currently on 9/20 of "non-essential but important issues to box through"). It is not forgotten

**Comment by pnrobinson** [comment]
@matentzn I am wondering maybe we can close this and reopen if there is an acute need?

**Comment by matentzn** [comment]
This is finished - we just need to meet and review it together in a meeting: https://github.com/obophenotype/human-phenotype-ontology/pull/10446
