### ISSUE TITLE
Creatine Transporter Deficiency has cardiac Arrhythmia Risk

### ISSUE THREAD

**Issue by sbergercnmc** [obophenotype/human-phenotype-ontology#7352]
**Disease ID and Name**
Creatine Deficiency Syndrome, X-linked OMIM:30035

**HPO ID and Name**
Prolonged QT interval HP:0001657

**Further information (Frequency, Onset, Pubmed-references, Comments)**
[Genet Med. 2021 Oct; 23(10): 1864–1872.]
Published online 2021 May 28. doi: [10.1038/s41436-021-01224-8](https://dx.doi.org/10.1038%2Fs41436-021-01224-8)
PMCID: PMC8487919
NIHMSID: NIHMS1717831
PMID: [34050321](https://www.ncbi.nlm.nih.gov/pubmed/34050321)
X-linked Creatine transporter deficiency results in prolonged QTc and increased sudden death risk in humans and disease model

**Comment by pnrobinson** [comment]
thanks for pointing this out, I added it to the annotations. This will be visible with the next HPO release in about 2 months.
