### ISSUE TITLE
Error in frequency of phenotype annotations for `OMIM:300912`

### ISSUE THREAD

**Issue by ielis** [obophenotype/human-phenotype-ontology#7353]
**HPO term**
The issue is not regarding an HPO term, but 3 annotations of `OMIM:300912` in the `phenotype.hpoa` file.

**Bug description**
In release `2022-02-14` there is an error in the frequency field of the following annotation lines:
- `HP:0000486` - frequency is `9/7`
- `HP:0001249` - frequency is `9/7`
- `HP:0000750` - frequency is `11/9`

Numerator cannot be greater than the denominator.

**Comment by pnrobinson** [comment]
fixed.
