### ISSUE TITLE
Acidosis vs acidemia

### ISSUE THREAD

**Issue by edfoster10** [obophenotype/human-phenotype-ontology#736]
Acidemia is currently an exact synonym of acidosis (HP_0001941).

From what I can tell these terms are used interchangeably, but are not applied consistently as exact synonyms across subclasses. Are these terms truly exact synonyms of each other?

**Comment by pnrobinson** [comment]
Acidemia is the actual measurement of a low pH in blood (below 7.35). Acidosis is an abnormal physiological state with excessive acid levels. Therefore, the terms are not exactly the same thing, however, since the terms are used synonymously in the clinic, the HPO does not make a distinction between them. (The process of acidosis is observed because of a measurement of acidemia). It seems that in typical clinical usage certain terms are preferred (e.g., metabolic acidosis seems to be used exclusively because there is an inference about the type of process leading to an acidemia in the blood). I think it would be confusing to try to be too linguistically correct here, and we have tried essentially to use the phrases that are in common clinical use. If there is a case where it is important to distinguish between acidemia and acidosis, then we may need to rethink this -- please then re-open this comment!

**Comment by nicolevasilevsky** [comment]
In LOINC, they have codes for pH of Blood and pH of urine. 
@callahantiff's team annotated 'Low pH of blood' and 'Low pH of urine'- both as HP_0001941	Acidosis.

In this case, I think it may be more accurate if we separated out acidemia and acidosis as separate terms. Or maybe clinically it makes sense to annotate them both as acidosis?

**Comment by pnrobinson** [comment]
Low ph of blood is acidemia. Acidosis is an inference about the overall metabolic state.

**Comment by callahantiff** [comment]
I was curious about this and did find an article what indicates in a nice [Figure](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3680269/figure/f1-pch18029/), that a low blood pH (<=7.39) is indicative of acidemia and in this case, the primary disorder would be acidosis [PMID24381489](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3680269/). Reading further, I found that, "When describing acid-base abnormalities, acidosis and alkalosis refer to physiological processes that lower or raise the pH, respectively, while acidemia and alkalemia simply describe the state of an abnormal blood pH. This distinction is important: a patient with acidemia could have both a respiratory and metabolic acidosis as well as a concurrent metabolic alkalosis." I think it's important to note that determining the type of acidosis (metabolic or respiratory), requires including additional lab results. So, I think we have two options:  1) change our annotation to acidemia unless we combine multiple labs, which would then allow us to determine the type of acidosis; 2) assign both acidemia and acidosis and don't specify the type of acidosis (assuming we are only considering the low blood pH lab result). What are your thoughts?

For low pH in urine, I understand why the clinicians choose [acidosis] (https://www.ucsfbenioffchildrens.org/tests/003583.html) as there is not currently a better fitting HPO term. The only alternative would be to choose the parent concept for aciduria, which when compared to acidosis seems like a worse fit. Thoughts here?

**Comment by nicolevasilevsky** [comment]
@callahantiff currently acidemia is a synonym for acidosis.

Another question that I have is how should we annotate the high value for pH of urine or blood - would that be HP_0001948 Alkalosis?

**Comment by callahantiff** [comment]
Should we then annotate both acidosis and acidemia explicitly? If we did not, even though they are synonyms would we miss other relations?

That's also a good question for annotating high pH for urine and blood. I think alkalosis makes the most sense given the currently available terms.

**Comment by pnrobinson** [comment]
I think the HPO terms should refer to the observed phenotypes -- this is acidemia and not acidosis. Since these terms may be used synonymously in the clinic, I would add the -osis terms as related synoynyms.

**Comment by pnrobinson** [comment]
Actually, there are several children of acidosis that probably are true -osis terms. Let's think about this.

**Comment by nicolevasilevsky** [comment]
@pnrobinson on our call today we discussed the possibility of creating a new class for acidemia (which is currently a synonym of HP_0001941 Acidosis

cc @callahantiff

**Comment by pnrobinson** [comment]
revised this and added new terms and disambiguated the concepts
