### ISSUE TITLE
prenatal renal ultrasonography

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#7362]
**Preferred term label:**
prenatal renal ultrasonography

Can we add this term and other prenatal sonography terms to HPO @matentzn @LCCarmody 

**Your nano-attribution (ORCID)**

**Comment by matentzn** [comment]
@LCCarmody Let me know if you need help setting this up, happy to support you!

**Comment by LCCarmody** [comment]
My only question is to patternize this--as this has been an issue with 'prenatal' terms before. I could use UBERON:0000323 late embryo (which HPO uses for prenatal elsewhere).

There is also UBERON:0009097 gravid organism but I believe Melissa had an issue with that (although I cannot find that discussion). 

So, something like this:
'ultrasonography procedure'
 and ('has input' some ('part of' some kidney))
  and ('inheres in part of' some 'late embryo')

**Comment by pnrobinson** [comment]
Note that embryonal is only up to 8 weeks gestational age and so we need a term that encompasses fetal -- doesn't uberon have something like that?

**Comment by LCCarmody** [comment]
Uberon's definition of 'late embryo' is "An embryo that is at the late embryonic stage; this stage covers late steps of the embryogenesis with a fully formed embryo still developing before birth or egg hatching. "  
and external definitions is: "Fetal structure, which is a developmental form of a vertebrate animal at any given time point from 8 weeks of gestation to birth (or hatching). Examples: There is only one fetus[FMA:63919]."

**Comment by LCCarmody** [comment]
I understand, but the narrow synonym for uberon is 'fetus'. We could open a ticket in UBERON? @matentzn ? @cmungall ?

**Comment by pnrobinson** [comment]
I am basically saying that uberon is wrong here, unless the terminology for non-human species is different. Since we are talking about a human diagnostic procedure, we definitely should not be using this term! :smile:

**Comment by PaulNSchofield** [comment]
Human embryonic-fetal transition is set by the first appearance of ossification in the humerus. This is sometime between week 7 and the end of 8 depending on the individual.  The terminology for other species is different and in fact its a well established norm that the mouse is considered not to have a fetal period by these criteria and you will rarely see reference to a mouse fetus. We should not be using the term "embryo" here if we are looking after the end of week 8 of gestation.

**Comment by pnrobinson** [comment]
We have added some new fetal onset terms. I will close this now, I think it is stale.
