### ISSUE TITLE
Hypertrophic labia minora (HP_0008694) vs Enlarged labia minora (HP_0008683)

### ISSUE THREAD

**Issue by edfoster10** [obophenotype/human-phenotype-ontology#737]
Seem to be synonyms of each other. Enlarged labia minora (HP_0008683) has a definition, but I'm not clear how it is different than Hypertrophic labia minora (HP_0008694).

**Comment by pnrobinson** [comment]
Thanks for picking this up, I agree they are synonymous, we will fix this.
