### ISSUE TITLE
Suggestions for new x-ref with SNOMED-CT and MedDRA

### ISSUE THREAD

**Issue by nbosc** [obophenotype/human-phenotype-ontology#7379]
ID | x-refs
-- | --
HP:0030157 | MedDRA:10016750||SCTID:247355005
HP:0002910 | MedDRA:10024690||SCTID:166603001
HP:0001657 | MedDRA:10014387||SCTID:111975006
HP:0003401 | MedDRA:10033775||SCTID:91019004
HP:0000708 | MedDRA:10061472||SCTID:75864003
HP:0002910 | MedDRA:10060795
HP:0002605 | MedDRA:10019692||SCTID:87248009
HP:0007185 | MedDRA:10024855||SCTID:419045004
HP:0001787 | MedDRA:10061781
HP:0001787 | SCTID:199745000
HP:0002590 | MedDRA:10021333
HP:0032310 | MedDRA:10018690||SCTID:317226009
HP:0001942 | MedDRA:10027417||SCTID:59455009
HP:0007957 | MedDRA:10011035
HP:0032156 | MedDRA:10041036
HP:0001913 | MedDRA:10018687||SCTID:417672002
HP:0025428 | MedDRA:10006482||SCTID:4386001
HP:0006677 | MedDRA:10014380
HP:0200119 | MedDRA:10019727
HP:0000112 | MedDRA:10029151
HP:0000726 | MedDRA:10078497||SCTID:10171000132106
HP:0001824 | MedDRA:10047895

Thanks

edit from 9th May 2022:
ID | x-refs
-- | --
HP:0001787 | MedDRA:10061781
HP:0004787 | MedDRA:10019772

**Comment by lcdaugherty** [comment]
Does this task include looking at all MedDRA and HPO?
eg: the above would miss this:
MEDDRA:10013573 for Dizziness is currently not featured in the OWL file. In theory it would be added to HPO term Vertigo https://hpo.jax.org/app/browse/term/HP:0002321 (Synonyms: Dizzy spell, Dizziness). 
Currently MEDDRA identifiers only appear 93 times in the ontology as dbxrefs for HPO terms, http://purl.obolibrary.org/obo/hp.owl
Are there plans to extend the update and integrate more MedDRA IDs to HPO as a cross-ref?

**Comment by nbosc** [comment]
This is just a modest contribution of xrefs. In no way I tried to map all the MedDRA terms but only those that I was using in a current safety project.

**Comment by lcdaugherty** [comment]
@nbosc ok thank you - it was wishful thinking on my behalf :)

**Comment by kanems** [comment]
@nbosc: the appropriate way to contact UMLS regarding HPO:CUI mappings is to open a ticket with the NLM Help Desk via this page: https://support.nlm.nih.gov/support/create-case/ (I work with the MedGen dataset, which contains only a subset of UMLS metathesaurus and I have no control over CUI x-refs or 'atoms' in the UMLS vernacular.)
