### ISSUE TITLE
 Clitoral hypertrophy (HP_0008665) vs Clitoromegaly (HP_0000057)

### ISSUE THREAD

**Issue by edfoster10** [obophenotype/human-phenotype-ontology#738]
Should Clitoromegaly (HP_0000057) be a subclass of Clitoral hypertrophy (HP_0008665) rather than a sibling class?

**Comment by pnrobinson** [comment]
Actually, perhaps it would be better to merge these terms, as they seem to be synonyms, or do you see a distinction?

**Comment by edfoster10** [comment]
I don't really see a distinction so merging them sounds good to me!
