### ISSUE TITLE
'beaded ribs' HP:0000923 - fractures vs rickets

### ISSUE THREAD

**Issue by azankl** [obophenotype/human-phenotype-ontology#7385]
We discussed this problem before when I tried to come up with a logical definition for beaded ribs (#3300). 
I think beaded ribs has 2 meanings: it can refer to a swelling at the junction of a rib and its cartilage, and this is related to rickets. But it can also refer (more commonly in my opinion) to multiple rib fractures. The term is currently assigned to various forms of osteogenesis imperfecta, and in these, the beaded ribs clearly refer to multiple fractures, not rickety changes. Also the current definition implies that there is only one swelling per rib (at the junction of rib and its cartilage), which is true for the rickety changes, but the beaded ribs caused by multiple fractures cause multiple swellings along the same rib. 

How about we rename HP:000923 to 'beaded ribs (rachitic rosary)' and create a new term 'beaded ribs (multiple rib fractures)' under 'Fractured rib HP:0041159'?

**Comment by pnrobinson** [comment]
There are existing terms

[Multiple rib fractures HP:0006640](https://hpo.jax.org/app/browse/term/HP:0006640)
and
[Rachitic rosary HP:0000897](https://hpo.jax.org/app/browse/term/HP:0000897)

I think what you are saying is that [Beaded ribs HP:0000923](https://hpo.jax.org/app/browse/term/HP:0000923) is potentially a synonym for both? Are there other causes? Do the phenotypes look different (without knowing the cause)?
@azankl

**Comment by azankl** [comment]
@pnrobinson yes, I am saying that [Beaded ribs HP:0000923](https://hpo.jax.org/app/browse/term/HP:0000923) is a synonym for [Multiple rib fractures HP:0006640](https://hpo.jax.org/app/browse/term/HP:0006640), while the current definition of [Beaded ribs HP:0000923](https://hpo.jax.org/app/browse/term/HP:0000923) makes it sound like a synonym of rachitic rosary. I don't use beaded ribs as a synonym for rachitic rosary, but I guess some people might use it that way. The phenotypic difference would be that beaded ribs in rachitic rosary would have one 'bead' per rib (a swelling at the costochondral junction), while beaded ribs in the context of multiple rib fractures have multiple 'beads' (fractures) along the same rib.

**Comment by pnrobinson** [comment]
@azankl 
Sorry for the delay in getting back.
The multiple rib fractures is sort of a higher level phenotypic observation that is based on more than beads, so it is not an exact synonym. The HPO does not encode pathophysiology, so the question is whether the beaded ribs from multiple fractures look different enough from the bearded ribs of a rachitic rosary so that one would recognize this reliably if this was the only sign one had? If this is the case, could you provide a definition please?

**Comment by azankl** [comment]
Beaded ribs in osteogenesis imperfecta refer to multiple bead-like structures along the ribs, caused by callus formation around multiple fractures along a rib. There are typically multiple beads along one rib and they can be located anywhere on the rib, not just at the costochondral junction. Figure 1 [here](https://www.ncbi.nlm.nih.gov/books/NBK279109/) shows a good example: 

In contrast, beaded ribs in rickets have one one bead per rib and its located at the costochondral junction. [Here](https://radiopaedia.org/cases/rickets-9) is an example. So yes, they look different.

How about the following:

1. We add beaded ribs as a synonym to Multiple rib fractures HP:0006640 and change the definition to: More than one fracture of the ribs. Callus formation around multiple rib fractures can give the appearance of ‘beaded ribs’.
2. We add beaded ribs as a synonym for Rachitic rosary HP:0000897 . The definition of Rachitic rosary (A row of beadlike prominences at the junction of a rib and its cartilage (i.e., enlarged costochondral joints), resembling a rosary.) includes the beaded ribs. 
3. We retire ‘Beaded ribs HP:0000923’. There are 7 disorders annotated to beaded ribs HP:0000923, I reviewed the literature to check which type of beaded ribs they are, they should be reassigned as follows:

**HP:0006640 multiple rib fractures:**
[OMIM:215140](https://hpo.jax.org/app/browse/disease/OMIM:215140) Greenberg skeletal dysplasia
[OMIM:616897](https://hpo.jax.org/app/browse/disease/OMIM:616897) Osteochondrodysplasia, complex lethal, Symoens-Barnes-Gistelinck type
[OMIM:166210](https://hpo.jax.org/app/browse/disease/OMIM:166210) Osteogenesis imperfecta, type II
[OMIM:259440](https://hpo.jax.org/app/browse/disease/OMIM:259440) Osteogenesis imperfecta, type IX
[OMIM:616229](https://hpo.jax.org/app/browse/disease/OMIM:616229) Osteogenesis imperfecta, type XVI

**HP:0000897 rachitic rosary:**
[OMIM:200600](https://hpo.jax.org/app/browse/disease/OMIM:200600) Achondrogenesis, type IA
[ORPHA:89936](https://hpo.jax.org/app/browse/disease/ORPHA:89936) X-linked hypophosphatemia

**Comment by pnrobinson** [comment]
@azankl THanks for this. I agree except that the current definition of Beaded ribs implies Multiple rib fractures (the comment implies rachitic rosary). I will retire Beaded ribs and merge it with Multiple rib fractures and adjust the definitions and annotations as you suggest. THANKS!

**Comment by pnrobinson** [comment]
@azankl 
Looking at https://omim.org/entry/200600
it is unclear what kind of beaded ribs are present. There are multiple fractures. Why is this rachitic rosary?

**Comment by azankl** [comment]
@pnrobinson I thought the flared ends of the ribs look more like a rachitic rosary, but the paper by Vanegas 2018 [cited in OMIM#200600](https://omim.org/entry/200600#18) specifically mentions rib fractures, so I think you are right, in OMIM#200600, beaded ribs should be rassigned to multiple rib fractures.

**Comment by pnrobinson** [comment]
OK, then we are all set! Thanks!
