### ISSUE TITLE
Maxillary lateral incisor microdontia HP:0001593 

### ISSUE THREAD

**Issue by anna-anagnostop** [obophenotype/human-phenotype-ontology#7386]
**HPO term Maxillary lateral incisor microdontia HP:0001593 currently uses "lower jaw incisor" UBERON:0003451 in the EQ**

**Suggested revision of logical definition: EQ should use "upper lateral incisor tooth" UBERON:0018604**

Regards, 

Anna

**Comment by pnrobinson** [comment]
Thanks for pointing out this error, I have fixed it!
