### ISSUE TITLE
Generalizing HPO morphology patterns to remove redundant part 

### ISSUE THREAD

**Issue by anna-anagnostop** [obophenotype/human-phenotype-ontology#7388]
While reviewing MP-HPO logical mappings, it came to my attention that the EQ for Abnormal cardiac atrium morphology [HP:0005120](http://www.ebi.ac.uk/ols4/ontologies/hp/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHP_0005120) uses: 

has part some (morphology and (inheres in some (cardiac atrium and (part of some heart))) and (has modifier some abnormal))

There are additional terms under Abnormal heart morphology [HP:0001627](http://www.ebi.ac.uk/ols4/ontologies/hp/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHP_0001627) branch (e.g. Abnormal heart valve morphology [HP:0001654](http://www.ebi.ac.uk/ols4/ontologies/hp/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHP_0001654)  -- and possibly elsewhere -- that use the redundant part.

EQ for the matching MP term (abnormal heart atrium morphology [MP:0003105](http://www.ebi.ac.uk/ols4/ontologies/mp/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FMP_0003105) does not include the (part of some heart) bit.

Please consider generalizing these patterns to remove the redundant part in the HPO.

Thank you,

Anna

**Comment by pnrobinson** [comment]
@matentzn @LCCarmody I think this should be simply
```
has part some (morphology 
and (inheres in some and (part of some cardiac atrium)) 
and (has modifier some abnormal))
```
does that sound about right (the atrium is part of the heart and not the entire atrium needs to be abnormal).

**Comment by matentzn** [comment]
@LCCarmody: EQ should be according to what Peter suggests here:

```
has part some (morphology 
and (inheres in part of some cardiac atrium) 
and (has modifier some abnormal))
```

- [ ] @rays22  Please make sure there is a pattern that uses `inheres in part of` with `morphology` (not just `inheres in`)

**Comment by anna-anagnostop** [comment]
Peter's suggestion sounds correct me.
@rays22 Please note there is a pattern available for [abnormalMorphologyOfPartOfAnatomicalEntity](https://github.com/obophenotype/upheno/blob/master/src/patterns/dosdp-dev/abnormalMorphologyOfPartOfAnatomicalEntity.yaml)

**Comment by pnrobinson** [comment]
@LCCarmody @matentzn @anna-anagnostop @rays22 
Can we close this issue? What was the outcome?

I think that the documentation of these patterns is currently rather opaque and suggest that we make an entry for each pattern like this in http://obophenotype.github.io/human-phenotype-ontology/ ?

**Comment by rays22** [comment]
@pnrobinson, I think the outcome is a consensus on the suggestion to change the logical definitions of [Abnormal cardiac atrium morphology](http://purl.obolibrary.org/obo/HP_0005120) and [Abnormal heart valve morphology](http://purl.obolibrary.org/obo/HP_0001654)
to: 

```
has part some (morphology 
and (inheres in part of some cardiac atrium) 
and (has modifier some abnormal))
```

However, it looks like the suggestion has not been actioned yet.

I also think that it is a good idea to document the pattern and reference the description section of the uPheno pattern [abnormalMorphologyOfPartOfAnatomicalEntity](https://github.com/obophenotype/upheno/blob/master/src/patterns/dosdp-dev/abnormalMorphologyOfPartOfAnatomicalEntity.yaml).

**Comment by LCCarmody** [comment]
just so we are cleare 'inheres in part of' is actually now 'characterstic of part of'

**Comment by rays22** [comment]
> just so we are cleare 'inheres in part of' is actually now 'characterstic of part of'

Yes, the current label for `inheres in part of` is [`characteristic of part of`](https://www.ebi.ac.uk/ols4/ontologies/ro/properties/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FRO_0002314).

```
has part some (morphology 
and (characteristic of part of some cardiac atrium) 
and (has modifier some abnormal))
```

**Comment by pnrobinson** [comment]
@rays22 
 it would be good to start to have English language definitions of all of the patterns, but that is outside of my wheelhouse (the yaml files are only good if you know what you want to look for; it would be great to have a table of related patterns).
I will add the corresponding definitions to the hp-edit file. Thanks!

**Comment by rays22** [comment]
> @rays22 it would be good to start to have English language definitions of all of the patterns, but that is outside of my wheelhouse (the yaml files are only good if you know what you want to look for; it would be great to have a table of related patterns). I will add the corresponding definitions to the hp-edit file. Thanks!

1. it would be good to start to have English language definitions of all of the patterns

I have just double checked, and the good news is that every uPheno pattern has an English language definition and also a description. However, I acknowledge that the English of some of the free text definitions and descriptions is weird. I would be happy to implement any suggested improvements on a case-by case basis.

2.  it would be great to have a table of related patterns).

@pnrobinson , by a table of related patterns, do you mean like a [tabular format representation](https://github.com/obophenotype/upheno/tree/master/src/patterns/dosdp-patterns) of the browsable [uPheno pattern ontology here](https://ols.monarchinitiative.org/ontologies/upheno_patterns) ?

**Comment by pnrobinson** [comment]
@rays22 -- it would be nice to have a more intuitive and compact summary of available terms. I think it would be good for the HPO project to have some publication that describes all of this work and how it relates to MPO. I do not want to lead such a manuscript but would be happy to contribute, and it would be great for the R24 project @mellybelly @cmungall 
As is, the resources are very opaque and it would be a major project to explore and understand!

**Comment by matentzn** [comment]
We are working on the uPheno 2 manuscript and all of this will be explained as part of that paper.
