### ISSUE TITLE
Synonym reassignment: 'Petit mal seizure'

### ISSUE THREAD

**Issue by edfoster10** [obophenotype/human-phenotype-ontology#739]
'Petit mal seizure' is currently an exact synonym to HP_0011147 Typical absence seizure. However, I think this synonym would be more accurate as an exact synonym to HP_0002121 Absence seizure.

**Comment by pnrobinson** [comment]
I agree, thanks!

**Comment by pnrobinson** [comment]
This was already fixed, I am closing this issue.
