### ISSUE TITLE
Limited ankle dorsiflexion

### ISSUE THREAD

**Issue by jagcsun** [obophenotype/human-phenotype-ontology#7396]
**HPO term**
Limited ankle dorsiflexion (HP:0033526)

**Synonym to be added**
Heel cord tightness(PMID: 22506166); tight heel cord(PMID: 26589087)

**broad/exact/narrow/plural/abbreviation ?**

**Your nano-attribution (ORCID)**
000-0002-6670-9157

@pnrobinson

**Comment by pnrobinson** [comment]
added, thanks
