### ISSUE TITLE
Similar synonyms: Bowing of the legs (HP_0002979) & Genu varum (HP_0002970) 

### ISSUE THREAD

**Issue by edfoster10** [obophenotype/human-phenotype-ontology#740]
The existing synonyms are very similar - in many ways, the same. Is there a better way to distinguish them, particularly since 'Genu varum' is a subclass of 'Bowing of the legs'?

**Comment by pnrobinson** [comment]
Thanks for picking this up, I have moved the synonyms to the superclass "Bowing of the legs"
