### ISSUE TITLE
Disagreement between downloaded files and online website

### ISSUE THREAD

**Issue by crispgc** [obophenotype/human-phenotype-ontology#7405]
**HPO term**
Global developmental delay HP:0001263

**Bug description**
We've found a disagreement between the files downloaded from the HPO webpage (https://hpo.jax.org/app/download/annotation) and the information on the online site. As an example, the HP:0001263 in the files, appears to be associated with the gene ACTL6A in the phenotype_to_genes.txt through the ORPHA:528084.

We've seen a couple of discrepancies:
- The gene is not present in the HPO website, even trying with synonymous names.
- The file genes_to_phenotype.txt does not seem to contain the ACTL6A gene and the beforementioned relationship.

As we download the file to use in our daily workflow, being in sync with the online site is very important. We have seen multiple similar cases just using the HP:0001263, with around 100 genes without the relationship in the web. After taking a look, only diseases that have a ORPHA disease related, but not an OMIM seems to be affected by this, but it's only a first look into the data.

Is there any explanation that we should know about this associations made in the file but not in the site?

Best

**Comment by pnrobinson** [comment]
ACTL6A is not considered to be a disease gene in OMIM (https://omim.org/entry/604958?search=actl6a&highlight=actl6a)
However, it is one of many genes listed without provenance in ORPHA (https://www.orpha.net/consor/cgi-bin/Disease_Search.php?lng=EN&data_id=27491&Disease_Disease_Search_diseaseGroup=ACTL6A&Disease_Disease_Search_diseaseType=Gen&Disease(s)/group%20of%20diseases=Non-specific-syndromic-intellectual-disability&title=Non-specific%20syndromic%20intellectual%20disability&search=Disease_Search_Simple).

@drseb Is the ACTL6A coming in via Orphanet? in this particular case it may be an error, or can we track down the source of the assertion?

**Comment by crispgc** [comment]
Hello, is there any update on this issue?

Best

**Comment by pnrobinson** [comment]
I see this article -- https://pubmed.ncbi.nlm.nih.gov/28649782/
I reported this to OMIM, and once they have created an ID we can add annotations. Our current pipeline is dependent on this 
Is this the only discrepancy?

**Comment by pnrobinson** [comment]
I think this issue has been resolved upstream:
```
grep ACTL6A phenotype_to_genes.txt
```
returns nothing. Sorry for the delay and thanks for reporting this issue.
