### ISSUE TITLE
Abnormal auditory Sensitivity

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#7413]
Explore terms related to poor tolerance of background noise
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6483953/

**Comment by pnrobinson** [comment]
How does this relate to existing term [Phonophobia HP:0002183](https://hpo.jax.org/app/browse/term/HP:0002183)

**Comment by pnrobinson** [comment]
I think this is likely the same thing
https://www.google.com/search?client=firefox-b-e&q=phonophobia+autism
I will add this as a related synonym

**Comment by bcoleman96** [comment]
The theory was that they weren't, but that paper seems to disprove it. What about with higher ranges where there is variable sensitivity? For example, an office worker complaining about a high-pitched noise when their coworkers can't hear it.

**Comment by pnrobinson** [comment]
@bcoleman96 
Looking at the terms underneath [Auditory hypersensitivity HP:5200060](https://hpo.jax.org/app/browse/term/HP:5200060) I think we are fine, this issue was superceded.
