### ISSUE TITLE
Creatine kinase - CK or CPK?

### ISSUE THREAD

**Issue by turnovec** [obophenotype/human-phenotype-ontology#7418]
**HPO term**
HP:0003236 | Elevated circulating creatine kinase concentration 
HP:0030234 | Highly elevated creatine kinase 
HP:0025659 | Decreased circulating creatine kinase concentration 

**Suggested revision of textual definition**
One of our translators insist on one acronym for creatine kinase - CK. In some definitions it's written just as CPK. I think in synonyms it's OK to have both variants if they are really used (in some countries maybe yes), but in definitions it should be standardized and written in one way (or write it in full as creatin kinase and not acronym). In main terms it's also written in full.

**Comment by pnrobinson** [comment]
I believe Creatine kinase and creatine phosphokinase are synonyms. In my experience CK is the more common abbreviation, but I have just also seen CPK in a short Google search. I will standardize the abbreviations in these definitions as CK.

**Comment by pnrobinson** [comment]
done

**Comment by turnovec** [comment]
For HP:0030234 there is still "CPK" in definition instead of CK.
