### ISSUE TITLE
Interchanged acronyms for ADH and ALDH in HP:0003533

### ISSUE THREAD

**Issue by turnovec** [obophenotype/human-phenotype-ontology#7419]
**HPO term**
HP:0003533 | Reduced acetaldehyde dehydrogenase level

**Bug description**
It looks like the acronyms in this definition are interchanged: "Decreased level of acetaldehyde dehydrogenase (ADH). ADH and alcohol dehydrogenase (ALDH) are the primary enzymes involved in alcohol metabolism."

ADH is usually used for alcoholdehydrogenase and ALDH for acetaldehyde dehydrogenase.

**Comment by pnrobinson** [comment]
Thanks for pointing out this error, I have fixed it.
