### ISSUE TITLE
Plural instead of singular in one synonym for HP:0009947

### ISSUE THREAD

**Issue by turnovec** [obophenotype/human-phenotype-ontology#7420]
**HPO term**
HP:0009947 | Duplication of the proximal phalanx of the 2nd finger 

**Bug description**
In "Duplication of the proximal bones of the index finger" the word "bones" should be changed to "bone" (as far as I know there is only one proximal bone for the index finger, like for other fingers).

**Comment by pnrobinson** [comment]
thanks, I have corrected this error as suggested!
