### ISSUE TITLE
Error in definition for HP:0009278: Deviation of the finger towards itself

### ISSUE THREAD

**Issue by turnovec** [obophenotype/human-phenotype-ontology#7422]
**HPO term**
HP:0009278 | Ulnar deviation of the 4th finger 

**Bug description**
Small logical error in the definition:
"Displacement of the 4th finger towards the ulnar side (i.e., towards the ring finger)."

The 4th finger itself is ring finger. So it should be "towards 5th finger" or "towards little finger".

**Comment by pnrobinson** [comment]
Thanks!
I have modified to 
```
Displacement of the 4th finger towards the ulnar side (i.e., towards the 5th finger).
```
