### ISSUE TITLE
Improved definition for HP:0010689

### ISSUE THREAD

**Issue by turnovec** [obophenotype/human-phenotype-ontology#7423]
**HPO term**
HP:0010689 Mirror image polydactyly 

**Bug description**
We think that last sentence of definition:
"The most lateral digits on each side of the **hand** typically resemble fifth fingers/toes."

Should be corrected to:
"The most lateral digits on each side of the **hand/foot** typically resemble fifth fingers/toes."

**Comment by pnrobinson** [comment]
Thank you, excellent suggestion! I have changed the definition as you suggest.
