### ISSUE TITLE
Amniotic fluid index

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#7428]
Should we show Increased Amniotic fluid index as a synonym for [Polyhydramnios](https://hpo.jax.org/app/browse/term/HP:0001561) and Decreased amniotic fluid index as a synonym for [Oligohydramios](https://hpo.jax.org/app/browse/term/HP:0001562) ?

See
[Amniotic fluid index](https://en.wikipedia.org/wiki/Amniotic_fluid_index)

**Comment by carlotarodo** [comment]
yes

**Comment by pnrobinson** [comment]
thanks, added
