### ISSUE TITLE
Should "cancer" be a synonym of "neoplasm"?

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#743]
I asked this question when we were in Portland and I thought the answer was cancer should not be a synonym of neoplasm.

The term HP_0012720	Neoplasm of the nose has the synonym "Nose cancer". 

I think there may be other cases like this.

**Comment by pnrobinson** [comment]
According to NCI: Neoplasm = An abnormal mass of tissue that results when cells divide more than they should or do not die when they should. Neoplasms may be benign (not cancer), or malignant (cancer). Also called tumor. 
So, the answer is "No".
Is suspect we will need to revise many of the synonyms. I will fix the Neoplasm of the nose issue now.
