### ISSUE TITLE
One of the synonyms for HP:0002700 is not capitalized, "hyperplasia" is questionable in this case

### ISSUE THREAD

**Issue by turnovec** [obophenotype/human-phenotype-ontology#7435]
**HPO term**
HP:0002700 | Large foramen magnum

**Bug description**
"**e**nlarged foramen magnum" -> "**E**nlarged foramen magnum"

It's also a question if the synonym could be "Hyperplasia of foramen magnum". Hyperplasia means that something is growing more then normal. But can we use the word hyperplasia to describe an opening that´s bigger than it´s supposed to be?

**Comment by pnrobinson** [comment]
I have corrected the capitalization. I agree that "Hyperplasia of foramen magnum" does not make sense and have removed it. Thanks for pointing this out.
