### ISSUE TITLE
Erorr in definition of HP:0500012

### ISSUE THREAD

**Issue by turnovec** [obophenotype/human-phenotype-ontology#7437]
**HPO term**
HP:0500012 | Abnormality of gonadotropin-releasing hormone level

**Bug description**
"A deviation from the normal circulating concentration of the normal gonadotropin-releasing hormone level secreted from the pituitary gland."

Gonadoliberin/Gonadorelin/GnRH  is produces by hypothalamus, not hypophysis.

**Comment by pnrobinson** [comment]
You are right, thanks for pointing out this error.
I have changed the term label to Abnormal gonadotropin-releasing hormone concentration (for consistency with other terms)
and changed the definition to
A deviation from the normal circulating concentration of the normal gonadotropin-releasing hormone (GnRH). Intermittent GnRH secretion from the hypothalamus acts upon its receptor in the anterior pituitary to regulate the production and release of the gonadotropins, follicle-stimulating hormone (FSH) and luteinizing hormone (LH).
