### ISSUE TITLE
HP:0041232 Fractured skeleton of manual acropodium

### ISSUE THREAD

**Issue by grahamponting** [obophenotype/human-phenotype-ontology#7448]
I am not sure which bone this concept refers to. Acropodium refers to the dorsum of the foot, although it is not a term I have heard of anatomically, and the parent refers to the bones of the hand. Perhaps the definition could be updated.
Many thanks.
Graham Ponting

**Comment by pnrobinson** [comment]
Hi Graham, I think this was a mistake from the process in which we generated fracture terms from uberon bone terms. I will obsolete this, thanks for pointing this out!

**Comment by pnrobinson** [comment]
merged.
