### ISSUE TITLE
Question about synonyms for HP_0000925	Absent/underdeveloped spine

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#745]
Thes synonyms seem too broad. Should there be an 'Abnormality of the spine' class that is a parent of HP_0000925	Absent/underdeveloped spine? 

Abnormality of the spine
Abnormal vertebral column
Abnormality of the backbone
Abnormal spine

@mellybelly

**Comment by nicolevasilevsky** [comment]
This term has the synonym 'abnormal spine' HP_0000925 Abnormality of the vertebral column

**Comment by cmungall** [comment]
seems totally fine to me

```
[Term]
id: HP:0000925
name: Abnormality of the vertebral column
namespace: human_phenotype
def: "Any abnormality of the vertebral column." [HPO:probinson]
subset: hposlim_core  ! Core clinical terminology
synonym: "Abnormal spine" EXACT [HPO:skoehler]
synonym: "Abnormal vertebral column" EXACT []
synonym: "Abnormality of the backbone" RELATED []
synonym: "Abnormality of the spine" EXACT []
is_a: HP:0009121  ! Abnormal axial skeleton morphology
property_value: HP:0040005 "Any abnormality of the `vertebral column` (FMA:13478)." xsd:string
```

**Comment by nicolevasilevsky** [comment]
Sorry for the confusion, the issue is there are similar synonyms for this term: HP_0000925 Absent/underdeveloped spine

**Comment by drseb** [comment]
I do not find any occurrence of "Absent/underdeveloped spine" in HPO. Closing for now. Let me know if there is still something unclear

**Comment by nicolevasilevsky** [comment]
Oh yeah, you are right. Somehow the label was wrong in our spreadsheet. Thanks!
