### ISSUE TITLE
Patent Ductus Arteriosus

### ISSUE THREAD

**Issue by TonyRoscioli** [obophenotype/human-phenotype-ontology#7454]
**HPO term**
Patent Ductus Arteriosus

**Suggested revision of textual definition**
Persistent Ductus Arteriosus

**Comment by pnrobinson** [comment]
I think that Patent DA is the preferred term, see for instance https://www.heart.org/en/health-topics/congenital-heart-defects/about-congenital-heart-defects/patent-ductus-arteriosus-pda and https://www.ahajournals.org/doi/10.1161/circulationaha.105.592063
'Persistent ductus arteriosus' is listed as a a synonym, see [Patent ductus arteriosus HP:0001643](https://hpo.jax.org/app/browse/term/HP:0001643)
