### ISSUE TITLE
Laterality, severity, progression, non-progression, time of life of presentation

### ISSUE THREAD

**Issue by TonyRoscioli** [obophenotype/human-phenotype-ontology#7455]
**HPO term**

Some anatomical abnormalities may have laterality - could be useful to add a unilateral or bilateral term for those features where either is possible

Same for static versus progressive.   There are some terms that have the primary terms and also additional terms with static and or progressive.   It could be useful to enable the addition of static or progressive for all terms where this is possible.

For prenatal onset, many features could be prenatal or postnatal or both - it could be useful to enable the additional of prenatal and postnatal for each features where this is possible

**Suggested revision of logical definition**

**Comment by pnrobinson** [comment]
@TonyRoscioli 
The HPO developed a series of [Clinical modifier](https://hpo.jax.org/app/browse/term/HP:0012823) terms a few years ago to do just this! Happy to provide more explanation by zoom
