### ISSUE TITLE
HP:0033724 Central venous sinus thrombosis

### ISSUE THREAD

**Issue by grahamponting** [obophenotype/human-phenotype-ontology#7458]
Reading the definition for this concept, I think it's highly likely that the title should be "**Cerebral** venous sinus thrombosis". I can't find any reference anatomically to a "Central venous sinus"  and it would fit with the other related concepts (siblings)
Many thanks
Graham Ponting

**Comment by pnrobinson** [comment]
Thanks for pointing out this error, I have corrected it to Cerebral venous sinus thrombosis
