### ISSUE TITLE
Inconsistent OMIM->HPO mapping between website and phenotype_annotation.tab file

### ISSUE THREAD

**Issue by yarong-lifemap** [obophenotype/human-phenotype-ontology#7464]
**HPO term**
HP:0003678

**Bug description**
In the "phenotype_annotation.tab" (http://purl.obolibrary.org/obo/hp/hpoa/phenotype_annotation.tab) file there is a mapping between OMIM:612954 and HP:0003678:
`OMIM       612954  Myopathy, myofibrillar, 6               HP:0003678      OMIM:612954    IEA                              C       MYOPATHY, MYOFIBRILLAR, 6       HPO:skoehler[2010-06-19]        -`

However, in the website, the HP:0003678 cannot be found at https://hpo.jax.org/app/browse/disease/OMIM:612954, nor can the disease be found in https://hpo.jax.org/app/browse/term/HP:0003678.

Thanks in advance!

**Comment by pnrobinson** [comment]
The website currently does not display terms such as [Rapidly progressive HP:0003678](https://hpo.jax.org/app/browse/term/HP:0003678) that represent "disease modifiers". This has been on our to-do list. I am transferring this issue to the website repository: https://github.com/TheJacksonLaboratory/hpo-web/issues/190
