### ISSUE TITLE
Cervical spine anomalies

### ISSUE THREAD

**Issue by IreneValenzuela** [obophenotype/human-phenotype-ontology#7467]
Dear all, 

Revising different patients with cervical spine alterations I've found that some disease with this manifestation are not represented with the hpo term. 
marshall-smith. Cervical cord compression HP:0002341 ( https://doi.org/10.1002/ajmg.a.33709) 

Sox9. Campomelic dysplasia/acampomelic dysplasia. Cervical spine instability HP:0010646 (https://pubmed.ncbi.nlm.nih.gov/20301724/)

Would it be possible to add this hpo to this diseases. Cervical spine alterations are quite atypical and it must be a guiding sign to diagnosis. 

Thank you in advance, 

Best, 

Irene

**Comment by pnrobinson** [comment]
I added both of these annotations, thanks for the suggestion. They will be visible with the next HPO release in June.
