### ISSUE TITLE
Cervix cancer should not be a Uterine neoplasm

### ISSUE THREAD

**Issue by buske** [obophenotype/human-phenotype-ontology#7468]
**HPO term**
Cervix cancer HP:0030079

**Suggested revision and reasons**
Should not be a child of: Uterine neoplasm HP:0010784 (syn: Uterine cancer)

We are using HPO for some cancer risk assessment analyses, and encountered this issue when attempting to use the structure for inference. Cervical cancer is not a subtype of uterine cancer, and having cervical cancer does not imply having uterine cancer in terms of any computational analysis.

**Comment by pnrobinson** [comment]
fixed, thanks!
