### ISSUE TITLE
Should we have synonyms which are same as main term?

### ISSUE THREAD

**Issue by turnovec** [obophenotype/human-phenotype-ontology#7474]
Hello all,

I was just playing a bit with exporting HPO to more simple "flat format" for utilization in one of our databases and I found, that there are many terms, where one of the synonyms is same as the main term. For example, just the second HPO termi defined in .obo file:

**HP:0000002 - Abnormality of body height**
name: Abnormality of body height
synonym: "Abnormality of body height"

Is this intentional or some bug? It's definitely not for all terms (there are terms which don't have any synonym).

In case it's a bug, I'm attaching a list of all terms where one of the synonym is same as main term.

[synonyms_same_as_main_term.txt](https://github.com/obophenotype/human-phenotype-ontology/files/8556322/synonyms_same_as_main_term.txt)

**Comment by drseb** [comment]
Hey, thanks. this is correct in hpo. They should always have the layperson annotation. This our way of differentiating between professional and layperson terms.

**Comment by turnovec** [comment]
Ok, it makes sense. You are right that in most of them they have "EXACT layperson []".

But there are still some of them, where they don't. But much less. I'm attaching them again.

[synonyms_same_as_main_term_not_layperson.txt](https://github.com/obophenotype/human-phenotype-ontology/files/8562676/synonyms_same_as_main_term_not_layperson.txt)

In first case (Optic disc pallor) there is "RELATED uk_spelling []". But it's for just one case. In others there are mostly just "EXACT []". In several cases there are "EXACT []" with some ORCID number.

For "AV nodal tachycardia" there is synonym "AV nodal tachycardia" with annotation "EXACT abbreviation []".

**Comment by pnrobinson** [comment]
Thanks for pointing this out, @turnovec 
- [ ] HP:0000543 Optic disc pallor
- [ ] HP:0000625 Eyelid coloboma
- [ ] HP:0002308 Chiari malformation
- [ ] HP:0002663 Delayed epiphyseal ossification
- [ ] HP:0002684 Thickened calvaria
- [ ] HP:0003160 Abnormal isoelectric focusing of serum transferrin
- [ ] HP:0003341 Subepidermal blistering with cleavage in the lamina lucida
- [ ] HP:0005306 Capillary hemangioma
- [ ] HP:0006297 Enamel hypoplasia
- [ ] HP:0006315 Solitary median maxillary central incisor
- [ ] HP:0006518 Pulmonary venous occlusion
- [ ] HP:0007526 Hypopigmented skin patches on arms
- [ ] HP:0009804 Tooth agenesis
- [ ] HP:0011043 Abnormality of circulating adrenocorticotropin level
- [ ] HP:0011687 AV nodal tachycardia
- [ ] HP:0012254 Ewing sarcoma
- [ ] HP:0012432 Chronic fatigue
- [ ] HP:0012556 Hyperbeta-alaninemia
- [ ] HP:0012639 Abnormal nervous system morphology
- [ ] HP:0030269 Increased serum insulin-like growth factor 1
- [ ] HP:0030473 Abnormal light-adapted flicker electroretinogram
- [ ] HP:0030873 Anti-centromere antibody positivity
- [ ] HP:0032574 Elevated uridine in urine
- [ ] HP:0033000 Subglottic laryngitis
- [ ] HP:0033714 Multiple meningiomata
- [ ] HP:0034063 Anti-islet antigen-2 antibody positivity
- [ ] HP:0034241 Prenatal death
- [ ] HP:0040089 Abnormal natural killer cell count
- [ ] HP:0410054 Decreased circulating GABA concentration
- [ ] HP:0410267 Intestinal hemangioma
- [ ] HP:5000026 Anti-neurexin-3alpha antibody

**Comment by pnrobinson** [comment]
@turnovec  thanks again for pointing these items out. I have applied various corrections to remove redundancy.
