### ISSUE TITLE
Clarification request: Metaphyseal chondrodysplasia & Metaphyseal dysostosis

### ISSUE THREAD

**Issue by kanems** [obophenotype/human-phenotype-ontology#7476]
**HPO term**
Metaphyseal dysostosis HP:0005899
and
Metaphyseal chondrodysplasia HP:0005871

**Bug description**
UMLS has lumped these onto the same CUI (Metaphyseal chondrodysplasia, UMLS CUI: C0265290) possibly because SNOMED CT uses these names synonymously on their concept 28681006. 
Is Metaphyseal chondrodysplasia phenotype the same as Metaphyseal  dysostosis?

**Comment by pnrobinson** [comment]
[Metaphyseal chondrodysplasia HP:0005871](https://hpo.jax.org/app/browse/term/HP:0005871) -- 19 annotations
vs
[Metaphyseal dysostosis HP:0005899](https://hpo.jax.org/app/browse/term/HP:0005899) - 3 Annotations

Dysostosis is a disorder of an individual bone, either singly or in combination (e.g., skull and fingers)
Chondrodysplasias are also referred to as[skeletal dysplasias

The nomenclature is sometimes inconsistent, and the two terms above are probably synonymous, I think the latter term is hardly used at all. Both of them are really used to name groups of diseases with characteristic developmental defects in the metaphysis (neck portion of a long bone between the growth plate and the shaft). I think that we should merge these terms. 
We will retain the Metaphyseal chondrodysplasia HP:0005871
and merge the other term into it.

**Comment by pnrobinson** [comment]
Actually, I think that [Metaphyseal dysostosis HP:0005899](https://hpo.jax.org/app/browse/term/HP:0005899) is such an illdefined term that it should be merged into Metaphyseal dysplasia HP:0100255
