### ISSUE TITLE
Mouth neoplasm HP:0012290

### ISSUE THREAD

**Issue by kanems** [obophenotype/human-phenotype-ontology#7477]
**HPO term**
Mouth neoplasm HP:0012290

**Reason for deprecation**
It seems redundant with "Neoplasm of the oral cavity" HP:0100649

**Suggested replacement or term to consider**
Neoplasm of the oral cavity HP:0100649

**Comment by pnrobinson** [comment]
Thanks, you are of course correct.
We have retained
"Neoplasm of the oral cavity" HP:0100649
and added Mouth neoplasm as a synonym
