### ISSUE TITLE
HP:0000376 and synonyms

### ISSUE THREAD

**Issue by maglott** [obophenotype/human-phenotype-ontology#7482]
**HPO term**
Incomplete partition of the cochlea type II

**Synonym to be added**
I see UMLS has multiple CUI for what I think may be the same concept as Mondini malformation.  If you agree these are synonymous, could you add the terms to HPO as alternates?  I cannot tell if there are subtle distinctions, or failure to aggregate according to clinical usage.
Thanks
[Mondini defect (C0395941)](https://uts.nlm.nih.gov/uts/umls/concept/C0395941)
[Mondini dysplasia (C4230309)](https://uts.nlm.nih.gov/uts/umls/concept/C4230309)
[Cochlear malformation defect (Mondini dysplasia) (C5393344)](https://uts.nlm.nih.gov/uts/umls/concept/C5393344)
**broad/exact/narrow/plural/abbreviation ?**

**Comment by pnrobinson** [comment]
@maglott sorry for the delay on this one, which is difficult.
As far as I can see, the two concepts are not exactly synonymous, but the community is moving away from the "Mondini" desgination -- see for instance the Radiopedia entry [Cochlear incomplete partition type II ](https://radiopaedia.org/articles/cochlear-incomplete-partition-type-ii), where it is stated
IP-II should not be confused with [Mondini anomaly](https://radiopaedia.org/articles/mondini-malformation?lang=us), which is a historic term for the combination of incomplete partition type II, enlarged [vestibule](https://radiopaedia.org/articles/vestibule-ear?lang=us), and [large vestibular aqueduct](https://radiopaedia.org/articles/large-vestibular-aqueduct-syndrome-1?lang=us).

However, I think these are all related synonyms that people might want to find. I will add the above as RELATED and adapt the definition.

**Comment by pnrobinson** [comment]
I have added this comment
The triad of incomplete partition of the cochlea type II, dilation of the vestibule, and an enlarged vestibular aqueduct was previously referred to as a Mondini malformation but this nomenclature is no longer recommended. It is important to note that while reading the related literature, it is often not easy to understand if the authors use the correct terminology, so even in recent studies, the term Mondini should be considered with caution.
see PMID: 34698066
