### ISSUE TITLE
revise logical definition for Renal cyst, Pulmonary cyst etc

### ISSUE THREAD

**Issue by anna-anagnostop** [obophenotype/human-phenotype-ontology#7484]
Renal cyst HP:0000107, Pulmonary cyst HP:0032445 and possibly other cyst terms use an outdated pattern in their EQs.

Please consider updating the EQs to use the [cystInLocation](https://github.com/obophenotype/upheno/blob/master/src/patterns/dosdp-dev/cystInLocation.yaml) pattern.

Many thanks, 

Anna

**Comment by pnrobinson** [comment]
Hi @anna-anagnostop 
The old pattern is like this
```
'has part' some 
    ('increased amount'
     and ('characteristic of' some 
        (cyst
         and ('part of' some kidney)))
     and ('has modifier' some abnormal))
```
I think the new pattern is wrong
```
has_part' some ('cystic' and ('inheres_in' some %s) and ('has_modifier' some 'abnormal'))
```
because the cyst should **inhere in part of**
(Cysts do not affect the entire organ they are located in).

**Comment by anna-anagnostop** [comment]
Hello @pnrobinson
Thank you for pointing this out . We discussed this on the 9/8/2022 uPheno call and agreed that the pattern should be changed to:

'has part' some
(cystic and ('characteristic of part of' some %) and ('has modifier' some abnormal))

@rays22 will work on updating the pattern.

**Comment by rays22** [comment]
> Hello @pnrobinson Thank you for pointing this out . We discussed this on the 9/8/2022 uPheno call and agreed that the pattern should be changed to:
> 
> 'has part' some (cystic and ('characteristic of part of' some %) and ('has modifier' some abnormal))
> 
> @rays22 will work on updating the pattern.

The pattern template has been updated in https://github.com/obophenotype/upheno/issues/878 .
