### ISSUE TITLE
Vestibular Schwannoma capitalisation

### ISSUE THREAD

**Issue by DLewisSmith** [obophenotype/human-phenotype-ontology#7502]
**HPO term**
Vestibular Schwannoma HP:0009588
**Bug description**
Should the 'S' of schwannoma should be capitalised as it is? This is currently inconsistent with other term names and a bit of a pain for at least my annotation pipelines.

**Comment by pnrobinson** [comment]
There are those who capitilaze Schwannoma in honor of Dr Schwann, but I agree the lower-case version is more common and appropriate here, I am making this change.
