### ISSUE TITLE
Difference in HPO counts in gene_to_phenotype.txt vs phenotype_to_gene.txt

### ISSUE THREAD

**Issue by batsal** [obophenotype/human-phenotype-ontology#7503]
Hello,

I downloaded the annotation files from https://hpo.jax.org/app/download/annotation and counted the number of uniq HPO terms in the files. As you can see from below the number are quite different. We have more HPO terms in phenotype_to_genes.txt compared to the other file. What is the reason behind the difference? I looked through the documentation but couldn't find the answer. Could I get the correct link for the explanation? Thank you.

% cat genes_to_phenotype.txt | awk '{FS="\t"}{print $3}' | sort | uniq | wc -l
8986
% cat phenotype_to_genes.txt | awk '{FS="\t"}{print $1}' | sort | uniq | wc -l
10275

**Comment by pnrobinson** [comment]
Please see here https://hpo.jax.org/app/faq
What is the difference between genes_to_phenotypes.txt and phenotype_to_genes.txt ?
