### ISSUE TITLE
Triangular shaped phalanges of the hand HP:0009774, subtypes appear to  be inappropriate.

### ISSUE THREAD

**Issue by grahamponting** [obophenotype/human-phenotype-ontology#7507]
**HPO term**
Triangular shaped phalanges of the hand HP:0009774.
Some of the subtypes for this concept appear to be inappropriate. 
The concepts  HP:0009541 Abnormality of the phalanges of the 2nd finger, and HP:0009602 Abnormality of thumb phalanx, do not relate to triangular phalanges but are more generic. The other subtypes are all relevant to the parent.

I would suggest that the two concepts HP:0009541 and HP:0009602 are moved to more appropriate, where they would fit.
Many thanks Graham Ponting

**Comment by pnrobinson** [comment]
You are right, thanks for pointing this out, I have fixed the error. The revised version will be available with the next release in June.
