### ISSUE TITLE
request for synonym: 

### ISSUE THREAD

**Issue by petkraw** [obophenotype/human-phenotype-ontology#751]
HP:0002579: Gastrointestinal dysmotility
please add: obstipation. as synonym
or create new term.

**Comment by pnrobinson** [comment]
Obstipation is a German word that translates to constipation. In English the word is rarely used (I had never heard it)  but there are sources that say it means "severe constipation caused by intestinal obstruction". Do you have a reference?

**Comment by petkraw** [comment]
We stumbled upon "obstipation" in a German health record of a patient with Smith-Lemli-Opitz syndrome. However, with your explanation we could also use "constipation" HP:0002019 to code this feature. Thanks.
