### ISSUE TITLE
Spasticity cannot always be said to be a form of cerebral palsy

### ISSUE THREAD

**Issue by DLewisSmith** [obophenotype/human-phenotype-ontology#7519]
**HPO term**
HP:0001257 Spasticity appears as a child of Cerebral palsy HP:0100021

**Suggested revision and reasons**
Cerebral palsy definition "Cerebral palsy describes a group of permanent disorders of the development of movement and posture,..." states that these are disorders of development (correctly) but not all spasticity meets this definition. Many (or quite possibly most) people with spasticity have acquired disorders with onset after the fetal/early life period (e.g., multiple sclerosis, stroke, adult-onset HSP and SCA).

**Comment by DLewisSmith** [comment]
I think this relates to changes from 2022-02-14 to 2022-04-14 https://github.com/obophenotype/human-phenotype-ontology/issues/7315.

**Comment by pnrobinson** [comment]
Thanks, you are right, I corrected this.
