### ISSUE TITLE
request for synonyms

### ISSUE THREAD

**Issue by drkeoni** [obophenotype/human-phenotype-ontology#752]
These were all observed in real cases of transliterating free-text indications to HPO terms.

HP:0007366 Atrophy/Degeneration affecting the brainstem
Synonym: Brainstem atrophy

HP:0009931 Enlarged naris
Synonym: Large nares

HP:0002020 Gastroesophageal reflux disease
Synonym: GERD

HP:0002757 Recurrent fractures
Synonym: Frequent fractures

Thanks,

Jon Sorenson

**Comment by drseb** [comment]
thanks. will do!

**Comment by pnrobinson** [comment]
Added these synonyms, thanks!
