### ISSUE TITLE
New eye terms

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#753]
From simulconsult-list:

- Eye pain / Eye movement pain included; component of optic neuritis
- Eye: anterior chamber mass or cyst 
- Eye: eyelid fissures 
- Eye: eyelid fluttering / Fasciculation
- Eye: fovea, ectopic / Macula ectopic
- Eye: foveal reflex absent / Absence of the small yellow-white shiny reflection in the centre of the macula
- Eye: globe elongated 
- Eye: Mizuo phenomenon / Color change in retina after dark adaptation with light onset
- Eye: orbital cellulitis / Infection of structures surrounding eyes
- Eye: orbital dystopia / Vertical displacement of orbit
- Eye: pupils shape abnormal / Oval; misshapen
- Eye: sclera thick / Scleral thickening
- Eye: scleral staphyloma / Posterior bulging of eye wall (sclera)
- Eye: visual accommodation decreased / 
- Eye: vitreous veils / Surface layer of retina elevated into vitreous
- Eyelids, heliotrope rash / Violaceous, reddish, purple discoloration
- Eyes: lower eyelid hooded / Eyelid partly covered by skin when eyes are open; hooding
- Eyes: lower eyelid retraction 
- Eyes: thickened eyelids / Not swollen
- Eyes: upper eyelid hooded / Eyelid partly covered by skin when eyes are open; hooding
- Eyes: vitreous strands

**Comment by pnrobinson** [comment]
I am creating separate requests for these, closing this item
