### ISSUE TITLE
Abnormal blood oxygen level logical def uses wrong CHEBI term

### ISSUE THREAD

**Issue by dosumis** [obophenotype/human-phenotype-ontology#7539]
**HPO term**
Abnormal blood oxygen level
[http://purl.obolibrary.org/obo/HP_0500165 ](http://purl.obolibrary.org/obo/HP_0500165)

**Suggested revision of logical definition**

Current:

Equivalent to:
[has part](https://www.ebi.ac.uk/ols/ontologies/hp/properties?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FBFO_0000051) some (
    [amount](https://www.ebi.ac.uk/ols/ontologies/hp/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0000070) and
    [characteristic of](https://www.ebi.ac.uk/ols/ontologies/hp/properties?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0000052) some (
        [oxygen molecular entity](https://www.ebi.ac.uk/ols/ontologies/hp/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCHEBI_25806) and
        [part of](https://www.ebi.ac.uk/ols/ontologies/hp/properties?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FBFO_0000050) some [blood](https://www.ebi.ac.uk/ols/ontologies/hp/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0000178)) and
    [has modifier](https://www.ebi.ac.uk/ols/ontologies/hp/properties?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0002573) some [abnormal](https://www.ebi.ac.uk/ols/ontologies/hp/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0000460))

The use of a too general CHEBI term is causing lots of incorrect inference. e.g. 

HP:0031212 | Abnormal circulating progesterone level | HP:0500165 | Abnormal blood oxygen level
-- | -- | -- | --
HP:0410057 | Increased level of D-threitol in plasma | HP:0500165 | Abnormal blood oxygen level
HP:0040302 | Hyperglycerolemia | HP:0500165 | Abnormal blood oxygen level
HP:0031415 | High serum calcitriol | HP:0500165 | Abnormal blood oxygen level
HP:0003124 | Hypercholesterolemia | HP:0500165 | Abnormal blood oxygen level
HP:0011731 | Abnormality of circulating cortisol level | HP:0500165 | Abnormal blood oxygen level

Solution:

Use a more specific CHEBI term.  Probably [dioxygen](https://www.ebi.ac.uk/ols/ontologies/chebi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCHEBI_15379)

**Comment by pnrobinson** [comment]
dioxygen is of course correct. I fixed the definition.
