### ISSUE TITLE
New modifier suggestions

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#754]
from simulconsult list:
- modifier_Axial nature to joint or bone findings / Sacroiliitis, axial arthritis; neck
- modifier_Breast feeding triggers symptoms in infant / 
- modifier_Calcaneus nature to talipes / Foot dorsiflexed (toes up); calcaneovarus; calcaneovalgus; heel walking
- modifier_Carbohydrates treat attacks / Sugar; glucose
- modifier_Carbohydrates trigger attacks or aversion / Sugar, glucose
- modifier_Cervical localization to lymphadenopathy / 
- modifier_Cold temperature triggers attacks or aggravates findings / Winter; paramyotonia
- modifier_Dehydration triggers symptoms / 
- modifier_Discoid shape to rash / 
- modifier_Dull or aching character to pain or discomfort / 
- modifier_Elbow predominance / Appendicular
- modifier_Emergence over days / Acute, abrupt onset or course
- modifier_Emergence over minutes / Acute, abrupt onset or course
- modifier_Emergence over months / Subacute, chronic onset or course
- modifier_Ethanol triggers symptoms / Alcohol sensitivity, EtOH
- modifier_Fasting triggers attacks / Caloric deprivation.  Eating food diminishes attacks.
- modifier_Fingertip localization to ulceration / 
- modifier_Fructose triggers attacks / 
- modifier_Galactose triggers attacks / Lactose-containing milk
- modifier_Head trauma triggers worsening / Concussion injury
- modifier_Heat or fever improves condition / Hot or warmer weather
- modifier_Heat, fever, or systemic infection triggers attacks or aggravates findings / Febrile illness, infection or hyperthermia, hot or warmer weather, post-infectious
- modifier_Heavy meals trigger symptoms / Postprandial; food
- modifier_Hemorrhagic nature to skin lesions / 
- modifier_High-fat diet worsens symptoms or triggers attacks / 
- modifier_Hip predominance / 
- modifier_Hyperventilation triggers attacks / Hyperpnea
- modifier_Immunizations triggers attacks or aggravates findings / Vaccination
- modifier_Joint extensor surface localization / Rash, papules, Gottron, plaques
- modifier_Joints: predominantly large affected / 
- modifier_Joints: predominantly small affected / 
- modifier_Lateral nature to oral clefting / 
- modifier_Localization to trauma or contact points / Pathergy; pressure points
- modifier_Location distal: sensory / Peripheral
- modifier_Lower body predominance to findings / Legs more affected than arms; paraparesis, paraplegia
- modifier_Malar distribution to rash / Butterfly, cheekbone
- modifier_Menstruation triggers attacks in female / Menstrual periods (cycle)
- modifier_Migratory signs or symptoms / Migrating (migrant, transient) focal symptoms or signs (anatomical location changes over time)
- modifier_Monoarticular: joint involvement / One joint; pauciarticular, monoarthritis
- modifier_Multifocal nature to bone abnormality / 
- modifier_Oligoarticular: joint involvement / 2-4 joints; pauciarticular, oligoarthritis
- modifier_Pain wakes up from sleep / Night
- modifier_Perineal distribution to finding / Perineum, groin
- modifier_Perspiration occurs with cold, not heat / Sweating, environmental temp. <22º C; paradoxical
- modifier_Perspiration occurs with sweet gustatory stimuli / Sweating
- modifier_Polyarticular: joint involvement / Joints, more than 4 affected, polyarthritis
- modifier_Pregnancy relieves symptoms in female / 
- modifier_Pregnancy worsens symptoms in female / Triggers symptoms; pregnant
- modifier_Prolonged nature to fever / 
- modifier_Radicular distribution to symptoms / Dermatome, dermatomal pattern
- modifier_Recurrent exacerbations / Episodic crises; intermittent, paroxysmal attacks, episodes, relapses, stuttering course, fluctuating, periodic paroxysms, spiking, spikes; quotidian, cyclical; undulating
- modifier_Sharp character to pain or discomfort / 
- modifier_Skin lesions grouped / Herpetiform (herpes) distribution, clusters included
- modifier_Sleep deprivation triggers attacks / 
- modifier_Sleep predominance to events / Nocturnal; diurnal
- modifier_Smoking or tobacco use exacerbates symptoms / Nicotine, nicotinic
- modifier_Sodium intake triggers attacks / 
- modifier_Sound triggered seizures / 
- modifier_Stress, excitement, or startle trigger symptoms / Epinephrine, albuterol, salbutamol or adrenergic stimuli; trauma; emotion; anxiety; acoustic stimulation; laughing; tickling, tickle
- modifier_Sudden movement triggers attacks / Kinesigenic; exercise
- modifier_Upper body predominance to findings / Arms, trunk, head more affected than legs
- modifier_Vestibular stimulation triggers attacks / Head turning, cold calorics, postural changes, rotating chair
- modifier_Worse in evening / Diurnal; time of day
- modifier_Worse with activity / Desire for inactivity; fatigue on feeding or exertion, non-energetic (without sleepiness), exercise intolerance, low energy; symptoms triggered by exercise, fatigability, asthenia, decreased stamina

**Comment by pnrobinson** [comment]
I have moved these suggestions to separate new requests according to category.
