### ISSUE TITLE
Abnormal malar bone morphology

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#7546]
**HPO term**
[Abnormality of malar bones HP:0012369](https://hpo.jax.org/app/browse/term/HP:0012369) is I think a synonym of 
[Abnormality of the zygomatic bone HP:0010668 ](https://hpo.jax.org/app/browse/term/HP:0010668)

Now malar bone is defined as
```
'has part' some 
    (morphology
     and ('characteristic of' some 'jugal bone')
     and ('has modifier' some abnormal))
```
and
zygomatic as
```
'has part' some 
    (morphology
     and ('characteristic of part of' some 'jugal bone')
     and ('has modifier' some abnormal))
```
(note -- slightly modifed from current version since the malar bone does not have an abnormal physiology, that is why this has come up).

@matentzn @cmungall  why are we using 'characteristic of part of' for one definition and 'characteristic of' for the other? Was there some intention to distinguish?
This is [jugal bone](https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0001683). Medically, they are synonymous.

**Reason for deprecation**

**Suggested replacement or term to consider**

**Comment by matentzn** [comment]
The difference between `characteristic of part of` and `characteristic of` is simply that the former implies that a morphological abnormality of a part of the jugal bone, for example a morphological abnormality of the `frontal process of zygomatic bone`, is also covered. In the case of `characteristic of` we do _not_ consider morphological abnormalities of (named) parts, like `frontal process of zygomatic bone`, only morphological abnormalities that are considered abnormalities of the "whole" jugal bone.

Morphology is really the quality that is the most contentious here - generally, we avoid `characteristic of part of` to be conservative about inferences.

Hope that helps!

**Comment by pnrobinson** [comment]
done
