### ISSUE TITLE
New mouth terms

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#755]
from simulconsult:

- Mouth: gum recession / Retraction; reduced gingival attachments
- Mouth: tongue lipomas 
- Mouth: tongue painful / Lingual
- Mouth: tonsils absent or hypoplastic 
- Mouth: tonsils large / Hypertrophy
- Mouth: tonsils with orange deposits

**Comment by pnrobinson** [comment]
I am adding a separate item for each of these term requests
