### ISSUE TITLE
Oculopharyngeal muscular dystrophy

### ISSUE THREAD

**Issue by svonschuch** [obophenotype/human-phenotype-ontology#7553]
**HPO term**

Oculopharyngeal muscular dystrophy

**Bug description**

Data Error - Spondylolisthesis is listed as a symptom. This has created a buzz within the patient communities (leading to pts educating their doctors about a new symptom). Quick PubMed search resulted in no findings. I believe this is an error. Thank- you so much for your attention on this. HPO is a terrific resource!

**Comment by pnrobinson** [comment]
I believe you are referring to the Orphanet entry (https://hpo.jax.org/app/browse/disease/ORPHA:270). We import the Orphanet data from https://www.orpha.net/consor/cgi-bin/index.php but cannot directly modify the files. 
This is the place to make requests to modify Orphanet content:
https://www.orpha.net/consor/cgi-bin/Directory_Contact.php?lng=EN
I agree with you that this is not a characteristic symptom of this disorder. 
I will also send an email about this to Orphanet, which is a wonderful resource with information about many topics in rare disease!

**Comment by svonschuch** [comment]
Hello,

Thank you kindly for your prompt reply! 

After I messaged you I did see HPO referenced Orphanet. I the. checked the orphanet website and their data table references HPO. there appears to be a reference loop. 

I truly appreciate you reaching out to orphanet to make the correction. 

Sincerely,

Sarah
