### ISSUE TITLE
New nails terms

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#756]
from simulconsult:

- Nails rough / Sandpaper-like; trachyonychia
- Nails, pointed / Beaked
- Nails: cuticle ragged / 
- Nails: fast growing / 
- Nails: lunulae absent / Lunula; crescent-shaped whitish area of the bed of a fingernail or toenail
- Nails: platonychia / Flat and broad
- Nails: upslanting / Ski-jump; upward angulation; toenails

**Comment by pnrobinson** [comment]
I am adding a separate issue for each of these requests
