### ISSUE TITLE
HP:0031643. Fusiform ascending tubular aorta aneurysm

### ISSUE THREAD

**Issue by grahamponting** [obophenotype/human-phenotype-ontology#7561]
The label name is not consistent with the definition "An eccentric abnormal localized widening (dilatation) of the ascending tubular aorta that involves only a portion of the circumference of the vessel wall."
The definition sounds more like a "saccular" aneurysm, which would be eccentric, but the label name is suggesting a fusiform aneurysm which is concentric.
Many thanks. Graham Ponting

**Comment by pnrobinson** [comment]
Thanks for pointing out this error!
I have corrected the definition to
A concentric abnormal localized widening (dilatation) of the ascending tubular aorta that involves the full circumference of the vessel wall.
