### ISSUE TITLE
Wrong capitalization of synonym for Supraventricular arrhythmia?

### ISSUE THREAD

**Issue by turnovec** [obophenotype/human-phenotype-ontology#7563]
**HPO term**
HP:0005115 | Supraventricular arrhythmia 

**Bug description**
The synonym is "arrhythmias, Supraventricular". Is the capitalization correct?

And agian, on hpo.jax.org it's not clear if there are two synonyms (arrhytmias and Supraventricular), or if there is only one, but with words separated by comma...

**Comment by pnrobinson** [comment]
In general, we do not use "reversed" forms like this. I wrote this as Supraventricular arrhythmias (has synonym type PLURAL).
Thanks for pointing out this error!
