### ISSUE TITLE
Possible erorr in definition of Severe combined immunodeficiency 

### ISSUE THREAD

**Issue by turnovec** [obophenotype/human-phenotype-ontology#7564]
**HPO term**
HP:0004430 | Severe combined immunodeficiency 

**Suggested revision of textual definition**
"A combined immunodeficiency primary immune deficiency that is characterized by a more severe defect in both the T- and B-lymphocyte systems."

Beginning of sentence don't make much sense to me. Maybe it should start just with "A primary immune deficiency that..."?

**Comment by pnrobinson** [comment]
Thanks for pointing out this error. I have altered the definition to

A type of primary immune deficiency that is characterized by a more severe defect in both the T- and B-lymphocyte systems.
