### ISSUE TITLE
Surplus letter in synonym for Increased spinal bone density

### ISSUE THREAD

**Issue by turnovec** [obophenotype/human-phenotype-ontology#7565]
**HPO term**
HP:0004563 | Increased spinal bone density 

**Bug description**
One of the synonyms is:
"increased spinal bone density Z"

Why is the "Z" there?

And without Z it's same as main term and  then it should be probably removed.

**Comment by pnrobinson** [comment]
Thanks!
Corrected to "Increased spinal bone density Z-score"
