### ISSUE TITLE
Shouldn't biopterin and tetrahydrobiopterin have different entries?

### ISSUE THREAD

**Issue by MickeySegal** [obophenotype/human-phenotype-ontology#7573]
**HPO term**
HP:0040209

**Bug description**
Tetrahydrobiopterin is listed as a synonym for biopterin, but they are different compounds, though similar.

**Comment by MickeySegal** [comment]
UMLS CUI 2751159 seems correct for Decreased tetrahydrobiopterin (BH4) in CSF

**Comment by pnrobinson** [comment]
This is [Decreased CSF biopterin level HP:0040209](https://hpo.jax.org/app/browse/term/HP:0040209)
I agree these are not the same compound of course.
I am not sure if tetrahydrobiopterin is measured clinically? I will check

**Comment by pnrobinson** [comment]
I agree tetrahydrobiopterin is a mistake and have removed it. As far as I know, tetrahydrobiopterin is not measured clinically, and so I will not create a new term unless we find an assay in pubmed or loinc etc.

**Comment by MickeySegal** [comment]
https://www.ncbi.nlm.nih.gov/books/NBK481554/ and https://www.ncbi.nlm.nih.gov/books/NBK493766/ mention measuring tetrahydrobiopterin in CSF.
