### ISSUE TITLE
Merge HP:0030210 and HP:5000045?

### ISSUE THREAD

**Issue by MickeySegal** [obophenotype/human-phenotype-ontology#7574]
**HPO term**
HP:0030210 and HP:5000045 seem to describe the same concept

**Bug description**
HP:0030210 is labeled as a Finding in UMLS and HP:5000045 is labeled as Laboratory Test Result, which prevents it getting into MedGen, so consolidating to HP:0030210 might be better.

**Comment by pnrobinson** [comment]
[Muscle specific kinase antibody positivity HP:0030210](https://hpo.jax.org/app/browse/term/HP:0030210)
and
[Anti-MuSK antibody positivity HP:5000045](https://hpo.jax.org/app/browse/term/HP:5000045)
do refer to the same class of antibodies (that can be observed in people with myasthenia gravis).

Thanks for picking up this error @MickeySegal  I will fix it such that HP:0030210 survives as the primary term id.
