### ISSUE TITLE
HP:0030908 and HP:0034113 seem to describe the same finding / result

### ISSUE THREAD

**Issue by MickeySegal** [obophenotype/human-phenotype-ontology#7579]
**HPO term**
HP:0030908 and HP:0034113

**Bug description**
These seem to describe the same finding / result.  Keeping HP:0030908 may make most sense because UMLS characterized it as a finding, but characterized HP:0034113 as a Lab Result, and therefore it doesn't get into MedGen.  For the long run, I am discussing with MedGen whether they should import not only HPO-derived findings but also HPO-derived test results, but that change won't happen instantly.

**Comment by kanems** [comment]
Just a quick ping on this merge request to see if it can get incorporated for the Sept release? MedGen should incorporate the update automatically but I've been monitoring this request to make sure. Thanks @pnrobinson and @nicolevasilevsky

**Comment by nicolevasilevsky** [comment]
@pnrobinson I can work on this. When is the next HPO release planned?
