### ISSUE TITLE
sleep terror

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#758]
Night terror, Pavor nocturnus

Episodes of intense fear, screaming and flailing although affected individuals are still asleep. Often individuals are also sleepwalking.

**Comment by pnrobinson** [comment]
This is definitely a phenotype that I have occasionally -- I am claiming this term!

**Comment by drseb** [comment]
also add: Sleep terrors

**Comment by pnrobinson** [comment]
Added term as HP_0030765
