### ISSUE TITLE
HP:0033404 Intestinal ischemia, mistake in definition

### ISSUE THREAD

**Issue by grahamponting** [obophenotype/human-phenotype-ontology#7580]
**HPO term**

**Suggested revision of textual definition**

**Comment by grahamponting** [comment]
The definition refers to a testis in the first sentence which must be a mistake

**Comment by pnrobinson** [comment]
Thanks for pointing this out!
I changed the definition to 

Restriction of arterial blood supply to the intestine associated with insufficient oxygenation to support the metabolic requirements of the tissue. Acute intestinal ischemia can involve the small or large intestine, and usually presents with sudden severe non-specific abdominal pain.
