### ISSUE TITLE
HP:0041053 Fractured head

### ISSUE THREAD

**Issue by grahamponting** [obophenotype/human-phenotype-ontology#7581]
There is no detail on this term which rather sits on it's own and has no children.
Does it refer to a fracture of the skull, although there is a separate term HP:0041082, or of any bone in the head ?
Could the definition be updated please ?
Many thanks
Graham Ponting

**Comment by pnrobinson** [comment]
This is an error that occured when we were generating fracture terms using an anatomy ontology (UBERON). 
I will merge this with Fractured skull HP:0041082
Thanks for pointing this out.
