### ISSUE TITLE
NTR: Sleep hypoxia

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#7604]
**Preferred term label:**
Sleep hypoxia

**Parent**:
Hypoxemia HP:0012418

**Synonyms**
Sleep-related hypoxemia

**Def**
A low level of oxygen in the blood during sleep.
https://www.sleepfoundation.org/sleep-related-breathing-disorders#:~:text=Sleep%2DRelated%20Hypoxemia%20Disorder,a%20sleep%2Drelated%20hypoventilation%20disorder.

This is needed for the INCLUDE Data Coordinating Center data annotations.
cc @lopierra

**Comment by pnrobinson** [comment]
Adding as HP:0034312 with primary label Nocturnal hypoxemia and the above synonyms.
def: Abnormally reduced oxyhemoglobin saturation during sleep (nocturnal). Different thresholds are used in the literature, including more than 10 percent of total sleep time below a SpO2 of 90 percent.
