### ISSUE TITLE
Typo in definition of Cardiac myxoma

### ISSUE THREAD

**Issue by turnovec** [obophenotype/human-phenotype-ontology#7605]
**HPO term**
HP:0011672 | Cardiac myxoma

**Bug description**
Definition: "A myxoma (tumor of primitive connective tissue) of the heart. Cardiac myxomas consist of stellate to plump, cytologically bland mesenchymal cells set in a myxoid stroma. Cardiac myxomas are of endocardial origina and general project from the endocardium into a cardiac chamber."

endocardial origina -> endocardial origin

**Comment by pnrobinson** [comment]
fixed, thanks!
