### ISSUE TITLE
Typo in definition of Shagreen patch

### ISSUE THREAD

**Issue by turnovec** [obophenotype/human-phenotype-ontology#7606]
**HPO term**
HP:0009721 | Shagreen patch

**Bug description**
Definition: "A plaque representing a connective-tissue nevus. Connective tissue naevi are uncommon skin lesions that occur when the deeper layers of the skin do not develop correctly or the components of these layers occur in the wrong proportion. Shagreen patches are oval-shaped and nevoid, skin-colored or occasionally pigmented, smooth or crinkled, The word shagreen refers to a type of roughened untanned leather."

There is a comma instead of period before the last sentence. Or there could be comma, but then the "T" should by small case and in English these long sentences are not so common...

**Comment by pnrobinson** [comment]
fixed, thank you!
