### ISSUE TITLE
Typo in definition for Increased alpha-globulin

### ISSUE THREAD

**Issue by turnovec** [obophenotype/human-phenotype-ontology#7607]
**HPO term**
HP:0005413 Increased alpha-globulin 

**Bug description**
Definition: "An abnormally increased level of circulationg alpha-globulin. Alpha globulins are a group of serum proteins defined by their mobility on serum electrophoresis. The alpha1-protein fraction is comprised of alpha1-antitrypsin, thyroid-binding globulin, and transcortin. Ceruloplasmin, alpha2-macroglobulin, and haptoglobin contribute to the alpha2-protein band. The alpha2 component is increased as an acute-phase reactant."

circulationg -> circulating

**Comment by pnrobinson** [comment]
Fixed, thank you!
