### ISSUE TITLE
Should HP:0012677 and HP:0002454 be merged?

### ISSUE THREAD

**Issue by MickeySegal** [obophenotype/human-phenotype-ontology#7608]
**HPO term**
HP:0012677 and HP:0002454 

**Reason for deprecation**
These seem to refer to the same abnormality.  

- Iron accumulation in globus pallidus
- Eye of the tiger anomaly of globus pallidus

**Suggested replacement or term to consider**
Suggest merge of these terms

**Comment by pnrobinson** [comment]
I think you are correct. The phrase "Iron accumulation in globus pallidus" was used to describe an MRI finding in the article we are annotating with the term, and so I think the authors mean the same thing. I will merge the term and keep "Eye of the tiger anomaly of globus pallidus" as the primary label

**Comment by pnrobinson** [comment]
done
