### ISSUE TITLE
Inconsistent approach to bilateral bilobed lung and bilateral trilobed lung

### ISSUE THREAD

**Issue by MickeySegal** [obophenotype/human-phenotype-ontology#7610]
**HPO term**
HP:0033183 and HP:0011861

**Synonym to be added**
HP:0033183 is called "Bilobed right lung" and HP:0011861 is called "Bilateral trilobed lungs".  Ideally the same approach to naming should be used for both, but at the minimum the other type of terminology should be included as a synonym for each.

**broad/exact/narrow/plural/abbreviation ?**

**Comment by pnrobinson** [comment]
Renamed to Bilateral trilobed lung and added the Bilateral trilobed lungs form as a synonym (Plural form)
thanks
