### ISSUE TITLE
HP:0007183 and HP:0031206 currently are not hierarchically related

### ISSUE THREAD

**Issue by MickeySegal** [obophenotype/human-phenotype-ontology#7612]
**HPO term**
HP:0007183 and HP:0031206

**Suggested revision and reasons**
HP:0007183 seems like a child of HP:0007183 but not so linked

**Comment by pnrobinson** [comment]
[Focal T2 hyperintense basal ganglia lesion HP:0007183](https://hpo.jax.org/app/browse/term/HP:0007183)
[Striatal T2 hyperintensity HP:0031206](https://hpo.jax.org/app/browse/term/HP:0031206)

The striatum is a component of the basal ganglia, and so a patient with Striatal T2 hyperintensity can be said to have a Focal T2 hyperintense basal ganglia lesion -- thus vice versa or am I overseeing something? @MickeySegal

**Comment by MickeySegal** [comment]
Agree; my point is that these have neither a parent/child nor a sibling relationship, and they should.

**Comment by pnrobinson** [comment]
added.
