### ISSUE TITLE
Add POTS as synonym

### ISSUE THREAD

**Issue by jmcmurry** [obophenotype/human-phenotype-ontology#7613]
**HPO term**
https://hpo.jax.org/app/browse/term/HP:0001278

**Synonym to be added**
Postural Orthostatic Tachycardia Syndrome
POTS

**broad/exact/narrow/plural/abbreviation ?**
Exact

**Comment by nicolevasilevsky** [comment]
@jmcmurry these synonyms sound like diseases, not phenotypes. We have this term in Mondo:
MONDO:0011479 'postural orthostatic tachycardia syndrome'

I'll add the synonym POTS to the Mondo term. I'll let @pnrobinson decide if he'd like to add these synonyms to the HPO term.

**Comment by pnrobinson** [comment]
I think this is a MONDO term and not an HPO term, agree with @nicolevasilevsky
