### ISSUE TITLE
organization of skeletal morphology branch

### ISSUE THREAD

**Issue by sbello** [obophenotype/human-phenotype-ontology#7615]
Looking at the Abnormal skeletal morphology (HP:0011842) branch I notice several child terms where there are both abnormality of X and abnormal morphology of X are present. See image for example. 

![HPO_skeletal_morph](https://user-images.githubusercontent.com/10979793/182416813-c74836ab-a0c6-4232-916c-d89e8e8c584a.png)

Looking at the definitions and eqs for the abnormality of X terms it appears that these are intended to cover both morphology and physiology. But given the location of the terms on the morphology branch they should be restricted to morphology. 

I would like to request a review of this branch and reorganization to remove terms that are intended to cover more than morphology out to a more general abnormality term or obsoletion of terms that are essentially duplicates.

**Comment by pnrobinson** [comment]
Thanks for pointing this out -- actually all of these terms are morphology and the labels are historical artefacts that we are revising. I will go over this now and fix as suggested
