### ISSUE TITLE
HP:0003607 and HP:0003607 seem the same

### ISSUE THREAD

**Issue by MickeySegal** [obophenotype/human-phenotype-ontology#7620]
**HPO term**
HP:0003607 and HP:0003607

**Reason for deprecation**
They seem the same

**Suggested replacement or term to consider**
Make one a synonym of the other

**Comment by pnrobinson** [comment]
I think you mean this pair of terms
[4-hydroxyphenylacetic aciduria HP:0003607](https://hpo.jax.org/app/browse/term/HP:0003607)
and
[Elevated urine 4-hydroxyphenylacetic acid level HP:0033304](https://hpo.jax.org/app/browse/term/HP:0033304)
-- agree they are synonyms, I will merge

**Comment by pnrobinson** [comment]
Retained HP:0003607 as the correct term and obsoleted/merged HP:0033304.
Thanks!
