### ISSUE TITLE
HP:0033465 has tetradecanolycarnitine instead of tetradecanoylcarnitine 

### ISSUE THREAD

**Issue by MickeySegal** [obophenotype/human-phenotype-ontology#7622]
**HPO term**
HP:0033465

**Bug description**
Letters Y and L are swapped erroneously.

Also worth adding that this is the C14 acylcarnitine.

**Comment by pnrobinson** [comment]
Fixed. Also added synonym
Elevated circulating C14 carnitine concentration (according to https://hmdb.ca/metabolites/HMDB0005066).

**Comment by MickeySegal** [comment]
How soon do such changes get onto the public version?

**Comment by pnrobinson** [comment]
The next release will be beginning of September. 
In the mean time it is possible to generate a local version with all of the interim changes -- if this would be useful let me know

**Comment by MickeySegal** [comment]
It sounds like the interim version would keep changing, so that may be a lot of trouble.  If you can indicate which term survives that would be the information that would most often be needed.
