### ISSUE TITLE
NTR: OMOP to HPO, missing mappings

### ISSUE THREAD

**Issue by hannahblau** [obophenotype/human-phenotype-ontology#7623]
Working with @pnrobinson on mapping from OMOP condition concept ids to the corresponding HPO terms, the following OMOP condition codes did not have a good match in the HPO hierarchy.

These are categories of abdominal pain:
- 195083 Left lower quadrant pain
- 193322 Right lower quadrant pain
- 194175 Left upper quadrant pain
- 198263 Right upper quadrant pain
- 4182562 Lower abdominal pain
- 4306292 Upper abdominal pain

and these are other types of pain:
- 312998 Pain in thoracic spine 
- 4150125 Persistent pain following procedure

**Comment by hannahblau** [comment]
More OMOP conditions that motivate new term / new synonym requests:

- 4346975 **Lumbar spondylosis** (new term)
- **Lumbago** new synonym for HP:0003419 Low back pain

**Comment by pnrobinson** [comment]
adding term and synonym, thanks!
