### ISSUE TITLE
HP:0034152 seems the same as HP:0033029

### ISSUE THREAD

**Issue by MickeySegal** [obophenotype/human-phenotype-ontology#7624]
**HPO term**
HP:0034152 and HP:0033029

**Reason for deprecation**
HP:0034152 seems the same as HP:0033029, and UMLS only includes HP:0033029

**Suggested replacement or term to consider**
Merge into HP:0033029

**Comment by pnrobinson** [comment]
[Anti-histidyl tRNA synthetase antibody positivity HP:0034152](https://hpo.jax.org/app/browse/term/HP:0034152)
and
[Anti-Jo-1 antibody positivity HP:0033029](https://hpo.jax.org/app/browse/term/HP:0033029)
-- thanks for pointing this out, they are synonym according to https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3380442/
@MaudDLVT do you agree these are synonyms? I will plan to merge HP:0033029 into HP:0034152 unless there is a distinction you are aware of.

**Comment by pnrobinson** [comment]
@MaudDLVT I will merge these two terms, I think they are syonyms. If there are future distinctions we need to make we can create new terms.

**Comment by pnrobinson** [comment]
@MickeySegal   HP:0034152 is the  "surviving" term id.

**Comment by MickeySegal** [comment]
Hopefully UMLS will update https://www.ncbi.nlm.nih.gov/medgen/C5398010, which references the subsumed term HP:0033029.
