### ISSUE TITLE
Add new subontology for past medical history

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#763]
This will cover medically relevant terms such as:
- Major illnesses, beginning in childhood
- Hospitalizations
- Surgeries
- Significant injuries
- Medications
- e.g. thalidomide exposure
- e.g. smoking
- ...

Related tickets:
https://github.com/obophenotype/human-phenotype-ontology/issues/670
https://github.com/obophenotype/human-phenotype-ontology/issues/300
https://github.com/obophenotype/human-phenotype-ontology/issues/264

**Comment by pnrobinson** [comment]
This is a relatively big item, and we need to think carefully about how to get there. Currently I believe that the section "exposures" is most straightforward (medications, infections, toxins, etc). The section hospitalizations and surgeries will be extremely difficult but probably quite useful for PMI, and we need to think carefully about how to do it, within or outside the HPO. I think we can start a subontology for medically relevant exposures though.

**Comment by drseb** [comment]
I would suggest an iterative approach. We have to start now, I think!

**Comment by pnrobinson** [comment]
Closing this issue as discussed
