### ISSUE TITLE
Bruxism is not always in sleep

### ISSUE THREAD

**Issue by DLewisSmith** [obophenotype/human-phenotype-ontology#7642]
**HPO term**
Bruxism (HP:0003763)

**Suggested revision and reasons**
Bruxism is a phenotype that can be a form of may different behavioural or movement phenotypes and can occur awake or asleep (PMID: 29926505). The awake form may be more common than the asleep form. I'd suggest moving to child of Behavioural abnormality (HP:0000708), it's current grandparent as I am not sure that **all** cases can be considered stereotypies, dystonia, etc..

**Comment by pnrobinson** [comment]
Thanks for this suggestion, I agree and have implemented
