### ISSUE TITLE
Synonym/Comment for HP:0031838

### ISSUE THREAD

**Issue by turnovec** [obophenotype/human-phenotype-ontology#7645]
**HPO term**
HP:0031838|Presence of xenobiotic

**Bug description**
This term has a definition: "Presence of a chemical substance found within an individual that is not naturally produced or expected to be present in human tissues or bodily fluids."

On hpo.jax.org, there is also a comment: "The presence of a xenobiotic in body tissues or fluids can be the result of ingestion of or exposure to substances such as drugs, environmental pollutants, food additives, hydrocarbons, and pesticides."

But as we are currently translating HPO to Czech on Crowdin platform, I've just found this as a "synonym" for translation:
"#The presence of a xenobiotic in body tissues or fluids can be the result of ingestion of or exposure to substances such as drugs, environmental pollutants, food additives, hydrocarbons, and pesticides"

Is it some bug in import from HPO to Crowdin? What should we do with this item during the translation? Should we omit it? Are there also comments for other terms in HPO? Should they be also translated?

**Comment by pnrobinson** [comment]
This is probably an error in the Crowdin data -- the term has a definition and a comment but no synonym.
Please check the HPO web page for the "canonical" form.
By the way could you send me (peter robinson) an email? We are putting together the nar issue for 2023 submission and want to include people who are making large contributions as coauthors.

**Comment by turnovec** [comment]
I checked it and on hpo.jax.org it's correct. But somehow the comment was imported in CrowdIn as synonym...

**Comment by pnrobinson** [comment]
thanks
