### ISSUE TITLE
single quotes 

### ISSUE THREAD

**Issue by sbello** [obophenotype/human-phenotype-ontology#7651]
The MGI software team has been running some checks on loads and identified a number of terms with questionable single quotes in ontologies we load. Possibly these are desired but at least n the MP I found several where the quotes were not needed. Would you please take a look and see if any single quotes should be removed from these terms:

 'cigarette paper scarring'

 'Sea blue' histiocytes

 'de toni-fanconi-debre' syndrome

 'Waddling' gait

 'steppage' gait

 'molar tooth sign' on brain imaging'

 'molar tooth' sign on imaging

 'Onion bulb' formations

 'rimmed vacuoles' on biopsy

 'rimmed' vacuoles on biopsy

 'curvilinear profiles' ultrastructurally

 'Curvilinear profiles' ultrastructurally in cells

 'Fingerprint profiles' ultrastructurally in cells

 'Generalised' tonic-clonic seizure with focal onset

 'Generalised' tonic-clonic seizure with partial onset

 'Generalized' tonic-clonic seizure with focal onset

 'Generalized' tonic-clonic seizure with partial onset

**Comment by pnrobinson** [comment]
Thanks for pointing this out @sbello ! Although there may be some motivation for the quotes in some cases, it may be best to remove them altogether from the labels. We'll take a closer look.

**Comment by pnrobinson** [comment]
Removed quotations marks as suggested - thanks!
