### ISSUE TITLE
Cerebral palsy - draft structure

### ISSUE THREAD

**Issue by peupeubangbang** [obophenotype/human-phenotype-ontology#7654]
**HPO term**
Cerebral Palsy HP:0100021

**Suggested revision and reasons**
Notes for suggested HPO CP structure...
- Add obligate frequency annotations for same CP HPO vs MONDO terms to account for phenotype/disease overlap?
- Introduce MONDO xrefs? (again for phenotype-disease overlap)
- [Multiple parents for existing terms are a good way of introducing into the HPO CP branch](https://github.com/obophenotype/human-phenotype-ontology/issues/7315)
- Using HPO clinical modifier terms are a good way to avoid having introduce upper limb/lower limb HPO CP codes which is what SNOMED uses for its disorder terms (a bit overcoded imo)
- Avoid progressive terms
- Severity is currently difficult to code for HPO CP terms as relies on [GMFCS I-V](https://cerebralpalsy.org.au/our-research/about-cerebral-palsy/what-is-cerebral-palsy/severity-of-cerebral-palsy/gross-motor-function-classification-system/) for motor function (plus [MACS](https://cerebralpalsy.org.au/our-research/about-cerebral-palsy/what-is-cerebral-palsy/severity-of-cerebral-palsy/manual-ability-classification-system/) for ability + [CFCS](https://cerebralpalsy.org.au/our-research/about-cerebral-palsy/what-is-cerebral-palsy/severity-of-cerebral-palsy/communication-function-classification-system-cfcs/) for communication)
- Onset prenatal vs neonatal vs post neonatal is important to differentiate between known cause of CP and probably useful for any links  to gene/variant
- Can use HPO clinical modifier terms in laterality & spatial pattern (lower vs upper body predominance) branches for identifying limbs affected

**Suggested structure**
- [Cerebral Palsy](https://hpo.jax.org/app/browse/term/HP:0100021) **all terms immediately below to have link to this as parent (bullet point indents represent branch level)**
	- Spastic CP **new term** (additional parent: [Spasticity HP:0001257](https://hpo.jax.org/app/browse/term/HP:0001257), [new term suggested so we can separate spasticity that isn't CP](https://github.com/obophenotype/human-phenotype-ontology/issues/7519))
		- Spastic CP bilateral **new term** OR _rely on clinical modifier terms to avoid laterality in HPO terms_
			- [Spastic tetraplegia (quadriplegia)](https://hpo.jax.org/app/browse/term/HP:0002510)
			- [Spastic triplegia](https://hpo.jax.org/app/browse/term/HP:0034183)
			- [Spastic diplegia](https://hpo.jax.org/app/browse/term/HP:0001264)
				- additional parent: [Cerebral palsy HP:0100021](https://hpo.jax.org/app/browse/term/HP:0100021) ([requested today](https://github.com/obophenotype/human-phenotype-ontology/issues/7652))
		- Spastic CP unilateral **new term** OR _rely on clinical modifier terms to avoid laterality in HPO terms_
			- [Spastic monoplegia](https://github.com/obophenotype/human-phenotype-ontology/issues/7653) **new term** _suggested today_
			- [Spastic hemiparesis (hemiplegia)](https://hpo.jax.org/app/browse/term/HP:0011099)
	- Dyskinetic CP **new term**
		- [Athetoid CP](https://hpo.jax.org/app/browse/term/HP:0011445) **reclassify and suggest rename term to _Choreoathetoid CP_ for aggregate form of athetosis + chorea**
			- remove Dyskinetic CP as synonym to become new parent term in own right (as above)
			- suggest renaming to _Choreoathetoid CP_
			- additional parent: [Choreoathetosis HP:0001266](https://hpo.jax.org/app/browse/term/HP:0001266) which needs [Athetosis HP:0002305](https://hpo.jax.org/app/browse/term/HP:0002305)  added as an additional parent (requested #7656)
		- Dystonic CP **new term**
			- additional parent: [Dystonia HP:0001332](https://hpo.jax.org/app/browse/term/HP:0001332)
		- Chorea CP is not a suggested classification (despite making up Dyskinetic CP: [athetosis](https://hpo.jax.org/app/browse/term/HP:0002305)/[dystonia](https://hpo.jax.org/app/browse/term/HP:0001332)/[chorea](https://hpo.jax.org/app/browse/term/HP:0002072))
	- Ataxic CP **new term**
		- additional parent: [Ataxia HP:0001251](https://hpo.jax.org/app/browse/term/HP:0001251)
	- Hypotonic CP **new term - CONTROVERSIAL!!!**
		- additional parents: [Generalized hypotonia HP:0001290](https://hpo.jax.org/app/browse/term/HP:0001290) + [Spasticity HP:0001257](https://hpo.jax.org/app/browse/term/HP:0001257)
		- Isn't considered a CP type for some countries
		- Definition for CP is "generalised hypotonia with increased reflexes"
		- Lot of syndrome overlap
	- For **mixed CP** could code above HPOs in conjunction with...
		-  [Mixed CP MONDO disease term](https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0000400&lang=en&viewMode=PreferredRoots&siblings=false)
			- [Mixed CP is not a good term for HPO](https://github.com/obophenotype/human-phenotype-ontology/issues/7300)
			- Often dystonia + spasticity, ataxia + spasticity

**Comment by nicolevasilevsky** [comment]
@peupeubangbang thanks for this! Do you think we should model the Mondo hierarchy in the same way? We can also add xrefs in Mondo to HPO.

cc @sabrinatoro @jagcsun

**Comment by peupeubangbang** [comment]
@nicolevasilevsky hi sorry it took me so long! Maybe hold off only because I am going to get some more feedback at the Australian CP Register (ACPR) classification meeting in two weeks and will also look at HPO-MONDO xrefs. I will update the above with any suggested changes 😄

**Comment by peupeubangbang** [comment]
closing as HPO structure has improved. Request pending for NTR spastic monoplegia #7653
