### ISSUE TITLE
Obsolete value in "consider" tag (HP:0045013/HP:0011016)

### ISSUE THREAD

**Issue by hendrikweisser** [obophenotype/human-phenotype-ontology#7655]
**HPO term**
HP:0045013 ("obsolete Decreased urinary glucose concentration") and HP:0011016 ("obsolete Abnormality of urine glucose concentration")

**Bug description**
In hp.obo (version "hp/releases/2022-06-11"), the term HP:0045013 ("obsolete Decreased urinary glucose concentration") contains `consider: HP:0011016`, which is itself an obsolete term ("obsolete Abnormality of urine glucose concentration"). I assume this shouldn't happen because the parser I'm using raises an error (`Error: Attempted to specify obsolete value ... for consider tag.`).

HP:0011016 in turn contains `replaced_by: HP:003076` ("Glycosuria"). However, that is defined as "An *increased* concentration of glucose in the urine.", so probably wouldn't be appropriate as an alternative for HP:0045013 (decreased concentration).

**Comment by drseb** [comment]
@matentzn can we discuss this in our next call?

**Comment by matentzn** [comment]
I added a QC check that ensures that `consider` and `replaced_by` IDs themselves _not_ obsolete: https://github.com/obophenotype/human-phenotype-ontology/pull/7657

Here is an example output [in the CI](https://github.com/obophenotype/human-phenotype-ontology/runs/8111070908?check_suite_focus=true):

![image](https://user-images.githubusercontent.com/7070631/187655031-e2915a73-adac-420c-91b7-31f7a690bb66.png)


Thank you @hendrikweisser for the report!

**Comment by matentzn** [comment]
@nicolevasilevsky feel free to jump in top https://github.com/obophenotype/human-phenotype-ontology/pull/7657 and fix the three issues so that QC passes again.

**Comment by pnrobinson** [comment]
@hendrikweisser medically, you cannot have "Decreased urinary glucose concentration" -- normally one should not have glucose in the urine. This class was simply a mistake, and we had to re-organize the hierarchy here. @matentzn I think we can just remove the term-replaced-by assertion?

**Comment by matentzn** [comment]
There are three cases (see above), not one, but of course, feel free to just delete them - this is your call to make :)
