### ISSUE TITLE
Dysplastic pulmonary valve - add synonym + xref

### ISSUE THREAD

**Issue by peupeubangbang** [obophenotype/human-phenotype-ontology#7658]
**HPO term**
Dysplastic pulmonary valve HP:0005164

**Synonym to be added**
Pulmonary valve dysplasia, dysplasia of pulmonary valve

**broad/exact/narrow/plural/abbreviation ?**
Exact

**xrefs**
SNOMEDCT_US:253588008

**Comment by pnrobinson** [comment]
adding synoynms.
SNOMED CT mapping is a separate file.

**Comment by peupeubangbang** [comment]
@pnrobinson sorry just to confirm and for future ref... HPO-SNOMED CT mapping/xrefs being done outside of github? So don't suggest SNOMED CT xrefs for now?

**Comment by pnrobinson** [comment]
@peupeubangbang  -- if you have suggested mappings that would be useful --- we are putting them in a separate file. Please let me know!
