### ISSUE TITLE
Palatal Tremor

### ISSUE THREAD

**Issue by carolina-f** [obophenotype/human-phenotype-ontology#7659]
**HPO term** Palatal myoclonus HP:0010530

**Synonym to be added**  Palatal tremor

**broad/exact/narrow/plural/abbreviation ?**

Articles finding: PMID: 34245630, PMID: 35246666

**Comment by pnrobinson** [comment]
Thanks for pointing this out:
Previously, palatal tremor was known as palatal myoclonus but it was subsequently renamed ‘palatal tremor’ during the First International Congress of Movement Disorders to acknowledge the continuous and rhythmic nature of the palatal movement 
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7546106/

I will make Palatal tremor be the primary label and have Palatal myoclonus be a synonym.

**Comment by carolina-f** [comment]
Thank you very much for the explanation
