### ISSUE TITLE
Characterize relationship of bracket and delta epiphysis and improve definitions

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#7661]
**HPO term**
Longitudinal epiphyseal bracket
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3886355/

**Synonym to be added**

**broad/exact/narrow/plural/abbreviation ?**

**Comment by pnrobinson** [comment]
@azankl -- could you help with this issue please? 😄

**Comment by azankl** [comment]
I would say `Longitudinal epiphyseal bracket` is an exact synonym for `Triangular epiphyses HP:0010587`. Here is a picture of triangular epiphyses from [Mundlos and Horn 2014](https://books.google.com.au/books/about/Limb_Malformations.html?id=4r_wQwAACAAJ&redir_esc=y):
![Mundlos and Horn 2014 - Limb Malformations](https://github.com/obophenotype/human-phenotype-ontology/assets/4812335/273b84db-c38f-442f-ba23-8ddb3b527ec4)

I think that looks identical to Fig.3 of [PMC3886355](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3886355/):
![11832_2013_544_Fig3_HTML](https://github.com/obophenotype/human-phenotype-ontology/assets/4812335/dc6b1080-52f1-4515-8ab9-6d7d5aae586f)

If the affected bone is a bit longer, the epiphysis looks less triangular and more like a bracket (as in Fig.2 of PMC3886355), but I would say it's the same thing.

`Triangular shaped phalanges of the hand HP:0009774` (aka `delta phalanx`) is what you get once the bracket/triangular epiphyses have closed (Stage IV in the figure above). So maybe that is a 'related' term?

**Comment by pnrobinson** [comment]
thanks, added!
