### ISSUE TITLE
Pulmonic stenosis - revise definition and comment

### ISSUE THREAD

**Issue by peupeubangbang** [obophenotype/human-phenotype-ontology#7664]
**HPO term**
Pulmonic stenosis HP:0001642

**Suggested revision of definition**
_New definition accounts for new child term in #7663_
A narrowing of the right ventricular outflow tract that can occur at the pulmonary valve (valvular stenosis), below the pulmonary valve (infundibular stenosis), or above the pulmonary valve (supravalvar stenosis).

**Suggested revision of comment**
_I have removed mention of the  new child term requested in #7663 from this comment to avoid confusion_
Pulmonic stenosis is often seen as a part of Fallot' s tetralogy, in which case the events leading to the formation of the overriding aorta are also believed to be a cause of the pulmonic stenosis. The pulmonic stenosis is the major cause of the malformations seen in patients with Fallot tetralogy, with the other associated malformations acting as compensatory mechanisms to the pulmonic stenosis. The degree of stenosis varies between individuals with TOF, and is the primary determinant of symptoms and severity.

**Comment by pnrobinson** [comment]
@peupeubangbang  -- 
I am wondering it it would be better to have the hierarchy reflect the three potential types of pulmonary stenosis
Pulmonary stenosis
--Valvular pulmonary stenosis 
--Subvalvular pulmonary stenosis.
--Supravalvular pulmonary stenosis

https://www.ncbi.nlm.nih.gov/books/NBK560750/

**Comment by pnrobinson** [comment]
modified definition and adding subterms as suggested, thanks!
