### ISSUE TITLE
Update to the textual definition of semidominant mode of inheritance

### ISSUE THREAD

**Issue by courtneythaxton** [obophenotype/human-phenotype-ontology#7665]
**HPO term**
Semidominant (HP:0032113)

**Suggested revision of textual definition**
A mode of inheritance that is observed for traits related to a gene encoded on chromosomes in which a trait can manifest in a monoallelic (e.g. heterozygotes) and biallelic (e.g. homozygotes, compound heterozygotes) state, with similar or differing phenotype severity present dependent on the number of alleles affected

The change is to include the word similar, when referring to the severity of phenotype. The current definitions implies that there should be differing severities in a dosage dependent state, which is typical but not always true, as there may be a range dependent on the type of variant and perturbation.

**Comment by pnrobinson** [comment]
Hi @courtneythaxton,
we have recently been discussing the inheritance terms with @angharadroberts and team. There was a suggestion to obsolete this term because of the difficulties in precisely defining it. Is this a term that ClinGen would need? If you would like to join the discussion about inheritance terms you would be welcome. I will hold off on any changes to this term until we have had the time to touch bases.

**Comment by courtneythaxton** [comment]
@pnrobinson ClinGen definitely needs the semidominant mode of inheritance for our work. 

We currently have 32 gene validity curations that use this MOI, and our interface(s) and website use the HPO ID for this MOI to display the name, which would lead to an "obsolete" showing up on these curations.

We will also have variant curation panels that may publish using this MOI as well, once we get ClinVar to accept it for publishing (they only had AD, AR, and XL). This is important for disease, like LDLR- related  like Familial Hypercholesterolemia, because it allows our variant curation expert panels to include cases with both monoallelic and biallelic presentation to be included on the same variant interpretation. Our feeling is that if the variant is pathogenic for a dominant disease, it is alos pathogenic for the recessive in the cases of semi-dominance, and we would rather not have two separate variant classifications based on MOI. As you know, this could result in disparities between final classifications if there is not enough data independently to get to pathogenic.

For ClinGen, we feel we have made the definition of this MOI clear, and is published in our SOPs, but are happy to work with you all as needed. I agree it has gotten conflated in the literature over the years with codominance, among other things.

**Comment by pnrobinson** [comment]
@courtneythaxton I am altering the definition as suggested above (thanks!). We discussed this also with genCC who are in agreement.
