### ISSUE TITLE
Add cerumen abnormalities

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#769]
Add under Abn. of outer ear

- Cerumen excessive
- Cerumen pigmented abnormal
- corresponding superclasses around these terms

**Comment by cmungall** [comment]
Note:

in uberon we treat the cerumen as being located-in the external ear 
(canal). To recapitulate the inference we'd need to either generalize 
the generic abnormality to include the (weaker) located-in relationship 
type. Or we can treat cerumen as being (stronger) part-of the external 
ear.

**Comment by drseb** [comment]
thanks. let's discuss on skype-call later today!?

**Comment by cmungall** [comment]
I'm traveling today but am on skype for the next 1hr

**Comment by pnrobinson** [comment]
I have added the requested terms and placed them under Abnormality of the auditory canal for now.
