### ISSUE TITLE
 Hereditary leiomyomatosis and renal cell cancer

### ISSUE THREAD

**Issue by svonschuch** [obophenotype/human-phenotype-ontology#7695]
Hello, 

I see "Abnormality of the musculature [HP:0003011]" listed as a very frequent symptom of HLRCC. 

There appears to be a reference loop (HPO cites Orphanet cites HPO). 

Would it be possible to get more information on what is meant by this term? I might guess it is referring to the leiomyomas (benign tumors of smooth muscle in the skin and uterus), however it is a really confusing use of this term. 

Could you clarify? 

Thank-you, 

Sarah

**Comment by svonschuch** [comment]
I am trying to find references for the listing of "Barrett's Esophagus" as well for HLRCC. I found the following from a 2002 article (Toro JR et al., Mutations in the fumarate hydratase gene cause hereditary leiomyomatosis and renal cell cancer in families in North America. Am J Hum Genet. 2003 Jul;73(1):95-106. PMCID: PMC1180594. --"In our clinical evaluation, we considered but did not find the phenotypic expression of two other conditions: FHD, which is an autosomal recessive disease due to mutations in FH, and esophageal leiomyomas. Patients denied neurological symptoms, and a general neurological examination did not reveal gross neurological abnormalities (e.g., microcephaly, hypotonia, and psychomotor retardation). Leiomyomatosis of the esophagus has been reported in other inherited syndromes, including multiple endocrine neoplasia type 1 (McKeeby et al. 2001). The cohort of patients studied denied substernal pain, dysphagia, or other upper-gastrointestinal symptoms typically associated with leiomyomas of the esophagus. Screening CT of the chest in 32 individuals did not show esophageal lesions suggestive of leiomyomas." 

This sounds like they report that it is NOT a known feature, but perhaps there is a newer publication? Thank-you very much for your help in verifying the source of this symptom. 

Sarah

**Comment by pnrobinson** [comment]
Hi @svonschuch  -- these are the annotations produced by the HPO team -- https://hpo.jax.org/app/browse/disease/OMIM:150800
These are complementary annotations produced by the Orphanet team -- https://hpo.jax.org/app/browse/disease/ORPHA:523

I do not see Abnormality of the musculature -- but maybe I am misunderstanding? Do you mean HLRCC=Hereditary Leiomyomatosis And Renal Cell Cancer?

**Comment by svonschuch** [comment]
﻿Hello,

Thank you for the links. I do in fact mean hereditary leiomyomatosis and renal cell cancer.  The abnormality of musculature is the first symptom listed on orphanet (see image) and I could have sworn I saw it in the HPO table today as well - I may have been mistaken. But I’m glad to see it’s not there. I’m not certain I understand how orphanet references it’s clinical signs (will try to did into this more on their site tomorrow).

I did submit a second comment via GitHub regarding Barrett’s esophagus which is listed on the link you shared - once again orphanet annotations. Would you have further information regarding that? 

Do I understand correctly that HPO curates symptom data from Omim… yet complementary annotations from orphanet are automated so you don’t have further reference data on symptoms listed from this database?

Sarah

**Comment by pnrobinson** [comment]
Orphanet creates its annotations with clinical experts. Orphanet annotates to clinical entities. The corresponding entries have an "ORPHA" disease code on the HPO site. Additionally, the HPO team manages annotations that are based on the OMIM gene-specific disease definitions. If the annotation is marked as OMIM, then it was text mined from OMIM. If the annotation is marked with a PMID, then the HPO team did the annotation upon manual review of the literature. Both sets of annotations are complementary. But in any case, suggestions about the Orphanet annotations should be made directly to the orphanet team -- https://www.orpha.net/consor/cgi-bin/index.php

We are always happy to receive suggestions or correction, thanks very much! I will close this issue now but please feel free to reopen or add a new issue if needed!
