### ISSUE TITLE
Ochronosis

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#770]
bluish black discoloration of the skin and mucosa (e.g. ear cartilage, ocular tissue). Seen in alkaptonuria, a metabolic disorder. 

probably add under "Abnormality of the skin"

@pnrobinson please advise if this should be added and where (from simulconsult-list)

**Comment by pnrobinson** [comment]
Def: Brown or blue-gray discoloration of the skin tha can present on the axillary and inguinal areas, face, palms or soles. In addition, blue-black discoloration can be apparent on skin overlying cartilage in which the pigment is deposited, such as the ears. This is a characteristic manifestation of alkaptonuria, which is an autosomal recessively inherited deficiency of homogentisic acid oxidase that  results in accumulation of homogentisic acid in collagenous structures. The sclerae are also typically involved.
PMID:26929770,24447956
