### ISSUE TITLE
Add Palmoplantar hypohidrosis

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#771]
We only have "Palmoplantar hyperhidrosis"

syns: Perspiration, sweating, palmar, skin on palms or soles, palmoplanter hyperhidrosis

**Comment by pnrobinson** [comment]
I do not think there is an entity with specific reduced sweating on palms and soles of feet. I do not think this term is needed. We have a term, HP_0000966, Hypohidrosis, for reduced sweating (in general).
