### ISSUE TITLE
Anti-thyroid-stimulating hormone receptor antibody positivity (HP:0034189) and Anti-thyrotropin receptor antibody (HP:0034116) should be synonyms

### ISSUE THREAD

**Issue by lopierra** [obophenotype/human-phenotype-ontology#7717]
**HPO term**
Anti-thyroid-stimulating hormone receptor antibody positivity (HP:0034189) and Anti-thyrotropin receptor antibody (HP:0034116) should be synonyms. I am not sure which is more common/preferred - have seen both in the literature.

Refs:
https://medlineplus.gov/lab-tests/tsh-thyroid-stimulating-hormone-test/
https://www.aafp.org/pubs/afp/issues/2021/0515/p605.html
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7567404/

**Synonym to be added**

**broad/exact/narrow/plural/abbreviation ?**
exact

**Comment by pnrobinson** [comment]
thanks for pointing this out. I have merged these two terms. The preferred term is now
Anti-thyroid-stimulating hormone receptor antibody positivity
and Anti-thyrotropin receptor antibody  was made to be a synonym.
