### ISSUE TITLE
Hip dysplasia synonyms + abbreviation

### ISSUE THREAD

**Issue by peupeubangbang** [obophenotype/human-phenotype-ontology#7718]
**HPO term**
Hip dysplasia HP:0001385

**Synonyms to be added**
Developmental dysplasia of the hip, congenital hip dislocation, congenital dislocation of the hip, DDH

**broad/exact/narrow/plural/abbreviation ?**
exact, exact, exact, abbreviation

**Comment by pnrobinson** [comment]
added -- thanks!
