### ISSUE TITLE
New teeth terms

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#772]
- Teeth red / Tooth; erythrodontia; dental
- Teeth: fragility / Tooth; dental; fragile; brittle
- Teeth: protruding / Tooth; dental; forward directed dentition
- Teeth: white specks or streaks / Tooth; dental

**Comment by drseb** [comment]
also :

Tooth abscesses

**Comment by pnrobinson** [comment]
I am making separate items for these
