### ISSUE TITLE
hyperandrogenemia

### ISSUE THREAD

**Issue by carolina-f** [obophenotype/human-phenotype-ontology#7721]
**HPO term**
Increased circulating androgen concentration HP:0030348

**Synonym to be added**
Hyperandrogenemia

**broad/exact/narrow/plural/abbreviation ?**
Hyperandrogenism, characterized by acne, hirsutism, 
and/or hyperandrogenemia, is a common finding in girls 
with JNCL
PMID: 27491213

**Comment by pnrobinson** [comment]
added the synonym, thanks!
