### ISSUE TITLE
Large elbow

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#773]
Elbows; prominent

**Comment by pnrobinson** [comment]
What is the use case for this term? I cannot find anything in the combined pubmed/google-ome.

**Comment by drseb** [comment]
simulconsult?

**Comment by pnrobinson** [comment]
(Mickey): one disease listed for large elbows, pseudoachondroplasia:

http://www.ncbi.nlm.nih.gov/books/NBK1487/

Extension at the elbows may be limited, and the elbows and knees may appear large.

 ... The corresponding finding about knees has 5 diseases, though.

**Comment by pnrobinson** [comment]
Adding as HP_0030865 (Large elbow).
Also a feature of Morquio syndrome
