### ISSUE TITLE
Polycystic kidney dysplasia

### ISSUE THREAD

**Issue by frichter** [obophenotype/human-phenotype-ontology#7733]
**HPO term**

"Polycystic kidney dysplasia" is not synonymous with "Enlarged polycystic kidneys" for HP:0000113. Enlarged polycystic kidneys are classically associated with ADPKD and ARPKD. Polycystic kidney dysplasia, which refers to kidneys with cysts that fail to grow, is _not_ associated with these genetic diseases. These phenotypes need to be entered separately to ensure accurate genotype-phenotype relationships and enable making new discoveries with dysplastic kidneys.

**Suggested revision and reasons**

Suggest moving "Polycystic kidney dysplasia" to be a subclass of "Multicystic kidney dysplasia" (HP:0000003)

**Comment by pnrobinson** [comment]
@frichter 
sorry for the long delay, the last two years have been insanely busy with my move back to Germany. 
I think that the entire subhierarchy of renal cysts requires work. We are going to be having a workshop about this in Berlin this Fall. For now, I am removing the Enlarged polycystic kidneys synonym.
