### ISSUE TITLE
Missing definition for "Abnormal facility in opposing the shoulders"

### ISSUE THREAD

**Issue by turnovec** [obophenotype/human-phenotype-ontology#7738]
**HPO term**
HP:0005259 | Abnormal facility in opposing the shoulders

**Suggested revision of textual definition**
My colleagues during a translation came to this term and we then discussed what does it mean exactly (to translate it correctly) and we agreed that it would help to have some definition for this term although we don't have any suggestion for it now...

**Comment by pnrobinson** [comment]
Thanks for pointing this add. Let's add this definition:
Def: Increased range of shoulder movement related to aplasia or hypoplasia of the clavicles that results in the ability to approximate the shoulders in front of the chest.
PMID:23289840
Comment: This feature is characteristic of cleidocranial dysplasia. See Figure 2 of PMID:23289840

**Comment by pnrobinson** [comment]
added definition
