### ISSUE TITLE
Mildly or moderately reduced visual acuity

### ISSUE THREAD

**Issue by Thil87** [obophenotype/human-phenotype-ontology#7739]
Dear team,
We have found an overlap in the definitions of 'mildly reduced visual acuity' (0.32-0.5) and 'moderately reduced visual acuity' (0.1-0.5). Is moderately reduced meant to have a narrower/lower range? We are in the process of expanding the MitoPhen database with HPO terms related to mitochondrial disease, and this has led to some issues. Please let us know best way forward. Many thanks, Thiloka

**Comment by pnrobinson** [comment]
@Sukram -- could we discuss the precise ranges?

**Comment by pnrobinson** [comment]
@Thil87 
sorry for the delay. I have revised the definitions to

Mild reduction of the ability to see. On the 6m visual acuity scale, mild reduction is defined as less than 6/12 but at least 6/18. On the 20ft visual acuity scale, mild reduction is defined as less than 20/40 but at least 20/70. On the decimal visual acuity scale, mild reduction is defined as less than 0.5 but at least 0.3.

Moderate reduction of the ability to see. On the 6m visual acuity scale, moderate reduction is defined as less than 6/18 but at least 6/60. On the 20ft visual acuity scale, moderate reduction is defined as less than 20/70 but at least 20/200. On the decimal visual acuity scale, moderate reduction is defined as less than 0.3 but at least 0.1.

Severe reduction of the ability to see. On the 6m visual acuity scale, severe reduction is defined as less than 6/60 but at least 3/60. On the 20ft visual acuity scale, severe reduction is defined as less than 20/200 but at least 20/400. On the decimal visual acuity scale, severe reduction is defined as less than 0.1 but at least 0.05.
