### ISSUE TITLE
Typo in definition for Pulsatile tinnitus (HP:0008629)

### ISSUE THREAD

**Issue by turnovec** [obophenotype/human-phenotype-ontology#7740]
**HPO term**
HP:0008629 | Pulsatile tinnitus 

**Bug description**
There is this stentence in definition:
"Finally, in some patients, mechanical abnormalities such a spatulous eustachian tubes, palatomyoclonus..."
I was trying to find what "spatulous eustachian tubes" are and I only found this:
https://en.wikipedia.org/wiki/Patulous_Eustachian_tube
Not just on Wikipedia, also there:
https://rarediseases.info.nih.gov/diseases/10812/patulous-eustachian-tube

So I think it's a typo and it should be corrected from "spatulous" to "patulous".

**Comment by pnrobinson** [comment]
Thanks for pointing out this error -- it should be patulous, which means  wide open or distended: a patulous eustachian tube

**Comment by pnrobinson** [comment]
Corrected to "Finally, in some patients, mechanical abnormalities such patulous eustachian tubes, palatomyoclonus (small spasms of muscles in the soft palate area), or idiopathic stapedial muscle spasm may represent the underlying cause of pulsatile tinnitus."
