### ISSUE TITLE
Bad capitalization in definition for Abnormal muscle fiber desmin 

### ISSUE THREAD

**Issue by turnovec** [obophenotype/human-phenotype-ontology#7743]
**HPO term**
HP:0030224 | Abnormal muscle fiber desmin 

**Bug description**
There is a sentence in definition:
"Desmin is an 53-KDa protein."

SI prefix for "kilo" is "k", not "K".

**Comment by pnrobinson** [comment]
corrected to 53-kDa protein. Thanks!
