### ISSUE TITLE
Bad unit acronym in definition of Abnormal muscle fiber myotilin

### ISSUE THREAD

**Issue by turnovec** [obophenotype/human-phenotype-ontology#7745]
**HPO term**
HP:0030226 | Abnormal muscle fiber myotilin

**Bug description**
Last sentence of defintion:
"Myotilin is a 57kD cytoskeletal protein."

Acronym for unit "Dalton" is "Da", not "D" (which is for dioptre).

**Comment by pnrobinson** [comment]
Thanks! Fixed to 57kDa
