### ISSUE TITLE
Wrong capitalization in "KDa" in definition for Abnormal muscle fiber dysferlin

### ISSUE THREAD

**Issue by turnovec** [obophenotype/human-phenotype-ontology#7746]
**HPO term**
HP:0030113 |  Abnormal muscle fiber dysferlin

**Bug description**
Second sentence of definition:
"Dysferlin is an ubiquitous 230-KDa transmembrane protein involved in calcium-mediated sarcolemma resealing."

Prefix for "kilo" is abbreviated as "k", not "K".

**Comment by pnrobinson** [comment]
Thanks! Fixed to 230-kDa
