### ISSUE TITLE
NTR: Mucosa erythematous (Mouth & throat)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#7767]
New term request Mucosa erythematous (segal_210723184057): Mouth red; nose

**Comment by pnrobinson** [comment]
See

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6405795/

**Comment by pnrobinson** [comment]
@MickeySegal -- I am not adding Mucosa erythematous, because it is ambiguous. Please note the term id  HP_0034418 for this. 

Label:
Erythematous oral mucosa
Def:
An erythematous lesion of the oral mucosa may result from a variety of tissue alterations, including inflammation, erythrocyte extravasation, and atrophy or reduced keratinization of the surface epithelium. PMID:[30693460](https://pubmed.ncbi.nlm.nih.gov/30693460)

**Comment by MickeySegal** [comment]
HP_0034418 seems to be a new term since I can't find it on the public HPO site.  

We had intended to include the nose as well, but I'm glad to use this term since nose and mouth are very correlated.
