### ISSUE TITLE
NTR: Jitteriness (Associated motor)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#7774]
New term request Jitteriness (lyon_020705092817): Rhythmic alternating movements of all extremities with equal velocity in flexion and extension, often stimulus sensitive; jittery  UMLS: 0549209

**Comment by pnrobinson** [comment]
@MickeySegal
Is this really different from tremor?
See - 
"In the present review, the terms tremor and jitter are used interchangeably."
(https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2606074/)
And are you referring to the phenotype seen in infants?

**Comment by MickeySegal** [comment]
It seems that jitteriness is used for recurrent tremor, but we had 30 times as many diseases with tremor as jitteriness so I've merged jitteriness into tremor so as to avoid issues based on which term was curated.  

It may be worthwhile mentioning jitteriness in your tremor finding.

**Comment by pnrobinson** [comment]
@MickeySegal 
thanks!
I added Jitteriness as a RELATED SYNONYM to the tremor term.
