### ISSUE TITLE
NTR: Cardiac imaging: cardiac valve chordae rupture (Cardiac & vascular)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#7784]
New term request Cardiac imaging: cardiac valve chordae rupture (nadea3_211014201126): Chordal; tricuspid and mitral valves  UMLS: 0155712

**Comment by pnrobinson** [comment]
@MickeySegal
I think this more usually refers to the mitral chordae tendinae
I have added this term
Label: Mitral chordae tendinae rupture
ID: HP_0034419
def: Breakage of the chordae tendinae of the mitral valve. This can lead to loss of tension of one of the mitral valve leaflets and mitral regurgitation.
Comment: The chordae provide the critical function of anchoring the mitral leaflets during systole, allowing for symmetric coaptation and preventing prolapse of the leaflets into the LA. The chordae are attached to the LV via the papillary muscles.


Note that I am not adding the "cardiac valve chordae rupture" as a synonym since it is too broad and thus the ID will not appear on the list I will send you when we have finished the curation.

**Comment by MickeySegal** [comment]
All our uses were for mitral, so I changed to "Cardiac imaging: mitral valve chordae rupture" and used your new code.

But note that UMLS has https://www.ncbi.nlm.nih.gov/medgen/C0155712 "Rupture of chordae tendineae" so there may be a role for a more general term.

BTW, why do HPO pages use the format HP:1234567 and you refer to the form with the underscore: HP_1234567?  The latter seems to confuse search algorithms less.

**Comment by pnrobinson** [comment]
HP:123 is the OBO and JSON format. HP_123 is the OWL format. They should be considered to be identical.
I cannot think of a situation with combined tricuspid and mitral chordae rupture and I wonder if the UMLS term also needs to be defined better? However, I am not an expert here.
