### ISSUE TITLE
NTR: Cardiac click sound on auscultation (Cardiac & vascular)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#7785]
New term request Cardiac click sound on auscultation (nadea3_211014205322): Mid-systolic  UMLS: 0277911

**Comment by pnrobinson** [comment]
@MickeySegal
I am adding this
label: Ejection click
def: A high-pitched sound that occurs at the moment of maximal opening of the aortic or pulmonary valves. They are heard just after the first heart sound. The sounds occur in the presence of a dilated aorta or pulmonary artery or in the presence of a bicuspid or flexible stenotic aortic or pulmonary valve. Ejection clicks may also be called ejection sounds.
PMID: 21250045
synonym: Cardiac click sound on auscultation

If this is not what you mean please reopen.

**Comment by MickeySegal** [comment]
This is fine.

**Comment by MickeySegal** [comment]
Did this get a new HPO code?

**Comment by MickeySegal** [comment]
Was an HPO code assigned?

**Comment by pnrobinson** [comment]
@MickeySegal 
Sorry, this got added as  HP_0034421
