### ISSUE TITLE
NTR: Triggered by smoke or burning flames (Chest, respiratory & breathing)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#7794]
New term request Triggered by smoke or burning flames (segal_210728155818): Tobacco, pollutants, pollution, poor air quality, open burning of natural gas on stove top  UMLS: 2220318

**Comment by pnrobinson** [comment]
@MickeySegal

this is a very broad descriptor. What is the disease context?

**Comment by MickeySegal** [comment]
We use it for asthma, Legg-Calvé-Perthes disease and ARDS.  The only one that seems specific is asthma, where there is an irritative or allergic response.  I could be persuaded to delete this finding - it is not as specific as exposure to volatile organic compounds.

**Comment by pnrobinson** [comment]
OK, let's not add this as a term for now, we can also revisit this if there are lots of data that could be clearly annotated with such a term.

**Comment by MickeySegal** [comment]
I deleted our finding.
