### ISSUE TITLE
NTR: Thoracic insufficiency syndrome (Chest, respiratory & breathing)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#7795]
New term request Thoracic insufficiency syndrome (hresko_220403201731): TIS; Stiffness of small chest or thorax; resulting in lung hypoplasia  UMLS: 4303632

**Comment by pnrobinson** [comment]
@MickeySegal

this appears to be a general pathophysiological description rather than an observable phenotypic abnormality.
If I am wrong, please provide a definition! thanks, Peter

**Comment by MickeySegal** [comment]
Dr. Hresko agrees that we should instead use the observable findings so we will eliminate this bundled term.

**Comment by pnrobinson** [comment]
thanks!
