### ISSUE TITLE
NTR: Decreased ability to smell cis-3-hexen-1-ol (specific) (Cranial nerves)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#7799]
New term request Decreased ability to smell cis-3-hexen-1-ol (specific) (elthat_130415184253): C3HEX  UMLS: 3554457

**Comment by pnrobinson** [comment]
@MickeySegal
is this a medically relevant phenotypic feature? This does not seem to be in scope for HPO.

**Comment by MickeySegal** [comment]
Described at https://www.omim.org/entry/615082, but less relevant clinically than the ability to taste phenylthiocarbamide.

**Comment by pnrobinson** [comment]
I think this is not a medically relevant finding, so it is outside the scope...
