### ISSUE TITLE
NTR: Seesaw winking (Cranial nerves)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#7802]
New term request Seesaw winking (elthat_130322192030): Alternate winking of the eyes; see-saw  UMLS: 1850266

**Comment by pnrobinson** [comment]
@MickeySegal
is this related to [Marcus Gunn jaw winking synkinesis HP:0025186](https://hpo.jax.org/app/browse/term/HP:0025186)?

**Comment by MickeySegal** [comment]
It is different clinically.  We have only one disease with this: https://www.ncbi.nlm.nih.gov/books/NBK1188 "OFD3 (OMIM [258850](https://omim.org/entry/258850)) is characterized by seesaw winking (alternate winking of the eyes) and polydactyly."

**Comment by pnrobinson** [comment]
@MickeySegal 
Given that the OMIM entry describes one patient with this phenomenon (https://omim.org/entry/258850) from 1971 and the definition of the feature is not really clear, I would propose we not make an HPO term for this at present. If you know of other instances of this feature with a clear definition, please reopen!
