### ISSUE TITLE
NTR: Ventricular shunt relieves symptoms (Cranium & spine)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#7804]
New term request Ventricular shunt relieves symptoms (segal_090625212841): Relief following shunt placement

**Comment by pnrobinson** [comment]
@MickeySegal
is this used in the diff dx of hydrocephalus? It seems unlikely that placement of a shunt would actually contribute to the diff in many real cases? Can you provide more background as to the intended use case?

**Comment by MickeySegal** [comment]
We've used the finding for Normal Pressure Hydrocephalus, where the result is not as obvious as for the usual high pressure hydrocephalus.

**Comment by pnrobinson** [comment]
I think this is probably not a great HPO term because this is really very specific for this one disease and would not necessarily make sense in a general context.
