### ISSUE TITLE
NTR: Battle sign bruise (Cranium & spine)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#7808]
New term request Battle sign bruise (segal_211118163916): Over mastoid process, behind ear  UMLS: 0741451

**Comment by pnrobinson** [comment]
@MickeySegal
added as 
HP:0034771
Battle sign

**Comment by MickeySegal** [comment]
You may want to include the information that the name refers to Dr. Battle, not acquiring the finding in battle.
