### ISSUE TITLE
NTR: Down syndrome-like facies (Face & neck)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#7822]
New term request Down syndrome-like facies (segal_120525190417): A bundled term whose absence facilitates exclusion of Down syndrome  UMLS: 0239542

**Comment by pnrobinson** [comment]
@MickeySegal

this is not a good HPO term because it is bundled  (as you say) and subjective -- this does not work in the HPO context. I will close for now, but reopen if there is some good workaround.

**Comment by MickeySegal** [comment]
Your position is reasonable.  We just used this term after being asked repeatedly how to remove Down syndrome from the differential diagnosis.  This gets suggested when Down syndrome is high, allowing easy dismissal of Down syndrome.

But UMLS created such a term: https://www.ncbi.nlm.nih.gov/medgen/C0239542
though that doesn't necessarily mean you should do the same.
