### ISSUE TITLE
NTR: Ingestion of beef contaminated with bovine spongiform encephalopathy (General history, localization & modifiers)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#7840]
New term request Ingestion of beef contaminated with bovine spongiform encephalopathy (elthat_140813091946):   UMLS: 2107823

**Comment by pnrobinson** [comment]
@MickeySegal

Wasn't it the case that this could only be inferred for those who came down with mad cow disease? I do not think there was ever a case where somebody brought a piece of steak to the hospital a day after eating it and asked for it to be tested, so I don't think this term would actually be of practical use (outside of the fact that it is mainly of historical interest now)

**Comment by MickeySegal** [comment]
There might be some use epidemiologically if there was a known outbreak, but that is rare and this wouldn't help diagnostically for an individual so I am deleting this term.

**Comment by pnrobinson** [comment]
closing
