### ISSUE TITLE
NTR: Maternal age young during pregnancy (General history, localization & modifiers)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#7843]
New term request Maternal age young during pregnancy (elthat_151204125311): Mother  UMLS: 2721699

**Comment by pnrobinson** [comment]
@MickeySegal
what is the definition of young? Can we provide context or a PMID?

**Comment by MickeySegal** [comment]
All my citations are for books, and I expect to be able to check in a few days when I return.

**Comment by MickeySegal** [comment]
Typical is the Woodward obstetrics book that says "younger maternal age" as a risk factor in septo optic dysplasia.  A literature citation is: https://pubmed.ncbi.nlm.nih.gov/22907285/ "SOD is associated with younger maternal and paternal age, primigravida births and ethnic differences."

**Comment by pnrobinson** [comment]
@MickeySegal 
The problem with this term is that the definition of young maternal age is culture-dependent and there is no single cut-off that would be (nearly) universally accepted in the way there is a cutoff for say serum potassium. I do not have access to the article, but from the abstract it looks like a linear regression was performed with maternal age, so there is no obvious way of saying whether a given mother is "too young" or not. I would suggest we not make this an HPO term.
