### ISSUE TITLE
NTR: Maternal amniocentesis (General history, localization & modifiers)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#7846]
New term request Maternal amniocentesis (elthat_160819034937): In utero; pregnancy; embryopathy; maternal; mother; prenatal; prenatally  UMLS: 0420931

**Comment by pnrobinson** [comment]
@MickeySegal
added as
HP:0034856

**Comment by peupeubangbang** [comment]
Can I ask how this will differ from **MAXO:0000534 _Amniocentesis_**? 

Will it be for a history of _**maternal amniocentesis_**?

http://purl.obolibrary.org/obo/MAXO_0000534

**Comment by MickeySegal** [comment]
We use the finding for "Amnion rupture sequence", i.e., treating the reduction of amniotic fluid as a bug, not a feature.
