### ISSUE TITLE
New term: upper limb muscle hypertrophy

### ISSUE THREAD

**Issue by CourtneyHum** [obophenotype/human-phenotype-ontology#785]
"upper limb muscle hypertrophy" under superclass HP:0003712 "skeletal muscle hypertrophy"

subclasses of "upper limb muscle hypertrophy" can be 
- "proximal upper limb muscle hypertrophy"
- "distal upper limb muscle hypertrophy"

**Comment by drseb** [comment]
note that *upper limb muscle hypertrophy* is subclass of

- *Abnormality of the musculature of the upper limbs* and
- *Skeletal muscle hypertrophy*
