### ISSUE TITLE
NTR: Folate intake inadequate (GI, feeding, vomiting & dehydration)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#7878]
New term request Folate intake inadequate (segal_110901211732):   UMLS: 5230732

**Comment by pnrobinson** [comment]
@MickeySegal

Could you provide context? Is this in the index patient or in the mother?

**Comment by MickeySegal** [comment]
In the patient.  The context is dietary folate deficiency https://www.ncbi.nlm.nih.gov/books/NBK535377/

**Comment by pnrobinson** [comment]
I am guessing that in clinical contexts, this would almost always be
[Reduced blood folate concentration HP:0100507](https://hpo.jax.org/browse/term/HP:0100507)
rather than by history, which perhaps outside of long sea voyages before citrus supplementation does not provide an accurate finding of vitamin deficiencies.
If we want to have a dietary term, I am guessing that it would be better to have something like Lack of fruit/vegetables in diet ...

**Comment by MickeySegal** [comment]
The list is more diverse than that: https://ods.od.nih.gov/factsheets/Folate-HealthProfessional/

We count on this finding coming up as a suggested useful finding for the clinician to ask about, and we give examples of "foods such as liver, spinach peas, or dietary supplements" and hyperlink to the URL above.
