### ISSUE TITLE
NTR: Modifier: emesis: bilious (GI, feeding, vomiting & dehydration)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#7886]
New term request Modifier: emesis: bilious (seidel_190217225716): Vomiting bile  UMLS: 0232599

**Comment by pnrobinson** [comment]
@MickeySegal
added as 

Bilious emesis
HP:0034754

(For reasons discussed in another issue, the HPO does not have such specific modifiers and it is better to make the combined (percomposed) term. If this does not work we can add a separate term "Bilious")

**Comment by MickeySegal** [comment]
This works.
