### ISSUE TITLE
NTR: Vegan or vegetarian diet (GI, feeding, vomiting & dehydration)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#7889]
New term request Vegan or vegetarian diet (segal_211224214903): Vegan excludes all meat and animal products (meat, poultry, fish, seafood, dairy and eggs), while vegetarian allows dairy and eggs.  Pescetarian (pescatarian) allows fish;  UMLS: 3241969

**Comment by pnrobinson** [comment]
@MickeySegal -- as a vegetarian for decades, there is a big difference in health risks between a vegetarian diet (non-existent unless limited beyond a typical vegetarian diet) and a vegan diet (where some supplementation is recommendable). Would it be a good idea to limit this to vegan?

**Comment by MickeySegal** [comment]
The primary reason for this finding was the association with B12 deficiency.  The idea was to include picky kids whose implementation of vegetarian excluded good sources of B12, but I think you are right that such kids would essentially be vegan, so I removed vegetarian from the name of the term.

**Comment by pnrobinson** [comment]
@MickeySegal 
adding as
HP:4000172
Vegan diet
def: A history of following a vegan diet characterized by avoidance of food sourced from animals including meet, fish, and dairy products.
