### ISSUE TITLE
Inflammatory_myofibroblastic_tumor

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#789]
Inflammatory_myofibroblastic_tumor
http://en.wikipedia.org/wiki/Inflammatory_myofibroblastic_tumour

reported here https://github.com/obophenotype/upheno/issues/65

**Comment by pnrobinson** [comment]
This is an extremely rare tumor, and I think that for now it would be better to wait for more NCI integration before adding this term.
