### ISSUE TITLE
Improve "Generalized osteoporosis with pathologic fractures"

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#795]
@pnrobinson can you provide a textual definition?

can we remove the logical definition? It does not comply any pattern - nothing really gained in terms of cross-ontology mappings.

**Comment by pnrobinson** [comment]
On second thought, this is not a good term and should be obsoleted (merged with the parent term generlized osteoporosis). The only annotation we have is http://www.omim.org/entry/176670. The annotation should be transferred to Generalized osteoporosis (which itself is already associated with a risk of pathological fracture). I am reassigining to Dr Seb to perform the obsoletion correctly!
