### ISSUE TITLE
Obsolete HP:0000735

### ISSUE THREAD

**Issue by bcoleman96** [obophenotype/human-phenotype-ontology#7951]
**HPO term**
Impaired social interactions
HP:0000735

**Reason for deprecation**
Term is overly vague and overlaps with Abnormal social behavior.

**Suggested replacement or term to consider**
Abnormal social behavior
HP:0012433

**Comment by pnrobinson** [comment]
@bcoleman96 
Any updates on this? The term could potentially be merged with the parent?

**Comment by bcoleman96** [comment]
Yeah, that would work.

**Comment by pnrobinson** [comment]
reciprocity is a pretty close synonym for interactions. I will merge for now and we can refine the synonyms. I will make it a related synonym
