### ISSUE TITLE
NTR: Testes firm  (Endocrine & genitourinary)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#7958]
New term request Testes firm  (elthat_110530000806): Testis; testicle; testicular; hard  UMLS: 0577210

**Comment by pnrobinson** [comment]
@MickeySegal
I think "firm" is a normal finding. "Hard(ened) testicle" is not -- but can you specify the disease here?

**Comment by MickeySegal** [comment]
The 2006 edition of Smith listed this for XXY syndrome, but it is gone in the 2013 edition and we don't use the finding for any other diseases and we don't want to encourage gratuitous squeezing of testicles.  So I will delete this finding.

**Comment by pnrobinson** [comment]
closing.
