### ISSUE TITLE
Hyperintensity of MRI T2 signal of the spinal cord

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#796]
moved from https://github.com/obophenotype/upheno/issues/131

**Comment by drseb** [comment]
This is now directly under *Abnormality of the spinal cord*. Let me know if you find a better super-class.

@Joiedavis

**Comment by Joiedavis** [comment]
Thank you Sebastian,

This finding is most often associated with the brain vs spinal cord, could it could under Abnormal morphology of brain? Or somewhere close?
Joie
828 595 2486

**Comment by drseb** [comment]
probably a stupid question: term label speaks about the *spinal cord*, so do you have any reference for your suggestion to move it to *abnormal brain morphology* ?

**Comment by Joiedavis** [comment]
Would MRI reports work?
Joie
828 595 2486

**Comment by pnrobinson** [comment]
Hi Joie,
I have added a text definition for this term. It seems to be properly placed within the ontology. I do not think there is a way of putting something like MRI Reports directly in the ontology, but it should be relatively easy to capture all such terms in a data entry GUI (i.e., all of the cebrebral MRI terms). Is this what you are after? Are you using Phenotips? I am closing this entry for now and we can take the discussion offline as needed.

**Comment by Joiedavis** [comment]
That's fine Dr Robinson,

I wasn't after adding MRI reports, I was offering to support my point that T2 hyperintensities are most often described in brain vs spinal cord.  I am using phenotips

Thank you
Joie
828 595 2486
