### ISSUE TITLE
NTR: Antenatal bleeding  (Endocrine & genitourinary)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#7961]
New term request Antenatal bleeding  (elthat_180529052436): Hemorrhage; vaginal  UMLS: 0269608

**Comment by pnrobinson** [comment]
@MickeySegal

Note that this term is already present as -- [Antepartum hemorrhage HP:0025328](https://hpo.jax.org/app/browse/term/HP:0025328). This term should be used if we are referring to the mother as the index patient. I am not sure if we need an additional term to refer to a history of antenatal bleeding if the index patient is the fetus or newborn?

**Comment by MickeySegal** [comment]
We have tried to clarify the child / mother language in our findings.  This finding is now "Antepartum hemorrhage in mother during one's gestation".  We used https://hpo.jax.org/app/browse/term/HP:0025328 despite this issue.  If you decide to make the child / mother distinction we'd be glad to divide into more specific terms, but using the same term for both may be good enough.

**Comment by pnrobinson** [comment]
OK, let's leave for now. We may be extended this part of the hierarchy later on.
