### ISSUE TITLE
NTR: Shoulders square-shaped (Extremities, joints & nails)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#7967]
New term request Shoulders square-shaped (elthat_110605200647): Horizontal clavicles  UMLS: 3280147

**Comment by pnrobinson** [comment]
@MickeySegal
I am not sure I understand what this is -- could you provide more context?

**Comment by MickeySegal** [comment]
https://www.ncbi.nlm.nih.gov/books/NBK1481/ describes "short thorax, square shoulders, winged scapulae", which doesn't add much explanation other than that the term is used.  

We've used a lay language description of "the shoulders do not slope down much".

https://www.ncbi.nlm.nih.gov/medgen/C3280147 uses the term but doesn't define it.

**Comment by pnrobinson** [comment]
If two MDs and UMLS cannot define it, then I would suggest it is probably will not add much. Shoulders that do not slope down much are not really an abnormal finding.

**Comment by MickeySegal** [comment]
I checked my clavicles and they slope up so I'm deleting this finding.

**Comment by pnrobinson** [comment]
closing
