### ISSUE TITLE
Update release pipeline

### ISSUE THREAD

**Issue by cmungall** [obophenotype/human-phenotype-ontology#797]
Background:

See the [PATO README-editors](https://github.com/pato-ontology/pato/blob/master/src/ontology/README-editors.md) for an example of a github release pipeline. See also [pato releases](https://github.com/pato-ontology/pato/releases)

See also [this post](https://douroucouli.wordpress.com/2015/12/16/creating-an-ontology-project-an-update/) for how to generate a github project from scratch. I don't recommend doing that here, but it is informative to run this in a sandbox and examine the results.
- [ ] change Makefile to include a release step that places `hp.{obo,owl}` in the github top level
- [ ] switch from releasing on hudson to manual releases in github
- [ ] update README-editors.md
- [ ] update https://github.com/OBOFoundry/purl.obolibrary.org/blob/master/config/hp.yml
- [ ] retrospectively make releases for some subset of previous versionIRIs that are out there?

**Comment by pnrobinson** [comment]
@drseb what do you think of this? Should we attempt to implement this? We could then do a monthly official release by using an outlook reminder or whatever to start the process?

**Comment by pnrobinson** [comment]
I am moving this to the Wiki: https://github.com/obophenotype/human-phenotype-ontology/wiki/Release%20pipeline
