### ISSUE TITLE
NTR: Back x-ray: Cobb angle greater than ten degrees (Extremities, joints & nails)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#7978]
New term request Back x-ray: Cobb angle greater than ten degrees (seidel_200907125930):   UMLS: 0563192

**Comment by pnrobinson** [comment]
@MickeySegal

can this be added as a related synonym to Scoliosis HP:0002650 ?

**Comment by MickeySegal** [comment]
This is an X-ray finding to go with the clinical finding of scoliosis, but I think your approach of treating it as a synonym is better because otherwise one would need to describe any disease with scoliosis with the radiology finding, which is duplicative.  I deleted our finding.

**Comment by pnrobinson** [comment]
added this as a related synonym!
