### ISSUE TITLE
NTR: Gray sclera (Eye structure & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#7992]
New term request Gray sclera (elthat_160826040757): Grey sclerae  UMLS: 4314009

**Comment by pnrobinson** [comment]
@MickeySegal
is this really distinct from 
[Blue sclerae HP:0000592](https://hpo.jax.org/app/browse/term/HP:0000592) ?

**Comment by MickeySegal** [comment]
OMIM considered "gray sclerae" important enough to put it in the name for https://omim.org/entry/617051.  We were deferring to them, but would gladly accept some consensus that others would agree on.

**Comment by pnrobinson** [comment]
As per email discussion, it seems grey and blue are both related to thinning of the sclera and so I will add this as a synonym

**Comment by MickeySegal** [comment]
We took the same approach, and also included both gray/grey spellings.  This is particularly confusing for Canadians since we would see both American and British spellings frequently and had trouble remembering which was which.

**Comment by pnrobinson** [comment]
definitely not a great idea to go it alone on spellings, but that train has left the station a long time ago! I can never remember whether to use one or two ll/rr in some words.
