### ISSUE TITLE
NTR: Knees dimpled (Skin and mucosa)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8011]
New term request Knees dimpled (elthat_150313160730): Dimples over the knees  UMLS: 1868580

**Comment by pnrobinson** [comment]
@MickeySegal I was going to add the following definition, but this kind of finding can be normal in infants. Can you specify the context in which this is seen?

Knee dimple
A groove or crease in the skin overlying the knee.

**Comment by MickeySegal** [comment]
In the Smith Malformation book this is described in Meier-Gorlin syndrome as "dimples over the knees".  But we do not have this listed for any other disease, and since it is also seen in normals, I deleted the finding.

BTW, I don't know why mucosa was listed in the title above.

**Comment by pnrobinson** [comment]
OK, closing
