### ISSUE TITLE
NTR: Skin: human bite mark (Skin and mucosa)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8015]
New term request Skin: human bite mark (seidel_190210202534): Human bite marks; animal bite marks  UMLS: 0574737

**Comment by pnrobinson** [comment]
@MickeySegal
thankfully I have no experience with this, but I imagine that the patient would tell us they were bitten by a shark rather than the physician inferring this from the appearance of a skin wound (is it really true that it is so characteristic that it must be shark and cannot be barracuda or whatever else? Now that the orcas are taking over, maybe the question will become more important, who knows)

**Comment by MickeySegal** [comment]
How did you infer involvement of a shark from this NTR?

But I see that this finding is a duplicate of https://hpo.jax.org/app/browse/term/HP:0020138 so I will merge our findings.

**Comment by pnrobinson** [comment]
OK!
