### ISSUE TITLE
Proposal for retiring the use of hasAlternativeIds or augmenting it with a proper obsoletion pattern

### ISSUE THREAD

**Issue by matentzn** [obophenotype/human-phenotype-ontology#8021]
The use of oboInOwl:hasAlternativeId is an accident of time which dates back to the old OBO format. Right now, HPO uses at least three different patterns to "obsolete" a term:

Given a correct term HP:123 and a deprecated alternative HP:321

1. HP:123 is annotated with the obsoleted id HP:321 using oboInOwl:hasAlternativeId
2. Same as (1), but HP:321 is furthermore declared explicitly as "obsolete" (owl:deprecated "true")
3. HP:321 is declared as obsolete, which is annotated with "term replaced by" HP:123, example http://purl.obolibrary.org/obo/HP_0002357

This causes [a some problems for downstream users](https://github.com/INCATools/ontology-access-kit/issues/340), as there is no single way with standard tooling to replace a deprecated HP term with another. One key problem is that solution (1), the dominant one in HP, does not result in the creation of a node in OBO-related tooling (any tooling), which means you can't "look for it" easily (`tool.getHPO().get(HP:321).getReplacement()`). This is important, for example, when processing a corpus of 1000ds of phenopackets and you need to replace old deprecated ids with new ones.

The correct solution according to current OBO practice is (3). This makes the deprecation and replacement with standard properties.

Here is an analysis of the prevalence of (1) and (2).

https://docs.google.com/spreadsheets/d/15ILrRtAJdclpMAIF7x_vewm6NMj_VxaOkqKZCLh56fY/edit?usp=sharing

I want to implement solution 3 across the board, and standardise HPO deprecation practices a bit more. This goes some way towards Aim 1.4 in the HPO grant, sub-heading `Develop Standard Operating Procedures (SOPs) for term obsoletion`.

**Comment by pnrobinson** [comment]
Agree.
In general, if we have
HP:123
label: obsoleted BLABLA
term replaced by HP:456

then this should also have owl:deprecated "true"

If you can create a list of terms where this is missing I will fix them.

**Comment by matentzn** [comment]
Yes, but moreover, what we also want is this:

if we have 

```
HP:123
label: BLABLA
alternativeId: HP:456
```

`HP:456` should also be deprecated properly:

```
HP:456
term replaced by: HP:123
owl:deprecated true
```

<img width="369" alt="image" src="https://user-images.githubusercontent.com/7070631/203748781-440de4a6-fe7e-4c72-b57e-5ed46ab8755d.png">

**Comment by matentzn** [comment]
BTW: these would be there if we were still using OBO Edit as an ontology editor. Its just that Protege does not add the `owl:deprecated true` automagically the way OBO Edit did.

**Comment by pnrobinson** [comment]
@matentzn I think we are in agreement on this -- can we add this to the Q/C pipeline? Can this issue be closed?

**Comment by matentzn** [comment]
I have other priorities right this moment but I will deal with this during a major push for the Paper. It is on my list of things!

**Comment by matentzn** [comment]
Related to #7947

**Comment by pnrobinson** [comment]
Hi @matentzn 
I think we should not change this because it is working fine, and we are catching the very occasional problem with the Q/C pipeline. I need to get this issue tracker below 100 by Summer - can we close :-o !?!

**Comment by matentzn** [comment]
Its cheating if you close issues without fixing them.. :P I would prefer we leave this open. As you see, we are getting to quite some HPO issues recently, and this one here really needs addressing. Its only "working fine" because people do not know all the things that are wrong, and people dont really care about the obsoleted concepts - but I think as part of our gradual maturation, we should do this right... Sorry, sorry.

**Comment by pnrobinson** [comment]
OK, but I do not understand what the proposal actually is?

**Comment by matentzn** [comment]
The most important part is https://github.com/obophenotype/human-phenotype-ontology/issues/8021#issuecomment-1326190656

But this is what needs to be done:

1. If a class is obsoleted, its should be added as an obsoleted class (not just the value of the "has alternative id" property)
2. If there is a "hasAlternativeId" property, there should also be a "is replaced by" relation

This is not going to change the way it works right now (all tools that worked before this intervention will continue to do so), but makes sure that we have "obsoletion" performed using a standard consistent pattern.

**Comment by pnrobinson** [comment]
But this is the way it is now. There were a few mistakes made with the 10,000 issues, but the vast majority of cases this is exactly how it was. There is no need to fix this issue!

**Comment by matentzn** [comment]
Let me just make it consistent - its not a lot of work... If it's just a handful wrong ones, all the better. If its not done by mid 9th April, you can close the issue.

**Comment by pnrobinson** [comment]
@matentzn  -- I think that this is actually working pretty well. I believe we have cleaned up a few legacy errors previously. I will close for now but we can add a check to the QC if this occurs again.
