### ISSUE TITLE
Change Abnormal Communicative Gestures

### ISSUE THREAD

**Issue by bcoleman96** [obophenotype/human-phenotype-ontology#8023]
**HPO term**
HP:4000090
Abnormal communicative gestures

**Suggested revision of textual definition**
Change title to "Abnormal gesture use"

**Comment by pnrobinson** [comment]
done

**Comment by bcoleman96** [comment]
Add Definition:
Abnormality in use of gestures defined as hand, shoulder, and head movements that convey a shared meaning within a culture that replace or supplement verbal communication.
