### ISSUE TITLE
Missing capitalization of "Hortega cells" in definition of "Abnormal microglia morphology"

### ISSUE THREAD

**Issue by turnovec** [obophenotype/human-phenotype-ontology#8030]
**HPO term**
HP:0100708 | Abnormal microglia morphology

**Bug description**
Definition: "An abnormality of the microglial cells. They are also known as brain-resident macrophages or hortega cells."

I think it should be capitalized as "Hortega cells".

**Comment by pnrobinson** [comment]
thanks, I fixed this!
