### ISSUE TITLE
Harmonise HPO attribution strategy to new OBO standards

### ISSUE THREAD

**Issue by matentzn** [obophenotype/human-phenotype-ontology#8032]
We have recently zoned in on a cool solution which easily allows pulling in basic metadata (names etc) for people with orcids based on @cthoyt "orcid dump" and @cmungall validation framework. 

I will work on harmonising all metadata in HPO to follow this system, which is, in essence based on using dublin core in conjunction with orcids to identify contributors.

**Comment by matentzn** [comment]
@pnrobinson for the paper this year, I would like to take this on - a full harmonisation of all attribution and date metadata in HPO. This includes:

- Harmonising all contributions to well formed ORCID identifiers
- Harmonising the old oboInOwl vocabulary use to dublin core (which is a FAIR, global standard), in particular term creation "date", and creator

Will you permit me to do this? I will write a nice section in the paper how this will align HPO more with FAIR metadata conventions.

**Comment by pnrobinson** [comment]
@cthoyt @matentzn it would be nice to create a list of contributors -- right now we are doing this manually.
But not everybody uses ORCIDs...so we need to also maintain a manual list...

**Comment by matentzn** [comment]
We take care of the attribution, and will make a list for you - but do you agree with my suggestions to proceed?

**Comment by pnrobinson** [comment]
You mean replacing the "oboInOwl" etc.? Sounds reasonable!

**Comment by matentzn** [comment]
Finishing this now. I need your help:

Can you contact these people and ask them for their ORCIDs? Or send me their emails so I can do it.

- "doelkens", "sdoelken", "sandra1" - (maybe https://orcid.org/0000-0001-6966-3863)
- "hecht" - (maybe https://orcid.org/0000-0002-6996-5279)
- "NIH:jdavis" - ?

**Comment by pnrobinson** [comment]
@matentzn I contacted the first two people and asked for their ORCID IDs (I could not find something unambiguously theirs myself). I am not sure who the third ID is referring to, I guess this is one reason to always use ORCID ids. 
Possibly our pipeline should just skip these entries until we can resolve them.

**Comment by matentzn** [comment]
@pnrobinson 

Can you if you have 15 minutes go through this table:

https://docs.google.com/spreadsheets/d/1IpumD1iNxTPHVvzCQVtdDHYT_z_LFXScw_aEaz3YHKk/edit#gid=0

And write all the complete names out? I can research the ORCIDs,  but I need some help understanding how is who.

**Comment by matentzn** [comment]
Todolist before closing this ticket:

- [ ] Remove http://www.geneontology.org/formats/oboInOwl#id annotation
- [ ] Decide what to do with http://purl.obolibrary.org/obo/hp#is_observable_through
- [ ] Harmonise http://www.geneontology.org/formats/oboInOwl#creation_date to dc:created (property and format)
- [ ] Upon release, materialise "creator" as a contributor (also if they contributed to the definition)
- [ ] Harmonise http://www.geneontology.org/formats/oboInOwl#createdBy to dc:creator
- [ ] HPO_CONTRIBUTOR:ClinGen_courtneythaxton  is this  https://orcid.org/0000-0002-6733-369X

**Comment by pnrobinson** [comment]
@matentzn can we close this issue or what remains to be done?

**Comment by matentzn** [comment]
I will close and re-open when this resurfaces as a priority! It was 80% done anyways.
