### ISSUE TITLE
Reduced beta-hexosaminidase activity HP:0033978 is ambiguous

### ISSUE THREAD

**Issue by MickeySegal** [obophenotype/human-phenotype-ontology#8033]
**HPO term**
Reduced beta-hexosaminidase activity HP:0033978

**Suggested revision of textual definition**
This would apply to both the products of the HEXA gene and the HEXB gene.  One is beta-hexosaminidase A and the other is beta-hexosaminidase B.  

We have tagged SimulConsult finding "Hexosaminidase A low" (our code f371) with HP:0033978 and have asked for an HPO term for "Hexosaminidase B low" (our code f372)

**Comment by pnrobinson** [comment]
@MickeySegal 
Not an expert, but isn't the enzyme activity measure from both the isoenyzmes? See https://www.cellbiolabs.com/sites/default/files/MET-5095-beta-hexosaminidase-activity-assay-kit.pdf

**Comment by MickeySegal** [comment]
Both enzymes are measured clinically:
https://www.ncbi.nlm.nih.gov/books/NBK579484/
"the diagnosis of Sandhoff disease is established by: (1) enzymatic testing that identifies abnormally low activity of the enzymes beta-hexosaminidase A (HEX A) and beta-hexosaminidase B (HEX B)"

But only A is low in Tay Sachs.

**Comment by pnrobinson** [comment]
The HEXA gene encodes the alpha subunit of hexosaminidase A ([EC 3.2.1.52](https://enzyme.expasy.org/EC/3.2.1.52)), a lysosomal enzyme involved in the breakdown of gangliosides. There are 2 isoenzymes of hexosaminidase: Hex-A and Hex-B (HEXB; [606873](https://omim.org/entry/606873)). [Beutler et al. (1975)](https://omim.org/entry/606869?search=beta-Hexosaminidase&highlight=%22beta%20hexosaminidase%22%2Cbetahexosaminidase#8) concluded that Hex-A has the structure alpha-beta, while Hex-B has the structure beta-beta.

**Comment by pnrobinson** [comment]
@MickeySegal 
HP:0025754
Reduced beta-hexosaminidase A activity

Also, the existing term "Reduced beta-hexosaminidase activity" was referring to the "B" form, so I updated the label.
