### ISSUE TITLE
NTR: Modifier: Skin: papules have white coloration (Skin and mucosa)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8035]
New term request Modifier: Skin: papules have white coloration (seidel_190616184956): Excludes scale, plaques, patches, hypopigmentation  UMLS: 0858697

**Comment by pnrobinson** [comment]
@MickeySegal
Is this a synonym? (Note the HPO does not in this case use a modifier term)

[White papule HP:0031289](https://hpo.jax.org/app/browse/term/HP:0031289)

**Comment by MickeySegal** [comment]
The HPO term is fine.  I had found the corresponding UMLS entry; I don't know why I didn't find the HPO term.

**Comment by pnrobinson** [comment]
ok, closing!
