### ISSUE TITLE
NTR: Hair protruding from cutaneous cyst (Skin and mucosa)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8037]
New term request Hair protruding from cutaneous cyst (segal_211221205721):

**Comment by pnrobinson** [comment]
@MickeySegal
what is the clinical context and the diagnostic value of specifying the hair protrusion in this case?

**Comment by MickeySegal** [comment]
https://www.ncbi.nlm.nih.gov/books/NBK560573/
"Hair protruding from a dermoid cyst punctum is pathognomic for dermoid cysts."

**Comment by pnrobinson** [comment]
@MickeySegal 
Possibly this is sufficient [Dermoid cyst HP:0025247](https://hpo.jax.org/app/browse/term/HP:0025247), if we add a comment that "Hair protruding from a dermoid cyst punctum is pathognomic for dermoid cysts."?
Unless there is a value in distinguishing between dermoid cysts with and without protruding hairs, this is probably the best way.

**Comment by MickeySegal** [comment]
OK

**Comment by pnrobinson** [comment]
done
