### ISSUE TITLE
Question about synonyms for neoplasm terms

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#804]
Many neoplasm of [anatomical site] terms have synonyms '[anatomical site] cancer. But based on the text def and what we discussed in Portland, this does not seem correct. Some are exact synonyms, but some are broad and some related. Can we remove the cancer synonyms or make them consistently broad or related (but not exact)?

09725
![image](https://cloud.githubusercontent.com/assets/6722114/14054785/3b9407a6-f299-11e5-9f36-d97852c8ccb0.png)

**Comment by drseb** [comment]
let's skype. can't follow your reasoning here on why you want to remove them.

**Comment by pnrobinson** [comment]
I am closing this for now. I think we need to speak with Warren about how to move forward with the cancer terms, and this is too big for one item on the tracker. Reopen if needed.
