### ISSUE TITLE
NTR: Poliovirus isolated from CSF (Lab: bacteriology, virology, parasitology, fungal)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8076]
New term request Poliovirus isolated from CSF (samant_110207040655): Cerebrospinal fluid  UMLS: 2748279

**Comment by pnrobinson** [comment]
@MickeySegal
not sure if this is a PCR test or perhaps electronmicroscopy?

**Comment by MickeySegal** [comment]
Not clear from https://www.cdc.gov/polio/us/lab-testing/diagnostic.html#:~:text=Detection%20of%20poliovirus%20in%20CSF,of%20infectious%20and%20noninfectious%20conditions. but it doesn't sound like it has high yield.

**Comment by pnrobinson** [comment]
OK, let's not add at this time, we can add it if there is a clear test that needs to be annotated.
