### ISSUE TITLE
NTR: Pathogenic bacteria in stool, or positive serologies in blood (Lab: bacteriology, virology, parasitology, fungal)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8080]
New term request Pathogenic bacteria in stool, or positive serologies in blood (hausma_130810162806): Shigella, Salmonella, Yersinia, Campylobacter; EHEC; enterohemorrhagic Escherichia coli; E. coli; shiga toxin; C. difficile; Clostridioides; Clostridium  UMLS: 0855265

**Comment by pnrobinson** [comment]
@MickeySegal
this is too broad a term to be useful. We will be extending the HPO's coverage of antibodies and cultures in this area moving forward. I think it might be more useful if you sent us an excel file with species names rahter than we doing one item at a time - we can automate this now that the backbone structure is there. @matentzn  -- this would be a good addition.

**Comment by MickeySegal** [comment]
This is a terribly bundled finding and we will un-bundle it.
