### ISSUE TITLE
Term request: transsexuality

### ISSUE THREAD

**Issue by petkraw** [obophenotype/human-phenotype-ontology#809]
How should I annotate "transsexuality"? It is currently listed as an OMIM phenotype that is associated with "abnormality of the nervous system" and abnormality of metabolism/homeostasis. However, if I don't have clinical information about these features, I would rather like to annotate "transsexuality"

**Comment by pnrobinson** [comment]
The current annotations are a result of the text mining procedures used previously. I have added a term, "Reduced volume of central subdivision of bed nucleus of stria terminalis", which was the neurological anomaly noted in the publication the OMIM record describes, and which seems to have been replicated in a few subsequent publications. This OMIM record is not that great, as it is certainly not the case that transsexuality is a Mendelian phenotype, and should not be described as a disease. 
The HPO currently does not have many terms that describe sexual behaviour. I think that this is in scope and something we should plan to do as a part of increased coverage of psychology/psychiatry/behaviour.
