### ISSUE TITLE
Retrospective releases on Github

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#810]
I have old release-data for every month since 2009. From what I understand about git-releases, each release has to be associated with a commit. There are no commits for this time, so I can’t create releases.

What would be a clever way to achieve retrospective releases from 2009 till today?

**Comment by DoctorBud** [comment]
I don't know any easy answers here. I'd write a script (probably in bash) that generated the necessary commits, tags, and releases.

### References

- [Using Curl to make GitHub releases](http://www.barrykooij.com/create-github-releases-via-command-line/)
- [Releases API curl example](https://github.com/blog/1645-releases-api-preview)
- [Releases API](https://developer.github.com/v3/repos/releases/#create-a-release)

Here is some pseudo-code that expresses one possible solution. Assume RELEASES is a directory path containing per-month release directories named something like `december_2014/`. Assume GITWORK is our Git working directory which is initially empty.

### Pseudocode

```
cd $GITWORK
for each directory D in releases/
   set DNAME = extract the month_year name from the full path of D
   git checkout -b release-$DNAME    # Create new branch
   cp -r $RELEASES/$DNAME ./$DNAME
   git add -A
   git commit -m "Release for $DNAME"

  # http://www.barrykooij.com/create-github-releases-via-command-line/
  API_JSON=$(printf '{"tag_name": "v%s","target_commitish": "master","name": "v%s","body":
           "Release of version %s","draft": false,"prerelease": false}'
           $DNAME $DNAME $DNAME)
  curl --data "$API_JSON" https://api.github.com/repos/:owner/:repository/releases
          ?access_token=:access_token
endfor
```

**Comment by cmungall** [comment]
I think it should be slightly easier in that you can migrate the svn git history using `svn git`. But I think this is into a new git repo. On top of that in earlier snapshots we did not use the same naming conventions, so I'm guessing you will have to do some code along the lines of that above.

(I think it may be worth bringing in the history to a new repo anyway)

How many retrospective releases do we want to make?

**Comment by drseb** [comment]
> (I think it may be worth bringing in the history to a new repo anyway)

but we lost a lot of history due to an error (I didn't make) when we moved hpo from one svn-repo to another.

How many retrospective releases do we want to make?

each month starting in january 2009.

**Comment by Relequestual** [comment]
I notice there's only one release in your releases section. I guess this is not the intent.
It's dated 2017 but the description is "new hp ontology release for march 2009".

We store the PURL (for example http://purl.obolibrary.org/obo/hp/releases/2016-09-03/hp.owl) to identify which version of HPO we are using, but now we can't provide this to users because it redirects to the github release (which is now 404).

Should I open a new issue for this?

**Comment by cmungall** [comment]
I updated the text on the release note so it says 2017

How many historic PURLs do you have registered? If you put the list here we can prioritize migrating these.

**Comment by cmungall** [comment]
@dougli1sqrd - would your tool be useful for this?

**Comment by drseb** [comment]
Please see HPO archive https://github.com/Human-Phenotype-Ontology/HPO-archive

**Comment by drseb** [comment]
Retrospective releases won't work for releases that we made before we moved to github

**Comment by dougli1sqrd** [comment]
Yeah, a "release" in git terms is really just a `tag`. Github keeps track of extra metadata. And it's correct, if you wanted to, you could do command line releases the way @DoctorBud describes, or use a tool, like my https://github.com/dougli1sqrd/bevos tool to perform releases a little easier from the command line. (it's just a wrapper for essentially what @DoctorBud does in bash.) But it sounds like you want to "release" each directory in your 2009-2013 archive? Yeah, I'm really not sure how you would do that. If you still had your svn (or whatever came before git) you could maybe try and import that history into github and then perform releases that way onto github.

**Comment by Relequestual** [comment]
@cmungall We currently use 9.11 (2016-09-03).

The problem is the PURL (http://purl.obolibrary.org/obo/hp/releases/2016-09-03/hp.owl) is invalid, as it redirects to github releases, and that release doesn't exist.

**Comment by Relequestual** [comment]
@drseb Saying "see the archives" is not a viable solution. It's not possible for me to tell which specific file is the 2016-09-03 release. 2016 releases are in a folder, but they just have a build number. I have no way to know which is which.

The PURLs for the old versions are now invalid (as explained above).

There's nothing stopping you from creating a separate archive branch, comitting the ontology files at a release's state, and then tagging that commit as an old release. That way your master branch would be unaffected, and the old PRULs would be valid, for whichever versions you tag.

I think this is probably the same as what @DoctorBud suggested.

Ultimatly, a PURL is supposed to be perminant. If it isn't, then what's the point? =/

**Comment by drseb** [comment]
The purls for the releases have never been valid. We currently only support the purls for the latest release. See HPO website. 

There several things stopping me to do that, e.g. time constraints, lack of a dedicated server, etc...

Please open a new ticket, as this one has been solved by creating the hpo-archive repo.
