### ISSUE TITLE
Dacryocystitis is misspelled as Dacrocystitis in HP:0000620

### ISSUE THREAD

**Issue by barkelj** [obophenotype/human-phenotype-ontology#811]

**Comment by drseb** [comment]
@pnrobinson please advise. I find both writings to be used.

**Comment by pnrobinson** [comment]
The correct spelling is Dacryocystitis, but the word seems to be often misspelled as Dacrocystitis. I have made the version with "Y" the term name and added the misspelled version as a synonym.
