### ISSUE TITLE
NTR: Iduronate 2-sulfatase (I2S) low in leukocytes or fibroblasts (Lab: blood chemistry: enzymes: leukocyte)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8132]
New term request Iduronate 2-sulfatase (I2S) low in leukocytes or fibroblasts (f386):

**Comment by pnrobinson** [comment]
@MickeySegal
closing as this seems a near duplicate of https://github.com/obophenotype/human-phenotype-ontology/issues/8131

**Comment by MickeySegal** [comment]
This is already present at https://hpo.jax.org/browse/term/HP:0034203, and as discussed in https://github.com/obophenotype/human-phenotype-ontology/issues/8131, different from alpha L iduronidase.
