### ISSUE TITLE
NTR: Galactocerebrosidase low in leukocytes or fibroblasts (Lab: blood chemistry: enzymes: leukocyte)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8134]
New term request Galactocerebrosidase low in leukocytes or fibroblasts (f389): Galactosylceramidase; GALC enzyme  UMLS: 2673270

**Comment by pnrobinson** [comment]
@MickeySegal
I think that this is Krabbe disease. The activity of the enyzme is measured in many places including serum fibroblasts and leukocytes. I am adding the latter two as synonyms to the existing term

[Reduced galactocerebrosidase activity HP:0034322](https://hpo.jax.org/browse/term/HP:0034322)

**Comment by MickeySegal** [comment]
I think we did this already - I have that HPO number.
