### ISSUE TITLE
NTR: Saposin B low in leukocytes or fibroblasts (Lab: blood chemistry: enzymes: leukocyte)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8143]
New term request Saposin B low in leukocytes or fibroblasts (segal_080219222051): Cerebroside sulfate activator protein

**Comment by pnrobinson** [comment]
@MickeySegal
can you provide the clinical context?

**Comment by MickeySegal** [comment]
https://omim.org/clinicalSynopsis/249900
"LABORATORY ABNORMALITIES
- Saposin B deficiency"

**Comment by pnrobinson** [comment]
@MickeySegal 
as far as I can see, these are all research-level assays and not clinical tests.

**Comment by MickeySegal** [comment]
A 2023 paper diagnosing this rare disease (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10037043/) used only gene testing so it looks like the saposin testing is not used clinically.

**Comment by pnrobinson** [comment]
thanks, closing!
