### ISSUE TITLE
NTR: Mitochondrial cobalamin reductase deficiency in fibroblasts (Lab: blood chemistry: enzymes)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8193]
New term request Mitochondrial cobalamin reductase deficiency in fibroblasts (segal_070724224338):

**Comment by pnrobinson** [comment]
@MickeySegal
could you provide the EC number or a gene symbol? What is the disease context?

**Comment by MickeySegal** [comment]
It is the defect in https://link.springer.com/referenceworkentry/10.1007/978-3-540-29676-8_364.  https://omim.org/entry/251100 doesn't mention it explicitly, but   https://www.ncbi.nlm.nih.gov/books/NBK1231/ refers to "enzymatic subtypes" that are sometimes used, but I can't tell if that refers to cobalamin reductase.

**Comment by pnrobinson** [comment]
@MickeySegal 
I think that this is actually
Decreased methylmalonyl-CoA mutase activity HP:0003210

see https://omim.org/entry/251100?search=CblA&highlight=cbla
