### ISSUE TITLE
NTR: Peroxisomal thiolase in blood low (Lab: blood chemistry: enzymes)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8198]
New term request Peroxisomal thiolase in blood low (segal_070726213703):

**Comment by pnrobinson** [comment]
@MickeySegal
can you provide the EC or OMIM number. Is it this? https://omim.org/entry/604054

**Comment by MickeySegal** [comment]
It is mentioned in Zellweger and related diseases in older references: https://pubmed.ncbi.nlm.nih.gov/1679469/; https://pubmed.ncbi.nlm.nih.gov/1673025/ but is now understood to be a category of enzymes: https://www.sciencedirect.com/science/article/abs/pii/S0300908411000575 
"Intriguingly, two different peroxisomal 3-ketoacyl-CoA thiolases for very-long-straight-chain fatty acids (thiolase A, ThA, Acaa1a and thiolase B, ThB, Acaa1b, EC:2.3.1.16) have been cloned in rodents, while only one corresponding gene (peroxisomal 3-acetyl-CoA acetyltransferase-1, ACAA1) has been identified in humans [2], [3], [4]. The third peroxisomal thiolase, SCP-2/3-ketoacyl-CoA thiolase (SCPx), displays a very broad substrate specificity, including cleavage of 2-methyl branched as well as straight-chain 3-ketoacyl-CoA esters"

I'm deleting the finding as replaced with more modern granular tests.

**Comment by pnrobinson** [comment]
OK!
