### ISSUE TITLE
NTR: Iduronidase-2-sulfatase high in blood or amniotic fluid (Lab: blood chemistry: enzymes)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8203]
New term request Iduronidase-2-sulfatase high in blood or amniotic fluid (segal_080118211335):

**Comment by pnrobinson** [comment]
@MickeySegal
is this alpha-L-iduronidase (https://omim.org/entry/607016)?

**Comment by MickeySegal** [comment]
We had a typo.  It is https://hpo.jax.org/browse/term/HP:0003538

**Comment by pnrobinson** [comment]
OK, closing!
