### ISSUE TITLE
NTR: beta-D-glucuronidase high in blood (Lab: blood chemistry: enzymes)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8209]
New term request beta-D-glucuronidase high in blood (mayman_090521174551):   UMLS: 5195139

**Comment by pnrobinson** [comment]
@MickeySegal
is this really a blood test? What is the context?

**Comment by MickeySegal** [comment]
It was from https://www.ncbi.nlm.nih.gov/books/NBK1828/ but no longer mentioned there so likely no longer a clinical test.  I will delete.

**Comment by pnrobinson** [comment]
OK!
