### ISSUE TITLE
NTR: beta-glucuronidase low in fibroblasts (Lab: blood chemistry: enzymes)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8212]
New term request beta-glucuronidase low in fibroblasts (mayman_090521175825):   UMLS: 1854750

**Comment by pnrobinson** [comment]
Can this be made a low tissue term?
Reduced leukocyte beta-glucuronidase activity HP:0034859

**Comment by pnrobinson** [comment]
@MickeySegal

Can this be made a low tissue term?
We already have
Reduced leukocyte beta-glucuronidase activity HP:0034859

**Comment by MickeySegal** [comment]
If the term includes fibroblasts it is what we need.

**Comment by pnrobinson** [comment]
@MickeySegal 
Reduced tissue beta-glucuronidase activity
HP:0034859
def: Concentration or activity of beta-glucuronidase (EC 3.2.1.31) below the lower limit of normal. FECH enzyme can be measured in multiple tissues including cultured fibroblasts and leukocytes.

narrow synoynm: Reduced beta-glucuronidase activity in cultured fibroblasts
