### ISSUE TITLE
NTR: alpha-L-fucosidase high in blood (Lab: blood chemistry: enzymes)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8213]
New term request alpha-L-fucosidase high in blood (mayman_090521223026):   UMLS: 4324670

**Comment by pnrobinson** [comment]
@MickeySegal
added as

HP:0034727
Reduced alpha-L-fucosidase activity

**Comment by pnrobinson** [comment]
Also 

Elevated alpha-L-fucosidase activity
HP:0034729

**Comment by MickeySegal** [comment]
Doing 2 in the same page was a bit confusing.  HP:0034729 is for the subject of this New Term Request, and HP:0034727 was for our "α-L-fucosidase low in leukocytes or fibroblasts" with our code f381.
