### ISSUE TITLE
pupils shape abnormal / Oval; misshapen

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#822]

**Comment by psergouniotis** [comment]
I think "Irregular pupil" should be added as a term with "Abnormal pupil shape" as a synonym. "Oval shaped pupil" could be a subclass. I personally, wouldn't include misshapen as a term.

**Comment by pnrobinson** [comment]
Adding HP_0025309 Abnormal pupil shape

**Comment by pnrobinson** [comment]
Adding HP_0025310, oval pupil
