### ISSUE TITLE
NTR: Prolinase activity high in blood, erythrocytes, or skin fibroblasts (Lab: blood chemistry: enzymes)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8222]
New term request Prolinase activity high in blood, erythrocytes, or skin fibroblasts (elthat_111113014304): RBCs, red blood cells

**Comment by pnrobinson** [comment]
@MickeySegal
Is it this enyzme? https://omim.org/entry/614243
What is the clinical context for increased activity?

**Comment by MickeySegal** [comment]
It is in https://academic.oup.com/clinchem/article-abstract/32/3/562/5652436 (see the table).  It was mentioned in https://ommbid.mhmedical.com/ommbid-index.aspx but I don't see it in https://omim.org/entry/170100 so it is real but not clear if done clinically now.

**Comment by pnrobinson** [comment]
Given the article is from the 1980s and that there are no more recent mentions I can find, let's hold off on making a term for now.
