### ISSUE TITLE
NTR: Spermine synthase activity low in leukocytes (Lab: blood chemistry: enzymes)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8229]
New term request Spermine synthase activity low in leukocytes (segal_130425204925): SMS

**Comment by pnrobinson** [comment]
@MickeySegal

as far as I can see this is not a clinical assay, it was used for some research projects but today is likely not relevant owing to WGS and the rarity of the disease,
PMID: 23897707

**Comment by MickeySegal** [comment]
https://www.ncbi.nlm.nih.gov/books/NBK144284/
"The diagnosis of Snyder-Robinson syndrome is established in a male proband with EITHER of the following:
Spermine synthase (SMS) enzyme analysis. Decreased or absent SMS enzyme activity in fresh white cells or cultured lymphoblasts"
