### ISSUE TITLE
NTR: Intestinal enterokinase activity low (Lab: blood chemistry: enzymes)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8230]
New term request Intestinal enterokinase activity low (elthat_130509042909):

**Comment by pnrobinson** [comment]
@MickeySegal
is it this enzyme? https://omim.org/entry/606635

**Comment by MickeySegal** [comment]
Yes.

**Comment by pnrobinson** [comment]
@MickeySegal 
It seems this is a determination from a small bowel biopsy rather than a circulating enzyme test, see
https://pubmed.ncbi.nlm.nih.gov/6347801/
It does not look like this is a current clinical assay and so I would suggest we close this issue.

**Comment by MickeySegal** [comment]
https://www.abcam.com/products/assay-kits/enterokinase-activity-assay-kit-fluorometric-ab170964.html sells a testing kit.

**Comment by pnrobinson** [comment]
Yes, but this company sells for research only products, I do not think this is a clinical test!
