### ISSUE TITLE
NTR: ATM protein low or absent (Lab: blood chemistry)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8240]
New term request ATM protein low or absent (segal_020521161940):

**Comment by pnrobinson** [comment]
@MickeySegal

is this ATM SERINE/THREONINE KINASE ?

**Comment by MickeySegal** [comment]
Yes, in ataxia-telangiectasia.

**Comment by pnrobinson** [comment]
I do not think this is a clinical test. See for instance https://pubmed.ncbi.nlm.nih.gov/14654357/
Therefore this is out of scope for HPO...
