### ISSUE TITLE
NTR: Ribotol elevated in blood (Lab: blood chemistry)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8247]
New term request Ribotol elevated in blood (segal_050824151142):

**Comment by pnrobinson** [comment]
@MickeySegal
this seems to be a xenobiotic, https://www.ebi.ac.uk/chebi/searchId.do;?chebiId=CHEBI:48505

Therefore, maybe "elevated" is misleading?

**Comment by MickeySegal** [comment]
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1181951/ has Figure 3 suggesting that ribitol is produced endogenously.

(I corrected the spelling in our term to ribitol)

**Comment by pnrobinson** [comment]
Thanks!
This is ribitol
https://www.ebi.ac.uk/ols/ontologies/chebi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCHEBI_15963


Adding as
Increased circulating ribitol concentration
HP:0034933
