### ISSUE TITLE
NTR: Guanidinoacetic acid high in blood (Lab: blood chemistry)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8248]
New term request Guanidinoacetic acid high in blood (segal_051118194127): GAA

**Comment by pnrobinson** [comment]
@MickeySegal
added as
HP:0034933
Increased circulating guanidinoacetic acid concentration

**Comment by MickeySegal** [comment]
This seems like a duplicate of https://hpo.jax.org/app/browse/term/HP:0034321

**Comment by pnrobinson** [comment]
Indeed that is a duplicate thanks for picking this up!
