### ISSUE TITLE
NTR: Dysferlin low or absent in blood (Lab: blood chemistry)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8256]
New term request Dysferlin low or absent in blood (segal_090128221921):

**Comment by pnrobinson** [comment]
@MickeySegal
is dysferlin really clinically measured in blood?
There are several muscles terms: [Abnormal muscle fiber dysferlin HP:0030113](https://hpo.jax.org/app/browse/term/HP:0030113)

**Comment by MickeySegal** [comment]
https://www.ncbi.nlm.nih.gov/books/NBK1408/ says "Only dysferlin immunoblotting of muscle is currently thought to be specific and sensitive" so I will delete the blood finding.

**Comment by pnrobinson** [comment]
OK
