### ISSUE TITLE
NTR: Thyroid binding globulin low in blood (Lab: blood chemistry)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8271]
New term request Thyroid binding globulin low in blood (elthat_101129015031):   UMLS: 0342182

**Comment by pnrobinson** [comment]
@MickeySegal
I think that Thyroid binding globulin is a possibly erroneous way of saying thyroxine-binding globulin
If this is not so, please reopen. Otherwise, this is the term
[Decreased circulating thyroxine-binding globulin concentration HP:0034591](https://hpo.jax.org/app/browse/term/HP:0034591)

**Comment by MickeySegal** [comment]
You are right that they are the same, but both show up on https://www.google.com/search?q=binding+globulin+thyroid+thyroxine so we should use your form but include the other as a synonym.
