### ISSUE TITLE
NTR: Macrophage inhibitory protein-1 alpha/beta high in blood (Lab: blood chemistry)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8274]
New term request Macrophage inhibitory protein-1 alpha/beta high in blood (elthat_110211033054):

**Comment by pnrobinson** [comment]
@MickeySegal
Not an expert but it seems that alpha and beta are measured separately? 
http://www.cloud-clone.com/products/APA092Hu61.html
Can you provide more context?

**Comment by MickeySegal** [comment]
https://www.gaucher.org.uk/completed_research_projects_collaborative_bone_study "Several serum were found to be elevated significantly in the patients with Gaucher disease compared with healthy control subjects serum biomarkers of several cytokines that were stable in stored serum and plasma. This included macrophage chemotactic protein 1 (MCP-1); macrophage inhibitory protein 1a and 1b (MIP-1b and MIP1-a); interleukin 8."

https://www.ncbi.nlm.nih.gov/books/NBK1269/ "Abnormalities in the concentration of certain bone markers have been found in some individuals with GD in serum (e.g., osteocalcin, bone-specific alkaline phosphatase, macrophage inhibitory protein-1 alpha and beta) and urine (e.g., urinary hydroxyproline, free deoxypyridinoline, calcium); however, the routine utility of these findings in clinical practice is not established."

So it may be best to delete this finding.

**Comment by pnrobinson** [comment]
I will delete for now, we can focus on details later on as needed.
