### ISSUE TITLE
NTR: FANCD2 protein decreased or absent in immunoblot assay (Lab: blood chemistry)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8276]
New term request FANCD2 protein decreased or absent in immunoblot assay (elthat_110307042547): Fanconi anemia group D2 protein

**Comment by pnrobinson** [comment]
@MickeySegal
is this a clinical assay? As written it sounds like a specific Western blot done in a research context, which might mean this is not ready to be an HPO term?

**Comment by MickeySegal** [comment]
It is no longer at https://www.ncbi.nlm.nih.gov/books/NBK1401/ so it seems no longer to be used clinically, so I deleted our finding.

**Comment by pnrobinson** [comment]
OK!
