### ISSUE TITLE
NTR: Cholesterol low in cultured lymphoblasts (Lab: blood chemistry)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8280]
New term request Cholesterol low in cultured lymphoblasts (elthat_110328055131):

**Comment by pnrobinson** [comment]
@MickeySegal
I am wondering if it would be appropriate to use a term like
"Low cholesterol in cultured cells"
or something like that unless this feature is specifically related to lymphoblasts? Could you provide more context?

**Comment by MickeySegal** [comment]
It is from https://www.ncbi.nlm.nih.gov/books/NBK51754/: "When cultured in cholesterol-depleted medium, lymphoblastoid cells of individuals with CHILD syndrome and CK syndrome have increased levels of methyl- and carboxy-sterols and slightly decreased levels of cholesterol"

This doesn't seem to be very useful clinically and I'd be inclined to delete the finding.

**Comment by pnrobinson** [comment]
OK; let's delete!
