### ISSUE TITLE
NTR: FASL high in blood (Lab: blood chemistry)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8287]
New term request FASL high in blood (elthat_110925174318): Tumor necrosis factor ligand

**Comment by pnrobinson** [comment]
@MickeySegal
should this be characterized as solubule Fas ligand (sFasL), see https://www.nature.com/articles/nm0396-317

**Comment by MickeySegal** [comment]
Yes.  I changed our term to: Soluble FASL high in blood
Our synonym field now lists: FasL (Fas ligand), a member of the tumor necrosis factor family; sFasL

**Comment by pnrobinson** [comment]
@MickeySegal 
HP:6000017
Elevated circulating soluble FASL concentration
