### ISSUE TITLE
NTR: N-carbamyl-beta-alanine high in blood (Lab: blood chemistry)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8294]
New term request N-carbamyl-beta-alanine high in blood (elthat_111121052137):

**Comment by pnrobinson** [comment]
@MickeySegal
I cannot find exactly this in CHEBI, but do see [N-carbamoyl-beta-alanine](https://www.ebi.ac.uk/ols4/ontologies/chebi/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCHEBI_18261), can you please check and name affected diseases?

**Comment by MickeySegal** [comment]
https://omim.org/entry/613161 lists "increased N-carbamyl-beta-alanine".
