### ISSUE TITLE
NTR: Aminolevulinate synthase activity high in erythrocytes (Lab: blood chemistry)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8299]
New term request Aminolevulinate synthase activity high in erythrocytes (elthat_121118173234): RBCs, red blood cells

**Comment by pnrobinson** [comment]
@MickeySegal
is this OMIM:300752  ?
IN  PMID: 23263862  the activity is measured in recombinant proteins. I am trying to find a reference for the enzyme being measured in RBCs? Also, there seem to be two isoforms. What is your source?

**Comment by MickeySegal** [comment]
We got this from https://www.ncbi.nlm.nih.gov/books/NBK121284/, where the relevant text is now "Erythroid-specific 5-aminolevulinate synthase 2 (ALAS2)"

**Comment by pnrobinson** [comment]
Looking at the references in the Gene Review, e.g. PMID: 23348515, it seems these are measurements of recombinat enzymes (https://pubmed.ncbi.nlm.nih.gov/23348515/), rather than clinical tests. I think this is outside the scope.
