### ISSUE TITLE
NTR: Normetanephrine low in blood, urine, or CSF (Lab: blood chemistry)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8310]
New term request Normetanephrine low in blood, urine, or CSF (elthat_130220200748): Cerebrospinal fluid

**Comment by pnrobinson** [comment]
@MickeySegal
according to one [source](https://www.urmc.rochester.edu/encyclopedia/content.aspx?contenttypeid=167&contentid=metanephrines_blood), the normal range for Normetanephrine is Less than 0.9 nmol/L. Therefore, there cannot be a "Reduced" test result. Please provide more context.

**Comment by MickeySegal** [comment]
Our sources that mentioned low metanephrine (https://hpo.jax.org/app/browse/term/HP:0034876, https://hpo.jax.org/app/browse/term/HP:0034877 and https://hpo.jax.org/app/browse/term/HP:0034878) no longer mention normetanephrine too, so I'm deleting any mention of normetanephrine.

**Comment by pnrobinson** [comment]
OK!
