### ISSUE TITLE
NTR: Vanillylmandelic acid low in blood, urine, and CSF (Lab: blood chemistry)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8311]
New term request Vanillylmandelic acid low in blood, urine, and CSF (elthat_130220200835): VMA; cerebrospinal fluid

**Comment by pnrobinson** [comment]
@MickeySegal
Similar to https://github.com/obophenotype/human-phenotype-ontology/issues/8310, the normal range starts at zero. Please provide context.

**Comment by MickeySegal** [comment]
Our source that mentioned this no longer does, so I'm deleting our finding.

**Comment by pnrobinson** [comment]
OK
