### ISSUE TITLE
NTR: Dihydroxyphenylglycol low in blood, urine, and CSF (Lab: blood chemistry)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8312]
New term request Dihydroxyphenylglycol low in blood, urine, and CSF (elthat_130220200914): DHPG; cerebrospinal fluid

**Comment by pnrobinson** [comment]
@MickeySegal

is this [3,4-Dihydroxyphenylglycol](https://hmdb.ca/metabolites/HMDB0000318)?

**Comment by MickeySegal** [comment]
All I know is from https://www.ncbi.nlm.nih.gov/books/NBK1474/ "DHPG = dihydroxyphenylglycol", but the GeneReviews articles for the diseases in the table don't mention it at all.  so it is not compelling that this is relevant clinically.

**Comment by pnrobinson** [comment]
OK. so let's close this for now!
