### ISSUE TITLE
NTR: 3-methoxytyramine high in blood, urine, and CSF (Lab: blood chemistry)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8313]
New term request 3-methoxytyramine high in blood, urine, and CSF (elthat_130220201315): Cerebrospinal fluid  UMLS: 3641671

**Comment by pnrobinson** [comment]
@MickeySegal
https://www.ebi.ac.uk/ols4/ontologies/chebi/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCHEBI_1582
Is this a clinical assay? To be a good HPO term, there should be a clinical test with normal range so that it is easy to say whether an individual has a too high or too low concentration. I saw a few publications that described distributions of values but did not find a clinical test. Could you provide the disease context and more background?

**Comment by MickeySegal** [comment]
It was mentioned in the 2003 version of https://www.ncbi.nlm.nih.gov/books/NBK1474/ but is no longer mentioned there or in https://omim.org/entry/223360.  So it doesn't sound like it is currently in clinical use so I deleted our finding.

**Comment by pnrobinson** [comment]
OK!
