### ISSUE TITLE
NTR: AICAR transformylase activity low in fibroblast (Lab: blood chemistry)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8326]
New term request AICAR transformylase activity low in fibroblast (elthat_130330194617): 5-aminoimidazole-4-carboxamide ribonucleotide formyltransferase

**Comment by pnrobinson** [comment]
@MickeySegal

I am thinking of slightly restructuring terms like this to have a hierarchy called tissue enzyme activity to cover cases where an enzyme can be measured in multiple tissues (since fibroblast is almost always just for convenience), and only have special terms for say muscle, liver, erythrocyte etc when the tissue of origin is important. So, this term would become something like

Reduced tissue AICAR transformylase activity

Thoughts?

**Comment by MickeySegal** [comment]
That works.
