### ISSUE TITLE
NTR: Cyclooxygenase 1 low in platelet (Lab: blood chemistry)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8329]
New term request Cyclooxygenase 1 low in platelet (elthat_130405113617): COX1; prostaglandin-endoperoxide synthase 1; PTGS1

**Comment by pnrobinson** [comment]
@MickeySegal
is this related to aspirin? What is the context?

**Comment by MickeySegal** [comment]
https://www.omim.org/entry/605735
"Laboratory studies showed impaired platelet aggregation due to a deficiency of platelet cyclooxygenase that catalyzes formation of PGG2"

**Comment by pnrobinson** [comment]
@MickeySegal 
well, this is a 20-year old "%" entry in OMIM that has never been confirmed and I cannot find any contemporary lab test for this feature. I would sughest we not include it for now, unless there is a recognized clinical test for this that is used in diagnostics.
