### ISSUE TITLE
NTR: Prebetalipoprotein low in blood (Lab: blood chemistry)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8347]
New term request Prebetalipoprotein low in blood (elthat_130602180114): Hypoprebetalipoproteinemia

**Comment by pnrobinson** [comment]
@MickeySegal
not sure this is up to date, but betaproteins used to be used to denote the combination of LDL and VLDL, and in some sources prebetalipoprotein is a band that overlaps with VLDL. Unless there is a reason to have this term now because modern lab tests are using this in a way that is very distinct from terms like Abnormal VLDL cholesterol concentration HP:0031889, it is probably best not to add it because it would partially overlap with existing terms.
thoughts?

**Comment by MickeySegal** [comment]
We use this for https://omim.org/entry/607236 "... described a woman with the combination of hyperprebetalipoproteinemia, acanthocytosis, retinitis pigmentosa, and pallidal degeneration."

It is possible that there is a more modern way to describe this.

**Comment by pnrobinson** [comment]
I think it is best not to make a term for this. See the following comments -- 

"hypoprebetalipoproteinemia” had originated in “a bygone era when gel or paper electrophoresis was used to separate plasma lipoproteins.

We emphasized then that “hypoprebetalipoproteinemia” and “aprebetalipoproteinemia” are meaningless from a metabolic perspective and are absent from the lipoprotein literature

(https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8490183/)
