### ISSUE TITLE
NTR: Leukotriene B4 low in blood (Lab: blood chemistry)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8358]
New term request Leukotriene B4 low in blood (elthat_130817165601):

**Comment by pnrobinson** [comment]
@MickeySegal
[Reduced circulating leukotriene C4 concentration HP:0030390](https://hpo.jax.org/app/browse/term/HP:0030390)

**Comment by MickeySegal** [comment]
The NTR was for B4, but the HPO term at the link above is for C4.
