### ISSUE TITLE
NTR: Muscle lactate clearance low in ischemic exercise test (Lab: blood chemistry)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8359]
New term request Muscle lactate clearance low in ischemic exercise test (elthat_130817172831): Transport

**Comment by pnrobinson** [comment]
@MickeySegal
is this really clearance of muscle lactate (rather than serum lactate)? 
What is the context?

**Comment by MickeySegal** [comment]
Seems to be erythrocyte lactate (with a previous disease name referring to a myopathy):
https://www.omim.org/entry/245340
"All 3 patients had erythrocyte lactate clearance rates that were 40 to 50% of normal control values."

I've changed our finding to refer to erythrocyte lactate clearance.

**Comment by pnrobinson** [comment]
@MickeySegal 
Looking back at this, I have been unable to find a second instance of the use of this test in the literature, and I cannot access the original paper (from 2000) because it is behind a paywall. I think that the specifally "RBC" location of this test was a one-off examination done for research and is not a current test that we would encounter in 2024, so this is not a good HPO term.

**Comment by MickeySegal** [comment]
Lactate clearance is tested in other circumstances such as assessing survivability: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4057293/ but I don't see how that is related to erythrocytes.  

It does sound like this is a research test, so I will delete it.  

Note that we also have "Erythrocyte lactate clearance low" elthat_130817172713.  I will delete that too.
