### ISSUE TITLE
NTR: UDP-glucose 4-epimerase activity low in lymphoblasts (Lab: blood chemistry)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8370]
New term request UDP-glucose 4-epimerase activity low in lymphoblasts (elthat_131211044228): GALE; uridine diphosphate-galactose-4'-epimerase  UMLS: 1856618

**Comment by pnrobinson** [comment]
@MickeySegal
there are some related terms ([Abnormal uridine diphosphate glucose-4-epimerase level HP:0410192
](https://hpo.jax.org/app/browse/term/HP:0410192)), but perhaps we need a new one.
What is the disease context?

**Comment by MickeySegal** [comment]
https://www.ncbi.nlm.nih.gov/books/NBK51671/
"GALE enzyme activity in red blood cells (RBC) (normal 17.1-40.1 μmol/hr/g Hb) as determined by the traditional spectrophotometric assay"

We have a separate finding for erythrocytes but this finding is about lymphocytes, testing that is no longer mentioned in this GeneReviews article and should probably be considered no longer a clinical test.
