### ISSUE TITLE
NTR: Matrix metalloproteinase 2 enzyme activity low in blood or fibroblasts (Lab: blood chemistry)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8394]
New term request Matrix metalloproteinase 2 enzyme activity low in blood or fibroblasts (elthat_160722074955): MMP2

**Comment by pnrobinson** [comment]
@MickeySegal
I think the serum assay is a (rarely used) clinical assay while the fibroblast assay is probably research only. For now I am making a term for the serum assay, please add another issue if you require the fibroblast version. Also the clinical assay is concentration rather than activity (which again I think is more of a research-only assay).

added as 
HP:0034615
Reduced circulating matrix metalloproteinase 2 concentration

**Comment by MickeySegal** [comment]
https://www.ncbi.nlm.nih.gov/books/NBK373578/ "The diagnosis of MONA is established in a proband with characteristic clinical and radiographic findings and either biallelic pathogenic variants in MMP2 or decreased activity of the enzyme matrix metalloproteinase 2.... Analysis of matrix metalloproteinase 2 enzyme activity can be performed by the electrophoretic technique gelatin zymography on body fluids and/or cell or tissue extracts".

This makes it sound like the assay is used clinically, and activity seems to be the proper term.
