### ISSUE TITLE
NTR: Hypoxanthine high in blood (Lab: blood chemistry)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8400]
New term request Hypoxanthine high in blood (elthat_160826073849):

**Comment by pnrobinson** [comment]
@MickeySegal this is Increased circulating hypoxanthine concentration HP:0034333

**Comment by MickeySegal** [comment]
Is this recently added to HPO?  I can't imagine why I would have missed it.  It is also not in UMLS.
