### ISSUE TITLE
NTR: Methanethiol high in breath (Lab: blood chemistry)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8420]
New term request Methanethiol high in breath (elthat_190101053713): Cabbage-like smell  UMLS: 4748388

**Comment by pnrobinson** [comment]
@MickeySegal
should this be a child of Halitosis HP:0100812?
what is the disease context?

**Comment by MickeySegal** [comment]
https://www.omim.org/entry/618148 "Breath odor is cabbage-like and results from high levels of methanethiol and dimethylsulfide in breath."

But I don't know if this is measured outside of a research context so it may be good to delete this.

**Comment by pnrobinson** [comment]
let's not add this term at this time then!

**Comment by MickeySegal** [comment]
We will keep the finding because of the explanatory term "Cabbage-like smell" but that may be too vague for HPO.
