### ISSUE TITLE
NTR: 14-3-3 protein high in CSF (Lab: cerebrospinal fluid tests)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8474]
New term request 14-3-3 protein high in CSF (elthat_140813095551): Cerebrospinal fluid

**Comment by pnrobinson** [comment]
@MickeySegal
not an expert. Do you know if one measures total 14-3-3 or isoforms as in https://www.frontiersin.org/articles/10.3389/fnagi.2022.941927/full ?

**Comment by MickeySegal** [comment]
The GeneReviews article https://www.ncbi.nlm.nih.gov/books/NBK1229/ says "Cerebrospinal fluid analysis may be abnormal with high levels of 14-3-3 protein and protein tau"
