### ISSUE TITLE
consider working to build the info box on wikipedia for phenotypes

### ISSUE THREAD

**Issue by mellybelly** [obophenotype/human-phenotype-ontology#848]
We could do for phenotypes similar to what the SU lab is doing for genes on phenotype pages?
@cmungall @drseb

**Comment by pnrobinson** [comment]
This would be awesome. There is a great need for this kind of Webpage, and probably Wikipedia would be the most efficient option! Andrew mentioned some interest about this, but I do not think he is funded to do it. It did not sound too hard to get started though. We can ask Andrew if he would give us a hand.

**Comment by pnrobinson** [comment]
I am closing this item, since we will be working with Andrew about this in the coming year.
