### ISSUE TITLE
NTR: Interferon-alpha high in blood (Lab: cerebrospinal fluid tests)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8481]
New term request Interferon-alpha high in blood (lee231_180715183254): IFN-alpha;

**Comment by pnrobinson** [comment]
@MickeySegal -- you may want to check this on your side, the item says both blood and CSF

**Comment by pnrobinson** [comment]
see also this in case it is CSF -- Increased CSF interferon alpha HP:0009709

**Comment by MickeySegal** [comment]
Our finding seem to be just about blood; e.g., for SAVI: STING-associated vasculopathy, infantile-onset.  Pui Lee, one of the experts in this area entered it from [Liu Y, et al. (2014) N Engl J Med. 371:507-518](https://pubmed.ncbi.nlm.nih.gov/25029335)

**Comment by pnrobinson** [comment]
added HP_0034513
Increased circulating Interferon-alpha concentration
