### ISSUE TITLE
Inconsistencies between JAX, genes_to_phenotypes and phenotypes_to_genes

### ISSUE THREAD

**Issue by yarong-lifemap** [obophenotype/human-phenotype-ontology#8486]
**HPO term**
HP:0000078

**Bug description**
In the phenotypes_to_genes file, there is a relationship with FBXW7. However, https://hpo.jax.org/app/browse/gene/55294 and in genes_to_phenotypes this relationship does not exist

**Comment by pnrobinson** [comment]
Could you check the FAQ -- What is the difference between genes_to_phenotypes.txt and phenotype_to_genes.txt ? here - https://hpo.jax.org/app/resources/faq

If this does not answer your question, please comment again, otherwise please close this issue

**Comment by yarong-lifemap** [comment]
Apologies for the late response and thanks for the reference. That said, can you please explain which file would contain, for example, the HPO terms related to HEXA gene? I cannot find that gene in phenotypes_to_genes or in genes_to_phenotypes
https://hpo.jax.org/app/browse/gene/3073

**Comment by yarong-lifemap** [comment]
Hi @pnrobinson any update on this?

**Comment by pnrobinson** [comment]
@drseb  -- this appears to be an omission in the genes_to_phenotype file, could you comment?

**Comment by yarong-lifemap** [comment]
@drseb We are releasing an updated version of GeneCards shortly. Would be great if we could have your insights!

**Comment by tobias2019** [comment]
We would also appreciate adding HEXA gene - HPO term associations to `phenotypes_to_genes` and `genes_to_phenotypes`. Thanks!

**Comment by pnrobinson** [comment]
Sorry for the late reply, 2023 was the year I relocated back to Berlin. We have made multiple updates to the entire pipeline, and so I hope whatever the issue was has been addressed. We have also added new documentation:
http://obophenotype.github.io/human-phenotype-ontology/annotations/genes_to_phenotype/
