### ISSUE TITLE
NTR: N-alpha-acetyllysine present in urine (Lab: chemistry: amino compounds)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8487]
New term request N-alpha-acetyllysine present in urine (segal_030428185030):

**Comment by pnrobinson** [comment]
@MickeySegal
I am not sure this is a clinical assay. I tried to search for normal range or medical applications but could not find anything. Could you provide context?

**Comment by MickeySegal** [comment]
https://link.springer.com/article/10.1007/BF01805679 "y restricting daily dietary lysine to 5.5 mg/kg body weight the fasting serum lysine became normal. Urinary lysine also became normal and the secondary metabolites homocitrulline, homoarginine,N α-acetyllysine andN ε-acetyllysine were no longer detected"

But this is a 1978 paper, and my only other reference is "Hommes FA (1990) Techniques Diagnostic Human Biochemical Genetics" so it is not clear that it is worth considering this as part of clinical medicine as it is currently practiced.

**Comment by pnrobinson** [comment]
OK, let's close this until a current publication etc appears.
