### ISSUE TITLE
NTR: Anserine present in blood (Lab: chemistry: amino compounds)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8493]
New term request Anserine present in blood (segal_030430194809):

**Comment by pnrobinson** [comment]
@MickeySegal
afaik anserine can result from dietary intake of poultry and other sources and the fact that it is present in the blood may not be an abnormal finding. Can you provide more context?

**Comment by MickeySegal** [comment]
https://rarediseases.org/rare-diseases/carnosinemia/ (click View Full Report) "The diagnosis of carnosinemia may be made by testing the levels of amino acids in blood and/or urine, which reveals abnormally high levels of carnosine and anserine in the serum and urine."  So I changed our finding to indicate that the level is elevated.

**Comment by pnrobinson** [comment]
@MickeySegal 
Still, looking at the OMIM entry: https://omim.org/entry/212200
it seems as if this condition was last described in the literature 25 years ago, and so it may well have been a "red herring". I think some of the RD websites do not do enough to provide an estimate of the reliability of a disease description??

**Comment by MickeySegal** [comment]
There is still some work in this area:
https://omim.org/entry/609064
"Gross (2023) mapped the CNDP1 gene to chromosome 18q22.3 based on an alignment of the CNDP1 sequence (GenBank BC113512) with the genomic sequence (GRCh38)."

So I will keep Carnosinemia, but this is the only disease in which we have anserine listed, so I will delete that since it seems unlikely to be a clinical test.

**Comment by pnrobinson** [comment]
OK, closing!

**Comment by MickeySegal** [comment]
I was looking through a lab report from Children's National Medical Center and the plasma amino acid panel included anserine and 16 other compounds.  I don't know why, but anserine is a clinical test.

**Comment by MickeySegal** [comment]
One of the metabolic experts at CNMC told me "It may result from dietary overload for example of chicken or fish. We don’t consider it clinically significant."

I'm exploring if there is some logic to measuring anserine, and asked "Is it helpful in interpreting other levels such as carnosine?  If it is not clinically significant, why is it measured?"

**Comment by MickeySegal** [comment]
The metabolic expert replied with the hypothesis of "I think of historical interest" for continued inclusion of anserine in the plasma amino acid panel.  So we made the right call in deleting it.
