### ISSUE TITLE
NTR: 3-amino-2-piperidone present in urine (Lab: chemistry: amino compounds)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8494]
New term request 3-amino-2-piperidone present in urine (segal_030430185427):

**Comment by pnrobinson** [comment]
@MickeySegal
I am not sure this is a clinical assay. I tried to search for normal range or medical applications but could not find anything. Could you provide context?

**Comment by MickeySegal** [comment]
1979 paper: https://pubmed.ncbi.nlm.nih.gov/491962/ "Increased amounts of 3-amino-2-piperidone were found in the urine, but these did not increase after the arginine-induced increase in ornithine levels"

But it is not clear whether this is currently used clinically.

**Comment by pnrobinson** [comment]
OK, closing
