### ISSUE TITLE
NTR: N-carbamoyl-aspartate present in urine (Lab: chemistry: amino compounds)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8496]
New term request N-carbamoyl-aspartate present in urine (segal_030501203309):

**Comment by pnrobinson** [comment]
@MickeySegal
what is the medical context?

**Comment by MickeySegal** [comment]
This is from Hommes FA (1990) Techniques Diagnostic Human Bi... in argininosuccinate lyase deficiency.  But https://omim.org/clinicalSynopsis/207900 doesn't list it, so this may no longer be measured.

**Comment by pnrobinson** [comment]
OK, let's close this for now!
