### ISSUE TITLE
NTR: Ethanolamine high in urine (Lab: chemistry: amino compounds)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8501]
New term request Ethanolamine high in urine (segal_030502153210):

**Comment by pnrobinson** [comment]
@MickeySegal, I am not an expert here, but the non-phosphate version of this feature seems obscure and there are mentions in the literature of [Phosphoethanolaminuria HP:0003239](https://hpo.jax.org/app/browse/term/HP:0003239). Is it possible this is what you are looking for? Could you specify the disease state?

**Comment by MickeySegal** [comment]
We have this listed in a disease called Ethanolaminosis as discussed in Hommes FA Techniques Diagnostic Human Biochemical Genetics.  It is also https://www.omim.org/entry/227150, which OMIM seems to consider as separate from those listed on your HPO page.  I am also not an expert here, but these 2 sources were our basis for including this.

**Comment by MickeySegal** [comment]
https://pubmed.ncbi.nlm.nih.gov/3233740/ concludes that "ethanolaminuria appears to be a non-specific sign of severe neurological disease rather than a distinctive feature of a specific inborn error of metabolism".  So I'll delete both the finding and the disease.
