### ISSUE TITLE
NTR: Hcy-Hcy high in blood (Lab: chemistry: amino compounds)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8507]
New term request Hcy-Hcy high in blood (segal_030502185427): Homocystine; homocystinemia

**Comment by pnrobinson** [comment]
@MickeySegal

similar question as #8500

**Comment by pnrobinson** [comment]
Closing because of -- https://github.com/obophenotype/human-phenotype-ontology/issues/8539
reopen if necessary

**Comment by MickeySegal** [comment]
Our sources that discussed Hcy-Hcy no longer do, and instead recommend just total Hcy.  So I'm merging this and the similar Hcy-Cys into our finding that uses https://hpo.jax.org/app/browse/term/HP:0002160
