### ISSUE TITLE
request for synonym/term

### ISSUE THREAD

**Issue by petkraw** [obophenotype/human-phenotype-ontology#851]
There is no term yet for "narrow palpebral fissure". Maybe this should be a synonym to "small palpebral fissure"? HP:0200007

**Comment by drseb** [comment]
"Narrow palpebral fissures" is already a synonym of  http://compbio.charite.de/hpoweb/showterm?id=HP:0000581

Does this help?

**Comment by petkraw** [comment]
Yes, this helps, but I am not sure whether "narrow palpebral fissure" is a good synonym for "blepharophimosis". We reviewed some cases with Prof. Horn and she wanted to annotate "schmale Liedspalte". Based on the definitions we thought the closest HP term was small palpebral fissure. Probably Nick knows how to handle it.

**Comment by pnrobinson** [comment]
Blepharophimosis is defined as A fixed reduction in the vertical distance between the upper and lower eyelids with short palpebral fissures (it is thus a bundled, or combined term, with both side-to-side shortness and top-to-bottom narrowness). The HPO currently has the term small palpebral fissure, which I think means the same as narrow palpebral fissure (top-to-bottom direction), and thus I have made narrow fissue the preferred term name and refined the definition. Thanks for the suggestion
