### ISSUE TITLE
NTR: beta-mercaptoacetate-cysteine disulfide high in urine (Lab: chemistry: amino compounds)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8515]
New term request beta-mercaptoacetate-cysteine disulfide high in urine (segal_030505145619):

**Comment by pnrobinson** [comment]
@MickeySegal
is this still a current investigation?
If referring to this disease, https://omim.org/entry/249650, then the latest entry was 1981 and no gene has been found.

**Comment by MickeySegal** [comment]
https://www.nature.com/articles/srep01986 adds a recent update, but it is not well linked yet to human disease so I'm deleting the finding and the disease.

**Comment by pnrobinson** [comment]
OK!
