### ISSUE TITLE
Unteraugenlie

### ISSUE THREAD

**Issue by petkraw** [obophenotype/human-phenotype-ontology#852]
I tried to attach a foto. I don't know whether it worked. We are looking for a term that might be used to describe the thickened wrinkle below the lower eyelid in Beckwith Wiedemann patients. This seems to be a rather specific feature in this syndrome. Frau Horn called it "dicke Unteraugenlidfalte".  

![bws](https://cloud.githubusercontent.com/assets/6832007/14790885/9ff21f70-0b13-11e6-9d07-6da4e34f8221.jpeg)

**Comment by drseb** [comment]
upload worked

**Comment by nicolevasilevsky** [comment]
maybe @markengelstad knows a term for this?

**Comment by markengelstad** [comment]
"Defect of lower eyelid"

**Comment by drseb** [comment]
not sure this is specific enough

**Comment by pnrobinson** [comment]
I would code this as infra-orbital crease, HP_0100876. This term is synonymous withthe eponymous term in Elements of Morphology, which has a photograph, see http://onlinelibrary.wiley.com/doi/10.1002/ajmg.a.32597/full and search for the term there!
