### ISSUE TITLE
NTR: Glutathione high in urine (Lab: chemistry: amino compounds)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8526]
New term request Glutathione high in urine (segal_030506160344):

**Comment by pnrobinson** [comment]
@MickeySegal

adding this as a synonym to [Glutathionuria HP:0034586](https://hpo.jax.org/app/browse/term/HP:0034586)

**Comment by MickeySegal** [comment]
Because I am keeping track of the new HPO numbers I see that this was added after I sent my list to you.  So I've added it to my list to check later for UMLS numbers being assigned.
