### ISSUE TITLE
NTR: Sarcosine high in CSF (Lab: chemistry: amino compounds)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8533]
New term request Sarcosine high in CSF (segal_030506190243): N-methylglycine; cerebrospinal fluid

**Comment by pnrobinson** [comment]
@MickeySegal
added as
Elevated CSF sarcosine concentration
HP:0034739

**Comment by pnrobinson** [comment]
@MickeySegal

See question at https://github.com/obophenotype/human-phenotype-ontology/issues/8539

**Comment by MickeySegal** [comment]
I don't see the connection with https://github.com/obophenotype/human-phenotype-ontology/issues/8539
