### ISSUE TITLE
NTR: Hcy-Hcy high in urine (Lab: chemistry: amino compounds)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8539]
New term request Hcy-Hcy high in urine (segal_030515145805): Homocystine; homocystinuria

**Comment by pnrobinson** [comment]
@MickeySegal

I am wondering if there is medical significance in recording specifically Hcy-Hcy as opposed to just
[Homocystinuria HP:0002156](https://hpo.jax.org/app/browse/term/HP:0002156)

See
Typically, Hcy in circulation is found either in free form (about 1%) or disulfide (Hcy-Hcy; homocystine) or mixed disulfide (Hcy-Cys) or in protein bound form. Therefore, in order to get a true estimate of Hcy, the free, disulfides and protein bound form of Hcy have to be accounted for. The expression total Hcy or tHcy is used to reflect the sum total of Hcy that comprises free Hcy, Hcy obtained from reduction of disulfides and Hcy liberated upon hydrolysis of proteins (protein bound).
https://nutritionandmetabolism.biomedcentral.com/articles/10.1186/s12986-017-0233-z

**Comment by MickeySegal** [comment]
Our sources for the diseases in which this finding has been used seem to have moved to this approach, though I think you mean https://hpo.jax.org/app/browse/term/HP:0002160.  so I will delete this finding.

**Comment by pnrobinson** [comment]
thanks, closing
