### ISSUE TITLE
New term: wheezing

### ISSUE THREAD

**Issue by CourtneyHum** [obophenotype/human-phenotype-ontology#854]
Perhaps under "functional respiratory abnormality" like cough

**Comment by CourtneyHum** [comment]
@pnrobinson When will the HPO be updated to reflect these new commits? Or has that already happened? Thanks

**Comment by drseb** [comment]
I can make the new release in the next days.

**Comment by drseb** [comment]
We plan to do the release on friday. Sorry for the delay

**Comment by CourtneyHum** [comment]
No worries, that is great! Thank you

On Mon, Jun 27, 2016 at 11:39 AM, Sebastian Köhler <notifications@github.com
> wrote:

> We plan to do the release on friday. Sorry for the delay
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/obophenotype/human-phenotype-ontology/issues/854#issuecomment-228784289>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ALZYM-EbXtZ24h0ZuQk_CBBqnFY3P19oks5qP-68gaJpZM4IQPhi>
> .
>



-- 
Courtney Hum, MSc
Genetic Counsellor
Centre for Computational Medicine
The Hospital for Sick Children
T: 416-813-7654 x414028
