### ISSUE TITLE
NTR: Hydroxylysine high in urine (Lab: chemistry: amino compounds)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8540]
New term request Hydroxylysine high in urine (segal_030515145923):

**Comment by pnrobinson** [comment]
@MickeySegal, this term existed already, I am adding the above as a synonym
[Hydroxylysinuria HP:0032414](https://hpo.jax.org/app/browse/term/HP:0032414)

**Comment by MickeySegal** [comment]
Thanks.  Without that a search for hydroxylysine doesn't find the entry.
