### ISSUE TITLE
NTR: gamma-aminobutyric acid (GABA) high in CSF (Lab: chemistry: amino compounds)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8544]
New term request gamma-aminobutyric acid (GABA) high in CSF (segal_040303195303): Cerebrospinal fluid  UMLS: 1848972

**Comment by pnrobinson** [comment]
@MickeySegal, this term existed, I am adding the above as a synonym
[Elevated CSF gamma-aminobutyric acid concentration HP:0032531](https://hpo.jax.org/app/browse/term/HP:0032531)

**Comment by MickeySegal** [comment]
Thanks.  This doesn't come up in an HPO search for GABA, but should with your changes.  I'm surprised, though, that I didn't find it with other searching, but I can't come up with another plausible search that fails.
