### ISSUE TITLE
NTR: Branched chain amino acids low in blood (Lab: chemistry: amino compounds)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8552]
New term request Branched chain amino acids low in blood (segal_120910125911): Valine, leucine, isoleucine  UMLS: 3278389

**Comment by pnrobinson** [comment]
@MickeySegal
Does this term refer to the total concentration of all three branched-chain AAs or to an observation that the concentration of one or more of Valine, leucine, isoleucine is low?

If the former, then does this definition make sense
Label: Reduced total circulating branched-chain amino-acid concentration
Def: Concentration in the blood of branched-chain amino acids (total amount of valine, leucine, isoleucine) is below the lower limit of normal.

**Comment by MickeySegal** [comment]
The implication in https://omim.org/entry/614923 and from the nature of the genetic defect is that all are low.  But we only use it for that one disease, so I'm deleting the bundled term and using valine, leucine, isoleucine individually.

**Comment by pnrobinson** [comment]
ok, closing
