### ISSUE TITLE
New terms to describe JOINT LAXITY

### ISSUE THREAD

**Issue by CourtneyHum** [obophenotype/human-phenotype-ontology#857]
JOINT LAXITY (HP:0001388)
- neck joint laxity
- shoulder joint laxity
- elbow joint laxity
- wrist joint laxity
- finger joint laxity
- hip joint laxity
- knee joint laxity
- ankle joint laxity
- toe joint laxity

**Comment by pnrobinson** [comment]
I do not think there is clinical distinction between hypermobility and laxity, and the hypermobility hierarchy has analogous terms. I have cleaned up the hierarchy. Please reopen if this is not sufficient.
