### ISSUE TITLE
NTR: Phenylpyruvic acid high in urine (Lab: chemistry: organic acids)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8572]
New term request Phenylpyruvic acid high in urine (segal_030509143818):

**Comment by pnrobinson** [comment]
child of Elevated urinary carboxylic acid HP:0040156

added as HP_0034458

**Comment by MickeySegal** [comment]
HP:0034458

**Comment by pnrobinson** [comment]
@MickeySegal  note that HP_0034458 and HP:0034458 are the same, just two different formats!

**Comment by MickeySegal** [comment]
It came through on the spreadsheet as HP:0040156 and I didn't notice the "added as HP_0034458" line.
