### ISSUE TITLE
New terms to describe JOINT DEGENERATION

### ISSUE THREAD

**Issue by CourtneyHum** [obophenotype/human-phenotype-ontology#858]
Not sure if these would be better as sub-terms of "abnormal joint morphology (HP:0001367) or "degenerative joint disease" (HP:0001379)
- neck joint degeneration
- shoulder joint degeneration
- elbow joint degeneration
- wrist joint degeneration
- finger joint degeneration
- hip joint degeneration
- knee joint degeneration
- ankles joint degeneration
- toes joint degeneration

**Comment by pnrobinson** [comment]
I think that all of these terms are essentially equivalent to the Osteoarthtis terms -- this is what is meant by joint degeneration. I will merge and add terms there
