### ISSUE TITLE
NTR: Decenedioic acid high in urine (Lab: chemistry: organic acids)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8601]
New term request Decenedioic acid high in urine (segal_030513144645):

**Comment by pnrobinson** [comment]
@MickeySegal
there are many different types of Decenedioic acid -- are we refering to the total level or to one of the subtypes, e.g., 
https://www.ebi.ac.uk/ols/ontologies/chebi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCHEBI_137808

**Comment by MickeySegal** [comment]
https://pubmed.ncbi.nlm.nih.gov/2380628/ refers to cis-5-decenedioic acid and apparently cis-4-decenedioic (with a typo); https://hmdb.ca/metabolites/HMDB0000603 also refers to cis-4-decenedioic.

**Comment by pnrobinson** [comment]
@MickeySegal 
I cannot seem to find one that is a clinical test -- e.g., in OMIM there are no results searching for Decenedioic.
the cited article is from 1990 -- maybe it is no longer worth adding a new term?

**Comment by pnrobinson** [comment]
@MickeySegal 
I will close this for now, I think this is not a current test!
