### ISSUE TITLE
NTR: Mevalonolactone high in urine (Lab: chemistry: organic acids)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8605]
New term request Mevalonolactone high in urine (segal_030513151657):

**Comment by pnrobinson** [comment]
@MickeySegal
are we talking about this compound: [R-mevalonolactone, (-)-](https://www.ebi.ac.uk/ols/ontologies/chebi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCHEBI_67849)?

**Comment by MickeySegal** [comment]
I don't know what the R means and I don't know about chirality.  The context is https://pubmed.ncbi.nlm.nih.gov/28284974/

**Comment by pnrobinson** [comment]
@MickeySegal 
I do not think there is a separate test for mevalolactone.

This is from GPT. I also searched "in an old-fashioned way"
Clinical tests for mevalolactone are not commonly performed as part of routine diagnostic procedures. Instead, clinical tests typically measure total mevalonate levels, which may include both mevalonic acid and mevalolactone due to their dynamic equilibrium.

**Comment by MickeySegal** [comment]
This was from the old Hommes (1990) Techniques Diagnostic Human Biochemical Genetics.  But it is also in:
https://ojrd.biomedcentral.com/articles/10.1186/1750-1172-1-13 
"MVA is biochemically characterized by accumulation of mevalonic acid and mevalonolactone."

I don't know if I believe that a mevalonic test also detects mevalonolactone, but I see tests offered for mevalonic but not mevalonolactone so I will delete mevalonolactone testing as superfluous and unavailable except on a research basis.
