### ISSUE TITLE
NTR: Hexanoic acid high in urine (Lab: chemistry: organic acids)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8608]
New term request Hexanoic acid high in urine (segal_030513165256):

**Comment by pnrobinson** [comment]
Dicarboxylic aciduria  -- merge with Elevated urinary dicarboxylic acid level HP:0033455

**Comment by pnrobinson** [comment]
added as HP_0034497

**Comment by MickeySegal** [comment]
This is a specific monocarboxylic acid, so it should have its own term under HP:0033303

**Comment by pnrobinson** [comment]
@MickeySegal 
this is effectively what we did.
I also merged Elevated urinary dicarboxylic acid level  and Dicarboxylic aciduria as synonyms.
