### ISSUE TITLE
NTR: Azelaic acid high in urine (Lab: chemistry: organic acids)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8615]
New term request Azelaic acid high in urine (segal_030513190456):

**Comment by MickeySegal** [comment]
All I see is a 1992 paper:
https://pubmed.ncbi.nlm.nih.gov/1527989/
Azelaic and pimelic acids are excreted in elevated amounts in urine in disorders of mitochondrial beta-oxidation and disorders of peroxisomal beta-oxidation, for which they are of significant diagnostic value.

**Comment by pnrobinson** [comment]
@MickeySegal 
Looking at HMD, I do not think that paper was accurate, a metabolic disorder is not mentioned here
https://hmdb.ca/metabolites/HMDB0000784
Please reopen if there is a modern clinical test for this compound.
