### ISSUE TITLE
New term request: Heterotaxy

### ISSUE THREAD

**Issue by kam41** [obophenotype/human-phenotype-ontology#862]
Please add heterotaxy and/or situs ambiguous.  Currently the closest term is "Abnormality of the abdominal situs" (HP:0011620).  "Situs inversus totalis" (HP:0001696) is not an accurate description of the symptom I would like to describe via HPO.  Thanks!

**Comment by pnrobinson** [comment]
Added term as HP_0030853

**Comment by kam41** [comment]
Thanks!


Kristin A. Maloney, MS, MGC, CGC
Instructor, Division of Endocrinology, Diabetes & Nutrition
Department of Medicine
Program in Personalized & Genomic Medicine
University of Maryland School of Medicine

685 W. Baltimore St., MSTF 3-14H Baltimore, MD 21201
P: 410-706-6071
F: 410-328-5484
kmaloney1@medicine.umaryland.edu


>>> Peter Robinson <notifications@github.com> 05/17/16 2:04 AM >>>
Added term as HP_0030853
 —
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
         
  
 

Confidentiality Statement:
This email message, including any attachments, is for the sole use of
the intended recipient(s) and may contain confidential and privileged
information. Any unauthorized use, disclosure or distribution is
prohibited. If you are not the intended recipient, please contact the
sender by reply email and destroy all copies of the original message.
