### ISSUE TITLE
NTR: Octanoylglycine present in urine (Lab: chemistry: organic acids)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8620]
New term request Octanoylglycine present in urine (segal_030514192612):

**Comment by pnrobinson** [comment]
@MickeySegal
do we mean this: https://hmdb.ca/metabolites/HMDB0000832
If not, what is the medical context?

**Comment by MickeySegal** [comment]
Scriver CR Physician's Guide to the Laboratory Diagnosis of Metabolic Diseases had this in Glutaric Aciduria II and Medium chain acyl CoA dehydrogenase deficiency but I don't see that anywhere else so I don't know if it is clinically used now.

**Comment by pnrobinson** [comment]
OK, let's close for now!
