### ISSUE TITLE
NTR: Methacrylicaciduria (Lab: chemistry: organic acids)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8627]
New term request Methacrylicaciduria (segal_070716195412): Methacrylicacid high in urine

**Comment by pnrobinson** [comment]
@MickeySegal
is this intended to be for https://omim.org/entry/250620
It is then "Urinary excretion of cysteine and cysteamine conjugates of methacrylic acid "
Is this a current clinical test or research-only?

**Comment by MickeySegal** [comment]
All I see are references to the same Brown paper cited in OMIM.

**Comment by pnrobinson** [comment]
@MickeySegal 
the Brown paper was from the 1980s. All I can find about this compound is that it is used industrially
https://en.wikipedia.org/wiki/Methacrylic_acid
I think this was possibly a mistake and would suggest we not include the term unless there is a modern precise reference.

**Comment by MickeySegal** [comment]
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4852729/ says "In addition, urinary excretion of 2-methyl-2,3-dihydroxybutyric acid can be seen in small quantities by urine organic acid analysis and methacrylyl-CoA metabolites, S-(2-carboxypropyl)cysteine and S-(2-carboxypropyl)cysteamine, can be detected through urine MS/MS analysis. However, these metabolites, which are not routinely measured in most laboratories"

So there may be a typo, but even if that is corrected it is still not a current test and other metabolites are measured instead.

So we can delete this finding.
