### ISSUE TITLE
NTR: Tiglic acid high in urine (Lab: chemistry: organic acids)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8629]
New term request Tiglic acid high in urine (segal_070724203105):

**Comment by pnrobinson** [comment]
@MickeySegal
is this for https://omim.org/entry/275190
If so it is a "legacy" disease apparently last reported in 1985 as an abstract, probably this is not enough to create a term.

**Comment by MickeySegal** [comment]
We had it for https://omim.org/entry/606054 but it is no longer there and may have been from the 1972 paper https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1178511/

I'd be OK with deleting the finding.

**Comment by pnrobinson** [comment]
let's not create the term now; if we find a current use case for the test then we will create one.
