### ISSUE TITLE
NTR: Triglycine high in urine (Lab: chemistry: organic acids)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8633]
New term request Triglycine high in urine (segal_070726191708):

**Comment by pnrobinson** [comment]
@MickeySegal
Can you provide the disease context?

**Comment by MickeySegal** [comment]
https://www.medlink.com/articles/biotin-holocarboxylase-synthetase-deficiency "Subsequently, beta-hydroxyisovaleric acid and triglycine were demonstrated in the urine. "

But I don't see triglycine mentioned at https://omim.org/entry/253270 so it is not clear if this is a clinical test.

**Comment by pnrobinson** [comment]
I cannot find a mention of a clinical test for triglycine in PubMed or google, so let's not create a term for now.
