### ISSUE TITLE
NTR: 2-butanone present in urine (Lab: chemistry: organic acids)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8636]
New term request 2-butanone present in urine (segal_071130202239):   UMLS: 1859855

**Comment by pnrobinson** [comment]
@MickeySegal
is this a xeno compound? What is the disease context?

**Comment by MickeySegal** [comment]
https://omim.org/entry/203750 "Alpha-methylacetoacetic aciduria, also known as 3-ketothiolase deficiency, is an inborn error of isoleucine catabolism characterized by urinary excretion of 2-methyl-3-hydroxybutyric acid, 2-methylacetoacetic acid, tiglylglycine, and 2-butanone."

**Comment by pnrobinson** [comment]
In [this:
The first case of mitochondrial acetoacetyl-CoA thiolasedeficiency identified by expanded newborn metabolic screeningin Italy: the importance of an integrated diagnostic approach](https://pubmed.ncbi.nlm.nih.gov/20157782/),
the authors mention: "the instability of this β-ketoacid because it undergoes spontaneous decarboxylation to 2-butanone,which is highly volatile and thus difficult to detect"
and do not actually test it. 
I could not find any other mention of a test of this in a clinical setting, and HMDB also does not actually describe it
https://hmdb.ca/metabolites/HMDB0000474

So this does not look like it is currently a useful clinical test
