### ISSUE TITLE
NTR: N-acetyl-acryloyl-cysteine high in urine (Lab: chemistry: organic acids)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8646]
New term request N-acetyl-acryloyl-cysteine high in urine (elthat_190815155306):

**Comment by pnrobinson** [comment]
@MickeySegal
can you provide context or a definition?

**Comment by MickeySegal** [comment]
https://www.ncbi.nlm.nih.gov/books/NBK542806/ "Elevations of urine acryloyl-cysteamine, acryloyl-l-cysteamine, N-acetyl-acryloyl-cysteine, methacryl-cysteamine, methacryl-cysteamine, or N-acetyl-methacryl-l-cysteamine"

**Comment by pnrobinson** [comment]
@MickeySegal 
see https://github.com/obophenotype/human-phenotype-ontology/issues/8645

**Comment by pnrobinson** [comment]
same comment as https://github.com/obophenotype/human-phenotype-ontology/issues/8644

**Comment by MickeySegal** [comment]
See my discussion in https://github.com/obophenotype/human-phenotype-ontology/issues/8644
