### ISSUE TITLE
NTR: Methacryl-cysteamine high in urine (Lab: chemistry: organic acids)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8647]
New term request Methacryl-cysteamine high in urine (elthat_190815155314):

**Comment by pnrobinson** [comment]
@MickeySegal
can you provide context or a definition?
Is this an exogenous compound?

**Comment by MickeySegal** [comment]
https://www.ncbi.nlm.nih.gov/books/NBK542806/ "Elevations of urine acryloyl-cysteamine, acryloyl-l-cysteamine, N-acetyl-acryloyl-cysteine, methacryl-cysteamine, methacryl-cysteamine, or N-acetyl-methacryl-l-cysteamine"

**Comment by pnrobinson** [comment]
@MickeySegal
I am having difficulty placing these chemicals in the hierarchy since I cannot find them in CHEBI. Searching in Google also does not produce many hits. I am wondering if these are non-standard descriptions that will not be reproducible. Not sure these are good HPO terms unless we can find a definition that is clear for future use. See also https://github.com/obophenotype/human-phenotype-ontology/issues/8644

**Comment by MickeySegal** [comment]
https://omim.org/entry/616277 "In 2 patients, analysis of urine metabolites showed elevated acryloyl cysteamine, N-acetyl-acryloyl-cysteine, methacryl-L-cysteine, and N-acetyl-methacryl-cysteine. "

**Comment by pnrobinson** [comment]
same comment as https://github.com/obophenotype/human-phenotype-ontology/issues/8644

**Comment by MickeySegal** [comment]
See my discussion in https://github.com/obophenotype/human-phenotype-ontology/issues/8644
