### ISSUE TITLE
NTR: Dimethylhept-enedioic acid high in urine (Lab: chemistry: organic acids)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8650]
New term request Dimethylhept-enedioic acid high in urine (elthat_200509174948):

**Comment by pnrobinson** [comment]
@MickeySegal
same question as https://github.com/obophenotype/human-phenotype-ontology/issues/8649
Unsure where to place this in the hierarchy. Do you know of a reference?

**Comment by MickeySegal** [comment]
That GeneReviews article is our only source.

**Comment by pnrobinson** [comment]
I think that this is not a good HPO then, because there is no clear definition that would allow users to annotate with this going prospectively. Possibly this is a mistake or a non-standard description in the article.

**Comment by MickeySegal** [comment]
Urine organic acids people seem to be able to look for such chemicals:
https://www.sciencedirect.com/science/article/pii/S0002929718301654
Urine organic acid GC-MS profiles of individual 1 (top) and a control subject (bottom). Normal urine components are indicated in italics. Numbered peaks indicate abnormal metabolites: (1) methylsuccinic, (2) mevalonic lactone, (3) mesaconic acid, (4) 2-methylgluatic acid, (5) 3-methyladipic acid, (6) 3-methylhex-3-enedioic acid, (7) 3-methylhex-2-endioic acid, (8) 2,6-dimethylheptanedioic acid, (9) unknown, (10) 3-methylhex-2,4-dienedioic, (11) 2,6-dimethylhept-2-enedioic acid, (12) 3,7-dimethyloctanedioic, and (13) 3,7-dimethyl-2,6-dienedioic.
