### ISSUE TITLE
NTR: Endoscopy: gastric xanthomas (Lab: endoscopy and exploratory surgery)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8653]
New term request Endoscopy: gastric xanthomas (elthat_120909180519): Stomach mucosal yellow lesions  UMLS: 1282522

**Comment by pnrobinson** [comment]
added as HP_0034468

**Comment by pnrobinson** [comment]
@MickeySegal -- with a few exceptions the HPO does not include the ascertainment method in the label or synonym, thus please note that this term will not be findable by comparing with "Endoscopy: gastric xanthomas"

**Comment by MickeySegal** [comment]
That is fine.  We often separate by ascertainment methods for the purpose of computing the usefulness of "bundles" such as the various possible findings on gastric endoscopy (versus the cost), but there is no reason you need to make that distinction.
