### ISSUE TITLE
NTR: Xanthomas of the upper aerodigestive tract (Lab: endoscopy and exploratory surgery)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8655]
New term request Xanthomas of the upper aerodigestive tract (f53):

**Comment by pnrobinson** [comment]
@MickeySegal
aerodigestive is not a specific anatomical designation but seems to describe what you would see with laryngoscopy? Could we make this more specific?

**Comment by pnrobinson** [comment]
I am not able to find a description of such an esophageal lesion in a patient with Niemann-Pick disease type C, and found only one other mention of a possibly roughly similar in another clinical context. GIven it would be hard to provide a good definition for this feature, I would suggest we hold off on creating a term because it would not be clear when the term pertains. If we come across a better description then we can create the term on the basis of that..

**Comment by MickeySegal** [comment]
This was just one patient, so I will delete this finding.
