### ISSUE TITLE
NTR: Endoscopy: small intestine webs, strictures, or diaphragms (Lab: endoscopy and exploratory surgery)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8659]
New term request Endoscopy: small intestine webs, strictures, or diaphragms (nadea3_190828155957):   UMLS: 3665988

**Comment by pnrobinson** [comment]
@MickeySegal
this term is too broad to be a good HPO term. There are several existing terms for specific parts of the small intestine that might fall under this. Could I ask you to open new terms for specific abnormalities if needed?

**Comment by MickeySegal** [comment]
I've changed our term to "small intestine strictures", treating the other terms as synonyms.  But I don't see any existing HPO term for that - I see terms for strictures of 7 other tubular parts of the anatomy.
