### ISSUE TITLE
NTR: Ultrasound: biliary sludging (Lab: ultrasound & echocardiogram)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8681]
New term request Ultrasound: biliary sludging (elthat_100624032336): Mixture of particulate solids that have precipitated from bile, e.g., cholesterol crystals, calcium bilirubinate pigment, and other calcium salts.  UMLS: 0941213

**Comment by pnrobinson** [comment]
@MickeySegal
does this refer to Gallbladder biliary sludging (https://pubmed.ncbi.nlm.nih.gov/11276386/) ?

**Comment by MickeySegal** [comment]
Yes.  I added the word gallbladder to our name for the term to make this more clear.

**Comment by pnrobinson** [comment]
@MickeySegal 
added as
Gallbladder biliary sludging 
HP:0034961
