### ISSUE TITLE
NTR: Uterus and fallopian tubes present  (Lab: ultrasound & echocardiogram)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8689]
New term request Uterus and fallopian tubes present  (elthat_130302190114):   UMLS: 1290605

**Comment by pnrobinson** [comment]
@MickeySegal -- please specify what this term is used for?

**Comment by MickeySegal** [comment]
Our terminology output made this confusing by eliminating the last two words in "Uterus and fallopian tubes present in male".

There may be other findings like this - I should have left "in male" and "in female" in the terminology output.

**Comment by pnrobinson** [comment]
@MickeySegal 

This is a complicated field with many phenotypes. Would the following term and definition be useful? Usually we try to avoid bundled terms (Uterus AND Fallopian tubes) although in this case it seems to be the commonest manifestation.

Presence of uterus in 46,XY individual
Definition: A developmental anomaly in which an individual with an X chromosome and a Y chromosome (usually 46,XY) has a uterus. The uterus and Fallopian tubes are derived from the Müllerian duct and thus this phenotype is generally also associated with the presence of Fallopian tubes.

**Comment by MickeySegal** [comment]
OK.

**Comment by pnrobinson** [comment]
@MickeySegal 
added as 
HP:0034546
