### ISSUE TITLE
ensure numerical synonyms present

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#869]
we have 10th, 11th, 12th -> enusure that there are the synonyms tenth, eleventh, twelfth

**Comment by drseb** [comment]
similar:

1st
1st-2nd
1st-3rd
1st-4th
1st-5th

2nd
2nd-3rd
2nd-4th
2nd-5th

3rd
3rd-4th
3rd-5th

4th
4th-5th

5th

**Comment by pnrobinson** [comment]
I have added this to the wiki!
