### ISSUE TITLE
NTR: Prenatal ultrasound: placental calcification (Lab: ultrasound & echocardiogram)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8695]
New term request Prenatal ultrasound: placental calcification (elthat_160507112637): Calcified  UMLS: 4760986

**Comment by pnrobinson** [comment]
@MickeySegal, this is Calcified placenta HP:0011415, adding synonym

**Comment by MickeySegal** [comment]
Thanks.
