### ISSUE TITLE
NTR: Prenatal ultrasound: echogenic intracardiac focus (Lab: ultrasound & echocardiogram)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8696]
New term request Prenatal ultrasound: echogenic intracardiac focus (elthat_160507131858):

**Comment by pnrobinson** [comment]
@MickeySegal, this is Echogenic intracardiac focus HP:0010942 (recently added!)

**Comment by MickeySegal** [comment]
Great.
