### ISSUE TITLE
spelling

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#870]
`AnnotationAssertion(Annotation(<http://purl.obolibrary.org/obo/hp.owl#layperson> "") Annotation(<http://www.geneontology.org/formats/oboInOwl#hasDbXref> "orcid.org/0000-0001-5208-3432") <http://www.geneontology.org/formats/oboInOwl#hasExactSynonym> <http://purl.obolibrary.org/obo/HP_0000141> "Abnormal absensce of menstruation")
`

**Comment by pnrobinson** [comment]
http://purl.obolibrary.org/obo/HP_0000141 "Abnormal absensce of menstruation")

absensce is misspelt, should be absence

**Comment by drseb** [comment]
@pnrobinson thats why there is this ticket
