### ISSUE TITLE
NTR: Voltage gated potassium channel antibodies in blood (Lab: serology & immunological tests)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8708]
New term request Voltage gated potassium channel antibodies in blood (segal_080910162246): VGKC; antibody  UMLS: 1627951

**Comment by pnrobinson** [comment]
@MickeySegal, is this the same as [Anti-P/Q-type VGCC antibody positivity HP:5000027](https://hpo.jax.org/app/browse/term/HP:5000027)?

**Comment by MickeySegal** [comment]
No, there are to potassium channels, not calcium channels.  It is more confusing in German where Kalium is used for potassium.

**Comment by pnrobinson** [comment]
OK!
Added as 
HP:4000171
Anti-voltage-gated potassium channel antibody positivity
def: The presence of autoantibodies (immunoglobulins) in the serum that react against a voltage-gated potassium channel.
COMMENT Voltage-gated potassium channels represent a family of transmembrane channels responsible for returning the depolarized cell to a resting state after each nerve impulse.

 PMID: 20816272
