### ISSUE TITLE
NTR: Flow cytometry: T-cell lymphocytes decreased (Lab: serology & immunological tests)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8711]
New term request Flow cytometry: T-cell lymphocytes decreased (segal_091013183917):

**Comment by pnrobinson** [comment]
@MickeySegal

this is probably this T lymphocytopenia HP:0005403
If you want to state that the proportion of T cells is reduced, maybe we need a new term. Right now there are terms for subtypes, https://hpo.jax.org/app/browse/term/HP:0025540

If so, please reopen

**Comment by MickeySegal** [comment]
This is fine.  It was just hard to find by searching.
