### ISSUE TITLE
NTR: Antiplatelet antibodies present (Lab: serology & immunological tests)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8713]
New term request Antiplatelet antibodies present (elthat_100424052024): Autoimmune thrombocytopenia included

**Comment by pnrobinson** [comment]
@MickeySegal, please specify the antigen -- could this be something like this? Anti-platelet derived growth factor receptor HP:0034091

**Comment by MickeySegal** [comment]
https://www.omim.org/entry/619846 doesn't specify an antigen.

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4792361/ lists Anti-platelet antibodies but doesn't give details.

**Comment by pnrobinson** [comment]
@MickeySegal 

Looking here, I think this refers to a heterogeneous group of antibodies that react to antigens on the surface of platelets (https://ashpublications.org/blood/article/132/Supplement%201/1137/262553/Antiplatelet-Antibody-Testing-in-Immune), including at least the platelet  glycoproteins GPIIb/IIIa, GPIb/IX, or GPIa/IIa.  
I have therefore made a term as follows:

HP:4000170
Antiplatelet antigen antibody positivity
Def: The presence of autoantibodies (immunoglobulins) in the serum that react against antigens present on the surface of thrombocytes such as the glycoproteins GPIIb/IIIa, GPIb/IX, and GPIa/IIa.
