### ISSUE TITLE
NTR: IgG response to immunization impaired in general (Lab: serology & immunological tests)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8716]
New term request IgG response to immunization impaired in general (elthat_100427192008): Immunoglobulins, antibodies

**Comment by pnrobinson** [comment]
@MickeySegal
I think this is this term
[Decreased specific antibody response to vaccination HP:0032140](https://hpo.jax.org/app/browse/term/HP:0032140)
?

**Comment by MickeySegal** [comment]
Good.  Thanks.

**Comment by pnrobinson** [comment]
thanks!
