### ISSUE TITLE
NTR: Flow cytometry: B-cell lymphocytes increased (Lab: serology & immunological tests)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8717]
New term request Flow cytometry: B-cell lymphocytes increased (elthat_100428044120):   UMLS: 4230422

**Comment by pnrobinson** [comment]
@MickeySegal

Is there any specific meaning to the flow cytometry? Otherwise this would be [Increased B cell count HP:0005404](https://hpo.jax.org/app/browse/term/HP:0005404)
?

**Comment by MickeySegal** [comment]
Flow cytometry is merely the method of measuring this.

**Comment by pnrobinson** [comment]
OK, so let's take [Increased B cell count HP:0005404](https://hpo.jax.org/app/browse/term/HP:0005404)!
