### ISSUE TITLE
NTR: BTK protein absent in monocytes by immunofluorescence or western blot (Lab: serology & immunological tests)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8719]
New term request BTK protein absent in monocytes by immunofluorescence or western blot (elthat_100502152922): Bruton's tyrosine kinase

**Comment by pnrobinson** [comment]
@MickeySegal
I see this in one of the aticles cited here, https://omim.org/entry/300755, but is this really a clinical assay or was this done specially for a few research publications? Seems like we would not see this in new data.

**Comment by MickeySegal** [comment]
https://www.ncbi.nlm.nih.gov/books/NBK1453/ no longer mentions doing the non-gene testing, so I'm deleting this.

**Comment by pnrobinson** [comment]
OK!
