### ISSUE TITLE
NTR: Thiamine uptake by fibroblasts impaired in vitro (Lab: serology & immunological tests)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8724]
New term request Thiamine uptake by fibroblasts impaired in vitro (elthat_100610021005):

**Comment by pnrobinson** [comment]
@MickeySegal
can you provide the disease context or a PMID describing the test in more detail?

**Comment by MickeySegal** [comment]
This is described at https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4916904/.  But it may be that today one only does SLC19A2 gene testing instead.
