### ISSUE TITLE
NTR: PiZZ type of alpha1 antitrypsin in blood (Lab: serology & immunological tests)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8726]
New term request PiZZ type of alpha1 antitrypsin in blood (elthat_100612184549): Protease inhibitor  UMLS: 0428498

**Comment by pnrobinson** [comment]
@MickeySegal
isn't this a genotype? I do not think this is in scope for the HPO?

**Comment by MickeySegal** [comment]
You are right.  That was old terminology, still used widely in the 2023 GeneReview article https://www.ncbi.nlm.nih.gov/books/NBK1519/ but it makes more sense to instead discuss zygosity of SERPINA1 variants.  I will delete our finding.

**Comment by pnrobinson** [comment]
closing
