### ISSUE TITLE
NTR: PiMZ type of alpha1 antitrypsin in blood (Lab: serology & immunological tests)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8727]
New term request PiMZ type of alpha1 antitrypsin in blood (elthat_100612193206): Protease inhibitor  UMLS: 0428501

**Comment by pnrobinson** [comment]
@MickeySegal
same question as https://github.com/obophenotype/human-phenotype-ontology/issues/8726

**Comment by MickeySegal** [comment]
You are right.  That was old terminology, still used widely in the 2023 GeneReview article https://www.ncbi.nlm.nih.gov/books/NBK1519/ but it makes more sense to instead discuss zygosity of SERPINA1 variants.  I will delete our finding.
