### ISSUE TITLE
spelling of "corpus collosum" and "hypoplasTic"

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#873]
`AnnotationAssertion(<http://www.geneontology.org/formats/oboInOwl#hasExactSynonym> <http://purl.obolibrary.org/obo/HP_0007370> "Agenesis/hypoplasic corpus collosum"^^xsd:string)
`

should probably be corpus callosum

**Comment by pnrobinson** [comment]
Two spelling errors
hypoplasTic 
corpus cAllosum

**Comment by drseb** [comment]
yap!
