### ISSUE TITLE
NTR: Japanese encephalitis antibody titer high in CSF or blood (Lab: serology & immunological tests)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8739]
New term request Japanese encephalitis antibody titer high in CSF or blood (samant_101227180540): Cerebrospinal fluid

**Comment by pnrobinson** [comment]
@MickeySegal

In principle, "high" could mean high acute or high chronic indicating past infection. 
However, maybe it is sufficient to have terms that would be

Japanese encephalitis antibody positivity, similar to terms like this  [Antinuclear antibody positivity HP:0003493](https://hpo.jax.org/app/browse/term/HP:0003493) ?

**Comment by MickeySegal** [comment]
That would be fine.

**Comment by pnrobinson** [comment]
@MickeySegal 

adding as
HP:0430062
Anti-Japanese encephalitis virus-specific antibody positivity
