### ISSUE TITLE
NTR: IgG kappa light chain low in blood (Lab: serology & immunological tests)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8751]
New term request IgG kappa light chain low in blood (elthat_130330041332): Immunoglobulin

**Comment by pnrobinson** [comment]
@MickeySegal

what is the context?
Will this "absent" term do?
Absent circulating immunoglobulin kappa chain HP:6000261

**Comment by MickeySegal** [comment]
https://www.omim.org/entry/614102
"Zegers et al. (1976) observed complete absence of immunoglobulin kappa chains in a male patient with cystic fibrosis (219700) in whom kappa chains were absent in serum immunoglobulins and in blood and bone marrow lymphocytes. Lymphocytes stimulated by pokeweed mitogen produced no kappa chains."

**Comment by pnrobinson** [comment]
It seems there are currently no clinical tests for absence of kappa chain, and given that this is one article from 1976 I am not sure that the phenotype was correctly measured back then and even so if it is a relevant test in 2024?

**Comment by pnrobinson** [comment]
thanks for this -- I was not able to find anything

**Comment by pnrobinson** [comment]
@MickeySegal 
Looking back at this, the cited webpage is only showing INCREASED IgG kappa. I do not think the "low" version is a current clinical test. If we can find a newer article, let's reconsider!

**Comment by MickeySegal** [comment]
https://medlineplus.gov/lab-tests/free-light-chains/
"What is a free light chains test?

There are two types of light chains: lambda and kappa light chains. You will usually have some of each in your blood. A free light chains test measures the amount of lambda and kappa free light chains in your blood.

If the amount of free light chains is higher or lower than normal, it may be a sign of a disorder of the plasma cells."
