### ISSUE TITLE
NTR: Flow cytometry: CD19 lymphocytes high (Lab: serology & immunological tests)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8754]
New term request Flow cytometry: CD19 lymphocytes high (elthat_130315203340):   UMLS: 1536260

**Comment by pnrobinson** [comment]
@MickeySegal
this is a marker of B cells and is this a synonym of [Increased B cell count HP:0005404](https://hpo.jax.org/app/browse/term/HP:0005404)? If not please provide context.

**Comment by MickeySegal** [comment]
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5865455/#:~:text=Summary%20of%20CD19%20and%20CD20,CD20%20expression%20has%20been%20lost. "CD19 expression is observed on earlier-stage B cells than is CD20. In addition, CD19 expression is found to persist on late-stage antibody-secreting B cells (plasmablasts and plasma cells) after CD20 expression has been lost."

So although https://www.omim.org/clinicalSynopsis/610798 refers to "Increased total number of CD19+ B cells" it may be OK to use https://hpo.jax.org/app/browse/term/HP:0005404

**Comment by pnrobinson** [comment]
@MickeySegal 
Let's leave this for now. We are going to have a workshop with immunologists for topics like this and will revise a lot of this subhierarchy.
