### ISSUE TITLE
NTR: HLA-B51 antigen in blood (Lab: serology & immunological tests)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8755]
New term request HLA-B51 antigen in blood (elthat_150817025909): Human leukocyte antigen

**Comment by pnrobinson** [comment]
@MickeySegal
in the HPO system, this would be handled as a genotype rather than a phenotype.

**Comment by MickeySegal** [comment]
The test is PCR for an antigen: https://testdirectory.questdiagnostics.com/test/test-detail/16775/hla-b51-behcets-disease-association-test?cc=MASTER
