### ISSUE TITLE
NTR: MPO (myeloperoxidase) antigen positive (Lab: serology & immunological tests)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8789]
New term request MPO (myeloperoxidase) antigen positive (segal_210427184345): Corresponds to P-ANCA; antineutrophil cytoplasmic antigen

**Comment by pnrobinson** [comment]
@MickeySegal
not sure I understand the P-ANCA comment.
This does not seem synonymous with [Perinuclear antineutrophil antibody positivity HP:0032229](https://hpo.jax.org/app/browse/term/HP:0032229)?

**Comment by MickeySegal** [comment]
I can't find support for the P-ANCA part.  This seems like its own type of ANCA:
https://www.ncbi.nlm.nih.gov/books/NBK531484/ "... result in the production of MPO-ANCA. In the second step, these MPO-ANCA cause damage to the host vasculature by reacting and crosslinking neutrophils to the endothelial receptors"

**Comment by pnrobinson** [comment]
@MickeySegal 
the term was already ther
Anti-myeloperoxidase antibody positivity HP:0033559
I will add MPO (myeloperoxidase) antigen positive  as a synonym
