### ISSUE TITLE
NTR: Hydroxyoctanoylglycine high in urine (Lab: urine tests)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8804]
New term request Hydroxyoctanoylglycine high in urine (segal_030514192838):

**Comment by pnrobinson** [comment]
@MickeySegal
is this https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:142691
what is the disease context?

**Comment by MickeySegal** [comment]
It was in "Medium chain acyl CoA dehydrogenase deficiency" but not mentioned in https://www.ncbi.nlm.nih.gov/books/NBK1424/; I had found it in "Scriver CR Physician's Guide to the Laboratory Diagnosis of Metabolic Diseases".  

It is also mentioned in http://www.msac.gov.au/internet/msac/publishing.nsf/Content/3F228B5A86A7FA3ACA25801000123B43/$File/1114-Assessment-Report.pdf but it is a judgment call as to whether it is important clinically if not mentioned in the GeneReview.

**Comment by pnrobinson** [comment]
I do not think this is used as a clinical test. It appears to have been investigated a few times for research purposes only. Let's hold off on the term.
