### ISSUE TITLE
NTR: D-inosine high in urine (Lab: urine tests)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8805]
New term request D-inosine high in urine (segal_030514193407):

**Comment by pnrobinson** [comment]
@MickeySegal
can we differentiate this from the (new) inosine high in urine term? Is the 'D' clinically relevant?

**Comment by MickeySegal** [comment]
This was in "Purine nucleoside phosphorylase deficiency", and from "Scriver CR Physician's Guide to the Laboratory Diagnosis of Metabolic Diseases" both findings  were created minutes apart, suggesting there is a difference.  But https://omim.org/entry/613179 doesn't mention it so I've deleted this finding.

**Comment by pnrobinson** [comment]
ok, closing
