### ISSUE TITLE
NTR: D-guanosine high in urine (Lab: urine tests)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8807]
New term request D-guanosine high in urine (segal_030514193450):

**Comment by pnrobinson** [comment]
@MickeySegal
I am not sure if the "D-" is superfluous:
https://www.ebi.ac.uk/ols4/ontologies/chebi/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCHEBI_16750
There is a current class
[Decreased urinary guanosine level HP:0033160](https://hpo.jax.org/app/browse/term/HP:0033160)
and I think it may be appropriate to drop the D for consistency, or am I missing something? What is the disease context?

**Comment by MickeySegal** [comment]
We use it for https://omim.org/entry/613179 and had gotten the chiral term from the "Scriver CR Physician's Guide to the Laboratory Diagnosis of Metabolic Diseases" book, but OMIM omits the chirality so OK to do that in creating the opposite of https://hpo.jax.org/app/browse/term/HP:0033160

**Comment by pnrobinson** [comment]
@MickeySegal 

HP:0040424
Elevated urinary guanosine level
