### ISSUE TITLE
NTR: Succinyl-aminoimidazole-carboxamide riboside high in urine (Lab: urine tests)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8821]
New term request Succinyl-aminoimidazole-carboxamide riboside high in urine (segal_080311211635): SAICAr  UMLS: 2676171

**Comment by pnrobinson** [comment]
@MickeySegal
I am not sure I can find this
Here (https://omim.org/entry/103050), I see
 - Increased succinylaminoimidazole carboxamide ribotide (SAICAr)  -- but this is ribotide rather than riboside.
 Can you provide context?

**Comment by MickeySegal** [comment]
Also using https://omim.org/entry/103050.  it says ribotide twice and riboside twice.  The Clinical Synopsis says ribotide.

https://rarediseases.org/rare-diseases/adenylosuccinate-lyase-deficiency/ (hit full button) says "When adenylosuccinate lyase is not functioning well, succinylaminoimidazole carbozamide ribotide gets converted into succinylaminoimidazole carbozamide riboside.... Therefore, in individuals in whom adenylosuccinate lyase is not functioning well, doctors can detect two compounds in body fluids that are normally undetectable: aminoimidazole carbozamide riboside and succinyladenosine. "

So it seems like roboside is the best choice.

**Comment by pnrobinson** [comment]
@MickeySegal 
[Elevated urinary succinylaminoimidazole carboxamide riboside level HP:6000390](https://hpo.jax.org/browse/term/HP:6000390)
