### ISSUE TITLE
NTR: Hypoxanthine in urine undetectable (Lab: urine tests)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8826]
New term request Hypoxanthine in urine undetectable (mayman_090512173331):

**Comment by pnrobinson** [comment]
@MickeySegal
is it important to have "undetectable" as opposed to just "reduced"?
What is the context?

**Comment by MickeySegal** [comment]
https://www.ncbi.nlm.nih.gov/books/NBK2591/ now says "Absent/low hypoxanthine concentration", so reduced is fine and we will change our description as well.

**Comment by pnrobinson** [comment]
@MickeySegal 
added as
Decreased urinary hypoxanthine level
HP:0040426
