### ISSUE TITLE
NTR: Metachromatic material in urine sediment (Lab: urine tests)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8842]
New term request Metachromatic material in urine sediment (segal_110421154414):

**Comment by pnrobinson** [comment]
@MickeySegal
Is this Metachromatic leukodystrophy?
Is this urine test still in clinical use, I cannot find anything modern?

**Comment by MickeySegal** [comment]
We have this from an old source and there is no mention in GeneReviews or OMIM so I deleted our finding.

**Comment by pnrobinson** [comment]
OK!
