### ISSUE TITLE
NTR: Imidazolepyruvic acid high in urine (Lab: urine tests)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8845]
New term request Imidazolepyruvic acid high in urine (elthat_111113034741):

**Comment by pnrobinson** [comment]
@MickeySegal
is this is from https://omim.org/entry/235800, then it appears that this metabolite is not (or not for a long time) clinically measured. If this is another disease, please provide context.

**Comment by pnrobinson** [comment]
@MickeySegal
I found some of the these compounds here, however, they do not appear to be in current clinical use and there would be much easier ways of measuring vitamin B12 and folic acid.
https://pubmed.ncbi.nlm.nih.gov/4645251/
? If there is a current clinical use, please post it, otherwise let's omit this.

**Comment by MickeySegal** [comment]
I only find references from the 1960s.  Deleting.

**Comment by pnrobinson** [comment]
OK!
