### ISSUE TITLE
NTR: Imidazoleacetic acid high in urine (Lab: urine tests)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8847]
New term request Imidazoleacetic acid high in urine (elthat_111113034857):

**Comment by pnrobinson** [comment]
@MickeySegal
I found some of the these compounds here, however, they do not appear to be in current clinical use and there would be much easier ways of measuring vitamin B12 and folic acid.
https://pubmed.ncbi.nlm.nih.gov/4645251/
? If there is a current clinical use, please post it, otherwise let's omit this.

**Comment by MickeySegal** [comment]
OK.  Deleting.

**Comment by pnrobinson** [comment]
OK
