### ISSUE TITLE
poor visual behavior for age

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#887]
- "poor visual behavior for age" (subclass of HP:0000551 "Abnormality of vision"). This would be a very useful term especially for paediatric ophthalmologists as this is many times the presenting symptom.

Term request 
Panagiotis Sergouniotis

**Comment by psergouniotis** [comment]
Please consider adding "abnormal visual behavior for age" (synonym  "poor visual behavior for age") as a subclass of HP:0000551 "Abnormality of vision"

**Comment by pnrobinson** [comment]
In terms of the definition, one possibility could be:
"abnormal visual behavior for age" (synonyms "poor visual behavior for age", "abnormal visual behaviour for age", "poor visual behaviour for age"):
lack of visual responsiveness or decrease in visual capabilities that might suggest abnormal visual development/function; typically refers to an infant or young child in which visual behavior does not meet normal developmental milestones.

This definition contains elements from Chapter 4 (, pages 23-29, "Pediatric Ophthalmology and Strabismus" 4th edition (editors CS Hoyt & D Taylor), Elsevier 2013.

**Comment by psergouniotis** [comment]
I think that the term "abnormal visual behavior for age" would be very useful for pediatric ophthalmologists and please consider adding it to the next HPO release.

**Comment by pnrobinson** [comment]
I have added this term as HP_0025152 with 
def:Lack of visual responsiveness or decrease in visual capabilities suggesting a lack of visual responsiveness or decrease in visual capabilities in an infant or young child in which visual behvior fails to meet normal developmental milestones.

comment: A failure to meet age-related milestones in areas such as (i) focusing ability, (ii) eye coordinationg and tracking of objects in the visual field, (iii) depth perception, (iv) color perception, and (v) object and face recognition. These milestones are generally met in the first three months of life, and failure to meet them may indicate abnormal visual development or function.

**Comment by psergouniotis** [comment]
I was just checking HPO workbench. It seems that currently the primary term is "poor visual behavior for age" (synonym "abnormal visual behavior for age"). Would it be possible to make "abnormal visual behavior for age" as the primary term?
