### ISSUE TITLE
NTR: Teeth X-ray: dental pulp chamber calcification nodules (Lab: radiology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8878]
New term request Teeth X-ray: dental pulp chamber calcification nodules (elthat_150821033948):

**Comment by pnrobinson** [comment]
@MickeySegal
Probably this
[Pulp calcification HP:0003771](https://hpo.jax.org/app/browse/term/HP:0003771)
If more detail is needed, please provide definitions/examples/context

**Comment by MickeySegal** [comment]
This is fine.  One of the UMLS entries linked to the HPO code discusses stones, which seem like calcified nodules.
