### ISSUE TITLE
NTR: MRI: T2 hyperintensities in cortex (Lab: radiology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8880]
New term request MRI: T2 hyperintensities in cortex (segal_020822193220): Unidentified Bright Objects (UBOs); increased signals; hyperintensity  UMLS: 4538857

**Comment by pnrobinson** [comment]
@MickeySegal
This is a slightly more general term
Focal hyperintensity of cerebral white matter on MRI HP:0040328
I am assuming you are refering to the UBOs in NF1?
The existing term has been used for this disease: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6606986/
I am wondering if want to get more specific and how to craft the definition, thoughts?

**Comment by MickeySegal** [comment]
We have this for NF! and 16 other diseases, but HP:0040328 seems fine.

**Comment by pnrobinson** [comment]
OK, will close for now!
