### ISSUE TITLE
NTR: X-ray: dural calcifications (Lab: radiology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8881]
New term request X-ray: dural calcifications (segal_030521175109): Falx, tentorium included  UMLS: 5393946

**Comment by pnrobinson** [comment]
@MickeySegal

given that this can sometimes be normal, should we provide more context?
see https://link.springer.com/chapter/10.1007/978-3-319-39790-0_17

**Comment by MickeySegal** [comment]
Examples:
https://www.ncbi.nlm.nih.gov/books/NBK1151/ "Ectopic calcification, particularly in the falx"

https://www.omim.org/clinicalSynopsis/603671 "Calcification of the falx"

**Comment by pnrobinson** [comment]
@MickeySegal 
perhaps this term is sufficient? [Calcification of falx cerebri HP:0005462](https://hpo.jax.org/app/browse/term/HP:0005462)

**Comment by MickeySegal** [comment]
OK

**Comment by pnrobinson** [comment]
thanks, closing
