### ISSUE TITLE
NTR: Skull X ray or CT: craniolacunia (Lab: radiology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8883]
New term request Skull X ray or CT: craniolacunia (segal_040518164752): Luckenschadel; Luckenschadel; scalloping of the inner table; lacunar skull; craniofenestria  UMLS: 0265537

**Comment by pnrobinson** [comment]
@MickeySegal

is this a bony skull defect? Please provide context.

**Comment by MickeySegal** [comment]
The original source was the Smith malformation textbook, which I don't have accessible today, but https://omim.org/clinicalSynopsis/208500 calls this "lacunar skull" so I took that out of our synonyms and used it in the place of craniolacunia.

**Comment by pnrobinson** [comment]
I am not able to find much information about this feature, but I suspect it is another way of saying

[Calvarial skull defect HP:0001362
](https://hpo.jax.org/app/browse/term/HP:0001362)

For now I would suggest we not make a new term unless we can find a PMID with a Figure and a good definition that differentiates "Craniolacuna"

**Comment by MickeySegal** [comment]
It is multiple lesions:

https://jamanetwork.com/journals/jamapediatrics/article-abstract/1177417 "Lacunar skull is an anomaly of the skull of the new-born usually associated with spina bifida and meningocele and occasionally with encephalocele. It is characterized by defects on the inner vault in the form of shallow depressions or deep cavitations extending to the outer surface, which vary in size, shape and number. "

http://learningradiology.com/archives2012/COW%20496-Lacunar%20skull/lacunarcorrect.html "Lacunar Skull Luckenschadel Skull ... Bone dysplasia of skull consisting of multiple oval lucencies separated by dense, bony ridges"

https://pubs.rsna.org/doi/10.1148/36.2.147 "CRANIOLACUNIA, a condition known in the literature as “lacunar skull” and “Lückenschädel,” has attracted the interest of several European authors. In the American literature, attention was called to this condition by Kerr (2) and by Doub and Danzer (1), who summarized and discussed the previous literature in addition to reporting their own observations. Except for these papers, only occasional mention has been made of this finding.  
The roentgenologic appearance in a typical case of craniolacunia is that of an arborizing pattern of bony ridges which sharply delineate and separate rounded defects one from another (Figs. 1-A and 1-B). In the pathologic specimen, these defects may be completely devoid of bony structure, in which case they are bridged by membranous diaphragms of periosteum and dura. Some of the defects may have an additional covering of bone which corresponds to the outer table of the skull, the inner table being incomplete (Fig. 2). There is considerable variation in the degree of involvement, even among lesions in the same skull."
