### ISSUE TITLE
NTR: MR Spectroscopy: polyols high in brain (Lab: radiology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8887]
New term request MR Spectroscopy: polyols high in brain (segal_071003145702): MRS; ribotol, D-arabitol

**Comment by pnrobinson** [comment]
@MickeySegal
-- are all polyols measure simultaneously or is there one measure each for compounds such as ribotol and D-arabitol

**Comment by MickeySegal** [comment]
https://omim.org/entry/608611 "Proton magnetic resonance spectroscopy of the brain showed highly elevated abnormal peaks that were identified as representing pentitols ribitol and arabitol."

**Comment by pnrobinson** [comment]
@MickeySegal 
added as

Elevated brain polyol compounds by MRS
HP:0034894
