### ISSUE TITLE
New cardiovascular term requests

### ISSUE THREAD

**Issue by tudorgroza** [obophenotype/human-phenotype-ontology#890]
* Shortness of breath
* Elevated jugular venous pressure
* Elevated heart rate
* Low pulse pressure

Thank you!

**Comment by drseb** [comment]
>  * Shortness of breath

we have Dyspnea which already has the synonym "Shortness of breath"

**Comment by drseb** [comment]
> * Elevated jugular venous pressure

@pnrobinson we have *Abnormality of jugular vein* with subclasses *Abnormality of internal jugular vein* and *Abnormality of external jugular vein* . would be nice add increase and decrease of pressure. can you add?

**Comment by drseb** [comment]
> *Elevated heart rate

we already have HP:0001649	*Tachycardia* with synonym *Elevated heart rate*

**Comment by drseb** [comment]
> * Low pulse pressure

@pnrobinson we have several blood pressure classes for systolic/diastolic, but no pulse pressure. can you add?

**Comment by tudorgroza** [comment]
@drseb - Right ... apologies for the confusion - they're indeed both there, but as related synonyms, not exact.

**Comment by pnrobinson** [comment]
Added terms for pusle pressure and jugular venous pressure
