### ISSUE TITLE
NTR: Abdominal imaging: abdominal wall mass (Lab: radiology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8902]
New term request Abdominal imaging: abdominal wall mass (elthat_100321030932): CT or MRI  UMLS: 1328363

**Comment by pnrobinson** [comment]
@MickeySegal

HP:6000171
Abdominal wall mass

**Comment by MickeySegal** [comment]
We dealt with this in https://github.com/obophenotype/human-phenotype-ontology/issues/7875
