### ISSUE TITLE
Addictive behaviour

### ISSUE THREAD

**Issue by asmunduhreinn** [obophenotype/human-phenotype-ontology#891]
I would like to request a new terms for describing addictive behaviour.
Behavioural abnormality (HP:0000708) is currently the best matching term which is to broad.

**Comment by pnrobinson** [comment]
Added this term with definition
A recurrent pattern of behavior that is characeterized by the failure to resist an impulse, drive, or temptation to perform an act that is harmful to the person or to others. The repetitive engagement in these behaviors ultimately interferes with functioning in other domains.

**Comment by asmunduhreinn** [comment]
Thank you very much.
