### ISSUE TITLE
NTR: Modifier: MRI: parieto-occipital predominance to brain imaging abnormality (Lab: radiology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8914]
New term request Modifier: MRI: parieto-occipital predominance to brain imaging abnormality (forsyt_100615084614): Dysmyelination; white matter  UMLS: 5418622

**Comment by pnrobinson** [comment]
@MickeySegal
since this is bundled it seemed better to have two terms

[@MickeySegal](https://github.com/MickeySegal)
HP:0430131

Parietal cortex localization
Localization to or predominance in the parietal cortex of the brain.


[@MickeySegal](https://github.com/MickeySegal)
HP:0430131

Occipital cortex localization
Localization to or predominance in the occipital cortex of the brain.

**Comment by MickeySegal** [comment]
Two terms is fine, but they need different HPO code numbers.
