### ISSUE TITLE
photopic ERG

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#892]
Is this the same as bright flash ERG? Add synonym if so. See  http://www.ncbi.nlm.nih.gov/pubmed/26029869, 5/6 patients have non-detectable photopic ERG

**Comment by psergouniotis** [comment]
* "non-detectable photopic ERG" is a synonym of "Undetectable light-adapted electroretinogram [HP:0030465]". 
* bright flash ERG is vague and should not be a term. It is typically used to describe the dark-adapted 10 ERG (http://link.springer.com/article/10.1007/s10633-014-9473-7)

**Comment by psergouniotis** [comment]
* "non-detectable photopic ERG" is a synonym of "Undetectable light-adapted electroretinogram [HP:0030465]". 
* bright flash ERG is vague and should not be a term. It is typically used to describe the dark-adapted 10 ERG (http://link.springer.com/article/10.1007/s10633-014-9473-7)

**Comment by pnrobinson** [comment]
I add this as a synonym and also added a definition. Givent that bright flash is not a good description, let us skip adding the annotations for now.
