### ISSUE TITLE
NTR: OCT: intraretinal splitting (Lab: radiology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8927]
New term request OCT: intraretinal splitting (elthat_100829122833): Optical coherence tomography; laminated  UMLS: 1839361

**Comment by MickeySegal** [comment]
It is the same pathology, but assessed using a lab test instead of an ophthalmoscope.  You may prefer the same code for both, but we will use separate findings.
