### ISSUE TITLE
NTR: Doppler ultrasound: vascular blood flow slow (Lab: radiology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8930]
New term request Doppler ultrasound: vascular blood flow slow (elthat_100911171848):

**Comment by pnrobinson** [comment]
@MickeySegal
this seems too general. What is the disease context and what vessel(s) is/are affected?

**Comment by MickeySegal** [comment]
https://www.ncbi.nlm.nih.gov/books/NBK1967/ "TEK-related venous malformations (VM) include slow-flow venous lesions that appear as light-to-dark skin discoloration overlying a soft compressible mass and develop primarily in cutaneous, subcutaneous, or mucosal tissues"

https://www.ncbi.nlm.nih.gov/books/NBK541085/ "Venous malformations are slow-flow lesions, making them prone to thrombosis"

But we also used this for https://www.ncbi.nlm.nih.gov/books/NBK559189/ "This entrapment syndrome restricts flow through the left renal vein, resulting in venous congestion and a host of symptoms"

It seems like we need to separate the skin venous malformations and the renal artery constriction.

**Comment by pnrobinson** [comment]
I think this is a description of a [Venous malformation HP:0012721](https://hpo.jax.org/app/browse/term/HP:0012721), but not actually a separate phenotype. So I think this term is probably what we want. We could add new terms for VMs in specific locations is needed.
