### ISSUE TITLE
NTR: Modifier: MRI: corpus callosum nature to white matter abnormality (Lab: radiology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8943]
New term request Modifier: MRI: corpus callosum nature to white matter abnormality (segal_110120155755): Dysmyelination  UMLS: 5232622

**Comment by pnrobinson** [comment]
@MickeySegal

I think this concept is probably too complicated to be easily expressible as an HPO term. Is there some way of describing it so that it is not bundled?

**Comment by MickeySegal** [comment]
How about https://www.ncbi.nlm.nih.gov/medgen/C5232622 "White matter abnormalities in the corpus callosum"

**Comment by pnrobinson** [comment]
@MickeySegal 

The corpus callosum is white matter, and I am not familiar with a part of the CC that is not white matter and that differentiates between different types of lesion, so I would say that "corpus callosum nature to white matter abnormality" is very close to [Abnormal corpus callosum morphology HP:0001273](https://hpo.jax.org/app/browse/term/HP:0001273). I am not sure the HPO is the right tool to modify whatever delta there may be between the two concepts, or if it is clinically important. Unless there is a strong need, I would suggest we not make a term for this. Thoughts?

**Comment by MickeySegal** [comment]
This is not for thin or thick corpus callosum, this is primarily for corpus callosum dysmyelination, so a term of that type would be good.

**Comment by pnrobinson** [comment]
Well if the literature is vague, then we can take the "vague" HPO term [Abnormal corpus callosum morphology HP:0001273](https://hpo.jax.org/app/browse/term/HP:0001273). We will not gain anything by adding another vague term!
