### ISSUE TITLE
NTR: CT or MRI: liver lobation abnormal (Lab: radiology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8947]
New term request CT or MRI: liver lobation abnormal (elthat_110128023404):   UMLS: 0685814

**Comment by pnrobinson** [comment]
@MickeySegal
I think this is a synonym for [Abnormal liver lobulation HP:0100752](https://hpo.jax.org/app/browse/term/HP:0031065) ?

**Comment by MickeySegal** [comment]
Thanks.  I appeared to have been tripped up by searching for lobation instead of lobulation.  I switched to lobulation in the name and lobation in the explanatory terms based on lobulation winning in Google results 260,000 to 55,600.

**Comment by pnrobinson** [comment]
added "Liver lobation abnormal" as synonym
