### ISSUE TITLE
NTR: MRI: bone marrow infiltration (Lab: radiology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8953]
New term request MRI: bone marrow infiltration (elthat_110211020742):   UMLS: 3854434

**Comment by pnrobinson** [comment]
@MickeySegal

Not sure this is a good HPO term since there are many kinds of infiltration but can you provide more context?

**Comment by MickeySegal** [comment]
https://www.ncbi.nlm.nih.gov/books/NBK1269/ "Conventional radiographs (x-rays) may reveal undertubulation (Erlenmeyer flask configuration) noted in the distal femur and endosteal scalloping as a sign of bone marrow infiltration.  T1-weighted MRI is the most sensitive method for following bone marrow infiltration"

**Comment by pnrobinson** [comment]
That article states:
Conventional radiographs may reveal undertubulation (Erlenmeyer flask configuration) in the distal femur and endosteal scalloping as a sign of bone marrow infiltration. 
so I would propose let's not create a new term.
