### ISSUE TITLE
Consider Raynaud’s phenomenon as a phenotype class or broad synonym

### ISSUE THREAD

**Issue by mellybelly** [obophenotype/human-phenotype-ontology#896]
For example, see:
http://www.niams.nih.gov/health_info/raynauds_phenomenon/raynauds_ff.asp

Term used to describe a phenotype in case of Polyarteritis Nodosa in this manuscript:
http://www.nejm.org/doi/full/10.1056/NEJMoa1307362
and is listed in the OMIM clinical synopsis for this disease: http://omim.org/clinicalSynopsis/615688

Not in HPO, though could also be construed as a compound set of phenotypes: 
over-constriction in response to cold by small blood vessels
digit numbness
digit discoloration
etc.

Note that we also have the disease 'Raynaud disease':
https://beta.monarchinitiative.org/disease/OMIM%3A179600
which has very many phenotypes and three genes currently associated.

However in the case of Polyarteritis Nodosa caused by mutation in CECR1, patients are described as having Raynaud's phenomenon, but this is not Raunaud disease as described above.

**Comment by pnrobinson** [comment]
Note HPO does have term Raynaud phenomenon (no possessive form, which is possibly why you did not find it). Currentlu, there is an exact synonym of Raynaud disease. I will make the latter a related synonsym and then add the possessive form as an exact synonym.
