### ISSUE TITLE
NTR: Modifier: radiolucent character to renal stones (Lab: radiology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8965]
New term request Modifier: radiolucent character to renal stones (segal_120706192401):   UMLS: 0582428

**Comment by pnrobinson** [comment]
@MickeySegal

given that current techniques can go much further than just lucency or not, e.g. https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5443345/, I wonder if this modifier is relevant for modern diagnostics? For instance, "Uric acid stones are typically 200–400 HU, whereas calcium oxalate stones are ~600–1,200 HU". I realize there may be an earlier part of the workup where less is known, but would clinical decisions typically be made on the basis of this (I do not know)

**Comment by MickeySegal** [comment]
The radiolucent term seems to be in current use:
https://www.ncbi.nlm.nih.gov/books/NBK100238/
"Radiolucent kidney stones, detected by ultrasound or computed tomography (CT). Stones are not seen on a plain abdominal x-ray."

**Comment by pnrobinson** [comment]
I am adding a section called Radiographic modifier

Under this, I added the following

Radiolucent
HP:0025789
def: Applies to a lesion that allow x-rays to penetrate through them and expose the receptor (radiolucency). Soft tissues appear black or dark on the processed radiograph and are called radiolucent.
