### ISSUE TITLE
Proposing abbreviation expansion

### ISSUE THREAD

**Issue by skocbek** [obophenotype/human-phenotype-ontology#897]
Hi, 

Using April 2016 hp.obo, I have found several term names and synonyms that contain abbreviations inside brackets. The brackets and abbreviations present an issue for text mining and NLP processing of these strings, so I propose to replace the strings containing abbreviations with two strings: a) a string without the abbreviation, and b) a string with the abbreviation. Below is a list of such terms with term id, an original string (either name or synonym), and recommended alternatives.

HP:0000654
Original: Decreased electroretinogram (ERG) amplitude
Alternative 1: Decreased electroretinogram amplitude
Alternative 2: Decreased ERG amplitude

HP:0011790
Original: Activating thyroid-stimulating hormone receptor (TSHR) defect
Alternative 1: Activating thyroid-stimulating hormone receptor defect
Alternative 2: Activating TSHR defect

HP:0003138
Original: Increased blood urea nitrogen (BUN)
Alternative 1: Increased blood urea nitrogen
Alternative 2: Increased BUN

HP:0000590
Original: External ophthalmoplegia, progressive (PEO)
Alternative 1: External ophthalmoplegia, progressive
Alternative 2: External PEO

HP:0003164
Original: Hypothalamic gonadotropin-releasing hormone (GNRH) deficiency
Alternative 1: Hypothalamic gonadotropin-releasing hormone deficiency
Alternative 2: Hypothalamic GNRH deficiency

HP:0011737
Original: Corticotropin-releasing hormone (CRH) deficient adrenal insufficiency
Alternative 1: Corticotropin-releasing hormone deficient adrenal insufficiency
Alternative 2: CRH deficient adrenal insufficiency

HP:0003402
Original: Decreased miniature endplate potentials (MEPP)
Alternative 1: Decreased miniature endplate potentials
Alternative 2: Decreased MEPP

HP:0000512
Original: Flattened or absent electroretinogram (ERG)
Alternative 1: Flattened or absent electroretinogram
Alternative 2: Flattened or absent ERG

HP:0003436
Original: Prolonged miniature endplate potentials (MEPP)
Alternative 1: Prolonged miniature endplate potentials
Alternative 2: Prolonged MEPP

HP:0011789
Original: Thyroid-stimulating hormone receptor (TSHR) defect
Alternative 1: Thyroid-stimulating hormone receptor defect
Alternative 2: TSHR defect

HP:0011791
Original: Inactivating thyroid-stimulating hormone receptor (TSHR) defect
Alternative 1: Inactivating thyroid-stimulating hormone receptor defect
Alternative 2: Inactivating TSHR defect

HP:0003760
Original: Percussion-induced rapid rolling muscle contractions (PIRC)
Alternative 1: Percussion-induced rapid rolling muscle contractions
Alternative 2: PIRC

HP:0000512
Original: Abnormal electroretinogram (ERG)
Alternative 1: Abnormal electroretinogram
Alternative 2: Abnormal ERG

HP:0011735
Original: Adrenocorticotropin (ACTH) deficient adrenal insufficiency
Alternative 1: Adrenocorticotropin deficient adrenal insufficiency
Alternative 2: ACTH deficient adrenal insufficiency

HP:0003785
Original: Decreased CSF homovanillic acid (HVA)
Alternative 1: Decreased CSF homovanillic acid
Alternative 2: Decreased CSF HVA

HP:0003431
Original: Decreased motor nerve conduction velocity (NCV)
Alternative 1: Decreased motor nerve conduction velocity
Alternative 2: Decreased motor NCV

HP:0003431
Original: Decreased motor nerve conduction velocities (NCV)
Alternative 1: Decreased motor nerve conduction velocities
Alternative 2: Decreased motor NCV

HP:0007984
Original: Reduced rod b-wave (ERG)
Alternative 1: Reduced rod b-wave
Alternative 2: Reduced rod ERG

HP:0003657
Original: Granular osmiophilic deposits (GROD) in cells
Alternative 1: Granular osmiophilic deposits in cells
Alternative 2: GROD in cells

HP:0008259
Original: Adrenocorticotropin (ACTH) receptor (ACTHR) defect
Alternative 1: Adrenocorticotropin receptor defect
Alternative 2: ACTH receptor defect
Alternative 3: ACTHR defect

HP:0001511
Original: Intrauterine growth retardation (IUGR)
Alternative 1: Intrauterine growth retardation
Alternative 2: IUGR

HP:0001491
Original: Congenital fibrosis of extraocular muscles (CFEOM)
Alternative 1: Congenital fibrosis of extraocular muscles
Alternative 2: CFEOM

HP:0005978
Original: Noninsulin dependent diabetes mellitus (NIDDM)
Alternative 1: Noninsulin dependent diabetes mellitus
Alternative 2: NIDDM

HP:0000654
Original: Reduced electroretinogram (ERG)
Alternative 1: Reduced electroretinogram
Alternative 2: Reduced ERG

HP:0001312
Original: Giant somatosensory evoked potentials (SEPS)
Alternative 1: Giant somatosensory evoked potentials
Alternative 2: Giant SEPS

HP:0003448
Original: Decreased sensory nerve conduction velocities (NCV)
Alternative 1: Decreased sensory nerve conduction velocities
Alternative 2: Decreased sensory NCV

HP:0011738
Original: Corticotropin-releasing hormone receptor (CRHR) defect
Alternative 1: Corticotropin-releasing hormone receptor defect
Alternative 2: CRHR defect

HP:0011945
Original: Bronchiolitis obliterans organizing pneumonia (BOOP)
Alternative 1: Bronchiolitis obliterans organizing pneumonia
Alternative 2: BOOP

HP:0007385
Original: aplasia cutis congenita (ACC)
Alternative 1: aplasia cutis congenita
Alternative 2: ACC

HP:0007984
Original: Reduced amplitude of b-wave (ERG)
Alternative 1: Reduced amplitude of b-wave
Alternative 2: Reduced amplitude of ERG

HP:0002494
Original: Abnormal rapid eye movement (REM) sleep
Alternative 1: Abnormal rapid eye movement sleep
Alternative 2: Abnormal REM sleep

HP:0003236
Original: Increased creatine phosphokinase (CPK)
Alternative 1: Increased creatine phosphokinase
Alternative 2: Increased CPK

HP:0003288
Original: Mitochondrial propionyl-CoA carboxylase (PCC) defect
Alternative 1: Mitochondrial propionyl-CoA carboxylase defect
Alternative 2: Mitochondrial PCC defect

HP:0006548
Original: Pulmonary arteriovenous malformation (PAVM), especially lower lobes
Alternative 1: Pulmonary arteriovenous malformation, especially lower lobes
Alternative 2: PAVM, especially lower lobes

HP:0003240
Original: Increased phosphoribosylpyrophosphate (PRPP) synthetase
Alternative 1: Increased phosphoribosylpyrophosphate synthetase
Alternative 2: Increased PRPP synthetase

HP:0001631
Original: Atrial septal defect (ASD)
Alternative 1: Atrial septal defect
Alternative 2: ASD

HP:0007688
Original: Absent cone and rod functions by electroretinogram (ERG)
Alternative 1: Absent cone and rod functions by electroretinogram
Alternative 2: Absent cone and rod functions by ERG

HP:0002928
Original: Decreased activity of the pyruvate dehydrogenase (PDH) complex
Alternative 1: Decreased activity of the pyruvate dehydrogenase complex
Alternative 2: Decreased activity of the PDH complex

HP:0003165
Original: Elevated circulating parathyroid hormone (PTH) level
Alternative 1: Elevated circulating parathyroid hormone level
Alternative 2: Elevated circulating PTH level

HP:0011738
Original: Corticotropin-releasing hormone receptor (CRHR) resistance
Alternative 1: Corticotropin-releasing hormone receptor resistance
Alternative 2: CRHR resistance

HP:0003436
Original: Prolonged miniature endplate currents (MEPC)
Alternative 1: Prolonged miniature endplate currents
Alternative 2: Prolonged MEPC

HP:0003145
Original: Decreased adenosylcobalamin (ADOCBL)
Alternative 1: Decreased adenosylcobalamin
Alternative 2: Decreased ADOCBL

HP:0000762
Original: Decreased nerve conduction velocities (NCV)
Alternative 1: Decreased nerve conduction velocities
Alternative 2: Decreased NCV

HP:0003203
Original: Negative nitroblue tetrazolium (NBT) reduction test
Alternative 1: Negative nitroblue tetrazolium reduction test
Alternative 2: Negative NBT reduction test

HP:0002959
Original: Impaired Ig class-switch recombination (CSR)
Alternative 1: Impaired Ig class-switch recombination
Alternative 2: Impaired Ig CSR

**Comment by pnrobinson** [comment]
Thanks for this suggestion, which was in parallel to a related item. It is not possible to remove all of the brackets, because sometimes brakcets are simply part of the name of an item. However, we are endeavouring to remove brackets from all of the primary term names and to reduce their use as much as possible, so that neither primary names nor synonym names will use brackets to indicate alternatives.
