### ISSUE TITLE
NTR: Ultrasound: urinary bladder muscular wall thick (Lab: radiology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8976]
New term request Ultrasound: urinary bladder muscular wall thick (elthat_130802071441): Hypertrophy of bladder wall  UMLS: 5232303

**Comment by pnrobinson** [comment]
@MickeySegal
Is this the same thing as [Hypertrophy of the urinary bladder HP:0008635](https://hpo.jax.org/app/browse/term/HP:0008635)? The current definition of the term is not good. Just enlargement would be distension?

**Comment by MickeySegal** [comment]
Smith Malformation for Prune Belly "bladder wall hypertrophy"

https://www.ncbi.nlm.nih.gov/books/NBK154138/ "Postnatal imaging by ultrasonography and micturating cystourethrography typically shows muscular thickening and trabeculation of the urinary bladder"

**Comment by pnrobinson** [comment]
@MickeySegal 
looking at the term and the literature, I think the term always intended to mean this, so I relabled it it
HP:0008635
Urinary bladder wall hypertrophy
