### ISSUE TITLE
Removing brackets in term names and synonyms

### ISSUE THREAD

**Issue by skocbek** [obophenotype/human-phenotype-ontology#898]
Below is a list of terms that contain brackets in name or synonym strings. These strings should probably be presented differently. 

Larger part of the brackets contain body parts, e.g.. "Acroosteolysis of distal phalanges (feet)”, and some brackets contain additional information, e.g., “Vocal cord paralysis (caused by tumor impingement)”. The concept "HP:0040037: obsolete Thin fingernail (obsolete))” seems not to follow the standard way for marking obsolete concepts.

Note that some brackets contain abbreviations which is reported in [issue #897](https://github.com/obophenotype/human-phenotype-ontology/issues/897)

The list:
HP:0008166: Decreased beta-galactosidase activity (leukocyte, fibroblast, plasma)
HP:0010112: Central polydactyly (feet)
HP:0001177: Preaxial polydactyly (hands)
HP:0001180: Oligodactyly (hands)
HP:0003880: Sclerotic foci (humeral)
HP:0001842: Acroosteolysis (feet)
HP:0012053: Low serum calcifediol (25-hydroxycholecalciferol)
HP:0004220: Hypoplastic middle phalanx (5th finger)
HP:0003868: Cortical thickening (humeral)
HP:0030336: Absence of CD4+CD25+ T regulatory cells (Tregs)
HP:0011003: Severe myopia (> -6.00 diopters)
HP:0001839: Ectrodactyly (feet)
HP:0010847: EEG with spike-wave complexes (<2.5 Hz)
HP:0008922: Disproportionate short stature (short trunk), identifiable in childhood
HP:0001162: Postaxial polydactyly (hands)
HP:0001991: Aplastic/hypoplastic phalanges (feet)
HP:0001248: Short tubular bones (hand)
HP:0007517: Excessive wrinkled skin (palms and soles)
HP:0003492: High urinary gonadotropins (primary hypogonadism)
HP:0003789: Minicore (multicore) myopathy
HP:0001870: Acroosteolysis of distal phalanges (feet)
HP:0003908: Corner spurs (humeral metaphyses)
HP:0003210: Decreased methylmalonyl-CoA mutase (mut, 609058) activity
HP:0001161: Polydactyly (hands)
HP:0004322: Short stature (below 3rd percentile)
HP:0002331: Headache (with pheochromocytoma)
HP:0003465: Elevated 8(9)-cholestenol
HP:0004635: Cervical vertebrae fusion (C5/C6)
HP:0002886: Vagal nerve tumors (glomus vagale)
HP:0100789: Prominent midpalatal ridge (torus palatinus)
HP:0001829: Polydactyly (feet)
HP:0040126: Abnormal serum cobalamin (vitamin B12)
HP:0001886: Osteomyelitis or necrosis, distal, due to sensory neuropathy (feet)
HP:0030766: Pain in the ear, which can be a consequence of otologic disease (primary or otogenic otalgia), or can arise from pathologic processes and structures other than the ear (secondary or referred otalgia).
HP:0100760: Clubbing (feet)
HP:0001770: Syndactyly (feet)
HP:0003916: Normal-density transverse bands (humerus)
HP:0006159: Central polydactyly (hands)
HP:0100747: Macrodactyly (feet)
HP:0003524: Decreased methionine synthase (MTR, 156570) activity
HP:0007443: Congenital partial albinism (leucoderma) on face, trunk, or limbs
HP:0004691: Syndactyly (2-3) (feet)
HP:0001983: Reduced lymphocyte surface expression of CD43 (sialophorin)
HP:0003875: Lytic defects (humeral)
HP:0003872: Exostoses (humeral)
HP:0200054: Monodactyly (feet)
HP:0001831: Short phalanges (feet)
HP:0001062: Atypical nevi (>5mm with irregular edge and pigmentation)
HP:0001613: Hoarse voice (caused by tumor impingement)
HP:0005315: A narrowing of the peripheral arteries (i.e., of arteries other than thos that supply the heart and the brain).
HP:0001859: Distal symphalangism (feet)
HP:0003951: Irregular metaphyses (elbow)
HP:0001868: Autoamputation (feet)
HP:0003955: Bone-in-a-bone appearance (forearm)
HP:0001011: Diaphoresis (with pheochromocytoma)
HP:0012301: Abnormal isoelectric focusing of serum transferrin (type 2 pattern)
HP:0010848: EEG with spike-wave complexes (2.5-3.5 Hz)
HP:0004333: Large vacuolated foam cells ('NP cells') on bone marrow biopsy
HP:0004440: Craniosynostosis (coronal)
HP:0001171: Ectrodactyly (hands)
HP:0030281: Cervical vertebral fusion (C3/C4)
HP:0000117: Decreased tubular maximum for phosphate reabsorption per glomerular filtration rate (TMP/GFR)
HP:0002165: Pterygium formation (nails)
HP:0008947: Hypotonia (infancy)
HP:0001673: Tachycardia (with pheochromocytoma)
HP:0002297: Red head (hair color)
HP:0003335: Low gonadotropins (secondary hypogonadism)
HP:0001204: Distal symphalangism (hands)
HP:0001606: Vocal cord paralysis (caused by tumor impingement)
HP:0001862: Acral ulceration and osteomyelitis leading to autoamputation of the digits (feet)
HP:0002292: Frontal balding (male pattern baldness)
HP:0010230: Cone-shaped epiphyses (hand)
HP:0003689: Multiple mitochondrial DNA (mtDNA) deletions
HP:0000823: Delayed puberty (female)
HP:0003950: Flared metaphyses (elbow)
HP:0000384: Preauricular tag, isolated (skin covered and composed of elastic cartilage)
HP:0003878: Periosteal new bone (humeral)
HP:0200118: Malabsorption of vitamin B12 (cyanocobalamin)
HP:0001857: Hypoplastic distal phalanges (feet)
HP:0100237: Proximal symphalangism (feet)
HP:0009489: Bracket-epiphyses (index finger)
HP:0000823: Delayed puberty (male)
HP:0003809: Nearly complete absence of metabolically active adipose tissue (subcutaneous, intraabdominal, intrathoracic)
HP:0003881: Sclerosis (humeral)
HP:0003514: Deficiency or absence of cytochrome b(-245)
HP:0100490: Camptodactyly (hands)
HP:0100651: Insulin-dependent diabetes mellitus (type I)
HP:0000740: Anxiety (with pheochromocytoma)
HP:0010554: Cutaneous syndactyly (hands)
HP:0006159: Interdigital polydactyly (hand)
HP:0010813: Double crown (hair whorls)
HP:0100759: Clubbing (hands)
HP:0009790: Hemisacrum (S2-S5)
HP:0003421: Platyspondyly (childhood)
HP:0010849: EEG with spike-wave complexes (>3.5 Hz)
HP:0045063: Increased PIVKA-II (protein increased in vitamin K's absence; undercarboxylated prothrombin)
HP:0003909: Cortical subperiosteal resorption (humeral metaphyses)
HP:0003877: Oval transradiancy (humeral)
HP:0004602: Cervical vertebral fusion (C2/C3)
HP:0003867: Cortical irregularity (humeral)
HP:0001836: Camptodactyly (feet)
HP:0006152: Proximal symphalangism (hands)
HP:0003538: Increased serum iduronate sulfatase (10-20x)
HP:0001854: Gout (feet)
HP:0003879: False joint (long bone in upper arm)
HP:0003795: Short middle bones (feet)
HP:0003866: Coarse trabeculae (humeral)
HP:0003879: Pseudarthrosis (humeral)
HP:0002667: Nephroblastoma (Wilms tumor)
HP:0040037: obsolete Thin fingernail (obsolete)
HP:0001849: Oligodactyly (feet)
HP:0002286: Towhead (hair color)
HP:0003365: Arthralgia (hip)
HP:0010621: Syndactyly, cutaneous (feet)
HP:0002476: Primitive reflexes (palmomental, snout, glabellar)
HP:0003869: Cortical thinning (humeral)
HP:0011788: Increased serum free triiodothyronine (fT3)
HP:0009568: Hypoplastic/aplastic middle phalanx (2nd finger)
HP:0012052: Low serum calcitriol (1,25-dihydroxycholecalciferol)
HP:0003795: Short middle phalanges (feet)
HP:0003642: Abnormal isoelectric focusing of serum transferrin (type 1 pattern)
HP:0001802: Absent toenails (anonychia)
HP:0000361: Pulsatile tinnitus (tympanic paraganglioma)
HP:0003931: Periosteal new bone (humeral diaphysis)
HP:0006715: Tympanic nerve tumors (glomus tympanicum)
HP:0004058: Monodactyly (hands)
HP:0001676: Palpitations (with pheochromocytoma)
HP:0100746: Macrodactyly (hands)
HP:0001841: Preaxial polydactyly (feet)
HP:0010621: Cutaneous syndactyly (feet)
HP:0001387: Joint stiffness (hands, shoulder, elbows, knees, and ankles)

**Comment by pnrobinson** [comment]
Thanks for pointing this out. In some cases, the phrases above are synonyms, and this seems valid because one does see these synonyms "out in the wild". For now, I am going to remove the brackets from the primary term name -- would this work for you?

**Comment by skocbek** [comment]
Thanks Peter. Well, for my purposes I am using both - names and synonyms, so I will have to do pre-processing anyway if brackets stay in synonyms. But, in general, I was wondering whether the brackets are a valid way to represent terms in HPO. For example, when I'm looking for HPO terms in some free text, should I look for the exact term "Hemisacrum (S2-S5)"? Looking for just "Hemisacrum" would be invalid?

**Comment by pnrobinson** [comment]
After thinking some more, it is apparent that there are phrases such as "Abnormal CSF A[beta]42 level" that require a bracket. I think it is a good idea to avoid brackets if at all possible in the main term names, but since the synonyms are also being used for text mining by many groups, I think we need to retain the brackets if that is how they are being used in the community. I am going to continue to revise the main terms names in this list (THANKS very much by the way for this input!) and I will close this item once I am done (Sorry there is an upcoming grant deadline so I have limited time right now!).

**Comment by pnrobinson** [comment]
Thanks for these suggestions. I have not been able to remove all parentheses from all terms/synonyms, since in some cases it is appropriate and necessary. But now ca. 95% are removed, this was a good suggestion.
