### ISSUE TITLE
NTR: OCT: retinal nerve fiber layer thin (Lab: radiology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8980]
New term request OCT: retinal nerve fiber layer thin (elthat_131117171432): Optical coherence tomography  UMLS: 3150324

**Comment by pnrobinson** [comment]
@MickeySegal
I am going to close this NTR here because we will be thoroughly revising this section of the HPO at several workshops.

**Comment by MickeySegal** [comment]
Please keep me in the loop so I can use the resulting terms.
