### ISSUE TITLE
NTR: X-ray or CT: breast calcifications (Lab: radiology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8985]
New term request X-ray or CT: breast calcifications (elthat_140129153403):   UMLS: 0587094

**Comment by MickeySegal** [comment]
https://ojrd.biomedcentral.com/articles/10.1186/s13023-017-0639-8 "Calcification of the kidneys, breasts, pancreas, testicles, liver and spleen has variously been observed in patients with PXE. With the possible exception of the kidneys, this calcification is not thought to have a major clinical impact "

Microcalcification is probably good enough.

**Comment by pnrobinson** [comment]
OK, for instance this article speaks of microcalcification in PXE --https://pubmed.ncbi.nlm.nih.gov/12637915/
closing.
