### ISSUE TITLE
New HPO terms for Bleeding, Platelet and Thrombosis disorder - BPD reopen #647

### ISSUE THREAD

**Issue by lcdaugherty** [obophenotype/human-phenotype-ontology#900]
#647 On behalf of the team, thank you for adding new terms relating to Bleeding, Platelet and Thrombosis disorders.

However, although the above classes were added by you I can’t find them
 > Invalid HPO id input
eg: Abnormality of fibrinolysis  http://compbio.charite.de/hpoweb/showterm?id=HP:0040224

Can you tell me how long we need to wait until these 28 terms are made public?

One of the tools we use to code our samples is updating this weekend (and hence the version of HPO), so it would be useful if this these terms could be made public as soon as possible.
Also, the proposed term Increased plasma vitamin K epoxide after vitamin K supplementation, seems to be missing, was there a reason why this was excluded?

Apologies if I have missed something from the HPO submission process please let me know if you require any more info from us before these terms can be made public.

**Comment by lcdaugherty** [comment]
Apologies, I am a creature of habit and now realize HPO browser has been superseded. For now I will use http://www.ontobee.org and in future use http://compbio.charite.de/phenomizer/ (when app fixed) for browsing the hierarchies. 
I can now see the new HPO terms for the BPD project have been added and are public (HPO release  #1700 April 1, 2016). 
This query can can now be closed.

**Comment by pnrobinson** [comment]
We are in the process of transitioning, but hope to have the HPO browser updated soon as well! thanks Peter
