### ISSUE TITLE
NTR: Ultrasound or CT: stomach right-sided (Lab: radiology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9002]
New term request Ultrasound or CT: stomach right-sided (elthat_151128162354):   UMLS: 4539799

**Comment by pnrobinson** [comment]
@MickeySegal
is this a type of Malposition of the stomach HP:0100802 or situs inversus of stomach (if the latter, would it be distinct from Abdominal situs inversus HP:0003363)? What is the disease context?

**Comment by MickeySegal** [comment]
https://www.omim.org/entry/616749
"In the first family, a boy had dextrocardia, ventricular and atrial septal defects, interrupted inferior vena cava, and interrupted aortic arch. A deceased sib (fetus) had right-sided stomach, total anomalous pulmonary return, mitral atresia, and double-outlet right ventricle. "

**Comment by MickeySegal** [comment]
That seems to be correct, as indicated in the OMIM clinical summaries:
https://www.omim.org/clinicalSynopsis/616749
ABDOMEN
- Situs inversus
https://www.omim.org/clinicalSynopsis/617205
"Situs inversus viscerum"

**Comment by pnrobinson** [comment]
OK, I will close then!
