### ISSUE TITLE
NTR: X-ray: fusion of maxilla and mandible (Lab: radiology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9003]
New term request X-ray: fusion of maxilla and mandible (elthat_151208173759): Maxillary; mandibular

**Comment by pnrobinson** [comment]
@MickeySegal is this distinct from [Temporomandibular joint ankylosis HP:0012478](https://hpo.jax.org/app/browse/term/HP:0012478) ?

**Comment by MickeySegal** [comment]
The temporomandibular joint is between the temporal bone and the mandible.  
Our finding is about the maxilla and the mandible.  
In the image at https://www.earthslab.com/anatomy/temporal-bone/ these to contact at very separate points.  

Our information was from Smith about Oromandibular-limb hypogenesis spectrum "complete bony fusion of the maxilla and mandible".

**Comment by pnrobinson** [comment]
@MickeySegal 
I see, sorry, I was not reading closely.
I think this is an exceedingly rare phenotype that can be called syngnathia (see., e.g. https://pubmed.ncbi.nlm.nih.gov/30106810/). The HPO has this term: [Fibrous syngnathia HP:0009754](https://hpo.jax.org/app/browse/term/HP:0009754) that mistakenly is only a child of Abn. mandible morphology. 
Is it the case that this phenotype is essentially Bony syngnathia?

**Comment by MickeySegal** [comment]
Oromandibular-limb hypogenesis spectrum is the only disease we have listed, so the congenital nature of syngnathia fits.

**Comment by pnrobinson** [comment]
OK, thanks!
