### ISSUE TITLE
NTR: MRI: hypointensities in pons (Lab: radiology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9005]
New term request MRI: hypointensities in pons (segal_160812164822): Pontine

**Comment by pnrobinson** [comment]
@MickeySegal it is probably best to specific T1 or T2. Not an expert here, but T2 hypointensity in the pons is recognize https://pubmed.ncbi.nlm.nih.gov/22268491/

**Comment by MickeySegal** [comment]
We had the same information from https://ojrd.biomedcentral.com/articles/10.1186/1750-1172-8-41 so I changed our finding to specify T2 as done there.

**Comment by pnrobinson** [comment]
@MickeySegal 
added as
HP:4000169
Pontine T2 hypointensity
