### ISSUE TITLE
NTR: Prenatal ultrasound: placental cysts (Lab: radiology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9007]
New term request Prenatal ultrasound: placental cysts (elthat_160819053023): Cystic  UMLS: 1394410

**Comment by pnrobinson** [comment]
@MickeySegal @sparkste 
there is one existing term [Subchorionic septal cyst HP:0030720](https://hpo.jax.org/app/browse/term/HP:0030720)
for placental cysts, however I wonder if we need to create a small hierarchy for different types?

**Comment by MickeySegal** [comment]
We have this only for Beckwith-Wiedemann syndrome, where we also have https://hpo.jax.org/app/browse/term/HP:0032165.  https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9688415/ says that for Placental Mesenchymal Dysplasia "In some cases, grape-like cysts formed by dilatation of the hydropic stem villi are present".

**Comment by sparkste** [comment]
Hi all,

Totally agree that placental mesenchymal dysplasia can be seen with BWS.  The other scenario where I have seen placental mesenchymal dysplasia (clinically and in the literature) is androgenic mosaicism (PMID 21585278). Of note, the cystic changes that are seen with a molar pregnancy can be confused for mesenchymal dysplasia, and I wonder if there is separate branching logic for the cystic placental changes that are seen with a molar pregnancy?

Thanks!
Teresa


Teresa Sparks, MD, MAS
Associate Professor, Maternal-Fetal Medicine and Clinical Genetics
Program Director, Maternal-Fetal Medicine Fellowship
Co-Director, Women's Reproductive Health Research/K12 Program
Division of Maternal-Fetal Medicine and Reproductive Genetics
University of California, San Francisco
________________________________

**Comment by pnrobinson** [comment]
@MickeySegal 
For BWS, the term [Placental mesenchymal dysplasia HP:0032165](https://hpo.jax.org/app/browse/term/HP:0032165) is available and is intended to include the cystic lesions. Admittedly it is a bit of a bundled term, but perhaps it is forgivable in this case.
@sparkste we may want to think more about placental lesions moving forward, but then prob. a workshop or zoom would be better than issues!
