### ISSUE TITLE
NTR: CT: orbital inflammation (Lab: radiology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9016]
New term request CT: orbital inflammation (nadea3_190123195858): With or without abscess; eye  UMLS: 0521747

**Comment by pnrobinson** [comment]
@MickeySegal
does this refer to https://www.ncbi.nlm.nih.gov/books/NBK551576/ ?
Please probvide context

**Comment by MickeySegal** [comment]
We used the finding for orbital cellulitis and dacrocystitis, but https://www.ncbi.nlm.nih.gov/books/NBK551576/ seems like it should be included too and I've asked our Ophthalmology curator to add this.
