### ISSUE TITLE
"topoisomerase I antibody positivity" 

### ISSUE THREAD

**Issue by slaulederkind** [obophenotype/human-phenotype-ontology#902]
I would like to see "Topoisomerase I antibody positivity" added to the HP ontology under the parent term "Autoimmune antibody positivity" (HP:0030057).  The definition could be "The presence of autoantibodies (immunoglobulins) in the serum that react against topoisomerase I."  An example can be found in PMID:16112028. Synonyms would be "Top1 antibody positivity" and "topoisomerase (DNA) I antibody positivity".

**Comment by pnrobinson** [comment]
Thanks! Added this as HP_0030859.
