### ISSUE TITLE
T cell term definitions

### ISSUE THREAD

**Issue by slaulederkind** [obophenotype/human-phenotype-ontology#903]
The same definition is used for two HP terms: "Abnormality of T cell physiology (HP:0011840)" and "Abnormality of T cell number (HP:0011839)."  "A deviation from the normal count of T cells" doesn't sound like a correct definition for "Abnormality of T cell physiology (HP:0011840)".

**Comment by pnrobinson** [comment]
Thanks for picking up this error. I changed the definition to "A functional anomaly of T cells."
