### ISSUE TITLE
NTR: X-ray or CT: temporomandibular malocclusion (Lab: radiology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9034]
New term request X-ray or CT: temporomandibular malocclusion (nadea3_191211162621): Jaw; TMJ; panorex; dislocation  UMLS: 1403534

**Comment by pnrobinson** [comment]
@MickeySegal
I am not familiar with this terminology.
As far as I know, dental malocclusion can cause temporomandibular dysfunction, but there is no such thing as temporomandibular malocclusion?

**Comment by MickeySegal** [comment]
Also called Temporomandibular joint dislocation  (https://www.sciencedirect.com/science/article/abs/pii/S1042369914000983?via%3Dihub)

**Comment by pnrobinson** [comment]
@MickeySegal 
this is 
Temporomandibular joint dislocation HP:6000814
I am adding the above as a synonym
