### ISSUE TITLE
NTR: Pelvic imaging: tubo-ovarian abscess, salpingitis (Lab: radiology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9042]
New term request Pelvic imaging: tubo-ovarian abscess, salpingitis (nadea3_210827110037): TOA; pelvic CT, MRI, ultrasound; ovary  UMLS: 0041343

**Comment by pnrobinson** [comment]
Salpingitis
An inflammation of the fallopian tube.
PMID: [19017411](https://pubmed.ncbi.nlm.nih.gov/19017411)

Tubo-Ovarian Abscess  -- see https://www.ncbi.nlm.nih.gov/books/NBK448125/

**Comment by pnrobinson** [comment]
@MickeySegal I think these are two terms, adding Salpingitis as HP_0034492
and
Tubo-ovarian abscess  as HP_0034493

**Comment by MickeySegal** [comment]
I agree.  The Mass General pediatrician who created this finding must have felt that they go together in practice, but UMLS split into the component findings as you suggest.  So I split them too.  I only see one of the UMLS listed in your first post in this thread, but I thought I'd provided both.  The Salpingitis one is https://www.ncbi.nlm.nih.gov/medgen/C0036130
