### ISSUE TITLE
NTR: X-ray or CT: spinal cord calcifications (Lab: radiology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9044]
New term request X-ray or CT: spinal cord calcifications (elthat_211112140729):

**Comment by pnrobinson** [comment]
@MickeySegal
added as HP_0034484

**Comment by MickeySegal** [comment]
When new HPO findings get incorporated into UMLS I will need to get the UMLS codes.  Will you have a list of these HPO terms added for our findings, or do I need to keep a log from these GitHub mentions?

**Comment by pnrobinson** [comment]
I will write a script to extract all mappings that include the simulconsult synonyms exactly as provided. If this is not the case, then I am tagging you, and for these exceptions please do keep a log. I will try to test the script this week so we can make sure it is all working.

**Comment by MickeySegal** [comment]
Thanks.  I started keeping a log yesterday and will backfill my list with earlier emails.
