### ISSUE TITLE
NTR: Bone imaging: lead lines in metaphyses of bones (Lab: radiology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9045]
New term request Bone imaging: lead lines in metaphyses of bones (segal_211223221146): Metaphysis; metaphyseal bands  UMLS: 0544864

**Comment by pnrobinson** [comment]
@MickeySegal
this is a synonym of [Dense metaphyseal bands HP:0100959](https://hpo.jax.org/app/browse/term/HP:0100959), see https://pubs.rsna.org/doi/abs/10.1148/radiology.211.3.r99jn13773?journalCode=radiology

I will add the synonym and a cross ref to this article.

**Comment by MickeySegal** [comment]
Looks solid.  Thanks.
