### ISSUE TITLE
NTR: Joint imaging: acetabular angle flat (Lab: radiology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9046]
New term request Joint imaging: acetabular angle flat (hresko_220214153758): Acetabulum; low angle  UMLS: 1968919

**Comment by pnrobinson** [comment]
@MickeySegal
this seems to be another way of saying [Flat acetabular roof HP:0003180](https://hpo.jax.org/app/browse/term/HP:0003180), see also https://radiopaedia.org/cases/acetabular-angle-diagram?lang=us
Do you think we can use this as a synonym?

**Comment by MickeySegal** [comment]
I'll ask Hresko.

**Comment by MickeySegal** [comment]
Hresko (former head of orthopedics at Boston Children's Hospital) agrees these are the same.

**Comment by pnrobinson** [comment]
@MickeySegal 
Thanks!
I have added "Acetabular angle flat " (without "joint imaging") as a synonym, you may need to add this to the list HP:0003180
