### ISSUE TITLE
NTR: REM sleep behavior disorder on sleep EEG (Lab: neurophysiology: EEG)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9048]
New term request REM sleep behavior disorder on sleep EEG (kalia_091014025726): Dream-enacting behavior; physically act out vivid, often unpleasant dreams with vocal sounds and sudden, often violent arm and leg movements during REM sleep; The affected individual may inflict self-injury or harm others, and is difficult to awaken from such episodes.  Episodes are usually followed by a vivid recollection of a dream that is consistent with the aggressive behavior.  RBD  UMLS: 0751772

**Comment by pnrobinson** [comment]
the HPO would code this item as well as #9049 with [Sleep disturbance HP:0002360](https://hpo.jax.org/app/browse/term/HP:0002360), i.e., it would not code the mode of diagnostics. However, the description here goes into some detailed manifestations. We are currently explaning the behavioral branch of the HPO and this might be appropriate there.

**Comment by MickeySegal** [comment]
This needs to be re-opened.  As detailed at http://www.sleepfoundation.org/parasomnias/rem-sleep-behavior-disorder this is a very distinct type of sleep disorder and needs to be one of the several terms under HP:0002360.  We have a second finding segal_220706150439 that is the same finding but diagnosed by history from the spouse, but you can give the same code to both.

**Comment by pnrobinson** [comment]
@MickeySegal  -- reopening!

**Comment by pnrobinson** [comment]
@MickeySegal 
I think this is a synonym for the relatively new term HP:5200299, REM parasomnia
Unless there is a distinction, I will add this as a synonym.

https://www.sleepfoundation.org/parasomnias/rem-sleep-behavior-disorder
REM sleep behavior disorder is a condition characterized by sudden body movements and vocalizations while a person experiences vivid dreams during REM sleep Trusted Source
National Library of Medicine, Biotech Information The National Center for Biotechnology Information advances science and health by providing access to biomedical and genomic information.
View Source
. It is a specific type of [parasomnia](https://www.sleepfoundation.org/parasomnias), which describes abnormal behaviors during sleep.

**Comment by pnrobinson** [comment]
In the meantime some terms have been added:

HP:5200291
Term Name: Sleep enactment (synonym of REM sleep behavior disorder)

-- rearrange and add synonyms

**Comment by pnrobinson** [comment]
@MickeySegal 
I have rearranged the three parasomnias as recommended.
The HPO typically does not record the diagnostic modalities of a term to avoid having a proliferation of terms that mean the same or nearly the same thing. Would it be appropriate to mention the EEG finding in the term or is there a clinical distinction between people with clinical Sleep enactment and EEG Sleep enactment findings?

**Comment by MickeySegal** [comment]
We use 2 terms because of their different costs, but it makes sense to use the same HPO term for the conclusion reached.  The issue, though, is by using the HPO code for clinical ascertainment one may be implying having done the EEG test when all that was done is history.

**Comment by pnrobinson** [comment]
@MickeySegal no model is perfect...but this kind of precision can be obtained if patients are coded using the Phenopacket Schema. I will close for now.

**Comment by MickeySegal** [comment]
OK.  This is not an issue here because https://hpo.jax.org/browse/term/HP:5200291 is titled "Sleep enactment".
