### ISSUE TITLE
Comments on the NCIT shadow experiment neoplasm slim import

### ISSUE THREAD

**Issue by mellybelly** [obophenotype/human-phenotype-ontology#905]
Comments on this branch:
https://github.com/obophenotype/human-phenotype-ontology/pull/904

There are some terms that come from the NCIT neoplasm slim that I would probably not include.

Things that have NOSs: 
'Chronic Eosinophilic Leukemia, Not Otherwise Specified'

Things that have specific gene/genotype mentions:
'Myeloid and Lymphoid Neoplasms with Eosinophilia and Abnormalities of PDGFRA, PDGFRB, or FGFR1'
'Acute Myeloid Leukemia with inv(3)(q21q26.2); RPN1-EVI1'

I would, however, keep the biomarker related classes, as these are phenotypic/expression descriptors and don't say anything about the genotype:
'Chronic Phase Chronic Myelogenous Leukemia, BCR-ABL1 Positive'

We also need a basic subsumption hierarchy, which is not in the slim file (which is a list), maybe NCIT could generate this as part of their build or we can create a bridge file.

**Comment by pnrobinson** [comment]
I am closing this in light of work on the NCIT in the intervening time.
