### ISSUE TITLE
NTR: Rectal biopsy: abnormal neural elements (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9053]
New term request Rectal biopsy: abnormal neural elements (f435):

**Comment by pnrobinson** [comment]
@MickeySegal
it would be good to say what is abnormal in the biopsy finding?

**Comment by MickeySegal** [comment]
This test doesn't seem to be done anymore.  I'm deleting it.

**Comment by pnrobinson** [comment]
thanks, closing.
