### ISSUE TITLE
NTR: Muscle biopsy: neuropathic or denervation abnormalities (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9054]
New term request Muscle biopsy: neuropathic or denervation abnormalities (f436): Neurogenic; Neuropathy  UMLS: 3550585

**Comment by pnrobinson** [comment]
@MickeySegal
this is like a NOS description and is probably too general for the HPO. Could you provide context?

**Comment by pnrobinson** [comment]
There is a general term that applies
[EMG: chronic denervation signs HP:0003444](https://hpo.jax.org/app/browse/term/HP:0003444)
If this is not what is required please reopen.

**Comment by MickeySegal** [comment]
That is correct mechanistically, but if you intend that to cover both EMG and muscle biopsy you should drop EMG from the title and change the description to also include biopsy.
