### ISSUE TITLE
NTR: Muscle biopsy: acid maltase low (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9055]
New term request Muscle biopsy: acid maltase low (f438): GAA; alpha-1,4-glucosidase  UMLS: 1856350

**Comment by pnrobinson** [comment]
@MickeySegal

does this refer to "Alpha-1,4-glucosidase was absent from muscle"? (https://omim.org/entry/232300)

**Comment by MickeySegal** [comment]
Yes.

**Comment by pnrobinson** [comment]
@MickeySegal 
Added as 
HP:6000088
Reduced muscle alpha-1,4-glucosidase activity
