### ISSUE TITLE
NTR: Peripheral nerve biopsy: abnormal structurally (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9056]
New term request Peripheral nerve biopsy: abnormal structurally (f439):   UMLS: 0853461

**Comment by pnrobinson** [comment]
@MickeySegal
the HPO would want to specify the concrete abnormality rather than the mode of visualization -- can we specify what is meant?

**Comment by MickeySegal** [comment]
This was a very old bundled finding that had in almost all cases been replaced by specific findings.  I added specific findings in the instances where that had not been done and deleted this finding.
