### ISSUE TITLE
NTR: Conjunctival biopsy: abnormal EM morphology (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9058]
New term request Conjunctival biopsy: abnormal EM morphology (f441):   UMLS: 0853094

**Comment by pnrobinson** [comment]
@MickeySegal
the HPO would want to specify the concrete abnormality rather than the mode of visualization -- can we specify what is meant?

**Comment by MickeySegal** [comment]
I agree that this is a terribly bundled vague finding.  It derives from a chapter in the 1986 textbook "Goldberg's Genetic and Metabolic Eye Disease".  I checked the various disease entries and get the impression that such testing was used until the 1980s but no longer.  

I deleted the finding.

**Comment by pnrobinson** [comment]
thanks, closing
