### ISSUE TITLE
NTR: Brain biopsy: distinctive abnormality not otherwise specified (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9059]
New term request Brain biopsy: distinctive abnormality not otherwise specified (f442):   UMLS: 0853418

**Comment by MickeySegal** [comment]
This is a deprecated finding that will be split up into specific terms and then deleted.  I'm sorry for not having filtered this out.
