### ISSUE TITLE
New term request: enlarged tonsils

### ISSUE THREAD

**Issue by CourtneyHum** [obophenotype/human-phenotype-ontology#906]
Suggested superclass: abnormality of nasopharyngeal adenoids (HP:3000033)

**Comment by pnrobinson** [comment]
There already was a term for enlarged tonsils, HP_0030812.
Abnormality of nasopharyngeal adenoids (HP:3000033) is a child of abnormality of the tonsils. I think this is correct because of: "The adenoid, also known as a pharyngeal tonsil or nasopharyngeal tonsil, is the superior-most of the tonsils."
Reopen if needed!

**Comment by CourtneyHum** [comment]
Hi Peter,
I was interested to know if enlarged could be considered a child of
abnormality. Abnormality certainly isn't incorrect, but perhaps not
specific enough in some cases.

Thanks,
Courtney

On Sat, Jun 11, 2016 at 4:06 AM, Peter Robinson <notifications@github.com>
wrote:

> There already was a term for enlarged tonsils, HP_0030812.
> Abnormality of nasopharyngeal adenoids (HP:3000033) is a child of
> abnormality of the tonsils. I think this is correct because of: "The
> adenoid, also known as a pharyngeal tonsil or nasopharyngeal tonsil, is the
> superior-most of the tonsils."
> Reopen if needed!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/obophenotype/human-phenotype-ontology/issues/906#issuecomment-225343579>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ALZYMzmpWRYnylr37mhvoOp9MRx0PEZDks5qKmyDgaJpZM4IzMvL>
> .
>



-- 
Courtney Hum, MSc
Genetic Counsellor
Centre for Computational Medicine
The Hospital for Sick Children
T: 416-813-7654 x414028
