### ISSUE TITLE
NTR: Muscle biopsy: neutral maltase level abnormal (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9076]
New term request Muscle biopsy: neutral maltase level abnormal (segal_050203153510):

**Comment by pnrobinson** [comment]
@MickeySegal
what is the gene or disease context? I cannot unambiguous identify "neutral maltase"

**Comment by MickeySegal** [comment]
We had the finding but no disease associated with it.  I deleted the finding.

**Comment by pnrobinson** [comment]
OK, closing!
