### ISSUE TITLE
NTR: Muscle biopsy: rotenone-sensitive NADH reductase low (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9077]
New term request Muscle biopsy: rotenone-sensitive NADH reductase low (segal_050203181941):

**Comment by pnrobinson** [comment]
@MickeySegal

I do not think this is the actual name of the enzyme; maybe it is this: https://www.uniprot.org/uniprotkb/P03886/entry
What is the disease context? Is this a clinical assay?

**Comment by MickeySegal** [comment]
The word cytochrome had been left out of the name; from https://pubmed.ncbi.nlm.nih.gov/2256918/ it seems this is just another way of saying [Complex III deficiency](https://hpo.jax.org/app/browse/term/HP:0011924), so I merged it into that existing finding.

**Comment by pnrobinson** [comment]
OK, closing!
