### ISSUE TITLE
NTR: Muscle biopsy: succinate-cytochrome c reductase low (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9080]
New term request Muscle biopsy: succinate-cytochrome c reductase low (segal_050203184015):

**Comment by pnrobinson** [comment]
@MickeySegal
is this distinct from 
[Cytochrome C oxidase-negative muscle fibers HP:0003688](https://hpo.jax.org/browse/term/HP:0003688)?

**Comment by MickeySegal** [comment]
It is https://hpo.jax.org/browse/term/HP:0008314.  We will use that.

**Comment by pnrobinson** [comment]
OK!
