### ISSUE TITLE
NTR: Coenzyme Q10 decreased in skeletal muscle or fibroblasts (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9085]
New term request Coenzyme Q10 decreased in skeletal muscle or fibroblasts (segal_050624133727):   UMLS: 3551958

**Comment by pnrobinson** [comment]
@MickeySegal
since Coenzyme Q10 is present ubiquitously, I wonder if we can just say
Decreased tissue coenzyme Q10 concentration
and place the term under
[Abnormal tissue metabolite concentration HP:0032243](https://hpo.jax.org/app/browse/term/HP:0032243)

**Comment by MickeySegal** [comment]
That is fine.

**Comment by pnrobinson** [comment]
@MickeySegal 
actually coming back to this I found we already had a term for muscle tissue

[Decreased level of coenzyme Q10 in skeletal muscle HP:0034369](https://hpo.jax.org/app/browse/term/HP:0034369)

If this is not appropriate then please reopen.

**Comment by MickeySegal** [comment]
That is good.  It seems like a recent HPO code number so it must have been added after I prepared my list.
