### ISSUE TITLE
New term: anomia

### ISSUE THREAD

**Issue by CourtneyHum** [obophenotype/human-phenotype-ontology#909]
Definition: the inability to name objects or recognize the written or spoken name of objects
Superclass: neurological speech impairment (HP:0002167)

http://www.ncbi.nlm.nih.gov/pmc/articles/PMC2699352

**Comment by pnrobinson** [comment]
A term Anomia already exists (HP_0030784) as a child of neurological speech impairment (HP:0002167). I have added an xref to the article you cited though!

**Comment by CourtneyHum** [comment]
Hi Peter,
I don't seem to see it in the HPO browser. Does it go by a different name?
[image: Inline image 1]

On Sat, Jun 11, 2016 at 3:55 AM, Peter Robinson <notifications@github.com>
wrote:

> A term Anomia already exists (HP_0030784) as a child of neurological
> speech impairment (HP:0002167). I have added an xref to the article you
> cited though!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/obophenotype/human-phenotype-ontology/issues/909#issuecomment-225343160>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ALZYM7tBsZUPPgphig6NWSvs0w3xx1sjks5qKmnwgaJpZM4IzNZW>
> .
>



-- 
Courtney Hum, MSc
Genetic Counsellor
Centre for Computational Medicine
The Hospital for Sick Children
T: 416-813-7654 x414028
