### ISSUE TITLE
NTR: Peroxisomes reduced or absent by immunohistochemistry (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9094]
New term request Peroxisomes reduced or absent by immunohistochemistry (segal_070726200601):   UMLS: 4314559

**Comment by pnrobinson** [comment]
@MickeySegal
I am struggling to find a PubMed reference that describes how this phenotype is measured. Do you have one on hand?

**Comment by MickeySegal** [comment]
https://www.omim.org/entry/614388 describes "immunofluorescence microscopic analyses showed fewer peroxisomes in fibroblasts compared to controls".

**Comment by pnrobinson** [comment]
See -- 614862 
PMID: 8940266 1/1
The immunohistochemical staining of cultured fibroblasts from this patient indicated the absence of peroxisomes
and confirmed the diagnosis of ZS.

**Comment by MickeySegal** [comment]
Right.

**Comment by pnrobinson** [comment]
@MickeySegal adding 
HP:0034554, Paucity of peroxisomes, def: Reduced number of observable peroxisomes per cell. This feature can be observed by  immunohistochemical staining of cultured cells (such as fibroblasts) or by electronmicroscopy.
and
HP:0034553, Absence of peroxisomes, def: Lack of observable peroxisomes. This feature can be observed by  immunohistochemical staining of cultured cells (such as fibroblasts) or by electronmicroscopy.
