### ISSUE TITLE
NTR: Brain biopsy: tubuloreticular inclusions (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9095]
New term request Brain biopsy: tubuloreticular inclusions (segal_071011164826):

**Comment by pnrobinson** [comment]
@MickeySegal
are we referring to this phenotype?
https://pubmed.ncbi.nlm.nih.gov/2839949/

**Comment by pnrobinson** [comment]
@MickeySegal
updates? :-0

**Comment by MickeySegal** [comment]
I don't remember the history here but we deleted this finding.  Maybe we preferred to check in muscle: https://hpo.jax.org/app/browse/term/HP:0100302

**Comment by pnrobinson** [comment]
OK, closing!
