### ISSUE TITLE
NTR: Glutaryl-CoA dehydrogenase low in fibroblasts or leukocytes (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9097]
New term request Glutaryl-CoA dehydrogenase low in fibroblasts or leukocytes (segal_071031152001):

**Comment by pnrobinson** [comment]
@MickeySegal
adding as

Reduced glutaryl-CoA dehydrogenase activity
def: Diminished activity of the enzyme glutaryl-CoA dehydrogenase, a key enzyme in the degradative pathways of l-lysine, l-hydroxylysine, and l-tryptophan.PMID:16641220

**Comment by MickeySegal** [comment]
Please add the HPO code.
