### ISSUE TITLE
NTR: Carnitine uptake low in fibroblasts (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9100]
New term request Carnitine uptake low in fibroblasts (segal_071120220955): Transport  UMLS: 2749743

**Comment by pnrobinson** [comment]
@MickeySegal
I am wondering if the "uptake" of Carnitine is measured, of if it is an inference if we see

Increased urinary carnitine
Decreased carnitine in serum, muscle, heart, and liver 

If this term is intended for this disease (https://omim.org/entry/212140?search=%22carnitine%20uptake%20defect%22&highlight=%22carnitine%20uptake%20defect%22) perhaps we should rely on the existing terms?

**Comment by MickeySegal** [comment]
We used the same reference, representing "A defect in the plasma membrane carnitine transporter was confirmed by carnitine uptake assay on fibroblast cultures".  Which existing term do you suggest?

**Comment by pnrobinson** [comment]
@MickeySegal 
this sounds like an assay that was used in the cited research studies but not something one would encounter in the clinic. I would suggest we not make an HPO term because it would not be used prospectively.

**Comment by MickeySegal** [comment]
It is listed in the GeneReviews article: 
https://www.ncbi.nlm.nih.gov/books/NBK84551/
Fibroblast carnitine transport (uptake). Carnitine transport in skin fibroblasts from affected individuals is typically reduced below 10% of control rates
