### ISSUE TITLE
NTR: Long-chain 2-enoyl-CoA hydratase activity low in fibroblasts (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9102]
New term request Long-chain 2-enoyl-CoA hydratase activity low in fibroblasts (segal_071121191708):   UMLS: 2675272

**Comment by pnrobinson** [comment]
@MickeySegal,
do we mean this enzyme?
https://omim.org/entry/608205

**Comment by MickeySegal** [comment]
Our term is also from https://omim.org/entry/609015 "long-chain 2-enoyl-CoA hydratase".

**Comment by pnrobinson** [comment]
@MickeySegal 

Adding new term: 
- ID: HP:6001023
- label: Diminished long-chain-enoyl-CoA hydratase
- parents: 
- pmid: 
- def: Concentration or activity of long-chain-enoyl-CoA hydratase (EC 4.2.1.74) as measured in cultured fibroblasts is below the limits of normal.
- comment: 
- orcid: orcid:0000-0002-0736-9199
- github ID: https://github.com/obophenotype/human-phenotype-ontology/issues/9102
- synonyms:
