### ISSUE TITLE
NTR: SCAD activity low in fibroblasts (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9104]
New term request SCAD activity low in fibroblasts (segal_071121194033): Short chain acyl CoA dehydrogenase; butyryl-CoA dehydrogenase

**Comment by pnrobinson** [comment]
@MickeySegal
similar to several recent other issues, here is a suggestionm please let me know before we finalzie
Label: Reduced Short-chain acyl-CoA dehydrogenase activity
Def: Diminished activbity of the enzyme Short-chain acyl-CoA dehydrogenase (SCAD), a key enzyme of fatty acid beta‐oxidation that catalyses the first step in mitochondrial beta‐oxidation of fatty acids.
PMID:26989860

**Comment by MickeySegal** [comment]
Fine.

**Comment by pnrobinson** [comment]
@MickeySegal 
added as 
HP:0034690

**Comment by MickeySegal** [comment]
I had neglected to point out the typo:
Diminished **activbity** of the enzyme Short-chain...

**Comment by pnrobinson** [comment]
fixed the above error, thanks!
