### ISSUE TITLE
NTR: Sterol 27-hydroxylase low in fibroblasts, liver, and leukocytes (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9107]
New term request Sterol 27-hydroxylase low in fibroblasts, liver, and leukocytes (segal_080310175548):   UMLS: 1859268

**Comment by pnrobinson** [comment]
@MickeySegal
similar to previous issue, please let me know if you have suggestions before we add this
Label: Reduced sterol 27-hydroxylase activity
Definition: Diminished activity of the enzyme sterol 27-hydroxylase, which participates in the degradation of cholesterol to bile acid. Sterol 27-hydroxylase catalyzes the first step in the normal oxidation of the steroid side chain, converting cholesterol, as well as different 7a-hydroxylated cholesterol metabolites, to 27-oxygenated steroids.
PMID:10856919

**Comment by MickeySegal** [comment]
This is fine.

**Comment by pnrobinson** [comment]
@MickeySegal 
added as HP:0034689
