### ISSUE TITLE
NTR: Cerebroside sulfate hydrolysis low by growing fibroblasts (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9109]
New term request Cerebroside sulfate hydrolysis low by growing fibroblasts (segal_080402190926):

**Comment by pnrobinson** [comment]
@MickeySegal
I would suggest we not specify "in fibroblasts" since this is probably a very general finding that is just easy to measure in fibroblasts -- let me know if you have suggestions before we add this.

Label: Impaired cerebroside sulfate hydrolysis
Definition: Reduced hydrolysis (splitting of a bond and the addition of the hydrogen anion of water) of the sulfuric ester linkage in the molecule of cerebroside sulfate, possibly leading to accumuation of cerebroside sulfate.
PMID:6137805

This feature can be assayed by cerebroside sulfate loading tests of cultured dermal fibroblasts.
PMID: 6137805

**Comment by MickeySegal** [comment]
That is fine.  We often specify how a result is determined because we group the findings into bundles (e.g., head MRI), which if ordered give the status of many findings.  But that is not a consideration that applies to what you are doing so it makes sense for you to use a more general finding.

**Comment by pnrobinson** [comment]
@MickeySegal 
added as HP:0034687
