### ISSUE TITLE
Parameters for immunology terms

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#911]
I am putting this here to keep track of things. We will be creating terms for the following parameters with our immunology colleagues here in Berlin.

T-Zellen:

CD4

CD8

CD45RA+CCR7+ (naïve)

CD45RA-CCR7+ (central memory)

CD45RA-CCR7- (effector memory)

CD45RA+CCR7- (TEMRA)

CD3+CD4-CD8- TCR V alpha/beta (DNT)

CD3 TCR V gamma/delta

 

B-Zellen:

CD19+

CD19+IgD+CD27- (naïve)

CD19+IgD+IgM+CD27+ (MZ-like)

CD19+IgD-IgM-CD27+ (class switched memory)

CD19+CD21lowCD38low (activiated)

CD19+CD21lowCD38++IgM+ (transitional)

CD19+CD21lowCD38++IgM- (switched plasmablast)

 

Weitere Leukozyten:

NK Zellen

Neutrophile Granulozyten

Eosinophile Granulozyten

Basophile Granulozyten

Monozyten

 

Antikörper:

IgG

IgA

IgM

IgE

IgG Subklassen IgG1 bis IgG4

Tetanus Impfantwort

Pneumokokken-Impfantwort

**Comment by cmungall** [comment]
Remember, the hierarchy in the CL has received a lot of attention here

**Comment by pnrobinson** [comment]
I  have transferred this item to the HPO wiki on this github repository
