### ISSUE TITLE
NTR: Creatine uptake low in fibroblasts (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9114]
New term request Creatine uptake low in fibroblasts (segal_090513172132):   UMLS: 1845871

**Comment by pnrobinson** [comment]
@MickeySegal
as far as I can see this is an extremely specialized assay that is rarely performed in research settings but it does not seem to be a clinical assay (which would make it in scope for HPO). Could you provide more context please?

**Comment by MickeySegal** [comment]
We have this only for "Cerebral creatine deficiency syndrome" (using OMIM name, but the SLC6A8-related transporter form) but https://www.ncbi.nlm.nih.gov/books/NBK3794/ says "Creatine uptake in the individual's cultured skin fibroblasts will be required to confirm biochemical diagnosis of CRTR deficiency in males."

**Comment by pnrobinson** [comment]
But looking at the diagnostic algorithm, this assay is not mentioned, I think it probably is research only and the statement might predate genomics. I will close for now, but if we can find a lab test or recent publication let's reopen.

**Comment by MickeySegal** [comment]
I've emailed Margaret Adam of GeneReviews to resolve the apparent discrepancy, and copied you.
