### ISSUE TITLE
Make CI check for synonyms across HP and MP

### ISSUE THREAD

**Issue by mellybelly** [obophenotype/human-phenotype-ontology#912]
We can leverage work across the two ontologies if we examine synonym discrepancies for equivalent classes. 

@cmungall @drseb @balhoff

**Comment by pnrobinson** [comment]
This item has not been active. Is this something we want to address or canthis request be closed?

**Comment by cmungall** [comment]
Move to upheno

**Comment by cmungall** [comment]
This issue was moved to obophenotype/upheno#206
