### ISSUE TITLE
NTR: Cardiac biopsy: mononuclear myocarditis (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9120]
New term request Cardiac biopsy: mononuclear myocarditis (elthat_100424153900): Heart

**Comment by pnrobinson** [comment]
@MickeySegal
this seems to be a characteristic of all active Myocarditis, rather than a subform of Myocarditis?
The HPO is starting to work on a separate branch of biopsy findings (since the would live somwhere else, it would avaid redundancy). 
Possibly we should not add this term now, unless there are other subforms of myocarditis that can be clearly delineating from this.

**Comment by MickeySegal** [comment]
I agree that using https://hpo.jax.org/app/browse/term/HP:0012819 makes more sense.

**Comment by pnrobinson** [comment]
OK, closing
