### ISSUE TITLE
NTR: Liver biopsy: adenocarcinoma (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9123]
New term request Liver biopsy: adenocarcinoma (elthat_100428052910): Hepatic biopsy  UMLS: 0948680

**Comment by pnrobinson** [comment]
@MickeySegal
can you specify which cancer is meant? 
I do not find an exact match in NCIT
https://www.ebi.ac.uk/ols4/ontologies/ncit/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FNCIT_C8609?lang=en

**Comment by pnrobinson** [comment]
@MickeySegal 
I cannot find any other reference to this. The "adeno" refers to a gland, and the liver itself does not have a gland outside of the bile system, so I am guessing that this reference is incorrect.
The following term is a kind of adenocarcinoma of the bile system:
Cholangiocarcinoma HP:0030153

**Comment by MickeySegal** [comment]
Agree, though UMLS has https://www.ncbi.nlm.nih.gov/medgen/C0948680.  I merged this finding into Cholangiocarcinoma.
