### ISSUE TITLE
NTR: Biliary biopsy: adenocarcinoma (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9124]
New term request Biliary biopsy: adenocarcinoma (elthat_100428053121):   UMLS: 5428732

**Comment by pnrobinson** [comment]
@MickeySegal

is this meant: Bile Duct Adenocarcinoma
https://www.ebi.ac.uk/ols4/ontologies/ncit/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FNCIT_C27813?lang=en

**Comment by MickeySegal** [comment]
We have it from https://www.ncbi.nlm.nih.gov/books/NBK1402/ "adenocarcinomas of the liver and gall bladder".

**Comment by pnrobinson** [comment]
@MickeySegal 
the terminology is used incosnsistently, it seems, but I think this is largely synonymous with  [Cholangiocarcinoma HP:0030153](https://hpo.jax.org/browse/term/HP:0030153)
see also:
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5401855/

thoughts?

**Comment by pnrobinson** [comment]
thanks, closing.
