### ISSUE TITLE
NTR: Modifier: Renal biopsy: acute proliferative and exudative character to glomerulonephritis (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9132]
New term request Modifier: Renal biopsy: acute proliferative and exudative character to glomerulonephritis (elthat_100516234132): Kidney

**Comment by pnrobinson** [comment]
@MickeySegal
this is bundled into three items, but we could use
Acute HP:0011009
I am thinking it is probably not a good idea to model the "proliferative" and "exudative" at this time. Over the next few years, the HPO will be doing biopsy findings/pathology and we can return to this, but I think it needs a concerted effort and on-site workshops to come up with something that is comprehensive and logical.

**Comment by MickeySegal** [comment]
I deleted our finding because we no longer have it applied to any disease.  We have checks for such situations, but they are not applied to findings in a bundle, here renal biopsy.  

I note, however, that you have some similar findings such as  https://hpo.jax.org/browse/term/HP:0000793.
