### ISSUE TITLE
New terms and revision of HPO terms associated to pulmonary arterial hypertension (PAH)

### ISSUE THREAD

**Issue by lcdaugherty** [obophenotype/human-phenotype-ontology#914]
On behalf of the BRIDGE consortium we have been looking at HPO terms relevant to patients with pulmonary arterial hypertension, with a particular focus on idiopathic PAH. We thought it might be useful to create some new terms and a broad structure for pulmonary hypertension which can be added to in the future.

Overview:
13 HPO PAH related new terms proposed (with definitions and proposed superclass/hierarchy)
6 Definition/synonym/name revisions
1 Hierarchy revision
4 Subclass/Superclass revisions 

The attached files :
BRIDGE_PAH_HPO_terms_20160616.xlsx
This file includes definitions, superclass terms (parents) and additional comments from us to explain our reasoning.

BRIDGE_PAH_HPO_graphs_20160616.pptx
Graphs showing a reduced set of terms to explain the proposed hierarchy revision. 
Graph A1 (current  hierarchy) and Graph A2 (proposed  hierarchy). 
We are proposing this change because Right ventricular failure (HP:0001708), Impaired left ventricular function (HP:0005162), Left ventricular diastolic dysfunction on cardiac imaging (new HPO) and Left ventricular systolic dysfunction on cardiac imaging (new HPO) all belong to functional abnormality, but currently they are mapped to morphological abnormality.

This has been verified by a team of experts in the field including Dr Charaka Hadinnapola (Research Fellow Pulmonary Vascular Diseases Unit, Papworth Hospital NHS Foundation Trust), Professor Nick Morrell (Cardiopulmonary physician and Head for cardiovascular research at the NIHR Biomedical Research Centre, Cambridge University Hospitals NHS Foundation Trust) and  Dr Simon Holden (Consultant Clinical Geneticist at Cambridge University Hospitals NHS Foundation Trust).

Best regards
Louise Daugherty- Pertinent Findings & Genomic Vigilance Specialist
NIHR BioResource - Rare Diseases Study (NIHRBR-RD)

[BRIDGE_PAH_HPO terms_20160616.xlsx](https://github.com/obophenotype/human-phenotype-ontology/files/318439/BRIDGE_PAH_HPO.terms_20160616.xlsx)
[BRIDGE_PAH_HPO_graphs_20160616.pptx](https://github.com/obophenotype/human-phenotype-ontology/files/318440/BRIDGE_PAH_HPO_graphs_20160616.pptx)

**Comment by pnrobinson** [comment]
I am closing this, as all items have ben attended to.
