### ISSUE TITLE
NTR: Colorectal biopsy: cancer (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9145]
New term request Colorectal biopsy: cancer (elthat_100322151141): Colonic  UMLS: 0009402

**Comment by pnrobinson** [comment]
@MickeySegal

this is a very general term.
Possibly it is close enough to

Neoplasm of the large intestine HP:0100834

or
Colon cancer HP:0003003

?

**Comment by MickeySegal** [comment]
Those are fine.

**Comment by pnrobinson** [comment]
ok closing
