### ISSUE TITLE
NTR: Neoplasia, multiple primary (not metastatic) (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9147]
New term request Neoplasia, multiple primary (not metastatic) (elthat_100304141616):   UMLS: 0027663

**Comment by pnrobinson** [comment]
@MickeySegal
if the same patient has more than one tumour then we would annotate to each of the tumors. This kind of combination is not a good HPO term.

**Comment by MickeySegal** [comment]
The idea is not that the patient has many different types of tumors.  The idea is that there are many tumors of the same type, e.g., 
https://www.omim.org/entry/615554
"Fibroadenoma represents a benign breast disease characterized by lobuloalveolar growth with abnormally high proliferation of the epithelium. Patients with more than 3 fibroadenomas in 1 breast are considered to have multiple fibroadenomas"

I've changed our finding name to use "multiple primary of the same type" but you may have better wording.
