### ISSUE TITLE
NTR: Liver biopsy: bile duct proliferation (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9152]
New term request Liver biopsy: bile duct proliferation (elthat_100527012614): Hepatic biopsy  UMLS: 2677001

**Comment by pnrobinson** [comment]
@MickeySegal
this is [Bile duct proliferation HP:0001408](https://hpo.jax.org/app/browse/term/HP:0001408)

**Comment by MickeySegal** [comment]
The terminology is identical to ours so I'm surprised I didn't find it unless it is newer than the version I searched.
