### ISSUE TITLE
NTR: Bone marrow: double-nucleated erythroblasts (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9155]
New term request Bone marrow: double-nucleated erythroblasts (elthat_100622034302): Binuclearity

**Comment by pnrobinson** [comment]
@MickeySegal

is it sufficient to have this term 
[Multinucleated erythroblast HP:0034278](https://hpo.jax.org/app/browse/term/HP:0034278)
?

**Comment by MickeySegal** [comment]
https://www.ncbi.nlm.nih.gov/books/NBK5313/  "On light microscopy, erythroid hyperplasia, few double-nucleated erythroblasts, and interchromatin bridges between erythroblasts (in 0.6%-2.8% of erythroblasts)"

I could either merge or split; I'll follow what you think is appropriate.

**Comment by pnrobinson** [comment]
@MickeySegal 
I am not a specialist in this area, but I did not find any source that suggested that bi vs. multinucleated erythroblsts ahve a different meaning in the differential, so I will add Binucleated as a narrow synonym for now. If there is more information about a relevant difference, we can add a separate term later.
