### ISSUE TITLE
NTR: Lung biopsy: occlusion of small pulmonary arteries (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9163]
New term request Lung biopsy: occlusion of small pulmonary arteries (elthat_100722021746): Pulmonary

**Comment by pnrobinson** [comment]
@MickeySegal
@mgriese

Is this different from [Peripheral pulmonary artery stenosis HP:0004969](https://hpo.jax.org/app/browse/term/HP:0004969) ?

**Comment by MickeySegal** [comment]
Seems the same.

**Comment by pnrobinson** [comment]
I will add as a related synonym, closing
