### ISSUE TITLE
NTR: Skin biopsy: keratin 5 or 14 antibody staining abnormal or absent by immunofluorescent antibody/antigen mapping (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9165]
New term request Skin biopsy: keratin 5 or 14 antibody staining abnormal or absent by immunofluorescent antibody/antigen mapping (elthat_100807150040):

**Comment by pnrobinson** [comment]
@MickeySegal
normally we would want to have separate terms for each item unless there is some reason to bundle?

**Comment by MickeySegal** [comment]
You are right.  Table 4 in https://www.ncbi.nlm.nih.gov/books/NBK1369/ updates criteria to separate keratin 5 and 14.  We will split our finding and expect 2 HPO codes.

**Comment by pnrobinson** [comment]
@MickeySegal 
adding

Reduced epidermal keratin 5 protein expression
HP:0035002

and

Reduced epidermal keratin 14 protein expression
HP:0035003
