### ISSUE TITLE
NTR: Skin biopsy: collagen VII intracellular retention on EM (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9172]
New term request Skin biopsy: collagen VII intracellular retention on EM (elthat_100812035049): Electron microscopy

**Comment by pnrobinson** [comment]
@MickeySegal
I think this can also be seen by immunofluorescence, I would add the term like this:

Label: Intracellular accumulation of collagen VII

Comment: Collagen VII is the major molecular constituent of anchoring fibrils in the skin. Collagen VII is synthesized as three identical pro-alpha1(VII) polypeptide chains, which are hydroxylated and glycosylated in a coordinated manner and then fold into triple-helical procollagen VII in the endoplasmic reticulum (ER). Mature collagen VII undergoes a multistep fibril polymerization process to form the anchoring fibrils. Mutant pro-alpha1(VII) polypeptide chains or procollagen VII molecules do not pass the ER quality control and are retained in the ER or designated for ubiquitin-proteasome degradation resulting in reduced amounts of collagen VII in the skin. See Figure 2B of PMID:8288900.

PMID:19726672
PMID: 8288900

**Comment by MickeySegal** [comment]
That is fine.

**Comment by pnrobinson** [comment]
added as 
HP:0034999
