### ISSUE TITLE
NTR: Bone marrow: dyserythropoiesis (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9180]
New term request Bone marrow: dyserythropoiesis (elthat_100822140336): Defective development of erythrocytes, RBCs, red blood cells; ineffective  UMLS: 3551071

**Comment by pnrobinson** [comment]
@MickeySegal
is this a synonym of [Erythroid dysplasia HP:0031688](https://hpo.jax.org/app/browse/term/HP:0031688) ?

**Comment by MickeySegal** [comment]
This is stretching my knowledge of hematology, but https://onlinelibrary.wiley.com/doi/full/10.1111/bjh.15435 shows a lot of overlap between the terms, particularly in Table 2.  Each seems to be used as a finding and in disease names, and I don't see a clear distinction in how the terms are used.

**Comment by pnrobinson** [comment]
@MickeySegal 
I cannot find a distinction, so I will add dyserythropoiesis as a synonym to the above term

**Comment by pnrobinson** [comment]
done

**Comment by MickeySegal** [comment]
I see we have also associated https://hpo.jax.org/app/browse/term/HP:0010972 with our term.  The distinction with https://hpo.jax.org/app/browse/term/HP:0031688 is not obvious.

**Comment by pnrobinson** [comment]
The anemia of inadequae production is a phenotype of peripheral blood and this is a phenotype of the bone marrow. Of course in the end they go together but the HPO does not model pathophysiology.
