### ISSUE TITLE
NTR: Corneal biopsy: disorganized collagen fibrils on transmission electron microscopy (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9182]
New term request Corneal biopsy: disorganized collagen fibrils on transmission electron microscopy (elthat_100826013922):

**Comment by MickeySegal** [comment]
https://www.ncbi.nlm.nih.gov/books/NBK2690/
"Corneal transparency requires that collagen fibrils be properly organized with a uniform diameter and a regular interfibrillar space. Congenital stromal corneal dystrophy (CSCD) is characterized by stromal opacities throughout the cornea. By transmission electron microscopy these opacities are seen as layers of amorphous material with thin filaments. The reported DCN pathogenic variants all lead to formation of a truncated decorin that has a tendency to aggregate in vitro."

**Comment by pnrobinson** [comment]
@MickeySegal 
The cited article states this: "Areas of amorphous substance with small filaments disrupted layers of apparently normal collagen fibrils. These areas were often located in the immediate vicinity of keratocytes. In some places, the lamellar structure of collagen fibrils appeared to disintegrate". 
There seems to be some mix up or am I misunderstanding?

**Comment by MickeySegal** [comment]
I don't see that quote in https://www.ncbi.nlm.nih.gov/books/NBK2690/ but it seems consistent with the quote a provided.

**Comment by pnrobinson** [comment]
@MickeySegal 
what I mean is that this description is for electron microcroscopy that was done during a research study and is unlikely to be used in the clinics, where this description would work "HP:0007759 Opacification of the corneal stroma". 
It is hard to make an HPO from a "narrative description" like that since future users would not have a clear way to decide if the term applies.

**Comment by MickeySegal** [comment]
We already have HP:0007759 so if you think that "disorganized collagen fibrils on transmission electron microscopy" we can delete it.  We only have it for https://omim.org/entry/610048
