### ISSUE TITLE
NTR: Skin biopsy: enlarged venous-like channels with flattened endothelium (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9185]
New term request Skin biopsy: enlarged venous-like channels with flattened endothelium (elthat_100911171230):

**Comment by pnrobinson** [comment]
@MickeySegal

this term and also #9186 is bundled.
What is a venous-like channel?

**Comment by MickeySegal** [comment]
https://www.ncbi.nlm.nih.gov/books/NBK1967/ "Enlarged venous-like channels with walls of smooth muscle of variable thickness are observed in TEK-related VM [Vikkula et al 1996]."

The flattened endothelium seems too bundled so I removed it from our finding.

**Comment by pnrobinson** [comment]
@MickeySegal 
I am wondering if this is actually just a characteristic of [Venous malformation HP:0012721](https://hpo.jax.org/app/browse/term/HP:0012721)
See for instance: "Venous malformations (VMs), the most common errors of vascular morphogenesis in humans, are composed of dilated, serpiginous channels. " (https://pubmed.ncbi.nlm.nih.gov/8980225/).

So unless we can distingusih the two, then probably Venous malformation HP:0012721 should be used ?

**Comment by MickeySegal** [comment]
OK.  Deleting.
