### ISSUE TITLE
NTR: Gonadal biopsy: peritubular fibrosis (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9188]
New term request Gonadal biopsy: peritubular fibrosis (elthat_100924023959): Part of dysgenetic gonads  UMLS: 4231203

**Comment by pnrobinson** [comment]
@MickeySegal
Do you mean Testicular peritubular fibrosis
Def: Thickening of the region surrounding the seminiferous tubules of the testis dues to deposition of excess connective tissue (fibrosis).

**Comment by pnrobinson** [comment]
@MagoWyr how does this fit in with the new terms we are discussing?

**Comment by MagoWyr** [comment]
Dieser Begriff ist am ehesten ein Synonym fuer den Term Tubular shadows
________________________________

**Comment by pnrobinson** [comment]
@MickeySegal  -- this is probably a synonym for the term Tubular shadows that we recently introduced. This term will be on the public HPO website by Aug 1. Can we discuss this in the second half of August?

**Comment by pnrobinson** [comment]
OK, closing, Tubular shadows is a term HP:0034945
