### ISSUE TITLE
NTR: Gonadal biopsy: germ cells decreased or absent (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9189]
New term request Gonadal biopsy: germ cells decreased or absent (elthat_100924024054): Germinal aplasia, part of dysgenetic gonads  UMLS: 4229925

**Comment by pnrobinson** [comment]
@MickeySegal
At least for males, I think this is the same as [Sertoli cell-only phenotype HP:0034299](Sertoli cell-only phenotype HP:0034299) ?  It might be better to add parentage to [Abnormal germ cell morphology HP:0012862 ](https://hpo.jax.org/app/browse/term/HP:0012862) as well?
Is it better to specific male vs female phenotypes?

**Comment by MickeySegal** [comment]
It seems a more general term is needed.  

In Y chromosome infertility https://www.ncbi.nlm.nih.gov/books/NBK1339/
Testicular biopsy. Testicular biopsy may reveal either one or a combination of the following:
1. Sertoli cell-only (SCO) syndrome, in which azoospermia is associated with the absence of or only occasional germ cells in tubules that for the most part have only Sertoli cells lining them with no or rare spermatogenesis
2. Maturation arrest with spermatocytes but no spermatids or mature sperm

In 46,XY DSD https://www.ncbi.nlm.nih.gov/books/NBK1547/
Gonadal findings, as determined by a combination of physical examination, imaging, and hormonal testing (and on occasion histologic examination; see Note), can range over the following spectrum:
1. Normal testis
2. Ovotestis
3. Dysgenetic testis (decreased size and number of seminiferous tubules, reduced number or absence of germ cells, peritubular fibrosis, and hyperplasia of Leydig cells)
4. Streak gonad

**Comment by pnrobinson** [comment]
@MagoWyr how does this fit in with the new terms we are discussing?

**Comment by MagoWyr** [comment]
Wenn die Germ Cells "absent" sind, ist dies ist eine andere Beschreibung fuer den Sertoli cell-only Phänotyp (SCO). Man koennte diesen Term dann als Synonym verwenden. Wenn die germ cells nur "decreased" sind, ist es eher ein Synonym fuer Hypospermatogenesis. Insgesammt ist der hier genannte Begriff aber unspezifisch und nicht haeufig gebraucht.
________________________________

**Comment by pnrobinson** [comment]
@MickeySegal 
translating, -- Absent germ cells is another description for Sertoli cell-only Phenotype (SCO). Decreased germ cells would be a synonym for Hypospermatogenesis. But "Gonadal biopsy: germ cells decreased or absent " is unsüpecific and not commonly used.
-- Mickey, we have revised the entire section (for males) and it may be different from when you last looked. Currently, it is difficult to build a hierarchy that is general for M,F,DSD and this is probably only something that we would try in an on-site workshop. I am going to close this term now acknowledging that additional work will need to be done on this subhierarchy, but that it cannot be done via github issues.
