### ISSUE TITLE
NTR: Gonadal biopsy: completely undeveloped streak gonads (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9190]
New term request Gonadal biopsy: completely undeveloped streak gonads (elthat_100925170502):   UMLS: 5194310

**Comment by pnrobinson** [comment]
@MickeySegal

Is this different from [Streak ovary HP:0010464 ](https://hpo.jax.org/app/browse/term/HP:0010464) (for the ovary), i.e., is "completely undeveloped" a differentiator? I think maybe "streak" already implies that? I do not think the HP) currently has a related term for testis

**Comment by MickeySegal** [comment]
That fits.  The terminology situation is complicated since many of the diseases with this finding are sex reversal disorders.

**Comment by pnrobinson** [comment]
613762 
PMID: 21129722  9/12

**Comment by MickeySegal** [comment]
Right.  https://omim.org/entry/613762 uses the more general term of "streak gonads".  That would make sense as parent of streak ovary, streak ovotestis etc.

**Comment by pnrobinson** [comment]
@MickeySegal 

I think that the intention of the existing term
[Gonadal dysgenesis HP:0000133](https://hpo.jax.org/app/browse/term/HP:0000133)
is essentially the same as Streak gonad

I need to look at the annotated diseases and make sure this is true.

**Comment by pnrobinson** [comment]
@MickeySegal 
on second thought, streak gonad is a suntype of gonadal dysgenesis.
Created a new term
HP:0025733
Streak gonad
def: A type of gonadal dysgenesis in which the gonadal tissue is underdeveloped and appears as fibrous, streak-like structures instead of fully formed ovaries or testes.
