### ISSUE TITLE
NTR: Collagen type I synthesis by fibroblasts abnormal in vitro (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9192]
New term request Collagen type I synthesis by fibroblasts abnormal in vitro (elthat_101012014513):

**Comment by MickeySegal** [comment]
The discussion in https://www.ncbi.nlm.nih.gov/books/NBK1279/ was vague, as was the discussion in    https://www.ncbi.nlm.nih.gov/books/NBK1295/, so I looked at the cited reference in the latter: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1683590/.  It described two types of abnormality: low amounts of normal collagen in some patients, and abnormal collagen in others.  
But https://www.ncbi.nlm.nih.gov/books/NBK1295/ says that "Biochemical analysis is essentially no longer used clinically with the advances in molecular diagnostics." so I've deleted the finding.

**Comment by pnrobinson** [comment]
OK!
