### ISSUE TITLE
NTR: Brain biopsy: neuroepithelial cyst (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9195]
New term request Brain biopsy: neuroepithelial cyst (elthat_101024163849): Neuroglial cyst; colloid cyst  UMLS: 0338600

**Comment by pnrobinson** [comment]
@MickeySegal
I believe these lesions can also be ascertained by imaging, and the HPO would not include "biopsy" in the label or definition.

adding as HP_0034485

definition:
A benign epithelial-lined cystic lesion that can occur anywhere in the neuraxis. Neuroepithelial cysts are ependymal or epithelial lined fluid collections of unknown etiology within the central nervous system parenchyma with no
obvious ventricular or subarachnoid connection. Most cysts are asymptomatic, however, some present
with seizures, mass effect, or rarely with movement disorders. On imaging, they present as CSF-like parenchymal cysts with smooth, rounded borders and minimal or no surrounding signal intensity abnormality.
PMID:14672275

**Comment by MickeySegal** [comment]
You can a colloid cyst by imaging.  I'm not sure about the other types, but since you don't need the method of ascertainment in your findings that is not an issue for you.
