### ISSUE TITLE
NTR: Bone biopsy: chondrocytes hypertrophy (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9211]
New term request Bone biopsy: chondrocytes hypertrophy (elthat_101205180616): Hypertrophic; Enlarged  UMLS: 2749580

**Comment by pnrobinson** [comment]
@MickeySegal
chondrocyte hypertrophy  is a normal part of bone development,
https://pubmed.ncbi.nlm.nih.gov/24677724/

Can you provide more context about the abnormality?

**Comment by MickeySegal** [comment]
https://ojrd.biomedcentral.com/articles/10.1186/1750-1172-5-29 "In the first publications describing this syndrome, a defect in ossification was well documented on bone biopsy, with particular abnormalities of the cartilage in the form of hypertrophic chondrocytes. Further studies reported an irregular proliferation of chondrocytes in the resting cartilage, with the presence of excessively thin ramified collagen fibers in the spongy bone."

**Comment by pnrobinson** [comment]
@azankl can you help with this term? What is the best way of describing these chondrocytes so there is no chance of confusion with normal chondrocyte hypertrophy?

**Comment by azankl** [comment]
I think what the authors of the OJRD article want to say is that the abnormalities in the cartilage affect specifically the hypertrophic chondrocytes. Here is Fig 2 from the original paper of Wolcott and Rallison (PMID:5008828):
<img width="1011" alt="Screenshot 2024-01-08 at 9 35 25 pm" src="https://github.com/obophenotype/human-phenotype-ontology/assets/4812335/fc281970-52aa-4f64-8b72-ee54a67499d1">
As stated in the legend, the area of cartilage vacuolation is narrow and the zone of provisional calcification is essentially nonexistent. We could create 2 new HPO terms for this (as children of HP:0003336 Abnormal enchondral ossification and/or Abnormal growth plate morphology HP:0025368):
1. reduced zone of chondrocyte hypertrophy
2. reduced zone of provisional calcification

**Comment by MickeySegal** [comment]
Our only use of this finding was for "Wolcott-Rallison syndrome" and this seems like a very research-oriented test, so I will delete this finding and it may not be necessary to have terms of this type.

**Comment by pnrobinson** [comment]
Thanks, both, let's hold off for now on creating this term, I agree it is unlikely to be used in clinical practice.
