### ISSUE TITLE
NTR: Liver biopsy: carbamoyl phosphate synthetase activity low (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9217]
New term request Liver biopsy: carbamoyl phosphate synthetase activity low (elthat_110106021545): CPS low on hepatic biopsy

**Comment by pnrobinson** [comment]
@MickeySegal
this is
[Reduced hepatic carbamoylphosphate synthetase activity HP:0034996](https://hpo.jax.org/app/browse/term/HP:0034996)

**Comment by pnrobinson** [comment]
@MickeySegal
Coming back to this, I think we need to have carbamoyl phosphate synthetase 1 and 2 terms -- the activities are different

**Comment by MickeySegal** [comment]
OK.  We use carbamoyl phosphate synthetase 1 and for https://omim.org/entry/616457 it was not clear whether the carbamoyl phosphate synthetase 2 activity in https://omim.org/entry/114010 is measured separately or as CAD in total.

**Comment by pnrobinson** [comment]
updating to 
Reduced hepatic carbamoylphosphate synthetase 1 activity
[HP:0034996](https://hpo.jax.org/app/browse/term/HP:0034996)

**Comment by pnrobinson** [comment]
@MickeySegal 
I am not sure that the "2" activity is a clinical test. I do think it is measured spearately though, see https://www.sciencedirect.com/topics/biochemistry-genetics-and-molecular-biology/carbamoyl-phosphate-synthetase --
Although both CPS activities are readily found in cells such as periportal hepatocytes, the CAD-associated CPS-2 activity is located in the cytoplasm, while that for CPS-1 is specific for mitochondria, where it functions primarily in the [urea cycle](https://www.sciencedirect.com/topics/biochemistry-genetics-and-molecular-biology/urea-cycle).

I cannot find usages for the "2" in clinical testing so am not convinced we need a separate term at this time. Please reopen if this is wrong.
