### ISSUE TITLE
NTR: Peritoneal biopsy: papillary serous carcinoma (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9220]
New term request Peritoneal biopsy: papillary serous carcinoma (elthat_110209011656):   UMLS: 3839184

**Comment by pnrobinson** [comment]
@MickeySegal
are we referring to this 
[Primary Peritoneal Serous Papillary Adenocarcinoma](https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C7695) ?

**Comment by MickeySegal** [comment]
Our finding is from https://www.ncbi.nlm.nih.gov/books/NBK1247/ "Ovarian cancer and primary papillary serous carcinoma of the peritoneum are considerably more common and tend to develop at an earlier age in women with a germline BRCA1 pathogenic variant as compared to women with a germline BRCA2 pathogenic variant".

**Comment by pnrobinson** [comment]
@MickeySegal 
adding
Primary peritoneal serous papillary adenocarcinoma
HP:0430116
