### ISSUE TITLE
NTR: Renal biopsy: renin immunostaining decreased (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9221]
New term request Renal biopsy: renin immunostaining decreased (elthat_110304030113): Kidney

**Comment by pnrobinson** [comment]
@MickeySegal
is this a clinical assay? I cannot find anything

**Comment by MickeySegal** [comment]
https://www.ncbi.nlm.nih.gov/books/NBK53700/ "Histologic examination reveals focal tubular atrophy, secondary glomerular scarring, and interstitial fibrosis [Zivná et al 2009]. Early in the disease course immunostaining for renin and prorenin is markedly decreased (compared to control tissues) in the granular cells of the juxtaglomerular apparatus and undetectable in the tubular epithelium."

**Comment by pnrobinson** [comment]
This appears to relate only to the first description of mutations in one disease (PMID: 19664745) and I doubt that anybody would do this now as a clinical assay, so this is not a good HPO term. I could not find any other references to renin staining as a clinical test.
