### ISSUE TITLE
NTR: Autopsy: necrotic lesions in basal ganglia (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9222]
New term request Autopsy: necrotic lesions in basal ganglia (elthat_110309014651):   UMLS: 5563536

**Comment by pnrobinson** [comment]
@MickeySegal
Maybe we should improve the definition, but I think it is this term. can you provide context
[Basal ganglia necrosis HP:0012128](https://hpo.jax.org/app/browse/term/HP:0012128)

**Comment by MickeySegal** [comment]
That looks like what we want.    https://www.ncbi.nlm.nih.gov/books/NBK1173/ "Typical neuropathologic changes: multiple focal symmetric necrotic lesions in the basal ganglia, thalamus, brain stem, dentate nuclei, and optic nerves. "

**Comment by pnrobinson** [comment]
Updated definition to:
Death of cells in the basal ganglia. This finding can be confirmed by autopsy. It can be suspected with hyperintensities within the basal ganglia on FLAIR and T2-sequences on magnetic resonance imaging.
