### ISSUE TITLE
NTR: Autopsy: necrotic lesions in brainstem (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9224]
New term request Autopsy: necrotic lesions in brainstem (elthat_110309014820):

**Comment by pnrobinson** [comment]
@MickeySegal
This feature can be found following radiation therapy -- is this the context? Not sure how much to specify this feature

**Comment by MickeySegal** [comment]
https://www.ncbi.nlm.nih.gov/books/NBK1173/ "multiple focal symmetric necrotic lesions in the basal ganglia, thalamus, brain stem, dentate nuclei, and optic nerves"

**Comment by pnrobinson** [comment]
@MickeySegal 
added as

HP:0034986
Focal necrotic brainstem lesion
def: A localized area of cell death, often accompanied by infiltration of inflammatory cells, in the brainstem
