### ISSUE TITLE
NTR: Collagen type VI synthesis by fibroblasts abnormal in vitro (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9227]
New term request Collagen type VI synthesis by fibroblasts abnormal in vitro (perlma_110328040952):   UMLS: 2749505

**Comment by pnrobinson** [comment]
@MickeySegal
I cannot find mentions of this as a regularly used diagnostic assay, even on the boundary between research and diagnostics; the articles that come up in searches are all over 30 years old. I would suggest we not make a term for this now, but as always if I am wrong please just let me know!

**Comment by MickeySegal** [comment]
https://www.ncbi.nlm.nih.gov/books/NBK1503/ "Immunocytochemical analysis of collagen VI in dermal fibroblast cultures can demonstrate decreased and/or abnormal-appearing collagen VI extracellular matrix deposition ... Collagen VI immunocytochemical studies in dermal fibroblasts in COL6-RD A. The normal control with collagen VI labeling with antibody demonstrates an abundance of well-organized collagen VI microfibrils in a linear, unidirectional trend"
