### ISSUE TITLE
NTR: Gastric biopsy: adenoma (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9236]
New term request Gastric biopsy: adenoma (elthat_110419020850): Stomach  UMLS: 0149826

**Comment by pnrobinson** [comment]
@MickeySegal
does this term intend to annotate: Adenomatous polyposis coli OMIM:175100
The HPO currently has this, but does not have a term for a single adenoma, I will add and rearrange if this is the same item.
Multiple gastric polyps HP:0004394

**Comment by MickeySegal** [comment]
Our finding had been used redundantly when other GI polyp findings had also been used such as HP:0004394.  I deleted our finding.

**Comment by pnrobinson** [comment]
thanks, closing
