### ISSUE TITLE
NTR: Conjunctival biopsy: multilamellar bodies in epithelial and endothelial cells (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9238]
New term request Conjunctival biopsy: multilamellar bodies in epithelial and endothelial cells (segal_110421154829):   UMLS: 3277222

**Comment by pnrobinson** [comment]
@MickeySegal
can you provide more context and/or a definition please?

**Comment by MickeySegal** [comment]
https://jamanetwork.com/journals/jamaophthalmology/fullarticle/269152

Identification of characteristic fibrillogranular and multilamellar inclusions in conjunctival biopsy specimens is considered diagnostic of [Mucolipidosis IV]

It is possible that such testing is no longer done.

**Comment by pnrobinson** [comment]
This finding was obtained by Transmission electron microscopy in the paper (2002), and I cannot find more references, so I am guessing this is not a current clinical test and thus unlikely to be a good HPO term
