### ISSUE TITLE
NTR: Nucleotide levels high in fibroblasts (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9243]
New term request Nucleotide levels high in fibroblasts (mayman_090519183249):

**Comment by pnrobinson** [comment]
@MickeySegal
Is this a clinical examination? Can you provide the disease context?

**Comment by MickeySegal** [comment]
https://www.ncbi.nlm.nih.gov/books/NBK1973/

Table 1: ... and Nucleotide Levels in PRS Superactivity

**Comment by pnrobinson** [comment]
@MickeySegal 
I think this is refering to this Paper https://pubmed.ncbi.nlm.nih.gov/2423135/ from 1986. I do not think this is a current clinical assay, thus it is not a good HPO term.

**Comment by MickeySegal** [comment]
The current GeneReviews article https://ncbi.nlm.nih.gov/books/NBK1973/ lists this as a diagnostic criterion (Table 1).
