### ISSUE TITLE
NTR: Renal biopsy: subcortical scars (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9244]
New term request Renal biopsy: subcortical scars (elthat_110726040145): Kidney  UMLS: 1700247

**Comment by pnrobinson** [comment]
@MickeySegal
Is this finding related to history of pyelonephritis? Can you provide more context? Does it have to be "sub" cortical (as opposed to cortical?)

**Comment by MickeySegal** [comment]
Smith's textbook refers for progeria to "renal ischemia resulting in focal subcortical scars".    We also used the same term for https://www.omim.org/entry/193000 and related entries referring to "renal injury or scarring".  

So I'm changing our term to delete the word subcortical and this seems to fit with https://hpo.jax.org/app/browse/term/HP:0009741

**Comment by pnrobinson** [comment]
OK!
