### ISSUE TITLE
NTR: Skin biopsy: cytoplasmic bodies in keratinocytes on EM (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9247]
New term request Skin biopsy: cytoplasmic bodies in keratinocytes on EM (elthat_110902025634): Electron microscopy  UMLS: 3550956

**Comment by pnrobinson** [comment]
@MickeySegal

can we specify more? For instance, are these Civatte bodies? https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3726905/

**Comment by MickeySegal** [comment]
We had used it for https://www.ncbi.nlm.nih.gov/books/NBK7041/ but the article suggests this is no longer useful so I'm deleting our finding.

**Comment by pnrobinson** [comment]
thanks, closing
