### ISSUE TITLE
NTR: FHL1 protein low or absent in fibroblasts or myoblasts (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9248]
New term request FHL1 protein low or absent in fibroblasts or myoblasts (segal_110909203952): Immunocytochemistry

**Comment by pnrobinson** [comment]
@MickeySegal
as far as I can see this was done in a few research papers but it does not appear to be a current clinical test.

**Comment by MickeySegal** [comment]
It is mentioned in the current GeneReviews article https://www.ncbi.nlm.nih.gov/books/NBK1436/
"Immunodetection of FHL1. In controls, the three FHL1 isoforms (A, B, and C) are ubiquitously expressed in the cytoplasm as well as in the nucleus. The isoforms can be detected by immunofluorescence and/or western blot in fresh muscle biopsy or myoblasts, fibroblasts, and cardiomyocytes [Sheikh et al 2008, Gueneau et al 2009].
In individuals with FHL1-related XL-EDMD, FHL1 is absent or significantly decreased [Gueneau et al 2009]."
