### ISSUE TITLE
IgA nephropathy disease definition

### ISSUE THREAD

**Issue by dgale25** [obophenotype/human-phenotype-ontology#925]
Diagnostic phenotype: IgA two orders of magnitude (ie ++) greater than IgM and IgG (eg IgG +, IgA +++, IgM +) deposited in glomerulus in immunofluorescence, combined with mesangial proliferation.

Other phenotypic features:
Microscopic hematuria
Macroscopic hematuria
Proteinuria
Renal impairment (CKD or AKI)

C3 deposition
Subendothelial dense deposits on Electron Microscopy
Mesangial dense deposits on EM
Other features correlated with disease activity/stage: Extracapillary glomerular hypercellularity, endocapillary hypercellularity, glomerulosclerosis,  Tubulointerstitial scarring etc.

**Comment by pnrobinson** [comment]
Note HP:0004746, dense deposit disease, should be altered the phenotype of dense deposits on EM. Need to read the original literature.

**Comment by pnrobinson** [comment]
C3 deposition added as synonym to current term C3 nephropathy

**Comment by pnrobinson** [comment]
I have updated the term to "Glomerular subendothelial electron-dense deposits" and "Glomerular C3 deposition". Will make requests for other new terms.
