### ISSUE TITLE
NTR: Fatty acid ß-oxidation analysis abnormal in fibroblasts (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9251]
New term request Fatty acid ß-oxidation analysis abnormal in fibroblasts (elthat_111004035246):

**Comment by pnrobinson** [comment]
@MickeySegal

I think this is an inference as to "what must be happening" rather than a direct phenotypic observation, but I am not an expert. Are we talking about these disorders? https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4934411/ Is there an assay that measures beta oxidation directly or are we measuring metabolites (In the latter case, the HPO term(s) should be about the metabolites).

**Comment by MickeySegal** [comment]
This is a good point; one should focus on what is measured and use the general description as a synonym.  There is such an explanation in "https://www.ncbi.nlm.nih.gov/books/NBK1424/": "Analysis of fatty acid β-oxidation in cultured fibroblasts involves acylcarnitine analysis of culture medium or a mix of culture medium and disrupted cells following the incubation of fibroblast cultures with labeled or non-labeled palmitic acid and non-labeled L-carnitine [Schmidt-Sommerfeld et al 1998]. The accumulation of C6-C10 acylcarnitines as described for plasma analysis confirms the diagnosis [Matern 2014]."

For these diseases we list such acylcarnitines being elevated in blood, but the fibroblast analysis is a separate test and seems deserving of its own finding, but it would seem like overkill to make it a cluster of findings for each acylcarnitine.

**Comment by pnrobinson** [comment]
@MickeySegal 

I have been improving and extending the acylcarnitine hierarchy.
The fibroblast analysis seems to have the same medical "meaning" as the plasma analysis. I would say that it might deserve its own term if there are situations where fibroblasts are positive and blood is normal. In general, the HPO does not model diagnostic procedures but rather their results. So I would prefer not to add this term without some specification. Could we close this and if needed after all of the dust has settled we can discuss and implement as needed?
