### ISSUE TITLE
NTR: Liver biopsy: proline oxidase activity decreased (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9253]
New term request Liver biopsy: proline oxidase activity decreased (elthat_111112200645): Proline dehydrogenase  UMLS: 1963705

**Comment by pnrobinson** [comment]
@MickeySegal

is this https://omim.org/entry/239500
Is liver biopsy still done?

**Comment by MickeySegal** [comment]
Yes.  A liver biopsy is mentioned, but from a 1991 paper.  You are likley correct that this is no longer done, so I'll delete our finding.

**Comment by pnrobinson** [comment]
thanks, closing
