### ISSUE TITLE
NTR: Liver biopsy: sarcosine dehydrogenase activity low (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9256]
New term request Liver biopsy: sarcosine dehydrogenase activity low (elthat_111118035856): Hepatic biopsy

**Comment by pnrobinson** [comment]
@MickeySegal
Since sarcosinemia is a "Benign metabolic state producing no disease" according to OMIM, I am wondering if liver biopsy for this enzyme activity is a current clinical assay or was this described for research purposes only?

**Comment by MickeySegal** [comment]
OK.  Deleted.

**Comment by pnrobinson** [comment]
thanks, closing
