### ISSUE TITLE
NTR: beta-alanine-alpha-ketoglutarate transaminase activity low in fibroblast (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9259]
New term request beta-alanine-alpha-ketoglutarate transaminase activity low in fibroblast (elthat_111121070845):

**Comment by pnrobinson** [comment]
@MickeySegal
is this a valid entity?
It appears to be mentioned in a legacy OMIM entry:
https://omim.org/entry/237400
but this is not something that could be diagnosed currently

**Comment by MickeySegal** [comment]
The disease entity is also mentioned in a 2017 article https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5097872/

**Comment by pnrobinson** [comment]
True, but in the 2017 article they are not investigating persons with OMIM:237400, they are adding beta alanine to cell culture to inviestigate β-alanine toxicity. 
I do not think that low beta-alanine-alpha-ketoglutarate transaminase activity is a current clinical test, and so let's hold off for now on a new term.
