### ISSUE TITLE
C3 glomerulopathy definition

### ISSUE THREAD

**Issue by dgale25** [obophenotype/human-phenotype-ontology#926]
Definition: C3 deposition 2 orders of magnitude or more than IgG, IgM and IgA deposition in the glomerulus with mesangial proliferation and/or other features of glomerular inflammation (eg capillary wall thickening).

Other phenotypic abnormalities that might be present:
Proteinuria
Nephrotic syndrome (Hypoalbuminaemia, proteinuria >3g/day, oedema)
Hematuria (microscopic or macroscopic)
Hypertension
Membranoproliferative glomerulonephritis
Thickening of glomerular capillary walls
Tubulointerstitial fibrosis/scarring
Focal glomerulosclerosis
Renal impairment (CKD or AKI)
C3 Nephritic Factor (autoantibody)
Ocular drusen (assd with DDD)
Partial lipodystrophy (assd with C3NeF)

Subclassification:
Dense deposit disease (DDD): C3 glomerulopathy with dense transformation (intramembranous dense deposit) in the glomerular basement membrane 
C3 glomerulonephritis: C3 glomerulopathy with discrete subendothelial, mesangial or subepithelial electron dense deposits on EM (w/out dense transformation of the GBM)

**Comment by pnrobinson** [comment]
Added tern for C3 Nephritic Factor (autoantibody)
Still need term for Thickening of glomerular capillary walls
