### ISSUE TITLE
NTR: Liver biopsy: PFIC1 protein decreased by immunohistochemical testing (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9262]
New term request Liver biopsy: PFIC1 protein decreased by immunohistochemical testing (elthat_100612143845): ATP8B1; hepatic biopsy; progressive familial intrahepatic cholestasis type 1 protein

**Comment by pnrobinson** [comment]
@MickeySegal
is this a current clinical test? I cannot find mention in OMIM or https://www.ncbi.nlm.nih.gov/books/NBK559317/ ?

**Comment by MickeySegal** [comment]
It is no longer mentioned in https://ncbi.nlm.nih.gov/books/NBK1297/, where we got it, so it doesn't seem to be a currently used test.

**Comment by pnrobinson** [comment]
OK, closing
