### ISSUE TITLE
NTR: Muscle biopsy: NADH dehydrogenase low (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9263]
New term request Muscle biopsy: NADH dehydrogenase low (segal_050203182540): Complex I Dehydrogenase deficiency; NADH-CoQ Reductase deficiency  UMLS: 1291288

**Comment by pnrobinson** [comment]
@MickeySegal
this appears to include several different enzymes with NADH dehydrogenase activity. Can you provide context?

**Comment by MickeySegal** [comment]
We changed the term to Complex I decreased activity and used HP:0011923

**Comment by pnrobinson** [comment]
OK!
