### ISSUE TITLE
NTR: Ornithine cellular mitochondrial transport low in cultured skin fibroblasts (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9264]
New term request Ornithine cellular mitochondrial transport low in cultured skin fibroblasts (elthat_120305182624):

**Comment by pnrobinson** [comment]
@MickeySegal
is this a current clinical assay? What is the context?

**Comment by MickeySegal** [comment]
https://www.ncbi.nlm.nih.gov/books/NBK97260/ refers to "function in cellular ornithine transport studies".

**Comment by pnrobinson** [comment]
I think that was undertaken in the course of a research study 15 years ago and it seems very unlikely this would be used as a clinical test today with NGS etc. Let's hold off unless we can find a reference for a current usage of this method as a clinical test.
