### ISSUE TITLE
NTR: Muscle biopsy: myotubularin absent immunocytochemically (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9265]
New term request Muscle biopsy: myotubularin absent immunocytochemically (segal_120613183039):

**Comment by pnrobinson** [comment]
@MickeySegal
as far as I can see, this is a research-only assay that is not a current clinical assay. Please reopen if this is not true.

**Comment by MickeySegal** [comment]
https://www.ncbi.nlm.nih.gov/books/NBK1432/
"Immunologic testing using antibodies specific for myotubularin, the protein encoded by MTM1 [Laporte et al 2001b], can detect the presence or absence of myotubularin in cell lines from affected individuals. In 21/24 males with known pathogenic variants, including some missense variants, no myotubularin was detected on western blot. "
