### ISSUE TITLE
NTR: Muscle biopsy: phosphoglucomutase-1 activity low (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9269]
New term request Muscle biopsy: phosphoglucomutase-1 activity low (segal_120814190852): PGM1  UMLS: 5393833

**Comment by pnrobinson** [comment]
@MickeySegal
The activity of this enzyme can also be measured in blood spots, so I will make a general "tissue" activity term
https://pubmed.ncbi.nlm.nih.gov/33342467/

**Comment by MickeySegal** [comment]
That is progress.  I changed our finding.

**Comment by pnrobinson** [comment]
sounds great, closing

**Comment by MickeySegal** [comment]
From the above it seemed like you would be creating a general tissue finding.
