### ISSUE TITLE
NTR: Cardiac biopsy: lysosomal-like PAS-positive vacuoles (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9270]
New term request Cardiac biopsy: lysosomal-like PAS-positive vacuoles (elthat_120818124947): Heart; periodic acid-Schiff  UMLS: 1836106

**Comment by pnrobinson** [comment]
@MickeySegal
Is this phenotype is for  infantile-onset form of Pompe disease?

**Comment by MickeySegal** [comment]
https://www.ncbi.nlm.nih.gov/books/NBK11168/ "Histologic examination of skin, liver, trachea, and heart shows lysosomal-like PAS-positive vacuoles, suggestive of glycoprotein and a storage disorder."

So this may apply to many diseases, and does for Pompe:  https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2861182/ "PAS-stained blood films can be used as a reliable screening tool to support a diagnosis of Pompe disease"

**Comment by pnrobinson** [comment]
OK. I will close this and work on https://github.com/obophenotype/human-phenotype-ontology/issues/9162 and https://github.com/obophenotype/human-phenotype-ontology/issues/9161
