### ISSUE TITLE
NTR: Fibrillin-1 protein abnormal in skin fibroblasts (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9271]
New term request Fibrillin-1 protein abnormal in skin fibroblasts (elthat_120818163642): Immunohistochemical or pulse-chase analysis  UMLS: 1835127

**Comment by pnrobinson** [comment]
@MickeySegal -- there are many different ways of abnormal (I used to work on fibrillin and in the 1990s we these assays!). This is not a typical clinical assay though, AFAIK it is purely research, and so this would be outside of the scope of HPO.

**Comment by MickeySegal** [comment]
We had this only in Marfan syndrome, but the latest version of https://www.ncbi.nlm.nih.gov/books/NBK1335/ no longer mentions this findings, so I agree that the most appropriate resolution is for SimulConsult to delete the finding.  We have a similar standard of clinical utility, though we even include autopsy findings if they are needed to establish a diagnosis.
