### ISSUE TITLE
NTR: Brain biopsy: axonal spheroids in brain (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9272]
New term request Brain biopsy: axonal spheroids in brain (elthat_120820221624): Autopsy

**Comment by pnrobinson** [comment]
@MickeySegal

is this a synonym with [Central nervous system axonal spheroid HP:0034381](https://hpo.jax.org/app/browse/term/HP:0034381) ?

**Comment by MickeySegal** [comment]
It is not a complete synonym because the CNS also includes the spinal cord, but it is good enough for our purposes since it includes what we want.

**Comment by pnrobinson** [comment]
OK, then I will close! thnks
