### ISSUE TITLE
NTR: alpha-mannosidase low in fibroblasts (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9276]
New term request alpha-mannosidase low in fibroblasts (f380): Acid alpha-mannosidase  UMLS: 2673366

**Comment by pnrobinson** [comment]
@MickeySegal
can this just be a sibling of [Decreased beta-mannosidase activity HP:0034367](https://hpo.jax.org/app/browse/term/HP:0034367)
i.e., without mentioning fibroblasts?

**Comment by MickeySegal** [comment]
Fine.

**Comment by pnrobinson** [comment]
@MickeySegal

Added as 

HP:0034712
Decreased alpha-mannosidase activity
