### ISSUE TITLE
NTR: Renal biopsy: oligomeganephronia (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9278]
New term request Renal biopsy: oligomeganephronia (elthat_120903205957): Reduced number and enlarged nephrons  UMLS: 0431694

**Comment by pnrobinson** [comment]
After reviewing the literature again I am not convinced this is a good term. I will close for now. We are hoping to conduct a nephro workshop this year and will revisit all terms.

**Comment by MickeySegal** [comment]
Splitting makes sense.  I await the Meganephronia term.  As guidance, the approach for muscle makes sense: https://hpo.jax.org/app/browse/term/HP:0100293
