### ISSUE TITLE
NTR: Liver biopsy: OATP1B1 and OATP1B3 proteins decreased or absent (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9281]
New term request Liver biopsy: OATP1B1 and OATP1B3 proteins decreased or absent (elthat_121120161443): Immunohistochemical testing, hepatic biopsy

**Comment by pnrobinson** [comment]
@MickeySegal
would this really be a clinical assay for https://omim.org/entry/237450 ? What is the intended use case?

**Comment by MickeySegal** [comment]
That is correct, but it sounds more like a research test from https://www.ncbi.nlm.nih.gov/books/NBK114805/ "Tests not generally available:... Immunohistologic study for OATP1B1 and OATP1B3 in archival liver biopsy specimen"

So it may be best to delete our finding.

**Comment by pnrobinson** [comment]
OK, let's not add at this time.
