### ISSUE TITLE
NTR: Liver biopsy: dark melanin-like pigment in lysosomes of hepatocytes (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9282]
New term request Liver biopsy: dark melanin-like pigment in lysosomes of hepatocytes (elthat_121120165116): Hepatic biopsy

**Comment by pnrobinson** [comment]
@MickeySegal
are we talking about Dubin Johnson (https://www.ncbi.nlm.nih.gov/books/NBK536994/)?
If so would this be adequate

Label: Hepatic melanin-like lysosomal pigmentation
Definition:  Accumulation of dark, coarsely granular pigment localized in lysosomes of centrilobular hepatocytes.

**Comment by MickeySegal** [comment]
Dubin Johnson and also the similar phenomenon in https://www.omim.org/entry/208085.

Your wording seems fine.

**Comment by pnrobinson** [comment]
@MickeySegal

added as HP:0034714
