### ISSUE TITLE
NTR: Liver biopsy: MRP2 proteins decreased or absent (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9283]
New term request Liver biopsy: MRP2 proteins decreased or absent (elthat_121120165742): Multidrug resistance-associated protein 2, immunohistochemical testing, hepatic biopsy

**Comment by pnrobinson** [comment]
@MickeySegal

I think that the name MRP2 is no longer current:
https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/HGNC:53

Could we rename this?

**Comment by MickeySegal** [comment]
MRP2 seems still to be used for the protein: https://www.ncbi.nlm.nih.gov/books/NBK114805/
"ABCC2 encodes MRP2, which serves as the canalicular export pump for conjugated bilirubin and numerous other anionic compounds."

**Comment by MickeySegal** [comment]
All I know is from that article.  It appears in Table 3, but compared to OATP1B1 and OATP1B3, which the article explains are tests "not generally available", so it may be wise to delete this as just a research test.

**Comment by pnrobinson** [comment]
OK, let's not add the term at this time.
