### ISSUE TITLE
NTR: Liver biopsy: uroporphyrinogen decarboxylase low (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9284]
New term request Liver biopsy: uroporphyrinogen decarboxylase low (elthat_121124184954): UROD, hepatic  UMLS: 0342861

**Comment by pnrobinson** [comment]
@MickeySegal
I think that one can test for this also in the blood, and so I am wondering if a generic term would be sufficieny (i.e., Reduced uroporphyrinogen decarboxylase activity rather than Reduced hepatic uroporphyrinogen decarboxylase activity)?

**Comment by MickeySegal** [comment]
That is fine.

**Comment by pnrobinson** [comment]
@MickeySegal
added as HP:0034715
