### ISSUE TITLE
NTR: UDP-GlcNAc 2-epimerase activity low in fibroblast (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9289]
New term request UDP-GlcNAc 2-epimerase activity low in fibroblast (elthat_130209153514):

**Comment by pnrobinson** [comment]
@MickeySegal
does this finding need to be specifically fibroblast?
Is this used clinically for https://omim.org/entry/269921 ?

**Comment by MickeySegal** [comment]
Yes, sialuria.  Doesn't need to be specifically fibroblast.

**Comment by pnrobinson** [comment]
@MickeySegal 
I am seeing now that we had related terms
Abnormal uridine diphosphate glucose-4-epimerase level HP:0410192
but they are not defined with the abbreviation.
I am going to rearrange and add the abbreviations to make the structure more consistent with the rest
