### ISSUE TITLE
renal histology

### ISSUE THREAD

**Issue by dgale25** [obophenotype/human-phenotype-ontology#929]
Focal: Involving some but not all glomeruli
Segmental: Involving some of but not all of each glomerulus
Diffuse: Involving all glomeruli
Global: Involving all of each affected glomerulus

eg: Focal segmental glomerulosclerosis
Focal global glomeruloslcerosis
Diffuse segmental proliferative GN

Mesangiocapillary GN is completely synonymous with Membranoproliferative GN
Mesangial proliferative means increased mesangial cells

"Proliferation" is now being replaced with "hypercellularity"

"Capillary wall" and "membrane" are used almost intrerchangeably in light microscopy reports. 
Location of electron dense deposits are determined by Electron Microscopy: Mesangial, subepithelial, intramembranous, subepithelial. Subepithelial deposits can be large and are termed "humps"

Fibrin deposition on EM often is described as "lucent" or "flocculent" material

Amyloid deposition is defined by positivity for Congo Red staining. On EM amyloid is disorganised fibrils. Organised fibrils are immunotactoid.

Tubular atrophy, tubulointerstitial fibrosis, interstitial fibrosis tubular atrophy=IFTA, interstitial scarring are all essentially synonymous

**Comment by pnrobinson** [comment]
Transfering this material to the wiki on this github site.
