### ISSUE TITLE
NTR: Mitochondrial Complex V deficiency (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9291]
New term request Mitochondrial Complex V deficiency (elthat_130213200201): Electron transport chain, ETC; ATPase  UMLS: 4748271

**Comment by pnrobinson** [comment]
@MickeySegal
I believe this is a synonym -- [Decreased activity of mitochondrial ATP synthase complex HP:0011925](https://hpo.jax.org/app/browse/term/HP:0011925) -- should we add "Mitochondrial Complex V deficiency" as a synonym?

**Comment by MickeySegal** [comment]
That would be good.  We have ATP synthase as a synonym.

**Comment by pnrobinson** [comment]
added the synonym as suggested
