### ISSUE TITLE
NTR: Modifier: Renal biopsy: mesangioproliferative character to glomerulonephritis (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9297]
New term request Modifier: Renal biopsy: mesangioproliferative character to glomerulonephritis (elthat_130314094645):   UMLS: 0221238

**Comment by pnrobinson** [comment]
@avizrosenberg @yongqunh @MickeySegal

Avi, is  [Mesangial hypercellularity HP:0012574](https://hpo.jax.org/app/browse/term/HP:0012574) essentially another way of saying "mesangioproliferative character"? 

Mickey, we would not normally have a bundled term like this, so I think we just want to characterize the "mesangioproliferative character"

**Comment by MickeySegal** [comment]
https://www.omim.org/entry/613652 says "Renal biopsies showed mesangial proliferative glomerulonephritis in all patients, tubulointerstitial abnormalities in 2, and deposition of immune complexes in all."  The Cassidy Pediatric Rheumatology textbook lists for Lupus Glomerulonephritis 3 patterns, one of which is "mesangial proliferative glomerulonephritis".

I will defer to Avi, but this sounds like it is the same as your existing term.

**Comment by avizrosenberg** [comment]
Yes it would seem that this is synonymous

**Comment by pnrobinson** [comment]
Thanks, I will leave this as a synonym without creating a new term!

**Comment by yongqunh** [comment]
It looks reasonable to leave it as a synonym.
