### ISSUE TITLE
NTR: Liver biopsy: cystathionase activity low (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9298]
New term request Liver biopsy: cystathionase activity low (elthat_130315182146): Hepatic

**Comment by pnrobinson** [comment]
@MickeySegal
are we talking about cystathionine gamma-lyase activity?
If so I would add
Reduced hepatic cystathionine gamma-lyase activity
syn Reduced hepatic cystathionase activity
to disambiguate.

**Comment by MickeySegal** [comment]
It is cystathionine gamma-lyase.  I changed our term to fit this.

**Comment by pnrobinson** [comment]
@MickeySegal 
added
HP:0034929
Reduced hepatic cystathionine gamma-lyase activity
