### ISSUE TITLE
NTR: Duodenal biopsy: inflammation (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9299]
New term request Duodenal biopsy: inflammation (elthat_130329062652): Duodenitis  UMLS: 4748586

**Comment by pnrobinson** [comment]
@MickeySegal
This is Duodenitis HP:0033117, I will add as a synonym Duodenal inflammation

**Comment by MickeySegal** [comment]
I agree, though UMLS has these as separate entries:
https://www.ncbi.nlm.nih.gov/medgen/C0013298
https://www.ncbi.nlm.nih.gov/medgen/C4748586

The HPO entry lists neither of these UMLS codes.  If you decide to make the HPO-UMLS cross-references more complete, I'd be glad to provide a listing of our assignments of HPO codes and UMLS codes to our findings. 

Keeping these as separate UMLS codes is within the bounds of rationality, so I won't pester UMLS about this, and I've retained both UMLS codes.
