### ISSUE TITLE
renal anatomical phenotypes

### ISSUE THREAD

**Issue by mellybelly** [obophenotype/human-phenotype-ontology#930]
The HPO is currently missing a variety of classes in the renal anatomical partonomy. 
It would be great if we could automate addition of these to HPO. Can we revisit the TermGenie @cmungall ?

e.g. I want 'Abnormality of X' where X is any part of the 'renal tubule'

I'll likely add some of the key parts but it would be great if we had a faster way to do this where we could say yay nay on which aspects of the partonomy closure one wanted to add.

**Comment by cmungall** [comment]
On 21 Jun 2016, at 5:56, Melissa Haendel wrote:

> The HPO is currently missing a variety of classes in the renal 
> anatomical partonomy.
> It would be great if we could automate addition of these to HPO. Can 
> we revisit the TermGenie @cmungall ?

You can go ahead and add these with hp.termgenie.org any time you like, 
but longer term we should use DOSDPs for these. Need to get patterns 
into YAML.

> e.g. I want 'Abnormality of X' where X is any part of the 'renal 
> tubule'

Abnormality or morphological abnormality? Probably the latter

> I'll likely add some of the key parts but it would be great if we had 
> a faster way to do this where we could say yay nay on which aspects of 
> the partonomy closure one wanted to add.

If we go the DOSDP route, we'd just make a CSV with the following:

UBERON:0001231 ! nephron tubule
UBERON:0001287 ! proximal convoluted tubule
UBERON:0001290 ! proximal straight tubule
UBERON:0004134 ! proximal tubule
UBERON:0004135 ! distal tubule
UBERON:0004196 ! proximal convoluted tubule segment 1
UBERON:0004197 ! proximal convoluted tubule segment 2
UBERON:0004810 ! nephron tubule epithelium
UBERON:0005097 ! renal connecting tubule
UBERON:0005117 ! metanephric distal convoluted tubule
UBERON:0005118 ! metanephric early distal convoluted tubule
UBERON:0005120 ! metanephric late distal convoluted tubule
UBERON:0005124 ! metanephric proximal convoluted tubule
UBERON:0005125 ! metanephric proximal straight tubule
UBERON:0005126 ! metanephric S1
UBERON:0005127 ! metanephric thick ascending limb
UBERON:0005129 ! metanephric distal tubule
UBERON:0005146 ! metanephric nephron tubule
UBERON:0005149 ! metanephric connecting tubule
UBERON:0005151 ! metanephric proximal tubule
UBERON:0005310 ! pronephric nephron tubule
UBERON:0005329 ! mesonephric nephron tubule
UBERON:0006173 ! pronephric proximal tubule
UBERON:0006175 ! pronephric distal tubule
UBERON:0006189 ! mesonephric connecting tubule
UBERON:0006190 ! mesonephric distal tubule
UBERON:0006192 ! mesonephric proximal tubule
UBERON:0006337 ! distal early tubule
UBERON:0006534 ! renal convoluted tubule
UBERON:0006853 ! renal cortex tubule
UBERON:0007298 ! pronephric proximal convoluted tubule
UBERON:0007308 ! pronephric distal early tubule
UBERON:0007685 ! region of nephron tubule
UBERON:0008404 ! proximale tubular epithelium
UBERON:0008408 ! distal tubular epithelium
UBERON:0009035 ! renal straight tubule
UBERON:0009622 ! pronephric proximal straight tubule
UBERON:0009651 ! nephron tubule basement membrane
UBERON:0009773 ! renal tubule
UBERON:0012428 ! proximal convoluted tubule brush border
UBERON:2005292 ! distal late tubule

You would delete rows for anything you thought too specific or not 
useful.

**Comment by pnrobinson** [comment]
To date, we have tried to have terms for things that are in practice measured in medical settings. As medicine becomes more of a data-driven endeavour, more things are going to get measured in more detail. Still, I think there is a place for adding terms manually and adding comments to contextualise their use in diagnostics. @mellybelly did we get a list of terms that are now missing or is it just that in general more terms are needed?

**Comment by pnrobinson** [comment]
I am closing this item for now, reopen if necessary.
