### ISSUE TITLE
NTR: Renal biopsy: glomerular atrophy (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9310]
New term request Renal biopsy: glomerular atrophy (elthat_130503195106): Kidney; small, collapsed glomerulus, or rudimentary glomeruli

**Comment by pnrobinson** [comment]
@MickeySegal
@avizrosenberg @yongqunh
Although this term "makes sense"  we did not include it in our previous revision ([Abnormal renal glomerulus morphology HP:0000095](https://hpo.jax.org/app/browse/term/HP:0000095)) and I do not recall it being on the list of terms we went over. Could you comment as to whether this is a good term and what the best definition should be?

**Comment by yongqunh** [comment]
glomerular atrophy appears to be a good term.
See PubMed: 
https://pubmed.ncbi.nlm.nih.gov/?term=%22glomerular+atrophy%22 

There is no specific page in Wiki about glomerular atrophy.
However, as seen here, glomerular atrophy appears in glomerulocystic kidney disease (GCKD): 
https://en.wikipedia.org/wiki/Glomerulocystic_kidney_disease

**Comment by avizrosenberg** [comment]
not familiar with the term glomerular atrophy….would avoid using it

**Comment by pnrobinson** [comment]
@MickeySegal 
given Avi's comments (https://www.hopkinsmedicine.org/profiles/details/avi-rosenberg), we should avoid using this description as a term since it is not a standard way of describing kidney biopsies. I looked at the OMIM entries above, and glomerular atrophy is not a major feature nor is it properly described.

**Comment by avizrosenberg** [comment]
Agreed that glomerular atrophy isnt a normative term. Sclerosis is the final stage of consolidation and would be synonymous with atrophy…were atrophy a used term to describe this process.

**Comment by MickeySegal** [comment]
Sclerosis would seem fine.
