### ISSUE TITLE
NTR: Transcobalamin uptake low in fibroblasts (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9311]
New term request Transcobalamin uptake low in fibroblasts (elthat_130505204030):

**Comment by pnrobinson** [comment]
@MickeySegal
I do not think the phenotype is specific for fibroblasts (it can be measured there). Also, shouldn't this be update of cobalamin (which is what the cells care about) rather than transcobalamine (which is one of the transport mechanisms)

What about

Reduced cellular cobalamin uptake
def: Diminished ability of cells to transport cobalamine from the extracellular space to the cytoplasm. 

Comment: Cobalamin (Cbl. also known as vitamin B12) plays a role in the recycling of folate for single carbon exchange reactions, purine and pyrimidine synthesis, and methylation of homocysteine for the production of S-adenosylmethionine. The absorption, blood transport and cellular uptake of Cbl are complex processes involving multiple proteins and receptors. Transcobalamine binds to Cbl to protect it from acid degradation in the stomach.

**Comment by MickeySegal** [comment]
https://www.omim.org/entry/613646 "fibroblasts showed low uptake of transcobalamin-bound cobalamin" so your form is good.

**Comment by pnrobinson** [comment]
@MickeySegal 

added
Reduced cellular cobalamin uptake
HP:0034985
