### ISSUE TITLE
NTR: Liver biopsy: heme oxygenase-1 activity low (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9312]
New term request Liver biopsy: heme oxygenase-1 activity low (elthat_130509060144):

**Comment by pnrobinson** [comment]
@MickeySegal
heme oxygenase is active in many tissues -- could we use a generic term here or is the "hepatic" essential for your use case?

**Comment by MickeySegal** [comment]
Generic is fine.

**Comment by pnrobinson** [comment]
@MickeySegal 
added as HP:0034716
