### ISSUE TITLE
NTR: Skin biopsy: hyaline deposits in dermis (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9315]
New term request Skin biopsy: hyaline deposits in dermis (elthat_130516071513): Hyaline-like  UMLS: 1856756

**Comment by pnrobinson** [comment]
@MickeySegal
What do you think about this definition & label
label: Perivscular dermis hyaline deposition
Definition: Deposition of a largely amorphous hyaline (transparent and homogeneous) substance around blood vessels in the dermis layer of the skin.
Comment: See Figure 4 of PMID:11298373

https://pubmed.ncbi.nlm.nih.gov/11298373/

**Comment by MickeySegal** [comment]
OK with me

**Comment by pnrobinson** [comment]
@MickeySegal 
added as
HP:0034925

**Comment by pnrobinson** [comment]
Note corrected spelling to Perivascular dermis hyaline deposition
