### ISSUE TITLE
NTR: Cardiac biopsy: hyaline deposits (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9317]
New term request Cardiac biopsy: hyaline deposits (elthat_130516082000): Heart  UMLS: 4231069

**Comment by pnrobinson** [comment]
@MickeySegal
can you provide more context? Are we walking about hyalinosis of blood vessels in the heart?

**Comment by MickeySegal** [comment]
We use it for https://www.omim.org/entry/255160.  Also for https://www.ncbi.nlm.nih.gov/books/NBK1525/ "Hyaline deposition has been documented in the dermis, the small and large intestine, skeletal muscle, lymph nodes, thymus, spleen, thyroid, adrenals, and myocardium."  Neither mentions blood vessels.

**Comment by pnrobinson** [comment]
@MickeySegal 
added as 
Cardiomyocyte hyaline bodies
HP:0034796
Def: Subsarcolemmal, eosinophilic glass-like regions within the cytoplasm of cardiomyocytes.
