### ISSUE TITLE
NTR: Bone biopsy: fibroma (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9318]
New term request Bone biopsy: fibroma (elthat_130516091658): Fibromatosis  UMLS: 1390470

**Comment by pnrobinson** [comment]
@MickeySegal
not an expert but I am not familar with "Bone fibroma".
Could this be Desmoplastic Fibroma (e.g. https://pubmed.ncbi.nlm.nih.gov/36685776/)

**Comment by MickeySegal** [comment]
We use this for https://www.omim.org/entry/228550 and https://www.omim.org/entry/600268.  Neither mentions desmoplastic.

**Comment by pnrobinson** [comment]
600268 mentions [Non-Ossifying Fibroma](https://www.ebi.ac.uk/ols4/ontologies/ncit/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FNCIT_C121929).  228550 is probably [Myofibroma](https://www.ebi.ac.uk/ols4/ontologies/ncit/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FNCIT_C7052)?

**Comment by pnrobinson** [comment]
@MickeySegal 
I think it is probably best not to create a new HPO term given it is a little unclear what the findings refer to. We can always come back if we get more information.

**Comment by MickeySegal** [comment]
HPO has Ossifying fibroma: https://hpo.jax.org/browse/term/HP:0030426 so it would seem reasonable to specify non-ossifying bone fibroma.  And we could use Myofibromatosis https://hpo.jax.org/browse/term/HP:0020135 for the myofibroma.  But UMLS does use the parent term.
