### ISSUE TITLE
NTR: Bone biopsy: ameloblastoma (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9319]
New term request Bone biopsy: ameloblastoma (elthat_130517083114): Immature epithelial jaw tumor  UMLS: 0002448

**Comment by pnrobinson** [comment]
@MickeySegal
Ameloblastoma originates in tooth, but the issue is for bone biopsy. 
Are we talking about https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4439660/

**Comment by MickeySegal** [comment]
We are talking about the same thing.  I changed our wording to "Jaw biopsy" to be more specific than "Bone biopsy".  As the article you cited makes clear, "Ameloblastoma is a benign odontogenic tumor generally present in the jaw bone. The tumor originates from the residual epithelium of the tooth germ, epithelium of odontogenic cysts stratified squamous epithelium and epithelium of the enamel organ."

**Comment by pnrobinson** [comment]
added as HP_0034515, "Ameloblastoma"
