### ISSUE TITLE
add broad synonyms for basic function tests

### ISSUE THREAD

**Issue by mellybelly** [obophenotype/human-phenotype-ontology#932]
for example, the LFT acronym is representative of a set of liver enzyme assays/phenotypes. It would be useful to have LFT as a broad synonym for these phenotype sets. @mellybelly or other to produce a list.

**Comment by pnrobinson** [comment]
Liver function tests include:

    Albumin
    Alpha-1 antitrypsin
    ALP
    ALT
    AST
    Gamma-glutamyl transpeptidase (GGT)
    Prothrombin time, also expressed as international normalized ratio (INR)
    Serum bilirubin
    Urine bilirubin

I wonder if we should not increase the use of labels (rather than synonyms) to indicate things like "this feature can be found by CT", "this feature is used to evaluate liver function", etc. I think that it will otherwise become harder to use this information computationally.

**Comment by cmungall** [comment]
On 3 Jul 2016, at 23:09, Peter Robinson wrote:

>  wonder if we should not increase the use of labels (rather than 
> synonyms)

not sure what you mean. Do you mean rdfs:label?

> to indicate things like "this feature can be found by CT", "this 
> feature is used to evaluate liver function", etc. I think that it will 
> otherwise become harder to use this information computationally.

Sounds like we want to use bona-fide logical axioms here, e.g.

     F SubClassOf found-by CT
     F SubClassOf evaluates ('enzymatic activity' and occurs_in some 
liver)

Here the OPs would be replaced by whatever standard is in RO/OBI. CT 
would be in OBI. In other cases we'd need an assay ontology. 'enzymatic 
activity' would be in GO. Alternatively this could be a trait in OBA.

**Comment by pnrobinson** [comment]
@mellybelly @cmungall @drseb   I was thinking that we could use a mechanism like that of GO slim to indicate groups like this. There are about 20 items that are used as LFTs. Similar things can be said for say phenotypes that can be identified by brain CT. I do not think that we canmodel this logically unless we work hard with OBI, which might be a good thing in the long term, but would possibly be overkill.

**Comment by mellybelly** [comment]
Not sure about the slims as we'd need to create quite a few of them. What about starting with set of tags that are the assays, via a new annotation property, 'via_assay' or some such? We could always migrate these out when we need to. We should make sure that the assays have an OBI or LOINC code though, this will make it easier later and there isn't likely a whole lot that wouldn't already be coded.

If I were to make this a new project, where would we get grouping sets to prioritize, eg. things like LFT? We can't start with all of LOINC, but seems like focusing on the most common assays or the assay groups would be a good start.

**Comment by pnrobinson** [comment]
@cmungall @mellybelly @drseb This is a major project but would be useful for EHRs. I am not sure it makes sense to try to do this without having specific funding for such a project, and it would naturally follow if we did get funding for EHR work. I think we can close this for now.
