### ISSUE TITLE
NTR: Brain biopsy: teratoid or rhabdoid tumors (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9323]
New term request Brain biopsy: teratoid or rhabdoid tumors (elthat_130529042312):   UMLS: 4042185

**Comment by pnrobinson** [comment]
@MickeySegal
Is this refering to 
[Atypical teratoid/rhabdoid tumor HP:0034401](https://hpo.jax.org/app/browse/term/HP:0034401)

**Comment by MickeySegal** [comment]
That's it.  I now have enough chronological mapping of HPO numbers to see that term must have been added just after I submitted my list.

**Comment by pnrobinson** [comment]
no prob! Closing
