### ISSUE TITLE
NTR: Cardiac biopsy: glycogen excessive (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9325]
New term request Cardiac biopsy: glycogen excessive (elthat_130602142223): Heart

**Comment by pnrobinson** [comment]
@MickeySegal
this is
[Increased myocardial glycogen content HP:0034532](https://hpo.jax.org/app/browse/term/HP:0034532)

**Comment by MickeySegal** [comment]
I see from the HPO number that this term is from after we submitted our list.  It is the appropriate choice.
