### ISSUE TITLE
NTR: Brain biopsy: swollen achromatic neurons (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9327]
New term request Brain biopsy: swollen achromatic neurons (elthat_130616152955): Pick cells  UMLS: 1868315

**Comment by pnrobinson** [comment]
@MickeySegal

I am wondering if it would be better for disambiguation to call this feature
Cerebral cortex swollen achromatic neurons
syn: Cerebral cortex Pick cells
def:The presence of enlarged and swollen neurons that lack Nissl bodies (the rough endoplasmic reticulum-achromasia refers to neurons that lack Nissl bodies) in the cortex of the brain. PMID:8171960

**Comment by MickeySegal** [comment]
That is fine.  We classify by procedures in order to make recommendations about procedures but that is not relevant to HPO.

**Comment by pnrobinson** [comment]
@MickeySegal 
added as
Cerebral cortex swollen achromatic neurons
HP:0034717

**Comment by MickeySegal** [comment]
On second thought, "Cerebral cortex swollen achromatic neurons" might be seen as ambiguous as to whether the cortex is swollen or the neurons are swollen.

**Comment by pnrobinson** [comment]
I see what you mean.
What about 
Cerebral cortex swollen achromatic neurons
or
Swollen achromatic neurons in the cerebral cortex 
?

**Comment by MickeySegal** [comment]
The latter avoids the ambiguity.

**Comment by pnrobinson** [comment]
I changed the preferred label to Swollen achromatic neurons in the cerebral cortex
