### ISSUE TITLE
NTR: Aromatase activity low in fibroblasts (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9331]
New term request Aromatase activity low in fibroblasts (elthat_130625093847):

**Comment by pnrobinson** [comment]
@MickeySegal -- I think that aromatiase can be measured in many cell types, and so I would propose we make just
_Reduced/Elevated aromatase activity_ terms -- thoughts?

**Comment by MickeySegal** [comment]
Fine for both.

**Comment by pnrobinson** [comment]
@MickeySegal 
added as
HP:0034700
Reduced aromatase activity
