### ISSUE TITLE
NTR: Bone marrow: lymphoid hyperplasia (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9338]
New term request Bone marrow: lymphoid hyperplasia (elthat_130808135355): Lymphoproliferative infiltration; lymphocytic infiltration  UMLS: 3807548

**Comment by pnrobinson** [comment]
@MickeySegal
are we talking about this -- https://pubmed.ncbi.nlm.nih.gov/1246987/

**Comment by MickeySegal** [comment]
Yes, and another example is https://www.omim.org/entry/616452

**Comment by pnrobinson** [comment]
@MickeySegal 
added as
Lymphoid hyperplasia
HP:0034839


def: An abnormal bone marrow finding characterized by many poorly circumscribed and occasionally confluent lymphoid nodules. The nodules contain small and uniform lymphocytes with rounded nuclei, clumped chromatin, and without prominent nucleoli. 
Comment: The appearance of lymphoid hyperplasia may resemble that of malignant lymphoma, well-differentiated lymphocytic type.
