### ISSUE TITLE
NTR: Modifier: Corneal predominance to amyloidosis (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9340]
New term request Modifier: Corneal predominance to amyloidosis (elthat_130810114720):   UMLS: 2939149

**Comment by pnrobinson** [comment]
@MickeySegal
the HPO would probably represent this as a term "Corneal amyloidosis", a child of Amyloidosis HP:0011034. If desired, a modifier such as "Severe" could be used to represent the "predominance". 
Should we go ahead and make a term "Corneal amyloidosis"

**Comment by MickeySegal** [comment]
That is fine.

**Comment by pnrobinson** [comment]
@MickeySegal 
added as

Corneal amyloidosis
HP:0034701
