### ISSUE TITLE
NTR: Skin biopsy: collagen fibers thin in dermis (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9346]
New term request Skin biopsy: collagen fibers thin in dermis (elthat_140105040000): Hypoplastic collagen

**Comment by pnrobinson** [comment]
@MickeySegal
are we talking about an abnormal cross sectional diameter of collagen fibers (e.g. https://pubmed.ncbi.nlm.nih.gov/431039/ for increased diameter) or about the amount of collagen in the skin, e.g., loss of collagen with aging?

**Comment by MickeySegal** [comment]
https://www.omim.org/entry/616914 "hypoplastic collagen bundles"
https://www.omim.org/entry/618000 "decreased dermal collagen"

"Decreased dermal collagen" may be the best name.

**Comment by MickeySegal** [comment]
https://www.omim.org/entry/616914 "hypoplastic collagen bundles"
https://www.omim.org/entry/618000 "decreased dermal collagen"

"Decreased dermal collagen" might be the best term.

**Comment by pnrobinson** [comment]
@MickeySegal 

added as
HP:0034943
Decreased dermal collagen
