### ISSUE TITLE
NTR: Skin biopsy: pigmented basal layer of epidermis (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9349]
New term request Skin biopsy: pigmented basal layer of epidermis (elthat_140125094628):   UMLS: 3809396

**Comment by pnrobinson** [comment]
@MickeySegal

The basal layer contains melanocytes, and so I am not sure what the abnormality is?

**Comment by MickeySegal** [comment]
This is from https://www.omim.org/entry/615402: "Histopathologic examination of a skin lesion biopsy showed a pigmented basal layer of the epidermis, pigmentary incontinence in the papillary dermis, and some melanophages and lymphocytes in the upper dermis"

But if you think that is a description of what is normal I'm glad to delete the finding.

**Comment by pnrobinson** [comment]
I suspect they actually mean that the basal layer of the epidermis was more pigmented in the pigmented lesion than in the surrounding skin. The authors say "See supplemental material" but I could not download any file. I suspect it would be better not to include this finding for now, because the description in the article is imprecise and poorly documented and there is a potential for confusion.
I will close for now but if we can find more information happy to add the term
