### ISSUE TITLE
NTR: Bone biopsy: inflammation (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9356]
New term request Bone biopsy: inflammation (sundel_140720170037): Osteitis  UMLS: 0029400

**Comment by pnrobinson** [comment]
@MickeySegal
can we make this more specific?

**Comment by MickeySegal** [comment]
We added to this finding HP:0002754 (Osteomyelitis) so I think that meets our needs and we don't need a new term.

**Comment by pnrobinson** [comment]
thanks, closing
