### ISSUE TITLE
NTR: Bone biopsy: culture positive (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9357]
New term request Bone biopsy: culture positive (sundel_140720170156):   UMLS: 1328642

**Comment by pnrobinson** [comment]
@MickeySegal
this is a general term that probably is synonymous with [Osteomyelitis HP:0002754](https://hpo.jax.org/app/browse/term/HP:0002754). If not, please describe the difference/context. Otherwise please close this issue.

**Comment by pnrobinson** [comment]
See [#9364](https://github.com/obophenotype/human-phenotype-ontology/issues/9356)

**Comment by MickeySegal** [comment]
You have the pus and the inflammation, but the positive culture seems separable.
