### ISSUE TITLE
autoimmune hepatitis

### ISSUE THREAD

**Issue by mellybelly** [obophenotype/human-phenotype-ontology#936]
please add as subclass of hepatitis

**Comment by pnrobinson** [comment]
Autoimmune hepatitis (AIH) is a chronic progressive liver disease characterized by circulating autoantibodies and hyperglobulinemia.  It is characterized by continuing hepatocellular inflammation and necrosis and has a tendency to progress to cirrhosis.
I think therefore that "autoimmune hepatitis" is best modelled as a disease. Amongst the serology markers for this disease, there are two of the following four that do not yet have HPO terms. I will add them.
antinuclear antibodies (ANAs) 
smooth-muscle antibodies (SMAs)
liver-kidney microsomal type 1 antibodies (LKM-1)
anti–liver cytosol 1 (anti-LC1) antibodies
