### ISSUE TITLE
NTR: Uterine biopsy: myxomas  (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9368]
New term request Uterine biopsy: myxomas  (elthat_150214025104): Uterus

**Comment by pnrobinson** [comment]
@MickeySegal
I am wondering if this is actually Uterine myxoid leiomyoma, e.g., https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C40166

**Comment by MickeySegal** [comment]
This was based on https://www.ncbi.nlm.nih.gov/books/NBK1286/ "Other sites for myxomas include the oropharynx (tongue, hard palate, pharynx) and the female genital tract (uterus, cervix, vagina)."

**Comment by pnrobinson** [comment]
@MickeySegal

added as
Uterine myxoma
HP_0034948
