### ISSUE TITLE
NTR: Brain biopsy: hamartoma (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9375]
New term request Brain biopsy: hamartoma (elthat_150403081530):   UMLS: 0349611

**Comment by pnrobinson** [comment]
@MickeySegal

is this term close enough
[Cerebral hamartoma HP:0009731](https://hpo.jax.org/app/browse/term/HP:0009731)
?

**Comment by MickeySegal** [comment]
OK

**Comment by pnrobinson** [comment]
thanks, closing.
