### ISSUE TITLE
NTR: Renal biopsy: IgM deposition by immunofluorescence (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9385]
New term request Renal biopsy: IgM deposition by immunofluorescence (elthat_150714080650): Kidney

**Comment by pnrobinson** [comment]
@avizrosenberg @yongqunh @MickeySegal
We have some existing terms like this, e.g., 
Mesangial Immune complex deposition HP:0033295

What is the best overall structure and all locations in which it is important to denote immunoglobulin deposition?

**Comment by avizrosenberg** [comment]
Not sure I understand

Mesangial is a specific region in the glomerulus where immunnecomplexs may deposit.

**Comment by pnrobinson** [comment]
@avizrosenberg  I mean that Renal IgM deposition is probably too general to be useful and we should specify what structures are affected?

**Comment by MickeySegal** [comment]
We have this finding only for Prolidase deficiency, and that use of IgM immunofluorescence seems to have faded from clinical practice.  It is no longer mentioned in https://www.ncbi.nlm.nih.gov/books/NBK299584/ and I find almost no mentions of this in the literature.  I've deleted the finding as non-clinical, allowing us to punt on the classification questions.

**Comment by pnrobinson** [comment]
@MickeySegal -- I will close this item without creating a new term then.
