### ISSUE TITLE
NTR: Skin biopsy: endarteritis obliterans (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9387]
New term request Skin biopsy: endarteritis obliterans (elthat_150807073417): Endothelial and medial smooth muscle proliferation and inflammation  UMLS: 1260885

**Comment by pnrobinson** [comment]
@MickeySegal
I am finding citations for this that are many decades old (e.g. https://journals.sagepub.com/doi/abs/10.1177/000331975200300603) and wonder if this term is still in clinical use or if it has been superseded by some other term? Can you provide more context?

**Comment by MickeySegal** [comment]
https://ojrd.biomedcentral.com/articles/10.1186/s13023-014-0215-4 "Several lines of evidence showed endarteritis obliterans from intimal endothelial proliferation and proliferation of medial smooth muscle cells"

**Comment by pnrobinson** [comment]
@MickeySegal
sorry I am not able to find a workable definition for this term. Possibly it has been superseded in most of the literature?

**Comment by MickeySegal** [comment]
There are details at https://en.wikipedia.org/wiki/Obliterating_endarteritis

It is a pathological term that here describes a skin biopsy.  We've only used it for Sneddon syndrome, where we also describe vasculitis on skin biopsy, so it might make sense to delete the finding since it may seem falsely pathognomonic for Sneddon.

**Comment by pnrobinson** [comment]
@MickeySegal 
I get the impression that the term has been used to describe a disease entity but there is not really specific and observable phenotypic feature. See e.g., https://www.sciencedirect.com/topics/medicine-and-dentistry/obliterating-endarteritis. Let's hold off on the term for now.

**Comment by MickeySegal** [comment]
I deleted our finding.
