### ISSUE TITLE
NTR: Modifier: Renal biopsy: necrotizing character to glomerulonephritis (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9388]
New term request Modifier: Renal biopsy: necrotizing character to glomerulonephritis (elthat_150818030359): Kidney  UMLS: 0268750

**Comment by pnrobinson** [comment]
@MickeySegal
we typically do not have combined terms like this. Would it be possible to describe the necrosis as a separate term? Please provide more context.

**Comment by MickeySegal** [comment]
We have this only for https://ojrd.biomedcentral.com/articles/10.1186/1750-1172-7-20 "Some cases of glomerular nephropathy mostly diffuse crescentic or focal and segmental necrotizing glomerulonephritis and IgA nephropathy have been described".

But this is the only place we use this so it is not clear whether it is useful to keep this term.

**Comment by pnrobinson** [comment]
There is an existing term [Glomerular fibrinoid necrosis HP:0033277](https://hpo.jax.org/app/browse/term/HP:0034784)

Avi, could you help us with this please? @avizrosenberg @yongqunh

**Comment by pnrobinson** [comment]
I think it is probably best to drop this term until we get some indication that it differentiates two diagnoses or otherwise can be reliably used in differential diagnosis.
