### ISSUE TITLE
NTR: Skin biopsy: dermal edema (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9396]
New term request Skin biopsy: dermal edema (elthat_160315041709): Edematous skin  UMLS: 0521464

**Comment by pnrobinson** [comment]
@MickeySegal
This is commonly measured in fetal medicine as [Fetal skin edema HP:0025672](https://hpo.jax.org/app/browse/term/HP:0025672)
I have seen a few articles with Papillary dermal edema but cannot find a good definition. Can you provide more context?

**Comment by MickeySegal** [comment]
https://www.ncbi.nlm.nih.gov/books/NBK349072/ "Histopathologic examination shows hyperkeratosis, nonspecific epidermal atrophy, dermal edema, incontinence of pigment with or without cytoid bodies..."

**Comment by MickeySegal** [comment]
Seems fine.

**Comment by pnrobinson** [comment]
@MickeySegal 
added as
Interstitial dermal edema
HP:0034989
