### ISSUE TITLE
NTR: Skin biopsy: vacuolated basal layer of epidermis (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9397]
New term request Skin biopsy: vacuolated basal layer of epidermis (elthat_160315042443): Vacuolation

**Comment by pnrobinson** [comment]
@MickeySegal
I am trying to find a good definition. What disease does this pertain to?

**Comment by MickeySegal** [comment]
https://www.ncbi.nlm.nih.gov/books/NBK349072/ "focal vacuolization of the basal layer of the epidermis".

**Comment by pnrobinson** [comment]
I am wondering if this term is sufficient
[Keratinocyte vacuolization HP:0034703](https://hpo.jax.org/app/browse/term/HP:0034703)
Looking at this illustration of Kindler syndrome, it seems the vacuolization is focused on the basal layer but can also been seen to some extent in other regions. https://journals.lww.com/ijpd/Fulltext/2014/15010/Kindler_syndrome__A_case_presenting_with.12.aspx

**Comment by MickeySegal** [comment]
https://www.oatext.com/kindler-syndrome-a-very-rare-bullosa-poikyloderma-discovered-in-a-baby.php describes "vacuolization of basal keratinocyte" so it seems close enough to merge this finding into HP:0034703.

**Comment by pnrobinson** [comment]
Thanks, closing
