### ISSUE TITLE
NTR: Skin biopsy: squamous epitheliomas (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9399]
New term request Skin biopsy: squamous epitheliomas (elthat_160614030713): Multiple self-healing  UMLS: 0546476

**Comment by pnrobinson** [comment]
@MickeySegal
it seems this type of tumor is always "self-healing", that is, I do not see any non-self-healing squamous epitheliomas in the literature. Should this be made part of the label? https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7760568/

**Comment by MickeySegal** [comment]
That is the only disease for which we use the finding.  One could argue for adding self-healing or multiple to the label, but then the finding seems crafted for this one disease.  This is a judgment call, and I'll adopt whatever you choose.

**Comment by pnrobinson** [comment]
I do not think this type of tumor exists in other settings and the "self-healing" seems to be inhereent in this kind of tumor. However, the "multiple" does not, so I am adding this, please reopen this issue if there is an error

HP:0034720

Label: Self-healing squamous epithelioma
Def: A type of skin tumor that initially presents as a reddish macule and subsequently becomes papular, enlarged, ulcerated and ultimately heals leaving pitted scars.
Comment: Individuals with pathogenic variants in TGFBR1 may present with multiple self-healing squamous epitheliomas.
