### ISSUE TITLE
pregnancy specific terms need restricted axioms

### ISSUE THREAD

**Issue by mellybelly** [obophenotype/human-phenotype-ontology#940]
We will need axioms that limit certain HPO terms to pregnant females (similar to other developmental stage restrictions). This will need to be coordinated with anatomical stage/sex restrictions. 

Some phenotypes have a higher propensity during pregnancy but are not limited to it.

**Comment by mellybelly** [comment]
Relevant comments, can be broken out into different tickets later

HP:0009800 This is not a precise enough term as the definition is maternal diabetes of either type 1, 2 or gestational - a better definition for our purposes (or sub definition of this term) would include those specifics

HP:0006575 and HP:0001406 - these phenotypes are correct but not specific to pregnancy (and may be some confusion with cholestasis outside pregnancy if used). In our case HP:0000952 is the best fit for the jaundice part of the phenotype. This issue speaks to the problem we were discussing last week around phenotypes within pregnancy and how that fits into the ontology.

HP:0012115 Hepatitis is much more useful as a descriptor with the subtypes specified - in ICP for example there is a clear association with Hep C but not the other types.

HELLP syndrome is a specific disorder of pregnancy (basically severe pre-eclampsia) which is not captured by the HPO terms listed (HP:0001878 and 1890).

HP:0002605 is the correct descriptor but as above in this case is in the context of gestation.

HP:0001197 seems a high level descriptor for a range of abnormalities but does not include the specific abnormality of fatal growth retardation.

**Comment by pnrobinson** [comment]
@mellybelly What is the status of this? Should we move it to the design patterns wiki? It seems there are some other terms that are similar, and it would be good to think up a general design pattern with things like
restricted to <entity>
has_higher_propensity_in <entity>

**Comment by pnrobinson** [comment]
I have moved this discussion to the wiki page:
https://github.com/obophenotype/human-phenotype-ontology/wiki/Restriction
