### ISSUE TITLE
NTR: Palatine biopsy: teratoma (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9403]
New term request Palatine biopsy: teratoma (elthat_161002172607): Palate

**Comment by pnrobinson** [comment]
@MickeySegal
would this term be sufficient?
https://hpo.jax.org/app/browse/term/HP:0031227

**Comment by MickeySegal** [comment]
We use this only for Epignathus, which seems to be the focus of the HPO entry as well.  So we will use this code.

**Comment by pnrobinson** [comment]
OK. I will add Palatine teratoma as a related synonym to Epignathus.
