### ISSUE TITLE
incomplete/complete cleft lip/palate

### ISSUE THREAD

**Issue by sabrinatoro** [obophenotype/human-phenotype-ontology#9414]
@pnrobinson 
I need to map orofacial clefts (lip and palate) data to HP terms.  I need terms for **complete/incomplete** cleft palate or cleft lip.
HP has a term for 'Incomplete cleft of the upper lip' (HP:0011340), but there is currently no term for "complete" cleft of the upper lip. There is also no term for "complete/incomplete" cleft palate (general, soft, and hard palate). 

Can we have new HPO terms for the complete/incomplete version of the cleft lip/palate? 
- if so, I will submit a list of terms needed
- if not, what is the best way to curate data for complete/incomplete cleft lip/palate? (maybe create new modifier terms? or use a pato term?) 

Thank you!

**Comment by sabrinatoro** [comment]
the list of terms needed would be:

- Complete cleft of the upper lip (sister class of ‘Incomplete cleft of the upper lip’)
- Complete bilateral cleft lip (child of ‘Bilateral cleft lip’)
- Incomplete bilateral cleft lip (child of ‘Bilateral cleft lip’ and ‘Incomplete cleft of the upper lip’)
- Complete unilateral cleft lip (child of ‘Unilateral cleft lip’)
- Incomplete unilateral cleft lip (child of ‘Unilateral cleft lip’ and ‘Incomplete cleft of the upper lip’)
- Complete cleft palate (child of ‘Cleft palate’)
- Incomplete cleft palate (child of ‘Cleft palate’)
- Complete cleft hard palate (child of ‘Cleft hard palate’)
- Incomplete cleft hard palate (child of ‘Cleft hard palate’)
- Complete cleft soft palate (child of ‘Cleft soft palate’)
- Incomplete cleft soft palate (child of ‘Cleft soft palate’)
- Complete cleft maxillary alveolus (child of ‘Cleft maxillary alveolus’)
- Incomplete cleft maxillary alveolus (child of ‘Cleft maxillary alveolus’)
- Complete bifid uvula (child of 'Bifid uvula')
- Incomplete bifid uvula (child of 'Bifid uvula')

**Comment by pnrobinson** [comment]
@sabrinatoro 
Complete cleft palate occurs when there is a cleft of the hard and soft palate
Incomplete cleft palate occurs when there is a cleft of the soft palate only and at least some of the bone portion of the palate is intact. 
=> Thus, some of these terms are (near) synonyms of existing terms
Are you working with a domain expert who can advise on the preferred terminology?

**Comment by sabrinatoro** [comment]
Thank you @pnrobinson 
Yes, I am working with a domain expert. I will ask about preferred terminology.

**Comment by pnrobinson** [comment]
@sabrinatoro 
Is this issue closable because of recent new terms etc?

**Comment by sabrinatoro** [comment]
Yes, I think this issue is a duplicate and can be closed.
