### ISSUE TITLE
NTR: Arthrocentesis: elevated WBC >50,000 / mm3 in synovial fluid (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9415]
New term request Arthrocentesis: elevated WBC >50,000 / mm3 in synovial fluid (lee231_180709135347): Neutrophils, white blood cells, leukocytes; pus; purulence; suppurative  UMLS: 0919784

**Comment by pnrobinson** [comment]
@MickeySegal

There is a term called "Synovitis" that is related but not currently defined.
We could create a term called Purulent synovial fluid -- not sure if the degree of purulence is essential?

**Comment by MickeySegal** [comment]
We specify the level of purulence as guidance but for HPO that specification is not needed.

**Comment by pnrobinson** [comment]
@MickeySegal 

added as
HP:0034939
Purulent synovial fluid
