### ISSUE TITLE
NTR: Bone marrow: megakaryocytes small (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9416]
New term request Bone marrow: megakaryocytes small (elthat_181102155535):   UMLS: 3551067

**Comment by pnrobinson** [comment]
@MickeySegal - is this what is intended?
suggested term label
Reduced bone-marrow megakaryocyte size
def: Decreased in average size (diameter) of megakaryocytes in the bone marrow. Megakaryocyte diameter can be assessed as using automated cellular imaging systems.
PMID:17515875

**Comment by MickeySegal** [comment]
Good.

**Comment by pnrobinson** [comment]
@MickeySegal
added as HP:0034541
