### ISSUE TITLE
NTR: Muscle biopsy: LAMA2 decreased by immunostaining (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9418]
New term request Muscle biopsy: LAMA2 decreased by immunostaining (elthat_181230144800):

**Comment by pnrobinson** [comment]
@MickeySegal
LAMA2 is the gene symbol -- do we mean
Reduced muscle laminin alpha-2 chain staining
def: A decreased amount of laminin alpha-2 chain in muscle tissue. This feature can be shown by immunohistochemistry or Western blotting of muscle tissue.

**Comment by MickeySegal** [comment]
We were just following https://www.omim.org/entry/618138 "Muscle biopsy showed partial and variably decreased immunostaining for LAMA2 as well as increased immunostaining for LAMA5" but your usage seems more proper.  We will use the protein description in the title and include the gene symbol in the explanatory terms.

**Comment by pnrobinson** [comment]
@MickeySegal 

adding as
HP:0034828
Reduced muscle laminin alpha-2 chain staining
