### ISSUE TITLE
NTR: Pus on bone aspirate (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9421]
New term request Pus on bone aspirate (seidel_190104152532): Aspiration; purulence; suppurative

**Comment by pnrobinson** [comment]
@MickeySegal
is this basically a synonym for [Osteomyelitis HP:0002754](https://hpo.jax.org/app/browse/term/HP:0002754)?

**Comment by MickeySegal** [comment]
We consider osteomyelitis more of a disease than a finding, but of course there is no clear distinction.  Our pediatrician and pediatric rheumatologist (Sundel) characterized osteomyelitis by:
Bone biopsy: inflammation (osteitis) sundel_140720170037
Bone biopsy: culture positive sundel_140720170156
Pus on bone aspirate seidel_190104152532

I've added your osteomyelitis term to each of these, but if you make individual terms we will add those also.

**Comment by pnrobinson** [comment]
closing as with other issues
