### ISSUE TITLE
NTR: Bone marrow: myeloid hyperplasia (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9429]
New term request Bone marrow: myeloid hyperplasia (nadea3_190710135914): Granulocytosis  UMLS: 0427703

**Comment by pnrobinson** [comment]
@MickeySegal
Is this synonymous with [Bone marrow hypercellularity](https://www.ebi.ac.uk/ols/ontologies/hp/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FHP_0031020)

**Comment by MickeySegal** [comment]
It seems to be the same thing, e.g., https://www.informatics.jax.org/vocab/mp_ontology/MP:0010373.  
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1474249/ notes that "The term myeloid hyperplasia has been used interchangeably with many other terms to describe an increased production of granulocytes, megakaryocytes, and erythrocytes in the spleen and other organs in the mouse."

We also have a "Bone marrow: hypercellularity" term (elthat_100822135442) mapped to https://hpo.jax.org/app/browse/term/HP:0031020.

It may make sense to merge these 2 terms.  It seems, however, that the same phenomenon is given different names in different contexts so it is not clear which term should be the name and which the synonym.

**Comment by pnrobinson** [comment]
@MickeySegal 
for now I am adding Myeloid hyperplasia as the synonym, since i think that Bone marrow hypercellularity is more unambiguous. We can change the order if there is reason to.

**Comment by MickeySegal** [comment]
I merged our terms in the way you suggest.
