### ISSUE TITLE
NTR: Liver biopsy: lymphoplasmacytic infiltrate (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9430]
New term request Liver biopsy: lymphoplasmacytic infiltrate (chang6_190715195712): Hepatitis; cellular infiltrate  UMLS: 1334467

**Comment by pnrobinson** [comment]
@MickeySegal
is it this finding?
https://www.researchgate.net/figure/Interface-hepatitis-demonstrated-by-infiltration-of-lymphoplasmacytic-infiltrate-into-the_fig1_51494342
Should we say Periportal?

**Comment by MickeySegal** [comment]
They sound the same.  We also have this for autoimmune hepatitis, and also for Hepatitis C infection.

**Comment by pnrobinson** [comment]
Currently, the HPO has
[Interface hepatitis HP:0032220](https://hpo.jax.org/app/browse/term/HP:0032220)
which admittedly is a bundled term but one that is found often. I am not sure if this is synonymous with the anomaly you are referring to?  @MickeySegal

**Comment by MickeySegal** [comment]
Seems good enough.

**Comment by pnrobinson** [comment]
thanks, closing
