### ISSUE TITLE
NTR: Skin biopsy: epidermal hyperplasia (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9433]
New term request Skin biopsy: epidermal hyperplasia (elthat_191123171335): Epidermis; thick  UMLS: 0263641

**Comment by pnrobinson** [comment]
@MickeySegal
Is this perhaps a synonym of [Epidermal acanthosis HP:0025092](https://hpo.jax.org/app/browse/term/HP:0025092) ?
See here - https://www.ncbi.nlm.nih.gov/books/NBK562206/

**Comment by MickeySegal** [comment]
We use this for:

- https://www.omim.org/entry/618531 "Histopathology of lesional skin showed psoriasiform hyperplasia of the epidermis with focal parakeratosis and mild perivascular lymphocytic infiltration in the superficial dermis"
- https://www.omim.org/entry/618535 "Mid-ventral forearm skin biopsy from the father showed thickened epidermis and stratum corneum, with a water content pattern in the stratum corneum that was more heterogeneous than controls. Stained sections showed densely packed collagen fibers in the papillary dermis and an increased number of proliferating cells in the epidermis"
- https://www.omim.org/entry/619208 "Histologic analysis of skin from patient 1 showed thickening of the epidermis (acanthosis) and of the stratum corneum (hyperkeratosis). Immunostaining revealed significantly increased mast cell counts in the dermis and greater percentages of proliferating cells in the basal layer of the interfollicular epidermis, consistent with hyperproliferation"

So it seems like epidermal acanthosis works here.  We have that as elthat_110327143243 with HP:0025092 so I will merge them and we don't need a new term.

**Comment by pnrobinson** [comment]
OK, I will add epidermal hyperplasia as a RELATED SYNONYM
