### ISSUE TITLE
NTR: Lung biopsy: cylindromas (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9437]
New term request Lung biopsy: cylindromas (elthat_200501102255):

**Comment by pnrobinson** [comment]
@MickeySegal
I think the preferred name is [Adenoid Cystic Carcinoma](https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C2970) ?

**Comment by MickeySegal** [comment]
We got it from https://www.ncbi.nlm.nih.gov/books/NBK555820/, describing cylindromas in both skin and lung (and some salivary adenomas).  

I see in https://en.wikipedia.org/wiki/Cylindroma that "Adenoid cystic carcinoma" is a type of cylindroma in the salivary gland and that another type is in the skin, but there is no mention of ones in the lung, but the author of the GeneReviews article is likely to be more knowledgeable.

**Comment by pnrobinson** [comment]
@MickeySegal 
added as 
Pulmonary cylindroma
HP:0034637
