### ISSUE TITLE
NTR: Esophageal biopsy: neuron degeneration of the myenteric plexus (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9441]
New term request Esophageal biopsy: neuron degeneration of the myenteric plexus (nadea3_210825164438):

**Comment by pnrobinson** [comment]
@MickeySegal

adding as 
HP_0034520
Esophageal myenteric plexus degeneration
def: Deterioration of the cells of the myenteric plexus (also known as the Auerbach plexus) located between the layers of the muscular propria of the esophagus.

**Comment by MickeySegal** [comment]
Is there a reason to avoid the more specific: Deterioration of the **neurons** of the myenteric plexus... ?
