### ISSUE TITLE
NTR: Muscle biopsy: granulofilamentous aggregates (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9443]
New term request Muscle biopsy: granulofilamentous aggregates (elthat_211022034448):   UMLS: 4313069

**Comment by pnrobinson** [comment]
@MickeySegal -- please specific which disease(s) show this feature, I am not sure what is being referred to. Could it be this? https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2776705/

**Comment by MickeySegal** [comment]
We used it for the same condition; also see https://www.omim.org/entry/619178.  It is a bundled term but since there are 3 UMLS entries using the term it might make sense to keep it.

**Comment by pnrobinson** [comment]
@MickeySegal 
added as
Muscle fiber granulofilamentous inclusion bodies
HP:0034635
