### ISSUE TITLE
NTR: Muscle biopsy: multinucleated fibers (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9444]
New term request Muscle biopsy: multinucleated fibers (elthat_211022035126):   UMLS: 5543040

**Comment by pnrobinson** [comment]
@MickeySegal
skeletal muscle cells are normalled multinucleated -- https://www.kenhub.com/en/library/anatomy/types-of-muscle-cells
can you specific the abnormal finding being described here?

**Comment by MickeySegal** [comment]
A geneticist entered this from https://www.omim.org/clinicalSynopsis/619178 but I agree that it makes no sense to call that abnormal and I've deleted the finding.

**Comment by pnrobinson** [comment]
thanks, closing
