### ISSUE TITLE
NTR: Liver biopsy: sulfide:quinone oxidoreductase activity low (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9445]
New term request Liver biopsy: sulfide:quinone oxidoreductase activity low (elthat_211130022445): SQOR; hepatic  UMLS: 5543168

**Comment by MickeySegal** [comment]
The code assigned here will be used also for SimulConsult elthat_211130022818.

**Comment by pnrobinson** [comment]
see #9446
