### ISSUE TITLE
NTR: Uterine cervix biopsy: dysplasia  (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9449]
New term request Uterine cervix biopsy: dysplasia  (elthat_211226184638): Uterus; cervical dysplasia  UMLS: 0007868

**Comment by pnrobinson** [comment]
@MickeySegal
I think this is the same as [Cervical dysplasia HP:0032131](https://hpo.jax.org/app/browse/term/HP:0032131)
I am adding the synonym Uterine cervix dysplasia
Please reopen this issue if I am misunderstanding something

**Comment by MickeySegal** [comment]
Agree.  It is strange - we already had the corresponding UMLS term that referred to the HPO term.  I don't know how we missed that unless it reflects a recent update.
