### ISSUE TITLE
NTR: Liver biopsy: hepatoportal microvascular dysplasia (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9450]
New term request Liver biopsy: hepatoportal microvascular dysplasia (elthat_211227190029): Hepatic biopsy; hypoplasia of portal veins  UMLS: 1299889

**Comment by pnrobinson** [comment]
@MickeySegal
Is this the same (or nearly the same) as [Congenital absence of portal vein HP:0031942](https://hpo.jax.org/app/browse/term/HP:0031942)

**Comment by MickeySegal** [comment]
We use this only for https://omim.org/entry/619433, where the name used in our finding doesn't appear and the synonym we used does appear as "hypoplasia of the portal veins".  I changed the name to that.  

This is clearly related to https://hpo.jax.org/app/browse/term/HP:0031942, though perhaps as a sibling term under parent https://hpo.jax.org/app/browse/term/HP:0031941; it is not quite https://hpo.jax.org/app/browse/term/HP:0005201 either.

**Comment by pnrobinson** [comment]
@MickeySegal 
added as 
HP:0034548
