### ISSUE TITLE
NTR: Liver biopsy: portal arteries, hypoplasia (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9451]
New term request Liver biopsy: portal arteries, hypoplasia (elthat_211227190211): Hepatic biopsy

**Comment by pnrobinson** [comment]
@MickeySegal
never heard of this one and cannot find it in PubMed -- can you provide context? What disease is this observed in?

**Comment by MickeySegal** [comment]
We have this for only one disease, as mentioned in https://www.omim.org/entry/619433

**Comment by pnrobinson** [comment]
@MickeySegal
Added as 
Portal artery hyperplasia
HP:4000148

-- The OMIM entry has HYPER rather than HYPO -- please reopen if I have misunderstood something

**Comment by MickeySegal** [comment]
You are right.  Fixed at my end.
