### ISSUE TITLE
NTR: Teeth X-ray: dental roots curved (Teeth)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9457]
New term request Teeth X-ray: dental roots curved (segal_090710193003): Tooth

**Comment by pnrobinson** [comment]
@MickeySegal
Are you referring to Tooth Dilaceration?
https://www.colgate.com/en-us/oral-health/mouth-and-teeth-anatomy/what-is-tooth-dilaceration

**Comment by MickeySegal** [comment]
That seems to be often seen along with curved dental roots, but we got it from:
https://www.ncbi.nlm.nih.gov/books/NBK1525/ "curved dental roots"
and
https://ojrd.biomedcentral.com/articles/10.1186/1750-1172-9-84 "shorter, sometimes curved, roots"

**Comment by pnrobinson** [comment]
added as HP_4000104
