### ISSUE TITLE
NTR: Teeth: double row (Teeth)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9459]
New term request Teeth: double row (hresko_220105154309): Two rows  UMLS: 1839799

**Comment by pnrobinson** [comment]
@MickeySegal
are you referring to "shark teeth"?
https://www.smilesbydrdonan.com/2017/09/happens-child-two-rows-teeth-dentist-fresno-ca/ ?

**Comment by MickeySegal** [comment]
That seems like the same thing.  I added "shark teeth" to our explanatory terms.

**Comment by pnrobinson** [comment]
@MickeySegal 
added as
HP:4000168
