### ISSUE TITLE
Term request: Mild Ataxia

### ISSUE THREAD

**Issue by GenomeDeb** [obophenotype/human-phenotype-ontology#946]
Requesting term addition for Mild Ataxia, thank you. Deb

**Comment by pnrobinson** [comment]
Hi Deb,
our strategy with items like "Mild abnormal X" is to use the term "abnormal X" together with the modifier term "Mild (HP:0012825)". We make an exception to this rule if there is an accepted clinical categorization scheme such as that for intellectual disability, where borderline, mild, moderate, severe, and profound are assigned to specific IQ ranges. Therefore, if there is something similar for ataxia (I am not aware of this), then we would add a set of terms accordingly. 
Could you ask your IT people if it is possible to use the HPO modifiers (you can find them all using an HPO browser like Ontobee or the one on our website)? Please reopen if needed.
