### ISSUE TITLE
NTR: Acetazolamide relieves attacks (Triggers or responses: drugs or treatments)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9461]
New term request Acetazolamide relieves attacks (segal_030225182034):

**Comment by pnrobinson** [comment]
@MickeySegal
What disease(s) are we covering here? Do we want to specifically emphasize "attacks"?

**Comment by pnrobinson** [comment]
@MickeySegal
Added as HP:4000148

**Comment by MickeySegal** [comment]
Lots of different conditions and types of attacks.  This is seen in episodic ataxia (e.g., https://www.ncbi.nlm.nih.gov/books/NBK25442/), myasthenic syndrome (e.g., https://www.omim.org/entry/614198), potassium-aggravated myotonia (https://www.omim.org/entry/608390).

**Comment by pnrobinson** [comment]
@MickeySegal 
added as 
Ameliorated by acetazolamide
HP:0034535
