### ISSUE TITLE
NTR: Ethanol exposure, excessive (fetal included) (Triggers or responses: drugs or treatments)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9468]
New term request Ethanol exposure, excessive (fetal included) (segal_041110222251): EtOH, alcohol; fetal exposure to alcohol  UMLS: 4038778

**Comment by pnrobinson** [comment]
@MickeySegal
Given the distinct medical consequences, it seems better not to conflate the various kinds of alcohol exposure
Perhaps we should add a term into the past medical history along the lines of 

History of excessive intrauterine alcohol exposure

**Comment by pnrobinson** [comment]
The "adult" term would be related to Alcoholism HP:0030955 (although this is focussing on the behavior rather than the exposure; I am not sure if we need to rethink this), but I think the fetal term is different in that it is second-hand drinking so to speak.

I have added
Fetal alcohol exposure
HP:0034984

If the Alcoholism term is not sufficient please reopen!

**Comment by MickeySegal** [comment]
Fine.  I'll use both that and https://hpo.jax.org/app/browse/term/HP:0030955 to cover the full age range.
