### ISSUE TITLE
Term Request: Rosette-forming glioneuronal tumor of the fourth ventricle

### ISSUE THREAD

**Issue by GenomeDeb** [obophenotype/human-phenotype-ontology#947]
Requesting a term (cancer term). RGNT is a type of cancer Rosette-forming glioneuronal tumor of the fourth ventricle. I don't know how important "of the fourth ventricle" is but when I looked this up many reports have "of the fourth ventricle". The main term could be Rosette-forming glioneuronal tumor, and a term above that glioneuronal tumor.

**Comment by pnrobinson** [comment]
Adding this term as  Rosette-Forming Glioneuronal Tumor, equivalent to NCI  (Code C129431). Note we will aim to coordinate with NCI on the cancer terms in the future.
