### ISSUE TITLE
NTR: Thyroid hormone triggers symptoms (Triggers or responses: drugs or treatments)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9471]
New term request Thyroid hormone triggers symptoms (segal_090419171300):

**Comment by pnrobinson** [comment]
@MickeySegal
for the sake of being concrete, I wonder if we should write
Triggered by levothyroxin exposure?
What diseases is being covered here?

**Comment by MickeySegal** [comment]
The main one is thyrotoxic periodic paralysis

**Comment by pnrobinson** [comment]
@MickeySegal 
added
Triggered by levothyroxin exposure
HP:0034827
