### ISSUE TITLE
NTR: Steroid treatment improves condition (Triggers or responses: drugs or treatments)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9481]
New term request Steroid treatment improves condition (segal_100721140147): Glucocorticosteroids (GCS); steroid responsiveness; prednisone; methylprednisolone, IVMP; dexamethasone

**Comment by pnrobinson** [comment]
@MickeySegal
There are some who say that steroids help with everything, at least for a short while. Would it be good to try to specify this term or provide a comment recommended when to use it?

**Comment by MickeySegal** [comment]
We use it for about 100 diseases, primarily rheumatologic.  

How about "alleviates abnormalities"?  I considered "symptoms", but many are "signs" or lab abnormalities.

**Comment by pnrobinson** [comment]
@MickeySegal 
I am adding a term
HP:0034825
Ameliorated by steroid medication
Applies to a sign or symptom that is improved or made more bearable by treatment with a steroid medication such as prednisone.
