### ISSUE TITLE
NTR: Diazoxide reduces hypoglycemia (Triggers or responses: drugs or treatments)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9507]
New term request Diazoxide reduces hypoglycemia (elthat_150916055531): Insulin secretion reduced; responsive

**Comment by pnrobinson** [comment]
@MickeySegal

this is too specific to be a good HPO term.
I imagine you are refering to https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9856357/
We would annotate this with a term from the (new) Medical Action Ontology (see https://monarch-initiative.github.io/maxo-annotations/)

**Comment by MickeySegal** [comment]
In https://ojrd.biomedcentral.com/articles/10.1186/1750-1172-6-63 this is used as a way of distinguishing various form of hyperinsulinemia: "Hypoglycemias are usually diazoxide-unresponsive, except in case of perinatal stress-induced transient hyperinsulinism, syndromic HI and HI related to HNF4A and GLUD1 mutations ...They are diffuse forms of HI and diazoxide-responsive with the exception of GCK mutations which can be diazoxide-unresponsive in some patients."
