### ISSUE TITLE
NTR: Zinc oral supplementation produces improvement (Triggers or responses: drugs or treatments)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9508]
New term request Zinc oral supplementation produces improvement (segal_190618182827):

**Comment by pnrobinson** [comment]
@MickeySegal
I think this is probably too broad unless there is a specific diagnostic test, see comments for #9509

**Comment by MickeySegal** [comment]
We use this only for https://omim.org/entry/201100.  It seems like the skin symptoms, the diarrhea and even the brain imaging improve with zinc supplementation, so I lean against splitting into those multiple specific findings.

**Comment by pnrobinson** [comment]
added! @MickeySegal 
HP_4000099
