### ISSUE TITLE
new term: Centrilobular groundglass opacification on CT

### ISSUE THREAD

**Issue by lcdaugherty** [obophenotype/human-phenotype-ontology#951]
relates to #914 BRIDGE_PAH_HPO_terms_20160616.xlsx

New term : Centrilobular groundglass opacification on CT
New definition: Centrilobular groundglass opacfication is a hazy area of increased attenuation in the lung with preserved bronchial and vascular markings seen on a CT scan. It is a non-specific sign with a wide aetiology including infection, chronic interstitial disease and acute alveolar disease.
Suggested Synonyms : Centrilobular groundglass opacification on imaging
HPO_ID superclass (parent): Diffuse reticular or finely nodular infiltrations HP:0002207

**Comment by pnrobinson** [comment]
Look here for references http://www.ncbi.nlm.nih.gov/pubmed/11699664  (no access to this article now)

**Comment by pnrobinson** [comment]
I think there should be a term, 
groundglass opacification on CT
with some children terms.

centrilobular = affecting the central parts of the lobules containing clusters of branching functional and anatomical units of the lung
