### ISSUE TITLE
NTR: Bronchodilator response positive acutely (dependence chronically) (Triggers or responses: drugs or treatments)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9510]
New term request Bronchodilator response positive acutely (dependence chronically) (segal_210723144615): Short acting beta-agonists (SABA; salbutamol, salmeterol, formoterol, vilanterol), anticholinergics (ipratropium, tiotropium, aclidinium, glycopyrronium) or methylxanthines (theophylline, theobromine, chocolate, coffee)  UMLS: 2128978

**Comment by pnrobinson** [comment]
@MickeySegal
this seems like a normal finding. Can you provide more context?

**Comment by MickeySegal** [comment]
I deleted the finding.

**Comment by pnrobinson** [comment]
OK!
