### ISSUE TITLE
NTR: Anticholinergic drug toxicity (Triggers or responses: drugs or treatments)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9513]
New term request Anticholinergic drug toxicity (segal_211028185209): Atropine, benztropine, scopolamine, diphenhydramine, antihistamines, jimson weed, nightshade, phenothiazines, tricyclics  UMLS: 0416669

**Comment by pnrobinson** [comment]
@MickeySegal

I do not think the "X drug toxicity" items are good HPO terms because they can include multiple phenotypic features and also include etiology.
Possibly terms from the OAE are better suited, e.g., :
https://www.ebi.ac.uk/ols4/ontologies/oae/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FOAE_0005827

thoughts?

**Comment by MickeySegal** [comment]
"Cholinergic syndrome" would be fine, but as someone who did a PhD thesis on cholinergic receptors, it doesn't seem much different.

**Comment by pnrobinson** [comment]
I mean the issue is that if we start to introduce terms such as X toxicity for side effects caused by medication X, we will need to add terms for all medications and this is probably not the way to go?

**Comment by MickeySegal** [comment]
It is meant to be the finding for the diagnosis "Anticholinergic intoxication".

**Comment by pnrobinson** [comment]
In the HPO universe, these "intoxication" items would probably be best described as (acute) diseases -- they have a specific etiology, they have a collection of phenotypic features (here: delirium, restlessness and picking at imaginary objects), a typical clinical course and a treatment. So these would be good Mondo terms. @nicolevasilevsky  I am closing the HPO NTRs, and we can think about whether to add a "toxidrome" branch to Mondo.
