### ISSUE TITLE
NTR: Opioid drug toxicity (Triggers or responses: drugs or treatments)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9516]
New term request Opioid drug toxicity (segal_211028200150): Heroin, morphine, fentanyl, oxycodone; opiates  UMLS: 0029100

**Comment by pnrobinson** [comment]
@MickeySegal
I am not sure that the "toxixity" term requests are actually phenotypic features (observations) rather than inferences about side effects? Can we discuss this issue?

**Comment by MickeySegal** [comment]
You are right.  I changed it to "use or abuse".  We use the finding for a variety of diagnoses such as "Opioid withdrawal syndrome" and "Ileus".

**Comment by pnrobinson** [comment]
@MickeySegal 
Is it then this
[Opioid addiction HP:0033515](https://hpo.jax.org/app/browse/term/HP:0033515)

**Comment by pnrobinson** [comment]
@MickeySegal 
similar questions about #9515 #9514 #9513 #9512
-- should these be "Triggered by X"  ?

**Comment by MickeySegal** [comment]
I imagine the following ontology:
Parent term : taking opioids
- Child term: abusing opioids
- Child term: using prescribed opioids for short or long term.

The diagnoses for which we use our term are opioid toxicity, opioid withdrawal, and ileus.  In all 3, it doesn't really matter whether you have a good or bad reason for taking opioids, hence the desire for the parent term or the 2 child terms.

Triggered might be OK for the parent term, but I think of trigger as more appropriate for something like hyperventilation triggering absence seizures.  Here, the triggering is less obvious.  The way we use these findings is that they are suggested as being useful diagnostically.  Here the question I'd want to ask is "Are you on opioids?" not "Was this triggered by opioids?" or "Are you an opioid abuser?"

**Comment by pnrobinson** [comment]
@MickeySegal see https://github.com/obophenotype/human-phenotype-ontology/issues/9512
