### ISSUE TITLE
NTR: Indomethacin over days effective in preventing attacks (Triggers or responses: drugs or treatments)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9517]
New term request Indomethacin over days effective in preventing attacks (segal_211109170024): Indocin; Nonsteroidal anti-inflammatory drug (NSAID)

**Comment by pnrobinson** [comment]
@MickeySegal

This is probably not a good HPO term. Thankfully Indomethacin is effective in preventing many symptoms such as headache and this does not seem specific enough to warrant a term -- if I am missing something, please provide more context.

**Comment by MickeySegal** [comment]
It is one of the few treatments that work for paroxysmal hemicrania, but I agree that it has other uses.

**Comment by pnrobinson** [comment]
closing, thanks
