### ISSUE TITLE
new term:  Excessive reduced blood flow to hands and feet

### ISSUE THREAD

**Issue by lcdaugherty** [obophenotype/human-phenotype-ontology#952]
relates to #914 BRIDGE_PAH_HPO_terms_20160616.xlsx

New term:  Excessive reduced blood flow to hands and feet
New definition: Excessive reduced blood flow in response to cold or emotional stress, causing discolouration of the fingers, toes.
Suggested Synonyms: Raynaud’s
HPO_ID superclass (parent): Abnormal vascular physiology HP:0030163

**Comment by pnrobinson** [comment]
I have made the term name to be Raynaud phenomenon, because I think it is more recognisable. Please reopen if you disagree.
