### ISSUE TITLE
NTR: Anticoagulant ingestion (Triggers or responses: drugs or treatments)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9527]
New term request Anticoagulant ingestion (segal_211228204837): Warfarin (Coumadin)  UMLS: 0573788

**Comment by pnrobinson** [comment]
@MickeySegal -- would 
History of recent anticoagulant ingestion
(child of https://hpo.jax.org/app/browse/term/HP:4000144)
capture the intended meaning?

**Comment by MickeySegal** [comment]
That seems fine.

**Comment by pnrobinson** [comment]
@MickeySegal 
adding with definition
Medical history of ingestion of anticoagulants prior to presentation.
HP:0034896
