### ISSUE TITLE
NTR: Nitrous oxide abuse (Triggers or responses: drugs or treatments)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9532]
New term request Nitrous oxide abuse (segal_220120141700):   UMLS: 2063168

**Comment by pnrobinson** [comment]
@MickeySegal
Currently, terms such as this are included under [Drug addiction HP:0033511](https://hpo.jax.org/app/browse/term/HP:0033511) rather than exposure. If this is OK, I will add this here

**Comment by MickeySegal** [comment]
That is fine.  We don't focus on the difference between a drug of abuse and a prescribed drug, but if such a distinction fits the HPO logic we will gladly use the code in the way that makes most sense for us.

**Comment by pnrobinson** [comment]
added as HP_4000128
