### ISSUE TITLE
NTR: History of medications associated with serum sickness-like reaction (Triggers or responses: drugs or treatments)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9540]
New term request History of medications associated with serum sickness-like reaction (segal_220420133426): Cefaclor, amoxicillin, sulfonamides, tetracyclines, ciprofloxacin, nonsteroidal antiinflammatory drugs (NSAIDs), barbiturates, carbamazepine, propranolol, thiouracil, and allopurinol

**Comment by MickeySegal** [comment]
Serum sickness and Serum sickness-like reaction (SSLR) are different clinical entities and triggered by different substances.  There is some discussion in https://www.ncbi.nlm.nih.gov/books/NBK559122/, notably "The precise mechanism of SSLR remains unclear; however, there could be a potential role of drug metabolites that are directly toxic to the cells. The features of serum sickness, such as vasculitis and glomerulonephritis, are not present in SSLR."

It seems like the name of the diseases is what needs changing; SSLR should get a name that more clearly distinguishes it from serum sickness.

**Comment by pnrobinson** [comment]
@MickeySegal 
I am not convinced that History of medications associated with <outcome> are good HPO terms, because in general HPO tries to avoid assumptions about pathophysiology. In general, I think that it is better to use the GA4GH Phenopacket to encode clinical courses - see e.g., https://pubmed.ncbi.nlm.nih.gov/36910590/.
I would propose for now that we do not include this term and the other analogous terms.
Thoughts?

**Comment by MickeySegal** [comment]
The way we use such findings is that if a disease triggered by such a medication is in the differential diagnosis, our Usefulness algorithm asks whether such a medication was used.  It is more of a correlation analysis than a statement about pathophysiology, though often the reason for the correlation is pathophysiology.  For natural language processing, the important part of the finding is the list of medications, and if one is found in the records, this will increase the chance of finding a drug-associated problem.

**Comment by pnrobinson** [comment]
Closing, see https://github.com/obophenotype/human-phenotype-ontology/issues/9541
