### ISSUE TITLE
NTR: History of medications associated with ANCA-associated vasculitis (Triggers or responses: drugs or treatments)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9541]
New term request History of medications associated with ANCA-associated vasculitis (segal_220420133838): Anti-thyroid drugs (benzylthiouracil, carbimazole, methimazole, propylthiouracil), adalimumab, etanercept, infliximab, golimumab, cephotaxime, minocycline, nitrofurantoin, trimethoprim-sulfamethoxazole, vancomycin, isoniazid, rifampicin, D-penicillamine, sulfasalazine, clozapine, thioridazine, allopurinol, atorvastatin, cocaine/levamisol, denosumab, hydralazine, isotretinoin, phenytoin

**Comment by pnrobinson** [comment]
@MickeySegal
see this comment -- https://github.com/obophenotype/human-phenotype-ontology/issues/9555
The current term request seems to be clearly past medical history, i.e., there is no inference that these medications were the cause, but there is an observation that the patient took one of the medications prior to presentation.
Are we intending to make this distinction? 
Currently the HPO has both triggered by and PMH (https://hpo.jax.org/app/browse/term/HP:0032443).

**Comment by MickeySegal** [comment]
As discussed in https://github.com/obophenotype/human-phenotype-ontology/issues/9555 there is a spectrum from clear causation to association that may or may not be causal.  For any particular finding, the position on this spectrum may change as science evolves.  

An excellent example is last week's controversy over gas stoves and asthma, with disagreement over whether an open flame of natural gas releases pollutants that trigger asthma attacks.  The New York Times and I are betting that it does, and the Wall Street Journal has doubled down claiming that it doesn't.  Accordingly, it is unclear whether to list natural gas stove as history or trigger for asthma.

The best approach is for you (and we) to create terms under either Trigger or History as seems sensible.  We can each change the classification as knowledge evolves.  In the meantime, we can use your History code for our Trigger or use you Trigger code for our history.

**Comment by pnrobinson** [comment]
I added a term called "Medication history" under Past Medical History. It seems to me that a lot of the medication terms are not known to deterministically cause a symptom but are something that we consider in the differential. We can additionally add terms for things that are certain, perhaps G6PD related for instance.

Here, I am not convinced it is good to have a term that contains a wide variety of agents. Maybe it would be better to have terms for individual categories and then to have software logic know that the categories can be associated with the side effect? Possibly we can also introduce HPO based annotations for the terms to make this easier?

**Comment by MickeySegal** [comment]
You are correct that this approach makes no sense without additional software logic.  In our software, that is our Usefulness algorithm, which when a particular drug-triggered illness is high in the differential diagnosis will promote to high usefulness a finding that has a list of known triggers of that condition.  

If you want to make separate HPO codes for each of the drugs listed we would then include that set of codes in our finding.  

We each should keep to the logic of our frameworks, but we can make them interoperable computationally in such ways.

**Comment by pnrobinson** [comment]
@MickeySegal 
probably we would encode this differently -- we are now using the Phenopacket Schema to encode cases and this can include a medication history. We do not do this now but if we did we would have a database that links certain medications to certain outcomes. I do not think it is in scope for the HPO to have terms like this that essentially already encode the diagnosis, and at most there would be terms such as Triggered by <medication class>. I am thinking it is probably best to close this collection of term requests and if desired think about new terms or schemas?

**Comment by MickeySegal** [comment]
Encoding each drug individually may make most sense.  We can accomplish that by the many specific terms that we've added.  We can get by without an HPO term for the collection.

**Comment by pnrobinson** [comment]
I will close these issues for now. Happy to work on this topic to make both of our systems work better, but for now it seems beyond the scope of what is (easily) possible with the HPO framework.
