### ISSUE TITLE
NTR: Calcium channel blocking drug use (Triggers or responses: drugs or treatments)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9542]
New term request Calcium channel blocking drug use (brumme_220601194021): Antagonists; CCB, includes: amlodipine, nicardipine, nifedipine, verapamil, diltiazem  UMLS: 4302930

**Comment by pnrobinson** [comment]
@MickeySegal 
for consistency with other labels, I added this as
Calcium channel blocker exposure
synonym as above
definition: History of having taken a calcium channel blocker such as amlodipine, nicardipine, nifedipine, verapamil, or diltiazem.
HP_4000119

**Comment by MickeySegal** [comment]
Good.  On our end, I've added the synonym "exposure" to our trigger findings, since the concepts are not simple to disentangle.
