### ISSUE TITLE
add two new subclass terms to Impaired left ventricular function HP: 0005162 

### ISSUE THREAD

**Issue by lcdaugherty** [obophenotype/human-phenotype-ontology#955]
relates to #914 BRIDGE_PAH_HPO_terms_20160616.xlsx

1) New term :  Left ventricular diastolic dysfunction on cardiac imaging
New definition: Evidence of left ventricular diastolic dysfunction on cardiac imaging.
HPO_ID superclass (parent): Impaired left ventricular function HP: 0005162

2) New term :  Left ventricular systolic dysfunction on cardiac  imaging
Definition: Evidence of left ventricular systolic dysfunction on cardiac imaging.
HPO_ID superclass (parent): Impaired left ventricular function HP: 0005162

**Comment by pnrobinson** [comment]
Hi Louise,
this is an interesting editorial about LV dysfunction:
http://www.ncbi.nlm.nih.gov/pmc/articles/PMC1767551/
I wonder if it would not be a better idea to either have the terms be called " Left ventricular systolic dysfunction" or to specify what measurement led to the inference (one could also have subterms that reflect things like E:E1 ratio etc -- there seem to be quite a few different ways of doing it.
Please let me know what you think!
