### ISSUE TITLE
NTR: Contralateral injury preceded symptoms (Triggers or responses: non-drug)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9550]
New term request Contralateral injury preceded symptoms (segal_211130164123):

**Comment by pnrobinson** [comment]
@MickeySegal
Similarly, should this be
History of recent cotralateral injury
Def:A history of an injury that occured several hours, days, or weeks before the current presenting complaint and is located on the same side of the body as the current presenting complaint.
Parent term -- see https://github.com/obophenotype/human-phenotype-ontology/issues/9551

**Comment by MickeySegal** [comment]
That sounds great.

**Comment by pnrobinson** [comment]
@MickeySegal 
Of course, my dumb. I have fixed the definition to
A history of an injury that occurred several hours, days, or weeks before the current presenting complaint and is located on the other side of the body relative to the current presenting complaint.
Term added as HP:4000151
