### ISSUE TITLE
NTR: Viral illness, antecedent (Triggers or responses: non-drug)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9553]
New term request Viral illness, antecedent (segal_211230174750):   UMLS: 5421677

**Comment by pnrobinson** [comment]
@MickeySegal
I wonder if if would be good to define what period of time is meant by "antecedant"? Are there any particular diseases being referred to?

**Comment by MickeySegal** [comment]
This is used for a bunch of illnesses, such as "Anti-NMDA receptor encephalitis" and " Immune thrombocytopenic purpura".  I suppose that "recent weeks" might be good for clarification.

**Comment by pnrobinson** [comment]
@MickeySegal 
added as
History of recent viral illness
HP_4000145
synonym Antecedent viral illness
