### ISSUE TITLE
Is HP:0003161 description correct?

### ISSUE THREAD

**Issue by MickeySegal** [obophenotype/human-phenotype-ontology#9559]
**HPO term**
4-Hydroxyphenylpyruvic aciduria HP:0003161

**Suggested revision of logical definition**
Shouldn't "Increased concentration of pyruvic acid in the urine" be "Increased concentration of 4-hydroxyphenylpyruvic acid in the urine"?

**Comment by pnrobinson** [comment]
@MickeySegal  thanks for pointing out this error -- fixed.
