### ISSUE TITLE
review parentage for ‘Submucous cleft of soft and hard palate’ 

### ISSUE THREAD

**Issue by sabrinatoro** [obophenotype/human-phenotype-ontology#9563]
‘Submucous cleft of soft and hard palate’ (HP:0410031) should be a child of 
- 'Submucous cleft hard palate' (HP:0000176) AND
- 'Submucous cleft soft palate' (HP:0011819)

This would be similar to 'Bilateral cleft lip and palate' (HP:0002744) that is a child of both 'Bilateral cleft lip' (HP:0100336) and 'Bilateral cleft palate' (HP:0100337)

**Comment by pnrobinson** [comment]
@sabrinatoro 
I am closing this because I think we addressed the issue.
