### ISSUE TITLE
New cleft lip/palate related terms

### ISSUE THREAD

**Issue by sabrinatoro** [obophenotype/human-phenotype-ontology#9564]
The following terms are required to annotate of orofacial phenotypes. 
(these are in addition of the terms referring to complete/incomplete terms in #9414)

- **cleft upper lip with or without cleft of maxillary alveolus** 
Parent: ‘Oral cleft’ (HP:0000202)
Children: ‘Cleft lip’ (HP:0410030) and ‘Cleft maxillary alveolus’ (HP:0410003)
Note: This term is required for annotations for which the information might or might not include a clef in the maxillary alveolus. (ie it was not recorded)

**- Microform lip** (could be notch, groove, or scar) 
Parents: though it is considered an “orofacial defect", the parent should probably not be ‘Cleft upper lip’ (HP:0000204) since there is no gap in the upper lip. Maybe the best parent would be 'Abnormal upper lip morphology' (HP:0000177)

**- Unilateral cleft maxillary alveolus**
Definition: A cleft maxillary alveolus on one side only.
Parent: ‘Cleft maxillary alveolus’ (HP:0410003)

**- Bilateral cleft maxillary alveolus**
Definition: A cleft maxillary alveolus on both the left and right sides.
Parent: ‘Cleft maxillary alveolus’ (HP:0410003)

**- ‘Unilateral cleft lip and palate’** 
Sister class of ‘Bilateral cleft lip and palate’ (HP:0002744)
Children: 'Bilateral cleft lip and palate' (HP:0002744), new ‘Unilateral cleft lip and palate’ 
Parent:  ‘Cleft upper lip’ (HP:0000204), ‘Cleft palate’ (HP:0000175)

**- 'Cleft lip and palate'**
Children: 'Bilateral cleft lip and palate' (HP:0002744), new ‘Unilateral cleft lip and palate’ 
Parent:  ‘Cleft upper lip’ (HP:0000204), ‘Cleft palate’ (HP:0000175)

**Comment by pnrobinson** [comment]
cleft upper lip with or without cleft of maxillary alveolus
=> This is a bundled term. Annotate separately!
Microform seems similar to https://hpo.jax.org/app/browse/term/HP:0011340 -- are they synonyms?
Let's not make terms with unilateral/bilateral, let's use modifiers.
We may need to revised some of the old terms for consistency!
Can we do an HPO zoom?

**Comment by pnrobinson** [comment]
@sabrinatoro 
can we close this -- I think these issues have been subsequently addressed?

**Comment by pnrobinson** [comment]
I will close this, I think we have implemented.
