### ISSUE TITLE
HP:0001763 has a comment with what looks like logic code

### ISSUE THREAD

**Issue by MickeySegal** [obophenotype/human-phenotype-ontology#9568]
**HPO term**
HP:0001763

**Bug description**
This looks like logic code, not text for the reader:
Comment:    'has part' some (flat and ('inheres in' some 'Longitudinal arch of foot (adult human)') and ('has modifier' some abnormal))

**Comment by pnrobinson** [comment]
Thanks for pointing this out, this was a note that is no longer needed and I have deleted it
