### ISSUE TITLE
Unable to export HPO associations

### ISSUE THREAD

**Issue by adt00** [obophenotype/human-phenotype-ontology#9570]
**HPO term**

**Bug description** Unable to export HPO associations: https://hpo.jax.org/app/browse/disease/OMIM:608363

**Comment by pnrobinson** [comment]
@iimpulse -- can you take a look - I can conform that the export button on this page is not working

**Comment by iimpulse** [comment]
Hi @adt00 thanks for the report. I've released a hotfix to the sit which resolved this issue. Please confirm and close @pnrobinson https://github.com/TheJacksonLaboratory/hpo-web/pull/232

**Comment by pnrobinson** [comment]
Thanks @iimpulse this is working now!
