### ISSUE TITLE
Typo in definition for Ventricular escape rhythm (HP:0005155)

### ISSUE THREAD

**Issue by turnovec** [obophenotype/human-phenotype-ontology#9571]
**HPO term**
HP:0005155 | Ventricular escape rhythm 

**Bug description**
First sentence of definition:
"A ventircular escape rhythm occurs whenever higher-lever pacemakers in AV junction or sinus node fail to control ventricular activation. "
ventircular → ventricular

**Comment by pnrobinson** [comment]
fixed, thanks!
