### ISSUE TITLE
Typo in HP:0030132 (Willibrand instead of Willebrand)

### ISSUE THREAD

**Issue by turnovec** [obophenotype/human-phenotype-ontology#9572]
**HPO term**
HP:0030132 | Absence of large von Willibrand factor multimers 

**Bug description**
Label: "Absence of large von Willibrand factor multimers"
Should be: "Absence of large von Willebrand factor multimers"

**Comment by turnovec** [comment]
Looks like same typo is also in:
HP:0030130 | Impaired von Willibrand factor collagen binding activity (also in fist occurance in definition)
HP:0030132 | Absence of large von Willibrand factor multimers 
HP:0030135 | Absence of intermediate von Willibrand factor multimers

**Comment by pnrobinson** [comment]
thanks, I fixed all the stray Willibrands -> Willebrand is correct
