### ISSUE TITLE
Discrepancy in spelling of "Hoffmann" (HP:0031993)

### ISSUE THREAD

**Issue by turnovec** [obophenotype/human-phenotype-ontology#9573]
**HPO term**
HP:0031993 | Hoffmann sign

**Bug description**
In label it is "Hoffmann sign" (with double "n"), but the definition begins with: "A Hoffman test is performed by flicking the fingernail..." (with just one "n"). It is named after german neurologist and his name was Johann Hoffmann (with double "n"), so I think it should be corrected to double "n" in definition.

**Comment by pnrobinson** [comment]
fixed! Thanks so much!
