### ISSUE TITLE
Strange synonym for HP:0002616 (Aortic root aneurysm)

### ISSUE THREAD

**Issue by turnovec** [obophenotype/human-phenotype-ontology#9575]
**HPO term**
HP:0002616 |Aortic root aneurysm

**Bug description**
Is "Bulge in wall of root of large artery that carries blood away from heart" really a synonym? Or it was intended as definition? But this term already has definition - "An abnormal localized widening (dilatation) of the aortic root."

**Comment by pnrobinson** [comment]
This is intended to be a lay-person synonym - I will check if the layperson label is correct

**Comment by pnrobinson** [comment]
The lay person label is correct, closing.
