### ISSUE TITLE
Is definition for HP:0031932 (Aorto-left ventricular tunnel) complete?

### ISSUE THREAD

**Issue by turnovec** [obophenotype/human-phenotype-ontology#9576]
**HPO term**
HP:0031932 (Aorto-left ventricular tunnel)

**Suggested revision of textual definition**
Current definition:
Aorto-left ventricular tunnel (ALVT) is a congenital extracardiac channel connecting the ascending aorta above the sino-tubular junction to either left ventricular cavity.

Is it complete? On the end there is "...either..." and then there is "left ventricular cavity". Usually there are two subjects after "either" - either A or B...

**Comment by pnrobinson** [comment]
Thanks for pointing this out. Two words were omitted inadvertently. The definition was corrected to

Aorto-left ventricular tunnel (ALVT) is a congenital extracardiac channel connecting the ascending aorta above the sino-tubular junction to either left or right ventricular cavity.
