### ISSUE TITLE
Is it possible to add some definition to HP:0003719 (Muscle mounding)?

### ISSUE THREAD

**Issue by turnovec** [obophenotype/human-phenotype-ontology#9577]
**HPO term**
HP:0003719 | Muscle mounding 

**Suggested revision of textual definition**
Is it possible to add some definition to this term? Currently I don't see any...

There is only this comment: Transient swelling of muscle induced by percussion. 

Maybe the comment should be moved to definition. But I'm not sure if it is correct to say that it is swelling. I found this article:
https://pubmed.ncbi.nlm.nih.gov/6681565/

But there are some other sources with synonyms like idiomuscular contraction (contraction without the signal from the nerve) or myoedema...

There is some other article where it is referred as kind of edema:
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1072826/

It is important for us to understand this term to find the correct translation...

**Comment by pnrobinson** [comment]
It's not an edema. A description is found here PMID:20300641
Here is a definition:
def: Percussion-induced, local prolonged contractions (‘‘mounding’’) in muscle persisting for several seconds. 
PMID:20300641

**Comment by pnrobinson** [comment]
added
