### ISSUE TITLE
New term and Subclass/Superclass revision: Pulmonary hypertension HP:0002092

### ISSUE THREAD

**Issue by lcdaugherty** [obophenotype/human-phenotype-ontology#958]
relates to #914 BRIDGE_PAH_HPO_terms_20160616.xlsx

1) Current term Pulmonary hypertension HP:0002092
Comment:  Pulmonary arterial hypertension is not a synonym of Pulmonary hypertension but should be a separate subclass (see below)

2) New term : Pulmonary arterial hypertension
New definition: mean pulmonary artery pressure >= 25mmHg and pulmonary capillary wedge pressure <= 15mmHg when measured by right heart catheterisation at rest and in a supine position.
HPO_ID superclass (parent): Pulmonary hypertension HP:0002092

**Comment by pnrobinson** [comment]
My understanding was that "pulmonary hypertension" is often used as a synonym for "pulmonary arterial hypertension" -- the current HPO term has this intended semantics -- I will check for the current annotations to confirm this. Additionally, there exists "pulmonary venous hypertension" (I will add a new term for the latter). I do knot know if it makes sense to have a group term called "pulmonary hypertension" that would have PAH and PVH as children -- I am worried that people would mistake such a grouping term "pulmonary hypertension" for PAH.
Would you think it is OK to have one term with prefered name Pulmonary arterial hypertension and synonym Pulmonary hypertension, and another term Pulmonary vernous hypertension, with both being children of Abnormality of pulmonary circulation?

**Comment by pnrobinson** [comment]
See also this reference
http://www.resmedjournal.com/article/S0954-6111(09)00379-5/pdf

The World Health Organization (WHO)
classification divides pulmonary hypertension into five
categories depending on histopathology, clinical presenta-
tion, diagnostic findings and response to treatment.

**Comment by pnrobinson** [comment]
I am adding a term for PVH, and have changed the primary label of pulmonary hypertension to pulmonary arterial hypertension, which was always the intended meaning.
