### ISSUE TITLE
Cleft palate

### ISSUE THREAD

**Issue by sbello** [obophenotype/human-phenotype-ontology#9580]
**HPO term**
Cleft palate (HP:0000175)

**Suggested revision and reasons**
Cleft palate is currently a direct child of 'abnormal hard palate morphology' (HP:0100737) but has among its child terms 'cleft soft palate' (HP:0000185). Soft palate is a sibling of hard palate in the HPO, so it seems wrong to have cleft soft palate as a descendant of abnormal hard palate morphology.
Suggest moving cleft palate out to be a direct child of 'Abnormal palate morphology' (HP:0000174) then making 'cleft hard palate' also be a child of 'Abnormal hard palate morphology' similar to the set up for soft palate.

Thanks,
Sue

**Comment by pnrobinson** [comment]
@sbello  thanks for the suggestion! I have updated accordingly
