### ISSUE TITLE
Typos in disease names

### ISSUE THREAD

**Issue by Jane2010** [obophenotype/human-phenotype-ontology#9581]
**OMIM terms**
OMIM:254450
OMIM:618952
OMIM:115000
OMIM:193200
OMIM:142700

**Bug description**
In the December 2022 release, the names of these disease terms have typos as follows (typos in brackets):

OMIM:254450: <Myelofibrosismyelofibrosis> with myeloid metaplasia, included
OMIM:618952: Combined oxidative phosphorylation <defiency> 46
OMIM:115000: Ventricular <arrythmias> due to cardiac ryanodine receptor calcium release deficiency syndrome
OMIM:193200: <VITILIGOVTLG> | OMIM193200
OMIM:142700: Acetabular <dysplasiahip>, dislocation of, congenital, included

**Comment by pnrobinson** [comment]
Thanks for pointing out these errors. I have fixed them and the correct disease names will be shown with the next HPO release in Feb
