### ISSUE TITLE
"Abnormal four chamber view" HPO term request

### ISSUE THREAD

**Issue by sng2140** [obophenotype/human-phenotype-ontology#9582]
Abnormal four chamber view

The four-chamber view of the fetal heart is the most widely used screening examination for the detection of structural cardiac abnormalities during routine fetal ultrasonography (PMID: 7932993). In the healthy normal fetus, the apical 4Ch view demonstrates four well-developed chambers, a concordant atrioventricular (AV) connection, unobstructed AV valves (mitral and tricuspid valves), the foramen ovale flap opening into left atrium (LA), and an intact interventricular septum. Additionally, the pulmonary venous opening can be visualized at the LA wall. Any structural deviations from normal anatomy may lead to congenital heart disease that can be determined by the 4Ch view of the fetal heart’s ultrasound imaging. (https://www.mdpi.com/2227-9709/9/2/34)
Ultrasound is limited and cannot always visualize all heart details well, though you can notice something isn't correct, needing further imagining. 

Fetal anomaly--> abnormal fetal morphology-->abnormal fetal cardiovascular morphology

**Comment by pnrobinson** [comment]
added as HP_4000105
thanks!
