### ISSUE TITLE
HPO GitHub stats

### ISSUE THREAD

**Issue by matentzn** [obophenotype/human-phenotype-ontology#9586]
## [Grainyhead stats](https://github.com/gouttegd/grainyhead) from 2022-12-31 to 2022-01-01

| Event                | Total | Internal | External | Ext. (%) |
| -------------------- | ----- | -------- | -------- | -------- |
| Issues opened        |  2376 |     2083 |      293 |    12.33 |
| Issues closed        |   659 |      655 |        4 |     0.61 |
| Pull requests opened |    29 |       27 |        2 |     6.90 |
| Pull requests closed |    26 |       26 |        0 |     0.00 |
| Pull requests merged |    22 |       22 |        0 |     0.00 |
| Comments             |  1375 |     1094 |      281 |    20.44 |
| Commits              |   274 |      272 |        2 |     0.73 |
| Contributors         |    84 |        8 |       76 |    90.48 |
| Releases             |     5 |          |          |          |

Just for reference @pnrobinson - there is no action item so you can close the issue immediately. Grainyhead allows you to further break down the stats by people and other modalities, but this is a useful overview for RPPRs (659 closed issues is _amazing_, congrats!).

**Comment by pnrobinson** [comment]
Thanks, this is great! 
In many cases the internal issues are just me using a script for external requests so I do not think that we can accurately differentiate between internal and external at this time.
What would we need to do to run this for our next RPPR? Is this from an external GitHub plugin?

**Comment by matentzn** [comment]
https://github.com/gouttegd/grainyhead

Here is an example how I use it:

```
pip install --upgrade pip
python -m pip install -U --force-reinstall grainyhead
grainyhead -s mondo metrics --from=2022-01-01 --to=2022-12-31 --team monarch-ontology-team > grainyhead-2022.json
```

But you have to have a specific config file on your system to be able to access to GitHub API (see readme of project).

**Comment by pnrobinson** [comment]
transferred this information to the Wiki of this repo
