### ISSUE TITLE
5 Concepts include references to HPO IDs in their Textual Definitions

### ISSUE THREAD

**Issue by ericsid** [obophenotype/human-phenotype-ontology#9588]
HPO textual descriptions that reference another HPO term do not typically include a reference HPO ID. 

For example, please compare textual descriptions for these two terms:
1. HP:0007201 - Atherosclerosis (HP:0002621) of a cerebral artery. 
2. HP:0031684 - An atherosclerotic lesion located in the renal artery.

Five terms were discovered to include references to HPO IDs (see below). Would suggest deleting the referenced HPO IDs to improve consistency.

**HPO terms**
HP:0000274 | Small face | A face that is short (HP:0011219) and narrow (HP:0000275).
HP:0001776 | Bilateral talipes equinovarus | Bilateral clubfoot deformity (see HP:0001762).
HP:0000368 | Low-set, posteriorly rotated ears | Ears that are low-set (HP:0000369) and posteriorly rotated (HP:0000358).
HP:0008247 | Euthyroid hyperthyroxinemia | An abnormality of thyroid physiology (HP:0002926) characterized by increased levels of thyroxine without evidence of clinical thyroid disease.
HP:0007201 | Cerebral artery atherosclerosis | Atherosclerosis (HP:0002621) of a cerebral artery.

**Suggested revision of textual definitions**
HP:0000274 | Small face | A face that is short and narrow.
HP:0001776 | Bilateral talipes equinovarus | Bilateral clubfoot deformity.
HP:0000368 | Low-set, posteriorly rotated ears | Ears that are low-set and posteriorly rotated .
HP:0008247 | Euthyroid hyperthyroxinemia | An abnormality of thyroid physiology characterized by increased levels of thyroxine without evidence of clinical thyroid disease.
HP:0007201 | Cerebral artery atherosclerosis | Atherosclerosis of a cerebral artery.

**Comment by ericsid** [comment]
Great points, here's a few thoughts:
1. As someone whose use case for HPO is targeted at non-clinical users, I would definitely agree! With that in mind, it is especially helpful if there is a _consistent_ style applied to the textual definitions. 

2. From a brief scan of the latest obo file, I was only able to find 9 HPO terms whose textual definitions is referencing another HPO ID (so a few more HPO terms in addition to those I had previously noted). 

3. Now I was _expecting_ these connections to other HPO terms and specifically, use of their respective HPO IDs, to be represented as semantic relationships or described within the comment field. If my expectation are outright wrong, any clarity would be most appreciated. :) 

For the two discussed examples, it may help to look at all of their data (per the latest HPO obo file): 
**For HP:0001776 | bilateral talipes equinovarus, a connection to HP:0001762 is already defined semantically as an "is_a" relationship:**
- id: HP:0001776
- name: Bilateral talipes equinovarus
- def: "Bilateral clubfoot deformity (see HP:0001762)." [HPO:probinson]
- synonym: "Bilateral clubfeet" EXACT []
- synonym: "Bilateral clubfoot" EXACT []
- synonym: "Club foot on both sides" EXACT layperson []
- xref: UMLS:C1837835
- **is_a: HP:0001762 ! Talipes equinovarus**

**For HP:0000274 | small face, short face and narrow face are also discussed in the comment field with more of the nuance you are describing, but without the HPO IDs:**
- id: HP:0000274
- name: Small face
- def: "A face that is short (HP:0011219) and narrow (HP:0000275)." [HP:probinson]
- **comment: This term represents a combination of two terms, short face and narrow face.**
- synonym: "Facial hypoplasia" EXACT [ORCID:0000-0001-5889-4463]
- synonym: "Hypoplasia of face" EXACT [ORCID:0000-0001-5889-4463]
- synonym: "Microface" EXACT [ORCID:0000-0001-5889-4463]
- synonym: "Microfacies" EXACT [ORCID:0000-0001-5889-4463]
- synonym: "Short and narrow face" EXACT layperson [ORCID:0000-0001-5889-4463]
- synonym: "Small face" EXACT layperson []
- synonym: "Small facies" EXACT layperson [ORCID:0000-0001-5889-4463]
- xref: UMLS:C1855538
- is_a: HP:0001999 ! Abnormal facial shape

-Eric

**Comment by pnrobinson** [comment]
Thanks, @ericsid , for pointing this out. The HPO now has a 15 year legacy and some of the definitions do require revision. I have revised to the following

- [ ] Cerebral artery atherosclerosis : The formation of  the formation of fibrofatty lesions in the wall of an artery located in the brain.

**Comment by pnrobinson** [comment]
@kanems  -- these five terms are not special in the sense that they are the only terms whose definitions could in principle use cross refs to other HPOs. Especially for the is_a relations there is no additional computational utility.

**Comment by pnrobinson** [comment]
fixed
