### ISSUE TITLE
Subclass/Superclass revision: Abnormal DLCO HP:0045049 add superclass Respiratory insufficiency HP:0002093

### ISSUE THREAD

**Issue by lcdaugherty** [obophenotype/human-phenotype-ontology#959]
Relates to #914 BRIDGE_PAH_HPO_terms_20160616.xlsx

term: Abnormal DLCO HP:0045049 
HPO_ID superclass (parents): Abnormality of the lung  HP:0002088
and **add new superclass** Respiratory insufficiency HP:0002093

**Comment by pnrobinson** [comment]
I have put this under functional respiratory abnormality. I am not sure that respiratory insufficiency is the correct parent, and plan to revise the structure of the lung section to get more organisation.

**Comment by pnrobinson** [comment]
Please note I have added a new term "Abnormality on pulmonary function testing" and have placed some terms including Abnormal DLCO underneath this. Please reopen this request if you think this term placement still needs revision.
