### ISSUE TITLE
HP:0001218 Autoamputation

### ISSUE THREAD

**Issue by grahamponting** [obophenotype/human-phenotype-ontology#9592]
Definition - Spontaneous detachment (amputation) of an appendage from the body.
I would suggest that autoamputation does not occur as a spontaneous event, there is always an underlying cause. Could the definition be updated to reflect this, if you agree ?
Many thanks - Graham Ponting

**Comment by pnrobinson** [comment]
I agree there is likely to be a trauma that would otherwise not lead to amputation. However, one reads "spontaneous" in many source documents, e.g. https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6789066/
Do you have  a suggestion or PubMed reference with a better definition?
thanks, Peter

**Comment by grahamponting** [comment]
Hi Peter,

I think just providing a bit more context in the HPO definition would be really helpful.

**Comment by grahamponting** [comment]
Hi Peter,

Sorry I didn't finish the previous email, autoamputation is most commonly an end result of gangrene which results in a spontaneous amputation. I think your reference explains this very well, there are a number of other case reports  including internal other organs such as appendix, ovary and fallopian tube, breast etc.
An expanded definition on HP:0001218 and it's subtypes, would be really helpful.

Graham

**Comment by pnrobinson** [comment]
@grahamponting 

I have updated the definition to 
Auto-amputation is the spontaneous detachment of an appendage from the body due to long standing pathology.
and also added the PMID citation.
I am updating the definitions of the subterms accordingly. This will be available with the next HPO release in August.
Thanks for the suggestion.
