### ISSUE TITLE
Cervical cancer OMIM:603956 is annotated with HP:0003319  Abnormality of the cervical spine

### ISSUE THREAD

**Issue by MSBradshaw** [obophenotype/human-phenotype-ontology#9597]
https://hpo.jax.org/app/browse/disease/OMIM:603956

For the HPO terms associated with "Cervical cancer" OMIM:603956 there is HP:0003319  "Abnormality of the cervical spine". But the description of "Cervical cancer" OMIM:603956 on [OMIM's website](https://www.omim.org/entry/603956) seems to be referring cervical cancer in the uterus, not the spine. Perhaps the annotation should be updated to include "Abnormality of the uterus" HP:0000130?

**Comment by pnrobinson** [comment]
Thanks for pointing out this error -- it was a bug in the text mining used about 10 years ago. I have fixed the annotations, the fix should be visible in the download files & website in early february
