### ISSUE TITLE
Typo in definition for Aorto-ventricular tunnel (HP:0011627)

### ISSUE THREAD

**Issue by turnovec** [obophenotype/human-phenotype-ontology#9598]
**HPO term**
HP:0011627 | Aorto-ventricular tunnel 

**Bug description**
"Aorto-ventricular tunnel is a congenital, extracardiac channel which connects the ascending aorta above the sinutubular junction to the cavity of the left, or (less commonly) right ventricle."

sinutubular → sinotubular

**Comment by pnrobinson** [comment]
fixed, thanks!
