### ISSUE TITLE
Two longitudinal nail ridge findings that seem the same

### ISSUE THREAD

**Issue by MickeySegal** [obophenotype/human-phenotype-ontology#9611]
**HPO term**
HP:0008402
HP:0001807
**Reason for deprecation**
These seem like the same thing.

**Suggested replacement or term to consider**
Consolidate on one of the existing terms.

**Comment by pnrobinson** [comment]
We have [Ridged fingernail HP:0008402](https://hpo.jax.org/app/browse/term/HP:0008402)
and
[Ridged nail HP:0001807](https://hpo.jax.org/app/browse/term/HP:0001807)
I think this are probably close enough to merge, I will check that there is not a specific "fingernail" ridging.

**Comment by pnrobinson** [comment]
Well, we have a lot of findings that are specific to foot or hand, so let's keep this for now. A link from the Ridged fingernail to Ridged nail was missing, I added it.
