### ISSUE TITLE
Definition/synonym/name revision :  Restrictive respiratory insufficiency HP:0002111

### ISSUE THREAD

**Issue by lcdaugherty** [obophenotype/human-phenotype-ontology#962]
relates to #914 BRIDGE_PAH_HPO_terms_20160616.xlsx 

term : Restrictive respiratory insufficiency HP:0002111
add definition: FEV1 and FVC <80% predicted and with FEV1/FVC >0.7 (FEV1 - forced expiratory volume in 1 second; FVC forced vital capacity).
Comment on term: We would prefer 'Restrictive respiratory insufficiency to be the synonym and 'Restrictive deficit on pulmonary function tests' to be the primary term name.
Suggested synonyms:  Restrictive deficit on pulmonary function tests

**Comment by pnrobinson** [comment]
Thanks. I changed the name to Restrictive deficit on pulmonary function testing, which seemed slightly more correct. Please reopen this issue if you disagree!
