### ISSUE TITLE
Narrow angle glaucoma HP:0032119

### ISSUE THREAD

**Issue by kanems** [obophenotype/human-phenotype-ontology#9625]
**HPO term**
HP:0032119 _Narrow angle glaucoma_

**Suggested revision of textual definition**
No definition is provided, can a definition be added?

Additional question: Is this notably different than "_Angle closure glaucoma_ HP:0012109" ?
UMLS combines these two HPO IDs on one CUI; MeSH, SNOMED CT and NCI thesaurus all use "Angle closure glaucoma" and "Narrow-angle glaucoma" (or "Closed Angle Glaucoma
" and "Narrow Angle Glaucoma") as synonyms.

**Comment by pnrobinson** [comment]
@kanems thanks for pointing out this error, these terms were synonyms, and I have merged them.
We have retained
[Angle closure glaucoma HP:0012109](https://hpo.jax.org/app/browse/term/HP:0012109)
