### ISSUE TITLE
Pairs of HPO IDs that seem highly similar

### ISSUE THREAD

**Issue by kanems** [obophenotype/human-phenotype-ontology#9626]
**HPO terms**
See list below. I am coordinating with UMLS to see if we can get HPO IDs mapped more uniquely in UMLS (right now there are ~30 UMLS CUIs with >1 HPO ID 'PT' atom, which seems incorrect) The list below is the UMLS CUI mapping and the two HPO IDs that seem like (as the HPO IDs are described in HPO) they may be the same phenotype? 

CUI Mapping in UMLS 	HPO ID	STR
C0006288	HP:0100632	Pulmonary sequestration
C0006288	HP:0010960	Bronchopulmonary sequestration
(Does bronchopulmonary not include the pulmonary aspect? Does HPO need both? looks like they have very similar children, too)

C0013595	HP:0000964	Eczema
C0013595	HP:0000976	Eczematoid dermatitis
(Can the distinction between these concepts be clarified?)

C0029883	HP:0031353	Otitis media with effusion
C0029883	HP:0040262	Glue ear
(There are a lot of records in UMLS that all seem very similar to these two phenotypes. If glue ear is a phenotype that presents in the absence of inflammation, it may be helpful to specify that in HPO, otherwise might these be the same? Or somehow related to mucoid otitis media?)

C0031941	HP:0010799	Pinealoma
C0031941	HP:0030694	Pineal parenchymal cell neoplasm
(NCI Thesaurus uses these as synonyms; but are they the same? I do not know and would appreciate some clarification)

C0033375	HP:0006767	Pituitary prolactin cell adenoma
C0033375	HP:0040278	Prolactinoma
(Are these distinct somehow?)

C0080024	HP:0007443	Partial albinism
C0080024	HP:0007544	Piebaldism
(Based on definitions in HPO these seem the same to me)

C0151636	HP:0034041	Ventricular ectopy
C0151636	HP:0006682	Premature ventricular contraction
(Cleaning up synonyms on these HPO records may help with clarifying the distinction; as written currently "Ventricular ectopics" is synonymous with "premature ventricular contraction." Or are they similar enough to merge ventricular ectopy with the parent concept?) 

C0154916	HP:0011497	Iris neovascularization
C0154916	HP:0025319	Rubeosis iridis
(Is rubeosis iridis actually a specific form of iris neovascularization? These are siblings, but maybe the distinction would be clearer in a parent/child relationship structure?)

C0265985	HP:0100814	Blue nevus
C0265985	HP:0011369	Mongolian blue spot
(Mongolian spot is syn for blue nevus, are these actually different?)

C0266483	HP:0001302	Pachygyria
C0266483	HP:0007227	Macrogyria
(Again, not sure from the reading of the definitions that I understand the distinction between these two)

C0339808	HP:0410325	House dust mite allergy
C0339808	HP:0410324	Dust mite allergy
(If there are no other types of dust mites in HPO, do we need to specify 'house' allergy vs the general dust mite allergy?)

C0728895	HP:0009380	Aplasia of the fingers
C0728895	HP:0001180	Hand oligodactyly
(??)

C1846460	HP:0008572	External ear malformation
C1846460	HP:0000356	Abnormality of the outer ear
(??)

C5558307	HP:0033919	Medial/intimal arcuate venulitis
C5558307	HP:0033917	Arcuate intimal/medial venulitis
(Differ only in word order, are they really different concepts?)

**Suggested revision and reasons**
Sorry, I have no answers, only questions :-) There are other cases where UMLS has lumped HPO IDs that are clearly distinct, so I will pass those along to them along with the link to this ticket so they can follow up with any specific changes HPO adopts.

**Comment by pnrobinson** [comment]
@mgiese 
Bronchopulmonary sequestration/Pulmonary sequestration -- It does look like these two terms are synonymous, could you please confirm or comment? Thanks

**Comment by pnrobinson** [comment]
To keep track of things (I will make one comment for each as I go along):
- [ ] HP:0100632 Pulmonary sequestration vs HP:0010960 Bronchopulmonary sequestration
- [ ] HP:0410325 House dust mite allergy vs . HP:0410324 Dust mite allergy
- [ ] HP:0000964 Eczema vs HP:0000976 Eczematoid dermatitis
- [ ] HP:0031353 Otitis media with effusion vs HP:0040262 Glue ear
- [ ]  HP:0010799 Pinealoma vs HP:0030694 Pineal parenchymal cell neoplasm
- [ ]  HP:0006767 Pituitary prolactin cell adenoma vs HP:0040278 Prolactinoma
- [ ] HP:0007443 Partial albinism vs HP:0007544 Piebaldism
- [ ]  HP:0034041 Ventricular ectopy vs. HP:0006682 Premature ventricular contraction
- [ ]  HP:0011497 Iris neovascularization vs. HP:0025319 Rubeosis iridis
- [ ] HP:0100814 Blue nevus vs. HP:0011369 Mongolian blue spot
- [ ] HP:0001302 Pachygyria vs. HP:0007227 Macrogyria
- [ ]  HP:0009380 Aplasia of the fingers -vsHP:0001180 Hand oligodactyly
- [ ] HP:0008572 External ear malformation vs  HP:0000356 Abnormality of the outer ear
- [ ]  HP:0033919 Medial/intimal arcuate venulitis vs.  HP:0033917 Arcuate intimal/medial venulitis

**Comment by pnrobinson** [comment]
@kanems  
HP:0410325 House dust mite allergy and HP:0410324 Dust mite allergy are synoynms, I have merged them and retained   HP:0410324 Dust mite allergy

**Comment by kanems** [comment]
@pnrobinson Hi, just a reminder that there are still multiple pairs here that may be redundant. I think Mickey Segal may have reported some of these as well? I appreciate you taking a look. I'll be happy to take any of these that you are confident should maintained as separate concepts I will report back to UMLS so they can represent these as distinct targets.

**Comment by kanems** [comment]
@pnrobinson Would it be easier for your workflow if I split these pairs into multiple individual tickets for review? I know there are a lot of request for new terms and this has probably fallen off your radar, but we are pending a determination from HPO before we can follow up with UMLS to request that they report unique HPO IDs on separate CUIs.

**Comment by kanems** [comment]
@pnrobinson I think the HP:0031353 Otitis media with effusion vs HP:0040262 Glue ear confusion would be resolved/clarified if HPO added some additional info to the definition.
From the link in the comment, a specific clarification is made vs. middle ear infection (otitis media with effusion):
"Glue ear is characterised by a collection of fluid in the middle ear space (behind the ear drum), _without any signs or symptoms of inflammation_. The fluid may be present in the middle ear for several weeks, especially in children. Whereas a middle ear infection occurs when a cold and the presence of germs such as bacteria or viruses led to the formation of pus and mucus behind the ear drum causing ear pain and fever, typically for just a few days."

**Comment by kanems** [comment]
I think that HP:0010799 Pinealoma vs HP:0030694 Pineal parenchymal cell neoplasm can be clarified if other forms of 'pinealoma' are added to HPO tree. NCI has several sub-types of neoplasms (benign or malignant)  under this concept http://purl.obolibrary.org/obo/NCIT_C3328  I don't really know when an NCI concept should be used for a Mondo concept vs. an HPO concept, though, so I trust your call on whether these NCI children terms are appropriate in HPO.
(In fact, NCI thesaurus provides a NICHD sourced definition that indicates that germ cell tumors might actually be a more common subtype? "NICHD Definition:  A tumor arising in the pineal region, the majority of which are malignant germ cell tumors. A minority of pinealomas are benign, and comprise neoplastic cells that resemble normal pineocytes."  https://ncithesaurus.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI_Thesaurus&ns=ncit&code=C3328

**Comment by kanems** [comment]
HP:0034041 Ventricular ectopy vs. HP:0006682 Premature ventricular contraction, HPO hierarchy is pretty clear that the first term is a subtype and there are other subtypes. I will ask UMLS to review their CUI mapping for this pair.

**Comment by kanems** [comment]
I made new tickets for the records I still think should be merged, with a little more evidence to support the request. Hopefully this makes review a little simpler. Two comments above deal with clarifying definitions/terms so we can ask UMLS to split their mappings, once those are reviewed/addressed I think this older ticket could be closed.

**Comment by pnrobinson** [comment]
@kanems 
sorry for the delay -- this last year was very full because I have relocated back to Germany. I will be working on these over the next few weeks, very much appreciated!

**Comment by pnrobinson** [comment]
@kanems  
I merged HP:0034041 Ventricular ectopy into HP:0006682 Premature ventricular contraction
that is, HP:0034041 Ventricular ectopy was obsoleted and  the label added as a synonym to  HP:0006682 Premature ventricular contraction

**Comment by pnrobinson** [comment]
@kanems 
I do not think that pinealoma and Pineal parenchymal cell neoplasm are synonyms. This branch of the HPO probably needs to be revised/expanded.


I added this comment to the Pinealoma term (from https://pubmed.ncbi.nlm.nih.gov/20966647/)

Pineal tumors are a rare and heterogeneous group of primary central nervous system neoplasms, including pineal parenchymal tumors (pineocytomas, pineal parenchymal tumors of intermediate differentiation, and pineoblastomas), germ cell tumors, and neuroepithelial tumors, such as astrocytomas, ependymomas, and papillary tumor of the pineal region.

**Comment by pnrobinson** [comment]
@kanems 
I do not think that Glue ear and otitis media with effusion are always synonyms; in some articlces they are treated as synonyms, but I think it is useful to make the following distinction. (I added this as a comment to the Glue ear term)

In some contexts, glue ear is used interchangably with otitis media with effusion (OME) (PMID:21653931). Some authors use glue ear to refer to a subtype of OME characterized by thick, glue-like fluid buildup in the middle ear (mucoid otitis media) (PMID:10993548). Serous otitis media is usually responsive to medical treatment, whereas mucoid otitis media is not. This term refers to the mucoid subtype.
