### ISSUE TITLE
Retiring the NBO Phenotype branch

### ISSUE THREAD

**Issue by DitchingIt** [obophenotype/human-phenotype-ontology#9628]
The NBO is planning to retire its Phenotype branch (no date set yet). We are aware that HP has been using 19 terms from this branch. We would encourage you to review these. I recommend tagging @matentzn in follow-up comments, not least if you need a technical discussion. NB: [MP is in a similar position](https://github.com/mgijax/mammalian-phenotype-ontology/issues/3717) regarding the two starred * classes and you may want to consider a common solution.

- [ ] NBO_0000030 hyperactivity
- [ ] NBO_0000032 paralysis *
- [ ] NBO_0000096 agoraphobia behavior
- [ ] NBO_0000248 obsessive-compulsive disorder
- [ ] NBO_0000258 bipolar disorder
- [ ] NBO_0000259 psychotic disorder
- [ ] NBO_0000265 personality disorder
- [ ] NBO_0000268 dementia
- [ ] NBO_0000515 depressive disorder
- [ ] NBO_0000542 polydipsia
- [ ] NBO_0000567 stereotypic behavior *
- [ ] NBO_0000586 opisthotonus
- [ ] NBO_0000589 tremor
- [ ] NBO_0000598 dystonia
- [ ] NBO_0000602 apathy
- [ ] NBO_0000603 delusion
- [ ] NBO_0000606 forgetfulness
- [ ] NBO_0000621 selective mutism
- [ ] NBO_0000623 echolalia

**Comment by matentzn** [comment]
For some more context: All of these terms are phenotypes in their own respect - they don't belong in an ontology of behavioural processes.

@rays22 please coordinate this with @sbello and @LCCarmody during your reconciliation session. The default should always be to simply drop the EQ, but if you can find better patterns that would be great.

**Comment by pnrobinson** [comment]
@matentzn @rays22  -- can we implement?

**Comment by pnrobinson** [comment]
Hi everybody, this seems the wrong tracker for this term. The HPO has much more detailed terms for behavioral abnormalities.

**Comment by rays22** [comment]
1. 'NBO:0000030 hyperactivity' is a component of the EQ for
    * HP:0000752 Hyperactivity
    'has part' some 
    ('increased amount' and ('characteristic of' some **hyperactivity**) and ('has modifier' some abnormal))
    * HP could use a similar logical definition to the 'MP:0001399 hyperactivity' EQ:
        'has part' some 
            ('increased rate'
             and ('characteristic of' some 'kinesthetic behavior')
             and ('has modifier' some abnormal))
2. 'NBO:0000606 forgetfulness' is a component of the EQ for
    * HP:0002354 Memory impairment
    'has part' some 
    ('increased rate' and ('characteristic of' some **forgetfulness**) and ('has modifier' some abnormal))
    * The HP could use 'NBO:0000304 memory loss behavior' as a component when defining the 'HP:0002354 Memory impairment' EQ.

and so on ...

**Comment by matentzn** [comment]
I documented the remaining EQs here:

https://docs.google.com/spreadsheets/d/1A_KOu8DI4oDBZY67UlbDE0CmhhgJvcgW2RWj76nMqV8/edit?gid=993477073#gid=993477073
