### ISSUE TITLE
Guttae or guttata?

### ISSUE THREAD

**Issue by MickeySegal** [obophenotype/human-phenotype-ontology#9633]
**HPO term**
HP:0012038

**Synonym to be added**
There is a good discussion at http://www.healio.com/news/optometry/20200408/blog-guttae-or-guttata-some-thoughts-on-fuchs of when to use guttae versus guttata.  It makes sense to include the former as well.

**broad/exact/narrow/plural/abbreviation ?**

**Comment by pnrobinson** [comment]
added Corneal guttae as a synonym, thanks!
