### ISSUE TITLE
Association between gene PAH (HGNC:8582) and HP:0000007 (MoI AR) not in genes_to_phenotype.txt anymore

### ISSUE THREAD

**Issue by roland-ewald** [obophenotype/human-phenotype-ontology#9634]
**HP:0000007**

In the HPO browser the gene [`PAH`](https://hpo.jax.org/app/browse/gene/5053) is (correctly) associated with the mode of inheritance [`HP:0000007` (Autosomal recessive inheritance)](https://hpo.jax.org/app/browse/term/HP:0000007):

![image](https://user-images.githubusercontent.com/392143/221225439-5c58ab8f-0057-4233-a2b1-475a6e6e4cbe.png)

**Bug description**

The relation between this gene and this HPO term is not stored in the current [`genes_to_phenotype.txt`](http://purl.obolibrary.org/obo/hp/hpoa/genes_to_phenotype.txt) or [`phenotype_to_genes.txt`](http://purl.obolibrary.org/obo/hp/hpoa/phenotype_to_genes.txt) files anymore. 

:arrow_right: This association is still present in [`v2022-04-14/genes_to_phenotype.txt`](https://github.com/obophenotype/human-phenotype-ontology/releases/download/v2022-04-14/genes_to_phenotype.txt), but not in [`v2022-06-11/genes_to_phenotype.txt`](https://github.com/obophenotype/human-phenotype-ontology/releases/download/v2022-06-11/genes_to_phenotype.txt).

**Comment by pnrobinson** [comment]
Hi @roland-ewald We are currently working on a fix for these issues @iimpulse, hopefully this should be online with the next release

**Comment by roland-ewald** [comment]
Thats' great! Thanks for letting me know.

**Comment by roland-ewald** [comment]
Great; thank you!
