### ISSUE TITLE
Are there tabular files for HPO to gene mapping and vice versa?

### ISSUE THREAD

**Issue by Yiran-Guo** [obophenotype/human-phenotype-ontology#9652]
Hi HPO team, I remember there were such files a few years ago. File names are ALL_SOURCES_ALL_FREQUENCIES_phenotype_to_genes.txt and ALL_SOURCES_ALL_FREQUENCIES_genes_to_phenotype.txt (see attached screenshots). Are there updated files currently? Thanks
<img width="423" alt="image" src="https://user-images.githubusercontent.com/5854272/223751299-28b0ccfc-f1ac-4c02-825e-c25e0b5bfbbd.png">

**Comment by pnrobinson** [comment]
@ielis It would be a good idea to add this to hpo-toolkit (function to create the above files from the latest HPO release). 
@Yiran-Guo we have stopped exporting all of these files because the contents are redundant and it is possible to generate them from the phenotype.hpoa file. We will create a python script that will allow users to do this easily.

**Comment by Yiran-Guo** [comment]
> @ielis It would be a good idea to add this to hpo-toolkit (function to create the above files from the latest HPO release). @Yiran-Guo we have stopped exporting all of these files because the contents are redundant and it is possible to generate them from the phenotype.hpoa file. We will create a python script that will allow users to do this easily.

Thank you so much @pnrobinson for the quick response - how soon do you think we can have the most updated tabular files then?

**Comment by ielis** [comment]
In the short term, I am sure we can produce the tables with a bit of hacking with `phenol` (our Java ontology library). However, I am not sure I see a simple way for producing the tables just based on the HPO annotation file.
In the long term, I can add support for the gene -> disease -> phenotype mappings into `hpo-toolkit` (our new python ontology library). However, realistically, I can implement it in a few months earliest.

@Yiran-Guo would it be helpful if I generated the mapping tables for you for the current HPO release, or you'd prefer waiting for the actual code?

**Comment by Yiran-Guo** [comment]
@ielis @pnrobinson Is there any update on generating the mapping tables for the current HPO release?

**Comment by ielis** [comment]
Hi, please find the tables attached to this message. 

The tables were prepared using the following files:
- HPO - 2023-01-27
- HPO annotations - 2023-01-27
- mim2medgen - accessed on March 17th, 2023
- hgnc complete set - 2023-03-16, accessed on March 17th, 2023

[genes_to_phenotype.csv.gz](https://github.com/obophenotype/human-phenotype-ontology/files/11003117/genes_to_phenotype.csv.gz)
[phenotype_to_genes.csv.gz](https://github.com/obophenotype/human-phenotype-ontology/files/11003118/phenotype_to_genes.csv.gz)

**Comment by emblake85** [comment]
> In the short term, I am sure we can produce the tables with a bit of hacking with `phenol` (our Java ontology library). However, I am not sure I see a simple way for producing the tables just based on the HPO annotation file. In the long term, I can add support for the gene -> disease -> phenotype mappings into `hpo-toolkit` (our new python ontology library). However, realistically, I can implement it in a few months earliest.

@ielis, I'm curious about the added functionality to the hpo-toolkit; is this still in development?

**Comment by Yiran-Guo** [comment]
@ielis @pnrobinson Good to see there is an update to the HPO recently (v2023-10-09; https://hpo.jax.org/app/data/ontology). I wonder if there is any accompanying updated files like `genes_to_phenotypes` and `phenotypes_to_genes`? Or is there a tutorial for users to generate these files using the current HPO release? Many thanks!

**Comment by pnrobinson** [comment]
@Yiran-Guo did you look at these files?
https://hpo.jax.org/app/data/annotations

**Comment by pnrobinson** [comment]
thanks, closing
