### ISSUE TITLE
Remove inappropriate synonyms of Global developmental delay

### ISSUE THREAD

**Issue by bcoleman96** [obophenotype/human-phenotype-ontology#9653]
**HPO term**
Global developmental delay (HP:0001263)

**Suggested revision of textual definition**
Global developmental delay has many synonyms which may have been helpful when the HPO lacked terms that described specific developmental delays, but now that more specific terms have been created, these synonyms need to be pruned to avoid confusion. My general sense is that most synonyms should be removed as there are now (or soon will be) specific terms to describe these different aspects of GDD that should be clearly separate from GDD given their specificity. I've created a table below to show all synonyms of GDD (notice that some are duplicated) and I've shown some terms which better match the synonyms within GDD. Maybe as an alternative, we could list these synonyms as being potential "symptoms" of GDD since it is more of a gestalt phenotype than a specific feature.

| **Synonym**                                 | **Better Match to Existing Term** |
|----------------------------------------------|-----------------------------------------|
|Delayed cognitive development| Delayed cognitive development|
|Delayed development|Developmental delay |
|Delayed developmental milestones|Developmental delay |
|Delayed intellectual development| Delayed cognitive development|
|Delayed milestones|Developmental delay |
|Delayed psychomotor development| |
|Developmental delay|Developmental delay |
|Developmental delay in early childhood| |
|Developmental delay| Developmental delay|
|global| |
|Developmental retardation| Developmental delay|
|Lack of psychomotor development| Delayed motor development|
|Motor and developmental delay| Delayed motor development|
|Motormental retardation| |
|Psychomotor delay| |
|Psychomotor development deficiency| |
|Psychomotor development failure| |
|Psychomotor developmental delay| |
|Retarded development|Developmental delay |
|Retarded mental development| Delayed cognitive development|
|Retarded psychomotor development| |
|Cognitive delay| Delayed cognitive development|
|Mental and motor retardation| |

**Comment by pnrobinson** [comment]
The purpose of the synonyms is (among other things) to enable text mining to pick up mentions of the concept even if old or non-preferred synonyms are used. I do not think it would be a good idea to remove the synonyms here. We will be revisiting the entire section.
