### ISSUE TITLE
Re HP:0005916 Abnormal metacarpal morphology

### ISSUE THREAD

**Issue by grahamponting** [obophenotype/human-phenotype-ontology#9654]
HP:0005916 Abnormal metacarpal morphology
Whilst the textual definition states "Irregularly shaped metacarpal bones of varying degree", as well as the synonyms, the subtypes are a range of conditions/morphologies much wider than suggested, including osteolysis, sclerosis, duplication as well as fracture. Should the definition be updated ?

Graham Ponting

**Comment by pnrobinson** [comment]
Thanks, Graham, you are right. I changed the definition to "Any abnormal shape or structure of the metacarpal bones."
