### ISSUE TITLE
illegal usage of 'BFO quality'

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9655]
@matentzn  -- I added about 20 terms and when I did the Q/C I got this. As far as I can see HP_0011396 is correct though. Could you take a look?

Test: PerformHpoOwlQC
found illegal usage of 'BFO quality' in line: EquivalentClasses(<http://purl.obolibrary.org/obo/HP_0011396> ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/BFO_0000051> ObjectIntersectionOf(<http://purl.obolibrary.org/obo/BFO_0000019> ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/RO_0002314> <http://purl.obolibrary.org/obo/UBERON_0004727>) ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/RO_0002573> <http://purl.obolibrary.org/obo/PATO_0000460>))))

**Comment by matentzn** [comment]
> http://purl.obolibrary.org/obo/BFO_0000019

(in your EQ) should be: http://purl.obolibrary.org/obo/PATO_0000001

that's all!

**Comment by pnrobinson** [comment]
thanks, fixed!
