### ISSUE TITLE
Add and Edit Terms from Workshop

### ISSUE THREAD

**Issue by bcoleman96** [obophenotype/human-phenotype-ontology#9659]
@matentzn 
Use CSV to add new terms from the behavioral HPO workshop held at the NIMH on Feb 2-3, 2023. CSV includes data for Term Labels, IDs, Synonyms, Parent Terms, Definitions, ORCID Attributions, References, and Comments. HPO terms should reflect what is in the spreadsheet for these fields, i.e. existing entries should be replaced and if a field is blank in the spreadsheet it should be left blank on the HPO. Fields not included in the spreadsheet (there is no column for them) should be retained from existing terms or left blank for new terms.

**Notes**
- The columns "Group_Attribution" and "Parent_ref" are for reference only and should not be used to edit the HPO.
- Fields with multiple entries have entries separated by a "|" with no spaces. 
- Pubmed IDs are listed as "PMID:########" with no space.
- Terms with HPO IDs above 5200000 are new terms whereas all others are existing terms
- Parent_ref uses terms labels to reflect labels after this update

**Comment by bcoleman96** [comment]
File from Slack channel
https://monarchinitiative.slack.com/files/U03TK3SNHPT/F04TNEW72BY/behavioralhpoterms.csv

**Comment by matentzn** [comment]
Hey @bcoleman96 can you share  a link to a google sheet? I have a lot on my plate this week but I will try to get it done towards Thursday.

**Comment by matentzn** [comment]
Thank you @bcoleman96 - Can you click on publish - on the web and "TSV" and then share the link to the TSV file (of the final sheet only)? I will work on a copy now but would prefer to keep working on the orgininal here.

**Comment by matentzn** [comment]
This is now done.
