### ISSUE TITLE
Typo in definition of HP:0034074 - Increased fetal long bone echogenicity 

### ISSUE THREAD

**Issue by turnovec** [obophenotype/human-phenotype-ontology#9666]
**HPO term**
HP:0034074 | Increased fetal long bone echogenicity 

**Bug description**
Definition: "An abnormally elevated echogenicity of fetal long bones in a prenatal sonographic investigation. Ths finding is due to hypermineralization."
Ths → This

**Comment by pnrobinson** [comment]
fixed, thanks!
