### ISSUE TITLE
"anticentromere antibody positivity"

### ISSUE THREAD

**Issue by slaulederkind** [obophenotype/human-phenotype-ontology#967]
I would like to see "anticentromere antibody positivity" added to the HP ontology under the parent term "Autoimmune antibody positivity" (HP:0030057).  The definition could be "The presence of autoantibodies (immunoglobulins) in the serum that react against the centromeres or centromere components."  An example can be found in PMID: 17444587. Synonyms would be "ACA positivity" and "anti-centromere antibody positivity".

**Comment by pnrobinson** [comment]
Thanks for the suggestion. BTW if you would like to be recorded as responsible for this term, please let me know how ("Microattribution"). For instance, I go as HPO:probinson, and some people go by ORCID:000...(Orcid ID)
