### ISSUE TITLE
Nephroblastoma named after Dr. Max Wilms

### ISSUE THREAD

**Issue by MickeySegal** [obophenotype/human-phenotype-ontology#9674]
**HPO term**
HP:0002667

**Suggested revision of textual definition**
**Wilm's** tumor is not correct because it is named after Dr. Max Wilms.  It may make sense to keep the erroneous form because some will use it, but perhaps it should be demoted in some way to indicate what is correct.

**Comment by pnrobinson** [comment]
Thanks for pointing out this error, fixed!
