### ISSUE TITLE
Definition which is unclear for HP:0032879 | Focal impaired awareness seizure with dissociation at onset

### ISSUE THREAD

**Issue by turnovec** [obophenotype/human-phenotype-ontology#9677]
**HPO term**
HP:0032879 | Focal impaired awareness seizure with dissociation at onset

**Bug description**
We agreed with colleagues that this definition doesn't make much sense:
"A focal cognitive seizure with dissociation at the onset of the seizure impairment of awareness at at some point during the seizure."

**Comment by pnrobinson** [comment]
@DLewisSmith if you get a chance could you take a look at this definition?

**Comment by DLewisSmith** [comment]
Yes, it appears to be missing the word 'with' and for avoidance of confusion with non-epileptic seizures that can be described as 'dissociative seizures' I would suggest the following update:
"A focal cognitive _epileptic_ seizure with dissociation at the onset of the seizure and _with_ impairment of awareness at at some point during the seizure."

**Comment by pnrobinson** [comment]
Updated the definitions, thanks to @DLewisSmith and @turnovec
