### ISSUE TITLE
Inconsistencies in writing of Schwannoma / Schwan cells

### ISSUE THREAD

**Issue by turnovec** [obophenotype/human-phenotype-ontology#9678]
There are inconsistencies in writing of Schwannoma (in some occurances it's with small "s") and Schwan cells (again, in some cases with s not capitalized):

HP:0100008 Schwannoma
HP:0009588 Vestibular schwannoma
HP:0009590 Unilateral vestibular schwannoma
HP:0100011 Scleral schwannoma
HP:0009593 Peripheral Schwannoma
HP:0025604 Orbital schwannoma
HP:0100697 Neurofibrosarcoma (Malignant schwannoma)
HP:0009589 Bilateral vestibular schwannoma
HP:0033035 Abnormal Schwann cell morphology

This is a list of all terms I found containing "schwann". I think that the S should be capitalized at least in "Schwann cells". With Schwannoma / schwannoma it's questionable, I found it in different sources both with s and S. But we should decide to one way of spelling and be consistent with it.

**Comment by pnrobinson** [comment]
I think that schwannoma is usually not capitalized but Schwann cell is. I have adjusted the spelling as necessary and think/hope I got all instances. Thanks!
