### ISSUE TITLE
Intrarotation contracture of the shoulder joint 

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9681]
Label:Intrarotation contracture of the shoulder joint 
Synonym: Internal rotation contracture of the shoulder joint, Shoulder internal rotation contracture.

Shahrzad and Noemi, could you define the Internal rotation contracture of the shoulder joint ? Is the following correct?

def: Lack of the full expected passive range of internal rotation (moving the shoulder such that the hand approaches the middle of ones body) of the shoulder joint.
PMID:[24987487](https://pubmed.ncbi.nlm.nih.gov/24987487)

Comment: Internal rotation contracture is the most frequent and important secondary deformity of the shoulder in children with Erb’s palsy. It occurs due to weakness of the external rotators (teres minor and infraspinatus) muscles compared to the internal rotators (teres major, pectoralis major, latissimus dorsi) muscles. Because of the lack of external rotation and persistence of internal rotation, chronic posterior shoulder dislocation develops.

**Comment by shahrzadnema** [comment]
Edit: Please remove this term.

**Comment by pnrobinson** [comment]
I never added this term so there is no need to remove it. I will close this issue for now, and we can revisit if needed.
