### ISSUE TITLE
Adduction contracture of the shoulder

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9682]
**Preferred term label:**
Adduction contracture of the shoulder

Shahrzad and Noemi, please provide definition

**Comment by shahrzadnema** [comment]
The definitions for Adduction (that I have found):
- Movement of a body part toward the median plane (of the body, in the case of limbs; of the hand or foot, in the case of digits) or midline of the body. (Ref.: Medical Dictionary for the Health Professions and Nursing. 2012. Farlex 22 Jul. 2022 https://medical-dictionary.thefreedictionary.com/adduction)
- Movement in the coronal plane that moves a limb medially toward or across the midline of the body; bringing fingers together (Betts, J. Gordon, et al. “Key Terms.” Anatomy and Physiology 2e, by J. Gordon Betts, Houston, Texas, openstax.org, 20 Apr. 2022, openstax.org/books/anatomy-and-physiology-2e/pages/1-introductionkey-terms. Accessed 15 July 2022.)

**Comment by shahrzadnema** [comment]
edited defintion: Decreased abduction movement of shoulder. Shoulders are closer to midline and inability to position shoulders away from the body.  Movement of hands toward the median plane or midline of the body.

**Comment by pnrobinson** [comment]
@shahrzadnema 

I have added with this revised definition:
HP:0035009
Label:Shoulder adduction contracture
A type of shoulder contracture characterized by a chronic reduction in the active and passive ability to abduct the shoulder. This results in the shoulders being closer to midline. The affected individual is not able to position the shoulders away from the body.
