### ISSUE TITLE
Abduction contracture of the shoulder

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9683]
**Preferred term label:**
Abduction contracture of the shoulder

Shahrzad and Noemi, please provide definition

**Comment by shahrzadnema** [comment]
- Movement of a body part away from the median plane (of the body, in the case of limbs; of the hand or foot, in the case of digits) (Ref.:"abduction." Medical Dictionary for the Health Professions and Nursing. 2012. Farlex 21 Jul. 2022 https://medical-dictionary.thefreedictionary.com/abduction)
- Movement in the coronal plane that moves a limb laterally away from the body; spreading of the fingers (Ref.: Betts, J. Gordon, et al. “Key Terms.” Anatomy and Physiology 2e, by J. Gordon Betts, Houston, Texas, openstax.org, 20 Apr. 2022, openstax.org/books/anatomy-and-physiology-2e/pages/1-introductionkey-terms. Accessed 15 July 2022.)

**Comment by shahrzadnema** [comment]
Edited definition==>Decreased adduction movement of shoulder. Movement of a body part away from the median plane (of the body, in the case of limbs; of the hand or foot, in the case of digits).

**Comment by pnrobinson** [comment]
@shahrzadnema 

added as

label: Shoulder abduction contracture
id: HP:0034990
def: A type of shoulder contracture characterized by decreased adduction movement of shoulder, that is, by a decreased ability to move the arm via the shoulder joint away from the median plane of the body.
synonym:Abduction contracture of the shoulder
