### ISSUE TITLE
External rotation contracture of the shoulder joint

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9684]
**Preferred term label:**
External rotation contracture of the shoulder joint

Shahrzad and Noemi, please provide definition

**Comment by shahrzadnema** [comment]
Movement of a joint, around its long axis, away from the midline of the body.  (Ref. "external rotation." Medical Dictionary for the Health Professions and Nursing. 2012. Farlex 21 Jul. 2022 https://medical-dictionary.thefreedictionary.com/external+rotation)

**Comment by shahrzadnema** [comment]
edited definition==>synonym to “Lack of internal Rotation”. Definition= Movement of the shoulder joint, around its long axis, away from the midline of the body.

**Comment by pnrobinson** [comment]
@shahrzadnema 

added as

Shoulder external rotation contracture
HP:0034991
def: A type of shoulder contracture characterized by decreased internal rotation of shoulder, that is, by a Chronic reduction in active and passive ability to internally rotate the humerus at the shoulder joint (if the arm is flexed at the elbow, Internal rotation of the shoulder rotates the forearm towards the center of the body).
synonym: External rotation contracture of the shoulder joint
