### ISSUE TITLE
Thumb extension contracture

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9685]
**Preferred term label:**
Thumb extension contracture

Shahrzad and Noemi, please provide definition

**Comment by shahrzadnema** [comment]
Movement in the sagittal plane that increases the angle of a joint (straightens the joint); motion involving posterior bending of the vertebral column or returning to the upright position from a flexed position (Ref.: Betts, J. Gordon, et al. “Key Terms.” Anatomy and Physiology 2e, by J. Gordon Betts, Houston, Texas, openstax.org, 20 Apr. 2022, openstax.org/books/anatomy-and-physiology-2e/pages/1-introductionkey-terms. Accessed 15 July 2022.)

**Comment by shahrzadnema** [comment]
edit: No new changes are made to the definition. The definition is: Movement in the sagittal plane that increases the angle of the thumb joint (straightens the joint); motion involving posterior bending of the vertebral column or returning to the upright position from a flexed position.

**Comment by pnrobinson** [comment]
@shahrzadnema 
this was
HP:0034667

Term Name: Thumb extension contracture

Synonyms:

Definition: Movement in the sagittal plane that increases the angle of the thumb joint (straightens the joint); motion involving posterior bending of the vertebral column or returning to the upright position from a flexed position.
