### ISSUE TITLE
Design pattern for use of 'has extra parts of type' in logical definitions

### ISSUE THREAD

**Issue by mbrush** [obophenotype/human-phenotype-ontology#969]
What is the preferred design pattern for using qualities like 'has extra parts of type' in hpo?

For example, with a phenotype of **"hyper-mannosylation of N-glycans"** (increased prevalence of mannose residues in sugar chains decorating cellular proteins), we might say:
1. 'has extra parts  of type' and ('inheres in' some N-glycan) and (towards some 'mannose residue')  
   OR
2. 'has extra parts  of type'  and ('inheres in' some ('mannose residue' and ('part of' some N-glycan))

Both patterns are common in hpo (compare HP_0009594 ! Retinal hamartoma  vs HP_0008985 ! Increased intramuscular fat).  I seem to recall we are moving away from use of the 'towards' relation, so guessing that pattern 2 is referred?  And perhaps using 'increased amount' here instead of 'has extra parts of type'?

@cmungall, @drseb?

**Comment by balhoff** [comment]
I wouldn't say those two are equivalent. The first says that 'N-glycan' has extra 'mannose residue', but the second says that a 'mannose residue' (which is part of an 'N-glycan') has extra parts of some unknown type. I don't think the 'Increased intramuscular fat' expression looks quite right.

**Comment by mbrush** [comment]
Yes, I would agree that these are not saying the same thing  - and I think the first pattern better captures the glyco-phenotype we want to describe.  But it seems that HPO is evolving in the direction of the second design pattern, and away from use of the RO:towards relation in logical definitions.  Hence the fishy'intramuscular fact' logical definition.

For the molecular glycan phenotypes we are creating in MGPO, the first 'towards'-based pattern may helps with some of the precise distinctions we need to make (e.g. between altered  levels of classes of glycans, altered composition in terms of the types of residues found in glycans, and altered overall length of glycans).  Should have some more examples to share as our work here continues.

**Comment by pnrobinson** [comment]
@cmungall @mbrush @balhoff @drseb 
Did we ever resolve this? It would be great to document this on the HPO github wiki and close the discussion here.

**Comment by pnrobinson** [comment]
I am closing this issue. Please add any new comments to the new site on design patterns.
