### ISSUE TITLE
Comment is merged into defintion for HP:0033520 | Paradoxical embolism 

### ISSUE THREAD

**Issue by turnovec** [obophenotype/human-phenotype-ontology#9693]
**HPO term**
HP:0033520 | Paradoxical embolism 

**Bug description**
The definition is:
Paradoxical embolism describes the passage of a venous or right-sided cardiac thrombus into the arterial or systemic circulation. Comment: Paradoxical embolism occurs most commonly through an intracardiac defect at the atrial level, but can also be due to another type of right-to-left-shunt, as for example in pulmonary arteriovenous malformations. Paradoxical embolism may lead to serious complications as ischemic stroke.

I think that "Comment" part should be separated. Even in hp.obo file it is in definition file after newline character (\n)...

**Comment by pnrobinson** [comment]
Ups! Thanks for finding this mistake! Fixed
