### ISSUE TITLE
Three typos in definition of HP:0033181 | Spinal epidural abscess 

### ISSUE THREAD

**Issue by turnovec** [obophenotype/human-phenotype-ontology#9695]
**HPO term**
HP:0033181 | Spinal epidural abscess 

**Bug description**
Current definition: "Spinal epidural abscess (SEA) is caused by a suppurative infection in the epidural space. The mass effect ofthe abscess can compress and reduce blood flow to the spinal cord, conus medullaris, or cauda equina. Left untreated, the infection can lead to sensory loss,muscle weakness, visceral dysfunction, sepsis, and even death. Early diagnosis is essential to limit mor-bidity and neurologic injury. The classic triad of fever, axial pain, and neurological deficit occurs in as few as 13 percent of patients, highlighting the diagnosticchallenge associated with SEA."

ofthe → of the
mor-bidity → morbidity
diagnosticchallenge → diagnostic challenge

**Comment by pnrobinson** [comment]
Thank you, I fixed the three errors and also am moving "Left untreated, the infection can lead to sensory loss, muscle weakness, visceral dysfunction, sepsis, and even death. Early diagnosis is essential to limit morbidity and neurologic injury. The classic triad of fever, axial pain, and neurological deficit occurs in as few as 13 percent of patients, highlighting the diagnostic challenge associated with SEA." from the definition to the comment section.
