### ISSUE TITLE
hyperintensities of white matter

### ISSUE THREAD

**Issue by slaulederkind** [obophenotype/human-phenotype-ontology#970]
I would like to see "Hyperintensity of cerebral white matter on MRI" added to the HP ontology under the parent term “Abnormality of the cerebral white matter (HP:0002500). The definition could be "A brighter than expected signal on magnetic resonance imaging emanating from the cerebral white matter."   Synonyms would be "white matter hyperintensities" and "WMH”.

I would also like to see two new children terms added under the new parent term “"Hyperintensity of cerebral white matter on MRI”:

"Periventricular white matter hyperdensities" - Definition could be "Areas of brighter than expected signal on magnetic resonance imaging emanating from the cerebral white matter that surrounds the cerebral ventricles."  Synonyms would be "periventricular white matter hyperintensities" and "PVWMH”. This term could also be added as a parent to "Punctate periventricular T2 hyperintense foci" (HP:0030081).

"Deep white matter hyperdensities" - Definition could be "Areas of brighter than expected signal on magnetic resonance imaging emanating from the deep cerebral white matter."  Synonyms would be "deep white matter hyperintensities" and "DWMH”. 

Examples of use can be found in PMID:15576652.  

Also, the reference (pmid:16239634) used as a "Definition source" in HP for "Periventricular white matter hypodensities" (HP:0012794) and "Deep white matter hypodensities" (HP:0007321) is a commentary of PMID:15576652.  It mentions only "hyperintensities", not "hypointensities".

Thanks.

**Comment by pnrobinson** [comment]
Thanks for these suggestions, just added them to the HPO.
