### ISSUE TITLE
One word two times in definition for HP:0033480 | Hypobilirubinemia

### ISSUE THREAD

**Issue by turnovec** [obophenotype/human-phenotype-ontology#9700]
**HPO term**
HP:0033480 | Hypobilirubinemia

**Bug description**
Definition: "Decreased circulation of bilirubin in the blood circulation."
The word "circulation" is there two times. Maybe instead of the first occurrence it should be "concentration"?

**Comment by pnrobinson** [comment]
Thanks!
Changed definition to
Concentration of bilirubin in the blood circulation below the lower limit of normal.
