### ISSUE TITLE
HP:4000075 and HP:0034642 lack parents in hp-edit.owl

### ISSUE THREAD

**Issue by matentzn** [obophenotype/human-phenotype-ontology#9701]
HP:4000075 and HP:0034642 lack parents in hp-edit.owl

When fixing this, make sure to

- [x] remove the fact that HP:4000075 is a parent of itself.

@bcoleman96 this is in your data sheet - I assume you checked the file I send you and it looked reasonable otherwise?

**Comment by bcoleman96** [comment]
I am still reviewing the OWL file.

I fixed HP:4000075 in the datasheet but I can't understand the issue with HP:0034642. It is not in the spreadsheet I created, nor is it on the HPO website. Could someone else have added it?

**Comment by matentzn** [comment]
Have you been fixing more things in the data sheet? Because we just merged the branch! I didn't update it again from yesterday

**Comment by pnrobinson** [comment]
fixed with recent push
