### ISSUE TITLE
Typo in definition of HP:0041048 | Decreased expression of GPI-anchored proteins on the cell surface

### ISSUE THREAD

**Issue by turnovec** [obophenotype/human-phenotype-ontology#9719]
**HPO term**
HP:0041048 | Decreased expression of GPI-anchored proteins on the cell surface

**Bug description**
Definition: "A decrease in the protein expression fo GPI-anchor proteins, such as CD55 and CD59, at the cell surface, which suggests a defect in GPI-anchor biosynthesis."
fo → of

**Comment by pnrobinson** [comment]
fixed, thanks!
