### ISSUE TITLE
dc:creator

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9721]
I cannot find dc:creator in the annotations in Protege, and am not sure how to set this up in Protege -- could we add this to the editors guide in the wiki?

**Comment by matentzn** [comment]
Can you try to use the Protege 5.5. instructions: https://oboacademy.github.io/obook/howto/set-up-protege/#setting-username-and-auto-adding-creation-date (Use http://purl.org/dc/terms/creator not http://purl.org/dc/terms/contributor)
I can fix the ones you did now for you
just push them

**Comment by pnrobinson** [comment]
@matentzn  -- thanks, I think I figured it out!
