### ISSUE TITLE
Missing space in definition of HP:0032378 - Immediate-type hypersensitivity drug reaction

### ISSUE THREAD

**Issue by turnovec** [obophenotype/human-phenotype-ontology#9722]
**HPO term**
HP:0032378 | Immediate-type hypersensitivity drug reaction 

**Bug description**
Definition: "Hypersensitivity that is observed within 1 hr of exposures. A variety of adverse reactions can occur within minutes to hours of exposure to a drug. Some can be related to the pharmacological action of the drug (WHO Adverse Reaction Terminology type A for augmented) and usually have a low mortality. Others are not readily predictable based on the structure and pharmacological action of the drug and have a relatively high mortality risk (Type B for bizarre). The most serious form of immediate onset drug hypersensitivity reaction, anaphylaxis. Other reactions including itching,dizziness/light-headedness, nausea, chest discomfort but without any objective skin features, physical signs or physiological compromise. Skin only reactions include generalized erythema, urticaria or angioedema without any sentinel features (see below) of other organ involvement."
There is missing space after comma: "itching,dizziness"

**Comment by pnrobinson** [comment]
Fixed, thanks!
