### ISSUE TITLE
Merge Impaired social interactions into Abnormal social behavior

### ISSUE THREAD

**Issue by bcoleman96** [obophenotype/human-phenotype-ontology#9724]
**HPO term**
Impaired social interactions
HP:0000735

**Reason for deprecation**
This term is non-specific and could describe everything from a language impairment to a covid lockdown. It is better to describe specific abnormalities such as environment or abnormal social behavior. Additionally, terms exist to describe the state of not having relationships that are independent of an impairment.

**Suggested replacement or term to consider**
Merge into Abnormal social behavior (HP:0012433)

**Comment by pnrobinson** [comment]
done/reworked
