### ISSUE TITLE
Move Drooling HP:0002307 out of behavioral branch

### ISSUE THREAD

**Issue by bcoleman96** [obophenotype/human-phenotype-ontology#9726]
**HPO term**
Drooling HP:0002307

**Suggested revision of textual definition**
This isn't really a behavioral term on its own. In workshops we discussed putting this into a category for terms without a clear home. I recommend we **change the parent to Constitutional symptom (HP:0025142)**.

**Comment by pnrobinson** [comment]
Done. It is now only a child of excessive salivation
