### ISSUE TITLE
Malignant hyperthermia

### ISSUE THREAD

**Issue by kanems** [obophenotype/human-phenotype-ontology#9727]
**HPO term**
Malignant hyperthermia HP:0002047

**Suggested revision of textual definition**
Malignant hyperthermia is characterized by a rapid increase in temperature to 39-42 degrees C. May occur in response to either inhalational anesthetics such as halothane, to muscle relaxants such as succinylcholine, or to exercise.

*Note: Orphanet recognizes both the anesthesia- and exercise-triggered forms of MH, I think HPO needs an entry for the form that is agnostic of the trigger or underlying genetics and possibly records for the anesthesia and exercise triggered forms?

**Comment by pnrobinson** [comment]
changed as suggested, thanks
