### ISSUE TITLE
Cleft lip terms: laterality agnostic + completeness agnostic

### ISSUE THREAD

**Issue by sabrinatoro** [obophenotype/human-phenotype-ontology#9730]
Goal: annotate bilateral cleft lips data. 

We want to be able to annotate the fact that any type of cleft lip (micro, complete, incomplete) could be on the left side and on the right side when having a bilateral cleft lip. 
One option would be to create terms for all combinations of bilateral cleft lip type (e.g. complete LCL/micro RCL; incomplete LCL/complete RCL; …), but this would require the creation of too many terms. 

Based on PMID:19884685, there are 4 types of bilateral cleft lips: 
Bilateral microform (both sides are microform)
Bilateral incomplete (one side is incomplete, the other side is incomplete or microform)
Bilateral complete (both sides are complete)
Bilateral asymmetric (one side is complete, the other side is either incomplete or complete)

We still need to specify what the cleft lip is on the left and on the right side. Therefore we need terms for “complete cleft lip”, “incomplete cleft lip”, and “microform cleft lip”. These terms are independent of bilateral/unilateral cleft lip
Currently, the existing terms are specific for the “unilateral cleft lip”, which definition specifies that this is when a cleft is ONLY on one side. 

The annotations will be done as follow: 
For bilateral cleft lip: 3 annotations
- Bilateral cleft lip term (see above)
- complete/incomplete/microform CL term + modifier left
- complete/incomplete/microform CL term + modifier right
For unilateral cleft lip:  
complete/incomplete/microform unilateral cleft lip terms
Note: we could also use “unilateral cleft lip” + one of the new complete/incomplete/microform CL terms

It seems like this allows the most flexibility for making annotations referring to both laterality and completeness. If we agree that this is the way to go, the same strategy will be used for the cleft maxillary alveolar ridge (ie creating laterality agnostic terms + completeness agnostic terms)

**Comment by pnrobinson** [comment]
@sabrinatoro sorry I think this fell through the cracks. I recall we wanted to discuss this with colleagues, can we touch bases after J4?

**Comment by pnrobinson** [comment]
implemented, closing
