### ISSUE TITLE
Comparison of phenotypes with no common parental term

### ISSUE THREAD

**Issue by jagcsun** [obophenotype/human-phenotype-ontology#9732]
In one of the exomiser comparisons of phenotypes of a patient and a known disease from OMIM (using HPO terms), a reported match does not have a common parental term in HPO:
_HP:0032239, Increased circulating band cell count - HP:0002282, Gray matter heterotopia_

This was first reported as an error in [Exomiser GitHub](https://github.com/exomiser/Exomiser/issues/490) and then based on @julesjacobsen suggestion, it is posted here. 

@pnrobinson

**Comment by pnrobinson** [comment]
This is not related to the HPO files, it is an algorithmic issue that is being addressed in the Exomiser project.
