### ISSUE TITLE
Duplicate word in definition for HP:0033004 | Palmar warts 

### ISSUE THREAD

**Issue by turnovec** [obophenotype/human-phenotype-ontology#9738]
**HPO term**
HP:0033004 | Palmar warts 

**Bug description**
Definition: "Multiple verrucous lesions on the skin of the palm. These lesions are raised, have a thickened and rough surface, and may display prominent black dots (thrombosed capillaries). Palmar warts are caused by caused by human papillomavirus (HPV)."

I think that one "caused by" in the last sentence could be removed.

**Comment by pnrobinson** [comment]
fixed
