### ISSUE TITLE
HP:0002719 Recurrent Infections 

### ISSUE THREAD

**Issue by GenomeDeb** [obophenotype/human-phenotype-ontology#974]
Hi this term does not say "bacterial" or "microbial" in the term, but in the definition it specifies increased susceptibility "to microbial infections". If this is general increased susceptibility to infections then viral induced infection should be in the definition too. I am looking for a term that would cover general increased susceptibility to infections, whether bacterial, microbial or viral. I nearly used this one until double checking the definition of the term, it would not fit because our subjects also have viral infection susceptibility too.

**Comment by GenomeDeb** [comment]
Sorry not to be clear here. I suggest the term should be re-named Increased Susceptibility to Microbial Infections , to make it clear that this does not cover all types of infections (viral). Thank you! For my own case I will use HP:0004429 and HP:0002719.

**Comment by drseb** [comment]
It does include viral infections, as it has the subclass "Recurrent viral infections". I changed the text-defintion to remove the word microbial. @pnrobinson
