### ISSUE TITLE
Better definition for HP:0033045 | Bipedal edema

### ISSUE THREAD

**Issue by turnovec** [obophenotype/human-phenotype-ontology#9740]
**HPO term**
HP:0033045 | Bipedal edema

**Bug description**
Definition: "A palpable swelling in both feet and ankles caused by palpable swelling caused by an increase in interstitial fluid volume (excess fulid)."
I think that "palpable swelling caused by palpable swelling" doesn't make much sense. The second occurrence could be removed. And last word should be "fluid" (not fulid). Maybe it should be "excessive fluid". Or it could be removed completely ("increase in interstitial fluid" is clear enough).

**Comment by pnrobinson** [comment]
Changed to

A palpable swelling in both feet and ankles caused by an increase in interstitial fluid volume (excess fluid).

Thanks!
