### ISSUE TITLE
Typo in definition of HP:0034318 | Unusual virus reactivation 

### ISSUE THREAD

**Issue by turnovec** [obophenotype/human-phenotype-ontology#9741]
**HPO term**
HP:0034318 | Unusual virus reactivation 

**Bug description**
Definition: "Reactivation is the mechanism whereby a latent virus that has infected a host cell switches to a lytic stage, undergoing productive viral replication and allowing the virus to spread. This term refers to reactivation regarded as unusual because of frequency, intensity, location, or nature of the virus, in the sense that the rreactivation would not be observed in an immunocompetent host."

rreactivation → reactivation

**Comment by pnrobinson** [comment]
fixed
