### ISSUE TITLE
Errors in definition for HP:0032422 | Abnormal HDL2b concentration 

### ISSUE THREAD

**Issue by turnovec** [obophenotype/human-phenotype-ontology#9743]
**HPO term**
HP:0032422 | Abnormal HDL2b concentration 

**Bug description**
Defintion: "Any deviation from the normal concentration of the HDL2a subfraction in the blood circulation. An HDL2B particle is defined as an HDL particle with a size of 9.7-12 nm."

Why it is referring to HDL2a? It should be HDL2b... And the second occurrence is wrongly capitalized (should be HDL2b, not HDL2B).

**Comment by pnrobinson** [comment]
Thanks for pointing out this mistake -- fixed!
