### ISSUE TITLE
Wrong capitalization of HDL2a in definitions of HP:0032419, HP:0032420 and HP:0032421

### ISSUE THREAD

**Issue by turnovec** [obophenotype/human-phenotype-ontology#9744]
**HPO terms**
HP:0032419 | Abnormal HDL2a concentration
HP:0032420 | Increased HDL2a concentration
HP:0032421 | Decreased HDL2a concentration 

**Bug description**
In definitions of these terms, there is HDL2a referred as "HDL2A". So it should be corrected:
HDL2A → HDL2a

**Comment by pnrobinson** [comment]
fixed!
