### ISSUE TITLE
Duplicate comma in definition of HP:0033168 | Reduced mevalonate kinase activity 

### ISSUE THREAD

**Issue by turnovec** [obophenotype/human-phenotype-ontology#9745]
**HPO term**
HP:0033168 | Reduced mevalonate kinase activity 

**Bug description**
Definition: "Abnormally reduced activity of mevalonate kinase, ,which is a key enzyme in the mevalonate biosynthetic pathway that leads to the synthesis of both cholesterol and nonsterol isoprenoids."

There are two commas separated by space between "kinase" and "which".

**Comment by pnrobinson** [comment]
fixed
