### ISSUE TITLE
Duplicate word in definition of HP:0033480 | Hypobilirubinemia

### ISSUE THREAD

**Issue by turnovec** [obophenotype/human-phenotype-ontology#9746]
**HPO term**
HP:0033480 | Hypobilirubinemia 

**Bug description**
Definition: "Decreased circulation of bilirubin in the blood circulation."

Maybe instead of first "circulation" there should be concentration?

**Comment by pnrobinson** [comment]
Fixed to
Concentration of bilirubin in the blood circulation below the lower limit of normal.
