### ISSUE TITLE
Typo in definition of HP:0032516 | Invasive dermatophyte infection 

### ISSUE THREAD

**Issue by turnovec** [obophenotype/human-phenotype-ontology#9749]
**HPO term**
HP:0032516 | Invasive dermatophyte infection 

**Bug description**
Defintion: "Infection that extends deeply into the dermins by dermatophytes, fungi that typically cause different types of superficial infection (tinea) or skin, hair, or nails."

dermins → dermis

**Comment by pnrobinson** [comment]
fixed
