### ISSUE TITLE
Wrong definition for HP:0034018 | Anti-class II HLA antibody positivity 

### ISSUE THREAD

**Issue by turnovec** [obophenotype/human-phenotype-ontology#9751]
**HPO term**
HP:0034018 | Anti-class II HLA antibody positivity 

**Bug description**
Defintion: "The presence of autoantibodies (immunoglobulins) in the blood circulation that react against a class I human leukocyte antigen (HLA). Class I HLA corresponds to MHC class II (DP, DM, DO, DQ, and DR)."

It looks like it is copied from definition for Anti-class I HLA antibody positivity (HP:0034017). At least the first sentence and beginning of the seccond one. I think it should be something like this:

"The presence of autoantibodies (immunoglobulins) in the blood circulation that react against a class II human leukocyte antigen (HLA). Class II HLA corresponds to MHC class II (DP, DM, DO, DQ, and DR)."

**Comment by pnrobinson** [comment]
@turnovec thanks for pointing this out. I corrected to

The presence of autoantibodies (immunoglobulins) in the blood circulation that react against a class II human leukocyte antigen (HLA). Class I HLA corresponds to MHC class II (DP, DM, DO, DQ, and DR).
