### ISSUE TITLE
Wrong definition for HP:4000020 | Anti-BP180 antibody positivity?

### ISSUE THREAD

**Issue by turnovec** [obophenotype/human-phenotype-ontology#9752]
**HPO term**
HP:4000020 | Anti-BP180 antibody positivity

**Bug description**
Defintion: Bullous pemphigoid (BP) is an autoimmune disease associated with subepidermal blistering due to autoantibodies directed against BP180 and BP230. BP180 is currently considered as the major pathogenic autoantigen.

Comment: The presence of autoantibodies (immunoglobulins) in the serum that react against BP180. 

For me it looks like the texts of comment and definition are swaped...

**Comment by pnrobinson** [comment]
I agree-- I have swapped them back! Thanks
