### ISSUE TITLE
Typo in definition of HP:0033154 | Elevated circulating deoxypyridinoline concentration 

### ISSUE THREAD

**Issue by turnovec** [obophenotype/human-phenotype-ontology#9757]
**HPO term**
HP:0033154 | Elevated circulating deoxypyridinoline concentration 

**Bug description**
Definition: "An increased concentration of lysyl-pyridinoline (deoxypyridinoline) cross-links in the bloood circulation."

bloood → blood

**Comment by pnrobinson** [comment]
fixed!
