### ISSUE TITLE
Difference between owl and obo version of v2023-04-05 or wrong use ?

### ISSUE THREAD

**Issue by valerieLanneau** [obophenotype/human-phenotype-ontology#9758]
**HPO term**
HP:0032541

**Bug description**
Dear all, 
I noticed that the term HP:0032541 Knuckle pad is found using the search engine on Jax website https://hpo.jax.org/app/browse/search?q=HP:0032541&navFilter=all
and I can find it in the obo release v2023-04-05 "Download latest hp.obo" on https://hpo.jax.org/app/data/ontology

But I cannot find it using files at the same date http://purl.obolibrary.org/obo/hp/hp-international.owl. accessible from https://github.com/obophenotype/human-phenotype-ontology/releases OR "Download latest hp.owl" accessible on https://hpo.jax.org/app/data/ontology

Maybe it's just my misuse of the files? or I must to work only with the obo version to be the most up to date ?

Best regards,
Valerie Lanneau

**Comment by pnrobinson** [comment]
The hp-internal.owl file is the new prototype file presenting HPO translations, probably you want simply hp.owl. For typical analysis purposes we recommend using the JSON or OBO file (if all you need is the HP ontology graph). @matentzn @iimpulse @drseb  -- we need to document this better on the website!

**Comment by matentzn** [comment]
@valerieLanneau The ID in the OWL serialisation is different. If you open hp.obo as a text file you will find:

```
[Term]
id: HP:0032541
name: Knuckle pad
```

If you open the OWL version as a text file, you will find:

```
<!-- http://purl.obolibrary.org/obo/HP_0032541 -->

    <owl:Class rdf:about="http://purl.obolibrary.org/obo/HP_0032541">
        ....
        <rdfs:label>Knuckle pad</rdfs:label>
    </owl:Class>
```

You can see, the OBO identifier, `HP:0032541` is written in CURIE form (compact URI), while the same identifier in hp.owl (or hp-international.owl) is written in URI syntax:  `http://purl.obolibrary.org/obo/HP_0032541`.

@pnrobinson Sure, we can document this better! If @iimpulse shares a link with a table of all files we should document, and I will fill in the content.

**Comment by valerieLanneau** [comment]
Dear Peter and Nico, 
thanks a lot for your explanations.

Best regards,
Valérie

**Comment by pnrobinson** [comment]
thanks!
