### ISSUE TITLE
Why the Disease ID and G-D source were deleted in the phenotype_to_genes.txt file?

### ISSUE THREAD

**Issue by Leejunho123** [obophenotype/human-phenotype-ontology#9760]
Hello HPO teams.
I wonder why the Disease ID and G-D source were deleted in the phenotype_to_genes.txt file.
I also want to see the information on Disease to Gene.

**Comment by pnrobinson** [comment]
@Leejunho123 
Please see the latest release -- [we have slightly changed the format bu](https://hpo.jax.org/app/data/annotations)
