### ISSUE TITLE
Unifying stenosis EQs

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#9762]
Trying to make as many 'stenosis' terms as consistent as possible. The vast majority of the terms (60+) are constant with the upheno pattern found [HERE](https://github.com/obophenotype/upheno/tree/master/src/patterns/dosdp-patterns#abnormal-constriction-of-anatomical-entity)
However, 2 terms use 'decreased width' instead of 'constricted' and 2 terms use 'characteristic part of' instead of 'characteristic of'. 

Several terms do not have EQs at all. Many are complicated, but I propose that 9 of these terms could add EQ based on the listed UBERON term.

<google-sheets-html-origin><style type="text/css"></style>

HPID | Label |   | Current term used in EQ
-- | -- | -- | --
HP:0000402 | Stenosis of the external auditory canal' |   | decreased width
HP:0008714 | Ureterovesical stenosis' |   | decreased width
  |   |   |  
HP:0000071 | Ureteral stenosis' |   | characteristic of part of
HP:0008661 | Urethral stenosis' |   | characteristic of
HP:0040103 | Cutaneous stenosis of the external auditory canal' |   | characteristic of
HP:0001602 | Laryngeal stenosis' |   | characteristic of
HP:0010446 | Tricuspid stenosis' |   | characteristic of part of

  | HPID | Label |   |   | Suggested UBERON term |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
NEQ | HP:0100254 | Stenosis of the medullary cavity of the long bones' |   |   | UBERON:0016413 | medullary cavity of long bone |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
NEQ | HP:0025491 | Venous stenosis' |   |   | UBERON:0001638 | vein |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
NEQ | HP:0012851 | Colonic stenosis' |   |   | UBERON:0001155 | colon |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
NEQ | HP:0025572 | Punctal stenosis' |   |   | UBERON:0001770 | lacrimal canaliculus |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
NEQ | HP:0010644 | Midnasal stenosis' |   |   | UBERON:0004110 | midnasal cavity |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
NEQ | HP:0100546 | Carotid artery stenosis' |   |   | UBERON:0005396 | carotid artery segment |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
NEQ | HP:0012492 | Cerebral artery stenosis' |   |   | UBERON:0004449 | cerebral artery |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
NEQ | HP:0012848 | Small intestinal stenosis' |   |   | UBERON:0002108 | small intestine |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
NEQ | HP:0032077 | Male urethral meatus stenosis' |   |   | UBERON:0012241 | male urethral meatus' |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
NEQ | HP:0040118 | Stenosis of the Eustachian tube' |   |   | UBERON:0010062 | pharyngotympanic tube epithelium |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  

@sbello @rays22

**Comment by sbello** [comment]
Suggest using http://purl.obolibrary.org/obo/UBERON_0002393 instead of UBERON:0010062

**Comment by pnrobinson** [comment]
@LCCarmody @sbello  --  is there still an open action item for this or can we close?

**Comment by pnrobinson** [comment]
@LCCarmody can we finalize this issue?

**Comment by LCCarmody** [comment]
I’ll work on this on Monday

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by LCCarmody** [comment]
made PR https://github.com/obophenotype/human-phenotype-ontology/pull/10610 
Some had already been updated, but I added all that could be added...except lacrimal canaliculus, which needs to be added to CHEBI slim before being able to add to EQ.

If you are okay with this, I will merge PR.
