### ISSUE TITLE
Remove logical def from Esophageal stricture

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#9763]
**HPO term**
Esophageal stricture (HP_0002043)  Textual definition is "A pathological narrowing of the esophagus that is caused by the development of a ring of scar tissue that constricts the esophageal lumen." 
Log def: 'has part' some 
    (constricted
     and ('characteristic of' some esophagus)
     and ('has modifier' some abnormal))

BUT it is child of the term
Esophageal stenosis (HP_0010450) Textual definition is "An abnormal narrowing of the lumen of the esophagus."
Log def: 'has part' some 
    (constricted
     and ('characteristic of' some 'lumen of esophagus')
     and ('has modifier' some abnormal))

**Suggested revision of logical definition**
I think the logical definition of Esophageal stricture should be removed because it doesn't make any reference to scarring and is not sufficiently different from esophageal stenosis.

**Comment by pnrobinson** [comment]
Agree. Also, it is the narrowing of the lumen that is important, and these two logical definitions were essentially identical. I have removed it.
