### ISSUE TITLE
Repetition in definition of HP:0032347 | Cutaneous macular amyloidosis 

### ISSUE THREAD

**Issue by turnovec** [obophenotype/human-phenotype-ontology#9765]
**HPO term**
HP:0032347 | Cutaneous macular amyloidosis 

**Bug description**
Definition: "A type of cutaneous amyloidosis that is characterized by hyperpigmented patches with indefinite margins composed of grayish brown macules, often with a reticulated or rippled appearance. Lesions may present as a hyperpigmented patch composed of small brown macules in a rippled or reticulated pattern."

It looks to me like the second sentence is just repeating the same information like the first sentence.

**Comment by pnrobinson** [comment]
You are correct - thanks for pointing this out. I have simplified the definition to 

A type of cutaneous amyloidosis that is characterized by hyperpigmented patches with indefinite margins composed of grayish brown macules, often with a reticulated or rippled appearance.
