### ISSUE TITLE
HPO terms missing from the phenotype to genes.txt file in release 2023-05-04

### ISSUE THREAD

**Issue by AlexRL2023** [obophenotype/human-phenotype-ontology#9767]
Hello, 
We have an issue related to the content of the phenotype to gene.txt file from the 2023-05-04 release.
We have noticed that in this file there are only 674.232 lines while in the previous version this same file contained 1.117.570 lines.
Some HPOs (such as  HP:0008771) has disappeared from the 2023-05-04 file. However, this term was present in the previous release and it is present in the web browser).
Could you help us with this issue.
Alejandro

**Comment by pnrobinson** [comment]
@AlexRL2023 
Hi Alejando, we have been extensively updating the entire pipeline and think things are now correct. If you still are seeing this problem, please open a new issue.
