### ISSUE TITLE
Typo in definition of HP:0025624 | Reduced proportion of CD4+ effector memory T cells

### ISSUE THREAD

**Issue by turnovec** [obophenotype/human-phenotype-ontology#9773]
**HPO term**
HP:0025624 | Reduced proportion of CD4+ effector memory T cells

**Bug description**
Definition: "An abnormally decreased proportion of effector memory CD4+ T cells compared to the total number of T cells in the blood. These are memory cells that are short-lived cells that migrate to the site of an infection and attempt to eliminate the pathogen. These cells have the phenotype CD3-positive, CD4-positive, CD62L-ngative, CCR7-negative, CD127-positive, CD45RA-negative, CD45RO-positive, and CD25-negative."

CD62L-ngative → CD62L-negative

**Comment by pnrobinson** [comment]
fixed
