### ISSUE TITLE
Missing space in definition of HP:4000025 | Anti-integrin antibody positivity 

### ISSUE THREAD

**Issue by turnovec** [obophenotype/human-phenotype-ontology#9774]
**HPO term**
HP:4000025 | Anti-integrin antibody positivity 

**Bug description**
Definition: The presence of autoantibodies (immunoglobulins) in the serum that react against an integrin. Integrins are a family of cell adhesion moleculeswith 24 known integrin heterodimers. Integrins transduce mechanical and biochemical signals from fibrotic extracellular matrix into the cell, activate latent TGFbeta, and subsequently modulate fibroblast adhesion, migration, and growth.

moleculeswith → molecules with

**Comment by pnrobinson** [comment]
fixed!
