### ISSUE TITLE
Typo in definition of HP:5000030 | Anti-Ri antibody 

### ISSUE THREAD

**Issue by turnovec** [obophenotype/human-phenotype-ontology#9775]
**HPO term**
HP:5000030 | Anti-Ri antibody 

**Bug description**
Definition: The presence of autoantibodies (immunoglobulins) in the blood circulation that react against Ri, ,an antineuronal antibody.

There are two commas separated just by space.

**Comment by pnrobinson** [comment]
fixed, thanks
