### ISSUE TITLE
Why both HP:0500149 and HP:0410068?

### ISSUE THREAD

**Issue by MickeySegal** [obophenotype/human-phenotype-ontology#9777]
**HPO term**
HP:0500149 and HP:0410068

**Reason for deprecation**
It seems like these are the same thing and should be combined.

**Suggested replacement or term to consider**

**Comment by pnrobinson** [comment]
I agree these terms are synonyms.

Hyperglutamatemia HP:0500149
Increased level of L-glutamic acid in blood HP:0410068

I've kept Hyperglutamatemia HP:0500149 as the primary term and merge the other term into it.
