### ISSUE TITLE
Acral keratosis

### ISSUE THREAD

**Issue by julievonz** [obophenotype/human-phenotype-ontology#978]
Request a new term for 'Acral keratoses' under Abnormalities of the skin

**Comment by drseb** [comment]
we need to annotated [cowden syndrome](https://en.wikipedia.org/wiki/Cowden_syndrome) with that term.

**Comment by drseb** [comment]
we do have acrokeratosis

@pnrobinson

**Comment by pnrobinson** [comment]
Added as a synonym to HP:0200016, acrokeratosis
