### ISSUE TITLE
Abnormality of the urethra (HP_0000795) should not be child of Abnormality of male external genitalia (HP_0000032)

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#9781]
**HPO term**
Abnormality of the urethra (HP_0000795) should not be child of Abnormality of male external genitalia (HP_0000032)

**Suggested revision and reasons**

Because urethra could be male or female, this is inappropriate placement. You could also argue that at least part of the male urethra is internal, but that might be splitting hairs.

Currently, it is also a child of Abnormality of the lower urinary tract, so I believe it should remain there. In addition, male urthral meatus stenosis (HP_0032077) should be child of urethral stenosis--but that might be taken care of after adding EQs as suggested in https://github.com/obophenotype/human-phenotype-ontology/issues/9762. 

This was based on a discussion with @sbello @anna-anagnostop

**Comment by pnrobinson** [comment]
fixed both errors, thanks!
