### ISSUE TITLE
question about source for Orphanet phenotype data in HPOA

### ISSUE THREAD

**Issue by Daniel-Olson** [obophenotype/human-phenotype-ontology#9788]
Critical Path Institute is currently working with Epilepsy data and would like to include disease-to-phenotype relationships in CPONT (C-path Ontology). We have noticed that some of the Orphanet and OMIM terms in HPO have different phenotypic profiles in the HPO annotation files. We would like to understand these differences. Is there source documentation for how the orphanet phenotypes were derived? 

Below is an example of phenotypes associated with the disease 'pyruvate dehydrogenase E2 deficiency' in OMIM and Orpahent, which have very little phenotype association overlap. We were just wondering where the orphanet phenotypes are derived from.

OMIM:245348 phenotypes = ['HP:0002465', 'HP:0002268', 'HP:0001256', 'HP:0001332', 'HP:0001252', 'HP:0001251', 'HP:0003593', 'HP:0001270', 'HP:0000639', 'HP:0000657', 'HP:0020045', 'HP:0007325', 'HP:0001348', 'HP:0001347', 'HP:0003128', 'HP:0000252', 'HP:0001266', 'HP:0011968', 'HP:0001263', 'HP:0002194', 'HP:0032988', 'HP:0002928', 'HP:0012043', 'HP:0000508', 'HP:0000007', 'HP:0001319', 'HP:0002307', 'HP:0006961']
ORPHA:79244 phenotypes = ['HP:0002355', 'HP:0012379', 'HP:0100503', 'HP:0500231', 'HP:0000496', 'HP:0000546', 'HP:0000707', 'HP:0000708', 'HP:0001260', 'HP:0001263', 'HP:0001276', 'HP:0001288', 'HP:0002136', 'HP:0002180', 'HP:0002268', 'HP:0002395', 'HP:0002454', 'HP:0003487', 'HP:0005656', 'HP:0010864', 'HP:0002454', 'HP:0025331', 'HP:0025335', 'HP:0031139', 'HP:0031936', 'HP:0031960', 'HP:0000252', 'HP:0000486', 'HP:0000726', 'HP:0000739', 'HP:0004302', 'HP:0007994', 'HP:0011098']   
 
Thank you!

**Comment by pnrobinson** [comment]
On the HPO website, the diseases labeled "ORPHANET" contain annotations that are ingested as is from the Orphanet resource. The diseases labeled OMIM are annotated either using text mining from the OMIM resource or by manual curation by the HPO team. Both resources are complementary. 
This is the best place to get documentation about Orphanet's resources: https://www.orphadata.com/
All such resources like this are an eternal work in progress and both teams welcome feedback -- happy to chat if anything is unclear.

**Comment by matentzn** [comment]
Very interesting question and answer. 

@pnrobinson 

1. does HPOA contain _all_ diseases in Orphanet and OMIM that are associated with phenotypes?
2. Do you have an explanation for the considerable divergence of OMIM and Orphanet in terms of phenotypes in the example provided by @Daniel-Olson above?

**Comment by pnrobinson** [comment]
The HPOAs contain all of the material from ORPHA. We are several months behind with OMIM but basically contain 99% of the material. One difference, though, is that OMIM keeps historical records that were created say in the 1990s but whose genetic or other etiology can no longer be tested (since the last patient contact was 30 years ago, no genetic association was found, and in most cases the clinical description is not specific enough to be used for certain diagnosis). The HPOAs do not include these entries.
