### ISSUE TITLE
Papillomatous papules

### ISSUE THREAD

**Issue by julievonz** [obophenotype/human-phenotype-ontology#979]
Request a new term for Papillomatous papules...phenotype observed as an Abnormality of the skin

**Comment by drseb** [comment]
superclass must be *Papule* HP:0200034

**Comment by pnrobinson** [comment]
A definition of papilloma is "a benign tumor of the skin or mucous membrane consisting of hypertrophied epithelial tissue, as a wart. "
Therefore, I think that "Papillomatous papule" is a synoynm of "Verrucous papule" (HP_0012500)
@julievonz do you agree? Should we add Papillomatous papule as a synonym or as the prefered term name?

**Comment by julievonz** [comment]
it is fine to add papillomatous papule as a synonym of verrucous papule.
