### ISSUE TITLE
Document release artefacts carefully

### ISSUE THREAD

**Issue by matentzn** [obophenotype/human-phenotype-ontology#9790]
@pnrobinson where can I find clear descriptions about the methodology for generating the following: 

- [genes_to_disease.txt](https://github.com/obophenotype/human-phenotype-ontology/releases/download/v2023-06-06/genes_to_disease.txt)
- [genes_to_phenotype.txt](https://github.com/obophenotype/human-phenotype-ontology/releases/download/v2023-06-06/genes_to_phenotype.txt)
- [phenotype.hpoa](https://github.com/obophenotype/human-phenotype-ontology/releases/download/v2023-06-06/phenotype.hpoa)
- [phenotype_to_genes.txt](https://github.com/obophenotype/human-phenotype-ontology/releases/download/v2023-06-06/phenotype_to_genes.txt)

If they dont exist, we should probably write 3 sentences about each for provenance!

**Comment by pnrobinson** [comment]
@iimpulse I am wondering if it would be good to add a section "For developers" to the "Resources" menu on the HPO home page where we document the API, the files, etc etc? I would think that a separate static HTML page for each of these things would be super useful for our users. What do you think @matentzn  -- I could take a first stab at writing the docs

**Comment by pnrobinson** [comment]
@matentzn 
these are explained in the new documentation:
http://obophenotype.github.io/human-phenotype-ontology/annotations/introduction/
