### ISSUE TITLE
HP:0030508 and HP:0011513 Retinal cavernous [hem]angioma

### ISSUE THREAD

**Issue by kanems** [obophenotype/human-phenotype-ontology#9795]
**HPO term**
Retinal cavernous hemangioma HP:0030508

**Reason for deprecation**
I'm not sure, but is this the same as Retinal cavernous angioma? UMLS maps these to the same CUI and NCI thesaurus ( code C4921) also says they are synonymous.

**Suggested replacement or term to consider**
Retinal cavernous angioma HP:0011513

**Comment by pnrobinson** [comment]
@kanems These are synonyms, thanks for pointing this out!
The following is the remaining term
HP:0011513
Retinal cavernous hemangioma

The other term was merged!
