### ISSUE TITLE
Oligozoospermia

### ISSUE THREAD

**Issue by MagoWyr** [obophenotype/human-phenotype-ontology#9797]
**HPO term**
HP:0000798

**Suggested revision of textual definition**
"Oligozoospermia" instead of "Oligospermia"
```[tasklist]
### Tasks
```

**Comment by pnrobinson** [comment]
@MagoWyr 
Aren't these two words synonyms? It seems Oligospermia is used much more frequently -- please provide a comment as to whether there is any distinction

**Comment by MagoWyr** [comment]
The correct term is "Oligozoospermia". "Oligospermia" is an alteration of the term frequently used by non-experts of the field. As a reference you can use the "WHO laboratory manual for the examination and processing of human semen", which is the gold standard in the field: https://www.who.int/publications/i/item/9789240030787
________________________________

**Comment by pnrobinson** [comment]
altered the primary label to Oligozoospermia
The HPO keeps all reasonable synonyms and used the "official" term as the label!
