### ISSUE TITLE
Epidermal nevi

### ISSUE THREAD

**Issue by julievonz** [obophenotype/human-phenotype-ontology#980]
Request a new term for Epidermal nevi...abnormality of the skin

**Comment by drseb** [comment]
this class already exists with ID HP_0003764 and label Nevus. I added a related synonym "Epidermal nevi"

**Comment by drseb** [comment]
There is even a class *Epidermal nevus*. I added the synonym there. 

May I ask what tool you are using to search through HPO?

**Comment by julievonz** [comment]
I am using the HPO browser online, however, I am submitting requests based on the clinicians suggestions. Appreciate your suggestions and alternatives..
