### ISSUE TITLE
Cryptozoospermia

### ISSUE THREAD

**Issue by MagoWyr** [obophenotype/human-phenotype-ontology#9802]
**HPO term**
HP:0030974

**Suggested revision of textual definition**
Definition: Detection of spermatozoa in an ejaculate only after centrifugation and inspection of the pellet.
Parent term: Extreme oligozoospermia
Synonymes: None (cryptospermia, as currently stated in the HPO is not an adequate synonyme for cryptozoospermia)

**Comment by pnrobinson** [comment]
The HPO synonym list is designed to help find things by text mining and "cryptospermia" is often used as a synonym, I think, e.g., "Cryptozoo[sperm](https://www.invitra.com/en/sperm-cell/)ia or cryptospermia is a severe alteration of sperm concentration and, therefore, a cause of male infertility." (https://www.invitra.com/en/cryptozoospermia/).

@MagoWyr 
Could you also provide a PMID for the definition or will this be from the paper that is to appear?

If we want to say to the community "No longer use cryptospermia" then we should add a comment saying why we think this and providing more background.

**Comment by MagoWyr** [comment]
"Cryptozoospermia" is the official term for this condition. "Cryptospermia" is probably an alteration of the term used by non-experts who are not familiar with the official terminology. As a reference you can use our soon to be published manuscript, but even better is the WHO laboratory manual for the examination and processing of human semen , which represents the gold standard for semen analysis and male infertility phenotypes:
https://www.who.int/publications/i/item/9789240030787
________________________________

**Comment by pnrobinson** [comment]
adapted the definition as suggested and altered the primary label to Cryptozoospermia
