### ISSUE TITLE
Early spermatogenesis maturation arrest (HP:0031039)

### ISSUE THREAD

**Issue by MagoWyr** [obophenotype/human-phenotype-ontology#9820]
**HPO term**
Early spermatogenesis maturation arrest (HP:0031039)

**Suggested revision of textual definition**
This term is ambiguous and should be replaced by "Spermatogonial arrest". The parent term should be the newly introduced term "Germ cell arrest", which summarises all forms of arrest.

**Comment by pnrobinson** [comment]
this was dealt with previously but we forgot to close the issue.
