### ISSUE TITLE
Spermatogenesis maturation arrest 

### ISSUE THREAD

**Issue by MagoWyr** [obophenotype/human-phenotype-ontology#9821]
**HPO term**
HP:0031038

**Suggested revision and reasons**
The parent term of this term should be the newly introduced term "Germ cell arrest" which summarises all forms of arrest.

**Comment by pnrobinson** [comment]
@MagoWyr 
There is no sense in making a new term that will have only this term as a child. I think that they are synonyms and that it would be better to revise the definition of [Spermatogenesis maturation arrest HP:0031038
](https://hpo.jax.org/app/browse/term/HP:0031038) if something is unclear. The latter term is supposed to group all kinds of male germ cell arrest.

**Comment by MagoWyr** [comment]
I understand your concern, but Round spermatid arrest does not fall under Spermatogenesis maturation arrest. It would be correctly labelled at Spermiogenesis arrest. Also the word "maturation" is misleading because some people use it as a synonym for meiotic arrest, which would not cover Spermatogonial and Round spermatid arrest. Therefore, we suggest using the term Germ cell arrest. This is a broader term, covering all three arrest forms, so there would be three different child terms as visualised in our figure:
[cid:cc847eda-f2ad-489c-9712-7e035a6155b7]
________________________________

**Comment by pnrobinson** [comment]
added/finalized per discussion
