### ISSUE TITLE
Late spermatogenesis maturation arrest 

### ISSUE THREAD

**Issue by MagoWyr** [obophenotype/human-phenotype-ontology#9823]
**HPO term**
HP:0031040

**Suggested revision of textual definition**
This term is not correct, because it is currently defined as "A type of maturation arrest in which spermatids are detected without spermatozoa". However, if spermatids are present the correct labelling would be spermiogenesis arrest instead of spermatogenesis arrest. Late spermatogenesis maturation arrest would strictly speaking label an arrest during a late stage of meiosis.  
We propose to use the term "Round spermatid arrest" because it is less ambiguous. The parent term should be the newly introduced term "Germ cell arrest" which summarises all forms of arrest.

**Comment by pnrobinson** [comment]
@MagoWyr 
not sure I understand. 
What would the correct definition of Late spermatogenesis maturation arrest be?
What is the definition for Round spermatid arrest?

**Comment by MagoWyr** [comment]
We think that the term Late spermatogenesis arrest is not a commonly used one and it's also unspecific, so there is no clear definition and everybody might understand something different from this term. So this term should not be used.

We propose the parent term Germ cell arrest and the sub-term Round spermatid arrest. The definition of Round spermatid arrest is that testicular histology shows spermatogonia, spermatocytes and round spermatids, but no cells behind round spermatid stage, so there are no elongating spermatids.
________________________________

**Comment by pnrobinson** [comment]
We have one annotation to this term and I agree we can revise the title/definition or merge it.
My understanding is that the final step of spermatogenesis did not occur (Spermiogenesis is the final stage of spermatogenesis, during which the spermatids develop into mature spermatozoa).

I do not see the concept of "Round spermatid" in places like this  https://en.wikipedia.org/wiki/Spermiogenesis

therefore if we are going to use this term, we really need a detailed definition with PMIDs etc.

**Comment by MagoWyr** [comment]
I think the expression Round spermatid arrest describes much more a phenotype than the term Late spermatogenesis maturation arrest, because the latter describes more of a mechanism than a phenotype. Round spermatid arrest is a quite obvious observation in testicular histology, when you find round spermatids, but elongating spermatids. It is a commonly used term for the phenotype: e.g. PMID: 36150389, PMID: 16887924, PMID: 9510006, PMID: 31267012
________________________________

**Comment by pnrobinson** [comment]
@MagoWyr 
How about this
We will rename the term Late spermatogenesis maturation arrest to Round spermatid maturation arrest with the definition: A failure of spermatogenesis to progress beyond the round spermatid stage.  Round spermatids are the The round spermatid is the first haploid cells produced during spermatogenesis and normally further develop into mature spermatozoa. This abnormality can be visualized with testicular biopsy and is characterized seminiferous tubules with increased numbers of round spermatids with few or no mature spermatozoa.
Comment: See Figure 2c and 2d of PMID: 9510006

**Comment by pnrobinson** [comment]
@kanems 
thanks for pointing out this error.

@MagoWyr 

I will rename the term (Late spermatogenesis maturation arrest) to be:

Round spermatid arrest
HP:0031040
def: A failure of spermatogenesis to progress beyond the round spermatid stage. The round spermatid is the first haploid cells produced during spermatogenesis and normally further develop into mature spermatozoa. This abnormality can be visualized with testicular biopsy and is characterized seminiferous tubules with increased numbers of round spermatids with few or no mature spermatozoa.
Comment: See Figure 2c and 2d of PMID: 9510006
