### ISSUE TITLE
Abnormal sperm morphology 

### ISSUE THREAD

**Issue by MagoWyr** [obophenotype/human-phenotype-ontology#9830]
**HPO term**
HP:0012864

**Suggested revision and reasons**
The parent term should be the newly introduced term "Abnormal sperm structure" which summarises the two term "Abnormal sperm motility" and "Abnormal sperm morphology".

**Comment by pnrobinson** [comment]
Morphology is Greek for structure. In the hierarchy of the HPO, structure and function are coded in separate subhierarchies. I have just added an Abnormal sperm physiology term and motility is under that.

**Comment by MagoWyr** [comment]
Okay, I am fine with this.
________________________________
