### ISSUE TITLE
Gonadal dysgenesis

### ISSUE THREAD

**Issue by MagoWyr** [obophenotype/human-phenotype-ontology#9843]
**HPO term**
HP:0000133

**Suggested revision and reasons**
Currently the parent term is "Abnormal internal genitalia (HP:0000812)". However gonadal dysgenesis often shows a broader phenotype than just abnormalities of the internal genitalia. Hypospadias for example can be the result of a mild gonadal dysgenesis. 
Gonadal dysgenesis should be under the parent term "Decreased male fertility (HP:0012041)"

**Comment by pnrobinson** [comment]
@MagoWyr I would say that if we regard gonadal dysgenesis as a disease, then it can be associated with non-gonadal manifestations, but in the context of the HPO it is limited to the gonadal phenotype. I think we have discussed this and this issue remained open for some reason. If necessary, please email me to discuss further.
