### ISSUE TITLE
Hypergonadotropic hypogonadism 

### ISSUE THREAD

**Issue by MagoWyr** [obophenotype/human-phenotype-ontology#9844]
**HPO term**
HP:0000815

**Suggested revision and reasons**
This term should be under the parent term "Decreased fertility in males (HP:0012041)" as infertility is a common issue in these patients.

**Comment by pnrobinson** [comment]
This is similar to https://github.com/obophenotype/human-phenotype-ontology/issues/9843, that the HPO terms describe only the phenotypic manifestations and not associations or path-mechanism. Please email me if there is need to further discuss!
