### ISSUE TITLE
HP:5200026 present as ID and alt ID

### ISSUE THREAD

**Issue by sbello** [obophenotype/human-phenotype-ontology#9854]
**HPO term**

**Bug description**
The HPO vocab load at MGI failed last night. 
The first error in the MGI discrepancy report appears to point to the problem:

http://prodwww.informatics.jax.org/data/loads/mgi/vocload/runTimeHPO/discrepancy.html (internal but I can send the full report if you want)

David found term HP:5200026 in the input file and noticed that it also has HP:5200026 as an alt ID.
See the term below. After removing the alt ID and the load ran fine. This also clears up all the
other errors in the discrepancy report.

Would someone please remove the alt ID in the edit file.

[Term]
id: HP:5200026
name: Abnormal social imitation
alt_id: HP:5200026
alt_id: HP:5200032
def: "A reduced ability to imitate a task or the movements of others." [PMID:18221343]
comment: The ability to imitate others is common in children during early cognitive development (4-5 years old) and can be abnormal in children with autism.
synonym: "Deferred imitation of others" NARROW []
synonym: "Reduced immediate imitation of others" NARROW []
is_a: HP:0012760 ! Reduced social reciprocity
property_value: http://purl.org/dc/terms/contributor https://orcid.org/0000-0001-9112-5148
property_value: http://purl.org/dc/terms/contributor https://orcid.org/0000-0002-4142-7153
property_value: http://purl.org/dc/terms/contributor https://orcid.org/0000-0002-6670-9157
property_value: http://purl.org/dc/terms/contributor https://orcid.org/0000-0002-9593-5508

**Comment by LCCarmody** [comment]
@matentzn What should be done to fix this? I was following the HP wiki, but clearly that is not the way...

**Comment by LCCarmody** [comment]
No, I'm not sure, I took @sbello word.  Not sure the way forward.

**Comment by matentzn** [comment]
I made a PR:

https://github.com/obophenotype/human-phenotype-ontology/pull/9858

I dont know how this happened, but it must have been a typo during some obsoletion in during the last release.. In any case, nothing wild (unless the goal was to deprecate HP:5200026)!
