### ISSUE TITLE
Missing term in hp.owl

### ISSUE THREAD

**Issue by alix-simon** [obophenotype/human-phenotype-ontology#9878]
**HPO term**
HP:0031105

**Bug description**
Hello,

I am using SPARQL querying to link HPO terms to tissue categories. To do this I downloaded the hp.owl file from the HPO website and I use it to create a SPARQL endpoint with Apache Jena Fuseki.

When I tried to extract all HPO terms that are subclasses of "Abnormal uterus morphology" (HP:0031105)  I got no results even though there should be several according to the website. The query below also returned no results, so the term seems to be completely missing from the ontology file. 

```
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>

SELECT DISTINCT ?hpo_id ?label ?class_id ?class_label WHERE {
  VALUES ?hpo_id {"HP:0031105"^^xsd:string}
  ?term oboInOwl:id ?hpo_id .
}
```

As a result, all its exclusive subclasses are "orphaned". When I run the following query for term HP:0030126, a subclass of term HP:0031105, I get no results, even though it should at least be linked as a subclass of "All". Running the same query for a term that is not a exclusively child of term HP:0031105 works as expected.

```
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>
PREFIX obo: <http://purl.obolibrary.org/obo/>

SELECT DISTINCT ?hpo_id ?label ?class_id ?class_label WHERE {
  VALUES ?hpo_id {"HP:0030126"^^xsd:string}
  ?term oboInOwl:id ?hpo_id ;
        rdfs:label ?label ;
        rdfs:subClassOf+ ?class .
  ?class oboInOwl:id ?class_id;
         rdfs:label ?class_label .
}
```

Do you know why this term seems to be absent from the hp.owl file ?

Thanks in advance,
Alix

**Comment by pnrobinson** [comment]
I think you may need to write the term as HP_0031105 for OWL. Could you check this?

**Comment by alix-simon** [comment]
It doesn't work either. I set the value of the <http://www.geneontology.org/formats/oboInOwl#id> object, which follows the format "HP:0031105".  The following query using another HPO term works perfectly, so I don't think it's a format issue:

```
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>

SELECT DISTINCT ?hpo_id ?term WHERE {
  VALUES ?hpo_id {"HP:0009127"^^xsd:string}
  ?term oboInOwl:id ?hpo_id .
}
```

I'm really only encountering this issue with the term HP:0031105, the other 30 terms that I am using are working as expected.

**Comment by pnrobinson** [comment]
@alix-simon 
sorry for the late reply.
I have looked in the hp-edit.owl file and the term definitely is there.
 grep 0031105 hp-edit.owl
Declaration(Class(<http://purl.obolibrary.org/obo/HP_0031105>))
# Class: <http://purl.obolibrary.org/obo/HP_0031105> (Abnormal uterus morphology)
(...)

This might be ab issue with the SPARQL implementation you are using but it is not a problem with the OWL file as far as I can see. Feel free to contact me via email if you would like some assistance troubleshooting.
