### ISSUE TITLE
Typos in disease names in phenotype.hpoa

### ISSUE THREAD

**Issue by Jane2010** [obophenotype/human-phenotype-ontology#9879]
**Bug description**
In the 2023-06-17 release. there are typos in disease_name in the phenotype.hpoa file. Typos are quoted:

OMIM:619103, neurodevelopmental disorder "wtih" dysmorphic facies, sleep disturbance, and brain abnormalities

OMIM:255995	myopathy, congenital, "Baily"-Bloch

OMIM615181	muscular dystrophy-dystroglycanopathy (congenital with brain and eye anomalies"here missing a closing parenthesis", type A, 11

OMIM611812	46,XX sex reversal with dysgenesis of kidney"here missing s", adrenals, and lungs

OMIM278850	46"here missing comma"XX sex reversal 2

OMIM614868	t-cell immunodeficiency, recurrent infections, and autoimmunity with"here missing a space"or without cardiac malformations

OMIM136570	chromosome 16p12.1 deletion syndrome, 520-kb(here missing a space)fragile site 16p12, included

OMIM115000	ventricular  "arrythmias" due to cardiac ryanodine receptor calcium release deficiency syndrome

OMIM618952	combined oxidative phosphorylation "defiency" 46	

There are also some disease names that seem to have been generated by concatenating several names together, but without proper delimiter:
OMIM241800	hypothalamic hamartomascongenital hypothalamic hamartoma syndrome, included

OMIM164500	spinocerebellar ataxia 7 opca III opca with retinal degeneration opca with macular degeneration and external ophthalmoplegia autosomal dominant cerebellar ataxia, type II adca, type II

OMIM200500	acheiropody acheiropodia acheiropody, Brazilian type

OMIM125370	dentatorubral-Pallidoluysian atrophy naito-oyanagi disease haw river syndrome ataxia, chorea, seizures, and dementia

OMIM182980	spinal muscular atrophy, proximal, adult, autosomal dominantspinal muscular atrophy, late-onset, finkel type, included

**Comment by pnrobinson** [comment]
Thanks for pointing these out! I am making a checklist to keep track of the corrections.
- [ ] OMIM:619103
- [ ] OMIM:255995 
- [ ] OMIM615181 
- [ ] OMIM611812 
- [ ] OMIM278850 
- [ ] OMIM614868 
- [ ] OMIM136570 
- [ ]  OMIM115000 
- [ ] OMIM618952 
- [ ] OMIM241800
- [ ] OMIM164500 
- [ ] OMIM200500 
- [ ] OMIM125370 
- [ ] OMIM182980

**Comment by pnrobinson** [comment]
@Jane2010 thanks for pointing out these errors. I have fixed or updated all of these labels. They will become visible with the next HPO release in August.
