### ISSUE TITLE
Update term name

### ISSUE THREAD

**Issue by angharadroberts** [obophenotype/human-phenotype-ontology#9880]
Inheritance modifier HP:0034335 is a very useful group of terms to describe a group of HPO terms intended for use in conjunction with other inheritance terms to modify the Inheritance ontology. However the name creates potential for confusion with disease modifiers and the concept of a modifier in a genetic mechanism sense.  

We propose changing the name of the term to 'Inheritance Qualifier' to avoid confusion.

**Comment by pnrobinson** [comment]
@angharadroberts  done
