### ISSUE TITLE
15 years old not represented by any HPO onset terms

### ISSUE THREAD

**Issue by vferretti** [obophenotype/human-phenotype-ontology#9882]
**HPO term**
HP:0410280 and HP:0003581

**Suggested revision and reasons**
According to the current definition of the two terms above, the age of 15 years falls through the cracks in the onsets classification

HP:0003581 : Onset of disease manifestations in adulthood, defined here as at the age of 16 years or later.
HP:0410280 : Onset of disease manifestations before adulthood, defined here as before the age of 15 years, but excluding neonatal or congenital onset.

**Comment by pnrobinson** [comment]
Thanks for pointing this out. I corrected to

HP:0410280 : Onset of disease manifestations before adulthood, defined here as before the age of 16 years, but excluding neonatal or congenital onset.
