### ISSUE TITLE
Make a list of all Github contributors (issues and issue comments)

### ISSUE THREAD

**Issue by matentzn** [obophenotype/human-phenotype-ontology#9890]
We need a list of all GitHub contributors that made more than X comments since January 2021. X can initially be five. Issues I guess count as comments, right, so the metric should be "comments". Ideally, the resulting table has the github handle and the associated name.

@cthoyt we are getting into paper mode - do you have code to put a table like this together?

**Comment by cthoyt** [comment]
No, I haven't done something like this. FYI I'm out of contact until July 17 (or whatever that Monday is$

**Comment by matentzn** [comment]
Enjoy holidays I got this!

**Comment by matentzn** [comment]
@pnrobinson I made a list of all contributions here:

https://docs.google.com/spreadsheets/d/1A-7WBaX91ZNM9puQ10w8R5s63E4zz1EJJZBIdrXXQSs/edit#gid=1612632891

Using @gouttegd awesome https://github.com/gouttegd/grainyhead tool.

Let me know if you need anything else from me on this (maybe chasing down the GitHub users is something that someone in your team can do, after you selected the lucky contributors from that list to include).

**Comment by matentzn** [comment]
This has been processed for the HPO paper!
