### ISSUE TITLE
weird inferrence

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9893]
![image](https://github.com/obophenotype/human-phenotype-ontology/assets/4943420/11f9729d-f3a6-4b75-b31d-ad3642dae95c)

Although anus is part of ..part of digestive system (https://www.ebi.ac.uk/ols4/ontologies/uberon/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_0001245)

@matentzn I am pushing the hp-edit file with this error, no idea how to fix it...

**Comment by matentzn** [comment]
Just a small typo: https://github.com/obophenotype/human-phenotype-ontology/pull/9894
