### ISSUE TITLE
phenotypes_to_genes.txt contains hpo with 0/ frequencies (absent)

### ISSUE THREAD

**Issue by jvreeuwijk** [obophenotype/human-phenotype-ontology#9898]
Hello,

I use the phenotype_to_genes.txt file to annotate and extract (variants in) genes with a certain phenotype (and including the more specific related phenotypes).

I noticed that the latest (June 2023) phenotypes_to_genes.txt file contains HPO which have a frequency of 0/ (absent) in the genes_to_phenotype.txt file. I assume the phenotypes_to_genes.txt should not include phenotypes with a 0/ frequency or include frequency data?

Example for ANTXR2:
phenotype_to_genes.txt: HP:0001249      Intellectual disability 118429  ANTXR2  OMIM:228600
genes_to_phenotype.txt: 118429  ANTXR2  HP:0001249      Intellectual disability 0/30    OMIM:228600

Thank you for this great resource. 

Best regards, Jeroen
Radboudumc, Nijmegen, The Netherlands

**Comment by pnrobinson** [comment]
For differential diagnosis, it can be important to know that affected individuals do not have the phenotypic feature in question (or that there is a low frequency). This is a relatively new resource on the HPO website and we need to better document this file -- I will try to do so before the next release.
