### ISSUE TITLE
Pruritus caused by medication

### ISSUE THREAD

**Issue by julievonz** [obophenotype/human-phenotype-ontology#990]
Request a new term for 'Pruritus caused by medication'

**Comment by pnrobinson** [comment]
The HPO intends to describe phenotypes, not diseases and not etiologies (there are some inconsistencies in the current version of the HPO in this respect that we are trying to correct). The HPO can easily be combined with other terminologies or ontologies to extend its expressivity. For instance, you could use the current HPO term for pruritus and combine it with the name of any of the very many entries in PubChem (the alternative of adding one HPO term for each possible medication would make the HPO so big that it would be difficult to use for other purposes!). If you are planning to capture data in this sphere and would like to speak with the HPO/Monarch team about how to structure data models, please contact me by email at peter.robinson@jax.org
The same (or an analogous) comment applies to several recent requests, and I will refer to this comment.
