### ISSUE TITLE
Difference between "phenotype_to_genes.txt" and "genes_to_phenotypes.txt"

### ISSUE THREAD

**Issue by JoKPro** [obophenotype/human-phenotype-ontology#9903]
Hi, 

why are the dimensions of http://purl.obolibrary.org/obo/hp/hpoa/genes_to_phenotype.txt and http://purl.obolibrary.org/obo/hp/hpoa/phenotype_to_genes.txt not the same?

The average number of genes associated to an hpo term is much higher in the latter file than in the former ( 74.41 vs. 24.93).

Would be great if someone could explain the difference.

Many thanks in advance

**Comment by pnrobinson** [comment]
Please see the FAQs on the HPO webpage

A question that is asked very often, deals with the asymmetry of the files:

genes_to_phenotypes.txt
phenotype_to_genes.txt
The difference is that one file uses the transitivity of the annotations and the other does not. I.e. in genes_to_phenotypes.txt we list for each gene the most specific HPO-classes (and not all the ancestors). In phenotype_to_genes.txt we show each phenotype that has at least one gene associated with it. Additionally, we have mapped genes to the ancestor classes of each associated phenotype. For example given that:

HP_1 subclass_of HP_3
HP_1 subclass_of HP_3
then genes_to_phenotypes.txt

geneA annotated to HP_1
geneB annotated to HP_2
then phenotype_to_genes.txt contains:

HP_3 annotates geneA and geneB


We are going to be expanfing the documentation @iimpulse
