### ISSUE TITLE
GATA1 linked to all HPO terms of Down syndrome

### ISSUE THREAD

**Issue by PatrickDeelen** [obophenotype/human-phenotype-ontology#9904]
**All Down syndrome terms**

**Bug description**

GATA1 is mentioned on the OMIM page of Down syndrome: https://omim.org/entry/190685?search=GATA1, however this is about leukemia's in Down syndrome. This gene should not be linked the other HPO terms used to describe Down syndrome.

**Comment by pnrobinson** [comment]
Thanks, Patrick, for pointing this out. I agree with your assessment. We will investigate our data pipeline and try to understand where this is coming from. @matentzn @iimpulse

**Comment by matentzn** [comment]
@iimpulse, let me know how I can help troubleshooting!

**Comment by pnrobinson** [comment]
@PatrickDeelen -- sorry for the very late reply - 2023 was the year I relocated back to Germany. 
Coming back to this, GATA1 is not linked to Down in the HPO website
https://hpo.jax.org/app/browse/gene/2623
https://hpo.jax.org/app/browse/disease/OMIM:190685
I am not sure I understand the bug.

**Comment by PatrickDeelen** [comment]
@pnrobinson, no problem.

It seems the problem is indeed fixed. But for clarity:

The genes_to_phenotype.txt file I downloaded on 17-6-2023 contained the following line:

`2623	GATA1	HP:0001252	Hypotonia	400/524	OMIM:190685`

Linking the hypotonia that is associated to down syndrome to the GATA1 gene. 

This is no longer the case. 

Thank you and your team.

**Comment by pnrobinson** [comment]
Super, thanks for reporting this error -- it is super helpful for us to be able to fix things, I guess it worked this time by chance :-0!
