### ISSUE TITLE
missing columns in recent phenotype_to_genes.txt file?

### ISSUE THREAD

**Issue by newgene** [obophenotype/human-phenotype-ontology#9905]
Looks like from early this year, the released `phenotype_to_genes.txt` file misses some columns compared to the older releases.

The latest release (2023.06) misses two columns of "Additional Info from G-D source" and "G-D source" compared to the release (2022.12).

Just want to confirm if these two columns are intentionally removed, or will be brought back in future releases.

In the [2023.06 release note](https://hpo.jax.org/app/news/June%202022), it did say:
>Our phenotype_to_genes and genes_to_phenotype have recieved feedback from our previous release and we have brought old columns back. 

Maybe it meant different columns.

**Comment by pnrobinson** [comment]
@newgene 
sorry for the late reply. We have reworked the pipelines for these files. This is the current documentation:
http://obophenotype.github.io/human-phenotype-ontology/annotations/introduction/
This will be the format moving forward.
if something is amiss with the current version, please let me know.
