### ISSUE TITLE
Arrhinencephaly

### ISSUE THREAD

**Issue by sbello** [obophenotype/human-phenotype-ontology#9918]
**HPO term**
Arrhinencephaly (HP:0002139)
term currently lacks a definition
**Suggested revision of textual definition**
A defect of development of the brain characterized by congenital absence of the part of the brain that includes the olfactory bulbs, tracts, and other structures associated with the sense of smell
https://dictionary.apa.org/arrhinencephaly
ORPHA:268936

Given that this can be isolated, with other parts of the brain present, I would suggest changing the parent from Anencephaly (HP:0002323) to Abnormal forebrain morphology (HP:0100547) basing this on the placement of the term olfactory pathway in UBERON http://purl.obolibrary.org/obo/UBERON_0013201 I believe this is the correct reference since the definition from APA refers to this as absence of the rhinencephalon and UBERON has rhinencephalon as a synonym for olfactory pathway.

**Comment by pnrobinson** [comment]
Thanks, @sbello, I agree with your assessment and have revised the parentage acccordingly and added the definition.
