### ISSUE TITLE
Inappropriate use of capitalization in HPO terms (excluding first word)

### ISSUE THREAD

**Issue by cmungall** [obophenotype/human-phenotype-ontology#992]
See https://github.com/cmungall/capital-offence/issues/1 for background

HPO capitalizes the first word (which is not OBO-compliant, but we ignore this for now)

However, there are some cases where HPO capitalizes words that are not the leading word, and these are *not* proper names. These should be fixed.

Low priority unless @drseb feels otherwise

## Membrane

 * [HP:0012039](http://purl.obolibrary.org/obo/HP_0012039) ! Descemet  __Membrane__  Folds

## Factor

 * [HP:0030131](http://purl.obolibrary.org/obo/HP_0030131) ! Abnormal von Willebrand  __Factor__  multimer distribution
 * [HP:0030133](http://purl.obolibrary.org/obo/HP_0030133) ! Abnormal presence of ultra-large von Willebrand  __Factor__  multimers
 * [HP:0030134](http://purl.obolibrary.org/obo/HP_0030134) ! Total absence von Willebrand  __Factor__  multimers
 * [HP:0040225](http://purl.obolibrary.org/obo/HP_0040225) ! Decrease in High molecular weight von Willebrand  __Factor__  Multimers [SYNONYM: "Decrease in HMW VWF multimers" (exact)]

## Positive

 * [HP:0030007](http://purl.obolibrary.org/obo/HP_0030007) ! EMG:  __Positive__  sharp waves

(I suggest coming up with a naming convention for these that spells out acronyms and doesn't use colons)

## High

 * [HP:0040225](http://purl.obolibrary.org/obo/HP_0040225) ! Decrease in  __High__  molecular weight von Willebrand Factor Multimers [SYNONYM: "Decrease in HMW VWF multimers" (exact)]

## Cataract

 * [HP:0010693](http://purl.obolibrary.org/obo/HP_0010693) ! Pulverulent  __Cataract__ 

# Latinized

Some of these it could be argued that capitalizing all terms is proper, but I would disagree:

 * [HP:0012653](http://purl.obolibrary.org/obo/HP_0012653) ! Status  __Asthmaticus__  [SYNONYM: "Acute severe asthma" (exact)]

## Narrow

 * [HP:0000446](http://purl.obolibrary.org/obo/HP_0000446) !  __Narrow__  nasal bridge [SYNONYM: " __Narrow__  bridge of nose" (exact)] [SYNONYM: " __Narrow__  nasal root" (exact)] [SYNONYM: "Nasal Bridge,  __Narrow__ " (exact)] [SYNONYM: "Nasal bridge, thin" (exact)] [SYNONYM: "Pinched bridge of nose" (related)] [SYNONYM: "Pinched nasal bridge" (related)]
 * [HP:0011829](http://purl.obolibrary.org/obo/HP_0011829) !  __Narrow__  philtrum [SYNONYM: "Decreased breadth of philtrum" (exact)] [SYNONYM: "Decreased horizontal dimension of philtrum" (exact)] [SYNONYM: "Decreased transverse dimension of philtrum" (exact)] [SYNONYM: "Decreased width of philtrum" (exact)] [SYNONYM: "Philtrum,  __Narrow__ " (exact)] [SYNONYM: "Thin philtrum" (exact)]

## Ear

 * [HP:0030022](http://purl.obolibrary.org/obo/HP_0030022) ! Question mark ear [SYNONYM: "Constricted  __Ear__ " (exact)] [SYNONYM: "Cosman  __Ear__ " (exact)] [SYNONYM: "Question mark ears" (exact)]

## Hemorrhage

 * [HP:0011887](http://purl.obolibrary.org/obo/HP_0011887) ! Choroid hemorrhage [SYNONYM: "Choroidal  __Hemorrhage__ " (exact)]

## Raphe, Midline

 * [HP:0011826](http://purl.obolibrary.org/obo/HP_0011826) ! Philtrum with midline raphe [SYNONYM: "Philtrum with central raphe" (exact)] [SYNONYM: "Philtrum with midline ridge" (exact)] [SYNONYM: "Philtrum, __Midline__  __Raphe__ " (exact)]

# Other notes

## Eustachian

HP is unique amongst ontologies in capitalizing Eustachian. This is technically arguably correct as it's proper https://en.wikipedia.org/wiki/Bartolomeo_Eustachi 

But it seems to be common to not capitalize this

## Slashes

It seems to be standard in HPO to capitalize the first N words, if these words are separated by a `/`, eg Atrophy/ __Degeneration__

Hence I do not report these here

**Comment by pnrobinson** [comment]
I learned Eustachian with a capital E, but usage does seem to vary. I will leave as is for now but do not have a strong opinion. For the most part, the slash terms have suboptimal names and we may want to revisit them. Otherwise I have implemented all suggestions.
