### ISSUE TITLE
Term Dysgiria also associated with ACTA2 variants

### ISSUE THREAD

**Issue by ivalenzuela84** [obophenotype/human-phenotype-ontology#9927]
**OMIM (# 613834) - MULTISYSTEMIC SMOOTH MUSCLE DYSFUNCTION SYNDROME; MSMDS**

**Dysgyria HP:0032398**

**Dysgiria is also observed in ACTA2 patients- ACTA2-Related Dysgyria: An Under-Recognized Malformation of Cortical Development ([10.3174/ajnr.A7364](https://doi.org/10.3174/ajnr.a7364)). This gene should be included in the list linked to the dysgyria HPO**

**Comment by pnrobinson** [comment]
@ivalenzuela84 
thanks for this contribution, I have added it to the annotations and it will appear with our next release in March.
