### ISSUE TITLE
Hyperosthenuria should mention elevated urine osmolality

### ISSUE THREAD

**Issue by MickeySegal** [obophenotype/human-phenotype-ontology#9929]
**HPO term**
https://hpo.jax.org/app/browse/term/HP:0033359

**Synonym to be added**
elevated urine osmolality
elevated urine osmolarity

Tthe parent term is Abnormal urine osmolality HP:0033358 so this seems appropriate.  Such a synonym strategy was done in the opposite term https://hpo.jax.org/app/browse/term/HP:0003158 

**broad/exact/narrow/plural/abbreviation ?**

**Comment by pnrobinson** [comment]
added, thanks!
