### ISSUE TITLE
Better undestanding of the files diseases_to_genes_to_phenotypes.txt x phenotype_to_genes

### ISSUE THREAD

**Issue by marcelcaraciolo** [obophenotype/human-phenotype-ontology#993]
Hello guys,

I would like to better undestand the differences between the number of genes in those two files:

[1] http://compbio.charite.de/jenkins/job/hpo.annotations.monthly/lastSuccessfulBuild/artifact/annotation/ALL_SOURCES_ALL_FREQUENCIES_diseases_to_genes_to_phenotypes.txt

and

[2] http://compbio.charite.de/jenkins/job/hpo.annotations.monthly/lastSuccessfulBuild/artifact/annotation/ALL_SOURCES_ALL_FREQUENCIES_phenotype_to_genes.txt

We picked one HPO term, for instance  HP:0011922 (Abnormal activity of mitochondrial respiratory chain) and comparing the two files the [2] had 19 different genes and the [1] were given only one.

We would like to understand the difference between the two files. We know that one is using relationship  phenotype <-> genes and the other disease <-> phenotype  <-> gene.   We were thinking that the [1] would give all the genes in [2] since we add one more step in the hierarchy (diseases).  Is is possible to clarify the differences between both ?

Thanks guys,

Regards,

**Comment by drseb** [comment]
Sorry for the delay. I think you should have look at http://human-phenotype-ontology.github.io/faq.html

Re-open if you still have questions.

Seb
