### ISSUE TITLE
"Neoplasm by anatomical site" shouldn't be the parent of "Abnormality of the digestive system"

### ISSUE THREAD

**Issue by birkanozer** [obophenotype/human-phenotype-ontology#9938]
**HPO term**
[Term]
id: HP:0034930
name: Digestive system neoplasm
def: "A tumor (abnormal growth of tissue) of the digestive system." []
**is_a: HP:0025031 ! Abnormality of the digestive system**
property_value: http://purl.org/dc/elements/1.1/date "2023-07-09T14:37:49Z" xsd:dateTime
property_value: http://purl.org/dc/terms/creator https://orcid.org/0000-0002-0736-9199

[Term]
id: HP:0025031
name: Abnormality of the digestive system
comment: Any anomaly of the digestive system, a collection of organs that is made up of the gastrointestinal tract and the liver, pancreas, and gallbladder. The gastrointestinal tract is a series of hollow organs joined in a long, twisting tube from the mouth to the anus, including the mouth, esophagus, stomach, small intestine, large intestine and anus.
**is_a: HP:0011793 ! Neoplasm by anatomical site**
property_value: http://purl.org/dc/elements/1.1/date "2016-08-27T13:44:32Z" xsd:dateTime
property_value: http://purl.org/dc/terms/creator https://orcid.org/0000-0002-0736-9199

**Bug description**
On the July 2023 version, a new HPO term of "Digestive system neoplasm" added to the ontology. The immediate parent of this HPO term is "Abnormality of the digestive system". As you can see on above the immediate parent of the "Abnormality of the digestive system" is "Neoplasm by anatomical site". If we follow the tree to the leaf nodes of the "Abnormality of the digestive system", we find this section below:

Abnormality of the digestive system
    Abnormality of digestive system physiology
        Abdominal symptom
            Abnormal bowel sounds
            Nausea and vomiting
            Constipation
            Abdominal pain
            Protein avoidance
            Diarrhea
            ...

Since **"Neoplasm by anatomical site"** is the sole parent of the **"Abnormality of the digestive system"**, all the terms in the tree above are listed as a subset of **"Neoplasm"**. Sure, we can see this symptoms in neoplasms, but the neoplasms are neither most common nor only reason of this symptoms. I think, "Digestive system neoplasm" should have 2 parents, "Abnormality of the digestive system" and "Neoplasm by anatomical site", and the relations of the "Abnormality of the digestive system" should revert back the June 2023 version of the ontology.

**Comment by LCCarmody** [comment]
Hi, I noticed this too...but checking out the HP-edit file and OLS, it appears to be fixed. Could you check if this is still an issue for you?

**Comment by birkanozer** [comment]
Yes it looks like the problem has been fixed.

**Comment by LCCarmody** [comment]
Great! Thanks for reporting. Closing.
