### ISSUE TITLE
HP:0034858 Abnormal leukocyte enzyme concentration or activity

### ISSUE THREAD

**Issue by grahamponting** [obophenotype/human-phenotype-ontology#9939]
**HPO term**
HP:0034858 Abnormal leukocyte enzyme concentration or activity.
The current definition of this concept, and it's children are based on "Concentration or activity of an enzyme as measured in leukocytes is above or below the limits of normal in the blood circulation."

This statement seems to be contradictory, is the value measured within white cells or in the blood circulation ?

**Suggested revision of textual definition**
The definition should be revised accordingly, I suggest by removing the words "in the blood circulation" if appropriate

Graham Ponting

**Comment by pnrobinson** [comment]
@grahamponting thanks for pointing this out, I agree and have made the suggested change.
