### ISSUE TITLE
HMG-CoA synthase-2 deficiency should be associated with Metabolic acidosis 

### ISSUE THREAD

**Issue by gou-kachi** [obophenotype/human-phenotype-ontology#9954]
**Disease ID and Name**
OMIM:605911 HMG-CoA synthase-2 deficiency
ORPHA:35701 3-hydroxy-3-methylglutaryl-CoA synthase deficiency 

**HPO ID and Name**
HP:0001942 Metabolic acidosis 
HP:0004911 Episodic metabolic acidosis
HP:0001987 Hyperammonemia
HP:0001298 Encephalopathy 
HP:0002919 Ketonuria
HP:0003215 Dicarboxylic aciduria
HP:0004372 Reduced consciousness/confusion

**Further information (Frequency, Onset, Pubmed-references, Comments)**
Most likely to present with metabolic acidosis but not including in the HPO of Metabolic acidosis yet.
PMID: 33045405
PMID: 35308163

**Comment by pnrobinson** [comment]
Thanks for pointing this out. I have added more detailed curation
https://github.com/monarch-initiative/phenopacket-store/blob/main/notebooks/HMGCS2/HMGCS2_individuals.ipynb
this will be on the main HPO website in a few weeks.
