### ISSUE TITLE
Early spermatogenesis maturation arrest 

### ISSUE THREAD

**Issue by MagoWyr** [obophenotype/human-phenotype-ontology#9957]
**HPO term**
HP:0031039

**Reason for deprecation**
This term is unclear. It it not clear whether Spermatogonial arrest is meant or Spermatocyte arrest. 

**Suggested replacement or term to consider**
Two terms should be created: Spermatogonial arrest and Spermatocyte arrest

**Comment by pnrobinson** [comment]
this has been implemented.
