### ISSUE TITLE
remove: Disharmonious carpal bone HP:0006153

### ISSUE THREAD

**Issue by azankl** [obophenotype/human-phenotype-ontology#9971]
**HPO term**
Disharmonious carpal bone HP:0006153

**Reason for deprecation**
Disharmonious carpal bones do not exist. Authors probably meant disharmonious carpal bone *ossification*. In fact, I checked OMIM:608154, the only disorder annotated with this term, and Rajab et al 2003, the only reference listed there, and Rajab refers to "Patient 3, 7 years old. The carpal bone age is 4 years old, whereas the epiphyseal bone age is slightly advanced." So this is actually better described as 'Dysharmonic bone age HP:0200000'.

**Suggested replacement or term to consider**
delete this term from HPO and add 'Dysharmonic bone age HP:0200000' as an annotation to OMIM 608154 instead

My Orcid ID:
0000-0001-8612-1062

**Comment by pnrobinson** [comment]
@azankl 
thanks for pointing this out. 
Since the phenotype is poorly described in the original publication and there is only one annotation, I obsoleted the term (merged with Abnormality of carpal bone ossification).
