### ISSUE TITLE
rename  Dysharmonic bone age HP:0005832 to Dysharmonic skeletal maturation

### ISSUE THREAD

**Issue by azankl** [obophenotype/human-phenotype-ontology#9972]
**HPO term**
Dysharmonic bone age HP:0005832

**Suggested revision and reasons**
This 'Abnormality of skeletal maturation' branch currently looks like this:

Abnormality of skeletal maturation HP:0000927
- Delayed skeletal maturation HP:0002750 (synonym: delayed bone age)
- Dysharmonic bone age HP:0005832 (synonym: dysharmonic skeletal maturation)
- Accelerated skeletal maturation HP:0005616 (synonym: advanced bone age)

Would rename Dysharmonic bone age HP:0005832 to Dysharmonic skeletal maturation, to bring it in line with its siblings (and make Dysharmonic bone age a synonym).

My Orcid ID
0000-0001-8612-1062

**Comment by LCCarmody** [comment]
@pnrobinson If you agree, I will change Dysharmonic bone age to exact synonym and change the label.

**Comment by pnrobinson** [comment]
@azankl 
agreed, thanks! Changed label
