### ISSUE TITLE
add 'dysharmonic bone age' to Dysharmonic maturation of the hand bones HP:0004053

### ISSUE THREAD

**Issue by azankl** [obophenotype/human-phenotype-ontology#9973]
**HPO term**
Dysharmonic maturation of the hand bones HP:0004053

**Synonym to be added**
dysharmonic bone age

**broad/exact/narrow/plural/abbreviation ?**
exact

My Orcid ID
0000-0001-8612-1062

**Comment by pnrobinson** [comment]
Thanks @azankl I added a second parent, [Dysharmonic bone age HP:0200000](https://hpo.jax.org/app/browse/term/HP:0200000)
