### ISSUE TITLE
abnormality of redox activity

### ISSUE THREAD

**Issue by slaulederkind** [obophenotype/human-phenotype-ontology#998]
I would like to see "abnormality of redox activity" added to the HP ontology under the parent term “Abnormality of cell physiology” (HP:0011017).  The definition could be "An abnormality of the processes that maintain the redox environment of a cell or compartment within a cell".  

As a child of "abnormality of redox activity" I’d like to see “oxidative stress”.  The definition could be “An accumulation of free radical groups in the body inadequately neutralized by antioxidants, which creates a potentially unstable and damaging cellular environment linked to tissue damage.” Related synonyms could be “increased ROS production” and “increased reactive oxygen species production”.  
An example can be found in PMID:26950655.

**Comment by pnrobinson** [comment]
Sorry for the delay.
I am thinking the HPO needs to have a major sublevel term "Abnormal cellular phenotype", and this would go well there (in analogy to the MPO, who have done a great job working this out).

**Comment by pnrobinson** [comment]
Sorry for the delay, just adding these terms. I used Increased reactive oxygen species production as the primary label. (HP_0025464)
