### ISSUE TITLE
Proctalgia

### ISSUE THREAD

**Issue by carolina-f** [obophenotype/human-phenotype-ontology#9980]
**HPO term**
Anal pain HP:0500005

**Synonym to be added**
Proctalgia
Anorectal pain

**broad/exact/narrow/plural/abbreviation ?**
Chapter 36 - Anorectal pain  https://doi.org/10.1016/B978-0-12-813037-7.00036-4
Definition

Chronic proctalgia is a general term used to define a chronic or recurring pain in the [anal canal](https://www.sciencedirect.com/topics/medicine-and-dentistry/anal-canal) or rectum [9]. Other names considered synonymous with chronic proctalgia are levator ani syndrome, puborectalis syndrome, chronic idiopathic [perineal pain](https://www.sciencedirect.com/topics/medicine-and-dentistry/perineal-pain), pyriformis syndrome, and pelvic tension [myalgia](https://www.sciencedirect.com/topics/medicine-and-dentistry/myalgia) [9].

**Comment by pnrobinson** [comment]
added - thanks!
